### ISSUE TITLE
Intelligent auto-regeneration

### ISSUE THREAD

**Issue by postmodern** [jekyll/jekyll#1012]
Currently Jekyll regenerates the _entire_ site, if only one file is changed. This makes working on large jekyll sites very slow (ex: [www.ruby-lang.org](https://github.com/ruby/www.ruby-lang.org)). Instead, jekyll should have intelligent auto-regeneration:
1. If a page is changed, only regenerate that page.
2. If a layout is changed, all pages that use that layout (or layouts that use that layout) should be regenerated.
3. If an include is changed, regenerate the entire site.
4. If `_config.yml` is changed, reload `_config.yml` and regenerate the entire site.
5. If a plugin in `_plugins/` is changed, regenerate the entire site.

**Comment by XiZepu** [comment]
hello,I have a question,when i use  `jekyll serve`  to build my blog, jekyll run sooooo slow,the message is here:    
 Regenerating: 1 file(s) changed at 2015-05-15 11:47:14 ...done in 618.4004
88 seconds.
      Regenerating: 1 file(s) changed at 2015-05-15 11:57:32 ...done in 615.2696
53 seconds.

my platform is win8 32bit

**Comment by envygeeks** [comment]
@XiZepu what is your Jekyll version? Have you tried it from master which currently has that?

**Comment by XiZepu** [comment]
Dear Jordon,

taday afternoon， I update  jekyll 3.0.0 pre beta,but it still so  slow,here
is my building message:

$ jekyll serve
Configuration file: e:/Github/xizepu.github.io/_config.yml
            Source: e:/Github/xizepu.github.io
       Destination: e:/Github/xizepu.github.io/_site
 Incremental build: enabled
      Generating...
                    done in 658.385 seconds.
 Auto-regeneration: enabled for 'e:/Github/xizepu.github.io'
Configuration file: e:/Github/xizepu.github.io/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.


yes! it spend 658.358 seconds.



——席泽璞(Xi Zepu)
       於蓉城成都理工大学(CDUT)

**Comment by parkr** [comment]
@XiZepu Do you have any custom plugins? How big is your site?

**Comment by envygeeks** [comment]
Yeah I have the same question because that's an insane number like running on hardware from the 90's type of number, my mind broke when I saw that number.

**Comment by XiZepu** [comment]
no  custom plugins， about 10 blog。

but now ，when I use jekyll， it run good，i don not change any things.

message:

$ jekyll serve
Configuration file: e:/Github/xizepu.github.io/_config.yml
            Source: e:/Github/xizepu.github.io
       Destination: e:/Github/xizepu.github.io/_site
 Incremental build: enabled
      Generating...
                    done in 0.146 seconds.
 Auto-regeneration: enabled for 'e:/Github/xizepu.github.io'
Configuration file: e:/Github/xizepu.github.io/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2015-05-15 18:29:32 ...done in
1.223826
 seconds.
      Regenerating: 1 file(s) changed at 2015-05-15 20:23:51 ...done in
1.519123
 seconds.
      Regenerating: 1 file(s) changed at 2015-05-15 20:24:02 ...done in
0.193129
 seconds.


but in morning and noon , i was confused by jekyll. thank you.

i just update jekyll version from 2.4 to 3.0.it solved.


——席泽璞(Xi Zepu)
       於蓉城成都理工大学(CDUT)

**Comment by envygeeks** [comment]
Is the source for your site open so I can test it?

**Comment by XiZepu** [comment]
it is HERE, feel free to test :+1: 

https://github.com/XiZepu/xizepu.github.io.git

**Comment by XiZepu** [comment]
I think it is a possible that in China the Firewall make the question. in any case, now i can use jekyll comfortable, but i don't find what is the key about the question i meet in morning.
