### ISSUE TITLE
Suggestion: Read metadata in separate files.

### ISSUE THREAD

**Issue by sequitur** [jekyll/jekyll#1082]
Hakyll currently reads metadata from separate files, i.e. a file called `foo.md` would be stapled to the YAML front matter of `foo.md.metadata` in the same directory.

Having this in Jekyll would be helpful both for projects building their content in more formats than one (E.g., HTML via Jekyll and PDF via Pandoc). It also makes it possible to attach metadata to non-text files, which may or may not be useful at present, but would be helpful for future features or plugins.

**Comment by Ajedi32** [comment]
:+1: for this. Unless I'm misunderstanding here, it's currently impossible to use standard markdown-formatted files with Jekyll and have them render properly (same for other file formats too). Unless you include weird, Jekyll-specific metadata at the top of all your files, Jekyll refuses to process them. That's kind of a deal breaker for me at the moment.

**Comment by micapam** [comment]
Me too, @Ajedi32. I'm going to use nanoc for now, but I'd rather use Jekyll if possible as there seems to be wider community support etc. So I'll watch this thread.

My thoughts on the 'simplicity' comments above: there is more than one kind of simplicity. I like Markdown because it's minimal, and system-agnostic. Simple for the user != simple for the system.

**Comment by parkr** [comment]
Are any of you using a plugin for this? What does it look like? I think we'll ship Jekyll 3 without this and revisit later. I have not heard anything for a while so it's becoming lower priority.

**Comment by Ajedi32** [comment]
A plugin would be great. Personally, my interest has shifted to [Metalsmith](http://www.metalsmith.io/) though so I don't really have the motivation to write one myself at the moment (especially given that I'm not very familiar with Jekyll or its plugin system).

If there is a plugin which implements this functionality though I'd certainly love to hear about it.

**Comment by micapam** [comment]
@parkr Beware self-selection bias. You not be hearing much about it because those people for whom it's a deal-breaker are going elsewhere. I considered Jekyll but decided on nanoc for this very reason.

**Comment by jooize** [comment]
I'm using [Hardwired](https://github.com/nathanaeljones/hardwired) much because of its support for omitting the YAML “---” and allowing capital letters in the front matter tags “Layout: legal-page”.

**Comment by envygeeks** [comment]
The latter part is a bit over the top to ask for IMO, those are keys that are meant for Jekyll and to have to lowercase them just because you want to uppercase them when we expected them to be lowercase is a step backwards in performance one that grows along with other issues as the site grows.  Those aren't problems that most people are concerned with but simply put: it's a configuration option.

**Comment by karelv** [comment]
:+1: to the original suggestion (and keeping the front matter as is, and thus madatory)

**Comment by karelv** [comment]
Made a generator plugin. Probably not 100% optimized or correct, but it does do what I need. (new on ruby and jekyll)

```ruby
module ReadMetaFiles
  class Generator < Jekyll::Generator
    def generate(site)

      site.posts.docs.each do |doc|
      	meta_file = (doc.path + ".yml")
      	if File.exist?(meta_file)
      		meta_data = SafeYAML.load_file(meta_file)
      		meta_data.each { |key, value| doc.data[key] = value}
        end
      end

      site.pages.docs.each do |doc|
      	meta_file = (doc.path + ".yml")
      	if File.exist?(meta_file)
      		meta_data = SafeYAML.load_file(meta_file)
      		meta_data.each { |key, value| doc.data[key] = value}
        end
      end

    end
  end
end
```

So place this rb-file in your `_plugins` directory. Now each post and page will try to load an additional *Front Matter* in the yml file name afer the post(or page) file-name with an extra `.yml` suffix.

Anyone an idea of the caveats?
