### ISSUE TITLE
Question - Destination directory cannot be or contain the Source directory.

### ISSUE THREAD

**Issue by Serhioromano** [jekyll/jekyll#1092]
My idea is to have github repository where root is the site root or to say `_site` root. But inside I have Jekyll older with sources or let's call it `source`.

Why? For example Windows Azure have automatik deploy process via GitHub. Not only Azure other service sas well. But repository root have to be site root. If it is in `_site` folder then it is not accessible by default. Or let's say I deploy to AWS S3 bucket. It does not matter but with how it works currently I have to have 3 repos. One is source and second is site. But I want site in root and in source jekyll.

**Comment by corysimmons** [comment]
@parkr What's the preferred method for having src in gh-pages and deploying it to the root of gh-pages? Or do I have to put my src in a separate repo and setup some deploy hook?

**Comment by parkr** [comment]
@corysimmons I don't understand your situation, sadly! Could you please elaborate?

**Comment by corysimmons** [comment]
@parkr Sorry, I wanted to have a `./src` folder with the entire site in it, and build to `./`.

I ran into an error where I couldn't output to a parent directory. I was wondering if this has been brought up before, and if there was an official solution? Seems like it'd clean up my project structure a bit.
