### ISSUE TITLE
Page not valid: duplicate use of ID

### ISSUE THREAD

**Issue by To1ne** [jekyll/jekyll#110]
I love just Jekyll and use it for my blog now.

But I have a problem the pages are not W3c valid: see [output](http://validator.w3.org/check?uri=http%3A%2F%2Fwritepermission.com).

So because some `<h1>` tags have the same value, the `id` attribute will reoccur.

I don't get why the `id` is set to the `<h1>` value anyhow?

**Comment by lengerfulluse** [comment]
Sorry for reopening this thread.
@mojombo I add the following to `_config.yml ` file to generate table of content.

    markdown: rdiscount
    rdiscount:
        extensions:
          - generate_toc

Unfortunately, **it still generates the same header id**, please refer the following screenshot:  
<img width="421" alt="screen shot 2015-07-27 at 5 30 30 pm" src="https://cloud.githubusercontent.com/assets/1578404/8921375/3bd39704-3507-11e5-84a6-7f414bc8a715.png">
Any idea? Thanks in advance!
