### ISSUE TITLE
Better Converter Feedback

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#1105]
Swear this is a duplicate ticket, but can't seem to find it. Converter exceptions are ugly. And this ugliness can be especially intimidating for usings not normally used to command line or Ruby error reporting. Would be awesome if we could give error messages a bit of love. A few suggestions:
- [x] Output the path to the file it's currently processing ( **huge help in large sites** )
- [x] Don't display the backtrace unless I use the `--trace` flag. Makes it really hard to see what actually matters
- [ ] ~~If one file fails, keep running other files, give me all the errors at once instead of making me rebuild~~
- [ ] ~~Links to help text (e.g., markdown, liquid, etc.)~~
- [x] Just in general, write error messages for humans

**Comment by purp** [comment]
Meanwhile, I added PR #3665 to enable just what @parkr asked for in [his comment on Jun 11, 2013](https://github.com/jekyll/jekyll/issues/1105#issuecomment-19256871).
