### ISSUE TITLE
Automatically add categories to posts based on their subdirectory within _posts

### ISSUE THREAD

**Issue by bdesham** [jekyll/jekyll#1141]
It would be great if putting a post in (for example) `_posts/news/` could automatically add `news` to that post's list of categories. In the default situation, where the permalink structure starts with `:categories`, this would make the generated URLs correspond somewhat to the position of the Markdown files on disk, which I think is often desirable.

My particular use case is that I want to have a Daring Fireball&ndash;style &ldquo;linked list&rdquo; blog consisting of the usual articles, along with shorter items that are mostly just links to other sites with a little bit of my commentary. I can keep these link posts in `_posts/links` to organize my site more easily. I can also set `category: links` on these posts so that their permalinks look like `/links/2013/05/something` instead of &ldquo;normal&rdquo; posts, whose permalinks look like `/2013/05/something`. It would be terrific if Jekyll could automatically infer the category from the on-disk organization so that I don&rsquo;t have to manually set `category: links` on each link post.

**Comment by danijar** [comment]
Would you be open to allowing `_posts/category/` as well? I would like to have quite a few categories. But there are also other top-level folders, for example holding statically hosted files. So it becomes confusing which directories is are categories and which are not.
