### ISSUE TITLE
The prerequisite to have file name of posts starting with a date is not so nice...

### ISSUE THREAD

**Issue by emiliano-poggi** [jekyll/jekyll#120]
...is there a way to provide the post date using something different from the filename? For example, jekyll could read the post date from the YAML frontmatter.

Thanks
Emi

**Comment by HoBi** [comment]
You can use `_drafts` folder. Drafts are posts w/o date in a file name and they are originally intended as posts you don’t want to publish yet.

But you can build Jekyll with it using `jekyll build --drafts` or `jekyll serve --drafts`.

http://jekyllrb.com/docs/drafts/

**Comment by envygeeks** [comment]
This ticket is being locked. If you have an issue please file a new ticket instead of practicing the art of necromancy. It has hard to maintain act…
