### ISSUE TITLE
With `server` deprecated, how can I reliably tell if I'm in Dev or Prod mode?

### ISSUE THREAD

**Issue by philipwalton** [jekyll/jekyll#1219]
Before the release of version 1, I could check if `site.server` was `true` and then include development only features (or exclude production only features) based on that conditional.

Here's a simple example:

```
{% if site.server %}
  {% include local-testing-scripts.html %}
{% endif %}
```

But now it seems that I have no way to reliably do this check (unless I'm missing something).

The only thing I can think of is to set some random config variable (like `port`), and then make the assumption that I'm in dev mode unless `port` is set to whatever number I choose to mean production mode.

But that seems hacky. Is there an officially supported way to do what I'm after?

**Comment by WickyNilliams** [comment]
@parkr sorry to dig up an old issue, but i'm wondering if you know whether `{{ jekyll.environment }}` is set to `"production"` on github pages?

**Comment by parkr** [comment]
@WickyNilliams Yes.
