### ISSUE TITLE
Permalinks Not Working

### ISSUE THREAD

**Issue by adamfairhead** [jekyll/jekyll#1233]
Hi chaps. Not sure when this started happening, but for some reason my permalinks have gone screwy.

_config.yml states:
permalink:   /:categories/:title/

_site reveals:
_site/blog/fc-webicons-set-launched/index.html

But the live URL appears as:
http://fairheadcreative.com/blog/2012/06/14/fc-webicons-set-launched.html

What I'm expecting (and wanting):
http://fairheadcreative.com/blog/fc-webicons-set-launched/

It's hosted with Github Pages, using jekyll 1.0.3 (just updated from 1.0.2 to see it if it helped resolve the problem, but no such luck)

**Comment by victusfate** [comment]
I have a similar issue, but the trailing slash on github breaks permalinks, but locally works fine. Quick fix?
