### ISSUE TITLE
Jekyll+Redcarpet - auto add IDs to headings?

### ISSUE THREAD

**Issue by nottrobin** [jekyll/jekyll#1249]
Is there a way with Redcarpet and Jekyll to automatically add IDs to headings?

```
<h1 id="my-heading">My heading</h1>
```

I've tried googling lots and lots but haven't found any answer.

**Comment by lengerfulluse** [comment]
Sorry for reopen this thread.
Hi @maul-esel 
I have a similar question for using rdiscount to generate toc: I configure rdiscount with:  

    markdown: rdiscount
    rdiscount:
        extensions:
            - generate_toc
And rdiscount auto add id for headers. But, unfortunately it generates the **same** id for all headers, which makes all the toc items point to the same anchor. Do you have some ideas about it? Thanks in advance!

**Comment by maul-esel** [comment]
no idea sorry :disappointed:

**Comment by parkr** [comment]
@lengerfulluse Please bring that up with the Rdiscount folks: https://github.com/davidfstr/rdiscount/issues

**Comment by lengerfulluse** [comment]
Thanks @parkr, I just submit a new issue: https://github.com/davidfstr/rdiscount/issues/129. Will keep this thread close.
