### ISSUE TITLE
Forbidden Error

### ISSUE THREAD

**Issue by railsfactory-aruns** [jekyll/jekyll#1293]
When I am trying to start "jekyll server". After that I refresh the page i'm getting "no access permission" error.

ERROR no access permission to `/'
localhost - - [10/Jul/2013:12:29:28 IST] "GET / HTTP/1.1" 403 283

Please help me out.

**Comment by tomjohnson1492** [comment]
I had this error. It turns out that in my _config.yml file, I had an empty line in my excludes property, like this:

```
excludes:
- _site
- _drafts
- 
```
