### ISSUE TITLE
Markdownify includes

### ISSUE THREAD

**Issue by maletor** [jekyll/jekyll#1303]
Is it intended that when you add `{% include a_markdown_file.md %}` from within an HTML page, that it doesn't markdownify the include? The documentation seems to include that it should.

http://jekyllrb.com/docs/templates/#includes

**Comment by daveas** [comment]
:+1:

**Comment by clarklab** [comment]
:+1:

Is there a way to include a post, formatted with markdown, inside another post? I've got a recipe build going where recipes (posts) are made up of small components (also posts).

The capture thing works inside a page, when the .md file is inside /_includes, bust that's pretty dang narrow. Any way to include a post in a post?

**Comment by daveas** [comment]
Yes, I don't know how you could include a specific post but I'm sure it's possible, perhaps not in safe mode. But you can include your most recent post simply with:



{% for post in site.posts limit:1 %}

{{ post.content }}

{% endfor %}







You can use whatever liquid you want for the title and such. Change 'content' to 'excerpt' for less body text. Then you can control the length as well.









On Tuesday, May 12, 2015 at 11:28 PM, Clark Wimberly <notifications@github.com>, wrote:


 Is there a way to include a post, formatted with markdown, inside another post? I've got a recipe build going where recipes (posts) are made up of small components (also posts).
 The capture thing works inside a page, when the .md file is inside /_includes, bust that's pretty dang narrow. Any way to include a post in a post?

**Comment by clarklab** [comment]
@daveas thanks for the tip, but that's not really what I'm after. Aside from the fact that it won't render from inside a post, I still need a way to call up specific posts (or sets of posts).

**Comment by daveas** [comment]
Sorry, can't help you there. There might be a way to do it by giving each post a unique identifier in the yaml front matter and referencing that post's content by that ID. I can't hack it together for you right now and there might be a cleaner solution. Just thought I'd share the idea. Good luck! Let us know if you get it!







On Wednesday, May 13, 2015 at 12:35 PM, Clark Wimberly <notifications@github.com>, wrote:

@daveas thanks for the tip, but that's not really what I'm after. Aside from the fact that it won't render from inside a post, I still need a way to call up specific posts (or sets of posts).

**Comment by ckreon** [comment]
Are we still stuck on this?

**Comment by pickfire** [comment]
@ckreon I think Jekyll isn't "*Just Works™*" anymore now.

**Comment by michaelboyles** [comment]
Just started using Jekyll for the first time and I also thought it was strange that includes don't automatically support markdown. I'd be happy for this just to be made explicit in the documentation. I shouldn't have to search through GitHub issues.

**Comment by hosnas** [comment]
Shouldn't we be waiting for this feature at all?

**Comment by pzp1997** [comment]
This issue has been unresolved for over five years now. Can't we do something about it at the framework level?

**Comment by jonaprieto** [comment]
How to include just the content of the file? I'm getting also the header information like layout, title and that...

**Comment by reedcornish** [comment]
I solved this by renaming the html files to have a ".md" extension. Jekyll still renders the html.

**Comment by Simran-B** [comment]
`{% include path/to/file.md %}` does render Markdown for me in Jekyll 4.0.0 without the capture workaround, but it includes the frontmatter indeed. That and the broken link mechanic are the final nails on Jekyll's coffin for me. Will move to another tool where basic things don't require ugly hacks.

**Comment by 7yl4r** [comment]
Why is this issue closed but not resolved? The suggested workaround is too kludgy a way to accomplish something that should be enabled by default.

**Comment by radkoff** [comment]
Like @jonaprieto, I was struggling to get the capture/include hack working due to front matter. My solution was to split the front matter from the included page content.

As an example, lets say you have `_pages/mypage.md`:

```
---
layout: page
permalink: /mypage/
title: My Page
---
This is *my page* in markdown
```

But you also want to include this on your homepage. Create `_pages/mypage_content.md` like so:
```
This is *my page* in markdown
```

Change `_pages/mypage.md` to this:
```
---
layout: page
permalink: /mypage/
title: My Page
---
{% capture my_include %}{% include_relative mypage_content.md %}{% endcapture %}
{{ my_include | markdownify }}
```

And similarly, add a capture/include somewhere on your homepage:
```
{% capture my_include %}{% include_relative _pages/mypage_content.md %}{% endcapture %}
{{ my_include | markdownify }}
```

Page variables will work as expected, so you can customize `mypage_content.md` depending on where it is included. I've tested this in Jekyll 4.1.1

**Comment by jackybourgeois** [comment]
For me, this hack did not work because I need the information from the front matter (maybe I did not understand @radkoff 's hack). However, it looks like if there is a liquid tag to process in the page to include, it removes the front matter. For instance, if I put the following at the bottom of all my page to include, I do not have front matters once rendered.

```markdown
[]({{site.baseurl}}{{page.url}})
```

This typically creates an invisible link to the current page.
