### ISSUE TITLE
Jekyll command not found

### ISSUE THREAD

**Issue by ghost** [jekyll/jekyll#1309]
In spite of an apparently good installation, following Jekyll's own guide, I repeatedly encounter the following error messages: 

$ sudo gem install jekyll
Successfully installed jekyll-1.1.0
Parsing documentation for jekyll-1.1.0
1 gem installed
$ jekyll
-bash: jekyll: command not found 

I have installed Command Line Tools, but don't know where to go next…
thnx

**Comment by naren8642** [comment]
I am also using rbenv and parkr's suggestion worked. But, why? I know this is really an rbenv question, but I don't think rbenv docs will give me the explanation for why this needed to be done in this context. TIA!
