### ISSUE TITLE
*.md does not generate *.index in _site folder

### ISSUE THREAD

**Issue by luoyunan** [jekyll/jekyll#1324]
I wanted to create a new page, so I crated a new folder named "test" with a "index.md" in it. However, when I run "jekyll serve", it did not generate index.html in _site folder. Also, I got "no access permission to `/test/'" when I entered "localhost:4000/test/"

 I searched on the web, and found may be "jekyll --no-auto --server" can solve it, but this command has been deprecated. Then what should I do?

**Comment by Eflores89** [comment]
I'm having the same issue. 

I have the following setup: 
`_config.yml`
`css`
`images`
`_posts`
`    - 2015-10-10-post.md`
`    - etc.....`
`_layouts`
`_site`
`_bibliography`
`_plugins`
`APV`
`    - index.md`
`EEM `
`    - index.md`

When I `jekyll build` or `jekyll serve` all posts work perfectly, as well as when going to `siteur/APV/` which means jekyll is building a proper `index.html` from that .md file. 

However, this is not the case for `siteurl/EEM/`... 

When I look into the `_site` folder, I see no .html file being created. 

The file has the following opening structure, which looks like proper YAML to me and is **the same** as the working `APV/index.md`: 

---

title: "Metodologias"
date: "2015-01-01"
featured_image: /images/proyectos/seguros_ap_header.jpg
output: pdf_document
layout: science
custom_css: science

---

# Historia


**En El Margen** nace en el 2011 como un espacio de reflexión y difusión entre alumnos de la carrera de Economía del Tec de Monterrey en forma de un proyecto de la dirección de la SALEC (Sociedad de Alumnos de Licenciados en Economía). Como colaboradores iniciales se cuenta a *Fernando Ramones, Eduardo Flores, Agustín Gomez y Jaime Ávila*.

etc...
`
What am I missing? Is jekyll only searching for max 2 index.md? 

The github repo is this [here](https://github.com/Eflores89/Eflores89.github.io), but it is only the site built, as a I build locally and only serve the `_site`.

**Comment by Eflores89** [comment]
Never mind! I see the issue: 

`output: pdf_document`

Sorry about this.
