### ISSUE TITLE
How to get url querystring param when using jekyll

### ISSUE THREAD

**Issue by luckydrq** [jekyll/jekyll#1334]
Hi, 
     A few days ago i asked a question about ' tags ' which stands for the type of articles of my Github Pages. It is solved and thanks a lot! Now i have another problem which is also related to ' tags' and here is the scene: 
     Every article of my blog has tags such as `'js'`,  or more words like `'js ajax'`. These tags are anchors which is linked to a page  when clicked. For example, if the tag of `'js'` is clicked , then it will navigate to a page which lists all the articles containing the tag `'js'` (including articles with `'js ajax'`). So, my problem is i can't get the tag 
param using jekyll. The thing i considered should go like below: 

```
    {% for post in site.posts %}
        {% if(post.pagetag == xxx ) %}
           //do output staff
        {% endif%}
    {% endfor %}
```

Actually it is only a filter. But how does jekyll recognize 'xxx' and how i should post the param to jekyll?? I've tried using HTTP GET by making url like `/filterPage?tag=js` but failed.  Thank you!

**Comment by danielsiwiec** [comment]
A bit late in the game, but I came up with a different solution for this. See [this commit](https://github.com/danielsiwiec/danielsiwiec.github.io/commit/cf04dd322f5ffe2251ca6e3733d2707c2eaec7d4).

In the gist, the tags page contains a list with all the posts hidden and then, dynamically using JavaScript, un-hides the posts that have the requested tag.

Hope it helps!
