### ISSUE TITLE
Markdown is not rendering line spacing/block quotes properly

### ISSUE THREAD

**Issue by DanielPollitt** [jekyll/jekyll#1368]
Update: I've had to add line breaks (br) because it is not parsing the blank lines. This works, but should not have to do this, right?

Anyone else having these issues?

I have looked at every single issue thread, close and open, in this forum. Cannot find an answer nor fix for the issue I'm having of markdown not rendering properly. 

Thanks,
Dan

http://github.com/DanielPollitt/The-Follow-Through/tree/gh-pages

**Comment by lastingman** [comment]
> blockquotes is not working
