### ISSUE TITLE
Liquid Exception: tag was never closed

### ISSUE THREAD

**Issue by bdesham** [jekyll/jekyll#1380]
I’ve written a simple plugin to implement a “preview” block on Jekyll’s posts. The idea is that part of a post is wrapped in `{% preview %}`…`{% endpreview %}`, and this text will be made available via `post.data['preview']`. The plugin code is as follows:

```
module Jekyll

  class Preview < Liquid::Block

    def render(context)
      # Get the current post's post object
      id = context['page']['id']
      posts = context.registers[:site].posts
      post = posts [posts.index {|post| post.id == id}]

      # Put the block contents into the post's preview field,
      # and also return those contents
      post.data['preview'] = super
    end

  end

end

Liquid::Template.register_tag('preview', Jekyll::Preview)
```

I created a new Jekyll site with nothing but this plugin (in `_plugins/preview.rb`) and the following in `_posts/2013-08-05-test.md`:

```

---
title: This is a test
date: 2013-08-05T12:22:12-04:00

---

{% preview %}

This text is within the preview.

{% endpreview %}

This text is not.
```

Running `jekyll build` from the root directory of this minimal site, I get:

```
Configuration file: /Users/bdesham/Sites/bdesham.info/_config.yml
            Source: /Users/bdesham/Sites/bdesham.info
       Destination: /Users/bdesham/Sites/bdesham.info/_site
      Generating...   Liquid Exception: preview tag was never closed in 2011-06-10-building-and-hosting-a-static-site.md
error: preview tag was never closed. Use --trace to view backtrace
Command failed: jekyll build
```

Am I doing something wrong, or is there a bug in Jekyll and/or in Liquid?

**Edit:** I get this error in Jekyll 1.1.1 and 1.1.2 but not in Jekyll 1.0.3.

**Comment by paynito** [comment]
Yes, add to the top of your blogpost.md excerpt_separator:  up in the YAML section with the title and the date.
