### ISSUE TITLE
China : gem install jekyll do not work

### ISSUE THREAD

**Issue by zheolong** [jekyll/jekyll#1409]
I am a Chinese student, when I first run `gem install jekyll` in my computer, it show that

``` bash
ERROR:  Could not find a valid gem 'jekyll' (>= 0) in any repository
ERROR:  Possible alternatives: jekyll` 
```

I tried a lot of ways and finally find the solution:

``` bash
$ gem sources --remove http://rubygems.org/
$ gem sources -a http://ruby.taobao.org/
$ gem sources -l
*** CURRENT SOURCES ***
http://ruby.taobao.org    
$ gem install rack 
```

Then, run `gem install jekyll` and it will work.

**Comment by hexiaoyuhaha** [comment]
It works !!! 
Thank you so much, I'm also a Chinese student

**Comment by HeroWit** [comment]
Thank you very much,it works!
F**k GFW!!!!!!!

**Comment by HeroWit** [comment]
Thank you very much,it works!
F**k GFW!!!!!!!,I'm a Chinese too....

**Comment by Chinquan** [comment]
Thx a lot. **It works fine.**

**Comment by cheng470** [comment]
Thank you very much

**Comment by ouyangyewei** [comment]
Thanks a lot !

**Comment by envygeeks** [comment]
This ticket is being locked, there is no need to send a thank you if something helps you, all it does is waste Github bandwidth by having them send dozens of emails and ping @jekyll/core.
