### ISSUE TITLE
error `/' not found

### ISSUE THREAD

**Issue by petroleumjelliffe** [jekyll/jekyll#1432]
I set up two separate jekyll blogs, the first one I set up works just fine.  But the second gives me this error after I try to access localhost:4000.

```
[2013-08-18 13:03:04] ERROR `/' not found.
localhost - - [18/Aug/2013:13:03:04 EDT] "GET / HTTP/1.1" 404 270
- -> /
```

Do I need to do anything special to have two blogs run side by side?

**Comment by naffan2014** [comment]
danman01 is right
