### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by themediaforge** [jekyll/jekyll#1460]
user$ sudo jekyll build
Configuration file: none
            Source: /Users/user
       Destination: /Users/user/_site
      Generating... error: No such file or directory - /Users/user/Documents/Parallels/Windows XP.pvm/Windows Disks/C. Use --trace to view backtrace

**Comment by aitorgrande** [comment]
i have the same problem :(

**Comment by envygeeks** [comment]
@albertogg do as requested and post more details and we'll repopen it if it's a Jekyll problem.

**Comment by aitorgrande** [comment]
i uninstalled and reinstalled jekyll and fixed the problem !!
