### ISSUE TITLE
Pages that live in subdirectories don't apply layouts?

### ISSUE THREAD

**Issue by petroleumjelliffe** [jekyll/jekyll#1461]
I created an HTML file, called it /patterns.html and it worked fine.  It's YAML front matter specified a layout I stored in /_layouts and it was applied.

I saved the files as /patterns/index.html (to get the nicer URL as described on http://jekyllrb.com/docs/pages/) and the layout was no longer applied.

Is this on purpose?  Do Pages only support layouts if they're in the root directory?

**Comment by rvkennedy** [comment]
I had the same problem - turns out that in my layout I had relative paths to the stylesheets, like this:

    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css"/>

-which is correct relative to the root, but wrong for subfolders. The fix was to use absolute paths:

    <link rel="stylesheet" type="text/css" href="/stylesheets/stylesheet.css"/>

**Comment by kleinfreund** [comment]
> `<link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css"/>`

… is not relative to the root. That's relative to the file.

**Comment by rvkennedy** [comment]
> … is not relative to the root. That's relative to the file.

It is correct relative to the root when the file is in the root, *but wrong for subfolders*...

**Comment by troyswanson** [comment]
@rvkennedy Thanks for chiming in with a potential fix!

**Comment by jrovegno** [comment]
@rvkennedy Thanks. In a github project page I have to use
`<link rel="stylesheet" href="{{ site.baseurl }}/stylesheets/core.css" media="screen">`
Works ok.
