### ISSUE TITLE
Small but very useful tip on using jekyll on macosx when you use hoembrew

### ISSUE THREAD

**Issue by jmfayard** [jekyll/jekyll#1504]
Hello,

in case you don't know yet (you should is you use macosx ;-), [Homebrew is the missing package manager for macosx](http://brew.sh/)

if you installed ruby with brew, jekyll won't work out of the box

so here is a small tip that should be integrated in the docs in my opinion

``` bash
○ → brew install ruby 

○ → which ruby
/usr/local/bin/ruby

○ → ruby --version
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.4.0]

○ → gem install jekyll

○ → jekyll --version
command not found

○ → export PATH=$(brew --prefix ruby)/bin:$PATH

○ → jekyll --version
jekyll 1.1.2
```

then jekyll works then like a charm
remember to put this in your .bash_profile

**Comment by MikeiLL** [comment]
You rock!
