### ISSUE TITLE
Liquid extension: trim

### ISSUE THREAD

**Issue by dossy** [jekyll/jekyll#153]
I'm actually quite surprised this isn't a standard filter in Liquid, but I'd really like a `trim` filter.

`{{ '0102030' | trim:'0' }}` => `'10203'`

As an added bonus, specific `ltrim` and `rtrim` filters too ... but if I could even just get `trim` as described, that would be great.

I originally tried to work around this lack of a `trim` filter using the `plus` filter, but discovered that Ruby coercion didn't behave as I'd hoped, specifically:

`{{ page.date | date:"%d" | plus:0 }}`

I want to remove the leading 0 in the two-digit day representation ... but even though the value is numeric, Ruby still blows up complaining about Fixnum vs. String.

**Comment by dalanmiller** [comment]
Just for reference since this issue comes up when searching for "Jekyll Trim" here is an updated TrimFilter:

```
module Jekyll
  module TrimFilter
    def trim(input)
      input.strip
    end
  end
end

Liquid::Template.register_filter(Jekyll::TrimFilter)
```
