### ISSUE TITLE
-bash: jekyll: command not found. After install

### ISSUE THREAD

**Issue by patrickbjohnson** [jekyll/jekyll#1546]
Sorry if this is a 'low-level' question but after installing Jekyll (both with and without sudo) my system still can't seem to locate it. 

I've updated all ruby gems, managing ruby with .rbenv. From what I've read it looks like it's a $PATH issue, but to be honest, I'm not super sure or experienced how exactly to update this problem. Any help would be appreciated!

Possibly useful info: 
- Running Mac 10.8.4
- Running ruby 2.0.0p195
- .rbenv ruby manager

**Comment by gprasant** [comment]
rbenv rehash worked for me
