### ISSUE TITLE
Permalinks error with pages in root directory

### ISSUE THREAD

**Issue by Heliosmaster** [jekyll/jekyll#1566]
In my `_config.yml` I have

```
permalinks: /:title/
```

All the posts have a correct permalink, but for the page `about.html` that I have in my root directory, the page `/about/` does not work (to access the page i have to access `/about.html`).

If I use the `pretty` settins for permalink (which should just be an alias for `/:categories/:year/:month/:day/:title/`, according the documentation) everything is correct, and the page `/about/` works.

The same error happens also if I put explicitly `/:categories/:year/:month/:day/:title/` as permalink.
Might this be related to #691 ? Probably the related code is [lib/jekyll/page.rb#L68](https://github.com/mojombo/jekyll/blob/master/lib/jekyll/page.rb#L68)

For sake of completeness, here are my other options in the _config.yml

```
paginate: 10
pygments : true
baseurl :
permalink: /:title/
relative_permalinks : true
```

(using ruby-2.0.0 and jekyll 1.2.1)

**Comment by jatindhankhar** [comment]
Sorry for opening a year old closed issue but it can be fixed using the following 

``` {{ site.baseurl }}{{ post.url }} ```
as per the [documentation on jekyll](http://jekyllrb.com/docs/github-pages/) which says

>When doing permalinks or internal links, do it like this: {{ site.baseurl }}{{ post.url }} – note that there is **no** slash between the two variables.

**Comment by parkr** [comment]
All urls (e.g. `{{ post.url }}` or `{{ page.url }}`) should have a preceding forward slash (`/`). If they don't, it's likely a bug.
