### ISSUE TITLE
Jekyll Local server not working

### ISSUE THREAD

**Issue by edgenard** [jekyll/jekyll#1580]
When I try and run a locally hosted version of my website I get this error

```
Generating... error: Operation not supported on socket -    /Users/emmanuelgenard/Library/Application Support/Google/Chrome/App Shim Socket. Use --trace to view backtrace
```

I have no idea what this means, what am I doing wrong here

**Comment by emineysprince** [comment]
so helpfull @edgenard I suffered with the same problem but after move to the directory where i install my jekyll file, every thing is working

**Comment by ChenPHPER** [comment]
did you solved this problem?

**Comment by WilliamRoger** [comment]
I'm also having the same problem

**Comment by ashmaroli** [comment]
Hello there, @ChenPHPER and @WilliamRoger 
Can you guys paste the present error message and provide necessary details of your environment?

**Comment by WilliamRoger** [comment]
My problem I could solve just updating the version of the bundler to the bundler update command and everything worked perfectly hope it helps you.
