### ISSUE TITLE
Pygments and the startinline option for PHP code blocks

### ISSUE THREAD

**Issue by aureliojargas** [jekyll/jekyll#1633]
In https://github.com/mojombo/jekyll/issues/31 an option `startinline` was added to the Liquid tag so we can highlight PHP snippets without the `<?php` tag:

```
<% highlight php startinline %>
```

Unfortunately, the triple backticks syntax has no way to inform this option.

As investigated by the discussion in this issue https://github.com/imathis/octopress/pull/1141, always turning on the `startinline` option has no drawbacks, and it's only used by the PHP lexer.

Maybe Jekyll could use it by default for redcarpet? It's a one line change in `lib/jekyll/converters/markdown/redcarpet_parser.rb`, resulting in the following:

```
Pygments.highlight(code, :lexer => lang, :options => { :encoding => 'utf-8', :startinline => true }),
```

Or maybe provide a global config such as:

```
pygments:
  options: ['startinline']
```

**Comment by barryvdh** [comment]
Sorry, but can somebody explain how I can enable the `startinline` option now, using Github Pages, using the backticks. I tried the config option, but that didn't work..

**Comment by whilefalse** [comment]
This worked for me:

{% highlight php startinline %}
...
{% endhighlight %}

**Comment by k-funk** [comment]
This seems to be broken again, at least in Jekyll 3.1.6 and 3.2

I dumped these samples into a fresh jekyll project's `index.html`:

Works:
```
  {% highlight php %}
    <?php
      $a = new MyClass;
      $c = new \my\name\MyClass;
      $ch = curl_init();
      curl_setopt($ch, CURLOPT_URL, "example.com");
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    ?>
  {% endhighlight %}
```
Doesn't work:
```
  {% highlight php startinline %}
    $a = new MyClass;
    $c = new \my\name\MyClass;
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, "example.com");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  {% endhighlight %}
```

**Comment by envygeeks** [comment]
We don't support Pygments anymore.  We use Rouge.

**Comment by k-funk** [comment]
@envygeeks can you explain how to pass options to Rogue? Based on [this](https://github.com/jneen/rouge/issues/381) issue/post, and the Rogue README, it looks like I should be able to call my block like `{% highlight php?start_inline=1 %}`, but that gives a syntax error.

**Comment by DirtyF** [comment]
@k-funk this option is not supported by the `highlight`tag yet. Try with triple backtick, [It should work](https://github.com/jneen/rouge/issues/381#issuecomment-232828110)

**Comment by k-funk** [comment]
@DirtyF The triple backtick is only available if I'm using markdown. 
This is getting off topic of the issue... but I have html (`<figure>, <div class="--bootstrap_class--">`) in my page as well, and unless I'm mistaken, I don't think I can mix the two. I use markdown for my posts, since the content is pretty standard, but pages usually require a lot of customization that markdown doesn't support.

Is that rouge option in the works for the highlight tag any time soon?

**Comment by DirtyF** [comment]
@k-funk of course you can use HTML in markdown and have the best of both worlds!

**Comment by k-funk** [comment]
Hmm.. only seems to work if the markdown is not inside of html tags.

Reproduce:
**/sample.md**

    ---
    layout: page
    ---
    # an h1 tag
    <div>
    ```php?start_inline=true
    $c = new \my\name\MyClass;
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, "example.com");
    ```
    </div>
    {% include code_sample.md %}
    ```php?start_inline=true
    $c = new \my\name\MyClass;
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, "example.com");
    ```
    ## an h2 tag


Markdown gets processed outside the `<div>`, but not inside. I attempted to `{% include code_sample.md %} inside of the div, but that didn't change anything.

**Comment by jcubic** [comment]
@k-funk try `markdown="1"` attribute as mention in this article [Little Stuff about Markdown I Always Forget and have to Google](https://css-tricks.com/little-stuff-markdown-always-forget-google/)

**Comment by k-funk** [comment]
@jcubic just tried that in Jekyll, and it doesn't seem to work.
