### ISSUE TITLE
paginator.previous_page_path and paginator.next_page_path should honor custom paginate_path

### ISSUE THREAD

**Issue by breun** [jekyll/jekyll#1701]
http://jekyllrb.com/docs/pagination/ mentions one can set a custom `paginate_path` in `_config.yml`, but while the generation of pages will honor that setting the values returned by `paginator.previous_page_path` and `paginator.next_page_path` still return the default `page:num` style paths.

**Comment by haxan7** [comment]
Had a similar issue and spent hours debugging only to realise that I had made a stupid mistake.

Was using `paginator.next_page` instead of `paginator.next_page_path`
