### ISSUE TITLE
Interpreted permalinks in YAML front-matter

### ISSUE THREAD

**Issue by orschiro** [jekyll/jekyll#1712]
Hi,

sometimes I want to use a custom permalink setup for a particular post. However, at the moment I can only define fixed permalinks in the YAML front-matter of a post which are not interpreted. What I would be able to do is the following:

```
---
layout: post
title: A post title
date: 2013-10-07 16:41:00
categories: computer
permalink: /:categories/:title
---
```

Is this possible?

**Comment by envygeeks** [comment]
Is this still a problem?
