### ISSUE TITLE
`include` adds extra newline after included data

### ISSUE THREAD

**Issue by IQAndreas** [jekyll/jekyll#1728]
Whenever you `include` a file, an extra newline is added after the data, even if there is no trailing whitespace in the originating file.

```
`{% include one_line_comment %} This is your code on steroids!`
```

Results in:

```
<pre>//
This is your code on steroids!</pre>
```

This extra newline is usually ignored in HTML, but if you are using markdown, that extra whitespace will be interpreted and throw off you formatting.

I can't find any whitespace manually added in the class, so I'm guessing it's either appearing in `Liquid::Template.parse()` or `partial.render!()`.

**Comment by nemoDreamer** [comment]
I had this issue when I switched to "Github Flavored Markdown", since it respects single newlines:

```yaml
markdown: kramdown
kramdown:
  input: GFM
```

The trailing newline at the end of my include files is now being interpreted as an extra `<br/>`
