### ISSUE TITLE
Deprecate Maruku in favor of a new default markdown interpreter

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#1752]
[Maruku is dead](http://benhollis.net/blog/2013/10/20/maruku-is-obsolete/). Long live Maruku.

Breaking out a discussion started in https://github.com/mojombo/jekyll/issues/1747#issuecomment-29161731 to its own thread: **moving to a new default Markdown parser for Jekyll 2.0.0... Discuss.**

![marukuuuuu](https://f.cloud.github.com/assets/282759/1609149/82048d20-5532-11e3-92f5-064af86c0129.jpeg)

The two big contenders in my mind would be Kramdown and Redcarpet.

Assuming performance and other developer concerns are a wash, I'd push for Kramdown, especially considering many users are going to be forced to move _from_ Maruku. Kramdown supports Markdown Extra, like Maruku did/does, and I'd assume a non-small percentage rely on it. Syntax-wise, Kramdown is going to be most similar to Redcarpet, making the transition even easier.

Let the holy wars begin.

**Comment by nasht00** [comment]
I know this is old. I'm just starting with Jekyll and liked that redcarpet supports
```
'''languageName
```

But I am wondering about drawbacks.

Is there a list that compares features, pros and cons?
I'm not worried about migrating from Maruku since it's a new project.

**Comment by JesseHerrick** [comment]
I actually wrote an article comparing markdown processors: http://www.sitepoint.com/markdown-processing-ruby/

**Comment by nasht00** [comment]
Thanks! You wrote that they all support fences, like the example I showed above.
However when I used kramdown it did not display correctly. With redcarpet yes.

I guess from your blog post, I'm safe choosing redcarpet as my default...

**Comment by JesseHerrick** [comment]
@nasht00 I've found both Kramdown and Redcarpet wonderfully full-featured, but Redcarpet is significantly faster. Back to your problem, however, fences are denoted using backticks, not single quotes.

**Correct:**

<pre>
```ruby
```
</pre>

**Incorrect:**

```
'''ruby
'''
```

**Comment by envygeeks** [comment]
It's both <code>```</code> and <code>~~~</code>.  The latter belonging to Kramdown which does not follow the Github definition of what the fencing delimiter is.

**Comment by nasht00** [comment]
@JesseHerrick in my example I used single quotes because I could not figure out how to escape backtiks :)

@envygeeks Thanks that seems to be it. Although it did not seem to trigger syntax highlighting.
More reasons to use Redcarpet I guess.
