### ISSUE TITLE
Add guide for non-blogs

### ISSUE THREAD

**Issue by afeld** [jekyll/jekyll#1811]
This came up w/ @parkr over chat, but Jekyll (and GH Pages, for that matter) seems blog-centric, when in fact it can be used to create other kinds of static sites.  Adding this as a placeholder for this guide, which I'm hoping to take a first pass at soon.

**Comment by fulldecent** [comment]
May someone share a link to the original source for the Jekyll homepage. This is kind of non-blog site I am trying to set up.

**Comment by kleinfreund** [comment]
It's over here: [jekyll/jekyll/tree/master/site](https://github.com/jekyll/jekyll/tree/master/site).

**Comment by taniarascia** [comment]
I was looking for how to do this and I found this issue but didn't find any article on it, so I wrote [this tutorial](http://www.taniarascia.com/make-a-static-website-with-jekyll/) on how to make a non-blog site with Jekyll from scratch. Hopefully this helps anyone searching and landing on this page.

**Comment by mattr-** [comment]
@taniarascia that tutorial is amazing. Thanks for writing it

**Comment by taniarascia** [comment]
@mattr- Thank you! I tried to make it as concise as possible, and learned a lot along the way.

**Comment by jaybe-jekyll** [comment]
Fantastic article; thanks for caring and taking the time to share you knowledge and learnings in such a readable, enjoyable format and presentation! Added to articles links on IRC://#jekyll@Freenode!

**Comment by taniarascia** [comment]
Thank you! I really appreciate the positive response.

**Comment by sueswe** [comment]
@taniarascia very nice, thank you for that work!
