### ISSUE TITLE
Can support using include tag with relative path?

### ISSUE THREAD

**Issue by yevon-cn** [jekyll/jekyll#1851]
I think it is sometimes very flexible to using relative path, so what I think about include tag is that:
When the directory structure is like this:

```
├── _includes
|   ├── template_a.html
|   └── templates
|       └── template_b.html
```

When in template_a.html , using `{% include ./templates/template_b.html %}` to include template_b.html.
And when in template_b.html, using `{% include ./../template_a.html %}` to include template_a.html.

**Comment by wendycan** [comment]
Why is it not feasible?

**Comment by rabbitwater** [comment]
I think it is very necessary! @wendycan

**Comment by parkr** [comment]
@wendycan @rabbitwater This was over 2 years ago. Have you used `include_relative`? It's a tag that includes relative to the file you're in.

**Comment by wendycan** [comment]
It seems that include_relative can't include parent directory. Can file with the './views/admin/index.haml ' path include(include_relative) partials with the './views/partials' path?

**Comment by andrewleyva** [comment]
This has never been resolved. Is there any plan to fix this bug?
