### ISSUE TITLE
Failed to build gem native extension

### ISSUE THREAD

**Issue by rkuhel** [jekyll/jekyll#1881]
after trying to install the gem I got this error: 

compiling porter.c
porter.c:31:10: fatal error: 'stdlib.h' file not found
# include <stdlib.h>  /\* for malloc, free */

```
     ^
```

1 error generated.
make: **\* [porter.o] Error 1

**Comment by oresmus** [comment]
It looks to me like the first comment is a totally different bug than the one covered in comment 3 and beyond, whose solution is given above.

FYI for anyone who got the "stdlib not found" error in the first comment -- I too got that error, after upgrading to yosemite on a mac (on which I'd previously tried and failed to install jekyll), and solved it (or at least affected it somehow) using the command "xcode-select --install" to install the command line developer tools. (I then got some other error, which looks like it's covered in some other old bug report here.)
