### ISSUE TITLE
Add random select

### ISSUE THREAD

**Issue by zlatanvasovic** [jekyll/jekyll#1890]
It would be nice to have random select option, e.g. for data items, or posts.

**Comment by BrendanBerkley** [comment]
Been searching around for a random feature. My use case is that I'm prototyping a product grid, and I'd like to be able to pull from an array of images to populate the grid without defining specific numbers. The grid would be randomly generated on build, and that'd be perfect - the grid now simulates a diverse set of products without me having to set anything manually other than a list of images.

I'll probably just go with a plugin, but I wanted to chime in to vocalize a use case.

**Comment by parkr** [comment]
@BrendanBerkley I'd look at a pr that adds a `random` filter to https://github.com/jekyll/jekyll/blob/master/lib/jekyll/filters.rb

**Comment by parkr** [comment]
Use the `sample` filter, coming your way in Jekyll 3.1.0: #4223.
