### ISSUE TITLE
Zero exit code after YAML parsing errors

### ISSUE THREAD

**Issue by zoul** [jekyll/jekyll#1907]
Jekyll currently (1.4.2) returns a zero exit code after YAML parsing errors:

    $ jekyll build; echo $?
    Configuration file: none
                Source: …
           Destination: …
          Generating... YAML Exception reading …: (<unknown>): mapping values are not allowed in this context at line 2 column 18
    done.
    0

I guess it would be better to report the error properly by returning a non-zero exit code?

**Comment by envygeeks** [comment]
It seems like this was addressed in #3211? Is that the case?

**Comment by benbalter** [comment]
> It seems like this was addressed in #3211? Is that the case?

That's my reading as well.

**Comment by quarterto** [comment]
Looks like these errors are being swallowed again by https://github.com/jekyll/jekyll/blob/1ac9c21956ed7e31be6fd8f0083f6414b6220684/lib/jekyll/document.rb#L277-L284
