### ISSUE TITLE
Install with RubyGems

### ISSUE THREAD

**Issue by yongce** [jekyll/jekyll#1911]
Failed to execute the command "gem install jekyll" because /var/lib/gems can only be accessed by root:

$ gem install jekyll
Fetching: liquid-2.5.4.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /var/lib/gems

When I tried the following command:

$ sudo gem install jekyll
Fetching: liquid-2.5.4.gem (100%)
Fetching: fast-stemmer-1.0.2.gem (100%)
....
Installing ri documentation for toml-0.1.0...
Installing ri documentation for jekyll-1.4.2...
ERROR:  While generating documentation for jekyll-1.4.2
... MESSAGE:   Unhandled special: Special: type=17, text=""
... RDOC args: --ri --op /var/lib/gems/1.8/doc/jekyll-1.4.2/ri --charset=UTF-8 lib README.markdown LICENSE --title jekyll-1.4.2 Documentation --quiet

**Comment by juanibiapina** [comment]
It still doesn't work for me with jekyll 1.4.2 and ruby 2.2.2. Updating jekyll and all my other gems solved it.
