### ISSUE TITLE
Jekyll author pages support

### ISSUE THREAD

**Issue by MartinThoma** [jekyll/jekyll#1919]
I would like to have author pages.

On the file system (in the Jekyll root folder with all the source files) I would like to use

```
_authors/martin-thoma.md
_authors/john-smith.md
_authors/mary-johnson.html
```

On the file system (in the generated `_sites` folder) I would like to get

```
author/martin-thoma/index.html
author/john-smith/index.html
author/mary-johnson/index.html
```

Also, it would be nice to be able to access the posts generated by the author in a paginated way:

```
<h2>Posts by {% author %}</h2>
{% for post in authorpaginator.posts %}
    <div class="post type-post hentry clearfix">
        <h2 class="title"><a href="{{ site.baseurl }}{{ post.url }}/" rel="bookmark" title="Permanent link to '{{ post.title }}'">{{ post.title }}</a></h2>
        <div class="postdate">
            <span>{{ post.date | date: '%B' }} {{ post.date | date: '%e' }}, {{ post.date | date: '%Y' }}</span> 
            <!--<span>No Comments / 1 comment / 2 comments</span>-->
        </div>

        {% include entry.html %}
    </div>
{% endfor %}
```
- Is something like this currently possible with Jekyll? 
- Are there example pages (blogs)? If so, where are they?

**Comment by smithtimmytim** [comment]
I'm also trying to do something like this. This is what I have in my layout and it doesn't work:

```liquid
{% assign author = site.posts | where: "author", "{{  page.author }}" %}
{% for post in author %}
…
{% endfor %}
```

It seems `assign` doesn't let me assign it something dynamic like `{{ page.author }}`

**Comment by pathawks** [comment]
@smithtimmytim Your question is unrelated to this issue. You should open a new issue for your question:+1:

**Comment by smithtimmytim** [comment]
Well… it's kind of related, but ok 😄

**Comment by BlkPingu** [comment]
I'm also trying to paginate by author. Posted on SO about it. 
https://stackoverflow.com/questions/51744240/how-to-paginate-posts-by-author
