### ISSUE TITLE
XHTML rather than HTML

### ISSUE THREAD

**Issue by FearGoidte** [jekyll/jekyll#1922]
Probably my own poor searching skills but I can’t work out how to manipulate Jekyll into spitting out xhtml rather than html files. The index page works by simply renaming the file but the posts continue to generate as `.html`.

I realize that authoring in XHTML (especially serving as `application/xhtml+xml`) is somewhat niche but it’s a habit I’m loathe to give up.

I’m using GitHub as a host which limits the tinkering options, I had hoped that it was available ‘out of the box’.

Could anyone point me in the right direction or dash my hopes?

**Comment by shnkr888** [comment]
Enable xhtml github pages
