### ISSUE TITLE
{% assign %} Cannot overwrite page.*

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#1956]
Is there a reason that I cannot, within a page, overwrite any of the page variables with `{% assign %}`?

If I have a post that contains:

``` yaml

---
title: "Hello World"
```

...and a template that contains

``` liquid
Original title: {{ page.title }}
{% assign page.title = 'Goodbye World' %}
New title: {{ page.title }}
```

my output will be:

``` text

Original title: Hello World

New title: Hello World
```

I'm just not sure if this is a bug or a feature, so I'm curious why this is happening.

**Comment by TWiStErRob** [comment]
So if that's not possible, is there any way to actually change `page.title` dynamically? For example based on other front matter properties and possibly `site.data`?

**Comment by parkr** [comment]
@TWiStErRob It's not possible to change `page.title` from within Liquid.

**Comment by envygeeks** [comment]
Use {% capture %} with if else and other stuff and then use that captured variable.

**Comment by TWiStErRob** [comment]
That's a good idea, thank you, but I will have to duplicate that logic in a lot of places (e.g. when listing the collection items in different ways). I'll see how includes can help with that. I hope I can create an output variable without capturing it.

**Comment by envygeeks** [comment]
If I could see the source I might be able to help, no promises but sometimes for things like that we actually drop down to using an include with some defaults and then just duplicate that include where we need it.  That doesn't always work, but it does cut down on how much you need to edit to correct logic which is the most important thing (at least to me when working on large projects.)
