### ISSUE TITLE
"Rebuilding index... Killed" when running jekyll build or server

### ISSUE THREAD

**Issue by evitiello** [jekyll/jekyll#1959]
I'm attempting to rebuild my site, and get the following:

``` text
      Generating... 
  Populating LSI... 
Rebuilding index... 
                    Killed
```

when doing either "jekyll build" or "jekyll serve"  adding --trace gives no additional feedback

Any idea how I can track down the problem?

**Comment by tamagokun** [comment]
I'm having a similar problem. Have never seen this "Killed" message before.

```
Configuration file: /digmshift/embroiderybycuttingedge.com/_config.yml
            Source: /digmshift/embroiderybycuttingedge.com
       Destination: /digmshift/embroiderybycuttingedge.com/_site
      Generating...
Killed
```

Running Jekyll 2.5.3

**Comment by tamagokun** [comment]
@parkr I believe I may have pinpointed this problem.

There are loads of references to bundler exiting with no error or stack trace and simply the word "Killed". All of these errors are related to the system running out of memory and being unable to continue.

In my case this was indeed what was happening. Free'd up some memory and it worked just fine.

**Comment by envygeeks** [comment]
@tamagokun can you please create an upstream bug at bundler and link this issue?

**Comment by tamagokun** [comment]
Did some more digging..

Actually, the "Killed" message comes from the kernel killing off the process, it has nothing to do with bundler or even Ruby for that matter.

**Comment by envygeeks** [comment]
Yeah I actually had a hunch it was the system doing it that's why it was so generic :cry: I don't think there anything we can do about that.  I mean I guess we could check for a low memory situation without any fallback's (like swap) but I don't know if that's even worth it since it's very rare this comes up.

**Comment by tamagokun** [comment]
It would be nice if Ruby handled out of memory situations and threw an error, but I think this is just one of those "things" that developers figure out once and then never forget.
