### ISSUE TITLE
missing dependency when jekyll installed with package manager (linux)

### ISSUE THREAD

**Issue by CutNGlass** [jekyll/jekyll#1987]
Dependency definitions for installation of Jekyll must be missing "red carpet" as a required item.  This causes error when trying to run jekyll (see below).

following along with instructions here:
https://github.com/poole/poole/#readme

silly me, not familar with either mac or ruby, and not recognizing "gem" command, I proceeded with installation of jekyll by using linux package manager, there were several dependencies which were not discovered (therefore rubygems not installed).

after installation completed, proceeded to command line where
   jekyll serve
returned the following error:
...You are missing a library required for Markdown. Please run:
  $ [sudo] gem install redcarpet
## Missing dependency: redcarpet

So now, I'm proceeding to re-install...this time  following along with your instructions from here:
http://jekyllrb.com/docs/installation/

so i guess i need to quit being lazy and do command-line apt get for installation.
I've never used ruby, so what is on machine is left-over from something else, re-installing ruby and rubygems first.

**Comment by a598799539** [comment]
@davidneudorfer I am having the same issue, too. But I try deleting the `Gem.lock` and `bundle install ` again, and that's work.

**Comment by knoxxs** [comment]
+1
