### ISSUE TITLE
Liquid Exception. Invalid Date

### ISSUE THREAD

**Issue by vif-maureen** [jekyll/jekyll#2003]
I'm running jekyll locally with Bootstrap and have built out some static pages with no problem. However, suddenly the server fails with the error:

Invalid Date: '' is not a valid datetime.   Liquid Exception: exit in _layouts/post.html

There is not much code in _layouts/post.html:

``` text

---
layout: default

---
{% include JB/setup %}
{% include themes/vif/post.html %}
```

**Comment by Wang-Kai-Xuan** [comment]
I have a similar situation, and my problem is solved by you.Thanks!

**Comment by steveharville** [comment]
I had the same issue but resolved it by removing a colon ( : ) from the title of the post.
