### ISSUE TITLE
Filtering out categories in paginator.posts

### ISSUE THREAD

**Issue by mdo** [jekyll/jekyll#2018]
Currently there doesn't seem to be a way to filter out any post that is in a category. I'm trying to have a separate list of posts that doesn't affect the main posts index in the slightest, but it seems there is no way to do it.

I can get close with this:

```
{% for post in paginator.posts %}
  {% unless post.categories contains 'resources' %}
  <div class="entry">
    <a class="entry-thumb" href="{{ post.source }}" title="Visit {{ post.title }}">
      {{ post.content }}
      <span class="icon icon-forward entry-icon"></span>
    </a>
    <div class="entry-content">
      <h2 class="entry-title">
        <a href="{{ post.url }}">{{ post.title }}</a>
      </h2>
      <p class="entry-date">{{ post.date | date: "%B %-d %Y" }}</p>
    </div>
  </div>
  {% endunless %}
{% endfor %}
```

The goal of that code is to get a list of posts (config says 10 posts per page), but don't include any of the posts that are in the resources category. However, it falls short in that it will find 10 posts, then filter out the ones in the resources category, leaving me with fewer than 10 posts on the generated page.

What I'd love to be able to do is one of two things:
1. Have a default category so that I can generate a custom loop for showing posts.
2. Have an option to filter out any and all categories in the default loop.

Is that too far out of left field for this? Does it makes sense what I'm trying to do?

**Comment by djacquel** [comment]
Done https://github.com/jekyll/jekyll-paginate/issues/6
