### ISSUE TITLE
Remove html extension from pages on test server.

### ISSUE THREAD

**Issue by cirosantilli** [jekyll/jekyll#2021]
On Github Pages it already works: I can create a page with path `/pagetitle.html`, and use URL `/pagetitle` (without `.html`).

The problem is that to do that I have to setup all my links without the `.html`, which breaks the links on the test server.

For posts, this is already possible with `permalink: /:title`.

Is there any way to do it for pages also?

Workarounds:
- use posts instead of pages. Not satisfactory because:
  - it requires you to use an unwanted date prefix #484 , which is not going to change
  - it forces all your posts to be of `/:title` format.
- put the file in a folder with the desired name and rename it as `index.html`.
  
  Too much boilerplate.
- use Apache and play with `.htaccess`.
  
  Requires to install and setup Apache...

Related discussions:
- https://github.com/jekyll/jekyll/issues/156: seems to focus on Posts, not Pages as this issue, and was closed after the `permalink: /:title` solution came up, but this does not yet work for pages.
- https://github.com/holman/feedback/issues/231: stuck with the index workaround

**Comment by Sayan98** [comment]
@cirosantilli See this [page](https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/)
and [this page for a bit of fun](http://sayan98.github.io/intellisults/)
