### ISSUE TITLE
site.categories is empty

### ISSUE THREAD

**Issue by thany** [jekyll/jekyll#2137]
When I just have jekyll output the site's categories:

```
{{ site.categories }}
```

It prints an empty object. Not good, because I do have pages with categories. This code prints the categories for each page correctly:

```
{% for page in site.pages %}
{{ page.categories }} - {{ page.url }}
{% endfor %}
```

So there's no possible way that `site.categories` could be empty.

**Comment by liquidvisual** [comment]
Does this still apply in 2015? I ran into this also and found it rather confusing. Do 'pages' not work with tagging or categories at all?

**Comment by envygeeks** [comment]
@liquidvisual I do believe that is still so, but you are free to file a feature request if you think that shouldn't be the case (though I don't know why you would want pages with categories.)

**Comment by liquidvisual** [comment]
Thanks for the quick reply! I'm building a fairly large corporate website with lots of pages - it's not set out like a traditional Jekyll site with posts. I'm just looking for a way to use some form of tagging on my pages.

Eg.  categories: [document, new]

And then have pages stored in a variable like:

    {% assign new_pages = site.pages | where: "categories", "new" %}

**Comment by envygeeks** [comment]
@liquidvisual have you tried looking at collections? http://jekyllrb.com/docs/collections/

**Comment by liquidvisual** [comment]
I do use collections for a specific part of the site, but my main pages aren't set up like collections for a few technical reasons.

**Comment by wjdp** [comment]
I think in future the backends for pages & collections are being merged as they work very differently, may be worth planning for that.
