### ISSUE TITLE
failed to install jekyll on my new macbook pro with 10.9.2 and xcode 5.1

### ISSUE THREAD

**Issue by rainzhaojy** [jekyll/jekyll#2147]
Hi, I just got a new macbook pro, the os version is 10.9.2, then try to install jekyll:

First install xcode 5.1, I don't see command line tools in xcode preference, seems it is installed already, and seems ruby and git is installed also, the ruby version is 2.0.0p247, git version is 1.8.5.2, then I install jekyll by "sudo gem install jekyll", but got below output and errors, anybody could help?

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
compiling porter.c
porter.c:359:27: warning: '&&' within '||' [-Wlogical-op-parentheses]
      if (a > 1 || a == 1 && !cvc(z, z->k - 1)) z->k--;
                ~~ ~~~~~~~^~~~~~~~~~~~~~~~~~~~
porter.c:359:27: note: place parentheses around the '&&' expression to silence this warning
      if (a > 1 || a == 1 && !cvc(z, z->k - 1)) z->k--;
                          ^
                   (                          )
1 warning generated.
compiling porter_wrap.c
linking shared-object stemmer.bundle
clang: error: unknown argument: '-multiply_definedsuppress' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make: **\* [stemmer.bundle] Error 1

**Comment by fyibmsd** [comment]
ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future gem install jekyll
