### ISSUE TITLE
markdownify filter adds \n to the end of a string, bonks JSON

### ISSUE THREAD

**Issue by budparr** [jekyll/jekyll#2248]
I'm creating a JSON file where I'm using the markdownify filter, but the filter invalidates my JSON. Markdownify adds `\n` to the end of the string. 

That doesn't appear to be expected behavior for the filter, though I saw a reference to "\n" in this [test](https://github.com/jekyll/jekyll/blob/702d5520d4a6d39df8d4a381c33252333ae994e3/test/test_filters.rb).

my code (simplified):

```
{
"quote": "{{ review.quote | markdownify }}",
}
```

result (see the line breaks after generation. in the quote):

```
{
"quote": "copy goes here.
"
}
```

I'm using the filter "strip_newlines" to fix the problem (with which the JSON validates fine), but thought it worth bringing up because that doesn't appear to be expected behavior for the markdownify filter and would make it a bit more difficult if I had multi-line values.

_I'm using the .3 alpha, but tested on 1.5.1 with same results._

**Comment by Joshfindit** [comment]
@budparr - Maybe we're both don't something 'wrong'. Thanks for the tip about adding `strip_newlines` after `remove: '</p>'`.
