### ISSUE TITLE
Plugins are evaluated AFTER layouts meaning plugins can't effect layouts.

### ISSUE THREAD

**Issue by shmuel** [jekyll/jekyll#225]
From what I can tell plugins are being evaluated after layouts so they effect pages but not layouts. You can see an example of what I mean by installing this plugin:

http://blog.martiandesigns.com/2010/07/19/haml-sass-converters-for-jekyll.html

Once installed try putting some HAML in both a layout and page. The HAML used in a page will be evaluated correctly and the HAML in the layout will be spit out literally.

**Comment by dgmstuart** [comment]
@parkr hooks sound like a great approach. But how should they actually be used this scenario? The best I can come up with is:

``` ruby
Jekyll::Hooks.register :site, :pre_render do |site|
  site.layouts = site.layouts.inject({}) do |hash, (name, layout)|
    layout.content = layout.transform
    hash.merge({ name => layout })
  end
end
```

...which works, but seems pretty hacky: mapping over the layouts, reaching inside each one and transforming the content. Is there a more direct way to target the specific layout being used?
