### ISSUE TITLE
Add an equivalent of post_url for collections

### ISSUE THREAD

**Issue by mscharley** [jekyll/jekyll#2252]
eg, given that I have a collection called `my_collection` and `_my_collection/test.md` exists, I should be able to do one of the following to access the link

```
{% post_url test.md %}
{% document_url test.md %}
```

Not sure on the naming of `document_url`. Is there something else perhaps? `collection_url` came to mind, but that may be misleading as we aren't linking to the collection but an item in the collection.

**Comment by karlmdavis** [comment]
Isn't this feasible, now that all collection items have an ID property?

**Comment by jeffkole** [comment]
The way I implemented this in [jekyll-page-collections](https://github.com/jeffkole/jekyll-page-collections#page_url-tag) was like so:

```
{% page_url projects 2014-03-05-jekyll-page-collections %}
```

Where the first argument to the tag is the name of the collection, which would need to match the name specified in the `_config.yml` file.  Would that be an acceptable solution?
