### ISSUE TITLE
Add Modified Variable to Pages

### ISSUE THREAD

**Issue by 0xcaff** [jekyll/jekyll#2260]
This variable, on the `page` and `post` objects, will show to date the file was last modified.

**Comment by ilg-ul** [comment]
From my recent experience, the jekyll-last-modified-at uses the commit date, not the local filesystem modified at date.

For GitHub Pages this should not a problem, but when running Jekyll locally this requires some attention, to be sure the source files are first committed and then the site be generated.

**Comment by KevinWorkman** [comment]
@parkr Does jekyll-last-modified-at still work with GitHub Pages? When I try to use it I just get a blank date, and I don't see anywhere else that says it works with GitHub Pages.

**Comment by parkr** [comment]
@KevinWorkman it was never whitelisted on GitHub Pages so it never worked there. You'd have to generate locally.

**Comment by KevinWorkman** [comment]
@parkr Okay cool, thanks for the reply. I misunderstood what you meant when you said it was available for use on GitHub Pages! :crying_cat_face:

**Comment by jhgorse** [comment]
I understand that GitHub has not whitelisted the plugin, so why are we not implementing mtime scraping from Jekyll's side similar to the {{ static_files.modified_time }}? I checked out the repo in a fresh directory and noticed that git squashes the mtimes, though the git log and such server side should still have these timestamps it may be obscured in the case of GitHub hosting.

I don't like this. Jekyll really ought to do timestamps from the server-side, just like the static_files.

Related:
https://talk.jekyllrb.com/t/where-are-page-modified-and-page-generated-variables/2349
https://talk.jekyllrb.com/t/is-there-an-automated-way-to-output-the-last-modified-date-of-an-item-in-a-collection/2303/2

**Comment by jdalton** [comment]
:+1: For adding this functionality. Would be handy for invalidating service worker cache.

**Comment by JasonYao** [comment]
Is there any update on the chances of this getting moved into core so Github pages publishers can use it directly?

**Comment by pathawks** [comment]
@JasonYao No, and this doesn't work when building on GitHub pages anyway, because GHP only does a shallow clone of the repository which lacks any meaningful information about when a file was last modified.
