### ISSUE TITLE
Why does Post title (file) should have the date ?

### ISSUE THREAD

**Issue by Delaunay** [jekyll/jekyll#2282]
Why does Post title (file) should start with a date ? `2014-04-27-mypost.md`

The date is already defined in the header :
from 2014-04-27-mypost.md

```

---
layout: page
title:  "MyPost"
date:   2014-04-27 12:54:47
categories: apost

---
```

I feel like I put twice the information and the date in the filename is not even used (from what I saw). Moreover, a file that start with a date create super long filename and it is not really pretty.

**Comment by aharris88** [comment]
I think it would be great if the date came from the front-matter instead, but could also come from the filename if you choose to name your file that way. The problem I run into, is that, when I save a draft, I don't know what date I will end up publishing it, so I end up having to rename the file right before I publish.

**Comment by kleinfreund** [comment]
@aharris88 That said, one has to _always_ name the file with a kinda made up time. When I write a post which I will publish right away, I need to do that as well. Plus, the time I put into the file name can’t be that actual publishing date, because I am pushing a bit later.

**Comment by aharris88** [comment]
I guess that's true, but I'm not talking about making up the time, I'm just
saying that it would be easier to change the date in the front-matter, than
by renaming the file.

**Comment by kleinfreund** [comment]
So with this we can choose between having optional dates in the file name and optional dates in the front matter.

Optional dates in the file name:
- Moving from drafts to published posts would be easier (good)
- Files are not sorted in your project (bad)
- Ultimately requires front matter in all posts (bad)

Optional dates in the front matter: (vice versa from the above)

**Comment by aharris88** [comment]
I think that's a good summary. It definitely would be completely optional if you want to keep using filenames. Although I disagree that having front-matter in all posts is bad. I already have front-matter in all my posts, so that's not a big deal to me.

**Comment by joelmccracken** [comment]
This one fact is the single most irritating thing about Jekyll for
me. I really hope this changes, someday.

I would def start investigating changing this, if others were into it.

**Comment by aharris88** [comment]
I agree. But issue #3578 would also fix my problem in some cases. In some cases, the only reason I don't want the date in the filename is because I'm using posts instead of pages so that they'll all be in one directory.

In other cases I don't want the date in the filename just because it's a hassle to name your files that way, and it's complicated to teach people to name their files that way.

**Comment by parkr** [comment]
Posts are just date-centric collection documents. What you're looking for is a collection.

**Comment by joelmccracken** [comment]
I never paid collections much attention, but this actually looks like
exactly what I wanted. Thanks!

**Comment by aharris88** [comment]
@parkr I agree with that. Posts are date-centric. Pages have to go in the correct location. And if you want to do it differently, use custom collections.
