### ISSUE TITLE
config.yml not reloaded when running jekyll serve --watch

### ISSUE THREAD

**Issue by aldoforce** [jekyll/jekyll#2302]
Running 1.5.1, OSX.

To reproduce:
- create a new site with "jekyll new test-site"
- start the server with "jekyll serve --watch"
- in another console edit the _config.yml, change the site's title
  (you will notice in the server console: Regenerating: 1 files at xxx xxx ...done.)
- refresh your browser

Result: no changes on the web page
Expected: if the site was regenerated (as console says), the edited configuration should apply (the new site's title should change)

Thx

**Comment by gilyes** [comment]
@gka

Thanks for the **watchy** idea. In Windows I had to do 
<pre>
watchy -w _config.yml -- ruby "<i>path_to_jekyll</i>/jekyll" serve
</pre>
as apparently watchy can only launch exe files, most likely related to [this](https://github.com/joyent/node/issues/2318).

**Comment by fulldecent** [comment]
I request that this issue be left open.

The current behavior is unintuitive and the reason it has not been fixed is because an elegant solution has not yet been found. This seems like an excellent example of something that should be kept in an issue tracker.

**Comment by fulldecent** [comment]
I request that this issue be left open.

The current behavior is unintuitive and the reason it has not been fixed is because an elegant solution has not yet been found. This seems like an excellent example of something that should be kept in an issue tracker.

**Comment by davidsilvasmith** [comment]
I'm chiming in too. _config.yml ++ for leaving this open.

**Comment by reustle** [comment]
This just bit me for a good 30 minutes, and it isn't the first time either. Definitely an unintuitive piece. While I understand we can't auto reload when a _config change is made, maybe we can log something in the console output when the config file has changed?

```
Regenerating: 1 file(s) changed at 2015-04-04 21:26:17 ...done in 0.045787 seconds.
Regenerating: 1 file(s) changed at 2015-04-04 21:26:51 ...done in 0.044885 seconds.
# NOTICE: _config.yaml has changed. Ctrl+C and restart to see changes
Regenerating: 1 file(s) changed at 2015-04-04 21:27:42 ...done in 0.045595 seconds.
```

**Comment by kleinfreund** [comment]
> maybe we can log something in the console output when the config file has changed?

This sounds reasonable. Something like _Ignoring: _config.yml_.

**Comment by reustle** [comment]
Yeah, something like that does sounds better.

`Ignoring changes made to _config.yml`

**Comment by lginter** [comment]
Please at least document it somehow; I wasted around 20 hours trying to get _config.yml to refresh.

**Comment by TWiStErRob** [comment]
+1, at least a notification if not an auto-restart

**Comment by CarlJohnston** [comment]
+1 for notification (or at least a comment near the top of _config.yml) to notify that server should be restarted.
