### ISSUE TITLE
`--watch` exits silently

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll#2320]
```

C:\Users\xmr\Desktop\bootstrap-blog>ruby -v && jekyll -v
ruby 1.9.3p545 (2014-02-24) [i386-mingw32]
jekyll 2.0.2

C:\Users\xmr\Desktop\bootstrap-blog>jekyll serve -w
Configuration file: C:/Users/xmr/Desktop/bootstrap-blog/_config.yml
            Source: C:/Users/xmr/Desktop/bootstrap-blog
       Destination: C:/Users/xmr/Desktop/bootstrap-blog/_site
      Generating...
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.8/lib/posix/spawn.rb:162: warning: cannot close fd before spawn
'which' is not recognized as an internal or external command, operable program or batch file.
                    done.
 Auto-regeneration: enabled

C:\Users\xmr\Desktop\bootstrap-blog>
```

`wdm` is installed, 1.5.1 works fine.

**Comment by Oberon00** [comment]
This issue is there again in the newest `listen` version (2.8.5). I have bisected the versions (by changing it in my `Gemfile.lock`): 2.7.9 works fine, 2.7.10 seems nonexistent, and since 2.7.11 it silently exits.

**Comment by parkr** [comment]
@Oberon00 Please file on the guard/listen repo.

**Comment by XhmikosR** [comment]
From my experience ruby 2.x doesn't have this issue. I'm using 2.1.5 for a
few months and have never faced that issue again.

**Comment by Oberon00** [comment]
Oh, yes I'm running jerkyll with Ruby 1.9.3p551. Then that will probably be the issue.

I don't have enough information to post at guard/listen, since it just silently exits. Also I don't know Ruby (I'm using it just for jekyll) and don't want to put too much time into debugging this since I have found a workaround now.

**Comment by XhmikosR** [comment]
I never managed to pinpoint this issue down to any gems; only using Ruby 2.x fixed the issue for me...

Unfortunately, there are more issues with Ruby 2.x. One is the yajl-ruby issue you will hit if you use pygments.rb. The other one is a rubygems issue when installing Jekyll which can be worked around by using rubygems 2.3.0.
