### ISSUE TITLE
Live Reload Recommendations?

### ISSUE THREAD

**Issue by liquidvisual** [jekyll/jekyll#2354]
Is there one method the Jekyll team officially recommend for getting live reload to work in the browser? Will this ever be built in?

**Comment by chrisfinazzo** [comment]
I know this is old, but as a related issue has come up [recently][], it got me thinking again. Would this work as a subcommand? (e.g, `jekyll reload`). I have a few old notes from over a year ago where I contemplated trying something similar - but [Mercenary][] didn't exist then, now it should be easier.

[Mercenary]: https://github.com/jekyll/mercenary

[recently]: https://github.com/jekyll/jekyll/pull/4144

**Comment by parkr** [comment]
@chrisfinazzo This would be better as a `jekyll serve` switch, like `jekyll serve --live-reload` or `jekyll serve -R`, etc.

**Comment by Dorian** [comment]
:+1: Live reloading would be nice
