### ISSUE TITLE
State of Jekyll

### ISSUE THREAD

**Issue by troyswanson** [jekyll/jekyll#2358]
I propose that we get together and hold a [town hall meeting](http://en.wikipedia.org/wiki/Town_hall_meeting) to discuss the current state of Jekyll and its future. Google Hangouts is a great solution to do something like this, since it offers the ability to record and publish the entire meeting to YouTube instantly and for free. We could have them weekly, bi-weekly, monthly, or whatever makes sense.

Thoughts?

**Comment by erlend-sh** [comment]
Read @parkr's post the day it came out, but I never got around to watching this video until now. It was much less technical than I had feared, and it reinforced my faith in Jekyll.

**To the team and core contributors:**

Re. "learning by example" in terms of collections, by far the best tutorial of this kind that I've read to date was written by Barry Clark on SmashingMagazine:
http://www.smashingmagazine.com/2014/08/01/build-blog-jekyll-github-pages/

He accompanies his tutorial with a Jekyll theme dedicated to getting up up and running quickly:
https://github.com/barryclark/jekyll-now

It's a little reminiscent of Drupal's "distributions", making this a "blog distro" of Jekyll, except with less complications and future-breaking overlap of features.

Re. community, I just gotta say (again #1521 ), any number of GitHub stars does not a community make. Stars are the equivalent of "+1"s in a thread. They're not conversations, they're not user stories, and they're not contributions. You run GitHub Pages; *of course* you're popular on GitHub. Does that make you the most popular static site generator there is? I don't think so.
![screen shot 2015-01-18 at 11 32 54](https://cloud.githubusercontent.com/assets/583842/5792146/c5250bbc-9f09-11e4-8e94-976279c865d0.png)
Note: This is not to say "Google knows best" but rather "There are other metrics" -- and you have to make sure not to make the most favourable one a crutch.

You never claimed that stars is everything or that you are the indisputable numero uno, but you do appear needlessly attached to GitHub. I love GitHub, but it is not a place for community growth. Issues make for a sub-par forum at best (not a great editor, no draft saving, overwhelming topics index, the list goes on).

As long as you insist on powering all central discussions on GitHub, you're effectively ostracising a lot of average-joes such as myself. I'd love to tell you more about my toddler adventures with Jekyll and how I approach it as a WordPress-convert, but I'm really not that comfortable pouring my heart out in your usual hangout. *Everyone looks at me strange there.*

Judging by your talks, you're very keen on engaging a larger portion of your *prospective* community. I sincerely hope that will soon extend to building out a community of your own making and ownership, and not GitHub's.

---

**Question for next Hangout session:** Might you consider adopting Prose.io as an official project under the Jekyll umbrella? Tooling like this is absolutely central for bringing Jekyll to the masses, and the team behind it certainly has a great deal of experience setting up Jekyll environments for end-users of varying technical savvy.

**Comment by parkr** [comment]
> As long as you insist on powering all central discussions on GitHub, you're effectively ostracising a lot of average-joes such as myself. 
>
> Judging by your talks, you're very keen on engaging a larger portion of your prospective community. I sincerely hope that will soon extend to building out a community of your own making and ownership, and not GitHub's.

Hey, @erlend-sh! Thanks for the thoughtful comment. This idea in particular resonated with me. So many Jekyll users are finding out about Jekyll through GitHub, and naturally come to this repository with issues, so it has been easy to stick with GitHub Issues as the central and exclusive place for decision-making. That being said, we've tried other things in the past. There's a [long-lost Google Group](https://groups.google.com/forum/#!forum/jekyll-rb) that has lain stagnant over the past few years, with 426 members. I just found out we [have a /r/Jekyll subreddit](http://www.reddit.com/r/Jekyll/). Neither seem to be particularly active. We have a Twitter account that gets some great activity, but it's not monitored regularly – I stop in once every 10 days or so and scroll through the mentions. I have never run an open source project before, and wasn't really a part of another one before Jekyll, so I'm not quite sure how best to serve the community. At the same time, the core team only has so much time and effort to devote to this project, so there isn't much beyond handling issues and developing the program that is immediately seen as beneficial. A Jekyll-related conference makes a heck of a lot of sense, but, again, it comes down to resources.

So I guess my question is this: how would you like to see the community grow, and what can we do (within reason) to foster this?

**Comment by nternetinspired** [comment]
> So I guess my question is this: how would you like to see the community grow, and what can we do (within reason) to foster this?

While I wouldn't see it as a great way to foster the core Jekyll community per se, it might well be worth setting up a Jekyll Q&A site at StackExchange for those new to Jekyll to quickly find answers to their questions; http://area51.stackexchange.com/

**Comment by geraldb** [comment]
Hello, FYI: I've put together a [Planet Jekyll](http://planetjekyll.herokuapp.com/?style=top) - that is, an old-fashioned news reader that pulls in web feeds from projects sites, blogs, github and friends. Still early - for now the Planet Jekyll has three sections, that is,  1) Jekyll  2) Jekyll (Dev Edition) and 3) Meta  - more in the pipeline e.g. Jekyll Themes etc.  Always looking for new web feeds, of course ;-)  All the machinery is in Ruby and public domain (e.g. powered by the [pluto feed reader](https://github.com/feedreader) gem). Keep it up. Jekyll, Octopress and friends rock! Cheers.

**Comment by Enkerli** [comment]
We’re all overextended but proper community management might both save you time and increase the value of the project. In fact, as the average Jane and Joe start appropriating Jekyll, it might happen organically and you might not have a choice in the matter.
Something which helps a lot, though, is a tiny bit of handholding. Welcoming new users, pointing them in the right directions, asking them to contribute something they can contribute (say, writing documentation, there's never enough and bloggers like to write)… These can go a long way. Gina Trapani has been an inspiration to many. Not that her Open Source projects are better. But you readily get the sense that she genuinely cares about her community. Don't think it takes her more time than fixing bugs. In fact, if Linus’s Law makes any sense, bugs ar shallow in a community.

**Comment by grobmeier** [comment]
Coming from apache.org I agree with @Enkerli. I would like to note that community building is a serious task and time consuming. One thing is to have a good communication channel everybody understands.

The dart programming language use mostly G+. It makes sense, as many Dart users are also Google+ friends. In addition I created a planet called dartosphere.org, from which users can pick up there news. Similar to the above example.

At apache.org the communication channel is mailing list. It works well as many enterprise users are there who are used to mail.

Personally I think Github Issues are no communication channel in general, or not a good one. it's also bad to have it on IRC only. Not everybody uses that or even know what it is these days.

My initial suggestion would be to promote the mailing list, as for many of us it is normal to read emails on daily basis. Having a users@jekyllrb.com mailing list and a dev@jekyllrb.com mailing list might make sense.

**Comment by kleinfreund** [comment]
GitHub was so far a consequent choice to manage the community. There is no obvious platform like Google+ is for the Dart programming language as @grobmeier said. I'm also not sure about the idea @nternetinspired brought up. Does Jekyll have a user base big enough to leave the proposal state at http://area51.stackexchange.com and form a (closed) beta site?

Lately, [Discourse](http://www.discourse.org/) forums are somewhat popular ([Prepros](http://discuss.prepros.io/) uses one).

**Comment by nternetinspired** [comment]
> Does Jekyll have a user base big enough to leave the proposal state at http://area51.stackexchange.com and form a (closed) beta site?

Possibly not, but there is definitely ongoing and current activity there, unlike the Google Group for example, and I think that momentum could be built upon. There's currently more that 1,500 posts tagged with Jekyll and that doesn't include posts that are related, like those tagged gh-pages or Liquid (which while not directly Jekyll issues could nevertheless still cover questions being asked by new Jekyll users). Crucially, SE is recognised already as a goto place for Q&A generally, which I think gives it an advantage over some other options.

**Comment by alfredxing** [comment]
SE would definitely be nice, but this is a Q/A site only, with no place for admins to post announcements or anything. For this, I believe we're currently using [jekyll/jekyll-help](https://github.com/jekyll/jekyll-help)?

I think a Discourse forum would be nice, but then we'll need a place to host it.

Apparently @parkr has an IRC server set up as well: http://irc.parkermoo.re/room/%23jekyll

**Comment by jaybe-jekyll** [comment]
The IRC channel, #jekyll, is hosted on Freenode. The link provides access to the public logging facility for the channel.

**Comment by jglovier** [comment]
>Does Jekyll have a user base big enough to leave the proposal state at http://area51.stackexchange.com and form a (closed) beta site?

It's unlikely that even if there are enough people to commit to using a beta that SE mods would let this one go through because it would draw people away from using StackOverflow. Per folks I know who work at SE, they tend to frown upon new sites that draw users away from SO. New sites are primarily for new audiences whose subject matter doesn't overlap with SO. Had this explained to me when I tried to propose a GitHub SE site.

**Comment by kleinfreund** [comment]
What @jglovier said pretty much rules this idea out then. @nternetinspired's point is also important that a Q/A model like SE provides will restrict us in several regards. Especially announcements but also discussion. SE offers chats, though. For example the soon-to-be-beta-leaving [Code Review](http://codereview.stackexchange.com/) site has an active chat culture: The [2nd Monitor](http://chat.stackexchange.com/rooms/8595/the-2nd-monitor). But then again, chat is not really what solves this problem in a whole.

**Comment by envygeeks** [comment]
I personally think a Linux model mailing list is the best.  User group for all to ask and answer with no expectation that the framework developers will help you with design problems such as the average Liquid problem but others might, and devs might if they have time and a dev list that is free for developers to post to but moderated if non-core wants to post to it (free for all to read) and an announce list that only people who make announcements can post to that replies to users.

**Comment by parkr** [comment]
@envygeeks: I like the idea of a mailing list as well. I'd like archives if that's possible. What addresses are you thinking? I'll ask for access to the DNS records of jekyllrb.com. MX is set to Mailgun atm.

**Comment by envygeeks** [comment]
I like this layout since it makes everything tons easier:

lists.jekyllrb.com -> Mailman Signup and Archives
dev@lists.jekyllrb.com (or development whatever everyone wants)
announce@lists.jekyllrb.com
users@lists.jekyllrb.com

**Comment by parkr** [comment]
Cool, i'll work on that. @gjtorikian also talked about getting a plugin website up & running, and setting up a meet up in SF.

**Comment by erlend-sh** [comment]
Mailinglists is counter to what I'm asking for. That's a move first and foremost in the interest of the developers, not the users. If you want to ease developer discussion, why not use something like Slack?

For community building, Discourse definitely gets my vote.

**Comment by parkr** [comment]
> For community building, Discourse definitely gets my vote.

Discourse is prohibitively expensive for us. None of us have the money to devote to a box that is fast enough to make Discourse usable. If you know someone who could sponsor us, that'd definitely work and I'd be happy to work with them to maintain it all.

> Mailinglists is counter to what I'm asking for. That's a move first and foremost in the interest of the developers, not the users. If you want to ease developer discussion, why not use something like Slack?

I don't agree with your argument at all here. Everyone has email, everyone uses email. Email is ubiquitous and has an incredibly low barrier to entry. While the core devs may have a `dev@` channel they use for internal (but public) discussion not worthy of GitHub, the primary list would be `talk@` or something. Additionally, email and Slack (or a chat client in general) are totally different. Email takes longer and has longer chunks (easier to explain a problem and provide code/configuration). Slack is for quick coordination with relatively short messages being sent more frequently.

Ultimately any solution has to work for the developers of the project, whether that means just the core team or the core team and the code-contributing portion of the user base. Choosing something that doesn't work for the core team just means we won't be able to participate effectively.

**Comment by envygeeks** [comment]
I'd be happy to sponsor the first $10 a month (myself,) but if the resources exceed a $10 DO server we'd need sponsoring.  I'd even manage the servers behind it since I already manage dozens of servers keeping this one is not a big deal.  Once it exceeds that we would probably need sponsoring.

**Comment by ldexterldesign** [comment]
+1 for mailing list/email

Regards,

**Comment by erlend-sh** [comment]
> Discourse is prohibitively expensive for us. None of us have the money to devote to a box that is fast enough to make Discourse usable. If you know someone who could sponsor us, that'd definitely work and I'd be happy to work with them to maintain it all.

Considering Jekyll's open source fame, I'd be very surprised if you couldn't arrange for free hosting or sponsorship by agreeing to set up an affiliate link, like how [Font Awesome](http://fortawesome.github.io/Font-Awesome/) is primarily served by MaxCDN.

If you'd like I could ask around, reference this thread and get you in the loop before any "formal handshake".

> Everyone has email, everyone uses email. Email is ubiquitous and has an incredibly low barrier to entry.

No disagreement there. Thing about mailing lists is they don't scale, at all. Developers will usually be interested in practically every single message that flies through their community, even if a lot of them are only glanced at. Barrier-entry users on the other hand start out with a much narrower field of interest: The problem/challenge they are pursuing and any topics related to that.

Mailing lists do a terrible job of letting the user:

 - Search for those topics
 - Ignore uninteresting topics

The list is short but the impact is huge. Mailing lists aren't really a community-building tool so much as a more advanced one-way contact form. I'm sure there are sone mailing list front-ends out there that might facilitate this better now than what I've experienced in the best, but I can say with utmost confidence that Discourse does a stellar job of doing all the things that mailing lists fail to do, and it does a pretty good job of doing the one thing mailing lists are good at: [sending mail](https://meta.discourse.org/t/replacing-mailing-lists-email-in/13099). You can turn on "mailing list mode" and use it as such if you'd like, and everyone's happy ;)

**Comment by grobmeier** [comment]
I disagree with your thoughts on mailing lists.

You can search mailing lists by either your own mail client (gmail does a fantastic job) or by things like markmail: http://markmail.org/. Google Groups also has a search interface.

With clients being able to show threads and having a mute function, ignoring a topic is easily possible. For the rest are filters for.

In fact, mailing lists is something everybody already got on his finger tips, everybody understands and which is independent of providers. While I like Discourse, sponsors and message boards might go away. While I like Slack, the Chat might be no longer free at some point. And so on.

Mails can be backed up by services like Markmail, are distributed like Git (everybody got the copy in their mail box). They are here to stay, and decisions are not lost.

That said, the Apache Software Foundation uses Mailing Lists first for community building. With more than 150 projects and more than 3000 active committers (not to mention the user base) I think its proven that mailing lists work. 

That said, if Discourse is chosen then i would definitely say the mailing list mode is non-negotiable. If it works well then all my points made above are fine, which are, the content must not be lost if Discourse goes away.

Finally I would like to reach out to the Discourse team if they would donate the hosting themselves if nobody objects.

If this isn't possible, I am willing to donate the 10$ for a Digital Ocean box in return to a nice sponsor badge. However, I'd prefer if the Discourse team helps, as I have learned its always complicated to keep up services like the by volunteers.

**Comment by grobmeier** [comment]
I have checked back with the Discourse team, and they told me they are just offering this:
http://blog.discourse.org/2014/02/discourse-installs-for-non-profit-and-education/

(99$ for an installation, then self-hosting and maintenance).

With that in mind, I'd think we can do it ourselves as well.

**Comment by alfredxing** [comment]
@grobmeier I don't think the setup is the problem, it's more the hosting costs ($10/month doesn't seem like much but it definitely adds up in the long run).

**Comment by grobmeier** [comment]
@alfredxing I know, thats why I asked them if they would donate a hosted version to us - but that's not possible it seems.

**Comment by envygeeks** [comment]
Because it takes a lot of resources to efficiently host Discourse.  While you could run it on the specs they say you can (and we would be at first until we saw real traffic) we're gonna have a bad day eventually, but if somebody threw in $10 a month with me then I could say we would be okay for a while.  Out of a dozen sites I've setup with Discourse and currently help manage (about 3 of them) the system requirements they list are an absolute crock in production... considering everything it needs behind the scenes to run efficiently.

Like I said, I'd be willing to manage the server and setup Discourse since I have experience but it's the hosting we need help with, not the setting up and maintaining it part.

**Comment by erlend-sh** [comment]
[RunAbove](https://www.runabove.com/), a derivative of OVH, is [using Jekyll for their docs](https://github.com/runabove/knowledge-base). Seems like a natural place to start ;)

My first stop was Linode and they told me, quite as expected, they need to hear directly from the Jekyll core team before they can get into specifics.

**Comment by envygeeks** [comment]
I'll talk to @parkr tomorrow and throw $10 at RunAbove which will give us 3 months of hosting and give us time to see if it will take off at which point we can come back and decide whether or not it's worth it to keep running and find a sponsor or just ditch it in favor of mailing lists only which take nothing to run and I can provide for free on my servers.

**Comment by erlend-sh** [comment]
What I meant is you could definitely ask RunAbove if they'd be willing to cover your hosting fees for you, e.g. in exchange for a simple "Hosted by RunAbove" affiliate link in your footer.

If that doesn't work out, surely you could ask GitHub, as a company, to pitch in?

**Comment by envygeeks** [comment]
I interpreted what you said the way you thought I didn't, however I would hope we would much rather trial run a forum for $10 (of which I would personally put in) then search for and waste a sponsors money if the problem we are asking money to solve doesn't actually exist.

**Comment by erlend-sh** [comment]
Sure, sounds reasonable. Thanks a bunch for setting it up! :+1:

**Comment by jglovier** [comment]
This thread has really gotten away from the original issue (which is since closed), and since the ongoing discussion here is so important I think it deserves it's own issue. Does someone want to open a new issue and move the discussion about picking a discussion medium over there?

>If that doesn't work out, surely you could ask GitHub, as a company, to pitch in?

I'll look into this.

**Comment by erlend-sh** [comment]
Any news on the Discourse forum @envygeeks and @parkr? I figured maybe in light of the recent GitHub meetup there might've been some developments.

**Comment by envygeeks** [comment]
@erlend-sh it'll be up sometime this week I've already had @parkr set the DNS and I cleaned up the server last night and setup Docker and got everything ready I just have to make time after work to get it up so look out for this week or you can watch the Discourse repo we have because I'll push the source (minus secure stuff) up there.

**Comment by envygeeks** [comment]
Discourse is up. @parkr will link to it when he feels it's ready for everybody!

**Comment by parkr** [comment]
The Discourse instance is here: http://talk.jekyllrb.com/t/welcome-to-jekyll-talk/13

Still working on customizing it, but have at it!

**Comment by mattr-** [comment]
:tada:

**Comment by troyswanson** [comment]
The minimum password length is 22 characters? That seems a tad... what's
the word... insane?

**Comment by troyswanson** [comment]
Also, I didn't get an activation email :cry:

**Comment by mattr-** [comment]
> The minimum password length is 22 characters? That seems a tad... what's the word... insane?

nah. that's just good security. :smiley:

>Also, I didn't get an activation email :cry:

You'll get one. There's just a small delay in the sending of the email.

**Comment by troyswanson** [comment]
> nah. that's just good security.

![fry](https://cloud.githubusercontent.com/assets/1420926/6332892/8ef56e7c-bb4e-11e4-86b4-5d5672d4d821.jpeg)

> You'll get one. There's just a small delay in the sending of the email.

Yes, I just got it.

**Comment by grobmeier** [comment]
Worked all well for me.

However I was very glad to have a password manager in my setup. Guess 22 characters exclude users who don't have one ;-)

**Comment by parkr** [comment]
Bahahahaha. 22 min chars was my call. the default is 8, believe it or not.

**Comment by envygeeks** [comment]
To @alfredxing @mattr- and @troyswanson you should all have your privileges now.

**Comment by mattr-** [comment]
![heman](https://cloud.githubusercontent.com/assets/77174/6333984/24484ca8-bb57-11e4-9df6-e24a1c793efd.gif)

I HAVE THE POWER!! :wink:

**Comment by alfredxing** [comment]
@envygeeks Thanks!

**Comment by erlend-sh** [comment]
Awesome work guys! As I said on Twitter, I think the 22 character length on passwords is rather extreme and might even deter users. As the "high priority target" that you are as admin you are free to make your password as long as you'd like, but don't impose that on the average user.

That being said, this can be heavily mitigated by setting up [login integration with GitHub](https://meta.discourse.org/t/configuring-github-login-for-discourse/13745), and probably Google & Facebook as well while you're at it.

**Comment by envygeeks** [comment]
I'm voting no on Google and Facebook because both require way too much work to get keys and I'm not in the mood to deal with all that trash (especially for Facebook because I don't have a Facebook so @parkr will probably have to do that) I'll setup Github today once @parkr gets me the keys and I'll setup Twitter later today both of those have straight forward app creations.

**Comment by envygeeks** [comment]
Both Twitter and Github are now enabled.

**Comment by jglovier** [comment]
>Both Twitter and Github are now enabled.

@envygeeks :metal: :zap: :metal:
