### ISSUE TITLE
Pagination support for collections

### ISSUE THREAD

**Issue by gpxl** [jekyll/jekyll#2376]
It looks like pagination is hardcoded for "posts". Something like, pagination.collection_name would be nice to have.

**Comment by smithtimmytim** [comment]
Since `jekyll-paginate` is no longer being maintained, is it possible to re-open this?

**Comment by elyday** [comment]
Please re-open this. It is a very nice feature when it will be done

**Comment by DirtyF** [comment]
You can paginate collections with `jekyll-paginate-v2` plugin, see: https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md
