### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by DaleLJefferson** [jekyll/jekyll#2409]
I have a product list

```
products:
  - title: Widget
    price: 14.00
```

And I would like to simply display 14.00 in my template.
Currently it gets displayed as 14.0. My current workaround is storing price as a string.

Shopify has the money filter
http://docs.shopify.com/themes/liquid-basics/output

```
{{ product.price | money }}
```

Could something like this be added to jekyll?

**Comment by jhabdas** [comment]
Stumbled across this earlier today while trying to output item amounts and *cough* couldn't believe there wasn't a plugin for this yet. So I made one: https://rubygems.org/gems/jekyll-money

**Comment by jimafisk** [comment]
Thanks @jhabdas this is great! For the lazy:

Add to _config.yml
```
gems:
  - jekyll-money
```

Add to Gemfile
`gem 'jekyll-money'`

Run
`bundle update`
`bundle install`

And use away in your templates
`{{ 5000 | money }}`
