### ISSUE TITLE
Add an option to be more verbose

### ISSUE THREAD

**Issue by mythmon** [jekyll/jekyll#241]
It would be nice if there was a option to make the output of jekyll more verbose. Something like

```
#> jekyll
Configuration from ...
Building site ...
Generating my-cool-page.html now.
> Unrecognized variable format.
> Using layout post.
>> Using layout default.
> Done with my-cool-page.html
...
Successfully generated site
```

It would have saved me some debugging trying to set up a personal jekyll site, to realize that my layouts weren't being sources correctly.

**Comment by gavinwye** [comment]
:+1:

**Comment by purp** [comment]
```jekyll build -V``` invokes verbosity. It doesn't produce a different result, though:

    purp@tinyjoy:test_jekyll_blog$ jekyll build --help
    jekyll build -- Build your site

    Usage:

      jekyll build [options]

    Options:
                --config CONFIG_FILE[,CONFIG_FILE2,...]  Custom configuration file
                --future       Publishes posts with a future date
                --limit_posts MAX_POSTS  Limits the number of posts to parse and publish
            -w, --[no-]watch   Watch for changes and rebuild
                --force_polling  Force watch to use polling
                --lsi          Use LSI for improved related posts
            -D, --drafts       Render posts in the _drafts folder
                --unpublished  Render posts that were marked as unpublished
            -q, --quiet        Silence output.
            -V, --verbose      Print verbose output.
            -h, --help         Show this message
            -v, --version      Print the name and version
            -t, --trace        Show the full backtrace when an error occurs

Non-verbose build:

    purp@tinyjoy:test_jekyll_blog$ jekyll build
    Configuration file: /Users/purp/work/test_jekyll_blog/_config.yml
                Source: /Users/purp/work/test_jekyll_blog
           Destination: /Users/purp/work/test_jekyll_blog/_site
          Generating...
                        done.
     Auto-regeneration: disabled. Use --watch to enable.

Verbose build:

    purp@tinyjoy:test_jekyll_blog$ jekyll build -V
    Configuration file: /Users/purp/work/test_jekyll_blog/_config.yml
                Source: /Users/purp/work/test_jekyll_blog
           Destination: /Users/purp/work/test_jekyll_blog/_site
          Generating...
                        done.
     Auto-regeneration: disabled. Use --watch to enable.

Would a pull request to add verbosity when this flag is set be interesting?

**Comment by purp** [comment]
p.s. If you ```export JEKYLL_LOG_LEVEL=debug``` you enable a reasonable amount of debug info in the meantime.

**Comment by purp** [comment]
Just added PR #3665 to properly set the log level when you use -V; this should be a good start since the output given by the jekyll command is just its log being redirect to your terminal. From there, it's just about adding some debug logging where we need it.

+1 on PR #3665 if you like what you see.

**Comment by nasht00** [comment]
Can someone clarify what is the status for this today?

I have Jekyll 2.4, and running with `--verbose` does not print anything more than this.

Was it fixed in 3.0? 

I am asking because I am running a Travis CI which complains after 10 minutes without any log (my Jekyll build is complex)

**Comment by envygeeks** [comment]
@nasht00 that is not what you are looking for.  You want `travis_wait` which is explicitly designed for this kind of thing: http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received

**Comment by nasht00** [comment]
Yep that's what I am doing now. But still, on my local machine `--verbose` does not do anything.

**Comment by nasht00** [comment]
To answer my own question, when using Jekyll 3.0, yes I see the real verbose going on

**Comment by envygeeks** [comment]
Yes @parkr added in some more diagnostic stuff when he updated to collections.  It's nice.
