### ISSUE TITLE
Multiple Content sections on a page

### ISSUE THREAD

**Issue by gerggggggg** [jekyll/jekyll#246]
A major feature that is preventing me from adopting Jekyll is the ability to have multiple content sections on a single page.  I enjoy the simplicity of a *.markdown or *.textile file in that they have some Front Matter, content, and that's it, however, I'm bummed at the fact that all of that content for a page goes into the "content" template variable.  It would be awesome if I could label multiple content sections in my *.markdown or *.textile file and then include those sections in different places in my layout.

Stacey does exactly this: http://staceyapp.com/documentation/creating-pages/editing-content/

So, as an example in Jekyll, it would be cool to be able to create a *.textile file like this:

```
--- 
layout: default
title: Foo Bar Page

---
content:
I'm the main body content.

other_section:
And I'm some other stuff
```

And then I could have a default.html layout file like this:

```
<!DOCTYPE HTML>
  <html>
    <head>
      <title>{{ page.title }}</title>
    </head>
    <body>
      <div id="main-content">
        {{ content }}
      </div>
      <div id="other-stuff">
        {{ page.other_section }}
      </div>
    </body>
  </html>
```

Obviously, there would need to be some agreed upon labeling and sectioning syntax, but I don't see any immediate problems with Stacey's syntax.

**Comment by kyleaffolder** [comment]
[This might help](https://gist.github.com/anonymous/bea7d7389b7331bba512) some of you that are interested in a plugin that adds this capability to Jekyll. I scoured the web and found this gem. Testing and working in my local Jekyll environment! I condensed all of the code from the original Git repo down into one .rb plugin file.

**Comment by bloggingfear** [comment]
#jacius you rock man
