### ISSUE TITLE
Permalink Front Matter does not Support/Respect Dynamic Elements 

### ISSUE THREAD

**Issue by jaybe-jekyll** [jekyll/jekyll#2475]
Permalinks set from within Page/Post/Other' front matter do not provide for or respect dynamic elements such as those represented by colon-prefixed keywords configurable via the global configuration (_config.yml) `permalink` directive.

The issues are as follows:

- Users may wish and expect to leverage dynamic permalink elements within pages, posts, etc.
  - Example/scenario:
    - User has ~250 posts, organized by filesystem hierarchy, such as:  `/cars/used/_posts/...`.
    - User has custom, static permalink: settings within each post' front matter:
      - `permalink: /vehicles/pre-owned/`
    - User wishes to change filesystem hierarchy and or permalink structure of all ~250 posts.
      - e.g. `permalink: /autos/:month/:title/`

- The documentation is misleading in the following ways:
  - [Jekyll (global) Permalink docs](http://jekyllrb.com/docs/permalinks/)

> Jekyll supports a flexible way to build your site’s URLs. You can specify the permalinks for your site through the Configuration or in the YAML Front Matter for each post. You’re free to choose one of the built-in styles to create your links or craft your own. The default style is date.

> Permalinks are constructed by creating a template URL where dynamic elements are represented by colon-prefixed keywords. For example, the default date permalink is defined as /:categories/:year/:month/:day/:title.html.
  - [Jekyll (front matter) Permalink Docs](http://jekyllrb.com/docs/frontmatter/#predefined-global-variables)

> If you need your processed blog post URLs to be something other than the default /year/month/day/title.html then you can set this variable and it will be used as the final URL.

While the Front Matter Permalink docs do suggest what is configured will be the `final URL`, the user will likely first visit the doc' Permalink documentation and expect dynamic elements to work throughout, consistently.

In opening this issue I hope to proceed as follows:

- Elicit feedback about the concept of providing for dynamic elements within Front Matter permalink: settings (per Page, Post, etc.)
  - Understand feasibility, impact, and implications of coding such a feature/adjustment.

- Elicit feedback regarding updating the documentation to more-accurately reflect and portray how permalink' settings work and differentiating the current capabilities differences between global (_config.yml) `permalink:` settings and per page/post/etc. `permalink:` settings.

**Comment by envygeeks** [comment]
It seems that #3031 added some features that were merged, did that fix this issue?
