### ISSUE TITLE
Sorting & ordering collections

### ISSUE THREAD

**Issue by ahmedelgabri** [jekyll/jekyll#2515]
I'm trying to sort/order & limit collections.

``` yaml
collections:
  collection:
    output: true
```

now in my template I have this

``` html
{% for item in site.collection limit:6 | sort: 'date' %}
    <li>
        <a href="{{ item.url }}">
             <img src="{{ item.thumb }} " alt="">
            </figure>
            <p>{{ item.title }}</p>
        </a>
    </li>
{% endfor %}
```

It doesn't work, the ordering is always by file name. I tried even added `order_page: n` inside each page YAML & use this to with `sort: 'order_page'` but it didn't work. Tried using `reversed` to fix this but then `limit: 6` returns the same 6 pages.

I want to order this collection but date "new pages first" & limit it showing the latest 6 pages.

**Comment by falkorichter** [comment]
```
{% for item in site.collection reversed %}
```
inverts the collection

**Comment by jacobmischka** [comment]
@penibelst Thank you. Two years later this comment is still helpful.

**Comment by deanpanayotov** [comment]
@penibelst Thank you!
@jacobmischka Four years later that comment is still helpful.

**Comment by merlinpatt** [comment]
Are there any plans to make sorting possible in the for loop? I'd rather not have an extra variable for something so simple
