### ISSUE TITLE
Setting Collections Relative Directory: Right Approach?

### ISSUE THREAD

**Issue by budparr** [jekyll/jekyll#2518]
This discussion is related to a [PR](https://github.com/jekyll/jekyll/pull/2517) I made to set a configuration variable for a Collection's location in the directory structure. I'm putting it here in an issue to open a broader discussion, if anyone cares, about the best approach to this.

Currently, a Collection's "relative_directory" is set to the Collection label. The documentation is a bit confusing here, because one can apparently access the relative_directory, but not configure it.

I believe it will be better for users, including content creators, to optionally organize their collections into a folder or folders.

So, is it best to be able to set each Collection's directory, or set all Collections' directory, or set aside (thinking of a previous conversation on this) the _includes and _layouts folder so everything else is content?

I've been trying to shove most of my content into a _documents folder and with a bit of finagling (setting permalinks) I can get them to render where I'd like. 
Ideally there'd be a way to have a lot of control over the directory structure to keep it organized.

Thoughts appreciated.

**Comment by envygeeks** [comment]
I'm gonna try and get this out by 3.0, no promises though. I ran into this issue today and I was bummed out that it didn't work like that out of the box.

**Comment by parkr** [comment]
Anyone have time for this?

**Comment by maban** [comment]
:+1: for this functionality. Like @budparr, I'm also trying to organise my collections so it's easy for editors to know which files to edit.

**Comment by mathematicalcoffee** [comment]
Would love this functionality, I also have many collections that I just want to group into subfolders for cleanliness.

I've just patched one line in jekyll to allow a collection's `relative_directory` to be set in `_config.yml`.
You can see it [here in my fork](https://github.com/mathematicalcoffee/jekyll/tree/collection_relative_paths) : it only neede one line to be changed - in the getter for `relative_directory` of `collection`, use the `relative_directory` in the metadata if it exists, and otherwise use the default (`_{#label}`).

If this is acceptable, I can try to do tests and documentation (like the contributing page says), though this is my first time using Ruby, so if anyone wants to help that'd be great.

**Comment by mathematicalcoffee** [comment]
Alright, I've added documentation and tests (though I am unsure if the tests are rigorous enough).
Currently this is what you do:

In `_config.yml`, just add `relative_directory`:

~~~
collections:
  my_collection:
    relative_directory: _collections/stupid_name
~~~

The resulting collection

* has label `my_collection` (**regardless** of the name of the actual directory, `stupid_name` in this case - though in practice you'd keep the name of the directory the same as the name of the collection).
* is copied to `<dest>/<collection name>/`
* each document in the collection has path `_collections/stupid_name/document-name.md` Note this refers to the source path ie `_collections/stupid_name`, not the destination path ie `<collection_name>/`. This is the only thing I might think of as being inconsistent.

If you think this modification sounds OK, I'll go ahead and submit a pull request.
The reason I ask first is I've only recently started using jekyll so I'm not sure if the third point is OK, though to me it's similar to when you add a permalink to the front matter, and is fine with me.
I am not sure if this should be explicitly mentioned in the documentation (I have not currently mentioned it).

On that note, the jekyll documentation says `path`. should be "Path to the document relative to the collection's directory", but for me this is instead the *absolute* path to the document (e.g. `/home/amy/sandbox/jekyllsite/_my_collection/index.md` under "normal" jekyll (where the collection is in the toplevel `_my_collection` folder) and `_collections/stupid_name/index.md` under jekyll after this modification. i.e. in neither case is it a path "relative to the collection's directory"; in the former it's an absolute path and in the latter it's a path relative to the **site**'s directory. But perhaps this is a different issue?

**Comment by envygeeks** [comment]
We won't know if they are OK until you send a pull request, if you feel that your code is suitable (and to me the idea sounds suitable) then please do submit a PR if you would like and we'd be happy to take a look at the code (I know I won't go digging through your repo to find the code, it's much easier to look at the PR's code.)

**Comment by envygeeks** [comment]
See: #3723

**Comment by DirtyF** [comment]
Closing this now that we have #6331, users can now store all their collections in a folder relative to the source dir with `collection_dir` :tada:
