### ISSUE TITLE
Manually select related posts

### ISSUE THREAD

**Issue by TheFox** [jekyll/jekyll#2539]
Is there a simpler way to "loop" over the inner array? And a simple way to get the basename of the file?

	{% for post_name in page.related_posts %}
		{% for post in site.posts %}
			{% assign basename = post.path | replace: '_posts/', '' | replace: '.md', '' %}
			{% if basename == post_name %}
				<li><a href="{{ post.url }}">{{ post.title }}</a></li>
			{% endif %}
		{% endfor %}
	{% endfor %}

Maybe someting like this?

	{% for post_name in page.related_posts %}
		{% assign post = site.posts[post_name] %}
		<li><a href="{{ post.url }}">{{ post.title }}</a></li>
	{% endfor %}

So I don't need to loop over the inner array.

In each post I have a custom variable named `related_posts`. For example:

	---
	layout: post
	date: 2014-06-23 19:00:00 CEST
	title: Test3
	related_posts: [2014-06-23-test2, 2014-06-22-test1]
	---

	This is a test post.

So I can select the related posts manually.

**Comment by envygeeks** [comment]
Recap: The surface of this issue seems to be that `site.related_posts` does not return the proper object.  As far as the other part of this issue can you please file a unique ticket for the hash access of the posts @TheFox Thanks!

**Comment by TheFox** [comment]
The other part of this issue?

**Comment by envygeeks** [comment]
This is two issues: 1. You related_posts does not give objects and 2. You cannot access a post as a Hash `site.posts[post_name]`  these are each independent features but the surface of this ticket leads to 1 so 2 should be split into it's own ticket.
