### ISSUE TITLE
Link to a document inside collection via post_url

### ISSUE THREAD

**Issue by svetlanapuro** [jekyll/jekyll#2540]
Can I link to a document inside collection via `post_url`?

I try to do it like this:

```
[Name of Link]({% post_url /_collection/start/01 %})
```

But I get the following error:

```
Liquid Exception: Could not parse name of post "/_collection/start/01" in tag 'post_url'.
Make sure the post exists and the name is correct.
```

**Comment by iloveip** [comment]
Hello,

Has this been implemented already? I would also like to track it somewhere.

**Comment by parkr** [comment]
> Has this been implemented already?

Not presently, no. There are many unanswered questions about behavior. If you would like to open a pull request, I would be happy to take a look. The code is in `lib/jekyll/tags/post_url.rb`.

**Comment by jonathanthomas83** [comment]
Any news on being able to link to a document in a collection yet? Many thanks

**Comment by parkr** [comment]
> Any news on being able to link to a document in a collection yet? Many thanks

@jonathanthomas83 No, we have not created anything and I haven't seen a PR yet. If you have some time, I'd gladly look at any PR you're interested in submitting!

**Comment by parkr** [comment]
The `link` tag has been added in v3.2 which is the next release we expect to make. See the pull request: #4624.
