### ISSUE TITLE
Liquid Exception (No such file or directory) when using Pygments

### ISSUE THREAD

**Issue by winghouchan** [jekyll/jekyll#2551]
Howdy all!

Upon running `jekyll build` or `jekyll build --watch` I am getting the following error:

```
Liquid Exception: No such file or directory - python C:/Ruby193/lib/ruby/gems/1.9.1/gems/pygments.rb-0.5.0/lib/pygments/mentos.py in _posts/2014/06/28-Name-of-post.md
```

You might be wondering why I'm using Pygments 0.5.0. That's because when using the version shipped with Jekyll (0.5.4) I experience the problem in issue #2052 . The workaround described by @michaelplus was to revert to Pygments 0.5.0, however it is obvious it did not work for me.

Looking at the error, it states "No such file or directory", however when I follow the path in the error (C:/Ruby193/lib...) I find that the path is valid.

Searching on StackOverflow, several suggestions have been made, including reverting to Pygments 0.5.0 and using Python < 3.0.0. I have already reverted to Pygments 0.5.0 and my Python version is 2.7.7 .

Anyone have any ideas?

**Comment by nickedes** [comment]
Thanx :bomb: :relieved:

**Comment by philippneugebauer** [comment]
great tip (y)

**Comment by chc24** [comment]
@XhmikosR , can you explain in more detail how to change it exactly? I've been having this same problem. thanks.

**Comment by XhmikosR** [comment]
@chc24: this issue is fixed with pygments.rb 0.6.1, so just update your gems.

**Comment by frankmolenaar1986** [comment]
THIS IS THE BEST THANK YOU SO MUCH I AM SORRY FOR CAPSLOCK BUT AFTER 3 HOURS OF FIDGETTING AROUND THIS FIXED IT! THANK YOU @kleinfreund

**Comment by mslfire** [comment]
I have the same - issue/error - my pygments.rb-0.6.3 
HOW do you change the line?? DO YOU JUST CHANGE THE gem folder name which in my case is named 'yajl-ruby-1.2.1' to 1.2.1???

**Comment by kleinfreund** [comment]
@mslfire Can you see if your `PATH` environment variable has the following?

> Open Start menu and enter Environment variables.
> 
> If the value of path doesn't have ;C:\python27, add it directly behind.

**Comment by mslfire** [comment]
my - windows - environment variables PATH (as I understand it) is/has - the bottom link - I added ;C:\python27 but still have same - liquid exception error python

C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Hewlett-Packard\HP Performance Advisor;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT

**Comment by quannt** [comment]
Thanks. Adding the Pythod path did it for me. To be fair, the Jekyll guide could have been more clear about having Python installed.

**Comment by kleinfreund** [comment]
@envygeeks That should be locked as well, I think.

**Comment by envygeeks** [comment]
Hello. This ticket is being locked because it is stale and further comment here is no longer beneficial. Please create a new ticket with your bug or feature request and link back to this ticket. This will help us better manage your issue. If this is a question then please ask your question at https://talk.jekyllrb.com rather than on this ticket system.

Thanks!
