### ISSUE TITLE
Liquid tags in SASS no longer work with version 2.1.0

### ISSUE THREAD

**Issue by travisneilson** [jekyll/jekyll#2573]
Hi! I was using liquid tags in my SASS compiled by Jekyll and it worked famously. But in 2.1 they no longer work.

I'm not sure if this feature broke, or if the way you go about it changed.

Here is the file I'm referring too: https://github.com/DevTips/Artists-Theme/blob/master/assets/css/all.sass
Lines 13-15

(I reverted to Jekyll 2.0.3 and it works fine again...)

**Comment by starbuck451** [comment]
I've found I can access front-matter by including it in an include:
```
$brightColor:{{ page.fillcolour }};
```
And then including that include in my scss file.
```scss
{% include sassinclude.scss %}
```
