### ISSUE TITLE
Jekyll reading image as a post

### ISSUE THREAD

**Issue by madhur** [jekyll/jekyll#2592]
I faced a pecuilar issue where Jekyll is trying to interpret an image as a post.

I created an `img` folder under `_posts` and copied an image named `2014-12-27-image.png`

Jekyll build fails with following error:

```
 Liquid Exception: invalid byte sequence in UTF-8 in _posts/imgs/2014-12-27-image.png
jekyll 2.1.1 | Error:  invalid byte sequence in UTF-8
```

In my .yaml it has markdown_ext set as txt,md. Why is it trying to read a .png file as text?

Note: This issue only occurs if image is named as `yyyy-mm-dd-something.png`

**Comment by envygeeks** [comment]
Asking again if this is still an issue.

**Comment by huangjinhui** [comment]
i'm afraid yes... it's still happening
```
huang@huang--T400:~/Public/huangjinhui.github.io$ jekyll serve
Configuration file: /home/huang/Public/huangjinhui.github.io/_config.yml
            Source: /home/huang/Public/huangjinhui.github.io
       Destination: /home/huang/Public/huangjinhui.github.io/_site
      Generating... 
Error reading file /home/huang/Public/huangjinhui.github.io/_posts/images/2015-08-26-19-network-setting.png: invalid byte sequence in UTF-8 
jekyll 2.5.3 | Error:  invalid byte sequence in UTF-8
```

**Comment by huangjinhui** [comment]
my current workaround is to create a `image` folder under my local repository,  and link images using 
```
![]({{ BASE_PATH }}/images/2015_08_26/network-setting.png)
```

and it'll work.

**Comment by parkr** [comment]
@huangjinhui Would you mind trying the latest beta? It contains fixes for this IIRC.

**Comment by huangjinhui** [comment]
@parkr 
i've installed the newest jekyll, but the problem seems still there:

by the way, i'm using **jekyll-bootstrap**, maybe it's their fault ? :) 

```
[huang@localhost testJekyll]$ jekyll serve
Configuration file: /home/huang/Public/testJekyll/_config.yml
            Source: /home/huang/Public/testJekyll
       Destination: /home/huang/Public/testJekyll/_site
 Incremental build: enabled
      Generating... 
Error reading file /home/huang/Public/testJekyll/_posts/images/2015-08-28-03:01:42-test.png: invalid byte sequence in UTF-8 
  Liquid Exception: invalid byte sequence in UTF-8 in _posts/images/2015-08-28-03:01:42-test.png/#excerpt
jekyll 3.0.0.pre.beta8 | Error:  invalid byte sequence in UTF-8
```

**Comment by sedouard** [comment]
Hey there! I'm having this issue too. I'm in a unique circumstance where I really must have my image content within `_posts/` as we want to have generate our blob from two separate git repositories using sub modules. However even with v3.0.1. Is this intended behavior?

**Comment by gukii** [comment]
same here with jekyll 3.4.0 on osx 10.12.3

Error: could not read file ... path to jpg inside _posts ..  invalid byte sequence in UTF-8

/Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:232:in `split': invalid byte sequence in UTF-8 (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:232:in `tokenize'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:122:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/template.rb:108:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:11:in `block in parse'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:47:in `measure_time'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/liquid_renderer/file.rb:10:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/renderer.rb:129:in `render_liquid'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/renderer.rb:82:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:452:in `block (2 levels) in render_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:450:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:450:in `block in render_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:449:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:449:in `render_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:190:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:69:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/command.rb:26:in `process_site'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:63:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:34:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/exe/jekyll:13:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
