### ISSUE TITLE
Strange error when building in drone CI

### ISSUE THREAD

**Issue by jwmarshall** [jekyll/jekyll#2624]
I've been trying to build my jekyll pages in a new CI environment (drone.io) and for some reason I keep getting this very strange error. I've done the builds manually within the same docker container and get no errors. Is this possibly related to some LANGUAGE/LC_ALL environment variables missing?

I originally thought this might be related to using ruby 2.1, but since moving back to the 1.9 branch I get the same error. I've never seen the error before and there dont appear to be any mentions of it in my google searches.

`/root/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/jekyll-2.0.3/lib/jekyll/page.rb:35:in`initialize': undefined method `default_proc=' for "this --- is correct":String (NoMethodError)`

**Comment by maban** [comment]
For anyone else who comes across this same error but excluding the directories didn't work, I updated ruby and jekyll just to make sure I was definitely on the most recent version and that let me build the site.

+1 to @albertogg's suggestion of adding those exclusions to the site template (if it's still likely to be a problem for people using the latest version who may also have the js-yaml node module on their system).

**Comment by maban** [comment]
Another thing to try for anyone getting the same error: restart terminal.

**Comment by anasant** [comment]
Ran into the same issue. Updated Jekyll, ran `bundle install`. Excluding `node_modules` in `_config.yml` fixed the issue for me!
