### ISSUE TITLE
Add swift syntax pigments highlighting 

### ISSUE THREAD

**Issue by kostiakoval** [jekyll/jekyll#2631]
Add support for new Apple programming language, Swift

**Comment by kylejm** [comment]
@parkr as I understand, the latest `github-pages` gem has pygments.rb 0.6.0, but my Swift code still isn't getting highlighted. I've been searching around for some way to get syntax highlighting for Swift when using Jekyll with GitHub Pages but have been unsuccessful. Is it possible at the moment or are we still waiting for GitHub's syntax highlighter to come along?

**Comment by parkr** [comment]
@kylejm No, Swift syntax highlighting should be working! Which version are you using? Try `bundle show` and paste the output. Are you using the highlight tag, or backtick code blocks?

**Comment by kylejm** [comment]
Do I have to run `bundle show` while in a certain directory? I got:

```
$ Could not locate Gemfile or .bundle/ directory
```

Using the highlight tag. [Here's the post](https://raw.githubusercontent.com/kylejm/kylejm.github.io/master/_posts/2015-07-02-APIs-Closures-Parameter-Types.md).

**Comment by parkr** [comment]
Are you not using a `Gemfile`? I'd recommend using one whenever you use Jekyll.

Looks like it _is_ highlighting properly, but the classes either don't have CSS properties, or they're very subtle. Notice the bold and non-bold in the first few examples? It looks like `self` and `"strings"` are colored. I think this is a matter of tweaking the syntax highlighting CSS.

![screen shot 2015-07-02 at 9 52 44 am](https://cloud.githubusercontent.com/assets/237985/8482739/6374a238-20a0-11e5-9457-010da68c849d.png)

**Comment by kylejm** [comment]
Sorry, I don't speak much ruby. I've only installed the github-pages gem and used it from there. I'll check it out though. Any pointers?

Ah awesome. My silly error. Sorry and thank you so much! Could you point me in the direction of a good CSS syntax highlighting template/file?
