### ISSUE TITLE
Pretty indent

### ISSUE THREAD

**Issue by jcubic** [jekyll/jekyll#2640]
Is it possible to have indent from before `{% include` to be inserted in each line of included partials? Basically I'm asking if it's possible to have pretty printed html as output? Using code from `jekyll new` I've got effect like simple string::replace so indent is added to first line of included partial.

**Comment by jcubic** [comment]
I've decide to run [tidy-html5](https://github.com/htacg/tidy-html5) on all files outputed by jekyll to have proper indent.

**Comment by PierBover** [comment]
Unfortunately tify-html5 [doesn't support SVG](https://github.com/htacg/tidy-html5/issues/70) or other modern features such as block elements inside links.

> line 68 column 25 - Warning: missing </a> before <div>

Anyone found a better option to deal with Liquid's indentation of includes?

**Comment by jcubic** [comment]
It work fine for my case but I have basic html.

**Comment by DirtyF** [comment]
There's a plugin for that; https://github.com/apsislabs/jekyll-tidy
