### ISSUE TITLE
paginator only available in index.html

### ISSUE THREAD

**Issue by choxi** [jekyll/jekyll#267]
I wanted to make mysite.com/blog list my posts and just have mysite.com be a landing page. it looks like you can only use the paginator template data in index.html:

```
def self.pagination_enabled?(config, file)
    file == 'index.html' && !config['paginate'].nil?
end
```

This is in https://github.com/mojombo/jekyll/blob/master/lib/jekyll/generators/pagination.rb. Is there a reason why it's limited to index.html?

**Comment by GloverDonovan** [comment]
Also experienced the same problem!

**Comment by envygeeks** [comment]
This ticket is being locked. If you have an issue (or feature request) please file a new ticket instead of practicing the art of necromancy. It has hard to maintain actual issues against comments if this happens.
