### ISSUE TITLE
Liquid Exception: undefined method `[]' for nil:NilClass in _posts/2014-08-01- welcome-to-jekyll.markdown

### ISSUE THREAD

**Issue by Bouhoum** [jekyll/jekyll#2678]
Hello, I'm a newbie to jekyll After I run Jekyll serve I got this problem

``` text
Notice: for 10x faster LSI support, please install http://rb-gsl.rubyforge.org/
Configuration file: D:/Work/Test Jekyll/tutorial-test/_config.yml
            Source: D:/Work/Test Jekyll/tutorial-test
       Destination: D:/Work/Test Jekyll/tutorial-test/_site
      Generating...
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:164
: warning: cannot close fd before spawn
'which' is not recognized as an internal or external command,
operable program or batch file.
  Liquid Exception: undefined method `[]' for nil:NilClass in _posts/2014-08-01-
welcome-to-jekyll.markdown
jekyll 2.2.0 | Error:  undefined method `[]' for nil:NilClass
```

I'm on windows
Any idea why ?
Cheers !

**Comment by christiantype** [comment]
I wasn't receiving this error a few days ago until today when I created a new project. Any idea why?

**Comment by grobmeier** [comment]
I have the same issue, no idea why for now. The highlighter settings did not help.

**Comment by DirtyF** [comment]
@grobmeier What does your error message look like ? Are you using LSI ? (`lsi: true` in your `_config.yml `)?

**Comment by grobmeier** [comment]
@DirtyF I am sorry for the noise, I think it was a mess I caused myself. Running jekyll with --trace helped me finding the root cause, and now it's working. To be more concrete, I am using a git submodule for some content which was not initialized correctly. The plugin then was accessing a null object
