### ISSUE TITLE
Make _includes directory configurable

### ISSUE THREAD

**Issue by minad** [jekyll/jekyll#2684]
All the other directories are configurable

**Comment by fniephaus** [comment]
@parkr I don't really understand why adding more configuration settings is a problem for beginners. They can still start with a very basic `_config.yml`.
On the other hand, things like this limit power users that like to be in full control over their site's structure.

Maybe Jekyll needs two documentations, one for beginners and one for advanced users. As an advanced user, I wouldn't even mind if I had to read [rubydoc](http://www.rubydoc.info/github/mojombo/jekyll/Jekyll) for finding out more about advanced/hidden features.

**Comment by parkr** [comment]
My comment was from last August. I think it'd be fine to add, as long as it's rock-solid and has no security problems.

**Comment by liquidvisual** [comment]
This would be immensely useful. +1
