### ISSUE TITLE
Automatically generate anchor tags for all headings?

### ISSUE THREAD

**Issue by kortina** [jekyll/jekyll#2690]
Is it possible to configure jekyll so that all headings are assigned anchor tags?  Eg,

```
### Some Heading
```

would yield

```
<a name="some-heading"></a><h3>Some Heading</h3>
```

If this is not a feature, do you think this is something that jekyll users would want and be open to seeing an implementation submitted as a pull request?

**Comment by bryanbraun** [comment]
Some markdown processors (like kramdown & redcarpet) can generate IDs but they typically don't add the anchor icon into your html. There are a few small javascript utilities that can add the anchors also, like [AnchorJS](http://bryanbraun.github.io/anchorjs/) (which I wrote) and the jQuery-based [anchorific.js](http://renaysha.me/anchorific-js/#html-structure).

**Comment by reinink** [comment]
Going off @parkr's suggestion, you can do something similar with some jQuery:

```js
$('.h2,h3,h4,h5,h6').filter('[id]').each(function () {
    $(this).html('<a href="#'+$(this).attr('id')+'">' + $(this).text() + '</a>');
});
```
