### ISSUE TITLE
Can you have a custom _includes directory?

### ISSUE THREAD

**Issue by jimniels** [jekyll/jekyll#2698]
[The documentation](http://jekyllrb.com/docs/configuration/#default-configuration) says I can configure  the `_plugins` and `_layouts` directories. Currently, I am creating a jekyll site that would employ shared templating and CSS files across projects. So I would like to have something like `_sharedTemplates` in each project's root (a git submodule) which would contain the `_layouts` and `_includes` folders, while `_posts`, `_data`, etc are all unique to each jekyll project.

However, I can't seem to have a custom configuration for the `_includes` directory. In `_config.yml` I set the following: `layouts: ./_sharedTemplates/_layouts` which works for layouts. But for layouts that use includes, I get an error because it's still looking in the root directory for `_includes` when really I want it to be looking in `_sharedTemplates/_layouts`.

I can't fix this in liquid either, that I know of. For example, if I do:

`{% include _sharedTemplates/_includes/head.html %}`

Jekyll is still looking in `_includes` in the root directory first, which makes me get this error:

`Liquid Exception: Included file '_includes/_sharedTemplates/_includes/head.html' not found in ./_sharedTemplates/_layouts/default.html
jekyll 2.2.0 | Error:  Included file '_includes/_sharedTemplates/_includes/head.html' not found`

Is there no way to set a custom directory for includes? Seems odd to be able to set a custom directory for layouts but not for includes ...

**Comment by CelticParser** [comment]
```
# _config.yml
layouts_dir     : ./_sharedTemplates/_layouts
includes_dir     : ./_sharedTemplates/_includes
```
