### ISSUE TITLE
Update how highlighting works

### ISSUE THREAD

**Issue by mattr-** [jekyll/jekyll#2715]
Not sure where we want to keep potential 3.0 work, but wanted to capture this relevant bit of info from #2709 regarding some work that we need to do for highlighting.

> In general our syntax highlighting needs a huge overhaul. We have Pygments and Rouge injected into places within Jekyll that would make Robert Louis Stevenson blush. It's an absolute mess. Most of our markdown converters find all the `<pre>` tags and use gsub (can you believe it?!) to provide some sort of highlighting. Few of the markdown libraries we use offer support for plugins, so we're a little dead in the water. We've been asked to match what GitHub is doing and we've bent over backwards to accomplish that. Unfortunately, it's left us in this present quandary.

> I think the path going forward is to ask markdown libraries to give us some means to work with their internal AST's (or whatever it is they build) to manipulate the code and pre tags to our liking. I have a strong urge to rip out all syntax highlighting in everything but the {% highlight %} tag and ship highlighting when it's ready from the Markdown library side (i.e. kramdown, RDiscount, RedCarpet).

> We may be able to use HTML Pipeline to port GitHub's Markdown approach, but we'll need a bit of assistance from them to put it all together in a useful way.

**Comment by envygeeks** [comment]
I have a question on this topic: Why don't we use something like ContentPipeline (my library) or HTMLPipeline (Github's) which would make rendering much cleaner for everybody? Mine normalizes everything from every client and gives  you access to highlighting, I don't know whether HTMLPipeline does, but in general we could clean up the whole mess that is rendering by just offloading it onto an external plugin that is designed to do content.

**Comment by envygeeks** [comment]
BTW, I'd be willing to hand over the source to content-pipeline if you wanted to use that in Jekyll (we don't use it on many of my projects and it was explicitly designed for Jekyll pretty much...)

**Comment by parkr** [comment]
@envygeeks I dig the idea of using a Pipeline. We're already using HTMLPipeline for jekyll-mentions and jemoji. Does it depend on Nokogiri, though? My big worry is including C extensions again.
