### ISSUE TITLE
Support using serve with both --watch and --detach

### ISSUE THREAD

**Issue by nicolasmccurdy** [jekyll/jekyll#2725]
I vaguely remember seeing a changelog mention this this was not possible, and that the bug would be fixed soon. However, as far as I'm aware this is still an issue.

**Comment by envygeeks** [comment]
I think this should be closed in favor of the newer ticket, there is nothing here not stated in the other or by reference to this ticket so there is no reason for this to stay open no?

**Comment by nicolasmccurdy** [comment]
There is definitely an overlap, though I intended this ticket to be a reminder of a missing feature and the newer ticket to note the issue in what is reported.

**Comment by envygeeks** [comment]
Gonna go ahead and close this in favor of the other ticket and /cc #3030

**Comment by nicolasmccurdy** [comment]
I like having the warning that it isn't supported, but would it be possible to support both watching and detaching at the same time?

**Comment by jerzygangi** [comment]
@envygeeks This ticket isn't the same as #3030, and so it should be reopened. This ticket is a feature request for both --watch and --detach simultaneously, as @nicolasmccurdy has advanced. #3030 is a bug in the output furnished the user. These are two separate issues.

**Comment by nicolasmccurdy** [comment]
Thanks @jerzygangi, my other issue was kind of vague but I would like to keep this one open.
