### ISSUE TITLE
Deprecation notice for relative permalinks in noisy

### ISSUE THREAD

**Issue by zpao** [jekyll/jekyll#2744]
The notice says "Starting in 2.0...", however I'm now using 2.2 and explicitly opting out of absolute permalinks (not depending on the previous default).

Should this message get removed now that we're past 2.0? Or should it at least be relaxed when specifically opting out?

**Comment by parkr** [comment]
@alfredxing, do you have time for this in the next week or so?

**Comment by alfredxing** [comment]
@parkr Sure, I have exams but can probably work on this when I'm taking breaks from studying.

I found the underlying code, but I'm wondering whether we *should* remove the warning, if its sole purpose is to be annoying to get users to switch to absolute permalinks.

**Comment by parkr** [comment]
Hm, that's true. I'm not sure if we can say opt-in or opt-out anymore -- maybe we just remove relative permalinks support altogether... i dig the feature myself (easily move files around etc) but it is prone to confusion and conflict.

**Comment by alfredxing** [comment]
Addressed in above PR!

**Comment by parkr** [comment]
:tada:
