### ISSUE TITLE
cannot close fd before spawn 'which' is not recognized

### ISSUE THREAD

**Issue by parisio** [jekyll/jekyll#2789]
Sorry if this overlaps with previously closed issues but I have yet to find a definitive solution anywhere.

Since installing Jekyll (2.2) on Windows 7 according to the special instructions on jekyllrb.com, I have been getting the following warning upon running jekyll serve: 

```
warning: cannot close fd before spawn
'which' is not recognized as an internal or external command [...]
```

 I initially thought it was a posix-spawn issue (see full excerpt below), and filed an issue on their page where they suggested that this is an issue between versions of Jekyll and pygments.rb. I then tried the often mentioned downgrade to pygments.rb 0.5.0, but it appears that no longer works. I just saw the filed issue where parkr mentioned that the current Jekyll version now uses pygments.rb 0.6.0. Do you have a suggestion as to how we can resolve the warning while still using pygments? Would downgrading to Jekyll 1.4.2 pose more significant problems for the future?
Thanks.

Full cmd excerpt:

```
my-blog $ jekyll serve --watch
Notice: for 10x faster LSI support, please install http://rb-gsl.rubyforge.org/
Configuration file: C:/dev/projects/my-blog/_config.yml
            Source: C:/dev/projects/my-blog
       Destination: C:/dev/projects/my-blog/_site
      Generating...
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:164
: warning: cannot close fd before spawn
'which' is not recognized as an internal or external command,
operable program or batch file.
                    done.
 Auto-regeneration: enabled for 'C:/dev/projects/my-blog'
Configuration file: C:/dev/projects/my-blog/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```

**Comment by fkostadinov** [comment]
I am running Jekyll 2.5.3 on my local machine (Windows 7) and I still receive this error message. Running <code>gem update</code> did not help. I only used _pygments_ because _rouge_ on GitHub did not work for any reasons (see this post: http://fabian-kostadinov.github.io/2015/01/04/problems-using-syntax-highlighting-with-pygments-on-windows/). Any suggestions?

**Comment by ZhuFengdaaa** [comment]
I have the completely same problem. Maybe it is caused by the incompatibilities between pygments and windows. Now I use rouge to preview on local and switch to pygments to push to the remote. [reference here](http://nathantreid.com/setting-up-this-blog/)
