### ISSUE TITLE
Include Jekyll plugins in Gemfile

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#2797]
Is there a better way to automatically include all the gems from `_config.yml` in my `Gemfile`?

``` ruby
jekyll = YAML.load_file('_config.yml')
jekyll['gems'].each { |requirement|
  gem requirement
}
```

**Comment by nickmccurdy** [comment]
I tend to only deploy Jekyll sites to GitHub Pages. If you use the [gem](https://github.com/github/pages-gem) it will install all the plugins supported on Pages (but you still have to list them in `_config.yml` for development).
