### ISSUE TITLE
Highlight does not work with django templates

### ISSUE THREAD

**Issue by dator-zz** [jekyll/jekyll#281]
Hi,

I begin to work with jekyll and i tried to highlight some django templates with {{ and {% tags.

But it does not work it just render html , not tags :s

Any ideas ?

By the way i tried to use html+django in in highlight :

```
{% highlight html+django %}
```

but the regex does not catch all html+django, just html :)
You should use => ([\w+]+)\s?([\w\s=]+)\* no?

Thanks a lot !

**Comment by Pawamoy** [comment]
I am using Jekyll 3.1.2 and this trick does not work anymore. It was working fine with Jekyll 2.2.0.
My `html+django` code block is rendered without any syntax highlighting.
