### ISSUE TITLE
C:/Ruby193/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.6/lib/posix/spawn.rb:162: warning: cannot close fd before spawn

### ISSUE THREAD

**Issue by ahyield** [jekyll/jekyll#2815]
After runing Jekyll serve  : 
<code>C:/Ruby193/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.6/lib/posix/spawn.rb:162: warning: cannot close fd before spawn
  Liquid Exception: No such file or directory - /bin/sh in _posts/2014-08-25-welcome-to-jekyll.markdown
                    done.</code>
on windows, tried this : [#2678](https://github.com/jekyll/jekyll/issues/2678)
it worked, but the syntax highlight is ugly :(.
i tried the roll back pygment to 0.5.0 0.5.2 , but it seems that jekyll running the 0.6.0 now.
every thing is installed correctly tho.

**Comment by Chinquan** [comment]
The similar problem happened to me either. Here is what happens to me:

```bash
D:/Ruby193/lib/ruby/gems/1.9.1/gems/posix-spawn-0.3.9/lib/posix/spawn.rb:164: warning: 
cannot close fd before spawn
'which' is not recognized as an internal or external command,
operable program or batch file.
                    done.
 Auto-regeneration: disabled. Use --watch to enable.
```
I compared my `_config.yml` with the default `_config.yml` which is generated by jekyll to find `markdown: ` may be the cause. In my `_config.yml` it was `markdown: redcarpet`, while the default is `markdown: kramdown` .  By changed this:

```bash
      Generating...
                    done.
 Auto-regeneration: disabled. Use --watch to enable.
```

I don't know why, but **it works for me.**
