### ISSUE TITLE
Error: Pygments.rb returned unacceptable value - caused by timeout?

### ISSUE THREAD

**Issue by mchelen** [jekyll/jekyll#2835]
I keep getting an error when trying to build a site on an old netbook (1.5ghz atom, 1gb ram):
```
While attempting to convert the above code, Pygments.rb returned an unacceptable value.
This is usually a timeout problem solved by running `jekyll build` again.
```
Re-running `build` shows the same error. It doesn't seem to be a problem with the site itself, because it builds fine on other, faster systems.

Is there any way to increase the timeout for `pygments.rb`? Or could this be cause by some other problem?

**Comment by parkr** [comment]
Closing as abandoned. Please use Rouge if this persists.
