### ISSUE TITLE
Layout yaml variables missing on collections

### ISSUE THREAD

**Issue by danielfdsilva** [jekyll/jekyll#2836]
Imagine the following layout structure:

**_layouts/entry.html**

```

---
layout: base

var1: Hello
var2: World

---
My content
```

**_layouts/base.html**

```
...
<body>
{{ page.var1 }} {{ page.var2 }}
{{ content }}
</body>
...
```

If the content being rendered is a post or a page, the variables that I defined in the layout's yaml front matter are available to be used. However, when rendering a collection they are not part of the page object and therefore can't be used.
Is this a normal behaviour or is it a bug?

**Comment by mdotasia** [comment]
I ran into the same issue. If I set a YAML variable `var` in a layout and apply the layout to a page or post, I can access `var` in `page.var`, but not `layout.var`. When applying the variable to a collection, it is the other way round, i.e. I can access `var` in `layout.var` but not in `page.var`.

I think `var` should be in `layout.var` to be consistent. It is not clear to me why posts behave like pages, even though they are part of a collection.

**Comment by danielfdsilva** [comment]
This just happened to me again. Can this be re-opened or is this the correct behavior?

Would it help if I setup a repo illustrating the problem?

**Comment by parkr** [comment]
I think I see the ideal behaviour you're looking for, I'm just not sure if it's what we should do, especially if it breaks sites with 3.0.

**Comment by danielfdsilva** [comment]
I thinks the ideal behavior would be to have the variables available under `page.` both for posts and collections.
If the rest stays the same (i.e. also available in the `layout.`) it shouldn't break anything.

If it is preferable they can be under `layout.`. The important thing here is that it is streamlined across types (posts, collections, simple pages)

**Comment by abeMedia** [comment]
+1

**Comment by parkr** [comment]
@abeMedia `layout.` is in Jekyll 3.

**Comment by abeMedia** [comment]
My bad... hadn't updated for a while!

**Comment by dalanmiller** [comment]
Question that I think is related to this issue. If I set YAML Front Matter in a layouts file `_layouts/post.html` like so:
```
--- 
layout: default
body_class: blog
---
```

I should be able to access `body_class` via `page.body_class` in the `_layouts/default.html` file correct? This isn't happening currently in Jekyll 3.0.1 and the value results in `nil`.
