### ISSUE TITLE
jekyll docs should deploy to /tmp

### ISSUE THREAD

**Issue by mrueg** [jekyll/jekyll#2840]
$> jekyll docs                                                                                                                                                          :(
Configuration file: /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.3.0/site/_config.yml
            Source: /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.3.0/site
       Destination: /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.3.0/site/_site
      Generating... 
jekyll 2.3.0 | Error:  Permission denied - /usr/lib64/ruby/gems/1.9.1/gems/jekyll-2.3.0/site/_site
jekyll docs  28.64s user 0.11s system 99% cpu 28.896 total

It would be nice if calling jekyll docs would try to deploy _site to /tmp instead.

**Comment by parkr** [comment]
Fixed by jekyll-docs gem in 3.x and greater. Patch in the works for 2.x: #4253
