### ISSUE TITLE
"Invalid syntax for include tag" for includes using variables in parameters

### ISSUE THREAD

**Issue by haschek** [jekyll/jekyll#2844]
```
Liquid Exception: Invalid syntax for include tag: ' alt='{{ contenttitle | strip_html | xml_escape }}' class='fullsize' Valid syntax: {% include file.ext param='value' param2='value' %} in _includes/maincontent_header.html, included in _layouts/page.html
jekyll 2.0.0 | Error:  Invalid syntax for include tag:

  ' alt='{{ contenttitle | strip_html | xml_escape }}' class='fullsize'

Valid syntax:

  {% include file.ext param='value' param2='value' %}
```

First I thought this error depends on the liquid version but it's shown first with Jekyll 2.0.0 (without changing the liquid version). It worked to use vars in includes until Jekyll 1.5.1. In later Jekyll versions (e.g. 2.3.0) the var is even replaced by its value in the error message but it still doesn't work again.

It's probably one of the most important features that includes can used dynamically with vars.

**Comment by phillipadsmith** [comment]
Subscribing.

**Comment by kamlekar** [comment]
Subscribed. This should be actually a bug.

**Comment by envygeeks** [comment]
Can you re-explain what you would like to see so we don't have to dig through a dozen tickets.  Thanks!

**Comment by kamlekar** [comment]
Hi @envygeeks,

I am unable to present the code as the below syntax:

         {% include "_head.html" %}

I am assuming that somehow, jekyll is trying interpret it even when I mentioned it by adding 4 spaces.

**Comment by envygeeks** [comment]
Easy problem to solve!  Thanks for the example.

**Comment by kamlekar** [comment]
Nice, you guys rock!!

I hope you will provide the solution here to help me :)

**Comment by haschek** [comment]
@envygeeks No, the problem of @kamlekar is actually not the issue that is described in this ticket.

First, the include-after-4-spaces-problem is related to content parsers like Markdown, generally it should be possible to have an valid include on every place in the template or document.

Second, the issue I described here first is about using variables in include attributes, see https://github.com/jekyll/jekyll/issues/2844#issue-41397182. I can say if this issue is still there in a recent version of jekyll because I still use 1.5.1 because of this issue. I could check this later.

**Comment by envygeeks** [comment]
This is still a problem because we don't run values through the context.  The first one shouldn't be a problem because we parse for Liquid before markdown don't we @parkr?

**Comment by parkr** [comment]
Yep, we [run through liquid before markdown](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/renderer.rb#L51-L56).

**Comment by kamlekar** [comment]
So how can I exactly fix my problem which I explained above? (_I have no idea about these things_)
