### ISSUE TITLE
--baseurl for build sub command

### ISSUE THREAD

**Issue by hugomrdias** [jekyll/jekyll#2874]
i know the `serve` has --baseurl option but if we dont use jekyll to serve locally you have no option to build with a different baseurl. 

i run jekyll from a gulp task to build everything and use browsersync to serve `_site`.
Locally i need `baseurl : ''` and for github pages i need `baseurl: '/projectname'` if i could run `jekyll build --baseurl ''` and leave the default for github pages would be perfect.

**Comment by adrianwhite** [comment]
Sorry to raise this long closed issue but I would find this very handy.
I have semi-automated deployment of mulitple versions of static sites served under different paths and it would be very useful to be able to change the `baseurl` when using `build`.
Does `serve` not just pass `baseurl` to `build` when using `serve --baseurl 'foo/baa'`?

**Comment by envygeeks** [comment]
@adrianwhite use multiple configurations.

**Comment by adrianwhite** [comment]
@envygeeks I already do. But multiple configurations is rather a blunt way of addressing the issue.

I'm implementing prototypes for testing etc. and it would be better to be able to pass the baseurl as this is used in a couple different places, not just Jekyll, to automatically deploy the site to a particular directory on a server and that path makes up part of the url.

e.g. 
baseurl = **served-directory/test-search**
directory on server = some/path/to/**served-directory/test-search**
url = http://example.com/**served-direcory/test-search**

If `serve` can build the site using `--baseurl` why can `build` not build the site with `--baseurl`

**Comment by envygeeks** [comment]
@adrianwhite I'll be honest I don't know the reasoning behind why, @parkr would know more but at this point I would suggest searching for an open ticket and if one doesn't exist open a feature ticket rather than doing ticket necromancy.  Adding the feature isn't that hard but opening a new ticket or responding to an open ticket will give it far more exposure.

**Comment by adrianwhite** [comment]
@envygeeks Ticket necromancy, I like it. 
Thanks for the help. I'll take your advice.
I'm sorry if I've broken ticket etiquette.

**Comment by parkr** [comment]
@adrianwhite No worries! Please do open a new issue and reference our discussion here. 😄
