### ISSUE TITLE
MultiMarkdown and Jekyll

### ISSUE THREAD

**Issue by hertze** [jekyll/jekyll#289]
Hi.

In my opinion, Fletcher Penney's MultiMarkdown (http://fletcherpenney.net/multimarkdown/) is the most complete, and reliable, parser for extended Markdown in existence. Right now it is being rewritten in C, making it possible to write a Ruby wrapper and then use it with Jekyll.

I've never been fond of Maruku, and Discount lacks a few features, such as footnotes. Please consider adding MultiMarkdown to Jekyll.

Joakim Hertze

**Comment by ickc** [comment]
@mojombo

I contacted Fletcher and this is what he said:

> I can't confirm what was done with the code in rpeg-multimarkdown.
> 
> There's not arbitrary code execution in MMD -- what purpose would it serve?
> 
> But any attempt to use MMD in another project should focus on MMD-5, not v3 which is significantly out of date at this point.
> 
> F-

So does it mean it can be merged?

cc @djungelvral

**Comment by parkr** [comment]
> So does it mean it can be merged?

@ickc No, we are not accepting new markdown converters for the core at this time.
