### ISSUE TITLE
Liquid: Filters for Arrays

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#2892]
Doing even basic operations with arrays is terrible. I'd love to be able to manipulate arrays more effectively. Some filter ideas:
- [ ] `shift`
- [ ] `unshift: val`
- [ ] `pop`
- [ ] `push: val`

Anything else?

/cc @benbalter  @fw42

**Comment by djacquel** [comment]
@parkr I've lost those files. Where are they ?

**Comment by narthur** [comment]
@parkr I feel like `pop` is still returning the remaining items after pop instead of the popped item itself. Is this the intended behavior?

**Comment by envygeeks** [comment]
@narthur looking at the code it shouldn't, file a bug and provide more source and examples.

**Comment by narthur** [comment]
@envygeeks Ok, will do. =)
