### ISSUE TITLE
page.path gives absolute path for document in collection

### ISSUE THREAD

**Issue by spyysalo** [jekyll/jekyll#2897]
In the document '_coll/entry.md', where `coll` is configured as a collection, `page.path: {{ page.path }}` renders as

```
page.path: /home/smp/jekyll/path-test/_coll/entry.md
```

instead of the expected

```
page.path: _coll/entry.md
```

the expected relative path is given for documents not in collections.

To replicate:
- `jekyll new path-test`
- create directory '_coll' and document '_coll/entry.md' containing `page.path: {{ page.path }}`
- add `coll` with `output:true` to `collections` in '_config.yml'
- `jekyll build`

Running jekyll 2.3.0 on ubuntu 12.04.

**Comment by wjdp** [comment]
Came across this today, when's it being addressed? (2908???)

**Comment by envygeeks** [comment]
@wjdp that's a ticket id, please ask your questions in #2908

**Comment by wjdp** [comment]
that seems very obvious now, cheers!
