### ISSUE TITLE
allow converters to run on files without YAML front matter

### ISSUE THREAD

**Issue by erisdev** [jekyll/jekyll#290]
I'd like to see support for converting files without YAML front matter. For instance, it would be nice to drop CoffeeScript libraries in my `js/` folder and have a custom-written converter automatically compile them to JavaScript in the destination directory. As it stands, I have to either prepend a header to any libraries I want to use or compile them myself each time I make a change to the source.

It would be wonderful if I could say `front_matter false` in my Converter subclass and get drop-in support for whatever CoffeeScript source I throw at it. Or, of course, any other source files I might want to compile without adding a header.

I would also be satisfied with a key in `_config.yml` that works similarly to `exclude` that would force Jekyll to run converters against a certain subset of my files, since I feel this might be more in line with the philosophy of the project.

**Comment by Ajedi32** [comment]
@mojombo

> This is a nice idea. The way I'd want to do it is to bind certain extensions to specific converters, and also have an option to set each of those to `:matching` or `:matching_with_header`. In this way you could customize your setup to your liking.

Did this ever happen? If not, is there an issue for it where I can follow the progress of this feature?
