### ISSUE TITLE
Relativity in Layouts

### ISSUE THREAD

**Issue by mecrouch** [jekyll/jekyll#2900]
So I love the new include_relative tag, but I'm a little confused as to its application in layouts. If I use the tag in one of my layouts, Jekyll appears to be looking for the included asset relative to the layout, not to the page that's being processed. Is this by design?

**Comment by tomjohnson1492** [comment]
I'm experiencing the same issue described in this thread. I have a layout called default.html in my layouts folder. In the same layouts folder, I add test.html. Then in my default.html layout file, I add `{% include_relative test.html %}` to include test.html inside the default.html file.

When I try to build the site, I get this error: 

```
Liquid Exception: Included file './test.html' not found in projects/jekyll-doc/layouts/default.html
```

Am I doing something wrong? Is this a known bug? 

One other note. I am using a different location for my layouts as defined in the configuration file: 

`layouts: projects/jekyll-doc/layouts`

I'm assuming this point shouldn't matter.

**Comment by kleinfreund** [comment]
Why was this closed without a statement?

Is `include_relative` just not working for layouts? Is there anything insight for a non-limited include like this:

```liquid
{% include css/main.css %}
```

**Comment by arthurattwell** [comment]
For reference, more detail on this issue in https://github.com/jekyll/jekyll/issues/3488
