### ISSUE TITLE
Jekyll serve --watch not recognizing and updating changes

### ISSUE THREAD

**Issue by javirivera** [jekyll/jekyll#2926]
I recently set up my github pages for my new website and installed bundler gem through the terminal and the git-hub pages gem. Since then the jekyll serve --watch has not been updating when I make a change to my code.

Thanks in advence for any help.

**Comment by dnl** [comment]
For future people coming across this.

 this issue for me was related (I suspect) to this: <https://github.com/thibaudgg/rb-fsevent/issues/10>

The case of a directory in the  "Auto-regeneration: enabled for ..." line was different than it was in the finder.

Renaming the incorrect dir, then renaming back, fixed it. (other possible solutions are listed here: <http://feedback.livereload.com/knowledgebase/articles/86239>)

**Comment by LukeMcGurdy** [comment]
I was having the same issue (git-hub pages gem on Win10) but jekyll --incremental seemed to do the trick

**Comment by sitecorian** [comment]
This article helped me with similar issue on Win10 with Jekyll 3.3.0. See "May not work" part: https://labs.sverrirs.com/jekyll//5-wdm-gem.html

**Comment by iddan** [comment]
Updates do not work for me at all.
macOS 10.12.3
ruby 2.4.1
jekyll 3.4.3
using the github-pages gem and bundler

**Comment by DirtyF** [comment]
@iddan I suggest you stick with ruby 2.3.3 for now (https://pages.github.com/versions/), Jekyll hasn't not been properly tests on ruby 2.4.x  yet.

**Comment by iddan** [comment]
So can you please update the ruby requirement?
https://rubygems.org/gems/jekyll/versions/3.3.1 :
 > REQUIRED RUBY VERSION:
 >\>= 2.0.0

**Comment by DirtyF** [comment]
@iddan got you #5983

**Comment by wraybowling** [comment]
Auto-regeneration isn't working for me with

- macOS 10.12.3
- ruby 2.3.3
- jekyll 3.4.3
not using the github-pages gem, and it doesn't seem to matter if I execute jekyll with bundler or not.

**Comment by ashmaroli** [comment]
@wraybowling `jekyll-admin v0.4.1` has the auto-regeneration disabled internally. Disable the plugin if you're using that particular version..

**Comment by wraybowling** [comment]
@ashmaroli WOW. Gosh I hope you didn't spend too long figuring that out, but that did the trick. Thank you!

**Comment by ashmaroli** [comment]
> I hope you didn't spend too long figuring that out

:smiley: I had encountered a similar issue on StackOverflow. So my first guess was on the plugin.. :wink:

**Comment by mikekok** [comment]
I'm facing the same problem on Elementary OS (it's Ubuntu based).
Jekyll doesn't automatically update changes, I have to manually reload the page.
I've tried everything, from force_polling to reinstalling the plugin, but nothing seems to work.

**Comment by ashmaroli** [comment]
@mikekok `jekyll-admin` no longer has that bug.. So that's not the issue.
You may need to "serve" your site with `--livereload` to have Jekyll refresh pages automatically.
If problems persist, please open a "new issue"
