### ISSUE TITLE
Highlight language as a variable

### ISSUE THREAD

**Issue by arronwoods** [jekyll/jekyll#2952]
Should it be possible to do this?

`{% highlight {{ language }} %}`

in the same way one can do

`{% include {{ file }} %}`

I just get the error:

> Liquid Exception: Syntax Error in tag 'highlight' while parsing the following markup: {{ example.format }} Valid syntax: highlight <lang> [linenos]

I'll see if my Ruby skills will stretch to submitting a pull request if this is something people would like/should be possible.

My use case is highlight code from information specified from _data, where the format could be json, bash or php, but I'd rather not use if/else.

**Comment by k-funk** [comment]
Would you still be open to a PR for this? I *may* have time to implement it. I'd follow an approach similar to way that the `IncludeTag` class does.

**Comment by envygeeks** [comment]
@k-funk I'm interested in the use-case here.

**Comment by k-funk** [comment]
I generate api docs dynamically for multiple languages.

URL: `example.com/docs/api/python.html`

Page: `python.html`

    ---
    layout: guide
    language: py
    ---
    ...
    {% include code_sample.html name="a_thing_my_api_does" %}
    ...

Include: `code_sample.html`

    {% highlight {{ page.language }} %}
      {% include guides/{{ include.name }}.{{ page.language}} %}
    {% endhighlight %}

That would be ideal.
Right now, my `code_sample.html` actually looks like this, with all of the `{%includes%}` being exactly the same:
```
{% comment %}Shoot me{% endcomment %}
{% case language %}

  {% when 'sh' %}
    {% highlight sh %}
      {% if include.printed_results %}
        {% include guides/{{ include.name }}.{{ page.language }} %}
      {% endif %}
    {% endhighlight %}

  {% when 'rb' %}
    {% highlight rb %}
        {% include guides/{{ include.name }}.{{ page.language }} %}
    {% endhighlight %}

  {% when 'py' %}
    {% highlight py %}
        {% include guides/{{ include.name }}.{{ page.language }} %}
    {% endhighlight %}

  {% when 'php' %}
    {% highlight php %}
        {% include guides/{{ include.name }}.{{ page.language }} %}
    {% endhighlight %}

  {% when 'java' %}
    {% highlight java %}
        {% include guides/{{ include.name }}.{{ page.language }} %}
    {% endhighlight %}

  {% when 'cs' %}
    {% highlight cs %}
        {% include guides/{{ include.name }}.{{ page.language }} %}
    {% endhighlight %}

{% endcase %}
```

**Comment by ChrisJefferson** [comment]
I also would like this functionality too.

My use case is using includes for extensions. I wanted to put a download link after each code snippet, but this doesn't work because `highlight` and the package `include_absolute` don't support variables.

```
{% highlight {{ include.lang }} %}
{% include_absolute {{include.file}} %}
{% endhighlight %}
[Download {{ include.file }}](/downloads/code/{{ include.file }})
```

**Comment by ashmaroli** [comment]
@ChrisJefferson, can you please add the expected HTML markup that would be generated for any two code snippet blocks, should the example you provided be supported..

**Comment by ChrisJefferson** [comment]
@ashmaroli : I'm not positive what you want..

Might be easier to say that given a file `code-link.html` containing:

```
{% highlight {{include.lang}} %}
{% include_absolute {{include.file}} %}
{% endhighlight %}
```

Then the line: 
```
{% include code-link.html lang="gap" file="proffunction.g" %}
```

Should be equivalent to just directly typing:
```
{% highlight gap %}
{% include_absolute proffunction.g %}
{% endhighlight %}
```

In practice, my `code-link.html` is more complicated, so I don't want to have to keep writing it over and over.

In general, my preference is to write small extensions to jekyll using `include` in this kind of way, so it would be nice to be able to use variables everywhere (but this is the only problem I've hit so far)

**Comment by ashmaroli** [comment]
okay.. @ChrisJefferson, I understand what you intend to do, now..

**Comment by ashmaroli** [comment]
Have you tried using assigns? 
It should work, in theory..
```
{% assign lang = include.lang %}
{% assign file = include.file %}

{% highlight lang %}
{% include_absolute file %}
{% endhighlight %}
```
(If you've tried this in the past and never got it to work, then pls dismiss the idea ..)

**Comment by k-funk** [comment]
@ashmaroli I'm fairly certain that that won't work. You can't use variables as an argument to `highlight`.

**Comment by baka-san** [comment]
Was this ever solved? I also want to use {% highlight {{ language }} %}.

**Comment by parkr** [comment]
@baka-san No, it's not possible to use variables in arguments to the `{% highlight %}` tag.
