### ISSUE TITLE
`published:false` doesn't seem to work with collections?

### ISSUE THREAD

**Issue by gjtorikian** [jekyll/jekyll#2956]
Setting `published: false` still renders my collection. It seems as though neither that, nor setting `output: false`, will do what I want it to: not create a resulting file (for just one collection item).

**Comment by mvaneijgen** [comment]
Why is this closed? Is it fixed? If so what can I do to not publish a collection via the `YAML` front-matter. First I thought maybe `published` was a new feature, but I updated to the latest version of `Jekyll` and still no luck.

**Comment by pathawks** [comment]
@mvaneijgen https://jekyllrb.com/docs/collections/

`output: false`

**Comment by mvaneijgen** [comment]
@pathawks This only works in the config file and will result in all my collections not being published. I am looking for a way to only disable one post/collection without deleting the content.

**Comment by lifeisfoo** [comment]
I've tried (jekyll 3.1.3) with the `output` and the `published` front matter, but nothing works. See also [my question on SO](http://stackoverflow.com/questions/37996115/collections-and-drafts-or-non-outputting-elements/37997886) (I've found this issue only after).
