### ISSUE TITLE
Utils#slugify strips all non-ASCII letters from string

### ISSUE THREAD

**Issue by hazzik** [jekyll/jekyll#2965]
The commit 4adc35aaf36ee30a7fef708950bbb2958d2a7681 reverted Utils#slugify to old implementation, which strips all non non-ASCII letters from the string. And, unfortunately, this is used by jekyll/jekyll-archives#24 to generate slugs for tags and categories, which can contain non ASCII letters.

Ideally I would like to see usage of StringEx#to_url here as it does some nice things like transliterations

/cc @kansaichris

**Comment by Mikaela** [comment]
I am not sure if this is this issue, but Jekyll appears to strip `🂱` and probably many other Unicode characters from text I type during `jekyll serve`.

I am using redcarpet and you can find my [_config here.](https://github.com/Mikaela/mikaela.github.io/blob/master/_config.yml)

**Comment by parkr** [comment]
I believe this is fine in Jekyll 3. If not, please open a pull request which modifies the relevant patterns to allow for UTF-8 characters with proper tests. Thanks!
