### ISSUE TITLE
Enhancement: "data collections"

### ISSUE THREAD

**Issue by phillipadsmith** [jekyll/jekyll#2983]
Howdy Jekyll Folks,

(Apologies if this idea isn't fully baked, or the right place to ask -- just want to get it out of my head while I'm thinking of it...)

I've been working a bit with [collections](https://github.com/phillipadsmith/everycandidate.org/tree/master/_toronto_city_council) and [data files](https://github.com/phillipadsmith/everycandidate.org/blob/master/_data/toronto_council.csv) recently and I'm curious if anyone else would find the idea of a "data collection" to be useful.

A data collection would simply be a collection where the source for the output of the collection is a data file. For example, where a CSV (or JSON, or YML) file [like this](https://github.com/phillipadsmith/everycandidate.org/blob/master/_data/toronto_council.csv) could result in the same output that is currently generated by [these files](https://github.com/phillipadsmith/everycandidate.org/tree/master/_toronto_city_council). 

Thinking it through a bit, there would likely need to be a way to specify what layout to use to output the collection. Perhaps that could be done in the configuration file, e.g.:

```
collections:
  toronto_city_council:
    output: true
    data: toronto_council.csv
    layout: candidate.html
    permalink: /:some/:val/:from/:data/:file.html
```

The use case, as [demonstrated here](https://github.com/phillipadsmith/everycandidate.org/blob/master/_scripts/generate_candidates.pl), is that I'm often generating [hundreds of stub files for a collection](https://github.com/phillipadsmith/everycandidate.org/tree/master/_toronto_city_council) from the [same CSV](https://github.com/phillipadsmith/everycandidate.org/blob/master/_data/toronto_council.csv) that is later used to [populate much of the data for that collection's output](https://github.com/phillipadsmith/everycandidate.org/blob/master/_layouts/candidate.html).

Let me know if any of this makes sense. And, if so, what would be helpful in thinking it through further.

Phillip.

**Comment by davidrleonard** [comment]
Not to resurrect a dead thread there, but wondering if any more thought was given to this? This is also a big need for me in designing large Jekyll sites that have a lot of pages with very similar content (i.e. bio pages for hundreds of people). I'd love to be able to manage this data elsewhere, like a Google Sheet, and export it to a single file then build my pages out from there.

**Comment by envygeeks** [comment]
This ticket is being locked. If you have an issue (or feature request) please file a new ticket instead of practicing the art of necromancy. It has hard to maintain actual issues against comments if this happens.
