### ISSUE TITLE
Asset Pipeline?

### ISSUE THREAD

**Issue by qrohlf** [jekyll/jekyll#2998]
This is just a venue to toss some ideas around about some kind of asset pipeline for Jekyll. See [here](https://twitter.com/qrohlf/status/519691532505346049) for the twitter discussion that kicked this off. 

**Feature ideas:**
- Concatenation/minification functionality
- Sourcemap support. (There's currently an open issue on this here: https://github.com/jekyll/jekyll-sass-converter/issues/12, but if Jekyll is concatenating/minifying even vanilla css/js files sourcemaps are a must.)
- Frontend package management. Ideally, I'd like to just specify some Bower dependencies in my `_config.yml` and have them added to my concatenated, minified CSS and JS.

I'm not sure if Jekyll is really the right project to implement that last one, since that's edging away from the "simple" end of spectrum and into "magic" end of the spectrum. However, I do think that any modern web framework should make it easy for developers to concatenate and minify their js and css. Some of this can be done in Jekyll with [includes](https://github.com/qrohlf/sensible-web-development/blob/1e6a39004b8b7d351bc0d8fd88d11751b3b37d7b/js/scripts.js), but it's pretty clunky. 

So, thoughts? Ideas about how to implement a more robust way to handle assets?

**Comment by seemantk** [comment]
Was a ticket ever filed for the concatenation/minification of JS files?  I'll be more than happy to file one if there isn't one yet.

I personally have a very strong need for this feature, as most of the websites I deploy (including for clients) are on github-pages, and so I prefer to have the simplest functional workflows for non-technical clients to continue using their sites -- automating the JS asset pipeline is a key component of that "simplest functional" :)

**Comment by envygeeks** [comment]
Use Jekyll Assets, Jekyll does not do asset pipelines.

**Comment by mhulse** [comment]
> Use Jekyll Assets, Jekyll does not do asset pipelines.

Good solution, but does not work for the github pages gem/setup.

**Comment by envygeeks** [comment]
Yes it does, build and push the HTML into gh-pages and disable Jekyll within Github Pages.

**Comment by mhulse** [comment]
> Yes it does, build and push the HTML into gh-pages and disable Jekyll within Github Pages.

Ok, technically it does, but not in the sense that GitHub accepts plugins. 😆 

There's a good reason for not using plugins, and that's because GitHub does the site generation/building. This is super convenient if you don't want, or are not able to, to run things locally.

**Comment by envygeeks** [comment]
Then you're stuck with the basics as that's what Jekyll does for you.  Jekyll Assets is the what you're looking for if you want something minimized, transpiled, managed better and so forth.  Jekyll's SCSS and Coffeescript transpilers are at their most basic, so that you can feel fancy.

**Comment by envygeeks** [comment]
There is a ticket for it on Github Pages, so go there and complain that they are taking forever to review.

**Comment by mhulse** [comment]
> There is a ticket for it on Github Pages, so go there and complain that they are taking forever to review.

Sounds good to me.

https://github.com/github/pages-gem/issues/189

**Comment by qrohlf** [comment]
now that's an issue I haven't heard from in a long time

![a6aada8f76ad140ad54e1208e01bf414](https://cloud.githubusercontent.com/assets/347189/17678777/75d17d94-62ed-11e6-9e9b-0647094a5f74.jpg)

FWIW, I use webpack for JS & style compilation and packaging in my Jekyll projects now.
