### ISSUE TITLE
sort or sort_by filter does not work

### ISSUE THREAD

**Issue by straz** [jekyll/jekyll#3004]
It seems like this is a bug in `sort`. How is sorting supposed to work? I'm getting errors when I use either the `sort` or the `sort_by` filter in my Liquid template. [Liquid docs](http://docs.shopify.com/themes/liquid-documentation/filters/array-filters#sort) say it's called `sort`, but [others](http://cheat.markdunkley.com/) say it's now called `sort_by`. Which am I supposed to use here?
```html
{% assign sorted_articles = site.data.articles  | sort:"julian" %}
```
I have a yaml file containing references to magazine articles. I'm trying to sort them by date. I've tried expressing dates in three different formats. Liquid fails to parse `YYYY-MM-DD` as a date, so `sort: "date"` sorts alphabetically instead of chronologically. Here is an example (`julian` is the same value as `date` and `iso_date`, just expressed as a Julian date integer):

    - title: 'Measuring Information Work Productivity'
      desc: 'Computerworld'
      url: 'measuring-info.html'
      date: '2004-3'
      iso_date: '2004-3-1 00:00:01'
      julian: 731641

 `sort` works fine on my local machine with `jekyll serve`, but it gives an error (see below) with `jekyll serve --safe` and it fails to build on github-pages.

 `sort_by` builds without error on my local machine and builds successfully on github-pages. But the results are useless. (1) On my local machine, the articles aren't actually sorted, they appear to be in random order. (2) With `--safe` or on gh-pages, the sorted array appears to be empty instead of being sorted.

Example of error when using `sort` (fails with `--safe` and fails to build on github-pages):
```
$ jekyll serve --watch
    Configuration file: /Users/sstrassmann/src/jekhub/pas/_config.yml
            Source: /Users/sstrassmann/src/jekhub/pas
       Destination: /Users/sstrassmann/src/jekhub/pas/_site
      Generating... 
                    done.
     Auto-regeneration: enabled for '/Users/sstrassmann/src/jekhub/pas'
Configuration file: /Users/sstrassmann/src/jekhub/pas/_config.yml
    Server address: http://0.0.0.0:4000/pas/
  Server running... press ctrl-c to stop.
 ^C
$ jekyll serve --watch --safe
Configuration file: /Users/sstrassmann/src/jekhub/pas/_config.yml
            Source: /Users/sstrassmann/src/jekhub/pas
       Destination: /Users/sstrassmann/src/jekhub/pas/_site
      Generating...     
  Liquid Exception: undefined method `sort' for nil:NilClass in articles.html
jekyll 2.4.0 | Error:  undefined method `sort' for nil:NilClass
```
So, what is the preferred way to sort a yaml array?

**Comment by hacknug** [comment]
This is what I have on one of my pages in which I print every collection on my site and I list every single item inside of it.

```
{% for collection in site.collections %}
  {% capture label %}{{ collection | first }}{% endcapture %}
  <h2>{{ label | capitalize }}</h2>
  {% assign ordenados = site.collections.[label].docs | sort: 'title' %}
  {% for doc in ordenados %}
    <li>
      <a href="{{ doc.url }}">{{ doc.title }}</a>
    </li>
  {% endfor %}
{% endfor %}
```

Sorting works fine when it comes to the docs part but I can't make it work when I try to do the same with the collections. I'm doing it like this:

```
{% assign colecciones = site.collections | sort: 'title' %}
{% for collection in colecciones %}
  {% capture label %}{{ collection | first }}{% endcapture %}
  <h2>{{ label | capitalize }}</h2>
  {% assign ordenados = site.collections.[label].docs | sort: 'title' %}
  {% for doc in ordenados %}
    <li>
      <a href="{{ doc.url }}">{{ doc.title }}</a>
    </li>
  {% endfor %}
{% endfor %}
```

I hope the first part solves your problem (I'm using it with 'title', so maybe it doesn't work with custom variables?). Works fine for me on GitHub Pages.

Does anyone know if the part I try to use to sort Collections should work?

**Comment by parkr** [comment]
Yep!
