### ISSUE TITLE
"Compliant mode" for missing Liquid references?

### ISSUE THREAD

**Issue by gjtorikian** [jekyll/jekyll#3008]
Let's say I work for a mediumsized company that loves Jekyll and uses it for documentation.

One day someone writes `{{ organizations.specific_team }}` in their content.

They _actually_ wanted to write `{{ site.data.conrefs.organizations.specific_team }}`--that is, get at some YAML data file in the __data_ directory. Unfortunately, Liquid does not complain for syntax that it does not understand--it just skips it. Is there a way to get Jekyll to make note of omissions like this, or is that something to take up with the Liquid team?

**Comment by iddan** [comment]
How can I use liquid's configuration: `strict_variables: true` with Jekyll?

**Comment by ianhinder** [comment]
This issue has been closed, but as far as I can tell, the strict_variables option implemented in Liquid is not yet accessible from Jekyll.  @parkr: should this issue be kept open until Jekyll can use the strict_variables option?
