### ISSUE TITLE
jekyll serve is pretty slow recently

### ISSUE THREAD

**Issue by kleinfreund** [jekyll/jekyll#3009]
I like to apologize because this will be not a specific issue description.

Anyway, `jekyll serve` is super slow for me recently. It takes a around 1-2 minutes from `Generating...` to `done.`. Regenerating from this point on takes a couple of seconds as well.

My site is fairly small (https://github.com/kleinfreund/kleinfreund.github.io). This was way faster before. Can't be more precise here because my studies started and I rarely enter the magical words `jekyll serve` since then.

Any things I can try on my end?

**Comment by ac70** [comment]
this may or may not help, but I cloned my jekyll repo and started setting it up to use with Grunt.   I didn't quite get there, but when I went back to trying to serve with Jekyll it was taking 1m+ for every save.  Maybe the added files caused this?

I switched back to the previous version and Jekyll serve is working fine again.

**Comment by envygeeks** [comment]
Hi @ac70 please ask your question on https://talk.jekyllrb.com unless you feel it's a bug. Thanks!

**Comment by tommoor** [comment]
Way late to the party here, but I had a similar issue and it was caused by node_modules, just needed adding to the ignored directories in config and everything sped up again :smile:
