### ISSUE TITLE
when run gem install jekyll, I got this : ERROR:  While executing gem ... (Errno::EACCES)

### ISSUE THREAD

**Issue by SophiaJia** [jekyll/jekyll#3025]
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/Cellar/ruby/2.1.3_1/lib/ruby/gems/2.1.0/gems/fast-stemmer-1.0.2/LICENSE

I just upgraded to os10.10 , I and my ruby upgraded to 2.1.3 and I had Bundler and RubyGems installed but still can't make it work ... 

What should I do?

Thanks!

Sophia

**Comment by dianaks** [comment]
I get the same problem but when I run sudo chown -R $(whoami) /var/lib/gems and write my password, chown: cannot access ‘/var/lib/gems’: No such file or directory
Can you help me? Thanks
