### ISSUE TITLE
Bug: --detach disables watching, despite saying that autogeneration is enabled

### ISSUE THREAD

**Issue by nicolasmccurdy** [jekyll/jekyll#3030]
Steps to Reproduce
---
1. Create a Jekyll site with `jekyll new site`.
2. Serve it with `jekyll serve --detach`.
3. Open `localhost:4000` in your web browser.
4. Modify `index.html`.
5. Reload the page in your web browser.

Expected Behavior
---
Watching is enabled (the web browser displays the updated page), or watching is disabled and Jekyll warns that watching is disabled.

Actual Behavior
---
Watching is disabled, and the web browser does not display the updated page. Jekyll says that auto-regeneration is enabled, which is inaccurate

Actual Output
---
    Configuration file: /Users/nick/site/_config.yml
                Source: /Users/nick/site
           Destination: /Users/nick/site/_site
          Generating...
                        done.
     Auto-regeneration: enabled for '/Users/nick/site'
    Configuration file: /Users/nick/site/_config.yml
        Server address: http://0.0.0.0:4000/
    Server detached with pid '4290'. Run `kill -9 4290' to stop the server.

**Comment by CharlieHawker** [comment]
Any news on this?

**Comment by parkr** [comment]
None yet, want to submit a PR?

**Comment by yourhead** [comment]
jekyll serve &
JEKYLLPID=`echo $!`
echo "Server detached with pid '${JEKYLLPID}'. Run 'kill -9 ${JEKYLLPID}' to stop the server."

**Comment by mpvosseller** [comment]
+1
I ran into this issue today. At minimum it would be great if the output could indicate that (in this case) Auto-regeneration is disabled. I spent time trying to figure out what I was doing wrong.
