### ISSUE TITLE
Proposal: Access collection variables from page

### ISSUE THREAD

**Issue by hamishwillee** [jekyll/jekyll#3044]
It would be very helpful to be able to access the collection variables defined in _config.yml from the page. For example, to define a collection-specific navbar in a layout I would then be able to use the variable {{page.collection.navbar}}.

Instead I currently have to get the name {{page.collection}} and iterate through site.collections comparing to the first element to get the actual collection. Annoying.

**Comment by schristm** [comment]
This isn't actually working for me. Was this feature removed?

**Comment by DirtyF** [comment]
@schristm Feel free to ask on https://talk.jekyllrb.com/

**Comment by adam-arold** [comment]
Bump. Why is this closed? The `collections` variables are still not visible from the `page` variable. Now I have to redefine each custom variable which I have in `collections` in `defaults` to be able to use them.

**Comment by oe** [comment]
@adam-arold Please try not to bump a 2 year-old issue, consider opening a new one instead.
