### ISSUE TITLE
0.0.0.0:4000 unreachable in Chrome Canary

### ISSUE THREAD

**Issue by kdzwinel** [jekyll/jekyll#3048]
Few days ago I found out that I'm unable to open jekyll's default local URL (`0.0.0.0:4000`) in Chrome Canary (nightly version of Chrome). Instead, Chrome redirects me to the Google results for "0.0.0.0". I've alerted Chromium team about it ( http://crbug.com/428046 ) and I've learned that:
- `0.0.0.0` is a non-routable address
- they are going to push this change to stable
- I should use `127.0.0.1:4000` instead (and that it actually works)

My guess is that, when this change lands in stable Chrome, many people will be confused, as I was, about `0.0.0.0` being not accesible. To avoid that, it might be a good idea to replace default "Server address: http://0.0.0.0:4000/" with "Server address: http://localhost:4000".

**Comment by ibnesayeed** [comment]
This change causes more inconveniences than it solves. The IP address `0.0.0.0` is not routable when resolved, that does not mean a service should not run on this address.

The issue it solves:

- The server says it is listening on 0.0.0.0:4000 but some browsers cant resolve that address.

The issues it causes:

- Running the server with default config is no longer accessible outside the localhost
- This affects deployment in Docker (with default config) as it will not allow accessing from outside the container until one gets the surprise revelation (or a some searching around) that a custom host must be supplied explicitly (which is against Ruby's philosophy of developer happiness and simpler fulfillment of expectations)

A possibly better approach:

- Keep the server listening on 0.0.0.0 but advertise local access differently, unless a custom hostname is provided

#3542 has some great suggestions on how to display a meaningful message.

**Comment by parkr** [comment]
You can very easily run `jekyll serve --host 127.0.0.1`. Going back and forth with this IP address has caused nothing but headaches and I don't want to see it changed yet again, causing another influx of issues. Please use the configuration options we provide for your use case.

**Comment by ibnesayeed** [comment]
@parkr you missed the point I made. Now, that I know how to run it to make it accessible outside, it is not my problem anymore. However, I wanted to record the frustration I faced initially when it did not work the way I would expect and the time I spent to figure the way out. The default out of the box experience is not smooth. In my opinion, the issue that was reported originally in this ticket, changing the IP address was not the best way to solve that as it has caused more issues than it has solved. Changing the default IP from `0.0.0.0` to `127.0.0.1` was a breaking change which has caused headaches to many people who were using it at that time and it will continue to bother new people. However, reverting it back to `0.0.0.0` perhaps won't cause that issue. #3542 has really good suggestions how to deal with it. Using `0.0.0.0` as the default IP is practiced in many applications that run some sort of server.

Having said that, I am not challenging your final decision on not switching things back and forth. This is your software and you can decide better what would be a good experience for your users. Being a user of this software, I juts provided my feedback.
