### ISSUE TITLE
gem install jekyll error?

### ISSUE THREAD

**Issue by ghost** [jekyll/jekyll#3059]
gem install jekyll
ERROR:  Could not find a valid gem 'jekyll' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ETIMEDOUT:
 A connection attempt failed because the connected party did not properly respon
d after a period of time, or established connection failed because connected hos
t has failed to respond. - connect(2) for "s3.amazonaws.com" port 443 (https://a
pi.rubygems.org/latest_specs.4.8.gz)

**Comment by chaichenluo** [comment]
Try to hange a new source
    gem source -r http://rubygems.org/;gem source -a http://taobao.com
