### ISSUE TITLE
jekyll broke after 2.5 upgrade

### ISSUE THREAD

**Issue by nicodev3** [jekyll/jekyll#3084]
I just updated jekyll to the latest 2.5 and when i "jekyll serve" i have the following 

``` text
WARN: Unresolved specs during Gem::Specification.reset:
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.4/lib/mercenary.rb:20:in `program': cannot load such file -- mercenary/program (LoadError)
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.0/bin/jekyll:20:in `<top (required)>'
    from /usr/bin/jekyll:23:in `load'
    from /usr/bin/jekyll:23:in `<main>'
```

What's wrong ?

**Comment by sr-murthy** [comment]
Hi

I had the same problem (it's OK now!) after I had added a Gemfile to my local static Jekyll site with the content

    source 'https://rubygems.org'
    require 'json'
    require 'open-uri'
    versions = JSON.parse(open('https://pages.github.com/versions.json').read)
    gem 'github-pages', versions['github-pages']

and ran `bundle install`, followed by (after a lot of content changes) `jekyll build`.  I got the following error

    WARN: Unresolved specs during Gem::Specification.reset:
      redcarpet (~> 3.1)
    WARN: Clearing out unresolved specs.
    Please report a bug if this causes problems.
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load     such file -- jekyll/version (LoadError)
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
    from /usr/bin/jekyll:23:in `load'
    from /usr/bin/jekyll:23:in `<main>'

Could someone please explain what `bundler` does, because I'm still not sure, and what its relationship to `jekyll` is?

Thanks in advance.

**Comment by themestechnology** [comment]
1) try to install the gem file listed under WARN i.e. gem install redcarpet 
2) delete gemfile.lock

**Comment by themestechnology** [comment]
try npm i and then bundle exec jekyll serve

**Comment by wapple** [comment]
I have the same problem ,but when I tried gem cleanup and bundle exec jekyll serve ,I got the output.
<pre>
<code>
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ gem cleanup
Cleaning up installed gems...
Clean Up Complete
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ bundle exec jekyll serve
Could not find gem 'github-pages (>= 0) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    github-pages (>= 0) x64-mingw32 depends on
      jekyll (= 1.1.2) x64-mingw32

    octopress (~> 3.0.0.rc.12) x64-mingw32 depends on
      jekyll (2.5.3)
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ 
</code>
</pre>
:question:

**Comment by themestechnology** [comment]
Have you tried removing octopress or even removing all gems and starting over.

# gem list --no-version | xargs gem uninstall -aIx

**Comment by envygeeks** [comment]
Show us your Gemfile and update your `github-pages`.

**Comment by wapple** [comment]
problems solved maybe I should use<code>cd ..</code> to bundle install

**Comment by themestechnology** [comment]
How?

**Comment by swirlsnap** [comment]
Jekyll broke for me as well, and now its not able to parse my CSS? cryptotap.com -- got the same error as OP -- bundle exec jekyll serve works, but now my whole sites formatting is broken. Funsies.

**Comment by parkr** [comment]
@swirlsnap Try the latest 3.0 beta.

**Comment by chaitanyav** [comment]
I am using jekyll 2.5.3 and it works 

Gemfile
```
source 'https://rubygems.org'

gem 'jekyll'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'
```
Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.0)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    blankslate (2.1.2.4)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    classifier-reborn (2.0.3)
      fast-stemmer (~> 1.0)
    coderay (1.1.0)
    coffee-script (2.3.0)
      coffee-script-source
      execjs
    coffee-script-source (1.8.0)
    colorator (0.1)
    execjs (2.2.2)
    fast-stemmer (1.0.2)
    ffi (1.9.6)
    ffi (1.9.6-x86-mingw32)
    hitimes (1.2.2)
    hitimes (1.2.2-x86-mingw32)
    i18n (0.7.0)
    jekyll (2.5.3)
      classifier-reborn (~> 2.0)
      colorator (~> 0.1)
      jekyll-coffeescript (~> 1.0)
      jekyll-gist (~> 1.0)
      jekyll-paginate (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 2.6.1)
      mercenary (~> 0.3.3)
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      safe_yaml (~> 1.0)
      toml (~> 0.1.0)
    jekyll-coffeescript (1.0.1)
      coffee-script (~> 2.2)
    jekyll-gist (1.1.0)
    jekyll-paginate (1.1.0)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-watch (1.2.1)
      listen (~> 2.7)
    json (1.8.2)
    kramdown (1.5.0)
    liquid (2.6.2)
    listen (2.8.5)
      celluloid (>= 0.15.2)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    mercenary (0.3.5)
    minitest (5.5.1)
    parslet (1.5.0)
      blankslate (~> 2.0)
    posix-spawn (0.3.9)
    pygments.rb (0.6.2)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.2.0)
    rake (10.4.2)
    rb-fsevent (0.9.4)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    redcarpet (3.2.2)
    safe_yaml (1.0.4)
    sass (3.4.10)
    stringex (2.5.2)
    thor (0.19.1)
    thread_safe (0.3.4)
    timers (4.0.1)
      hitimes
    toml (0.1.2)
      parslet (~> 1.5.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    yajl-ruby (1.2.1)

PLATFORMS
  ruby
  x86-mingw32

DEPENDENCIES
  activesupport
  coderay
  jekyll
  kramdown
  rake
  stringex
  thor
```

The only thing i did to get around this error was 
```
/usr/local/lib/ruby/2.2.0/fileutils.rb:1450:in `unlink': Operation not permitted @ unlink_internal - /Users/nagachaitanyavellanki/Documents/projects/minimal-mistakes/_site/tags (Errno::EPERM)
```

Change the line 82  in
```
/usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/static_file.rb
```
to 

``` FileUtils.rm_rf(dest_path) if File.exist?(dest_path)```

This must be something to do with my _site directory. 

# Conclusion: jekyll 2.5.3 works!!

**Comment by Pajamaman** [comment]
Can anyone explain why `bundle exec jekyll serve` works but `jekyll serve` does not?

**Comment by parkr** [comment]
@Pajamaman `bundle exec` makes sure you have the right versions of everything. :)

**Comment by envygeeks** [comment]
Gem does too @parkr since quite a while now (sometime last year -- it will use the Gemfile,) don't include a path @Pajamaman and bundler will install to the system, you can also force it with `--system` if I remember right, we do on our Docker images so we can pre-spawn.

**Comment by willianribeiro** [comment]
Works for me when I added the Gemfile posted by @chaitanyav at the root of my jekyll project, and after it executed the command `bundle install`. Thank you! (:

**Comment by eplehans** [comment]
Worked for me after I installed Bundler by running `$ bundle install` and then  `$ bundle exec jekyll serve`

**Comment by robotutu** [comment]
@eplehans  How can i running into by ‘jekyll serve’ ?

**Comment by eplehans** [comment]
@robotutu I'm sorry, I don't understand what you mean

**Comment by SuriyaaKudoIsc** [comment]
@parkr Still the same problem on newer versions of Jekyll.

----

I need to run: **`bundle exec jekyll serve`**!

**Comment by themestechnology** [comment]
install ruby-full; Make sure you install ruby-full not ruby! https://www.ruby-lang.org/en/documentation/installation/
install gem; https://rubygems.org/pages/download
gem install bundler;
bundle install;
install nodejs; https://nodejs.org/en/download/package-manager/
npm install -g npm; https://docs.npmjs.com/getting-started/installing-node
npm install -g bower; http://bower.io/#install-bower

Remove any .loc files ie "Gemfile.lock"

gem install rubygems-update;
gem update;
bundle update;
npm install -g npm;
npm install -g bower;
npm install;
npm update;
bower install --allow-root;
bower update --allow-root;
