### ISSUE TITLE
Modifying a .sass file outside of the css directory doesn't trigger a regenerate

### ISSUE THREAD

**Issue by lewisflude** [jekyll/jekyll#3097]
What I expected to happen: to modify a file (i.e. _base.scss) which is imported by main.scss and for that to trigger a build of my jekyll project.

I seem to remember before, having the ability to modify an imported sass file and have that trigger a regeneration instantly.

Is this intended behaviour?

I feel like this is an issue, and in the interest of helping others if they're running into this problem I thought I'd flag it.

**Comment by fi5u** [comment]
Hi, I'm having the same issue. All the included `.scss` files in `_sass` directory are being watched and built, but `.scss` files within subdirectories within `_sass` are not being watched or built. I tried the uninstall/reinstall liquid solution, but that hasn't changed things.

Are there any more solutions I could try?

**Comment by kleinfreund** [comment]
Are really all fil3s not being watched? I have the issue where files starting with _site won't be watched.

**Comment by envygeeks** [comment]
@fi5u @kleinfreund Can you guys file a unique ticket for this problem so we can check it out?  More than likely it's a quick and easy fix that can land in the next beta.

**Comment by fi5u** [comment]
Created new issue: https://github.com/jekyll/jekyll/issues/3589

**Comment by kleinfreund** [comment]
@envygeeks I did so in January: https://github.com/jekyll/jekyll-watch/issues/22
