### ISSUE TITLE
Sunset Maruku

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#3098]
Remove support for Maruku.

See https://github.com/github/pages-gem/pull/82 for more info.

**Comment by parkr** [comment]
Not sure it's a great idea to remove Maruku support. It seems to be the only library that supports things like MathJAX. Thoughts?

/cc @benbalter @gjtorikian for their :thought_balloon:

**Comment by pathawks** [comment]
If there are specific features that only Maruku supports, maybe we should make a list of those features and try to tackle them from another angle, ie: feature specific plugins.

**Comment by gjtorikian** [comment]
> It seems to be the only library that supports things like MathJAX.

For many reasons, I don't think MathJax is the end-all-be-all for math rendering. In short, I do not think MathJax (or other capabilities) are worth keeping Maruku around for. The project is dead; let Kramdown or other rendering libraries incorporate the features people want.

In any event, I wrote [a Jekyll plugin](https://github.com/gjtorikian/jekyll-mathematical) for [a math rendering library](https://github.com/gjtorikian/mathematical) I'm working on.

**Comment by alfredxing** [comment]
@parkr Kramdown has math support: http://kramdown.gettalong.org/syntax.html#math-blocks

**Comment by parkr** [comment]
Ok cool! Anyone have time for a PR?

**Comment by alfredxing** [comment]
I think Kramdown parses all of the math blocks by default if you follow their syntax.

**Comment by parkr** [comment]
I mean for removing maruku.

**Comment by alfredxing** [comment]
@parkr Right :smile:
I can work on it!

**Comment by alfredxing** [comment]
PR merged, Maruku is now removed!

**Comment by mattr-** [comment]
:heart:
