### ISSUE TITLE
Jekyll choking on something when running the Jekyll site locally

### ISSUE THREAD

**Issue by jglovier** [jekyll/jekyll#3103]
I'm trying to work on a refactor of the Jekyll site sass, and I'm not able to get Jekyll running locally. When I `cd` into `/site` and try to run `jekyll serve` I'm getting the following output, and the server aborts:

```
|===jglovier===| ~/code/github-jekyll/jekyll/site $ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      posix-spawn (~> 0.3.6)
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
      classifier-reborn (~> 2.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/joelglovier/code/github-jekyll/jekyll/site/_config.yml
            Source: /Users/joelglovier/code/github-jekyll/jekyll/site
       Destination: /Users/joelglovier/code/github-jekyll/jekyll/site/_site
      Generating...
  Liquid Exception: cannot load such file -- pygments in _docs/assets.md
/opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll/tags/highlight.rb:77:in `require': cannot load such file -- pygments (LoadError)
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll/tags/highlight.rb:77:in `render_pygments'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll/tags/highlight.rb:51:in `render'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/liquid-2.6.1/lib/liquid/block.rb:109:in `block in render_all'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `each'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/liquid-2.6.1/lib/liquid/block.rb:96:in `render_all'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/liquid-2.6.1/lib/liquid/block.rb:82:in `render'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/liquid-2.6.1/lib/liquid/template.rb:128:in `render'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/liquid-2.6.1/lib/liquid/template.rb:138:in `render!'
    from /Users/joelglovier/code/github-jekyll/jekyll/lib/jekyll/renderer.rb:92:in `render_liquid'
    from /Users/joelglovier/code/github-jekyll/jekyll/lib/jekyll/renderer.rb:49:in `run'
    from /Users/joelglovier/code/github-jekyll/jekyll/lib/jekyll/site.rb:292:in `block (2 levels) in render'
    from /Users/joelglovier/code/github-jekyll/jekyll/lib/jekyll/site.rb:291:in `each'
    from /Users/joelglovier/code/github-jekyll/jekyll/lib/jekyll/site.rb:291:in `block in render'
    from /Users/joelglovier/code/github-jekyll/jekyll/lib/jekyll/site.rb:290:in `each'
    from /Users/joelglovier/code/github-jekyll/jekyll/lib/jekyll/site.rb:290:in `render'
    from /Users/joelglovier/code/github-jekyll/jekyll/lib/jekyll/site.rb:51:in `process'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll/command.rb:28:in `process_site'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll/commands/build.rb:56:in `build'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll/commands/build.rb:34:in `process'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /opt/rubies/2.1.2-github1/lib/ruby/gems/2.1.0/gems/jekyll-2.5.1/bin/jekyll:20:in `<top (required)>'
    from /opt/boxen/rbenv/versions/2.1.2-github/bin/jekyll:23:in `load'
    from /opt/boxen/rbenv/versions/2.1.2-github/bin/jekyll:23:in `<main>'
```

Is there a simple fix for this that I'm missing? 

Also, on a [UX note](https://github.com/jekyll/jekyll/issues/2695), is there a way for the output to be more helpful in knowing what to do next?

**Comment by wapple** [comment]
I have the same problem ,but when I tried gem cleanup and bundle exec jekyll serve  ,I got the output.

wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ gem cleanup
Cleaning up installed gems...
Clean Up Complete
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ bundle exec jekyll serve
Could not find gem 'github-pages (>= 0) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    github-pages (>= 0) x64-mingw32 depends on
      jekyll (= 1.1.2) x64-mingw32

    octopress (~> 3.0.0.rc.12) x64-mingw32 depends on
      jekyll (2.5.3)
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$

**Comment by wapple** [comment]
I have the same problem ,but when I tried gem cleanup and bundle exec jekyll serve ,I got the output.
<pre>
<code>
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ gem cleanup
Cleaning up installed gems...
Clean Up Complete
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ bundle exec jekyll serve
Could not find gem 'github-pages (>= 0) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    github-pages (>= 0) x64-mingw32 depends on
      jekyll (= 1.1.2) x64-mingw32

    octopress (~> 3.0.0.rc.12) x64-mingw32 depends on
      jekyll (2.5.3)
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ 
</code>
</pre>

**Comment by wapple** [comment]
I have the same problem ,but when I tried <code>gem cleanup</code> and <code>bundle exec jekyll     serve</code> ,I got the output. :question:
<pre>
<code>
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ gem cleanup
Cleaning up installed gems...
Clean Up Complete
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ bundle exec jekyll serve
</code></pre>
and then
<pre><code>
Could not find gem 'github-pages (>= 0) ruby' in the gems available on this machine.
Run `bundle install` to install missing gems.</code></pre>
so I tried
<code><pre>
wapple@wapple-Lenovo-G470:~/Downloads/hpstr-jekyll-theme-master$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    github-pages (>= 0) x64-mingw32 depends on
      jekyll (= 1.1.2) x64-mingw32

    octopress (~> 3.0.0.rc.12) x64-mingw32 depends on
      jekyll (2.5.3)
</code>
</pre>

**Comment by pathawks** [comment]
@wapple You have the same problem, three times.
What does your `Gemfile` look like?

Can you run `bundle update` and try again?

**Comment by eplehans** [comment]
I just upgraded to 2.4.0. Running `bundle exec jekyll build` instead of  `jekyll build` fixes it.

**Comment by footyapps27** [comment]
`bundle update` & `bundle install` did the trick for me. Thanks @pathawks.

**Comment by zachdyer** [comment]
same

**Comment by Joyce-Ng** [comment]
I have the same problem , my problem was fixed when I try to run this : bundle exec jekyll serve

**Comment by Joyce-Ng** [comment]
I have the same problem , my problem was fixed when I try to run this :` bundle exec jekyll serve`
