### ISSUE TITLE
site.related_posts gives the same results for every page

### ISSUE THREAD

**Issue by giladnaor** [jekyll/jekyll#3105]
In my post template, I have:

```
 {% for post in site.related_posts %}
   <li><a href="{{ site.url }}{{ post.url }}" title="{{ post.title }}">{{ post.title }}</a></li>
 {% endfor %}
```

I get the same related posts regardless of the actual post.

Any tips on how to debug this?

(I'm using Jekyll 2.4.0 with LSI)

**Comment by davidsilvasmith** [comment]
You seem to be right. Looking through my site it seems to just swap out the current page in the related pages with all other links being the same.

**Comment by mediavrog** [comment]
+1

**Comment by davidsilvasmith** [comment]
@mediavrog the docs were [updated on github 2/17/2015](https://github.com/jekyll/jekyll/commit/e9638fa6a2be45e4b5d460300fc230ecaffdc2a5) about 3 months after this bug was filed. I'm not sure when those changes went live.
