### ISSUE TITLE
Add right to left stylesheet

### ISSUE THREAD

**Issue by mehdisadeghi** [jekyll/jekyll#3137]
I would like to see RTL support in jekyll. Right now I add a new rtl.scss to change direction and do some css to have a proper RTL output. How about adding this file to default styles and having a new `direction` keyword in config file to change direction (which defaults to LTR)? If this suffices I will send a pull request. Please let me know your ideas.

**Comment by navidkashani** [comment]
One method that can be used is writing scss with direction control , see: https://github.com/parhumm/sass-direction-controller

**Comment by mehdisadeghi** [comment]
@navidkashani I think it is a good idea. Then based on a keyword in `_config.yml` file we can activate it.

**Comment by parkr** [comment]
This is not currently in the roadmap. If someone were to propose it, I would certainly accept a PR that added a `--rtl` flag to `jekyll new` and that added the RTL CSS file to `lib/site_template` for use with that flag.

That said, this is not something the Core Team has time to work on, so I'm going to close. If someone comes across my comment and has time to implement, please send a PR and reference this issue. Thanks!

**Comment by tehchieftain** [comment]
I altered the basic Jekyll theme's direction and style to help people speed things up.
Here's the repository https://github.com/tehchieftain/jekyll-arabic.git

I know this isn't a real RTL support, but it can save sometime for people to use it.
