### ISSUE TITLE
/css/main.css considered as a Jekyll:Page?

### ISSUE THREAD

**Issue by tkrotoff** [jekyll/jekyll#3151]
Inside site template file [header.html](https://github.com/jekyll/jekyll/blob/v2.5.2/lib/site_template/_includes/header.html#L18), remove line `{% if page.title %}` and you will see that /css/main.css is considered as a Jekyll:Page object.

I find it confusing considering it is a generated file.

~~In a similar way, feed.xml, even with `layout: null` is also considered as a Jekyll:Page.~~

**Comment by aguynamedben** [comment]
Being new to jekyll I also find this very confusing. To list all pages I guess I'll have to create YAML front matter data for "actually is a page."

**Comment by Wolfgange3311999** [comment]
I, as well, recently ran into the same problem. I don't mind that it is considered a page but rather that I haven't found a way to differentiate it from html pages with something like an automatic `page.file_type`front matter variable.

**Comment by parkr** [comment]
@Wolfgange3311999 I don't think we could do filetypes very easily (e.g. `text/html`), but we could easily provide the extension name as `page.extname`. Would that help?

**Comment by Wolfgange3311999** [comment]
@parkr For me it would help. Although thinking about it, with almost any larger website there wouldn't be a need to do so; html files would eventually become meaningless for categorization when more than 3 are in the project.

**Comment by San7hos** [comment]
Sorry to comment on a closed issue, but I am now having the same issue.
I am cycling through site.pages and my main.scss located in folder /css/main.scss is in the collection. Do I have to skip it manually or should I move the file elsewhere?

**Comment by kynan** [comment]
I work around this with an extra

    {% if page.title %}
    ...
    {% endif %}

**Comment by parkr** [comment]
You can also do the following if you are looking for file output as HTML:

```liquid
{% for page in site.html_pages %}
  ...
{% endfor %}
```

Or, you can use [`where_exp`](http://jekyllrb.com/docs/templates/):

```liquid
{% assign my_pages = site.pages | where_exp: "page", "page.ext != 'css'" %}
{% for page in my_pages %}
  ...
{% endfor %}
```

The expression `page.ext != 'css'` might not work (doing this from memory), but that's the gist. 😄
