### ISSUE TITLE
Switch to Rouge as Default Syntax Highlighter

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#3157]
I've been very pleased with @jneen's [rouge](https://github.com/jneen/rouge) syntax highlighter. It's pure Ruby and is compliant with the current version of Pygments (as far as I can tell). Pygments causes a lot of issues and puts a hard requirement on Python for use of Jekyll. A common complaint and issue we hear about is pygments failing. It is usually either the wrong Python version (using v3 instead of v2.7) or they don't have Python wired up properly in their `$PATH`.

To eliminate the need for Python altogether, I would like to move to Rouge by default.

/cc @jekyll/gh-pages for Pages consideration, and @jekyll/windows for Windows concerns.

**Comment by greenify** [comment]
+1 for having `rouge` as default syntax highlighter :)
(I don't use Windows, but I know that many people on this OS struggle to setup their machine correctly)

Did someone compile the statistics?

**Comment by dlee13** [comment]
The Pygments highlighter has caused my build to fail as well, so I installed the Rouge gem and set my _config.yml. The site builds fine now, but nothing is highlighted in the code snippet from the "Welcome to Jekyll!" default post. Am I missing something?

**Comment by XhmikosR** [comment]
GitHub pages don't support Rouge, at least not at this point.

**Comment by jneen** [comment]
GitHub Pages should support rouge - it's just HTML and CSS.

**Comment by XhmikosR** [comment]
No it doesn't because it's not part of their gems.

**Comment by jneen** [comment]
Does GitHub Pages even run ruby?  I thought it was for static hosting.

**Comment by tarebyte** [comment]
It does, ruby 2.1.1 to be precise https://pages.github.com/versions/

**Comment by jneen** [comment]
Oh, that's their convenience gem I guess.  Pages itself still hosts static files, which you can generate with any version of jekyll under any configuration.

https://help.github.com/articles/creating-project-pages-manually/

**Comment by pathawks** [comment]
This has gotten a bit off topic, huh?

**Comment by jneen** [comment]
@dlee13 I suggest opening a separate ticket.

**Comment by dlee13** [comment]
This isn't related to Github pages because I was trying to generate my site on my own system. But actually, I figured out what was wrong. I have Jekyll 2.5.3 installed and this issue was brought up in issue #3371 and addressed by #3323 for Jekyll 3.0. Sorry for bringing it up.

**Comment by v0lkan** [comment]
Long time lurker, first time poster here :) 

I'd second the "defaulting to rogue" decision.

The lest runtimes we need to fiddle with, the better.

**Comment by alfredxing** [comment]
I believe this was done in #3323, and should be included in the `v3.0.0.pre.beta2` pre-release.

**Comment by parkr** [comment]
Yes, thanks Alfred!!
