### ISSUE TITLE
Uninstall jekyll.

### ISSUE THREAD

**Issue by francisceril** [jekyll/jekyll#3168]
How to completely remove jekyll that was installed using your own guide (sudo gem install jekyll)? I would like to reinstall it using homebrew as I've read its the way to go.
Thanks.

**Comment by chrisdemars** [comment]
If you don't have permissions you have to run ```sudo gem uninstall jekyll``` then depending on how many versions of Jekyll are installed, you will be prompted with a number option to pick.

**Comment by envygeeks** [comment]
This issue is being locked, if you have trouble doing something that is not directly related to Jekyll and a bug in Jekyll please use https://talk.jekyllrb.com thanks.
