### ISSUE TITLE
Will GitHub Pages Auto-Rebuild my future Jekyll posts?

### ISSUE THREAD

**Issue by bzerangue** [jekyll/jekyll#3174]
I have a list of future daily posts. When I upload them to Github Pages, will it auto rebuild based on the dates of posts? In other words, when the current-date matches the date of the post, will it or can it auto-rebuild, or do I have to manually rebuild?

**Comment by PunKeel** [comment]
:cry:

**Comment by parkr** [comment]
@PunKeel If this is a feature you would like to see, you can write support@github.com about it. Only they can help you!
