### ISSUE TITLE
Make more dependencies optional

### ISSUE THREAD

**Issue by postmodern** [jekyll/jekyll#3183]
Jekyll used to be a simple tool that would render markdown and liquid templates. Now it sports 14 dependencies, each with their own sub-dependencies!

* [classifier-reborn ~> 2.0](http://rubygems.org/gems/classifier-reborn)
* [colorator ~> 0.1](http://rubygems.org/gems/colorator)
* [jekyll-coffeescript ~> 1.0](http://rubygems.org/gems/jekyll-coffeescript)
* [jekyll-gist ~> 1.0](http://rubygems.org/gems/jekyll-gist)
* [jekyll-paginate ~> 1.0](http://rubygems.org/gems/jekyll-paginate)
* [jekyll-sass-converter ~> 1.0](http://rubygems.org/gems/jekyll-sass-converter)
* [jekyll-watch ~> 1.1](http://rubygems.org/gems/jekyll-watch)
* [kramdown ~> 1.3](http://rubygems.org/gems/kramdown)
* [liquid ~> 2.6.1](http://rubygems.org/gems/liquid)
* [mercenary ~> 0.3.3](http://rubygems.org/gems/mercenary)
* [pygments.rb ~> 0.6.0](http://rubygems.org/gems/pygments.rb)
* [redcarpet ~> 3.1](http://rubygems.org/gems/redcarpet)
* [safe_yaml ~> 1.0](http://rubygems.org/gems/safe_yaml)
* [toml ~> 0.1.0](http://rubygems.org/gems/toml)

Of course rubygems handles installing most of these dependencies without issue. The real problem is dependencies such as jekyll-coffeescript and pygments.rb which require external dependencies (JavaScript VM and Python, respective). Other dependencies such as jekyll-sass-converter, jekyll-gist, toml and even jekyll-coffeescript are questionable (not everyone likes SASS and CoffeeScript...), and could be made optional. Some internal dependencies such as colaborator or mercenary could be replaced by simple modules (ANSI codes are not hard) or code from stdlib (ex: OptionParser).

**Comment by parkr** [comment]
For 3.0, we'll have the following as required:

```ruby
  s.add_runtime_dependency('liquid',    '~> 3.0')
  s.add_runtime_dependency('kramdown',  '~> 1.3')
  s.add_runtime_dependency('mercenary', '~> 0.3.3')
  s.add_runtime_dependency('safe_yaml', '~> 1.0')
  s.add_runtime_dependency('colorator', '~> 0.1')
  s.add_runtime_dependency('rouge', '~> 1.7')
  s.add_runtime_dependency('jekyll-sass-converter', '~> 1.0')
  s.add_runtime_dependency('jekyll-watch', '~> 1.1')
```
