### ISSUE TITLE
Let's talk about the Resources page

### ISSUE THREAD

**Issue by jordanthornquest** [jekyll/jekyll#3188]
Hey, folks!

_Foreword: this is a minor issue in the grand scheme of Jekyll's development and improvement, but being fairly inexperienced when it comes to refining Jekyll's backend and logic, I figured this was a good way that I and like-minded developers could help better Jekyll for users. I think Jekyll rocks, and I'd love to do my part in making it easier for people to wield the tool and approach it._

Jekyll has proven to be a powerful tool with a bit of a learning curve and, as a result, much of the discussion about Jekyll is centered around questions like, "How do I do (x) in Jekyll?" The whole process of working with static pages and Jekyll's template-to-site workflow enables a lot of functionality in a static site, but also opens up a lot of mystery, due to Jekyll's fairly un-opinionated design.

As a result, there are an abundance of articles, tips, and tricks about how to make Jekyll do what you want, written both independently by a developer who pioneered a solution themselves and by clever problem-solvers who respond to questions asked by Jekyll users via IRC, StackOverflow, or Jekyll's own [help repo](https://github.com/jekyll/jekyll-help).

Here's what I want to bring to the table:

* Is there a place or a need for the [Resources](http://jekyllrb.com/docs/resources/) page within Jekyll's documentation? Or does the ability to Google a solution prove its use limited?
* Is there a better, more prominent place we could put it?
* Should there be a more active curation and spread of useful articles, tips, and tricks that can be shared to those using Jekyll?

I consider this a worthy discussion because, after asking about Jekyll's resources page [on Twitter](https://twitter.com/jekyllrb/status/540710545783939073), the response seemed to infer that the resources page had been left untouched for a while. And, after making a [pull request](https://github.com/jekyll/jekyll/pull/3185) of my own about adding an article, another user [did the same thing](https://github.com/jekyll/jekyll/pull/3186) a little while later with their own excellent article! In other words, there seems to be some interest about this topic. 

Any other discussion points, questions, or ideas about the Resources page are also appreciated here.

**Comment by parkr** [comment]
Feel free to submit PR's to this page if you'd like. They should be:

1. Generally relevant – all Jekyll users could benefit from this information
2. Tested on the latest version

Ideally, they would also be vetted by other Jekyll users or core team members. Thanks!
