### ISSUE TITLE
January 2015 Townhall

### ISSUE THREAD

**Issue by troyswanson** [jekyll/jekyll#3190]
After our first beta townhall that we just did (#2358), we kind of decided that we wanted to do one of these a month. The day of the week and time of day dont really matter to me too much, although I would probably like to not have it be 11:00pm on a Friday again. :beer:

PS: If you missed the first townhall, check it out [here](https://www.youtube.com/watch?v=vZbvHsY1Oa8)!

**Comment by parkr** [comment]
Perhaps next weekend?

**Comment by troyswanson** [comment]
Next weekend is good for me.

**Comment by redknitin** [comment]
If we're trying to narrow it down to a particular day, Friday night would be good because that's Saturday morning for me, but I think most people wouldn't want to be up late to participate in a Google Hangouts session.

If it's Saturday night (which becomes Sunday morning in the timezone here), I'll have to check if I can make it because Sunday is a workday in this part of the world.

**Comment by troyswanson** [comment]
Friday night is fine for me.

**Comment by redknitin** [comment]
I'm going to have to cancel... I have to travel on Friday night.

I'll catch up by watching the recorded session and will post back with suggestions/questions/concerns.

**Comment by troyswanson** [comment]
I can do it next weekend too. Just about any Friday is good for me.

**Comment by envygeeks** [comment]
haha I forgot all about this and I was just thinking this morning "when are we having the next one" either way I am available next weekend if you guys want to move it.

**Comment by alfredxing** [comment]
Next weekend is good for me as well!

**Comment by mattr-** [comment]
I'm out. Sorry. :disappointed: I'll just catch the recorded version.

**Comment by troyswanson** [comment]
Let's come up with some topics for Friday's hangout.

* Obviously more Jekyll 3 discussion, steps on how to get there, etc.
* The Jekyll Meetup at GitHub HQ in Feb

Que mas?

**Comment by alfredxing** [comment]
We should also discuss the forums/community issue that popped up recently in #2358 (see [this comment](https://github.com/jekyll/jekyll/issues/2358#issuecomment-70406217)).

**Comment by grobmeier** [comment]
A timezone would be great!

Here is a fantastic tool to announce such dates:
http://www.timeanddate.com/worldclock/fixedform.html

**Comment by parkr** [comment]
@grobmeier 7pm PST, probably? I'd like to move the times in future months to make it possible for Europe to participate.

**Comment by grobmeier** [comment]
Thanks @parkr - 7pm PST will be 4am my time, if I am correct:
http://www.timeanddate.com/worldclock/meetingdetails.html?year=2015&month=1&day=23&hour=3&min=0&sec=0&p1=137&p2=37&p3=2&p4=248&p5=240&p6=179

I will miss this one most likely, but look forward to the stream :)

**Comment by envygeeks** [comment]
I'm willing to make it a few hours later (about 6AM your time) but that's up to the rest of the team.

**Comment by troyswanson** [comment]
7pm PST is the latest I can swing.

**Comment by troyswanson** [comment]
https://plus.google.com/events/cbdrenqsd640jh1j4ohru55h71s

**Comment by envygeeks** [comment]
Uhm, wasn't it supposed to be today?

**Comment by troyswanson** [comment]
True enough. It's in 50 minutes. Sorry for setting the wrong date.

**Comment by troyswanson** [comment]
Try this one instead. https://plus.google.com/events/c8dj8ojg6tvvjl1rs00dsrdblb8

**Comment by alfredxing** [comment]
I'm watching the stream right now; I think I'm just going to listen in on this one.

**Comment by redknitin** [comment]
I watched the streamed event.

I think the one in Dec '14 was an hour long, whereas this one was for a half hour. Anyway, looking forward to the next one in February.

**Comment by troyswanson** [comment]
Glad you tuned in! An hour is a long time, so I tried to keep this one at 30 minutes. This is only the second one we did, so feedback is absolutely necessary for us to fine tune this thing.

**Comment by MartinRogalla** [comment]
@troyswanson do you have a date for the next Town Hall Meeting? I'm interested to see the current developments of Jekyll. I have watched the last two Town Hall Meeting and really enjoyed them.

**Comment by troyswanson** [comment]
@MartinRogalla Thanks, man. I just opened a new issue for Feb's Townhall (#3482).

Glad you've found our little chat sessions helpful. If you have any feedback on how to improve the meetings, please let us know.

I'm going to close this issue since it's long past.
