### ISSUE TITLE
Discussion about an easier Jekyll quick start

### ISSUE THREAD

**Issue by barryclark** [jekyll/jekyll#3191]
The discussion regarding ease of use and GitHub Pages in the #2358 Hangout around 26:00 was really interesting. @envygeeks mentioned "What is easy about Jekyll right now?".

I agree that it's pretty difficult to get started with Jekyll, about half of that difficulty comes from wrapping your head around the static site paradigm shift (mentioned by @troyswanson), and the other half is dependency installation pain.

Here are some ideas to throw out there that I had about possible alternate quick start workflows for newcomers getting started with Jekyll. The goal is to try to get them up and running as quickly and easily as possible.

#### Quick Start 1 - www.jekyllrb.com

This is the existing quick start for new users from www.jekyllrb.com:

1. gem install jekyll (and possibly have difficult with dependencies)
1. jekyll new my-awesome-site
1. cd my-awesome-site
1. jekyll serve
1. Stick your site on a host or go figure out how to use GitHub Pages to publish

#### Quick Start 2 - [barryclark/jekyll-now](https://github.com/barryclark/jekyll-now)

I think an easier workflow for getting started (assuming that you want to use GitHub Pages) is the one that I've detailed at https://github.com/barryclark/jekyll-now. 

1. Fork an existing template jekyll site
1. Rename the repository to make it your user repository
1. Edit the config / content to personalize
1. GitHub Pages builds your site and it's live in a few minutes

This uses GitHub Pages as the build server and GitHub as the CMS allowing you to get up and running extremely quickly. You can then `git clone` down from there if you'd like to build your site locally.

#### Quick Start 3 - [GitHub Pages automatic page generator](https://help.github.com/articles/creating-pages-with-the-automatic-generator/)

Workflow 2 is really just an MVP of what I think would be the most ideal getting started with Jekyll workflow. The easiest route (especially for less technical savvy users) would be if GitHub Pages provided an automatic generator for a blog template, like the [Automatic Generator for Pages](https://help.github.com/articles/creating-pages-with-the-automatic-generator/).

1. Create user repository
1. Click Automatic Page Generator
1. Select a blog theme
1. Select config and enter initial content for your blog
1. Theme gets spat out into your repository and built by GitHub Pages
1. Live immediately

**Comment by parkr** [comment]
Dependency headaches should be largely relieved with Jekyll 3, and ease of use is a constant concern with Jekyll. We will work diligently to ensure the priority of this product goal as Jekyll's development continues. Thanks, Barry!
