### ISSUE TITLE
Code blocks are not responsive

### ISSUE THREAD

**Issue by mehdisadeghi** [jekyll/jekyll#3192]
When I try a page which contains code blocks using `{% highlight %}` notation the page is not responsive anymore. Could this one be improved or it will be left as is?

**Comment by JesseHerrick** [comment]
@mehdisadeghi you could try percentages instead of multiple pixel media queries.

**Comment by kleinfreund** [comment]
@mehdisadeghi You don't even need to set `width` for the `pre` element. HTML block elements’ default is the responsive state. Only by adding fixed dimension they become unresponsive.

**Comment by mehdisadeghi** [comment]
@JesseHerrick Multiple media queries is just a workaround to force certain *fixed* `width` for poular devices such as my N5.

@kleinfreund You are right and I think this is the problem itself! Inside the code blocks I have some *comment* lines which are too long and the `pre` tag increases the width of the page and it goes off canvas.

Here is how it will look like if I use the default behavior (with percentage it is the same as well):
![image](https://cloud.githubusercontent.com/assets/3101557/5821431/73d9d9c6-a0cc-11e4-9f48-5470b1164502.png)

Thanks for the comments :)

**Comment by kleinfreund** [comment]
For lines with too long contents, scrolling is probably the desired behavior. Especially on narrow screen widths this quickly becomes hard to read or even unusable. I'm not sure how to deal with that right now.
