### ISSUE TITLE
Partials: Includes with layouts

### ISSUE THREAD

**Issue by koraktor** [jekyll/jekyll#32]
Call it partials, subpages or whatever. I came to a point where I wanted to generate multiple similar sections in a page and found no way to achieve this with Jekyll. Instead of writing lots of "copy & paste" code, I'd like to use some kind of partial (like in Rails).

I created a new tag for this, called `import`. It's more or less the same as the `include` tag, but it uses `Jekyll::Page` for rendering, not just `Liquid::Template`.

[koraktor/jekyll@import-tag](http://github.com/koraktor/jekyll/tree/import-tag)

Please note that this isn't perfect yet - e.g. you can't use this in Markdown or Textile files as line wraps and indentation are interpreted.

**Comment by ChrisSargent** [comment]
I know this is an old thread but it was the top Google result and I faced this problem recently. I wanted an include to use a particular layout when calling that include. A fairly simple way I found around not having this functionality, was to use the 'layout' as an 'include' (let's call it the layout-include.html) and pass a 'src' variable when calling the layout-include ('src' could be called anything of course but I think this fits well with normal html semantics).

So, this would be your layout-include.html file which contains all your layout markup etc. Nested inside is another include, where the source for the include is set to the variable {{include.src}}.

```html
<div class="layout">
    {% include {{include.src}} %}
</div>
```

Then, when you use the include-layout file, you pass in the include.src variable as follows:

```html
{% include include-layout.html src="include-content.html" %}
```

Unfortunately, markdown in the 'include-content' file won't be rendered (at least in my environment it wasn't) so it will have to be an html file.

Hope it helps someone out!

**Comment by gesa** [comment]
@ChrisSargent I'm curious what version of Jekyll you're using. When I try to use this solution, I get the error `Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: Valid syntax: {% include file.ext param='value' param2='value' %} in _layouts/white-container.html`

Also, it's a little convoluted, but to get Markdown, perhaps you could do

```
{% include include-layout.html src="include-content.md" %}
```

```
<div class="layout">
{% capture thisPage %}
    {% include {{include.src}} %}
{% endcapture %}
{{ thisPage | markdownify }}
</div>
```

**Comment by ChrisSargent** [comment]
@gesa, it seems I have Jekyll 2.5.3 installed.

I just updated my comment too to make it a little clearer.

**Comment by davidgoli** [comment]
@qrush I don't think `include` addresses the use case for `import`. Consider:

```
---
layout: some-nested-thing
---
{% import section-wrapper %}
Some really long block of text
....
blah
{% endimport %}

{% import section-wrapper %}
Another long block of text
...
blah
{% endimport %}
```

I'm low-key shocked that this templating system doesn't support this as it's a really basic feature supported by haml, handlebars, and many other popular templating languages and not at all a power-user feature as you suggest.

**Comment by daurnimator** [comment]
I too would love for this to be reopened.

**Comment by lukeeey** [comment]
Same

**Comment by SaswatPadhi** [comment]
Same

**Comment by ashmaroli** [comment]
Jekyll has two Liquid Tags to provide this functionality:
  - `{% include .. %}`
  - `{% include_relative .. %}`

Please refer our documentation at https://jekyllrb.com/docs/includes/ to decide which tag best fits your use-case.
