### ISSUE TITLE
safe_yaml problem?

### ISSUE THREAD

**Issue by jaydreyer** [jekyll/jekyll#3201]
I'm stumped. I can't get a skeleton site created. Here is the output:

Jays-MacBook-Pro-5:~ jay$ jekyll new deanne
/Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:4:in `<class:PsychResolver>': uninitialized constant Psych::Nodes (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:2:in`module:SafeYAML'
    from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:1:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in`require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:131:in`module:SafeYAML'
    from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:26:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in`require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/lib/jekyll.rb:26:in`<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in`require'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.2/bin/jekyll:6:in `<top (required)>'
    from /usr/bin/jekyll:23:in`load'
    from /usr/bin/jekyll:23:in `<main>'

Any ideas? Can't find an answer via Google and I'm stumped as to what to do. Was able to get everything set up on another computer, but not mine.

**Comment by nielsgl** [comment]
This is still an issue, install the gem from RubyGems on my Mac results in the same error. I cloned the source from the repository and after building the gem with bundler and installing it did work. It seems that the jekyll binary from the 2.5.3 version on RubyGems is behind the one in this repository with the fix, so I think that bumping the version should resolve it.

**Comment by parkr** [comment]
Jekyll is not distributed as a binary, but rather a series of library files. If you have an old version of `safe_yaml` installed, you will have to remove it and install the latest. This is a problem with safe_yaml, not with Jekyll.

**Comment by djmtype** [comment]
Here's a list of my gems. 

```
jekyll (2.5.3)
jekyll-coffeescript (1.0.1)
jekyll-gist (1.1.0)
jekyll-paginate (1.1.0)
jekyll-sass-converter (1.3.0)
jekyll-watch (1.2.0)

psych (2.0.5, 2.0.2)

safe_yaml (1.0.4)
```

I only have one version installed of each – the most current – with the exception of Psych. But, it should be reading Psych 2.0.5. I ran `sudo gem cleanup` and I'm still unable to create a new Jekyll project.

**Comment by parkr** [comment]
This looks like https://github.com/dtao/safe_yaml/issues/72

**Comment by brunobatista** [comment]
+1

**Comment by jaysalvat** [comment]
Hello.

Same problem here.
Can't use Jekyll anymore.

**Comment by jaysalvat** [comment]
Fixed it with the help of https://github.com/dtao/safe_yaml/issues/72

    sudo gem uninstall psych -v 2.0.5

It did the trick.
Hope it helps.

**Comment by dyscribe** [comment]
I also encountered this error on my local machine and had `psych (2.0.12, 2.0.5)` in my gem list. 
On my server Jekyll was working fine with `psych (2.0.5, 2.0.3)`.

When I tried to run the command above I received `gem "psych" cannot be uninstalled because it is a default gem`. In my case I got it working with removing version `2.0.12` and reinstalling `2.0.3` using `gem install psych -v 2.0.3`. 

Thanks everyone for the input! :+1:

**Comment by AbdullahAlger** [comment]
+1 @dyscribe

**Comment by sghiassy** [comment]
+1 @dyscribe

**Comment by zx1986** [comment]
`gem cleanup` works for me too.
