### ISSUE TITLE
"Failed to build gem native extension." on win7

### ISSUE THREAD

**Issue by zieckey** [jekyll/jekyll#3208]
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

```
d:/Ruby21-x64/bin/ruby.exe extconf.rb
```

creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating stemmer-x64-mingw32.def
compiling porter.c

compiling porter_wrap.c
In file included from d:/Ruby21-x64/include/ruby-2.1.0/ruby/ruby.h:29:0,
                 from d:/Ruby21-x64/include/ruby-2.1.0/ruby.h:33,
                 from porter_wrap.c:1:
d:/Ruby21-x64/include/ruby-2.1.0/ruby/defines.h:65:22: fatal error: setjmpex.h: No such file or directory
compilation terminated.
make: **\* [porter_wrap.o] Error 1

make failed, exit code 2

Gem files will remain installed in d:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/fast-stemmer-1.0.2 for inspection.
Results logged to d:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/fast-stemmer-1.0.2/gem_make.out

**Comment by vishnuc17** [comment]
I also have the same issue,am working on 64 bit operating system.How do i fix this?

**Comment by alfredxing** [comment]
@vishnuc17 If you're using RubyInstaller, make sure you get the 64-bit DevKit, and not the 32-bit one.

**Comment by vishnuc17** [comment]
Thanks it worked

**Comment by brianunlam** [comment]
@alfredxing Ey dude!, you save my day! Thanks a lot!
