### ISSUE TITLE
Yet another "in_source_dir" error upon upgrade

### ISSUE THREAD

**Issue by philipmjohnson** [jekyll/jekyll#3214]
I just attempted to upgrade Jekyll from 2.1.0 to the latest release (2.5.2) using 'sudo gem install jekyll' on MacOS.  

After doing so, my site, which ran fine under 2.1.0 would not build and instead generated for each markdown file an error of the form:

```
Error reading file .... undefined method: `in_source_dir' for nil:NilClass
```

I did some googling and tried to install Jekyll using Bundler following the recommendations [here](https://help.github.com/articles/using-jekyll-with-pages/) and [here](http://matthodan.com/2012/10/27/how-to-create-a-blog-with-jekyll.html), but this did not solve the problem.

To reproduce the problem, you can follow the instructions in the [Morea Framework Quickstart](http://morea-framework.github.io/quickstart.html).  In fact, I became aware of this problem after a new Morea user reported it [here](https://github.com/education/teachers/issues/24). 

I would appreciate any suggestions as to how to fix this problem.  Thanks!

**Comment by eduOS** [comment]
I ran into a snag showing as the following when I ran bundle exec jekyll serve --trace: 
``` 
/usr/local/rvm/gems/ruby-2.1.2/gems/bundler-1.7.12/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': jekyll is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from /usr/local/rvm/gems/ruby-2.1.2/bin/jekyll:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```
What should I do next? 

Thanks,
Leo

**Comment by sondr3** [comment]
Have you tried adding Jekyll to your Gemfile as the error says you should?

**Comment by eduOS** [comment]
I don't know how I could add Jekyll to Gemfile..
I only found one similar question here: orlando/svbtle-jekyll#1, but got no answer. 
Sorry for the silly question.

**Comment by sondr3** [comment]
Do you have a Gemfile in your Jekyll directory? If you do then add `gem "jekyll"` to it.

**Comment by orlando** [comment]
@eduOS here's an example gemfile for jekyll https://github.com/orlando/svbtle-jekyll/blob/master/Gemfile. also remember do `bundle install` to create `Gemfile.lock`. Commit both files

**Comment by eduOS** [comment]
Thanks very much @sondr3. But I encounter an other error: 
```
Your Gemfile lists the gem jekyll (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
You cannot specify the same gem twice coming from different sources.
You specified that jekyll (>= 0) should come from source at . and
```

**Comment by eduOS** [comment]
Thanks after downloaded and run ```morea-merge-upstream.sh```, I made it works.

**Comment by sondr3** [comment]
Did you close the whole Jekyll directory from Github instead of installing the Jekyll? Because that would explain it. Besides, the source line should be at the top.

**Comment by sondr3** [comment]
Wow, my phone was not cooperating there. I meant if you cloned the Jekyll directory instead of installing the Jekyll gem.

**Comment by parkr** [comment]
If you clone the jekyll source code, you just run `bundle install`, then `bundle exec bin/jekyll`. But that's for development, not for usage. To install for usage, run `gem install jekyll` and then just use the command `jekyll`.

**Comment by ttimsmith** [comment]
What helped me:

1. Run `gem cleanup`
2. Delete `Gemfile.lock`
3. Use the gem line with version number straight from [RubyGems.org](https://rubygems.org/gems/jekyll).
