### ISSUE TITLE
Jekyll Serve doesn't start server, doesn't show any errors. Using Windows

### ISSUE THREAD

**Issue by JasonSwingen** [jekyll/jekyll#3221]
![jekyll-serve](https://cloud.githubusercontent.com/assets/6412968/5508034/4fc01888-876e-11e4-8c84-ba9d0f2ef5f5.JPG)

I am new to jekyll and already hit almost all of the windows related jekyll problems and fixed them.

Now  when I try to serve jekyll I am not receiving any errors.

If I make a new jekyll site and serve it, it will work, but when I try to serve the my current website (jasonswingen.github.io) it will not start the server.

**Comment by JasonSwingen** [comment]
Thank you so much Axi5. That solved the problem. I uninsulated jekyll version 2.5.2 and installed version 2.1.1 and it is now serving my site.

**Comment by Leeforall** [comment]
thx very much, it works for me @JasonSwingen @Axi5
