### ISSUE TITLE
Use Liquid::Drop to liberate and speed up Jekyll.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3224]
This is probably something for the Jekyll rewrite but recently while working on an an app we had performance problems even with user caching because of the way we were processing the liquid and I discovered `Liquid::Drop` (https://github.com/Shopify/liquid/wiki/Introduction-to-Drops) and while a lot of people use it for security we actually used it to our advantage because of the way it was designed.  We used it to defer processing of data by routing in and routing back out to the object that got routed in which increased our sites performance exponentially (you're talking going from 500ms to the average load of 20ms)

That basically means that a Page has Posts, the Page gets to_html ran with :vars => { :posts => [] } with the array being a bunch of Post drops and those post drops are just references to the objects we want to allow on Post (say title, blah, blah, blah) but there is one difference, normally we would pre-render content of those posts, with a drop we create a content method that allows us to defer the processing until the user wants it processed and when the user sends a message to the content method on the drop we then finally route `#content` back to `Post#content_as_markdown`.

Here let me show you in code because I'm bad at explaining: https://gist.github.com/envygeeks/52aadf5ad9166eec11dd

The above is a working example of how fast it could be, it creates 1000 posts and defers the content until the user wants it (rendering and reading!), but writes 12 of those posts, tell me it isn't fast.  To test it against Jekyll in actuality I would have to rewrite the parts of current Jekyll to use Drops (which wouldn't be that hard to do but would have to wait until I have time over the next few days.)

Advantages:

1. #3116 by @alfredxing can get exponentially faster and/or more efficient in regeneration.
2. We have a single place for people to look at when people want to see what data goes into Jekyll.
3. We have an entry point to start allowing people to insert data into Jekyll easier.

Disadvantages:

It doesn't really provide a boost to Jekyll as a whole other than making it "feel more responsive" because it will load tons faster but it could provide some benefits if mixed with with the way @alfredxing wants it to work and with the way that Jekyll is currently designed because incremental generation in both Jekyll and life incremental generation become significantly faster because of all the deferring, we are only reading what has actually changed and not reading everything upfront.

---

What I mean by all the above is that in total it probably wont help us much unless we mix it with incremental generation, and if we do, things just got tons faster because of the deferring alone, we could do that without drops, but we could do it cleaner and in a more encapsulated extensible way with drops because then we add data points to the drops, not to Jekyll's core.

**Comment by alfredxing** [comment]
I just went over this idea again and I'm more confused. From what I understand about Drops, they have the ability to only be rendered when referenced. However, I don't see how this would provide much benefit, except if you had lots of pages/posts that were never used (for example, your example above where you had 1000 posts but only used 12)?

It also wouldn't get rid of the need for incremental regeneration dependency tracking as I had originally thought&mdash;for example, if an include changes, how would the Drop system detect that?

**Comment by envygeeks** [comment]
While your stuff was listed as an advantage, drops aren't for anything you've done @alfredxing... at the end of the day... they are for us to simplify the way we work with Liquid, if we use drops we can track what data goes out a lot easier and in a more common way without having to have our own classes with all the stuff we currently have.

That said it doesn't really need to track anything it uses a deferred model but the implmentation is yet to be finalized so I would wait to refute anything until I have the concept down in full and have a branch with the idea implemented but there are far bigger things on my plate right now so this has taken a low priority in my personal backlog.

With all that said... this is very low priority to me, I will try my best to get it into Jekyll 3 (that is if @parkr is willing to make the possible 3 release an alpha this round rather than a beta) but the fact of the matter is on the matters most important to me testing has become an obvious problem for me because I've discovered several major problems with our testing as it stands and I'll hate myself if I don't make fixing our tests a \#1 priority.

**Comment by parkr** [comment]
:+1: to fixing tests. So needed. :heart:

This is great for Liquid, but if we were going to allow other parsers as plugins in the future, this would make it a lot harder. Just a side thought.

**Comment by parkr** [comment]
I think we should start tackling this. I did a preliminary test and moving `to_liquid` into Liquid Drops makes it much, much faster. We create a lot of unnecessary objects in to_liquid. We should also move URL placeholders into this framework – we create a lot of unnecessary objects there, too.

**Comment by envygeeks** [comment]
I still have a lot of that old drop code laying around, I'll pull it out this weekend and see what we can salvage into an idea to start a group pull with a branch.

**Comment by alfredxing** [comment]
:+1: Implementing this would be great. I'll be done my exams on Thursday so I'll probably be catching up and doing some work over the weekend! (e.g. improving incremental, writing docs, etc.)

**Comment by parkr** [comment]
Follow-up additions: https://github.com/jekyll/jekyll/pull/4281& https://github.com/jekyll/jekyll/pull/4285.
