### ISSUE TITLE
cannot create a new project with jekyll

### ISSUE THREAD

**Issue by schaary** [jekyll/jekyll#3238]
I use ruby version 2.2.0 on macosx 10.10.1 - with rbenv as version manager
1. gem install jekyll   #=> works fine, finishes without errors
2. jekyll new schaary.blog
   /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/liquid-2.6.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"
   /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/source/git/git_proxy.rb:151:in `allowed_in_path': The git source git://github.com/nixme/jazz_hands.git is not yet checked out. Please run`bundle install`before trying to start your application (Bundler::GitError)
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/source/git/git_proxy.rb:47:in`revision'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/source/git.rb:212:in `revision'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/source/git.rb:81:in`install_path'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/source/path.rb:126:in `load_spec_files'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/source/git.rb:185:in`load_spec_files'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/source/path.rb:92:in `local_specs'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/source/git.rb:155:in`specs'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/definition.rb:511:in `block in converge_locked_specs'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/definition.rb:500:in`each'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/definition.rb:500:in `converge_locked_specs'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/definition.rb:190:in`resolve'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/definition.rb:132:in `specs'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/definition.rb:177:in`specs_for'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/definition.rb:166:in `requested_specs'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/environment.rb:18:in`requested_specs'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:13:in `setup'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler.rb:122:in`setup'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'
       from /Users/schaary/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:16:in`<top (required)>'
       from /Users/schaary/.rbenv/versions/2.2.0/bin/jekyll:23:in `load'
       from /Users/schaary/.rbenv/versions/2.2.0/bin/jekyll:23:in`<main>'

I have no idea what to do :(

**Comment by kylejm** [comment]
I get the same "warning: duplicated key at line 46 ignored: "index0"" when entering jekyll server. I googled around a bit and found one recommendation to make sure that I've got at least Python 2.7, which I have.

The server works fine, but I get this warning each time. Is this worrying? Could it be causing issues? Will it cause and issue when GitHub builds my site?

Thanks so much for help :smile:

**Comment by parkr** [comment]
The warning is not an issue, don't worry.
