### ISSUE TITLE
A general solution to allow interpolation of items passed in to Liquid tags. (Proposal for 3.0)

### ISSUE THREAD

**Issue by tamouse** [jekyll/jekyll#3249]
*(Edit: I meant this to be a discussion for 3.0)*

This has come up with regard to `{% include %}` tags before, and there have been some solutions there, however, it's also a general problem with Liquid tags. I don't believe a solution is possible in the current architecture, and I'm pretty sure it's not possible given just the Liquid implementation, which means something maybe needed in addition.

In looking at the `flickr_photoset` plugin <https://github.com/j0k3r/jekyll-flickr-photoset/blob/master/_plugins/flickr_photoset.rb#L34-L37> the author is doing something somewhat tricky to render the variable in the current context. This actually appears to work, *however*, only within the current context. So this works:

```
---
layout: post
title: "My Gallery"
gallery: 72157646883230496
---

{% flickr_photoset page.gallery %}
```

However, if one tries to do something like so, in another page:

```
{% for post in site.posts %
{% flickr_photoset post.gallery %}
{% endfor %}
```

Then the context is lost when it comes time to render that page, and only one photoset is rendered in each iteration.

It would be wonderful to have a more general approach that would work in all contexts.

I don't know if this is possible, at all, but I'd hope we can entertain some discussion.

**Comment by parkr** [comment]
We did this: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/liquid_extensions.rb

:)

**Comment by acaid** [comment]
parkr, so in theory this syntax should function correctly?

```liquid
{% for post in site.posts %}
  {% if post.gallery %}
    {% flickr_photoset post.gallery %} 
  {% endif %}
{% endfor %}
```

**Comment by parkr** [comment]
With the above code, yes!

**Comment by acaid** [comment]
Sorry for the basic question. Still quite new to ruby. I'm not sure where you mean to use
```liquid
include Jekyll::LiquidExtensions
```
In jekyll.rb it looks like it's loaded by default...
```ruby
require 'jekyll/liquid_extensions'
```
Thanks :)

**Comment by parkr** [comment]
Requiring loads the module into the runtime, but it doesn't apply it to the class you want to use it in. In order to use the method, you have to:

```ruby
module Jekyll
  class FlickrPhotosetTag < Liquid::Tag
    include Jekyll::LiquidExtensions

    def render(context)
      if @photoset =~ /([\w]+\.[\w]+)/i
        @photoset = lookup_variable(context, @photoset)
      end

      # ...
    end
  end
end
```

**Comment by acaid** [comment]
Maybe the issue is in 
```ruby
def initialize
```
but I'm still seeing the same issue described in the original post, even after implementing what you described in your last comment.

**Comment by parkr** [comment]
> Then the context is lost when it comes time to render that page, and only one photoset is rendered in each iteration.

Hm. What does `Shellwords` do? https://github.com/j0k3r/jekyll-flickr-photoset/blob/master/_plugins/flickr_photoset.rb#L24

**Comment by acaid** [comment]
It's being used to split the arguments into an array. For the purposes of debugging I've set all other variables manually within the script and I'm only passing the first argument with the page.gallery liquid variable. Seems like shellwords could be omitted, but when I've tried it seems 'page.gallery' gets parsed as a string instead as a variable within the script.
