### ISSUE TITLE
How to create the multiple github pages in one server locally

### ISSUE THREAD

**Issue by icai** [jekyll/jekyll#3250]
for example:

I want to builld the bootstrap docs and some other github project docs(github pages) locally, and assume that they are using `jekyll`.

when I checkout them(github pages) in a direction(root ), my question that can I use `jekyll serve` on the root direction to run the server as the single one github page. If this is no, can I use something to solve this.

**Comment by parkr** [comment]
You have to give them separate ports. By default, Jekyll just chooses `4000`. You can't use the default twice, so you'd have to do:

```text
$ jekyll serve # for one site
$ jekyll serve --port 5000 # for another, in another terminal window
```
