### ISSUE TITLE
link broken within quote for Eastern Asian language

### ISSUE THREAD

**Issue by Hasset** [jekyll/jekyll#3252]
Recently I found that jekyll does not resolve link mark within a quote paragraph. For example:

Here are the [raw code](https://github.com/Hasset/hasset.github.com/blob/master/_posts/2014-06-29-anti-iad-die.md). I am sorry that this article was writen in Chinese, but I'd like to point out that the link with quote were after these words: **(([zotpress item=8SI9DMMA]))、 (([zotpress item=VAGQ2NAR]))**
Here are the [resolved page](http://hasset.github.io/diary/2014/06/29/anti-iad-die/)

**Comment by parkr** [comment]
Try another markdown converter. This might be a problem with Kramdown. Jekyll doesn't handle this data by itself. It passes it to Kramdown (or RedCarpet, etc).
