### ISSUE TITLE
Jekyll runtime issues

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll#3259]
Hi

I need help - I built and tested a local site (a blog) using Jekyll without using `bundler` - it worked find and I managed to push it successfully to the location on GitHub where it was hosted.

Then, after reading the instructions at GitHub pages, I decided to do that `bundler` thing (what exactly does it do?), and added a Gemfile to the root of my local static Jekyll site and running `bundle install` and `bundle exec jekyll serve`, which starts the local server.  The blog looks fine, and I use GitHub for Mac to push any changes to the GitHub hosted blog repo.
 
But there seems to be a problem with Jekyll itself (without doing `bundle exec jekyll serve`):

    WARN: Unresolved specs during Gem::Specification.reset:
         redcarpet (~> 3.1)
    WARN: Clearing out unresolved specs.
    Please report a bug if this causes problems.
    /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load  such    file -- jekyll/version (LoadError)
   	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
 
I thought this was due to some outdated gems, so I updated them using `sudo gem update`.  Now when I run Jekyll I get the following error:

    /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:4:in    `<class:PsychResolver>': uninitialized constant Psych::Nodes (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:2:in `<module:SafeYAML>'
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:131:in `<module:SafeYAML>'
	from /Library/Ruby/Gems/2.0.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll.rb:26:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:6:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'

I don't know what the problem is - basically I seem to be able to test the blog locally by doing `bundle exec jekyll serve`, but I cannot do the same by doing `jekyll build` and `jekyll serve`.  Any help appreciated?

**Comment by parkr** [comment]
It's our bundler integration.

**Comment by sr-murthy** [comment]
Thanks.
