### ISSUE TITLE
Liquid Filter "Slice" Isn't Working

### ISSUE THREAD

**Issue by pattulus** [jekyll/jekyll#3260]
I'm currently on the lastest version of Jekyll (2.5.3). The slice filter for strings isn't working.

I also tried it with the example `{{ "hello" | slice: -3, 3 }}`, but nothing happens, not even an error to add here.

This seems to be the status quo since Jekyll 2.4 ([Tags and Filters](http://jekyll.pygmeeweb.com/tests/#panel-106))

It would be cool and useful if it works again.

**Comment by parkr** [comment]
Hm... when do you remember it working? [It's not in Liquid 2.6.x](https://github.com/Shopify/liquid/blob/2-6-stable/lib/liquid/standardfilters.rb).

**Comment by pattulus** [comment]
I honestly don't know, I just took a look at ["Liquid for Designers · Shopify/liquid Wiki"](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers)… but that pretty much explains it. I was ablee to workaround it using split.

**Comment by parkr** [comment]
Liquid 3 comes out with Jekyll 3. Soon :smile:

**Comment by MCMic** [comment]
Same problem here, slice is not working. Any workaround?

**Comment by MCMic** [comment]
Ok, so workaround with split to get the first letter of the title:
{% assign title_letter = post.title | split: '' | first %}

**Comment by alessandrococco** [comment]
I just noticed the same problem, thanks @MCMic for the workaround ;)

**Comment by edhenderson** [comment]
jekyll 2.4.0 I ran these 3 tests locally:

```
1{{ "ABC" | slice: 0, 1 }}1 => 1ABC1
2{{ "ABC" | slice: 0,1 }}2 => 2ABC2
3{{ "ABC" | slice: 0 }}3 => 3ABC3
```

**Comment by kenold** [comment]
@MCMic Thanks for the fix. It works OK with strings. How would I go about getting the last number of an integer ex: 52 ?

**Comment by envygeeks** [comment]
@kenold please ask your question at https://talk.jekyllrb.com since this is not related to a bug.
