### ISSUE TITLE
Search for Jekyll Collections

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll#3262]
Hello,

Can anyone recommend a search plugin which powers Jekyll Collections?

**Comment by budparr** [comment]
The best is the Jekyll plugin for Lunr.js, which search should support them soon (there's been an unmerged PR for a while though). I use [List.js](http://www.listjs.com/), which isn't exactly search, but quite configurable filtering ([example](http://www.iliadx.us/sitemap/)), and there's [Jekyll Search](http://mathayward.com/jekyll-search/), but it's a bit finicky to get working. You could also try [Tipue](http://www.tipue.com/search/) or [Swiftype](https://swiftype.com/).

**Comment by iloveip** [comment]
@budparr Thank you very much! Do you mean Lunr.js https://github.com/slashdotdash/jekyll-lunr-js-search?

**Comment by iloveip** [comment]
@budparr Ok, thank you very much.
