### ISSUE TITLE
Related documents in Collections

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll#3263]
Hello,

Is there any way I can reference in a document related documents in the same collection via YAML front matter or data files?

I would like to add related links after each document in a collection, something similar to `related_posts` but hand-picked and for collections.

**Comment by parkr** [comment]
No, `related_posts` is only available for posts at the moment. If we move `posts` to be a default collection, then this will change.

**Comment by budparr** [comment]
@iloveip Do you have a more specific use-case? There are lots of things you can do with the [Where filter](http://jekyllrb.com/docs/templates/#filters) or using 'contains' in a conditional, so maybe with more information someone can help (perhaps better over at Jekyll-Help)

**Comment by iloveip** [comment]
@budparr I use documents in collections as knowledgebase articles. After some articles I would like to add a set of related links to other articles. Also I will need to add some PDF files specific to each article. So is there any way I can do it in one place for all articles?

**Comment by budparr** [comment]
>  a set of related links to other articles

I assume you mean other articles in the collection. I do something like [this:](https://github.com/ABA-Center-for-Human-Rights/aba-icc/blob/gh-pages/_includes/nav/prev-next-links.html)

```
{% capture the_collection %}{{ page.collection }}{% endcapture %}

{% if page.collection %}
  {% assign  topic = site[the_collection]  %}
{% endif %}

{% for links in topic %}
stuff here
{% endfor %}
```
Seems to work for me. You can look at the link to the repo above for more details, though it's complicated with other things.

**Comment by iloveip** [comment]
@budparr Ok, I will try it. Thank you very much.
