### ISSUE TITLE
pretty permalinks not displaying correctly

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll#3267]
Hi

I've set the permalink style to `pretty` in `_config_yml` like

    permalink: pretty

I'm testing this locally but I've noticed the post URLs on my archive page contain commas.  For example, one post with source `Bashed.md` has the categories `OS X, Shells` in the YAML header, but the URL for this post appears on the archives page as

    http://localhost:4000/os/x,/shells/2015/01/08/Bashed/

The spaces in "OS X" are being used as separators, I thought it was commas separating different categories.

Also, is there a way of removing categories from `pretty`?  Thanks.

**Comment by yihangho** [comment]
Category (or categories) is either a space-separated string or a YAML list. Hence, you should do either of these instead:

```yaml
categories: [OS X, Shells]
```

```yaml
categories:
  - OS X
  - Shells
```

Simply set `permalink: /:year/:month/:day/:title/` in `_config.yml` to remove categories from the permalink.

**Comment by sr-murthy** [comment]
Hi 

thanks.  On <a href="http://jekyllbootstrap.com/lessons/jekyll-introduction.html" target="_blank">Jekyll Bootstrap</a> the section on categories says that `categories: [OS X, Shells]` will create Shells as a subcategory of OS X, but I want the post to be tagged under two separate categories.  I tried and that is what it appears to be doing. I haven't tried

    categories:
      - OS X
      - Shells

**Comment by yihangho** [comment]
AFAIK, there are no subcategories in Jekyll. Hence, either way, two categories will be created.

I suggest that you refer to the official documentation of Jekyll instead of Jekyll Bootstrap: the JB docs were last updated 3 years ago!
