### ISSUE TITLE
A variable for posts category

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll#3268]
Hello,

I would like to have some different html for posts in different categories. So in my layout template I would like to have something like this:

````
{% if page.category == 'category1' %}
    <a href="/kb/#category1">
        <span>{{ page.order }} from 10</span>
    </a>
{% elsif page.category == 'category2' %}
    <a href="/kb/#category2">
        <span class="num">{{ page.order }} from 7</span>
    </a>
{% endif %} 
````

It worked for documents in collection, but doesn't work for posts. Although I have categories for posts defined in front matter defaults. Is there any variable similar to `page.category` but for posts?

**Comment by yihangho** [comment]
I guess you should be using `page.categories` (plural) instead:

```
{% if page.categories contains 'category1' %}
  <!-- Stuff for category1 -->
{% elsif page.categories contains 'category2' %}
  <!-- Stuff for category2 -->
{% endif %}

**Comment by iloveip** [comment]
@yihangho Thank you very much! It's working now.
