### ISSUE TITLE
Pagination without subfolders

### ISSUE THREAD

**Issue by purpleKarrot** [jekyll/jekyll#3272]
Setting `pagination_path` to "blog/page:num/" creates the second page as "blog/page2/index.html", fine.

When `pagination_path` is set to "blog/index:num.html", the expected path for the second page is "blog/index2.html". However, it is generated as **"blog/index2.html/index.html"**.

This behavior is inconsistent with that of `permalink`.

**Comment by parkr** [comment]
Interesting. The pagination plugin is at jekyll/jekyll-paginate. Let's continue the conversation over there (preferably with code :))
