### ISSUE TITLE
Pagination when the index.html has had its name changed

### ISSUE THREAD

**Issue by mildrenben** [jekyll/jekyll#3282]
Hey guys,

So I changed the original index.html file to blog.html and then added in my own index.html. So blog.html is at the root of the dir.

Whenever I try and paginate it says ' Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination'.

How would one fix this?

**Comment by parkr** [comment]
You can't use any file other than `index.html`. This is a problem with the jekyll-paginate project, not with Jekyll core. Thanks!
