### ISSUE TITLE
Lower-case category in permalink breaks all inbound links

### ISSUE THREAD

**Issue by SurajGupta** [jekyll/jekyll#3285]
Hello.  I've had been using an older version of Jekyll and recently upgraded to the latest version as part of setting up a new box.  It seems that in the latest version, `:categories` in permalink resolves to the lowercase version of whatever categories are in my post instead of the category as specified (my posts use first-letter-upper-case).  That has effectively broken all inbound links to my site because URLs are case sensitive and inbound links are using URLs as I originally published them.  Needless to say, this really sucks.  Is there a way to get a configuration option that will respect the case of categories so that Jekyll is backward compatible?

**Comment by parkr** [comment]
> Is there a way to get a configuration option that will respect the case of categories so that Jekyll is backward compatible?

No, I'm sorry, this isn't possible. You'd have to downgrade for now (we keep all versions on RubyGems.org). We've been having discussions around this:
#1739 #2571.

**Comment by SurajGupta** [comment]
Could you point me to the last version that maintains the case of categories?  Also, really hoping you guys change your minds on this - I imagine there must be many sites that would be affected by this issue.  Seems like a crumby penalty for adopting earlier versions of Jekyll.

**Comment by parkr** [comment]
It's been this way since v1.0.0: #842, #872. I guess it'd break current sites if we changed it back now. It's not meant to be a penalty, it's just the changes that have been made since you last upgraded. In our defense, it's been a while, and there are two major version bumps in the middle.

**Comment by SurajGupta** [comment]
So wouldn't a config option help everyone?  =)  You could default to the way it works now.  I don't think the number of versions since v1 is relevant here - at some point someone made a call that it was OK to break pre-existing (and probably a substantial number) of sites with no backward compatibility.  It's not simply a matter of changing the way our sites work.  I'm happy to use lower-case!  But my blog posts are linked by other sites, and I cannot possibly ask everyone who links-into my site to update their site.  It's a bit frustrating given how much energy and effort went into launching the site, writing posts, and getting people to read/considering linking to them, and particularly when we're talking about the case of a single term in a URL.  Is it a ton of effort to support this?

**Comment by parkr** [comment]
> number of versions since v1 is relevant here

The number of `MAJOR` bumps does matter – we follow SemVer, so a MAJOR bump means there are breaking changes. We try our hardest not to change things but 1.0 was a reimagining of Jekyll to a certain degree, so breaking changes were inevitable. Sorry you ran into this one.

> But my blog posts are linked by other sites, and I cannot possibly ask everyone who links-into my site to update their site.

An alternative is to setup your server to handle both unaltered and downcase'd URL's. Is that possible? Alternatively, you can use jekyll-redirect-from. Either of those would be a stop-gap solution until we have a better solution for everyone.

> So wouldn't a config option help everyone?

One thing that frustrates me is that we throw configuration options at everything. This may be an appropriate place to use a configuration option, but I'm unsure. It makes sense to differentiate between `Apple` and `apple`, two semantically different things, but not between `Orange` and `orange` and `OrANge`. If we had an option `category_case` with options `mixed` & `downcase`, would that work?

**Comment by SurajGupta** [comment]
Hi Parker - I sincerely appreciate your willingness to dialog about this.  I'm hosted on GitHub Pages, so I don't think I can control any server behavior?  

I completely agree with your frustration about config.  In general I'm a fan of convention over configuration.  In this particular case and given the great flexibility that Jekyll affords site authors across-the-board, the inability to control the appearance of categories and thus the appearance of the URL seems philosophically divergent.  Also, categories seems to be the only Permalink token/variable that's manipulated from it's original form.  Other variables such as year, day, title, appear as specified (either by nature of the datatype - int for most, or in the case of Title it's just taken as-is).

In terms of the proposed solution, I would support `downcase` and `as-is`.  `mixed` is a bit confusing because it's not obvious whether the system is going to do any manipulation and you might not actually have any mixed case categories at all.  `downcase` is clear - Jekyll will downcase stuff.  `as-is` is clear - Jekyll will just take your category values as-is.

Perhaps one way to build this so that it doesn't feel idiosyncratic to category and is more future-proof is to make it a Permalink config option.  So, optionally, you can specify how to case one or more Permalink variables.  That way, if new Permalink variables are introduced they can inherit this capability.  Here's a proposed syntax, but I'm sure you can come up with something much better:

    permalink:     
        format:  pretty
        categories_format: downcase
        title_format: as-is

thoughts?

**Comment by SurajGupta** [comment]
Hey Parker - any thoughts on my last post?

**Comment by x-way** [comment]
As this issue was bugging me too, I've written a small patch for a config option which enables case sensitive categories: x-way/jekyll@6aa23fcadd9d94ce2c24d907635d3bba900cafb4

**Comment by SurajGupta** [comment]
@x-way could you submit this as a pull request?
@parkr would you be willing to accept this solution?  would be a HUGE help.
