### ISSUE TITLE
A command line flag for different deployments

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll#3286]
Hi

At the moment it seems as if (correct me if I'm wrong) that there is no way to set the site url in `_config.yml` dynamically at build time.  This would be useful in situations when you are trying to publish the same site to different URLs (<username>.github.io and your personal domain URL or some other location).  At the moment I have to manually change the `site.url` variable to <username>.github.io or <personal domain> in `_config.yml` before building and generating the static site.  It would be nice to something as follows:

bundle exec jekyll build --seturl <url>

which would generate the same site but with `site.url` pointing to <url>.

Is there something I'm missing (please correct me if so) or can this be added easily?

Thanks, Sandeep

**Comment by parkr** [comment]
One would achieve this by having a custom config file and calling:

```text
$ bundle exec jekyll build -c _config.yml,_config.prod.yml
```
