### ISSUE TITLE
Using variables in css files

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll#3290]
Hi

I wish to specify a transparent background image for a CSS sidebar on my site.  At the moment I have to specify the full path of the image file in the CSS file, e.g.

    background-image: url( "<url>/assets/sidebar-background.png" )

I can't do something like this

    background-image: url( "{{ site.url }}/assets/sidebar-background.png" )

Jekyll doesn't seem to recognise this - sidebar is blank because it can't find the image.

Am I missing something, or is there a way to use variables in CSS files?

Thanks in advance.

**Comment by yihangho** [comment]
Just add an empty front matter to the top of the CSS files:

```
---
---

/* Other CSS rules */

background-image: url( "{{ site.url }}/assets/sidebar-background.png" )
```

**Comment by parkr** [comment]
What he said ^^

**Comment by sr-murthy** [comment]
Thank you.
