### ISSUE TITLE
Paginator problem

### ISSUE THREAD

**Issue by sr-murthy** [jekyll/jekyll#3294]
My paginator on `index.html` seems broken - currently it looks like this

![paginator_problem](https://cloud.githubusercontent.com/assets/9358070/5709225/e90b6252-9a8f-11e4-9036-5cb4eeb9b534.png)

Could someone please help?  Here's the code:

    <div class="pagination">
      {% if paginator.next_page %}
        <a class="pagination-item older" href="{{ site.url }}page{{paginator.next_page}}">Older</a>
      {% else %}
        <span class="pagination-item older">Older</span>
      {% endif %}
      {% if paginator.previous_page %}
        {% if paginator.page == 2 %}
          <a class="pagination-item newer" href="{{ site.url }}">Newer</a>
        {% else %}
          <a class="pagination-item newer" href="{{ site.url }}page{{paginator.previous_page}}">Newer</a>
        {% endif %}
      {% else %}
        <span class="pagination-item newer">Newer</span>
      {% endif %}
    </div>

**Comment by troyswanson** [comment]
What do you want it to look like?

PS: This kind of issue should be opened in the [jekyll-help](https://github.com/jekyll/jekyll-help) repo (for future reference).

**Comment by sr-murthy** [comment]
Originally they were not stacked on top of each other like that, they were next to each other, nothing has changed in the code, so I'm not sure why this is happening.

**Comment by troyswanson** [comment]
Could be a change in how your browser is rendering the page. I'm not sure that this is a Jekyll problem, though. Feel free to ask for help in the jekyll-help repo with some more info and we'll be glad to give you a hand.

**Comment by parkr** [comment]
You should have a `/` after `site.url`, I think, or use `{{ paginator.next_page_path | prepend: site.url }}`.

**Comment by sr-murthy** [comment]
OK thanks, will continue this on Jekyll help if necessary.
