### ISSUE TITLE
Issue with date_to_rfc822 filter

### ISSUE THREAD

**Issue by ryanburnette** [jekyll/jekyll#3298]
I'm using Jekyll 2.5.1 and I'm using Collections pretty heavily. In each item in a particular collection I have a `date` field in my YAML front-matter. In one of my templates I filter that date using the `date_to_rfc822` Liquid filter.

The YAML front-matter item looks like this
```yaml
date: 2014-12-07
```

The template item looks like this
```html
{{ item.date | date_to_rfc822 }}
```

And this is the error I get.

```
Invalid Date: '2014-12-07' is not a valid datetime.
```

Looking at [the source of this filter][1] it looks like it's falling through the case statement.

Note that if I set the date like this it works fine.

```yaml
date: "2014-12-07"
```

[1]: https://github.com/jekyll/jekyll/blob/a098dc80cdd18e58479f005facbb985244f0c3a2/lib/jekyll/filters.rb#L301-L313

**Comment by parkr** [comment]
What is the type of the first option?

**Comment by ryanburnette** [comment]
I don't know. I was about to test that and I just had to jump on the phone for a bit. Great question. It should be a String I thought.

**Comment by parkr** [comment]
This is probably a bug:

```text
>> yaml = "date: \"2014-12-07\"\ndate_other: 2014-12-07"
=> "date: \"2014-12-07\"\ndate_other: 2014-12-07"
>> SafeYAML.load(yaml)
=> {"date"=>"2014-12-07", "date_other"=>#<Date: 2014-12-07 ((2456999j,0s,0n),+0s,2299161j)>}
>> SafeYAML.load(yaml).map(&:inspect)
=> ["[\"date\", \"2014-12-07\"]", "[\"date_other\", #<Date: 2014-12-07 ((2456999j,0s,0n),+0s,2299161j)>]"]
```
