### ISSUE TITLE
Default new post layout prints user name wrongly

### ISSUE THREAD

**Issue by uliwitness** [jekyll/jekyll#3300]
When creating a new site using `jekyll new foo.com`, the layout for posts in `_layouts/post.html` has the following line:

    <p class="post-meta">{{ page.date | date: "%b %-d, %Y" }}{% if page.author %} • {{ page.author }}{% endif %}{% if page.meta %} • {{ page.meta }}{% endif %}</p>

This results in post pages showing a meta-byline of something like `{ display_name: george, e-mail: foo@example.com, url: foo.com }`. Shouldn't this show the user name and add links around them instead? My quick fix for now is just writing `page.author.display_name` here instead:

    <p class="post-meta">{{ page.date | date: "%b %-d, %Y" }}{% if page.author %} • {{ page.author.display_name }}{% endif %}{% if page.meta %} • {{ page.meta }}{% endif %}</p>

But obviously in the release version you may want to also generate a link around the author's name based on page.author.url.

**Comment by kleinfreund** [comment]
I think this is intended behavior. The `jekyll new` theme is a simple and blank slate to start with. It's not meant to be a _fully featured_ theme (whatever that is). I serves the purpose of simply working and not doing much. Especially not doing too much.

Sure, we could add links there, but the user can do that on his own, right? That is, if they need them.

**Comment by uliwitness** [comment]
It is intended behaviour to log "{ display_name: george, url: , email: email@example.com }" instead of just "george"?!

**Comment by parkr** [comment]
The `jekyll new` theme and the `jekyll import` commands have not been developed side-by-side, so any problems that may exist in their cross-compatability are entirely coincidental. The `jekyll new` theme is meant to work with the `_config.yml` that is generated in the new site, not with any imported code.

**Comment by pathawks** [comment]
Not a `_config.yml` issue.

In this case, `{{ page.author }}` is a hash, while the default template expects it to be a string. The post probably has something like the following in it's front matter:

```yaml
author:
    display_name: george
    e-mail: foo@example.com
    url: foo.com
```

This *does* seem like a genuine bug that needs to be addressed, either by explicitly defining how `jekyll import` should represent imported data in YAML, or by making the default Jekyll template a bit more liberal in what it accepts at the expense of making it a bit less approachable for a new user.

**Comment by parkr** [comment]
> either by explicitly defining how jekyll import should represent imported data in YAML, or by making the default Jekyll template a bit more liberal in what it accepts at the expense of making it a bit less approachable for a new user.

I'd go with the former.
