### ISSUE TITLE
Proposal: Article Series

### ISSUE THREAD

**Issue by Karmac** [jekyll/jekyll#3302]
I think it would be nice if not implemented yet (although I searched I dind't find anything related to this) to have an option (perhaps as an external plugin) which allowed to link content together easily, like in a series of articles that are to long to post just in one page.

I currently managed to do this using some Liquid code, but it's rather a hack than a sustainable solution because it really slows down the compilation of all my page (which, in fact, gets even slower as I add content to it).

I'd really implement this myself, but my knowledge doesn't go further from PHP :stuck_out_tongue_winking_eye: Hope it's a good feature to include in next versions, I'd be really glad to see it working.

Thank you very much for this awesome tool that is Jekyll and excuse the grammar errors I could have done :sweat_smile:

**Comment by troyswanson** [comment]
We do something similar to this on jekyllrb.com using data files to create the various sections and sort the documents. Maybe check that out to find some inspiration! :8ball:

**Comment by sondr3** [comment]
Been thinking about something like this myself, I'll have to check out how you guys do it on jekyllrb.com.
