### ISSUE TITLE
Research HTML + Jekyll Sublime Text formatter

### ISSUE THREAD

**Issue by ldexterldesign** [jekyll/jekyll#3303]
Hey,

I'm currently using https://github.com/victorporof/Sublime-HTMLPrettify

Unfortunately it's making a hash of my HTML now I've introduced Liquid syntax

Does anyone have any hints/tips on formatting now?

Yours hopefully,

**Comment by parkr** [comment]
I used https://github.com/schinckel/jekyll-tmbundle for a while. I think they're compatible.

**Comment by ldexterldesign** [comment]
Hey @parkr,

Could I ask what you use now?

Kind thanks,

**Comment by parkr** [comment]
I use vim now -- parkr-vim-jekyll.

**Comment by ryderr** [comment]
id like HTMLPrettify for liquid too!

**Comment by envygeeks** [comment]
@ryderr I think that would be a great plugin, not necessarily something for Core Jekyll!
