### ISSUE TITLE
Front-matter inheritance

### ISSUE THREAD

**Issue by bbBobbyEarl** [jekyll/jekyll#3307]
Perhaps I've misunderstood the way in which front-matter variables are inherited, but assume the following scenario:

In layout A.html, I'm setting variable showComments: true.  Also in layout A.html, in the content I check if page.showComments is true, and if so, show a comments section.

In page B.html, which is using layout A.html, I'm NOT setting showComments in the front-matter.  When fully rendered, I do see comments section, as I would expect.

In page C.html, which is also using layout A.html, I DO set showComments, but I set it to false.  When fully rendered; however, I still see the comments section, which is not what I would expect.

Have I misunderstood how the front-matter variables are overridden?

**Comment by troyswanson** [comment]
The layout furthest down in the stack will overwrite previously set variables. So in this case, C.html is setting showComments to false, but A.html is overwriting that variable to true. In your example, the only way around this is to remove the declaration of showComments from A.html, and add set showComments to true in B.html.

**Comment by parkr** [comment]
@troyswanson is correct. Check out `Renderer#place_in_layouts` if you're curious
about how the layouting system works.
