### ISSUE TITLE
Nicer baseurl use when deploying on GitHub - add to docs

### ISSUE THREAD

**Issue by BLooperZ** [jekyll/jekyll#3308]
Instead of configuring in _config.yml the baseurl
You can use the HTML base element
Supported in every browser - even ie6 when you add self closing like XHTML
Use it like this:
```
<base href="{{ site.github.url }}/"/>
```
_*Note the trailing slash in the value_
It will interpreted  correctly in both user and project sites, also when testing locally it will interpreted as "/" which fits for it
For site pages use only
```
<a href="{{ page.url | remove_first: '/' }}">...
```
(Leading slashes means absolute path and not affected by base)

Most of project with costum domain mostly will be on the root anyway, so it's almost all in one solution, consider changing the docs

**Comment by kleinfreund** [comment]
Not on this. Read http://stackoverflow.com/questions/1889076/is-it-recommended-to-use-the-base-html-tag for example. 

Baseurl solves the problem of sites hosted in /subdirectory of a repo. The base tag introduces other disadvantages and may lead to unwanted behavior.

**Comment by BLooperZ** [comment]
i see that the base element may cause problems if not used right,
e.g. linking to assets directory (and then lose the ability for having links)
although, this is the right use of the base tag,
and everything would work fine,

BTW, on in-page link just use
```
<a href="{{ page.url | remove_first: '/' }}#whatever">..</a>
```
which makes perfect sense (well, you __are__ linking to somewhere in this page)
and it much easier with links for other pages in your site,
external and absolute links works just fine,
I have read that page and haven't found any reason why not use it in this case:
basing the links at your __site root directory__ instead of adding it to every links
