### ISSUE TITLE
Installing jekyll in current directory fails

### ISSUE THREAD

**Issue by lackita** [jekyll/jekyll#3309]
The guide says that I can install jekyll in the current directory with "jekyll new .", but when I run it I get a conflict saying that directory already exists.

**Comment by parkr** [comment]
That's because your current directory isn't empty. Run `jekyll new . --force` to force generation. Just be very sure you're not going to lose data.

**Comment by ApolonHellas** [comment]
i have problem install jekyll 2 is said  after sudo gem install jekyll --no-rdoc --no-ri
Successfully installed jekyll-2.5.3
1 gem installed
