### ISSUE TITLE
undefined method `regenerate?'

### ISSUE THREAD

**Issue by crearc** [jekyll/jekyll#3311]
@envygeeks @alfredxing - Thanks for the help and getting incremental build (https://github.com/jekyll/jekyll/pull/3116)  in!

I've been testing out incremental regeneration on latest. Couple of liquid 3.0 fixes, no problems with that. But I did run into an issue when trying to serve it up, any ideas? Here's the stack trace:

```
Configuration file: /home/eric/workspace/website/_config.yml
            Source: src
       Destination: /home/eric/workspace/website/_site
 Incremental build: enabled
      Generating... 
/home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:322:in `block in write': undefined method `regenerate?' for #<Sprockets::StaticAsset:0x007f662353c5d8> (NoMethodError)
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:481:in `block (2 levels) in each_site_file'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:480:in `each'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:480:in `block in each_site_file'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:479:in `each'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:479:in `each_site_file'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:321:in `write'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-assets-0.9.2/lib/jekyll/assets_plugin/patches/site_patch.rb:61:in `__wrap_write'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:57:in `process'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:58:in `build'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/eric/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:17:in `<top (required)>'
	from /home/eric/.rbenv/versions/2.0.0-p481/bin/jekyll:23:in `load'
	from /home/eric/.rbenv/versions/2.0.0-p481/bin/jekyll:23:in `<main>'
```

**Comment by parkr** [comment]
This is a problem with a plugin. Eventually it will need to respond to regenerate? .

I still think it shouldnt but that's the structure we have atm.

**Comment by envygeeks** [comment]
Why don't we just see if it responds to our expectation and then if it doesn't assume it needs to be written, this will impact their performance but Sprockets tracks it's own need to regenerate doesn't it?

**Comment by parkr** [comment]
Why not just pass the object to the site metadata instance and have that determine whether it needs to be regenerated? It's basically doing that anyway, so it'd clean up the code base a bit that way. It would also solve this problem:

```
def regenerate?(document)
  case document
  when Post, Page, Document
    # handle our internal case
  else
    true
  end
end
```

**Comment by alfredxing** [comment]
There were some specific things in Document and Convertible that we wanted to check, so we put a `regenerate?` method in each of those to take into account those things. We could put everything into Metadata but it would get a bit messier with the methods checking whether an object is a Post or Page or Document.

I agree with @envygeeks to just check whether an object responds to `regenerate?`. Where should this be done though, in Site or in Metadata?

**Comment by envygeeks** [comment]
Please both sides of the party and have Metadata handle the `regenerate?` method and delegate to `Document`, `Page` and `Post` or (any other class) that responds to `regenerate?` then have everything tap into `Metadata#regenerate?` instead of `Post#regenerate?` that way there is a consistent API even if said class does not support it.

**Comment by parkr** [comment]
Having lots of ways of doing something just makes it more confusing to potential readers of this code. I'd like to have regeneration knowledge in only one place. :)

**Comment by envygeeks** [comment]
At that point then Metadata's class name needs to change, if it's brokering transactions it cannot and should not be called Metadata because it's doing more than storing Meta, it's brokering builds.  If we don't change the name then we confuse experienced programmers who go searching for classes logically based on name that is, unless we use a service class to hold the contract that has `regenerate?` and meta remain simply a data class.  I'd have to go back and re-read the source again because I could be assuming wrongly about the way it's designed.

**Comment by parkr** [comment]
Hm ok. Maybe `Regenerator` or something that sounds like it'd have `regenerate?`?

**Comment by envygeeks** [comment]
`Regenerator` sounds like a good name to me!

**Comment by alfredxing** [comment]
I can probably get to this sometime tomorrow. Thanks for the suggestions!

**Comment by crearc** [comment]
Wonderful. Thanks for all the help and such a quick turnaround! I'll give
it a go this week!
