### ISSUE TITLE
Possible to combine site.posts and site.pages into one array?

### ISSUE THREAD

**Issue by yoshyosh** [jekyll/jekyll#3315]
I have some special pages that are like posts that I will display in an rss feed. Is there a good way to combine site.posts and site.pages (filtered version) so I can sort by date?

**Comment by parkr** [comment]
No, this isn't possible AFAICT. We aren't interested in doing this as posts and pages shouldn't mix in Liquid (different fields, semantic value, etc). Two `for` loops will work.

**Comment by yoshyosh** [comment]
That makes sense, thanks Parker! Collections work really well for this. Just running into the permalink bug :(.

Can you provide some pseudo code for how you would sort these 2 different arrays reverse chronologically to make 1 cohesive reverse chronological list?

**Comment by parkr** [comment]
Posts are chronological, whereas pages are not – the latter are stand-alone objects. In terms of combining collections into one cohesive list, it's via `site.documents`.
