### ISSUE TITLE
How do I store links as variables in _data?

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll#3317]
I have a lot of links in my site, and because the links may change, I want to indirectly reference them using variables. This way, if I change, say, my Overview page to Introduction, all my links to Overview won't break. I can change the value for my overview variable and everything will update.

Here's my approach:

In my _data folder, I have a file called links.yml. The file contains this:

```
overview: "<a href={{ '/overview' | prepend: site.baseurl }}>Overview</a>"
```

To link to overview in a page, I write `{{ site.data.links.overview}}`. However, the code inside the `{{ }}` tags doesn't get rendered. The HTML produced shows the following:

```
<a href={{ '/overview' | prepend: site.baseurl }}>Overview</a>
```

How can I get the `{{ }}` to convert to the real code? 

I also tried another technique:

```
{% assign overview = "<a href='{{ '/overview' | prepend: site.baseurl }}'>Overview</a>" %}
```

Same result.  Can I not reference one variable inside another like this?

**Comment by parkr** [comment]
Data files can only contain static data – they cannot contain Liquid themselves. Sorry about this!

**Comment by tomjohnson1492** [comment]
Thanks. This is good to know. But even in an HTML file in an _include directory, using `assign`, I got the same result. What approach would I use so that I can reference a link just by writing {{ overview }} to point to overview.html?

**Comment by parkr** [comment]
The only problem is that the Liquid is in there – get rid of the Liquid in your data file and you're golden.
