### ISSUE TITLE
Liquid markup {{ xxx }} are not rendered inside {{ post.content }}

### ISSUE THREAD

**Issue by pyrog** [jekyll/jekyll#3318]
```python
    {% for post in site.categories.[page.category] %}
      {% if {{post.lang}} == {{page.lang}} %}{% unless post.hidden %}
        {{ post.content }}
      {% endunless %}{% endif %}
    {% endfor %}
```

If the post contain for example this:
```markdown
# This is an example
![an image]({{site.baseurl}}/images/an_image.png}}
```

should be rendered as:
```html
<h1>This is an example</h1>
<img alt="an image" href="/images/an_image.png" />
```

but is rendered as:
```html
<h1>This is an example</h1>
<img alt="an image" href="{{site.baseurl}}/images/an_image.png" />
```

The issue could be solved in using replace for each variable: see hotosm/learnosm#90

**Comment by parkr** [comment]
Use `post.output` instead wherever possible. Additionally, you can only include posts in pages, not in other posts.

**Comment by pyrog** [comment]
Thanks Parker :smile: 

The issue is solved when I include posts in **pages** (the site is not a blog but a book. All chapters are subdirectories under **_posts** folder)

**Note:** ```post.output``` doesn't work, so I still use ```post.content```  :wink:
