### ISSUE TITLE
Fix YAML Front Matter Date

### ISSUE THREAD

**Issue by ldexterldesign** [jekyll/jekyll#3330]
Hey,

Can anyone tell me why I get this console error:
![screen shot 2015-01-20 at 16 07 31](https://cloud.githubusercontent.com/assets/1715809/5820678/81e943c0-a0be-11e4-8fe3-de6a3161bb85.png)

It simply uses the default Date value https://github.com/jekyll/jekyll/blob/master/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb#L4

If I change the Date value to:
```
date: 2015-01-20
```
... then it compiled just fine??

Yours hopefully,

**Comment by troyswanson** [comment]
I'd love to know more about what you're trying to accomplish with that date value in your front-matter. The reason it's not compiling is pretty simple, and the error message even lets you know: that date is invalid in the context of YAML. Jekyll will not replace the string that you put there with the current date.

I'm still curious as to why you'd want to do this in the first place. Maybe we can figure out a better solution for you, because this implementation is very odd.

**Comment by parkr** [comment]
> It simply uses the default Date value https://github.com/jekyll/jekyll/blob/master/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb#L4

@ldexterldesign That isn't a default date at all. That post is the ERB template we use to generate the new post when you run `jekyll new my-site`. We [read in the file and run it through ERB](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/new.rb#L51) which creates something like `date: 2015-01-20 12:09:42`, which *is* a valid date. You cannot use ERB in your templates with Jekyll out of the box.

**Comment by ldexterldesign** [comment]
@parkr ahh, that did cross my mind last night after I posted this - cheers for the clarification

Out of interest is there a better way of generating a post timestamp with Jekyll without hardcoding one?

Thanks,

**Comment by alfredxing** [comment]
@ldexterldesign If you don't include `date` in the front-matter Jekyll falls back to the file name, so you can always generate that. I think [jekyll-compose](https://github.com/jekyll/jekyll-compose) does this for you.

**Comment by ldexterldesign** [comment]
@alfredxing thanks, I now realise that unless you're using ```date``` as a variable (or need the minute/second timestamp), then it's not crucial this is included in ```*.post``` front matter

Cheers,

**Comment by stevemoser** [comment]
FYI for those coming from Google for:
`"welcome to jekyll" does not have a valid date in the YAML front matter.`
Then you need to exclude vendor in _config.yml as #2938 suggests.

**Comment by JazzMaster** [comment]
is there a way to 'not assume' a date format and set one up? config file maybe, like with pico/phile (in php format)?

**Comment by envygeeks** [comment]
That's an upstream bug @JazzMaster and needs to be done by Psych or Ruby.  Ruby expects logical time formats and does not support parsing like PHP, because it's Ruby, not PHP.  Sorry.

**Comment by envygeeks** [comment]
Well, I guess we could use `Time.strptime` but that is only if *we* are the ones parsing the time, technically it's Psych that will parse your time for us and ship us the Object.

**Comment by calebthompson** [comment]
@stevemoser You're the real hero.
