### ISSUE TITLE
OFFTOPIC: eLance job for Jekyll website conversion

### ISSUE THREAD

**Issue by fulldecent** [jekyll/jekyll#3337]
Hello I am hiring a freelancer to assist in converting a website of ~20 pages to Jekyll/Markdown by using Jekyll's best practices. I am inviting you to work on this job since you are a Jekyll committer and should know best practices. If you are available and this opportunity is interesting to you, please see https://www.elance.com/j/convert-website-jekyll-markdown/67703690/ and make some reference to this post in your proposal, since that clearly means you are qualified.

Please mark this issue as invalid. I apologize for abusing GitHub's issue system to PM you. I will not bother you again in this way.

@mojombo
@mattr-
@maul-esel
@penibelst
@alfredxing
@qrush
@benbalter
@cobyism
@XhmikosR
@zachgersh
@jglovier
@krisb
@tombell
@kleinfreund
@gjtorikian
@afeld
@albertogg
@stephenmcd
@JackDanger
@scribu
@jpiasetz
@mreid
@pathawks
@budparr
@tmm1
@robin850
@envygeeks
@nitoyon
@pborreli
@troyswanson
@ivantsepp
@x3ro
@rusikf
@sferik
@konklone
@yizeng
@mccxj
@jaybe-jekyll
@laumann
@richbecks
@MattHall
@tkrotoff

**Comment by troyswanson** [comment]
Interesting tactic.

**Comment by envygeeks** [comment]
Very interesting indeed, too bad I don't use eLance because something like this could be done in less than a couple of days with little effort and I'm pretty bored right now.

**Comment by fulldecent** [comment]
@envygeeks Thank you. Would be happy to work with you privately and by PayPal. Please send your (brief!) project plan and price/terms to will@medtrainingsolutions.com

**Comment by fulldecent** [comment]
And holy shit with this issue label

**Comment by parkr** [comment]
Yeah, definitely not a good use of our issues. :no_good: 

Good luck to you.

**Comment by afeld** [comment]
Please mark OP as spam.

**Comment by gjtorikian** [comment]
Please don't ever do this again.

**Comment by jaybe-jekyll** [comment]
I have a vintage set of 1982 Encyclopedia Brittanica available. And boy will they go fast. First person to outbid @parkr wins. :black_joker:

**Comment by konklone** [comment]
Reported the OP for abuse.
