### ISSUE TITLE
Killing Detached Server?

### ISSUE THREAD

**Issue by plaindocs** [jekyll/jekyll#3339]
Guys,

I might be missing something really obvious, but if you detach, and don't note down the PID in the output
````
Server detached with pid '4311'. Run `kill -9 4311' to stop the server.
````
how do you find and kill the process?

**Comment by chrisfinazzo** [comment]
This is actually in the [Usage][] docs - you can do `ps aux | grep jekyll` to find a list of PID's. As you indicated, UNIX `kill` with the identifier should take care of things.

[Usage]: http://jekyllrb.com/docs/usage/

More info [here][].

[here]: http://unixhelp.ed.ac.uk/shell/jobz5.html

To be fair, I don't have many situations where I need to detach, so I'm not certain if you can get into situations where it is possible to "lose" a PID. I do have unlimited scrollback set to on and I suppose you could always look in `.bash_history` to find the command.

**Comment by plaindocs** [comment]
Hi

Thanks for that! Rechecking it actually *is* in the usage docs, but using code blocks to show things that are not explained in the text is pretty confusing. 

It could also be mentioned in the command output. 

That said, now I know you can't detach and watch at the same time makes it fairly useless. :-p

**Comment by envygeeks** [comment]
`pgrep` is the preferred way, the docs should be updated.

**Comment by chrisfinazzo** [comment]
I guess...

Although `pgrep` is limited in some cases, [as well][]. Like I said, I don't use this feature often, so either way you want to do it is fine by me.

[as well]: http://askubuntu.com/questions/157075/why-does-ps-aux-grep-x-give-better-results-than-pgrep-x

**Comment by envygeeks** [comment]
@chrisfinazzo The question you pointed to is an invalid argument to not use `pgrep` because if you would have read further down or did `man pgrep` you would have noticed `-f` which leads to doing `pgrep -f php5` | `pgrep -f jekyll`.  `-f` on `pgrep` exists to solve the exact problem you claim exists with `pgrep`

**Comment by chrisfinazzo** [comment]
Oops, `man prep` _does_ reference `-f` in the context of `pidfile`, which leads me to [here][] and explains its usage.

Carry on 👍

[here]: http://www.unix.com/man-page/freebsd/3/PIDFILE/
