### ISSUE TITLE
Broken links in generated html in case of cyrillic soft sign used in link text

### ISSUE THREAD

**Issue by ionicer** [jekyll/jekyll#3340]
Problem: After html generation, I get 404 error by following link which contain "ь" (name: CYRILLIC SMALL LETTER SOFT SIGN | Unicode: 044C | UTF-8: D1 8C) in link text.

Page with broken link http://ionicer.github.io/blog/2014/10/26/takoy-den-31/
Scroll down to the footer and click "временный обитатель". Here goes screenshot for your convenience so you know where to scroll and click: http://screencast.com/t/cFLa9xS66p

Click sends us to http://ionicer.github.io/blog/categories/vriemiennyi-obitatiel which gives 404.

What was expected:
And actual page located at http://ionicer.github.io/blog/categories/vriemiennyi-obitatiel'/

My system: jekyll (2.5.3), liquid (2.6.1), bundler (1.7.3)

I am just a blogger not the Ruby or Yaml programmer so, please, pardon me for any inconvenience :)

**Comment by parkr** [comment]
![screen shot 2015-01-22 at 11 28 26 pm](https://cloud.githubusercontent.com/assets/237985/5871205/6d5ed394-a28e-11e4-8310-e782466145cb.png)

It looks like the apostrophe in the URL is causing the browser to freak out. This is a template issue – it's not expecting the output to contain single quotes, so it doesn't check for it:

![screen shot 2015-01-22 at 11 29 29 pm](https://cloud.githubusercontent.com/assets/237985/5871214/97702458-a28e-11e4-84f8-24720b96b187.png)

/cc @imathis

**Comment by kleinfreund** [comment]
Also after the href attribute there are 3 single quotes. I guess the second one should not be there?

**Comment by ionicer** [comment]
Oh, thanks for explanation.
At the same time seems strange for me to bring [ ' ](single quote) into the URL.
May I suggest the alternation of transliteration rules?
CYRILLIC SMALL LETTER SOFT SIGN simply transliterate to nothing in case of URL.
Is it real or this change will be a casualty of not implicated things in?

**Comment by pathawks** [comment]
It's not Jekyll outputting these broken links, it's **[recurser/jekyll-plugins]**, which you have installed in your `_plugins`

This seems to be fixed in the current version.

**Comment by pathawks** [comment]
in [`_includes/post/categories.html`](https://github.com/ionicer/ionicer.github.io/blob/source/source/_includes/post/categories.html#L6) you have the line

```liquid
{{ post.categories | category_links }}
```

Which calls [`plugins/category_generator.rb`](https://github.com/ionicer/ionicer.github.io/blob/source/plugins/category_generator.rb#L155-L157) which [outputs](https://github.com/ionicer/ionicer.github.io/blob/source/plugins/category_generator.rb#L167)

```ruby
    def category_link(category)
      dir = @context.registers[:site].config['category_dir']
      "<a class='category' href='/#{dir}/#{category.to_url}/'>#{category}</a>"
    end
```

The [updated version](https://github.com/recurser/jekyll-plugins/blob/master/generate_categories.rb) of this plugin *seems* to have a very different way of generating the category permalink, which seems to avoid this issue.

**Comment by ionicer** [comment]
Just updated template. Problem persists
