### ISSUE TITLE
Error installing Jekyll Gem

### ISSUE THREAD

**Issue by geoffdavis92** [jekyll/jekyll#3341]
I tried installing the Jekyll gem via CLI, but when installation is complete, the `jekyll` command is unavailable. I get the `-bash: jekyll: command not found` error when I try to use it; I looked back at the install log and saw the following error after the build notification...

    Building native extensions.  This could take a while...
    ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

I'm fairly new to the command line, and ruby gems in general, so I do not know exactly what to do to remedy this. I already tried to reinstall it but got the same result. 

It seems like there may be an issue with the build.

My information:

2011 Macbook Pro using OS X 10.9.4 "Mavericks"
Ruby v.2.0.0

**Comment by parkr** [comment]
The error means one of the C extensions didn't install properly. Re-run `gem install jekyll` and see which one failed.

**Comment by envygeeks** [comment]
Can you post the entirety of the log and bundle output @geoffdavis92 if you can give us the entire log and not just the last few lines we can tell you what you are missing.

**Comment by nikhiljindal** [comment]
I am getting a similar error.
I am on linux though. Here is my full log:

```
$sudo gem install jekyll
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
creating Makefile

make
compiling yajl.c
compiling yajl_encode.c
compiling yajl_parser.c
compiling yajl_buf.c
compiling yajl_ext.c
yajl_ext.c: In function ‘rb_yajl_parser_parse’:
yajl_ext.c:471:17: warning: variable ‘stat’ set but not used [-Wunused-but-set-variable]
     yajl_status stat;
                 ^
compiling yajl_lex.c
compiling yajl_version.c
compiling yajl_gen.c
compiling yajl_alloc.c
linking shared-object yajl/yajl.so

make install
/usr/bin/install -c -m 0755 yajl.so /var/lib/gems/1.9.1/gems/yajl-ruby-1.2.1/lib/yajl
installing default yajl libraries


Gem files will remain installed in /var/lib/gems/1.9.1/gems/yajl-ruby-1.2.1 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/yajl-ruby-1.2.1/ext/yajl/gem_make.out
```


Note that earlier I was getting the "mkmf.rb can't find header file" error, but installing ruby-dev fixed it and now I am getting this.
Any idea on how can I fix this?

**Comment by chaitanyav** [comment]
@nikhiljindal Please try installing yajl lib (https://lloyd.github.io/yajl/) and retry the installation. The installation is failing on yajl-ruby gem.

**Comment by envygeeks** [comment]
The preferable solution is not to send people to compile and manage their own software lest they run into issues later (security wise) it is: `yum install yajl-devel` or `sudo apt-get install yajl-dev`
