### ISSUE TITLE
Jekyll not updating in localhost

### ISSUE THREAD

**Issue by fitzski** [jekyll/jekyll#3343]
I have been using jekyll for over a month however today when I run 'jekyll serve --watch' I get this;

```text
Jamies-MacBook-Pro:casa jamiefitzhenry$ jekyll serve
Configuration file: /Users/jamiefitzhenry/desktop/casa/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
            Source: /Users/jamiefitzhenry/desktop/casa
       Destination: /Users/jamiefitzhenry/desktop/casa/_site
      Generating... 
                    done.
 Auto-regeneration: enabled for '/Users/jamiefitzhenry/desktop/casa'
Configuration file: /Users/jamiefitzhenry/desktop/casa/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
    Server address: http://127.0.0.1:3000/
  Server running... press ctrl-c to stop.
```
The basic html loads however there is no sass or anything. When I make changes to the html nothing updates. 

I'm running jekyll 2.5.3 and ruby 2.0.0p481. 

My config.yml looks like this:

```text
# Build settings

markdown: kramdown
permalink: pretty

port: 3000

auto: true

sass:
  sass_dir: assets/css
  style: :nested
```
I tested another jekyll theme and it seemed to load straight away, however once I went to make changes nothing was updating. 

Any help would be appreciated, if I need to supply more information please let me know. 

Thanks

**Comment by parkr** [comment]
Re-run Jekyll with `LISTEN_GEM_DEBUGGING=1` and paste the output after editing a file.

**Comment by fitzski** [comment]
thanks, I re-ran Jekyll with LISTEN_GEM_DEBUGGING=1 and got this: 

Configuration file: /Users/jamiefitzhenry/desktop/casa/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
            Source: /Users/jamiefitzhenry/desktop/casa
       Destination: /Users/jamiefitzhenry/desktop/casa/_site
      Generating... 
                    done.
I, [2015-01-23T22:22:43.857108 #10814]  INFO -- : Celluloid loglevel set to: 1
I, [2015-01-23T22:22:43.857170 #10814]  INFO -- : Listen version: 2.7.12
I, [2015-01-23T22:22:44.030665 #10814]  INFO -- : Record.build(): 0.15069317817687988 seconds
 Auto-regeneration: enabled for '/Users/jamiefitzhenry/desktop/casa'
Configuration file: /Users/jamiefitzhenry/desktop/casa/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
    Server address: http://127.0.0.1:3000/

Sorry I'm fairly new to the terminal, when you say paste the output specifically what do you mean?

**Comment by fitzski** [comment]
When I input 

    LISTEN_GEM_DEBUGGING=1 jekyll serve --watch --force_polling

things start to update, however it now takes around 6 seconds rather than instantly before. I also still have this 

Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.

**Comment by parkr** [comment]
> Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.

Yep, remove `auto: true` from your `_config.yml` file.

> things start to update, however it now takes around 6 seconds rather than instantly before. I also still have this

Polling is a means of automatically checking every X seconds. Are you using the latest jekyll-watch? Have you done `gem cleanup` lately? Try `gem uninstall jekyll && gem cleanup && gem install jekyll`.

**Comment by fitzski** [comment]
Cool I've removed   auto:true from the _config.yml file which has got rid of 

    Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-  ]watch/-w command-line option instead.

I've done gem uninstall jekyll && gem cleanup && gem install jekyll, however it still doesn't seem to be updating anything. I just get the html layout and no updates. 

I'm not sure about the latest jekyll-watch? I'm using jekyll 2.5.3.

**Comment by parkr** [comment]
If you type `gem list | grep jekyll-watch`, what do you see?

**Comment by parkr** [comment]
Did you change a file? There is no indication that you did.

**Comment by fitzski** [comment]
I tried both   gem update jekyll-watch & gem update jekyll and typed in gem list | grep jekyll-watch which pulled up

   jekyll-watch (1.2.1, 1.1.2)

The config file is now 
   # Build settings

markdown: kramdown
permalink: pretty

port: 3000


sass:
  sass_dir: assets/css
  style: :nested

**Comment by parkr** [comment]
@fitzski I don't know what to tell you. Without more debugging info from Listen, I am blind. Can you please try: https://github.com/guard/listen/wiki/Troubleshooting

Beyond that, there's nothing we can do :(
