### ISSUE TITLE
Changes to files starting with _site are not being picked up

### ISSUE THREAD

**Issue by kleinfreund** [jekyll/jekyll#3348]
I noticed that changes to files starting with `_site` are not being picked up by Jekyll when using `jekyll s`. Namely, I have the following file names. When I save one of them, there is no reaction in the commond line window.

- `_sass/_site-head.scss`
- `_sass/_site-logo.scss`
- `_sass/_site-nav.scss`
- `_includes/_site-head.html`

All my other Sass are leading to a regeneration upon saving them.

_P.S.: Ah, I forgot. Is this a [jekyll-watch](https://github.com/jekyll/jekyll-watch) issue?_

**Comment by parkr** [comment]
> P.S.: Ah, I forgot. Is this a jekyll-watch issue?

Yes!
