### ISSUE TITLE
Some input on 3.0.0

### ISSUE THREAD

**Issue by Wolfr** [jekyll/jekyll#3350]
Hi guys,

I used to use Jekyll a lot for application prototypes a lot.

In 2013 I made some videos on how to use Jekyll (one got about 5k views on Youtube so at least some people were interested, it's <a href="https://www.youtube.com/watch?v=O7NBEFmA7yA">here</a>).

At some point the generation of my app prototype became too slow (20 seconds to build HTML, ouch) so we switched to Wintersmith (another SSG). When the full prototype was converted to Wintersmith (which uses Jade internally for templating) we found that is was slow again (20 seconds).

So we built our own thing called Renderpipe ( https://github.com/rubenv/renderpipe/ ) we use in conjunction with a custom Grunt flow. All the grunt flow really does is render the static site and Sass. It also helps to parse some JSON templates (our not-so-handy replacement for site.data).

It's really fast (a few seconds for a prototype with hundreds of templates and loops), the problem was considered solved and we got back to work.

I still follow the changelog and Twitter and was excited to see 3.0.0 offers incremental regeneration. So I made my old prototype work with 3.0.0. I was happy to see that the build time for HTML changed from 20 seconds to 8 seconds so your work in performance definitely paid off.

I saw @parkr posting in the Liquid repo on the performance of for loops in Liquid. I think this in itself might be the main cause of slowness in my prototype.

Anyway, happy to see that Jekyll is alive and kicking.

**Comment by parkr** [comment]
A belated Thanks, @Wolfr :)
