### ISSUE TITLE
Bug sorting a collection using nested property?

### ISSUE THREAD

**Issue by alessandrococco** [jekyll/jekyll#3351]
Hi all, 
I found a strange behavior sorting posts using a custom nested property as sorting key.
 
My Front Matter is the following:

<pre>
---
layout: post
title: "...."
category: "recensioni"
book:
    title:    "AAA"
    author:   "BBB"
---
</pre>

With 
<pre>{% assign filtered_posts = site.posts | where: 'category', 'recensioni' %}</pre>
I retrieved all posts in the "recensioni" (reviews) category.

Now I want to sort my reviews by book's author name so I write this:

<pre>
{% assign sorted_posts = filtered_posts | sort: 'book.author' %}
{% for post in sorted_posts %} 
     {{ post.book.title }} - {{ post.book.author }} 
{% endfor %}
</pre>

Jekyll builds without errors but the sort does not work (default order of the posts still remains). Using sort with **'title'** instead of  **'book.author'** makes sort working right.

Is this a bug or am I missing something? Thank you :)

**Comment by parkr** [comment]
We don't support `sort: 'book.author'`. You'd have to change that to, say, `book_author`. Ruby doesn't handle sorting by sub-properties.

**Comment by alessandrococco** [comment]
Ah ok, I didn't know. Thanks!

**Comment by Fresheyeball** [comment]
:-1:  lame. Can we write a plugin to provide this kind of functionality? Ruby doesn't support it is not a reason that jekyll should have this limitation. If you point me in the right direction I could send a PR.

**Comment by envygeeks** [comment]
Nobody is stopping you from building a plugin to do it.  http://jekyllrb.com/docs/plugins/  I don't think this behavior belongs in Jekyll though, this is more something that belongs in liquid because that is their filter, I would ask @fw42 if he's fine with a PR going there because that is where the sort filter is.

**Comment by Fresheyeball** [comment]
Ok, well I am new to the Rubies and the world of Jekyll. Let me know where this needs to be written and I will do my best!

**Comment by Fresheyeball** [comment]
https://github.com/Shopify/liquid/pull/604 should take care of this. Thanks @untra
