### ISSUE TITLE
<p> tags being wrapped around <picture>

### ISSUE THREAD

**Issue by davetgreen** [jekyll/jekyll#3352]
Hello!,

I'm building a site at the moment where I'm using the picturefill plugin for responsive images, and I've noticed that Jekyll isn't wrapping the `<picture>` element in `<p>` tags.

Is there a workaround for this?

Thanks,
Dave

**Comment by kleinfreund** [comment]
Can you please format the tags as code with backticks (e.g. \`code\`)? They are not showing currently.

Also this is probably an issue of the Markdown in use. What Markdown parser are you using? The default for the current version is kramdown.

**Comment by nternetinspired** [comment]
My first thought is that this is the correct behaviour as, unlike `<img>`, `<picture>` is a block-level element.

**Comment by davetgreen** [comment]
@kleinfreund Sorry, forgot the backticks! I've switched back to kramdown as I was using redcarpet and that's resolved the issue. Thank you!

**Comment by kleinfreund** [comment]
> My first thought is that this is the correct behaviour as, unlike <img>, <picture> is a block-level element.

@nternetinspired I don’t think this is necessarily the case. Browser support is not so great, so there are no user agent styles present yet. This element ist still in experimental stage.

**Comment by nternetinspired** [comment]
@kleinfreund While it is true that there may not be widespread browser defaults `<picture>` in the draft html5 draft spec seems to be described as a content container, like `<video>` or `<figure>`.

@davetgreen As @kleinfreund correctly points out I wouldn't expect *any* MD parser to support this yet though, it isn't in Commonmark spec yet at least: http://spec.commonmark.org/0.17/#html-blocks. You can enforce consistency between browsers by to defining the element it in your css, e.g.;

    picture {display: block;}

**Comment by pathawks** [comment]
> Jekyll isn't wrapping the `<picture>` element in `<p>` tags.

Jekyll doesn't wrap anything in anything. This is an issue with your Markdown processor, rather than with Jekyll itself.

**Comment by nternetinspired** [comment]
Jekyll doesn't wrap anything in anything. This is an issue with your Markdown processor, rather than with Jekyll itself.
:+1:

**Comment by parkr** [comment]
Thanks guys!!

**Comment by davetgreen** [comment]
Thanks for the assistance folks.
