### ISSUE TITLE
timezonedb is outdated at github pages

### ISSUE THREAD

**Issue by fizzka** [jekyll/jekyll#3355]
When I set tz in _config.yaml (github pages)

```yaml
timezone: Europe/Moscow
```

I receive a dates with +0400 timezone:

```
{{ site.time | date_to_rfc822 }} => Mon, 26 Jan 2015 02:46:57 +0400
```

But right value for Europe/Moscow is +3 (http://en.wikipedia.org/wiki/Europe/Moscow)

**Comment by parkr** [comment]
We have no influence over Pages but thanks for the report! Please write support@github.com with a link to this issue :)

**Comment by fizzka** [comment]
cheers)
