### ISSUE TITLE
Should the default variables in the front matter for a "posts" type be automatically extended to the "drafts"?

### ISSUE THREAD

**Issue by sabhiram** [jekyll/jekyll#3356]
Just a question, I ran into this when adding some post specific styling into my front matter. I needed to copy paste in the posts "defaults" for the drafts as well. Not a big deal, but figured I would ask here.

**Comment by parkr** [comment]
Right now, posts and drafts are different, yes. Are you asking that drafts have `posts` type applied to them in the YAML front matter defaults as well? Good idea.

**Comment by sabhiram** [comment]
Right, that would make life easier when linking between drafts and posts (using {% post_url ... %}), as well as when adding default liquid variables to the config.

I am not a ruby expert, but dont mind investigating the code if you could point me in the right direction.

**Comment by parkr** [comment]
The way in which inheritance is done is hacky and gross. I don't like it much at all, but it's what we have.

Drafts should inherit everything from Posts in theory – they are Posts in every way except their publish date is "now".
