### ISSUE TITLE
Run Object#to_s on values from front-matter.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3358]
Today I discovered that Jekyll does not ensure that the data it is receiving is to the spec it wishes to receive.  For example if you set a title to "YYYY-MM-DD" it will result in Jekyll failing to build, because `YAML` converts that to a `DateTime` object, which results in the `String#gsub` failing.  If we expect a string for "title" we should convert it to a string to ensure it is a string before doing anything, so that a user does not have to quote or worry about simple things like that, they can just get work done.

**Comment by parkr** [comment]
I wouldn't run `#to_s` for every item in the front matter (hashes, arrays, numeric values should be left un-touched), but anytime we're doing `#gsub` we should make sure it's a string beforehand.

**Comment by envygeeks** [comment]
Definitely not every item, just items we expect to be strings. Such as title and others.

**Comment by parkr** [comment]
Out of what was this borne? It'd be nice to do this, but I don't think it's crucial for 3.0. Punting. :football:
