### ISSUE TITLE
Should Jekyll include a blog template?

### ISSUE THREAD

**Issue by nternetinspired** [jekyll/jekyll#3364]
It has always seemed a little strange to me that Jekyll ships with a page template, a post template (which are almost identical) but without a blog template. 

Given that Jekyll is widely considered as a great option for blogging maybe a blog template should be included? Personally I feel that there is a pretty big use case for this, and it is something that I always include in my own builds.

I'd be happy to code the layout if there was any interest.

**Comment by nternetinspired** [comment]
Related thought: Is there merit in maintaining both page and post templates? The current differences in output can be maintained with a single {% if %} statement making a single template perform for both pages and posts.

**Comment by nternetinspired** [comment]
>  The current differences in output can be maintained with a single {% if %} statement making a single template perform for both pages and posts.

Ah. I thought this would be possible with `{% if page.layout == 'post' %} … {% endif %}` but apparently the page layout variable isn't available directly, though I'm not certain why.

**Comment by paulrobertlloyd** [comment]
@nternetinspired That’s a bug, being tracked here: https://github.com/jekyll/jekyll/issues/1934 (annoying, isn’t it!)

**Comment by nternetinspired** [comment]
Nice spot @paulrobertlloyd, yes it is annoying. Getting the rendering template name and using it as a css hook is something I do a lot in Shopify themes, so just assumed it would work out-of-the-box here.
