### ISSUE TITLE
Accept multiple Sass load paths

### ISSUE THREAD

**Issue by wjdp** [jekyll/jekyll#3366]
Currently a `sass_dir` is configured like this. The directory is now the Sass load path.

```
sass:
    sass_dir: _sass
```

I propose allowing this:

```
sass:
    sass_dir:
        - _sass
        - bower_components
```

Both directories should now be on the load path allowing imports from either source.

**Comment by parkr** [comment]
Specify them under the `load_paths` key. [It's already implemented when not in safe mode](https://github.com/jekyll/jekyll-sass-converter/blob/master/lib/jekyll/converters/scss.rb#L74-L80).

**Comment by wjdp** [comment]
Thanks! For anyone stumbling on this later:

```
sass:
    load_paths:
        - _sass
        - bower_components
```

**Comment by i8ramin** [comment]
I ended up going with this, which seemed more appropriate given that we only need/want the foundation scss files.

```
sass:
  load_paths:
    - _sass
    - bower_components/foundation/scss
```
