### ISSUE TITLE
Feature request: multiple permalinks for page

### ISSUE THREAD

**Issue by kaatt** [jekyll/jekyll#3368]
I have a file `about.md` and I want to make it appear in multiple permalinks like
```
/about/
/about-me/
/about.htm
/about.html
```
(not actual use case, just an example)

I'm aware of `jekyll-redirect-from` and using it I can make the other 3 permalinks redirect to any 1 permalink. But I don't want to redirect, I just want to make the same content with the same front matter available at multiple permalinks.

Something like this in the front matter:
```
permalink:
- /about/
- /about-me/
- /about.htm
- /about.html
```
instead of `permalink: /about/`

I can set the canonical meta tag to /about/ so no SEO trouble.

**Comment by kleinfreund** [comment]
I'm not sure if that is easily achievable. However, let me ask – why do you want to do this?

**Comment by kaatt** [comment]
My use case is too complex to explain. Doesn't have to be in the core, a separate plugin maybe?

**Comment by pathawks** [comment]
> Doesn't have to be in the core, a separate plugin maybe?

Yes, you’ll have to do this in a plugin.

For the most part, Jekyll is (currently) pretty well set on the idea of **single file in** => **single file out**

**Comment by parkr** [comment]
Yeah, we like the simplicity of the 1-1 relationship we have going. This won't be possible for Jekyll core. Thanks for the suggestion though!

**Comment by gduverger** [comment]
FWIW, I used http://www.marran.com/tech/creating-redirects-with-jekyll to enable multiple permalinks.

**Comment by parkr** [comment]
jekyll-redirect-from is a plugin we also provide (supported by GitHub Pages, too), that allows for redirects.

**Comment by gduverger** [comment]
Ha, indeed. [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) works. Thanks for letting me know.

**Comment by justinperkins** [comment]
FWIW, this typically isn't desirable since it could result in negative SEO due to having multiple URLs with the same content. However, one valid use-case I ran into was a 404 page. On many web servers, they will automatically serve up /404.html but on S3, they automatically serve up /error.html. Yes, this can be configured on S3 to use /404.html, but convention over configuration is my preference.
