### ISSUE TITLE
v3.0.0 pre-release: Liquid syntax error: Unexpected character /

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll#3369]
Hello,

I thought I would checkout the pre-release version of Jekyll to try the incremental regeneration, and to see how much breaks. Unfortunately, I’m still at the part of seeing what breaks.

I have a few plugins that provide Liquid filters and tags; many problems seem to be solved by adding a pipe here, removing a square bracket there – although I’m unsure if these ’fixes’ will actually generate the desired content; right now I’m just trying to build a copy of the site! Anyway, I’ve come up against an issue I can’t resolve, so thought I would document it here.

Using the jekyll-picture-tag plugin (https://github.com/robwierzbowski/jekyll-picture-tag) and the following template tag:

```
{{ picture showcase /2008/12/washington_dc_vietnam_memorial.jpg }}
```

I get the following error (full trace provided):

```
  Liquid Exception: Liquid syntax error: Unexpected character / in "{{ picture showcase /2008/12/washington_dc_vietnam_memorial.jpg }}" in journal/_posts/entries/2008-12-29-washington_dc.markdown
/Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/lexer.rb:42:in `tokenize': Liquid syntax error: Unexpected character / in "{{ picture showcase /2008/12/washington_dc_vietnam_memorial.jpg }}" (Liquid::SyntaxError)
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/parser.rb:5:in `initialize'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/variable.rb:64:in `new'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/variable.rb:64:in `strict_parse'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/parser_switching.rb:21:in `strict_parse_with_error_context'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/parser_switching.rb:5:in `parse_with_selected_parser'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/variable.rb:25:in `initialize'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/block.rb:102:in `new'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/block.rb:102:in `block in create_variable'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/block.rb:100:in `scan'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/block.rb:100:in `create_variable'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/block.rb:44:in `parse'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/tag.rb:10:in `parse'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/block.rb:31:in `parse'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/tag.rb:10:in `parse'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/document.rb:5:in `parse'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/template.rb:122:in `parse'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/liquid-3.0.1/lib/liquid/template.rb:108:in `parse'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/convertible.rb:106:in `render_liquid'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/convertible.rb:239:in `do_layout'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/post.rb:270:in `render'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/site.rb:307:in `block in render'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/site.rb:305:in `each'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/site.rb:305:in `render'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/site.rb:55:in `process'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/command.rb:28:in `process_site'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/commands/build.rb:58:in `build'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-69e8f1923c85/bin/jekyll:17:in `<top (required)>'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bin/jekyll:23:in `load'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bin/jekyll:23:in `<main>'
	from /Users/plloyd/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
```

My guess is that this relates to this portion of the plugin code: https://github.com/robwierzbowski/jekyll-picture-tag/blob/master/picture_tag.rb#L41 (the scary looking regex), though I could be wrong.

I also use this tag in a layout, where I populate the liquid block with a page variable, like so:

```
{% picture showcase {{ page.image.url }} %}
```

This works as expected. Any ideas what needs fixing in the plugin to make it work with Liquid/Jekyll 3.0?

**Comment by paulrobertlloyd** [comment]
If I may add a few additional notes/grumbles in the comments…

1. I suspect many existing plugins are going to break on the jump to Jekyll 3. I’ve had to disable a few gems that have their dependancy tied to the 2.x branch — that will require pestering authors to update their Gemspec and any legacy code, which I guess is normal for any big release. But what’s the plan for dealing with the issues that may result from the jump to Liquid 3.0?

2. There doesn’t seem to be any documentation or best practice for how plugin authors should provide arguments in Liquid block tags; I’ve seen different means of providing these, some rely on complex regexs while others use `markup.scan(Liquid::TagAttributes)`(see https://github.com/jekyll/jekyll-help/issues/239 for the issues that raises). Is there a single location where the correct syntax for a Liquid block is documented!?

Liquid is not my favourite piece of software at the moment, not helped by the poor documentation 😬

Okay, moan over!!

**Comment by nternetinspired** [comment]
I made the jump to 3.0.0 yesterday and my own, admittedly poorly constructed, Liquid syntax cause the Liquid 3 parser to crap out in several places. In each case it turned out to be a double pipe `||` or `| |` that was the problem. 

I did a quick ctrl+f of that picture plugin and found 3 instances of `| |`, so that might be worth looking at further.

**Comment by paulrobertlloyd** [comment]
Thanks @nternetinspired. Have you got examples of the changes you made? Seems like the `||` in the plugin are pretty integral to its function (and indeed, removing them breaks things!)

**Comment by paulrobertlloyd** [comment]
Okay, this is odd. This works as expected if I use `{%` instead of `{{`, i.e.:

```
{% picture showcase /2008/12/washington_dc_vietnam_memorial.jpg %}
```

Why is this the case? What’s happening here?

**Comment by pathawks** [comment]
`picture` is a Liquid *tag*, rather than a variable. That’s why you must use `{% picture %}`

**Comment by paulrobertlloyd** [comment]
Ha, and would you look at that… the example I described as working uses `{%` too. And… ooh no… the plug-in documentation uses `{%` too. Doh!

Closing (with my head in my hand, and three-hours of my life I’ll never get back!)
