### ISSUE TITLE
kramdown:syntax_highlighter should automatically take value of highlighter

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll#3371]
Currently, the `highlighter` config value only applies to code wrapped within `{% highlight %}`; fenced code blocks are ignored. You can change this behaviour by providing a value to `kramdown:syntax_highlighter`, but this seems like an unnecessary (and fairly opaque) step. Ideally, rather than this:

```yaml
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
```

we could write this:

```yaml
highlighter: rouge
```

Assuming Rouge is the default, **we wouldn't need to provide a config value at all**. Then using either `~~~ ruby` or `{% highlighter ruby %}` would automatically highlight text. Which would be _lovely_.

**Comment by parkr** [comment]
I like this! In the `KramdownParser`, we'd have to add in somewhere `config['kramdown']['syntax_highlighter'] ||= config['highlighter']` (that allows one to override it if desired) and then we'd have a solution.

**Comment by paulrobertlloyd** [comment]
@parkr Okay, I’ve caught the contribution bug! So with that, I’ve tried to fix this long standing issue… I have some questions, which I’ve detailed in my PR. Thanks!

**Comment by parkr** [comment]
> I’ve caught the contribution bug!

:smile: :tada: :raised_hands: !!
