### ISSUE TITLE
`:title` of collections parsed differently than `:title` of posts

### ISSUE THREAD

**Issue by beep** [jekyll/jekyll#3372]
Filed [a bug in jekyll-help about (possibly) inconsistent `:title` parsing between collections and posts](https://github.com/jekyll/jekyll-help/issues/253). @parkr [helpfully noted](https://github.com/jekyll/jekyll-help/issues/253#issuecomment-71773638) this might be a bug:

> Turns out [jekyll] [extracts the slug (used by `:title`) from the post filename](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/post.rb#L170), whereas collection documents' slugs [are generated either from the title element in the YAML front matter or, if it doesn't exist, by the file basename](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/document.rb#L135).
> 
> It would make sense to me to call the slug the input file's basename in all cases (with date data stripped, of course). What say you?

@parkr’s suggestion gets a big +1 from me. (He also asked me to [file the issue here](https://github.com/jekyll/jekyll-help/issues/253#issuecomment-71773638), so, uh, hello all.)

**Comment by parkr** [comment]
Thank you for re-filing, @beep! We'll get this fixed right away. :sparkling_heart:

**Comment by parkr** [comment]
In implementing this, I noticed that it un-does some of #2864, which allows the `title` attribute to override the filename. Hm.

**Comment by parkr** [comment]
Fixed! It'll be a part of Jekyll 3. Thanks, again! :smile:

**Comment by beep** [comment]
Amaaaaaazing. Thank you, @parkr!
