### ISSUE TITLE
Feature request: initial generation time

### ISSUE THREAD

**Issue by kaatt** [jekyll/jekyll#3377]
Jekyll 3 shows the regeneration time and so showing the initial generation time will be consistent and useful.

**Comment by parkr** [comment]
Sure. Can you please submit a pull request? Should be a trivial change.

**Comment by kaatt** [comment]
Sorry not a ruby coder.

**Comment by parkr** [comment]
Give it a try – Ruby is really easy to use. Write this in `lib/jekyll/commands/build.rb` in the `process` method. Grab a `start_time = Time.now` at the top, then do `Time.now - start_time` at the bottom. The "done" string should be in there.

**Comment by kaatt** [comment]
Already got there but I can't test my code. I specified the path in my Gemfile but get this error while building:

> There was a ArgumentError while loading jekyll.gemspec: 
Malformed version number string 3.0.0-beta1 from /Downloads/jekyll-master/jekyll.gemspec:13:in `block in <main>'

**Comment by parkr** [comment]
What version of `gem` are you using? Try changing `lib/jekyll/version.rb` to `3.0.0.beta1`.

**Comment by kaatt** [comment]
:) Done: #3378
