### ISSUE TITLE
Liquid Exception: undefined method `split'

### ISSUE THREAD

**Issue by IcyTesseract** [jekyll/jekyll#3381]
Hello,
I'm trying to figure out if the following is intentional behavior and if I'm not supposed to be putting in possible Liquid tags in the syntax highlighter. Here is the Markdown:

```html
{% highlight html %}
<p class="post-content">
  {{ post.content | split:"<!-- more -->" | first }}

  {% if post.content contains "<!-- more -->" %}
    <a class="btn btn-primary" href="{{ post.url }}" role="button">Read More of Post</a>
  {% endif %}

</p>
{% endhighlight %}
```

Here is the full error:

```
Liquid Exception: undefined method `split' for nil:NilClass in _posts/2015-01-29-jekyll-tricks-1.md
jekyll 2.5.3 | Error:  undefined method `split' for nil:NilClass
```

I'm using Kramdown as the markdown parser (not sure if that is relevant information). I tried installing a different version of Liquid, but Jekyll says something like version ~2.6.1 is required. Also, I saw something on some IRC from a few days ago from someone who was having a similar issue. I'm not sure if it was resolved.

https://botbot.me/freenode/jekyll/2015-01-26/?msg=30484543&page=1

Is the proper link I believe.

**Comment by sabhiram** [comment]
This totally works for me btw, are you placing this code in your "posts" page? Seems to me like the error is being reported in your jekyll-tricks-1.md post itself. This probably does not have the `post` variable. You would need something like:

```
{% for post in site.posts %}
// use `post` here
{% endfor %}
```

The link you posted had an error in that they were nesting the {{ }} within a {% assign %}. In your case, I think post.content is just nil. In which case the error would make perfect sense :)

**Comment by pathawks** [comment]
I don’t think the `split` tag is included in Liquid 2.x

**Comment by parkr** [comment]
Run `jekyll build --trace` and paste the output, please.

**Comment by IcyTesseract** [comment]
@sabhiram Sorry if I wasn't clear. The code is in the "posts" page and works fine there, but I'm trying to write a post about what I implemented in said "posts" page. Thus, the point is to highlight the syntax.

**Comment by sabhiram** [comment]
Oh, if you are trying to emit the raw text for the HTML formatting - then you can use the {% raw %} tag.

```html
{% highlight html %}
{% raw %}
<p class="post-content">
  {{ post.content | split:"<!-- more -->" | first }}

  {% if post.content contains "<!-- more -->" %}
    <a class="btn btn-primary" href="{{ post.url }}" role="button">Read More of Post</a>
  {% endif %}

</p>
{% endraw %}
{% endhighlight %}
```

**Comment by IcyTesseract** [comment]
Oh thanks. Sorry about that.

**Comment by sabhiram** [comment]
No worries, happy to help out.
