### ISSUE TITLE
frontmatter inheritence

### ISSUE THREAD

**Issue by davidsilvasmith** [jekyll/jekyll#3386]
I recommend adding cascading front matter values.

Example if I have post  xyz.md with frontmatter 

    layout: post
    image: yyy.jpg` 

Post.html has frontmatter:

    layout: default

Default.html has frontmatter:

    image:xxx.jpg

I want `{{ page.image }}` to return yyy.jpg (overriding the value from default.html)  when rendering.

It seemed intuitive for me to set default values in layouts and override them with specific values in actual posts & pages.

Unfortunately layout values override posts and pages layouts.

I ended up working around this by putting the defaults into _config.yml defaults, but then that gets into the whole site reloading issue (#2302).

**Comment by gntech** [comment]
Default front matter values can be defined through _config.yml like so [http://jekyllrb.com/docs/configuration/#front-matter-defaults](http://jekyllrb.com/docs/configuration/#front-matter-defaults)

# Example
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false

**Comment by gntech** [comment]
I think the intended way is having the default values defined in _config.yml per [http://jekyllrb.com/docs/configuration/#front-matter-defaults](http://jekyllrb.com/docs/configuration/#front-matter-defaults)

Then you can override the defaults in your specific post front matter.

Why is #2302 a problem for you in this case?

**Comment by davidsilvasmith** [comment]
Thanks for the response.

Yes the _config.yml is the way to do it. However it is intuitive to have frontmatter in leaf pages / layouts override what they inherit from.

#2302 is a UX issue because Jekyll has to be restarted to read those values. That is a sub-optimal workflow, which would be fixed by having frontmatter inheritance from layouts.

**Comment by parkr** [comment]
This has been fixed in 3.x where layout data is `layout.image` and post data is `page.image`.
