### ISSUE TITLE
Collection files without YAML

### ISSUE THREAD

**Issue by tonyarnold** [jekyll/jekyll#3387]
Hi guys, currently it seems like YAML is required in files that want inclusion in a collection. I'd love to see this changed so that I can pop raw Markdown files in a collection and have them generated into HTML for output _without requiring the frontmatter_. 

Is there any way to achieve this at present?

**Comment by parkr** [comment]
Not at present. If you don't have the front matter, it's considered a raw file, like an image or a pdf. We only look at file extensions *after* this initial "does it have yaml?" stage.

What is your use-case? Why can't you add the header?

**Comment by tonyarnold** [comment]
It's documentation from another system. I was trying to keep it single source and not modify the files unless necessary.

**Comment by parkr** [comment]
Ah. Are you trying to use multiple static site generators? If not, adding the yaml should br pretty trivial. :)

**Comment by tonyarnold** [comment]
It's bundled within a desktop app then processed through a markdown engine directly (that doesn't understand YAML front matter). It's definitely trivial to add the FM, but undesirable for my needs.

**Comment by parkr** [comment]
We allow static files in collections in Jekyll 3, but we have no plans to deviate from Jekyll's way of knowing whether something is convertible (presence of front matter). Thanks!
