### ISSUE TITLE
Incorrect deprecation warning for jekyll-paginate gem

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll#3393]
I’ve just updated to the latest build, and now getting this message:

```
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
```

I'm not loading my Jekyll gems by listing them in my config file, but via the `:jekyll_plugins` Gemfile group, i.e.:

```ruby
group :jekyll_plugins do
  gem 'jekyll-archives'
  gem 'jekyll-assets'
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
end
```

So this warning is incorrect. Is there a better way to test for the existence of `jekyll-paginate`?

**Comment by parkr** [comment]
We should probably do a config/plugin check after the plugins are required. Good catch!

**Comment by mediadoneright** [comment]
Seems to mean the docs are incorrect, too:  http://jekyllrb.com/docs/pagination/#enable-pagination

Doesn't specify how to include the pagination plugin
