### ISSUE TITLE
Duplications of Home page when using pagination

### ISSUE THREAD

**Issue by IcyTesseract** [jekyll/jekyll#3395]
Hello,
I'll do my best to explain this issue, but it's kind of hard to describe. Currently I'm trying to setup my navbar on my website and I'm using this code:

```html
{% if site.pages.size > 0 %}
  <ul class="nav navbar-nav navbar-right">
    {% for page in site.pages %}
      {% if page.title %}
        <li><a href="{{ site.url }}{{ page.url }}">{{ page.title }}</a>
        </li>
      {% endif %}
    {% endfor %}
  </ul>
{% endif %}
```

to:

- Check for pages
  - If there are pages, loop through them
    - If the page has a title then it's added (avoids blank entries with files that have front matter)

The problem is when I add `paginate: 5`, since I have more than 5 posts, the other posts move to another page. This causes Jekyll to think that I have more than one page titled: "Home." Thus, the loop creates more entries for Home within the navbar (one for each time there is a new page created).

Was this behavior intentional? Technically a work around would be to use liquid in order to check whether or not "Home" has already been added and, if it has been added, to omit it every other time.

**Comment by pathawks** [comment]
Maybe only add “Home” to the sidebar when that page’s permalink matches the homepage?

**Comment by IcyTesseract** [comment]
How can you check a page's permalink?

**Comment by parkr** [comment]
Use page.url.




— Parker

**Comment by IcyTesseract** [comment]
Perfect! I'm sure this will come in handy somewhere else.
