### ISSUE TITLE
Is possible define a custom strategy to generation of files?

### ISSUE THREAD

**Issue by gabrielcaires** [jekyll/jekyll#3398]
We have a large project with more of 2000 posts and growing.
Our worflow is:
- A custom cms that generate markdown files
- The markdown are "pushed" to a repo in github
- We have a CLI tool that execute a pull in this repo and use Jekyll to generate all HTML pages.
- The CLI push to Github' pages branch

Our priority is:
First:
- Generate the index page
- Generate the "post page"
- Update all other posts page (related_posts) in a second moment. If is possible with a hook to manege the files generated.

**Comment by parkr** [comment]
Liquid would likely be what you're looking for here, unless I'm missing something.
