### ISSUE TITLE
../rvm/gems/ruby-2.2.0/gems/liquid-2.5.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"

### ISSUE THREAD

**Issue by tonyynot** [jekyll/jekyll#3399]
I'm receiving this error each time I run a Jekyll command.

../rvm/gems/ruby-2.2.0/gems/liquid-2.5.1/lib/liquid/htmltags.rb:43: warning: duplicated key at line 46 ignored: "index0"

Troubleshooting:
I ran bundle install, reinstalled liquid, reinstalled jekyll, reinstalled python. Is there a way I can manually remove the duplicated key from htmltags.rb?

**Comment by tarebyte** [comment]
@tonyynot are you using the `github-pages` gem?

**Comment by parkr** [comment]
This will not affect your build and this issue is a duplicate. Upgrade Liquid to the latest 2.6 version (2.6.2 i believe) and it'll go away.
