### ISSUE TITLE
About Firewall

### ISSUE THREAD

**Issue by wi1d5ky** [jekyll/jekyll#3400]
I don't know how to set so let I can use another computer visiting my site...
I am using Windows, and don't know how to set firewall...
((Before, I use xampp so I just let firewall allow its service, apache, to work.
But jekyll is command... I don't know what I should set...
Plz help me :-(

Sorry for my poor English...

**Comment by parkr** [comment]
For other computers, you have to bind Jekyll to the host. So if your computer is at 10.123.312.231, run Jekyll with that host:

```text
$ jekyll serve --host 10.123.312.231 --port 4000
```

Then tell people to go to http://10.123.312.231:4000 :)

**Comment by wi1d5ky** [comment]
@parkr Can't I let any other computers visit my site?
Thank you for your quick answer :-)

**Comment by wi1d5ky** [comment]
OH !!!!! I got it, Thank you very much!!!
