### ISSUE TITLE
Set meaningful file modification times

### ISSUE THREAD

**Issue by fulldecent** [jekyll/jekyll#3403]
My workflow to use Jekyll is:

  * Edit source files
  * `jekyll build`
  * Rsync files to server

This causes every file to be republished every time because jekyll sets the file modification times to the current time.

I recommend that each built file have a modification time equal to the latest modification time of any of its input files.

**Comment by parkr** [comment]
Incremental regeneration will do this for you and we have a PR merged which preserves mtime of static files: https://github.com/jekyll/jekyll/pull/3220

These will ship with 3.0

**Comment by fulldecent** [comment]
Very cool, thank you.
