### ISSUE TITLE
Error Liquid Exception on compile

### ISSUE THREAD

**Issue by LeG3nDz** [jekyll/jekyll#3406]
Hi community,

Yesterday I set up a new date format ( FR) on Jekyll . The compilation worked perfectly with the command " bundle exec Jekyll serve -w" . Today, without touching anything , no change , I have an error message during compilation :

    Liquid Exception : in is not a valid local in _layouts / blog - post.html

I'm a Windows user and my repot : https://github.com/LeG3nDz/v3.stephane-richin.lan

Thank you all !

**Comment by parkr** [comment]
Something definitely changed if it built fine then didn't build fine later. Jekyll isn't *that* crazy.

Did you check _layouts/blog-post.html for misplaced colons?

**Comment by LeG3nDz** [comment]
Hi,

Yep i've check the blog-post.html :

    <time datetime="{{ post.date | date: "%Y-%m-%d" }}" itemprop="datePublished">{{ post.date | localize: "%e %B %Y" }}</time>

It's for chang the date format with plugin.

**Comment by parkr** [comment]
We don't maintain those plugins so please file this with the plugin author. If you remove `localize`, does it compile?

**Comment by LeG3nDz** [comment]
Yes, compile fine

**Comment by tkrotoff** [comment]
@LeG3nDz 

I'm also using `i18n_filter.rb` and I got a similar issue: `Liquid Exception: :en is not a valid locale`. Here the hack to fix this:

```Ruby
# Taken from https://github.com/gacha/gacha.id.lv/blob/master/_plugins/i18n_filter.rb

require 'i18n'

LOCALE = :fr # set your locale

# Create folder "_locales" and put some locale file from https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale
module Jekyll
  module I18nFilter
    # Example:
    #   {{ post.date | localize: "%d.%m.%Y" }}
    #   {{ post.date | localize: ":short" }}
    def localize(input, format=nil)
      load_translations
      format = (format =~ /^:(\w+)/) ? $1.to_sym : format

      # Force the locale each time otherwise `jekyll serve` will fail with
      # "Liquid Exception: :en is not a valid locale" each time a regeneration happens
      I18n.locale = LOCALE

      I18n.l input, :format => format
    end

    def load_translations
      if I18n.backend.send(:translations).empty?
        I18n.backend.load_translations Dir[File.join(File.dirname(__FILE__),'../_locales/*.yml')]
      end
    end
  end
end

Liquid::Template.register_filter(Jekyll::I18nFilter)
```

**Comment by LeG3nDz** [comment]
Hi @tkrotoff !

Thank you, i've test your code and it's fix this ! Thank you again :) By curiositer , what was the problem?

**Comment by tkrotoff** [comment]
For a reason I don't know, I18.locale does not keep its value when Jekyll performs a regeneration.
