### ISSUE TITLE
Package with Traveling Ruby

### ISSUE THREAD

**Issue by FooBarWidget** [jekyll/jekyll#3409]
Not all of your users are Ruby programmers, and those who are not Ruby programmers may have trouble installing Jekyll. Maybe you can package Jekyll with [Traveling Ruby](http://phusion.github.io/traveling-ruby/) to solve this problem.

**Comment by parkr** [comment]
I was thinking that just the other day! I worked on omnibus-jekyll (another repo) and so far I have been able to extract a .pkg from that which works well, but I have not been able to support Windows yet. Does Travelling Ruby support Windows?

**Comment by FooBarWidget** [comment]
Not at the moment. Linux and OS X only so far.

**Comment by FooBarWidget** [comment]
Traveling Ruby 20150210 has been released. It now supports Windows.

**Comment by parkr** [comment]
> Traveling Ruby 20150210 has been released. It now supports Windows.

:100: . I'll take a look soon! I imagine we can take this package, throw it in `/opt/jekyll` and `ln -s /opt/jekyll/bin/jekyll /usr/local/bin/jekyll` and call it a day?

**Comment by FooBarWidget** [comment]
The symlink approach might be problematic. The wrapper script detects its own location by parsing its filename. When you start jekyll through the symlink, the wrapper script may think it's own location is /usr/local/bin instead of /opt/jekyll.

There are two ways to solve this. You can either make /usr/local/bin/jekyll a wrapper script which calls /opt/jekyll/bin/jekyll, or you can go for the symlink approach but make /opt/jekyll/bin/jekyll resolve symlinks when detecting its own location.

**Comment by FooBarWidget** [comment]
I noticed that Jekyll uses a number of native extensions that Traveling Ruby currently does not package. I've packaged them now and they will be made available in the next version.

**Comment by parkr** [comment]
:raised_hands: 

With symlink support, it'd be perfecto.

**Comment by envygeeks** [comment]
Is there any reason to select Traveling Ruby over the native package managers @FooBarWidget?

**Comment by FooBarWidget** [comment]
Because of the effort involved. If you want to package using native package managers, it can easily take months due to the sheer number of platforms involved as well as the extremely steep learning curves. With Traveling Ruby, I estimate a week at most, because it's literally dropping a bunch of files in a tarball and calling it a day.

See https://github.com/phusion/traveling-ruby#motivation.

**Comment by envygeeks** [comment]
I'm looking for real reasons, not hyperbolic assessments I already know are false when it comes to Linux.

**Comment by envygeeks** [comment]
I'm not trying to be mean here, but the statements made about treating each distro as a unique OS are simply flat out a lie, we build packages that are portable from Ubuntu 12.04 to 14.10 and even to the old-stable and current-stable of Debian with no problems what so ever, in a single binary, a single deb.  I personally do it almost every week for our Ruby packages that are ported between our entire stack and all of our client stacks.  BTW, we build all those packages from my Ubuntu 14.04 build server.

**Comment by FooBarWidget** [comment]
I am sensing some animosity here because you accuse me of lies. Perhaps you think my claims are unfounded and pulled out of thin air.

I'm not going to spend a lot of time defending myself because you are clearly convinced that building portable binaries is easy. For me, Traveling Ruby is a side project that I'm sharing with the world because I think people will benefit from it. There's only so much time I can spend on it, including on explaining the problem.

Suffice to say that,

1. I have been programming C and C++ for Linux since 2001, and that I have spent a lot of time researching Linux binary portability and Linux runtime components like gcc, glibc etc for years.
2. The "treating each distro as a unique OS" mentality came from *Linux distribution makers themselves* when I corresponded with them.
3. I spent literally 3 months on trying to create Debian and Ubuntu packages for Phusion Passenger.

So instead of further explaining the problem, I encourage you to go ahead and make OS specific packages. If you are lucky and you happen to have made RPMs, DEBs and .dmgs in a single week, and it also happens to be portable, more power to you. If not, then you will have personally experienced all the pain I had gone through and you will know what I'm talking about.

**Comment by tamouse** [comment]
@FooBarWidget -- I think using Traveling Ruby is probably the best way to make Jekyll good for non-programmers. I have a lot of problems trying to explain things when people do not understand Ruby and though most people get through the installation and so on of Ruby's ecosystem, it's still a barrier.

That said, I hope Jekyll's trajectory isn't to become the next wordpress, either, and retains it's sense of hackability, which I don't actually worry about at all... :)

Thanks for working on Traveling Ruby, too.

**Comment by envygeeks** [comment]
I already did and I already do (all the time) @FooBarWidget that's why I was asking why there was an upside (if there is any.) I do apologize if you thought I had animosity when I didn't. Calling out something clearly false and highly situational is not in any way animosity but if you took it that way there is nothing I can or will do about it because I stated what I thought as a sysadmin by trade and programmer by choice who has been making portable packages for a long time.

I'm not ruling out TravelingRuby for OS X since I have no experience in that operating system but I can say for sure that I have already built (within a day) portable Deb's and RPM's that bundle Ruby and Jekyll into an isolated folder now all I have to do is recompile them to support older distros (about 10 minutes worth of work) and we'll be good as gold.

All that said, if you feel the need to defend yourself or your product then perhaps your product is doing it wrong, because you shouldn't need to build a defense towards the question: "What does it bring that I can't do myself just as quickly."  That's the wrong way to treat a product you are trying to push.

**Comment by FooBarWidget** [comment]
It isn't so much that I think the product needs defending. It is that I do not feel like convincing others that there is a problem. If you do not feel the pain of the problem, or if you can't imagine it, then I don't want to push too hard.

But for some, the problem is *very* evident, and contrary to your experiences. For example, the Heroku Toolbelt developers recently rewrote the software in Go so that they could easily build executables for Linux, OS X and Windows. For them, the fact that they had recompile stuff for older distros was a huge pain point. Ditto for the Github "hub" command line tool developers -- they rewrote it in Go as well, citing distribution as a major pain point. Had Traveling Ruby been released sooner then maybe they wouldn't have had abandoned Ruby at all.

**Comment by parkr** [comment]
I, for one, cannot build all these different packages very easily, so I think Traveling Ruby is focused on people like me, who don't know or have less experience with systems. :)

**Comment by envygeeks** [comment]
What is the status of this?  Even though @FooBarWidget thinks I have beef with his product I don't so I would like to know what the decision is or if I should try to package for OS X with Traveling Ruby?  Again, I do not believe we need it for Linux but I think it would be a great idea for OS X where none of us have experience compiling for that operating system (and even more so for Windows.)

If nobody wants to do this I would be glad to do this just point me to the docs and I'll get it done.

**Comment by parkr** [comment]
I think the idea of making packages for each system is great – the installation process for Jekyll is often lamented. (See: https://talk.jekyllrb.com/t/closed-poll-installation-priorities-for-3-0/106, 21 votes for single-click installer!) It should work "seamlessly" and not require PATH updates if at all possible.

**Comment by envygeeks** [comment]
I don't know if that's possible without seeing docs to see if they even support post install hooks.  I surely wouldn't go around symlinking shit all over the place because that is disastrous on uninstall but tbh I don't even know how Mac handles binaries from packages to begin with so I would have to start from there to even have a grasp on how to do it.  As far as Windows we can modify the users path on install which would solve the problem there.

**Comment by strzibny** [comment]
We started to use Jekyll for a Fedora site and I might slowly start packaging it for Fedora (native repositories, not bundle). (We need that for deployment to Fedora infra if we want to generate the site on the server.) If someone would like to help me, just say ;).

**Comment by envygeeks** [comment]
@strzibny we provide docker images so that people don't have to package, we do plan on adding packages for distros (and we already do provide a packager for debian) but Docker should help alleviate some of the problem.

**Comment by strzibny** [comment]
@envygeeks Docker unfortunately does not really solve the problem for us as it's pretty much the same thing for Fedora Infra (not part of Fedora repos), but we will see.

**Comment by envygeeks** [comment]
@strzibny well if you ya'll need help or wish to put it under our umbrella so that we can keep it up to date after you do the intial build let us know.  I'm happy to help maintain and keep it up to date for Fedora users.

**Comment by parkr** [comment]
We have gone ahead and packaged everything inside of Docker which fulfills our goals of being easy to deploy/use and supporting most major platforms. See https://github.com/jekyll/docker for more.
