### ISSUE TITLE
Interpolation in YAML frontmatter

### ISSUE THREAD

**Issue by nybblr** [jekyll/jekyll#3410]
I'm working on a Jekyll app that hosts a blog, various pages, and a ton of bios. All of these pages share the exact same layout. The bios have frontmatter like `name` and `position` all specified.

All the bios (quite a few them) need to have a particular `title` format: `"#{page.name} - #{page.position}"`. However, the only way I can accomplish this without duplicating my main layout (along with the various _includes) is to manually build the `title` attribute out for every single bio entry (on the order of 100 entries). Neither solution feels DRY.

I've entertained a few different ways this could be accomplished:

1. **A `yield` mechanism** such as ERB allows. This seems like it might be tricky to implement though and might run against the grain of Liquid?
2. **Allow a page to specify (in its frontmatter) what Page type it should be hydrated with.** Then I could just specify `page_type: BioPage` and implement a page type that defines a `title` method. This mechanism would also allow a default page type to be specified in `_config`. It seems like a potentially elegant solution that could make similar problems easier.
3. **Allow interpolation in the Yaml frontmatter,** similar to Rails' interpolation syntax in locales. Thus, I could simply have all the bios use an intermediary layout called `bio`, and the `bio` layout would use the `default` layout, but with one YAML frontmatter addition: `title: "%{name} - %{position}"`

Those last 2 options seem like good feature additions to Jekyll, but is there a similar mechanism already in place that would make them less desirable (or would solve the duplication issue I currently face)?

**Comment by pathawks** [comment]
**#****2** is the way this is done. Instead of `page_type`, it's called `layout`.

Then, just include a `BioPage.html` layout in your `_layouts/` directory. Depending on your needs, the `BioPage.html` layout may be able to make use of your main layout, further DRYing your codebase.




...unless I am misunderstanding what you are asking.

**Comment by nybblr** [comment]
@pathawks I don't thinks that's quite what I'm after. Nesting layouts does not allow me to dynamically generate frontmatter attributes (e.g. title).

Normally, all the pages are backed by an instance of `Jekyll:Page` or another `Jekyll::Convertible` type. I was looking for a way to tell Jekyll that a particular template (e.g. `abouts/bios/founder.html`) should be "hydrated" with a `Jekyll::Page` subclass. That way, I could define a Page subclass like:

~~~ruby
module Jekyll
  class BioPage < Page
    def title
      super || "#{name} - #{position}"
    end
  end
end
~~~

**Comment by kleinfreund** [comment]
@nybblr I usually use the `_data` directory with a YAML/JSON file and a layout for these kind of things. Won't that work for you?

**Comment by pathawks** [comment]
I guess I don't understand why you need to dynamically generate frontmatter attributes.  
Why not just use `{{ name }} - {{ position }}` in your layout?

**Comment by nybblr** [comment]
@pathawks I could, but I use that layout with a bunch of other pages that generate titles differently (most of them are set explicitly). I don't want to copy-paste the layout over and over with slight mods just to modify how the title is generated.

@kleinfreund I use `_data` liberally, but maybe I'm not understanding how you recommend using it?

**Comment by pathawks** [comment]
So in your master layout, set up a conditional.
Something like:

```html
<title>
    {% if page.bio %}
        {{ name }} - {{ position }}
    {% else %}
        {{ page.title }}
    {% endif %}
</title>
```

**Comment by nybblr** [comment]
@pathawks That's essentially what I resorted to, only I moved the logic into a helper since we reuse the title in several meta tags.

Giant case statements like this feel really inelegant to me and introduce changes to unrelated parts of the codebase — I still feel like #2 and #3 could be nice cleanups, so I may try prototyping #3 to start with.

**Comment by parkr** [comment]
Please see https://github.com/gjtorikian/jekyll-conrefifier for this functionality. Thanks!
