### ISSUE TITLE
"Jekyll Weekly" Newsletter

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#3416]
Hey!

At the Jekyll meet-up tonight, @jglovier mentioned a newsletter. I think it's an *amazing* idea. Thoughts?

**Comment by jglovier** [comment]
![yup-stepbrothers](https://cloud.githubusercontent.com/assets/1319791/6090428/b9c89d6e-ae2d-11e4-9e3c-02eb9fb9c32e.gif)

I can get started with setting up a free MailChimp account. Is there an email address I should use other than my own for admin purposes?

**Comment by troyswanson** [comment]
+1 for MailChimp.

**Comment by parkr** [comment]
> Is there an email address I should use other than my own for admin purposes?

I can create a newsletter@jekyllrb.com account.

**Comment by jglovier** [comment]
@parkr :+1: :zap:

**Comment by alfredxing** [comment]
That would be awesome! It would make a great supplement to the blog/news site.

**Comment by penibelst** [comment]
Why not use the official blog? It’s already there.

**Comment by jalcine** [comment]
@penibelst The newsletter could be used a lead generator to the blog and a means of keeping the community chatting. A newsletter is opt-in, too.

**Comment by parkr** [comment]
The official blog is about Jekyll news more directly, whereas the "newsletter" is any Jekyll- or static site-related content that the community might be interested in hearing!

**Comment by mattr-** [comment]
IMHO, we should think of Jekyll Weekly like the various weekly newsletters (Ruby Weekly, Javascript Weekly, etc.) put out by Peter Cooper.

**Comment by parkr** [comment]
> we should think of Jekyll Weekly like the various weekly newsletters (Ruby Weekly, Javascript Weekly, etc.) put out by Peter Cooper

That's what I was driving at for sure. Not as an announcement newsletter, but as a more educational kind of piece.

**Comment by grobmeier** [comment]
Awesome! In case admins don't know, Mailchimp can do a weekly newsletter automatically by reading a blogs rss feed.

**Comment by budparr** [comment]
One of Jekyll's strengths is its great community and I think people would love a chance to submit their blog posts, gists and sites for showcasing; a newsletter is a good format. 

I think posting to Mailchimp is probably a pain to keep up with over time, but you you could throw up a Jekyll blog (separate from the main blog, which would not benefit from community participation), take PRs, and, like @grobmeier says, have Mailchimp read the feed and send it out automatically. It would all mostly take care of itself.

The thing I'm doing with [The New Dynamic](http://www.thenewdynamic.com/) is about static site generators in general because the primary purpose of the site is to encourage people who build websites to adopt static sites and to see how the whole scene evolves. Thanks for the notice, @parkr and I'm happy to help with this endeavor any way I can.

**Comment by envygeeks** [comment]
planet.jekyll.com would definitely fit that bill and could be auto-curated into Mailchimp.

**Comment by parkr** [comment]
The word "planet" doesn't sit super well with me, but maybe "community"?

**Comment by jalcine** [comment]
On Sunday, February 08, 2015 03:10:24 PM Parker Moore wrote:
> The word "planet" doesn't sit super well with me, but maybe "community"?

Community does sound a lot more flat :)
However, the term Planet has been used a lot by other communities (hah) to 
represent a core syndication of related content. Like Planet KDE and Perl's own 
syndicated blog.

**Comment by parkr** [comment]
As much as I respect them, I'm not sure that I want to emulate KDE or Perl. :wink: "Planet" just sounds really cult-ish.

**Comment by envygeeks** [comment]
"planet" is the standard term used by most open source projects to gather data from across the planet and aggregate it into either a website with an XML feed or into a newsletter: planet.ubuntu.com, planet.gnome.com, planet.fedoraproject.org

**Comment by jalcine** [comment]
On Sunday, February 08, 2015 03:16:46 PM Parker Moore wrote:
> As much as I respect them, I'm not sure that I want to emulate KDE or Perl.
> :wink: "Planet" just sounds really cult-ish.

Hah, that I can definitely see. :+1: for community from me, though!

-- 
Jacky Alcine
http://jacky.wtf

**Comment by envygeeks** [comment]
And also, they don't use the term plant because it's a cult-ish thing they use the term planet because they are figuratively troving the "planet" for data to feed to the user, it's a pragmatic usage and community is a very bad term to use for such an aggregation because community implies some form of input, and users do not have some form of input.

**Comment by grobmeier** [comment]
I didn't want to use the term "planet" as it sounds a little oldschool. Instead I used "sphere", in my case "dartosphere.org"

sphere.jekyll.org - not sure if I like, just want to give some inspiration

**Comment by alfredxing** [comment]
My suggestion would be "community" if it's a forum or something, and just "news" if it's a newsletter site.

**Comment by jglovier** [comment]
+:100: for `community`. From a marketing perspective, "planet" is just really ambiguous, whereas "community" has the clear connotation I think we are implying.

**Comment by jglovier** [comment]
>>IMHO, we should think of Jekyll Weekly like the various weekly newsletters (Ruby Weekly, Javascript Weekly, etc.) put out by Peter Cooper.

>That's what I was driving at for sure. Not as an announcement newsletter, but as a more educational kind of piece.

:star: :star: :star: :star: Good play. I think it would still be an appropriate venue for Jekyll announcements, but it's primary value would be in the former content suggestion.

**Comment by jglovier** [comment]
>@jglovier Please use newsletter@jekyllrb.com !

Done. Is that a distro you can add me to?

**Comment by parkr** [comment]
> Is that a distro you can add me to?

I added you! Maybe I added the wrong email address. Email me your email address? I got rid of my twitter account. :)

**Comment by jglovier** [comment]
@parkr yup - it came through. Thx!! :love_letter:

**Comment by envygeeks** [comment]
Is this still a pending issue or better can we move this discussion to talk.jekyllrb.com meta?

**Comment by envygeeks** [comment]
The reason I say that is because we've been pushing others off of this medium for non-bugs and this is kind of a non-bug IMO so maybe we should kick it off here and onto talk.jekyllrb.com so we dog food what we do to other people.

**Comment by parkr** [comment]
@envygeeks Yeah we can continue this on the discourse site! I'm sure some of this need is filled by the digest email from Discourse, but there is something to be said about it being curated, too.
