### ISSUE TITLE
Option draft is an alias for drafts

### ISSUE THREAD

**Issue by penibelst** [jekyll/jekyll#3421]
Jekyll 2.5.3 here. I noticed the command line option `--draft` without “s” works the same way as `--drafts`. Is this an intended behaviour? If not, it would be nice to deprecate the undocumented feature in the upcoming major release.

```shell
jekyll build --drafts
# same output
jekyll build --draft
```

**Comment by parkr** [comment]
What output did you see for both? It should just be [`--drafts`](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/command.rb#L57).

**Comment by penibelst** [comment]
Both render the drafts. No error is thrown.

**Comment by zebron** [comment]
How do I get off the email thread?

**Comment by pathawks** [comment]
> How do I get off the email thread?

Stop watching Jekyll?

**Comment by parkr** [comment]
I have been all through Mercenary and OptionParser – it looks like it's a feature of OptionParser. Try this out:

```ruby
require 'optparse'

p ARGV
options = {}

optparser = OptionParser.new do |opts|
  opts.on('--drafts') do
    options['show_drafts'] = true
  end
end

p optparser.parse!
p options
```

It works with `-d`, `--draft`, and `--drafts`. We'd have to catch `--draft` ourselves, which I'm not really interested in at this point.
