### ISSUE TITLE
Problem after removing previous runtime dependencies

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#3422]
65d43ef398b81127c692995664170e561bca8da7 Causes my site to not build, and doesn't provide much in the way of error messages.

I was pulling my hair out before I realized that all I needed to do was add `redcarpet` to my Gemfile. I guess I was using a plugin that `require 'redcarpet'`, and this had never been a problem before since it was just there. Now, I need to explicitly add it to my Gemfile.

Is there anyway at all for Jekyll to catch this sort of thing and provide just a bit more guidance?

**Comment by parkr** [comment]
We *might* be able to catch `LoadError`'s in certain situations.

**Comment by parkr** [comment]
I believe we now [provide guidance through our require helper method](https://github.com/jekyll/jekyll/blob/fb8bf7bab6ab76cdc669a6ac218cedc432cc7fed/lib/jekyll/converters/markdown/redcarpet_parser.rb#L58).
