### ISSUE TITLE
Fix configuration documentation

### ISSUE THREAD

**Issue by adius** [jekyll/jekyll#3430]
Shouldn't it be "kramdown" instead of "maruku" in the [configuration documentation](https://github.com/jekyll/jekyll/blob/gh-pages/docs/configuration/index.html#L2518)?

**Comment by penibelst** [comment]
Yes, the documentation is outdated. Feel free to make a PR.

**Comment by parkr** [comment]
Those are the maruku configuration options. Maruku is still supported (as of the writing of this comment), and can therefore still be configured.

**Comment by adius** [comment]
But maruku is not the default compiler. And it's nowhere mentioned that kramdown is. So you start changing the settings for Maluku and wonder why nothing happens until you find out in the xth forum that Jekyll is actually using kramdown and not Mariko like suggested by the docu...

**Comment by penibelst** [comment]
I was wrong. As @parkr said, those are Maruku configuration options.

```yaml
markdown:    kramdown
```

The default markdown compiler is set by the `markdown` option. It’s in the documentation, but the formatting is broken, so it’s unreadable. I’ll fix it.

**Comment by penibelst** [comment]
This is how the current documentation looks in Firefox 35:

![docs-config-3430](https://cloud.githubusercontent.com/assets/3617307/6103655/e42f1f18-b046-11e4-926a-c386468601a7.png)

**Comment by penibelst** [comment]
If I build the docs locally, they looks right.

![docs-config-3430-local](https://cloud.githubusercontent.com/assets/3617307/6103773/ceb43adc-b047-11e4-80e0-c7d03b4a60ea.png)

@parkr The current build on the website seems broken.

**Comment by parkr** [comment]
This is caused by #3401 I think.

**Comment by parkr** [comment]
Just re-published. Fixed!

**Comment by penibelst** [comment]
Very nice.
