### ISSUE TITLE
Not all files generated every time

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#3432]
It seems that, sometimes when I build my site, not all of the files are generated. If I delete my `_site` directory and run `bundle exec jekyll build`, after the build has finished my destination will sometimes be missing key files. Sometimes it is missing the `index.html` file (!), sometimes the favicon, etc.

Obviously, this is not the desired behavior.

I'm running Jekyll master. Unfortunately, my site is private and I really can't post the source.

**Comment by pathawks** [comment]
I seem to get better results if I delete `.jekyll-metadata` before each build; does this have something to do with incremental regeneration?

**Comment by parkr** [comment]
Check out `Incremental build` in the output. If it's `enabled`, that means it's incrementally building. This is a feature, not a bug. :smile:

**Comment by pathawks** [comment]
I guess I was just running into very strange edge cases as I was switching between different versions of Jekyll. :page_with_curl:

**Comment by willnorris** [comment]
for future reference, you can also just pass `-f` or `--full-rebuild` to `jekyll build` instead of manually deleting the `.jekyll-metadata` file.

**Comment by pathawks** [comment]
@willnoreis Thanks.
I ended up putting `full_rebuild: true` in my `_config.yml`.
