### ISSUE TITLE
did not find expected key???

### ISSUE THREAD

**Issue by ZhipengZeng** [jekyll/jekyll#3433]
Guys, any ideas for this issue?
`jekyll 2.4.0 | Error: (e:/AAA-Blog/_config.yml): did not find expected key while parsing a block mapping at line 1 column 1`

my `_config.yml`:
```
highlighter: rough
baseurl: /AAA-Blog
markdown: kramdown
#markdown: redcarpet
encoding: utf-8
highlighter: true
#highlighter: pygments
activate :syntax, line_numbers: true
- C:/Ruby21-x64
```

**Comment by pathawks** [comment]
`rough`?

**Comment by ZhipengZeng** [comment]
sorry for spelling mistake,
in my `_config.yml`, it's `rouge`, I typed wrong, so not that problem

**Comment by pathawks** [comment]
You do have `highlighter` twice:

```yaml
highlighter: rough
highlighter: true
```

**Comment by ZhipengZeng** [comment]
tried that, still the same result, but would it really cause something unexpected problems?
```
highlighter: rouge
baseurl: /AAA-Blog
markdown: kramdown
#markdown: redcarpet
encoding: utf-8
#highlighter: pygments
activate :syntax, line_numbers: true
- C:/Ruby21-x64
```

**Comment by ZhipengZeng** [comment]
I fixed this issue now by deleting the last line `- C:/Ruby21-x64`
but why? I'll close this issue, thx @pathawks

**Comment by pathawks** [comment]
I'm not a Windows guy so I don't know: what did you expect that line to do?

**Comment by ZhipengZeng** [comment]
I don't know...I've modified `_config.yml` so many times that I totally messed up.
But I thought I copied it from somewhere.
I still have some confusion in highlighting code with rouge, pygments

**Comment by kleinfreund** [comment]
You copied that line from the tutorial to install jekyll on Windows. This line belongs into the config.yml in the devkit directory. I mentioned that in your previous issue.

**Comment by ejaffee01** [comment]
I'm having a similar issue. 

My config.yml looks like this

`lang: en
author: "Ethan Jaffee"
title: "Ethan Jaffee"
description: "Blog and website of Ethan Jaffee."
keywords: "smith, jones, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "ejaffee01@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Ethan Jaffee is an awesome person. He lives in Westfield, where he is a high school student.

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/EthanJaffee"
  - title: "twitter"
    url: "https://twitter.com/ejaffee01"
  - title: "github"
    url: "https://github.com/ejaffee01"
  - title: "bitcoin"
    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji`

I am getting the error  `did not find expected key while parsing a block mapping at line 1 column 1`

Thanks!

**Comment by pathawks** [comment]
@ejaffee01This issue has been closed.

If you are experience a bug with the latest version of Jekyll, please open a new issue and provide a way to replicate that issue (preferably with some sort of minimal Jekyll site that exhibits the behavior)
