### ISSUE TITLE
which highlighter matches which markdown syntax?

### ISSUE THREAD

**Issue by ZhipengZeng** [jekyll/jekyll#3434]
* if I use `highlighter: rouge` or `highlighter: pygments` with syntax below:  

> \`\`\`sh
> #!/bin/bash
> \`\`\`

it generates to website as:
> sh 
> #!/bin/bash

and the html code is:
> \<code\>
> "sh
> #!/bin/bash
> "
> \</code\>

* If I use {% highlight bash %} and {% endhighlight %} tag with `highlighter: rouge`, it works fine.

* If I use {% highlight bash %} and {% endhighlight %} tag with `highlighter: pygments`, jekyll shows this error: **undefined method `[]' for nil:NilClass**, and the jekyll serve breaks down. But actually if I commit my changes and sync to github, it works fine.

my `_config.yml`:
```
#highlighter: rouge
baseurl: /AAA-Blog
markdown: kramdown
#markdown: redcarpet
encoding: utf-8
highlighter: pygments
activate :syntax, line_numbers: true
```

BTW, which one is better, kramdown or redcarpet? or it's all up to me? I don't see the difference.
**So any ideas for issues above? Thanks**

**Comment by pathawks** [comment]
Do you have the `pygments.rb` gem installed on your local machine? I know for a while pygments was totally borked under Windows.

**Comment by kleinfreund** [comment]
Don't bother getting pygments to work under Windows. You would need to install python for that.

**Comment by parkr** [comment]
Yeah, definitely continue using Rouge. Backtick code blocks only work with certain markdown converters, not with all of them.
