### ISSUE TITLE
Article is leading to 404 error in 'Resources' on website

### ISSUE THREAD

**Issue by jordanthornquest** [jekyll/jekyll#3437]
Hey, folks! The article "Using Jekyll’s Data Files to build a dynamic navbar" is currently hitting a 404 error. It should be leading to `http://www.jordanthornquest.com/blog/building-dynamic-navbars-with-jekyll/`. Sorry for the inconvenience.

**Comment by parkr** [comment]
Would you please send a pull request? We're checking with HTML Proofer and CircleCI and this hasn't been throwing up anything so maybe it's still a 200 but has a redirect?

**Comment by jordanthornquest** [comment]
You got it. [Here's the PR](https://github.com/jekyll/jekyll/pull/3438).
