### ISSUE TITLE
site_template: use ids instead of classes

### ISSUE THREAD

**Issue by tkrotoff** [jekyll/jekyll#3439]
Currently the following are classes instead of ids:
- site-header
  - site-title
  - site-nav
    - menu-icon
- page-content
  - home
    - page-heading
    - post-list
    - rss-subscribe
- site-footer
  - footer-heading
  - footer-content

**Comment by kleinfreund** [comment]
What's the benefit of ID's over classes in your opinion?

**Comment by parkr** [comment]
We'll continue to use classes. ID's are strongly advised against.

**Comment by tkrotoff** [comment]
> benefit of ID's over classes

If there should be only 1 site-header/page-content/site-footer then it is semantically more correct to have them as id.
The benefit appears when using JavaScript: `getElementsByClassName()` returns an array vs `getElementById()` returns directly the DOM element (or null).

**Comment by kleinfreund** [comment]
However, the strict use of ID's can't be ensured. No one prevents you from having multiple _working_ ID's (just like classes, but with higher specificity) in your HTML. The higher specificity is also pretty strong argument against the use of ID's in my opinion. Maintaining HTML classes is easier.
