### ISSUE TITLE
Page shifts position slightly when navigating from page to page

### ISSUE THREAD

**Issue by mariobox** [jekyll/jekyll#3441]
I've noticed this problem in several of the example sites in Jekyll's website. I have a site hosted in Github Pages, and when you click from page to page, let's say from the index to the about page, the page seems to move a few pixels to the left or to the right, depending on which page you're at. This happens while viewing the site on a laptop or desktop (does not happen in mobile devices). It's a minor annoyance, but I wonder if anybody else have had this issue and how they solved it.  My site is at mariobox.github.io

Thanks,
Mario

**Comment by kleinfreund** [comment]
Scrollbars. To absolutely get rid of this behavior, add `html { overflow-y: scroll; }` to your CSS. This will render a scrollbar on all pages while being a bit _greyed out_ on pages which don't actually need one.

**Comment by mariobox** [comment]
Thanks buddy! Working like a charm now. Appreciate it!

**Comment by parkr** [comment]
Is this the site template? Or was this a site of your own?

**Comment by mariobox** [comment]
It is my site, based on the Jekyll-Now template.
