### ISSUE TITLE
possible bug in post.excerpt

### ISSUE THREAD

**Issue by gntech** [jekyll/jekyll#3442]
Shouldnt the statement post.excerpt == post.content evaluate to true if no excerpt_separator is present in the post? I tried to use that as a check to see if should include a read more link. It works sometimes but not always.

**Comment by kleinfreund** [comment]
If `excerpt_ceparator` is neither present in the post nor the _config.yml, it defaults to `\n\n`. So unless you only have a one-line post or no double line-breaks, the condition won't return true.

**Comment by parkr** [comment]
If the excerpt separator isn't in the content, the excerpt is empty.
