### ISSUE TITLE
Browser support for the site template

### ISSUE THREAD

**Issue by kleinfreund** [jekyll/jekyll#3444]
It’s about time. We need a statement about what browsers we want to support with the new site template.

As @jglovier said, targeting modern browsers would suite our needs for Jekyll already and I think so, too.

I propose something along the lines of the __last two browser versions__. I’m explicitly not mentioning IE9 here, because it has an even lower userbase as IE8 and we really don’t want to deal with that anymore.

**Comment by parkr** [comment]
Once we have the site template working with IE 10 and latest Safari, Chrome, Opera, and Firefox, I'm going to freeze the site template code and stop accepting PR's to change it. If the browsers move forward in breaking ways, we'll fix it. But unless something is really truly broken, the site template will not be up for edits or pull requests.
