### ISSUE TITLE
Stick with an external site template

### ISSUE THREAD

**Issue by penibelst** [jekyll/jekyll#3445]
One year ago in #1856 I proposed to stick with an easy to maintain and well documented site template. It was the [HTML5 Boilerplate](http://html5boilerplate.com/). My main motivation was to *reduce the non Jekyll related noise* in this repository. I quote myself:

> My motivation for H5BP is the fact it’s the tiniest scaffold out there. The project is active and has many great people as core members. We can take it as the truth and make the default template by stupidly copy and paste the H5BP. [Otherwise] It will end up in endless discussion about not Jekyll related things, like colors and fonts.

Let’s take a look what happened regarding the default site template in the *last 3 weeks*.

Issue | Conversation
| ------- | -----:
#3444 | 0
#3440 | 2
#3404 | 13
#3402 | 0
#3382 | 18
#3361 | 17
#3359 | 0
#3379 | 6
#3376 | 8
#3375 | 2
#3360 | 2
#3331 | 2
#3329 | 6

This is a lot. While @parkr and a small core team work on Jekyll’s features, other guys spend their time on fonts and colors. It’s a pure distraction.

I propose to rethink the importance of the default site template. There are some ready to use frameworks: H5BP, Zurb Foundation, Bootstrap, … Why not **stick with one of those without any change**? This step would help to focus on important things.

Jekyll is a static site generator in Ruby. It’s not opinionated about graphic design.

**Comment by parkr** [comment]
> I propose to rethink the importance of the default site template.

The idea is to make it stupid simple to get started with Jekyll. `jekyll new my-new-site`. It teaches by example the way Jekyll works.

> There are some ready to use frameworks: H5BP, Zurb Foundation, Bootstrap, … Why not stick with one of those without any change?

I really don't like any of those sample sites – they're bloated and very generalist. They're also not Jekyll sites AFAIK. Ideally, our site would be super basic HTML and minimal CSS. The current design is fantastic and pretty minimalistic for what it is, but it's not perfect.

I suppose one solution is to reject all future changes to the site template and enforce it being "frozen." That would be the end of the discussion: "We're not accepting any changes to the site template."

**Comment by alfredxing** [comment]
I agree with @penibelst about the distraction. Why don't we move the site template into a separate repository/plugin? `jekyll new` is a separate command already.

I'll even suggest doing the same for the docs site, though there seems to be much less chatter about that.

**Comment by parkr** [comment]
I wouldn't move it into a different repo – I want to find a "done" place and end the discussions about it, not just move them.

**Comment by nternetinspired** [comment]
> One year ago in #1856 I proposed to stick with an easy to maintain and well documented site template. It was the HTML5 Boilerplate. My main motivation was to reduce the non Jekyll related noise in this repository.

:100:  

html5BP is lean, mean and unquestionably good. This would be a great move IMHO.

> This is a lot. While @parkr and a small core team work on Jekyll’s features, other guys spend their time on fonts and colors. It’s a pure distraction.

Personally, as a front-ender, this is what I can do to contribute. I can't contribute to core features. I'd love to, but I don't Ruby; I Sass, I CSS, I html. I try to contribute in the areas in which I can, my apologies if this is viewed as noise.

**Comment by sondr3** [comment]
[Pure](https://github.com/yahoo/pure) is pretty small compared to Foundation/Bootstrap, might be something to consider using alongside H5BP since you find the others more on the bloated side.

**Comment by parkr** [comment]
> Personally, as a front-ender, this is what I can do to contribute. I can't contribute to core features. I'd love to, but I don't Ruby; I Sass, I CSS, I html. I try to contribute in the areas in which I can, my apologies if this is viewed as noise.

@nternetinspired I bet you could learn to Ruby no problem. I appreciate your contributions! It's just about focusing our efforts on Jekyll core so we can get 3.0 out the door.

**Comment by penibelst** [comment]
@nternetinspired What you can contribute is as same important as back-end coding. But maybe this core repository can’t keep up with your front-end skills? Look at the popular theme authors like @mmistakes. For many newbies his themes are the first to fork, before they even see the default site template. So @mmistakes works on Jekyll too, but in his own repositories.

> I wouldn't move it into a different repo – I want to find a "done" place and end the discussions about it, not just move them.

@parkr I can feel it.
