### ISSUE TITLE
Installing Jekyll Error on Yosemite Mac

### ISSUE THREAD

**Issue by JasonNewton1** [jekyll/jekyll#3447]
Hi there,

I cannot install the necessary gem even after installing xcode on Yosemite, using the command line tool.
Here is the error:

MacBook-Air:~ jasonnewton$ gem install jekyll
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Users/jasonnewton/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/redcarpet-3.2.2/COPYING
MacBook-Air:~ jasonnewton$ 

Can anyone help me?

Kind Regards

**Comment by JasonNewton1** [comment]
Okay, I'm a bit further along now. I think it is now installed.
When I list the gems, I get this:
*** LOCAL GEMS ***

addressable (2.3.2)
bigdecimal (1.1.0)
bundler (1.2.3)
chunky_png (1.2.5)
classifier (1.3.3)
classifier-reborn (2.0.3)
colorator (0.1)
compass (0.12.2)
directory_watcher (1.4.1)
excon (0.16.10)
fast-stemmer (1.0.1)
fssm (0.2.9)
haml (3.1.7)
heroku (2.35.0)
heroku-api (0.3.7)
io-console (0.3)
jekyll (0.12.0)
json (1.5.4)
kramdown (1.5.0, 0.13.8)
launchy (2.2.0, 2.1.2)
liquid (2.6.2, 2.5.5, 2.3.0)
maruku (0.6.1)
mercenary (0.3.5)
mime-types (1.20.1)
minitest (2.5.1)
multi_json (1.8.2)
netrc (0.7.7)
posix-spawn (0.3.6)
promise (0.3.0)
pygments.rb (0.6.0, 0.3.4)
rack (1.5.2, 1.4.1)
rack-protection (1.5.1, 1.3.2)
rake (0.9.2.2)
rb-fsevent (0.9.4, 0.9.1)
rdiscount (1.6.8)
rdoc (3.9.4)
RedCloth (4.2.9)
rest-client (1.6.7)
rubygems-update (2.4.5)
rubypants (0.2.0)
rubyzip (0.9.9)
safe_yaml (1.0.4)
sass (3.1.20)
simple_oauth (0.2.0)
sinatra (1.4.4, 1.3.3)
stringex (1.4.0)
syntax (1.0.0)
thor (0.18.1)
tilt (1.4.1, 1.3.3)
tumblr-rb (2.1.1)
weary (1.1.3)
yajl-ruby (1.1.0)
MacBook-Air:~ jasonnewton$ 

However, when I run this:    jekyll new ~/jekyll-sites/blog 
It tells me the this:
WARNING: Could not read configuration. Using defaults (and options).
	No such file or directory - new/_config.yml
/Users/jasonnewton/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:20:in `expand_path': user jekyll-sites doesn't exist (ArgumentError)
	from /Users/jasonnewton/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:20:in `initialize'
	from /Users/jasonnewton/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/bin/jekyll:238:in `new'
	from /Users/jasonnewton/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-0.12.0/bin/jekyll:238:in `<top (required)>'
	from /Users/jasonnewton/.rbenv/versions/1.9.3-p0/bin/jekyll:23:in `load'
	from /Users/jasonnewton/.rbenv/versions/1.9.3-p0/bin/jekyll:23:in `<main>'

As a novice, this is hardly inspiring as a way of setting up a blog. If anyone can help, I'd appreciate it.

Regards

**Comment by JasonNewton1** [comment]
Okay, when I type the command:  jekyll build, I see more problems.

I have trouble when listing the folder structure.

Here is the error message https://www.dropbox.com/s/xr78vbz769aygaj/Screenshot%202015-02-12%2013.10.20.png?dl=0

Here is my folder structure https://www.dropbox.com/s/h5veict5wmtekoz/Screenshot%202015-02-12%2013.11.25.png?dl=0

When I run the gem list, I can see that Jekyll is installed https://www.dropbox.com/s/ygos5mz4ankm8sh/Screenshot%202015-02-12%2013.13.23.png?dl=0

Can anyone help me at all?

Regards

**Comment by kleinfreund** [comment]
> jekyll (0.12.0)

You have a super old version of Jekyll. Can you do `gem update` followed by `gem cleanup`, please?

**Comment by JasonNewton1** [comment]
Okay, just one moment.

**Comment by JasonNewton1** [comment]
Okay, this is what happened.
https://www.dropbox.com/s/0hpa1zoy38r0zgs/Screenshot%202015-02-12%2015.55.26.png?dl=0

**Comment by JasonNewton1** [comment]
Shall I still now run gem cleanup?

**Comment by kleinfreund** [comment]
Okay, then run `gem update jekyll` first, please.

**Comment by JasonNewton1** [comment]
Okay, please wait one moment.

**Comment by JasonNewton1** [comment]
Still same problem.

https://www.dropbox.com/s/iiz7swh0zgryw5n/Screenshot%202015-02-12%2016.06.11.png?dl=0

**Comment by kleinfreund** [comment]
I need to pass here. This might go away by using `sudo gem update`, but I think one should be able to install Jekyll/Ruby gems in general without root.

**Comment by alfredxing** [comment]
Hmm, seems to be a permissions error. How did you install rbenv?

**Comment by JasonNewton1** [comment]
I cannot even remember if I did that or not. So confused now.
Is there a way to check?

**Comment by JasonNewton1** [comment]
Can I uninstall rbenv and then reinstall it?

**Comment by JasonNewton1** [comment]
It may have been homebrew. The problem for a beginner like me is that there are all these website tutorials offering different ways to achieve the same thing but they never tell you how to undo things when you run into problems.
Hoping someone can help me out. I may need to start from scratch.

**Comment by kleinfreund** [comment]
I've worked with [this](http://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/) about half a year ago and didn't have trouble with it. I don't know whether it was carefully updated since then.

**Comment by JasonNewton1** [comment]
Okay, I installed Homebrew using the tutorial above but it seems I have a few warnings.
Can anyone tell me how to moved things?

https://www.dropbox.com/s/hflqse9x7nsx0oo/Screenshot%202015-02-12%2016.54.38.png?dl=0

**Comment by kleinfreund** [comment]
Phew, not so sure about these warnings. Maybe you leave them for now, since they're only warnings.

I forgot to mention this until now, but for these kinds of issues, we have a dedicated repository: https://github.com/jekyll/jekyll-help

Open your issue over there the next time, if it's not a bug with Jekyll itself.

**Comment by JasonNewton1** [comment]
Okay, thanks. I've opened the issue in the dedicated repository.
