### ISSUE TITLE
Reference link id doesn't render when it contains ä

### ISSUE THREAD

**Issue by davidsilvasmith** [jekyll/jekyll#3448]
I ran into an issue where reference links didn't render when the link id contained ä

Markdown showing the issue:

    [Risto Pietilä]: https://twitter.com/ristopietila
    [Risto Pietila]: https://twitter.com/ristopietila
    [Risto Pietilä] - does not render as an a tag.
    [Risto Pietilä][Risto] - renders as an a tag

**Comment by parkr** [comment]
This is an issue with your markdown parser (kramdown, maruku, redcarpet, rdiscount, etc), not with Jekyll itself.

**Comment by davidsilvasmith** [comment]
Thanks, I submitted it [there](https://github.com/gettalong/kramdown/issues/221)
