### ISSUE TITLE
Using double quotes as first character in a title

### ISSUE THREAD

**Issue by lpellegr** [jekyll/jekyll#3449]
I would like to create a post whose the title is for instance `"Unfortunately, Launcher has stopped" on Android`. If I use this title that contains the double quotes as first character, when I try to generate the site I get the following error: 

```
Error reading file /path/to/my/post.markdown: (<unknown>): did not find expected key while parsing a block mapping
```

My second attempt was to escape the double quotes. In that case, the generation succeeds but the double quotes characters are displayed along with the backslash character.

The issue occurs only when " is used as first character in a title. 

Is there a mean to achieve my purpose? is it a bug?

I use jekyll 3.0.0-beta1.

**Comment by kleinfreund** [comment]
Does `title: '"Unfortunately, Launcher has stopped" on Android'` work?

If you want to go full-nerdy here, you might use typographically correct quote characters like this:

    title: “Unfortunately, Launcher has stopped” on Android

**Comment by lpellegr** [comment]
Wrapping the title with single quotation marks works. Thanks!
