### ISSUE TITLE
3.0.0-beta1- Liquid syntax error: Expected id but found string in...

### ISSUE THREAD

**Issue by phillipadsmith** [jekyll/jekyll#3454]
While testing `master` (3.0.0-beta1) for ticket #3451, I got this output:

```
  Liquid Exception: Liquid syntax error: Expected id but found string in "{{ page.slug | 'front' }}" in _layouts/default.html
```

This is the line in the template:
https://github.com/TheTyee/bottom-lines/blob/master/_layouts/default.html#L7

This isn't an issue for 2.4.0 and skimming through the changelog I can't see an obvious change that be causing this.

Non-urgent, obviously, as this was just while testing 3.0.0-beta1.

**Comment by parkr** [comment]
This is Liquid's strict parser. It's meant to catch Liquid errors, like this one. `'front'` isn't a valid filter, so it balks and tells you to fix it.

What is the expected behaviour?

**Comment by phillipadsmith** [comment]
Doh, you're right, that has never worked! My bad. :(

**Comment by parkr** [comment]
No problem! I'm glad Jekyll 3 caught it for you. :)
