### ISSUE TITLE
Direct link to @jekyllrb Twitter account on help page.

### ISSUE THREAD

**Issue by MartinRogalla** [jekyll/jekyll#3465]
Hello,

I would like to get started on contributing to the Jekyll Project. I realize this is a small issue, but I would like to start small:
On the Jekyll help page it mentions the @jekyllrb Twitter account, but it links to Twitter in general. I would propose to directly link it to the @jekyllrb Twitter account itself.

--
Martin Rogalla

**Comment by kleinfreund** [comment]
Welp, these things happen. Of course it should link to the actual account. :+1:

**Comment by alfredxing** [comment]
Nice catch, thanks!
