### ISSUE TITLE
Pagination doesn't generate page directories when permalink is set

### ISSUE THREAD

**Issue by gabelevi** [jekyll/jekyll#3471]
This tripped me up for 30 mins or so. I was trying to paginate `/blog/index.html`, but I had `permalink: /blog` set (I'm a n00b and I don't know what I'm doing). I did have `paginate_path` set correctly. The result was that visiting `/blog` would always start on the last page of pagination and be unable to find the other pages. None of the `/blog/pageN/`directories were generated.

In retrospect I can kind of understand what's going on. I suppose jekyll wanted to write `_site/blog/page2/index.html`, but `permalink` overrode it to write `_site/blog/index.html`, so each page was written to the same file. Perhaps an error when you keep overwriting the same file would help n00bs like me!

**Comment by parkr** [comment]
Can you file this on the jekyll-paginate repo, please? Yes, it's a bug. Thanks!
