### ISSUE TITLE
strip yaml front matter in includes

### ISSUE THREAD

**Issue by greenify** [jekyll/jekyll#3476]
Hi,

I am fighting a bit with the `include` tags. Consider this example where I want to embed page B in page A.

`B.md`
```
---
layout: default 
title: B
---
A fancy text with some liquid tags like {{ site.baseurl }}.
```

So when I now include page B into another page, the YAML front matter is rendered to the final HTML.

`A.md`
```
{% include_relative B %}
```

Another solution to this would be a special filter that strips the YAML front matter.
I would be happy to submit a PR if you agree that this is a bug.

Cheers,
Seb

PS: I know that there are [custom plugins](http://dtsn.me/2013/07/11/remove-front-matter-jekyll-plugin/) out there that remove the front matter, but I think this should be part of the normal include behavior.

**Comment by parkr** [comment]
`include_relative` should never include a document with yaml front matter. If it has front matter, it's a page, post, or collection document. If it doesn't, it's an include.

> Consider this example where I want to embed page B in page A.

As I've said before, you should never embed pages within other pages. If pages relate to each other, they're collection documents.

**Comment by aug-riedinger** [comment]
:+1: to allow Front Matter on includes pages.

**Comment by envygeeks** [comment]
This ticket is being locked. If you have an issue (or feature request) please file a new ticket instead of practicing the art of necromancy. It has hard to maintain actual issues against comments if this happens.
