### ISSUE TITLE
Add HTTP header Content-Security-Policy during development with jekyll serve?

### ISSUE THREAD

**Issue by smuda** [jekyll/jekyll#3478]
Is it possible to get "jekyll serve" to include a HTTP header somehow? 

In particular, it would be a good thing to be able to add Content-Security-Policy as that tend to break things and it would be a Good Thing to notice that as early as possible.

**Comment by parkr** [comment]
Do you know if WEBrick supports this header?

**Comment by smuda** [comment]
I don't know anything about WEBrick, but google is my friend :-). It seems one adds headers like this under rails 4 with WEBrick:
config.action_dispatch.default_headers.merge!({
  'Access-Control-Allow-Origin' => '*',
  'Access-Control-Request-Method' => '*'
})
https://stackoverflow.com/questions/2535454/how-to-set-access-control-allow-origin-in-webrick-under-rails
http://edgeguides.rubyonrails.org/security.html#default-headers

And in serve.rb:70 it seems you set a header (but not a default header) so I suppose WEBrick itself supports any header.

**Comment by parkr** [comment]
I'd be happy to look at a PR!

**Comment by envygeeks** [comment]
Is there any unobvious reason why this should be added to a dev environment? Unless you are serving your Jekyll site in production with WEBrick and Jekyll (which I think kinda defeats the purpose of Jekyll?) Your assets should be coming from the same origin in development no? Otherwise I don't understand how you update assets and if I remember right all browsers default to same origin.

**Comment by smuda** [comment]
Browsers default to wide open. You can verify that by adding "style" to a html element, which works nicely, which it wouldn't if default-src was set to 'self'.

The thing is that I want to tighten the CSP to for example 'self' and test the website without going to the production website. Sure, I can install IIS or Apache locally to serve the site, which is what I did to preserve time for this release, but there will be more releases.

**Comment by envygeeks** [comment]
Looser same origin policies doesn't mean it's not same origin.  If there weren't same origin restrictions then attacks would be much easier.  That said, I am absolutely against us adding anything CSP related directly (if that is even implied) I think it would be better for us to accept a Jekyll option for advanced users that allow them to adjust headers as they see fit.

**Comment by smuda** [comment]
looser? Aren't we polite in the OSS world. I understand that you're talking about same-origin policy, while I'm talking about Content-Security-Policy. That's different.

I agree an option to add arbitrary HTTP headers is the best solution, as there are and probably will be even more security related headers in the future.

**Comment by envygeeks** [comment]
CORS, CSP and all the other header based content security models are about extending the origin policies of same-origin past that of the defaults.  Just because Wikipedia does not mention CSP does not mean it is not extending same-origin policies in applications like Firefox and Chrom(e|ium) but this whole argument is not even relevant.

With that said, I was not rude in any way, just because I did not accept your solution and stood firm does not mean I was being rude.  If you are somehow implying the word "looser" was somehow rude I do not even know hot to address that logic.

I am :+1: on allowing user configurable headers but I am still definitely :-1: on default CSP.

**Comment by trevor** [comment]
:+1: for configurable headers in local development.

This would help with errors such as:

<blockquote>
Font from origin 'http://dev.local:4000' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dev.local:5000' is therefore not allowed access.
</blockquote>

Perhaps some syntax like this in _config.yml:

```yaml
webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD
```

**Comment by trevor** [comment]
This worked for me:

https://github.com/trevor/jekyll/blob/c4cf83d9ba26aac604223f430b05bfdf8837296a/lib/jekyll/commands/serve.rb#L99-L105

```ruby
if config['webserver_headers']
  opts.merge!({
    :RequestCallback => Proc.new do |req, res|
      config['webserver_headers'].each {|k,v| res[k] = v }
    end
  })
end
```

example headers added to `_config.yml`:
```yaml
webserver_headers:
  "Access-Control-Allow-Origin": "*"
  "Server": "CustomServerName"
```

**Comment by envygeeks** [comment]
I actually have something in the works that rewrites the entire serve page using a custom handler that sub's FileHandler and allows for this and SSL.  I already have part of the pull open but the rest is still pending and something like this is included in that already.

**Comment by envygeeks** [comment]
This issue is resolved with #4224.

**Comment by ibc** [comment]
@envygeeks said:

> Unless you are serving your Jekyll site in production with WEBrick and Jekyll (which I think kinda defeats the purpose of Jekyll?) Your assets should be coming from the same origin in development no? 

No. You may want to test a 3rd party widget within your development site.

**Comment by ChrisBup** [comment]
Forgive me, I'm getting this error:
```
Access to Font at 'http://localhost:4000/assets/fonts/din-light-webfont.woff' from origin 'http://127.0.0.1:4000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:4000' is therefore not allowed access.
```
with a Jekyll site but I'm still unclear on how to exactly to resolve it. I tried adding this to my _config.yml:
```
webserver_headers:
  "Access-Control-Allow-Origin": "*"
  "Server": "CustomServerName"
```
as well as this:
```
webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD
```
But neither worked. I'm a newbie. Can someone help?

**Comment by trevor** [comment]
@ChrisBup Try this:

```
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
```

**Comment by ChrisBup** [comment]
Thanks @trevor, that worked!

**Comment by exequeryphil** [comment]
Hm. @trevor's answer is working for me.  Is there a clear way to do this with WEBrick?

**Comment by laukstein** [comment]
@parkr @trevor Github Pages doesn't support Webrick https://github.com/github/pages-gem/issues/415 . Is there any workaround for it (except specifying in HTML `<meta>` tags) or needed open Jekyll task for it?
