### ISSUE TITLE
February 2015 Townhall

### ISSUE THREAD

**Issue by troyswanson** [jekyll/jekyll#3482]
Let's keep this thing going. I'm free this weekend.

/ref #2358 #3190

**Comment by parkr** [comment]
I'm free all of Sunday.

**Comment by troyswanson** [comment]
How about Sunday evening, around 10pm CST?

**Comment by alfredxing** [comment]
That works for me.

**Comment by parkr** [comment]
@jekyll/core

**Comment by troyswanson** [comment]
https://plus.google.com/events/c9c83g8g32ff72o54ktpn621kog

**Comment by troyswanson** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYe6u70Ez5mmmxRteOQPLLSfCBhSSnC-kYbDPvQelLSYDVa_SA

**Comment by troyswanson** [comment]
http://youtu.be/sRCXRkUVAag

**Comment by parkr** [comment]
Thanks, Troy!
