### ISSUE TITLE
TU Delft students on Jekyll

### ISSUE THREAD

**Issue by MartinRogalla** [jekyll/jekyll#3483]
Hello Jekyll Team,

Three other students(@joopaue, @mdenhoedt, @abouter) and I have been lurking on IRC, browsing your repository, viewing the Townhall Meetings and reading your personal blogs the past few days. We are Software Engineering students of the [TU Delft](http://en.wikipedia.org/wiki/Delft_University_of_Technology) and are following the [Software Architecture Course](http://avandeursen.com/2013/12/30/teaching-software-architecture-with-github/) by Arie van Deursen. The four of us will be writing a chapter for a book similar to the [The Architecture of Open Source Applications](http://aosabook.org/en/index.html) book describing the Sofware Architecture of Jekyll.

Apart from the chapter, we will also try to make useful contributions to the project via pull-requests such as the micro-contribution we made earlier this week(#3466). Additionally we will try to analyze some submitted issues, establish metrics and set up a plan of approach and try to resolve the issues. 

We think it is a great opportunity for us to learn from an active open source project and a great opportunity for Jekyll to receive some valuable feedback from new active members of the community.

We are extremely excited with this opportunity to give back to the Jekyll Community!

If you have any questions, feedback, comments or simply want to say hi, please don't hesitate to contact us.

Best Regards,

@martinrogalla, @joopaue, @mdenhoedt, @abouter

**Comment by troyswanson** [comment]
Sounds like a sweet project! Absolutely keep us posted. :tada:

**Comment by envygeeks** [comment]
Welcome! Glad you are using Jekyll.
