### ISSUE TITLE
call plugin hook after rendering a page or post

### ISSUE THREAD

**Issue by stevecrozz** [jekyll/jekyll#3487]
I'm working on an idea for a plugin to strip unused CSS out of a document, but in order to make it work, I need to have a full document available (so it can read the document's entire structure and related css). Is this something we could make possible with a new plugin hook? Or is it something I should just do separately outside of Jekyll? There are some useful things I could do if something like this were available as part of the plugin interface.

Specifically, it would be nice if I could receive a notification after a document is fully rendered, but before it's written to disk so my plugin could have the opportunity to transform it before it's written.

Thoughts?

**Comment by parkr** [comment]
Did you check out #3392?

**Comment by stevecrozz** [comment]
Thanks @prkr. This #3392 looks like exactly what I want. I'd be willing to help on this if you want. Let me know if you want to coordinate something.

**Comment by prkr** [comment]
@stevecrozz I think you tagged the wrong @parkr :)

**Comment by parkr** [comment]
@stevecrozz I have a checkbox there. Feel free to submit PR's to my PR! :)

@prkr :smile: :wave:
