### ISSUE TITLE
Add "Edit this Page" links to documentation

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#3495]
@benbalter has a couple cool pieces on his website:

![screen shot 2015-02-21 at 2 25 24 pm](https://cloud.githubusercontent.com/assets/237985/6316249/849c3020-b9d5-11e4-96bf-5be4440c111f.png)

and

![screen shot 2015-02-21 at 2 25 16 pm](https://cloud.githubusercontent.com/assets/237985/6316250/8674b4d0-b9d5-11e4-9e85-a9df85872b0c.png)

People reading his blog can go and suggest edits to his blog posts with one click. I'd love to have a feature like this on jekyllrb.com

**Comment by parkr** [comment]
@cobyism Where might you place this on the site? I was thinking add an `Edit this page &rarr;` to the top of each page excepting the index pages. Thoughts?

**Comment by MartinRogalla** [comment]
I saw Font Awesome is already being used. Perhaps you could use the [fa-pencil-square-o](http://fontawesome.io/icon/pencil-square-o/) icon?

**Comment by parkr** [comment]
@MartinRogalla Sure! I think words should accompany whatever symbol we use, though. Maybe below "Back" and "Next" we say "Edit this page" centered.

**Comment by MartinRogalla** [comment]
How does this look?
Do you prefer the icon to be light?
![image](https://cloud.githubusercontent.com/assets/1066157/6321062/88d4a89a-baf0-11e4-89e7-66c13f790b10.png)

or do you prefer the icon to be dark?
![image](https://cloud.githubusercontent.com/assets/1066157/6321069/c88b1a50-baf0-11e4-821d-4f9b5c2538ac.png)

Is the spacing of the button okay? I wanted the size to match the size of the two navigation buttons.

**Comment by parkr** [comment]
I'd rather not have it as a button, I think. What do you think about placing it outside the grey container and putting it below it?

**Comment by MartinRogalla** [comment]
Is this more what you're looking for? Is the spacing okay?

![image](https://cloud.githubusercontent.com/assets/1066157/6327478/b710832a-bb5c-11e4-8535-3bf3dc6ca600.png)

**Comment by benbalter** [comment]
FWIW, I like the latest version (text outside the container) the best. It's clear it's not part of the content and allows those just looking to browse the docs to do their thing.

That said, thoughts on making it a call to action, rather than a chore? E.g. "Improve this page" versus "edit this page"? Edit Makes me think it might be an administrative link and I'd need permissions or something, whereas improve sounds like it's something I can propose. Alternatively, "propose an improvement".

**Comment by troyswanson** [comment]
:+1: @benbalter 

I think the latest version is the best as well. I also like your idea on changing the microcopy. I'm a fan of short and sweet CTAs, so I like "Improve this page"

**Comment by parkr** [comment]
> "Improve this page" versus "edit this page"

:+1: to "Improve this page"

Also thinking maybe it should be at the top? Then it becomes very obvious and you don't have to hit the bottom of the page to know you can improve it.

**Comment by kleinfreund** [comment]
> Edit Makes me think it might be an administrative link […]

This one. I agree.

**Comment by MartinRogalla** [comment]
Sounds good, I'll make a version where it is on the top right saying "Improve this page".

**Comment by benbalter** [comment]
As a pro-tip, if the docs have CI (e.g, html proofer),  you'll need to [do some magic](https://github.com/benbalter/benbalter.github.com/blob/master/.travis.yml#L1-L4), to get pull requets not to break the build (because the edit link would be invalid), by either adding `proofer-ignore` to the link, or by making the link branch-specific. Either way, can be in a subsequent PR.

**Comment by MartinRogalla** [comment]
@benbalter thanks! I will take that into account.

**Comment by MartinRogalla** [comment]
![image](https://cloud.githubusercontent.com/assets/1066157/6351839/1cc9d33c-bc3f-11e4-918e-880e3564780f.png)

Do you like this spacing and position?

**Comment by kleinfreund** [comment]
It should visually be on the baseline with the heading, I think.

**Comment by mattr-** [comment]
So much :heart: for this idea.

**Comment by MartinRogalla** [comment]
I'm having troubles aligning it visually with the baseline of the heading. I am able to do it by changing the line-height and margin, but I don't think it will be aligned in all browsers. How is the following look?

![image](https://cloud.githubusercontent.com/assets/1066157/6356559/82c375ca-bc5e-11e4-92ca-faf910a90c92.png)

**Comment by kleinfreund** [comment]
That's too much importance on it. The text-only link is fine. How is the link currently placed on their? Can you open the dev tools, inspect the element and screenshot that?

**Comment by MartinRogalla** [comment]
![image](https://cloud.githubusercontent.com/assets/1066157/6358962/a87c7940-bc6f-11e4-9f0e-67c7930d3de7.png)

**Comment by kleinfreund** [comment]
That looks about right to me. Remember to remove the `border-radius` and change the padding declaration to `padding-top`, because that’s the only thin you assign.

**Comment by MartinRogalla** [comment]
Thank you! I filed a pull request here: #3510.
