### ISSUE TITLE
Doc link in template is pointing to homepage

### ISSUE THREAD

**Issue by JoopAue** [jekyll/jekyll#3501]
Hi everyone,

I am finding my way with Jekyll just as the rest of my team (#3483) and while setting up Jekyll and serving the Jekyll template I noticed the link to the Jekyll documentation is pointing to the homepage.

![image](https://cloud.githubusercontent.com/assets/6662540/6325149/f200c7a6-bb43-11e4-9eea-a96f4befff64.png)

I believe it should be pointed to http://jekyllrb.com/docs/home/ instead of http://jekyllrb.com/

Although this is a small issue, I have to start somewhere

Joop

**Comment by parkr** [comment]
Works for me, thanks!
