### ISSUE TITLE
Offline doc not working (a.k.a. issues with jekyll-docs)

### ISSUE THREAD

**Issue by jjarava** [jekyll/jekyll#3503]
Hi!

I've installed the offline docs as per the hints on http://jekyllrb.com/docs/usage/ but I haven't been able to get them to run.

I've created an issue in the jekyll-docs repo (https://github.com/jekyll/jekyll-docs/issues/2) but I've decided to create another one here to link back to it, in case other are having this kind of problem (and decide to search before opening an issue!)

Thanks for all the great work on Jekyll

https://github.com/jekyll/jekyll-docs/issues/2

**Comment by envygeeks** [comment]
You are right that this issue belongs there.

**Comment by jjarava** [comment]
I'm glad we agree; I just hope that someone will pick up the issue on the other side - which so far isn't happening.
