### ISSUE TITLE
How can I add an include on every single page by default?

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll#3505]
I have an include file that contains variables for callouts, notes, links, and other re-used components. On every page where I want those variables to be in scope, I have to add this: 

```
{% include_relative reuse/variables.html %}
```

If I forget to include this reference, the variables (such as `{{warning_note}}` simply don't appear in the content. This puts my doc at high risk for user error. 

How can I automatically include this `include_relative` tag on every page by default? If I put the include into the page.html layout, the include gets included too late -- the content is already rendered before it gets stuffed into the page layout. 

Is there any way that I can specify default content inside the `{{content}}` tag itself?

**Comment by parkr** [comment]
Hey, Tom! Why not use data files or collections for this shared info? Then it's just in `site` :)

**Comment by tomjohnson1492** [comment]
I'm not sure if I can use data and collections for this. With content in _data, I have to use YML syntax. The content I want to reuse looks like this:

Reusing a bootstrap style:

```
{% capture calloutdanger %}
<div class="bs-callout bs-callout-danger">
{% endcapture %}
```

Reusing a link that gets the page name: 

```
{% capture supported_features %}
{% for page in site.pages %}{% if page.permalink == '/supported_features/' %}<a href="{{ "/supported_features" | prepend: site.baseurl }}">{{page.title}}</a>{% break %}{% endif %}{% endfor %}
{% endcapture %}
```
Reusing a note: 

```
{% capture vimeo_note %}
{{alertinfo}}<b>Note:</b>The is a note about how to access the videos on vimeo ... {{end}}{% endcapture %}
```

The reuse must support HTML and Liquid content. I don't think YML allows that. 

Re collections, I'm not sure how collections could work here. I thought collections were another content type. Can you expand how I might do this reuse through collections?

BTW, here's my theme I'm working on: https://github.com/tomjohnson1492/jekyll-doc

**Comment by kleinfreund** [comment]
It might just work. I know that it does for HTML. Use that on my site for translations. However, it would be formatted in an ugly way.

**Comment by tomjohnson1492** [comment]
When I put `{%` characters into a YML file in _data, I get this error: 

```
Error: (/Users/tjohnson/projects/resolve/_data/options.yml): found character that cannot start any token while scanning for the next token at line 17 column 2
```

**Comment by mattr-** [comment]
You may need to escape them.

**Comment by tomjohnson1492** [comment]
As a follow-up to this thread, Parker is totally right -- use data files. The more I started using `for` loops, the slower the build took. Eventually it got to be around 20 seconds. Yesterday I switched everything into data files (without relying on any liquid tags for my re-use scenarios) and the build time is back to under 2 seconds. 

As far as I can tell, I cannot use any liquid or curly brace tags in the yml file. (I mean, technically I could but they aren't rendered at all.)

Here's a scenario I can't figure out. I want to manage my links in a links.yml file. I will have around 50 pages in the site, and I want to link to other pages frequently. Given that page names may change often, I want an easy way to manage the links indirectly. 

Here's my approach. In a links.yml file inside _data, I add this:

```
overview:
 title: Overview
 url: /overview/
```

To add a link on a page, I add this: 

```
<a href="{{ site.data.links.overview.url | prepend: site.baseurl }}">{{ site.data.links.overview.title }}</a>.
```
Then if the page name changes, I can just update the data file instead of finding every instance where I need to adjust "Overview" maybe to "Introduction".

However, this is really long and cumbersome for a link. How can I shorten this?

I could add a capture and reference it using an include, like this: 

```
{% capture overview %}<a href="{{ site.data.links.overview.url | prepend: site.baseurl }}">{{ site.data.links.overview.title }}</a>{% endcapture %}
```
Then refer to it on a page like this:

```
{% include captures.html %}
{{overview}}
```
But then I have to remember to always add the include, and all those includes add to the build time. Plus I now have the link defined in two places, which is just as cumbersome.

What I really want to do is somehow put this into a data file:

```
overview: "<a href="{{ overview.html | prepend: site.baseurl }}">Overview</a>"
```

But this doesn't work -- the `{{ }}` part doesn't get the logic of the site.baseurl inserted.

Here's another approach. I could use markdown links like this:

```
See [overview][1] for more info. 

[1]: {{site.baseurl}}{{site.data.links.overview.url}} "{{site.data.links.overview.title}}"
```

This is a little cleaner, because it keeps the link mess out of the way of the content Still bulky, but more manageable.

Given that I also need to support translation, separating out the link into a data file might be essential anyway. But it just feels dumb writing 100 characters for a link when it really should only take 25.

Am I going about this the right way? Any ideas for me on how to better manage links?

**Comment by dimitrisdervas** [comment]
I read this article "Hacking a Routing Component in Jekyll"
by Hugo Giraudel. It might give you an idea

http://www.sitepoint.com/hacking-routing-component-jekyll/

**Comment by tomjohnson1492** [comment]
Thanks for the follow-up and link. I decided that I was going about this the wrong way, so I put some re-use into data files and others into the _include directory. It's working well.

**Comment by parkr** [comment]
> It's working well.

:smiley:
