### ISSUE TITLE
How do I add an "Edit me" link on a page?

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll#3506]
How can I add an "Edit me" link on a page? WordPress has a feature where you can click a link on a page and directly edit that page. Maybe prose.io has something like this? 

I find it a little disconnected to try to edit my files. Suppose I have a table of contents with 50 files. Many authoring tools allow me to browse the navigation in a draft view and go directly to my files. But with Jekyll, I have a YML file listing all the pages in my navigation. I have to correlate the permalink in the YML file and hope that I named my file the same way. Then I look through my pages folder to find the file name I want to edit. 

It would be ideal to somehow browse and edit my files more easily on my local machine. Any tips for doing this?

**Comment by parkr** [comment]
Check out #3504! We just use the GitHub editor.

**Comment by tomjohnson1492** [comment]
Thanks. That is the feature I'm looking for. I assume that this feature is only do-able if you're hosting your Jekyll site on Github, right? The doc project I'm working on right now is behind a firewall only. I guess I could incorporate it using a private github repo, though.

**Comment by parkr** [comment]
You can test `jekyll.env` in your Liquid code. `development` and `production` are two possible values. Set by `JEKYLL_ENV` in your terminal environment (defaults to `development`). If your hosting has a means of setting JEKYLL_ENV, then you can use that to either generate the link or not.

In terms of opening your editor, there's nothing we can do about that :(
