### ISSUE TITLE
several tests still use .textile files

### ISSUE THREAD

**Issue by willnorris** [jekyll/jekyll#3507]
Textile functionality was removed in #3319, and many of the tests were switched over to markdown at that time.  However, there still exist a large number of textile files in [tests/source/_posts](https://github.com/jekyll/jekyll/tree/master/test/source/_posts).  This is technically not a problem with the current tests as written, but is becoming a problem with the work I'm doing for #3490, since that now relies on `output_ext` returning the correct extension.  Since the new [jekyll-textile-converter](https://github.com/jekyll/jekyll-textile-converter) plugin isn't present when running tests, `output_ext` doesn't return the expected value of ".html" for textile files, breaking various tests.  So we either need to include the textile plugin when running the tests, or switch the remaining textile files over to markdown.  I'll be following up with  PR that does the latter.  

(feel free to assign this issue to me, or just consider it as such)

**Comment by mattr-** [comment]
Then remove the tests as part of your work for #3490 and keep going. :smiley:

**Comment by willnorris** [comment]
actually, I opened this issue specifically because I *didn't* intend to include this in the work being done on #3490 :)  While this is related work, it's a self-contained enough chunk that I thought it would be easier to review separately.  Plus, since it's a continuation of @parkr's work from #3319, I wanted to open an issue for discussion before I did a lot of the work, in case there was a reason @parkr didn't do this as part of the previous PR.  That said, happy to just do the work first and let the discussion happen on the PR if that is more what @jekyll/core prefers.

**Comment by parkr** [comment]
At this point, those tests are more regression tests – ensuring we don't mistakenly break support for Textile. Think that's not a good idea? 

Thanks for the issue, Will :)

**Comment by willnorris** [comment]
> At this point, those tests are more regression tests – ensuring we don't mistakenly break support for Textile. Think that's not a good idea?

but since the tests are running without the textile plugin, I'm not sure that it's *actually* testing for regression of textile support.  I guess it may be testing to make sure that non-markdown in general are supported reasonably well?  Though that is certainly not all the tests I'm looking at... I know at least some of them are testing functionality that could just as easily be tested with markdown files.

I think we should definitely keep some regression tests around that ensure we support non-markdown files, but since textile has been moved out of core, I'm not sure that it's necessary to have regressions for that specifically.  Or if we do, we should actually load the textile plugin as part of tests (which I think would be fine)?

**Comment by willnorris** [comment]
I guess another question would be: is the textile plugin doing anything different than the markdown converter in the way that it interacts with jekyll?  Is there reason to believe that we could accidentally break textile support in a way that wouldn't be caught by the markdown tests?

**Comment by parkr** [comment]
> but since the tests are running without the textile plugin, I'm not sure that it's actually testing for regression of textile support.

My goodness, you're right. They aren't running with the plugin installed... How very strange. I guess it's not really testing anything then. :hankey: :cocktail:
