### ISSUE TITLE
Feature request: page generation on browser-request

### ISSUE THREAD

**Issue by kaatt** [jekyll/jekyll#3508]
Jekyll should have another option for serving, where pages are generated and served to the user when the user's browser requests them, just like WordPress and other dynamic CMS. This should only be for local previewing and not intended to be installed on a server. This is going to be super useful for previewing small changes in large projects which take minutes to generate.

In the current `jekyll serve`, (even incremental) regeneration takes minutes. I make a small change in the header file (which is included in all pages), the site takes minutes to regen. I'm not happy with the change and I make dozens of small changes until I'm satisfied. Minutes and minutes go by generating when I just want to preview a single page. This is even slower than Photoshop.

**Comment by kleinfreund** [comment]
> where pages are generated and served to the user when the user's browser requests them, just like WordPress and other dynamic CMS.

That is exactly the thing that Jekyll does not want to do. Jekyll is a _static_ site generator which is contrary to that request. If you need dynamic page creation you’re going to need another tool than Jekyll.

**Comment by budparr** [comment]
@kaatt - I've worked on some larger sites and have found ways to work around these issues. 

First off, there are faster static site generators (Hugo is lightening fast, metalsmith is very fast), but they don't have the community and some of the features or easy templating language as Jekyll. 

I tend to do a lot of my small, incremental type work in Chrome Dev Tools, then, when I'm satisfied, make the change on the site itself. 

I also use a subset of my content for development work, which saves quite a bit of time. 

Hope that's helpful. As @kleinfreund says, serving pages dynamically would go against the nature of the beast. But there's still a lot to gain for users, so in my view worth the extra steps to take for larger sites.

**Comment by kaatt** [comment]
> This should only be for local previewing and not intended to be installed on a server.

As I said, this feature should just be for the dev of the site and not for serving users. In production, the dev can do a full build and deploy.
Chrome Dev Tools works but you have to duplicate the content (html, css) and it can't use Liquid/SASS.
There's no easy way to convert a large Jekyll project to Hugo/metalsmith.

> I also use a subset of my content for development work, which saves quite a bit of time.
This is an annoying workaround that I've employed too.

@kleinfreund You won't even want to wait 10 seconds to preview a trivial change. My site has about 2000 html pages and takes 1-2 mins.

I don't think this is too hard to develop and no matter how slow Jekyll becomes in the future, single pages won't take much time.

**Comment by pathawks** [comment]
> I don't think this is too hard to develop

Pull request?

**Comment by kaatt** [comment]
@pathawks I know nothing about Ruby and Jekyll ;)

**Comment by mattr-** [comment]
As it stands right now, this is not something that we'll ever have Jekyll do. It's simply not architected this way.

**Comment by kaatt** [comment]
@m

**Comment by parkr** [comment]
The point of a static site engine is to have static content served by the server. JavaScript can be applied for dynamicity, but it defeats the purpose of Jekyll to dynamically generate on-request!
