### ISSUE TITLE
Occasionally failing CoffeeScript test

### ISSUE THREAD

**Issue by alfredxing** [jekyll/jekyll#3512]
Seems like something in CoffeeScript changed recently (it's started to underscore local variables).
I've seen this a couple of times in Travis CI, but here's a seed that you can run to try and reproduce it (this was fresh off the master branch):

```diff

# Running tests with run options --seed 46670:

.F..

Finished tests in 1.025797s, 3.8994 tests/s, 1.9497 assertions/s.

Failure:
TestCoffeeScript#test_: converting CoffeeScript should produce JS.  [test/test_coffeescript.rb:44]
Minitest::Assertion: --- expected
+++ actual
@@ -9,13 +9,13 @@
       return square(x) * x;
     };
     cubes = (function() {
-      var i, len, results;
-      results = [];
-      for (i = 0, len = list.length; i < len; i++) {
-        num = list[i];
-        results.push(math.cube(num));
+      var _i, _len, _results;
+      _results = [];
+      for (_i = 0, _len = list.length; _i < _len; _i++) {
+        num = list[_i];
+        _results.push(math.cube(num));
       }
-      return results;
+      return _results;
     })();
     if (typeof elvis !== \"undefined\" && elvis !== null) {
       return alert(\"I knew it!\");

4 tests, 2 assertions, 1 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/alfred/Documents/Git/alfredxing/jekyll/coverage. 1291 / 2064 LOC (62.55%) covered.
```

**Comment by alfredxing** [comment]
Hmm.. Actually this is quite weird. It only seems to be failing in my repo (alfredxing/jekyll), even after I ran `git pull upstream master` and `bundle install`...

**Comment by alfredxing** [comment]
Oh, nevermind. Ran `bundle update` and it works now, turns out my `coffee-script-source` gem was a bit oudated.

**Comment by willnorris** [comment]
I've been noticing the same error the last few days.  Deleting my Gemfile.lock file and rerunning `bundle install` *seems* to have been what fixed it.  No idea what changed between those file though :-\

**Comment by willnorris** [comment]
ah okay, I guess `bundle update` would have accomplished the same :)

**Comment by parkr** [comment]
This was caused by an update to CoffeeScript. It changed the output of the transpiled JS. I fixed it in https://github.com/jekyll/jekyll/pull/3492/files#diff-789a77c0b9de19dc9025f9e8699ab1ebL22
