### ISSUE TITLE
Verifying with Google Webmaster

### ISSUE THREAD

**Issue by surfer190** [jekyll/jekyll#3514]
Is there a recommended method of adding the html file given from webmaster tools to the `_site` directory or is it better/easier to place the `meta tag` in the head of the html of the `home page`.

Are there any `gems` for this, any suggestions thanks?

**Comment by kleinfreund** [comment]
I use the `meta` tag with a custom variable set in my _config.yml:

__\_config.yml:__

```yaml
google_verify: 2D5zbZ2Vatb8CeFj1cUCRdJZ3SQatSUlQesml02jEPo
```

__default.html (default layout):__

```liquid
{% if site.google_verify %}
    <meta name="google-site-verification" content="{{ site.google_verify }}">
{% endif %}
```

No reason to throw a gem or an extra file in there.

**Comment by pathawks** [comment]
Rather than include a `meta` tag on every page (and an extra Liquid if on every page), I just added the provided HTML file to the root of my Jekyll site as a static file, without any front-matter. This way it will be included in the built `_site`.

No gems necessary :)

**Comment by parkr** [comment]
:)

**Comment by surfer190** [comment]
@pathawks The cleanest solution, only problem is I am using jenkins to deploy...So it clears `_site` and regenerates it. :0

**Comment by kleinfreund** [comment]
You don’t put in `_site` yourself. You put it in the root of your uncompiled Jekyll site. Just the file. No front matter. Jekyll will copy the file as-is to `_site`.
