### ISSUE TITLE
error with "jekyll new my-awesome-site"

### ISSUE THREAD

**Issue by ianmartins** [jekyll/jekyll#3515]
It's taking some time to start finally learning about Jekyll doing something with it but after installing all the riquired items, ruby (1.9.3p484), rubygems (2.4.6), nodejs (0.10.25) and finally Jekyll (011.2), installed from sudo apt-get install jekyll.

So, let's start jekyll new my-awesome-site

```text
(trusty)ianyam@localhost:~/Documents/Blog$ jekyll new my-awesome-site
/usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require': iconv will be deprecated in the future, use String#encode instead.
WARNING: Could not read configuration. Using defaults (and options).
	No such file or directory - new/_config.yml
Building site: new -> my-awesome-site
/usr/lib/ruby/vendor_ruby/jekyll/site.rb:126:in `chdir': No such file or directory - /home/ianyam/Documents/Blog/new/ (Errno::ENOENT)
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:126:in `read_directories'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:98:in `read'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:38:in `process'
	from /usr/bin/jekyll:250:in `<main>'
```

I just cant figure out what it is, can anyone help me?
thank you for your time

**Comment by pathawks** [comment]
> Jekyll (011.2)

That version is *years* old.

Try installing a more recent version of Jekyll (2.5ish)

**Comment by ianmartins** [comment]
hello @pathawks , thanks for the advice, but thats what it get when try to install from "gem install jekyll":
(trusty)ianyam@localhost:~$ sudo gem install jekyll
[sudo] password for ianyam: 
ERROR:  Error installing jekyll:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /usr/lib/ruby/gems/1.9.1/cache/ffi-1.9.6.gem

**Comment by parkr** [comment]
That's super weird. Try `gem cleanup`.

**Comment by ianmartins** [comment]
Clean up complete

jekyll 2.5.3 now its the version!
You was awesome with this gem cleanup, @parkr thank you.
Just to make sure that it's all ok:

(trusty)ianyam@localhost:~/Documents/Blog$ jekyll new my-awesome-site
New jekyll site installed in /home/ianyam/Documents/Blog/my-awesome-site. 
(trusty)ianyam@localhost:~/Documents/Blog$ cd my-awesome-site
(trusty)ianyam@localhost:~/Documents/Blog/my-awesome-site$ jekyll serve

Server adress working.

Guys, thanks again. It's really cool the way the things are done here on github.
I'm runing jekyll on my xfce4 trusty from crouton thats its running on my chromebook, i'll sleep well tonight.

**Comment by parkr** [comment]
:+1:
