### ISSUE TITLE
Add talk.jekyllrb.com to the Help page

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#3517]
We have http://jekyllrb.com/help/ but we don't have a link to our new Discourse site on it yet.

**Comment by alfredxing** [comment]
PR opened! We should also write a blog post about it, just to elaborate a bit more.

**Comment by parkr** [comment]
Thanks! :)

Yeah, want to write that blog post? :)

**Comment by alfredxing** [comment]
@parkr Nah, you've written all of the ones so far, and we should probably keep the style the same.

**Comment by parkr** [comment]
> @parkr Nah, you've written all of the ones so far, and we should probably keep the style the same.

I don't want to write all of them! It was your idea :wink:

**Comment by alfredxing** [comment]
Sure, I'll try to get a PR in tomorrow. :sweat_smile:

**Comment by parkr** [comment]
You got this!!
