### ISSUE TITLE
using pagination more than once?

### ISSUE THREAD

**Issue by w1n78** [jekyll/jekyll#3519]
i'm already using the post pagination in my /index.html file. i'd like to also use it in my /blog/index.html file. but when i try to use the code again, that area is empty. here's the code i'm using in both places.

    {% for post in paginator.posts %}
      # display posts information
    {% endfor %}

am i only able to use pagination once per site?

**Comment by parkr** [comment]
it's not currently possible to paginate more than once – you can only paginate posts once. I was working on a solution but lost steam: https://github.com/jekyll/jekyll-paginate/pull/22

**Comment by w1n78** [comment]
ok thanks for the response
