### ISSUE TITLE
htmlproofer on Jekyllrb.

### ISSUE THREAD

**Issue by MartinRogalla** [jekyll/jekyll#3521]
I just ran htmlproofer on the generated jekyllrb site. We have a few 404's in there. Shall we remove those links or keep it like it is?

```
- ./site/_site/docs/history/index.html
  *  External link https://github.com/Chrononaut failed: 404 No error
  *  External link https://github.com/Chrononaut failed: 404 No error
  *  External link https://github.com/Chrononaut failed: 404 No error
  *  External link https://github.com/Chrononaut failed: 404 No error
  *  External link https://github.com/Chrononaut failed: 404 No error
- ./site/_site/docs/plugins/index.html
  *  External link http://picture.responsiveimages.org/ failed: 301 SSL connect error
- ./site/_site/news/index.html
  *  External link https://twitter.com/parkr/status/430826309707902976/photo/1 failed: 404 No error
```

**Comment by parkr** [comment]
Did you run `script/proof`?

**Comment by MartinRogalla** [comment]
No I ran `htmlproofer ./site/_site`(on the generated site) from the Jekyll root. The proofer found on http://jekyllrb.com/news/2014/06/04/jekyll-stickers-1-dollar-stickermule/ that the link https://twitter.com/parkr/status/430826309707902976/photo/1 returns a 404.
 and on http://jekyllrb.com/docs/history/ the mentions of `@Chrononaut` also link to a 404.

I don't know if these things matter, but I just wanted to point out that there are some links which link a 404. 

If I run `script/proof`, I only get the 301 SSL errror.

**Comment by parkr** [comment]
Script/proof is the way to do it. It has ignores such tat our content can be historically accurate where needed.

Ssl error for what?

**Comment by MartinRogalla** [comment]
```
- ./site/_site/docs/plugins/index.html
  *  External link http://picture.responsiveimages.org/ failed: 301 SSL connect error
```

Ah it's apparently redirecting right now from `http://picture.responsiveimages.org/` to `https://picture.responsiveimages.org/`.

**Comment by parkr** [comment]
Let's replace that link with `https://html.spec.whatwg.org/multipage/embedded-content.html#the-picture-element`.
