### ISSUE TITLE
Remove the "two lines of triple dashes" requirement to suport SASS

### ISSUE THREAD

**Issue by mauriciomelo** [jekyll/jekyll#3524]
This causes syntax error when running Jekyll with other tools that also compiles SASS.
Maybe a **comment** on top of the file can be a alternative.

http://jekyllrb.com/docs/assets/

**Comment by kleinfreund** [comment]
You only need the front matter when you want Jekyll to actually process the Sass. If you use another tool that does this, you should remove the front matter.

**Comment by parkr** [comment]
Best solution would be to have the other tools exclude Sass compilation. We've talked about this before. Dropping the dashes would make jekyll unacceptBly inconsistent in how it chooses to generate things.

I put only my imports on css/style.scss, then I proof all my partials in _sass to get around this requirement.

**Comment by keesvandieren** [comment]
The 'two lines of triple dashes' caused issues for us as well.

Another option to enable sass processing would be helpful for us as well.

For example, by adding a switch in _config.yml:

```
sass:
    enabled: true
```
