### ISSUE TITLE
Jekyll doctor looks in the site_template ?

### ISSUE THREAD

**Issue by mjankowski** [jekyll/jekyll#3525]
Running `jekyll doctor` in a project which has no blog posts present (I tried both with an empty _posts dir and with no _posts dir at all), yields the following error:

    jekyll 2.4.0 | Error:  Invalid date '0000-00-00': Post '/vendor/bundle/ruby/2.2.0/gems/jekyll-2.4.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the filename.

This appears to only occur on Linux, not on OSX.

My guess is that the lib/ directory is being added to a load path somewhere and thus the "welcome" post which probably shouldn't be analyzed as part of `jekyll doctor` is being included.

**Comment by parkr** [comment]
It may not mind the `exclude` directive.

**Comment by parkr** [comment]
(Make sure you have `exclude: [vendor]` in your config file and run again to test)

**Comment by mjankowski** [comment]
Adding the exclude vendor line does indeed solve this issue.

It still seems bizarre that a) this behaves differently on OSX vs Linux, b) a file that is not located in the local repo, but is coming from a gem, gets included in the `doctor` analysis.

**Comment by parkr** [comment]
> It still seems bizarre that a) this behaves differently on OSX vs Linux, b) a file that is not located in the local repo, but is coming from a gem, gets included in the doctor analysis.

Jekyll doesn't ignore any content in your directory that doesn't start with `_`, so if it's in `vendor`, it'll just try to consume it like it does everything else. If you're using `vendor` to bundle your gems or do whatever that isn't meant to end up on the site, add it to `exclude`. :)

**Comment by mjankowski** [comment]
There's no `vendor` directory in my project.  This is coming from somewhere within ruby gems, from within the jekyll gem itself.

**Comment by parkr** [comment]
Can you paste all the output of the failure?

**Comment by mjankowski** [comment]
Yeah, let me try to replicate on a fresh repo and show you.

The failure I saw was on Travis CI: https://travis-ci.org/thoughtbot/high_voltage/builds/52444716 - although the revision being run in that build is not available on GH anymore.

**Comment by mjankowski** [comment]
Ah, wait... I see now.

Travis itself is instructing bundler to install things into `vendor`, which is why it exists in the test environment, and not for me locally.

That's also why the `exclude vendor` line fixes the CI issue, even though the directory does not exist in the repo itself, or on my local test runs.

Changing my local `bundle install` to replicate what Travis does allows me to replicate this.

Consider this resolved!

**Comment by fulldecent** [comment]
This example shows a the required change. The prior build failed. This build passed:

https://github.com/fxlex/homepage/compare/700dc2af1962...c190827130c5
