### ISSUE TITLE
Is it possible to use markdown for my static pages, rather than html?

### ISSUE THREAD

**Issue by duanefields** [jekyll/jekyll#3526]
I was thinking if I created static content pages (outside of _posts) with a .markdown extension, it would get converted to HTML as part of the build, but it doesn't seem to. It seems like a reasonable thing - if I write all my posts in markdown, why wouldn't I want to write my static content (like say my "about" page) in markdown as well? Or am I missing something?

**Comment by parkr** [comment]
You must be forgetting the front matter. Your file, say `about.markdown`, should contain:

```
---
# front matter goes here
layout: page
title: About Me
---

Hey! My name is Duane.

![Image of me](https://github.com/duanefields.png)

I'm a software developer from ...
```

You need those 2 lines of triple dashes for it to be converted. These are called Pages.

**Comment by duanefields** [comment]
ha, geez, I had 2 dashes instead of 3 for some reason, and until I read the word triple I hadn't noticed!
