### ISSUE TITLE
What value can page.meta variable in the jekyll new post.html return?

### ISSUE THREAD

**Issue by kihonkai** [jekyll/jekyll#3536]
Hello, I'm still quite new to both Jekyll and Ruby so I'm sorry if I've missed something obvious.

I was trying to understand how I could modify the output of the `jekyll new` command.  I noticed the following line from the _layouts/post.html file:

```
<p class="post-meta">{{ page.date | date: "%b %-d, %Y" }}{% if page.author %} • {{ page.author }}{% endif %}{% if page.meta %} • {{ page.meta }}{% endif %}</p>
```
Specifically the part `page.meta` which I can't seem to find in the documentation or in other issues.  I found issue #3300 happens to contain this line but appears to be unrelated to my question.

The documentation pages [Variables](http://jekyllrb.com/docs/variables/) nor [Front Matter](http://jekyllrb.com/docs/frontmatter/) provide any details.  In fact, I tried a Google search of `site:http://jekyllrb.com/ "page.meta"` which returns no results.  I couldn't find anything on https://talk.jekyllrb.com/ either.

Finally I used the `jekyll new` command to create a fresh site and added the following to post.html:

```
<div>
  	page.meta: {{ page.meta }}
</div>
```

This returns no content.  Is this a mistake in that layout or can it return some kind of content that I've not found yet?

**Comment by kleinfreund** [comment]
You’re right. This looks like an unused bit of code. The pages of the default site template don’t have a custom variable called `meta`, so this condition is never true und never used. Probably at one point there where additional information provided via the pages’ front matter.

And for your question: No, there is no special `meta` variable every page or post has.

**Comment by jglovier** [comment]
Responded on https://github.com/jglovier/jekyll-new/commit/11fb96a268f12cfbe537b29de8107b44e007603d#commitcomment-9997043 as well, but the intention here was just to add support for a convention I commonly use where if you have any extra meta info added via the front-matter, it would be returned here.

e.g.:

```
---
layout: default
author: jglovier
meta: "Notes On Design Series"
---
```

**Comment by kihonkai** [comment]
Thanks for the replies.  It's good to get confirmation on why it's like that.  Rather than removing it maybe adding a post with an example use would be an idea.  Though I'm starting to see that there are many options when using Jekyll so no right or wrong way.

**Comment by jglovier** [comment]
>Though I'm starting to see that there are many options when using Jekyll so no right or wrong way.

Yeah, that was my intention - to illustrate that. Though you're right I def should have added a file to demonstrate it. I'll open a pull to correct! :bow: :sparkles: :zap:

**Comment by parkr** [comment]
> Though you're right I def should have added a file to demonstrate it. I'll open a pull to correct!

What kind of meta material?

**Comment by jglovier** [comment]
>What kind of meta material?

@parkr the "anykind" kind. :smile: For example the series name if the blog post is a post in a series, or a note if the post is an external link. Basically any type of meta info other than date, author, and category which are already supported by default.

If you think it's a usecase that isn't prevalent enough, I'm happy to :fire: it though. I don't really have strong opinions about it.

**Comment by parkr** [comment]
I think generic meta is what the front matter in general is for, not one item within it. I think I'd rather see it nixed, if only for greater simplicity and fewer questions for newbies. You cool with that?

**Comment by jglovier** [comment]
@parkr :+1:
