### ISSUE TITLE
Sort on nested values in collections not working

### ISSUE THREAD

**Issue by troyswanson** [jekyll/jekyll#3539]
Given a collection that has documents with a pattern that look something like:

```yaml
time:
  start: 2015-05-11 18:00:00 -8
  end: 2015-05-12 16:00:00 -8
```

And a layout that has something like this:

```html
<ul id="calendar">
  {% assign events = site.events | sort: 'time.start' %}
  {% for page in events %}
  <li class="event">
    <a href="{{ page.url }}">
      <span class="month">{{ page.time.start | date: "%B" }}</span>
      <span class="day">{{ page.time.start | date: "%-d" }}</span>
    </a>
  </li>
  {% endfor %}
</ul>
```

Jekyll just doesn't sort them using that nested value at all.

If I move the values out into top-level properties, like:

```yaml
date_start: 2015-05-11 18:00:00 -8
date_end: 2015-05-12 16:00:00 -8
```

And modify the layout to use:

```html
{% assign events = site.events | sort: 'date_start' %}
```

It works as expected.

**Comment by troyswanson** [comment]
Whoops, hit the wrong button and submitted this early on accident.

I am updating the original post right now.

**Comment by troyswanson** [comment]
OK, updated the top post. Sorry about that.

**Comment by parkr** [comment]
> Jekyll just doesn't sort them using that nested value at all.

You're right, it'd be good to support sorting based on sub-elements. Want to take a crack at a PR?

**Comment by troyswanson** [comment]
I'm on vacation so I've got some time to kill. I'll give it a shot, but make no promises.

**Comment by parkr** [comment]
Definitely a nice-to-have.

**Comment by wjdp** [comment]
+1

**Comment by Fresheyeball** [comment]
This is being addressed as a part of liquid currently https://github.com/Shopify/liquid/pull/604

**Comment by troyswanson** [comment]
@Fresheyeball Cool!
