### ISSUE TITLE
Support JEKYLL_DOCKER env variable so we can alter defaults without shivs.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3540]
With people asking about installing Gems in the Docker Jekyll image it might be useful to accept a `JEKYLL_DOCKER` env variable so that we can default the source path to `/srv/jekyll` and the listen address to `0.0.0.0` if we detect it, which will allow people to use `bundler` easier and will allow us to stop shiv-ing the current Jekyll bin file.

/cc @jekyll/core

**Comment by parkr** [comment]
> default the source path to /srv/jekyll

Isn't everything relative? Shouldn't this be taken care of with the `bin/jekyll` executable?

> listen address to 0.0.0.0

We might as well make this the default, no? As long as it doesn't change anything for current users (i.e. require sudo permissions or fail on Windows, etc)

**Comment by envygeeks** [comment]
> Isn't everything relative? Shouldn't this be taken care of with the bin/jekyll executable?

Actually that's quite right for the path, because we do put them into /srv/jekyll by default (as it is Jekyll's home) so that doesn't need to change... I didn't even think about that till you brought it up and I remembered that I put them in the spot we expect them to volume to by default.

> We might as well make this the default, no? As long as it doesn't change anything for current users (i.e. require sudo permissions or fail on Windows, etc)

We could, it's what Rails does now if I am not mistaken (I wouldn't know since we enforce `localhost` anyways but I don't know how people would take to that since some people don't know how to firewall and we might expose something they don't want exposed?  As far as failing on Windows, if that happens I assume that would be a WEBrick bug but I don't assume it should be a problem.

If we do default to 0.0.0.0 we should at minimum send a warning saying it's all up in the public?

**Comment by envygeeks** [comment]
See the pull for the reason for this close.
