### ISSUE TITLE
Site Setting make change without restar server

### ISSUE THREAD

**Issue by nivla** [jekyll/jekyll#3548]
There is a way that i can make a change in _config.yml without need to restar the server?

**Comment by parkr** [comment]
Not at the moment, nope! Open to it, but haven't found a good way to do it yet.

https://github.com/jekyll/jekyll/issues/2302, https://github.com/jekyll/jekyll/issues/3373, https://github.com/jekyll/jekyll/issues/681, https://github.com/jekyll/jekyll/issues/730

I recommend putting data that you might want to change in this way into a [data file](http://jekyllrb.com/docs/datafiles/) (things like a title, description, etc).

**Comment by nivla** [comment]
Ok. Thanks.
