### ISSUE TITLE
Remove rr gem

### ISSUE THREAD

**Issue by arthurnn** [jekyll/jekyll#3549]
RR is not supported anymore =(
https://github.com/rr/rr/commit/885885ca0cd426ea5c35fa3851abefe3d3a78428

I am trying to remove it from rubygems.org too, not sure if the best option is to use mocha. Anyhow, we probably should remove it from jekyll too.

**Comment by parkr** [comment]
@arthurnn The end of an era! We stub a little but I think it'd be relatively quick to fix.

**Comment by arthurnn** [comment]
You think mocha would be the replacement? or try to not stub at all? I will try to send a PR today.

**Comment by parkr** [comment]
> You think mocha would be the replacement? or try to not stub at all? I will try to send a PR today.

I'm fairly certain we only ever stub `Jekyll.configuration` – we have a way to do this already in `test/helper.rb` (methods like `site_configuration(overrides) :: Hash` and `fixture_site(overrides) :: Site`), so we should just remove rr and substitute in those methods where appropriate :)

**Comment by envygeeks** [comment]
We want to move to RSpec eventually anyways, why not just pick up `rspec-mocks` since it's independent? https://www.relishapp.com/rspec/rspec-mocks/v/3-0/docs/outside-rspec/integrate-with-minitest

**Comment by arthurnn** [comment]
@envygeeks cool.. will do the PR soon.

**Comment by parkr** [comment]
In the case of `stub(Jekyll).configuration`, I'd prefer not to stub/mock at all... just use `site_configuration` or `fixture_site` depending upon what you'd like to have (either a hash or a site).

**Comment by envygeeks** [comment]
@parkr @arthurnn if neither of you want to do this this weekend I'd be happy to do it this weekend and sort it out since I'll be in the tests anyways.  Just let me know! I'm not trying to be pushy or anything just trying to help out since I'll already be in there :100:

**Comment by parkr** [comment]
i'm cool with whoever! race to the first pr :wink:

**Comment by arthurnn** [comment]
:runner: almost done here =)
