### ISSUE TITLE
Unable to install with --pre under Ubuntu: Asks for Ruby >= 2.0.0 when it’s 2.2.0

### ISSUE THREAD

**Issue by kleinfreund** [jekyll/jekyll#3558]
Although I have Ruby 2.2 installed, the installation of Jekyll 3.0.0.beta is aborted due to the required ruby version being 2.0.0.

```bash
philipp@RAUMBASIS:~$ git --version
git version 2.3.2
philipp@RAUMBASIS:~$ sudo gem cleanup
[sudo] password for philipp: 
Cleaning up installed gems...
Clean Up Complete
philipp@RAUMBASIS:~$ sudo gem install jekyll --pre
Fetching: jekyll-3.0.0.pre.beta1.gem (100%)
ERROR:  Error installing jekyll:
	jekyll requires Ruby version >= 2.0.0.
philipp@RAUMBASIS:~$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
philipp@RAUMBASIS:~$ 
```

**Comment by envygeeks** [comment]
That's gotta be a bug in RubyGems?

**Comment by kleinfreund** [comment]
I try to update Ruby and RubyGems. After that I’ll try using a different Ruby version with rvm (i.e. 2.1.5).

**Comment by envygeeks** [comment]
This might either be an edge on your system (what do you use to manage your Ruby? I build mine into `/opt/ruby`) or an edge in RubyGems.  I just manually installed the gem on my system and it immediately let me remove it.

```
jordon@laptop:~/development/envygeeks/docker$ gem --version && ruby --version
2.4.6
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
```

**Comment by kleinfreund** [comment]
I updated Ruby via rvm from 2.2.0 to 2.2.1. Also did `sudo gem update --system` which installed `rubygems-2.4.6`. Issue is not resolved by that.

Next thing. `rvm install 2.1.5 && sudo gem install jekyll --pre`. Same thing.

**Comment by envygeeks** [comment]
What is the value of $GEM_HOME?

**Comment by kleinfreund** [comment]
```bash
philipp@RAUMBASIS:~$ echo $GEM_HOME
/home/philipp/.rvm/gems/ruby-2.2.1
```

**Comment by envygeeks** [comment]
For now since I don't know how this bug is existing lets just see if we can work around the edge:

```
find ${GEM_HOME} -type f -name jekyll.gemspec -exec sed -i 's/10 s/^/#//g' {} \; && gem uninstall jekyll
```

**Comment by kleinfreund** [comment]
```bash
philipp@RAUMBASIS:~$ find ${GEM_HOME} -type f -name jekyll.gemspec -exec sed -i 's/10 s/^/#//g' {} \; && gem uninstall jekyll
Remove executables:
	jekyll

in addition to the gem? [Yn]  y
Removing jekyll
Successfully uninstalled jekyll-2.5.3
philipp@RAUMBASIS:~$ sudo gem install jekyll --pre
[sudo] password for philipp: 
ERROR:  Error installing jekyll:
	jekyll requires Ruby version >= 2.0.0.
```

Got it running under OS X (same Ruby/RubyGems version) in the meantime without issues.

**Comment by envygeeks** [comment]
Perhaps @mpapis or @drbrain can provide some insight? Since both of their softwares are included.

**Comment by envygeeks** [comment]
Also @kleinfreund we provide a jekyll binary for Ubuntu now (with isolated Ruby and packages) in the meantime while I try to figure out how this is happening perhaps you can use that: https://github.com/jekyll/jekyll/releases/tag/v3.0.0.beta2

**Comment by mpapis** [comment]
drop the `sudo` and try: `gem install jekyll --pre` - when you run with `sudo` it goes to system ruby so you would need to check `sudo ruby -v` and `sudo gem -v`

**Comment by kleinfreund** [comment]
@mpapis Yikes, I always felt that this was not the right way to handle things, since installing Ruby Gems on OS X always worked without sudo. Best thing would be to reinstall the whole stuff without sudo, huh?

@envygeeks Thanks for you help, I’ll first try to get Ruby/RubyGems to work on Ubuntu without sudo as this seems to be the more logical approach. I’ll come back to the binaries later.

**Comment by kleinfreund** [comment]
Alright, it worked. What did I do?

- `rvm remove 2.2.1 && rvm remove 2.1.5` to remove the current rvm rubies I had
- `rvm install 2.2.1` to reinstall the latest Ruby version
- `gem install sass jekyll-sitemap jekyll-sass-converter jekyll` to install my default gems
- `gem install jekyll --pre` to install beta (which strangely is beta1, should it not be beta2?)
- `gem uninstall jekyll -v 2.5.3 && gem uninstall liquid -v 2.6.2` to remove conflicting gems

Thank you guys for your help :+1:

**Comment by envygeeks** [comment]
Closing this ticket now then. Glad it's fixed! Thanks @mpapis

**Comment by parkr** [comment]
It was the uses of `sudo`, yep glad you guys got this fixed!

**Comment by maximevaillancourt** [comment]
Same here. Thanks!
