### ISSUE TITLE
Liquid Error when using Pipes to limit output (Jekyll 3.0 beta 1 & 2)

### ISSUE THREAD

**Issue by kevingimbel** [jekyll/jekyll#3559]
With the beta 1 and beta 2 release I get the following error for Liquid 'filters', e.g. `{post in site.posts | limit: 3`. 
```
  Liquid Exception: Liquid syntax error: Expected end_of_string but found pipe in "post in site.posts | limit: 10" in _layouts/front-page.html
```
May or may not be related to #3557. I can confirm that limiting this way works with Jekyll  2.5.3 which I downgraded to. 

#### Additional information: 
Found while testing: #3557
OS: Ubuntu 14.04
Ruby: ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux]
Jekyll: 3.0.0beta2
File: https://github.com/kevingimbel/kevingimbel.github.io/blob/master/_layouts/front-page.html#L8

**Comment by kleinfreund** [comment]
Try it without the pipe:

```liquid
{% for post in site.posts limit: 10 %}
```

I’m using this filter with a for loop like this:

```liquid
{% for post in posts limit:site.max_posts %}
```

**Comment by parkr** [comment]
@kleinfreund is right! `for` loops have no pipes :)
