### ISSUE TITLE
Conditional exclude files that get generated

### ISSUE THREAD

**Issue by yoshyosh** [jekyll/jekyll#3561]
I have some pages that take a long time to generate. I want to include them in the exclude method of _config.yml while i'm working in development using --watch. When I'm ready to move the site to production I'd like for it to generate these files. Is there a better way than just commenting/uncommenting the exclude line? Like a plugin/script?

**Comment by yoshyosh** [comment]
Maybe multiple config files? https://github.com/jekyll/jekyll/issues/703

**Comment by willnorris** [comment]
yep, that's exactly what I was going to suggest.  There has also been discussion in #3173 of automatically reading specific config files based on a `JEKYLL_ENV` environment variable.

**Comment by yoshyosh** [comment]
Got it thanks :)
