### ISSUE TITLE
exclude + ends with wildcards?

### ISSUE THREAD

**Issue by yoshyosh** [jekyll/jekyll#3562]
I have a folder structure like jp/books, cn/books, br/books, etc. I would like to exclude anything with that folder ending like so
`exclude: ['*/books']`

Any tips?

**Comment by parkr** [comment]
When you tried that, did it work? We use `File.fnmatch?` under the hood so anything that works there will likely work with Jekyll

**Comment by yoshyosh** [comment]
Unfortunately no. Any ideas on how I can get some behavior like this? Every few weeks i'll be adding new countries. So i'll see more things like fr/books, sp/books

**Comment by yoshyosh** [comment]
I did this exclude: ['README.md', '*/books']

**Comment by yoshyosh** [comment]
Oh oops, I think it is working sorry about that!

**Comment by parkr** [comment]
:tada:

**Comment by yoshyosh** [comment]
Thanks :+1:
