### ISSUE TITLE
Using HTML Chunks in Jekyll

### ISSUE THREAD

**Issue by realph** [jekyll/jekyll#3563]
So, I'm fairly new to the markdown syntax and was wondering how far I'm able to bend it. I'm using Jekyll for my site and my `post.html` page shapes up like this:

    <section class="entry-content e-content py3" itemprop="articleBody">
      {{ content }}
    </section>

The content of my `.md` file goes inside those curly braces.

The problem though, is I need my page to be rendered like so:

    <div class="container">
      <div class="sm-col-8">
        <section class="entry-content">
          {{ content }}
        </section>
      </div>
    </div>

    <section class="image-gallery">
      <div class="container">
        <div class="sm-col-12"></div>
      </div>
    </section>

    <div class="container">
      <div class="sm-col-8">
        <section class="entry-content">
          {{ content }}
        </section>
      </div>
    </div>

    <section class="image-gallery">
      <div class="container">
        <div class="sm-col-12"></div>
      </div>
    </section>

Is there a solution to get around this? I'd rather not have hundreds of HTML tags in my markdown, is there a simple yet elegant way to do something like I've illustrated above?

Any help from Jekyll experts is appreciated. Thanks in advance!

**Comment by kleinfreund** [comment]
Why do you want the same content twice on your page? That does not sound useful to me.

**Comment by realph** [comment]
@kleinfreund I don't want repeated content on the page. I'd like to place the `image-gallery` block between the content and have the content to continue to flow after the gallery block. Hope that makes sense?

**Comment by kleinfreund** [comment]
Only possibility I can think of right now is actually placing the image gallery at the top or bottom of the HTML and position it via CSS. But this solution would really be messy and dirty.

**Comment by chrisfinazzo** [comment]
That _is_ odd...don't think I've ever seen it before...

That said, why not fallback to HTML inside your Markdown file? I know that sounds like it defeats the purpose, but the lack of support for positioning elements with Markdown makes this a necessary evil IMO.

I'm also not sure if you can place `{{content}}` twice on a page; Variables I guess would do the job, but that might be gross as well. Do you have an example to demonstrate this? (CodePen, Fiddle, whatever)

**Comment by kleinfreund** [comment]
Yeah, that’s probably your best bet: Do it manually in your .md files.

**Comment by parkr** [comment]
> I don't want repeated content on the page. I'd like to place the image-gallery block between the content and have the content to continue to flow after the gallery block. Hope that makes sense?

I'm confused by what you're trying to do here. It sounds like you could have N images that you want to display in your gallery and you're using every other  `<section class="image-gallery">` element to delineate K of them? So you have 12 images and you have an empty `image-gallery` every, say, 3 or 4 images? In this case, you're working with structured data so I'd use a `for` loop instead of posts. 

In the future, please post questions like this on https://talk.jekyllrb.com – we're trying to keep GitHub for development issues only. Thanks!
