### ISSUE TITLE
How to make synthetic pages in a generator plugin with arbitrary filename extensions

### ISSUE THREAD

**Issue by migurski** [jekyll/jekyll#3565]
I’m experimenting with a generator plugin that generates multiple output languages from single Jekyll input files:

https://github.com/codeforamerica/ceviche-starter/blob/93250f130/_plugins/languages.rb#L23

Apache MultiViews [uses multiple unordered filename extensions](http://httpd.apache.org/docs/2.2/content-negotiation.html#naming) to determine what version of a file to serve to a user based on request headers.

In order for Jekyll to correctly parse the files as Markdown, the `.markdown` extension should come after a language extension, e.g. `index.en.markdown` outputting to `index.en.html`. It’d be more convenient for Apache to have these in the opposite order, `index.html.en` allowing clients to request `index.html` and get a language-appropriate response. How might I trigger Markdown parsing in a Jekyll 2 generator plugin [like the one above](https://github.com/codeforamerica/ceviche-starter/blob/93250f130/_plugins/languages.rb) when the filename extension is `.markdown.{language}`?

**Comment by parkr** [comment]
> How might I trigger Markdown parsing in a Jekyll 2 generator plugin like the one above when the filename extension is .markdown.{language}?

You can configure markdown extensions, so in this case, set the `markdown_ext` setting to include your languages. That should do it!

**Comment by migurski** [comment]
Thank you @parkr. `site.find_converter_instance` didn’t work in 2.4.0, but [`site.getConverterImpl` did](https://github.com/jekyll/jekyll/blob/e72f8cf5b15e824aeec39164183a040aefecdb2c/lib/jekyll/site.rb#L379).

**Comment by parkr** [comment]
@migurski Ah, yeah. We changed that in 3.0. :smile:
