### ISSUE TITLE
Can't add a quote block on my post

### ISSUE THREAD

**Issue by kun2012** [jekyll/jekyll#3568]
I want to add a quote block on my post, so I add the character '>' at the head of the paragraph.
When I open the post html then noting happened.
The character '>' didn't work.
But if I use other apps(e.g. Markdown Preview Plus on Chromium), everything works fine.
Anyone know how to fix this?

**Comment by kleinfreund** [comment]
What exactly do you have in your post? The following works fine with my setup (default markdown processor is _kramdown_):

```markdown
This is a regular paragraph.

> This will be rendered as a blockquote.
```

**Comment by kun2012** [comment]
Oh, it's the layout problem.
Not using any layouts works fine.

**Comment by chrisfinazzo** [comment]
@kun2012, No harm done, but something to keep in mind...

Next time you have a question like this, can you post it on the Discourse [site][]? Trying to limit this to only bug reports. If there is a problem that needs to be addressed, it will eventually land here.

[site]: https://talk.jekyllrb.com

**Comment by parkr** [comment]
:)
