### ISSUE TITLE
Variables for accessing files in site.data

### ISSUE THREAD

**Issue by rhewitt22** [jekyll/jekyll#3569]
Let's say I have 3 subdirectories in `_data`: `officex`, `officey`, `officez`.  Each of those subdirectories contains a staff lasting: `staff.yml`.  I'd like to be able to create one layout, and pass in a page variable to generate a staff listing page for each office.

office page: `officex.html`
```
---
title: Office X Staff Listing
layout: staff
office: officex
---
```
staff layout: `staff.html`
```
{% capture office %}{{page.office}}.staff{% endcapture %}

{% for employee in site.data[office] %}
  {{ employee.name }}
{% endfor %}
```
**OR**
```
{% for employee in site.data.{{page.office}}.staff %}
  {{ employee.name }}
{% endfor %}
```

Instead I need to create a separate include for every office, which is very duplicative.

**Comment by parkr** [comment]
Why not `site.data[page.office].staff`?

**Comment by rhewitt22** [comment]
Doh!  Don't know why I made it so hard.

Thanks.
