### ISSUE TITLE
Remove script/test or have it just rake test.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3573]
Is there any real reason to use it? `bundle exec rake test` works just as well.  It would remove the hacky loader.rb from our files which tbh probably serves no real purpose at the end of the day, it seems like a legacy piece and it's better to remove it now before we head into RSpec than to deal with it later.

Link: #3543

**Comment by parkr** [comment]
I'd like to keep all the script/ stuff. I have them in all my projects -- it's a nice abstraction so new users don't get lost trying to run a project because they don't know the language's standards.

**Comment by mattr-** [comment]
:+1: to keeping the `script` folder.

**Comment by parkr** [comment]
It could just shell out to bundle exec rake test, but i'd like to keep it :)

**Comment by envygeeks** [comment]
While I don't agree that it's a nice abstraction (if there honestly isn't anything that happens that's special) I never removed `script/` inside of my pull request (and never will intend to remove `script/`, because it's not my purpose to disrupt) I removed `loader.rb` and did in-fact have it rely on bundle exec and the way minitest works.
