### ISSUE TITLE
Fix or remove circleci.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3575]
It really gets in the way of the purpose of pull statuses on Github!

**Comment by parkr** [comment]
It should really only run if the docs site changes. It prevents breaking anything on the site.

**Comment by pathawks** [comment]
Even then, it is frustrating and confusing when it throws errors that are totally unrelated to what has been changed.

Example: #3572

**Comment by parkr** [comment]
Sure, I hear that. I just wanr the site to stay unbroken. Maybe CircleCI should just not report globally and just email me.

**Comment by envygeeks** [comment]
Why not finally split the site out into it's own repo since it's open source?  This would allow both.  You can add a readme.md to the site folder that gives the link to the new repo so people don't get confused when they come to edit.  At that point we could also just utilize Travis (unless you are deploying and have worries about Travis deploying.)

**Comment by parkr** [comment]
> Why not finally split the site out into it's own repo since it's open source

This makes is much harder to contribute documentation when you're adding a new feature. My ideal process is that contributions come with documentation – if you change the way permalinks work, documentation should accompany the code changes. Keeping it all in the same source tree makes it way easier to do this.

**Comment by envygeeks** [comment]
That argument would hold if they could actually see the failure though.

**Comment by willnorris** [comment]
> if you change the way permalinks work, documentation should accompany the code changes.

yeah, that was my fault :disappointed: Though to be fair, #3556 has been out for review for a week now :wink: 

> That argument would hold if they could actually see the failure though.

I've never understood why the circleci pages always 404'ed.  Can we fix that, or if it's a limitation of circleci, can we run the documentation tests somewhere else?

**Comment by envygeeks** [comment]
@willnorris as a core member you can login to CircleCI (though I refuse to because it asks for access to my private repo's) and see the test failures and even restart a test to get it to pass, but a normal person can't.  The 404 part is them not knowing what the purpose of status codes are for (or knowing and not caring.)

CircleCI does in-fact have public builds but I don't know if @parkr wants that.

**Comment by parkr** [comment]
> if you change the way permalinks work, documentation should accompany the code changes.
>
> >  yeah, that was my fault  Though to be fair, #3556 has been out for review for a week now

@willnorris No worries at all, I was just using that recent change as an example.

> I've never understood why the circleci pages always 404'ed. Can we fix that, or if it's a limitation of circleci, can we run the documentation tests somewhere else?

It's wall of settings. I just fiddled with it, so now others should be able to see it.

I've disabled GitHub Status updates. It'll still run (afaict), but it won't report back so we won't be blocked by this stuff.

**Comment by willnorris** [comment]
> @willnorris as a core member you can login to CircleCI (though I refuse to because it asks for access to my private repo's) and see the test failures and even restart a test to get it to pass, but a normal person can't.  The 404 part is them not knowing what the purpose of status codes are for (or knowing and not caring.)

Ah, didn't realize I had access.  I also just backed away slowly when I saw the level of access they were requesting.  Full write permission to all of my repos in order to see some test results?  Not gonna happen.

Is there anything we can do to make the test results visible publicly?  Or is there some specific reason not to do so?

**Comment by parkr** [comment]
@willnorris I think i did that yesterday. There's a "Free and Open Source" switch I had to flip.

**Comment by willnorris** [comment]
> @willnorris I think i did that yesterday. There's a "Free and Open Source" switch I had to flip.

yep, looks great now.  thanks! :tada:
