### ISSUE TITLE
Documentation for adding variable parameters to an include

### ISSUE THREAD

**Issue by daviewales** [jekyll/jekyll#3577]
Currently, the [documentation for includes](http://jekyllrb.com/docs/templates/#includes) explains how to pass string parameters to includes, but gives no explanation of how to pass variable parameters to includes.

Specifically, the documentation says:

    {% include footer.html param="value" %}

However, it doesn't explain that variables can be passed this way:

    {% include footer.html param="value" variable-param=page.variable %}

It took lots of searching to figure this out.

**Comment by parkr** [comment]
Agreed, that should be in there! Feel free to throw that in there.

**Comment by tomjohnson1492** [comment]
I'm trying to understand the documentation that you added around variable parameters, but I'm coming up blank. I added a question on Jekyll Talk trying to understand this section of the documentation. Can you clarify it a bit? Here's more detail on my Jekyll Talk post. [https://talk.jekyllrb.com/t/do-parameters-for-includes-allow-liquid-syntax/2536](https://talk.jekyllrb.com/t/do-parameters-for-includes-allow-liquid-syntax/2536)

Ultimately I want to store a product variable in my configuration file, and then use it in a parameter in my include.
