### ISSUE TITLE
_pages Directory

### ISSUE THREAD

**Issue by aharris88** [jekyll/jekyll#3578]
I would like to be able to put all my pages in a single `_pages` directory, and then specify their permalink in the front-matter, instead of having to put them in the correct location, especially since that means that I end up putting all of my pages in directories and naming all of the files `index.html`.

It would be really nice to have all my pages in one central location.

Are there any thoughts about potentially adding this feature to Jekyll?

**Comment by parkr** [comment]
We have been asked about this a couple times. We built collections for this purpose.

**Comment by aharris88** [comment]
@parkr Thanks, I couldn't find an issue about this. Collections are perfect!
