### ISSUE TITLE
File to import not found or unreadable: bootstrap-sprockets

### ISSUE THREAD

**Issue by jastuccio** [jekyll/jekyll#3579]
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'style.scss':
                    File to import not found or unreadable: bootstrap-sprockets. Load path: /Users/joe/Sites/jastuccio.github.io/_sass on line 5

I am getting an error when starting the server :(  I searched, tried deleting the Gemfile.lock and executing bundle install.

**Comment by parkr** [comment]
Check your `@import`'s in your sass. It's trying to load `bootstrap-sprocket` somewhere and it can't find it.
