### ISSUE TITLE
Jekyll broke, SCSS not building CSS

### ISSUE THREAD

**Issue by swirlsnap** [jekyll/jekyll#3582]
cryptotap.com

My site runs just fine, but seems like the SCSS compiler failed to serve my css correctly, making all my sites formatting not show up -- any help would be awesome :) BTW, this worked before attempting to upgrade gems -- I rolled back my changes.

**Comment by swirlsnap** [comment]
Thinking i am going to just revert snapshots as this is giving me hell. >.<

**Comment by parkr** [comment]
@swirlsnap The SCSS is compiled on the build. Where is it compiling to? http://cryptotap.com/assets/css/i.css gives a 404.

**Comment by swirlsnap** [comment]
Rolled back to original theme / snapshot -- Not sure what i did there but i tried everything from removing RVM, installing normal 1.9.1 and then re-installing Jekyll but kept running into strange issues -- thank god for good backups :dancers:

**Comment by kleinfreund** [comment]
> thank god for good backups

Better thank yourself. :)
