### ISSUE TITLE
Calling “jekyll” with no arguments gives a zero return value

### ISSUE THREAD

**Issue by bdesham** [jekyll/jekyll#3584]
I just did several rounds of editing a file followed by

    jekyll && cat _site/2015/03/17/test.html

before I realized that Jekyll hadn’t actually built the site: calling `jekyll` with no arguments prints the help message and quits. It’s good that Jekyll automatically prints some help information when this happens but I’m not sure that a zero exit code is appropriate. If the user intentionally wrote `jekyll --help` then this would make sense, but just calling plain `jeykll` is really an error and the resulting `$?` should reflect that.

**Comment by parkr** [comment]
:+1:

**Comment by parkr** [comment]
Want to fix that?

**Comment by bdesham** [comment]
Sure, I'll take a look at it tomorrow.

**Comment by envygeeks** [comment]
This is a problem with mercenary no? Because technically mercenary should be handling the exit codes unless it doesn't handle the help output?

**Comment by parkr** [comment]
We have a "default task" that it executes, but we handle all exit codes. Mercenary just handles the user input and dispatches a command.

**Comment by bdesham** [comment]
:+1:
