### ISSUE TITLE
Subdirectories within _sass directory are not being watched or built

### ISSUE THREAD

**Issue by fi5u** [jekyll/jekyll#3589]
All the included `.scss` files in `_sass` directory (direct descendents) are being watched and built correctly, but `.scss` files in subdirectories within `_sass` are not being watched or built.

I tried uninstalling/reinstalling liquid, but that hasn't changed things.

Are there any more solutions I could try?

**Comment by parkr** [comment]
What does your config's `exclude` directive look like?

**Comment by fi5u** [comment]
Aarhh, just realised that this is this issue: https://github.com/jekyll/jekyll-watch/issues/22

The affected files are starting with '_site'.
