### ISSUE TITLE
Incremental regeneration issues

### ISSUE THREAD

**Issue by nickburlett** [jekyll/jekyll#3591]
The incremental regeneration doesn't work properly when using serve or watch for three reasons:
1. it only caches the mtime of the first dependency it discovers, so for posts/pages with N multiple dependencies (i.e., every layout file used to render them), it continues to regenerate the post/page N times, at which point it's seen all of the dependencies. 
2. it also incorrectly remembers which files are unchanged, meaning that once it decides a file is unchanged it won't ever regenerate that file until the jekyll command is restarted. 
3. it doesn't regenerate files (other than static files) if the destination file is removed

**Comment by nickburlett** [comment]
Test for removed files (it fails):

````diff
diff --git a/test/test_site.rb b/test/test_site.rb
index 7888f33..e19341e 100644
--- a/test/test_site.rb
+++ b/test/test_site.rb
@@ -495,6 +495,25 @@ class TestSite < JekyllUnitTest
         assert_equal mtime3, mtime4 # no modifications, so remain the same
       end
 
+      should "regnerate files that have had their destination deleted" do
+        contacts_html = @site.pages.find { |p| p.name == "contacts.html" }
+        @site.process
+
+        source = @site.in_source_dir(contacts_html.path)
+        dest = File.expand_path(contacts_html.destination(@site.dest))
+        mtime1 = File.stat(dest).mtime.to_i # first run must generate dest file
+
+        # simulate file modification by user
+        File.unlink dest
+        refute File.exist?(dest)
+
+        sleep 1
+        @site.process
+        assert File.exist?(dest)
+        mtime3 = File.stat(dest).mtime.to_i
+        refute_equal mtime2, mtime3 # must be regenerated 
+      end
+
     end
 
   end
````

**Comment by alfredxing** [comment]
@nickburlett The regenerator doesn't check for the existence of destination files. If you delete destination files, you should delete `.jekyll-metadata` as well (or just use the `jekyll clean` command)

**Comment by nickburlett** [comment]
@alfredxing I guess was expecting behavior similar to StaticFile. In test_site, there's a test for `should "write static files if not modified but missing in destination"`. However, it looks like this test is actually part of a full_rebuild site test, so I guess that wouldn't apply. 

Are you against the idea of it checking for the existence of destination files? It seems like it would be a helpful feature and make incremental build less error-prone if files go missing or if the config changes the output path.

**Comment by nickburlett** [comment]
@alfredxing I have working code to check the destination file and regenerate if it's missing. I haven't added it to the branch my original pull request came from in case you decide you don't want this feature. But could you take a look and consider it? See https://github.com/nickburlett/jekyll/tree/patch/incremental-build-dest-missing
