### ISSUE TITLE
Liquid syntax errors when upgrading 2.5.3 ⇒ 3.0.0.pre.beta2

### ISSUE THREAD

**Issue by fj** [jekyll/jekyll#3594]
I have this simple snippet in Jekyll 2.5.3, which renders correctly:

```
{% assign current = page.url | downcase | split: '/' %}
{% assign page.nav_highlight = 'blog' %}
# ...
  <a href="{{'/blog.html' | prepend: site.baseurl}}"
    {% if page.nav_highlight == 'blog' || current[1] == 'blog.html' %} class="active" {% endif %}
    title="Blog">
    Blog
  </a>
```

If I upgrade to 3.0.0.pre.beta2, I instead get:

```
  Liquid Exception:
    Liquid syntax error: Expected end_of_string but found pipe in "page.nav_highlight == 'blog' || current[1] == 'blog.html'" in _includes/header.html, included in _layouts/measure-lg.html
```

Additionally, if I remove

```
{% assign page.nav_highlight = 'blog' %}
```

so that `nav_highlight` is no longer defined on `page`, I get a different error (probably because `nav_highlight` is now null):

```
  Liquid Exception:
    Liquid syntax error: Expected dotdot but found comparison in "(page.nav_highlight == 'blog' || current[1] == 'blog.html')" in _includes/header.html, included in _layouts/measure-lg.html
```

Neither error occurs on 2.5.3.

**Comment by envygeeks** [comment]
This is probably a liquid bug but not necessarily a bug more than a bug fix... maybe.  I would definitely cross-file there too. I do not believe you are meant to be using filters in assign, can you switch the filtered assign to a capture and see if works?

```liquid
{% capture current %}{{ page.url | downcase | split: '/' }}{% endcapture %}
```

**Comment by pathawks** [comment]
Instead of ` || ` you need to use ` or `

I made that change and the site builds for me.

**Comment by fj** [comment]
It seems that this was always incorrect in Liquid, but Jekyll was silently ignoring some kinds of errors. I've fixed my site and will close this ticket.
