### ISSUE TITLE
Please tell me why~~

### ISSUE THREAD

**Issue by WangKunKun** [jekyll/jekyll#3604]
used rake generate~ Get this
-------
`appledeMacBook-Pro:octopress apple$ rake generate`
`Generating Site with Jekyll`
   `write source/stylesheets/screen.css`
`Configuration file: /Users/apple/octopress/_config.yml`
           ` Source: source`
      ` Destination: public`
      `Generating... `
`jekyll 2.0.0 | Error:  undefined method `gsub' for nil:NilClass`

used jekyll bulid --trace   __get this 
---
`appledeMacBook-Pro:~ apple$ jekyll build --trace`
`Configuration file: none`
        `    Source: /Users/apple`
    `   Destination: /Users/apple/_site`
    `  Generating... `
`/Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/entry_filter.rb:24:in ``join': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)`
`	from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/entry_filter.rb:24:in` `relative_to_source'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/entry_filter.rb:49:in` `excluded?'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/entry_filter.rb:30:in ``block in filter'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/entry_filter.rb:28:in` `reject'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/entry_filter.rb:28:in` `filter'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:400:in ``filter_entries'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:165:in` `block in read_directories'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:165:in ``chdir'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:165:in ``read_directories'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:176:in` `block in read_directories'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in ``each'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in ``read_directories'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:176:in` `block in read_directories'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in` `each'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:172:in` `read_directories'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:151:in` `read'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:49:in` `process'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in` `process_site'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in` `build'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in` `process'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in` `block (2 levels) in init_with_program'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in` `call'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in ``block in execute'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in` `each'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in ``execute'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in` `go'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in ``program'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/bin/jekyll:20:in ``<top (required)>'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/bin/jekyll:23:in ``load'`
	`from /Users/apple/.rbenv/versions/1.9.3-p0/bin/jekyll:23:in ``<main>'`

**Comment by kaatt** [comment]
Check out the config about Encoding in http://jekyllrb.com/docs/configuration/

**Comment by pathawks** [comment]
In the first example, you’re using Jekyll 2.0.0 to build a site from the `source` directory, and in the second example, you are using Jekyll 2.5.3 to generate a site from your home directory?

**Comment by envygeeks** [comment]
Set the encoding in your config, `encoding: ` to the encoding of your language.  `ASCII-8BIT`
