### ISSUE TITLE
Jekyll processes all Liquid filters and tags in asset files

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#3613]
From the [Assets page](http://jekyllrb.com/docs/assets/):

> **Jekyll processes all Liquid filters and tags in asset files**
> If you are using Mustache or another JavaScript templating language that conflicts with the Liquid template syntax, you will need to place {% raw %} and  {% endraw %} tags around your code.

And then a bit further down:

> **The `sass_dir` is only used by Sass**
> Note that the `sass_dir` becomes the load path for Sass imports, nothing more. This means that Jekyll does not know about these files directly, so any files here should not contain the YAML Front Matter as described above nor will they be transformed as described above. This folder should only contain imports.

These two blocks seem to be in conflict with one another.

For instance: if I include Liquid in my Sass, will Jekyll render it, or does Jekyll not know about these files?

**Comment by envygeeks** [comment]
I'd have to go back and double confirm but I believe we don't default ignore `sass_dir` which means if you do put liquid in the sass dir it will get processed as per normal, and from the last site I did the verse applies for sass (I don't even think we had trouble importing... I'd have to again double check that.)

**Comment by parkr** [comment]
> For instance: if I include Liquid in my Sass, will Jekyll render it, or does Jekyll not know about these files?

In your partial files? Jekyll ignores `sass_dir` if it starts with an underscore, but if it's a normal directory, you'll see it in your _site as a series of static files (because no `---\n---\n`). I didn't think partials could include sass – i thought the sass compiler would vomit on things like `{{ site.baseurl }}` or something.

**Comment by pathawks** [comment]
> i thought the sass compiler would vomit on things like {{ site.baseurl }} or something.

I believe that to be the case, in which case maybe the wording needs to be changed to reflect that "Jekyll processes all Liquid filters and tags in asset files, except partials in the `sass_dir` if it starts with an underscore":grey_question:

**Comment by parkr** [comment]
Jekyll will only render Liquid in the parent Sass file, it seems.
