### ISSUE TITLE
Missing tests for static_file.rb

### ISSUE THREAD

**Issue by mdenhoedt** [jekyll/jekyll#3626]
There are no unit tests for the [StaticFile](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/static_file.rb) class in the map `/test`, are there? Is it a good idea to add `/test/test_static_file.rb` with unit tests?

**Comment by envygeeks** [comment]
It is but it would probably be wasted effort since we are rewriting tests for RSpec anyways.
