### ISSUE TITLE
The code block of post content in markdown looks awful

### ISSUE THREAD

**Issue by johnsonlee** [jekyll/jekyll#3631]
I posted a markdown, there're some single line source code block and multiple line source code block, both code blocks are awful.

![screen shot 2015-04-01 at 13 54 18](https://cloud.githubusercontent.com/assets/2344882/6935364/ba6e5a56-d876-11e4-8e97-d6d46063a8fc.png)
![screen shot 2015-04-01 at 13 54 41](https://cloud.githubusercontent.com/assets/2344882/6935365/baa7b6a2-d876-11e4-8248-ea115713d8f8.png)

**Comment by kleinfreund** [comment]
The backticks need to be on a new line each. Also, how something looks is totally up to the sites design.

**Comment by parkr** [comment]
^^ this guy. :ok_hand: Spot on. Cheers!
