### ISSUE TITLE
I get the requirements installed but encountered a problem at the right begining

### ISSUE THREAD

**Issue by zykzhang** [jekyll/jekyll#3634]
type"$ jekyll new myblog", and get an err:
~/projects$ jekyll new myblog
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
WARNING: Could not read configuration. Using defaults (and options).
	No such file or directory - new/_config.yml
Building site: new -> myblog
/usr/lib/ruby/vendor_ruby/jekyll/site.rb:126:in `chdir': No such file or directory - /home/jason/projects/new/ (Errno::ENOENT)
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:126:in `read_directories'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:98:in `read'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:38:in `process'
	from /usr/bin/jekyll:250:in `<main>

**Comment by parkr** [comment]
You are using a very old version of Jekyll (pre 1.0). You need to update! Use `gem install jekyll`.
