### ISSUE TITLE
Announcing JekyllConf - The Free online conference for all things Jekyll

### ISSUE THREAD

**Issue by mneumegen** [jekyll/jekyll#3635]
Hi Jekyllrb community!

Today I'm very excited to announce the launch of JekyllConf.

JekyllConf is a free, online conference for all things Jekyll taking place on the 2nd of May (PST). You can find out more details including the currently confirmed speakers here - [JekyllConf.com](http://jekyllconf.com/)

The vision for JekyllConf is to bring together the existing Jekyll community and inspire it's wider adoption.

Specific focuses for this year are: to share best practice; advanced case studies and interesting implementations; and discuss the future of Jekyll.

We still have a few more slots for keen community members to speak.

Check out [JekyllConf.com](http://jekyllconf.com/) and [@JekyllConf](https://twitter.com/JekyllConf) for more info.

Cheers,
Mike (& Sam), JekyllConf team

**Comment by parkr** [comment]
Pretty stoked about this! Thanks for organizing it. :smile: 

![](http://gifs.joelglovier.com/high-five/community-high-five.gif)

Please leave comments here: https://talk.jekyllrb.com/t/jekyllconf-launch-announcement/286
