### ISSUE TITLE
No instructions for installing jekyll blog on a subdirectory (or non-main repo)

### ISSUE THREAD

**Issue by jonbstrong** [jekyll/jekyll#3636]
I would like to have a jekyll blog running on a subdomain of my main repo at www.jonbstrong.com/blog however all the instructions I can find refer to installing Jekyll on the main repo rather than the subdomain. Is this possible?

**Comment by parkr** [comment]
A subdomain or a subfolder?

Both are possible, yes. The latter asks that you make judicious use of `{{ "/my/path" | prepend:site.basurl }}` in your templates. There's no out-of-the-box url rewriting.

**Comment by jonbstrong** [comment]
Subfolder, yes. Are there full instructions for this anywhere?

**Comment by parkr** [comment]
@jonbstrong Nothing official – if you look for GitHub Pages Project Pages tutorials, you'll probably find a good one!
