### ISSUE TITLE
Absolute URL to main.css breaks styles on subdirectories

### ISSUE THREAD

**Issue by olivierlacan** [jekyll/jekyll#3639]
When deploying a Jekyll site to a GitHub pages project page the CSS files are not hosted at `/css` but instead at `/project/css` so following in `_includes/head.html` causes the styles not to load: 

```html
<link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.baseurl }}">
```

It should probably be replaced with:

```html
<link rel="stylesheet" href="{{ "css/main.css" | prepend: site.baseurl }}">
```

PS: I'm seeing this in Jekyll 2.5.3

**Comment by kleinfreund** [comment]
That's why `site.baseurl` is prepended. `baseurl` should be set to `project` in this case.

**Comment by olivierlacan** [comment]
@kleinfreund Yup. Just found that out. Closing. :smile:
