### ISSUE TITLE
Error:  undefined method `default_proc=' for #<String:0x00000101e45e88>

### ISSUE THREAD

**Issue by tomdavenport** [jekyll/jekyll#3643]
Hi, not entirely sure if this is a bug with Jekyll or my system, but Google is serving no results so trying for feedback here.

Normally running `jekyll serve --watch` runs fine, but today I got this as a result:

`jekyll 2.5.1 | Error:  undefined method ``default_proc=' for #<String:0x00000101e45e88>`

Any ideas what is up? Is this a bug or something else?

**Comment by parkr** [comment]
Please run again with `--trace` to get the full output. Are you using any plugins?

**Comment by tomdavenport** [comment]
````
/Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/page.rb:35:in `initialize': undefined method `default_proc=' for #<String:0x0000010179eb98> (NoMethodError)
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/site.rb:178:in `new'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/site.rb:178:in `block in read_directories'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/site.rb:172:in `each'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/site.rb:172:in `read_directories'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/site.rb:151:in `read'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/site.rb:49:in `process'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/commands/build.rb:56:in `build'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `call'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `each'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `execute'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/mercenary-0.3.4/lib/mercenary/program.rb:35:in `go'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/mercenary-0.3.4/lib/mercenary.rb:22:in `program'
	from /Users/tom/.rvm/gems/ruby-2.1.1/gems/jekyll-2.5.1/bin/jekyll:20:in `<top (required)>'
	from /Users/tom/.rvm/gems/ruby-2.1.1/bin/jekyll:23:in `load'
	from /Users/tom/.rvm/gems/ruby-2.1.1/bin/jekyll:23:in `<main>'
	from /Users/tom/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tom/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
 ```
Only plugin is Reading Time but that has worked fine for ages.

Recently tried installing JAPR (the asset pipeline plugin) but abandoned while trying the Google Pagespeed tool on my server.

**Comment by parkr** [comment]
Super weird. Looks like one of your pages has invalid yaml. What did you edit recently?

The property it's trying to affect is [`Page.data`](https://github.com/jekyll/jekyll/blob/v2.5.1/lib/jekyll/page.rb#L35-L37), which should be a `Hash`, not a `String`.

**Comment by tomdavenport** [comment]
Great, it was me doing a dumb 'replace all' on colons in the body, but this screwed up the YAML. Thanks for your help :+1:

**Comment by envygeeks** [comment]
I think your problem might be a testament to our need to be more verbose with YAML issues.  We can readily detect them and pass the error out without verbosity enabled can we not @parkr?

**Comment by parkr** [comment]
we could detect `if !data.is_a? Hash` pretty simply and say something like `path/to/page.html has invalid YAML front matter. Please fix`

**Comment by tomdavenport** [comment]
That would work, I have limited experience and even something that simple would make the solution obvious to me.

**Comment by parkr** [comment]
Want to submit a PR?

**Comment by tomdavenport** [comment]
I have no idea how to set up the detection.

**Comment by parkr** [comment]
In the `read_yaml` method in `convertible.rb`, we'd probably check the value of `self.data`. If it's not a Hash, we'd print the appropriate error message and fail (`Jekyll.logger.abort_with "Error:", "Invalid YAML front matter in index.html`)

**Comment by Allianzcortex** [comment]
I ever met the same questions,just because **the lack of space** during the YAML files. such like **layout:post** should be changed into **layout: post".May this will help someone.
