### ISSUE TITLE
install New system for my samsung S4 and reboot to recovery.

### ISSUE THREAD

**Issue by lgp36018** [jekyll/jekyll#3645]
i try to recovery with TWRP and was show seandriod not enforce,please help me to install the new rom with TWRP recovery here

**Comment by lgp36018** [comment]
just install any recommanded  custom Rom  and Kernel that will not brick my mobile phone again.My model is Samsung S4 GT19505 international model.......Tar...Jflte

**Comment by kleinfreund** [comment]
@lgp36018 I think you've got some things mixed up here. This is the issue tracker for Jekyll and it does not have anything to do with your Samsung S4.
