### ISSUE TITLE
Jekyll Appends Absolute Path of _layout/default.htm to Absolute Path of the _posts Directory

### ISSUE THREAD

**Issue by carljparker** [jekyll/jekyll#3648]
Jekyll appends the absolute path of `_layout/default.htm` to the absolute path for the `_posts` directory and then tries to find `default.htm` at that location.

The issue appears to have started occurring in Jekyll `2.5.0`.

I do not see the issue in the preceding version, Jekyll `2.4.0`.

You can find a test case at the following repo:

https://github.com/carljparker/test-case-jekyll-directory

**Comment by parkr** [comment]
That's because you set `-s _posts` in your `make.sh`. Remove that and it should all work. It worked for me!
