### ISSUE TITLE
Ensure the Dir.pwd and the actual working directory line up

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#3653]
Sometimes `Dir.pwd` returns the `$(pwd)` in downcased or otherwise incorrect form. In `jekyll doctor`, we should check this and it should be Windows-compatible as well.

Ref: https://github.com/jekyll/jekyll/issues/3624.

**Comment by envygeeks** [comment]
We can probably skip it on Windows because I don't think Windows has a inotify or fsnotify equiv?

**Comment by envygeeks** [comment]
Ah yes they do: https://msdn.microsoft.com/en-us/library/aa364417(VS.85).aspx but either way, we'll skip it on both Linux and Windows and return true for those operating systems because they are not affected.
