### ISSUE TITLE
Minitest 5.6 breaks tests

### ISSUE THREAD

**Issue by alfredxing** [jekyll/jekyll#3656]
Minitest 5.6 was released today, causing the [latest Travis run](https://travis-ci.org/jekyll/jekyll/jobs/58387226#L271) to throw this error:
```
Error:
TestCommand#test_: when calling .add_build_options should add common options. :
NoMethodError: undefined method `to' for #<Minitest::Expectation:0x00000004e91188>
    /home/travis/build/jekyll/jekyll/test/test_command.rb:7:in `block (2 levels) in <class:TestCommand>'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /home/travis/build/jekyll/jekyll/vendor/bundle/ruby/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
```

I could reproduce on my local machine after running `bundle update`.

/cc @arthurnn @envygeeks @parkr

**Comment by arthurnn** [comment]
Minitest 5.6 added the `expect` method when using the `spec` module. https://github.com/seattlerb/minitest/commit/bed95459bdefc6c8e9699d1563a472ac661ccd5c

That will definitely collide with rspec-mocks.
I would say the solution for now is force to use minitest 5.5 , until rspec-mock finds a solution.

**Comment by arthurnn** [comment]
https://github.com/jekyll/jekyll/pull/3657 should fix the issue for now.

**Comment by parkr** [comment]
Locked to 5.5.1 per @arthurnn's PR.

**Comment by arthurnn** [comment]
I think this can be closed now, I would say this is a rspec-mock issue, which they could do something about it or not.

**Comment by envygeeks** [comment]
I'm going to be entirely honest here, this is not an rspec-mock problem.  This is a Jekyll problem.  We chose to use Minitest and rspec-mocks, rspec-mocks is under no obligation to work with minitest as it's apart of the rspec family.  If we want to use rspec-mocks it's up to us to fix the problem, it's rather annoying the conclusion was made that it's a rspec-mocks problem.

**Comment by arthurnn** [comment]
> If we want to use rspec-mocks it's up to us to fix the problem, it's rather annoying the conclusion was made that it's a rspec-mocks problem.

I agree @envygeeks , I opened an issue on their side, just so they are aware, but, by no means, they should do anything about it.

**Comment by envygeeks** [comment]
Gonna close this since there is a ticket on rspec-mocks.  If there is a change there I'll get notified or @arthurnn will get notified and we can take action then.  No reason to leave this dangling since the direct issue is resolved multiple times!

**Comment by parkr** [comment]
Fixed by https://github.com/jekyll/jekyll/pull/3658.
