### ISSUE TITLE
Add generators  for posts, pages y drafts

### ISSUE THREAD

**Issue by nmenag** [jekyll/jekyll#3659]
Add generators same  what  use Octopress project  https://github.com/octopress/octopress#octopress-commands.

**Comment by parkr** [comment]
Check 'em out! https://github.com/jekyll/jekyll-compose

**Comment by nmenag** [comment]
Ok, but for generate new pages y unpublish post?

**Comment by parkr** [comment]
> Ok, but for generate new pages y unpublish post?

Feel free to suggest them over on that repo!
