### ISSUE TITLE
How to add values using Generators at build time

### ISSUE THREAD

**Issue by yoshyosh** [jekyll/jekyll#3661]
Having trouble understanding the documentation. I'm trying to add variables that I create in my generator into specific blog posts. Is there a way to parse a blog post to retrieve something like a url, then use that url (to ping an api for example) in the generator to return another value that is then added to that blog post?

**Comment by parkr** [comment]
The generators are called after the read step so you should be able to look through `site.posts` and do whatever you need in your generator's `generate` method. To add variables, add them to the `post.data` hash!

**Comment by yoshyosh** [comment]
Great thank you!
