### ISSUE TITLE
kramdown abbreviations not being output

### ISSUE THREAD

**Issue by rudedogg** [jekyll/jekyll#3664]
I looked at the `abbr` test suite in the 1.6.0 release of kramdown and it's rendered correctly, so I'm thinking it might be an issue in Jekyll.

My markdown:
```
*[TIL]: Today I Learned
```
Expected output:
```html
<abbr title="Today I Learned">TIL</abbr>
```

`gem list` output:
```
jekyll (2.5.3)
jekyll-coffeescript (1.0.1)
jekyll-gist (1.2.1)
jekyll-paginate (1.1.0)
jekyll-sass-converter (1.3.0)
jekyll-watch (1.2.1)
kramdown (1.6.0)
```

`_config.yml` setting: 
```yml
markdown: kramdown
```

**Comment by envygeeks** [comment]
Can you please post the actual output you got too?

**Comment by rudedogg** [comment]
Sure @envygeeks,

I have this chunk in my markdown file:
```markdown
test

*[TIL]: Today I Learned

test
```

The generated HTML is:
```HTML
<p>test</p>

<p>test</p>
```

**Comment by paulrobertlloyd** [comment]
@rudedogg Are you using this feature correctly? Your markdown should be ass follows:

```
test TIL test

*[TIL]: Today I Learned
```

Which will output:

```html
<p>test <abbr title="Today I Learned">TIL</abbr> test</p>
```

That is to say, you need to have the abbreviation appear in the text preceding the definition. Here’s an example from my own site: https://raw.githubusercontent.com/paulrobertlloyd/paulrobertlloyd.com/master/source/journal/_posts/entries/2015-04-20-ttip.markdown

**Comment by parkr** [comment]
> That is to say, you need to have the abbreviation appear in the text preceding the definition

@paulrobertlloyd to the rescue. Try that @rudedogg and let us know.

**Comment by rudedogg** [comment]
That was it, thank you @paulrobertlloyd!

I jumped straight to the sample code of the kramdown docs, but skipped this text:
> When writing the text, you don’t need to do anything special. However, once you add abbreviation definitions, the abbreviations in the text get marked up automatically.
> - http://kramdown.gettalong.org/syntax.html#abbreviations

My apologies and thanks again everyone!
