### ISSUE TITLE
Liquid math filter "round" does not work in Jekyll

### ISSUE THREAD

**Issue by DominikTo** [jekyll/jekyll#3669]
It seems like all the math filters documented in the [liquid docs](https://docs.shopify.com/themes/liquid-documentation/filters/math-filters) work fine, with the exception of the [round](https://docs.shopify.com/themes/liquid-documentation/filters/math-filters#round) filter, which just doesn't do anything.

It works fine, when I just try it directly in liquid via `irb` (see below), so I am not quite sure why it's not working via jekyll.

```
irb(main):002:0> require 'liquid'
irb(main):003:0> template = Liquid::Template.parse("{{ 4.1234 | round }}")
irb(main):004:0> template.render
=> "4"
```

In Jekyll however `{{ 4.1234 | round }}` outputs `4.1234`.

**Comment by parkr** [comment]
In your IRB shell, what version of Liquid were you using? Jekyll presently uses 2.6.x, not 3.x. Liquid 3 could have a fix for this.

**Comment by DominikTo** [comment]
Good point! Indeed `liquid-3.0.1` in the `irb` shell.

* Is it planned to upgrade to 3.x?
* Which version is running on GitHub pages?

**Comment by kleinfreund** [comment]
> Which version is running on GitHub pages?

As of https://pages.github.com/versions/: Liquid 2.6.1

**Comment by sondr3** [comment]
> Is it planned to upgrade to 3.x?

The beta for Jekyll 3.0 uses Liquid 3.x.

**Comment by parkr** [comment]
:)

**Comment by sinalpha** [comment]
same issue . ` liquid (~> 2.6.1)`. And i try with the  filters module 

` {{ 4.1234 | modulo: 1 | minus: 4.1234 | times: -1 }}`

which return `4.0`, still a float number.

**Comment by envygeeks** [comment]
Please update your Jekyll, current Jekyll uses Liquid 3.
