### ISSUE TITLE
Lint config step prior to compiling?

### ISSUE THREAD

**Issue by gjtorikian** [jekyll/jekyll#3673]
I just helped out a colleague who was having problems with my [jekyll-html-pipeline](https://github.com/gjtorikian/jekyll-html-pipeline) plugin. First, he neglected to add `gems` to the config file. Then, he neglected to add `filter`s, which the plugin requires.

It would be neat if plugins could define expected values in the config file, prior to the compilation step. For example, some DSL like:

``` ruby
:require => :gem => 'jekyll-html-pipeline', :keys => [:filter]
```

**Comment by parkr** [comment]
We can't know about your plugin (or its configuration) without it being required, so `:gem => 'jekyll-html-pipeline'` wouldn't help.

In terms of requiring configuration, this should be up to the plugin. The `initialize()` call for your plugin could be the place to do this. :+1: 

```shell
$ jekyll build
Warn: jekyll-html-pipeline received no filters and will not be used.
```

etc.
