### ISSUE TITLE
jekyll serve ignore the "url" parameter in config.yml

### ISSUE THREAD

**Issue by hfiguiere** [jekyll/jekyll#3680]
jekyll serve ignore the ````url```` paramater in _config.yml

I believe it should use it as the base to serve the content.

So if url is set too ````foobar````, ````jekyll serve```` would by default serve ````http://127.0.0.1:4000/foobar/````

**Comment by pathawks** [comment]
I believe what you are looking for is `baseurl`

**Comment by parkr** [comment]
Yep, @pathawks is correct! 

https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
