### ISSUE TITLE
Parsing csv data not working

### ISSUE THREAD

**Issue by yoshyosh** [jekyll/jekyll#3682]
`_data/dummy.csv`
My CSV looks like this
````
date, pub
7/14/2014, The best news
7/20/2014, Secondary news
````

My html

````
{% for article in site.data.dummy %}
  <p>Wooo</p>
  <p>{{% article.date %}}</p>
{% endfor %}
````

Only prints Wooo twice, not the article date. Any ideas?

**Comment by yoshyosh** [comment]
Needed to use `{{ article.date }}` saw it right as I posted this

**Comment by envygeeks** [comment]
Fair enough! Thanks for noticing!
