### ISSUE TITLE
Cannot install jekyll

### ISSUE THREAD

**Issue by Tsien** [jekyll/jekyll#3684]
ERROR:  Could not find a valid gem 'jekyll' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/quick/Marshal.4.8/jekyll-2.5.3.gemspec.rz)
ERROR:  Possible alternatives: jekyll

**Comment by envygeeks** [comment]
This is actually an error with RubyGems that randomly happens now days when connecting outside of America.  If you don't mind, please file this ticket on their tracker so that they have one more person who can let them know this has been happening since around November for a lot of people.

**Comment by parkr** [comment]
@Tsien See #1409.

**Comment by Tsien** [comment]
Thanks!

**Comment by parkr** [comment]
:smiley:
