### ISSUE TITLE
CoffeeScript conversion error

### ISSUE THREAD

**Issue by oliverhuynh** [jekyll/jekyll#3685]
I got below error while using coffeescript in a project
  Conversion error: Jekyll::Converters::CoffeeScript encountered an error while converting 'js/top-slide.coffee':
                    could not find a temporary directory
jekyll 2.5.3 | Error:  could not find a temporary directory

Any ideas how to fix this? Is this a bug of Jekyll?
I tried to use TMPDIR variable but it no helps. My current OS is Ubuntu

**Comment by parkr** [comment]
Can you run with --trace? Probably a caching thing.

**Comment by oliverhuynh** [comment]
Hi,

I already got the fix. Put a sticky bit to /tmp can solve the issue.

**Comment by AllenDuane** [comment]
Thank you ~ I`m a new boy here.

**Comment by AllenDuane** [comment]
thank you ,I`m a new bot here

在 2015-05-06 13:08:52，"oliverhuynh" <notifications@github.com> 写道：


Closed #3685.
