### ISSUE TITLE
error

### ISSUE THREAD

**Issue by frodawork** [jekyll/jekyll#3686]
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20150507-6506-1qnockp.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14/ruby/config.h', needed by `yajl.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/yajl-ruby-1.2.1 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/yajl-ruby-1.2.1/gem_make.out

**Comment by parkr** [comment]
You don't have the Ruby header files. I'd recommend installing a new Ruby version with `rbenv`, or installing Jekyll 3 beta3 with `gem install jekyll --pre`.
