### ISSUE TITLE
Default yml has error ?

### ISSUE THREAD

**Issue by AntiMoron** [jekyll/jekyll#3689]
The file is ```_config.yml```

> description: > # this means to ignore newlines until "baseurl:"
>  Write an awesome description for your new site here. You can edit this
>  line in _config.yml. It will appear in your document head meta (for
>  Google search results) and in your feed.xml site description.
> baseurl: "" # the subpath of your site, e.g. /blog/

The description of character ```#``` may be not correct.
Actually it won't ignore the line between ```#``` and ```baseurl:```.Instead,it'll just ignore the words between character ```#``` and the end of the same line.

**Comment by parkr** [comment]
What is the correct description?

**Comment by envygeeks** [comment]
`# < Triggers a line based comment that will last until you create a "new line"`

**Comment by pathawks** [comment]
[line 4](https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml#L4)

We're talking about different things.

The `#` character begins a newline terminated comment, yes.

The preceeding `>` character begins a block string. *This* is what the comment is referring to.

**Comment by AntiMoron** [comment]
@pathawks  I still do not get what you said.Do you mean that ```> #``` triggers a block comment ?

**Comment by envygeeks** [comment]
@AntiMoron Yes, apparently we have an explanation issue.  I didn't grasp that at first either until I reread it a few times after @pathawks pointed it out.  It seems like we could be much better at explaining it to people in a less ambiguous way because "this" could refer to either one of those two line items.

**Comment by pathawks** [comment]
The `>` triggers a block string containing the description

The `#` triggers a comment, explaining that multi-line string but not included in the multi-line string.

**Comment by AntiMoron** [comment]
@pathawks  oh I see now.

**Comment by AntiMoron** [comment]
@envygeeks  Tks dude. ```This``` is not that clear for those new to jekyll like me :).
