### ISSUE TITLE
Jekyll serve does not auto regenerate

### ISSUE THREAD

**Issue by sashoa** [jekyll/jekyll#3695]
Running jekyll serve gives me no errors and it says - Auto-regeneration: enabled, but its not working for some reason.

I am using Jekyll 2.5.3 on Arch Linux.

**Comment by parkr** [comment]
Please search the issues before you post – we have seen this kind of thing before. You'll need to collect debugging issue by running `bundle exec jekyll build --watch` with `LISTEN_GEM_DEBUGGING=1` in your environment. Change a file and collect all output and post here, please.

**Comment by sashoa** [comment]
This is what i got. As i can see the changes are made, but the browser is not updating:

     Configuration file: /home/sashe/Dev/sashoa/_config.yml
            Source: /home/sashe/Dev/sashoa
       Destination: /home/sashe/Dev/sashoa/_site
      Generating... 
                    done.
    I, [2015-05-12T20:20:48.173988 #2268]  INFO -- : Celluloid loglevel set to: 1
    I, [2015-05-12T20:20:48.174064 #2268]  INFO -- : Listen version: 2.10.0
    I, [2015-05-12T20:20:48.184036 #2268]  INFO -- : Record.build(): 0.0017943382263183594 seconds
     Auto-regeneration: enabled for '/home/sashe/Dev/sashoa'
    I, [2015-05-12T20:20:51.829449 #2268]  INFO -- : listen: raw changes: [[:added, "/home/sashe/Dev/sashoa/foo"]]
    I, [2015-05-12T20:20:51.829595 #2268]  INFO -- : listen: final changes: {:modified=>[], :added=>["/home/sashe/Dev/sashoa/foo"], :removed=>[]}
      Regenerating: 1 file(s) changed at 2015-05-12 20:20:51 ...done in 0.111329991 seconds.

This is with 'LISTEN_GEM_DEBUGGING=2':

    Configuration file: /home/sashe/Dev/sashoa/_config.yml
            Source: /home/sashe/Dev/sashoa
       Destination: /home/sashe/Dev/sashoa/_site
      Generating... 
                    done.
    I, [2015-05-12T20:28:37.140464 #2421]  INFO -- : Celluloid loglevel set to: 0
    I, [2015-05-12T20:28:37.140543 #2421]  INFO -- : Listen version: 2.10.0
    D, [2015-05-12T20:28:37.147637 #2421] DEBUG -- : Adapter: considering TCP ...
    D, [2015-05-12T20:28:37.147682 #2421] DEBUG -- : Adapter: considering polling ...
    D, [2015-05-12T20:28:37.147722 #2421] DEBUG -- : Adapter: considering optimized backend...
    I, [2015-05-12T20:28:37.151627 #2421]  INFO -- : Record.build(): 0.002410411834716797 seconds
     Auto-regeneration: enabled for '/home/sashe/Dev/sashoa'
    D, [2015-05-12T20:28:44.753065 #2421] DEBUG -- : inotify: foo2 ([:create])
    D, [2015-05-12T20:28:44.753494 #2421] DEBUG -- : raw queue: [:file, #<Pathname:/home/sashe/Dev/sashoa>, "foo2", {:change=>:added}]
    D, [2015-05-12T20:28:44.754809 #2421] DEBUG -- : inotify: foo2 ([:attrib])
    D, [2015-05-12T20:28:44.755420 #2421] DEBUG -- : added: file:/home/sashe/Dev/sashoa/foo2 ({:change=>:added})
    D, [2015-05-12T20:28:44.755640 #2421] DEBUG -- : raw queue: [:file, #<Pathname:/home/sashe/Dev/sashoa>, "foo2", {:change=>:modified}]
    D, [2015-05-12T20:28:44.756723 #2421] DEBUG -- : inotify: foo2 ([:close_write, :close])
    D, [2015-05-12T20:28:44.756870 #2421] DEBUG -- : raw queue: [:file, #<Pathname:/home/sashe/Dev/sashoa>, "foo2", {:change=>:modified}]
    D, [2015-05-12T20:28:44.758058 #2421] DEBUG -- : modified: file:/home/sashe/Dev/sashoa/foo2 ({:change=>:modified})
    D, [2015-05-12T20:28:44.758418 #2421] DEBUG -- : modified: file:/home/sashe/Dev/sashoa/foo2 ({:change=>:modified})
    I, [2015-05-12T20:28:44.859081 #2421]  INFO -- : listen: raw changes: [[:added, "/home/sashe/Dev/sashoa/foo2"]]
    I, [2015-05-12T20:28:44.859192 #2421]  INFO -- : listen: final changes: {:modified=>[], :added=>["/home/sashe/Dev/sashoa/foo2"], :removed=>[]}
      Regenerating: 1 file(s) changed at 2015-05-12 20:28:44 D, [2015-05-12T20:28:44.957248 #2421] DEBUG -- : inotify: _site/jekyll/update/2015/05/12/welcome-to-jekyll.html ([:close_write, :close])
    D, [2015-05-12T20:28:44.957431 #2421] DEBUG -- : raw queue: [:file, #<Pathname:/home/sashe/Dev/sashoa>, "_site/jekyll/update/2015/05/12/welcome-to-jekyll.html", {:change=>:modified}]
    D, [2015-05-12T20:28:44.958769 #2421] DEBUG -- : inotify: _site/about/index.html ([:close_write, :close])
    D, [2015-05-12T20:28:44.958949 #2421] DEBUG -- : raw queue: [:file, #<Pathname:/home/sashe/Dev/sashoa>, "_site/about/index.html", {:change=>:modified}]
    D, [2015-05-12T20:28:44.959605 #2421] DEBUG -- : (silenced): "_site/jekyll/update/2015/05/12/welcome-to-jekyll.html"
    D, [2015-05-12T20:28:44.959899 #2421] DEBUG -- : (silenced): "_site/about/index.html"
    D, [2015-05-12T20:28:44.961046 #2421] DEBUG -- : inotify: _site/feed.xml ([:close_write, :close])
    D, [2015-05-12T20:28:44.961221 #2421] DEBUG -- : raw queue: [:file, #<Pathname:/home/sashe/Dev/sashoa>, "_site/feed.xml", {:change=>:modified}]
    D, [2015-05-12T20:28:44.962182 #2421] DEBUG -- : (silenced): "_site/feed.xml"
    D, [2015-05-12T20:28:44.962918 #2421] DEBUG -- : inotify: _site/index.html ([:close_write, :close])
    D, [2015-05-12T20:28:44.963088 #2421] DEBUG -- : raw queue: [:file, #<Pathname:/home/sashe/Dev/sashoa>, "_site/index.html", {:change=>:modified}]
    D, [2015-05-12T20:28:44.963900 #2421] DEBUG -- : (silenced): "_site/index.html"
    D, [2015-05-12T20:28:44.964478 #2421] DEBUG -- : inotify: _site/css/main.css ([:close_write, :close])
    D, [2015-05-12T20:28:44.965064 #2421] DEBUG -- : raw queue: [:file, #<Pathname:/home/sashe/Dev/sashoa>, "_site/css/main.css", {:change=>:modified}]
    D, [2015-05-12T20:28:44.965982 #2421] DEBUG -- : inotify: _site/foo2 ([:create])
    ...done in 0.106988834 seconds.
    D, [2015-05-12T20:28:44.966150 #2421] DEBUG -- : (silenced): "_site/css/main.css"
    D, [2015-05-12T20:28:44.966318 #2421] DEBUG -- : raw queue: [:file, #<Pathname:/home/sashe/Dev/sashoa>, "_site/foo2", {:change=>:added}]
    D, [2015-05-12T20:28:44.966446 #2421] DEBUG -- : Callback took 0.10719895362854004 seconds
    D, [2015-05-12T20:28:44.967117 #2421] DEBUG -- : inotify: _site/foo2 ([:close_write, :close])
    D, [2015-05-12T20:28:44.967813 #2421] DEBUG -- : (silenced): "_site/foo2"
    D, [2015-05-12T20:28:44.967975 #2421] DEBUG -- : raw queue: [:file, #<Pathname:/home/sashe/Dev/sashoa>, "_site/foo2", {:change=>:modified}]
    D, [2015-05-12T20:28:44.968761 #2421] DEBUG -- : (silenced): "_site/foo2"

**Comment by parkr** [comment]
Looks like your `foo2` is generating after all and that celluloid and listen are working as expected.

**Comment by sashoa** [comment]
Chrome does not automaticaly reload after regeneration for some reason, however Firefox is doing it well.

**Comment by envygeeks** [comment]
Why would chrome automatically reload?
