### ISSUE TITLE
Geting Jekyll site rebuild dayly on github pages

### ISSUE THREAD

**Issue by djacquel** [jekyll/jekyll#3699]
This is certainly not the place to ask this question, but I know that @parkr , @benbalter, and other influential contributors are in the place.
My use case is :
- my agenda is stored in a data file that contains all my event history.
- the agenda.html page only displays present and future events.
- the archive.html page only displays past events.
- on day 0, both events are displayed on the correct page.
- on day n, there is no new content but as time moved forward, some events might have to move from agenda to archive page.

As my static site is on Github pages how can I have a daily automatic build ?
And where can I post this feature request ?

**Comment by envygeeks** [comment]
Please move your topic to talk.jekyllrb.com this is not a help forum.

**Comment by djacquel** [comment]
Thank you for the hint.
