### ISSUE TITLE
Css content escaping

### ISSUE THREAD

**Issue by proukornew** [jekyll/jekyll#3701]
I have head.html that contains:
```css
<style>  
#someId:before {  
        content: "";  
</style>
```
jekyll generates page that contains:
```css
<style>  
#someId:before {  
        content: &#8220;&#8221;;
</style>
```
How to avoid this?

**Comment by kleinfreund** [comment]
Could it be Markdown intereferring with that? Nontheless, this shouldn't happen. This is a bug.

**Comment by proukornew** [comment]
@kleinfreund 
>Could it be Markdown intereferring with that?

In my _config.yml

```
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
```
also same behavior occurs with redcarpet

**Comment by envygeeks** [comment]
We shouldn't be running that page through Markdown at all and if we are then that is a major bug.  What is the source of the page (as much as you can reveal?)

**Comment by proukornew** [comment]
@envygeeks 
```
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
<style>
  @media screen,projection {

    #test:after,
    #test:before {
        content: "";
        float: right;
        height: 4px
    }

</style>
  
</head>
```

**Comment by envygeeks** [comment]
Do you have any plugins that we don't know about and that aren't core?

**Comment by proukornew** [comment]
@envygeeks 
Its octopress build

**Comment by envygeeks** [comment]
I don't actually know that much about Octopress (I do use key pieces of it in our stuff but I don't use the whole thing...) so I'm going to defer to @parkr and @imathis or anybody else who does have experience.

**Comment by imathis** [comment]
Sorry about that. It seems that RubyPants (used for smart quotes) doesn't get to smart about escaping content. I removed the plugin from Octopress as there are better ways to get smart quotes in your content than to process an entire page's output. :cringe:

Cheers!

**Comment by envygeeks** [comment]
Yay :tada: thanks @imathis.
