### ISSUE TITLE
Highlight tag was never closed

### ISSUE THREAD

**Issue by danielbarbarito** [jekyll/jekyll#3703]
Whenever I run Jekyll locally I get the error:
"Liquid Exception: highlight tag was never closed in....
jekyll 2.5.3 | Error:  highlight tag was never closed"

When I push the site to Github Pages, however, the site builds fine and works as intended. I tried the fix for this issue that's listed on Jekyll's website which is to put `excerpt_separator: "` in the config file, but that doesn't work either.

**Comment by pathawks** [comment]
Is your source online? Difficult to diagnose without seeing source.
(I imagine it is, since you're using GH Pages)

**Comment by danielbarbarito** [comment]
This is...strange. I ran `jekyll serve --safe` and then the error did not occur. I then ran `jekyll serve` and once again, the error did not occur. I have no clue why that happened but I'm not complaining.

**Comment by pathawks** [comment]
Sounds like you may have had a plugin that was causing the build to fail; safe mode disables plugins.

**Comment by danielbarbarito** [comment]
That makes sense. But why would it work with 'jekyll serve' after though? Wouldn't the plugins be reenabled?
