### ISSUE TITLE
[Performance] Sorting files in Jekyll::Reader

### ISSUE THREAD

**Issue by fw42** [jekyll/jekyll#3705]
When running Jekyll with incremental regeneration on a site with about 6000 files (about 4000 of which are images, the rest is pages), it takes about ~5 seconds on my machine for Jekyll to complete the build (no changes were made, so that's 5 seconds to realize that nothing needs to be done - those 5 seconds run again on every file modification when using watch mode).

I noticed that `Jekyll::Reader` sorts the list of pages and the list of static files that it generates after scanning the filesystem and after profiling it, I saw that it spends a considerable amount of time comparing strings. Removing those calls to `sort_by!` shaves off about 1-1.5 seconds of the mentioned 5 seconds for me (without changing the generated output!).

I couldn't find a reason why the file lists need to be sorted. Nothing in Jekyll seems to depend on it. What am I missing? What's the use case for this?

If this isn't necessary, I can make a PR to remove it.

@parkr @envygeeks thoughts?

**Comment by envygeeks** [comment]
It probably meant something back in Mad Max Times (Ruby 1.8) but now days it's probably meaningless.  Personally (and as always my opinion doesn't reflect on everyone) I say it should go if it provides performance and doesn't break any tests (that that our tests are infallible.)

**Comment by envygeeks** [comment]
Oh, I forgot to put the obligatory :+1: from me.

**Comment by fw42** [comment]
Cool. Will make a PR then.

**Comment by fw42** [comment]
Hm I guess this can potentially change the generated output. Was just a coincidence that it didn't for me.

You can do stuff like
```
{% for file in site.static_files %}
  ...
{% end %}
```

My PR would possibly change the output of that.

Maybe there is another way to fix this. Will think about it some more.

**Comment by envygeeks** [comment]
@parkr what do you think of just adding a sort helper (if we don't already have one) so that users can opt to do that themselves if they wish.

**Comment by fw42** [comment]
maybe we could do something like overwrite the `Site#static_files` method to do the sorting there, on demand, so that at least you only sort things if your template actually references this variable...

**Comment by parkr** [comment]
> maybe we could do something like overwrite the Site#static_files method to do the sorting there, on demand, so that at least you only sort things if your template actually references this variable...

That's not a bad idea at all!
