### ISSUE TITLE
post_url support prepend

### ISSUE THREAD

**Issue by flyboarder** [jekyll/jekyll#3708]
it would be great if we could do:
{% post_url | prepend: site.baseurl %}

Instead of:
{{ site.baseurl }}{% post_url %}

**Comment by flyboarder** [comment]
Or if post_url automatically included the baseurl

**Comment by kleinfreund** [comment]
> Or if post_url automatically included the baseurl

This is not going to happen, because it would break alot of sites plus it's not what's expected.

Also `{% post_url | prepend: site.baseurl %}` should work, because it's a Liquid filter. Have you actually tested that?

**Comment by flyboarder** [comment]
Yes I have! I get the following results:

Error: Could not find post “YYY-MM-DD-POSTNAME | prepend: site.baseurl" in tag 'post_url'. Make sure the post exists and the name is correct.

Looks like post_url takes the entire string including the pipe and whatever follows.

I use 

{{ site.baseurl }}{% post_url YYY-MM-DD-POSTNAME %}

to get around the issue.

Can I ask why site.baseurl is not included? I would assume that if i use post_url it will resolve to the correct url which it doesn’t.

**Comment by envygeeks** [comment]
Because it's not our job to assume how you structure your URL's and why should we break accepted specifications for the web? Such as `<base>` which exists for the exact "problem" you have, but if we include a base fqdn with that we break optimizations people like me do: not sending extra data that browsers address themselves and could be enforced with 301 wildcards on the upper level.

**Comment by parkr** [comment]
> it would be great if we could do:
> {% post_url | prepend: site.baseurl %}

That's a limitation of Liquid – filters only work with double curly brackets, e.g. `{{ some_url | prepend: site.baseurl }}`. We talked about defaulting to adding baseurl but we figured it might actually hurt way more than it would help given how many sites it would likely break (the baseurl would be there twice). We could always have an option like `{% post_url 2015-05-18-hello-world baseurl:true %}` but that hasn't been discussed yet.

**Comment by flyboarder** [comment]
(the baseurl would be there twice)

^How is this? I noticed inconsistency with trying to set this using site.url

if I set site url to include baseurl assets are not loaded correctly (might just be my template)

**Comment by kleinfreund** [comment]
> if I set site url to include baseurl assets are not loaded correctly (might just be my template)

You need to prepend your asset references with `{{ site.baseurl }}` then.

**Comment by parkr** [comment]
`site.url` and `site.baseurl` are very different: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/

**Comment by flyboarder** [comment]
Thanks that clears things up a bit as to how it works, guess the template just isn't including baseurl in any assets so they are freaking out when I push to GitHub. 

Sent from Outlook




On Mon, May 18, 2015 at 12:14 AM -0700, "Parker Moore" <notifications@github.com> wrote:












site.url and site.baseurl are very different: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
