### ISSUE TITLE
Liquid exception: failed to get header

### ISSUE THREAD

**Issue by melissa9407** [jekyll/jekyll#3709]
hi, I would like some help with this problem. I tried to run 'jekyll serve' but I got the following exception

linux-ezrl:/home/melissa/Descargas/portfolio # jekyll serve
Configuration file: /home/melissa/Descargas/portfolio/_config.yml
            Source: /home/melissa/Descargas/portfolio
       Destination: /home/melissa/Descargas/portfolio/_site
      Generating... 
  Liquid Exception: Failed to get header. in _posts/2015-05-16-welcome-to-jekyll.markdown
jekyll 2.5.3 | Error:  Failed to get header.

There are other issues with this problem without solution. I use openSuse 13.2, with the latest version of Ruby, nodeJs and Jekyll installed. Any help would be appreciated.

**Comment by envygeeks** [comment]
Please ask your help question at https://talk.jekyllrb.com/ this area is for bug reports and your problem is caused by a systems problem that should be noted on our help site.
