### ISSUE TITLE
command `jekyll new .` throws an error

### ISSUE THREAD

**Issue by Hemphill** [jekyll/jekyll#3710]
When I issued the command: `jekyll new .` ([per docs](http://jekyllrb.com/docs/quickstart/)) I got the following error:  

    Conflict: /Users/greg/Documents/code/side_projects/blog-attempts/hemphill-jekyll-blog exists and is not empty.

I was in the directory `/Users/greg/Documents/code/side_projects/blog-attempts/hemphill-jekyll-blog` at the time I issued the `jekyll new .` command.

**Comment by chrisfinazzo** [comment]
In the future, please post these kinds of issues on [Jekyll Talk][]. Just to be sure, can you `ls -a` in your current directory? Seems like you may have a typo in the path somewhere that's not in the original issue. Do you have an existing directory structure? Might also be useful to share that if you can...

Usually, I would suggest you run the command w/ `--trace` or enable debugging on the command (See #3695 for an example of how to do this) but I don't know if this works for new installs or just existing sites.

cc @jekyll/core

[Jekyll Talk]: https://talk.jekyllrb.com

**Comment by envygeeks** [comment]
As @chrisfinazzo stated, this area is for bug reports only, please post generic questions at the aforementioned link (https://talk.jekyllrb.com)
