### ISSUE TITLE
Shell not recognizing 'jekyll' command

### ISSUE THREAD

**Issue by bradbergeron-us** [jekyll/jekyll#3722]
Jekyll command not working properly within zsh shell?

here is an output of what zsh gives for feedback when trying to use jekyll comand
zsh: correct 'jekyll' to '_jekyll' [nyae]? n
zsh: command not found: jekyll

**Comment by sondr3** [comment]
It probably means that your `$PATH` doesn't include Ruby gems and such, if you just upgraded to Zsh you need to update your `$PATH` to include them. Just copy over the `$PATH` you had in Bash and you should be fine.

**Comment by envygeeks** [comment]
If you ever have trouble again please feel free to ask for help on https://talk.jekyllrb.com unless you can confirm it's a bug directly related to Jekyll.  Thanks.

**Comment by bradbergeron-us** [comment]
Will do, thank you!

Bradley Bergeron
Cell-(475)201-5153
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1.3]
On Fri, May 22, 2015 at 12:35 AM, jekyll/jekyll
<reply@reply.github.com>
wrote:
If you ever have trouble again please feel free to ask for help on https://talk.jekyllrb.com [https://talk.jekyllrb.com] unless you can confirm it's a bug directly related to Jekyll. Thanks.

—
Reply to this email directly or view it on GitHub
[https://github.com/jekyll/jekyll/issues/3722#issuecomment-104504826] .[https://github.com/notifications/beacon/AIiAh1fUvhWfQqt0eylgP5VzPPq1-gESks5oLqmqgaJpZM4Ejylw.gif]
