### ISSUE TITLE
Jekyll install fails with 'bundle' on Ubuntu 14.04 with Ruby 2.2

### ISSUE THREAD

**Issue by chr-br** [jekyll/jekyll#3737]
I'm following [this guide](https://help.github.com/articles/using-jekyll-with-pages/#installing-jekyll) to install Jekyll to use with a *.github.io site. Step 3 fails for me with `bundle`, here's the output:

	$ bundle install
	Fetching gem metadata from https://rubygems.org/............
	Fetching version metadata from https://rubygems.org/...
	Fetching dependency metadata from https://rubygems.org/..
	Resolving dependencies....

	Your user account isn't allowed to install to the system Rubygems.
	You can cancel this installation and run:

	    bundle install --path vendor/bundle

	to install the gems into ./vendor/bundle/, or you can enter your password
	and install the bundled gems to Rubygems using sudo.

	Password: 

	Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

	    /usr/bin/ruby2.2 -r ./siteconf20150525-5486-4tzjrr.rb extconf.rb
	mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

	extconf failed, exit code 1

	Gem files will remain installed in /tmp/bundler20150525-5486-10tpq9cRedCloth-4.2.9/gems/RedCloth-4.2.9 for inspection.
	Results logged to /tmp/bundler20150525-5486-10tpq9cRedCloth-4.2.9/extensions/x86_64-linux/2.2.0/RedCloth-4.2.9/gem_make.out
	An error occurred while installing RedCloth (4.2.9), and Bundler cannot
	continue.
	Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.

Also, here is my `Gemfile`:

	$ cat Gemfile
	source 'https://rubygems.org'
	gem 'github-pages'

I have not tried installing with `gem install github-pages`, since github's guide recommends against it.

Trying to install `RedCloth` with `gem` also fails:

	$ sudo gem install RedCloth -v '4.2.9'
	ERROR:  While executing gem ... (Gem::FilePermissionError)
	    You don't have write permissions for the /var/lib/gems/2.2.0 directory.
	chrbr@turing:~/Documents/me/github.io/chr-br.github.io$ sudo gem install RedCloth -v '4.2.9'
	Building native extensions.  This could take a while...
	ERROR:  Error installing RedCloth:
		ERROR: Failed to build gem native extension.

	    /usr/bin/ruby2.2 -r ./siteconf20150525-6230-9rpa9y.rb extconf.rb
	mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

	extconf failed, exit code 1

	Gem files will remain installed in /var/lib/gems/2.2.0/gems/RedCloth-4.2.9 for inspection.
	Results logged to /var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/RedCloth-4.2.9/gem_make.out

So it looks like there's something wrong with Ruby's install files. There is no `include` dir in `/usr/lib/ruby`:

	$ ls /usr/lib/ruby
	1.9.1  2.2.0  gems  vendor_ruby

Nor in the two version's subfolders:

	$ ls /usr/lib/ruby/1.9.1/include
	ls: cannot access /usr/lib/ruby/1.9.1/include: No such file or directory
	$ ls /usr/lib/ruby/2.2.0/include
	ls: cannot access /usr/lib/ruby/2.2.0/include: No such file or directory

I am running Ubuntu 14.04. Ruby 1.9.1 is the `ruby` package bundled with Ubuntu 14.04 and Ruby 2.2.0 is the `ruby2.2` package from [Brightbox](https://www.brightbox.com/docs/ruby/ubuntu/)'s repo `ppa:brightbox/ruby-ng`. My default is ruby2.2:

	$ ruby -v
	ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux-gnu]

**Comment by chr-br** [comment]
The same error occurs if I only have Ubuntu's Ruby 1.9 package installed as well. I removed Brightbox's `ruby2.2` package and reinstalled Ubuntu's `ruby` package giving myself Ruby 1.9. Running `bundle install` with the same `Gemfile` gave the same output and errors that you see above.

**Comment by kleinfreund** [comment]
Are the Ruby headers (e.g. `ruby-devel`) installed? It's complaining about a missing ruby.h.

**Comment by chr-br** [comment]
No they weren't! I installed `ruby2.2-dev` and `ruby-dev` and now it seems to have installed fine. Thanks.
