### ISSUE TITLE
3.0.0.pre.beta5 - random front-matter not printing

### ISSUE THREAD

**Issue by jcontonio** [jekyll/jekyll#3740]
I have front-matter that looks like this in my pages

```
zone: "szn"
id: "sln_smn_1"
```

Neither will print, even if I change the key "zone" to "bob" it won't print. Should I be on a newer version of a YAML parser with 3.0.0?

**Comment by envygeeks** [comment]
Why was this closed? Was there a resolution?

**Comment by jcontonio** [comment]
This was me being an idiot =) Totally my bad.
