### ISSUE TITLE
jekyll serve and build --watch do not clean out destination directory

### ISSUE THREAD

**Issue by lvonk** [jekyll/jekyll#3742]
Hi,

I noticed that `jekyll build --watch` and `jekyll serve` do not clean out the destination directory. It is cleaned when I restart both commands, but not while running. Is this intended?

**Comment by parkr** [comment]
Nope. It should be cleaning on each iteration. I don't experience this. Can you provide an example site?

**Comment by parkr** [comment]
Preferably woth the steps you took to get this error.

**Comment by envygeeks** [comment]
What version are you on because I just tested this too and this is what I get on the latest beta:

```
[10:02:17] jordon@envygeeks:~/development/envygeeks/website ~> ll _site
total 52K
drwxr-xr-x+  5 jordon root   4.0K May 28 10:02 .
drwxr-xr-x+ 12 jordon jordon 4.0K May 28 10:02 ..
drwxr-xr-x+  7 jordon root   4.0K May 28 10:02 assets
drwxr-xr-x+  3 jordon root   4.0K May 28 10:02 blog
drwxr-xr-x+  2 jordon root   4.0K May 28 10:02 script
-rw-r--r--   1 jordon root   6.1K May 28 10:02 blog.html
-rw-r-----   1 jordon root      2 May 27 21:54 favicon.ico
-rw-r--r--   1 jordon root   5.3K May 28 10:02 index.html
-rw-r--r--   1 jordon root    391 May 28 10:00 mirrors.txt
-rw-r--r--   1 jordon root   4.6K May 28 10:02 work.html
[10:02:25] jordon@envygeeks:~/development/envygeeks/website ~> mv mirrors.txt ubuntu-mirrors.txt
[10:02:37] jordon@envygeeks:~/development/envygeeks/website ~> ll _site
total 52K
drwxr-xr-x+  5 jordon root   4.0K May 28 10:02 .
drwxr-xr-x+ 12 jordon jordon 4.0K May 28 10:02 ..
drwxr-xr-x+  7 jordon root   4.0K May 28 10:02 assets
drwxr-xr-x+  3 jordon root   4.0K May 28 10:02 blog
drwxr-xr-x+  2 jordon root   4.0K May 28 10:02 script
-rw-r--r--   1 jordon root   6.1K May 28 10:02 blog.html
-rw-r-----   1 jordon root      2 May 27 21:54 favicon.ico
-rw-r--r--   1 jordon root   5.3K May 28 10:02 index.html
-rw-r--r--   1 jordon root    391 May 28 10:00 ubuntu-mirrors.txt
-rw-r--r--   1 jordon root   4.6K May 28 10:02 work.html
```

**Comment by lvonk** [comment]
Tested with ruby 2.2.2

Steps to reproduce

    git clone https://github.com/lvonk/jekyll-3642
    jekyll serve

Make some changes to `_base.sass` and look in the `site` directory. The old css (and css.gz) are still there.

**Comment by envygeeks** [comment]
Who exactly is generating this "css.gz" because that's not a file we would build yeah and if we don't manage (build) that file then we wouldn't know to delete that file.

**Comment by envygeeks** [comment]
Ah yes, you are using jekyll-assets, this seems like a problem that should be taken downstream to them as they are generating and managing this file and they are the ones who should track it's removal.  We do not manage files we do not build.

**Comment by lvonk** [comment]
Ok. Thanks for clarifying!

**Comment by envygeeks** [comment]
If you have any more issues please do let us know!

**Comment by parkr** [comment]
:)
