### ISSUE TITLE
`jekyll clean` doesn't understand `--config`

### ISSUE THREAD

**Issue by superlukas** [jekyll/jekyll#3744]
I'm using 3.0.0.pre.beta5

`jekyll clean -s src -d build` doesn't work either.

---

`config.yml` is at the root of the source tree; the commands are executed from the root as well.

**Comment by superlukas** [comment]
By the way: Is `clean` supposed to remove stuff listed in `keep_files`?

**Comment by envygeeks** [comment]
I don't know if it is but I'd be happy to look into it this week since I would like to integrate the clean command into my build setup. Maybe @parkr can provide some input?

**Comment by parkr** [comment]
> By the way: Is clean supposed to remove stuff listed in keep_files?

Nope.

It should definitely take the build commands. There's a method on `Jekyll::Command` for that, I think.

**Comment by superlukas** [comment]
IIRC (big if) I got the clean command to work one way or another and it removed everything, but please don't take my word for it.

I'm not a ruby guy, but I looked at the source and it looks like it's doing what it's supposed to be doing (i.e., calling `configuration_from_options ` lie the other commands). I guess calling `configuration_from_options` isn't good enough and you'd have to (re-)add them using `add_build_options ` or something?

**Comment by superlukas** [comment]
Did anybody have a chance to look into this? It would be really nice to get this into 3.0 and it shouldn't be too hard to fix.

**Comment by parkr** [comment]
Yeah check out `command.rb`. There's a method in there that should be called.
