### ISSUE TITLE
Allow the addition of arbitrary HTTP headers

### ISSUE THREAD

**Issue by mc10** [jekyll/jekyll#3748]
Sometimes blog users would like to add custom HTTP headers, such as Content-Security-Policy, for their sites that don't make sense to be enabled for all Jekyll sites. It'd be nice if there was an easy way to add these headers to a blog, perhaps through the standard Jekyll configuration files.

**Comment by parkr** [comment]
This is a duplicate issue.

**Comment by mc10** [comment]
Do you know what the original issue is? I did a search but I couldn't find any similar issues.

**Comment by parkr** [comment]
Sure! https://github.com/jekyll/jekyll/issues/3478

**Comment by mc10** [comment]
I saw that issue--I thought that one focused strictly on CSP, so I created a new issue to address *all* headers. If that's not the case, it'd be nice if the title for that issue was altered.
