### ISSUE TITLE
How to return Liquid output before Markdownify front matter content?

### ISSUE THREAD

**Issue by cpicanco** [jekyll/jekyll#3753]
Hi everyone,

If you have some post with some Liquid markup, say

  _posts/YYYY-MM-DD-some-front-matter.md:
```
---
author: someone
---
content should be some Liquid output:
{% site.url %}

```

how to return the Liquid outputs using the `markdownify` filter?

For example, I am using the `markdownify` to filter the `page.content` in a layout:

 - _layouts/some-layout.html:
```
{{ page.content | markdownify }}
```

The previous code returns everything in markdown and Liquid markup strings {% site.url %}. How to return Liquid markup output instead?

**Comment by envygeeks** [comment]
I hate to do this to you but on principle I must close this ticket without answer and ask you to post your question on talk.jekyllrb.com because this ticket system is for bugs only.

**Comment by cpicanco** [comment]
Thank you @envygeeks , my fault.
