### ISSUE TITLE
docs typo 'pagination_path' to 'paginate_path'

### ISSUE THREAD

**Issue by cpicanco** [jekyll/jekyll#3759]
>Pagination only works within HTML files

> Pagination does not work from within Markdown or Textile files from your Jekyll site. Pagination works when called from within the HTML file, named index.html, which optionally may reside in and produce pagination from within a subdirectory, via the `pagination_path` configuration value.

There is no `pagination_path` config accessible from the configuration file, but `paginate_path`.

**Comment by envygeeks** [comment]
For documentation corrections please do not open tickets, the preferable path here would be to submit a correction directly to us.  While we normally would not ask directly for pull requests something like this is simple for anybody to do.

You can edit directly from Github, simply visit: https://github.com/jekyll/jekyll/tree/master/site and follow the path from the URL on https://jekyllrb.com, upon correction simply create a branch (a so-called feature branch) and in the message be explicit about what you corrected.  Upon submission Github will take you directly to a pull request where you can submit for the correction.

Thanks!

**Comment by envygeeks** [comment]
This wasn't meant to be closed sorry, it was meant to only inform you of how you can fix the problem.

**Comment by cpicanco** [comment]
Thank you!
