### ISSUE TITLE
Jekyll 3.0.0 Beta 5 - Marshal Data Too Short

### ISSUE THREAD

**Issue by lcizzle** [jekyll/jekyll#3761]
I am in the process of upgrading an old Jekyll template site I used to make other websites. For the life of me I can't get it to work with newer versions of Jekyll.

If I try to build the site with just Jekyll I receive the following unhelpful error.

    PS D:\Development\Git\Projects\jekyll-stack> jekyll build
    Configuration file: D:/Development/Git/Projects/jekyll-stack/_config.yml
    jekyll 3.0.0.pre.beta5 | Error:  marshal data too short
    PS D:\Development\Git\Projects\jekyll-stack>

Here is a copy of the config.

    # Jekyll Config

    source      : src/_pages
    posts       : src/_posts
    layouts     : src/_layouts

    plugins     : src/_plugins

    destination : dist

    keep_files  : [ 'css', 'fonts', 'images', 'js' ]

    safe        : false
    markdown    : kramdown

If  I use grunt to build I receive the following.

    PS D:\Development\Git\Projects\jekyll-stack> grunt build                        
    Running "less:screen" (less) task                                               
    File dist/css/screen.css created: 0 B → 169.38 kB                               
                                                                                
    Running "uglify:site" (uglify) task                                             
    File dist/js/site.js created: 274.88 kB → 98.27 kB                              
                                                                                
    Running "copy:images" (copy) task                                               
    Created 1 directories                                                           
                                                                                
    Running "exec:jekyll" (exec) task                                               
    Configuration file: _config.yml                                                 
    D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B1/lib/ruby
    /gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:164:in `load' 
    : marshal data too short (ArgumentError)                                     
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:164:
    in `read_metadata'                                                              
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:9:in
     `initialize'                                                                   
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:34:in `new'
                                                                                
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:34:in `init
    ialize'                                                                         
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/commands/build.rb:3
    0:in `new'                                                                      
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/commands/build.rb:3
    0:in `process'                                                                  
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/commands/build.rb:1
    8:in `block (2 levels) in init_with_program'                                    
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call
    '                                                                               
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `bloc
    k in execute'                                                                   
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each
    '                                                                               
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `exec
    ute'                                                                            
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'  
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'     
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/bin/jekyll:17:in `<top (requir
    ed)>'                                                                           
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/bin/jekyll:23:in `load'                                                       
    from D:/Programs/Development/Languages/Ruby/x64/2.2.2-Base-Jekyll-3.0.0B
    1/bin/jekyll:23:in `<main>'                                                     
    Exited with code: 1.                                                         
    Warning: Task "exec:jekyll" failed. Use --force to continue.                    
                                                                                
    Aborted due to warnings.                                                        
    PS D:\Development\Git\Projects\jekyll-stack>  

Any help would be great.

**Comment by envygeeks** [comment]
This is related to the Marshal changes that @fw42 implemented to speed up Jekyll.  For now you can jump back to 3.0.0.beta4 and this will not happen.  Really that's pretty much the only thing that changed between beta5 and beta4.

**Comment by lcizzle** [comment]
I'll try that out and report back. Thanks.

**Comment by fw42** [comment]
Hm that's odd. I wonder why [this test](https://github.com/jekyll/jekyll/blob/bba7870f8baed7c871b53901eecce5abb6dab376/test/test_regenerator.rb#L182-L190) doesn't catch that.

**Comment by fw42** [comment]
`ArgumentError` (which is what you are getting) is explicitly being rescued [here](https://github.com/jekyll/jekyll/blob/bba7870f8baed7c871b53901eecce5abb6dab376/lib/jekyll/regenerator.rb#L167). Which exact version are you on?

**Comment by fw42** [comment]
ah beta5, hm

**Comment by fw42** [comment]
I guess beta5 doesn't include https://github.com/jekyll/jekyll/commit/376c87b62ee0b38bb4f157288a6fbc32d2acae32 yet? Time for beta6?

**Comment by envygeeks** [comment]
I thought we cut beta5 after?

**Comment by envygeeks** [comment]
Hold up, let me ping @parkr and get him to cut a new beta.

**Comment by parkr** [comment]
Hmmmm... I thought we did too. Just cut beta6.

**Comment by fw42** [comment]
@lcizzle can you try again with the latest gem version? (beta6)

**Comment by lcizzle** [comment]
Works fine now thanks.

**Comment by mmistakes** [comment]
Just tried building a test site and noticed the marshal data too short message in beta 8 on a Windows 7 box. Site was generated with `jekyll new` and not modified.

```
E:\> jekyll -v
jekyll 3.0.0.pre.beta8

jekyll new test-site
New jekyll site installed in E:/test-site.

E:\test-site>jekyll build
Configuration file: E:/test-site/_config.yml
            Source: E:/test-site
       Destination: E:/test-site/_site

 Incremental build: enabled
      Generating...
                    done in 0.461 seconds.
 Auto-regeneration: disabled. Use --watch to enable.


E:\test-site>jekyll build
Configuration file: E:/test-site/_config.yml
Failed to load E:/test-site/.jekyll-metadata: marshal data too short
            Source: E:/test-site
       Destination: E:/test-site/_site

 Incremental build: enabled
      Generating...
                    done in 0.351 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by envygeeks** [comment]
Try running `jekyll clean` to remove the metadata and see if that solves it please.

**Comment by mmistakes** [comment]
This was the first thing I tried. Also this was with a brand new Jekyll
site so it started clean with only the config, layouts, posts, assets, etc
that come with `jekyll new`.

Seems to only be a Windows issue because I had zero problems with Mac OS X.

**Comment by fw42** [comment]
Interesting. I don't have a Windows machine to try this out. What does the metadata file look like after you create a new site? Is it empty?

**Comment by mmistakes** [comment]
Running `jekyll build` on a clean site creates a new `.jekyll-metadata` file that is 2.72 KB. 

On the second build it triggers the `marshal data too short` and updates the modified date of the metadata file but doesn't appear to do anything else (file size and contents are the same from the first build).

Anything else I can look at to help?

**Comment by fw42** [comment]
Can you run `Marshal.load(Marshal.dump({}))` in an `irb` shell on your Windows machine?

**Comment by fw42** [comment]
also, can you add this file to the directory of your (new, empty) site and run it with Ruby?

```ruby
require 'jekyll'

module Foo
  def write_metadata
    puts "Metadata: #{metadata.inspect}"
    super
  end
end

Jekyll::Regenerator.prepend(Foo)

Jekyll::Commands::Build.process({'full_rebuild' => true})
```

It will trigger a rebuild of your site. On my (Mac OS X) machine it prints a line that says `Metadata: {}`. Does it do the same for you?

**Comment by mmistakes** [comment]
Running `Marshal.load(Marshal.dump({}))` prints `=> {}`

Running the Ruby file prints this:

```
E:\test-site> ruby rebuild.rb
rebuild.rb:10:in '<main>': private method 'prepend' called for Jekyll::Regenerateor:Class (NoMethodError)
```

**Comment by fw42** [comment]
hrm... old ruby version...

**Comment by mmistakes** [comment]
Looks like it. `ruby 2.0.0.p594`
I'm on a work machine so don't have the luxury of upgrading it.

**Comment by envygeeks** [comment]
We support 2.0+ so there is no reason for you to upgrade until it's EOL.

**Comment by fw42** [comment]
nah the original error is not about ruby... just that my little patch fails because of his old ruby :) will write a 2.0 compatible one later..

**Comment by envygeeks** [comment]
Well if you guys can't figure it out I'd be happy to get on my Windows box when I get unlazy since I've already got a host of stuff I need to checkout there anyways.  I don't know if you are a Rubyist @mmistakes so I'd be happy to jump into pry and see what is going on.

**Comment by mmistakes** [comment]
I'm definitely not a Rubyist but so I'll defer to you guys on that. But I
can certainly help test things.

**Comment by envygeeks** [comment]
Please file a new ticket and /cc both me and @fw42 then please so we can track this issue properly.
