### ISSUE TITLE
Site wont build since update to Fedora 22

### ISSUE THREAD

**Issue by juancancela** [jekyll/jekyll#3765]
I wont be able to build or serve my site locally since i updated to Fedora 22.
I've tried reinstalling Ruby and extensions, but no luck. 
This is the message im getting:

[bak@localhost juancancela.github.io]$ jekyll serve
Configuration file: /home/bak/WebstormProjects/juancancela.github.io/_config.yml
            Source: /home/bak/WebstormProjects/juancancela.github.io
       Destination: /home/bak/WebstormProjects/juancancela.github.io/_site
      Generating... 
     Build Warning: Layout 'none' requested in feed.xml does not exist.
                    done.
E, [2015-06-07T16:36:35.872747 #18790] ERROR -- : Actor crashed!
LoadError: libruby.so.2.1: cannot open shared object file: No such file or directory - /home/bak/.gem/ruby/extensions/x86_64-linux/ffi-1.9.8/ffi_c.so
	/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	/home/bak/.gem/ruby/gems/ffi-1.9.8/lib/ffi.rb:18:in `rescue in <top (required)>'
	/home/bak/.gem/ruby/gems/ffi-1.9.8/lib/ffi.rb:3:in `<top (required)>'
	/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	/home/bak/.gem/ruby/gems/rb-inotify-0.9.5/lib/rb-inotify/native.rb:1:in `<top (required)>'
	/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	/home/bak/.gem/ruby/gems/rb-inotify-0.9.5/lib/rb-inotify.rb:1:in `<top (required)>'
	/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	/home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/adapter/linux.rb:29:in `_configure'
	/home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/adapter/base.rb:50:in `block in configure'
	/home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/adapter/base.rb:41:in `each'
	/home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/adapter/base.rb:41:in `configure'
	/home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/adapter/base.rb:55:in `start'
	/home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	/home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	/home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	/home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	/home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	/home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	/home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	/home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': libruby.so.2.1: cannot open shared object file: No such file or directory - /home/bak/.gem/ruby/extensions/x86_64-linux/ffi-1.9.8/ffi_c.so (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/bak/.gem/ruby/gems/ffi-1.9.8/lib/ffi.rb:18:in `rescue in <top (required)>'
	from /home/bak/.gem/ruby/gems/ffi-1.9.8/lib/ffi.rb:3:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/bak/.gem/ruby/gems/rb-inotify-0.9.5/lib/rb-inotify/native.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/bak/.gem/ruby/gems/rb-inotify-0.9.5/lib/rb-inotify.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/adapter/linux.rb:29:in `_configure'
	from /home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/adapter/base.rb:50:in `block in configure'
	from /home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/adapter/base.rb:41:in `each'
	from /home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/adapter/base.rb:41:in `configure'
	from /home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/adapter/base.rb:55:in `start'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	from /home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/listener.rb:268:in `_start_adapter'
	from /home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/listener.rb:93:in `block in <class:Listener>'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/fsm.rb:175:in `instance_eval'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/fsm.rb:175:in `call'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/fsm.rb:127:in `transition_with_callbacks!'
	from /home/bak/.gem/ruby/gems/celluloid-0.16.0/lib/celluloid/fsm.rb:95:in `transition'
	from /home/bak/.gem/ruby/gems/listen-2.10.0/lib/listen/listener.rb:100:in `start'
	from /home/bak/.gem/ruby/gems/jekyll-watch-1.2.1/lib/jekyll/watcher.rb:8:in `watch'
	from /home/bak/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:68:in `watch'
	from /home/bak/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:38:in `process'
	from /home/bak/.gem/ruby/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /home/bak/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/bak/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/bak/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/bak/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/bak/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/bak/.gem/ruby/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/bak/.gem/ruby/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /home/bak/bin/jekyll:23:in `load'
	from /home/bak/bin/jekyll:23:in `<main>'

**Comment by envygeeks** [comment]
This is a problem with your Ruby installation.  Please try reinstalling your Ruby. While in the past we might of helped you with these types of problems on this bug tracker we no longer help with generic questions unrelated to actual bugs in Jekyll on this tracker.  Please move your question https://talk.jekyllrb.com where somebody who uses Fedora might be able to help you.

Thanks!
