### ISSUE TITLE
Trouble instaling in Yosemite (10.10.2)

### ISSUE THREAD

**Issue by Hipomenes** [jekyll/jekyll#3766]
I've been trying to install Jekyll, but I keep getting the following ERROR:

ERROR:  Error installing jekyll:
ERROR: Failed to build gem native extension. /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r ./siteconf20150607-2310-1an9jd5.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h
extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/fast-stemmer-1.0.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/fast-stemmer-1.0.2/gem_make.out

If tried everything suggested in the troubleshooting, short of installing the 3 GB Xcode, that I don't plan to ever use in my life. Any suggestions? 

Thanks! 
david

**Comment by envygeeks** [comment]
Hello.  While I regret to say this I must ask that you take this non-bug issue and post it on https://talk.jekyllrb.com because this is not a bug directly related to Jekyll and this ticket system is only for Jekyll bugs.

Thanks.
