### ISSUE TITLE
--trace doesn't print stack trace for invalid custom markdown converters

### ISSUE THREAD

**Issue by TWiStErRob** [jekyll/jekyll#3773]
Forking off from #3770.

`jekyll build --trace` doesn't print stack trace even though there's a [`raise Errors::FatalException`](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/converters/markdown.rb).

To reproduce change `markdown:` to an invalid value in `_config.yml`.

```text
Invalid Markdown Processor: KramdownPygments
                    Valid options are [ maruku | rdiscount | kramdown | redcarpet ]
  Conversion error: Jekyll::Converters::Markdown encountered an error converting '_posts/....md/#excerpt'.
  Conversion error: Invalid Markdown Processor: KramdownPygments
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid Markdown Processor: KramdownPygments
```

The conversation from #3770 related to this:
> `jekyll serve --skip-initial-build` suggest
Error: Run jekyll build --trace for more information.
    - TWiStErRob

> The suggestion of trace is a default message just incase, but there was no error thrown so there could be no trace, we defensively program in Markdown checks rather than failing, you can only have a trace if there was an exception... there was no exception.
    - envygeeks

> ... but there's a `raise Errors::FatalException` there...
    - TWiStErRob

> You are right and I don't remember if RuntimeError is caught by a standard rescue. This is more than likely a bug but this should be filed separately of this issue because the lack of more context and --trace while related in your case are unrelated in general.
    - envygeeks

**Comment by parkr** [comment]
This appears to be a factor of how [`Jekyll::Command.process_site` works](https://github.com/jekyll/jekyll/blob/224a1ab9efefea5b9c7aadc8bab3446ce7e8b17e/lib/jekyll/command.rb#L29-L33). Let's see if I can figure out something better.
