### ISSUE TITLE
Is there a way to insert continuous music in jekyll website?

### ISSUE THREAD

**Issue by AntiMoron** [jekyll/jekyll#3774]
I wanna insert a music into my github blog(generated by jekyll).

I added music in ```index.html``` with ```<EMBED src="bgm.mp3"/>``` .
But I didn't find a method to make music keep playing after click posts' titles.
Is there a way to insert continuous music in jekyll website?

**Comment by envygeeks** [comment]
I am sorry I have to do this but on principle I must close your ticket and ask that you post your question onto https://talk.jekyllrb.com because this ticket system is for bugs only.  Thanks.

**Comment by AntiMoron** [comment]
roger, sorry for the trouble I made.

**Comment by envygeeks** [comment]
There was no trouble and I'm sorry if I implied there was.  We just like to have people use the forum now because that medium was created just for these kind of questions where discussions can go on forever!
