### ISSUE TITLE
Pygments' hl_lines option is sanitized incorrectly

### ISSUE THREAD

**Issue by TWiStErRob** [jekyll/jekyll#3776]
#2642 introduced correct support for Pygments `hl_lines` in the first commit, and then immediately [broke it in the next one](https://github.com/jekyll/jekyll/commit/3cb2e74b5c93e837d08182d735ebb8a5fd793ced#diff-7dbeb1c0a6ca43d2d580a95ed86deb26R66). /cc @parkr

Pygments has [`hl_lines`](http://pygments.org/docs/formatters/), but you whitelisted [`hl_linenos`](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/tags/highlight.rb#L67) which leads to **line highlighting not available in safe mode**.

```html
<style>.hll, .special { color: red !important; }</style>
{% highlight text linenos=table hl_linenos=2 %}
hl_linenos=2
line2
line3
line4
{% endhighlight %}

{% highlight text linenos=table hl_lines=2 %}
hl_lines=2
line2
line3
line4
{% endhighlight %}

{% highlight text linenos=table linenospecial=2 %}
linenospecial=2
line2
line3
line4
{% endhighlight %}

{% highlight text linenos=table hl_linenos=2 hl_lines=3 linenospecial=4 %}
hl_linenos=2 hl_lines=3 linenospecial=4
line2
line3
line4
{% endhighlight %}
```

![image](https://cloud.githubusercontent.com/assets/2906988/8082264/3ff5bc28-0f7c-11e5-813e-f328ce7bc3eb.png)

So `hl_lines` works only in non-safe mode. There was probably never a `hl_linenos` option, you invented that I guess. `linenospecial` is useless because it somehow pollutes the previous highlight as well and can only highlight one line.

**Comment by parkr** [comment]
Ok, would you mind updating this so that it works for you in safe mode and submitting a PR?
