### ISSUE TITLE
Liquid/Pygments comments highlight

### ISSUE THREAD

**Issue by hacdias** [jekyll/jekyll#3784]
Hello!

I'm new to Jekyll and when I was moving my WordPress posts I had some problems with the syntax highlight. I don't know if it is a bug, but there is the issue.

I have this in my post:

```markdown
{% highlight php %}
    /**
     * This function get the content of 'url' variable
     * of HTTP GET method. See the .htaccess for more
     * information.
     */
    private function _getUrl()
    {
        $url = isset($_GET['url']) ? $_GET['url'] : null;
        $url = rtrim($url, '/');
        $url = filter_var($url, FILTER_SANITIZE_URL);
        $this->_url = explode('/', $url);
    }
{% endhighlight %}
```

I want to show this:

```php
    /**
     * This function get the content of 'url' variable
     * of HTTP GET method. See the .htaccess for more
     * information.
     */
    private function _getUrl()
    {
        $url = isset($_GET['url']) ? $_GET['url'] : null;
        $url = rtrim($url, '/');
        $url = filter_var($url, FILTER_SANITIZE_URL);
        $this->_url = explode('/', $url);
    }
```

**But** it converts it to:

```php
    /**
* This function get the content of 'url' variable
* of HTTP GET method. See the .htaccess for more
* information.
*/
    private function _getUrl()
    {
        $url = isset($_GET['url']) ? $_GET['url'] : null;
        $url = rtrim($url, '/');
        $url = filter_var($url, FILTER_SANITIZE_URL);
        $this->_url = explode('/', $url);
    }
```

The best regards :)

**Comment by envygeeks** [comment]
It would help if we knew what version of Jekyll you are on.

**Comment by hacdias** [comment]
Ooops! Here it is:

**Ruby**: ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]
**Jekyll**: v2.5.3
**pygments.rb**: v0.6.3

If you want something more, say =D

**Comment by envygeeks** [comment]
Can you please try with --pre flag and see if this is still the case on the latest beta? Thanks.

**Comment by hacdias** [comment]
@envygeeks the latest pre-release version still has this issue. Thanks for answering.

**Comment by parkr** [comment]
We do [strip newlines from code](https://github.com/jekyll/jekyll/blob/407fc82b2d822ace149dfaf6ee74991163a9e2b6/lib/jekyll/tags/highlight.rb#L45) but that's only newlines at the very beginning and very end of the code. Not sure what could be causing this. Out of curiosity, why not left-align that snippet?

**Comment by hacdias** [comment]
@envygeeks I think this problem isn't only related with Windows! I'm running my Jekyll Website on Github and I also have that problem (see here: [article](https://henriquedias.com/tutorials/mvc-linguagem-php-ii/) and [source](https://raw.githubusercontent.com/hacdias/hacdias.github.io/master/_posts/2014-12-19-mvc-linguagem-php-ii.markdown)).

@parkr I haven't left-aligned that snippet because I simply pasted it here from a class. =D

**Comment by envygeeks** [comment]
OK.  Everybody has this one wrong.  This has nothing to do with Windows or Linux or anything as a matter of factly, this has to do with somebody using horrible CSS... it could be us it could be them/you?
```
.highlight pre code * {
  /* white-space: nowrap; */
}
```

Removing that line (aka the comment that you see) fixed this problem and realigned all comments.

**Comment by envygeeks** [comment]
Are we the ones adding that? If so then I'll work on that CSS and correct it if somebody tells me what their goal was with that, but if it's you who added it, then remove that or move it higher up the chain.

**Comment by hacdias** [comment]
Ooops. Ahah. That's a little of css which comes with the theme I'm using. Thanks, a lot, for helping! =D
