### ISSUE TITLE
Serving locally with regeneration gives "invalid byte sequence in US-ASCII"

### ISSUE THREAD

**Issue by harpojaeger** [jekyll/jekyll#3788]
Jekyll 2.5.3.  Encoding: utf-8 in config.yml.  I've searched all files for non-ASCII characters and removed them (I think).  The funny thing is that this *only* happens on regeneration, not the initial build, and not at all using the build command, rather than serve.  The regen works the first time, dumps this error and then stops working.

**Comment by envygeeks** [comment]
Can you please try with `--pre` 3.0.0.beta6 and let us know if this still happens? What version of Ruby?

**Comment by harpojaeger** [comment]
Ruby 2.1.2pn5.  I'm new to Ruby – how do I install a beta version of a gem?

**Comment by envygeeks** [comment]
As mentioned, use the `--pre` flag when you gem install.  Or if you use a Gemfile, target that version directly or if you don't want to deal with any of that use the Docker image `jekyll/jekyll:beta`... to add are you on Windows? This is a common problem on Windows.

**Comment by harpojaeger** [comment]
Nope, OX X – sorry for not mentioning this from the beginning.  Installing 3.0.0.beta6 has fixed the issue!  Cool!  Thanks for the quick turnaround and useful comments.

**Comment by harpojaeger** [comment]
Just a note: incremental site updating is totally awesome.  I'd never been able to use it before.  This makes my life so much easier.  Thanks for your work!

**Comment by envygeeks** [comment]
Yes @alfredxing did a great job on that, he deserves many :cake: for it.

**Comment by parkr** [comment]
And @mattr-! :) All the :cake:s.
