### ISSUE TITLE
Jekyll local development over https

### ISSUE THREAD

**Issue by mattfelten** [jekyll/jekyll#3791]
Is there a way to run jekyll locally and have it run securely? I'm doing some AJAX posts to a remote server that is https only and I'm getting insecure content errors. Trying to figure out a better way of doing this.

**Comment by troyswanson** [comment]
Probably not a great way to do this, since there (should) be a CORS issue.
The best thing (imo) would be to create a mock service running on your
computer or tied into the JS framework that you're using to simulate
responses from the server.

**Comment by envygeeks** [comment]
I'm adding in custom headers anyways right now because I need a few custom headers to fix the caching issues in chrome (which seems to always suck here lately) so I might as well add in support for https too, since it's nothing more than checking for a few configuration options and a cert.

**Comment by mattfelten** [comment]
@troyswanson I can solve the CORS issue easily enough, but because it's sending to https from http, that part is tougher.

@envygeeks That would be awesome!
