### ISSUE TITLE
Unable to launch Jekyll serve

### ISSUE THREAD

**Issue by TaylorHuston** [jekyll/jekyll#3797]
I'm getting the following error message.

OSX. Ruby v 2.2.2

```
/usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:21:in `block in <top (required)>': cannot load such file -- jekyll/version (LoadError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:18:in `program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by envygeeks** [comment]
We are going to need way more information on this @TaylorHuston because that is a very edgy case.  Can you give us exact steps.  Have you tried reinstalling? What are the contents of the base folder? What is the RubyGems version?

**Comment by parkr** [comment]
@TaylorHuston This reminds me of the errors we used to see when there were conflicting dependencies. Add a `Gemfile` to your project and run `bundle exec jekyll serve`.

**Comment by TaylorHuston** [comment]
Exact steps: Opening a terminal windows in my project root and typing in 'jekyll serve'

@parkr Running `bundle exec jekyll serve` worked! Any idea why?

**Comment by envygeeks** [comment]
Because you did `bundle install --path vendor/bundle` or the like and put it into a local install instead of a system wide install.  Remove the `.bundle` folder and `bundle install` without any arguments if you want it to globally install with shared gems.

**Comment by TaylorHuston** [comment]
@envygeeks I can safely say I've never ran a command like that. Just `bundle install` and the occasional `bundle update`. Only been working with Rails for a few weeks, haven't gotten into anything particularly advanced yet.

Oh well, no biggy it works now. Thanks for the prompt response!

**Comment by envygeeks** [comment]
That's weird then because normally bundler will install globally unless you request a local install unless it can't get hold of sudo, I don't actually know what happens in that scenario since I've never experienced that case could that be what's happening?

I can give you one tip that might save you trouble in the future if bundler keeps acting like that: `rm -rf .bundle Gemfile.lock && gem install -g Gemfile` and it'll install your Gemfile gems (as long as they don't use Git) using RubyGem's.

**Comment by parkr** [comment]
> @parkr Running bundle exec jekyll serve worked! Any idea why?

@TaylorHuston Glad it works! The problem is that Bundler ran into a version conflict or otherwise couldn't load Jekyll with our integration.

**Comment by parkr** [comment]
[`Bundler.setup` should have fixed this problem.](https://github.com/jekyll/jekyll/blob/5647b9168941228dfff696cec10ac4731213a4b5/lib/jekyll/plugin_manager.rb#L35-L48)

Can you see if the 3.0 beta works for you without `bundle exec`? http://jekyllrb.com/docs/installation/#pre-releases
