### ISSUE TITLE
could not download

### ISSUE THREAD

**Issue by carmelo006** [jekyll/jekyll#3799]
ERROR:  Could not find a valid gem 'jekyll' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)

but i can download https://rubygems.org/latest_specs.4.8.gz in my browser

**Comment by parkr** [comment]
This could be a problem with a firewall or your installation of RubyGems. Check out #1409.

**Comment by carmelo006** [comment]
follow your guide, the problem was solved.
thank you very much
