### ISSUE TITLE
Incremental regeneration

### ISSUE THREAD

**Issue by zanshin** [jekyll/jekyll#380]
Can some form of incremental regeneration (ala https://github.com/graysky/jekyll/commit/39ae8c7c3f4a3cffd095e3b7638cfa8025c5a67a) be added to the core of Jekyll? This would greatly enhance the tool for those sites (like mine) that have nearly 1800 entries and counting, and which take upwards of 5 minutes to generate.

**Comment by parkr** [comment]
#3116 solves this, at least as a first iteration. If you have time, I'd appreciate it if y'all could try building your sites with the current `master` and see how it works out for you.

**Comment by parkr** [comment]
Going to close this.
