### ISSUE TITLE
collection file being served as raw file (with no extension) if permalink does not end with "/" 

### ISSUE THREAD

**Issue by 0a-** [jekyll/jekyll#3800]
Suppose I have a collection cats and have this in the front matter of one of the files in `_cat/`

```yaml
---
permalink: pageURL
---
```

when visiting http://domain/pageURL browser will treat it as raw file and download it. (Setting `output_ext: ".html"` for the collection in `_config.yml` would yield no change.)

However if I have it as

```yaml
---
permalink: pageURL.html
---
```

or 

```yaml
---
permalink: pageURL/
---
```

the file would be served as a html file instead.  (and visiting http://domain/pageURL would go to http://domain/pageUR/ )

Apparently this happens only to collections files because they support multi formats. For `post` files, even permalink without ending of `/` will still be served as `.html`.

**Comment by walutisme** [comment]
Try make a new page on jekyll root folder, set it permalink like this:

```yaml
# filename: test.md
---
permalink: test
---
```

Test it

```bash
bundle exec jekyll build --limit_posts 1
```

Check your build folder. There's a file named `test` without extension.

I hope you can understand this.

**Comment by 0a-** [comment]
@mojombo I think you didn't get what I mean. Pages and posts both work well with permalink. The raw-file-serving is only happening to collections files.

**Comment by envygeeks** [comment]
You pinged the wrong user.

**Comment by 0a-** [comment]
@envygeeks Gosh.. How did that happen...

**Comment by walutisme** [comment]
Well then there's a problem on jekyll collection part. I dont know much, never used it. I just want to explain that raw-file-serving thing are happen to page too if we set it permalink wrong

**Comment by Lewiscowles1986** [comment]
Does this depend upon the web-server, in which case it is not Jekyll specific issue?

Also I can't see a way around this, because what if I want Jekyll to generate a file without extension? Fixing this would break that

**Comment by willnorris** [comment]
@0a- what is the name of the source file that is causing this?  Do you have this in a public repo somewhere?  I'm not able to reproduce this behavior locally (I still get an output file of `pageURL.html` even with `permalink: pageURL`), so a good first step would be to see if we can get someone to reproduce what you're seeing.

And just to confirm, what version of jekyll are you running?

**Comment by Lewiscowles1986** [comment]
@willnorris 2.5.3 for me on Windows

```
---
title: clients
permalink: clients
---

```

generates /_site/clients #no extension

**Comment by willnorris** [comment]
have you tried this with any of the jekyll-3 releases?  A lot of work went into permalinks for jekyll-3 which *should* handle this case.  I'm actually not sure what the expected behavior for this would be for jekyll 2.x

**Comment by 0a-** [comment]
oops my bad I forgot to mention the version I was using. Yup @Lewiscowles1986 the phenomenon occurs in version 2.4.0 @willnorris I Just tested it on `jekyll 3.0.0.pre.beta7` and the file isn't severed raw :+1: Great work

**Comment by 0a-** [comment]
Looks like it was fixed in [0d1586a5c471d322a79177e3e9c2f5813c697c32](https://github.com/jekyll/jekyll/commit/0d1586a5c471d322a79177e3e9c2f5813c697c32)

**Comment by Lewiscowles1986** [comment]
Just so I understand, @willnorris broke the ability to have permalinks without extension in the unstable and yet-to-be-released, and everyone but me is happy that now we cannot do something we could do before? :-1:

**Comment by envygeeks** [comment]
@Lewiscowles1986 the author explicitly said that was not the case for him, is there something that you can input that would lead us to believe it would not be the case for you as well?

**Comment by Lewiscowles1986** [comment]
If I specify no extension, with no trailing slash; of course I want a file with no extension. It is EXACTLY what I have just told the computer I want... Also worth thinking about, is that collections do not need a permalink in the front-matter, and this does not damage content...

If without an optional permalink being included this happened, I would be 100% on-board that this is a bug; But this only happens when we intentionally break the permalink AFAIM, in the same way you can construct an SQL statement that will not run, or will run and damage the DB; MySQL, SQLite etc do not "shield" the user from this. I think Jekyll should take the same approach.

It is almost always better to educate your users to understand they need the trailing slash or desired file-extension, rather than coddle them, or teach them software should perform actions to correct human behavior, even when explicit... This is where I am coming from

**Comment by parkr** [comment]
Lewis, please don't jump to conclusions. Your comments feel unnecessarily accusatory and it makes those of us spending our free time on this really unwilling to help you.

Will Norris fixed this issue if I read correctly. It should now generate a .html file and support an extensionless path in the request.

**Comment by Lewiscowles1986** [comment]
Sorry, I am not jumping to conclusions, the "fix" breaks something that worked before, it is really really simple. I am not accusing Will of knowingly breaking others work-flow, but I am saying that is the end result.

**Comment by parkr** [comment]
The trouble is that permalink is the output value of `page.url` in Liquid. If you want a clean URL with no extension, but wanted the output file to contain the extension so the server knew what MIME Type to use, you were previously out of luck. What is your use-case for a file on the filesystem with no extension on your Jekyll site?

**Comment by Lewiscowles1986** [comment]
Forced download of a file via browser, possibly a script
