### ISSUE TITLE
Merge PostReader and DraftReader?

### ISSUE THREAD

**Issue by alexbuzzbee** [jekyll/jekyll#3801]
Code Climate reports that Jekyll::PostReader and Jekyll::DraftReader are almost identical. maybe they should be merged? Perhaps just a PostReader with a 'draft' flag?

**Comment by envygeeks** [comment]
We are well aware of these issues and it's being worked on.

**Comment by parkr** [comment]
#3690 will make this obsolete.

**Comment by alexbuzzbee** [comment]
@parkr: Got it. Closed.
