### ISSUE TITLE
Introduce new file naming for posts

### ISSUE THREAD

**Issue by penibelst** [jekyll/jekyll#3804]
## Status quo

All posts live in the `_posts` directory. Each file is named `YYYY-MM-DD-name.EXT`. As the post count grows, the directory becomes unclear. An example: [Rails Blog](https://github.com/rails/weblog/tree/gh-pages/_posts) with more than 1000 posts.

## Proposal

I would allow to cluster the date part into dedicated subdirectories: `YYYY/MM/DD/name.EXT`. This structure is easy to understand for humans, like the current structure does. But this way the usability scales. And I feel it’s easier to move a post from drafts to published posts.

```
_posts
  |__2004
  |__2007
  |__2008
    |__11
      |__17
        |__blogging-like-a-hacker.md
  |__2010
  |__2011
  |__2015
```

I think both structures even could live side by side in the same `_posts` directory without breaking each other. What do you think?

**Comment by envygeeks** [comment]
Posts are becoming collections I'm wondering if this is rendered moot by that?

**Comment by envygeeks** [comment]
What I mean is, don't collections support sub-folder hierarchies?  I don't remember exactly.

**Comment by pathawks** [comment]
Posts already support sub folders.
The filename must keep the same date syntax, but there’s nothing currently stopping a site from moving posts into a `_posts/2015/` directory.

**Comment by envygeeks** [comment]
Optimization is what stops them from doing that, Jekyll will start creating a ton of categories.

**Comment by penibelst** [comment]
You are right, it’s already possible to move posts into sub folders. But this pattern is not obvious for most users. I’ve never seen its usage in the wild. And as @envygeeks pointed out, sub folders trigger categories creation.

My proposal is a long-term goal. Busy Jekyll users (often than monthly) like Rails boys or @benbalter will write a lot in the next years. I don’t want to distract them by a huge amount of own posts every time they open the posts folder.

**Comment by Lewiscowles1986** [comment]
I think it's a perfectly good solution to do this by year, and perhaps we can all accept the overhead of 1 extra category per-year blogging... 

It also does stop any confusion, or interface incompatibility with GitHub's file listing for large listings; and as @penibelst mentions, it helps authors to manage their post-based content more easily. :+1:

**Comment by parkr** [comment]
We have often talked about renaming post files. I'm not convinced yet reading this post. It's a reasonable request (as long as it's backwards-compatible), but introduces some complexities (e.g. what if I don't create a day folder?). It's easier to enforce a filename convention when only one directory, namely `_posts`, is involved, instead of 4.

**Comment by envygeeks** [comment]
We could always simplify the way this is handled with YACO: do you want us to generate categories from your post list or not? If not then just **/*.* and pump out the files per normal using their permalink, if so then do it the old way.

**Comment by envygeeks** [comment]
What I mean by that is, once they disable our category generation organization is on them, so we don't need to worry about what happens when something goes wrong, because they are probably just slicing up the file system to organize it the way we do with say pictures instead of caring about categories.

**Comment by pathawks** [comment]
> YACO

Love it. I have all sorts of sub-directories inside my `_posts/`, and just use YAML for *real* categories I want to use.

Then again, not everyday can be Christmas :christmas_tree:

**Comment by penibelst** [comment]
Thank you for the rich conversation. Maybe anybody could mention the sub-folder trick in the documentation.
