### ISSUE TITLE
what svg viewbox and pathfill do in generated default index page?

### ISSUE THREAD

**Issue by Behinder** [jekyll/jekyll#3805]
When I generate whole site I've noticed such code in index.html

    <nav class="site-nav">
      <a href="#" class="menu-icon">
        <svg viewBox="0 0 18 15">
          <path fill="#424242" d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.031C17.335,0,18,0.665,18,1.484L18,1.484z"/>
          <path fill="#424242" d="M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0c0-0.82,0.665-1.484,1.484-1.484 h15.031C17.335,6.031,18,6.696,18,7.516L18,7.516z"/>
          <path fill="#424242" d="M18,13.516C18,14.335,17.335,15,16.516,15H1.484C0.665,15,0,14.335,0,13.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.031C17.335,12.031,18,12.696,18,13.516L18,13.516z"/>
        </svg>
      </a>
    
Is there any purpose of this path-fill in default theme? Does default theme should not be keep as simple as possible?

**Comment by kleinfreund** [comment]
That's used for the little icons you see in the footer. If it bothers you, you can remove it from your theme, of course.

**Comment by envygeeks** [comment]
We should probably be using Octicons now that web fonts are pretty much supported everywhere and used pretty much everywhere /cc @jglovier @jekyll/core

**Comment by jglovier** [comment]
I opted not to use Octicons because a) it's an extra http request (vs SVG is just inline code) and b) it's overkill to load an entire font set for literally 1 icon we'd use it for.

>Is there any purpose of this path-fill in default theme?

Path fill sets the color of the path before css loads.

**Comment by jglovier** [comment]
> for literally 1 icon we'd use it for

To clarify, it would only gain us the Octocat mark. The menu bar icon in Octicons is ugly, and I wouldn't use that as a replacement. Even if we did, it would still only be 2 icons for an entire http request. Not sure what that would gain us. SVG is supported everywhere.

**Comment by envygeeks** [comment]
I haven't looked at that theme for months but fair point, I didn't even remember that.

**Comment by parkr** [comment]
Ditto to what @jglovier said. I think I remember asking about this, but we decided it was a lot to ask of a simple theme to import in a huge font set for just one font.

**Comment by Lyonsclay** [comment]
The code posted actually is in the header, I was curious about it myself. There are svg paths in the footer which represent the Github and Twitter icons.

**Comment by judsonx** [comment]
+1 @Lyonsclay 

Yes, the svg mentioned originally is a 3 bar, menu looking thing. It does not seem to show up anywhere in the header though.

**Comment by Lyonsclay** [comment]
It turns out that it is a menu bar for mobile, when the screen size is below a certain size it appears.
