### ISSUE TITLE
Unable to install jekyll on El-Capitan

### ISSUE THREAD

**Issue by lomudi** [jekyll/jekyll#3807]
Getting this error on terminal:

ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
creating Makefile

make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15/ruby/config.h', needed by `hitimes.o'.  Stop.

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/hitimes-1.2.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out

**Comment by parkr** [comment]
You require the development headers for Ruby, which Apple does not bundle. Please use RVM or rbenv to install a Ruby with development headers, or use something like docker [with one of our official images](https://github.com/jekyll/docker-jekyll#running).

**Comment by fulldecent** [comment]
@parkr Jekyll is less of a "tool for Ruby people" and more of "a tool for many people that happens to be written in Ruby".

Previously, the instructions on http://jekyllrb.com/ were sufficient to go from "just bought a Mac" to "using Jekyll". I would petition that this high standard of documentation be maintained with the new version of OS X and this issue remain open.

**Comment by parkr** [comment]
@fulldecent I agree that Jekyll is a tool for 

> @parkr Jekyll is less of a "tool for Ruby people" and more of "a tool for many people that happens to be written in Ruby".

I absolutely agree!

> Previously, the instructions on http://jekyllrb.com/ were sufficient to go from "just bought a Mac" to "using Jekyll". I would petition that this high standard of documentation be maintained with the new version of OS X and this issue remain open.

I'd love to keep the docs up to snuff, though I would say we don't necessarily need to document an un-released version of OS X's shortcomings. I don't have El Capitan, and would therefore love it if you could help us out with the documentation here. Please submit a PR and I'll take a look! We will merge and deploy it once El Capitan comes out.

**Comment by fulldecent** [comment]
Discussion is continued at https://github.com/jekyll/jekyll/issues/3984#issuecomment-142416330

**Comment by HintikkaKimmo** [comment]
Had this issue as well. Brew install newest stable Ruby fixed it to me, but is probably not a solution for everybody. Does someone know what El Capitan does to gems? I mean even Sudo does not allow me to install. 

sudo gem install jekyll
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/jekyll

**Comment by jaybe-jekyll** [comment]
OS X is a tinker-hostile environment when it comes to OSX system/installed/owned files and directories. OS X provides user space for customization at the sensible /usr/local/.

Please also see #3984 for my (and others) comments about ways to manage.

I state this in #3984; default, native Ruby that comes with OS X is perfectly fine as it is Ruby 2+. It's fine to use Homebrew, but it is wholly not necessary.

**Comment by envygeeks** [comment]
To add an extra note to what @jaybe-jekyll we also provide Docker images, which do not require you to install anything but Docker, no need to tinker with Homebrew or install Ruby.
