### ISSUE TITLE
Jekyll Beta bytesize bug

### ISSUE THREAD

**Issue by Lewiscowles1986** [jekyll/jekyll#3808]
Okay so while trying out #3800 in 3.0.0.pre.beta7

```cmd
 Incremental build: enabled
      Generating...
  Liquid Exception: undefined method `bytesize' for nil:NilClass in _layouts/post.html
jekyll 3.0.0.pre.beta7 | Error:  undefined method `bytesize' for nil:NilClass
```

:bug:

**Comment by Lewiscowles1986** [comment]
Also after google see
http://stackoverflow.com/questions/21799817/ruby-undefined-method-bytesize-for-hash0x2954fe8
http://stackoverflow.com/questions/1117272/error-happens-when-i-try-all-method-in-datamapper

looks like a problem with something that should be a string :-1:

**Comment by Lewiscowles1986** [comment]
last post on this until response, check out https://github.com/kyledrake/ruby-client/commit/060fc792a761a591b71534d86a7f3c2e0a03fd44, I believe they turn their hash into json to make it a string....

**Comment by pathawks** [comment]
How can I reproduce this?

**Comment by parkr** [comment]
Never seen this before. I think it is a plugin. Please re-run with `--trace` and paste the stacktrace.

**Comment by Lewiscowles1986** [comment]
```cmd
 Incremental build: enabled
      Generating...
  Liquid Exception: undefined method `bytesize' for nil:NilClass in _layouts/pos
t.html
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/liquid_
renderer/file.rb:38:in `ensure in measure_bytes': undefined method `bytesize' fo
r nil:NilClass (NoMethodError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/liquid_renderer/file.rb:38:in `measure_bytes'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/liquid_renderer/file.rb:27:in `block in render!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/liquid_renderer/file.rb:43:in `measure_time'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/liquid_renderer/file.rb:26:in `render!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/renderer.rb:95:in `render_liquid'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/renderer.rb:137:in `place_in_layouts'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/renderer.rb:59:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/site.rb:172:in `block (2 levels) in render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/site.rb:170:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/site.rb:170:in `block in render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/site.rb:169:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/site.rb:169:in `render'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/site.rb:59:in `process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/command.rb:28:in `process_site'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/commands/build.rb:60:in `build'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/commands/build.rb:35:in `process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/lib/j
ekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `block in execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/command.rb:220:in `execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y/program.rb:42:in `go'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenar
y.rb:19:in `program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta7/bin/j
ekyll:17:in `<top (required)>'
        from C:/Ruby22-x64/bin/jekyll:23:in `load'
        from C:/Ruby22-x64/bin/jekyll:23:in `<main>'
```

**Comment by Lewiscowles1986** [comment]
even if I make `_layouts/post.html` blank, it then moves to `_layouts/default.html`, which I then make blank and I get a blank site...

**Comment by pathawks** [comment]
> even if I make _layouts/post.html blank, it then moves to _layouts/default.html, which I then make blank and I get a blank site...

It’s some post that is _using_ that layout which is triggering this.

**Comment by fw42** [comment]
Hmmm. Interesting. I guess it renders `nil` for some reason. An easy fix would be to just do `to_s.bytesize` instead of `bytesize` in `LiquidRenderer`. I'm out of town right now, but I can fix this on Thursday.

**Comment by fw42** [comment]
Is your site open source? How can I reproduce this issue? Can you create a minimal example that reproduces this?

**Comment by envygeeks** [comment]
Could empty post content trigger this? This could be a case of nil in nil out.

**Comment by Lewiscowles1986** [comment]
Hi all, 

@envygeeks sadly I emptied the content because of the message, but it has frontmatter and a non-breaking space, so not empty... The original file which still threw this error was not empty and is synced with the repo online.

@fw42 `git clone https://github.com/birdyrose/birdyrose.github.io --depth=1` should do it. I have been playing on my PC, but it's the main Repo I play with (my cousin wants to blog, she drew some pages, and I decided as I was learning Jekyll, I'd use that as the basis for a project).

as an aside, it may be something else as if I use `jekyll new sitename` from the commandline it seems to run just fine, I suppose I should really init a new repo with a new site, and check the differences in the new files.

**Comment by envygeeks** [comment]
@Lewiscowles1986 Having front-matter doesn't mean not an empty file to Jekyll because we treat the two exclusively in the context of parsing but all of that is based on my assumptions of which I have no confirmed.  They don't need to be confirmed anyways.

The problem here is for some reason `comments: false` in https://github.com/BirdyRose/birdyrose.github.io/blob/master/_posts/2015-06-14-second-post-test.markdown is causing a problem in either Jekyll or Liquid (probably Jekyll because this is happening in the front-matter and that is our territory)

**Comment by envygeeks** [comment]
Or not, it's back again...

**Comment by alexmwu** [comment]
I get a similar issue. It seems to be breaking a plugin.

Liquid Exception: undefined method `bytesize' for nil:NilClass in _layouts/blog.html
/Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/liquid_renderer/file.rb:38:in `ensure in measure_bytes': undefined method `bytesize' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/liquid_renderer/file.rb:38:in `measure_bytes'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/liquid_renderer/file.rb:19:in `block in render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/liquid_renderer/file.rb:18:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/convertible.rb:112:in `render_liquid'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/convertible.rb:211:in `render_all_layouts'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/convertible.rb:252:in `do_layout'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/page.rb:116:in `render'
	from /Users/me/projects/website/src/_plugins/tag_gen.rb:28:in `write_tag_index'
	from /Users/me/projects/website/src/_plugins/tag_gen.rb:21:in `block in generate'
	from /Users/me/projects/website/src/_plugins/tag_gen.rb:20:in `each'
	from /Users/me/projects/website/src/_plugins/tag_gen.rb:20:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/site.rb:155:in `block in generate'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/site.rb:154:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/site.rb:154:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/site.rb:58:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/command.rb:28:in `process_site'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/commands/build.rb:60:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/commands/build.rb:35:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0.pre.beta7/bin/jekyll:17:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'

**Comment by Lewiscowles1986** [comment]
moved `_plugins` folder so Jekyll doesn't know where it is (outside of site root), and tried jekyll serve, so now I know it's not my plugin code "phew" :smiley_cat:

**Comment by Lewiscowles1986** [comment]
apparently `2.5.3` was allowing something bad in my liquid for category pages with no error, but 3.0.0.pre.beta7 does not allow this (maybe liquid lib was updated?)...

```Liquid
	{% assign catpages = site.categories[page.category] | sort: 'date' 'last' | reverse %}
```

had to become

```Liquid
	{% assign catpages = site.categories[page.category] | sort: 'date', 'last' | reverse %}
```

https://docs.shopify.com/themes/liquid-documentation/filters/string-filters#replace gave the hint...

Which was fun, still looking into the rest

**Comment by Lewiscowles1986** [comment]
weirdness existed in the `header.html` as well

It was producing a liquid error in the rendered content

> Liquid error: Liquid syntax error: Expected end_of_string but found pipe in "page.description | strip_html | strip_newlines | truncate: 160" 

Fixed by not using filters in an if statement (I know, I'm new, but should have known that would cause issues)

```Liquid
<meta name="description" content="{% if page.description %}{{ page.description | strip_html | strip_newlines | truncate: 160 }}{% else %}{% if page.excerpt %}{{ page.excerpt }}{% else %}{{ site.description }}{% endif %}{% endif %}">
```

**Comment by Lewiscowles1986** [comment]
Right we may be able to close this one out as fixed... I now have the site running, and it seems that Jekyll 3 beta 7 is just less tolerant of poor liquid syntax...

**Comment by fw42** [comment]
Still, the error that you are seeing is confusing. You should be seeing a Liquid error, not some unrelated-looking Ruby error. I will create a PR soon. I think this happens because the code is in an `ensure` block (which will get executed even if the code before it raised an exception (like a Liquid::Error)).

**Comment by Lewiscowles1986** [comment]
:+1: cool. There are more bugs btw, I just want to separate them from this as separate issues... Before I can tackle that, I need to get recording and ensure what I am feeding Jekyll is better
