### ISSUE TITLE
Jekyll 3.0.0.pre.beta7, variable only exists if I echo or modify if statement

### ISSUE THREAD

**Issue by Lewiscowles1986** [jekyll/jekyll#3810]
Hello again

I have a plugin for Jekyll for improved pagination. Using `Jekyll 3.0.0.pre.beta7` I noticed when I have 1 post it is not paginating

```
{% if page.pages >= 1 %}
```

seems to return false.
the moment I output the value of page.pages

```
{{ page.pages }}
```

it evaluates to true... This is weird!

What is even weirder is that if I evaluate

```
{% if page.pages > 0 %}
```

The problem goes away...

This problem does not exist when testing with `2.5.3`

**Comment by Lewiscowles1986** [comment]
If I run 

`jekyll clean`

It seems to have remitted this issue

**Comment by envygeeks** [comment]
Can you try with `full_rebuild: true` inside of your configuration file and see if this resolves your issue?

**Comment by Lewiscowles1986** [comment]
@envygeeks not sure how to get the issue back since running `jekyll clean`, assuming `full_rebuild: true` initiates a clean command before building?

**Comment by envygeeks** [comment]
`full_rebuild` actually disabled our next generation incremental regeneration (it's kind of like clean in that like old Jekyll 2.5.3 it always regenerates the entire site again.)  By disabling that I was trying to see if you were running into one of the edges we know about, but we can let this ticket set until you come across this issue again and can try that fix and we can go from there.

**Comment by Lewiscowles1986** [comment]
i'll set it and test

**Comment by fw42** [comment]
Can you create a minimal example how to reproduce this problem?

**Comment by Lewiscowles1986** [comment]
Hi @fw42 

```bash
git clone https://github.com/BirdyRose/birdyrose.github.io
cd birdyrose.*
git checkout jekyll3-beta7-broken
jekyll serve
```

then `CTRL+C`
`Y`

```bash
git checkout master
jekyll serve
```

Should do it, I will check myself tomorrow when I should have access to a *nix laptop. Also, so I can test if the behavior is platform specific...

In any case I believe `jekyll clean` fixes, and I intend to test @envygeeks solution as a better all round solution

**Comment by Lewiscowles1986** [comment]
Looks like I need to work on another branch to get it to work, essentially I need to re-fix some of the commits so that it runs, but outputs the broken liquid, then try switching to master

**Comment by Lewiscowles1986** [comment]
unable to reproduce, I have been through all the files, reverted and retried...

**Comment by Lewiscowles1986** [comment]
Unfortunately I cannot reproduce on a windows or linux box, so I have no clue what caused this issue

**Comment by envygeeks** [comment]
Sometimes flukes happen and nobody can explain why. For now we'll close this ticket and if you experience it again you can file a new ticket (or if sooner than later just ask for this to be reopened) and link this one (we like to close tickets unless a problem is reproducible and active.)

**Comment by parkr** [comment]
:+1: @envygeeks.

**Comment by Lewiscowles1986** [comment]
:+1:
