### ISSUE TITLE
Stuck on jekyll new 

### ISSUE THREAD

**Issue by zivanovicb** [jekyll/jekyll#3816]
Hi there
Im rookie in development and I tried to install jekyll by watching an youtube video.

![2222](https://cloud.githubusercontent.com/assets/13037008/8336641/235dddf4-1aa6-11e5-837a-17488105f7f2.png)

**Comment by parkr** [comment]
Did you run `gem install jekyll`? It doesn't look like the right version of `pygments.rb` installed. Install the correct version of pygments.rb and you'll be fine.

**Comment by zivanovicb** [comment]
I did.What is the right version of pygments.rb, at the moment I am on 0.6.3.

**Comment by parkr** [comment]
0.6.3 should be fine – it looks like the message above only found 0.3.6.
