### ISSUE TITLE
Support for ".liquid" file extension

### ISSUE THREAD

**Issue by leo** [jekyll/jekyll#3817]
I changed the extension of all of my template-files to ".liquid" (since the content is technically based on Liquid markup and not only HTML). All the files in `_includes`and `_layouts` are getting included into the HTML output as usual by Jekyll - only the `index.liquid` file doesn't seem to be affected.

Could someone please check that and make sure that this file also gets compiled?

**Comment by parkr** [comment]
Do you have the YAML front matter at the top of your `index.liquid` file?

As far as I know, we don't take `.liquid` and output `.html` because `.liquid` could be HTML, JSON, XML, or anything else.

**Comment by leo** [comment]
Yep! That might be true, but I don't get the point there. — `.html`files can also be JSON, HTML, or XML. And if you ask me, this is the only right way to tell editors which syntax to use.

**Comment by leo** [comment]
I mean, `.liquid` is the proper file extension for files containing this kind of syntax, isn't it? Otherwise, it's just a HTML file containing text-strings which are not part of HTML itself. And also, if the files in `_includes` and `_layouts` are able to work with the extension, why not also this one file? :blush:

**Comment by envygeeks** [comment]
I don't think liquid has an actual extension reserved for it because it does not pick up and read the files itself (at least from my experience) it requires you to do such a thing yourself.  The choice of extension is up to the author of the software using liquid.  I mean @fw42 would have to step in and confirm.

I'm personally +1 .liquid being accepted but it's not a big deal to me so I'm going with what @parkr decided because I can switch my editor to Liquid syntax quickly without even a blink so I'm not mithered by what extension we use.

**Comment by leo** [comment]
You're probably right!

I'm also not completely sure if this extension is officially needed. All I know is that all other layouts and includes work with this extension and I therefore thought keeping continuity here would be the right thing.

Another thing is that I'm also able to switch the syntax to Liquid, if I wanted to (I'm using Sublime Text). Nevertheless, this is an extra step that could be avoided by changing the extension (which will then be recognised and the proper syntax mode will be enabled).

Hopefully @fw42 can say more about this.

**Comment by fw42** [comment]
Yeah Liquid (the gem) doesn't know anything about file extensions. This is up for the application to decide. In Shopify we use things like ".html.liquid" and ".css.liquid" etc., similar to how the Rails asset pipeline has ".html.erb" and ".css.erb".

**Comment by parkr** [comment]
I'm down with that. :point_up:

**Comment by envygeeks** [comment]
That really would simplify the way we output things right? .css.liquid in -> .css out.

**Comment by leo** [comment]
I might be missing something here, but how are extensions like ".css.liquid" useful? Isn't Liquid just a templating language which allows you to achieve more advanced things within HTML? Or does this mean the syntax is also intended to be used in combination with CSS, etc.? :sweat_smile:

If the latter is right, then I'm also for what @fw42 proposed. But only if this includes the fact that ".liquid" files are converted into ".html" ones. I mean, this extension definitely exists within the community. Whether or not it's actually intended by the creators of the language. — Just take a look at the [results][1] of a search for the "Liquid" language, there are many repo's which contain files using this extension.

P.S. It also looks like thousands of developers are using the ".liquid" extension (without the "html" before) to create their Shopify themes (I don't know, why @fw42 didn't mention this).

[1]: http://git.io/vtlK6

**Comment by fw42** [comment]
Liquid has nothing to do with HTML, you can use it to generate whatever text-based output you want, like HTML, CSS, SVG, plain text, emails, whatever you can think of.

**Comment by leo** [comment]
Alright, thank you for clarifying that! Never done learning.

**Comment by leo** [comment]
What do you think guys? Is it possible to implement this? :blush:
