### ISSUE TITLE
Docs for "Creating Pages" Should Mention Markdown Support

### ISSUE THREAD

**Issue by alphang** [jekyll/jekyll#3824]
I'm new to Jekyll. While reading http://jekyllrb.com/docs/pages/, I found myself thinking that only static HTML pages are supported, because of the way it's is worded.

Can those docs be expanded to mention _layouts/page.html, as well as dynamic content (Markdown etc) support?

Thanks.

**Comment by gynter** [comment]
Technically markdown is not a dynamic content, it's a markup language which is easier to write and read also as plain text. All content (posts, pages and collections) are run trough markdown parser. More information is available at the [Welcome](http://jekyllrb.com/docs/home/) page. Also, layouts and includes are not parsed with markdown parser.

**Comment by alphang** [comment]
Thanks. I didn't get that "All content (posts, pages, and collections) are run through the markdown parser." in the documentation. It's not clear on the Welcome page, either.

**Comment by plaindocs** [comment]
I can pick this up if nobody else wants to add docs for it.

**Comment by parkr** [comment]
@plaindocs I don't think anyone is working on it. Please feel free! Even just mentioning `index.md` or something after some carefully-chosen `index.html`s could be helpful enough here.

**Comment by pathawks** [comment]
Looks like this was fixed via #4275 :+1:

**Comment by parkr** [comment]
Thanks @pathawks :)
