### ISSUE TITLE
jekyll --pre error on build with pipes

### ISSUE THREAD

**Issue by shadowlightwolf89** [jekyll/jekyll#3825]
so, I had a bit of code in my index.html, namely this

```liquid
{% for post in site.posts | limit: site.post_limit %}
```

and it works fine in previous jekyll builds, but after upgrading to the --pre version, it gave off errors on build.

this is the error

```bash
Liquid Exception: Liquid syntax error: Expected end_of_string but found pipe in "post in site.posts | limit: site.post_limit" in index.html
jekyll 3.0.0.pre.beta7 | Error:  Liquid syntax error: Expected end_of_string but found pipe in "post in site.posts | limit: site.post_limit"
```

**Comment by pathawks** [comment]
The pipe is unnecessary.

`limit` is not a filter, but an option passed to `for`

Previously, Jekyll was not as verbose with regrad to Liquid errors, which is probably why you’ve not had this problem before.

Remove the pipe and you’ll be fine.

**Comment by shadowlightwolf89** [comment]
oh, okay, let me try that XD

**Comment by shadowlightwolf89** [comment]
works, thanks!

**Comment by envygeeks** [comment]
If you don't mind, did you find this bad example in our docs or anything related to Jekyll or it's maintainers? We can always fix something we wrote that does not apply anymore.

**Comment by shadowlightwolf89** [comment]
No, it was in a theme called [Carte Noire](https://github.com/jacobtomlinson/carte-noire)
