### ISSUE TITLE
jekyll 3.0.0.pre.beta7 - Undefined Method

### ISSUE THREAD

**Issue by shadowlightwolf89** [jekyll/jekyll#3826]
So, when I try to build my jekyll site, I keep getting a liquid error...

The error code:

```bash
 Liquid Exception: undefined method `bytesize' for nil:NilClass in _layouts/default.html
jekyll 3.0.0.pre.beta7 | Error:  undefined method `bytesize' for nil:NilClass
```

the site source: [Jekyll Guide Theme](https://github.com/WolfenShadows/jekyll-guide-theme)

**Comment by sondr3** [comment]
Had the same thing happen with me when I downloaded someone else's Jekyll site but they never had the problem. Cleaning out the `_layout/*.html` file made the error go away but it was all or nothing, I tried removing things piece by piece but the error was there as long as there were content in the layout file.

**Comment by parkr** [comment]
I think we fixed this in #3811. /cc #3808

**Comment by sondr3** [comment]
Any ETA for the next beta release then?

**Comment by envygeeks** [comment]
I'll ping @parkr and ask him to release a new version.

**Comment by parkr** [comment]
Done!

**Comment by Lewiscowles1986** [comment]
to be fair on this issue, has everyone experiencing these issues run `jekyll clean`, and checked their liquid syntax? The reason I ask is I know I found some really strange errors, but after checking the liquid and ensuring found errors were fixed and clean was run these errors went away and I could not reproduce.
