### ISSUE TITLE
Add hooks for :config, :post_read or :post_set and others.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3829]
In theory we could just tap into :site, :post_reset (which happens whenever we first boot up Jekyll) but it would be nice if we had some earlier hooks so that we can do things with the configuration based on environments we set ourselves.

**Comment by parkr** [comment]
:+1:

**Comment by parkr** [comment]
@envygeeks Add to 3.0.1 or 3.1?

**Comment by envygeeks** [comment]
I think I'd rather target 3.1 for that because there are more hooks to be added too.

**Comment by parkr** [comment]
@envygeeks still want this?

**Comment by envygeeks** [comment]
Yes, I just haven't had time! Sorry.

**Comment by parkr** [comment]
Will punt to v3.2.
