### ISSUE TITLE
css/main.scss is executable

### ISSUE THREAD

**Issue by oblitum** [jekyll/jekyll#3833]
Just got back to Octopress, now 3.0 =).

I've just generated a scaffold site and noticed in Vim that css/main.scss is with executable permission, which is weird, it's a jekyll generated file.

relates to https://github.com/octopress/octopress/issues/117.

**Comment by envygeeks** [comment]
We scaffold these files so it could have happened by accident.  Normally it's not a big deal since people don't go around and execute random files (well I hope they don't) however I've removed the bit so it's not a problem.
