### ISSUE TITLE
Does the Jekyll::Hooks provide for the collections?

### ISSUE THREAD

**Issue by icai** [jekyll/jekyll#3834]
Does the Jekyll::Hooks privode for the  custom  collections ?

----
I want to trigger a hook for my custom collection. 
Does I use `:document` to do this?

http://jekyllrb.com/docs/plugins/#hooks

**Comment by envygeeks** [comment]
I do believe you are correct that you would hit document (or perhaps page) to hooks.

**Comment by parkr** [comment]
Yep, `document` is the generic one for all collections. Nothing for specific collections yet.

**Comment by parkr** [comment]
@icai In Jekyll 3.0.0, you can create one based on your collection. Say you have a `_recipes` collection:

```ruby
Jekyll::Hooks.register :recipes, :post_render do |post|
  post.output = render_again!(post.output)
end
```

More is here: http://jekyllrb.com/docs/plugins/#hooks
