### ISSUE TITLE
Jekyll::LogAdapter breaks standard Logger behavior by not allowing blocks.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3835]
As we step into Jekyll3 this would be the perfect time for us to start accepting a `msg` or `block` so that we can pass the logger into other things that accept a logger for a common behavior.  I discovered this when working with Sprockets.  It falls down because Sprockets assumes we have a standard logger behavior where blocks are accepted in place of a string.  We should accept this at a basic level so that at least the most basic things work.

**Comment by parkr** [comment]
This should be easy to add. Feel free to commit directly to master if you like.
