### ISSUE TITLE
Site template overwrites `page` variable

### ISSUE THREAD

**Issue by gynter** [jekyll/jekyll#3836]
The loop at site template [header.html][1] overwrites the page variable and therefore it's not possible to use it anymore for example to see if the current page matches the entry in the list to make it selected/active.

[1]: https://github.com/jekyll/jekyll/blob/master/lib/site_template/_includes/header.html#L17

**Comment by parkr** [comment]
Feel free to name it something else and submit a patch if you'd like. It's not a huge concern as we aren't doing that in the template. Cheers!
