### ISSUE TITLE
Content Blocks [Enhancement]

### ISSUE THREAD

**Issue by shivajivarma** [jekyll/jekyll#3843]
It would be nice if we have content blocks feature embedded into core of jekyll. It's an excellent feature to build complex templates.

something like https://github.com/rustygeldmacher/jekyll-contentblocks developed by @rustygeldmacher

**Comment by envygeeks** [comment]
{% include %} and {% capture %} both suite to serve this purpose IMO.

**Comment by shivajivarma** [comment]
@envygeeks But the problem here is you can extract "capture" data (in pages) on to layouts.

Something like this cannot be performed

```HTML
<html>
    <head>
        {% contentblock scripts %}
    </head>
    <body>
        <div class="main">
            {{ content }}
        </div>
        <div class="sidebar">
            {% contentblock sidebar %}
        </div>
    </body>
</html>
```

Here is my post content.
```HTML
---
layout: default
---
Some body content comes here 

{% contentfor scripts %}
 function SmallFunctionSpecificToThisPage(){
            return "Hello";
}
{% endcontentfor %}
```

Everytime i don't want to keep page specific scripts in fragment files and micro manage them. Inside i would like to keep in page itself and push it into specific section of layout.
