### ISSUE TITLE
No Styles in build

### ISSUE THREAD

**Issue by AmmarAliShah** [jekyll/jekyll#3844]
When I run my site in local server, it's okay but after build, it has no style. It's just random content
Git repo: https://github.com/AmmarAliShah/ammaralishah.github.io/tree/master/_site
Site: http://ammaralishah.me/_site

**Comment by parkr** [comment]
This isn't a problem with Jekyll – your styles are in the resulting site. Rather, it's a problem with your templates.

**Comment by parkr** [comment]
Please use https://talk.jekyllrb.com/ in the future for things like this, too. :smile:

**Comment by AmmarAliShah** [comment]
I'm using the default theme - I changed nothing - I just ran ```jekyll new blog``` then ```jekyll serve``` and finally ```jekyll build``` and copied _sites content to my GH rep

**Comment by pathawks** [comment]
> copied `_sites` content to my GH rep

You copied the `_sites` directory itself without updating the `baseurl`; your `css` directory is not in the root, but that’s where your HTML is trying to link.

**Comment by AmmarAliShah** [comment]
What do I change? @pathawks

**Comment by pathawks** [comment]
This is not the place to request Jekyll tutorials.
As mentioned above, you should use https://talk.jekyllrb.com/ for that.

Every comment on an issue pings everybody following Jekyll, which gets noisy.
