### ISSUE TITLE
Erases changes

### ISSUE THREAD

**Issue by ktagilbert** [jekyll/jekyll#3846]
Everytime I leave my work anything I do in JavaScript or any changes I make to the index.html file gets erased. I save repeatedly yet when I go back to see my work it is all gone. Why? (note: am using Sublime Text)

**Comment by envygeeks** [comment]
We need more information:
* What does your config look like?
* Is the site's source available for us to view?
* What exactly is "Sublime Text" doing?
* Define: "gone" is the source file gone or the compiled file?

**Comment by parkr** [comment]
Ensure you're not changing anything in the `_site` directory – this is overwritte.

**Comment by ktagilbert** [comment]
Gotcha! Thanks!
