### ISSUE TITLE
Working with drafts over midnight causes unexpected URL changes.

### ISSUE THREAD

**Issue by shinkondo** [jekyll/jekyll#3847]
Let's Say I created a draft, and opened it up in a browser at `/2015/7/12/{post-name}.html` on 7/12/2015.

If made change to the post on 7/13/2015 and regenerated the site, the updated post shows up in `/2015/7/13/{post-name}.html`.

This would be confusing because I can still reload the old post at `/2015/7/12/{post-name}.html`, which does not show any change I made.

I use Windows 7, Cygwin, Jekyll 3.0.0.pre.beta8, gulp, and browser-sync.

I think the following could be possible solutions:
- Give drafts future date that is long enough and do not require change (but may conflict with the `future: false` option ).
- Delete outdated drafts in `_site`.
- Put caution about this in [documentation](http://jekyllrb.com/docs/drafts/)

I would appreciate your advice/ suggestion/ comments.

**Comment by kleinfreund** [comment]
> Delete outdated drafts in _site.

Can you build your site with `full_rebuild: true` in the _config.yml, please? This way, everytime you change something (or run `jekyll build`) the contents of the `_site` directory are wiped.

**Comment by envygeeks** [comment]
I agree with @kleinfreund what happens when you do what he asked? Because outdated drafts *should* be deleted as they should end up in the outdated files list because they are no longer in theory being generated because technically drafts have no date, the date is the current date given on a whim.

**Comment by shinkondo** [comment]
I cannot check in the exact situation until midnight, but I realized that any renamed file under `_site` is not deleted after build regardless of `full-rebuild` option.

And it is probably due to the bug of `keep_files`, combined with my blog folder name containing ".git" as a substring. Please see #3849 for detail.

This fix prevents me from reloading an outdated file when a post is renamed. It is good enough as a reminder for me.

Thank you for your help.
