### ISSUE TITLE
Update default template to use relative path for css

### ISSUE THREAD

**Issue by Ollo** [jekyll/jekyll#3851]
When using the default template for a project based github page the default stylesheet reference breaks if you also have a user github page under the same account.

```
user.github.io
user.github.io/project-site
```
by changing this [line](https://github.com/jekyll/jekyll/blob/master/lib/site_template/_includes/head.html#L9) to use a relative path the correct stylesheet for the project site is loaded.
`<link rel="stylesheet" href="{{ "css/main.css" | prepend: site.baseurl }}">`

**Comment by kleinfreund** [comment]
In that case, the following settings are applied, I think:

```yaml
url: http://user.github.io
baseurl: project-site
```

Doesn't this work?

**Comment by Lewiscowles1986** [comment]
the line linked is correct if `site.baseurl` is "", the leading slash should be prepended to `site.baseurl`, I don't think it is a problem with the template, but a user setup

**Comment by parkr** [comment]
Making your `baseurl: /project-site` (note preceding slash), does that fix it, @Ollo?

**Comment by Ollo** [comment]
I've used the above solutions and they do fix the issue.

The confusion is configuring this for a development workflow as I'm only using the github page uri's during development to preview my build / theme. 

After development I want to use a custom domain and host the site at the root as opposed to from a subdirectory. Is there a way to configure this without mapping my domain or should I stick with my proposed change while I develop and then change it once I have mapped my domain? 

Sorry about any n0ob questions here just not finding clear instructions in the docs and this is my first attempt to use Jekyll. 

Thanks for all the support!

**Comment by envygeeks** [comment]
There can be confusion with "baseurl" and what it means but what I always tell clients is "baseurl" is simply just a sub-folder path that should be absolute from root and have no fqdn or resource attached, we (and by we I mean me -- not necessarily Jekyll as a software) provide "url" for that if that is what you wish to do.  Now I don't know if this is the official meaning, but that is the meaning I give to people I do Jekyll sites for.

So for example, given I don't host a clients site and they wish to host it on their own Github but they have other sites on Github, then we would set baseurl to "/repo.name".

**Comment by kleinfreund** [comment]
It should be noted that `baseurl` has no implicit meaning. It's arbitrary choice. You might as well name it something different.

**Comment by Ollo** [comment]
@envygeeks thanks for the info I think I have a handle now on how to configure this a bit more effectively. 

Closing this out as I think this is a configuration issue and not a template / project issue.

Thanks everyone for the tips really enjoying the software.

**Comment by Lewiscowles1986** [comment]
@Ollo one more thing to think about is that you can override the config file for different deployment strategies [Jekyll docs on configuration](http://jekyllrb.com/docs/configuration/) has information such as this and a lot more :wink:
