### ISSUE TITLE
Inconsistent shebangs used in the scripts

### ISSUE THREAD

**Issue by AJ-Acevedo** [jekyll/jekyll#3857]
There are inconsistent shebangs used in the [scripts](https://github.com/jekyll/jekyll/tree/master/script)

They should all use a shebang that is more portable like:

`#!/usr/bin/env bash`

I can submit a pull request if this is something the core team is interested in implementing.

**Comment by envygeeks** [comment]
Nobody is going to stop you from sending a pull request if it annoys you but it's not a big deal.

**Comment by AJ-Acevedo** [comment]
It's strange that commit 9e4ae5d is referenced above. That commit was pushed to an old fork of jekyll that I deleted. I then forked an updated copy of the repo and submitted the pull request with the updates.
