### ISSUE TITLE
jekyll with rouge pbm

### ISSUE THREAD

**Issue by ravinsinghd** [jekyll/jekyll#3859]
I have create the Jekyll blog in my PC with rouge highlighter. I can view the blog page without any problem in my PC. once I have publish the blog with github pages it showing error in page build process.
Then I remove the rouge from my config file after page start working in github pages also. so I want to clarify whether rouge supported in github or not.

**Comment by pathawks** [comment]
No, it is not.

**Comment by envygeeks** [comment]
If you ever want to know what is supported on Github Pages see: https://pages.github.com/versions/

**Comment by ravinsinghd** [comment]
Thanks
