### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sagarhani** [jekyll/jekyll#3861]
Hey, I'm using ubuntu 14.04.
On terminal, I executed this command to install jekyll - ``` sudo apt-get install jekyll```

After this, I did - ```jekyll new myblog```
This gives me following warning : 
```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
WARNING: Could not read configuration. Using defaults (and options).
	No such file or directory - new/_config.yml
Building site: new -> myblog
Successfully generated site: new -> myblog
```
This is not creating a new directory named ```myblog```
If I do ```cd myblog```, it shows following statement 
``` -bash: cd: myblog: No such file or directory ```

Also, ``` gem install jekyll ``` gives this error :
```
Fetching: liquid-2.6.2.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /home/private
```

Please help me in installing it. I read the [documentation](http://jekyllrb.com/docs/installation/) it didn't help. :(

**Comment by parkr** [comment]
Unfortunately this is an installation problem that is environment-specific, not a bug with Jekyll so we can't help you here. Please re-post this over on the discussion forum: https://talk.jekyllrb.com/

Thanks!
