### ISSUE TITLE
Add Babel compilation support

### ISSUE THREAD

**Issue by thejameskyle** [jekyll/jekyll#3863]
In addition to the built-in coffeescript support, it'd be nice to support ES6+ with Babel.

http://babeljs.io (incidentally also a jekyll site)

**Comment by envygeeks** [comment]
If you need it now the master branch of https://github.com/jekyll-assets/jekyll-assets provides ES6 Harmony support through Babel.

**Comment by thejameskyle** [comment]
Can't add gems to github pages though :disappointed:

**Comment by envygeeks** [comment]
Hopefully it will when Jekyll3 comes around, once I finish working on the new 2.0.0 of Jekyll-Assets I'll submit it to @benbalter or whoever on the security team can review it and see if we can get it included by default, the new version uses Jekyll to sanitize and even disables ERB t o try and increase those chances, I don't know if it will work but I will be trying, the only thing that prevents me from using Github Pages is the lack of asset management.

**Comment by parkr** [comment]
This will likely have to be a plugin. I'm sure GHP would be interested in it. If you have a version built, add it to our [Plugins Page](http://jekyllrb.com/docs/plugins/#converters-1).

**Comment by thejameskyle** [comment]
I just put together https://github.com/thejameskyle/jekyll-babel based on your work on jekyll-coffeescript

**Comment by parkr** [comment]
Excellent. Did you add it to the plugins page? Feel free to submit a quick PR for that.
