### ISSUE TITLE
suggest you change XXX.github.com  to   XXX.github.io

### ISSUE THREAD

**Issue by hellfire** [jekyll/jekyll#3866]
### You'd better change username.github.com to username.github.io

This may be a small point,  today I use jekyll to build a blog, after I use jekyll bootstrape base on http://jekyllbootstrap.com/usage/jekyll-quick-start.html, I found hellfire.github.com can't visit, but hellfire.github.io can visit, I thought there may be something wrong with the document. So I suggest you to fix it, although this may be a small thing.

![snip20150726_7](https://cloud.githubusercontent.com/assets/7992020/8892488/5bff06f2-338c-11e5-8d71-4007ee96c1b9.png)

**Comment by envygeeks** [comment]
That is not our source, please file it on their repo.
