### ISSUE TITLE
Support for three-backtick code block

### ISSUE THREAD

**Issue by jyuhuan** [jekyll/jekyll#3868]
Specifying code blocks as

    ```java
    int a = 0;
    ```

is not only easier than the current `{% highlight java %}` syntax, but also more compatible with what many popular markdown editors support. Without the three-backtick syntax, I cannot paste what I wrote before (e.g., a README.md on Github) directly into Jekyll. 

Was there any difficulties in allowing this three-backtick syntax which forced a more complicated syntax?

**Comment by envygeeks** [comment]
Hey @jyuhuan this is already supported: http://jekyllrb.com/docs/configuration/#redcarpet
