### ISSUE TITLE
Initial posts page is not regenerated when a new post is added

### ISSUE THREAD

**Issue by Mingan** [jekyll/jekyll#3872]
gem install jekyll --pre # jekyll 3.0.0.pre.beta8
    jekyll new test .
    jekyll serve # Normal initial installation of Jekyll is running, welcome post is there
    echo "---\nlayout: post\n---\n\nTest" > _posts/2015-07-28-test.md
    jekyll serve # Now I get the same page as before, the new post is not present (not even in the RSS feed), the file ittslef (_site/_posts/2015/07/28/test.html) is generated

To make the change propagate i have to run `jekyll clean` and then `jekyll serve`.

Might be useful: We use `CategoryPagination` in our website (because we need to support multiple locales) and then only the first page is not regenerated. Page 2 is fine and takes the new post into account.

**Comment by parkr** [comment]
Yes, this sounds like a plugin error. They have to register themselves with the regenerator in Jekyll 3. If they don't, they won't be regenerated with the new system. To get around this for now, use `--full-rebuild` when running Jekyll.

**Comment by Mingan** [comment]
Thank you for the quick response and your tip, but I think you misunderstood me. The problem occurs even with plain Jekyll 3.0.0.pre.beta8. That's why I posted the exact minimal steps to reproduce the problem. I meant the information about the pagination plugin only as extra information because the second page in the listing gets regenerated ok. It's problem only on the first one.

**Comment by envygeeks** [comment]
@Mingan please provide a repository with your example in it that we can pull and test.

**Comment by Mingan** [comment]
@envygeeks There's no need for repository. It's a completely fresh install of Jekyll out of the box.

**Comment by envygeeks** [comment]
Fair enough, Works For Me ™

**Comment by envygeeks** [comment]
If you will not provide us with a broken example that does not work for you we must rely on our examples and it literally works for me on my examples without a problem on a completely fresh install.

**Comment by Mingan** [comment]
FWIW https://github.com/Mingan/jekyll-bug-demo tried it two different times on different computers, tried to copy the initial post and just change the date to rule out any typo.

**Comment by envygeeks** [comment]
I'll test it after I finish building this Linux kernel for our servers in the meantime can you tell us your operating system?

**Comment by Mingan** [comment]
I initially encountered it on Fedora 22, now on Ubuntu 13.09 in VirtualBox.

**Comment by Mingan** [comment]
Tried it again this morning to make sure and it still happens. When I delete a post, its HTML file gets deleted but the index is not updated until I delete `_site/`.
