### ISSUE TITLE
Jekyll has just decided to stop generating

### ISSUE THREAD

**Issue by e0i** [jekyll/jekyll#3873]
Hello. I failed to generate exactly the same content I had generated some time ago with Jekyll. The error message says,

>  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2015-05-01-sciences.markdown/#excerpt':
>                    Failed to get header.
> jekyll 2.5.3 | Error:  Failed to get header.

I am sure that the versions of both Ruby and Jekyll are the same as before.  I also keep my blog in a git repository and `git diff` and `git status` show nothing. Not even a byte.

Perhaps a side effect of some other change in one of the gems or other tools? My Jekyll version is 2.5.3. 

Thanks.

**Comment by parkr** [comment]
Check out the issues here for that error, "Failed to get header." This has to do with Pygments in most cases. Furthermore, re-run jekyll with `--trace` to get more details about what's going on.

**Comment by e0i** [comment]
Thanks for the quick reply. I have Python in my `$PATH` and `pygments` installed. As I said, I had successfully generated the blog on the exact same machine that I have failed to generate yesterday, and blog had no changes. If the configuration about Python or pygments was not proper, I couldn't generate it in the first place. I have also looked up the error before submitting this issue and came across the same link you have provided, and followed suggestions. Still nothing. Unfortunately I will try to generate the blog on my server. This is probably a mysterious side effect of something else. Thanks again.

**Comment by parkr** [comment]
> I have Python in my $PATH and pygments is installed.

`pygments` via `pip` or `pygments.rb` via `gem`? You'll want the latter. Sometimes running `gem install jekyll` helps ensure gem issues are resolved.

> I have also looked up the error before submitting this issue and came across the same content with the link you have provided, and followed suggestions. Still nothing.

Sorry, we get so many duplicate reports and this one didn't have anything new that I could remember so I figured it was already tracked (and possibly solved).

I'm fairly certain this is not a bug. If you're still stuck, create a post on https://talk.jekyllrb.com and we can help you out there. Are you on Windows, Mac or Linux?

**Comment by e0i** [comment]
I am on Linux, and I have `pygments` installed both for Ruby and Python. The interesting thing was that I had succesfully generated the blog before various times, but I fail to do so with the exact same configuration. I think I'll share the situation at Jekyll forums. Thank you again for the reply.

**Comment by e0i** [comment]
Hi. I have struggled with upgrading the packages and experimentation with different virtual environments. All failed. However after changing the highlighter to `rouge`, it worked! The solution:
```shell
$ sudo gem install rouge
$ echo "highlighter: rouge" >> _config.yml
$ jekyll build
```
