### ISSUE TITLE
.sass-cache not uploading and no content or styles!

### ISSUE THREAD

**Issue by sonokamome** [jekyll/jekyll#3878]
I was updating my site as normal but then after I uploaded my site, I got the following page result.
![defaultjekyllnostyle](https://cloud.githubusercontent.com/assets/13297452/8996200/0e5efa5a-36cb-11e5-9966-4b20287ad2a6.PNG)

I did notice though that it's because of something going on during ftp upload:

_sass, _layout, and _includes are reported by my ftp client to have failed to upload (but they do anyway) and yet I get the result aforementioned. I wanted to know if anyone here has had that problem before. 

I have Dreamhost shared hosting so I wonder if that has to do with anything.

**Comment by parkr** [comment]
Only FTP up the `_site` directory. Directions are here: http://jekyllrb.com/docs/deployment-methods/#web-hosting-providers-ftp

**Comment by sonokamome** [comment]
Omg I'm so sorry! thank you so much! I totally forgot ha ha ha!
Thanks again I'm very thankful!
