### ISSUE TITLE
timezone is not read.

### ISSUE THREAD

**Issue by amoblin** [jekyll/jekyll#3879]
System Time Zone: Asia/Shanghai

YAML head in Markdown is:

date: 2015-07-30 15:59:59

then the generated url is:    2015/07/30/...

while the YAML head in Markdown is:

date: 2015-07-30 16:00:00

then the generated url is: 2015/07/31/...

the jekyll version is 2.5.3

Maybe Jekyll alwasy use the US time zone, and not use the system time zone?

**Comment by parkr** [comment]
Have you tried Jekyll 3? Can you reproduce?

**Comment by amoblin** [comment]
Just Now I have had tried Jekyll 3 beta 8:

```
➜ ~ $ jekyll --version
jekyll 3.0.0.pre.beta8
```

My System Time Zone is:

```
➜ ~ $ sudo systemsetup -gettimezone
Time Zone: Asia/Shanghai
```

and the yam head is:

```
➜ jekyll-icindy.github.io (master !+%) $ head -7 _posts/2014-11-18-jekyll-one-step.md
---
layout: post
title:  jekyll搭建1－模仿nodejs.org
date:   2014-11-18 17:33:36
categories: jekyll
tag: fontend
---
```

the generated file path is:

```
➜ jekyll-icindy.github.io (master !+%) $ ls _site/jekyll/2014/11/19/jekyll-one-step.html 
_site/jekyll/2014/11/19/jekyll-one-step.html
```

which should be **_site/jekyll/2014/11/18/jekyll-one-step.html**

**Comment by pathawks** [comment]
Is the problem that the date is read as GMT, which is then converted to `Asia/Shanghai`?

**Comment by envygeeks** [comment]
Try forcing Jekyll to be in your timezone: https://github.com/jekyll/jekyll/blob/master/lib/jekyll.rb#L110

**Comment by envygeeks** [comment]
Also, you can set a TZ directly on the date in your post, this is what we tend to do.

**Comment by parkr** [comment]
I believe this is how SafeYAML reads dates. If there is no information for the timezone, it assumes UTC offset is 0, i.e. GMT. Then Jekyll asks for localtime for all those dates and Ruby obliges by converting UTC+0 to your local timezone, some UTC+10 or so.

**Comment by amoblin** [comment]
add CST in the YAML head can fix this bug, but it's a huge work for all markdown files...
 
add      **timezone: Asia/Shanghai** in _config.yml does not work, both for Jekyll 2.5.3 and 3.0.0 beta8. 

I prefer to config the timezone in _config.yml, it's simple. How to config it correctly?

Thank you all.

**Comment by AndorChen** [comment]
@amoblin Try and set `timezone: '+0800'` in _config.yml.

**Comment by amoblin** [comment]
@AndorChen it works! 太感谢啦！
