### ISSUE TITLE
talk.jekyllrb.com Upgrade Plan

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3884]
- [x] Snapshot System
- [x] Snapshot SSD User Storage
- [x] Backup `/var/lib/docker` as secondary
- [x] Backup `/srv/docker` as secondary
- [x] Upgrade Docker if already not upgraded
- [x] Upgrade `docker-extras` -> `docker-compose`
- [x] Verify Docker Security
- [x] Reset Docker
- [x] Download new Alpine Linux Images
- [x] Try Boot with `/srv/docker`

**Comment by envygeeks** [comment]
This action has been delayed pending glibc integration into base images.

**Comment by erlend-sh** [comment]
There are pending changes to the way the Discourse Docker image works that might affect this:

https://meta.discourse.org/t/can-discourse-ship-frequent-docker-images-that-do-not-need-to-be-bootstrapped/33205

**Comment by envygeeks** [comment]
@erlend-sh: We don't use Discourses Docker images, our systems have their own: https://github.com/envygeeks/docker/tree/master/dockerfiles/discourse

**Comment by envygeeks** [comment]
This is completed.
