### ISSUE TITLE
Getting Installation Error on Windows 8.1

### ISSUE THREAD

**Issue by kutec** [jekyll/jekyll#3885]
Error Code:
<pre>C:\Users\Dell>gem install jekyll
ERROR:  Could not find a valid gem 'jekyll' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://ru
s.org/latest_specs.4.8.gz)</pre>

**Comment by parkr** [comment]
This is an SSL issue with your environment. Try #1409 or google for this SSL_connect error. Sorry I can't help further!
