### ISSUE TITLE
Inverted Paginator.

### ISSUE THREAD

**Issue by lagseeing** [jekyll/jekyll#3887]
Is there a way to have the paginator inverted?

I'm trying to make 1 post per page and i want the most recent post to be in a page that matches the total_pages

**Comment by envygeeks** [comment]
Hi @lagseeing this medium is for Jekyll bugs only and this is not a bug so I must ask that you please move your question over to https://talk.jekyllrb.com where generic Jekyll help is archived and asked.  Thanks!
