### ISSUE TITLE
Visual editor for jekyll

### ISSUE THREAD

**Issue by juando** [jekyll/jekyll#3888]
Hi, first of all im not sure if i can publish this here since is not really an issue so for that i'm sorry i'm quite new to github.

Im building a theme for jekyll and to put it out there for free, i've been using jekyll for the past two weeks and i think its great.

The problem comes when i think about non-techy skills users and how they could publish to jekyll (im not talking about markdown just the compile and server stuff). So i tried to look for a visual version of jekyll so far i found a few like prose, but they need to run heavy commands on server or installs or github.

So my question is "is there some visual editor based on something simple like php and js out there for jekyll?" or perhaps a way to compile jekyll posts and push them to a server without using the terminal, not push to github since for me is quite expensive and im not that into host websites on github.

If theres is no library available ill try to make one. So any contributors or people interested to build something like prose but without touching the server too much comment or tell me its a bad idea :p

thanks!

**Comment by envygeeks** [comment]
Hi, I'm sorry to say this but this medium is for Jekyll bugs only and your ticket is not a bug so I must ask that you please repost your question on https://talk.jekyllrb.com.

Thanks!

**Comment by juando** [comment]
ok im sorry about that i will!
