### ISSUE TITLE
Contributing.md feature command doesn't work

### ISSUE THREAD

**Issue by nateberkopec** [jekyll/jekyll#3893]
Contributing.md suggests `bundle exec rake features` to run the feature tests. This did not work for me:

```
$ bundle exec rake features
/Users/censored/.rbenv/versions/2.2.2/bin/ruby -S bundle exec cucumber  --profile travis
cucumber.yml was not found.  Current directory is /Users/censored/Documents/Code/jekyll.  Please refer to cucumber's documentation on defining profiles in cucumber.yml.  You must define a 'default' profile to use the cucumber command without any arguments.
Type 'cucumber --help' for usage.
```

That's sort of annoying. I just want to run the feature tests, not set up Cucumber. `script/cucumber` does seem to work, but that isn't the command documented in Contributing.md.

Also noted in #3605

**Comment by parkr** [comment]
Can you update Contributing.md to refer to `script/cucumber` please?
