### ISSUE TITLE
How isolatefolder from jekyll.

### ISSUE THREAD

**Issue by paullarionov** [jekyll/jekyll#3896]
I want to post some `html/pdf/...` files to github page. How I could make the jekyll ignore the folder. E.g. I created folder `data`, put into `_config.yml`

```
# Exclude these files from your production _site
exclude: [Gemfile, Gemfile.lock, LICENSE, README.md, CNAME, data]
```
but jekyll still gives 404 error, by requesting `github.io/data/file.html`.

It worries me too much(( How could I solve this?

**Comment by parkr** [comment]
`exclude` contains strings which are converted to regular expressions. Any file whose name contains "data" will be ignored.

**Comment by paullarionov** [comment]
Thanks for your reply, Park, but not works for me(( Still get 404 - Page not found:
'''
exclude: [Gemfile, Gemfile.lock, LICENSE, README.md, CNAME, data, data.html]
url: github.io/data.html
'''
Have to refuse...

**Comment by parkr** [comment]
You _should_ get "404 - Page not found" if you exclude `data` and `data.html`.

**Comment by paullarionov** [comment]
But I want get 'data.html'.

**Comment by parkr** [comment]
Remove `data` and `data.html` from your `exclude` directive, then. They are turned into regular expressions so `/data/ =~ "data.html" # => true`.
