### ISSUE TITLE
Set gist async 

### ISSUE THREAD

**Issue by Fandekasp** [jekyll/jekyll#3899]
when using a gist, eg

    {% gist d130eda27aa45238ebee %}

The google [Pagespeed insight](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fadrien.is%2Fsharing-tips-about-habitica%2F) notes it as javascript render-blocking.

Can we set a async option on that liquid element ?

**Comment by pathawks** [comment]
It must not be `async` as it uses `document.write()`  
It is necessarily render-blocking.

This could only be fixed by GitHub changing the embed code itself.

**Comment by envygeeks** [comment]
You can however defer it with `defer`, that does work with `document.write()`

**Comment by Fandekasp** [comment]
The gist tag doesn't accept any other argument than a filename. I also tried the defer manually

    <script defer src="https://gist.github.com/Fandekasp/d130eda27aa45238ebee.js"></script>

but it's never rendered in the page. Doesn't seem to work in that case.

**Comment by Fandekasp** [comment]
I solved my problem by using the [gist async](https://gist.github.com/razor-x/8288761) script, but it forces me to write html in my markdown template.
