### ISSUE TITLE
A pretty permalink should end with a slash

### ISSUE THREAD

**Issue by eugenebolshakov** [jekyll/jekyll#39]
AFAIK when apache gets a request like /path/to/post it looks for a file named "post" by default, not a directrory. That's why a mod rewrite rule is often added that redirects such requests to /path/to/post/ (basically just adds a trailing slash) and everything works well. 

However the links in jekyll still don't have that trailing slash which confuses disqus. Comments are added to a page with the trailing slash and counters are requested for a page without the slash. 

I think the pretty permalinks template should have the trailing slash to avoid the redirect and make disqus comments counters work correctly. I have it my fork http://github.com/eugenebolshakov/jekyll/tree/trailing-slashes-for-pretty-permalinks

It's obviously a tiny fix. I've also added the entire test/dest directory to .gitignore

**Comment by codingthewheel** [comment]
With respect, pretty permalinks should *not* end with slashes. I understand why they have to in this case, but the fact that Jekyll has to mangle proper URL form to appease a second-rate commenting service (Disqus is basically the Experts Exchange of comments) is a kludge, plain and simple, and it goes against everything Jekyll stands for (minimalism) in my opinion. This insistence on universal trailing slashes for all resources is a worst practice, and Jekyll's specific handling of this leads to the creation of wasteful `/foo/index.html` structures and other cruft. Comment support is far and away the worst part of Jekyll and that the app basically serves as a massive on-ramp into Disqus doesn't help the issue.
