### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by TreBey** [jekyll/jekyll#3900]
Hi, I am trying to get my imported SCSS partials to work with the main.scss file inside of the CSS directory that Jekyll provides. All of my partials are organized in the _scss directory, and each file is imported to the master file within that directory (stylesheet,scss). I am trying to simply import _scss/stylesheet.scss into the bottom of css/main.scss so that I can get an auto regeneration while building my site, but I get the following error when running 'jekyll serve watch' as a command:

![screenshot from 2015-08-09 12 57 32](https://cloud.githubusercontent.com/assets/12147635/9156163/3ebbeeec-3e96-11e5-9b64-903ee971a625.png)

I've tried different things to make it work, but the path seems to be broken. Can anyone shed some light on what I may be doing wrong? Thanks.

![screenshot from 2015-08-09 13 00 17](https://cloud.githubusercontent.com/assets/12147635/9156171/9e85f002-3e96-11e5-8fae-68c711b913b7.png)

![screenshot from 2015-08-09 15 45 23](https://cloud.githubusercontent.com/assets/12147635/9156847/c1f04864-3ead-11e5-9346-28e8aaf8ecd3.png)

**Comment by ctalr** [comment]
Hey there, have you tried the following?
Try adding this to your _config.yml:
```
sass:
    sass_dir: ./_scss
```
This tells Jekyll to look in the _scss directory for your Sass/SCSS partials. Because of this, you'll also need to shorten your import statement to: `@import 'stylesheet';`

**Comment by TreBey** [comment]
Thanks, that did tthe trick. But now I have a new problem. One of my imports is throwing the same error deeper within the tree. I am using Neat grid system, and one of the files inside of the neat directory is not found or unreadable. I am not exactly sure what the error is telling me: 
![screenshot from 2015-08-10 09 59 27](https://cloud.githubusercontent.com/assets/12147635/9174613/84b37e5a-3f46-11e5-9c16-53807860e7ab.png)


Also, I don't think it is a problem with the way I set up my import partials, because the error seems to be a conversion error. But I could be wrong (still kind of new to this). Thanks! @ctalr

**Comment by ctalr** [comment]
Glad to help!
For that deep error, I'm not too sure about why it's failing on you either. Have you tried removing the import for neat-helpers to see if the others in the same file fail?

**Comment by TreBey** [comment]
I found the problem by removing the import and tracked it back to another file that was referencing the neat-helpers file through the wrong path. Thanks for the help! +1
