### ISSUE TITLE
jekyll-docs gem not found

### ISSUE THREAD

**Issue by idmarjr** [jekyll/jekyll#3901]
Hi!
I was walking around the jekyll documentation and in the bottom of [Basic Usage](http://jekyllrb.com/docs/usage/) page there is a paragraph about install the `jekyll-docs` to have all the documentation on-the-go.

I tried to instal it but the follow error was showed:
<img width="1207" alt="screen shot 2015-08-10 at 00 11 03" src="https://cloud.githubusercontent.com/assets/301545/9158993/7f364ab6-3ef6-11e5-8c31-5dd346a081aa.png">

Since I'n not sure if the documentation out of date and this gem doesn't exist anymore, or if the gem itself have some problem, I'm opening this issue here. :smile:

**Comment by envygeeks** [comment]
https://rubygems.org/gems/jekyll-docs -- use --pre.

**Comment by idmarjr** [comment]
It works!
Thanks for the super quick answer @envygeeks .
There's a way that I can update the Basic Usage page and make clear to the user the he need to use `--pre` to install it?

**Comment by envygeeks** [comment]
Yup.  You can edit https://github.com/jekyll/jekyll/blob/master/site/_docs/usage.md

**Comment by idmarjr** [comment]
:+1: :smile: 

By the way, not sure if I'm doing something wrong but, after install the gem I run `jekyll docs` and get the follow error:
<img width="654" alt="screen shot 2015-08-10 at 00 46 15" src="https://cloud.githubusercontent.com/assets/301545/9159151/7a0e3604-3ef9-11e5-84a7-3be3be1c0005.png">

**Comment by envygeeks** [comment]
I would file that ticket here: https://github.com/jekyll/jekyll-docs/issues

**Comment by idmarjr** [comment]
I will do that!
Thanks again. :blush:
