### ISSUE TITLE
Plans to allow a configurable .jekyll-metadata location?

### ISSUE THREAD

**Issue by coneybeare** [jekyll/jekyll#3904]
I have a large site (3k posts) and for my workflow, I use a development build of just 5 posts, then a production build of the whole lot. They are configured to use different site folders so that the overhead of file creation and deletion is not added to the build time, and both build are accessible at any given moment.

Every path necessary to split up the build into environments exists, and I can make config files for the different configs, so it would also be great to expose the .jekyll-metadata path setting so I can do the same with that file.

Currently, it appears that the file is shared no matter what environment I am using.

Are they any plans to add this to the incremental build feature?

**Comment by parkr** [comment]
Hey @coneybeare, we don't have plans at the moment. We feel we have [too many configuration options already](https://github.com/jekyll/jekyll/blob/cd4829d28d3323bdf74dbb6808be99be8f1c1d41/lib/jekyll/configuration.rb#L8-L83) and are not prepared to add another. If this comes up for other folks, please send them here to discuss it further. If enough folks have a similar problem, we can revisit this.

For production, I would recommend using the `--full-rebuild` flag, which skips incremental regeneration. It is still a bit young and rough around the edges.
