### ISSUE TITLE
Jekyll Truck Factor

### ISSUE THREAD

**Issue by gavelino** [jekyll/jekyll#3905]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Jekyll** and obtained a value of **4**.

The developers responsible for this TF are:

Parker Moore - author of 63% of the files
Tom Preston-Werner - author of 11% of the files
Alfred Xing - author of 6% of the files
Nick Quaranto - author of 6% of the files

To validate our results, we would like to ask **Jekyll** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Jekyll**?

(b) Do you agree that **Jekyll** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Jekyll** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by envygeeks** [comment]
This is *not* the medium to do this.

**Comment by envygeeks** [comment]
Please move this discussion to https://talk.jekyllrb.com if you would like to continue it.
