### ISSUE TITLE
Jekyll fails to get installed on ruby 2.2.2

### ISSUE THREAD

**Issue by collegeimprovements** [jekyll/jekyll#3909]
It's because of pygments gem and I've raised an issue for the same [here](https://github.com/tmm1/pygments.rb/issues/151).

Just to make sure that there is the only problem out there, I'm raising this issue here at jekyll, too.

**Comment by envygeeks** [comment]
Here on our systems we have no problem with Ruby 2.2.2 and Pygments with Jekyll 3.0, not only does it power my website but the Docker image that has those powers dozens of other sites all with syntax highlighting explicitly done through Pygments.

**Comment by envygeeks** [comment]
Can you provide more information about your site?

**Comment by collegeimprovements** [comment]
I've installed ruby-2.2.2 and installed a lot of gems including rails and sequel and others. However when I tried to install jekyll it failed to get installed and threw the following error.

```ruby
gem install jekyll                                                                         [20:57:41]
ERROR:  Error installing jekyll:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /Users/arpit/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/cache/pygments.rb-0.6.3.gem
```

Then I explicitly tried to install `pygments` gem but the error persists. Hence raised the issue.

**Comment by envygeeks** [comment]
That's not a problem with Jekyll that's a problem with RubyGems (literally) clear your gem cache and then try again, either the download was modified by a middle-man in route and failed the check or your download was cut short (for various reasons).

Try: `find /Users/arpit/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/cache -type f -iname \*.gem -delete`

**Comment by envygeeks** [comment]
To add, it's not a problem with Pygments either.

**Comment by collegeimprovements** [comment]
It works. My bad. But I learned something new from your solution. I didn't know about gem's cache.  @envygeeks  Thanks a lot :+1:
