### ISSUE TITLE
How to render posts by category or tag without plugin? Thanks!

### ISSUE THREAD

**Issue by Sspeed5cm** [jekyll/jekyll#3915]
This is my blog with Jekyll.
http://sspeed5cm.github.io/blog/index.html

__Q1:__I don't know how to render posts by category or tag without plugin. I don't want to use Jekyll plugins.

The function I want to  implement is when I click the category , it should be render the post list under the category which the post belongs to.

__Q2:__How to sort the post? There is some questions about sort. like: '2015-08-15-1' and ‘2015-08-15-10’, The latter should be the first post in post list, but it does't work. 
The 'bower cache' post( '2015-08-15-10') is not the first. It 's last but one.

And .... My English is poor.I' m doubt about whether or not you know what I say? Sorry for that.
Thanks a lot!

**Comment by SakyaStelios** [comment]
I dont undestand your question very well, but if you can render the posts by category, you can write this:

```xml

{% for category in site.categories %}
	<h3><a name="{{ category | first }}" style="text-transform:capitalize;">{{ category | first}}</h3>
		<ul>
			{% for posts in category %}
				{% for post in posts %}
					{% if post.url %}
						<li><a href="{{ post.url }}">{{ post.title }}</a></li>
        			{% endif %}
      			{% endfor %}
    		{% endfor %}
    	</ul>
{% endfor %}

```

**Comment by envygeeks** [comment]
Please move your ticket to https://talk.jekyllrb.com, this medium is for bugs, not for generic questions.
