### ISSUE TITLE
(documentation) broken link "Migrate from your previous system"

### ISSUE THREAD

**Issue by ewann** [jekyll/jekyll#3919]
on page:
https://github.com/jekyll/jekyll/blob/master/README.markdown

link text:
Migrate from your previous system
link:
http://import.jekyllrb.com/docs/home/

seems to be an invalid hostname:

dig import.jekyllrb.com

; <<>> DiG 9.9.5-9ubuntu0.2-Ubuntu <<>> import.jekyllrb.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 50886
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;import.jekyllrb.com.		IN	A

;; AUTHORITY SECTION:
jekyllrb.com.		57961	IN	SOA	dahlia.ns.cloudflare.com. dns.cloudflare.com. 2019140839 10000 2400 604800 3600

;; Query time: 14 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Mon Aug 17 23:23:30 AEST 2015
;; MSG SIZE  rcvd: 109

for reference:
dig jekyllrb.com

; <<>> DiG 9.9.5-9ubuntu0.2-Ubuntu <<>> jekyllrb.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33377
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;jekyllrb.com.			IN	A

;; ANSWER SECTION:
jekyllrb.com.		265	IN	A	104.27.139.113
jekyllrb.com.		265	IN	A	104.27.138.113

;; Query time: 14 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Mon Aug 17 23:21:24 AEST 2015
;; MSG SIZE  rcvd: 73

**Comment by parkr** [comment]
Somehow a bunch of DNS records were blown away. This affected import.jekyllrb.com and talk.jekyllrb.com. I have restored them and they should be back soon. Thank you!
