### ISSUE TITLE
'&' a result of the build is not '&amp;' but '&'.

### ISSUE THREAD

**Issue by jicjjang** [jekyll/jekyll#3922]
i have a little english skill....

The problem is a title. '&' a result of the build is not '&amp;' but '&'.

'&' it will remain in the bottom of the article in feed.xml file.

show this picture.

![amp](https://cloud.githubusercontent.com/assets/6022539/9356966/3469971a-46bf-11e5-831f-04980cc90fd9.jpg)

**Comment by parkr** [comment]
Which file is it in?

**Comment by pathawks** [comment]
This is expected behavior.

If you are inserting a page title into a page template, you must make sure to use the `xml_escape` filter:

```
{{ page.title | xml_escape }}
```
