### ISSUE TITLE
{% post_url %} not working with subdirectory

### ISSUE THREAD

**Issue by katelovescode** [jekyll/jekyll#3926]
I'm getting this error when presumably using the correct format for the tag.

```
Liquid Exception: Could not find post "/recipes/2015-07-08-overnight-oats-recipe" in tag 'post_url'. Make sure the post exists and the name is correct. in blogs/_posts/2015-07-01-coconut-milk.md
jekyll 2.5.3 | Error:  Could not find post "/recipes/2015-07-08-overnight-oats-recipe" in tag 'post_url'.

Make sure the post exists and the name is correct.
```

Here's my code:
```
I put it in smoothies, [overnight oats]({% post_url /recipes/2015-07-08-overnight-oats-recipe %})
```

Here's my directory structure:
```
- blogs/
-- _posts/
--- 2015-07-01-coconut-milk.md
- recipes/
-- _posts/
--- 2015-07-08-overnight-oats-recipe.md
```

Is it possible that because I'm referencing from within one subdirectory, it won't find the other?  It works if I don't include the subdirectory, but that precludes me having a blog post and recipe on the same day with the same name (which is how this issue originally arose - wanting to post a blog & recipe on the same day with the same topic, and linking using the subdirectory).

**Comment by parkr** [comment]
Hi Kate! This looks like an issue to me with the [PostComparer](https://github.com/jekyll/jekyll/blob/cd4829d28d3323bdf74dbb6808be99be8f1c1d41/lib/jekyll/tags/post_url.rb#L8-L18). Are you willing to take a stab at it?

**Comment by yihangho** [comment]
I am interested to give this a try. However, I am unable to reproduce the exact error, got this instead:

```
Deprecation: A call to '{{ post_url jekyll::tags::posturl }}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.
```

**Comment by parkr** [comment]
@yihangho That means the arguments to the `post_url` is different than the slug on the filesystem. That error message could be improved...

**Comment by yihangho** [comment]
I see. In that case, how should I proceed from here? Should I modify PostComparer to handle Kate's directory structure or simply improve the error message?

**Comment by parkr** [comment]
I believe I fixed the error in Jekyll 3 stable. PostComparer should be improved, however, to allow this. Mind taking a look?

**Comment by yihangho** [comment]
Not at all. I think we need to figure out how to deal with ambiguity though. Consider this directory structure:

```
Project Root
+-- _posts
|   +-- recipes
|   |   +-- 2015-10-31-first-recipe.markdown
|   +-- 2015-10-31-my-post.markdown
+-- recipes
    +-- _posts
        +-- 2015-10-31-first-recipe.markdown
```

Currently, `{% post_url 2015-10-31-first-recipe %}` refers to the one in `_posts/recipes`. To maintain backward compatibility, this behavior should be maintained.

In other words `{% post_url date-post %}` should look for posts in `_posts` and its (direct or indirect) subdirectory while `{% post_url dir/date-post %}` should search `dir/_posts` and its (direct or indirect) subdirectories. Is this reasonable?

**Comment by kateklemp** [comment]
Sorry I've disappeared on this, things have exploded at work the last few months - I'm following, though, thanks for picking up my slack @yihangho and @parkr

**Comment by parkr** [comment]
> In other words {% post_url date-post %} should look for posts in _posts and its (direct or indirect) subdirectory while {% post_url dir/date-post %} should search dir/_posts and its (direct or indirect) subdirectories. Is this reasonable?

That's a good place to start, yes. We can think about subdirectories later (e.g. _posts/dir)

**Comment by boompig** [comment]
+1 to this: posts are not found when referenced with `{% post_url dir/post_name %}`, but are found when simply referenced with `{% post_url post_name %}` when the post is in directory `dir`.

I'm running Jekyll version 3.0.0 on Mac OS X 10.9, if that helps.

**Comment by yihangho** [comment]
> We can think about subdirectories later (e.g. _posts/dir).

I just realize the behavior I described will actually break existing tests: https://github.com/jekyll/jekyll/blob/4fa7aa2613697f3bda271cd780d5dfeb2f119ad8/test/test_tags.rb#L440-L443

**Comment by spudowiar** [comment]
The problem is https://github.com/jekyll/jekyll/blob/master/lib/jekyll/tags/post_url.rb#L17 which was introduced when posts were treated as an ordinary collection. I can provide a pull request to fix this.

**Comment by RyanMcCarl** [comment]
I'm using Jekyll 3.4.3 and still get this error; the posts in subfolders appear in the build, but I get a deprecation notice that the `post_url` links to them need updatng:

```
       Deprecation: A call to '{{ post_url 2017-06-05-spanish-por-vs-para-by-example }}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.
                    done in 8.537 seconds.

```

Note that the actual slug / URL is `/spanish/spanish-por-vs-para-by-example/`

Thanks,
Ryan

**Comment by abethcrane** [comment]
I'm using jekyll 3.8.5 and if I have subfolders in _drafts I get this same error

> Deprecation: A call to '{% post_url 2018-05-20-flexing-my-willpower-muscles %}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.

I use _drafts for both drafts and private posts that I only wish to view locally, and don't plan on uploading anywhere.
