### ISSUE TITLE
Markdown not rendered on regeneration after changes to root-level files

### ISSUE THREAD

**Issue by joekissell** [jekyll/jekyll#3927]
On several test installations of jekyll 3.0.0.pre.beta8 (on both CentOS 7 and OS X), I've found that my sites build correctly the first time and regenerate correctly (and incrementally) on post changes. However, if I make changes to files at the top level of my source directory, such as index.html or _config.yml, then after regeneration, the index page shows raw Markdown rather than rendered content. This problem did not occur with jekyll 2.5.3.

(Similar behavior was noted in [#3747](https://github.com/jekyll/jekyll/issues/3747).)

Steps to reproduce:

1. Start with a clean site, e.g., `jekyll new`.
2. Modify index.html to display post content, e.g.:

        ---
        layout: default
        ---
        {% for post in site.posts %}
        {{ post.content }}
        {% endfor %}
3. Do `jekyll build`. Observe correctly rendered results in index.html.
4. Make any modification to index.html—even just `touch index.html`.
5. Once again, `jekyll build`. Incremental regeneration occurs.
6. Check the rendered index.html page. Everything that was inside `{{ post.content }}` is now raw Markdown.

If, between steps 4 and 5, I either delete .jekyll-metadata or do `jekyll clean`, the problem does not occur. (If I use `jekyll build --w` the problem occurs but can't be avoided by deleting the metadata file.)

And, I should reiterate that the problem doesn't occur if I merely make changes to items in the _posts directory, and it isn't evident if the index.html doesn't show `{{ post.content }}` or if the post content contains no Markdown or liquid tags. In addition, individual post pages are just fine after regeneration, Markdown intact; it's just the index.html page (as far as I've observed) that isn't correct.

**Comment by envygeeks** [comment]
Maybe this can be merged into #3747?

**Comment by joekissell** [comment]
@envygeeks Possibly. I'm not sure whether it's the same underlying problem or merely a similar symptom with a different cause.

**Comment by envygeeks** [comment]
They are the same problem they just have to different causes.
