### ISSUE TITLE
space-separated string for multiple tags is not working

### ISSUE THREAD

**Issue by zilongshanren** [jekyll/jekyll#3930]
As it mentioned in the http://jekyllrb.com/docs/frontmatter/

```
Similar to categories, one or multiple tags can be added to a post. Also like categories, tags can be specified as a YAML list or a space-separated string.
```

But only the YAML list works. 
please fix it, thanks.

**Comment by parkr** [comment]
did you try `category1, category2, category3`, i.e. a comma-separated string? The docs might be wrong in this case – AFAICR we have never supported a space-separated string.

**Comment by zilongshanren** [comment]
@parkr
Thanks. I know the reason now.

**Comment by yoshinari-nomura** [comment]
@parkr, are you talking about both `categories` and `tags`?

I'm afraid I misunderstood the relation between Jekyll and Octopress but
space-separated `categories` seems to work well with my Octopress environment while `tags` doesn't.

**Comment by parkr** [comment]
I mean both tags and categories. We prefer string array, but (I think) we allow a string of commas.
