### ISSUE TITLE
Build with CoffeeScript Dies Silently on Windows

### ISSUE THREAD

**Issue by OliverSherouse** [jekyll/jekyll#3932]
I've got a site that generates properly on Unix and on Github Pages. On Windows, however, when I try to build with any coffeescript file, including a blank one with just the yaml frontmatter, the build fails silently at the generation step:

    C:\Users\osherouse\blog>jekyll serve
    Configuration file: C:/Users/osherouse/blog/_config.yml
                Source: C:/Users/osherouse/blog
           Destination: C:/Users/osherouse/blog/_site
          Generating...

Coffee can compile properly when the frontmatter is removed. I'm using the Github-Pages bundle, so versions are uniform across installations. Coffee version is 1.9.3.

Any thoughts, or even thoughts on how I could get some useful debugging info? The build still dies silently with `--trace`.

**Comment by envygeeks** [comment]
`jekyll build --trace --verbose` and post the output please.

**Comment by OliverSherouse** [comment]
Thanks for the quick attention! No dice, I'm afraid: 

    C:\Users\osherouse\blog>jekyll build --trace --verbose
    Configuration file: C:/Users/osherouse/blog/_config.yml
                Source: C:/Users/osherouse/blog
           Destination: C:/Users/osherouse/blog/_site
          Generating...
    
    C:\Users\osherouse\blog>

**Comment by envygeeks** [comment]
The only other way to check on this issue would be to run the specs and see where they error out but that might be something you're not willing to do and I don't even know how well our specs are on Windows tbh.  If this can wait and you're willing to install Docker on Windows you can work around it for now by using our Docker images which will give us a bit of time to get on Windows (because AFAIW nobody uses Windows as their primary OS.) so Windows issues are served when there is time.

**Comment by OliverSherouse** [comment]
Thanks anyway. I probably won't rush to do it, but how would I go about running the specs?

**Comment by envygeeks** [comment]
`bundle install --path vendor/bundle -j 128 && script/test`

**Comment by envygeeks** [comment]
You'll need to pull the source of course.

**Comment by OliverSherouse** [comment]
Got it. Thanks!

**Comment by parkr** [comment]
A series of the specs fail on Windows, so this may pull a bunch of those.

CoffeeScript uses a series of C extensions (IIRC) so the likely cause is that some dynamic link is gone. The best course of action, I think, is to uninstall jekyll-coffee-script and its dependencies and re-install. That usually does it for people.

**Comment by parkr** [comment]
Please re-open on jekyll-coffeescript repo if this is still an issue.
