### ISSUE TITLE
Include directive with variable will not guess extension

### ISSUE THREAD

**Issue by fulldecent** [jekyll/jekyll#3938]
## Test case

**_includes/theInclude.htm**

    I'm in

**_layouts/page.htm**

    {% include {{ page.whichInclude }} %}

**aPage.htm**

    ---
    layout: page
    whichInclude: theInclude
    ---

## Expected

The resulting `aPage.htm` will contain `I'm in`.

## Actual

 > Liquid Exception: Included file '_includes/theInclude' not found in _layouts/page.htm

## Discussion

Tested and failed on Jekyll 2.5.3. The expected outcome WILL happen if we substitute `{{ page.whichInclude }}` to be `theInclude`.

**Comment by parkr** [comment]
> The expected outcome WILL happen if we substitute {{ page.whichInclude }} to be theInclude.

Weird... I definitely didn't expect that myself.

What is the value of `{{ page.whichInclude }}` in your template?

**Comment by fulldecent** [comment]
It is `theInclude`

**Comment by fulldecent** [comment]
Confirmed still broken on jekyll 3.0.1

**Comment by parkr** [comment]
@fulldecent Do you mean 3.1.6? 3.0.1 is not something we're still working on.

**Comment by envygeeks** [comment]
I'm confused, is this a feature or a bug?

**Comment by fulldecent** [comment]
I have tested again in 3.1.6 and found that:

 * `{% include {{ page.whichInclude }} %}` does not work (same since originally reported)
 * `{% include theInclude %}` does not work (different since reported, not sure when changed)

This behavior is now consistent. Thank you, closing issue.
