### ISSUE TITLE
Commands in _plugins/

### ISSUE THREAD

**Issue by thom-nic** [jekyll/jekyll#3939]
Apologies if this is covered somewhere or I am just doing something stupid...

I am attempting to add a jekyll command (e.g. a `.rb` file that defines a class which extends `Jekyll::Command`) to the `_plugins/` directory.  At the beginning of the [Plugins documentation](http://jekyllrb.com/docs/plugins/#installing-a-plugin) it suggests that using `_plugins/` is equivalent to the Gemfile or _config.yml method.  However the [section on Commands](http://jekyllrb.com/docs/plugins/#commands) specifically mentions the Gemfile method only.  So does that mean I can't create a command in `_plugins/`?  

If so, maybe documentation should be more explicit.  If not, I'm not sure why I can't get it to work.  `jekyll --help` only shows the builtin commands.

**Comment by parkr** [comment]
> So does that mean I can't create a command in _plugins/?

Yes! That's why the documentation adds that exception specifically. How would you word it? Please send a PR!

**Comment by thom-nic** [comment]
Something like 
> **Please note**: commands can **only** be created by adding plugins to `Gemfile`, not from the `_plugins` folder.

would make it unambiguous.  Regardless, thx for clarifying.

**Comment by envygeeks** [comment]
It's only ambiguous if you assume that commands are plugins, but they aren't IMO so your wording seems to imply that.  I would refine that to not mention plugins and simply mention commands as gems.

**Comment by thom-nic** [comment]
My understanding of Commands is based solely on the Jekyll documentation, where Commands are a subsection of the plugins page.  

Honestly not trying to be deliberately obtuse or abrasive, honestly this is how the doc reads.  I guess most newbs aren't trying to add commands off the bat :D  I have an old octopress rake task that uploads the static site to S3 that I'm trying to port to jekyll.  Moving the code to `_plugins/` and converting to a `Jekyll::Command` seemed to make sense after reading the Plugins doc.

**Comment by parkr** [comment]
A PR will be more convincing :wink: I'd be happy to make the change if you are willing to make a PR!
