### ISSUE TITLE
"include" syntax in the demo code is Interpreting somehow

### ISSUE THREAD

**Issue by kamlekar** [jekyll/jekyll#3941]
I am using Kramdown markdown in Jekyll blog template for my site which is getting published on github from [here](http://github.com/kamlekar/kamlekar.github.io). 

In one of the `.md` files, I wrote a sample demo code which is something like this:

     {% include "_head.html" %}

After inserting this code in my post and running my site, I am getting "page build" error.

You can find the file [here](https://github.com/kamlekar/kamlekar.github.io/blob/master/_posts/2015-08-26-compiling-html-templates-to-html-pages.md).

I already asked the same question on [kramdown issue tracker](https://github.com/gettalong/kramdown/issues/277), which got closed as off-topic.

Thanks in Advance.

**Comment by envygeeks** [comment]
Please provide the error.

**Comment by kamlekar** [comment]
Here is the error which was sent by github support on request:

>Invalid syntax for include tag. File contains invalid characters or sequences:

>  "_head.html"

>Valid syntax:

>  {% include file.ext param='value' param2='value' %}

**Comment by envygeeks** [comment]
What happens when you remove the quotes as it implies.

**Comment by kamlekar** [comment]
@envygeeks  FYI, we had this discussion before [here](https://github.com/jekyll/jekyll/issues/2844#issuecomment-135054243)

I didn't check that, I will check now and share the result here.

**Comment by kamlekar** [comment]
I just checked by removing quotes and I got this mail:

>The page build failed with the following error:

>A file was included in `_posts/2015-08-26-compiling-html-templates-to-html-pages.md` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink.

>If you have any questions you can contact us by replying to this email.

**Comment by kamlekar** [comment]
FYI, I am using the jekyll version which is taken from [clean blog template](https://github.com/IronSummitMedia/startbootstrap-clean-blog-jekyll). @envygeeks

**Comment by kamlekar** [comment]
Please remove the "pending feedback" label as I shared the information.

**Comment by parkr** [comment]
Are you asking we allow `include` tag calls with quotes?

**Comment by envygeeks** [comment]
This is probably part of the larger rewrite of the tag syntax parser I was going to port into Jekyll from Jekyll-Assets, I've already got it built out but I won't send a PR until 3.0 is released.

**Comment by parkr** [comment]
> I've already got it built out

@envygeeks Rock on. Looking forward to it. :metal:

**Comment by kamlekar** [comment]
Why this is closed? Is the issue fixed?

**Comment by parkr** [comment]
@kamlekar It was closed because nothing happened for over 2 months. We have a very limited amount of time to tackle issues and would love more help. Is this still a problem for you? Could you write a test which demonstrates the behaviour you're looking for and submit it as a pull request?

We don't allow quotes and the error message is fairly clear on that. Included files, in your case `_head.html`, must be a regular file at `_includes/_head.html`. You can use `include_relative` to include other files.

**Comment by RoyiAvital** [comment]
By the way, in the [Includes Guide](https://jekyllrb.com/docs/includes/) there is the following:

```
{% if page.my_variable %}
  {% include {{ page.my_variable }} %}
{% endif %}
```

Is there a syntax for `if not` and `elseif`?

I want to verify a variable was defined in the include string and act differently on it.

**Comment by ashmaroli** [comment]
> Is there a syntax for `if not` and `elseif`?

Yo can use `{% unless ... %}` and `{% elsif %}`
Refer: https://shopify.github.io/liquid/tags/control-flow/

P.S. *Please refrain from posting in old issue tickets.
The issue tracker on Jekyll's GitHub repo is for reporting bugs only.
For everything else, please seek support at https://talk.jekyllrb.com/*
