### ISSUE TITLE
HTML5 History API Support

### ISSUE THREAD

**Issue by JedWatson** [jekyll/jekyll#3943]
I'm having trouble publishing a site built with React.js and [react-router](https://github.com/rackt/react-router) to GitHub pages, using the HTML5 History API to handle navigation. Apologies if this is possible and I've not found the setting.

Jekyll (I think, otherwise gh-pages) supports a custom 404.html document, but it would be really useful to be able to serve a default document at any path without the `HTTP/1.1 404 Not Found` header.

If it helps, you can see the site here: http://elemental-ui.com and the source is [here](https://github.com/elementalui/elemental/tree/gh-pages)

Notice that when you navigate, the router updates the URL correctly, but when you refresh the page is lost (it goes to the 404, which redirects to `/`) and its not possible to bookmark / link directly to pages.

I think a possible workaround is to create duplicates of my `index.html` page with a permalink for each route, but this would be a real pain to manage as the sitemap expands. First-class support for this use case would be awesome.

Thanks!

**Comment by envygeeks** [comment]
That's probably something you'll have to take up with support@github.com because we don't control their servers, they just use Jekyll and organize it how they see fit (albeit mostly vanilla) but the problem you are having is mostly related to the server.

**Comment by JedWatson** [comment]
Thanks for the quick response! Will do :)

**Comment by envygeeks** [comment]
To add a small note I forgot to add, is there no way to reorganize the router in to support /page.html as /page because Github will route /page to /page.html or /page/index.html AFAIW.
