### ISSUE TITLE
Build a YAML wrapper and move to Psych.safe_load.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#3951]
On Ruby 2.1 (or any Ruby with new Psych [I believe]) we should use YAML.safe_load instead of safe_yaml.  I propose that we build a YAML wrapper that handles this so that we can deprecate it coming into 3.0 and push it out as we push out old versions of Ruby.  This will also reduce our need for an extra dependency for newer Rubies.

**Comment by parkr** [comment]
Maybe throw it in our utilities class: `Jekyll::Utils.safe_load_yaml(fname)`. This can be added at any point in the release cycle.

In terms of conditional dependencies, we won't be able to remove the `safe_yaml` gem until we deprecate support for Rubies without `YAML.safe_load`. Gemspecs are, unfortunately, static. I tried to add a conditional dependency on wdm for windows folks, but it did not work. Either everyone gets it, or no one gets it. :/

**Comment by envygeeks** [comment]
Hulk: backlog +jekyll/jekyll ++priority:high
