### ISSUE TITLE
"jekyll build relative" as a way to output a _site folder that does not need a server.

### ISSUE THREAD

**Issue by Joshfindit** [jekyll/jekyll#3952]
Essentially, Jekyll would build the entire site with only realitive paths, such as:

    <link rel="stylesheet" type="text/css" href="../../style.css">
    <a href="../about.html">
    <img src="./images/logo.png">

This is the kind of tedious work that sucks to do manually, and makes sense to do programically. Jekyll knows whether something is a subfolder, how many levels deep it is, and everything else neccessary to do this kind of work.

For compatibility, Jekyll could set url to nil, and baseurl to the relative path (eg. ".", "../..", etc)

**Comment by parkr** [comment]
This is a really neat idea, but it's not within the scope of Jekyll. At the moment, we don't deal at all with your content directly – we pass it to a Markdown renderer (or Sass, or Textile, etc) then pass it to Liquid. If we were to do this, we would have to find all our HTML files, run them through something like Nokogiri or Hpricot, iterate over all the `a` tags, find a document that matches that output path, and rewrite the a tag.

It's something a plugin could do with our new [Hooks](http://jekyllrb.com/docs/plugins/#hooks) architecture, however. Perhaps look into that.

Thanks for the idea, though! Unfortunately, it's not something Jekyll core can include at this time.

**Comment by Joshfindit** [comment]
I wasn't aware that Jekyll doesn't handle the content directly.

Thanks for the explanation.
Consider the request withdrawn.

Cheers
