### ISSUE TITLE
use_coderay: false does not work with kramdown GFM

### ISSUE THREAD

**Issue by jhalterman** [jekyll/jekyll#3953]
Using Jekyll 2.5.3

Apologies if this is a kramdown issue rather than jekyll - not sure.

Basically, when enabling GFM and using a fenced code block, coderay highlighting always hapepns even with `use_coderay` set to false.

**Comment by envygeeks** [comment]
It looks like this is a bug in Kramdown because according to https://github.com/jekyll/jekyll/blob/master/lib/jekyll/converters/markdown/kramdown_parser.rb#L23 we simply just send your options off to them.

**Comment by jhalterman** [comment]
Thanks for the quick response.

**Comment by envygeeks** [comment]
I'm wrong.  It's not a bug in Kramdown, it's a bug with us.

**Comment by envygeeks** [comment]
Sorry no, I'm wrong again, haha sorry, that's for coderay specific options.

**Comment by jhalterman** [comment]
FWIW: a workaround for anyone else who stumbles on this:

```
  syntax_highlighter: none
  use_coderay: false
```
