### ISSUE TITLE
This syntax site.list[page.value].attr1 doesn't work in include

### ISSUE THREAD

**Issue by GNUletik** [jekyll/jekyll#3954]
Hi,
I discovered what I think is a bug in the last version of jekyll.
As code will be more explicit : 
This work : 
```jekyll
{% assign tmp=site.list[page.value].attr1 %}
```
But this doesn't : 
```jekyll
{% include include.html var=site.list[page.value].attr1 %}
```
I see no reason it couldn't work.

Of course, as a workaround, we just have to assign a temporary variable and then, send it to the include.

You can test it with : 

```bash
git clone https://github.com/GNUletik/jekyll-include-bug && cd jekyll-include-bug && jekyll build
```
Thanks for your answer :)
If you need more information, just ask :)

**Comment by envygeeks** [comment]
This is part of a larger issue with tags that we plan on addressing soon.
