### ISSUE TITLE
Use include params in other tags

### ISSUE THREAD

**Issue by jhalterman** [jekyll/jekyll#3955]
It would be great to be able to use include params in other tags in an included file. Ex:

```
{% assign words = {{ include.words }} | split: ' ' %}
```

Or even better:

```
{% assign words = include.words | split: ' ' %}
```

Currently this yields:

```
Error: undefined method `split' for nil:NilClass
```

If I'm missing a workaround for this, feel free to let me know.

**Comment by envygeeks** [comment]
Does assign accept other variables? If it doesn't then this is an upstream issue.

**Comment by envygeeks** [comment]
Also, I think this might be a case for capture:

```liquid
{% capture var %}{{ include.words | split: ' ' }}{% endcapture %}
```

Though I don't know if that will create an array.

**Comment by jhalterman** [comment]
@envygeeks Assign will accept other assigned variables (and perhaps other things), but not include params.

**Comment by parkr** [comment]
@jhalterman What do your include params look like? [Liquid should support it if our implementation is correct](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/tags/include.rb#L126-L131). Hopefully it's not some reserved keyword.

What version of Jekyll is this?

**Comment by jhalterman** [comment]
Sorry for not mentioning - it's jekyll 2.5.3

**Comment by envygeeks** [comment]
The blame for that file shows that the linked source is 3.0.0, can you try it with `gem install jekyll --pre`?

**Comment by parkr** [comment]
@jhalterman Please let us know exactly what the `{% include %}` call looks like as I asked for above.

**Comment by jhalterman** [comment]
@parkr My include statement looks like:

```
{% include sync-tabs.html active=".sync:Sync API" %}
```

I can echo the include.active value out, I just can't use it in a tag, such as:

```
{% assign words = {{ include.active }} | split: ' ' %}
```

@envygeeks Sorry for the slow response on 3.0.0 pre - I've installed it via rbenv but jekyll -version is still showing 2.5.3. I suck.

**Comment by parkr** [comment]
I can tell you for sure that the `{{` and `}}` inside the `assign` tag is invalid, so it should just be

```liquid
{% assign words = include.active | split: ' ' %}
```

but I can't tell you why it's failing. @fw42, is `include` a reserved word?

**Comment by jhalterman** [comment]
@parkr Thanks - I wasn't sure why it failed to resolve so I tried it both ways.

**Comment by jhalterman** [comment]
@envygeeks Things seem good with the 3.0.0 pre-release. I suppose it will be a while before gh-pages gets 3.0.0 though, so I'll hack around this in the meantime.

**Comment by envygeeks** [comment]
Great!

**Comment by parkr** [comment]
> I suppose it will be a while before gh-pages gets 3.0.0 though, so I'll hack around this in the meantime.

They're in the process of doing a security review so hopefully the upgrade path is smoother.
