### ISSUE TITLE
Jekyll Serve generates main.scss instead of main.css

### ISSUE THREAD

**Issue by ggw215** [jekyll/jekyll#3957]
I've been monkeying around trying to create a site with jekyll and once I had finished a bit of work I restarted the jekyll server and wouldn't you know it:

![screen shot 2015-09-01 at 10 15 51 pm](https://cloud.githubusercontent.com/assets/6859374/9623530/0af7ae84-50f7-11e5-9d9d-d1053935a22e.png)

Massive icons and no styles

The network tab in the chrome console is telling me that the /css/main.css is not found. Correct it is! Because in the _site/css directory is a main.scss It is not converted to css. Please help!

_config.yml:

description: "" 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/archives/page/:num"

exclude: ["vendor"]

sass:
    style: compressed
    sass_dir: _sass

**Comment by envygeeks** [comment]
Did you forgot to include the `---\n---` in your main.scss?

**Comment by ggw215** [comment]
My main.scss file begins with:
---
# Only the main Sass file needs front matter (the dashes are enough)
---

**Comment by mmistakes** [comment]
@ggw215 Where does `main.scss` live... in `<root>/css/`? Also do you have any Sass partials, are they in `_sass`? If you have any Sass partials what does that structure look like? Do you have a folder named `vendor` with .scss inside? I've seen that blow up stylesheets because of `exclude: ["vendor"]` in `_config.yml`.

**Comment by ggw215** [comment]
@mmistakes main.scss lives in the ```<root>/css/``` and I have some sass partials and they are as you say in the _sass directory.
There is no vendor folder, and I removed my ```exclude:["vender"]``` in my ```_config.yml``` to no avail.

**Comment by pathawks** [comment]
Is your source public?  
Or can you create a small test site that reproduces this behavior?

**Comment by ggw215** [comment]
https://github.com/ggw215/temp_jekyll_site
duplicate repo with the problem in it

**Comment by parkr** [comment]
@ggw215 We have had some problems where the front matter exists but has a BOM preceding it or spaces after the first set of dashes. can you check those?

**Comment by ggw215** [comment]
@parkr I posted the front matter above, no extra spaces unfortunately

**Comment by parkr** [comment]
There's usually a "show special characters" setting in your editor. You could try that.

Have you tried moving the file and creating a new one? Ruby isn't the best with file encodings, sadly.

**Comment by ggw215** [comment]
@parkr  I have tried both to no avail. It's so odd because I can create a brand new site and it works, but as soon as I start adding stuff it breaks. I don't understand what is breaking it.

**Comment by ggw215** [comment]
Ok looks like when I added a Gemfile so that Heroku could install the dependencies THAT's where everything breaks. it replaces needed gems I guess? So how do I deploy to heroku without breaking everything?

**Comment by parkr** [comment]
What's in your gemfile and gemfile.lock?

**Comment by ggw215** [comment]
Gemfile:
```
source 'https://rubygems.org'
ruby '2.1.5'
gem 'jekyll'
gem 'kramdown'
gem 'rack-jekyll'
gem 'rake'
gem 'puma'
```

Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    blankslate (2.1.2.4)
    classifier (1.3.4)
      fast-stemmer (>= 1.0.0)
    colorator (0.1)
    commander (4.1.6)
      highline (~> 1.6.11)
    fast-stemmer (1.0.2)
    ffi (1.9.10)
    highline (1.6.21)
    jekyll (1.5.1)
      classifier (~> 1.3)
      colorator (~> 0.1)
      commander (~> 4.1.3)
      liquid (~> 2.5.5)
      listen (~> 1.3)
      maruku (= 0.7.0)
      pygments.rb (~> 0.5.0)
      redcarpet (~> 2.3.0)
      safe_yaml (~> 1.0)
      toml (~> 0.1.0)
    kramdown (1.8.0)
    liquid (2.5.5)
    listen (1.3.1)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      rb-kqueue (>= 0.2)
    maruku (0.7.0)
    parslet (1.5.0)
      blankslate (~> 2.0)
    posix-spawn (0.3.11)
    puma (2.13.4)
    pygments.rb (0.5.4)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.1.0)
    rack (1.5.5)
    rack-jekyll (0.4.1)
      jekyll (>= 0.12.0, < 2.0)
      rack (~> 1.5.0)
    rake (10.4.2)
    rb-fsevent (0.9.6)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rb-kqueue (0.2.4)
      ffi (>= 0.5.0)
    redcarpet (2.3.0)
    safe_yaml (1.0.4)
    toml (0.1.2)
      parslet (~> 1.5.0)
    yajl-ruby (1.1.0)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll
  kramdown
  puma
  rack-jekyll
  rake
```

even when I exclude both those files in the _config.yml it still won't work

**Comment by ggw215** [comment]
The ```rb-fsevent (0.9.6)``` gem has come up in error messages while monkeying around trying to mirror jekyll's list of dependencies.

**Comment by parkr** [comment]
You're using Jekyll 1.x! Hahahah. You need jekyll 2 to use Sass.

**Comment by whereswaldon** [comment]
I'm getting an identical issue, but by Gemfile.lock has
```
GEM
  remote: https://rubygems.org/
  specs:
    RedCloth (4.2.9)
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    blankslate (2.1.2.4)
    classifier-reborn (2.0.4)
      fast-stemmer (~> 1.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    colorator (0.1)
    ethon (0.8.1)
      ffi (>= 1.3.0)
    execjs (2.6.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    fast-stemmer (1.0.2)
    ffi (1.9.10)
    gemoji (2.1.0)
    github-pages (42)
      RedCloth (= 4.2.9)
      github-pages-health-check (= 0.5.3)
      jekyll (= 2.4.0)
      jekyll-coffeescript (= 1.0.1)
      jekyll-feed (= 0.3.1)
      jekyll-gist (= 1.4.0)
      jekyll-mentions (= 0.2.1)
      jekyll-paginate (= 1.1.0)
      jekyll-redirect-from (= 0.9.1)
      jekyll-sass-converter (= 1.3.0)
      jekyll-seo-tag (= 0.1.4)
      jekyll-sitemap (= 0.9.0)
      jemoji (= 0.5.0)
      kramdown (= 1.9.0)
      liquid (= 2.6.2)
      maruku (= 0.7.0)
      mercenary (~> 0.3)
      pygments.rb (= 0.6.3)
      rdiscount (= 2.1.8)
      redcarpet (= 3.3.3)
      terminal-table (~> 1.4)
    github-pages-health-check (0.5.3)
      addressable (~> 2.3)
      net-dns (~> 0.8)
      public_suffix (~> 1.4)
      typhoeus (~> 0.7)
    html-pipeline (1.9.0)
      activesupport (>= 2)
      nokogiri (~> 1.4)
    i18n (0.7.0)
    jekyll (2.4.0)
      classifier-reborn (~> 2.0)
      colorator (~> 0.1)
      jekyll-coffeescript (~> 1.0)
      jekyll-gist (~> 1.0)
      jekyll-paginate (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 2.6.1)
      mercenary (~> 0.3.3)
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      safe_yaml (~> 1.0)
      toml (~> 0.1.0)
    jekyll-coffeescript (1.0.1)
      coffee-script (~> 2.2)
    jekyll-feed (0.3.1)
    jekyll-gist (1.4.0)
      octokit (~> 4.2)
    jekyll-mentions (0.2.1)
      html-pipeline (~> 1.9.0)
      jekyll (~> 2.0)
    jekyll-paginate (1.1.0)
    jekyll-redirect-from (0.9.1)
      jekyll (>= 2.0)
    jekyll-sass-converter (1.3.0)
      sass (~> 3.2)
    jekyll-seo-tag (0.1.4)
      jekyll (>= 2.0)
    jekyll-sitemap (0.9.0)
    jekyll-watch (1.3.0)
      listen (~> 3.0)
    jemoji (0.5.0)
      gemoji (~> 2.0)
      html-pipeline (~> 1.9)
      jekyll (>= 2.0)
    json (1.8.3)
    kramdown (1.9.0)
    liquid (2.6.2)
    listen (3.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    maruku (0.7.0)
    mercenary (0.3.5)
    mini_portile2 (2.0.0)
    minitest (5.8.3)
    multipart-post (2.0.0)
    net-dns (0.8.0)
    nokogiri (1.6.7.1)
      mini_portile2 (~> 2.0.0.rc2)
    octokit (4.2.0)
      sawyer (~> 0.6.0, >= 0.5.3)
    parslet (1.5.0)
      blankslate (~> 2.0)
    posix-spawn (0.3.11)
    public_suffix (1.5.3)
    pygments.rb (0.6.3)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.2.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.5)
      ffi (>= 0.5.0)
    rdiscount (2.1.8)
    redcarpet (3.3.3)
    safe_yaml (1.0.4)
    sass (3.4.21)
    sawyer (0.6.0)
      addressable (~> 2.3.5)
      faraday (~> 0.8, < 0.10)
    terminal-table (1.5.2)
    thread_safe (0.3.5)
    toml (0.1.2)
      parslet (~> 1.5.0)
    typhoeus (0.8.0)
      ethon (>= 0.8.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    yajl-ruby (1.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  github-pages

BUNDLED WITH
   1.11.2

```

My repo lives [here](https://github.com/whereswaldon/coding-blog/tree/gh-pages). Do you have any idea what I'm doing wrong?

**Comment by parkr** [comment]
@whereswaldon this is always a problem with the `limk` element in your page's head. Inspect the source and you should see that element. The href value is probably incorrect.

**Comment by Strangehill** [comment]
tangential question: 
wouldn't adding the width and height attributes to the `svg` elements in the site template's header.html and footer.html _includes, and removing them from base.scss help with graceful degradation?

**Comment by whereswaldon** [comment]
Found it. I was the dumb and hadn't properly configured my baseurl in _config.yml. Newbie mistake.

**Comment by so0k** [comment]
for anyone coming here from google, another reason may be a change in the minima theme (the default jekyll theme): https://github.com/jekyll/minima#customization
> The site's default CSS has now moved to a new place within the gem itself, assets/main.scss

perhaps the blog was created with an older version of the gem (putting the Gemfile.lock in git helps to ensure gem version is consistent across environments)

**Comment by jeffchang5** [comment]
Had this issue with Webstorm as my editor. There was indeed special whitespace characters before my front-matter

**Comment by richcouzzi** [comment]
For me the issue was I used a formatter in my IDE to beautify my sass. In doing so I unknowingly reformatted the first line to:

```
---# main.scss---
```
Which caused `ERROR '/assets/main.css' not found.`

Reverting it to the correct format fixed my issue:

```
---
# main.scss
---
```
