### ISSUE TITLE
.htaccess Files are ignored from exclude: filter in _config.yml

### ISSUE THREAD

**Issue by htmelvis** [jekyll/jekyll#3958]
The documentation states that dotfiles (.htaccess) should be placed in the `include:` filter in your config file. By default dotfiles are ignored.

 .htaccess is compiled and placed in the jekyll `destination:`  even if placed in the `exclude:` filter  

The issue stems from #742 and I believe it was brought back here: 
<img width="973" alt="screen shot 2015-09-02 at 2 18 10 pm" src="https://cloud.githubusercontent.com/assets/1952926/9640200/580bf248-517e-11e5-9959-f0c9c54f391b.png">

**Comment by kenzierocks** [comment]
+1, this is a big problem if you have a rewrite in `.htaccess`.

**Comment by ashmaroli** [comment]
To *exclude* `.htaccess` from being processed into `_site/`, insert an empty `include:` list in your config file:
```yaml
# _config.yml

# the empty 'include' list below overrides the default
# setting `include: [".htaccess"]`
include: []
```

**Comment by Crunch09** [comment]
@ashmaroli Any further action we need to take here before we can close this one? Just wondering as it's open for two years.
