### ISSUE TITLE
Operations on an included variable doesn't work if I use it like page.test[variable_name].test

### ISSUE THREAD

**Issue by GNUletik** [jekyll/jekyll#3960]
Hi,
I just discovered that if I use a variable in an included file and apply an operation (minus, plus etc..) on it. I'm unable to do something like ```page.test[variable_name].test```

If I don't make any operations, it just works.

Here is an example : 
```
git clone https://github.com/GNUletik/jekyll-include-filter-bug.git && cd jekyll-include-filter-bug && jekyll build && cat _site/index.html
```
Github gh-pages's here : http://gnuletik.github.io/jekyll-include-filter-bug/

Is that related to #3954 ?

Thanks :)

**Comment by envygeeks** [comment]
Dup of #3954
