### ISSUE TITLE
Different results with same code in `index.html`

### ISSUE THREAD

**Issue by darshanime** [jekyll/jekyll#3961]
I was setting up my blog from someone's theme I took up. I wished to change the landing page to the `About Me` page. So, I took the code in `index.html` which showed the most recent 8 blog posts and copied it to `blog.html`. Also, I pasted the code for `about.md` into `index.html` but it did not work. So, I copied the `html` generated by Jekyll from `_sites` dir. Then I added a link to the `blog.html` page from `index.html`. Recall `blog.html` had the original `index.html` code. However, when I navigate to that page, I do not get the blog entries ; it is just a blank page.

Here is the original code in `index.html` which I copied to `blog.html` :

```html
---
layout: default
---
<!-- Posts -->
<ul id="posts">
	{% for post in paginator.posts %}
	  <li class="post">
	  	<h2><a href="{% if site.baseurl == "/" %}{{ post.url }}{% else %}{{ post.url | prepend: site.baseurl }}{% endif %}">{{ post.title }}</a></h2>
	  	<time datetime="{{ post.date | date_to_xmlschema }}" class="by-line">{{ post.date | date_to_string }}</time>
	  	<p>{{ post.content | strip_html | truncatewords:50 }}</p>
	  </li>
    {% endfor %}
</ul>
```

This snippet works in `index.html` and not in `blog.html`. Is this an error or am I doing something wrong ? (and in that case, I apologize for posting this here)

**Comment by parkr** [comment]
Pagination (famously) [only works with `index.html`](https://github.com/jekyll/jekyll-paginate/blob/52262e7fe1e9b54610992d2449a50f221edf2cb2/lib/jekyll-paginate/pager.rb#L39). You'll have to find another pagination solution, sadly.
