### ISSUE TITLE
installation docs fail to document required version of Ruby

### ISSUE THREAD

**Issue by oresmus** [jekyll/jekyll#3963]
Jekyll apparently has system requirements which are not mentioned on any of these pages:

    http://jekyllrb.com/docs/quickstart/

    http://jekyllrb.com/docs/installation/

    http://jekyllrb.com/docs/troubleshooting/

Specifically, it uses a subpackage which says it requires Ruby version >= 1.9.3.

##### Background and details: 

I am running Mac OS X 10.7.5. It has Ruby 1.8.7, apparently from Apple. I have successfully installed RubyGems in the past.

I first solved a minor problem, namely that "gem install jekyll" hung with no error message, consuming 100% cpu until I killed it after a few minutes, by running

    % sudo gem update --system

as advised by the troubleshooting page. I then got a permission error from `gem install jekyll`, so I tried

    % sudo gem install jekyll

which started working, but then reported the system requirement mentioned above:

    % sudo gem install jekyll
    Fetching: fast-stemmer-1.0.2.gem (100%)
    Building native extensions.  This could take a while...
    Successfully installed fast-stemmer-1.0.2
    Fetching: classifier-reborn-2.0.3.gem (100%)
    ERROR:  Error installing jekyll:
    	classifier-reborn requires Ruby version >= 1.9.3.
    Exit 1
    % 

I will of course try to install a newer Ruby, but so far (as a Ruby beginner) I find multiple ways of doing this on OSX, no clear indication of which is best, and that many of them don't list their system requirements regarding required version of OSX.

##### Suggested fix:

The jekyll installation pages should list explicitly whatever oldest version of Ruby (and of Mac OS X) is supported.

Also, if practical, they should suggest a specific way of installing a newer Ruby on OS X which is known to work well with jekyll. (This may be helpful only to Ruby beginners, but Jekyll is useful for anyone wanting to use gh-pages, and many of them may have no other need for Ruby.)

**Comment by jaybe-jekyll** [comment]
Updating the (OSX) system gem with sudo is an absolute Nono. Never mess with OSX internals in any way. 

If you desire a custom Ruby, use homebrew or the likes to achieve it. Rbenv is a optio. And works well. 

Furthermore I prefer to install Jekyll locally as a user and [only] in user space. That can be accomplished with something such as the following:

'gem install --no-rdoc --no-ri -n ~/bin --user-install --verbose jekyll'

**Comment by envygeeks** [comment]
Stable Jekyll does support 1.9.3 and if you can't install it with 1.9.3 then that is a bug and we need to release a hotfix (IMO -- but I'll digress to @jekyll/core) to lock the dependency that prevents that installation.  As far as supporting an older version of OS X outside of the normal guides... I would say probably not gonna happen.  Even some of our work around (like Docker) don't even support 10.7.

**Comment by envygeeks** [comment]
Let me also add that aside from what @jaybe-jekyll posted there is also rvm which if I remember right (and @mpapis would have to confirm) will do everything for you as a one stop shop from installing the tools you need to providing the latest Rubies.

**Comment by oresmus** [comment]
"supporting an older version of OS X outside of the normal guides"...

This issue is just that those guidelines are not documented. (The jekyll pages say nothing that I can find about required version of either OSX or Ruby.)

Thanks for the other info... I'm in the middle of investigating and trying all that. Nothing has yet fully worked, but I should probably not clutter this issue with any details.

**Comment by oresmus** [comment]
(BTW @jaybe-jekyll  the sudo commands I ran came straight from http://jekyllrb.com/docs/troubleshooting/ , so maybe you would consider that another doc bug about that page.)

**Comment by oresmus** [comment]
@envygeeks , I did not yet try ruby 1.9.3 (I had an older one, since then I have tried only with the latest one), and the error message I listed suggests that it might work with 1.9.3, just not with anything older than that.

**Comment by alfredxing** [comment]
It seems like the required Ruby version for the latest release, 2.5.3, is Ruby 1.9.3, and for the upcoming 3.0 release (including the current beta releases), it's Ruby 2.0.0.

This is specified in the gemspec, and I would expect RubyGems to detect this and prevent you from installing the gem if your Ruby doesn't meet the requirement...

But it would be a good idea to also specify on the installation pages!

**Comment by envygeeks** [comment]
I thought there was a pull request that was merged that did this but I'm too lazy to search.

**Comment by chrisfinazzo** [comment]
FWIW, the requirement for Ruby 2.0 is documented on the Troubleshooting page under [Installation Problems][]. At the same time, the [use case][] for NearlyFreeSpeech and several Linux distributions (Debian/Ubuntu) still reference v1.8 to set the correct `$PATH`.

Seems like a good time to encourage people to get off 1.8 and 1.9 if they possibly can. @oresmus, is there a reason you needed an old version? Compatibility, I suppose, but now I'm guessing.

The oldest version of OS X I can remember using Jekyll on is 10.8, and even there, I think I used [rbenv][] to get Ruby 2.0.

[Installation Problems]: http://jekyllrb.com/docs/troubleshooting/#installation-problems

[use case]: http://jekyllrb.com/docs/troubleshooting/#problems-running-jekyll

[rbenv]: https://github.com/sstephenson/rbenv

**Comment by envygeeks** [comment]
No matter the usecase it was already agreed to drop EOL (1.8 and 1.9 in 3.0) Rubies to simplify and push towards the future, and we even have some code that would prevent those old Rubies anyways.  As far as Debian and Ubuntu: https://github.com/jekyll/jekyll/pull/3785

**Comment by oresmus** [comment]
@chrisfinazzo , I didn't need to use an old version of ruby; I just needed to know which version to use (and how). I have no knowledge about ruby and just wanted to get jekyll running.

FYI, I ended up upgrading to Yosemite, and eventually got jekyll to work (after fixing several problems not mentioned on the Troubleshooting page, with the partial help of some other bug reports here). If anyone intends to update that page, I'd be happy to summarize the problems and what I did about them. I should not suggest specific changes to that page myself, since I don't know which things I did mattered, might cause other problems, etc.

As for the required Mac OS version -- just from my own experience I'd advise anyone in the same situation to try at least Mac OS 10.8, but again I can't say whether that's what you should recommend in general (and I didn't try it, since I went directly from 10.7.5 to 10.10.5).

**Comment by envygeeks** [comment]
IMO it's better to submit a pull request and let us comment and have you cherry-pick the useful bits than to leave it to us because we are programmers who use Ruby on a daily basis so our troubles aren't the same as your troubles.

**Comment by oresmus** [comment]
(@chrisfinazzo , FYI, I don't agree that "the requirement for Ruby 2.0 is documented on the Troubleshooting page" -- by my reading, that info is Linux-specific, and also sounds more like "if you are using Ruby 2.0, do such and such" rather than "you need to be using Ruby 2.0".)
