### ISSUE TITLE
ubuntu下无法安装jekyll

### ISSUE THREAD

**Issue by yuzhubin** [jekyll/jekyll#3964]
ubuntu版本10.04 
执行命令依次为
1、apt-get install ruby
2、apt-get install ruby1.9.1-dev
3、gem install jekyll
出现以下错误：
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- net/https (LoadError)
	from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
	from /usr/lib/ruby/1.8/rubygems/remote_fetcher.rb:241:in `connection_for'
	from /usr/lib/ruby/1.8/rubygems/remote_fetcher.rb:320:in `request'
	from /usr/lib/ruby/1.8/rubygems/remote_fetcher.rb:279:in `open_uri_or_path'
	from /usr/lib/ruby/1.8/rubygems/remote_fetcher.rb:288:in `open_uri_or_path'
	from /usr/lib/ruby/1.8/rubygems/remote_fetcher.rb:164:in `fetch_path'
	from /usr/lib/ruby/1.8/rubygems/spec_fetcher.rb:227:in `load_specs'
	from /usr/lib/ruby/1.8/rubygems/spec_fetcher.rb:192:in `list'
	from /usr/lib/ruby/1.8/rubygems/spec_fetcher.rb:188:in `each'
	from /usr/lib/ruby/1.8/rubygems/spec_fetcher.rb:188:in `list'
	from /usr/lib/ruby/1.8/rubygems/spec_fetcher.rb:123:in `find_matching'
	from /usr/lib/ruby/1.8/rubygems/spec_fetcher.rb:69:in `fetch'
	from /usr/lib/ruby/1.8/rubygems/dependency_installer.rb:99:in `find_gems_with_sources'
	from /usr/lib/ruby/1.8/rubygems/dependency_installer.rb:192:in `find_spec_by_name_and_version'
	from /usr/lib/ruby/1.8/rubygems/dependency_installer.rb:213:in `install'
	from /usr/lib/ruby/1.8/rubygems/commands/install_command.rb:118:in `execute'
	from /usr/lib/ruby/1.8/rubygems/commands/install_command.rb:115:in `each'
	from /usr/lib/ruby/1.8/rubygems/commands/install_command.rb:115:in `execute'
	from /usr/lib/ruby/1.8/rubygems/command.rb:257:in `invoke'
	from /usr/lib/ruby/1.8/rubygems/command_manager.rb:132:in `process_args'
	from /usr/lib/ruby/1.8/rubygems/command_manager.rb:102:in `run'
	from /usr/lib/ruby/1.

**Comment by envygeeks** [comment]
We do not support Ruby 1.8, please update to 1.9.3+ if using stable and 2.0.0+ on beta.
