### ISSUE TITLE
array_to_sentence_string needs overload for coma seperator and "and"

### ISSUE THREAD

**Issue by dengere** [jekyll/jekyll#3967]
coma seperator and "and"  its nice for English but not comfortable for my language.
it should be seperator parameter, and also "and" if necessary.

**Comment by envygeeks** [comment]
Please provide examples of what it would be like in your native language, we cannot make implementations around nothing and to do so might be a quirky attempt.  Thanks!

**Comment by dengere** [comment]
i suppose like that
array_to_sentence_string(["madrid","milano","istanbul"], **"|"**)
it will produce
**madrid | milano | istanbul**

array_to_sentence_string(["madrid","milano","istanbul"], **","**, "ve")
it will produce
**madrid , milano ve istanbul**

**Comment by envygeeks** [comment]
What is your native language?

**Comment by dengere** [comment]
Turkish

**Comment by parkr** [comment]
This is outside the scope of Jekyll at this time. Consider using the "join" filter and the "last" filter to achieve your desired putput for now.

**Comment by parkr** [comment]
i18n support will come a bit later.

**Comment by dengere** [comment]
nice news :+1:  thanks.

**Comment by envygeeks** [comment]
Closing this so it's not dangling.
