### ISSUE TITLE
UTF-8 and ASCII-8BIT issue

### ISSUE THREAD

**Issue by jpcaruana** [jekyll/jekyll#3969]
Hi,

until today, I was using the `jekyll` gem but I wanted to try the new `jekyll-feed` gem, so I followed the doc and installed `github-pages` gem. It downloaded the whole internet and now jekyll build doesn't work anymore:

````bash
$ jekyll build
Configuration file: /home/jp/src/perso/barreverte.github.io/_config.yml
            Source: /home/jp/src/perso/barreverte.github.io
       Destination: /home/jp/src/perso/barreverte.github.io/_site
      Generating... 
  Liquid Exception: incompatible character encodings: UTF-8 and ASCII-8BIT in _posts/2012-08-27-binomer-avec-un-clavier-dvorak-et-un-clavier-azerty.markdown
jekyll 2.4.0 | Error:  incompatible character encodings: UTF-8 and ASCII-8BIT
````

But this post is online since 2012 (see http://www.barreverte.fr/binomer-avec-un-clavier-dvorak-et-un-clavier-azerty/ and its source: https://github.com/barreverte/barreverte.github.io/blob/master/_posts/2012-08-27-binomer-avec-un-clavier-dvorak-et-un-clavier-azerty.markdown)

I removed this post, just to test, and another one post failed for the same reason.

I removed the  following from my config but build is still broken for the same reason 

````yaml
gems:
  - jekyll-feed
````

Is is a jekyll issue ?
Is it something I am doing wrong ? Why is my website well build on github pages and not locally ?

````bash
gem list jekyll

*** LOCAL GEMS ***

jekyll (2.4.0)
jekyll-coffeescript (1.0.1)
jekyll-feed (0.3.1)
jekyll-gist (1.3.4)
jekyll-mentions (0.2.1)
jekyll-paginate (1.1.0)
jekyll-redirect-from (0.8.0)
jekyll-sass-converter (1.3.0)
jekyll-sitemap (0.8.1)
jekyll-watch (1.2.1)
````

Thanks for your help

**Comment by jpcaruana** [comment]
````bash
$ file -i _posts/2012-08-27-binomer-avec-un-clavier-dvorak-et-un-clavier-azerty.markdown
_posts/2012-08-27-binomer-avec-un-clavier-dvorak-et-un-clavier-azerty.markdown: text/html; charset=utf-8
````

**Comment by jpcaruana** [comment]
````
$ github-pages versions
+-----------------------+---------+
| Gem                   | Version |
+-----------------------+---------+
| jekyll                | 2.4.0   |
| jekyll-coffeescript   | 1.0.1   |
| jekyll-sass-converter | 1.3.0   |
| kramdown              | 1.5.0   |
| maruku                | 0.7.0   |
| rdiscount             | 2.1.7   |
| redcarpet             | 3.3.2   |
| RedCloth              | 4.2.9   |
| liquid                | 2.6.2   |
| pygments.rb           | 0.6.3   |
| jemoji                | 0.5.0   |
| jekyll-mentions       | 0.2.1   |
| jekyll-redirect-from  | 0.8.0   |
| jekyll-sitemap        | 0.8.1   |
| jekyll-feed           | 0.3.1   |
+-----------------------+---------+
````

**Comment by parkr** [comment]
Try adding `encoding: utf-8` to your _config.yml file

**Comment by jpcaruana** [comment]
it didn't work any better :(

````bash
$ git diff
diff --git i/_config.yml w/_config.yml
index 3c9c008..7f2fe7a 100644
--- i/_config.yml
+++ w/_config.yml
@@ -29,6 +29,8 @@ comments: true
 permalink: /:title
 paginate: 9
 
+encoding: utf-8
+
 gems:
   - jekyll-feed
````

error: 

````
jekyll 2.4.0 | Error:  incompatible character encodings: UTF-8 and ASCII-8BIT
````

**Comment by envygeeks** [comment]
does jekyll-feed cause this through Jekyll or is there something I didn't catch?  What I'm asking is, was jekyll-feed the only addition and did it happen right after that?

**Comment by jpcaruana** [comment]
I don't think the jekyll-feed isn't the issue: I tested it without the plugin and got the same error. 

I changed my gems by installing github-gem. Then site generation began to fail. I don't know if my answer is clear or not.

**Comment by jpcaruana** [comment]
it didn't work any better :(

````bash
$ git diff
diff --git i/_config.yml w/_config.yml
index 3c9c008..7f2fe7a 100644
--- i/_config.yml
+++ w/_config.yml
@@ -29,6 +29,8 @@ comments: true
 permalink: /:title
 paginate: 9
 
+encoding: utf-8
+
 gems:
   - jekyll-feed
````

error: 

````
jekyll 2.4.0 | Error:  incompatible character encodings: UTF-8 and ASCII-8BIT
````

**Comment by arturhoo** [comment]
I'm facing the same issues. When github announced support for jekyll-feed I installed it on my machine and it worked for some time. When I tried to build my blog this morning I started getting those errors on posts written years ago. So far, I've been unable to find the causes of this issue.

Removing the gem or adding the `enconding: utf-8` didn't work.

**Comment by envygeeks** [comment]
Please file your issue with `jekyll-feed` at https://github.com/jekyll/jekyll-feed
/cc @benbalter

**Comment by arturhoo** [comment]
I reinstalled ruby, and then installed only jekyll, removing the `gems` lines from my `_config.yml`. The problem persists:

```
Generating...
  Liquid Exception: invalid byte sequence in UTF-8 in _layouts/post.html
/Users/artur/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/standardfilters.rb:68:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
```

I'm on OSX 10.10.5, and I've recently upgraded to XCode 7. I was **unable** to reproduce the error on a fresh Ubuntu 14.04 with Ruby 2.2.3, so this could be OSX related, although @jpcaruana doesn't seem to be running it.

The issue probably isn't on `jekyll-feed`

**Comment by envygeeks** [comment]
Then why did you mention `jekyll-feed` at all?  Please file a unique ticket with more information, like the contents of the file (or a repo), how to reproduce it reliably and then we can test it and track it down.

**Comment by arturhoo** [comment]
I mentioned it because I thought it was relevant, investigated a bit more and rectified what I said previously. This is how a community constructively solve an issue. Will open a new issue, thanks!

**Comment by jpcaruana** [comment]
I had the issue under linux ubuntu.
@envygeeks I gave some info in the issue, my repo is public, I gave the gem versions.

**Comment by jpcaruana** [comment]
see travis build that shows the issue: https://travis-ci.org/barreverte/barreverte.github.io/

**Comment by parkr** [comment]
@jpcaruana Wow, you write a lot! So great to see. I tried running this on Jekyll 3 beta8 and it worked fine for me. Sometimes all it takes is deleting the original file and re-creating an identical one. The encoding information could have been written improperly by your OS. If that doesn't work, try doing the same process in the web editor on GitHub.com and seeing if that works for you.

**Comment by jpcaruana** [comment]
Hi @parkr,

I created a travis build to show that current jekyll fails on fresh checkout, fresh OS, since travis servers are not mine.

Good te know this is working on Jekyll 3 beta8: can't wait fot it to be released (or the bugfix back ported)

**Comment by jpcaruana** [comment]
I also tried with [jekyll/docker](https://github.com/jekyll/docker) and it also fails:

````bash
$ docker run --rm --volume=$(pwd):/srv/jekyll -it -p 127.0.0.1:4000:4000 jekyll/jekyll jekyll serve --drafts --watch
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
      Generating... 
  Liquid Exception: incompatible character encodings: UTF-8 and ASCII-8BIT in _posts/2012-08-27-binomer-avec-un-clavier-dvorak-et-un-clavier-azerty.markdown
jekyll 2.5.3 | Error:  incompatible character encodings: UTF-8 and ASCII-8BIT
ok: down: /etc/startup3.d/nginx: 0s, normally up
````

**Comment by parkr** [comment]
@jpcaruana I think the problem can be solved without any added work on our side, and very little work on your side: remove the file, copy the contents into a new file of the same name, save and commit.

**Comment by jpcaruana** [comment]
hi @parkr, this solution (copy the contents into a new file of the same name, save and commit) too doesn't work.

i even tried to give the new file a different name (.markdown became .md)

**Comment by envygeeks** [comment]
I think this is part of the larger issue where we agreed to start doing some encoding a while back.  I can't remember the ticket but there was a consensus on starting to do some normalizing (it was mostly for Windows) but these types of issues would be resolved by that.

**Comment by parkr** [comment]
Try adding `encoding: utf-8` to your config file: https://github.com/barreverte/barreverte.github.io/blob/master/_config.yml

**Comment by jpcaruana** [comment]
I removed (in a test branch) the non working posts:

- _posts/2012-08-27-binomer-avec-un-clavier-dvorak-et-un-clavier-azerty.md
- _posts/2014-04-22-creer-un-chroot-part-2-se-connecter.markdown

and I could complete the build. I will investiqate on these files to see what is different about these ones

**Comment by jpcaruana** [comment]
@parkr it also fails with the `encoding: utf-8` parameter (I now remember I already tried it before)

**Comment by jpcaruana** [comment]
same (closed) issue: #2523

**Comment by jpcaruana** [comment]
@envygeeks this one ? #2029

**Comment by jpcaruana** [comment]
I replaced the `gist` commands in these files (but a lot remain in other posts) and the site builds:

- in my local jekyll
- in my docker jekyll
- on travis-ci: https://travis-ci.org/barreverte/barreverte.github.io/builds/85153335

see commit https://github.com/barreverte/barreverte.github.io/commit/3eda1563590cad50c0560cf68dff5952384cb9a5

**Comment by parkr** [comment]
INTERESTING! So next time I'll ask you to run with `--trace` haha. Good catch. Move this to jekyll-gist?

**Comment by jpcaruana** [comment]
issue "moved" to jekyll-gist: https://github.com/jekyll/jekyll-gist/issues/22
