### ISSUE TITLE
Rouge version issue

### ISSUE THREAD

**Issue by SteveEdson** [jekyll/jekyll#3970]
I've started getting the following issue:

```
Generating... 
Please install Rouge 1.3.0 or greater and try running Jekyll again.
```

However, this dependency should be met:

```
....
Installing rouge 1.10.1
Installing titleize 1.3.0
Using bundler 1.9.5
Bundle complete! 10 Gemfile dependencies, 49 gems now installed.
```

`jekyll --version` is 2.5.3.

Thanks.

**Comment by parkr** [comment]
If you downgrade to Rouge 1.9, does it fix the issue?

**Comment by parkr** [comment]
[Relevant code](https://github.com/jekyll/jekyll/blob/407fc82b2d822ace149dfaf6ee74991163a9e2b6/lib/jekyll/converters/markdown/redcarpet_parser.rb#L79-L81)

**Comment by SteveEdson** [comment]
Just checked and yes it does fix things.

**Comment by parkr** [comment]
Then it's a problem with our version comparison. Sorry about htat.

**Comment by envygeeks** [comment]
That's Ruby precision for you.

**Comment by parkr** [comment]
Thanks, @envygeeks!
