### ISSUE TITLE
Installation issue.

### ISSUE THREAD

**Issue by YixuanFranco** [jekyll/jekyll#3971]
Hi,

I was trying to install jeyll, but after I enter `gem install jekyll` I got this:
> ERROR:  Could not find a valid gem 'jekyll' (>= 0), here is why:
> Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/latest_specs.4.8.gz)

Could you please help me to solve this problem?

**Comment by parkr** [comment]
Try #1409, or try upgrading RubyGems. This isn't an issue with Jekyll. Check [Jekyll Talk](https://talk.jekyllrb.com), too!

**Comment by ls2uper** [comment]
中国人吧，国内rubygems.org被屏蔽了，更换镜像地址吧 详细信息查看ruby.taobao.org
淘宝的镜像……以后所有指向rubygems的地址全换成淘宝的就好了

2015年9月12日星期六，Yixuan Li <notifications@github.com> 写道：

> Hi,
>
> I was trying to install jeyll, but after I enter gem install jekyll I got
> this:
>
> ERROR: Could not find a valid gem 'jekyll' (>= 0), here is why:
> Unable to download data from https://rubygems.org/ - Errno::ECONNRESET:
> Connection reset by peer - SSL_connect (
> https://rubygems.org/latest_specs.4.8.gz)
>
> Could you please help me to solve this problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekyll/jekyll/issues/3971>.
>


-- 
发自移动版 Gmail

**Comment by YixuanFranco** [comment]
Problem solved! Awesome! Thx dudes!
@parkr 
@ls2uper
