### ISSUE TITLE
Allow sass-converter to be optional

### ISSUE THREAD

**Issue by iamcarrico** [jekyll/jekyll#3973]
I am running into an odd case. I want to have a different version of Sass (in this case LibSass) to compile all my Sass files. Since I am running that through Node JS, everything is hunky-dory. Until I want to add in some `scss-lint` magic. 

`jekyll-sass-converter` relies on Sass 3.2, which is incompatible with newer versions of `scss-lint`. A newer version of `scss-lint` is needed, to be able to output in JSON to be viewed by Node JS tools. 

That is a long round-about way to say, is it possible to remove the direct runtime dependency of `jekyll-sass-converter`, and only need it if users want their Sass to be converted within Jekyll?

It will make Pikachu happy too! 

![Pikachu just wants more linting to occur](https://31.media.tumblr.com/0c84c987661a1ccdf0152068590ec558/tumblr_mv9dly95NG1rrw07go1_500.gif)

**Comment by mediadoneright** [comment]
please

**Comment by parkr** [comment]
This is a pretty frankenstein collision of tools. What if we updated Sass?

**Comment by iamcarrico** [comment]
I think updating Sass is a much better idea than not updating Sass— but this problem may be run into again moving forward. 

But I fully :+1: just updating Sass for now— a good solution for the problem at hand. 

![image](https://cloud.githubusercontent.com/assets/1394978/10050422/3d85e56a-61ea-11e5-8ba8-8bbcc7cd13a5.png)

**Comment by mediadoneright** [comment]
I feel like I'm missing something.  Aren't these two related?  https://github.com/jekyll/jekyll-sass-converter/issues/12#issuecomment-142646162

**Comment by envygeeks** [comment]
I don't know what source maps has to do with linting?

**Comment by parkr** [comment]
> I feel like I'm missing something. Aren't these two related? jekyll/jekyll-sass-converter#12 (comment)

Sourcemaps are supported by the version of sass we're using, so nope I think it's separate.

**Comment by mediadoneright** [comment]
The version of SASS supported by Jekyll.  If Jekyll supported the current version of SASS it'd fix sourcemaps.... and possibly linting, though I'm afraid [front matter in scss is causing grief with scss-lint task](https://github.com/jekyll/jekyll/issues/3408#issuecomment-74325182) would still be an issue.

As I was typing, @parkr mentioned the version of sass Jekyll is using... I guess that's whats not clear to me... what version is being proposed?

**Comment by iamcarrico** [comment]
Might as well update it to the most recent minor version (3.4)— Which would include the version that source maps were enabled (3.3). 

Front matter would create issues with scss-lint— although I think that is a separate issue entirely, one that will take a bit more careful consideration on how Sass/Jekyll should work together in the future.

**Comment by parkr** [comment]
I was under the impression that sourcemaps were in Sass 3.2... The problem with those is in the way the Jekyll Converter class is used.

**Comment by iamcarrico** [comment]
Well, I will take lead from you @parkr — if you want me to open a PR to just update Sass— I can do that. If we want to discuss the longer-term looking-at-how-Sass-and-Jekyll-work-together— I am fine with that. If we want to just `¯\_(ツ)_/¯` for now, I am okay with that too. Or door number `D`, whatever you feel is appropriate—

**Comment by parkr** [comment]
> if you want me to open a PR to just update Sass— I can do that.

Yes, please!

**Comment by iamcarrico** [comment]
:+1: I will get that in today— and try and test it with Jekyll proper as well. 

Closing this issue, as the problem at hand will be solved with that PR.
