### ISSUE TITLE
page.dir sometimes contains a trailing /

### ISSUE THREAD

**Issue by davidchisnall** [jekyll/jekyll#3974]
Updating Jekyll has broken some sites that I manage because the `dir` property on `site.pages` now sometimes contains a trailing slash.  This is not consistent, so string comparisons of the property don't work, and as Liquid does not have a standard filter for stripping a trailing slash it is cumbersome to work around.

**Comment by parkr** [comment]
Which version of Jekyll?

**Comment by davidchisnall** [comment]
jekyll 3.0.0.pre.beta8 (which was installed by default as a dependency for `gem install jekyll-scholar`)

**Comment by parkr** [comment]
That is only one version. Please provide two – where you came from and where you are now.

Also, `page` could be a `Page`, `Post`, `Document` (collection doc), or `Draft`. Which of these does it seem to be an issue on?

**Comment by davidchisnall** [comment]
I believe the previous version was jekyll-2.5.3.  I also apparently had jekyll-1.4.3 installed, but I'm not sure it worked there.  The `page`s are mostly `Page`s and a few are `Documents`.

**Comment by abeMedia** [comment]
I've just updated to Jekyll 3.0 and the same error has effectively broken my site. I was using the page.dir variable to display a sub-pages using the following:
```{% assign pages = (site.pages | where: 'dir', page.dir) %}```

Since the update page.dir contains a trailing slash for all index pages (index.md & index.html) but not the others, meaning none of my sub-pages are being displayed on any category...

**Comment by envygeeks** [comment]
Hey @abeMedia can you provide a working example I can pull and play with and we'll get this patched for 3.0.1.

**Comment by abeMedia** [comment]
There you go: https://github.com/abeMedia/foobar
In Jekyll 2.5 it works as expected but in Jekyll 3.0 the behaviour is odd:
For the root folder everything works fine and the pages foo and bar are displayed, if you check out the sub-folder /foobar though you will see the dir of the index has no trailing slash while the others do; e.g. browsing to /foobar/foo.html will display the link to /foobar/bar.html but not to the index file.

**Comment by abeMedia** [comment]
You can test out the expected behaviour on http://abemedia.github.io/foobar

**Comment by parkr** [comment]
@abeMedia: this is because of the `dir` method:

```diff
~/jekyll/jekyll#master$ git diff
diff --git a/lib/jekyll/page.rb b/lib/jekyll/page.rb
index eda87f1..890a714 100644
--- a/lib/jekyll/page.rb
+++ b/lib/jekyll/page.rb
@@ -55,7 +55,7 @@ module Jekyll
     #
     # Returns the String destination directory.
     def dir
-      url[-1, 1] == '/' ? url : File.dirname(url)
+      url[-1, 1] == '/' ? url : File.dirname(url) + '/'
     end

     # The full path and filename of the post. Defined in the YAML of the post
```

:point_up: That change fixes it.
