### ISSUE TITLE
newly installed Jekyll broken, without dependency.

### ISSUE THREAD

**Issue by ZhuFengdaaa** [jekyll/jekyll#3975]
I tried 
    ```sudo apt-get install ruby ruby-dev make gcc nodejs```
   ``` sudo gem install jekyll```
Then I typed the command with
   ``` jekyll -v```

And Here is the ERROR message

    /usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find jekyll (>= 0) amongst [actionmailer-4.0.13, actionpack-4.0.13, activemodel-4.0.13, activerecord-4.0.13, activerecord-deprecated_finders-1.0.4, activesupport-4.0.13, arel-4.0.2, arel-helpers-2.1.0, aruba-0.6.2, bcrypt-3.1.10, builder-3.1.4, bundler-1.10.6, capybara-2.4.4, childprocess-0.5.5, coderay-1.1.0, cucumber-1.3.19, cucumber-rails-1.4.2, diff-lcs-1.2.5, docile-1.1.5, erubis-2.7.0, factory_girl-4.5.0, factory_girl_rails-4.5.0, ffi-1.9.8, fivemat-1.2.1, gem-wrappers-1.2.7, gherkin-2.12.2, hike-1.2.3, i18n-0.7.0, jsobfu-0.2.1, json-1.8.3, mail-2.6.3, metasploit-concern-1.0.0, metasploit-credential-1.0.0, metasploit-model-1.0.0, metasploit-payloads-1.0.12, metasploit_data_models-1.2.5, method_source-0.8.2, mime-types-2.6.1, mini_portile-0.6.2, msgpack-0.6.2, multi_json-1.11.1, multi_test-0.1.2, network_interface-0.0.1, nokogiri-1.6.6.2, packetfu-1.1.11, pcaprub-0.12.0, pg-0.18.2, pg_array_parser-0.0.9, postgres_ext-2.4.1, pry-0.10.1, rack-1.5.5, rack-test-0.6.3, rails-4.0.13, railties-4.0.13, rake-10.4.2, rb-readline-r7-0.5.2.0, recog-2.0.6, redcarpet-3.2.3, rkelly-remix-0.0.6, robots-0.10.1, rspec-2.99.0, rspec-collection_matchers-1.1.2, rspec-core-2.99.2, rspec-expectations-2.99.2, rspec-mocks-2.99.3, rspec-rails-2.99.0, rubyntlm-0.5.1, rubyzip-1.1.7, rvm-1.11.3.9, shoulda-matchers-2.8.0, simplecov-0.9.2, simplecov-html-0.9.0, slop-3.6.0, sprockets-2.12.3, sprockets-rails-2.2.4, sqlite3-1.3.10, thor-0.19.1, thread_safe-0.3.5, tilt-1.4.1, timecop-0.7.3, tzinfo-0.3.44, xpath-2.0.0, yard-0.8.7.6] (Gem::LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
	from /usr/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
	from /usr/local/bin/jekyll:22:in `<main>'

I tried to use the `gem install` to install the packages, but the message like below:
   ```ERROR:  Could not find a valid gem 'arel-4.0.2,' (>= 0) in any repository```

my OS version is Ubuntu 14.04 and my ruby version is `ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]`

**Comment by envygeeks** [comment]
We don't use arel or activerecord (arel is what activerecord uses,) this is a problem that is unrelated to jekyll and more than likely due to something that broke an install of a previous gem.  Clear your gems manually and try again please.  `sudo rm -rf /usr/lib/ruby/gems/*/cache/* /usr/local/lib/ruby/gems/*/cache/* && sudo gem install jekyll`

**Comment by envygeeks** [comment]
Sorry I forgot to do: `sudo gem uninstall $(gem list | awk '{ print $1 }'` too.

**Comment by ZhuFengdaaa** [comment]
I'll try it later, thanks for you time~

**Comment by ZhuFengdaaa** [comment]
I succeeded, thank you so much !
