### ISSUE TITLE
Jekyll --pre no changes Jekyll version

### ISSUE THREAD

**Issue by ymatuhin** [jekyll/jekyll#3977]
```
gem install jekyll --pre
Successfully installed jekyll-3.0.0.pre.beta8
Parsing documentation for jekyll-3.0.0.pre.beta8
Done installing documentation for jekyll after 1 seconds
1 gem installed

jekyll -v
jekyll 2.5.3
```

**Comment by envygeeks** [comment]
I'm sorry to do this to you but this is not a Jekyll bug so please ask your question at https://talk.jekyllrb.com so it can benefit the wider community.

**Comment by envygeeks** [comment]
To add a few hints, if you use rbenv then do `rbenv rehash` if it's RVM then please file a ticket at https://github.com/rvm/rvm
