### ISSUE TITLE
Permalink definition

### ISSUE THREAD

**Issue by Fastidious** [jekyll/jekyll#3978]
I am looking to have a custom permalink in the form of:

`http://example.com/20050916065604/`

for example. Is that possible? If not, could it be implemented, so there is more "creativity" possible when generating permalinks? Thanks!

**Comment by envygeeks** [comment]
Please see: https://jekyllrb.com/docs/permalinks -- our algorithm does not require / AFAIW and if it does that should be considered a bug.

**Comment by Fastidious** [comment]
@envygeeks I was not referring to the trading slash, you can safely disregard it.

Right now, on _config.xml we can specify certain default [permalink styles](https://jekyllrb.com/docs/permalinks/#built-in-permalink-styles). What I am asking is to have the ability to expand that, so we can use timestamps, for example. If I write an entry on September 16, at 08:24:30, I would like the permalink to be:

`/20150916082430`

Without having to manually enter it on each entry front matter.

**Comment by envygeeks** [comment]
At this time you cannot use time stamps.

**Comment by parkr** [comment]
Unfortunately, all we have is the date, not the time. If you title your posts with the time, you can do `permalink: /:month:day:year:title`.

**Comment by envygeeks** [comment]
It wouldn't be too hard to add it (actually this might be the easiest feature request we've had in a while IMO) but I wonder how many people would try it and freak out because it alters the URL all the time... in that I wonder how many people refine their post dates that deep.  I know I don't at all.

**Comment by Fastidious** [comment]
> how many people refine their post dates that deep.

I do. On my workflow I could do it (with Atom and Markdown writer), but it is better if it can be set on the configuration. It would certainly add much more flexibility to Jekyll.

@parkr I knew about that one. Short, but still very long URL depending on the title length.

**Comment by envygeeks** [comment]
I honestly don't know how hard this would be but I'm gonna flag it as easy, @parkr can adjust it if he thinks it's gonna be a bit harder.

**Comment by envygeeks** [comment]
Looks like this was left dangling, this is fixed with https://github.com/jekyll/jekyll/pull/3990
