### ISSUE TITLE
jekyll 2.4.0 serve command announces wrong url to user: it's not 0.0.0.0:4000, but localhost:4000

### ISSUE THREAD

**Issue by aspectmkn8rd** [jekyll/jekyll#3980]
when you run

```
jekyll serve --watch
```
it tells you:
```
Server address: http://0.0.0.0:4000/
Server running... press ctrl-c to stop.
```
which is not true and can be very confusing.

what it actually should be is the following:
```
Server address: localhost:4000 (http://127.0.0.1:4000/)
Server running... press ctrl-c to stop.
```

**Comment by kleinfreund** [comment]
I believe this is fixed in the upcoming version. Are you running v2.5.3? Because I have the latest beta and it shows:

```bash
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

**Comment by aspectmkn8rd** [comment]
@kleinfreund ah, ok, seems like it already fixed in newest version. I'm running stable one: 2.4.0 :)

**Comment by envygeeks** [comment]
Actually 2.4.0 is old-stable, 2.5.3 is stable.

**Comment by aspectmkn8rd** [comment]
>>Actually 2.4.0 is old-stable, 2.5.3 is stable.
weird, though I installed it as gem install github-pages, maybe that is the reason :)

**Comment by kleinfreund** [comment]
> weird, though I installed it as gem install github-pages, maybe that is the reason :)

That's because GitHub Pages runs Jekyll v2.4.0: https://pages.github.com/versions/

**Comment by envygeeks** [comment]
Yeah they skipped 2.5 in favor of 3.0 to save time, things should be better soon!
