### ISSUE TITLE
SSL error on Windows when running jekyll serve

### ISSUE THREAD

**Issue by TaylorHuston** [jekyll/jekyll#3985]
Getting the following error when trying to run 'jekyll serve' from the command line on Windows

d:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)

It seems to be the same error as this RubyGems issue 

https://gist.github.com/luislavena/f064211759ee0f806c88

But I have no trouble installing gems, and the workaround in that issue had no effect.

**Comment by envygeeks** [comment]
This ticket probably belongs on Ruby or RubyInstaller because we don't use SSL so any errors you get would be related to their builds and nothing that we can really control.  Can you provide more information than a generic explanation?

**Comment by TaylorHuston** [comment]
It only happens when I try to run 'jekyll serve' from inside a jekyll project though. Everything else Ruby/Rails/Gems related seems to work fine.

**Comment by envygeeks** [comment]
Please provide more information than a generic explanation.

**Comment by TaylorHuston** [comment]
Not sure what other information you are looking for. I navigate to the directory of my Jekyll project, type in 'jekyll serve', press Enter, get that SSL error.

**Comment by envygeeks** [comment]
That's not the full backtrace for first thing, second thing is what are you doing in your Jekyll project? Are you using external gems? Do you get it on another version of Ruby? When did t his error start happening?

**Comment by envygeeks** [comment]
Personally it probably still leans as an upstream bug since I didn't notice anything out of the ordinary in our commands/serve.rb (but I also looked on master.) Can you try to see if this is the same with 3.0.0 (gem install jekyll --pre)

**Comment by TaylorHuston** [comment]
Jekyll project is a simple blog. Not sure when it started happening and I've been hosting it on GitHub Pages just fine, never bothered to run it locally on my Windows box before. I only have the one version of Ruby installed on my Windows box (it was hard enough to get that to work right, Windows and Ruby don't play nice).

Same error after running 'gem install jekyll --pre'

So, I get the same SSL error if I run just the 'jekyll' command from within that directory. But if I run the 'jekyll' command from any other directory, it just gives me the basic 'A subcommand is required' response.

**Comment by TaylorHuston** [comment]
Weird, also getting the same SSL error when running bundle update or bundle install, but only from within that directory. Any other Rails project works fine. Comparing it to a different Rails project. Both reporting the same Ruby version and path, same gem version and path, same bundler version and path, etc. Both Gemfiles using  'https://rubygems.org' s the source. I can 'bundle install', 'bundle update' and 'rails s' from the Rails project fine, but getting the SSL error in the Jekyll project.

Also same project runs fine on my Macbook. Go home Windows you're drunk.

**Comment by envygeeks** [comment]
I don't think this is Windows fault tbh but seems like something is off, try deleting the `.bundle` folder and the vendor folder if you use one and try again?

**Comment by TaylorHuston** [comment]
Commented out these two lines in the Gemfile:

versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages']

And that stopped the SSL error when running 'bundle update'. Manually installed github-pages gem.  Got a completely different 'missing kramdown' error, manually installed kramdown gem. Ran 'gem update' and 'gem cleanup' just to be safe, still got 'missing kramdown' error. Finally tried 'bundle exec jekyll serve', that works fine (still leaving those two lines commented out).

Note having just 
gem 'github-pages'
in the gemfile seems to cause no issues.

Probably just my machine, but mayhaps the documentation on this link doesn't apply to Windows?
http://jekyllrb.com/docs/github-pages/

**Comment by envygeeks** [comment]
That documentation is quirky and crazy, only @parkr can explain why it's there but it certainly doesn't solve any problem, we should actually be telling people to use just `gem "github-pages"` instead of that craziness.

**Comment by TaylorHuston** [comment]
Yeahp working fine only real issue is that I still get the 'missing kramdown' error if I just use 'jekyll serve', have to use 'bundle exec jekyll serve'. No idea why, not sure if it's something you guys want to investigate or note in the documentation anywhere. The normal 'jekyll serve' works fine on the Macbook though. Other than that, can probably close this issue.

**Comment by parkr** [comment]
The documentation is there to ensure the user is using the latest pages gem to exactly match what's being run on their build servers. For some, it will be a pain, so we can add the simpler version as well.

**Comment by ceefour** [comment]
Most likely this: https://github.com/jekyll/jekyll-gist/issues/30

**Comment by BardOfCodes** [comment]
It was solved by installing the following gem: certified.
<code>gem install certified</code>

**Comment by dsherret** [comment]
This was solved for me by using the steps found on [this page](https://github.com/mzlogin/mzlogin.github.io/wiki/Problems-and-solutions-when-run-Jekyll-on-Windows).

> 1. Download https://curl.haxx.se/ca/cacert.pem
2. Add a environment variable SSL_CERT_FILE values /path/to/cacert.pem

**Comment by rajsite** [comment]
@dsherret's response worked for me on Windows 10

**Comment by jakefrn** [comment]
@dsherret  solution worked on win10 for me as well.  I saved it in C:\Windows\cacert.pem
Hit Win + r, enter in sysdm.cpl > Advanced tab > Environment Variables > System Variables : New >  SSL_CERT_FILE and browse to the file
