### ISSUE TITLE
Implement Jekyll in NodeJS?

### ISSUE THREAD

**Issue by macmladen** [jekyll/jekyll#3986]
I know this may start a avalanche of negativity, but world of NodeJS tools is moving very fast and many tools like Sass itself are moving to NodeJS with many workflow suggestions also moving that path.

Is there any plan to release Jekyll as pure JS/node without requirement for Ruby?

P.S I did read about **removing** requirement for Python and NodeJS in roadmap which I also support (less dependencies, less problem)

**Comment by parkr** [comment]
Hey @macmladen,

Rewriting the entire codebase is not something we are planning or interested in doing at this point. If we did that, all existing Ruby plugins would cease working as-is.

If we do rewrite Jekyll, which is plausible for the distant future, it will be in a language that offers excellent cross-platform support, such as Go.

Thanks

**Comment by macmladen** [comment]
I completely understand your point. Taking care of the whole ecosystem makes development a responsible one.

But the question was in light of Sass and Compass transition to libsass on NodeJS as a it supposedly have better reach but also offer greater build speed and greater community (according to Chris Eppstein).

There is some void that needs to be filled like Compass library but there is some serious progress with all tools and libraries although road is still bumpy.

Maybe I am wrong but from some posts that I read, making port to NodeJS may not be too demanding for someone with good JS knowledge and readiness to undertake such task. Of course, there are many other needed components needed to make it work.

But I think it is worth the effort and reach would be substantial.

Also, I really do think that JS with node is quite cross-platform as it already works on three major OS families but there may be some things I am not aware of and concerning Go. From what I have researched some time ago and recently, JS is second only to compiled C/C++ (of course, Go is also compiled).

Thanks for insight.

**Comment by envygeeks** [comment]
libsass is a C library so I don't know what that really has to do with NodeJS.

**Comment by macmladen** [comment]
NodeJS is also written in C but that also has nothing to do with the idea of writing Jekyll in JavaScript.

The reasoning is this:

1. NodeJS is cross platform
2. Javascript is modern object oriented language with fast growing popularity and great community
3. NodeJS enables very fast execution of interpreted code, second only to compiled ones
4. Jekyll could benefit from greater developer community

The idea was only inspired by my amazement that Sass compilation is taking anywhere from 10 to 100 times faster for the same Sass code base.

It is also a puzzle for me how Ruby community of developers embraced **libsass** and incorporated it in **node-sass** and has switched to NodeJS to build ecosystem around node-sass implementation.

So it was just a question, idea because I am also in a process of shifting my workflow from Ruby based tools to NodeJS based tools so I was wondering if Jekyll is evaluating this path.

Apparently not, which is less issue for me personally as Jekyll is not critical for my business (just my interest) but then again I see some potential.

There are at least few clones, [Heckle](https://github.com/marijnh/heckle) being one of them which means that there is interest in such version, to move away from Ruby into Node environment. It is very clear that such version would not benefit from many Ruby gem extenders but it would open the door for new breed that would come from Node world.

I think Sass team showed their openness when they embraced libsass/node and offered it right from the source (not some third party clone). That way they also kept control of the language. New environment proved to be very agile and created whole new set of plugins so that even author of old library with very strong presence **Compass**, Chris Eppstein decided to start development of library in NodeJS [Port to libSass #1916](https://github.com/Compass/compass/issues/1916).

All of this is just side effect of my research on **Sass** and switching my front end development to NodeJS environment. Primarily a Drupal front end developer I find Drupal an overkill for many things and I look with interest and sympathy toward Jekyll which currently powers my poorly executed personal website.

However I am strong proponent of static site generators and see great potential in them, [Jekyll being a leader](https://www.staticgen.com/).

**Comment by parkr** [comment]
Thanks, everyone!
