### ISSUE TITLE
error installing jekyll

### ISSUE THREAD

**Issue by udhayam** [jekyll/jekyll#3993]
Fetching: fast-stemmer-1.0.2.gem (100%)
ERROR:  Error installing jekyll:
        The 'fast-stemmer' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

**Comment by parkr** [comment]
Did you try installing the DevKit?

**Comment by parkr** [comment]
This is a problem with installation, not with Jekyll. Going to close out of our issue tracker. Jekyll Talk ( https://talk.jekyllrb.com ) is a better place for things like this.
