### ISSUE TITLE
Variable to check environment

### ISSUE THREAD

**Issue by cesarjr** [jekyll/jekyll#3995]
Is it possible to have one var that show-me if jekyll was started using ```jekyll server``` or ```jekyll build```.

It would be useful to disable some features while I'm working at development - i.e. google analytics.

**Comment by envygeeks** [comment]
By default `JEKYLL_ENV=development` so if you want to kick off features for production set it to production in the env, then use `site.jekyll.environment` to detect it.

**Comment by parkr** [comment]
That's jekyll.environment, not site.jekyll.environment.

**Comment by jaybe-jekyll** [comment]
There are also site variables which would provide some insight.

Within a page:

`{{ site }}`

... to see current settings, one of which will refer to serving.

**Comment by parkr** [comment]
`site.serving` will be set, yes, thank you @jaybe-jekyll!

**Comment by cesarjr** [comment]
Thank you so much! It works perfectly!
