### ISSUE TITLE
a post may be considered as a future post when no timezone is given

### ISSUE THREAD

**Issue by hartmel** [jekyll/jekyll#3998]
A newly created jekyll tree comes with a "welcome to jekyll" post with a front matter without timezone option : "date:   2015-09-27 13:44:54".
It seems that this date is considered as a future one, since the html file is note built. Adding the timezone to the date fixes it. As this is the default scaffold when creating a new site, this can be a problem for newcomers to not seeing a generated HTML file for the first post.

Maybe a post of the current day should not be considered as a future post whatever the time is or the timezone should be guessed if it s not provided in the front matter.

```shellscript
$ date -R
Sun, 27 Sep 2015 14:41:33 +0200
$ grep -F "date:" _posts/2015-09-27-welcome-to-jekyll.markdown 
date:   2015-09-27 13:44:54
$ jekyll build --full-rebuild > /dev/null 2>&1
$ find . -name "welcome-to-jekyll.html"
$ 
$ grep -F "date:" _posts/2015-09-27-welcome-to-jekyll.markdown 
date:   2015-09-27 13:44:54 +0200
$ jekyll build --full-rebuild > /dev/null 2>&1
$ find . -name "welcome-to-jekyll.html"
./_site/jekyll/update/2015/09/27/welcome-to-jekyll.html
$ 
```

**Comment by parkr** [comment]
Would you submit a PR to add the time zone offset to the generated date? Thanks!

**Comment by hartmel** [comment]
Done (in #4001, didn't found how to PR in this issue)
