### ISSUE TITLE
Liquid tags cause paragraph breaks in wrong places

### ISSUE THREAD

**Issue by reitzig** [jekyll/jekyll#4002]
Consider code like this in `template.md`:

```
[empty line]
{% if page.variable1 %}{{ page.variable1 }}{% endif %}
{% if page.variable2 %}{{ page.variable2 }}{% endif %}
[empty line]
```

We would expect:

```html
<p>value1 value2</p>
```

The space is due to the newline. However, we get:

```html
<p>value1</p>
<p>value2</p>
```

I use kramdown for converting Markdown to HTML, so I assume that the expansion of the Liquid tags inserts spurious newlines.

This is annoying since it makes templates more messy than they have to be.

**Comment by kleinfreund** [comment]
The reason for this is Markdown. If you add a newline, kramdown will treat the two bits as two paragraphs. You should be templating with HTML not Markdown.

**Comment by parkr** [comment]
> I use kramdown for converting Markdown to HTML, so I assume that the expansion of the Liquid tags inserts spurious newlines.

This is not the case – liquid does not add these newlines. It's merely using the newline you have after your first `{% endif %}`. Encase these if's in a `<p>` tag if that's what you desire:

```liquid
<p>
  {% if page.variable1 %}{{ page.variable1 }}{% endif %}
  {% if page.variable2 %}{{ page.variable2 }}{% endif %}
</p>
```

For the record, if the variable doesn't exist, it will just be an empty string (due to NilClass#to_s), so feel free to just do 

```liquid
{{ page.variable1 }} {{ page.variable2 }}
```

**Comment by reitzig** [comment]
I see now that this can not be reproduced with two values. The real issue occurs if you have

```
[empty line]
{% if page.variable1 %}{{ page.variable1 }}{% endif %}
{% if page.variable2 %}{{ page.variable2 }}{% endif %}
{% if page.variable3 %}{{ page.variable3 }}{% endif %}
[empty line]
```

And `variable2` does not exist. This is of course not the fault of Liquid, and can probably not be circumvented.

@parkr Thanks for the suggestions. However, enclosing in `<p>` is not so nice because then Markdown inside will not be compiled. Then `if` tags are needed because I print more than just the values.

**Comment by envygeeks** [comment]
Yeah that's a gotcha between Markdown and Liquid, where one keeps the blank line and the other is happy to accept it and move along because that's what it was designed to do.  I don't think there is anything that can really be done about that because lets be honest, if they did, Liquid would suffer horribly from that.

**Comment by reitzig** [comment]
@envygeeks Can you nest Liquid tags? If so, one could write a "remove linebreaks" tag (or environment, like `{% for... %} ... {% endfor %}`?) and wrap sensitive passages.

**Comment by reitzig** [comment]
I can answer my own question. This works as intended:

```ruby
module Jekyll
  class NoLinebreaksBlock < Liquid::Block
  
    def initialize(tag_name, text, tokens)
       super
    end

    def render(context)
      super.gsub(/\s+/, " ")
    end
  end
end

Liquid::Template.register_tag('nolinebreaks', Jekyll::NoLinebreaksBlock)
```

This may be of general interest since it allows to write Liquid tags in a more clear/programming-ish way, e.g.

```
{% nolinebreaks %}
  {% if page.variable1 %}
    val1: {{ page.variable1 }};
  {% endif %}

  {% if page.variable2 %}
    val2: {{ page.variable2 }};
  {% endif %}

  {% if page.variable3 %}
    val3: {{ page.variable3 }};
  {% endif %}
{% endnolinebreaks %}
```

will output everything in one line.

(Would we want a way to force linebreaks then, e.g. by escaped `\\n` or something?)
