### ISSUE TITLE
Jekyll Serve and Bundle Exec Jekyll Serve Return "Not Found"

### ISSUE THREAD

**Issue by cooperpellaton** [jekyll/jekyll#4007]
I've tried running both `jekyll serve` and `bundle exec jekyll serve` on Mac OS X 10.11 only to then navigate to my local host at port 4000 and see the following returned:
>Not Found
>`/cooperpellaton.github.io/' not found.
>WEBrick/1.3.1 (Ruby/2.0.0/2015-04-13) at 127.0.0.1:4000

The following is what was returned from the CLI when running just jekyll serve. 

>x-vl950-72-19-86-177:cooperpellaton.github.io cooperpellaton$ jekyll serve
>Configuration file: /Users/cooperpellaton/Documents/Projects/cooperpellaton.github.io/_config.yml
>/Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:34:in `block in setup': You have >already activated kramdown 1.9.0, but your Gemfile requires kramdown 1.8.0. Prepending `bundle >exec` to your command may solve this. (Gem::LoadError)
>	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:19:in `setup'
>	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
>	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/setup.rb:8:in `<top (required)>'
>	from /Library/Ruby/Gems/2.0.0/gems/algoliasearch-jekyll-0.4.3/lib/algoliasearch-jekyll.rb:2:i>n >`require'
>	from /Library/Ruby/Gems/2.0.0/gems/algoliasearch-jekyll-0.4.3/lib/algoliasearch-jekyll.rb:2:in >`<top (required)>'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in >require_gems'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in >`conscientious_require'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 >levels) in init_with_program'
>	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
>	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in >execute'
>	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
>	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in >`execute'
>	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
>	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
>	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
>	from /usr/local/bin/jekyll:23:in `load'
>	from /usr/local/bin/jekyll:23:in `<main>' 

I then ran `bundle exec jekyll serve` and got the following:
>1x-vl950-72-19-86-177:cooperpellaton.github.io cooperpellaton$ bundle exec jekyll serve
>Configuration file: /Users/cooperpellaton/Documents/Projects/cooperpellaton.github.io/_config.yml
>            Source: /Users/cooperpellaton/Documents/Projects/cooperpellaton.github.io
>       Destination: /Users/cooperpellaton/Documents/Projects/cooperpellaton.github.io/_site
>      Generating...
>                    done.
> Auto-regeneration: enabled for '/Users/cooperpellaton/Documents/Projects/cooperpellaton.github.io'
>Configuration file: /Users/cooperpellaton/Documents/Projects/cooperpellaton.github.io/_config.yml
>    Server address: http://127.0.0.1:4000//cooperpellaton.github.io/
>  Server running... press ctrl-c to stop.

Only to then see "not found" again.
<img width="1394" alt="screenshot 2015-10-03 20 51 22" src="https://cloud.githubusercontent.com/assets/5178017/10265897/9010731c-6a10-11e5-9bda-fbcd855b1109.png">

Just in case, I'm posting a screenshot of the Gemfile.lock as well.
![screenshot 2015-10-03 20 56 04](https://cloud.githubusercontent.com/assets/5178017/10265906/32c75012-6a11-11e5-8a11-8f66bdd7cc45.png)

I'm not sure what's happening here, and would appreciate any support.

**Comment by parkr** [comment]
What is your baseurl? In your config. Just go to 127.0.0.1:4000. Seems like a problem with baseurl usage. See https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/ for more.

**Comment by cooperpellaton** [comment]
The base url is "//cooperpellaton.github.io". I've tried just navigating to 127.0.0.1:4000 only to get the same error. 
<img width="1351" alt="screenshot 2015-10-04 20 45 49" src="https://cloud.githubusercontent.com/assets/5178017/10271282/e9bca0f2-6ad8-11e5-94ad-a5c6b11e0642.png">

**Comment by i-give-up** [comment]
Seems like baseurl doesn't work when it starts with 2 backslashes, "/cooperpellaton.github.io" would work.

*But*, you are misunderstanding what baseurl is. You should read the link that parkr posted.

**Comment by cooperpellaton** [comment]
You are correct in saying that the use of a single slash does work, so "/cooperpellaton.github.io" will properly serve the site. The issue is that in production if you serve the _config.yml with the baseurl only containing 1 slash then no CSS is served. I've read the article, is there something *I* am misunderstanding?

_config.yml served with baseurl "/cooperpellaton.github.io"
<img width="1351" alt="screenshot 2015-10-04 23 20 18" src="https://cloud.githubusercontent.com/assets/5178017/10272504/7cdaa518-6aee-11e5-984d-50f8fc7cf746.png">

_config.yml served with baseurl "//cooperpellaton.github.io"
<img width="1351" alt="screenshot 2015-10-04 23 21 45" src="https://cloud.githubusercontent.com/assets/5178017/10272519/bbe83810-6aee-11e5-8760-ae07d36564b5.png">

**Comment by parkr** [comment]
See how the CSS URL is constructed. It is likely the issue here, where a slash is forgotten.

You should be all set!

**Comment by pathawks** [comment]
If you set baseurl to an empty string, it will work in both settings.

**Comment by parkr** [comment]
Use `bundle exec jekyll serve --baseurl ''`

**Comment by cooperpellaton** [comment]
@pathawks Yes, in the end that is the solution that works best.
