### ISSUE TITLE
Unresolved specs during Gem::Specification.reset

### ISSUE THREAD

**Issue by boyriot** [jekyll/jekyll#4009]
I'm using windows 10, I got these errors when I tried to run jekyll 

$ jekyll serve -w
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      listen (~> 2.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: c:/Users/Heisenberg/documents/github/minimal-mistakes/_config.yml
c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-sitemap (LoadError)
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:79:in `setup'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:41:in `initialize'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `new'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:29:in `process'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from c:/Ruby21/bin/jekyll:23:in `load'
        from c:/Ruby21/bin/jekyll:23:in `<main>'

**Comment by Birate** [comment]
+ 1

**Comment by parkr** [comment]
You don't have Jekyll-sitemap installed. Install all plugins you're using and you'll be fine.
