### ISSUE TITLE
Styles not showing on site. Github pages

### ISSUE THREAD

**Issue by TreBey** [jekyll/jekyll#4016]
Hi, 
I am working on a blog sitre and for some reason, I can't figure out why my styles are not showing live on the web. My domain is iambey.com, and I am using github pages in order to host my website.I think the problem has to do with the config.yml file, but I am not really sure what to change, because I am still pretty new to the way jekyll works, and this is my very first site. 

If I could get some feedback or guidance on this issue, that would be great. The repository that this site is stored on is under my repositories: TreBey.github.io.

Thanks.

**Comment by envygeeks** [comment]
I hate to do this to you but this is a medium for bugs only, please repost your question on https://talk.jekyllrb.com where the community will gladly try to help you (including some of us maintainers who chime in!)

**Comment by TreBey** [comment]
Thanks for the guidance @envygeeks. Will do
