### ISSUE TITLE
Collections stricter parsing front-matter than posts

### ISSUE THREAD

**Issue by elliz** [jekyll/jekyll#4017]
If you have whitespace after the first --- in the front-matter in collections then they are not parsed by Jekyll.

Use the same markdown files as posts (with the timestamp part of course) they are parsed and rendered correctly.

Note: this also extends to non-collection files such as sitemap.xml etc too ... this may be as-designed but is inconsistent with the behaviour of posts.

**Comment by envygeeks** [comment]
Please provide examples.

**Comment by elliz** [comment]
Should be a demo up at https://elliz.github.io/elliz/jekyll-collection-issue/ shortly ...

**Comment by elliz** [comment]
Issue seems to be on has_yaml_header function at https://github.com/jekyll/jekyll/blob/581dee7ba975e05622548fdfc785631dcff824f3/lib/jekyll/utils.rb#L107-L109

changing regex to `/\A---[\t ]*\r?\n/` might fix it but may create other unintended consequences ... 

I have not looked deeply , but that check may not be called when rendering posts. This may be "as designed"

**Comment by envygeeks** [comment]
@elliz the easiest way to check the consequences is to change it and run the specs :palm_tree:

**Comment by elliz** [comment]
If I was on mac on linux ... not time to set up on win10 and did not work via cygwin ... might try on vm if have time.
