### ISSUE TITLE
A proposal to move jekyll-assets/jekyll-assets to jekyll/assets.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4019]
I would like to merge `jekyll-assets/jekyll-assets` into `jekyll/assets` and make it an official plugin piece for Jekyll (not installed by default) and was wondering what @jekyll/core thinks of this?

At this time I would also like to propose that Github review the source and see if there are any security that needs to be done because I would like to get it included on Github Pages by default.  There are a lot of users who currently use `jekyll-assets` and I think all parties would benefit from both being on `jekyll`'s umbrella and being included on Github Pages.

/cc @benbalter @ixti @zmbush

**Comment by cameronmcefee** [comment]
I'm not a maintainer or a security person so I can't give the final thumbs up to the idea, but I definitely support it. I've wished for this numerous times.

From an implementation standpoint, does this convolute the existing built in sass/coffee setup?

**Comment by parkr** [comment]
I personally am not that interested in maintaining jekyll-assets, but I don't might giving it the Jekyll Seal of Approval and making it easier to do funky asset things.

:+1: @envygeeks, feel free.

**Comment by ixti** [comment]
I'm not opposed to move it under jekyll umbrella (especially considering fact that latest version is 100% maintained by @envygeeks and not me), but don't see lots of profit (unless github pages will support it at some point).

**Comment by envygeeks** [comment]
I'll have @parkr create an assets group so that you can continue to contribute any time you wish -- there will be no lock out or removal of contributors to the project -- that would be unfair. The idea is to get it more exposure -- not that it doesn't already have a lot, and to also to try and get it included in Github Pages because a lot of people ask about that.  Luckily we make a lot of our stuff outside of normal asset digesting and management optional so Github can exclude stuff it needs to.

**Comment by parkr** [comment]
Done. @jekyll/assets is now a group. @ixti, I sent you an invite and you'll both have full admin rights over your repos.

**Comment by parkr** [comment]
:tada:
