### ISSUE TITLE
Variable value set in page, get in layout

### ISSUE THREAD

**Issue by GNUletik** [jekyll/jekyll#4025]
Hi !
I realized that when a variable is set in a rendered file like that : 
```
{% assign my_var = true %}
```
index.html

I can't get the variable in my layout like that
```
{{ my_var }}
```
_layouts/default.html

If you want to test it,
```sh
git clone https://github.com/GNUletik/jekyll-vars-in-layout.git && cd jekyll-vars-in-layout && jekyll server
```
or 

code : https://github.com/GNUletik/jekyll-vars-in-layout
page : http://gnuletik.github.io/jekyll-vars-in-layout/

Is this a bug ?
I'm using it to include some javascript if a variable that I set in an include is set to true.
So I'm thinking about a new feature : Would it be possible to set a variable if a file is included in the page ?
Thanks :)
If you need any information, just ask ! :)

**Comment by envygeeks** [comment]
This is not a bug, this is a consequence of linear processing, we are not Rails and do not have `content_for` therefore anything you process is a linear action.  It's possible sure, whether or not it's a feature or an acceptable feature is negotiable.

**Comment by GNUletik** [comment]
Okay thanks, I understand.
So, I'm asking if it would be possible to set a variable if a file is included in the page ?
like ```page.name_of_include_file.included``` set to true or false.

**Comment by envygeeks** [comment]
Yes, fork the include plugin and edit it to add a variable to the data passed around, but I don't know if that would be available in the layout at all, I don't quite remember how we process layouts and pages other than remembering it's all linear.

**Comment by GNUletik** [comment]
Okay, I will try !
Thanks :)
