### ISSUE TITLE
Using more than one variable in {% include %} is not possible

### ISSUE THREAD

**Issue by omnidan** [jekyll/jekyll#4028]
I tried the following, which did not work:

```
{% include {{page.lang}}/features/{{feature.name}}.md %}
```

However, this works:

```
{% include {{page.lang}}/features/test.md %}
```

And so does this workaround:

```
{% capture filename %}{{page.lang}}/features/{{feature.name}}.md{% endcapture %}
{% include {{filename}} %}
```

**Comment by parkr** [comment]
Code for this is here in case you want to contribute: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/tags/include.rb

**Comment by omnidan** [comment]
@parkr thanks for the answer - although I'm not really a ruby guy so I don't think I can do much there :grin:

**Comment by parkr** [comment]
I wasn't a Ruby guy until I started writing Jekyll sites either! Once I decided I wanted to write a plugin, I said I would learn it. I don't regret that decision one bit!

**Comment by omnidan** [comment]
I don't think I'll have time for it anytime soon, sorry :smile: but at least when someone else runs into this issue, (hopefully) they will find this thread and use the workaround (not get frustrated for a long time like me :sweat_smile:)

**Comment by envygeeks** [comment]
I'm going to take this ticket, this is part of a larger problem with our tags I'm working on for any milestone > 3.0, we should be using Liquid to process the context to parse the variables.

**Comment by envygeeks** [comment]
Shifting this to 3.2 as other things are more important.
