### ISSUE TITLE
If a config file is empty Jekyll stops processing later configs

### ISSUE THREAD

**Issue by sparanoid** [jekyll/jekyll#4030]
For example:

```shell
$ jekyll build --config _config.yml,_config.user.yml,_config.local.yml
```

_config.user.yml:

```yaml
#
# Jekyll user configurations
#

# Define your variables here
```

if `_config.user.yml` is empty, Jekyll will stop processing `_config.local.yml`.

**Comment by parkr** [comment]
I'd probably change the following code in Jekyll to accept `false`: https://github.com/jekyll/jekyll/blob/8add5aec4b8490aa129a01cee4d37c215f6b6dc8/lib/jekyll/configuration.rb#L155-L158

`false` is returned when `SafeYAML.load` gets no content
