### ISSUE TITLE
Default configuration layout being ignored when rendering markdown pages

### ISSUE THREAD

**Issue by ngmaloney** [jekyll/jekyll#4031]
I'm experiencing an issue with a default layout specified in _config.yml being ignored when rendering a markdown file that does not specify a layout via front matter.

Given [the following config & markdown file](https://gist.github.com/ngmaloney/81584abd7714065be800) the page renders without a layout. Should the expected behavior be to render the default layout if one is not specified? If a specify a layout via front matter, it renders as expected.

I threw a debugger in and noticed that in the [Convertible module](https://github.com/jekyll/jekyll/blob/2807b8a012ead8b8fe7ed30f1a8ad1f6f9de7ba4/lib/jekyll/convertible.rb#L211) layout will only be set IF one is specified in the data attribute but I don't see where it cascades down to a default _config layout if there isn't one specified in the data attribute. Am I derping out here or is this a bug? Happy to write a spec + patch but wanted to confirm with a sanity check first.

**Comment by i-give-up** [comment]
`defaults` takes a list of dictionaries, so it should look like this (you are missing a dash in front of `scope`)

    defaults:
      - scope:
          path: ""
        values:
          layout: "default"

**Comment by envygeeks** [comment]
The bug here is why we didn't throw on that misconfiguration and if we didn't then the syntax should be considered valid, is this the case @jekyll/core?

**Comment by ngmaloney** [comment]
@i-give-up Thank you! Don't know how I missed that. 

@envygeeks I can open another ticket and possibly a spec concerning an error on misconfiguration.
