### ISSUE TITLE
jekyll docs fails in 2.5.3

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [jekyll/jekyll#4041]
The online documentation says:

> If you’re interested in browsing these docs on-the-go, install the `jekyll-docs` gem and run `jekyll docs` in your terminal.

However, doing so results in a _file not found error_ ... it seems that jekyll-docs is looking for the generated site to be present in the jekyll gem installation, something that apparently stopped being generated or save with jekyll version 2.5. See [issue #3](https://github.com/jekyll/jekyll-docs/issues/3) in the jekyll-docs project.

This seems like some that a CI test could catch ...

**Comment by envygeeks** [comment]
It should be caught but not by Jekyll, we don't provide that command, it's provided by: https://github.com/jekyll/jekyll-docs can you move this ticket there.

**Comment by envygeeks** [comment]
Sorry, what I mean is (we) `jekyll/jekyll` don't provide that command, it's provided by `jekyll/jekyll-docs`

**Comment by JeNeSuisPasDave** [comment]
OK, well there's already an issue posted there. So I'll close this.
