### ISSUE TITLE
install jekyll on Fedora 22 x86_64 , needed update

### ISSUE THREAD

**Issue by agompel** [jekyll/jekyll#4045]
# on fedora 22 x86_64 , oct18-2015
## "gem install jekyll"  was not enough, header file was(were?) missing, install failed.
---------------  this worked -----------------

    sudo dnf install ruby
    sudo dnf install gcc mysql-devel ruby-devel rubygems
    gem install jekyll

**Comment by parkr** [comment]
Never heard of `dnf` before! Want to add this to http://jekyllrb.com/docs/troubleshooting/#installation-problems?

**Comment by parkr** [comment]
File to edit is here: https://github.com/jekyll/jekyll/blob/master/site/_docs/troubleshooting.md

**Comment by agompel** [comment]
@parkr 
1) sorry I forgot "nodejs" so the procedure below is adequate
2) dnf has replaced yum in fedora 22, the gui is now "yumex-dnf", see there:
    http://fedoramagazine.org/managing-packages-fedora-dnf/

3) May also want to see:
    http://fedoramagazine.org/make-github-pages-blog-with-pelican/

----
# on fedora 22, oct18-2015
## gem install jekylll was not enough, header file was(were?) missing.
-------------------- this worked fine -------------------------
sudo dnf install ruby
sudo dnf install gcc mysql-devel ruby-devel rubygems nodejs
gem install jekyll
