### ISSUE TITLE
site.collections returning different hash on 2.5.3 and 3.0

### ISSUE THREAD

**Issue by matallo** [jekyll/jekyll#4047]
I experienced a different behaviour for the same `{{ site.collections }}` depending on the setup I was using.

With Jekyll `2.5.3` it returned a Hash with collection label as the key and an array of docs.
```
{"cartodbjs"=>#, #]>, "sqlapi"=>#]>}
```
With Jekyll last beta `3.0.0.pre.beta10` it returned a list of hashes
```
{"output"=>true, "title"=>"CartoDB.js", "label"=>"cartodbjs", "docs"=>[#, #], "files"=>[], "directory"=>"/", "relative_directory"=>"_cartodbjs"}{"output"=>true, "title"=>"SQL API", "label"=>"sqlapi", "docs"=>[#], "files"=>[], "directory"=>"/", "relative_directory"=>"_sqlapi"}
```

It would be great to keep with the former behaviour as for example I reuse a layout for different collections. Thus, I can easily render the collection title:

```
{% assign collection = site.collections[page.collection] %}
{{ collection.title }}
```

With the latest versions, I have to iterate through the list of collections:

```
{% assign collection = false %}

{% for collection_item in site.collections %}
  {% if collection_item.label == page.collection %}
    {% assign collection = collection_item %}
  {% endif %}
{% endfor %}
{{ collection.title }}
```

my questions are:

- are there any implications that prevent `{{ site.collections }}` to respond as in the previous versions?
- shouldn't [this test](https://github.com/jekyll/jekyll/blob/master/test/test_collections.rb#L115) specifically cover that? Sorry for my ignorance as I don't excel at Ruby

**Comment by parkr** [comment]
No need for all the looping! Simply do `site[page.collection]`. This should give you the collection you're looking for.

**Comment by matallo** [comment]
still not getting the expected behaviour, with `{{ site[page.collection] }}` it renders the current page content, as wel as the other docs'

if I try to access `{{ site[page.collection].title }}` it is blank

I've been using Jekyll for some time now and in order to know more about the internals, could you elaborate on my questions? I'm a bit lost here

Thanks in advance!

**Comment by parkr** [comment]
@matallo `site[page.collection]` will you give you an `Array` of `Document` objects. See what this does for you:

```liquid
{% for doc in site[page.collection] %}
  {{ doc.title }}
{% endfor %}
```

Should list the titles of all the documents in the page's collection.
