### ISSUE TITLE
Docs: Add page describing build-in plugins

### ISSUE THREAD

**Issue by iBobik** [jekyll/jekyll#4054]
Will be nice to describe mandatory plugins what users can use without installing them.

How about to add section "Build-in plugins" there?
http://jekyllrb.com/docs/plugins/

I can prepare PR, just asking if maintainers agree.

**Comment by parkr** [comment]
The non-Jekyll dependencies?

**Comment by envygeeks** [comment]
I think he means our actual dependencies, this is a spawn of the discussion on @jekyll/docker where it was originally thought that the dependencies there were dependencies of the Docker image but are actually the dependencies of Jekyll.

**Comment by parkr** [comment]
We used to have them in our readme but we decided they were all too often ignored or not updated.

Paraphrase for me please: why do you think listing our dependencies is helpful?

**Comment by iBobik** [comment]
Jekyll users usually are not Ruby devs, so they don’t know how to see what
is included there and what they can use without installing something extra.



Jan Pobořil

2015-10-25 18:40 GMT-05:00 Parker Moore <notifications@github.com>:

**Comment by parkr** [comment]
> what they can use without installing something extra

I agree that sometimes the core functionality of Jekyll is not very well understood. We try to explain it in our [Basic structure](http://jekyllrb.com/docs/structure/) documentation page. What could we describe better? Ideally the dependencies are not something the user has to consider (except where they have a choice, like Kramdown vs Redcarpet). What dependencies don't we explain?

**Comment by iBobik** [comment]
At first, what are these buid-in packages? :-)



Jan Pobořil

2015-10-26 11:44 GMT-05:00 Parker Moore <notifications@github.com>:

**Comment by iBobik** [comment]
Example use-case: I/user googled how to make redirects for migrated site. I found jekyll-redirect-from gem. I see, that it is included in @jekyll/docker, but not mentioned at jekyllrb.com/docs. And I don't know if is is already enabled in Jekyll, or I should install it like on plugin's README, or it is just needed to enable it in _config.yml.

All this questions should be answered somewhere visible because it is UX bug. I can help with solution (submit PR), I just need "strategic decision" what is right solution.
