### ISSUE TITLE
Documentation for incremental regeneration

### ISSUE THREAD

**Issue by alfredxing** [jekyll/jekyll#4057]
I still need to write some documentation for incremental regeneration specifying:

- What it does and a brief overview of how it works
- Warnings, shortfalls, and where it doesn't work
- Configuration options

It's midterm season (:cry:) so this will probably have to wait for a few days until after my exams this week.

**Comment by envygeeks** [comment]
I think it was agreed on (informally) to disable it until 3.1 so we can work out the kinks and bugs because you were busy, @parkr would have to backtrack and confirm but I don't assume it's important to write them until it goes on by default.

**Comment by alfredxing** [comment]
That's what I was thinking as well (making it an "experimental" feature for now).

It's definitely not critical as you mentioned, but It'll still be good to have docs for users who want to try it out or enable it though.

**Comment by parkr** [comment]
> I think it was agreed on (informally) to disable it until 3.1 so we can work out the kinks and bugs

Oh, it's totally on by default right now and there's no flag to turn it on. When did we decide to turn it off by default?

**Comment by envygeeks** [comment]
Quite a while back (probably like 4 months ago now) when I was struggling to get it to work with some stuff and filed that big ticket with a bunch of stuff coupled into a single ticket.

**Comment by envygeeks** [comment]
Oh, it looks like it was about 6 months ago now: https://github.com/jekyll/jekyll/issues/3747

**Comment by envygeeks** [comment]
If I'm honest though, I'm on the fence and will digress to @alfredxing, since that ticket was filed we've found ways to work around the lot of the stuff on sites we build on our cluster, except for pages not being rendered on update of another page and sometimes pages not being rendered I think others have had that problem too as there are a few tickets about it.

**Comment by alfredxing** [comment]
I'll need to re-familiarize myself with exactly how the regenerator behaves. I know that basically the only thing that isn't recorded as a dependency right now is any reference to rendered post/page content outside of that post/page, since this usually involves references to `post.content` which is not directly checkable by the regenerator.

I guess one thing (that I just thought of!) is that we can check _in the post.content accessor method_ whether or not the post is rendered, then render it on-the-fly if it isn't...

**Comment by alfredxing** [comment]
But: my call is that we disable it by default for now.

This should be a simple switch in `configuration.rb` of the `full_rebuild` option&mdash;maybe rename this too?&mdash;and fixing broken Regenerator tests by re-enabling that flag for those tests.

**Comment by alfredxing** [comment]
:arrow_up: PR to disable incremental by default!

**Comment by parkr** [comment]
> But: my call is that we disable it by default for now.

Not a bad idea.

**Comment by parkr** [comment]
@alfredxing Have time to write some docs for this?

**Comment by alfredxing** [comment]
I'll see if I can get something done tonight. I'll be away for a couple days starting tomorrow, though.
