### ISSUE TITLE
page.excerpt no longer output in Jekyll v3.0.0.pre.rc1

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll#4061]
Given a markdown file with an `excerpt` in its YAML front matter, in this version of Jekyll, it is no longer output. Instead, the default (the first paragraph of the file body) is shown instead.

**Comment by parkr** [comment]
Is your `excerpt_separator` set? The default?

Looks like if it's set, we just override your custom excerpt. https://github.com/jekyll/jekyll/blob/5e425a99b4b808589d452a6e6db16e97734050b7/lib/jekyll/document.rb#L309-L311

**Comment by paulrobertlloyd** [comment]
I’m not using the `excerpt_separator` feature.

**Comment by parkr** [comment]
@paulrobertlloyd So it's not set to `""` in your `_config.yml`? It's set to `"\n\n"` by default, which is enabled.

**Comment by parkr** [comment]
Thanks for the bug report :)

**Comment by paulrobertlloyd** [comment]
No problem. Yup, to be clear, not setting any type of separator, and only using `excerpt:` within my YAML front matters. And if one exists, I show it:

{% if page.excerpt %}
<div class="p-summary">
    {{ page.excerpt | markdownify }}
</div>
{% endif %}

Hope that helps!

**Comment by parkr** [comment]
@paulrobertlloyd Automatic excerpt generation is on by default, just so you know, so `page.excerpt` will always yield something unless you set `excerpt_separator: nil` or `excerpt_separator: ""` in your `_config.yml`.

**Comment by paulrobertlloyd** [comment]
@parkr Oh, that’s good to know, thanks!
