### ISSUE TITLE
Including a symlinked file in safe mode outputs the error to the rendered document, exits 0

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#4066]
## Steps to reproduce

1. Create an `index.html` file with the content:
  
    ```
    ---
    ---
    
    {% include foo.html %}
    ```

2. Make `_includes/foo.html` a symlink to a file outside your source directory

3. `jekyll build --safe`

## Expected

* Exit status > 0
* Red output to STDOUT with the text `Liquid error: The included file ‘_includes/foo.html’ should exist and should not be a symlink`
* `_site/index.html` should be blank

## Actual

* Exit status of 0 
* No error output
* `cat _site/index.html` returns:

    ```
   <p>Liquid error: The included file ‘/Users/benbalter/projects/jekyll-test/_includes/foo.html’ should exist and should not be a symlink</p>
   ```

(Note the full path, which we don't use elsewhere AFAIK).

I believe this to be a regression from 2.x to 3.x.

To note, the symlink file is properly *not* included.

**Comment by envygeeks** [comment]
If you expect an exit we need follow proper casing and `exit 1` but I think I would prefer us not to exit and bubble the error in both places.  Unless I am missing the purpose of "exit status of 0"

**Comment by benbalter** [comment]
> Unless I am missing the purpose of "exit status of 0"

More technically, I was expecting an exception to be raised, which would have resulted in a non-zero exit status (as it does for other errors that are raised (e.g., invalid tags, etc.))

**Comment by Crunch09** [comment]
Hey, if no one has started on this yet, i'd be happy to try a patch?

**Comment by envygeeks** [comment]
@Crunch09 this is a two parter in two repos.  First there is a problem with the command system Jekyll uses which doesn't always exit 1 (actually it exits 0 sometimes -- that issue is already documented) and this issue where it doesn't raise.  Patches are welcome but not required!

**Comment by parkr** [comment]
Not sure if this is a Liquid issue. Perhaps @fw42, @pushrax, or @dylanahsmith could elaborate on why the error is being rescued by Liquid and output in the template instead of being sent back to caller?

**Comment by envygeeks** [comment]
@parkr There was something a while back that @fw42 did that made errors surface properly, maybe we should go back and reaudit the patch and see what changed since his commits.  I'll do a blame tomorrow if you don't want to.

**Comment by fw42** [comment]
This is with Liquid 3.0.6?

**Comment by fw42** [comment]
I don't think this is a recent change, the same behaviour is present with Liquid master, Liquid 3.0.6, Liquid 2.6.3, and Liquid 2.5.5, as far as I can tell.

**Comment by fw42** [comment]
You can use `render!` (instead of `render`) or use the `rethrow_errors` config option, if you want exceptions to bubble up...

**Comment by fw42** [comment]
Did someone confirm that this is behaving differently on Jekyll 2.x?

**Comment by benbalter** [comment]
Yes. This broke one of our integration tests for GitHub Pages (which verified that the error was properly raised). You can see the currently working versions at https://pages.github.com/versions.

**Comment by envygeeks** [comment]
@benbalter do you guys run the tests on 2.5? can you test it on 2.5 so we can see when it started (well what branch.)

**Comment by benbalter** [comment]
> do you guys run the tests on 2.5? can you test it on 2.5 so we can see when it started (well what branch.)

It's definitely new to either Jekyll 3.x or Liquid 3.x. 

I created [this small test script](https://github.com/benbalter/jekyll-symlink-test), and set up [a build matrix on Travis](https://travis-ci.org/benbalter/jekyll-symlink-test) to run it against `master`, 3.0.0 and the past five versions. Here's what we've got:

![screen shot 2015-10-29 at 2 09 53 pm](https://cloud.githubusercontent.com/assets/282759/10827707/c11d4738-7e46-11e5-8c1a-ff65747cf4a1.png)

You can clone down the repo and test it yourself locally by pointing the gemfile at a local path to jekyll, or in theory, if you submit a PR to my test repo (potentially adding a new jekyll brand to test against), it should properly test the use case.

**Comment by fw42** [comment]
I think this might have been caused by https://github.com/jekyll/jekyll/pull/3762, especially [this line](https://github.com/jekyll/jekyll/commit/1e9163fdf449acefcbd541ff41cb447883be3557#diff-817b22aa9906612f8c43543d6aa8202dL112) where I changed it from `render!` to `render`. Changing it back to `render!` might fix this bug.

**Comment by fw42** [comment]
As far as I remember, that change was not intentional. Looks like it should have stayed `render!`. I'm kinda busy right now, can someone else take care of this and see if that's actually the problem?

**Comment by envygeeks** [comment]
I think it's something else but I'm already forking @benbalter script to create a more robust test scenario where it tests specific commits.

**Comment by benbalter** [comment]
> I think it's something else but I'm already forking @benbalter script to create a more robust test scenario where it tests specific commits.

@envygeeks added you as a collaborator if it's easier / you don't want to deal with travis. Feel free to commit directly to `master` if you want.

**Comment by parkr** [comment]
I think #4077 will take care of this.

**Comment by BlockWorld** [comment]
It's seeming to work if I don't put it in the actual site, if I symlink it from `blockworld.github.io/tests/index.html` it works.

**Comment by envygeeks** [comment]
@BlockWorld can you please provide an example? What you are experiencing is a higher level bug (if it is a bug) than this one I'm to assume (in that if it lets you use a symlink we have a problem higher up -- this was about the error that include was sending not surfacing.) Now I might be wrong and @parkr would have to confirm but I believe we do allow symlinks as long as they originate from within the current build folder.

**Comment by BlockWorld** [comment]
Wow. I JUST got a few emails saying there was a page build error. Never mind. :/
