### ISSUE TITLE
enumerate markdown files in folders other than _posts

### ISSUE THREAD

**Issue by treetty** [jekyll/jekyll#4071]
it's very convenient to enumerate posts, especially markdown files in _post, and embed in js script or html script, such as:

```
<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>
```

however, it seems _posts is the only folder that can use loop. there's no way out when there're more than two categories of docs that need to to be enumerated.

**Comment by envygeeks** [comment]
All data should be enumerable now that it's all collections and you should be able to get at it through `site.collections` in your Liquid but only @parkr can confirm that.

**Comment by parkr** [comment]
If you have `_docs`, you should be able to use `site.docs` to iterate over them. This works for any collection. Categories are available in `site.categories.CATEGORY`.
