### ISSUE TITLE
Consider adding a new permalink style with original title name (no downcase)

### ISSUE THREAD

**Issue by rebornix** [jekyll/jekyll#4072]
After upgrading my website from 2.5 to 3.0, `:title` in permalinks will be converted to lower case. All my website page links change slightly, for instance, from `/2015/10/27/NewPost/` to `/2015/10/27/newpost/`. It's a minor change, but all the links I used in other websites are broken totally.

As all permalink style are using the lower case `:title`, there is no backwards compability or any flexibility. Can we have another permalink style to use the original `title` from file name?

**Comment by parkr** [comment]
Seems like a regression to me. Does this affect only posts for you, or for all documents/pages/posts?

**Comment by rebornix** [comment]
It only affects posts, documents and pages are okay. I went through the code base roughly, it maybe not an easy fix. The code is using `Utils.slugify` to generate post file's metadata `permalink` or `title` in pre-process phase

```
  string.
        # Strip according to the mode
        gsub(re, '-').
        # Remove leading/trailing hyphen
        gsub(/^\-|\-$/i, '').
        # Downcase
        downcase 
```

When we finally generate the permalink per Permalink Style configuration
```
def add_permalink_suffix(template, permalink_style)
      case permalink_style
      when :pretty
        template << "/"
      when :date, :ordinal, :none
        template << ":output_ext"
      else
        template << "/" if permalink_style.to_s.end_with?("/")
        template << ":output_ext" if permalink_style.to_s.end_with?(":output_ext")
      end
      template
    end
```

The permalink is already finalized. We can't easily pass any optional parameter to determine whether to lowercase the title.

I'm not a ruby guy, correct me if I'm wrong.

**Comment by rebornix** [comment]
BTW, there is a workaround for this issue: add permalink "/2015/10/31/UpperCase.html" in post's yaml front matter. But I have to update all my posts ...

**Comment by parkr** [comment]
In 3.0.1, `:title` will be what it used to be.
