### ISSUE TITLE
Vanilla site creates stray, possibly invalid `.jekyll-metadata` file

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#4075]
## Steps to reproduce

1. Create a new directory, add a Gemfile with `gem "jekyll", "3.0.0"`, and an `index.html` file with some content
2. `bundle exec jekyll build`

## Expected

1. `_site` folder with `index.html` file
2. No changes to the source folder since incremental regeneration is disabled by default

## Actual

1. `_site` folder with `index.html` file
2. New `.jekyll-metadata` file with a single `{` as the content

I suspect this might be a side affect of incremental generation being disabled by default? In either case, I'd assume a single `{` does not make a valid metadata file.

**Comment by parkr** [comment]
Truth. Thanks, @benbalter !

**Comment by envygeeks** [comment]
See: #4079

**Comment by benbalter** [comment]
*Finding esoteric bugs since 2013* (TM) :smile:
