### ISSUE TITLE
What is the Jekyll 3 equivalent of this simple plugin?

### ISSUE THREAD

**Issue by bdesham** [jekyll/jekyll#4083]
Under Jekyll 2.x I used the following plugin for easy access to a page’s “full URL” (domain and path). I could write `{{ page.full_permalink }}` in the layout file and I got the expected output both in blog posts and in standalone pages.

```
module Jekyll

  class Page
    ATTRIBUTES_FOR_LIQUID.push('full_permalink')
    def full_permalink
      site.baseurl + url
    end
  end

  class Post
    ATTRIBUTES_FOR_LIQUID.push('full_permalink')
    def full_permalink
      site.baseurl + url
    end
  end

end
```

When I tried to use this under Jekyll 3.0.0 I got an error because `Post` no longer exists. I tried changing “Post” to “Document” (which necessitated also removing the “attributes for liquid” line), and I also tried removing the “Post” monkey-patch completely, and in both of those cases I got no errors but the `{{ page.full_permalink }}` tag produced no output.

I’ve created a simple example in [this GitHub project](https://github.com/bdesham/jekyll-permalink-test). If you uncomment the lines in “full_permalink.rb” and build it under Jekyll 2.5 you can see that both of the generated pages have the desired permalink in them. How do I need to adapt this plugin to get it to work under Jekyll 3?

**Comment by parkr** [comment]
@bdesham Use a hook:

```ruby
Jekyll::Hooks.register [:posts, :pages], :pre_render do |doc|
  doc.data['full_permalink'] = doc.site.baseurl + doc.url
end
```

See http://jekyllrb.com/docs/plugins/#hooks

**Comment by envygeeks** [comment]
Plugins just got a metric tonne quicker.

**Comment by bdesham** [comment]
OK, thanks. I found that I actually needed to do this:

```ruby
Jekyll::Hooks.register [:posts, :pages], :pre_render do |doc, hash|
  full_permalink = doc.site.baseurl + doc.url
  doc.data['full_permalink'] = full_permalink
  hash['page']['full_permalink'] = full_permalink
end
```

to get the permalink to show up in the generated “about.html” in my example. Is this a bug? If not, can you briefly explain the difference between `doc.data` and `hash['page']`?

**Comment by parkr** [comment]
Nope, that's as expected. Maybe there's a different hook earlier on that would work.

**Comment by bdesham** [comment]
Using the post-init hook didn’t really work; at that point `doc.url` is equal to something like

    /2015/10/2012-09-03-some-article

when it should really be

    /2012/09/some-article

Maybe there’s a way to fix the URL but it seems like way more effort than it’s worth.

**Comment by parkr** [comment]
Pre render should work fine. :)
