### ISSUE TITLE
sub-directories of _path are being added to the categories variable

### ISSUE THREAD

**Issue by Daniel0524** [jekyll/jekyll#4084]
I'm not sure if this is an intended regression/behavior but since upgrading from the Jekyll 3.0-beta to Jekyll 3.0, my permalink structure has changed.

My permalink structure is set as the following:
```
permalink: :categories/:title/
```

My `_posts` directory looks like this:

```
_posts
├── blogs
│   └── 2014-05-19-great-blog-post.md
└── photo_blogs
    ├── 2014-03-23-great-photo-blog-post.md
    └── africa
        └── 2015-05-16-great-photo-blog-post-with-additional-category.md
```

Prior to Jekyll 3.0, my posts were created with the following page/permalink/directory structure inside the _site directory which is exactly in line with the documentation for permalink:
```
title: Post, categories: ['post']----------------------->/post/Post
title: PhotoPost, categories: ['photos']---------------->/photos/PhotoPost
title: PhotoPostAfrica, categories: ['photos','africa']->/photos/africa/PhotoPostAfrica
```

However since switching to 3.0, the permalink structure has changed. Now each post is being placed inside whichever folder it was inside in the _posts folder. I don't care about the directory structure inside `_posts/`, and before 3.0, Jekyll didn't either, but now it does and it generates the following directory structure inside `_site`:

```
title: Post, categories: ['post']----------------------->/blogs/post/Post
title: PhotoPost, categories: ['photos']---------------->/photo_blogs/photos/PhotoPost
title: PhotoPostAfrica, categories: ['photos','africa']->/photo_blogs/photos/africa/PhotoPostAfrica
```

I realize I could get around this by flattening all of the posts inside `_posts/**/*` into just `_posts`, but I'd rather not do that. Is there anything I can do to get permalinks to support the old behavior? Is the old behavior deprecated?

**Comment by Daniel0524** [comment]
Doing more reading on this it seems like this might be a side effect of the deprecation of what is referred to in the docs as [Absolute Permalinks](http://jekyllrb.com/docs/upgrading/#absolute-permalinks).

I have no idea if this is the case because despite constant references to `relative permalinks` and `absolute permalinks` throughout the docs, there isn't an actual definition of them anywhere that I can find.

Additionally - if this is the case - then I would have expected this behavior to have presented itself way back when absolute paths became opt-out in Jekyll 2.0 - or for that matter when I upgraded to the 3.0beta.

Any confirmation of whether or not I'm understanding this correctly would be really helpful. Likewise if there is way for me to maintain my existing permalink structure without flattening my _posts subdirectories I'd appreciate the help!

**Comment by parkr** [comment]
Relative permalinks is about the permalink setting in your individual pages. It shouldn't affect this. Not sure what's happening here but will try to dig into it. Might be automatic category inference causing issues.

**Comment by Daniel0524** [comment]
It seems like it may be related to https://github.com/jekyll/jekyll/pull/2633. It seems like all first-child subdirectories of _posts are now being automatically introduced as categories?

I don't think this behavior makes sense - it doesn't seem right to be conflating something set manually in front-matter with something that's generated automatically based on your folder structure.

**Comment by Daniel0524** [comment]
Just ran a quick check and verified that `{{page.categories}}` is adding the subdirectories `photo_blogs`/`photos` as a category to the page automatically.

Maybe I read #2633 and https://github.com/jekyll/jekyll/pull/2705  incorrectly, but it seems like this should decidedly **not** be the behavior.

**Comment by Daniel0524** [comment]
This is a pretty significant breaking change - do we know whether it was intended or not?

**Comment by parkr** [comment]
@Daniel0524 This is a side effect of moving posts from a single array to being a collection. I think we only meant to do categories before `_collection`, so just `es/_posts` not `_posts/es`. This can be fixed in the `initialize` method of `Document`.

**Comment by parkr** [comment]
@Daniel0524 #4110 should fix this for you.
