### ISSUE TITLE
incremental regeneration breaks auto generation feature

### ISSUE THREAD

**Issue by rebornix** [jekyll/jekyll#4089]
Using Jekyll 3.0.0 on windows, if I start the jekyll service with `jekyll serve`, once I update the layout content, the site is regenerated automatically and I can see the change real quick. But if I run `jekyll serve -I`, after I change the layout, the verbose output shows it noticed the update but the related output file was still the old one...

BTW, it's even harder to set up development environment on Windows, which means I can't run all the test cases on Windows for troubleshooting...

**Comment by envygeeks** [comment]
Provide logs from `--verbose`.

**Comment by rebornix** [comment]
I update layout `_layout/post.html` then visit the post page once more. 

```
http://localhost:4000/jekyll/update/2015/10/31/welcome-to-jekyll.html -> /css/main.css
      Regenerating: 1 file(s) changed at 2015-11-01 21:26:47        EntryFilter: excluded?(/default.html) ==> false
       EntryFilter: excluded?(/page.html) ==> false
       EntryFilter: excluded?(/post.html) ==> false
       EntryFilter: excluded?(/about.md) ==> false
       EntryFilter: excluded?(/css) ==> false
       EntryFilter: excluded?(/feed.xml) ==> false
       EntryFilter: excluded?(/index.html) ==> false
       EntryFilter: excluded?(/_posts/2015-10-31-welcome-to-jekyll.markdown) ==> false
           Reading: _posts/2015-10-31-welcome-to-jekyll.markdown
       EntryFilter: excluded?(/css/main.scss) ==> false
         Rendering: /css/main.scss
  Pre-Render Hooks: /css/main.scss
  Rendering Liquid: /css/main.scss
  Rendering Markup: /css/main.scss
 Post-Render Hooks: /css/main.scss
...done in 0.115002 seconds.
[2015-11-01 21:27:07] DEBUG close: 127.0.0.1:4297
[2015-11-01 21:27:13] DEBUG accept: 127.0.0.1:4337
[2015-11-01 21:27:13] DEBUG  is invoked.
127.0.0.1 - - [01/Nov/2015:21:27:13 China Standard Time] "GET /jekyll/update/2015/10/31/welcome-to-jekyll.html HTTP/1.1" 304 0
- -> /jekyll/update/2015/10/31/welcome-to-jekyll.html
[2015-11-01 21:27:13] DEBUG  is invoked.
127.0.0.1 - - [01/Nov/2015:21:27:13 China Standard Time] "GET /css/main.css HTTP/1.1" 200 8810
http://localhost:4000/jekyll/update/2015/10/31/welcome-to-jekyll.html -> /css/main.css
```

**Comment by parkr** [comment]
Your comment above is confusing. I don't get what you did differently between the two logs.

It looks like you found a drawback of the current incremental regeneration: if you change the layout, anything using that layout may not be regenerated. If you change a post, only it will be regenerated, not everything that includes it. There are dependency problems with incremental regeneration.

**Comment by rebornix** [comment]
@parkr sorry for that, it's a mistake, please see my update. 

The only difference is the first one is running on Windows while the second is running on Ubuntu. If I change the layout, anything using the layout will be regenerated on Mac or Ubuntu, but this doesn't happen on Windows Machine.

**Comment by parkr** [comment]
Could you please create a sample repo that can be used to replicate this?

**Comment by rebornix** [comment]
@parkr Actually it's just a new jekyll site without any change, you can refer to [this repo](https://github.com/rebornix/jekylltest), on your windows machine, run `jekyll serve -I --verbose`, then edit `_layouts\post.html`, you can see jekyll monitored the change but doesn't take effect.

BTW, if you don't have windows box, I can setup one for you to test.

**Comment by parkr** [comment]
> BTW, if you don't have windows box, I can setup one for you to test.

That would be great! I don't presently have any Windows machines available for testing.

**Comment by rebornix** [comment]
@parkr sent you email :)
