### ISSUE TITLE
Where is Jekyll:Post  in jekyll 3?

### ISSUE THREAD

**Issue by santos82** [jekyll/jekyll#4092]
Hi
I have a plugin that add some liquid attributes to post like that:
```ruby
module Jekyll
	class Post
		def cleanurl
			...
		end

		def to_liquid(attrs = ATTRIBUTES_FOR_LIQUID)
			super(attrs + %w[
				cleanurl
			])
		end
	end
end
```
And it was working in Jekyll 2 but now, in Jekyll 3, it seem that class Post not exists.

Where have I placed know this kind of code?

**Comment by envygeeks** [comment]
Hi, sorry to do this but this is not a bug, please ask your implementation questions at https://talk.jekyllrb.com

**Comment by parkr** [comment]
For anyone else looking for an answer to this, please see: https://talk.jekyllrb.com/t/where-is-jekyll-post-in-jekyll-3/1441/2
