### ISSUE TITLE
I can't install jekyll with gem on El Capitan

### ISSUE THREAD

**Issue by AndyHT** [jekyll/jekyll#4093]
I want to install jekyll with gem, but I got this error in terminal
```bash
$ sudo gem install jekyll
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/jekyll
```

so I installed jekyll on other place
```bash
$ sudo gem install -n /usr/lcoal/bin/ jekyll -V
```

but when I got error message when I use jekyll like that
```bash
$ jekyll serve
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/bundler-1.9.9/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find jekyll-gist-1.1.0 in any of the sources (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.9/lib/bundler/spec_set.rb:85:in `map!'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.9/lib/bundler/spec_set.rb:85:in `materialize'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.9/lib/bundler/definition.rb:132:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.9/lib/bundler/definition.rb:177:in `specs_for'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.9/lib/bundler/definition.rb:166:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.9/lib/bundler/environment.rb:18:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:13:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.9.9/lib/bundler.rb:122:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:38:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.0/bin/jekyll:13:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```
but I already installed jekyll-gist 1.3.5.
How can I solve the problem?

**Comment by mattr-** [comment]
El Capitan doesn't allow unsafe binaries in system controlled locations anymore, and `/usr/bin` is one of those locations. The only workaround I'm aware of requires installing a tool such as `rvm` or `rbenv` and using it to manage your rubies, but that's a lot of effort on your part. Sorry I couldn't be more help. You might want to check talk.jekyllrb.com to see if someone there has a solution for you.

**Comment by parkr** [comment]
When you ran `jekyll serve`, there was a Gemfile you had in that directory. The `Gemfile.lock` asked for jekyll-gist v1.1.0, not v1.3.5 so it didn't care. Use `bundle update` to update your Gemfile.lock.

/cc #3999

**Comment by alfredxing** [comment]
@AndyHT We have a handy section relating to this issue as well [on our Troubleshooting page](http://jekyllrb.com/docs/troubleshooting/#jekyll-amp-mac-os-x-1011)! Personally, I recommend using the Homebrew method.

**Comment by kevinSuttle** [comment]
I still can't install `jekyll` on OSX 10.11.2. I have tried everything short of compiling the ruby source myself.

- [x]  `brew install rbenv`
- [x]  `brew install ruby-install`
- [x]  `brew install ruby`
- [x]  `sudo chown -R $USER /usr/local`
- [x]  `xcode-select --install`
- [x]  `sudo xcodebuild -license`
- [x]  `sudo gem update --system`
- [x]  `export PATH=/usr/local/bin:$PATH`
- [x]  `gem install --user-install --bindir ~/bin --no-document --pre --verbose jekyll` 
- [x]  `sudo gem install -n /usr/local/bin jekyll`

```bash
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.2.0/gems/ffi-1.9.10/ext/ffi_c
/usr/local/bin/ruby -r ./siteconf20151213-36533-e9ynie.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/local/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.2.0/gems/ffi-1.9.10 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/ffi-1.9.10/gem_make.out
```
**Same** exact error. _Every_. Single. Time. 



```bash
❯ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

❯ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

**Comment by parkr** [comment]
Try this:

```bash
$ brew remove ruby
$ rbenv install 2.2.3
$ rbenv global 2.2.3
$ gem install jekyll
```

**Comment by kevinSuttle** [comment]
Thanks @parkr. Will give it a shot.

**Comment by kevinSuttle** [comment]
:boom: That did it!

**Comment by kevinSuttle** [comment]
@parkr saves the day once again. :+1:

**Comment by myseven** [comment]
For me, `sudo gem install -n /usr/local/bin/ jekyll` works, maybe  it is permission problem.

**Comment by arlogilbert** [comment]
@myseven that worked like a charm!

**Comment by AndyHT** [comment]
If you don't like input <code>/usr/local</code>  every install, you can close Rootless.
Link:[http://apple.stackexchange.com/questions/204312/cant-install-bundler-using-gem](http://apple.stackexchange.com/questions/204312/cant-install-bundler-using-gem)

**Comment by fbarrento** [comment]
`$ brew remove ruby`
`$ brew install ruby`
`$ brew link libyaml`
`$ sudo gem install jekyll bundler`

**Comment by aniddan** [comment]
@myseven I think sudo is unnesseacry there
