### ISSUE TITLE
`where` on array

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll#4094]
I am trying to write:
`{{site.posts | where:"tags","MyTag"}}`

But it does not return anything.

"tags" is an array of strings, is it supposed to work?

**Comment by alfredxing** [comment]
I believe the `where` filter requires an exact match, which in this case we don't have, since (as you mentioned) the tags are an array, and you are trying to match it with just a string...

What behaviour are you trying to achieve with this?

**Comment by parkr** [comment]
@nasht00 That is already available: `site.tags.MyTag` will contain a list of posts with that tag.

**Comment by nasht00** [comment]
Thank you @parkr that is a nice feature. Is it documented anywhere?

**Comment by nasht00** [comment]
Also, how would you choose "MyTag" but with a variable?

Assume that "MyTag" is defined in `page.checkTag`.

**Comment by parkr** [comment]
@nast00: `site.tags[page.checkTag]`.

**Comment by parkr** [comment]
@nasht00 Yes, see http://jekyllrb.com/docs/frontmatter/#predefined-global-variables, under `tags`.

**Comment by nasht00** [comment]
The link you attached described how to define `tags` for a specific post. It does not mention the `site.tags` variable that contains the list of posts for each tag.

**Comment by parkr** [comment]
Whoops! My bad. See here: http://jekyllrb.com/docs/variables/#site-variables
