### ISSUE TITLE
XML file with no trailing slash

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll#4095]
For backward-compatibility, I want to support my old Wordpress-style URL for my RSS feed:

`/feed/`

I use the `pretty` permalink, but for `xml` files it still generates them with the `.xml` extension (which I can understand).

How do I force a specific xml file to have a different path, ending with a trailing slash, while keeping the content type to xml?

**Comment by envygeeks** [comment]
Hi @nasht00 this is not a Jekyll bug so I must ask that you please ask your question at https://talk.jekyllrb.com.  To add this is a problem with the server serving the Jekyll files, if it's with Github Pages you should email support@github.com as they control the servers that control and serve Jekyll content for Github Pages.  If it happens in development there is already a pull request that allows that but it needs to be updated and probably won't land until 3.1 (maybe 3.2.)

**Comment by nasht00** [comment]
Sorry I was not aware of this talk site.
Moved the conversation there: https://talk.jekyllrb.com/t/xml-file-with-no-trailing-slash/1460
