### ISSUE TITLE
Jekyll 3.0.0 | Error:  undefined method `gsub' for #<Hash....

### ISSUE THREAD

**Issue by Jepz** [jekyll/jekyll#4097]
Just updated my Jekyll  2.5.3 to 3.0, tried to run "jekyll serve", under "Generating..."-phase i'm getting the error: jekyll 3.0.0 | Error:  undefined method `gsub' for #<Hash:0x007fa363880460>. FYI, the numbers after Hash is new everytime.

Care to help me out? =)

**Comment by alfredxing** [comment]
Can you run Jekyll with the `--trace` flag? It'll help us pinpoint the issue. Also, if you're able to, the source code of the site you're trying to build would be super useful too.

**Comment by Jepz** [comment]
Terminal gives me this:
  Deprecation: Jekyll now uses subcommands instead of just switches. Run `jekyll --help` to find out more.
..when I run jekyll --trace.

I guess something must be broken... :-/

**Comment by Jepz** [comment]
Sorry about the previous post, changed it to the log information you were asking for.
When you say source code, what do you need? Would it be good enough with a lin to the repo?

**Comment by alfredxing** [comment]
Found the issue! If you're specifying `output` or `permalink` for a collection, you'll need to specify the collection itself as a hash and not part of an array.

So in your `_config.yml`, use this instead:
```yaml
collections:
  projects:
    output: true
    permalink: /projects/:path/
```

Let me know if that works!

**Comment by Jepz** [comment]
Thanks! it helped!
I actually hade that already in my config, but hade the hyphen before projects. Removing the hyphen made it work =)

Thanks for helping out!

**Comment by ron4stoppable** [comment]
thanks @alfredxing that worked for me too
