### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by zeynel1** [jekyll/jekyll#4098]
Hello, I was trying to install Jekyll with `gem install jekyll` but I got this error `You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory` I'm using Yosemite 10.10. I looked up your troubleshooting suggestions but İ did not try them because [this Stack Exchange thread](http://stackoverflow.com/questions/14607193/installing-gem-or-updating-rubygems-fails-with-permissions-error) questions the safety of using `sudo` to change system Ruby. I'm not an advanced user to try other options. Is there an easier way to install Jekyll? It's a shame because I was excited to try Jekyll. Thanks.

**Comment by parkr** [comment]
@zeynel1 I guess you're on a mac? Are you using Homebrew? You can run `brew install ruby` and that should make things a bit easier for you. :)

**Comment by parkr** [comment]
This issue tracker is for bugs so if you have further issues, please use talk.jekyllrb.com.
