### ISSUE TITLE
Importing Bourbon and getting Sass Error

### ISSUE THREAD

**Issue by loganegbert** [jekyll/jekyll#4099]
Trying to get Bourbon up and running with my Jekyll site.

All of the files are in the _sass directory. The main.scss file is in a scss directory, the subsequent css file will be output to a css directory.

I put the following into that main scss file:

>@import "bourbon/bourbon";
@import "neat/neat";
@import "base/base";

When I run sass -w scss:sss I get:

>error scss/main.scss (Line 5: Invalid CSS after "...ourbon/bourbon"": expected "{", was ";")

Any thoughts on what might be going wrong here?

I've made a non-jekyll project folder, done the import into a sass file and sass runs without error.

**Comment by loganegbert** [comment]
Jekyll v3.0.0

**Comment by parkr** [comment]
```scss
@import "bourbon/bourbon";
@import "neat/neat";
@import "base/base";
```

looks just fine. if you have the YAML front matter, then that will cause an error:

```
---
---
```

You should just use Jekyll directly if you have that.

**Comment by parkr** [comment]
Please post to talk.jekyllrb.com, this doesn't appear to be a bug in Jekyll.

**Comment by loganegbert** [comment]
I was under the impression the yaml front matter was necessary for the main CSS file. I'll try it again when I'm home and post to talk.jekyllrb.com if it still isn't working.

**Comment by parkr** [comment]
> I was under the impression the yaml front matter was necessary for the main CSS file.

It is, but it's not compatible with the `sass` generator.

**Comment by loganegbert** [comment]
Removing the YAML frontmatter just gave me a new error. I've moved things over to talk.jekyllrb.com to continue troubleshooting. 

Thanks!
