### ISSUE TITLE
error in running metasploit framework

### ISSUE THREAD

**Issue by Abdulaziz959** [jekyll/jekyll#4106]
when i try to install metasploit by ./msfconsole
![picsart_11-03-06 06 17](https://cloud.githubusercontent.com/assets/8897274/10918518/07c8fa86-825e-11e5-8453-858bd92cf50b.jpg)

What should i do to fix this issue plz.

**Comment by mattr-** [comment]
It doesn't look like that this is really a jekyll issue based on your screenshot.

**Comment by Abdulaziz959** [comment]
yes it isn't made a mistake it's my issue. so if u can help me to know how to fix it plz.

**Comment by mattr-** [comment]
you'd need to go ask the metasploit folks. Jekyll doesn't have anything to do with metasploit.

**Comment by Abdulaziz959** [comment]
tnx
