### ISSUE TITLE
Split Jekyllrb.com content from Jekyll source code

### ISSUE THREAD

**Issue by manuelgruber** [jekyll/jekyll#4107]
Hi,

I realized quite late that the source code of the Jekyll generator software and the content of the jekyllrb.com website are in the same Git repository.
Especially because jekyllrb.com is the flagship example for a Jekyll implementation, why not give it an own repository?

It will be a clean split between code and content. So why not put the [site folder](https://github.com/jekyll/jekyll/tree/master/site) into a separate location and use 2 git repositories with different purposes:
- https://github.com/jekyll/jekyll (source code)
- https://github.com/jekyll/jekyllrb.com (website)

@parkr @envygeeks @benbalter @alfredxing 
What do you think?

I'm more than happy to help and prepare everything.

Best Manuel

**Comment by envygeeks** [comment]
I'm Swiss on this topic because I'll support whatever is agreed on.

**Comment by parkr** [comment]
Hey @manuelgruber, we include it inside the source code here on purpose. We want to keep the code and the documentation up to date with each other and make it very easy to submit documentation changes for  code changes with one pull request. This cannot be done across multiple repositories so we have put the code here. The easier it is to keep the documentation in line with the code, the better off everyone will be.

Thanks!
