### ISSUE TITLE
i have ruby 2.0.0-p247 but jekyll still say: jekyll requires Ruby version >= 2.0.0

### ISSUE THREAD

**Issue by leandroruel** [jekyll/jekyll#4115]
i'm very pissed off because, i'm trying for a few hours install jekyll, googling here and there, and nothing solve my problem. i updated my ruby. and do a lot of things and this error persists

**Comment by leandroruel** [comment]
solved, after i few minutes, i figure out what happened, i need change my ruby version with RVM

with this command:

rvm use 2.0.0

**Comment by envygeeks** [comment]
I'm sorry you were having problems @leandroruel and I'm glad you figured it out.
