### ISSUE TITLE
Scss encounters and error while converting main.scss

### ISSUE THREAD

**Issue by whitephoenix0** [jekyll/jekyll#4119]
Google was no help, so hopefully we can figure this out. I am trying to set up jekyll and ran jekyll new, then when I try jekyll "serve", it outputs this:

https://gist.github.com/whitephoenix0/75384d699c3567d855ec

I don't think I'm doing anything wrong as this is a completely clean directory and I just fresh installed jekyll, but who knows

**Comment by rebornix** [comment]
What the exact command you ran to create a new website? The error logs show the folder you run jekyll serve is empty.

**Comment by whitephoenix0** [comment]
Wow. Go ahead and just close this, I was up a directory higher than I should have been. Sorry for wasting your time.

**Comment by envygeeks** [comment]
@whitephoenix0 next time you can use https://talk.jekyllrb.com and I'm sure somebody will help you figure out where your SCSS error is.
