### ISSUE TITLE
Documentation: HTML Proofer with baseurl

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll#4122]
I find this page very helpful:

http://jekyllrb.com/docs/continuous-integration/

However when trying to enable htmlproof, I ran into an issue. I am using `site.baseurl` in all my links, images, etc. And sure enough htmlproof fails on every request.

**Comment by parkr** [comment]
To work around this, put your site in a subdirectory of `_site` which corresponds to your site.baseurl. Run `bundle exec jekyll build -d _site/my/baseurl` and run `htmlproof` like usual against `_site` (the base). The links should then work as intended.

**Comment by nasht00** [comment]
Worked great. Thanks.

**Comment by swizca** [comment]
Sadly, the workaround requires hard coding baseurl in more places than just _config.yml. Bummer.

In any case, two more workarounds. (In my case, repo is 'dev', i.e. Links become /dev/\<something>.)
`--url-swap \'/dev/:/\'` (or)
`ln -s _site _site/dev`

The latter you will have to rerun each time, as build, or even serve, removes the link. You may want to script it. The ln is also circular, but seems to work.
