### ISSUE TITLE
Jekyll 3 not reading YAML variables on layout pages

### ISSUE THREAD

**Issue by madhur** [jekyll/jekyll#4123]
https://github.com/madhur/madhur.github.com/blob/source/_layouts/blog-post.html

I have this layout page with the following header:

```
---
layout: default
top: Madhur Ahuja
css: syntax.css
---
```

I have this line
` <title>{{ page.title }} &#8211; {{ page.top }}</title>`

in my `default.html`

https://github.com/madhur/madhur.github.com/blob/source/_layouts/default.html

Previously, `page.top` was working fine and was rendered as `Madhur Ahuja`. However, post jekyll 3, it is broken.

Rendered page example:

http://www.madhur.co.in/blog/2015/11/02/countdownlatch-python.html

**Comment by budparr** [comment]
If the front matter is in the layout, call it with: {{ layout.top }} That should work.

**Comment by madhur** [comment]
Is it not a breaking change? Is this documented somewhere

**Comment by envygeeks** [comment]
No, if it works with {{ layout.top }} then it's not, it's a feature change as this is a major version and it's up to @parkr if he wants to backport it into 3.0.

**Comment by ahnesbitt** [comment]
hi team. think I am stuck on this. I would like to specify my header per page and but just have a single `default.html` layout file. I would like to use the pages yaml to spec the header partial to include from `_includes` folder. 

so in default.html I do:

`  <div class="site-wrap">
    {% include {{page.header_select}} %}
....
  </div>
`

Then on each page yaml I do `header_select: headername.html`.

I always encounter the "Error: Invalid syntax for include tag. File contains invalid characters or sequences: Valid syntax: {% include file.ext param='value' param2='value' %} " error. Interestingly, if I do one of the default page vars like `page.title` it will fetch data correctly from my pages in `/posts`.

If i understand the covo above, the best way to do this would just be to have multiple layouts in addition to default.html and change the include call for each? I thought i followed the docs that  suggest `{% include {{my_variable}} %}` syntax. Am i correct that the layout cannot call a variable from a page's yaml in this manner?

I have also done it with if/else logic but not as simple. thanks! and pardon my noob level skills.

**Comment by parkr** [comment]
Can you confirm that `{% include {{page.header_select}} %}` works if you don't use a dot, like `{% include {{page_header_select}} %}`? Could be our regexp.

**Comment by budparr** [comment]
Try wrapping it in a conditional, like this:

```
{% if page.header_select %}
<div class="site-wrap"> {% include {{page.header_select}} %} .... </div> 
{% endif %}
```
The error is just telling you that somewhere you don't have header_select in a page that it's expecting from.

**Comment by ahnesbitt** [comment]
Thanks for the great work team! 

@parkr : using `{% include {{page_header_select}} %}` did not work in my case. 

@budparr : wrapping it in a conditional did do the trick so I am going with this construction. 

```<div class="site-wrap">{% if page.header_select %}
 {% include {{page.header_select}} %} 
{% endif %}.... </div> ```

thanks again for the help all!
