### ISSUE TITLE
Jekyll V3.0 requires gems: [jekyll-paginate] in config file on mac OSX El Capitan

### ISSUE THREAD

**Issue by saifthe1** [jekyll/jekyll#4124]
Few hours ago I updated Jekyll to version 3.0 using `gem update jekyll` command, the update process went fine however after restarting Jekyll I keep getting the following error  
`Deprecation: You appear to have pagination turned on, but you haven't included the jekyll-paginate gem. Ensure you have gems: [jekyll-paginate] in your configuration file.`
Accordingly I installed jekyll-paginate gem, although the site is running but I could observe categories being repeated twice which isn't the case prior to update the whole thing was working seamlessly. Please could someone help me with this issue?

**Comment by budparr** [comment]
This might help you: https://talk.jekyllrb.com/t/error-messages-when-upgrading-to-3-0-on-mac-os-x/1398/7?u=budparr

https://talk.jekyllrb.com/t/announcement-retiring-jekyll-paginate/1004/18

**Comment by saifthe1** [comment]
Thanks @budparr for your response. 
Moreover on downgrading Jekyll from V3.0 now it seems to work fine.

**Comment by vwochnik** [comment]
By looking into the repository today I have found some repercussions of `paginate`. For instance, the `Jekyll::Page.render` method contains a `paginator`. I'm not completely sure but I reckon that needs to be cleaned up.

**Comment by parkr** [comment]
We added the installation info to the docs: http://jekyllrb.com/docs/pagination/

@vwochnik That should be fine – if it's `Nil` then `NilClass#to_liquid` will just return `nil`.

**Comment by tomsarduy** [comment]
Been there, you just need to add the gem at the end of your `_config.yml` file.
```
# Gems
gems: [jekyll-paginate]
```

**Comment by yangshun** [comment]
Alternatively, add to your `Gemfile`:
~~~
gem 'jekyll-paginate', group: :jekyll_plugins
~~~

**Comment by chrisdemars** [comment]
None of this works whatsoever. I have installed the gem, added it to the config file, still getting errors.

**Comment by enriquecabra** [comment]
@chrisdemars I had the same trouble. Apparently was a problem with highlighter: pygments in changed pygments and it worked.

**Comment by JasonNewton1** [comment]
I also have this exact same problem. Where are the pygments?

Kind Regards

**Comment by DirtyF** [comment]
@JasonNewton1 default highlighter is now Rouge. See https://jekyllrb.com/docs/upgrading/2-to-3/#syntax-highlighter-changed

**Comment by JasonNewton1** [comment]
Thanks. I followed the instructions fir going back to pygments by writing highlighter: pygments in the config file and running gem install pygments.rb but I still get the dependency error for jekyll-paginate.

Thanks anyway.

**Comment by DirtyF** [comment]
@JasonNewton1 Did you follow instructions on http://jekyllrb.com/docs/pagination/?

**Comment by JasonNewton1** [comment]
I added it to the config file but I'm unsure about altering the Gemfile. How do I include the plug-in?

Kind Regards

**Comment by DirtyF** [comment]
@JasonNewton1 see: https://talk.jekyllrb.com/t/jekyll-paginate-is-not-working-with-jekyll-3-0-1/1700

**Comment by andrewbanchich** [comment]
I'm getting this error as well. I've tried adding the gem in several ways, including the official docs.

**Comment by deanilvincent** [comment]
I'm having this issue also.

**Comment by deanilvincent** [comment]
I added this code snippet on my _config.xml but it doesn't work.

`# Gems
gems: [jekyll-paginate]`

**Comment by ashmaroli** [comment]
@deanilvincent any error message?

**Comment by deanilvincent** [comment]
@ashmaroli there you have it

![screen shot 2017-06-01 at 11 27 47 pm](https://cloud.githubusercontent.com/assets/10904957/26687307/fc999e24-4721-11e7-98a7-c1fd8b4f388a.png)

**Comment by deanilvincent** [comment]
![screen shot 2017-06-01 at 11 32 26 pm](https://cloud.githubusercontent.com/assets/10904957/26687562/9cff3c34-4722-11e7-89ea-37e177f559e9.png)

I just fix it somehow by installing github-pages in administrator.

**Comment by ashmaroli** [comment]
@deanilvincent Another way without using `github-pages` gem is by simply adding the `jekyll-paginate` gem to your `Gemfile` as well:
```ruby
# Gemfile

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-paginate"
end
```

**Comment by noblesilence** [comment]
I had to:
1. in _config.yml, add
```
gems:
  - jekyll-paginate
paginate: 10
```

2. in Gemfile, add
```
group :jekyll_plugins do
   gem "jekyll-paginate"
end
```

3. In Terminal, type bundle install and press enter.
