### ISSUE TITLE
Docs out of date: Installing a plugin

### ISSUE THREAD

**Issue by rebornix** [jekyll/jekyll#4126]
Hi there,
  I'm trying to install plugins with the instruction from [Installing a plugin](http://jekyllrb.com/docs/plugins/#installing-a-plugin). The doc is saying we can type 

```
gem install jekyll-test-plugin jekyll-jsonify jekyll-assets
```

but after running this command in console, we would get

```
gem install jekyll-test-plugin jekyll-jsonify jekyll-assets
ERROR:  Could not find a valid gem 'jekyll-test-plugin' (>= 0) in any repository
ERROR:  Possible alternatives: jekyll_test_plugin
ERROR:  Could not find a valid gem 'jekyll-jsonify' (>= 0) in any repository
ERROR:  Possible alternatives: jekyll-jsminify, jekyll-json, jekyll-jsonball, jekyll-emoji, jekyll-slim
```

Only `jekyll-assets` exist for now. I suppose `jekyll-test-plugin` should be `jekyll_test_plugin`, but I'm not sure what's the alternative of `jekyll-jsonify`, or maybe we can just remove it? 

I can help update it to `gem install jekyll_test_plugin jekyll-assets` if you are fine with it.

**Comment by Lewiscowles1986** [comment]
I think it's code meant for illustrative purposes, and I am sure jsonify is now in the core of Jekyll... In any case, it's not for you to run each line; it's to illustrate this is the command sequence to run X AFAIK.

Looks like the code-examples at the top could use some :heart: though... want this wrangled?

**Comment by rebornix** [comment]
@Lewiscowles1986 let's say this is the first time you use Jekyll and you want to try this plugin feature, what kind of plugins you will install? I suppose most neophytes will just copy/paste the command we provide.

**Comment by envygeeks** [comment]
Copypasta is to the internet what Spaghetti and Meat Sauce is to America.  Everybody eats it and loves it and some claim they don't but they secretly eat it.

**Comment by envygeeks** [comment]
Incase nobody got that, I agree, it should probably be updated but I'll defer to @jekyll/core as to what plugins should be included, maybe since we dropped jekyll-coffeescript by default it should become one of the ones in that copy and paste lines, it seems like a lot of people who use Jekyll love them some CoffeeScript.

**Comment by napcae** [comment]
gem | number of downloads
---------|------------
jekyll-sass-converter |	783,914	
jekyll-coffeescript	| 724,886	
jekyll-watch  |	719,423
jekyll-gist	| 688,318	
jekyll-paginate	| 666,747
jekyll-sitemap	| 259,152
jekyll-redirect-from |	192,926	
jekyll-mentions	 | 176,246
jekyll-assets |	95,102	
jekyll-feed	| 50,523

Here is a table of the 10 most popular plugins. Maybe we should take the first 5?

**Comment by envygeeks** [comment]
I'm not afraid to admit that I am biased and will probably keep jekyll-assets there.

**Comment by parkr** [comment]
"An example:" means "This is what it would look like," not "try this thing here, it'll work". I guess I could have been more explicit about that.

**Comment by napcae** [comment]
Rule of the internet: If there is copy pasta, users will eat copy pasta.

**Comment by parkr** [comment]
> Rule of the internet: If there is copy pasta, users will eat copy pasta.

Hahaha, thanks @napcae for that Internet wisdom. I guess I have misplaced faith that people actually _read_ the documentation, rather than just look for the code blocks and copy-paste. It even says `jekyll-test-plugin`, which is like the old java days of `myArray` and `myString` in documentation – clear indication that this is an example and not the code you should actually be using.

**Comment by envygeeks** [comment]
Copy past is to the internet what Spaghetti and meat sauce is to America.  Everybody eats it and loves, some claim they don't but they're probably lying because everybody eats it in America.

**Comment by parkr** [comment]
I haven't had Spaghetti in _years_. :wink:

**Comment by parkr** [comment]
Fixed by https://github.com/jekyll/jekyll/pull/4154
