### ISSUE TITLE
Markdown templates

### ISSUE THREAD

**Issue by SoniEx2** [jekyll/jekyll#4132]
There should be templates to configure markdown, e.g.

_md/url.html (for `[text](url)` and friends)

```html
<a href="{{ whatever.url }}">{{ whatever.text }}</a>
```

_md/h1.html (for lines starting with `#`)

```html
<h1 id="{{ whatever.anchor }}"><a href="#{{ whatever.anchor }}" class="anchor">{{ whatever.text }}</a></h1>
```

etc.

**Comment by envygeeks** [comment]
What is the benefit here? Other than complicating something simple and adding a penalty to processing.

**Comment by SoniEx2** [comment]
Add links to headers automatically and more flexibility.

Alternatively this could be done with a custom plugin, but then it wouldn't work on github pages (which's what I want it on).

**Comment by envygeeks** [comment]
I don't know what the rest of @jekyll/core thinks about this but I personally think this is out of our scope.  I think if you want this it's an upstream problem.

**Comment by mattr-** [comment]
The general rule to follow is that if you want something outside of what Markdown does by default, then just embed HTML in the Markdown document. I agree with @envygeeks that this is out of scope for Jekyll's current goals and will close this issue.

We appreciate that you took the time to file an issue!
