### ISSUE TITLE
Make strings frozen by default to save some memory (and GC time sometimes.)

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4133]
```
# Frozen-string-literal: true
# Encoding: utf-8
```

The former will only work on 2.3 but it's still good to have now that it's supported.

**Comment by mattr-** [comment]
I guess we're not mutating any of these string literals we create anywhere?

**Comment by envygeeks** [comment]
@mattr- We do mutate a lot of strings but I don't think we do anything that would prevent this, this would mostly benefit our usage of string keys everywhere, in one of our apps it dropped the GC time drastically but that was a huge app so the scale will be way smaller.
