### ISSUE TITLE
add more data types

### ISSUE THREAD

**Issue by Lewiscowles1986** [jekyll/jekyll#4136]
It would be really nice if we could use SQLite data, and have more query capability.

It would also be really nice to have XML data. 

Adding these two would add the possibility of using jekyll as a converter for data, which is really cool. I've already started using Jekyll to generate data-sets from CSV->SQL, and it's really cool; if it just supported more formats going in, I'm sure it could be an amazing data visualization and transformation tool. (think static diagrams output in SVG etc)

**Comment by envygeeks** [comment]
I'm gonna be honest, this is way out of scope for Jekyll. /cc @jekyll/core

**Comment by Lewiscowles1986** [comment]
okay, I just wanted to put it out there, see how what other people think, rather than just close, can we leave it, and see if anything happens, otherwise we are literally killing the idea

**Comment by envygeeks** [comment]
It'll probably get closed after a consensus is made by the team to decide whether or not we want to support it and whether or not it's out of scope, we are a blogging framework after all and something like that puts us way out of our scope.

**Comment by Lewiscowles1986** [comment]
Thanks @envygeeks you are probably right, I just think Jekyll is more powerful than just blogging (a lot of sites use it for documentation, and it has great applicability for that, or github would not use Jekyll for GitHub Pages)
