### ISSUE TITLE
I can't make that auto regenerate files when save

### ISSUE THREAD

**Issue by rubenmedios** [jekyll/jekyll#4148]
I try all, including "jekyll serve --force_polling" and more, but when i run, only generate one time, after this i need use ctrl + c and run the jekyll serve --force_polling or jekyll serve -w or whathever again to regenerate the site. 

This happens two day ago, before the auto regenerate system work well.

Look the code:
**************************************************************
$ jekyll serve --force_polling
Configuration file: C:/Users/Ruben Rojas/Desktop/designer-portfolio/_config.yml
            Source: C:/Users/Ruben Rojas/Desktop/designer-portfolio
       Destination: C:/Users/Ruben Rojas/Desktop/designer-portfolio/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.776 seconds.
 Auto-regeneration: enabled for 'C:/Users/Ruben Rojas/Desktop/designer-portfolio'
Configuration file: C:/Users/Ruben Rojas/Desktop/designer-portfolio/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2015-11-16 23:32:15

**Comment by parkr** [comment]
Can you run this with `LISTEN_GEN_DEBUGGING=1` and `--verbose`? It looks like it sees the save, but it can't finish. Are you using plugins?

**Comment by rubenmedios** [comment]
I do not use plugins, unless you already have the Jekyll default. I have no idea how to run that "LISTEN_GEN_DEBUGGING = 1" command :/

**Comment by rubenmedios** [comment]
i ran the command --verbose and:

jekyll serve --verbose
  Logging at level: debug
Configuration file: C:/Users/Ruben Rojas/Desktop/designer-portfolio/_config.yml
            Source: C:/Users/Ruben Rojas/Desktop/designer-portfolio
       Destination: C:/Users/Ruben Rojas/Desktop/designer-portfolio/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       EntryFilter: excluded?(/default.html) ==> false
       EntryFilter: excluded?(/page.html) ==> false
       EntryFilter: excluded?(/post.html) ==> false
       EntryFilter: excluded?(/about.md) ==> false
       EntryFilter: excluded?(/articles.html) ==> false
       EntryFilter: excluded?(/css) ==> false
       EntryFilter: excluded?(/feed.xml) ==> false
       EntryFilter: excluded?(/hire-me.html) ==> false
       EntryFilter: excluded?(/images) ==> false
       EntryFilter: excluded?(/index.html) ==> false
       EntryFilter: excluded?(/work.html) ==> false
       EntryFilter: excluded?(/_posts/blog) ==> false
       EntryFilter: excluded?(/_posts/blog/2015-11-11-quas-nempe.markdown) ==> false
       EntryFilter: excluded?(/_posts/blog/2015-11-12-titulum-diros-sermonibus.markdown) ==> false
       EntryFilter: excluded?(/_posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown) ==> false
       EntryFilter: excluded?(/_posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown) ==> false
       EntryFilter: excluded?(/_posts/blog/2015-11-15-et-bella.markdown) ==> false
       EntryFilter: excluded?(/_posts/project) ==> false
       EntryFilter: excluded?(/_posts/project/2015-11-11-quas-nempe.markdown) ==> false
       EntryFilter: excluded?(/_posts/project/2015-11-12-titulum-diros-sermonibus.markdown) ==> false
       EntryFilter: excluded?(/_posts/project/2015-11-15-et-bella.markdown) ==> false
           Reading: _posts/blog/2015-11-11-quas-nempe.markdown
           Reading: _posts/blog/2015-11-12-titulum-diros-sermonibus.markdown
           Reading: _posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown
           Reading: _posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown
           Reading: _posts/blog/2015-11-15-et-bella.markdown
           Reading: _posts/project/2015-11-11-quas-nempe.markdown
           Reading: _posts/project/2015-11-12-titulum-diros-sermonibus.markdown
           Reading: _posts/project/2015-11-15-et-bella.markdown
       EntryFilter: excluded?(/css/main.scss) ==> false
       EntryFilter: excluded?(/images/banner.jpg) ==> false
       EntryFilter: excluded?(/images/bikes.jpg) ==> false
       EntryFilter: excluded?(/images/bridge.jpg) ==> false
       EntryFilter: excluded?(/images/project.png) ==> false
       EntryFilter: excluded?(/images/road.jpg) ==> false
       EntryFilter: excluded?(/images/Thumbs.db) ==> false
       EntryFilter: excluded?(/images/wing.jpg) ==> false
         Rendering: _posts/blog/2015-11-11-quas-nempe.markdown
         Rendering: _posts/blog/2015-11-11-quas-nempe.markdown
  Pre-Render Hooks: _posts/blog/2015-11-11-quas-nempe.markdown
  Rendering Liquid: _posts/blog/2015-11-11-quas-nempe.markdown
  Rendering Markup: _posts/blog/2015-11-11-quas-nempe.markdown
  Pre-Render Hooks: _posts/blog/2015-11-11-quas-nempe.markdown
  Rendering Liquid: _posts/blog/2015-11-11-quas-nempe.markdown
  Rendering Markup: _posts/blog/2015-11-11-quas-nempe.markdown
  Rendering Layout: _posts/blog/2015-11-11-quas-nempe.markdown
         Rendering: _posts/project/2015-11-11-quas-nempe.markdown
         Rendering: _posts/project/2015-11-11-quas-nempe.markdown
  Pre-Render Hooks: _posts/project/2015-11-11-quas-nempe.markdown
  Rendering Liquid: _posts/project/2015-11-11-quas-nempe.markdown
  Rendering Markup: _posts/project/2015-11-11-quas-nempe.markdown
  Pre-Render Hooks: _posts/project/2015-11-11-quas-nempe.markdown
  Rendering Liquid: _posts/project/2015-11-11-quas-nempe.markdown
  Rendering Markup: _posts/project/2015-11-11-quas-nempe.markdown
  Rendering Layout: _posts/project/2015-11-11-quas-nempe.markdown
         Rendering: _posts/blog/2015-11-12-titulum-diros-sermonibus.markdown
         Rendering: _posts/blog/2015-11-12-titulum-diros-sermonibus.markdown
  Pre-Render Hooks: _posts/blog/2015-11-12-titulum-diros-sermonibus.markdown
  Rendering Liquid: _posts/blog/2015-11-12-titulum-diros-sermonibus.markdown
  Rendering Markup: _posts/blog/2015-11-12-titulum-diros-sermonibus.markdown
  Pre-Render Hooks: _posts/blog/2015-11-12-titulum-diros-sermonibus.markdown
  Rendering Liquid: _posts/blog/2015-11-12-titulum-diros-sermonibus.markdown
  Rendering Markup: _posts/blog/2015-11-12-titulum-diros-sermonibus.markdown
  Rendering Layout: _posts/blog/2015-11-12-titulum-diros-sermonibus.markdown
         Rendering: _posts/project/2015-11-12-titulum-diros-sermonibus.markdown
         Rendering: _posts/project/2015-11-12-titulum-diros-sermonibus.markdown
  Pre-Render Hooks: _posts/project/2015-11-12-titulum-diros-sermonibus.markdown
  Rendering Liquid: _posts/project/2015-11-12-titulum-diros-sermonibus.markdown
  Rendering Markup: _posts/project/2015-11-12-titulum-diros-sermonibus.markdown
  Pre-Render Hooks: _posts/project/2015-11-12-titulum-diros-sermonibus.markdown
  Rendering Liquid: _posts/project/2015-11-12-titulum-diros-sermonibus.markdown
  Rendering Markup: _posts/project/2015-11-12-titulum-diros-sermonibus.markdown
  Rendering Layout: _posts/project/2015-11-12-titulum-diros-sermonibus.markdown
         Rendering: _posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown
         Rendering: _posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown
  Pre-Render Hooks: _posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown
  Rendering Liquid: _posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown
  Rendering Markup: _posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown
  Pre-Render Hooks: _posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown
  Rendering Liquid: _posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown
  Rendering Markup: _posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown
  Rendering Layout: _posts/blog/2015-11-13-duro-mihi-hoc-egit-gravatum-apium.markdown
         Rendering: _posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown
         Rendering: _posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown
  Pre-Render Hooks: _posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown
  Rendering Liquid: _posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown
  Rendering Markup: _posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown
  Pre-Render Hooks: _posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown
  Rendering Liquid: _posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown
  Rendering Markup: _posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown
  Rendering Layout: _posts/blog/2015-11-14-clamore-o-ramos-submisit.markdown
         Rendering: _posts/blog/2015-11-15-et-bella.markdown
         Rendering: _posts/blog/2015-11-15-et-bella.markdown
  Pre-Render Hooks: _posts/blog/2015-11-15-et-bella.markdown
  Rendering Liquid: _posts/blog/2015-11-15-et-bella.markdown
  Rendering Markup: _posts/blog/2015-11-15-et-bella.markdown
  Pre-Render Hooks: _posts/blog/2015-11-15-et-bella.markdown
  Rendering Liquid: _posts/blog/2015-11-15-et-bella.markdown
  Rendering Markup: _posts/blog/2015-11-15-et-bella.markdown
  Rendering Layout: _posts/blog/2015-11-15-et-bella.markdown
         Rendering: _posts/project/2015-11-15-et-bella.markdown
         Rendering: _posts/project/2015-11-15-et-bella.markdown
  Pre-Render Hooks: _posts/project/2015-11-15-et-bella.markdown
  Rendering Liquid: _posts/project/2015-11-15-et-bella.markdown
  Rendering Markup: _posts/project/2015-11-15-et-bella.markdown
  Pre-Render Hooks: _posts/project/2015-11-15-et-bella.markdown
  Rendering Liquid: _posts/project/2015-11-15-et-bella.markdown
  Rendering Markup: _posts/project/2015-11-15-et-bella.markdown
  Rendering Layout: _posts/project/2015-11-15-et-bella.markdown
         Rendering: about.md
  Pre-Render Hooks: about.md
  Rendering Liquid: about.md
  Rendering Markup: about.md
  Rendering Layout: about.md
  Rendering Layout: about.md
 Post-Render Hooks: about.md
         Rendering: articles.html
  Pre-Render Hooks: articles.html
  Rendering Liquid: articles.html
  Rendering Markup: articles.html
  Rendering Layout: articles.html
 Post-Render Hooks: articles.html
         Rendering: feed.xml
  Pre-Render Hooks: feed.xml
  Rendering Liquid: feed.xml
  Rendering Markup: feed.xml
 Post-Render Hooks: feed.xml
         Rendering: hire-me.html
  Pre-Render Hooks: hire-me.html
  Rendering Liquid: hire-me.html
  Rendering Markup: hire-me.html
  Rendering Layout: hire-me.html
 Post-Render Hooks: hire-me.html
         Rendering: index.html
  Pre-Render Hooks: index.html
  Rendering Liquid: index.html
  Rendering Markup: index.html
  Rendering Layout: index.html
 Post-Render Hooks: index.html
         Rendering: /css/main.scss
  Pre-Render Hooks: /css/main.scss
  Rendering Liquid: /css/main.scss
  Rendering Markup: /css/main.scss
 Post-Render Hooks: /css/main.scss
         Rendering: work.html
  Pre-Render Hooks: work.html
  Rendering Liquid: work.html
  Rendering Markup: work.html
  Rendering Layout: work.html
 Post-Render Hooks: work.html
                    done in 1.031 seconds.
           Watcher: Ignoring (?-mix:_config\.yml)
           Watcher: Ignoring (?-mix:_site)
 Auto-regeneration: enabled for 'C:/Users/Ruben Rojas/Desktop/designer-portfolio'
  Logging at level: debug
Configuration file: C:/Users/Ruben Rojas/Desktop/designer-portfolio/_config.yml
[2015-11-17 09:52:56] INFO  WEBrick 1.3.1
[2015-11-17 09:52:56] INFO  ruby 2.2.3 (2015-08-18) [i386-mingw32]
[2015-11-17 09:52:56] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
[2015-11-17 09:52:56] DEBUG unmount .
[2015-11-17 09:52:56] DEBUG #<Class:0x31e4038> is mounted on /designer-portfolio.
    Server address: http://127.0.0.1:4000/designer-portfolio/
[2015-11-17 09:52:56] INFO  WEBrick::HTTPServer#start: pid=5636 port=4000
  Server running... press ctrl-c to stop.

**Comment by envygeeks** [comment]
What he asked you to run is not a command,  Put it before the jekyll command, it's an environment variable.

**Comment by rubenmedios** [comment]
watch this video, I have documented on video and my problem so they can see what they tell me is happening

https://youtu.be/oiBJ-5BLOpo

**Comment by envygeeks** [comment]
What is the content of _site/about.html (or _site/about/index.html) after it claims it regenerates?

**Comment by rubenmedios** [comment]
The content of the page About generates full after he is regenerated, the problem s that pages are not generated is that need to close the process with "Ctrl + C" and then again run the "Jekyll serve" command to that generate, several days ago did not need to do that, whenever slvaba a document is generated without leaving the proecso and rerun Jekyll server with "Jekyll serve"

**Comment by envygeeks** [comment]
Please, tell me what the content of _site/about.html is after it generates.  Is the content in the source page updated? That's all I need to know.

**Comment by rubenmedios** [comment]
The content is the same, this work well, this not the problem, the problem is that i need to close the process in the console with **ctrl + c** and then **jekyll serve** to the page or site auto regenerates, but the content after this is the same that markdown after this manual process.

**Comment by parkr** [comment]
I'm having trouble understanding your comments. I think you're saying: `jekyll serve` doesn't regenerate when I save a file. Run `SET LISTEN_GEM_DEBUGGING=1` then run `jekyll serve` and see what output you get.

You should see Jekyll write `Regenerating` to the console with some information about how many files were changed and how long it took to regenerate.

**Comment by rubenmedios** [comment]
When i put the comand in my cmd windows results this

$ SET LISTEN_GEM_DEBUGGING=1
bash: SET: command not found

**Comment by rubenmedios** [comment]
parkr, i have a problem with auto regenerate each time that i save, i need to close the process with **ctrl + c** and then run **jekyll serve** again to regenerate the files. This is my problem

**Comment by joernba** [comment]
Hi, I have the exact same problem, but on 10.11.1. So, I guess, it's not a Windows specific problem. 
When I put LISTEN_GEM_DEBUGGING=1 before the jekyll serve command I get this after saving a file (i.e. some sass file):

```
Configuration file: /Users/joern/Sites/personal/joern.im-v2.1/_config.yml
            Source: /Users/joern/Sites/personal/joern.im-v2.1
       Destination: /Users/joern/Sites/personal/joern.im-v2.1/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.34 seconds.
I, [2015-11-19T09:08:34.966800 #46776]  INFO -- : Listen loglevel set to: 1
I, [2015-11-19T09:08:34.966862 #46776]  INFO -- : Listen version: 3.0.4
I, [2015-11-19T09:08:35.077816 #46776]  INFO -- : Record.build(): 0.10121 seconds
 Auto-regeneration: enabled for '/Users/joern/Sites/personal/joern.im-v2.1'
Configuration file: /Users/joern/Sites/personal/joern.im-v2.1/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2015-11-19 09:09:13
```

With --verbose rendering stops after the first .md file (after it checks EntryFilter, I'll omit the checks here): 

```
EntryFilter: excluded?(/works/_posts/2015-06-29-draga-aurel.markdown) ==> false
       EntryFilter: excluded?(/works/_posts/2015-06-29-surya.markdown) ==> false
           Reading: works/_posts/2015-06-29-draga-aurel.markdown
           Reading: works/_posts/2015-06-29-surya.markdown
         Rendering: works/_posts/2015-06-29-draga-aurel.markdown
         Rendering: works/_posts/2015-06-29-draga-aurel.markdown
  Pre-Render Hooks: works/_posts/2015-06-29-draga-aurel.markdown
  Rendering Liquid: works/_posts/2015-06-29-draga-aurel.markdown
  Rendering Markup: works/_posts/2015-06-29-draga-aurel.markdown
```

Jekyll just stops there. I tried the same thing with a newly created Jekyll project and it doesn't work either. 
ruby 2.2.1p85
jekyll 3.0.1

Thanks.
Joern

**Comment by parkr** [comment]
What's inside your `_config.yml` file? Do you have anything in `exclude`?

**Comment by rubenmedios** [comment]
In my config.yml:

# Site settings
title: Design Portfolio
email: ruben.media@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer, specializing in Jekyll,
  HTML, CSS and Javascript.
baseurl: "/designer-portfolio" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: rubenmedios
github_username:  rubenmedios
google_username:  rubenmedios

permalink: /:categories/:title 

links:
  - title: about
    titledesc: pepe es lo mio
    url: /about
  - title: work
    titledesc: pepe es lo mio
    url: /work
  - title: articles
    titledesc: pepe es lo mio
    url: /articles
  - title: hire me
    titledesc: pepe es lo mio
    url: /hire-me

# Build settings
markdown: kramdown

**Comment by parkr** [comment]
This looks to me like a Listen bug. @e2, would you be able to take a look at the above?

**Comment by e2** [comment]
@parkr - works flawlessly for me (but on Linux). I tried with the about page on a new project, but everything works fine (save file ->  refresh -> page changed).

I tested on Jekyll 3.0.1 and Listen 3.0.5 (shouldn't be a difference).

Based on the video, it looks like a Jekyll failure, because it never shows that `site.process` completed.

It never gets to this line:

https://github.com/jekyll/jekyll-watch/blob/6382b3a1e33d024b9ea2c2371efe780d50cef9e7/lib/jekyll/watcher.rb#L45

E.g. the video shows:

```
Regenerating: 1 file(s) changed at 2015-11-17 10:08:00
```

while on my setup I see:

```
Regenerating: 1 file(s) changed at 2015-11-20 00:05:08 ...done in 0.13747286 seconds.
```

Correct me if I'm wrong, but I believe the "done" part should appear always (it's a warning).

Also, the version of jekyll-watch may be relevant (just guessing).

Perhaps there's a broken plugin autoloaded? Or bad/outdated versions of something?

I'd suggest using a `Gemfile` and attaching `Gemfile.lock` (to make sure).

**Comment by joernba** [comment]
Just a quick note: I reinstalled Jekyll, Jekyll-watch, Listen, Kramdown and Safe-yaml and now it seems to work again. The versions didn't change, just reinstalled. I guess, you're right, @e2. It was a bad installation of one of the gems. Thanks.

**Comment by rubenmedios** [comment]
maybe the reinstall repair the problem. somebody can help me with this? how to uninstall and reinstall?

**Comment by rubenmedios** [comment]
C:\Users\Ruben Rojas>gem uninstall jekyll

You have requested to uninstall the gem:
        jekyll-3.0.1

jekyll-gist-1.3.5 depends on jekyll (>= 2.0, development)
jekyll-sitemap-0.9.0 depends on jekyll (>= 2.0, development)
I try this:

jekyll-watch-1.3.0 depends on jekyll (>= 2.0, development)
octopress-hooks-2.6.1 depends on jekyll (>= 2.0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Remove executables:
        jekyll

in addition to the gem? [Yn]  y
Removing jekyll
Successfully uninstalled jekyll-3.0.1

and then install

C:\Users\Ruben Rojas>gem install jekyll
Fetching: jekyll-3.0.1.gem (100%)
Successfully installed jekyll-3.0.1
Parsing documentation for jekyll-3.0.1
Installing ri documentation for jekyll-3.0.1
Done installing documentation for jekyll after 8 seconds
1 gem installed

when i try again is the same, like e2 say above is a listen problem, look this:

C:\Users\Ruben Rojas\Desktop\designer-portfolio>jekyll serve
Configuration file: C:/Users/Ruben Rojas/Desktop/designer-portfolio/_config.yml
            Source: C:/Users/Ruben Rojas/Desktop/designer-portfolio
       Destination: C:/Users/Ruben Rojas/Desktop/designer-portfolio/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 6.203 seconds.
 Auto-regeneration: enabled for 'C:/Users/Ruben Rojas/Desktop/designer-portfolio'
Configuration file: C:/Users/Ruben Rojas/Desktop/designer-portfolio/_config.yml
    Server address: http://127.0.0.1:4000/designer-portfolio/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2015-11-20 15:01:41

Do not show the time **...done in 0.13747286 seconds** when serve and generate the files

**Comment by rubenmedios** [comment]
My versions

jekyll 3.0.1
ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]

**Comment by rubenmedios** [comment]
I can`t understand about this:

**I'd suggest using a Gemfile and attaching Gemfile.lock (to make sure).**

I have no idea how make this

**Comment by envygeeks** [comment]
See: https://bundler.io

**Comment by rubenmedios** [comment]
![captura de pantalla de 2015-11-21 16 17 57](https://cloud.githubusercontent.com/assets/1053982/11320479/820ddf12-906b-11e5-89f4-e87d32eac9c5.png)

I need to reset or uninstall for new install? In elementary OS run well and when save regenerates the site, i need to correct this in my windows

Regarding the Gemfile I have no idea who put in the bundle, I surrender to that, I need is to know how to uninstall and reinstall everything on windows, please if anyone can help me I appreciate it very much

**Comment by e2** [comment]
@rubenmedios - try this:

1) `gem update jekyll`
2) `jekyll new pepe`


3) Then in the folder `pepe` create a file named `Gemfile` with the following:
```ruby
gem 'jekyll'
gem 'jekyll-watch'
gem 'listen'
```
4) `cd pepe1`
5) `bundle update`
6) `bundle jekyll serve -w`

Note: put `bundle` before every ruby/jekyll command.

**Comment by rubenmedios** [comment]
Excuse me for my ignorance, ¿what extension have the Gemfile? is .rb file?

**Comment by rubenmedios** [comment]
Ohhhh thank you very much e2!!! This make work well, bur without bundle in comand. Look the capture and the code here

$  bundle jekyll serve -w
Could not find command "jekyll".

![captura de pantalla 153](https://cloud.githubusercontent.com/assets/1053982/11320617/42447742-9070-11e5-96cf-d19d330bf272.png)

is running again :)

only a question ¿what extension have the Gemfile? I udsed from another project with copy/paste and then put the code of yours in the Gemfile, but i don`t know what extension have the Gemfile files

**Comment by parkr** [comment]
Thanks a lot, @e2 :)

**Comment by facelesspanda** [comment]
shouldn't the bundle commands be more like `bundle exec <command>` ?
