### ISSUE TITLE
is Jekyll having problems with gulp? or is that idk how to config my gulp file

### ISSUE THREAD

**Issue by c-hris** [jekyll/jekyll#4149]
Im using window 10, Jekyll 2.4.0 gulp 3.9.0 npp 2.14.7
When i delete my gulp file, node_modules folder everything is fine with jekyll serve but when i try just running gulp i get a error. 
This is my gulp file

var gulp         = require('gulp');
var sass         = require('gulp-sass');
var browserSync  = require('browser-sync');
var prefix       = require('gulp-autoprefixer');
var cp          = require('child_process');
var plumber      = require('gulp-plumber');
var uglify       = require('gulp-uglify');
var rename       = require("gulp-rename");
var imagemin     = require("gulp-imagemin");
var pngquant     = require('imagemin-pngquant');
gulp.task('jekyll-build', function (done) {
    return cp.spawn('jekyll.bat', ['build'], {stdio: 'inherit'}).on('close', done)
});
gulp.task('jekyll-rebuild', ['jekyll-build'], function () {
    browserSync.reload();
});
gulp.task('sass', function() {
  gulp.src('assets/css/**')
  .pipe(sass({outputStyle: 'compressed'}))
  .pipe(prefix('last 2 versions', '> 1%', 'ie 8', 'Android 2', 'Firefox ESR'))
  .pipe(plumber())
  .pipe(gulp.dest('assets/css'));
});
gulp.task('browser-sync',['jekyll-build'], function() {
  browserSync.init(['assets/css/*.css', 'assets/js/**/*.js', 'index.html'], {
    server: {
      baseDir: '_site'
    }
  });
});
gulp.task('scripts', function() {
  gulp.src('assets/js/*.js')
  .pipe(uglify())
  .pipe(rename({
    dirname: "min",
    suffix: ".min",
  }))
  .pipe(gulp.dest('js'))
});
gulp.task('images', function () {
  return gulp.src('assets/img/*')
  .pipe(imagemin({
    progressive: true,
    svgoPlugins: [{removeViewBox: false}],
    use: [pngquant()]
  }))
  .pipe(gulp.dest('assets/img'));
});
gulp.task('watch', function () {
    gulp.watch('assets/css/**', ['sass']);
    gulp.watch('assets/js/**/*.js', ['scripts'],['jekyll-rebuild']);
    gulp.watch('assets/img/*', ['images'],['jekyll-rebuild']);
    gulp.watch(['*.html', '_layouts/*.html','_includes/*.html', '_posts/*'], ['jekyll-rebuild']);
});
gulp.task('default', ['sass', 'browser-sync', 'scripts', 'images','watch']);

The error that im having is
`$ gulp
[23:17:56] Using gulpfile c:\Users\christian\desktop\site\gulpfile.js
[23:17:56] Starting 'sass'...
[23:17:56] Finished 'sass' after 11 ms
[23:17:56] Starting 'jekyll-build'...
[23:17:56] Starting 'scripts'...
[23:17:56] Finished 'scripts' after 4.93 ms
[23:17:56] Starting 'images'...
[23:17:56] Starting 'watch'...
[23:17:56] Finished 'watch' after 20 ms
[23:17:56] gulp-imagemin: Minified 0 images
[23:17:56] Finished 'images' after 39 ms
Configuration file: c:/Users/christian/desktop/site/_config.yml
            Source: c:/Users/christian/desktop/site
       Destination: c:/Users/christian/desktop/site/_site
      Generating...
jekyll 2.4.0 | Error:  No such file or directory @ rb_sysopen - c:/Users/christi
an/desktop/site/node_modules/gulp/node_modules/gulp-util/node_modules/dateformat
/node_modules/meow/node_modules/normalize-package-data/node_modules/validate-npm
-package-license/node_modules/spdx-correct/node_modules/spdx-license-ids/package
.json
[23:17:59] 'jekyll-build' errored after 2.43 s
[23:17:59] Error: 1
    at formatError (c:\Users\christian\AppData\Roaming\npm\node_modules\gulp\bin
\gulp.js:169:10)
    at Gulp.<anonymous> (c:\Users\christian\AppData\Roaming\npm\node_modules\gul
p\bin\gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (c:\Users\christian\desktop\site\node_mod
ules\gulp\node_modules\orchestrator\index.js:264:8)
    at c:\Users\christian\desktop\site\node_modules\gulp\node_modules\orchestrat
or\index.js:275:23
    at finish (c:\Users\christian\desktop\site\node_modules\gulp\node_modules\or
chestrator\lib\runTask.js:21:8)
    at ChildProcess.cb (c:\Users\christian\desktop\site\node_modules\gulp\node_m
odules\orchestrator\lib\runTask.js:29:3)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)`

**Comment by parkr** [comment]
Add `node_modules` to `ignore` in `_config.yml`. That should fix it based on the error above.

**Comment by c-hris** [comment]
Thanks I add `exclude:   - node_modules` and it work! Thanks!!!!!
