### ISSUE TITLE
jekyll 3.0.1 incorrect css link

### ISSUE THREAD

**Issue by pmadhikar** [jekyll/jekyll#4158]
Running `jekyll build` puts the css link at `/css/main.css` instead of `css/main.css`.

**Comment by parkr** [comment]
> Running jekyll build puts the css link at /css/main.css instead of css/main.css.

Huh? Where is this? Is this when you run `jekyll new`?

**Comment by pmadhikar** [comment]
Sorry, I'm new at this. Whatever I did is below. 

The layout is completely screwed up after generating the static webpages:

    jekyll new test
    cd test
    jekyll build
    chrome _site/index.html 

Chrome reports `Failed to load resource: net::ERR_FILE_NOT_FOUND file:///css/main.css` 

This is because in the header of the html file

      <link rel="stylesheet" href="/css/main.css">

should be

     <link rel="stylesheet" href="css/main.css">

**Comment by envygeeks** [comment]
@pmadhikar This is a non-issue, if you would like to browse your site and generate it run `jekyll serve`, we do not directly support loading index.html into the browser.
