### ISSUE TITLE
Change in subdirectory / category behavior in 3.0.1 is breaking

### ISSUE THREAD

**Issue by mshick** [jekyll/jekyll#4159]
I'd like to point out that this commit: https://github.com/jekyll/jekyll/commit/db6103bdeeccd46d97fa96319d724c6e2e19bbc3 represents a larger change, and would request it either be modified or, well, I'm not sure, at least be documented as a major / breaking change?

The change in behavior might result in people (me) needing to re-architect projects. I opted for an approach where subdirectories of a root-level `_posts` represented all the changing / user-updatable content on my site, and I scoped their permissions accordingly. 

I would now need to place `_posts` directories throughout my tree to get similar behavior.

In an ideal scenario, I'd ask that the logic be modified to treat the root-level `_posts` differently, and allow subdirectories to define categories (e.g., `if directory has no public superdirectory then add directory to categories`)

**Comment by mshick** [comment]
Thanks @parkr that all makes sense. 

I started development on 2.5, and upgraded to an early 3.0rc since the project is still under active dev. It may be that I only started down the categories path after that upgrade, though I could swear it was working in 2.5... Anyway, thanks for the code-snippet. Just getting into the hooks and they certainly seem useful.

**Comment by parkr** [comment]
@mshick Well, sorry for the frustration and thanks for the report!
