### ISSUE TITLE
Liquid raising SASS syntax error

### ISSUE THREAD

**Issue by charliesneath** [jekyll/jekyll#4161]
I'm using `jekyll-assets` to process image and css files.

The first lines of my `main.scss` file are as follows:

```
@charset "utf-8";
@import 'fonts';
@import 'bourbon/bourbon';
@import 'neat/neat';
...
```

The main.scss file is in `_assets/css` and being included in head.html using `{% stylesheet main %}`.

I'm getting the following error when building my site.

`Liquid Exception: Invalid CSS after "@charset "utf-8"": expected "{", was ";" (in /Users/charlie/GitHub/jekyll-test/_assets/css/main.scss:4) in _includes/head.html, included in _layouts/default.html`

Is it possible to resolve this?

I also have this issue outstanding here: https://github.com/jekyll/jekyll-assets/issues/206.

**Comment by envygeeks** [comment]
Jekyll does not process your `jekyll-assets` in `_assets/`  This is not a Jekyll bug... UNLESS you have `---\n--- at the top of your file and even then it shouldn't and if it does then that is a bug in `jekyll-assets`.

The upstream you are looking for is Sprockets.  Not Jekyll.

**Comment by charliesneath** [comment]
> Jekyll does not process your jekyll-assets in _assets/

That's what I needed to know, thanks.

**Comment by charliesneath** [comment]
This means that any CSS that requires Liquid processing should live outside `_assets/`, correct?

That works out because the SASS partials can be treated as assets, but can still be included in the main CSS file, which pulls everything in as long as the `sass_dir` is updated in config ([referenced here](http://jekyllrb.com/docs/assets/#sassscss)).

**Comment by charliesneath** [comment]
That said, if `main.scss` is in `/css` and `/css` is added as a `source` for jekyll-assets, does that make `main.scss` available both for Liquid processing and jekyll-asset processing?

**Comment by envygeeks** [comment]
No, because Jekyll will write it to `/css` and we will write it to `/assets`. And if you tell us to use the `/css` prefix then we will assert ourselves over Jekyll and overwrite anything it writes because we operate after Jekyll and we operate independent of Jekyll.

Jekyll simply initializes us with it's instance, after that we process independently.

**Comment by charliesneath** [comment]
All makes sense, thanks for the clarification.

**Comment by envygeeks** [comment]
@charliesneath please refile a ticket on jekyll-assets, I've already started the wip for 2.1 and this is a feature of that and 2.1 will be released very soon so if you open a ticket for liquid processing of assets themselves you can get pinged when it's in beta.

**Comment by charliesneath** [comment]
@envygeeks Sure: https://github.com/jekyll/jekyll-assets/issues/208.

Does Liquid processing of assets include SASS processing? 

Specifically, will that allow for the `main.scss` file to `@import` CSS partials with helper functions, e.g. `background: url(asset_path('background.jpg');`?

**Comment by envygeeks** [comment]
Can you provide an actual SCSS example of what you are trying to achieve in that ticket please.

**Comment by charliesneath** [comment]
Done.
