### ISSUE TITLE
Can't install jekyll properly, it says gem installed successfully, but throws a not found error on command

### ISSUE THREAD

**Issue by lastnoob** [jekyll/jekyll#4162]
![image](https://cloud.githubusercontent.com/assets/1821091/11258033/223fee48-8e56-11e5-919f-5b82cb96bd4f.png)
You can see it here. I'm trying to install it on a DigitalOcean LEMP stack droplet(nginx).

Any ideas what am I doing wrong?

**Comment by parkr** [comment]
Try removing `sudo`. Using sudo will cause problems on most systems, because of differences between the normal and super user environments.
