### ISSUE TITLE
jekyll serve: Sass not converting custom color function

### ISSUE THREAD

**Issue by shaunrfox** [jekyll/jekyll#4164]
I have a few Sass color functions that I typically use. Running `jekyll serve` to serve the site and compile the Sass (SCSS, truly). But it's not converting the function all the way and it's not throwing any errors. Here's what I've got:
**Function and Color definitions**
```
@function tint($color, $percentage) {
  @return mix($color, white, $percentage);
}

$blue: #06668e;
$pale-blue: tint($blue, 50%);
```
---
**SCSS**
```
.thing {
  color: $pale-blue;
}
```
---
**CSS Output**
```
.thing {
  color: tint(#06668e, 50%);
}
```
Obviously, the browser doesn't know what to do with this. 

*Important note:* This function works if written simpler, like this:
```
.thing {
  color: tint($blue, 50%);
}
```
It seems the added complexity of going back up to do the second conversion is where things are breaking.

**Comment by parkr** [comment]
Can you post **actual** vs **expected** output? I don't see a problem yet.

**Comment by envygeeks** [comment]
I think this is an upstream bug unless somehow we are transforming something, does it work when you directly do it with the `sass` or `scss` command?

**Comment by shaunrfox** [comment]
@parkr, @envygeeks :
Thanks for getting back to me so quickly. I need to dig into this further. I think you're probably right about it being upstream. I know I've had it work before, but need to dig into where and why it worked. Thanks.
