### ISSUE TITLE
Jekyll pass on Liquid error

### ISSUE THREAD

**Issue by iBobik** [jekyll/jekyll#4165]
When I put string to liquid condition like:
```
{% if site.data.event.datetime > site.time %}
```
it will print in place of this condition error "Liquid error: comparison of String with Time failed", but Jekyll build finish successfully (without error to stderr).

It makes automated testing in CI almost impossible.

jekyll 3.0.0

**Comment by envygeeks** [comment]
Can you please put that into a repo so that we can clone it and test the case with it?

**Comment by parkr** [comment]
3.0.1 had a fix for a related bug. Please update!

**Comment by iBobik** [comment]
Sorry, fixed.



Jan Pobořil

2015-11-19 10:00 GMT-06:00 Parker Moore <notifications@github.com>:
