### ISSUE TITLE
highlight a line with rouge

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll#4176]
Before upgrading to Jekyll 3.0, I was able to use `{% highlight java hl_lines="2" %}` to highlight a specific line.

This seems to no longer work with 3.0

**Comment by parkr** [comment]
It doesn't look like [rouge supports this feature](https://github.com/jneen/rouge#full-options).

Please set `highlighter: pygments` and install the `pygments.rb` gem to continue using `hl_lines`.

**Comment by parkr** [comment]
Added to upgrading docs, thanks! http://jekyllrb.com/docs/upgrading/2-to-3/#syntax-highlighter-changed
