### ISSUE TITLE
when --verbose is on and future=false (now default), a message should be logged when a post is skipped for publishing

### ISSUE THREAD

**Issue by untra** [jekyll/jekyll#4178]
Minor feature request, title says it all:

If I am running `--verbose` and `--future` is false ([which is now the default](https://github.com/jekyll/jekyll/pull/3892)), I should at least get a message in the verbose logs informing me that a post is being skipped for publishing.

**Comment by untra** [comment]
IMHO, a message should be delivered if a post is skipped for future publishing, whether or not verbose is on. I intend to write a hook to do just this though. 

At the very least though, if I have turned on `--verbose`, and my post has been skipped for publishing, I should see a message in the logs telling me the post was skipped because of the future date.

**Comment by parkr** [comment]
Great idea!

**Comment by envygeeks** [comment]
For verbose it's understandable and was probably an oversight, I agree, we need a fix and I'm sure @jekyll/core will agree, for non-verbose the simple answer should be "no", we don't show you when a unique post is processed when not verbose, why would we show you when a unique post is not processed when not verbose?

**Comment by untra** [comment]
@envygeeks you're right about non-verbose. Still, my application needs a warning for when a blogpost is timestamped in the future and won't be published. Eh, I can write a hook to do just that. Except...

I'm having trouble writing a hook that will leave a warning about posts not being published. Presume I have a post with a future date, and `--future` is false. consider the following hook:
```ruby
Jekyll::Hooks.register :posts, :post_init do |post|
    if post.respond_to?(:date) && post.site.future
      puts post.date
    end
end
```
after running this hook, the printed date on all of the posts is current timestamp. [This makes sense](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/document.rb#L75) considering the date hasn't been loaded in from the frontmatter. Frontmatter is loaded during [`document.read`](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/document.rb#L289), but after reading the document with the future date, it gets [kicked out of the collection by the publisher](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/collection.rb#L61)!

This means I can't write a convenient hook to look for posts with the future set. I can probably write a plugin that `alias_method`s `collection.read` to print my message, but that's a tad hacky.

Consider this a :+1: for a hook for after reading documents.

**Comment by envygeeks** [comment]
I thought we had processing hooks?

**Comment by untra** [comment]
I was looking [here](http://jekyllrb.com/docs/plugins/#hooks) for whatever hooks were available.
