### ISSUE TITLE
Front matter not inherited

### ISSUE THREAD

**Issue by cornae** [jekyll/jekyll#4185]
If I have a page '/test.html' which has the following front matter:

    ---
    layout: landing-page
    --- 

and '/_layouts/landing-page looks like this:

    ---
    layout: shell
    application: foo
    --- 

and '_layouts/shell.html looks like this:

    <p>{{ page.application }}</p>

Then the HTML will — as expected — output `<p>foo</p>. However if test.html were not test.html but /_posts/2015-11-25-test.md, then the value of `application:` is not outputted. If I put `application: foo` in the front matter of the post itself, then it is passed through. However I don't want to have this variable in every post. 

If I render the same project with Jekyll 2.5.x, then there is no issue. Only with 3.0.x.

**Comment by parkr** [comment]
In Jekyll 3, this has been changed to avoid confusion. Please access with `{{ layout.application }}`. Thanks!

**Comment by cornae** [comment]
Thanks!
