### ISSUE TITLE
Hash.map doesn't work

### ISSUE THREAD

**Issue by victorhurdugaci** [jekyll/jekyll#4186]
I have this in a template:

```
{% assign X = Hash["a" => [100,101,102], "b" => [200, 201, 202, 203], "c" => [300]] %}
{% assign Y = X.map { |a, b| a } %}
{{ Y | inspect }}
```

The result is `nil`. I was expecting `["a", "b", "c"]`.

I'm quite new to Jekyll/Ruby so I'm not sure if this is just my code or an actual bug. The code seems to work fine in `irb`.

- Jekyll 3.0.1
- Ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

**Comment by parkr** [comment]
What does `{{ X | inspect }}` output?

**Comment by super-ala** [comment]
what s  this  ???how use~~~~~

2015-11-26 7:16 GMT+08:00, Victor Hurdugaci <notifications@github.com>:

**Comment by victorhurdugaci** [comment]
@parkr the output is `nil`

**Comment by parkr** [comment]
> the output is nil

Just as I thought. Liquid doesn't allow you to create arbitrary data structures like this. It uses a very simply syntax which does not allow anything but simple numbers and strings to be declared inside the templates themselves – "complex" data structures like hashes can be created in Ruby and passed to the template as variables but that's the extent to which you can do things like this.

More info here: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers

**Comment by victorhurdugaci** [comment]
Make sense. Thanks!
