### ISSUE TITLE
Title not working as expected / documented in collections not using dates in their filenames

### ISSUE THREAD

**Issue by jeromecoupe** [jekyll/jekyll#4188]
If I create a collection named "portfolio" and use dates in my filenames like `2015-11-26-my-first-post.md` but do not set a title variable in the file YAML front-matter.

A `title` variable is available in Liquid. For example when doing this in Liquid, everything works as expected.

```liquid
{% for item in site.portfolio %}
  {% if forloop.first %}<ul>{% endif %}
    <li>{{ item.date }}  {{ item.title }}</li>
  {% if forloop.last %}</ul>{% endif %}
{% endfor %}
```

output

```html
<ul>
    <li>2015-11-26 00:00:00 +0100  My First Post</li>
</ul>
```

However, if I remove the date from the filename like so `my-first-post.md`, the `title` variable outputs nothing, although [the doc for collections](http://jekyllrb.com/docs/collections/) states that 

> If the document does not define a title in its front matter, this is equivalent to name.

Is this expected behaviour ?

**Comment by rebornix** [comment]
IMO Jekyll shouldn't eat the slug of dateless file in collection, but from related test case below 

```
  Scenario: Sort by relative_path
    Given I have an "index.html" page that contains "Collections: {% assign methods = site.methods | sort: 'relative_path' %}{% for method in methods %}{{ method.title }}, {% endfor %}"
    And I have fixture collections
    And I have a "_config.yml" file with content:
    """
    collections:
    - methods
    """
    When I run jekyll build
    Then the _site directory should exist
    And I should see "Collections: Jekyll.configuration, Jekyll.escape, Jekyll.sanitized_path, Site#generate, , Site#generate," in "_site/index.html"

```

It's saying, if you don't declare `title` in FM, this property will be empty. This piece of code is introduced in PR #2345 . So I'm not sure whether it's expected or a test issue. 

If expected behaviour is using the filename as the title, @parkr you can give it to me, I already have a fix on my local machine :walking: .

**Comment by jeromecoupe** [comment]
Thanks for coming back to me.

I was simply not expecting the behaviour to change from a file with a date to a dateless one in collections. Outputting the title from the filename just as it does when there is a date in the filename would seem more logical to me.

Whatever the expected behaviour is, it should be consistent between filenames with dates and filenames without dates IMHO.

**Comment by parkr** [comment]
@rebornix PR it up!
