### ISSUE TITLE
Jekyll Serve just generating, no actual server

### ISSUE THREAD

**Issue by Fluidbyte** [jekyll/jekyll#4201]
I'm using Jekyll 2.1.1 with Ruby 2.0.0 (on Ubuntu 15.04), when I try to run `jekyll serve` it builds the site but does not run the service. I don't have anything running on `4000`. Not really sure what's going on since it doesn't throw any errors:

```
$ jekyll serve
Configuration file: /home/fluidbyte/workspace/blog/_config.yml
Building site: /home/fluidbyte/workspace/blog -> serve
Successfully generated site: /home/fluidbyte/workspace/blog -> serve
```

**Comment by envygeeks** [comment]
Please update your Jekyll to at least 2.5.3 and try it again.

**Comment by Fluidbyte** [comment]
Same thing with 2.5.3

**Comment by parkr** [comment]
@Fluidbyte The serving code forks. Does `Process.fork` work for you in an IRB shell?

```irb
=> Process.fork { puts "hi" }
```

**Comment by Fluidbyte** [comment]
Yep, `Process.fork` works fine.

**Comment by envygeeks** [comment]
I'm just curious, I don't know if it will lead anywhere but can you post the output with `--verbose` flag?

**Comment by Fluidbyte** [comment]
tells me it's an invalid option:

```
$ jekyll serve --verbose
/usr/bin/jekyll:137:in `<main>': invalid option: --verbose (OptionParser::InvalidOption)
```

**Comment by Fluidbyte** [comment]
I just tried manually starting the server:

```
$ jekyll server 4000
Configuration file: none
Building site: server -> 4000
Error reading file /home/fluidbyte/workspace/blog/_layouts/default.html: No such file or directory - /home/fluidbyte/workspace/blog/server/home/fluidbyte/workspace/blog/_layouts/default.html 
Error reading file /home/fluidbyte/workspace/blog/_layouts/post.html: No such file or directory - /home/fluidbyte/workspace/blog/server/home/fluidbyte/workspace/blog/_layouts/post.html 
Error reading file /home/fluidbyte/workspace/blog/_layouts/page.html: No such file or directory - /home/fluidbyte/workspace/blog/server/home/fluidbyte/workspace/blog/_layouts/page.html 
/usr/bin/jekyll:251:in `rescue in <main>': uninitialized constant Jekyll::FatalException (NameError)
        from /usr/bin/jekyll:249:in `<main>'
```

Is there a way to prevent the double-pathing locally?

**Comment by parkr** [comment]
@Fluidbyte Can you please use Jekyll 2.5.3 at least? The output above is from `jekyll` v0.12.1, which is a _very_ old version. Thanks!

**Comment by Fluidbyte** [comment]
I don't have `0.12.1` installed, version check gives me this:

```
$ jekyll -v
Jekyll 2.5.3
```

**Comment by parkr** [comment]
@Fluidbyte Interesting. The output in all your comments above are not consistent with Jekyll 2.x and above. It should look different. What is the value of `which jekyll`? What do you see when you open that file?

To ensure you have Jekyll 2.x, please run:

```console
$ mkdir jekyll-4201
$ cd jekyll-4201
$ echo -e 'source "rubygems.org"\n\ngem "jekyll", "~> 2.5"' > Gemfile
$ bundle install
$ bundle exec jekyll serve -s <your-site-source>
```

And see what happens then.

**Comment by Fluidbyte** [comment]
when I run `which jekyll` I get back `/usr/local/bin/jekyll`, which looks like this:

```
$ cat /usr/local/bin/jekyll
#!/usr/local/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'jekyll' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/
    version = $1
    ARGV.shift
  end
end

gem 'jekyll', version
load Gem.bin_path('jekyll', 'jekyll', version)
```

When I tried your suggested steps for Jekyll 2.x I get this:

```
bundle install
/usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/bin/bundle:7:in `<main>'
```

**Comment by parkr** [comment]
Run `gem install bundler`.

**Comment by Fluidbyte** [comment]
Got this:

```
$ jekyll serve
Configuration file: /home/fluidbyte/workspace/blog/_config.yml
Building site: /home/fluidbyte/workspace/blog -> serve
       Deprecation: Collection#map should be called on the #docs array directly.
                    Called by /home/fluidbyte/workspace/blog/_plugins/rssgenerator.rb:46:in `block in generate'.
       Deprecation: Collection#count should be called on the #docs array directly.
                    Called by /home/fluidbyte/workspace/blog/_plugins/rssgenerator.rb:49:in `rescue in block in generate'.
       Deprecation: Collection#reverse should be called on the #docs array directly.
                    Called by /home/fluidbyte/workspace/blog/_plugins/rssgenerator.rb:51:in `block in generate'.
       Deprecation: Document#title is now a key in the #data hash.
                    Called by /home/fluidbyte/workspace/blog/_plugins/rssgenerator.rb:53:in `block (3 levels) in generate'.
       Deprecation: Document#excerpt is now a key in the #data hash.
                    Called by /home/fluidbyte/workspace/blog/_plugins/rssgenerator.rb:55:in `block (3 levels) in generate'.
/usr/bin/jekyll:251:in `rescue in <main>': uninitialized constant Jekyll::FatalException (NameError)
        from /usr/bin/jekyll:249:in `<main>'
```

**Comment by envygeeks** [comment]
@Fluidbyte from your paths is it safe to assume you use Linux?

**Comment by Fluidbyte** [comment]
Yup, Ubuntu 15.04.

**Comment by envygeeks** [comment]
```
sudo gem uninstall $(gem list --no-versions)
rm -rf /usr/local/bin/{bundler,bundle,jekyll}
sudo yes | gem update --system
sudo yes | gem update
sudo yes | gem clean
sudo gem installl jekyll
jekyll -v
```

Depending on how you installed with bundler:

```
rm -rf .bundle vendor/bundle Gemfile Gemfile.lock
```

**Comment by parkr** [comment]
Try `gem uninstall jekyll` and remove all but the version you want. Have you ever installed Jekyll through apt-get or similar? Try to use `gem` to install things from RubyGems.org.

**Comment by envygeeks** [comment]
@parkr Ubuntu Vivid has http://packages.ubuntu.com/vivid/jekyll (Jekyll 2.2), AFAIW 0.12 was never released into Universe on Ubuntu (or it's upstream provider Debian.) It went from 0.11 to 1x to 2x and hopefully with Xenial it will go to 3x

**Comment by jsroyal** [comment]
jsrathore@jsrathore:~$ sudo gem install jekyll bundler
[sudo] password for jsrathore: 
Fetching: jekyll-3.4.0.gem (100%)
Successfully installed jekyll-3.4.0
Parsing documentation for jekyll-3.4.0
Installing ri documentation for jekyll-3.4.0
Done installing documentation for jekyll after 4 seconds
Fetching: bundler-1.14.3.gem (100%)
Bundler and RubyGems.org are free for anyone to use, but maintaining them costs more than $25,000 USD every month. Help us cover those costs so that we can keep the gem ecosystem free for everyone: https://ruby.to/support-bundler
Successfully installed bundler-1.14.3
Parsing documentation for bundler-1.14.3
Installing ri documentation for bundler-1.14.3
Done installing documentation for bundler after 10 seconds
2 gems installed
jsrathore@jsrathore:~$ jekyll new my-awesome-site
jekyll 3.4.0 | Error:  uninitialized constant Bundler::Plugin::API::Source

**Comment by parkr** [comment]
@jsroyal If you re-run `jekyll new my-awesome-site --trace`, what do you see?

**Comment by jsroyal** [comment]
$ jekyll new my-awesome-site --trace
/var/lib/gems/2.1.0/gems/bundler-1.14.3/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
	from /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb:124:in `block in full_require_paths'
	from /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb:123:in `map'
	from /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb:123:in `full_require_paths'
	from /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb:60:in `contains_requirable_file?'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:937:in `block in find_in_unresolved'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:937:in `each'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:937:in `find_all'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:937:in `find_in_unresolved'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:80:in `require'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.3/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.3/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb:124:in `block in full_require_paths'
	from /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb:123:in `map'
	from /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb:123:in `full_require_paths'
	from /usr/lib/ruby/2.1.0/rubygems/basic_specification.rb:60:in `contains_requirable_file?'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:937:in `block in find_in_unresolved'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:937:in `each'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:937:in `find_all'
	from /usr/lib/ruby/2.1.0/rubygems/specification.rb:937:in `find_in_unresolved'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:80:in `require'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.3/lib/bundler/rubygems_integration.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /var/lib/gems/2.1.0/gems/bundler-1.14.3/lib/bundler.rb:12:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/lib/jekyll/external.rb:43:in `block in require_with_graceful_fail'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/lib/jekyll/external.rb:40:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/lib/jekyll/external.rb:40:in `require_with_graceful_fail'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/lib/jekyll/commands/new.rb:137:in `bundle_install'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/lib/jekyll/commands/new.rb:129:in `after_install'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/lib/jekyll/commands/new.rb:38:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/lib/jekyll/commands/new.rb:17:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.1.0/gems/jekyll-3.4.0/exe/jekyll:13:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

@parkr
here is the log but I don't understand coz of not familiar with Ruby on rails.
Actually, I want using Jekyll to build Github page so please can you help.
