### ISSUE TITLE
Kramdown Markdown Options (Defaults?) for Github Flavored Markdown (GFM) - Backticks

### ISSUE THREAD

**Issue by geraldb** [jekyll/jekyll#4202]
For your reference: I've put together a simple test page for kramdown using the gfm mode (see [testgfm.html](http://viennahtml.github.io/testgfm.html) and the source [testgfm.md](https://github.com/viennahtml/viennahtml.github.io/blob/master/testgfm.md) using these settings:

    markdown: kramdown
    
    kramdown:
      input: GFM
      hard_wrap: false

It works as expected (if you turn off the hard_wrap) :-)

**Comment by envygeeks** [comment]
Thanks @geraldb I'll make sure it gets into the Kramdown processor rewrite for @jekyll/core to review!

**Comment by benbalter** [comment]
Setting the default as GFM would go a long way to creating a more intuitive experience, especially around code blocks, for folks coming from GitHub issues and markdown elsewhere.

**Comment by benbalter** [comment]
Question: Reading [the docs](http://kramdown.gettalong.org/parser/gfm.html), we may be able to add the defaults below to 3.0.x. The backtick support, I believe, is in addition to tidle support (meaning non-breaking). The only breaking-ish change would be requiring a space after the final `#` in headers. 

```yml
kramdown:
  input: GFM
  hard_wrap: false
```

GitHub Pages could set this as a default when we upgrade to 3.0.x, but it'd be a better user experience if it were in core (and thus work locally), IMHO.

**Comment by envygeeks** [comment]
@benbalter the reason it was set to 3.1 is because it's going into https://github.com/jekyll/jekyll/pull/4109 which is flagged to be let loose around 3.1 and so far most of what's going into 3.1 is just simple stuff like optimization and the odds and ends.

**Comment by benbalter** [comment]
> the reason it was set to 3.1 is because it's going into #4109

Ahh. Had no idea. Makes sense.
