### ISSUE TITLE
Cannot use YAML defined variable in intermediate layout

### ISSUE THREAD

**Issue by bpatra** [jekyll/jekyll#4203]
Hello,
I think I found a bug when upgrading to latest jekyll (3.1.0).
In a blog post, when using a layout (e.g. *postalone.html*) that reuses another layout (e.g. *basic.html*), the YAML variables introduced in this latter layout are not defined in the final resulting blog post.
This is a regression, it worked with jekyll 2.5.3 but fails with 3.1.0.
I have created a small minimal reproduction case [here](https://github.com/bpatra/jekyllintermediatevariableissue) . There is only one blog post and you will see that the `<h1>` tag defined in *basic.html* is not visible in the blog post generated html page.

Thank you

**Comment by parkr** [comment]
In Jekyll 3, layout metadata is available via `layout` in Liquid, instead of overwriting `page`. In this case, use `{{ layout.lang }}`.

Please see: http://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata
