### ISSUE TITLE
empty baseurl

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll#4207]
My `_config.yml` has a value for `baseurl`.

According to the documentation, I can overwrite this value in the command line with `--baseurl`. However, how do I **remove** the value? Meaning I no longer want a baseurl?

I tried `--baseurl` with no value but I get `jekyll 3.0.1 | Error:  undefined method `+' for nil:NilClass`

**Comment by envygeeks** [comment]
Try `--baseurl=''`

**Comment by nasht00** [comment]
```
jekyll 3.0.1 | Error:  Whoops, we can't understand your command.
jekyll 3.0.1 | Error:  invalid option: --baseurl=
```

**Comment by nasht00** [comment]
Sorry - I was using build instead of serve.

Yes your suggestion works.

Which reminds me, are there plans to support `--baseurl` in `build` as well?

**Comment by envygeeks** [comment]
I'll digress those semantics to @jekyll/core

**Comment by parkr** [comment]
> are there plans to support --baseurl in build as well?

No, baseurl exists so the server can mount in such a way to mimic GitHub Pages project pages served at a subdirectory path. The way to override config settings is to use multiple config files.
