### ISSUE TITLE
Twitter timeline embeds not rendering properly 

### ISSUE THREAD

**Issue by enzanki-ars** [jekyll/jekyll#4208]
I am currently in the process of migrating my site to Jekyll, but I have come across one issue preventing me from fully converting. When placing a Twitter timeline embed into my page, the build causes the Twitter embed to fail to render properly. 

Expected: https://enzanki-ars.github.io/
Jekyll: https://enzanki-ars.github.io/betasite/

**Comment by envygeeks** [comment]
This is probably better asked over at https://talk.jekyllrb.com/ unless you think it's a bug in Jekyll.  We do not handle non-bugs (generally) in the ticket system as the forum is much more indexable and the entire community chips in much quicker if they can.

**Comment by enzanki-ars** [comment]
Thank you for the information.  I will post in the forum, but this does seem like a bug as this embed code should not be modified by Jekyll.  
```html
<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/enzanki_ars"
    data-widget-id="612307238137528320">Tweets by @enzanki_ars</a>
    <script>
      ! function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
          p = /^http:/.test(d.location) ? 'http' : 'https';
        if (!d.getElementById(id)) {
          js = d.createElement(s);
          js.id = id;
          js.src = p + "://platform.twitter.com/widgets.js";
          fjs.parentNode.insertBefore(js, fjs);
        }
      }(document, "script", "twitter-wjs");
    </script>
```

**Comment by enzanki-ars** [comment]
Forum Discussion: https://talk.jekyllrb.com/t/twitter-timeline-embeds-not-rendering-properly/1605

**Comment by enzanki-ars** [comment]
Never mind on this issue... I found that there was a missing bracket in the line before messing everything up.  My apologies and thank you for your time!
