### ISSUE TITLE
--verbose should also set LISTEN_GEM_DEBUGGING=1

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#4214]
In addition to enabling logging of WEBrick, `--verbose` should enable logging for listen.

**Comment by rebornix** [comment]
@parkr, seems it's a one line change by adding `ENV["LISTEN_GEM_DEBUGGING"] ||= "1" if options["verbose"]` to [server command processing](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/serve.rb#L35), am I right?

**Comment by envygeeks** [comment]
@rebornix It's a one line change but it's not to be made in the server, that's a bad place to make it, it needs to be made in the logger because this is about logging and logically people will look for logging stuff in the logger, not in the server.
