### ISSUE TITLE
Variable '{{' was not properly terminated with regexp

### ISSUE THREAD

**Issue by wcoder** [jekyll/jekyll#4215]
Hello

I'm using Jekyll on github with gem `github-pages`

I added post [here](https://github.com/wcoder/wcoder.github.io/blob/master/_posts/2014-12-14-how-to-build-forms-with-laravel.md).

After check compile on my local machine get this error:
```
 Liquid Exception: Variable '{{' was not properly terminated with regexp: /\}\}/ in _posts/2014-12-14-how-to-build-forms-with-laravel.md
jekyll 2.4.0 | Error:  Variable '{{' was not properly terminated with regexp: /\}\}/
```

Please help!

**Comment by envygeeks** [comment]
This is an error in your own Liquid page unless you tried to use just `{{` and in that case wrap it in `{% raw %}`  Other than that, 2.4.0 is legacy so it probably won't get updated if there was a resolution... unless you can reproduce it on 3.0.0.

**Comment by wcoder** [comment]
Great, thanks.
