### ISSUE TITLE
Split up the Rakefile

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4218]
The Rakefile as it stands is hard to mantain, hard to understand; this is a bug we should split it up the way large projects normally do; Rails gets one thing right, splitting up the Rakefiles so they are easier to manage and maintain.

**Comment by parkr** [comment]
How would you propose this? I think the rakefile is easy to understand.

**Comment by envygeeks** [comment]
The same way Rails does it, create a rake folder in lib and fill it with `{namespace,task}.rake`  The reason I find it confusing is because it contains lots of logic that isn't grouped, it's pretty large and hard to spot tasks, splitting it up maintains that logic in the file it belongs to making it easier to spot stuff.

**Comment by envygeeks** [comment]
This isn't finished yet, there is still work to be done.

**Comment by envygeeks** [comment]
Sorry, sometimes my bot is mean, this is finished as far as I'm concerned.
