### ISSUE TITLE
Jekyll exported html files without extension

### ISSUE THREAD

**Issue by rubenmedios** [jekyll/jekyll#4222]
Ubuntu distro Elementary OS.
When i made changes and saved markdown files Jekyll regenerates the files in the folder _sites does in html with full content, the content is not a problem, but the files en _site folder haven`t .html extension

**Comment by envygeeks** [comment]
Off-topic correction: Elemenatary OS isn't Ubuntu and it's not an Ubuntu distro ;) that's like saying CentOS is RHEL :P or Fedora is RHEL (well actually that is *almost* sorta true kinda maybe almost probably not but like almost.)

Pleas show us your configuration and run jekyll with the verbose option and post those.  Thanks.

**Comment by rubenmedios** [comment]
rubenrojas@ruben-rojas:~/Github/TuCavaCuarto/sitio-web$ jekyll serve --verbose
Configuration file: /home/rubenrojas/Github/TuCavaCuarto/sitio-web/_config.yml
            Source: /home/rubenrojas/Github/TuCavaCuarto/sitio-web
       Destination: /home/rubenrojas/Github/TuCavaCuarto/sitio-web/_site
      Generating... 
                    done.
 Auto-regeneration: enabled for '/home/rubenrojas/Github/TuCavaCuarto/sitio-web'
Configuration file: /home/rubenrojas/Github/TuCavaCuarto/sitio-web/_config.yml
[2015-12-04 10:37:30] INFO  WEBrick 1.3.1
[2015-12-04 10:37:30] INFO  ruby 1.9.3 (2013-11-22) [i686-linux]
[2015-12-04 10:37:30] DEBUG TCPServer.new(127.0.0.1, 4000)
[2015-12-04 10:37:30] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
[2015-12-04 10:37:30] DEBUG unmount .
[2015-12-04 10:37:30] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on .
    Server address: http://127.0.0.1:4000/
[2015-12-04 10:37:30] INFO  WEBrick::HTTPServer#start: pid=3566 port=4000
  Server running... press ctrl-c to stop.

**Comment by envygeeks** [comment]
Please try it with Jekyll 3.0.0, we do not issue bug fixes for < 3.0.0 anymore.

**Comment by rubenmedios** [comment]
OK, i will try, thanks

**Comment by rubenmedios** [comment]
envygeeks, very thanks to you, already i can work, update ruby and jekyll, the system run well again, here the --verbose 

*************************************

rubenrojas@ruben-rojas:~/Github/TuCavaCuarto/sitio-web$ jekyll serve --verbose
  Logging at level: debug
Configuration file: /home/rubenrojas/Github/TuCavaCuarto/sitio-web/_config.yml
            Source: /home/rubenrojas/Github/TuCavaCuarto/sitio-web
       Destination: /home/rubenrojas/Github/TuCavaCuarto/sitio-web/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       EntryFilter: excluded?(/default.html) ==> false
       EntryFilter: excluded?(/page.html) ==> false
       EntryFilter: excluded?(/post.html) ==> false
       EntryFilter: excluded?(/feed.xml) ==> false
       EntryFilter: excluded?(/css) ==> false
       EntryFilter: excluded?(/accesibilidad.md) ==> false
       EntryFilter: excluded?(/index.html) ==> false
       EntryFilter: excluded?(/about.md) ==> false
       EntryFilter: excluded?(/contacto.md) ==> false
       EntryFilter: excluded?(/unidades.md) ==> false
       EntryFilter: excluded?(/consejos.md) ==> false
       EntryFilter: excluded?(/cavas.md) ==> false
       EntryFilter: excluded?(/_posts/2015-12-02-welcome-to-jekyll.markdown) ==> false
           Reading: _posts/2015-12-02-welcome-to-jekyll.markdown
       EntryFilter: excluded?(/css/main.scss) ==> false
         Rendering: _posts/2015-12-02-welcome-to-jekyll.markdown
         Rendering: _posts/2015-12-02-welcome-to-jekyll.markdown
  Pre-Render Hooks: _posts/2015-12-02-welcome-to-jekyll.markdown
  Rendering Liquid: _posts/2015-12-02-welcome-to-jekyll.markdown
  Rendering Markup: _posts/2015-12-02-welcome-to-jekyll.markdown
  Pre-Render Hooks: _posts/2015-12-02-welcome-to-jekyll.markdown
  Rendering Liquid: _posts/2015-12-02-welcome-to-jekyll.markdown
  Rendering Markup: _posts/2015-12-02-welcome-to-jekyll.markdown
  Rendering Layout: _posts/2015-12-02-welcome-to-jekyll.markdown
         Rendering: about.md
  Pre-Render Hooks: about.md
  Rendering Liquid: about.md
  Rendering Markup: about.md
  Rendering Layout: about.md
  Rendering Layout: about.md
 Post-Render Hooks: about.md
         Rendering: accesibilidad.md
  Pre-Render Hooks: accesibilidad.md
  Rendering Liquid: accesibilidad.md
  Rendering Markup: accesibilidad.md
  Rendering Layout: accesibilidad.md
  Rendering Layout: accesibilidad.md
 Post-Render Hooks: accesibilidad.md
         Rendering: cavas.md
  Pre-Render Hooks: cavas.md
  Rendering Liquid: cavas.md
  Rendering Markup: cavas.md
  Rendering Layout: cavas.md
  Rendering Layout: cavas.md
 Post-Render Hooks: cavas.md
         Rendering: consejos.md
  Pre-Render Hooks: consejos.md
  Rendering Liquid: consejos.md
  Rendering Markup: consejos.md
  Rendering Layout: consejos.md
  Rendering Layout: consejos.md
 Post-Render Hooks: consejos.md
         Rendering: contacto.md
  Pre-Render Hooks: contacto.md
  Rendering Liquid: contacto.md
  Rendering Markup: contacto.md
  Rendering Layout: contacto.md
  Rendering Layout: contacto.md
 Post-Render Hooks: contacto.md
         Rendering: feed.xml
  Pre-Render Hooks: feed.xml
  Rendering Liquid: feed.xml
  Rendering Markup: feed.xml
 Post-Render Hooks: feed.xml
         Rendering: index.html
  Pre-Render Hooks: index.html
  Rendering Liquid: index.html
  Rendering Markup: index.html
  Rendering Layout: index.html
 Post-Render Hooks: index.html
         Rendering: /css/main.scss
  Pre-Render Hooks: /css/main.scss
  Rendering Liquid: /css/main.scss
  Rendering Markup: /css/main.scss
 Post-Render Hooks: /css/main.scss
         Rendering: unidades.md
  Pre-Render Hooks: unidades.md
  Rendering Liquid: unidades.md
  Rendering Markup: unidades.md
  Rendering Layout: unidades.md
  Rendering Layout: unidades.md
 Post-Render Hooks: unidades.md
                    done in 0.408 seconds.
           Watcher: Ignoring (?-mix:_config\.yml)
           Watcher: Ignoring (?-mix:_site)
 Auto-regeneration: enabled for '/home/rubenrojas/Github/TuCavaCuarto/sitio-web'
  Logging at level: debug
Configuration file: /home/rubenrojas/Github/TuCavaCuarto/sitio-web/_config.yml
[2015-12-04 16:10:15] INFO  WEBrick 1.3.1
[2015-12-04 16:10:15] INFO  ruby 2.2.3 (2015-08-18) [i386-linux-gnu]
[2015-12-04 16:10:15] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
[2015-12-04 16:10:15] DEBUG unmount .
[2015-12-04 16:10:15] DEBUG #<Class:0x9d35bcc> is mounted on .
    Server address: http://127.0.0.1:4000/
[2015-12-04 16:10:15] INFO  WEBrick::HTTPServer#start: pid=27083 port=4000
  Server running... press ctrl-c to stop.

**Comment by rubenmedios** [comment]
My version now

rubenrojas@ruben-rojas:~/Github/TuCavaCuarto/sitio-web$ jekyll -v
jekyll 3.0.1

**Comment by ndarville** [comment]
You could try getting around this by adding an explicit `permalink` field in the YAML header of your file:

```
---
permalink: filename.html
---
```
I have this problem with page files in Jekyll 2.5.3 where I have to use `permalink: error.html` for Jekyll to even render my `error.html` file to show 404s on AWS S3.
