### ISSUE TITLE
Tags string not separated by spaces

### ISSUE THREAD

**Issue by eberkund** [jekyll/jekyll#4225]
For me when I try to get the tags for a particular document using `{{ post.tags }}` the string it returns is not separated by spaces.

**example.md**
    ---
    title: Anything
    tags: one two
    author: SomeGuy
    ---
    Blah blah blah

**Result of `{{ post.tags }}`**
onetwo

In previous versions of Jekyll the string was space separated.

**Comment by parkr** [comment]
@eberkund In Jekyll 3, we upgrade to Liquid 3. Liquid 3 seems to have a difference in the way it outputs Arrays.

We recommend you use the `array_to_sentence_string` filter:

```liquid
{{ post.tags | array_to_sentence_string }}
```

**Comment by eberkund** [comment]
Thanks, that did the trick!
