### ISSUE TITLE
Jekyll errors are terribly broken.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4229]
```
jekyll 3.0.1 | Error:  undefined method `pages' for #<Jekyll:Page @name="about.md">
```

That's what I get for an error, that's not very helpful.

**Comment by parkr** [comment]
What would you like to see instead?

**Comment by envygeeks** [comment]
@parkr I actually wanted to see the line number it originated from, but enabling trace did that for some errors so I went on about my business and considered this a nonbug.
