### ISSUE TITLE
Using redcarpet with Jekyll 3

### ISSUE THREAD

**Issue by barryclark** [jekyll/jekyll#4230]
If I want to continue using redcarpet after it's [dropped as a dependency in Jekyll 3](http://jekyllrb.com/docs/upgrading/2-to-3/#dropped-dependencies), is specifying `markdown: redcarpet` in `_config.yml` sufficient to install it a) locally and b) by GitHub Pages?

**Comment by barryclark** [comment]
Moved to Jekyll Talk - https://talk.jekyllrb.com/t/using-redcarpet-with-jekyll-3/1627

**Comment by envygeeks** [comment]
Woah, I was just about to say that, I'll answer for you there!

**Comment by barryclark** [comment]
Thanks!
