### ISSUE TITLE
undefined method `safe_glob' for Jekyll::Utils:Module

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4232]
```
/srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/cleaner.rb:43:in `existing_files': undefined method `safe_glob' for Jekyll::Utils:Module (NoMethodError)
        from /srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/cleaner.rb:25:in `obsolete_files'
        from /srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-assets-87034c98b920/lib/jekyll/assets/patches/jekyll/cleaner.rb:10:in `obsolete_files'
        from /srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/cleaner.rb:15:in `cleanup!'
        from /srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/site.rb:192:in `cleanup'
        from /srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/site.rb:60:in `process'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<main>'
```

**Comment by envygeeks** [comment]
At first I thought this might be a bug in Jekyll-Assets but it turns out it's a bug here. /cc jekyll-assets#216

**Comment by parkr** [comment]
You're trying to use Jekyll 3.0.1 with Jekyll-fdf12efde40c which are incompatible. Use either `master` or 3.0.1. It's [definitely there on master](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/utils.rb#L250-L257)

**Comment by envygeeks** [comment]
@parkr actually it is master, it says 3.0.1 because that's the version master currently is, the Master Jekyll Docker image builds the gem and installs so the user doesn't need to use bundler.

**Comment by parkr** [comment]
@envygeeks Look at your paths:

```text
        from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<main>'
```

vs.

```text
/srv/jekyll/vendor/bundle/ruby/2.2.0/bundler/gems/jekyll-fdf12efde40c/lib/jekyll/cleaner.rb:43
```

Two different versions of Jekyll right there.

**Comment by envygeeks** [comment]
@parkr That's irrelevant, it was the master image, the sources match, the only difference is I enforced bundler to update to the ***latest*** master because I had just commited some WEBRick code I wanted right away and didn't want to push out another Docker build.  ***it was master even if it say's 3.0.1 because that is what master's Jekyll::VERSION is set to.

**Comment by envygeeks** [comment]
Since code speaks louder than words: https://github.com/jekyll/docker/blob/master/Dockerfile#L31-L37 should tell you exactly what I mean.

**Comment by parkr** [comment]
@envygeeks I'm not sure why you have both sources on there – perhaps that's what is causing the issue? It could be trying to load `Utils` from 3.0.1's source instead of from `master`'s source. If you package up the gem and run `gem install jekyll-3.0.1-master.pkg` then you shouldn't need the other path and I should just see one. I can't reproduce this locally with `bundle exec rake site:preview` which uses Jekyll core (but not jekyll-assets) so I don't think it's a problem with our current master, I think it's either with the Docker setup or with jekyll-assets.

**Comment by envygeeks** [comment]
I could reproduce it locally dozens of times, that's why I filed the issue.  I'm don't file tickets unless I'm confident there is a bug somewhere that I can track down and fix eventually.

**Comment by parkr** [comment]
> I could reproduce it locally dozens of times, that's why I filed the issue.

@envygeeks I can't reproduce in just jekyll/jekyll outside of docker is my point. I can't run docker on my machine and if I can run it just fine on my mac then i'm not going to go through the trouble of setting up a VM with Linux and managing it. If you can reproduce locally, outside of Docker, with the command I mentioned above, I would appreciate that stack trace.

**Comment by envygeeks** [comment]
Not worth it, we already fixed it on our build servers.

**Comment by parkr** [comment]
Ok cool!
