### ISSUE TITLE
Start using Set instead of Array

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4236]
Things like "excludes" and "includes" would benefit from being a set ove an array since you can do uniq without needing to worry about doing uniq and it makes plugin authors source much simpler since they no longer have to care about whether or not it's there, it won't be doubled causing potential memory leaks over long running Jekyll processes in development.

**Comment by parkr** [comment]
:+1:

**Comment by parkr** [comment]
@envygeeks Still want to do this?
