### ISSUE TITLE
Auto regeneration stuck at 'Rendering Markup...' after first change; subsequent changes not detected.

### ISSUE THREAD

**Issue by abrahamian** [jekyll/jekyll#4237]
Oddly, I've worked on, and deployed Jekyll (3.0.0) projects recently with no such problems. Been working on a Rails project in the past month, which certainly added a few gems to my system). 

On a MBP running OSX 10.8.5, with Ruby 2.1.5, and these gems installed:

	*** LOCAL GEMS ***

	actionmailer (4.1.13)
	actionpack (4.1.13)
	actionview (4.1.13)
	activemodel (4.1.13)
	activerecord (4.1.13)
	activesupport (4.1.13)
	addressable (2.3.8)
	arel (5.0.1.20140414130214)
	autosize-rails (1.18.17)
	bcrypt (3.1.10)
	bigdecimal (1.2.4)
	bootstrap-sass (3.2.0.2)
	builder (3.2.2)
	bundler (1.10.6)
	byebug (6.0.2)
	capybara (2.5.0)
	carrierwave (0.10.0)
	childprocess (0.5.7)
	coderay (1.1.0)
	coffee-rails (4.0.1)
	coffee-script (2.4.1)
	coffee-script-source (1.9.1.1)
	colorator (0.1)
	cookiejar (0.3.2)
	daemons (1.2.3)
	database_cleaner (1.5.1)
	devise (3.5.2)
	diff-lcs (1.2.5)
	em-http-request (1.1.2)
	em-socksify (0.3.1)
	erubis (2.7.0)
	eventmachine (1.0.8)
	excon (0.45.4)
	execjs (2.6.0)
	factory_girl (4.5.0)
	factory_girl_rails (4.5.0)
	faye (1.1.2)
	faye-websocket (0.10.0)
	ffi (1.9.10)
	font-awesome-sass (4.4.0)
	formatador (0.2.5)
	guard (2.13.0)
	guard-compat (1.2.1)
	guard-rspec (4.6.4)
	hike (1.2.3)
	http_parser.rb (0.6.0)
	i18n (0.7.0)
	io-console (0.4.2)
	jbuilder (2.3.2)
	jekyll (3.0.0)
	jekyll-sass-converter (1.3.0)
	jekyll-watch (1.3.0)
	jquery-rails (3.1.4)
	json (1.8.3, 1.8.1)
	kgio (2.10.0)
	kramdown (1.9.0)
	launchy (2.4.3)
	libv8 (3.16.14.13)
	liquid (3.0.6)
	listen (3.0.5)
	lumberjack (1.0.9)
	mail (2.6.3)
	mandrill-api (1.0.53)
	mercenary (0.3.5)
	method_source (0.8.2)
	mime-types (2.6.2)
	mini_portile (0.6.2)
	minitest (5.8.2, 4.7.5)
	modernizr-rails (2.7.1)
	mono_logger (1.1.0)
	multi_json (1.11.2)
	mysql2 (0.3.20)
	nenv (0.2.0)
	nokogiri (1.6.6.2)
	notiffany (0.0.8)
	orm_adapter (0.5.0)
	owlcarousel-rails (1.1.3.3)
	paper_trail (4.0.0)
	private_pub (1.0.3)
	pry (0.10.3)
	psych (2.0.5)
	pundit (1.0.1)
	quiet_assets (1.1.0)
	rack (1.5.5)
	rack-protection (1.5.3)
	rack-test (0.6.2)
	rails (4.1.13)
	rails-livestamp (1.1.3)
	railties (4.1.13)
	raindrops (0.15.0)
	rake (10.4.2, 10.1.0)
	rb-fsevent (0.9.6)
	rb-inotify (0.9.5)
	rdoc (4.2.0, 4.1.0)
	redcarpet (3.3.3)
	redis (3.2.1)
	redis-namespace (1.5.2)
	ref (2.0.0)
	request_store (1.2.0)
	responders (1.1.2)
	resque (1.25.2)
	rmagick (2.15.4)
	rouge (1.10.1)
	rspec (3.3.0)
	rspec-core (3.3.2)
	rspec-expectations (3.3.1)
	rspec-mocks (3.3.2)
	rspec-rails (3.3.3)
	rspec-support (3.3.0)
	rubyzip (1.1.7)
	safe_yaml (1.0.4)
	sass (3.4.19, 3.2.19)
	sass-rails (4.0.5)
	sdoc (0.4.1)
	select2-rails (3.5.9.3)
	selenium-webdriver (2.48.1)
	shellany (0.0.1)
	shoulda-callback-matchers (1.1.3)
	shoulda-matchers (3.0.1)
	sinatra (1.4.6)
	slop (3.6.0)
	soundmanager2-rails (2.97.20140901)
	spring (1.4.0)
	sprockets (2.12.4)
	sprockets-rails (2.3.3)
	taglib-ruby (0.7.0)
	test-unit (2.1.5.0)
	therubyracer (0.12.2)
	thin (1.6.4)
	thor (0.19.1)
	thread_safe (0.3.5)
	tilt (2.0.1, 1.4.1)
	typeahead-rails (0.10.5)
	tzinfo (1.2.2)
	uglifier (2.7.2)
	unicorn (5.0.0)
	vegas (0.1.11)
	warden (1.2.3)
	websocket (1.2.2)
	websocket-driver (0.6.2)
	websocket-extensions (0.1.2)
	xpath (2.0.0)
	
Steps to reproduce:

Initialize & serve a new Jekyll project

	jekyll new regeneration_stuck
	cd regeneration_stuck
	jekyll serve ENV["LISTEN_GEM_DEBUGGING"]=1 --profile --verbose
	

Output:

	  Logging at level: debug
	Configuration file: /Users/MihranAbrahamian/dev/regeneration_stuck/_config.yml
	            Source: /Users/MihranAbrahamian/dev/regeneration_stuck
	       Destination: /Users/MihranAbrahamian/dev/regeneration_stuck/_site
	 Incremental build: disabled. Enable with --incremental
	      Generating... 
	       EntryFilter: excluded?(/default.html) ==> false
	       EntryFilter: excluded?(/page.html) ==> false
	       EntryFilter: excluded?(/post.html) ==> false
	       EntryFilter: excluded?(/about.md) ==> false
	       EntryFilter: excluded?(/css) ==> false
	       EntryFilter: excluded?(/feed.xml) ==> false
	       EntryFilter: excluded?(/index.html) ==> false
	       EntryFilter: excluded?(/_posts/2015-12-08-welcome-to-jekyll.markdown) ==> false
	           Reading: _posts/2015-12-08-welcome-to-jekyll.markdown
	       EntryFilter: excluded?(/css/main.scss) ==> false
	         Rendering: _posts/2015-12-08-welcome-to-jekyll.markdown
	         Rendering: _posts/2015-12-08-welcome-to-jekyll.markdown
	  Pre-Render Hooks: _posts/2015-12-08-welcome-to-jekyll.markdown
	  Rendering Liquid: _posts/2015-12-08-welcome-to-jekyll.markdown
	  Rendering Markup: _posts/2015-12-08-welcome-to-jekyll.markdown
	  Pre-Render Hooks: _posts/2015-12-08-welcome-to-jekyll.markdown
	  Rendering Liquid: _posts/2015-12-08-welcome-to-jekyll.markdown
	  Rendering Markup: _posts/2015-12-08-welcome-to-jekyll.markdown
	  Rendering Layout: _posts/2015-12-08-welcome-to-jekyll.markdown
	         Rendering: about.md
	  Pre-Render Hooks: about.md
	  Rendering Liquid: about.md
	  Rendering Markup: about.md
	  Rendering Layout: about.md
	  Rendering Layout: about.md
	 Post-Render Hooks: about.md
	         Rendering: feed.xml
	  Pre-Render Hooks: feed.xml
	  Rendering Liquid: feed.xml
	  Rendering Markup: feed.xml
	 Post-Render Hooks: feed.xml
	         Rendering: index.html
	  Pre-Render Hooks: index.html
	  Rendering Liquid: index.html
	  Rendering Markup: index.html
	  Rendering Layout: index.html
	 Post-Render Hooks: index.html
	         Rendering: /css/main.scss
	  Pre-Render Hooks: /css/main.scss
	  Rendering Liquid: /css/main.scss
	  Rendering Markup: /css/main.scss
	 Post-Render Hooks: /css/main.scss
	
	Filename                                              | Count |  Bytes |  Time
	------------------------------------------------------+-------+--------+------
	_layouts/default.html                                 |     3 | 18.95K | 0.008
	_includes/footer.html                                 |     3 |  8.43K | 0.004
	_posts/2015-12-08-welcome-to-jekyll.markdown          |     1 |  1.52K | 0.002
	_includes/header.html                                 |     3 |  3.05K | 0.002
	_includes/head.html                                   |     3 |  1.95K | 0.001
	feed.xml                                              |     1 |  3.46K | 0.001
	_includes/icon-github.html                            |     5 |  5.09K | 0.001
	about.md                                              |     1 |  2.41K | 0.001
	_layouts/post.html                                    |     1 |  2.03K | 0.001
	_includes/icon-twitter.html                           |     3 |  2.66K | 0.001
	index.html                                            |     1 |  0.39K | 0.000
	_includes/icon-github.svg                             |     5 |  4.52K | 0.000
	_posts/2015-12-08-welcome-to-jekyll.markdown/#excerpt |     1 |  0.42K | 0.000
	_layouts/page.html                                    |     1 |  2.64K | 0.000
	_includes/icon-twitter.svg                            |     3 |  2.31K | 0.000
	css/main.scss                                         |     1 |  0.96K | 0.000
	
	                    done in 0.411 seconds.
	           Watcher: Ignoring (?-mix:_config\.yml)
	           Watcher: Ignoring (?-mix:_site)
	 Auto-regeneration: enabled for '/Users/MihranAbrahamian/dev/regeneration_stuck'
	  Logging at level: debug
	Configuration file: /Users/MihranAbrahamian/dev/regeneration_stuck/_config.yml
	[2015-12-08 16:16:24] INFO  WEBrick 1.3.1
	[2015-12-08 16:16:24] INFO  ruby 2.1.5 (2014-11-13) [x86_64-darwin12.0]
	[2015-12-08 16:16:24] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
	[2015-12-08 16:16:24] DEBUG unmount .
	[2015-12-08 16:16:24] DEBUG #<Class:0x007fe946459a20> is mounted on .
	    Server address: http://127.0.0.1:4000/
	[2015-12-08 16:16:24] INFO  WEBrick::HTTPServer#start: pid=10580 port=4000
	  Server running... press ctrl-c to stop.

Then, make any change to `index.html`. The change is detected. Output:

	      Regenerating: 1 file(s) changed at 2015-12-08 16:19:17        EntryFilter: excluded?(/default.html) ==> false
	       EntryFilter: excluded?(/page.html) ==> false
	       EntryFilter: excluded?(/post.html) ==> false
	       EntryFilter: excluded?(/about.md) ==> false
	       EntryFilter: excluded?(/css) ==> false
	       EntryFilter: excluded?(/feed.xml) ==> false
	       EntryFilter: excluded?(/index.html) ==> false
	       EntryFilter: excluded?(/_posts/2015-12-08-welcome-to-jekyll.markdown) ==> false
	           Reading: _posts/2015-12-08-welcome-to-jekyll.markdown
	       EntryFilter: excluded?(/css/main.scss) ==> false
	         Rendering: _posts/2015-12-08-welcome-to-jekyll.markdown
	         Rendering: _posts/2015-12-08-welcome-to-jekyll.markdown
	  Pre-Render Hooks: _posts/2015-12-08-welcome-to-jekyll.markdown
	  Rendering Liquid: _posts/2015-12-08-welcome-to-jekyll.markdown
	  Rendering Markup: _posts/2015-12-08-welcome-to-jekyll.markdown
	

… Which just sits there. Make another change to `index.html` or any other file, no further output to the console. 

What's going on?

**Comment by abrahamian** [comment]
The problem was solved by adding a `Gemfile` with these contents:

	gem 'jekyll', '3.0.0'
	gem 'jekyll-watch'
	gem 'listen'
	
then running `bundle install` before `jekyll serve`. Yet I'm still puzzled as the output was:

	Using colorator 0.1
	Using ffi 1.9.10
	Using sass 3.4.19
	Using jekyll-sass-converter 1.3.0
	Using rb-fsevent 0.9.6
	Using rb-inotify 0.9.5
	Using listen 3.0.5
	Using jekyll-watch 1.3.0
	Using kramdown 1.9.0
	Using liquid 3.0.6
	Using mercenary 0.3.5
	Using rouge 1.10.1
	Using safe_yaml 1.0.4
	Using jekyll 3.0.0
	Using bundler 1.10.6
	Bundle complete! 3 Gemfile dependencies, 15 gems now installed.
	Use `bundle show [gemname]` to see where a bundled gem is installed.
	
	
... and I don't see any version mismatch between the gems listed here, and those I had already installed locally (listed in my original post).  Would appreciate any clarification.

**Comment by envygeeks** [comment]
The way your system is setup is way out of scope in my opinion, that's pretty extreme and this is one of several reasons why most Ruby programmers use bundler, but I'm not here to preach to you how to do your system.  Lets get more information:

1. `LISTEN_GEM_DEBUGGING=2 jekyll serve --profile --verbose`, post us the output and /cc @e2
2. Try updating your gems, if it works, then it was an oudated gem, easy!
3. Try it with Bundler, use a Gemfile and bundle install without shared gems (`--path vendor/bundle`)
    1. If it works... you have a conflict and this is out of scope, it's a systems problem.

With these steps we should be able to see where to go from there... hopefully.

**Comment by envygeeks** [comment]
Well apparently I didn't see your reply before I posted, there was a conflict somewhere, now you know why most of us use Bundler instead of messing about with Global gems, unless they are truly global CLI tools (the only global gem I have on my system is Travis and Pry, everything else is a Gemfile.)

**Comment by envygeeks** [comment]
Closing this as out-of-scope since it was solved with a Gemfile, seemed like a systems problem.

**Comment by abrahamian** [comment]
@envygeeks , thank you.

What do you mean exactly about my system set-up? I do use bundler, and Gemfiles specific to  individual projects, and I generally prefix commands with  `bundle exec` prefix to ensure that correct versions are used. Is it preferable, in your opinion, to not have any gems installed 'globally' ? 

Truthfully, I haven't put a lot of thought into my system's setup, so I do welcome your advice.

**Comment by envygeeks** [comment]
If I don't use it everywhere and I don't consider it a system utility I don't globally install it.  Which means that Jekyll development happens with `bundle install`, Rails too (this is the most chaotic gem, not because it's bad but because it's dependencies vary so widely depending on what you are doing.)

If the system is doing one job, I'll system wide install unlesss... I want a volatile system, then I `bundle install` so that it's portable across "like systems" that are volatile and could disappear tomorrow.  If I'm in Docker, I always globally install because even if it's volatile, it's state is persistent (except for the things that aren't but that's obvious.)

I don't install anything globally that I might uninstall or that has a large dependency set that I can't remove quickly... especially if it's a Ruby Gem because Ruby has no concept of recommends and dependency tracking that's advanced enough to unininstall the dependencies of my dependencies (exp: I `apt-get autoremove --purge pkg` it will remove stuff it installed with pkg, Ruby does not do that, I don't have time to cleanup that mess... I do have time to `rm -rf vendor/` though.)

There's a lot more to it and I'm sure other people can chip in and give advice from their perspective but that's the gist of how I work.
