### ISSUE TITLE
Javascript files are copied to _site dir with no content when Jekyll is watching.

### ISSUE THREAD

**Issue by stewartknapman** [jekyll/jekyll#4239]
I am having an issue where running `jekyll build --watch` copies `.js` files from inside the `js/` directory to the built `_site` dir, but they contain no content. This is also intermittent and I'm not sure how to track down whats going on.

Firstly, I'm using browserify to build my js files because I'm using a couple of npm packages and requiring  other js files. I also have my build tasks set up with npm scripts inside a `package.json` file.
These are my js tasks:

    "scripts": "browserify ./_src/js/app.js > ./js/app.js",
    "postscripts": "uglifyjs ./js/app.js -c -m > ./js/app.min.js",
    "scripts:watch": "watch 'npm run scripts' ./_src/js/",
    ...

The `scripts` task bundles the js files with browserify and places the output inside `js/app.js`. The `postscripts` task takes the bundled app.js and minifies it. There is also a watch task for running the script task when a file changes. This is all working fine and the output `app.js` and `app.min.js` files have the expected content.

I'm also running `jekyll build --watch` at the same time. So this then sees that the js files have been updated and does its thing. However the files inside `_site/js/` are missing their content.
Sometimes app.js will be empty, other-times app.min.js will be empty, sometimes they are both empty and occasionally they will both work. There seems to be no rhyme or reason.

If I run `jekyll build` once after the npm tasks have run it creates the js files fine and all the contents is there again. However this is not a fix, because if I update any other file (html/md/scss/etc.) the watch task runs and then junks up the otherwise fine js files, again.

It only seems to be effecting the Javascript files as I'm also doing a similar thing with my `.scss` files and the output css files are always intact.

If I was to take a wild guess at what might be causing it, it would either be a timing issue—jekyll is picking up the js files before they are completely added? OR the asset pipeline is doing something crazy to the js files during the build process?

**EDIT**
My current work around is to `exclude:` the `./js` dir and `keep_files:` the `./js` and then copy my built js files in via my npm scripts.

**Comment by envygeeks** [comment]
If it works without your external scripts this is out of our scope.  Does it work with all that disabled?

**Comment by stewartknapman** [comment]
Ok, it looks like it's a timing issue. I can't replicate the issue with just running `jekyll build --watch` by it's self.

It seems that creating the output files in a directory that jekyll is watching is causing jekyll to run with them before they have finished being created/updated, so it ends up making empty files in the build directory.

Still, it would be reasonable to think anyone doing something similar with gulp or grunt might be experiencing the same issue.

**Comment by envygeeks** [comment]
This is just my opinion and the rest of @jekyll/core might have a different opinion but the only place this can be solved is in your Gulp task... at least right now.

I can't say for sure that my opinion has standing without knowing more though. So far I am making broad assumptions based on experience. I'm only to assume something in Gulp is doing unoptimized file system handling leading to multiple events... a few of which could be blocked either by rate limiting (I don't remember if listen does that -- or FSNotify/INotify) or a busy Jekyll.

Is there source we can look at when we have time, ultimately I don't think it will change the standing that this is a corner caused directly by Gulp so it's out-of our scope possibly but I'd be happy to try and help you if I can.

**Comment by stewartknapman** [comment]
That makes sense, and it is what I'm thinking now, as well.

I think I have a sufficient work around now. Which is to tell jekyll not to worry about the js/ folder and I move the .js files into _site/ with one of my npm scripts.

Thanks for your time anyway.

**Comment by davidbiehl** [comment]
Have you tried `--force_polling`? I'm curious to see if it makes a difference in this case.

**Comment by parkr** [comment]
The issue, as you stated, seems to be with Listen picking up modifications to your files before the write is complete. I suspect the file is being created by your node process before it is populated with data. Ruby's just too fast for it! :wink: Glad you found a working solution.
