### ISSUE TITLE
Generator garbles PHP code

### ISSUE THREAD

**Issue by KAnoshkin** [jekyll/jekyll#424]
Sorry if I'm missing something obvious.

I need to have a contact form on my Octopress site, so I made a php page (with file name extension "php"). All is well except the php code in the generated php file is heavily escaped. Can I somehow configure Jekyll to leave <?php ... ?> blocks as is?

Thanks in advance.

**Comment by anden259** [comment]
`{% raw %}<?php echo("untoutched"); ?>{% endraw %}`
