### ISSUE TITLE
HTML inline script single line comment bug

### ISSUE THREAD

**Issue by RaySuhyunLee** [jekyll/jekyll#4241]
Hi! I'm new to Jekyll and was working on javascript inside the _post.html template. The problem is, since jekyll removes new line characters and compress the inline script in one line, when I comment using `//` lines below the comment are also considered by browser as comment. As a result I can't run the code below single line comments.
I wonder if it is an intended behavior or a bug. Maybe it should wipe out the comments, or leave new line characters. If it is a bug, I'd like to fix it :)

**Comment by envygeeks** [comment]
It's not Jekyll "removing new lines" and compressing your inline script, it's a plugin or something else you have going on, please tell us what plugins you have and if you are using something to compress your HTML (like a grunt task or something.) All of which are out of our scope of support because that's third party.

**Comment by RaySuhyunLee** [comment]
Oh I see! I'm using an open source theme and I noticed that there is [html compressor written by penibelst](https://github.com/penibelst/jekyll-compress-html) in _layout directory. It raised the problem.
Thank you for clarification and sorry for confusion :sweat_smile:

**Comment by RaySuhyunLee** [comment]
Let me close this issue to prevent further confusion!

**Comment by envygeeks** [comment]
Gonna /cc @penibelst so he can check it out and comment!

**Comment by penibelst** [comment]
@envygeeks Thank you for the hint.

@RaySuhyunLee Your issue with `//` comments is a [documented restriction](http://jch.penibelst.de/#restrictions). Please use the dedicated repository https://github.com/penibelst/jekyll-compress-html for further details.

**Comment by RaySuhyunLee** [comment]
Thanks a lot!
