### ISSUE TITLE
I'm being haunted by a previous version of _config.yml

### ISSUE THREAD

**Issue by jtremback** [jekyll/jekyll#4245]
I change some stuff in my `_config.yml`, and do `jekyll serve`. At first, the new `_config.yml` is served. However, after a couple of changes and refreshes, it seems that the settings from the old `_config.yml` are back.

**Comment by envygeeks** [comment]
We don't store previous copies of your `_config.yml` and if you change it and reboot we wouldn't even know the old one existed, we don't write to `_config.yml` at all either.  Perhaps there is something on your system recovering the file outside of Jekyll's scope?

Can you provide more details?

**Comment by jtremback** [comment]
Should have been clearer- the actual file `_config.yml` is not altered, but the `_site` directory is rebuilt with the settings from the old `_config.yml` when it is auto-regenerated with `jekyll serve`

**Comment by envygeeks** [comment]
Ah yes, we do not re-read `_config.yml` if it's altered while we are loaded, you'll need to reboot Jekyll to pick up the new changes to `_config.yml`, I don't quite know why Jekyll does not reboot (cc @parkr for clarification on that) but that's just how it is, does it pick up the changes when you reboot?

**Comment by jtremback** [comment]
Yes, it picks up the changes when I reboot. However, on the first or second auto-regeneration, the _site folder reverts to the old settings. I made some changes to the url structure half an hour ago, and now have to rebuild manually every time, otherwise the old url structure comes back.

**Comment by parkr** [comment]
@jtremback If you change your _config.yml, it will not be reloaded during the same server session. This is a known issue: https://github.com/jekyll/jekyll-watch/issues/8 You have to reboot to get the new configuration.

If you're using your config to output something in your browser and you're seeing old values, double-check your browser cache. If you stop and restart the Jekyll server, the new data is used so it would be entirely out of our hands. Hope this helps!

**Comment by jtremback** [comment]
I had another instance of jekyll running that I had forgot about, that was using the old `_config.yml`

**Comment by parkr** [comment]
@jtremback Glad you figured it out! :)

**Comment by envygeeks** [comment]
I've had that happen before, I'm finally ready to admit it now that another has.
