### ISSUE TITLE
YAML Front Matter not attached to `page` in layout

### ISSUE THREAD

**Issue by dalanmiller** [jekyll/jekyll#4246]
Also posted in #2836 

If I set YAML Front Matter in a layouts file `_layouts/post.html` like so:

```
--- 
layout: default
body_class: blog
---
```

I should be able to access `body_class` via `page.body_class` in the `_layouts/default.html` file, correct? This isn't happening currently in Jekyll 3.0.1 and the value results in `nil` and renders as empty space. This code was also working as expected in Jekyll 2.2. 

Interestingly, normal usage of `page.body_class` is working, such as in an `{% if .. %}` statement and other places. However, in this specific case (within a string?) it is failing:

```
<div class="{{page.body_class}}">
```

However, `<div class="{{ layout.body_class }}">` is working. Can someone explain why this is?

**Comment by budparr** [comment]
I think this is what you're looking for: http://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata

**Comment by parkr** [comment]
Thanks, @budparr! You're right. @dalanmiller We changed this in 3.0 to be `layout.body_class` because no one could decide whether page data should overwrite layout data, or the other way around. So we just separated it.

**Comment by dalanmiller** [comment]
Thank you for the quick reply guys @budparr & @parkr! Is there a reason why some variables are still attached to `page`? Like in this instance, `page.body_class` works in pretty much every other instance except the one I showed above.

**Comment by dalanmiller** [comment]
I also that if I change that specific line to `layout.body_class` it breaks my template in `./blog/index.html` whose header looks like this:

```
---
layout: default
title: Blog
active: blog
body_class: blog
---
```
This file works with `page.body_class` not `layout.body_class`. So there's something different happening when the inheriting template is another layout or a non-layout. Is there maybe something wrong with the way I have my directory setup? 

```
_layouts
├── default.html
└── post.html
blog
├── index.html
```

**Comment by dalanmiller** [comment]
I think I now understand that the value is under `layout` when the layout inherits another layout, but under `page` when a page inherits from layout `_layouts/default.html`.

**Comment by envygeeks** [comment]
That just broke my brain.

**Comment by parkr** [comment]
@dalanmiller I believe this was fixed by #4205. It was inconsistent, but will be fixed in 3.1.

**Comment by dalanmiller** [comment]
As a stopgap/jerry-rig, could I do something like this?

```
{% if layout.body_class.nil? || layout.body_class == "" %}
  {% assign layout.body_class = page.layout.body_class %}
{% endif %}
```

**Comment by parkr** [comment]
@dalanmiller From [the `if/else` documentation](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#if--else), this should work:

```liquid
{% if layout.body_class and layout.body_class == "" %}
  {% assign layout.body_class = page.layout.body_class %}
{% endif %}
```

**Comment by evgenyneu** [comment]
Does not work for me in `3.1.0.pre.beta1`. I can not access metadata specified in layout file. 

_layouts/project.html

```
---
layout: default
layout_class: isTextCentered
---
```

_layouts/default.html

```
<body class="{{ layout.layout_class }}">
```

The output HTML is `<body class=" ">` while it should be `<body class="isTextCentered">`. Am I going something wrong?
