### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#4250]
Part of #4109 was an update to our tests for them. One seems to be flaking out somewhat frequently in Ruby 2.2:

```text
Finished tests in 114.908768s, 4.7255 tests/s, 7.9193 assertions/s.
Failure:
TestKramdown#test_: kramdown should render fenced code blocks with syntax highlighting.  [/home/travis/build/jekyll/jekyll/test/test_kramdown.rb:59]
Minitest::Assertion: Failed refutation, no message given
543 tests, 910 assertions, 1 failures, 0 errors, 0 skips
```

@envygeeks, know why that would sometimes not work?

**Comment by envygeeks** [comment]
Without seeing the error I have no idea, It's not the test that's flaky more than likely, it's the stuff around it that is, we've always had fragile testing (which is why the rewrite is in the works,) but something could be exacerbating it with a mutation that isn't corrected somewhere because we don't properly mock.  I'll take a look.

**Comment by parkr** [comment]
@envygeeks: It seems related to what we were discussing yesterday:

```ruby
    should "render fenced code blocks with syntax highlighting" do
      result = nokogiri_fragment(@markdown.convert(Utils.strip_heredoc <<-MARKDOWN))
        ~~~ruby
        puts "Hello World"
        ~~~
      MARKDOWN

      selector = "div.highlighter-rouge>pre.highlight>code"
      refute result.css(selector).empty?
    end
```

**Comment by spudowiar** [comment]
+1, but annoyingly I cannot reproduce it on my computer to do debugging. I've only ever seen it on Travis CI.

**Comment by parkr** [comment]
> @parkr Could I have some context on your system setup?

@spudowiar I am running Mac OS X 10.11.3. I use rbenv to setup my rubies, and probably ran this test with either 2.1.7-github (branch of github/ruby) or 2.3.0. I have libxml installed via Homebrew, though I think nokogiri uses its own version when I install.

**Comment by spudowiar** [comment]
It's state leakage, you can reproduce it by running `rake TESTOPTS="--seed=31954" test` with any version of Ruby. This means some of the tests are modifying something that then breaks this test.

**Comment by spudowiar** [comment]
It should be noted (although it might be my fault) that that seed breaks the OpenSSL test (because it's relying on it being `require`d elsewhere?)

**Comment by spudowiar** [comment]
Normally we expect `<div class="highlighter-rouge"><pre class="highlight"><code><span class="nb">puts</span> <span class="s2">"Hello World"</span></code></pre></div>` but the error is producing `<pre><code class="language-ruby">puts "Hello World"</code></pre>`. Presumably Rouge has not been set-up yet?
