### ISSUE TITLE
Liquid for loop working in live site but not locally

### ISSUE THREAD

**Issue by jseldess** [jekyll/jekyll#4256]
I just started working on a new OSX 10.11.2. I installed Jekyll and all dependencies without trouble, it seems, and then cloned this repo locally: https://github.com/jseldess/jseldess.github.io

When I view the live site off the repo (http://jseldess.github.io/), the Liquid loop in the default layout successfully generates a page tree in the sidebar. But when I serve up the site locally, that sidebar is empty. I can't figure out why that's happening. Any ideas?

Here's the loop:

```
{% for item in site.collections %}
    {% assign collection = item[1] %}
    {% if section %}
        {% if collection.output %}
            {% assign next = collection %}
            {% break %}
        {% endif %}
    {% elsif url contains collection.active_prefix %}
        {% assign section = collection.title %}
        {% assign items = collection.docs | sort: 'order' %}
    {% elsif collection.output %}
        {% assign previous = collection %}
    {% endif %}
{% endfor %}
```

Wondering if this problem has something to do with the fact that jekyll 3 is installed locally whereas github pages are still on jekyll 2.4, according to this page: https://pages.github.com/versions/

**Comment by parkr** [comment]
@jseldess This is because `site.collections` changed in 3.0. http://jekyllrb.com/docs/upgrading/2-to-3/#sitecollections-has-changed

In your repo, add a Gemfile that looks like this:

```ruby
source "https://rubygems.org"

gem "github-pages"
```

Then run `gem install bundler` and `bundle install`. Then, when you want to run Jekyll locally, always prefix it with `bundle exec`, like `bundle exec jekyll serve`. This will ensure that you use the proper Jekyll version that matches the one on GitHub Pages.

http://bundler.io/

**Comment by jseldess** [comment]
Thanks very much, parkr! But after creating that gem (I called it githubpages.gem), putting it in the project's root directory, and running `gem install bundler`, I get this error:

```
ERROR:  While executing gem ... (Gem::Package::FormatError)
    package metadata is missing in githubpages.gem
```

Any additional help you can offer?

**Comment by parkr** [comment]
@jseldess I believe you misunderstood me. You should not be creating any gems. You should be installing ones available on RubyGems.org, namely https://rubygems.org/gems/github-pages.

```console
$ cd jseldess.github.io
$ echo -e "source 'https://rubygems.org'\ngem 'github-pages'" > Gemfile
$ bundle install
$ bundle exec jekyll serve
# Open your browser at go to http://localhost:4000 to see your new site.
```

**Comment by jseldess** [comment]
Thanks for the clarification! All's well again.
