### ISSUE TITLE
Ruby gem can't connect.. SSL_connect error

### ISSUE THREAD

**Issue by faisalmehmood59** [jekyll/jekyll#4257]
I have been trying to get jekyll running. I tried both LinuxMint and Lubuntu. I get the same error on both OSes. 

```
ncepu@sprite:~$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
ncepu@sprite:~$ gem install jekyll
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect SYSCALL returned=5 errno=0 state=unknown state (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/jekyll-3.0.1.gemspec.rz)
```
I found a couple of similar posts off Google but couldn't find anything that solved the problem.

**Comment by faisalmehmood59** [comment]
Temporarily modified the gem sources list by replacing the ```https://rubygems.org``` version by ```http://rubygems.org```. It isn't much of a solution but it got the packages installed successfully. Spent the entire day on this!

**Comment by envygeeks** [comment]
Unfortunately there is nothing we can do about this error @faisalmehmood59, this is a RubyGems error and can only be solved by the team at https://github.com/rubygems/rubygems.org
