### ISSUE TITLE
Install with RubyGems

### ISSUE THREAD

**Issue by nijagu-ugajin** [jekyll/jekyll#4260]
Nothing is it seems, as quite straightforward as one would like. On running the command `$ gem install jekyll`.
Terminal kindly generated the following error message: `ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.`
However, I do not know how to fix the permissions issue for the install.
Assuming this to be a common thing on OS X, then some further guidance notes would I think be be both useful, and helpful.
Thanks.
-u

**Comment by envygeeks** [comment]
There is: http://jekyllrb.com/docs/troubleshooting/#jekyll-amp-mac-os-x-1011 please use the guidance in that, other than that we cannot help you as this is a systems problem, however you can ask your question at https://talk.jekyllrb.com and the community will gladly help you sort out your system.

**Comment by nijagu-ugajin** [comment]
Thanks. 
I do not believe it is a systems problem, as the installation instructions appear incorrect and/or incomplete. OS X terminal seems to require `sudo`which the guide omits. It may be a small thing to correct this error. The frustration that may arise if it is not corrected may be disproportionally large, at least for OS X practitioners.

**Comment by envygeeks** [comment]
I do not require `sudo gem` to `gem install` on any of my systems.  As a primary Linux user, a secondary Windows user and a testing OS X user.  `gem install gem` *is the correct way* and whether you need `sudo` or not is literally a systems problem as it all hinges on how *you* manage your system.

**Comment by nijagu-ugajin** [comment]
Maybe you should look at and reconfigure the testing OS X system.

**Comment by envygeeks** [comment]
I could say the same about your OS X but since I do systems for a living I'm fine with it as is.

**Comment by nijagu-ugajin** [comment]
Why, you do not need the `sudo` command?

**Comment by parkr** [comment]
OS X Yosemite and above have Ruby installed in a secure location that requires sudo. We do not recommend installing with this Ruby as, if anything goes wrong, it can damage OS X. We recommend using rbenv/rvm or using `gem install --user jekyll` which installs into your home directory.

We will do our best to never recommend using sudo as it is very unsafe. We could delete your whole system! We could steal your information. We don't want you to use sudo, so we do not recommend using it.

**Comment by nijagu-ugajin** [comment]
I see.
I am running El Capitan
What should I do?
I have installed jekyll using sudo?
Thanks.

**Comment by parkr** [comment]
If you have installed Jekyll via sudo, you may keep using it. Just know it is not recommended because things can go wrong when it is done this way.

**Comment by nijagu-ugajin** [comment]
I would rather do it as recommended.
It appears to have installed jekyll in `/Library/Ruby/Gems/2.0.0`
Can I dump 2.0.0 and its contents into the trash, and then run `gem install --user jekyll`, or do I need to run a Terminal command to undo the installation?

**Comment by envygeeks** [comment]
@nijagu-ugajin if you wish to uninstall and then go the user route (this is what I do on my systems, well almost like it...) then you can actually use Ruby Gem to uninstall by doing `sudo gem uninstall jekyll`.. the problem here is Gem doesn't do reverse dependency handling the way the system does so you'll also need to uninstall all our dependencies too (which can be found here: https://rubygems.org/gems/jekyll) however... if you only have Jekyll installed I can make it easy: `sudo gem uninstall $(gem list | awk '{ print $1 }'`, it should skip over stdlib, I don't quite remember if OS X has the right Gem version to do that so tred carefully in that aspect, the defaults (and I might be a few off) are io-console, bigdecimal, rake, rdoc, and test-unit)

**Comment by parkr** [comment]
> Also, I see on the jekyll troubleshooting page a reference to system integrity on OS X 10.11, where it suggests running sudo gem install -n /usr/local/bin jekyll This information ought to be flagged in the installation page, it is not much use otherwise.

The troubleshooting page is linked to on the [Installation page](http://jekyllrb.com/docs/installation/#install-with-rubygems). It is not a standard way to install, as we recommend using a Ruby version manager like rbenv or rvm to manage your version of ruby entirely within user-permissible locations.

**Comment by nijagu-ugajin** [comment]
@envygeeks - I am concerned by the comment, `... it should skip over stdlib, I don't quite remember if OS X has the right Gem version to do that so tred carefully in that aspect.` Anyhow I tried running it, and Terminal flagged the following: `ERROR:  While executing gem ... (Gem::InstallError)
    gem "test-unit" cannot be uninstalled because it is a default gem`

BTW the information on `https://rubygems.org/gems/jekyll` seems not to be current for all the runtime dependencies listed, when compared with those that appear to have been installed. 

@parkr Yes, the troubleshooting page is flagged, but the issue isn't except on the trouble shooting page. IMHO this isn't good enough, especially as it is a known issue that the installation instruction will not work for OS X 10.11. Do you intend to require all X 10.11 users to direct themselves to the 'troubleshooting' page in the first instance? 

The claim made on the installation page that 'Installing Jekyll is easy and straight-forward' is somewhat disingenuous, at least for OS X v10.11. Indeed, even the advice, which you gave earlier is inconsistent with the advice on the trouble shooting page. You advised `gem install --user jekyll, whereas the trouble-shooting page suggests `sudo gem install jekyll`(which I have used) as well as `sudo gem install -n /usr/local/bin jekyll`. Can all three be right? There is also a somewhat ambiguous remark about using `sudo only if necessary`, which is dotted throughout the trouble-shooting page. Why? Based on what has been said so far, it seems `sudo` will be required.

I understand that you recommend a version manager, but perhaps you can point to this recommendation on the, a) the Welcome page, b) the Quick-start guide, or c) the Installation page. I do not think recommending Ruby Gems (half way down the installation page) makes this clear, especially when it is immediately followed by the instruction: `At the terminal prompt, simply run the following command to install Jekyll: $ gem install jekyll ' makes this clear.
