### ISSUE TITLE
Unable to add conditional classes and elements in jekyll version 2.4.0

### ISSUE THREAD

**Issue by AshBardhan** [jekyll/jekyll#4264]
I was required to add a class and an element based on `layout` of `post`. So I applied the following logic inside the parent `post.html` file.

````
<article class="post-content text-big {%if include.post.layout == 'post' %}post-content--blog{% endif %}">
		{{ include.post.content }}
		{%if include.post.layout == 'post' %}
		<div class="post-content__image"></div>
		{% endif %}
 </article>
`````

In jekyll version 3 so far, this will work and the class and element will be added based on the condition. But on lower versions such as `2.4.0` (up to which Github pages supports), this will only work for home page (showing latest post) not for other post pages.

Is there any alternative solution to solve the problem for this version? Or am I doing completely wrong?

**Comment by parkr** [comment]
Unfortunately, we can't support 2.x anymore, especially a version as old as 2.4. GitHub is working on upgrading to Jekyll 3: https://github.com/github/pages-gem/pull/175

In the meantime, you'll have to build your site and push it up manually. You can see how we do that for jekyllrb.com [in the Rakefile at the root of this project](https://github.com/jekyll/jekyll/blob/645a2cc664ca39c672c5139a294515cec10be0d8/Rakefile#L182-L230).
