### ISSUE TITLE
Is there a way to create new paragraphs in a YAML multi-line key?

### ISSUE THREAD

**Issue by shanecarmody** [jekyll/jekyll#4266]
I have a YAML key set up like so:

```yml
en:
  info: |
    Hello!

    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
    
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
```

The intended render is:

> Hello!
>
>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
>    
>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 

However, in reality, this is rendered like so:

> Hello! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 

So, my question is: Is it possible to for YAML to be rendered the way I want it to be? Or, do I need to create a separate key for each paragraph?

**Comment by envygeeks** [comment]
Hello, this is a not a bug with Jekyll, so I must please ask you that you ask your non-bug-related question at https://talk.jekyllrb.com as this medium is for bug directly related to Jekyll and not generic questions about stuff that Jekyll uses or how Jekyll works.

Thanks.

**Comment by shanecarmody** [comment]
@envygeeks yeah, I was about to close it myself as I realised the YAML repo itself was a better place to ask it.

Thanks

**Comment by parkr** [comment]
We use SafeYAML, so you can ask on dtao/safe_yaml. It might be worth checking the YAML spec too to see if it's even something that should be there.

**Comment by shanecarmody** [comment]
@parkr thanks. @budparr answered my question in https://github.com/yaml/yaml/issues/9
