### ISSUE TITLE
Undefined method error on http://jekyllrb.com/docs/posts/

### ISSUE THREAD

**Issue by ryanburnett** [jekyll/jekyll#4271]
I ran into an issue on:

http://jekyllrb.com/docs/posts/

Following this page's instructions I pasted this into `_posts/2015-12-18-welcome-to-jekyll.markdown`:

```
… which is shown in the screenshot below:
![My helpful screenshot]({{ site.url }}/assets/screenshot.jpg)
```

...and got the following command prompt error:

```
$ jekyll serve
Error reading file C:/Projects/jekyll/_posts/2015-12-18-welcome-to-jekyll.markdown:
invalid byte sequence in UTF-8
jekyll 3.0.1 | Error:  undefined method `each' for nil:NilClass
```

This error can be avoided by editing the page and replacing the ellipses character with three periods, for example:

```
... which is shown in the screenshot below:
![My helpful screenshot]({{ site.url }}/assets/screenshot.jpg)
```

Hope this helps.

**Comment by parkr** [comment]
Thanks, @ryanburnett!

**Comment by ryanburnett** [comment]
:)
