### ISSUE TITLE
Misleading parsing error line

### ISSUE THREAD

**Issue by ununhexium** [jekyll/jekyll#4272]
Hi,

I got the following error with Jekyll 3.0.1:
```
jekyll 3.0.1 | Error:  (/path/_config.yml):
did not find expected key while parsing a block mapping at line 1 column 1
```

this error comes from an indentation problem: indent by 1 space before a key that must not be indented.
The wrong indentation is several lines later (14). Could have been much further.

Is there a way to change that to point to the correct line, first error line or which key is causing problems?

**Comment by envygeeks** [comment]
You'll need to file this ticket at Psych as that error comes directly from them and we are only forwarding it on their behalf. https://github.com/tenderlove/psych
