### ISSUE TITLE
Github Jekyll processing seems broken

### ISSUE THREAD

**Issue by nesteruk** [jekyll/jekyll#4274]
Seems that GitHub's support for Jekyll is broken - after updating recent posts, I get the category as the title, and the text of the post is all jumbled up as can be seen here: http://matkrug.com

**Comment by pathawks** [comment]
Just a link to the generated site is not terribly useful; where is the source?

**Comment by nesteruk** [comment]
matkrug.github.io but I've already fixed the bug without understanding what
the bug is. just removing body text in a few blog posts and re-adding it
without any changes caused the posts to be recreated correctly. sorry but I
cannot diagnose what the problem actually is.

On 20 December 2015 at 18:24, Pat Hawks <notifications@github.com> wrote:

> Just a link to the generated site is not terribly useful; where is the
> source?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekyll/jekyll/issues/4274#issuecomment-166128260>.
>



-- 
Dmitri Nesteruk
dmitrinesteruk@gmail.com
skype: dmitri.nesteruk

**Comment by parkr** [comment]
Please write support@github.com – we cannot diagnose your issue here, unfortunately.

**Comment by envygeeks** [comment]
As a side note, Github should email you the logs and if I remember right they also make them available via your messages dialog too no?  That said, I agree here that unless you can produce it reliably locally then it should be reported directly to Github.
