### ISSUE TITLE
Migrating from 2.x to 3.x seems to have broken custom excerpt_separator support

### ISSUE THREAD

**Issue by iphoting** [jekyll/jekyll#4278]
In my Jekyll 2.x installation, my `_config.yml` contains:
```
excerpt_separator: "<!-- more -->"
excerpt_link: "Read more &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
```

Snippet of `index.html` contains:
```
<article class="post-content">
  {% if post.excerpted %}
    {{ post.excerpt }}
    <footer>
      <a rel="full-post" href="{{ post.url | prepend: site.baseurl }}">{{ site.excerpt_link }}</a>
    </footer>
  {% else %}
    {{ post.content }}
  {% endif %}
  {% if post.linkpost %}
    {{ post.permalink }}
  {% endif %}
</article>
```
Generated pages correctly contains the appropriate "Read more" links at the `excerpt_separator` position.

However, upon upgrading to Jekyll 3.x, excerpts stopped functioning and behaved as if it was totally disabled. 

Any ideas on where/how to begin debugging?

**Comment by parkr** [comment]
What is `page.excerpted`?

**Comment by iphoting** [comment]
Thanks for catching that. I replaced `page.excerpted` to `page.excerpt` and it worked as expected.
No idea why that bit worked for Jekyll 2.x though.

Thanks for your help!
