### ISSUE TITLE
Have "--profile" memory profile Jekyll too.  Or accept --profile=mem,liquid, etc...

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4283]
Users have no insight into how much overhead Jekyll gives them, lets give them an idea.

**Comment by parkr** [comment]
This is for the CLI? I'd like to see `total` which can be broken down into time, bytes & # operations for each:

1. Markdown
2. Liquid

If you run `export BENCHMARK=true; bundle install && bundle exec script/stackprof object` you can see the object overhead in Jekyll. It's not wonderful, we make like 15 million objects for jekyllrb.com
