### ISSUE TITLE
Markdown Error

### ISSUE THREAD

**Issue by minimalchaos** [jekyll/jekyll#4291]
The current jekyll version does not seem to detect kramdown or redcarpet after setting it via config.yml even though the gems are installed. Am I doing something wrong ?

**Comment by parkr** [comment]
Hello, thanks for your report. Without more information, I won't know how to proceed. Would you either the source of your site or your config, as well as sharing your OS and the Jekyll version you're running?

**Comment by parkr** [comment]
If there is a stacktrace, please also provide that.

**Comment by minimalchaos** [comment]
Im running Jekyll 3.0.1 on Windows 10

here is my gem list 
![image](https://cloud.githubusercontent.com/assets/14039227/12011068/cf3b99fa-ace5-11e5-82ac-6a4d6d6a3125.png)

and here is the build error
![image](https://cloud.githubusercontent.com/assets/14039227/12011065/ad39d2fe-ace5-11e5-9a8c-7820bdeaebeb.png)

**Comment by minimalchaos** [comment]
I had to add jekyll-archives to my gemfile to fix this. I wonder why this error for that mistake.
