### ISSUE TITLE
recreate source from build

### ISSUE THREAD

**Issue by mjhea0** [jekyll/jekyll#4302]
Is it possible to recreate the source files based on the build?

**Comment by envygeeks** [comment]
Hello, this is not a bug in Jekyll so please ask your question at https://talk.jekyllrb.com. Thanks.

**Comment by mjhea0** [comment]
ty

**Comment by parkr** [comment]
Thanks for making the topic! https://talk.jekyllrb.com/t/recreate-source-structure/1718
