### ISSUE TITLE
Fail to build on the github?!

### ISSUE THREAD

**Issue by dotku** [jekyll/jekyll#4316]
I just jekyll under my github.io/blog directory.

    jekyll new blog

After I pushing to the git, I received the error message from github as below:

    The page build failed with the following error:

    A file was included in `blog/about.md` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink.

    If you have any questions you can contact us by replying to this email.

Well, about.md is not a symlink file; I also place a about.html file under _includes, but it seems doesn't work.

**Comment by parkr** [comment]
Look at the include tags in your blog/about.md. One of these doesn't exist. I agree that the error could be improved.

**Comment by parkr** [comment]
Closing as abandoned or, presumably, fixed. :)
