### ISSUE TITLE
with_toc_data with Japanese

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll#4317]
I have a markdown file in Japanese.

A header might look like:

`## アプリケーション・ストリングの翻訳`

The generated HTML looks like:
`<h2 id=">アプリケーション・ストリングの翻訳</h2>`

As you can see, it's not just that it leaves it empty, it generates invalid HTML (missing closing quote), breaking the entire page.

PS. I am using redcarpet

**Comment by parkr** [comment]
Thanks for the report! It looks like a problem with RedCarpet to me. Please bring it up on vmg/redcarpet!

**Comment by nasht00** [comment]
For reference: https://github.com/vmg/redcarpet/issues/538
