### ISSUE TITLE
Liquid Exception

### ISSUE THREAD

**Issue by alexanderdunne** [jekyll/jekyll#4320]
Hi, I'm really new to coding and I'm having a go with Jekyll. I tried making a new site, I entered 

'jekyll new site'
'jekyll serve' 

then it went on to say 
Build Warning: Layout 'post' requested in portfolio/_posts/2016-01-04-welcome-to-jekyll.markdown does not exist.
     Build Warning: Layout 'post' requested in blog/_posts/2016-01-05-welcome-to-jekyll.markdown does not exist.
     Build Warning: Layout 'post' requested in site/_posts/2016-01-05-welcome-to-jekyll.markdown does not exist.
  Liquid Exception: Included file '_includes/icon-github.html' not found in site/about.md
jekyll 3.0.1 | Error:  Included file '_includes/icon-github.html' not found

I'm really confused, I would really really appreciate it if someone helped. I know it may be an obvious answer but I'm just trying to learn :')

**Comment by envygeeks** [comment]
Hi, this issue is not a Jekyll bug please ask your question at https://talk.jekyllrb.com as this medium is for bugs only.

**Comment by parkr** [comment]
> jekyll 3.0.1 | Error: Included file '_includes/icon-github.html' not found

It looks like you don't have a file called `_includes/icon-github.html`. You probably didn't enter the `site` directory. Make sure you `cd site` (on Mac or Linux).

**Comment by pizzapgh** [comment]
cd to the _site directory or the jekyll directory you named?

**Comment by pizzapgh** [comment]
C:/Users/chris/dropbox/webprojects/tacos4fun/funtacos/_site/_site it works when I cd to _site but when I cd to _funtacos it gives me this liquidation error the op is getting.

**Comment by ashmaroli** [comment]
@pizzapgh, if your jekyll version is <3.2.0 and your blog has been installed at `~tacos4fun/funtacos`. Simply examine the directory contents at that location. You should have a `_includes/icon-github.html` too
On your terminal, `cd` to `C:/Users/chris/dropbox/webprojects/tacos4fun/funtacos/` and then run `jekyll serve`

**Comment by vsharma030** [comment]
I am also new this and i was facing the same issue. But i was succeed in overcoming this error. 
I suggest you to follow below steps:
0. Check you are in correct directory and and see whether its there or not ( ls ) command.
1. Change Directory :-  cd yourwebsitename
2. jekyll serve yourwebsitename 

This worked for me
