### ISSUE TITLE
Remove profanity from documentation

### ISSUE THREAD

**Issue by dotancohen** [jekyll/jekyll#4321]
The Jekyll documentation currently contains this passage:

> Getting Jekyll installed and ready-to-go should only take a few minutes. If it ever becomes a pain in the ass, please file an issue (or submit a pull request) describing the issue you encountered and how we might make the process easier.

I propose this variant with the profanity removed which keeps the message intact:

> Getting Jekyll installed and ready-to-go should only take a few minutes. If it ever becomes a pain, please file an issue (or submit a pull request) describing the issue you encountered and how we might make the process easier.

**Comment by envygeeks** [comment]
Can you please file a pull request with your suggested changes?  Thanks.

**Comment by parkr** [comment]
I'm :+1: for these changes. Sorry that the profanity hung around. Thanks for spotting and reporting it! :heart:

**Comment by Epitaph64** [comment]
There's a period missing at the end of the sentence now. Minor issue though.
