### ISSUE TITLE
Cannot build depending on the site path

### ISSUE THREAD

**Issue by oalbiez** [jekyll/jekyll#4324]
We are building jekyll inside docker. We have an error depending on the path of the site.

When the site is located into `/site`, we have the following error:

    root@5fe143ffcf81:/site# jekyll build -t
    Configuration file: /site/_config.yml
                Source: /site
           Destination: /site/_site
     Incremental build: disabled. Enable with --incremental
          Generating... 
    /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/utils.rb:117:in `initialize': No such file or directory @ rb_sysopen - /sitemap.xml (Errno::ENOENT)
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/utils.rb:117:in `open'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/utils.rb:117:in `has_yaml_header?'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/reader.rb:43:in `block in read_directories'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/reader.rb:43:in `select'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/reader.rb:43:in `read_directories'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/reader.rb:17:in `read'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:144:in `read'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:57:in `process'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/command.rb:28:in `process_site'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:60:in `build'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:35:in `process'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /var/lib/gems/2.1.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'

When we move our site into `/workspace` directory it's work:

    root@5fe143ffcf81:/workspace# jekyll build
    Configuration file: /workspace/_config.yml
                Source: /workspace
           Destination: /workspace/_site
     Incremental build: disabled. Enable with --incremental
          Generating... 
                        done in 0.299 seconds.
     Auto-regeneration: disabled. Use --watch to enable.

It's also works when the site is located into `/workspace/site`

Our configuration:

    # jekyll --version
    jekyll 3.0.1
    # ruby --version
    ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

**Comment by parkr** [comment]
This is a known bug: #4011 with a fix: #4026. As a workaround for now, either:

1. Don't place your site source in a direct subdirectory of `/`, use `/srv/site` or something at least 2 dirs deep
2. Rename site source dir to something that doesn't match the beginning of any of the files in the site source. `/site` uses `site` which matches `sitemap.xml`.
