### ISSUE TITLE
Embeding Javascript inside markdown files

### ISSUE THREAD

**Issue by jessp01** [jekyll/jekyll#4325]
Hello all,

I was to supporting the following inside a markdown file so that it renders as actual Javascript on the auto generated _site/ HTML page:
```
<div style="width: 60%;display: inline-block;position: relative;">
        <div id="dummy" style="margin-top: 56.25%;"></div>
        <div id="kaltura_player" style="position:absolute;top:0;left:0;left: 0;right: 0;bottom:0;border:solid thin black;">
        </div>
    </div>
    <script src="https://cdnapisec.kaltura.com/p/1829791/sp/182979100/embedIframeJs/uiconf_id/32334692/partner_id/1829791"></script>
    <script>
        kWidget.embed({
            "targetId": "kaltura_player",
            "wid": "_1829791",
            "uiconf_id": 32334692,
            "flashvars": {
            "streamerType": "auto",
            },
            "cache_st": 1450868353,
            "entry_id": "1_ddrwr3yz"
        });
    </script>
```

I cannot use an include file for that because the embed will change according to the video entry one wishes the embed.

The way I achieve the above code is by extending [OneBox] (https://github.com/discourse/onebox) to generate Kaltura video embeds. That works fine and then I can just:
{% onebox http://www.kaltura.com/tiny/sj0h8 %}

Which generates the embed code above. However, alas, all double quotes chars are escaped and so it becomes:
```
      kWidget.embed({
            &quot;targetId&quot;: &quot;kaltura_player&quot;,
            &quot;wid&quot;: &quot;<em>1829791&quot;,
            &quot;uiconf_id&quot;: 32334692,
            &quot;flashvars&quot;: {
            &quot;streamerType&quot;: &quot;auto&quot;,
            },
            &quot;cache</em>st&quot;: 1450868353,
            &quot;entry_id&quot;: &quot;1_ddrwr3yz&quot;
        });
```
which naturally does not work. How can I escape the '"' char so that the Jekyll engine leaves it as is?
I tried '\"' but that did not work either.

Thanks,

**Comment by envygeeks** [comment]
Jekyll does not alter the content of your files, you will need to ask this question on the markdown processor you chose to use a it is the one that transforms the content.

**Comment by jessp01** [comment]
Thank you, @envygeeks.
You are right of course. 
For those interested who may have hit the issue, I changed back to kramdown from redcarpet and also, had to make sure the onebox engine I created does NOT indent the JS code at all, when doing it like that, it worked great, when indenting, it automatically insisted on placing '<code>' tags around the JS code, which, of course, made it not function.
