### ISSUE TITLE
Your builds have been broken for days.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4327]
Hi,

This is an automatic message to let you know that your builds have been broken for days.  I have pulled your logs from Travis-CI and analyzed them for you.

```
Failure: 
TestKramdown#test_:
  kramdown when a custom highlighter is chosen should use the chosen highlighter if it's
  available.  [/home/travis/build/jekyll/jekyll/test/test_kramdown.rb:73]
Minitest::Assertion: Failed refutation, no message given
```

```
Failure:
TestKramdown#test_:
  kramdown when a custom highlighter is chosen should support legacy enable_coderay...
  for now.  [/home/travis/build/jekyll/jekyll/test/test_kramdown.rb:93]
Minitest::Assertion: Failed refutation, no message given
```

I have done an `git bisect` for you and discovered that https://github.com/jekyll/jekyll/commit/dab53a697b8f58db9bef819dc9b6f5c3a592fe56#diff-c1d5392333c096c4a80c604fd595395dR189 is the commit that breaks your builds.  I can revert this command for you if you like: `hulk +revert:dab53a6 ++use-revert-commit`

**Comment by parkr** [comment]
I reverted that in a1b39840bbf00d2acf1f5c84213d6e5692dfe0a4

**Comment by envygeeks** [comment]
Hulk had a dirty cache which reported a past bisect, the issue is real, the reason is wrong.

**Comment by envygeeks** [comment]
This issue is resolved.
