### ISSUE TITLE
Permalink time variables not working?

### ISSUE THREAD

**Issue by guypursey** [jekyll/jekyll#4336]
This [page on Jekyll permalinks](http://jekyllrb.com/docs/permalinks/) says that you can use the `permalink` field in `_config.yml` to specify a preferred format for one's post and page pathnames. I would really also like to use the `:hour` and `:minute` variables, both of which are mentioned.

I've tried renaming my file to include the hour and minute as well but the variables don't seem to render properly when I serve the site.

This is what I tried in `_config.yml`:

    Permalink: "/blog/:year:month:day:hour:minute-:title"

Expected result: `2016-01-10-11-00-post-title.html` should become `/blog/201601101100-post-title.html`

Actual result: `2016-01-10-11-00-post-title.html` becomes `/blog/20160110:hour:minute-post-title.html`

Am I missing something or do these variables not work?

**Comment by Altiano** [comment]
You need to inlcude the `hour` and `minute` in you post filename
http://jekyllrb.com/docs/permalinks/

**Comment by guypursey** [comment]
Thanks for the response. I did include the `hour` and `minute` values in the post filename; see the inputs for the expected and actual results my OP.

**Comment by Altiano** [comment]
Maybe you could ask it on talk.jekyllrb.com

**Comment by parkr** [comment]
I believe the docs are wrong. We don't currently support the time in the filename, only the date. Add a `date` item in your front matter with the time and this should work.

Maybe we could throw an error when someone requests a property that doesn't exist.
