### ISSUE TITLE
[Question] How to scope the posts in pagination variable?

### ISSUE THREAD

**Issue by Altiano** [jekyll/jekyll#4337]
This is my directory structure
```
--css
--js
--images
--topics
     subdir-a
       _post
            2012-12-12....html
     subdir-b
       index.html
       _post
            2012-12-12....html
            2012-12-12....html

```
How to limit the posts being displayed using the `paginator.posts` to only posts relative to the parent folder (in this case: `subdir-b`)?
Is there a method like `paginator_relative`?

**Comment by chrisfinazzo** [comment]
In the future, please use [Jekyll Talk][] for these kinds of questions. If there is an actual bug that should be reported, it will eventually land here.

[Jekyll Talk]: https://talk.jekyllrb.com

Regarding this specific issue, the closest thing I can see in the [documentation][] is `paginate_path`, but that only specifies the destination. Hmm...

[documentation]: http://jekyllrb.com/docs/pagination/

**Comment by parkr** [comment]
Scoping of input for pagination is not supported. You're asking for category or similar support, which is not available.

https://github.com/jekyll/jekyll-paginate/issues/4

**Comment by sverrirs** [comment]
Here is a re-written pagination plugin I've recently finished, could be a viable alternative for you. https://github.com/sverrirs/jekyll-paginate-v2
