### ISSUE TITLE
Jekyll crashes when a post directly starts with a highlight section

### ISSUE THREAD

**Issue by doekman** [jekyll/jekyll#4339]
A post which directly starts with a highlight tag makes Jekyll (liquid) crash with an exception. It probably can't create an excerpt in this situation. When one paragraph is present before the `highlight` part, everything is fine.

Exception:

>   Liquid Exception: undefined method `t' for nil:NilClass in /Users/doekman/prj/GitHub/doekman.github.io/_drafts/test.md/#excerpt
> /Library/Ruby/Gems/2.0.0/gems/liquid-3.0.6/lib/liquid/block.rb:114:in `assert_missing_delimitation!': undefined method `t' for nil:NilClass (NoMethodError)

File content:

    ---
    layout: post
    title:  "To crash Jekyll"
    ---

    {% highlight JavaScript %}

    function isLeapYear(year) {
      if (year % 4) {
        return false;
      } else {
        if (year % 100) {
          return true;
        } else {
          if (year % 400)
            return false;
          else return true;
        }
      }
    }

    {% endhighlight %}

**Comment by envygeeks** [comment]
This is happening because you did not wrap the source in `{% raw %}` not because the file starts with `{% highlight %}` try wrapping everything inside of `{% highlight %}` with `{% raw %}`.  I consider this a non-issue because this is technically a Liquid issue but I thought somebody recently submitted a commit to fix this issue, either way, the former should fix it regardless.

**Comment by doekman** [comment]
I see your point. Just learning Jekyll & Liquid now.

The `welcome-to-jekyll.markdown` page (generated with `jekyll new`) doesn't include these `{% raw %}` tags. I'm not sure if they are normally necessary...

**Comment by envygeeks** [comment]
As long as I've been using Liquid they have been necessary for stuff that might interfere with the Liquid parser.  There are ways to work around it, the lot of them kind of complicated, I remember doing it in one of my apps was so complicated we ended up throwing it away.

**Comment by doekman** [comment]
Let's not go there ;-)
