### ISSUE TITLE
Auto create HTML files with Liquid

### ISSUE THREAD

**Issue by Justthingsido** [jekyll/jekyll#4346]
Hello, this might sound a little bit weird, or probably out of place. But recently I have found my self creating single page websites, and for this I use .yml file to add data to each section  on pages. 

Ex. I would create a about.yml, services.yml, etc.  For each of this sections I would create a new jade>html file that then I would include into my index.html. 

So I was thinking, is it possible to automate this? I mean, could I use a for example sections.yml file which would have the name of the sections as well some class names and ID etc. You know have different properties and Data that each section would have. And based on this auto create the html file? 

For example. Let's imagine I have the following in my sectionsData.yml 

    Sections: 
         - section: about 
           class: about
           id: about
           href-atr: #about
         - section: services 
           class: services 
            ..... 

And I would have a something like sections.jade (which would later on compile to html using gulp-jade)that would have the filling liquid code.  (Just a hypothetical exaple) (.jade file

    {% for section site.data.sections.sectionData %}
    {% create file sectionname %} 
    //with the following markup 
    section(class="{{section.name}}"id"{{section.id}}")
        section-wraper
             Section-container
     {% endfor %}

Something like that. It's just hypothetical,  maybe my laziness is making me ask this question but do you think it is possible? Or is there any other tool using gulp or something that would allow the creation of a file by reading .yml file? 

I think that I we could do something like this, jekyll wouldn't be so static anymore sine. We would be able to create new sections or pages, by adding a few likes to a .yml file that is if it becomes a supported plug-in in git hub, etc. 

It might be a long post, so I hope I made my crazy idea somewhat understandable.

**Comment by parkr** [comment]
Have you seen our data files feature? 
http://jekyllrb.com/docs/datafiles/

**Comment by Justthingsido** [comment]
@parkr I have but nothing relevant.

**Comment by envygeeks** [comment]
Just my opinion but I think this is better suited as a plugin.

**Comment by wjdp** [comment]
Possibly not the cleanest implementation but may be of use: https://github.com/newtheatre/history-project/blob/278a79d3c065cf87502fcc198e9c151ae769cf84/_plugins/venue.rb

Using an array (`site.data["shows_by_venue"]`) pages are generated. This is generated at build time but could also be defined by a file in the _data directory.

**Comment by pathawks** [comment]
Why not just do it with pages that are all front matter with no content?

**Comment by Justthingsido** [comment]
@pathawks the idea is to be able to automate the creation sections, so that later on yee can be included into whatever page we want. In my case all this goes into index .html page. 

Actually,  could you elaborate more o. What you just said? How would we do that?

**Comment by envygeeks** [comment]
@pathawks @Justthingsido @parkr I think that documentation is out of date, when I was in that source last week I thought it was supported everywhere (at least the front-matter only yaml data files)

**Comment by parkr** [comment]
@justthingsido Reading through this again, it sounds like a perfect fit for any page in Jekyll. Create a sections.html and plop your data in there with `layout: singlepageapp`. In `_layouts/singlepageapp.html`, write your template. Jekyll doesn't have any Jade processing so any jade you write will end up as Jade, not as HTML. Every time you change the metadata in your page, Jekyll will re-render the site.

**Comment by parkr** [comment]
If you're jncluding them on index.html, I would use our Collections feature and have a collection called "sections" that follows the above.
