### ISSUE TITLE
Jekyll fails to serve under Manjaro Linux, due to a load error with jekyll-redirect-from

### ISSUE THREAD

**Issue by fusion809** [jekyll/jekyll#4351]
Hi,

I have installed Jekyll 3.0.1 on my Manjaro Linux machine by running:
```bash
$ gem install jekyll
```
in my Jekyll site's folder (and yes the `$` denotes that this is as standard, non-root user) and after it installs without any obvious errors, I ran:
```bash
jekyll serve
```
from my Jekyll site's root folder this returned the error:
```bash
Configuration file: /home/fusion809/GitHub/fusion809.github.io/_config.yml
/home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-redirect-from (LoadError)
	from /home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
	from /home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `each'
	from /home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `require_gems'
	from /home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
	from /home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
	from /home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
	from /home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
	from /home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /home/fusion809/.gem/ruby/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/fusion809/.gem/ruby/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/fusion809/.gem/ruby/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/fusion809/.gem/ruby/2.3.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/fusion809/.gem/ruby/2.3.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/fusion809/.gem/ruby/2.3.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
	from /home/fusion809/.gem/ruby/2.3.0/bin/jekyll:23:in `load'
	from /home/fusion809/.gem/ruby/2.3.0/bin/jekyll:23:in `<main>'
```

I have attempted to fix this error by running `gem install jekyll-redirect-from` but this did not fix the issue at all. Installing an older version of Jekyll (namely 2.4.0) with Bundler worked and is serving fine with `bundle exec jekyll serve`, but I would prefer to be using the latest version if possible. 

Thanks for your time,
Brenton

**Comment by envygeeks** [comment]
Either choose to use bundler or choose not to use bundler, gem install does not use bundler, bundler does not use gem install.  Gem can use your Bundle file, but it does not use Bundler to do that.  That said, pick one or other because you are flip flopping on install methods.

Add `jekyll-redirect-from` to your Gemfile: https://jekyllrb.com/docs/plugins/#installing-a-plugin for Jekyll 3.0 (this is the preferred method.)

**Comment by envygeeks** [comment]
if you have any further questions or problems please ask your questions at https://talk.jekyllrb.com as at this time I feel this is not a bug in Jekyll but an edge created by odd usage.

**Comment by envygeeks** [comment]
It seems I misread what is going on I didn't notice you explictly chose to use bundler so ignore that flip flopping comment.  However the solution I pointed to should work if you do not wish to use bundler, you still need to add the gem to your list of gems for Jekyll.

If it doesn't work at that point please do let us know.
