### ISSUE TITLE
{% highlight %} blocks fail to preserve initial whitespace

### ISSUE THREAD

**Issue by mitza-oci** [jekyll/jekyll#4352]
Source code highlighting must preserve initial whitespace at the start of a block.  See http://mitza-oci.github.io/test-gh-pages/2016/01/13/test-highlight.html for an example.  Pygments and rouge (unclear which is actually use) seem to handle this OK based on their documentation and live test sites.  The whitespace seems to be incorrectly stripped at the Jekyll/Liquid level.

A workaround can be applied when running Jekyll locally, but it requires adding 'nowrap' to the {% highlight %} directive which is not considered 'safe' by GitHub.

**Comment by pathawks** [comment]
Yes, [the code seems to agree](https://github.com/jekyll/jekyll/blob/v3.1.0.pre.beta1/lib/jekyll/tags/highlight.rb#L45) that the highlight tag intentionally strips whitespace at the start of a block.

**Comment by envygeeks** [comment]
Link to your source.

**Comment by mitza-oci** [comment]
https://github.com/mitza-oci/test-gh-pages/blob/gh-pages/_posts/2016-01-13-test-highlight.html

**Comment by parkr** [comment]
We have seen this before: https://github.com/jekyll/jekyll/issues/3265
It was fixed in https://github.com/jekyll/jekyll/pull/3278.

This will be solved once GitHub upgrades to Jekyll 3, which has the fix. Track that progress here: github/pages-gem#175

**Comment by envygeeks** [comment]
I thought that too but you were quicker than me since you remembered the ticket, I was actually in Github cloning the source and double checking.
