### ISSUE TITLE
Attempting to set custom extension in permalink fails

### ISSUE THREAD

**Issue by chrissheppard41** [jekyll/jekyll#4354]
Hi guys,

Hopefully I can get some help with this because this seems like an issue more than anything else. I'm trying to change the default ".html" extension to ".htm" when building my website and i've attempted a few ways to achieve this end goal, unsuccessfully:

1:
In the .md files Front Matter, i've changed the perma link to say: "/test.htm" but when building it outputs the file: "test.htm.html". I think someone said somewhere down the line that Jekyll supports "." characters within the permalink but doesn't treat it as a extension which brings me to attempt 2.

2:
Collections in _config.yml I've outputted this:

```
collections:
  structure:
    output: true
    output_ext: .htm
    permalink: /:path/:title:output_ext
```

and still I can't get the extension of file changed.

I have managed to "break" a solution. On the permalink of the .md file i've set this: /:title.htm:htm and that's outputted the correct url that I want but that feels more like a bug. 

Any help, on how I can achieve this, or if it's possible?

Regards
Chris

**Comment by parkr** [comment]
(1) was fixed by #4314. I don't believe (2) is valid at all given that this document metadata (i.e. `output_ext`) is not inherited by documents from collections, so that's not possible. In v3.1, though, (1) will work.

What is your motivation for using `.htm` over `.html`? `.htm` is considered antiquated by many in the web industry today. Curious why you need that output extension.

**Comment by chrissheppard41** [comment]
Hi, I thought that ticket was related but I'd thought it'd throw the question in anyway.

The company I work for uses .htm, and they wont change it for SEO purposes no matter what I say. There is nothing I can do about this unfortunately, I would use .html all day long

**Comment by envygeeks** [comment]
Tell them that Google has tools that can solve this problem for them.  Check out Google webmaster.

**Comment by chrissheppard41** [comment]
Thank you Envygeeks, will do
