### ISSUE TITLE
`jekyll new` should add a Gemfile and tell people to use Bundler

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#4358]
One of the most common problems we run into are installation and version problems. Using Bundler could help alleviate these issues and streamline the experience of working with Jekyll, its plugins and all their versions.

/cc @jekyll/core

**Comment by envygeeks** [comment]
Should probably attach it to the site so a grep can be done to just merge and change everything on the site to using `bundle install` and `bundle exec`, this will also reduce our surface with OS X and others since we can now say "our official way is non-system wide installs"

**Comment by chrisfinazzo** [comment]
See #4368 for work on this issue.
