### ISSUE TITLE
Missing dependency: kramdown

### ISSUE THREAD

**Issue by alidcastano** [jekyll/jekyll#4360]
When I try to run jekyll serve, I get the following error: 

```
 Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2015-7-15-prestigious-safety-cushion.md':
                    Missing dependency: kramdown
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Missing dependency: kramdown
```

If I run bundle exec jekyll serve --watch, the server runs but the CSS doesn't load and I get the following error in main.css: 

```
Error: Invalid CSS after "@charset "utf-8"": expected "{", was ";"
        on line 4 of ./Projects/alidcastano/css/main.scss
```
 
I've tried uninstalling and updating kramdown, as suggested, but that didn't fix the problem.
I also installed the previous version of jekyll (now I only have 3.01) , but that didn't work either. 

What else can I do to try to fix this? Thanks

**Comment by envygeeks** [comment]
I don't remember if our rewrite landed in 3.0.1 can you try it with master and see if that still happens?

**Comment by alidcastano** [comment]
Do you mean the master branch? I didn't make any changes, really. I was just writing articles in markdown files. In case that's what you meant, I checked out and committed the changes. 


It gave me an error saying: 
```
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find jekyll-2.4.0 in any of the sources (Bundler::GemNotFound)
```
so I reinstalled it... and now same error shows up.

**Comment by parkr** [comment]
I'm really confused as to what you're doing here. Can you please provide step-by-step instructions for how to reproduce? A site source, Jekyll version, and operating system information is needed.

The following error means that you should find all `@charset` declarations in your code and add `;` to the end of the line.

```text
Error: Invalid CSS after "@charset "utf-8"": expected "{", was ";"
```

**Comment by alidcastano** [comment]
Figured out the problem....

So when I had gem 'github-pages' in my gemfile and did bundle update, it reverted jekyll version back to 2.4.0. So when I tried to run jekyll serve it gave the error posted above. 

Now that I removed github pages gem, it allowed me to update the jekyll version to 3.0.1 and the server is running now. 
(Concidently, I ran into a similar conflict [here](https://github.com/jekyll/jekyll-compose/issues/35) with github pages and jekyll-compose.)


Now, when my site is ready, will I not be able to use the gem and host my site in github pages?

**Comment by envygeeks** [comment]
@alidcastano you'll have to wait for Github pages to update their source and push out Jekyll 3.

**Comment by parkr** [comment]
Yeah, @envygeeks is right. GitHub Pages has to upgrade. You can follow the progress here: github/pages-gem#175.

In the meantime, you can push the contents of `_site/` to [the branch which builds on GitHub](https://help.github.com/articles/user-organization-and-project-pages/). That's [what Jekyll does for jekyllrb.com](https://github.com/jekyll/jekyll/blob/281f75182e63998d1fb823aee4f9562aa1f6fded/rake/site.rake#L52-L100), actually.
