### ISSUE TITLE
-bash: jekyll: command not found

### ISSUE THREAD

**Issue by Nnamso** [jekyll/jekyll#4365]
Error that i get 

-bash: jekyll: command not found

it was working well yesterday. i tried again today. thats what i get.

**Comment by envygeeks** [comment]
Unfortunately this is a systems problem and we do not provide systems support at Jekyll.  My suggestions would be to check and see if somebody uninstalled Jekyll if you did a global install or deleted your vendor folder if you did a bundle install.
