### ISSUE TITLE
How install jekyll on Linux Mint

### ISSUE THREAD

**Issue by EdgarOliveira** [jekyll/jekyll#4367]
Hello everyone,

I tried run "sudo gem install jekyll" but received this message:

ERROR:  Error installing jekyll:
	jekyll requires Ruby version >= 2.0.0.

The output the command "ruby -v" is: ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
Already ran the command "sudo apt-get install ruby-full", but the version ruby didn't change!

How can I fix that?
Thanks

**Comment by envygeeks** [comment]
You need to install Brightbox Ruby 2+ from the PPA or Ruby 2.0+ which the latest Mint should have.  We do not support Ruby 1.9.3 which default Ruby on Ubuntu provides to Mint.

**Comment by envygeeks** [comment]
Sorry, forgot to add, the package is `ruby2.0`

**Comment by parkr** [comment]
If you don't want to install Ruby on your system, you can use [our docker containers](https://github.com/jekyll/docker) instead.

**Comment by EdgarOliveira** [comment]
Hello everyone,

After post my question here I ended up solving following this steps:

1. sudo apt-get install curl;
2. Install RVM - Ruby Version Manager:
  * gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  * \curl -sSL https://get.rvm.io | bash -s stable
3. source ~/.rvm/scripts/rvm;
4. sudo apt-get isntall ruby-2.2.0
5. sudo apt-get install nodejs
6. gem install jekyll

I don't know if this is a place better to throw this question, but I prefer Vagrant instead Jekyll. But, I'm still studying how Jekyll do and what her proposer.

Thanks
