### ISSUE TITLE
Jekyll caching html files / not rebuilding entire _site?

### ISSUE THREAD

**Issue by tejbirwason** [jekyll/jekyll#4369]
I have a jekyll blog running at http://www.tejbirwason.com. Repo link: https://github.com/tejbirwason/tejbirwason.github.io

I wanted to add my resume as a simple html file, so following instructions [here](http://jekyllrb.com/docs/pages/) I created a resume/index.html. However http://www.tejbirwason.com/resume never got updated with my changes except once (the first time).

Finally, I tried renaming the resume/ -> cv/ to show the latest version http://www.tejbirwason.com/cv which works fine but the old link (http://www.tejbirwason.com/resume) STILL WORKS! 
It should not link to anything, making me wonder whether jekyll caches files or whether I am handling the files incorrectly.

Where is it finding this old resume/index.html, when I have already moved it to cv/index.html.

I would really appreciate some help! :)

**Comment by parkr** [comment]
Hey @tejbirwason! Sorry you're having this issue. This repository is for bugs in Jekyll only. It looks like you have found a problem with GitHub Pages, so once I'm done adding my thoughts and replying, I'm going to have to ask that you email support@github.com who can take a look at this for you. Please include a link to this issue in your request.

Did you receive an email from GitHub saying your build failed? Are you able to reproduce this locally?

Jekyll has a "clean" task when it builds which removes old files (like `resume/index.html`). Jekyll doesn't cache any files on GitHub Pages, so this would likely be a bug on their side.
