### ISSUE TITLE
Complex expression not working in {% if %}

### ISSUE THREAD

**Issue by Sidnicious** [jekyll/jekyll#4371]
I'm inexperienced with Jekyll. I created a site with `jekyll new` a while ago and just came back to it. I decided to try the installation recommended by [GitHub](https://help.github.com/articles/using-jekyll-with-pages/) to mimic the behavior of GitHub Pages, so right now I run Jekyll with `bundle exec jekyll serve` and `bundle exec jekyll --version` shows that I have version 2.4.0.

The `_includes/header.html` that `jekyll new` generated a while ago contains this:

```liquid
{% if site.pages.any? { |p| p.title } %}
    …
{% endif %}
```

The body isn't printed, even though iterating over `site.pages` shows that pages with titles exist. Changing the condition to `site.pages.any?` or even `[true].any?` doesn't output anything and no warnings or errors are printed to my terminal, but a condition of `true` works.

I assume I'm doing something wrong, but even if this isn't a bug outright whatever is happening should definitely be an error, or at least a warning, instead of silently failing.

**Comment by pathawks** [comment]
`jekyll new` generated this, you say? I cannot find that code anywhere in [the history of the `_includes/header.html` file.](https://github.com/jekyll/jekyll/commits/master/lib/site_template/_includes/header.html)

It looks like you are trying to use to use Ruby in your site template, which is not supported. Site templates are processed by [Liquid](https://github.com/Shopify/liquid).

I think you could achieve what it seems you are trying to accomplish with:

```html
{% for p in site.pages %}
  {% if p.title %}
    {{ p.title }}
    ...
  {% endif %}
{% endfor %}
```

**Comment by parkr** [comment]
Hey @Sidnicious! Unfortunately, Liquid is not quite that smart. The [documentation for `if/else` is over on the Shopfy/liquid wiki](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#if--else). It's _very_ simple as it's meant to protect the executor from user input. This is the language used to design Shopify.com templates.

```liquid
{% for otherpage in site.pages %}
  {% unless otherpage.title %}
    {% continue %}
  {% endunless %}
  ...
{% endfor %}
```

**Comment by parkr** [comment]
Oh, hey @pathawks! Thanks for your response :smile:

**Comment by Sidnicious** [comment]
Understood, thanks! Shouldn't there be a warning or an error, though, to protect people like me, instead of it just silently failing?

Is Liquid a new addition to Jekyll? The example was definitely generated by (an older) `jekyll new`, I didn't make it up.

**Comment by parkr** [comment]
> Is Liquid a new addition to Jekyll? The example was definitely generated by (an older) jekyll new, I didn't make it up.

We wouldn't have released that – Liquid has been in Jekyll since the very beginning. That looks to me like an ERB template that someone who shimmed support for ERB might have added.

> Shouldn't there be a warning or an error, though, to protect people like me, instead of it just silently failing?

Liquid has a `strict` mode, but we didn't enable it. I'll open an issue to track configuration of that.
