### ISSUE TITLE
Support Liquid `strict` parsing mode

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#4372]
Some users are seeing invalid queries/commands being swallowed by Liquid. We should test strict mode, which is available in Liquid v3 to more strictly parse Liquid templates.

Enabling it is as simple as: `Liquid::Template.error_mode = :strict`. Ideally, this would be turned on via:

```yaml
liquid:
  mode: strict
```

or similar, like `strict: true`.

Ref: https://github.com/jekyll/jekyll/issues/4371

**Comment by pathawks** [comment]
Is there some way that `jekyll doctor` could try to generate the site with Liquid strict mode?

This way, if a user just encounters a one time problem, they could run one command to diagnose, rather than modifying the site config.

**Comment by parkr** [comment]
@pathawks That's a good idea! Using `jekyll doctor` is excellent. Want to add that line to the Doctor command?
