### ISSUE TITLE
Feature request: add where_contains filter

### ISSUE THREAD

**Issue by drumanagh** [jekyll/jekyll#4385]
This would be a counterpart to the `where` filter, allowing selection by one item in an array in a variable rather than by the full contents of a variable.

For an example:

In `file-1.md`, I have
```
---
title: File 1
permalink: /file-1/
array_a:
  - dogs
  - fish
  - cats
---
```

In `file-2.md`, I have
```
---
title: File 2
permalink: /file-2/
array_a:
  - giraffes
  - lions
  - fish
---
```

In `file-3.md`, I have
```
---
title: File 3
permalink: /file-3/
---

{% assign post_list = site.posts | where_contains: 'array_a', 'giraffes' %}
{% for post in post_list %}
- {{ post.title }}
{% endfor %}
```

And the output would be:
```
- File 2
```

At the moment, the only way to do this kind of thing seems to be to do a `for` loop with an `if x.y contains z` checking over each item, which isn't a huge problem, but is less than elegant and is probably rather slower for big collections than it'd be with more built-in handling.

**Comment by davidbiehl** [comment]
How would you expect non-array values to be handled? I'm thinking it could fall-back to `where`. For example, if you had a `file-4.md` like this:

```
---
title: File 4
array_a: giraffes
---
```
Then `- File 4` would be included in the output using your example above. What do you think?

**Comment by drumanagh** [comment]
That sounds like it'd be good. It'd cover some edge cases and I can't really think of a case where you specifically wouldn't want it to behave like that.

**Comment by edgemaster** [comment]
I've implemented this with a generic where_exp filter of the form:
```liquid
{% assign post_list = site.posts | where_exp: "array_a contains 'giraffes'" %}
```
I'll reference this issue in a PR.

**Comment by yalov** [comment]
Is there a way to combine `where_exp` with `unless`? Something like:
 
`{% assign posts_noncats = site.posts | where_exp: "item", unless item.category contains 'cats'" %}`
