### ISSUE TITLE
Jekyll via JRuby on Windows fails with Permission denied error

### ISSUE THREAD

**Issue by keesvandieren** [jekyll/jekyll#4386]
We are using Jekyll via JRuby and Maven. 

Its working great on Linux and OSX.

On Windows, the following error occurs:

    [INFO] Configuration file: c:\Users\username\projects\jekyll-jruby-maven/src/main/resources/_config.yml
    [INFO] Source: c:\Users\username\projects\jekyll-jruby-maven/src/main/resources
    [INFO] Destination: c:\Users\username\projects\jekyll-jruby-maven\target\classes
    [INFO] Incremental build: disabled. Enable with --incremental
    [INFO] Generating...
    [INFO] C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/utils.rb:117:in `open': Permission denied - c
    :/Users/username/projects/jekyll-jruby-maven/src/main/resources/css (Errno::EACCES)
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/utils.rb:117:in `has_yaml_header?'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/reader.rb:43:in `block in read_directories'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/reader.rb:43:in `select'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/reader.rb:43:in `read_directories'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/reader.rb:17:in `read'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/site.rb:144:in `read'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/site.rb:57:in `process'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/command.rb:28:in `process_site'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/commands/build.rb:60:in `build'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/commands/build.rb:35:in `process'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/lib/jekyll/commands/build.rb:18:in `block in init_
    with_program'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/gems/jekyll-3.0.2/bin/jekyll:17:in `<top>'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/bin/jekyll:1:in `load'
    [INFO] from C:/Users/username/projects/jekyll-jruby-maven/target/rubygems/bin/jekyll:1:in `<top>'
    [INFO] from -e:1:in `load'
    [INFO] from -e:1:in `<top>'

The following sample project that reproduces the issue with Jekyll 3.0.2: https://github.com/squins/jekyll-jruby-maven

**Comment by envygeeks** [comment]
I don't think there is anything we can do about this, `Errno::EACCESS` is Ruby surfacing a File system issue to us, what do the permissions look like in that folder?

**Comment by keesvandieren** [comment]
Thanks for your response.

The user has 'full control' to the main folder and every subfolder.

It can user other folders; the workaround we use to continue now is to add this folder to _config.yml:

`
exclude: [css]
`

That makes jekyll serve run, but the CSS is not exposed so there is no style.

**Comment by parkr** [comment]
> We are using Jekyll via JRuby and Maven.

So interesting! This is the first I have heard of this method. Glad it's working for you on Mac & Linux!

Thanks for providing the test repo! I'll see if I can get my hands on a test machine and give it a whirl.

**Comment by envygeeks** [comment]
What is the output of:

```
dir c:\Users\username\projects\jekyll-jruby-maven\src\main\resources/css | Get-NTFSAccess
dir c:\Users\username\projects\jekyll-jruby-maven\src\main\resources/css | Get-Acl
```

**Comment by rlippolis** [comment]
I executed the above commands in a default powershell (not run as administrator). The first command didn't produce any output, the second command did:

```
> dir c:\Users\username\projects\jekyll-jruby-maven\src\main\resources/css | Get-NTFSAccess
> dir c:\Users\username\projects\jekyll-jruby-maven\src\main\resources/css | Get-Acl

Directory: c:\Users\username\projects\jekyll-jruby-maven\src\main\resources\css


Path      Owner             Access
----      -----             ------
style.css computer\username BUILTIN\Administrators Allow  FullControl...
```

**Comment by parkr** [comment]
@rlippolis No idea how to fix it sadly, but [from what I can find](https://technet.microsoft.com/en-us/library/ee176838.aspx), it should have `BUILTIN\Users Allow...`

This is definitely a systems issue. I couldn't repro locally. Sorry!

**Comment by rlippolis** [comment]
I have changed the permissions to allow everything, but still the same error message appears. This is the new output for the 'Get-Acl' command:

```
> dir c:\Users\username\projects\jekyll-jruby-maven\src\main\resources/css | Get-Acl

Directory: c:\Users\username\projects\jekyll-jruby-maven\src\main\resources\css

Path      Owner              Access
----      -----              ------
style.css computer\username  BUILTIN\Users Allow  FullControl...
```

**Comment by handylearn** [comment]
I have also "permission denied" error message with the css-path with jruby 9.0.5.0 on windows 7. 
The directories are created by jekyll itself, including the css directory. I just did "jekyll add myblog" and then "jekyl serve" in the myblog directory. It is Jekyll 3.1.1.  
I  have the suspicion that the message with "permission denied" is wrong, and another file error has happened.

**Comment by envygeeks** [comment]
Hulk was unable to reproduce it, but I'll get on a Windows server and manually try to reproduce it.  That said, if that's not the actual error that is going on that is more or less a bug with JRuby because it's the error that we were given :/ but I'll see what I can come up with and start filing tickets or fixing problems if I can reproduce it.

**Comment by handylearn** [comment]
I have done some more investigation.
 
The error is also happening in the method `has_yaml_header?(file)`, like for keesvandieren. 
But the file path "..../css" is a directory, so the method tries to read the file content from a directory and this fails on windows.

The method is called from `Reader.read_directories`, and when I understand it correctly, directories should have been filtered out. I decided to look at this later.

I have guarded the `File.open` call in `has_yaml_header?(file)` with 
```
unless File.file?(file)
        puts "has_yaml_header: not a regular file:"
        puts File.realpath(file)
        puts  File.ftype(file)
        return false   
end
```

Then the test also fires for `/km/ruby/myblog/about.md`. Furthermore, the ftype-call throws an exception:

    Errno::ESRCH: No such process

So is seem not like the way the file path is defined...

I then have used `File::realpath` to translate the file path. This is adding the volume letter to the path, in my case `d:/`. My new method looked like this:

```
def has_yaml_header?(file)
      puts "has_yaml_header #{file.inspect}"
      rfile = File.realpath(file)
      unless File.file?(rfile)
        puts "has_yaml_header: not a regular file:"
        puts  File.ftype(rfile)
        return false      
      end
      !!(File.open(rfile, 'rb') { 
        |f| f.readline 
        } =~ /\A---\s*\r?\n/)
    rescue EOFError
      false
    end

```

With this modification, the `read_directories ` succeeds, but later there is another exception, again when trying to access the `css `directory, but this time in `StaticFile::write` in  "static_file.rb:83"

**Comment by handylearn** [comment]
The "Errno::ESRCH: No such process" problem is depended on a JRuby / Native layer problem:

#https://github.com/jnr/jnr-posix/issues/61

**Comment by keesvandieren** [comment]
Maybe it has something todo with sass?

(s)css files might also be watched by the sass compiler.

Maybe the sass compiler is watching css files. Windows often is stricter with file locks then Unix / Linux is. Having two threads watching the same dir, might cause it?

**Comment by gangsthub** [comment]
I think it has to do with: [sass/libsass#1750](https://github.com/sass/libsass/issues/1750#issuecomment-161038089) or (more likely) with [file permissions](http://stackoverflow.com/questions/23822491/ruby-on-rails-permission-denied-when-using-rails-generate-controller-welcome#answer-25870769) in ruby.

It seems to work if you: 
- specify the `source: "C:/..."` of your project in your `config.yml` (yes, even if it is the **same dir** as your config file). Note: this may not be necessary at all.
- update your dependencies (`npm update`).
- [Equivalent of `chmod 777` for Windows](http://superuser.com/questions/163049/what-is-the-equivalent-of-chmod-777): (`F` comes from _Full controll_)
```
icacls .\pathto\css\file.css /grant Everyone:F
```

(Sometimes I really dislike developing in windows.)
