### ISSUE TITLE
Jekyll 3.0.2 cannot call a collection by name like site.collections.mycollection

### ISSUE THREAD

**Issue by djacquel** [jekyll/jekyll#4392]
In Jekyll 2, you can call a collection with `site.collections["myCollection"]` or `site.collections.myCollection`, and it returns the collection with all attributes (label, docs, ...).

With Jekyll 3.0.2, doing `site.collections["myCollection"]` or `site.collections.myCollection` returns nothing.

Am I missing something ?

**Comment by parkr** [comment]
Hey, @djacquel! Do you happen to have an example? I can't seem to replicate this.

**Comment by djacquel** [comment]
I reproduce it :

  1. On Github Pages with Jekyll 2.4.0 [repo](https://github.com/djacquel/jekyll-collections-test) and [preview](http://pygmeeweb.com/jekyll-collections-test/).
  `{{ site.collections.col }}` returns a collection with all attributes.

  2. locally using ruby 2.1.8 and Jekyll 3.0.2

```
git clone git@github.com:djacquel/jekyll-collections-test.git
cd jekyll-collections-test/
bundle install
bundle exec jekyll serve
```

We clearly see that `site.collections.col` returns nothing.

**Comment by envygeeks** [comment]
Hi @parkr and @djacquel; Hulk here:

My owner has helped and allowed me to pull and debug your Git repository on a secure Docker instance. I have taken your steps, striped them and done as you requested, here are your results:

```
Jekyll version : 3.0.2

site.collections.col

site.collections.col.label

site.collections.col.docs

loop in site.collections.col.docs
```

---

During my trace I noticed that `site.collections` is an `Array` (or behaves like it) and you are trying to access it like a `Hash`.  Here are the relevant sources (I may be wrong):

- https://github.com/jekyll/jekyll/blob/3.0-stable/lib/jekyll/site.rb#L276
- https://github.com/jekyll/jekyll/blob/3.0-stable/lib/jekyll/collection.rb#L168

I noticed that you are using `collections.values`, this will result in an `Array` with Ruby if used on a `Hash`, I am unreliably assuming that this is not an intended behavior based on keywords.

---

Since my owner is constantly banging on about references here are some details:

* My Host: Ubuntu 14.04
* My Kernel: 4.2.0-25-generic
* I used the Docker image `jekyll/jekyll:3.0.2`
  * It uses Alpine Linux 3.3 from envygeeks/alpine

```
docker run --rm -it jekyll/jekyll:3.0.2 jekyll --version # => jekyll 3.0.2
docker run --rm -it jekyll/jekyll:3.0.2 cat /etc/issue
# => Welcome to Alpine Linux 3.3
# => Kernel \r on an \m (\l)
```

**Comment by parkr** [comment]
Thanks, Hulk! You're absolutely right. I can't believe I forgot.

Use `site.myCollection`: http://jekyllrb.com/docs/upgrading/2-to-3/#sitecollections-has-changed

**Comment by djacquel** [comment]
@parkr , **Hulk**. I simply want to assign a collection (with all attributes) to a variable.
Obvious use case : a page that summarize collection's content. Because I need to work with `collection.label`, `collection.docs` an so on. 
I'm not talking about `site.myCollection` that only returns `collection.docs` Array. Just like `site.posts` does.
I'm talking about collections as first class citizens like they appear in jekyll 3 code or in @benbalter [article](http://ben.balter.com/2015/02/20/jekyll-collections/).

### Jekyll 2 collection's API
`{% assign collection = site.collections.myCollection %}`

This code is working on Github Pages but it will break once Jekyll 3 is in production.
OK. "[You've been warned](http://jekyllrb.com/docs/collections/)" this is an experimental feature.

### Jekyll 3 collection's API
Here's the Jekyll 3 workaround :
```
{% assign collectionName = "myCollection" %}
{% for c in site.collections %}
    {% if c.label == collectionName %}
        {% assign collection = c %}
    {% endif %}
{% endfor %}
```
Not elegant ! An not user friendly.
Can you imagine this in Jekyll documentation ?

### How to develop ?

I will not tell my clients that my work will break soon and that, they will have to pay me to upgrade to Jekyll 3.

Will I really have to push this to production (I mean Github Pages) to avoid Jekyll 3 compatibility break ?

```
{% assign collectionName = 'myCollection' %}
{% assign versionMajor = jekyll.version | split: "." | first %}
{% case versionMajor %}
  {% when '2' %}
     {% assign collection = site.collections[collectionName] %}
  {% when '3' %}
    {% for c in site.collections %}
        {% if c.label == collectionName %}
            {% assign collection = c %}
        {% endif %}
    {% endfor %}
{% endcase %}
```

Or Am I missing something ?

**Comment by parkr** [comment]
@djacquel In Jekyll 3, just do `site.myCollectionName`. You do not need to do the loop. See the link I sent as I believe it's explained there. If not, please send a PR to update that upgrading docs page!

**Comment by djacquel** [comment]
@parkr 
- `site.myCollectionName` doesn't return a collection but only collection.docs array.
- the link you've send just says that iteration in `site.collections` returns a collection instead of the jekyll 2 array [ collection.label, collection ] and I get this.
- I'm just saying that `site.collections.myCollection` is no longer working in Jekyll 3 and that the only way to get a collection is by looping in site.collections.

**Comment by envygeeks** [comment]
Hi, Hulk here.

I am verifying your claim, please stand by.

**Comment by envygeeks** [comment]
Hi, Hulk here.

I was finally able to allocate resources and with the help of my owner I have tried to replicate your issue. Per his (@envygeeks) instructions I was to make sure that "site.my_collection" was unavailable.

#### COMMANDS

```
docker run --rm --volume=$(pwd):/srv/jekyll -it jekyll/jekyll jekyll new .
hulk make jekyll debuggable

# => CREATE _layout/blank.html
# => ADD envygeeks-jekyll-tracer
# => ADD envygeeks-jekyll-mem-tracer
# => ADD envygeeks-liquid-tracer
# => SMASH _layouts
# => INSTALL

printf -- "---\nlayout: blank\n---\n\n{{ site.my_collection | escape }}\n" > index.html
mkdir _my_collection

printf -- "---\ntitle: my title\n---\n\n<p>CONTENT</p>" > _my_collection/one.html
printf -- "---\ntitle: my title\n---\n\n<p>CONTENT</p>" > _my_collection/two.html
printf "collections:\n  my_collection: " > _config.yml

docker run --rm --volume=$(pwd):/srv/jekyll -it jekyll/jekyll jekyll b
```

#### RESULT

```
<p>CONTENT</p><p>CONTENT</p>
```

---

Please verify this is accurate @parkr and @envygeeks

**Comment by djacquel** [comment]
@envygeeks my claim is : `site.collections.myCollection` is no longer working in Jekyll 3. 
NOT `site.my_collection`.

**Comment by envygeeks** [comment]
@djacquel @parkr is saying stop using `site.collections.my_collection` and start using `site.my_collection`, the old way is no longer available in 3.0 and that is not considered a bug.

**Comment by djacquel** [comment]
Well it seems that you're not understanding my concern. Let's try something else.

In Jekyll documentation we can find this

```
collections:
  my_collection:
    foo: bar
```

Can you please give me the code I can use to get this **foo** variable from anywhere in my site ?

**Comment by parkr** [comment]
Thanks for being patient with us, @djacquel. I think if we had a play.jekyllrb.com or something like that, we could more easily see the problem.

You're right. Jekyll 3 only gives you the docs array for `site.collectionName`, and `site.collections` gives you access to the collection directly, but requires finding it in the array of collections.

The previous solution where `site.collections` was a hash was undesirable because iterating over it was a pain. Maybe we can make `site.collections` both accessible via the dot syntax as a hash and iterable as an array.

**Comment by pathawks** [comment]
Can you use the `where` filter to pull out a specific collection more easily?

**Comment by parkr** [comment]
`site.collections | where:"label",collectionName`?

**Comment by pathawks** [comment]
> `site.collections | where:"label",collectionName`?

Yeah. Does that work? Seems like exactly what the filter was designed for.

**Comment by budparr** [comment]
No, ```site.collections | where:"label",collectionName?``` doesn't appear to work, in 3.1.

**Comment by pathawks** [comment]
> No, `site.collections | where:"label",collectionName?` doesn't appear to work

It sure does.

If I have a `_config.yml` with:

```yml
collections:
  my_collection:
    foo: bar
```

And a template with

```html
{% assign collectionName = 'my_collection' %}
{% assign d = site.collections | where:'label',collectionName | first %}
{{ d.foo }}
```

My output is, as expected:

```
bar
```

**Comment by budparr** [comment]
I see. I was confused by the very issue the thread brought out, I think. At any rate, sorry for muddling the issue.

**Comment by pathawks** [comment]
@budparr No worries! I wasn’t sure myself until I tried it.

**Comment by djacquel** [comment]
@parkr Right we are now talking about the same thing : the `site.collections.myCollection` API disappearing.

> Maybe we can make site.collections both accessible via the dot syntax as a hash and iterable as an array.

Yes ! Please.

**Comment by parkr** [comment]
>  >Maybe we can make site.collections both accessible via the dot syntax as a hash and iterable as an array.
>
> Yes ! Please.

@djacquel It was deliberately removed to make the iteration over `site.collections` more understandable, as I said. I'm not sure it makes sense to add as it would require a lot of weirdness. Is there anything preventing you from using the `where` syntax?

**Comment by djacquel** [comment]
@parker it's OK, I will go with the "where trick".
