### ISSUE TITLE
Custom permalink with :title

### ISSUE THREAD

**Issue by yazinsai** [jekyll/jekyll#4395]
I've defined permalinks in my `_config.yml` as:
```yml
permalink: /:categories/:title/
```

However, there 1 particular post that I'd like to have with a permalink of `:title/`.

When I try to place that in the post frontmatter like so:

```yml
title: This is my post title
permalink: /:title/
```

The generated permalink is `/:title/` instead of `/this-is-my-post-title/`.

Is this expected behavior? (If so, then I have no issue just typing out the title in text)

**Comment by parkr** [comment]
What version of Jekyll are you using? I don't think we don't do interpolation on permalinks.

**Comment by yazinsai** [comment]
jekyll 2.4.0

**Comment by yazinsai** [comment]
Just realized how old that is .. upgrading.

**Comment by yazinsai** [comment]
Update fixed it, sorry for the nuisance @parkr

**Comment by parkr** [comment]
No problem at all! In the future, check out https://talk.jekyllrb.com for usage questions like this. We escalate to these issues if something looks like a bug. Glad it's all set now though! :smile:
