### ISSUE TITLE
Propose to whitelist AutoPrefixer plugin in Github Pages

### ISSUE THREAD

**Issue by JohnStarich** [jekyll/jekyll#4396]
After reading #325, I would like to propose a plugin to be whitelisted for Github Pages.

The Autoprefixer plugin adds CSS rules to support current browsers including vendor prefixes or alternate rules in order to support more browsers out of the box.

Original Autoprefixer: [autoprefixer-rails](https://github.com/ai/autoprefixer-rails)
Jekyll Autoprefixer Plugin: [octopress-autoprefixer](https://github.com/octopress/autoprefixer)

I find this feature essential because it simplifies my CSS/Sass files considerably. With this plugin I don't need to specify many different rules in my stylesheets to do exactly the same thing in different browsers.

As an example, in Autoprefixer I only need to write `justify-content: center;` and it will generate the following for me:
```
-webkit-justify-content: center;
-ms-flex-pack: center;
justify-content: center;
```
This plugin saves me a lot of time while making websites, so I hope this may make its way to Github Pages so we might all save a little time. :smile:

**Comment by parkr** [comment]
Hey @JohnStarich! Unfortunately, we have no power to add plugins to GitHub Pages. That's for GitHub to decide. Generally speaking, they try to be fairly strict on adding new plugins, as the GitHub Security Team must review every line of every plugin that is added or upgraded so it takes quite a bit of time.

Assets in particular are a difficult topic and we should figure out what is the best approach. @envygeeks has requested `jekyll-assets` be added to GitHub Pages, and I believe the team is considering his proposal now. It allows autoprefixing with the rails addon, so if we were to consider this, we'd do it either in his proposal, or as a pull request to `jekyll-sass-converter`.

Hope this clarifies things a bit. Thanks!

**Comment by JohnStarich** [comment]
It does, thank you! Perhaps we should leave a comment on #325 letting others landing there know as well?

**Comment by jamiewilson** [comment]
@JohnStarich You could use [-prefix-free](https://leaverou.github.io/prefixfree/), which adds any needed prefixes client-side. Not as nice as prefixing at build time, but it'll at least allow you to still use gh-pages to compile from your remote repo.

**Comment by JohnStarich** [comment]
@jamiewilson Thank you! That's a great solution for me. :+1:
