### ISSUE TITLE
Jekyll 3.1.0 Issue: Permalinks with dots are broken (e.g., version numbers)

### ISSUE THREAD

**Issue by sjrd** [jekyll/jekyll#4397]
Since Jekyll 3.1.0, our permalinks for news about new releases are broken. The `index.html` file that is produced does not have the right name; it's called `index.html.1` (or another digit). Links the to the page are "correct" (end with `/`) but then their destination is a 404.

Example:
permalink: `/news/2016/01/25/announcing-scalajs-0.6.6/`
file produced: `/news/2016/01/25/announcing-scalajs-0.6.6/index.html.6`
expected: `/news/2016/01/25/announcing-scalajs-0.6.6/index.html`

The actual file (and the rest of the website's repo) can be found at https://github.com/scala-js/scala-js-website/blob/master/_posts/news/2016-01-25-announcing-scalajs-0.6.6.md
Currently I downgraded to Jekyll 3.0.1.

I suspect this comes from #4373.

**Comment by parkr** [comment]
@sjrd Sorry about that! Can you please try out my branch from #4401?

```ruby
gem "jekyll", github: "jekyll/jekyll", branch: "fix-documents-with-permalink-with-slash"
```

then 

```bash
$ bundle install && bundle exec jekyll serve
```
