### ISSUE TITLE
install jekyll problem

### ISSUE THREAD

**Issue by SilverBulletZyp** [jekyll/jekyll#4399]
When I use bash install jekyll in OS X EI Capitan,I enter the command"sudo gem install jekyll".But it show that the response is "ERROR:  While executing gem ... (Errno::EPERM) Operation not permitted - /usr/bin/kramdown".What should I do? Could you tell me the detail steps to use the command line?Thanks a lot!

**Comment by parkr** [comment]
> (Errno::EPERM) Operation not permitted - /usr/bin/kramdown

This means you don't have permissions to execute this. Run `sudo chown 755 /usr/bin/kramdown` and that should fix it up.

Generally we suggest against using `sudo` but here are some troubleshooting tips: http://jekyllrb.com/docs/troubleshooting/#jekyll-amp-mac-os-x-1011
