### ISSUE TITLE
Jekyll 3.1.0 incremental build

### ISSUE THREAD

**Issue by wwilyW** [jekyll/jekyll#4400]
Hello,
As I read, when I run jekyll serve --incremental it should rebuild after I save change in files. That don't work for me, every time when I edit file, I need to restart server. I tried it on clean install, just jekyll new sample_blog, than delete one line from sample post, reload browser and no changes.

Or maybe I omits something?

**Comment by parkr** [comment]
@wwilyW Run with `--verbose`. You'll see that only the post is regenerated, not the `index.html`. This is a known limitation! The incremental regeneration is in very early development at the moment, we're still in need of wiring up those dependencies. The post page will regenerate properly.

Stay tuned!
