### ISSUE TITLE
Jekyll date issue

### ISSUE THREAD

**Issue by vivekraj** [jekyll/jekyll#4405]
I was using jekyll dotX theme (https://github.com/nandomoreirame/dotX). Now I am facing issue while providing the post with 2016 dates. The link is not getting generated. May I know how to fix this? Tried upgrading the jekyll version with "gem update jekyll". Also found that there is no problem with new website generated using "jekyll new site_name".

**Comment by vivekraj** [comment]
I fixed it by changing the highlighter from pygments to rouge on _config.yml

**Comment by parkr** [comment]
Glad to hear you fixed it! Still not super clear on what the issue was but glad it's resolved.
