### ISSUE TITLE
Error for conflicting permalinks

### ISSUE THREAD

**Issue by chadokruse** [jekyll/jekyll#4406]
Put this in the UX/nice-to-have bucket, but it appears a Jekyll project can have duplicative permalinks without throwing an error. The page rendered seems to differ depending on host/environment.  

For example. I can specify `permalink: /bar/` in both `foo.html` at root as well as `pages/foo.html`. Jekyll will complete the build just fine. 

In my case, I forgot to delete the original `foo.html` at root while restructuring my app. Production rendered `foo.html` while local rendered `pages/foo.html`.

Wish my ruby-fu was a bit stronger for a pull request, sorry.

**Comment by parkr** [comment]
Did you try running `jekyll doctor`? It checks for duplicate output URLs.

**Comment by chadokruse** [comment]
Ah, didn't know `jekyll doctor` existed. Awesome.

**Comment by parkr** [comment]
Yep! :smile: I don't think we'd be able to error our that easily (and performantly) during the write process so I'd rather refer folks to the doctor command. Thanks!
