### ISSUE TITLE
Error while installing on Ubuntu Trusty

### ISSUE THREAD

**Issue by hultberg** [jekyll/jekyll#4416]
Hello!

I'm trying to install jekyll with `sudo gem install jekyll` on an Ubunutu 14.04 LTS 64-bit. Following the instructions on the jekyll website I get the following error:
````
ERROR:  Error installing jekyll:
        jekyll requires Ruby version >= 2.0.0.
````

When installing ruby on my box I get the 1.9.3 version, and it's obvious that jekyll needs ruby >= 2.0.0. If I remove the `ruby` package and just install `ruby2.0-dev` I'm unable to use `gem`.

Gem version: `gem -v -- 1.8.23`
Ruby version: `ruby -v -- ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]`

How to get around this?

**Comment by hultberg** [comment]
For anyone else having troubles, I managed to resolve the issue by using `rvm` and installing a newer ruby version.

1. Install RVM
2. Activate RVM
3. Install latest ruby with RVM
4. `gem install jekyll`
5. ????
6. PROFIT

close

**Comment by envygeeks** [comment]
Or you could have just `update-alternatives --config ruby`
