### ISSUE TITLE
GFM fenced code blocks regression in Jekyll 3

### ISSUE THREAD

**Issue by spikeheap** [jekyll/jekyll#4427]
I could be missing something obvious, but I don't seem to be able to get fenced code blocks to work with Jekyll 3, using a config which worked fine in 2.5.3.

Tested with Jekyll 3.1.0.

To reproduce:

```
~ $ mkdir jekyll-rouge && cd jekyll-rouge
~/jekyll-rouge $ jekyll new
```

Add the following snippets in _posts/2016-XX-XX-welcome-to-jekyll.markdown:

    ```ruby
    def print_hi(name)
      puts "Hi, #{name}"
    end
    print_hi('Tom')
    #=> prints 'Hi, Tom' to STDOUT.
    ```
    
    {% highlight ruby %}
    def print_hi(name)
      puts "Hi, #{name}"
    end
    print_hi('Tom')
    #=> prints 'Hi, Tom' to STDOUT.
    {% endhighlight %}

And to the config (for compatibility with 2.5.3) add:

```
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
```

Then:

```bash
# For 2.5.3
~/jekyll-rouge $ jekyll _2.5.3_ s

# For 3.1.0
~/jekyll-rouge $ jekyll _3.1.0_ s
```

These are the same steps as https://github.com/jekyll/jekyll/pull/4053#issuecomment-151048257. Jekyll 2.5.3 generates a syntax-highlighted code block as expected, however the same code run with 3.1.0 generates:

<img width="756" alt="welcome_to_jekyll_" src="https://cloud.githubusercontent.com/assets/464482/12696168/5af42c04-c763-11e5-9df7-ca2976145e77.png">

I believe from https://github.com/jekyll/jekyll/issues/4202 that the additional GFM config I was using for 2.5.3 is the default in 3.1.0. Removing those lines and using the stock config doesn't affect the result.

I've just rolled back to 2.5.3, which is doing just fine, so this isn't urgent for me.

**Comment by ummels** [comment]
Just stumbled over the same issue after upgrading from 3.0.1 to 3.1.1.

**Comment by jhalterman** [comment]
Hit this too going from 2.4 to 3.1.1 - GFM is DOA. 3.0.1 seems to work as @ummels suggested.

**Comment by envygeeks** [comment]
@jhalterman @ummels @parkr it's because Kramdown wants symbols, we give it strings, so we need to make the hash accessible so that we can work the way we want and Kramdown can do what it wants.
