### ISSUE TITLE
Liquid errors should show line numbers

### ISSUE THREAD

**Issue by wjdp** [jekyll/jekyll#4431]
Currently tracking down the culprit of `Liquid Exception: Liquid syntax error: Unknown tag 'endfor' in _layouts/person.html`. This would be made much easier if the liquid parser could tell me what line is causing a problem.

Unsure if this is an issue is relevant here or needs to go upstream.

**Comment by parkr** [comment]
From what I understand, we should be able to get the line number from the Liquid exception. Would you mind taking a crack at this and submitting a PR? Thanks!

**Comment by wjdp** [comment]
Yep, will do.

**Comment by wjdp** [comment]
Tracked down StandardError in liquid, looks like if the line number is known it would be in the message anyway. *Line 38 https://github.com/Shopify/liquid/blob/master/lib/liquid/errors.rb*

Seems `line_number` has not been assigned. :disappointed:

**Comment by parkr** [comment]
@fw42 @pushrax Know why a line_number wouldn't be assigned?

**Comment by pushrax** [comment]
Need to set the `line_numbers` option to `Template.parse` https://github.com/Shopify/liquid/blob/master/lib/liquid/template.rb#L118

**Comment by parkr** [comment]
@pushrax like in #4452?
