### ISSUE TITLE
Layout inheritance broken in Jekyll 3.1.1?

### ISSUE THREAD

**Issue by kvz** [jekyll/jekyll#4433]
Hi,

I have the following layout inheritance set up: `post.html > blog.html > default.html`.

Example of `post.html`:

```
---
layout: blog
bodyClasses: "blog-post"
---

<div>
```

How do I make a frontmatter variable called `bodyClasses`, set in `post.html`, available in `default.html`?

I have tried using `{{layout.bodyClasses}}` as well as `{{page.bodyClasses}}`, but in both cases, the value set in `blog.html` is used.

I would expect layouts that inherit from parent layouts to be able to override these variables, and I think this used to work in 2.0 releases too?

**Comment by envygeeks** [comment]
The worry is if it worked in 3.0 and not 3.1, if it worked in 2.0 and not in 3.1 then that's a possible WONTFIX as feature changes are expected in major releases as SemVer implies.  Did it work in 3.0?

**Comment by kvz** [comment]
I just tested it and it doesn't work in 3.0 either. I am aware of this breaking change: http://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata and it there said that going from `page` to `layout` was to help make it clearer what gets merged. It does not mention however how the merging works if you have several layouts extending each other. In my case, an ancestor layout wins and overrides any layout extending on top of it.

Would it not make sense if the 'highest' layout would overwrite variables that ancestors have already set?

I agree that major version bumps are a legit way of doing breaking changes, so I'm all for that. I'm just wondering if a bug (or at least unpredictable behavior) could be at play here. 

Possibly related #4203 #4246

**Comment by envygeeks** [comment]
I do think it makes sense that a child should override the ancestor and it's a bit unintuitive for a child's value not to appear at all, however I'll defer the decision on if it's intended or not to @parkr as he works on that area.  I wonder if the work around isn't `{{ page.data.var | default: pay.layout.var }}` does trying the front-matter directly and then falling back to layout work?

**Comment by envygeeks** [comment]
Oh sorry, I'm bad at reading, I didn't notice you had already tried that.  Ignore that trial and error.

**Comment by kvz** [comment]
Yes this is zooming in just on `layout.var` now, where the problem is Jekyll seems unclear on how to merge child over ancestors.

I just tried the very latest `3.1.1` to see if that fixes anything, but that makes matters very worse; leaking layout variables from an unrelated layout, into the generated homepage. This screenshot might take a second to digest, but it shows a page: `home.html`, hosted at `/`, that only uses the `default.html` layout, but when generated, also has the totally unrelated layout bodyClasses from the `docs.html` layout in them:

![](https://dl.dropboxusercontent.com/s/er2n856ozuv2vso/2016-02-01%20at%2015.14.png?dl=0)

**Comment by parkr** [comment]
Hey @kvz, it looks like you figured it out from your screenshot.

> It does not mention however how the merging works if you have several layouts extending each other. In my case, an ancestor layout wins and overrides any layout extending on top of it.

This behaviour is described [on line 141 of `renderer.rb`](https://github.com/jekyll/jekyll/blob/v3.1.1/lib/jekyll/renderer.rb#L141). It looks like layout metadata from subsequent layouts override the previous metadata. So if you have `_layouts/blog.html > _layouts/docs.html > _layouts/default.html`, `docs` would overwrit `blog`, and `default` would overwrite the result of that.

**Comment by kvz** [comment]
Thanks! Is there any way we can have this behavior reversed? Maybe via opt-in?

In my opinion, ancestors should be overwritten, not overwrite, similar to extending classes in oop, or what have you :)

Without this, it's hard to take a base layout and tweak it in order to have Dry layouts

**Comment by kvz** [comment]
There still is the issue though of the `docs.html` layout leaking its layout vars into totally unrelated layouts (that's what the screenshot is about).

Is it possible the merging happens on the default layout _by reference_ or similar? Causing unrelated layouts that are, or extend on `default.html`, to also carry the layout variables set by `docs.html`?

**Comment by greenify** [comment]
Seems to be related to #4442

**Comment by axelfontaine** [comment]
+1

**Comment by parkr** [comment]
Hey, folks! Sorry you're all having trouble and for not getting to it sooner... so many competing priorities! I believe I have fixed this in #4909 😄 It will be released as a part of 3.1.4!
