### ISSUE TITLE
Default excerpt values for collections—bug or intention?

### ISSUE THREAD

**Issue by ndarville** [jekyll/jekyll#4435]
I’m upgrading to Jekyll 3.0, and the only problem I’ve run into is this:

```liquid
<meta charset="utf-8" />
<title>Asides</title>
<meta name="twitter:title" content="Asides" />
<meta name="description" content="<style type="text/css">
strong { color: #1EAEDB; font-weight: normal; }
</style>" />
<meta name="og:description" content="<style type="text/css">
strong { color: #1EAEDB; font-weight: normal; }
</style>" />
<meta name="twitter:description" content="<style type="text/css">
strong { color: #1EAEDB; font-weight: normal; }
</style>" />
```

This is with this layout code:

```liquid
<meta charset="utf-8" />
<title>{% if page.emoji %}{{ page.emoji }} {% endif %}{{ page.title }}</title>
<meta name="twitter:title" content="{{ page.title }}" />
<meta name="description" content="{% if page.excerpt %}{{ page.excerpt }}{% else %}{{ page.description }}{% endif %}" />
<meta name="og:description" content="{% if page.excerpt %}{{ page.excerpt }}{% else %}{{ page.description }}{% endif %}" />
<meta name=“twitter:description” content="{% if page.excerpt %}{{ page.excerpt }}{% else %}{{ page.description }}{% endif %}" />
```

for this page:

```liquid
---
title: Asides
description: Everything else.

layout: project
---
<style type="text/css">
    strong { color: #1EAEDB; font-weight: normal; }
</style>

<div class="row" style="margin-top: 5%">
    <header class="one-half columns" role="banner">
        <h1>{{ page.title }}</h1>
        <p>Some asides by <a href="/">{{ site.author }}</a>.</p>
    </header>
</div>
```

In other words, there is a now a new excerpt behaviour for Collections. I just wanted to bring this to attention, in case this is not the intention, because it might mess up pages relying on the same layouts that blog posts do. I missed any info about this from the changelogs.

I guess I could do something like `excerpt: “”` in each of the collections (since I can’t get default values to work in `_config.yml`), but just wanted to let you know either way!

Grats on shipping to `github-pages`; can’t wait to use round in my liquid tags now. :)

**Comment by parkr** [comment]
Hey, @ndarville! This is expected behaviour, as now that posts are `Document`s, the `Document` class now uses the post excerpt functionality. Setting `excerpt: ""` in your collection documents will, as you mention, solve this issue.

You can't get default values to work? That would be something we'd want to fix for a 3.0.3. Could you file an issue or surface one that describes your issue? Thanks. :smile: 

> Grats on shipping to github-pages; can’t wait to use round in my liquid tags now. :)

Whee! We're super stoked to have Jekyll 3 _finally_ :ship:'d. Nice to have the projects starting to align. :)
