### ISSUE TITLE
Using layout YAML in blog posts vs other pages in Jekyll 3: inconsistent behaviour

### ISSUE THREAD

**Issue by daattali** [jekyll/jekyll#4439]
([crosspost form jekyll-talk](https://talk.jekyllrb.com/t/using-layout-yaml-in-blog-posts-vs-other-pages-in-jekyll-3/1875))

I host a website on GitHub Pages, which updated to Jekyll 3 today, and this update broke the blog posts on my site.  I found the problem and I believe it is a Jekyll bug, or perhaps I'm not understanding the jekyll docs.

The [jekyll 2.x to 3.x migration document](http://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata) says that any YAML defined inside a layout was previously accessed through `page.` and will now be accessed with `layout.`

But what I'm finding, at least on GitHub Pages, is that YAML that I'm trying to access inside a template that is called from a layout will use `layout.` when the page is a blog post under the `_posts` directory, but for top-level pages it will use the old style of `page.`.  This seems like inconsistent and buggy behaviour to me, I'd love for someone to clarify this for me or confirm that it's a bug.

Reproducible example:

- I created two files with the text "hello" and they only contain one YAML parameter: the layout. One is a blog post (inside `_posts`) and therefore has `layout: post`, and the other has `layout: mytest`. You can view the files here: [blog post](https://github.com/daattalitest/daattalitest.github.io/blob/master/_posts/2016-02-01-test-jekyll3.md) and [top-level file](https://github.com/daattalitest/daattalitest.github.io/blob/master/testjekyll3.md).

-  Both the "post" and the "mytest" layouts contain exactly the same code, they're identical. You can view these files here: [post layout](https://github.com/daattalitest/daattalitest.github.io/blob/master/_layouts/post.html) and [mytest layout](https://github.com/daattalitest/daattalitest.github.io/blob/master/_layouts/mytest.html). This is their contents:

**post.html / mytest.html**
```
---
foo: bar
---

<!DOCTYPE html>
<html lang="en">
	<head></head>
	<body>
		 {% include mytest.html %}
		{{ content }}
	</body>
</html>
```

- The "mytest" template simply checks whether `layout.foo` exists and whether `page.foo` exists.  [mytest.html](https://github.com/daattalitest/daattalitest.github.io/blob/master/_includes/mytest.html):

```
{% if layout.foo %}
found YAML in layout
{% else %}
no YAML in layout
{% endif %}

<br/>

{% if page.foo %}
found YAML in page
{% else %}
no YAML in page
{% endif %}
```

- Before today, `page.foo` is what would always be there. The migration docs claim that `layout.foo` is what should exist now. But what I found is that in the blog post `layout.foo` exists and in the other page `page.foo` exists. You can see it by visiting the webpages rendered from the two files: [blog post](http://daattalitest.github.io/2016-02-01-test-jekyll3) and [top-level page](http://daattalitest.github.io/testjekyll3)

This is very annoying for me because I have CSS defined in the default layout YAML and now all my blog posts have no CSS

**Comment by daattali** [comment]
@envygeeks @parkr I'm sure you guys are extremely busy , but it'd be nice if anyone could see why this is happening, whether it's a bug or not

**Comment by parkr** [comment]
#4433 looks like a similar UX issue. I agree it should be fixed.

**Comment by daattali** [comment]
I know the bug report is a bit confusing to reproduce, so a TL;DR for future reference:

**If a layout defines a YAML parameter, then a blog post inside the `_posts` folder using that layout needs to refer to the variable as `layout.foo`, while a regular page using the same layout needs to use `page.foo`.**

@parkr thanks for response - #4433 sounds like it's *not* a regression bug, whereas this is something that used to work. Also, that issue is about inheritance, whereas this is about inconsistent behaviour between page types, and violates what the migration document says

**Comment by sunieldalal** [comment]
My site also broke due to these issues. Great if you guys can fix it..

**Comment by droglenc** [comment]
Same problem.  Would also like to see it fixed.
