### ISSUE TITLE
Comparison of Jekyll::Document with Jekyll::Document failed

### ISSUE THREAD

**Issue by stefanw** [jekyll/jekyll#4444]
While building [I encountered an error.](https://travis-ci.org/okfde/codefor.de/builds/106443626)

```
jekyll 3.0.2 | Error:  comparison of Jekyll::Document with Jekyll::Document failed
```

I tracked this to collection documents having `published: false` in their data which results in documents having no `date` in their data and making [this comparison fail](https://github.com/jekyll/jekyll/blob/v3.0.2/lib/jekyll/document.rb#L400): `cmp` is not `0`, but `nil`. This makes the comparison return `nil` which causes the error.

I believe this used to work before `3.0.2`.

**Comment by parkr** [comment]
Just needs to check `cmp.nil?` in the path comparison. https://github.com/jekyll/jekyll/blob/7ae4973788217deef5af8e1ec6a7504e014568ca/lib/jekyll/document.rb#L358
