### ISSUE TITLE
Inside a for loop over a sorted collection, items appear in the correct order but "previous" refers to the original order

### ISSUE THREAD

**Issue by stvnrlly** [jekyll/jekyll#4447]
## The collection

I have a bunch of `.md` files in a collection, with `agency` and `subagency` as part of the YAML front matter. I'd like them to show on a page, sorted into agency headings and, beneath those, subagency headings.

I'm on OS X 10.11.2 with ruby 2.2.4p230, running Jekyll 3.1.1 (also tried on 3.0.0).

## The code

```
{% assign iaas = (site.iaa | sort:"agency") %}
{% for iaa in iaas %}
{% if iaa.previous.agency != iaa.agency %}
# {{ iaa.agency }}
## {{ iaa.subagency }}
{% elsif iaa.previous.subagency != iaa.subagency %}
## {{ iaa.subagency }}
{% endif %}
* [{{ iaa.title }}]({{ iaa.url }})
{% endfor %}
```

## The problem

This outputs the items in the correct alphabetical order, but using `previous` refers to the previous item in original collection—`site.iaa`—rather than the `iaas` variable. I would expect the opposite since I'm inside of the for loop.

**Comment by parkr** [comment]
> `previous` refers to the previous item

This is as-intended. `Document#previous_doc` doesn't change depending upon the `for` loop it's in. It is based on the sorting logic for the collection, which is currently `date` comparison, falling back to `path` if the date isn't specified for either of the documents being compared.

To get the item previous in the iteration, consider:

```liquid
{% assign previous_iaa = iaas[forloop.index0-1] %}
```

See https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#for-loops for more.

**Comment by stvnrlly** [comment]
Thanks for the quick response, @parkr, this wasn't obvious to me. I was assuming that the sorted variable was a buffer of sorts between the `for` loop and the collection. I still feel like this is a weird behavior, but it seems like my issue may more with Liquid than Jekyll, so I'll move over there if I want to continue this.

Trying that code snippet at the beginning of the loop didn't work (though that might be my fault), but using `{% assign previous_iaa = iaas[forloop.index0] %}` at the end of the loop did the trick.
