### ISSUE TITLE
Jekyll 3.1 doesn't understand backtick-style fenced code blocks

### ISSUE THREAD

**Issue by weppos** [jekyll/jekyll#4448]
I was under the impression that the new release supported backtick-style fenced code blocks.

See:
- https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
- https://github.com/jekyll/jekyll/issues/2709

However, it looks like since I switched my Jekyll site (note, it's not hosted on GitHub) from Redcarpet to Kramdown, the code highlighting stopped working.

If I use the standard tilde style it works

    ~~~
    this is a code
    ~~~

but the backtick-style will not work and the content is rendered as

```
<p><code class="highlighter-rouge">shell
➜  curl -I --http2 https://www.cloudflare.com/
curl: (1) Unsupported protocol
</code></p>
```

You can test it using the default site created by jekyll. If you change

```
{% highlight ruby %}
def print_hi(name)
  puts "Hi, #{name}"
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
{% endhighlight %}
````

to

```
\```
def print_hi(name)
  puts "Hi, #{name}"
end
print_hi('Tom')
#=> prints 'Hi, Tom' to STDOUT.
\```
```

it will break. Is my assumption incorrect?

**Comment by weppos** [comment]
I also enable the [specific config](http://jekyllrb.com/docs/configuration/#kramdown):

```
kramdown:
  input: GFM
```

**Comment by envygeeks** [comment]
This issue is a duplicate of #4227 and was resolved with the merger of #4228.

**Comment by envygeeks** [comment]
Wait, one second, we never backported that feature it was a mistake it was listed there.

**Comment by parkr** [comment]
@weppos If you're using Jekyll 3.0.2 (which is what GitHub is using), please update your issue title.

**Comment by envygeeks** [comment]
Yes, it would be nice to know if you are on Github pages or on Jekyll stable outside of Github pages because this feature does work in 3.1 and we explicitly test it (as far as I remember) and we also default it to GFM on 3.1 so if you are on 3.0 then we might need to do a public backport of GFM.

**Comment by weppos** [comment]
No, I'm using Jekyll 3.1.

```
    jekyll (3.1.1)
      colorator (~> 0.1)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.3)
      liquid (~> 3.0)
      mercenary (~> 0.3.3)
      rouge (~> 1.7)
      safe_yaml (~> 1.0)
```

As mentioned, the site is not hosted on GitHub. The `Gemfile` is quite standard

```
source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-archives'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 's3_website'
```

and all the gems have been updated via `$ bundle update`.

**Comment by weppos** [comment]
> this feature does work in 3.1 and we explicitly test it 

@envygeeks it you can easily reproduce it from the default project generated with `jekyll new`. As I was afraid of conflicts, I generated a new site, wrote a simple code snippet and it did not work.

**Comment by envygeeks** [comment]
Okay, this issue is resolved then @weppos with the aforementioned tickets.

**Comment by weppos** [comment]
> Okay, this issue is resolved then @weppos with the aforementioned tickets.

Are you saying that the current version I can download from RubyGems doesn't contain the bug? In other words, are you expecting 3.1.1 to work?

**Comment by weppos** [comment]
Ok, nevermind, I saw the merge was a few hours ago hence I suspect 3.1.1 is buggy and we should wait for a bugfix release.

**Comment by envygeeks** [comment]
For the time being you can hit master directly with `gem "jekyll", :github => "jekyll/jekyll"` in your Gemfile and it should work as testing to make sure that fixed it did properly highlight on the default site now with that fix on that branch.

**Comment by weppos** [comment]
I confirm that using the latest version from master fixes the issue :+1: 

Thanks.

**Comment by Treri** [comment]
jekyll 3.1.1 have this bug. when will a fix release?

**Comment by parkr** [comment]
> jekyll 3.1.1 have this bug. when will a fix release?

Working on it!
