### ISSUE TITLE
Problems with {{ ASSET_PATH }} in Jekyll 3.1.1

### ISSUE THREAD

**Issue by ploeh** [jekyll/jekyll#4450]
Please accept my apologies in advance if this issue is inappropriate, or if it's a duplicate.

Since [GitHub Pages updated to run on Jekyll 3.0 February 1, 2016](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0), `{{ ASSET_PATH }}` no longer includes the theme on my site.

As an example, this:

```
<link href="{{ ASSET_PATH }}/bootstrap/css/bootstrap.min.css" rel="stylesheet">
```

generates this:

```
<link href="/assets/themes//bootstrap/css/bootstrap.min.css" rel="stylesheet">
```

(notice the double slashes between `themes` and `bootstrap`) while I would have expected it to generate this:

```
<link href="/assets/themes/ploeh/bootstrap/css/bootstrap.min.css" rel="stylesheet">
```

which Jekyll 2 did.

I'm neither a Jekyll expert nor a Ruby programmer, but AFAICT, `ASSET_PATH` is built in `JB/Setup`. Here, it uses `{{ page.theme.name }}`, but as far as I can tell, this expression evaluates to nothing (or the empty string).

My `_layout` files essentially look like the following, so I can't figure out what I'm doing wrong:

**default.hml**

```
---
theme :
  name : ploeh
---
{% include JB/setup %}
{% include themes/ploeh/default.html %}
```

**page.html**

```---
theme :
  name : ploeh
layout: default
---
{% include JB/setup %}
{% include themes/ploeh/page.html %}
```

**post.html**

```---
theme :
  name : ploeh
layout: default
---
{% include JB/setup %}
{% include themes/ploeh/post.html %}
```

My entire site's source code is [publicly available](https://github.com/ploeh/ploeh.github.com), if that's any help.

What am I doing wrong, and what can I do to correct the problem?

**Comment by envygeeks** [comment]
This question is probably better suited to https://talk.jekyllrb.com until we flag it as a potential bug.

**Comment by ploeh** [comment]
Sorry about that. I now realise that this is most likely an issue with Jekyll Bootstrap, so I've [cross-posted the issue there](https://github.com/plusjade/jekyll-bootstrap/issues/295).

**Comment by parkr** [comment]
Thanks @ploeh. The only thing I can think of is that when an include `assign`'s, it's not trickled back to the parent page/post. @benbalter have you encountered this? I feel like you mentioned something similar to this before.

**Comment by ploeh** [comment]
I may have found [an explanation](https://github.com/plusjade/jekyll-bootstrap/issues/295#issuecomment-178869307)...

**Comment by parkr** [comment]
Wonderful! I commented with a docs page link.
