### ISSUE TITLE
Headers in Markdown are not being rendered

### ISSUE THREAD

**Issue by saatvikshah1994** [jekyll/jekyll#4456]
In my website all pages generating headers using "#" in markdown, instead have the # rendered. See this [example](https://saatvikshah1994.github.io/project/irstapp/). Every other markdown element is being correctly rendered such as the **bold** or links. Only these are being incorrectly rendered. 
Locally this is being rendered correctly, but when pushing to github pages this is happening. I've attached images as well:
This is being rendered locally
![localcopy](https://cloud.githubusercontent.com/assets/6854735/12769690/d8b3b9fa-ca3f-11e5-88f3-1c43e3517676.png)
and this is rendered on github-pages
![gh-pages](https://cloud.githubusercontent.com/assets/6854735/12769701/f0c046d0-ca3f-11e5-8faa-c62f50c62995.png)

**Comment by saatvikshah1994** [comment]
Ok I figured this out - its because there has to now be a space between # and the first letter, which was not required before the recent update.

**Comment by envygeeks** [comment]
In the future https://talk.jekyllrb.com is the place to ask questions that are not confirmed bugs.  Thanks!
