### ISSUE TITLE
Files that start with a tilde (~) break builds

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#4457]
The way [we use `File.expand_path`](https://github.com/jekyll/jekyll/blob/7df8f502487f3b6476b5ce0f296be28f70df59cb/lib/jekyll.rb#L156), we expand paths of every file. We should escape a number of different values in this call. [StackOverflow has a great idea of what to escape](http://stackoverflow.com/questions/6159355/how-do-i-escape-parentheses-and-brackets-in-ruby).

```irb
>> File.expand_path("~hi.txt")
ArgumentError: user hi.txt doesn't exist
	from (irb):3:in `expand_path'
	from (irb):3
	from /Users/parkr/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
>> File.expand_path('\~hi.txt')
=> "/Users/parkr/jekyll/jekyll/\\~hi.txt"
```

Should be patched on 3.0.2 and 3.1.2.

/cc @benbalter

**Comment by envygeeks** [comment]
Yeah, that's a terrible way to do `Shellwords.shellescape`

**Comment by parkr** [comment]
> Yeah, that's a terrible way to do Shellwords.shellescape

Is there a `Shellwords.shellunescape`? `File.read("\\~hi.txt")` fails.

**Comment by envygeeks** [comment]
No, but I digress with any further comments as they are unheeded anyways.
