### ISSUE TITLE
Scope values not applied

### ISSUE THREAD

**Issue by borisyankov** [jekyll/jekyll#4458]
I am using the approach to localize pages, described here:
https://www.sylvaindurand.org/making-jekyll-multilingual/

It was working perfectly on 2.x, but now both on GH Pages, and locally (3.1.1) it does not work.

When there is lang: en for root, all subfolders do have lang: en (though they are set otherwise)
If the lang: en for root is removed, the subfolders also have no value set.
It seems the variables don't work at all for the subfolders.

**Comment by 1nsunym** [comment]
I've got the exact same problem.

**Comment by borisyankov** [comment]
@1nsunym unfortunately not.
I think it is genuine bug, and not some behaviour that changed.
And not aware of a workaround. But looking urgently for a fix/workaround.

**Comment by 1nsunym** [comment]
@borisyankov Mines only a small blog, so my fix-around was setting 'en' default for lang variables and setting lang variable for other language post/pages explicitly on frontmatters.

**Comment by sylvaindurand** [comment]
I'm working on it. 
Defaults doesn't seem to work anymore, I'm trying to understand why!

**Comment by borisyankov** [comment]
@sylvaindurand Great that you will update your article. I used it as a guideline an year ago.
Seems to be part of the 'distributed documentation' of Jekyll. ;)

**Comment by Crunch09** [comment]
@borisyankov @sylvaindurand 
Hi, i tried to come up with a testcase to reproduce this bug but i wasn't able to get it to fail both on 3.1 and master. Could you maybe take a [look at it](https://gist.github.com/Crunch09/b41156779c998e9a3c6b) an see if i missed something?

**Comment by parkr** [comment]
@Crunch09 Were you able to test this on v3.0.3? Check out the `v3.0.3` tag in your fork (I do this via `git checkout v3.0.3` in the shell) and add this test and run it. It may have been fixed in 3.1.

**Comment by Crunch09** [comment]
@parkr Thanks! You were right, the test is failing on `v3.0.3`. Should i submit a PR with this test to prevent further regression?

**Comment by parkr** [comment]
> @parkr Thanks! You were right, the test is failing on v3.0.3. Should i submit a PR with this test to prevent further regression?

Yes, please! Submit a patch based on the `3.0-stable` branch and pointed to that branch instead of `master`.
