### ISSUE TITLE
3.0.2: Non-HTML documents have strange extension behaviour

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#4466]
If you have `_licenses/mit.txt` with `permalink: /licenses/mit/`, `Document#destination` in v3.0.2 will write out `_site/licenses/mit/index.html.txt`. We need to not write that extra `.txt` in the case that we're appending `index.html`.

We should check this in 3.1 as well.

**Comment by envygeeks** [comment]
Isn't this the problem you recently fixed involving custom extensions?
