### ISSUE TITLE
where key exists functionality

### ISSUE THREAD

**Issue by draco2003** [jekyll/jekyll#4467]
It would be great to be able to use the where or similar filter to just verify that the variable exists.

{% assign post_list = site.posts | where: 'menu_item' %}
{% for post in post_list %}
- {{ post.title }}
{% endfor %}

or something similar to where not empty.

**Comment by parkr** [comment]
@draco2003 That's a possibility, but you can achieve that functionality by doing something like

```liquid
{% assign post_list | site.posts | where: "nav_type", "menu_item" %}
```

I could see something like

```liquid
{% assign post_list = site.posts | withany: "menu_item" %}
```

`withany`, `with`, something like that.

@benbalter any other ideas here? Would you use this?
