### ISSUE TITLE
Liquid Exception Issues?

### ISSUE THREAD

**Issue by mkkwon** [jekyll/jekyll#4469]
I forked this site: https://github.com/pattern-lab/website

And when I tried to follow the [Installation readme](http://jekyllrb.com/docs/installation/), it would still show these errors.
![image](https://cloud.githubusercontent.com/assets/558258/12827916/d732ecd4-cb36-11e5-9ee3-9272b8db8789.png)

Any way I can fix this? I wonder if I am missing any other dependencies... I can update the readme.MD to make this process easier. Thanks!

**Comment by parkr** [comment]
@mkkwon This is a problem with [their RawTag plugin](https://github.com/pattern-lab/website/blob/master/patternlabsite/_plugins/raw_tag.rb). Please file this issue with pattern-lab/website!

**Comment by mkkwon** [comment]
Got it. Thanks @parkr!
