### ISSUE TITLE
jekyll comand line extremely slow

### ISSUE THREAD

**Issue by ianks** [jekyll/jekyll#4477]
After installing the new Jekyll ('3.1.1.`), I noticed the CLI is very slow.

```
~/Documents » time jekyll -v
jekyll 3.1.1
jekyll -v  5.91s user 0.10s system 99% cpu 6.069 total
```

**Comment by parkr** [comment]
@ianks This is due to an issue with your environment. Run `gem uninstall jekyll` and remove old versions. Then run `gem prune`.

**Comment by ianks** [comment]
`gem uninstall jekyll`, `gem cleanup`, then `gem install jekyll` did the trick.

I'm curious as to why this is an environment issue though. Other gems don't seem to suffer from the same problem, AFAICT.
