### ISSUE TITLE
# not rendering HTML heading tags after GitHub's recent update for pages and Jekyll

### ISSUE THREAD

**Issue by xameeramir** [jekyll/jekyll#4481]
This week, [GitHub announced that it will *only* support kramdown](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0) for it's product [Pages](https://pages.github.com/).

Hence, as per their suggestion - I [removed `markdown: redcarpet`](https://github.com/xameeramir/xameeramir.github.io/commit/f700fa5cbcf5f65b355b44197558bc0b2f2550a3) and updated [`highlighter` value to `rouge`](https://github.com/xameeramir/xameeramir.github.io/commit/db0f42108322323a564407ca39075538d94c6eb3) in the [_config](https://github.com/xameeramir/xameeramir.github.io/blob/master/_config.yml) of [my project](https://github.com/xameeramir/xameeramir.github.io).

Now the only problem is that `#` is unable to render heading on any of the pages on the [main website](http://xameeramir.github.io/)

 - What is the workaround for this?

>side question: Is there anything else to watch out for?

[source](http://stackoverflow.com/q/35242130/2404470)

**Comment by envygeeks** [comment]
That is because your markdown is invalid.  Markdown requires a space between the `#` and the content, both the CommonSpec and the original Daring Fireball spec imply that by both example and direct mention, see: http://spec.commonmark.org/0.23/#atx-heading
