### ISSUE TITLE
When adding linenos to highlight and have multiple highlight blocks, the closing tags for the highlight blocks are placed incorrectly.

### ISSUE THREAD

**Issue by dolfandringa** [jekyll/jekyll#4486]
I have this problem with jekyll 2.40 and using rouge 1.10.1 as highlighter. With a post with the markdown below with two highlight blocks and using the linenos parameter, if I have two highlight blocks, the closing tag of the first block wraps around the closing tag of the second block. The `</code></pre></div>` of the first code block is placed after the end of the second code block.

I pasted both a md file and the resulting html (snippet, I left the template stuff out for brevity's sake) below. I also added indentation to the html to make it readable. This does mean the `<pre></pre>` blocks have indentation that isn't there in the real html, but it reads much easier this way.

```
 ---
 layout: post
 title: Code highlight test
 ---
 
 Some text
 
 {% highlight md linenos=table %}
 line 1
 line 2
 line 3
 {% endhighlight %}
 
 Some text
 
 {% highlight md linenos=table %}
 line 1
 line 2
 line 3
 {% endhighlight %}
```
It produces the following html output

```
<section>
<p>Some text</p>
<div class="highlight">
<pre>
<code class="language-md" data-lang="md">
    <table style="border-spacing: 0"><tbody><tr>
        <td class="gutter gl" style="text-align: right">
            <pre class="lineno">1
                2
                3
            </pre>
        </td>
        <td class="code">
            <pre>line 1
                line 2
                line 3<span class="w">
            </span></pre>
        </td>
    </tr></tbody></table>

Some text

<div class="highlight">
<pre>
<code class="language-md" data-lang="md">
    <table style="border-spacing: 0"><tbody><tr>
        <td class="gutter gl" style="text-align: right">
            <pre class="lineno">1
                2
                3
            </pre>
        </td>
        <td class="code">
            <pre>line 1
                line 2
                line 3<span class="w">
                </span>
            </pre>
        </td>
    </tr></tbody></table>
</code>
</pre>
</div>
</code>
</pre> # this should be above "Some Text"
</div> # this should be above "Some Text"
</section> # this should be above "Some Text"
```

**Comment by parkr** [comment]
> with jekyll 2.40

I'm sorry, but we can't support Jekyll 2.4 anymore, especially now that GitHub Pages has updated to Jekyll 3. Please update to at least Jekyll 3.0.3 and try again. File another bug if this persists in Jekyll v3.0.3 or later. Sorry we can't help you with v2!

**Comment by dolfandringa** [comment]
Ok, I didn't even realize 2.4 was old. I'll update.

**Comment by dolfandringa** [comment]
Cool, the update to 3.0.2 fixed it. Thanks for the feedback @parkr
