### ISSUE TITLE
Empty filename in liquid profiler output

### ISSUE THREAD

**Issue by akoeplinger** [jekyll/jekyll#4488]
I ran `jekyll build --profile` over our [website](https://github.com/mono/website) and noticed there's an empty filename in the report:

```
Filename                                                       | Count |     Bytes |  Time
---------------------------------------------------------------+-------+-----------+------
_layouts/base.html                                             |   941 | 14967.91K | 0.816
_layouts/docpage.html                                          |   377 |  5520.46K | 0.518
docs/about-mono/releases/index.md                              |     1 |     7.99K | 0.481
_layouts/obsolete.html                                         |   540 |  4375.85K | 0.228
atom.xml                                                       |     1 |    18.21K | 0.184
_layouts/blog.html                                             |    15 |    28.93K | 0.067
_includes/blogpost.html                                        |    30 |    43.12K | 0.059
                                                               |  1043 |   385.62K | 0.056   <--
_includes/blogpost/meta.html                                   |    30 |     7.04K | 0.043
_layouts/releasenotes.html                                     |   100 |  1155.28K | 0.042
...
```

Is there a way I can find out which file that is?

**Comment by parkr** [comment]
That's interesting. Maybe it's a variable in an include or something. [Searching through the code](https://github.com/jekyll/jekyll/search?utf8=%E2%9C%93&q=liquid_renderer.file&type=Code), that's the only place a path isn't specified. Can you try debugging that?

**Comment by pathawks** [comment]
Could it be a plugin like **jekyll-feed** or **jekyll-sitemap** that generates a Page Without A File?

**Comment by akoeplinger** [comment]
@pathawks yep, you're right. If I remove *jekyll-redirect-from* from _config.yml then the empty file doesn't show up.

**Comment by akoeplinger** [comment]
It doesn't seem to happen on our site anymore with jekyll 3.1.6 / jekyll-redirect-from 0.10.0, so this was likely fixed :)
