### ISSUE TITLE
Default ighlighting language per page

### ISSUE THREAD

**Issue by ktzanev** [jekyll/jekyll#4489]
When we reed the [kramdown documentation about rouge](http://kramdown.gettalong.org/syntax_highlighter/rouge.html) we can guess that 

    kramdown:
      syntax_highlighter_opts:
        default_lang: python

set default language to `python`. 

I have tried to put this same configuration options in the yaml preamble of a post, but it seems that they are only "per site" (inside `_config.yml`). 

The questions is how to do this per page/post. How to set for one post the default language to `python` and for another post to `ruby` ?

**Comment by envygeeks** [comment]
I don't think that's possible right now as the Kramdown parser only asks the main configuration.

**Comment by ktzanev** [comment]
@envygeeks Bad news. Having default language per post seems natural. Writing one post abour javascript, anothe about ruby, and so on, is what a lot of peaople do, no ?

**Comment by envygeeks** [comment]
It's not natural; if you ask me at least. It's unintuitive if you ask me for further details. Defaults are defaults, they are not meant to be changed "per-post" or "per-page" they are just meant to be static defaults that can be overriden or if you choose not to send a value the default.

What is intuitive to me is set the default to your most commonly used language and then do <code>```ruby</code> on a per-code block basis which is the value that is overriding the default.

**Comment by ktzanev** [comment]
@envygeeks Well, obviously we disagree ;)

There are a lot of options in jekyll that can have a site default that is overwritten by the page settings. For example : the page layout.

So why should I have a default syntax highlight for the entire site ? For some people that have a "main language" this could be useful, but for other this is meaningless, just because they use equally often more than one language.

And there is another big problem : how do you set  easily the inline code language? the <code>```ruby</code> is not working in this case.

**Comment by envygeeks** [comment]
> There are a lot of options in jekyll that can have a site default that is overwritten by the page settings. For example : the page layout.

You aren't overriding a default, you set the layout in the page (parent) of your post, it is not a default in the way you assume it is.  Layouts must be set per-page and there is no default unless you set one via your `_config.yml` and that is not a default in the way the way Kramdown defaults are defaults.

> And there is another big problem : how do you set easily the inline code language? the ```ruby is not working in this case.

You don't and even if you wanted to, Kramdown doesn't support it anyways. As far as I'm aware Kramdown doesn't even highlight those. Inline code is meant to be simple things like talking about the `echo` command.  That's neither here nor-there as that' a semantics issue out of this scope.

**Comment by ktzanev** [comment]
@envygeeks 

> You aren't overriding a default, you set the layout in the page (parent) of your post, it is not a default in the way you assume it is. Layouts must be set per-page and there is no default unless you set one via your _config.yml and that is not a default in the way the way Kramdown defaults are defaults.

I agree that the actual setting of the default hilight language is not the same thing as setting the default layout in the `default` section of `_config.yml`. 

But this is precisely what I suggest : set the default hilight language per page/post and set the default if needed in the `default` section of `_config.yml`.

> You don't and even if you wanted to, Kramdown doesn't support it anyways. As far as I'm aware Kramdown doesn't even highlight those. Inline code is meant to be simple things like talking about the echo command. That's neither here nor-there as that' a semantics issue out of this scope.

And what if I set : 

    kramdown:
      syntax_highlighter_opts:
        span: 
          default_lang: python

**Comment by envygeeks** [comment]
> But this is precisely what I suggest : set the default hilight language per page/post and set the default if needed in the default section of _config.yml.

To do that would require a hefty logic change from the bottom up (across multiple classes) because at this time the processor is global (that doesn't need to change) but the processing when it's done only ships the content as we initialize, cleanup and normalize your configuration defaults on class initialization, and none of the meta (front-matter) that the page has comes into that processor, just your sites settings.  The problem isn't the change it's the milestone. I'm not against the change even if I think it's unintuitive, I'm more so against when it gets placed.

> And what if I set

Then at that point it's between you, Markdown (pick any number of specs) and Kramdown. :wink:  (I will say though, I'm almost happy it supports that option though, and I would love to see Markdown itself support single tick languages.)

**Comment by parkr** [comment]
> Having default language per post

This is not something we are considering at this time. Only one Markdown parser is currently created and is used for every document. This would require a significant restructuring of how we do things and it doesn't have other benefits. We are interested in keeping Jekyll simple.

Thanks for the suggestion!

**Comment by bcb** [comment]
Put this at the top of your post:
```
{::options syntax_highlighter_opts="default_lang: python" /}
```

**Comment by ktzanev** [comment]
@bcb This is the solution I was looking for. Thanks.

**Comment by sio4** [comment]
@bcb Thanks for this tips!

https://kramdown.gettalong.org/options.html
