### ISSUE TITLE
Jekyll and Safari includes scrollbar width for viewport and margin:auto (whereas neither html+Safari nor Jekyll+Chrome does.)

### ISSUE THREAD

**Issue by gehoon** [jekyll/jekyll#4490]
Hi, I am not sure if this has been brought up previously, but I couldn't find relevant posts so here it goes:

I am moving my site from drupal to Jekyll, and I am doing it more like re-creating than migrating way. The problem is that the Jekyll-generated html page is rendered differently from the original html page it copied and pasted from, and it happens only in Safari (9.0.3 on OSX 10.11.3), but not in Chrome (48.0.2564.97). Specifically, safari takes the scroll-bar space into the screen width when viewing Jekyll-generated html page (Fig 1), but not the original plain html document (Fig 2). Investigating the cause of the weird behavior, Bootstrap and CSS codes were removed one by one until only the bare html tags were left, but the problem persists. Here is the codes and the screenshots of rendered pages. 

`Fig. 1`: **Jekyll-generated** simple html page rendered in **Safari**
![screenshot 2016-02-07 11 54 51](https://cloud.githubusercontent.com/assets/1791612/12873672/a66d2e22-cd91-11e5-90fe-1fccef07ab2d.png)

`Fig. 2`: **Original** simple html document opened in **Safari** (note the difference at the **right edge**.)
![screenshot 2016-02-07 11 54 55](https://cloud.githubusercontent.com/assets/1791612/12873673/a66d8688-cd91-11e5-8f7f-7abccae6cbad.png)

`Fig. 3`: **Jekyll-generated** simple html page rendered in **Chrome**
![screenshot 2016-02-07 11 55 00](https://cloud.githubusercontent.com/assets/1791612/12873670/a66b99e0-cd91-11e5-8465-39c2805702c7.png)

`Fig. 4`: **Original** simple html document opened in **Chrome**
![screenshot 2016-02-07 11 55 03](https://cloud.githubusercontent.com/assets/1791612/12873671/a66bbf7e-cd91-11e5-907a-bfb0516413ea.png)

`Code 1` Page feeded to Jekyll (Fig 1 and 3 above are Jekyll-generated result of this file.)
```
---
layout: testViewTemp
title: testView
permalink: /test/
---

This is Jekyll-generated test page.
```
`Code 2` Jekyll layout template used (Fig. 2 and 4 above are reading of this file through browsers.) 
```
<html lang="en">
<head>
	<title>Test: viewport</title>
</head>
<body>
	{{ content }}

	<h2>Testing Viewport Width</h2>
	<div><h4>Lorem Ipsum </h4>
		<p style="text-align:justify; vertical-align: middle;">is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
		<BR>
	</div>
</body>
</html>
```

I might give right margin a positive value but then it would look lefted when there is no scroll-bar, and it wouldn't be the right solution per se (I'd like to have the same results both in Safari and Chrome.)

Thanks in advance for any suggestion and Happy Chinese New Year!

**Comment by envygeeks** [comment]
Please ask your question at https://talk.jekyllrb.com, the community will help you with your CSS woes if it can, we do not provide support for anything but Jekyll, your design is yours to support.  Sorry.

**Comment by gehoon** [comment]
I thought the problem might be from Jekyll and wanted to know if anyone had similar experience. (Because there is no CSS or anything near design in my code.) Thanks for the reply, though.

**Comment by envygeeks** [comment]
@gehoon when you mentioned it worked correctly in one browser and not another to me (from experience) that seems like a disparity between rendering engines rather than Jekyll altering something and causing that disparity.

**Comment by gehoon** [comment]
Thanks again @envygeeks. That should be problem of rendering engine. But my main concern was that a simple html document looked differently when it came out of Jekyll (Both Fig. 1 and 2 are viewed in Safari, so the rendering engine was ruled out). I will look somewhere else, and update you if I find the answer.

**Comment by envygeeks** [comment]
@gehoon if you do find it's a Jekyll bug please do reping and I will personally task my tracer to finding how what part of Jekyll is causing that problem so we can figure out if it's us or possibly a lib we rely on doing something weird that needs to be reported.
