### ISSUE TITLE
unable to overwrite existing hash value with null

### ISSUE THREAD

**Issue by willnorris** [jekyll/jekyll#4494]
A recent change in `Utils::deep_merge_hashes!` (this happened in 5d79c55b2cee0aa19ca57ad331333edba9db47b7) broke the ability to overwrite an existing value in a hash with nil.  This is because of the obvious:

```ruby
if new_val.nil?
  old_val
```

An example of how this previous behavior is useful can be seen in my jekyll config files.  In my [main _config.yml](https://github.com/willnorris/willnorris.com/blob/99f27a1b2b903532a75ded22e8ccc3c9f2bee535/_config.yml#L5), I set a `imageproxy_baseurl` key, but in [my _debug.yml](https://github.com/willnorris/willnorris.com/blob/99f27a1b2b903532a75ded22e8ccc3c9f2bee535/_debug.yml#L2) I set this back to `null`.  My [startup script for local development](https://github.com/willnorris/willnorris.com/blob/99f27a1b2b903532a75ded22e8ccc3c9f2bee535/tools/run) loads these two files in order, and expects there to be no value for this key when run in development.

I can certainly work around this on my side (and I recall there being a proposal for loading different config files based on the value of `JEKYLL_ENV` or something... not sure if that ever went anywhere, maybe I should be using that. *update: it's #3173*).  But I wanted to bring it up because this is such a widely used utility function, and I suspect there may be other places where people intentionally override an existing value with null.

/cc @parkr

**Comment by envygeeks** [comment]
Nil is not NULL :wink:.  

I don't like the complexities that nil brings to other pieces of code (potentially depending on how programmers program.) I do love the per-env configurations though I wish that did come of something.  Since those complexities were never addressed though I concede if that specific piece wants to be redressed until a later date when bigger more important complexities are addressed.

**Comment by willnorris** [comment]
I had a sneaking suspicion there was an actual difference between nil and null, but haven't touched ruby recently enough to remember.  So what would have been the correct solution for me to override the value like I was trying?  Should I have been setting a different value in my `_debug.yml`, or is the `deep_merge_hashes` function as written just going to have problems with that no matter what?  (as you can see in the commit above, I already fixed this in my own case, but am somewhat curious now)

**Comment by envygeeks** [comment]
Setting it to a different value would *should* override it (and if it doesn't that is a major bug IMNSHO.)

**Comment by willnorris** [comment]
yes, I can set it to an empty string and it overrides properly, but I was actually trying to set it to `null`.

**Comment by willnorris** [comment]
I'm now running into this with syntax highlighting as well.  For years, I've disabled server side syntax highlighting by adding the following to my jekyll config:

```yaml
highlighter: nil
```

Since jekyll 3.1.0, this is being ignored and jekyll is trying to use fallback highlighter, rouge.

**Comment by willnorris** [comment]
though I suspect this is unrelated to the `deep_merge_hashes` change, and is rather related to 3432fd2c2dcc1a367732e16404f5cd1fee895c43

**Comment by envygeeks** [comment]
@willnorris It is because  I have a no-promises policy with `nil` values because `nil` is not how one should handle things like disabling syntax highlighters... so I'll go out of my way to replace it with a valid value... however, we can resolve that though, I'll explicitly check for `nil` and let people ship false for `syntax_highlighter`

**Comment by willnorris** [comment]
Kramdown specifically says to use `nil`: http://kramdown.gettalong.org/options.html#option-syntax-highlighter

So this was fixed by switching to:

```yaml
kramdown:
  syntax_highlighter: nil
```

as well as running with the latest jekyll from git (I appear to also have been bitten by #4427)

**Comment by willnorris** [comment]
Or does that mean `nil` in the ruby sense, but not in the yaml sense?  Happy to use whatever value will work, just not sure what's the recommended use (though sounds like maybe you're going to map `false`?)

**Comment by willnorris** [comment]
actually, the config change I mentioned above wasn't even necessary.  Seems this was just completely related to #4427 (or something else that got fixed since 3.1.1, but that seems like the most likely culprit)

**Comment by envygeeks** [comment]
#4427 is resolved and I've confirmed it on a couple dozen sites our (EnvyGeeks) stack builds as well as some other stacks.  If you are still having problems with that please do be very explicit so I can test it and see if there is another edge but it should be entirely resolved as we recursively allow accessible hash keys.

```yaml
kramdown:
  syntax_highlighter: nil
```

When you do that you aren't being bitten by any bug (in a sense -- it is a bug.) You are being loosely guarded as when I program I always expect values (non-`nil` -- if I care about the key) and false wasn't a valid consideration either... so it corrects that loosely to a valid value being "rouge".  It can still be broken many ways as the guard was only against nil and false.

> (though sounds like maybe you're going to map false?)

No, I wasn't going to (until you brought up them actually *wanting* explicit `nil` which does make me sad,) I'll just have to lower my standards and allow `nil` values explicitly.

**Comment by willnorris** [comment]
So if not `nil`, what would have been the recommended way to disable syntax highlighting?  Just a dummy string value?

**Comment by envygeeks** [comment]
`false`

**Comment by willnorris** [comment]
:+1:
