### ISSUE TITLE
CircleCI

### ISSUE THREAD

**Issue by nielsenramon** [jekyll/jekyll#4495]
Hey guys,

I updated to the latest version of Jekyll (3.1.1) and Ruby (2.3.0).
When running Jekyll build in CircleCI I get the following error.

![screen shot 2016-02-08 at 10 41 57](https://cloud.githubusercontent.com/assets/1246672/12882293/d6065c20-ce50-11e5-9368-360ba47da1ae.png)

```
ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------

Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.3.0/gems/jekyll-3.1.1/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter. bundle exec jekyll build returned exit code 1
```

It used to work with older versions, so not sure what is causing this error.

Any help would be appreciated! :)

**Comment by envygeeks** [comment]
Exclude the `vendor/` folder in your `_config.yml` because CircleCI (and most CI's) `bundle install`.
***NOTE:*** Questions like these are preferably asked at https://talk.jekyllrb.com/
