### ISSUE TITLE
Site URL doesn't change when I go to a sub page on my site

### ISSUE THREAD

**Issue by eplehans** [jekyll/jekyll#4499]
When I click on a post or go to a sub page on my site, the URL stays the same. This only happens on the live site and not on my local environment. The site is hosted on GitHub pages. Any ideas why this is happening?

**Comment by parkr** [comment]
@eplehans No, there is no reason this should be happening other than that your links are empty or wrong, If you have `<a href="">My post</a>`, it won't go to another page. You need to populate the href properly.

This doesn't look like a bug in Jekyll. We are trying to keep our issue tracker for only bugs and feature requests. Would you please search through our forum, [Jekyll Talk](https://talk.jekyllrb.com), for your issue and [post a new topic in the Help section](https://talk.jekyllrb.com/c/help) if it's not there? We can better assist you as a community in the forums. Additionally, [GitHub Support](https://github.com/contact) is always available to help with your Pages-related issues.

Thanks!

**Comment by eplehans** [comment]
Ok, I have a hunch why this is happening. I looked at the source it is outputting, and something really weird is going on. The site is being sent through a <frameset> tag and I have no idea why it is happening. 


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Frameset//EN"
"http://www.w3.org/TR/REC-html40/frameset.dtd">
<HTML>
<FRAMESET ROWS="100%,*" BORDER=0 FRAMEBORDER=0 FRAMESPACING=0>
  <FRAME MARGINWIDTH=10 MARGINHEIGHT=10 SRC="http://www.hanseri.no/" NAME="_main">
</FRAMESET>
<NOFRAMES>
<BODY>
The document is located <A HREF="http://www.hanseri.no/">here</A>.
</BODY>
</NOFRAMES>
</HTML>

**Comment by eplehans** [comment]
Could it have something to do with how GitHub Pages is handling custom domain and CNAME?
