### ISSUE TITLE
`site.categories` Do Not Have Information on the Hierarchy of the Category

### ISSUE THREAD

**Issue by ickc** [jekyll/jekyll#4500]
# Constructing the Sub-Categories Folder Structure #

## Problem: `site.categories` Do Not Have Information on the Hierarchy of the Category ##

Currently in Jekyll variable `site.categories`, I think the information of the original hierarchy of categories are lost.

e.g. if I have posts:

```
/Physics/QFT/_posts/
/Physics/EM/_posts/
```

or equivalently, with YAML front matter

```yml
categories: [Physics, QFT]
categories: [Physics, EM]
```

And then if one want to create an archive like this:

```markdown
# Physics
## QFT
- posts...
## EM
- posts...
```

Currently, site.categories cannot help one to get this result.

### Temporary Solution: Liquid and Nesting ###

Using pure Liquid only, the following can generate the folder structure of the categories. There's a lot of nesting and is non-trivial to have arbitrary level of hierarchy. Please let me know if there's a better way though.

#### Basic Building Block ####

```Liquid
{% assign category_list = site.categories | sort %}
<!-- level 0 -->
<ol>
{% for category0 in category_list %} <!-- change level here -->
	{% assign printed0 = false %} <!-- change level here -->
	{% for post in site.posts %}
		{% if post.categories[0] == category0[0] and printed0 == false %} <!-- change level here -->
			<li><a href="{{ site.category_dir | prepend: site.baseurl}}/{{ category0[0] | slugify }}">{{ category0[0] }}</a></li> <!-- change level here -->
			{% assign printed0 = true %} <!-- change level here -->
<!-- level 1 -->
<!-- end of level 1 -->
		{% endif %}
	{% endfor %}
{% endfor %}
</ol>
<!-- end of level 0 -->
```

Copy between `<!-- level 0 -->` and `<!-- end of level 0 -->` and paste it between `<!-- level 1 -->` and `<!-- end of level 1 -->` and change the level in `<!-- change level here -->`

#### Example for Subcategories Up to Level 2 `[category, sub-category, sub-catogory]` ####

```Liquid
{% assign category_list = site.categories | sort %}
<!-- level 0 -->
<ol>
{% for category0 in category_list %} <!-- change level here -->
	{% assign printed0 = false %} <!-- change level here -->
	{% for post in site.posts %}
		{% if post.categories[0] == category0[0] and printed0 == false %} <!-- change level here -->
			<li><a href="{{ site.category_dir | prepend: site.baseurl}}/{{ category0[0] | slugify }}">{{ category0[0] }}</a></li> <!-- change level here -->
			{% assign printed0 = true %} <!-- change level here -->
<!-- level 1 -->
			<ol>
			{% for category1 in category_list %} <!-- change level here -->
				{% assign printed1 = false %} <!-- change level here -->
				{% for post in site.posts %}
					{% if post.categories[0] == category0[0] and post.categories[1] == category1[0] and printed1 == false %} <!-- change level here -->
						<li><a href="{{ site.category_dir | prepend: site.baseurl}}/{{ category1[0] | slugify }}">{{ category1[0] }}</a></li> <!-- change level here -->
						{% assign printed1 = true %} <!-- change level here -->
			<!-- level 2 -->
				<ol>
				{% for category2 in category_list %} <!-- change level here -->
					{% assign printed2 = false %} <!-- change level here -->
					{% for post in site.posts %}
						{% if post.categories[0] == category0[0] and post.categories[1] == category1[0] and post.categories[2] == category2[0] and printed2 == false %} <!-- change level here -->
							<li><a href="{{ site.category_dir | prepend: site.baseurl}}/{{ category2[0] | slugify }}">{{ category2[0] }}</a></li> <!-- change level here -->
							{% assign printed2 = true %} <!-- change level here -->
				<!-- level 3 -->
				<!-- end of level 3 -->
						{% endif %}
					{% endfor %}
				{% endfor %}
				</ol>
			<!-- end of level 2 -->
					{% endif %}
				{% endfor %}
			{% endfor %}
			</ol>
<!-- end of level 1 -->
		{% endif %}
	{% endfor %}
{% endfor %}
</ol>
<!-- end of level 0 -->
```

### Proposed Solution: Add a New Variable ###

I suggest Jekyll to provide a new variable, say, site.subcategories such that it will returns an array of arrays, where each array contains the category structure (e.g. [Physics, QFT], [Physics,EM]).

Please correct me if I am wrong or misunderstood anything, and make some suggestions on how to archive it currently and in the future too. Thanks.

**Comment by parkr** [comment]
Hey @ickc! Thanks for writing up your issue in great detail.

A category hierarchy has been proposed once or twice before and we've said no for a number of reasons, the first being that it is a complication that can be solved by applying one category and using tags for "super" categories which span a number of different categories.

Thanks for your suggestion, though!
