### ISSUE TITLE
Feature Request: Providing an Alternative Folder Structure for Posts with Categories

### ISSUE THREAD

**Issue by ickc** [jekyll/jekyll#4501]
From the [Variables](http://jekyllrb.com/docs/variables/) in the documentation, currently Jekyll only accept the folder structure of `/work/code/_posts/2008-12-24-closures.md` to represent an array of categories, but not a folder structure like `/_posts/work/code/2008-12-24-closures.md`.

I think the later way is more intuitive. Could such alternative folder structure for representing categories (and sub-categories) be added in Jekyll?

In fact, I think issue #2645 actually assumes the proposed folder structure works, but it actually isn't.

**Comment by parkr** [comment]
We tried supporting this in 3.0.0 and it broke _tons_ of sites because the URL's changed for the posts. This is unfortunately not possible for us at this point.

**Comment by ickc** [comment]
So unfortunate. Thanks for the update on the reason why it can't be done.
