### ISSUE TITLE
Verbose build does not explain why future posts are skipped

### ISSUE THREAD

**Issue by zandaleph** [jekyll/jekyll#4507]
I'm a new Jekyll user, just getting started with my first jekyll blog.  I attempted to create a future-dated post about my experiences with Jekyll, and then was very confused when it was not published with either `jekyll serve` (which I was running in the background) or `jekyll build`.  A bit of poking around led me to try `jekyll build --verbose`, which generated the output below.  It was only a few minutes later that I realized what was probably happening, moved the post date back a couple days, and then tried again.  It would have been very useful for the background server and the verbose build to emit a message explaining why the file was skipped.

> $ jekyll build --verbose
  Logging at level: debug
Configuration file: /Users/zspencer/Code/testblog/_config.yml
         Requiring: kramdown
            Source: /Users/zspencer/Code/testblog
       Destination: /Users/zspencer/Code/testblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
           Reading: _posts/2016-02-10-welcome-to-jekyll.markdown
           Reading: _posts/2016-02-11-using-jekyll-as-a-layout-engine.markdown
         Rendering: _posts/2016-02-10-welcome-to-jekyll.markdown
  Pre-Render Hooks: _posts/2016-02-10-welcome-to-jekyll.markdown
  Rendering Liquid: _posts/2016-02-10-welcome-to-jekyll.markdown
         Requiring: rouge
  Rendering Markup: _posts/2016-02-10-welcome-to-jekyll.markdown
         Requiring: kramdown
  Rendering Layout: _posts/2016-02-10-welcome-to-jekyll.markdown
         Rendering: _posts/2016-02-10-welcome-to-jekyll.markdown
  Pre-Render Hooks: _posts/2016-02-10-welcome-to-jekyll.markdown
  Rendering Liquid: _posts/2016-02-10-welcome-to-jekyll.markdown
  Rendering Markup: _posts/2016-02-10-welcome-to-jekyll.markdown

**Comment by hubgit** [comment]
Same here - it took a while to work out that I needed to add `future: true` to `_config.yml` for future-dated posts to show up. Perhaps `--serve` could output a warning message like "3 future-dated posts were skipped", and a note about adding `--future` to render them, and needing the setting in `_config.yml` for GitHub Pages?

**Comment by envygeeks** [comment]
Shouldn't it be obvious that today `11/02/2016` is not `14/02/2016` and anything I write for the 14th won't be published?

**Comment by hubgit** [comment]
> Shouldn't it be obvious that today 11/02/2016 is not 14/02/2016 and anything I write for the 14th won't be published?

Not if it didn't work like that in the previous version of Jekyll :smile:

**Comment by envygeeks** [comment]
Can you elaborate what you mean by previous version? If it's 2.x to 3.x then I do not agree, if it's 3.0 to 3.1 then I agree.  Major versions are anything goes.

**Comment by hubgit** [comment]
In my case, future posts stopped rendering in GitHub Pages when Jekyll was upgraded from v2 to v3 - it took a while to figure out locally that the `future: true` setting was needed, partly because there was no message saying that posts were being skipped.

**Comment by envygeeks** [comment]
So the problem here isn't that we changed the feature it's that we don't log it, which I definitely agree with you on, we used to have a lot message about skipping posts from the future, I wonder what happened to it or if I was just imaging things.

**Comment by zandaleph** [comment]
I think with the added debug line I'm satisfied this issue is resolved.  Thank you for the support and guidance in resolving this issue.

**Comment by moviuro** [comment]
Would it make sense to print a warning in the default build behavior (the **not** verbose one) such as:

    post xxx.md was written in the future! I'm not a DeLorean.

I nearly lost my cool trying to find out why my latest post wasn't showing.
