### ISSUE TITLE
Gem-based themes

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#4510]
Similar to what we did with Gem-based plugins, we should introduce the concept of Gem-based themes, making it easier for users to style their content, and hopefully creating a more robust theme ecosystem.

### How themes work today

Today, while there are lots of great Jekyll themes out there, the installation process generally involves either forking a repo or copying files into the destination site. The problem with this approach, beyond ease of use and the ability to quickly switch themes, is that there's no good way to downstream subsequent updates (not to mention, from a DRY perspective, the theme's CSS and templates now exist in hundreds or thousands of repos, each with their own versions and edits).

### How Gem-based themes would work for users

Find a theme you like? Simply add `theme: awesome-theme` in your site's `_config.yml` file. That'll instruct Jekyll to load the Gem-based theme, just like it would any plugin. The theme would be able to register layouts, and its static assets (css, javascript, images, etc.) would be automatically included in the built site. Heck, maybe there's even an `{{ asset_include_tag }}`, or similar, to include the theme's assets in your HTML. Lets say the theme has a `main` layout. If you don't like it, simply create a layout in your standard `_layouts` folder with the same name. At render time Jekyll will first look to the user's layouts and includes, and if one doesn't exist, it'll then look to the theme's. As an added bonus, if you're just using the theme defaults, we've allowed you to better separate content from presentation, as your repo is now almost entirely your own content, with less Jekyll noise getting in your way.

### How Gem-based themes would work for theme creators

Themes are just Gems with a defined folder structure, not unlike the Jekyll site itself. The only required file would be the Gemspec itself. Beyond that, you can introduce as many layouts you'd like, in a `_layouts` folder, the same with `_includes`. For assets, the `_sass` folder can automatically be included in sass's include path (meaning the user could just do `@import 'awesome-theme'` to include your css in there own). We can also define some sort of `assets` (`_assets`?) folder, which'll be automatically included as a whole, in the built site. Heck, maybe themes can even be dependencies of other themes (e.g., a vanilla Bootstrap theme might be a dependency of Hyde). We'll probably also want to include a screenshot in a predictable path.

### A note on security

From a GitHub Pages perspective, it'd be important to us that themes not be allowed to contain any server-side executable code (e.g., only liquid-based logic). As far as I understand it, the Gemspec isn't executed once the Gem is built. That would allow us to very quickly whitelist a large number of themes for use with GitHub Pages (and would then not have to strictly version each), allowing theme developers to push updates to Rubygems, which would then update the version used by GitHub Pages, without requiring (much) human intervention. If themes need advanced functionality, they can require a plugin (which could go through the existing review process).

### A note on conventions

Right now, everyone has their own design patterns. Is it `site.title` or `site.name`? `site.description` or `site.tagline`? `layout: main` or `layout: default`? For themes to be truly fungible, we'll probably want to put out some sort of style guide for themes, describing common design patterns, and how best to implement them in cross-theme ways.

### A note on our own theme

If we went down this path, the default Jekyll theme (that's bundled with Jekyll), would be pulled out into its own Gem. `jekyll new` could them simply create the necessary config and folder structure. Heck, maybe `jekyll new` could even take a theme name and be capable to generate a boilerplate site for any theme.

Thoughts? I Know there's some prior art within Octopress, but think making themes first class citizens of the Jekyll world, like we did for plugins, could go a long way to level up the Jekyll publishing experience, especially for new users.

**Comment by envygeeks** [comment]
> `{{ asset_include_tag }}`

The `asset_` prefix and `{{ asset }}` tags are well known in `jekyll-assets` this will muddy our tags and the include tag is a planned tag for us as users keep asking us to allow merging assets outside of Sprockets.  So this further exacerbates that.

> We can also define some sort of assets (_assets?)

`jekyll-assets` uses this folder, I would be pretty angry to see that Jekyll started taking over our well known folder and muddied our meaning of it for it's own purposes further complicating our goals on `jekyll-assets` because of shallow design.

**Comment by benbalter** [comment]
> I would be pretty angry to see that Jekyll started taking over our well known folder and muddied our meaning of it for it's own purposes

It looks like the `_assets` folder is just used for images, fonts, etc. Unless I'm misunderstanding, theoretically, a theme could have an `_assets` folder, that would work with `jekyll-assets`, no?

**Comment by envygeeks** [comment]
@benbalter they could, if `_assets` had `images/`, `fonts/`, `css/` and others (which if that happened I would be :+1: all the way,) which is something I've been hoping that Jekyll itself would adopt for it's basic processors to that `jekyll-assets` could be the big brother to Jekyll's own scss and other processors and be a straight up advanced drop in replacement for full on asset management.

**Comment by geraldb** [comment]
Hello, if I may add my two cents on themeing. I'd say ideally you can simply "link" in a theme to your site in the theme folder using a git submodule. See Hugo or other site builders / generators where it works today. That way you can, for example, install a couple of themes (lets say three) and ideally switch the theme just by changing the `theme` settings in `_config.yml`.  Bundling up themes into gems would be a nice extra. Keep it up. Cheers.  PS: FYI: There's also a related discussion thread titled ["What is the future of Octopress Ink?"](https://talk.jekyllrb.com/t/what-is-the-future-of-octopress-ink/1471) in the jekyll talk forum.

**Comment by envygeeks** [comment]
@geraldb I like the premise behind what `submodule` does but I think for the sake of quickness when it comes to new users people should consider `subtree` instead: https://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/ it just makes life easier for regular users.

**Comment by erlend-sh** [comment]
Super psyched about this! Would be a great topic for [JekyllConf](http://jekyllconf.com/).

cc @imathis

**Comment by benbalter** [comment]
>  I'd say ideally you can simply "link" in a theme to your site in the theme folder using a git submodule (or low-tech just unpack a theme zip archive).

The challenge with submodules, is that there's a high degree of technical complexity involved. I've been using Git for years and I still have to look up the commands each time. Not to mention, it requires you to have Git locally and feel comfortable using the command line. 

In terms of subsequent upstream updates, there's no way to semantically version a git submodule, meaning you just have to blinding update to the latest version. And unlike all other dependencies (Kramdown, Rouge, etc.), the theme would have its own upgrade process, independent of `bundle update`, and in the case of zip files, that gets even more complicated, as you're taking things out of version control completely.

> That way you can, for example, install a couple of themes (lets say three) and ideally switch the theme just by changing the theme settings in _config.yml

Yes! This should be possible, with what I described above. You could have multiple themes "installed" by adding them to your Gemfile, and could switch between them by simply changing an option in your config file.

**Comment by geraldb** [comment]
@benbalter  The idea is that a theme is just a git repo, that is, a bunch of files and folders. A "normal" user just unpacks an archive in the theme folder. I'd argue that bundling up a theme into a Rubygem is beyond most users skills. The idea is to keep it as simple a possible e.g. just a bunch of files (in a git repo).  Using a theme "linked" in with a git module is just an "advanced" option as would be using a "gem". A mentioned above Hugo might be a "real world" model to study (for inspiration) - see https://gohugo.io/themes/installing  as are other static or dynamic site builders such as WordPress and others.  Anyways, thanks for the consideration and thanks for all the great plugins (avatar, seo, sitemap, feed, etc.) and the GitHub Pages push to Jekyll 3. Keep it up. Cheers.

**Comment by benbalter** [comment]
@geraldb Totally with you, and in what I'm proposing above, themes are just repos, so the above would be possible for those that prefer. The biggest limitation with unpacking an archive is that it requires command-line, or at least local access. Imagine a completely wed-based publishing flow, where you simply choose a theme and start adding content. 

Not to mention, there's something to be said for separating content from presentation and DRYing up Jekyll sites. For most users, there's no reason to have a third-party theme cluttering up their site's version control (or to have 30,000 different versions floating around, each with one edit never surfaced upstream).

The other limitation is that archive or submodule based themes are limited to one folder, so while assets (css, javascript) may copy cleanly, things like vendoring layouts and includes do not, as you cannot currently have multiple layout or include folders. 

The other advantage of the above is an idea similar to WordPress's template hierarchy, in which I theme can have a `default.html`, but if I don't like it, I can add my own to my site (not modifying the theme itself), which Jekyll could use instead, still giving me access to includes, other templates, assets, etc.

See where you're coming from, and a big fan of Hugo, I'm hoping the Jekyll theme ecosystem can (and should be) much bigger than one repo would safely allow! :smile:

**Comment by geraldb** [comment]
@benbalter   If I may add one more comment:

> Yes! This should be possible, with what I described above. You could have multiple themes 
> "installed" by adding them to your Gemfile, and could switch between them by simply changing an 
> option in your config file.

I'd argue that keeping the option of just a bunch of files and folders (that you can copy or more "advanced" link into a theme folderwill make it easier (in addition to the option for bundled gems) e.g.:

- GitHub does NOT need to whitelist any themes (less work and more choice) and, thus,
- Jekyll users you can use whatever theme they like  - even on GitHub Pages.

**Comment by alias1** [comment]
I really like the idea of gem-based themes, so long as there is still the option to overwrite the files we want to customize (something along the lines of [drupals base/subtheme](https://www.drupal.org/node/441088))

**Comment by fmaida** [comment]
IMHO two nice additions would be:

1) 

Each theme and every asset and partial html file used to render the theme should reside in the same folder. Basically I'm suggesting to drop "_include" and "_layouts" folders and use a "_themes" folder. Inside the _themes folder you should have one subfolder for each theme.
For example:

Default theme --> jekyll-test/_themes/default
Alternative theme --> jekyll-test/_themes/alternative

2)

Each theme subfolder should contain another _config.yml where you could store some preferences that would help defining how that theme should be rendered by Jekyll.

For example, next holidays you could decide to set an option to change the look of the theme, and Jekyll and the theme author could use that parameter to display some festive images (dunno... a santa claus with his sled and the reindeers that flies up in the air on the background of the website... some christmas decorations here and there...)
When the holidays are over you could simply turn that option to false, rebuild the pages and turn the site back to its previous look.


I'm sorry for my bad english... I hope that you'll understand anyway what I'm trying to explain...

**Comment by spudowiar** [comment]
Does GitHub Pages support submodules?

**Comment by benbalter** [comment]
> Does GitHub Pages support submodules?

In some cases. See https://help.github.com/articles/using-submodules-with-pages/

**Comment by spudowiar** [comment]
Neat. Then people using GitHub Pages (AKA Jekyll in `safe` mode) can just use folders and submodules as themes. Other users can also use Gem-based themes.

**Comment by benbalter** [comment]
> Then people using GitHub Pages (AKA Jekyll in safe mode) can just use folders and submodules as themes. Other users can also use Gem-based themes.

To be clear, I'm looking to make Gem-based themes widely available on GitHub Pages (to avoid having to use copy :spaghetti: or resorting to adding submodules via command line).

**Comment by spudowiar** [comment]
+1 on letting themes have a `_config.yml`, you could then support theme extending (e.g. a theme called `base` and an extension of that theme containing `theme: base` in its `_config.yml`)

**Comment by miklb** [comment]
I believe there is some prior art in regards to this and what was planned for [Octopress 3](http://octopress.org/2015/01/15/octopress-3.0-is-coming/). There even seems to be a working(?) theme-as-gem [genesis-theme](https://github.com/octopress/genesis-theme)

Maybe @imathis could shed some light on how far he got on the work on this?

**Comment by ezekg** [comment]
Hey guys, loving the idea of having themes be installable via gems.

But the [theme documentation](https://jekyllrb.com/docs/themes/) is _very_ confusing as it is now. I was searching everywhere trying to find a gem-based theme (even searching https://www.google.com/#q=jekyll+theme+filetype:gemspec) until I realized that this is still in discussion. 

Can we update that site with a disclaimer and possibly link to common places users can find themes right now? I still don't really know where to look to find an easily installable theme.

**Comment by parkr** [comment]
@ezekg This feature is unreleased and I believe no one has created a compatible theme. So you're coming up empty because there's nothing to find yet. 😄 🔜

**Comment by ezekg** [comment]
@parkr, I still think the documentation should be updated until this feature is actually released. It's really, really confusing for newcomers. 👌

**Comment by envygeeks** [comment]
@ezekg that's part of a larger problem unrelated to this.

**Comment by parkr** [comment]
> I still think the documentation should be updated until this feature is actually released. It's really, really confusing for newcomers as it is now. 👌

@ezekg There is no documentation yet so you can bet we will write some! 😄 see https://github.com/jekyll/jekyll/issues/4891

**Comment by ezekg** [comment]
@parkr, what do you mean there's no documentation? The section on themes is live on the Jekyll docs: https://jekyllrb.com/docs/themes/. As it is now, it's telling you to do something that isn't even supported yet. It was definitely confusing for me and prompted me to search for themes installable via Rubygems.

But maybe I'm just misunderstanding and what's outlined in the docs isn't what's being discussed here. I thought it was related but it doesn't look like it from @envygeeks's response. My bad.

Edit: I see that in #4891, you're aware of the issue. Fair enough. Still might want to add a disclaimer if you're going to publish docs about something that isn't fully done. 😜 

Anyways, thanks for the info and links!

**Comment by alias1** [comment]
Should this be reopened, as that commit doesn't really fix this?

Get Outlook for iOS




On Fri, May 13, 2016 at 9:51 AM -0700, "Parker Moore" <notifications@github.com> wrote:












Closed #4510 via 6a2ffba.

**Comment by pathawks** [comment]
> Should this be reopened, as that commit doesn't really fix this?

That's a different issue.

**Comment by alias1** [comment]
@pathawks Different issue?

This issue is now Closed.

> parkr closed this in 6a2ffba 11 hours ago

https://github.com/jekyll/jekyll/commit/6a2ffbac62bccf6eb4e85a8465c5bad8047e5d92
> Add note about being unreleased to the Themes documentation.
> Fixes #4510.

**Comment by pathawks** [comment]
The title of _this_ issue is *Gem-based themes*. The fact that documentation is synced with `master` instead of stable is a very real problem, but that is a different issue. It is also being discussed in #4891

I’m not saying it’s not a problem, only that it is a bigger/different problem than _this_ issue. :+1:

Perhaps a new issue should be opened re: website being out of sync?

**Comment by alias1** [comment]
@pathawks I know what the title of THIS issue is. And I am saying that THIS issue became CLOSED automatically based on the wording in the above mentioned commit.

**Comment by xHN35RQ** [comment]
@parkr did you accidentally close this issue #4510 with 6a2ffbac62bccf6eb4e85a8465c5bad8047e5d92??

**Comment by haslinger** [comment]
It seams, that the _assets folder didn't make it in the code as it is also not in the docs. Is there a different way to include assets (i.e. images, javascript files, fonts) into the gem?

**Comment by thisguy07** [comment]
Who are all u guys

**Comment by parkr** [comment]
@haslinger Not at the moment, no! But we want to add that soon.

I'll push my commit up to jekyllrb.com later today. Sorry for the confusion!

**Comment by chrisfinazzo** [comment]
See #4891.

**Comment by Joshfindit** [comment]
One thing that's really grinding my gears (full disclosure: I'm biased against gem-based themes right now, but I do see the logic and the positive possibilities):

Doing `jekyll serve`, then making a change to a theme file does not rebuild the site.
Being able to effortlessly iterate was huge when I first discovered Jekyll, and now there is much more friction.

**Comment by parkr** [comment]
@Joshfindit We are working on this in Jekyll 3.3. The various theme directories (`_includes`, `_layouts`, `_sass` and in 3.3, `assets`) behave as though they were a Jekyll site. Plop some posts or pages in your theme project as if it were a Jekyll site, run `jekyll serve` and everything should work great. The `example` subdirectory was something we decided was a bad idea after noticing this exact issue.
