### ISSUE TITLE
Undefined method

### ISSUE THREAD

**Issue by chrisfinazzo** [jekyll/jekyll#4511]
On a fresh `bundle install` w/ 3.1.1.

<pre>NoMethodError: undefined method `spec' for nil:NilClass
Did you mean?  inspect</pre>

**Comment by parkr** [comment]
@chrisfinazzo Run with `--trace` and get a line number. This is not enough information.

**Comment by chrisfinazzo** [comment]
Ugh, now it works (Stupid Bundler).

Figures since was messing with `_config.yml` thinking about what kind of work needs to be done [here].

[here]: https://github.com/jekyll/jekyll/issues/4509

Should there be a baseline version requirement for Bundler? In my experience, 1.6.4 and 1.11.2 will both do the job, but for debugging purposes, it might help isolate things further.

Thoughts?

**Comment by envygeeks** [comment]
What do you mean by baseline requirement?

**Comment by chrisfinazzo** [comment]
Just as Ruby 2.0 and higher is required in order to use Jekyll 3, apply that same standard to the use of Bundler.

**Comment by envygeeks** [comment]
I don't think Bundler allows us to do that.
