### ISSUE TITLE
'Could not find' dependencies on Jekyll 3.1.1 (ruby 2.2, Ubuntu 14.04)

### ISSUE THREAD

**Issue by woodruffw** [jekyll/jekyll#4518]
After updating Jekyll to 3.1.1 via `gem`, I encounter a number of `Bundler::GemNotFound` exceptions for older versions of dependencies:

```
/var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find sass-3.4.20 in any of the sources (Bundler::GemNotFound)
	from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `map!'
	from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:87:in `materialize'
	from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
	from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:182:in `specs_for'
	from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/definition.rb:171:in `requested_specs'
	from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/environment.rb:18:in `requested_specs'
	from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:13:in `setup'
	from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:92:in `setup'
	from /var/lib/gems/2.2.0/gems/jekyll-3.1.1/lib/jekyll/plugin_manager.rb:33:in `require_from_bundler'
	from /var/lib/gems/2.2.0/gems/jekyll-3.1.1/bin/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

Upon installing one with `gem -v`, another pops up. This goes all the way down:

```
sass 3.4.20
jekyll-sass-converter 1.3.0
rb-fsevent 0.9.6
rb-inotify 0.9.5
listen 3.0.5
jekyll-watch 1.3.0
```

It then finally states that `jekyll-3.0.1` is missing. Bizarre. After installing that, more not found:

```
redcarpet 3.3.3
```

Then, finally, errors from Jekyll itself:

```
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /home/william/Dropbox/dev/woodruffw.github.io/_config.yml
Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.1.1 | Error:  jekyll-paginate
```

`jekyll-watch` and `jekyll-paginate` are installed, so this is completely mystifying.

I'm completely at a loss to explain this. I doubt it's a direct Jekyll bug, probably just an unexpected interaction. It's worth noting that I don't have any sass whatsoever on my blog, so the `sass` and `jekyll-sass-converter` dependencies don't make much sense to me.

System information:

* Ubuntu 14.04
* `ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux-gnu]`
* Jekyll 3.1.1

I'd greatly appreciate any insight anybody could offer on this.

Best,
William

**Comment by woodruffw** [comment]
I "fixed" this by doing a `gem uninstall --all` and reinstalling `jekyll` completely. Must've been something strange on my end.

**Comment by envygeeks** [comment]
Normally errors like that happen from a funky lock file, normally I just delete vendor and Gemfile.lock and do the same as you did to force a reinstall and it happens.  Rarely does it happen but yeah I've never been able to explain why it happens.

**Comment by woodruffw** [comment]
@envygeeks In this case, it looks like two separate projects of mine are mangling the installed gems somehow. Individually both work fine, but installed together I get these errors with Jekyll and strange SSL errors with the other. 

Very odd, I'll look into it some more. A lockfile problem sounds very probable.
