### ISSUE TITLE
I wonder why do we enable auto index of directory

### ISSUE THREAD

**Issue by wittyfox** [jekyll/jekyll#4520]
When we visit a directory, it will show all files of current directory, but I think maybe we don't want this.

```
def file_handler_opts
  WEBrick::Config::FileHandler.merge({
    :FancyIndexing     => true,
    :NondisclosureName => [
      '.ht*', '~*'
    ]
  })
end
```

Link: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/serve.rb#L102-L109

**Comment by envygeeks** [comment]
Yes, yes I do, as it was a very conscious decision I made when I rebuilt that class.  It is a development server, not a production server and directory indexing aides development sometimes.
