### ISSUE TITLE
page.date variable is always showing midnight

### ISSUE THREAD

**Issue by BradKnowles** [jekyll/jekyll#4521]
When I create a post in the _posts directory, the page.date variable is set to the right date, but the time component is always set to midnight, no matter when I generate the site.

However, when working with drafts, it seems to generate the time portion just fine.

My front matter only specifies
layout: post
title: some text
author: me
excerpt: overriding the default
categories: a list of categories

I'm using jekyll 3.0.3.

Is this by design?

**Comment by pathawks** [comment]
If you don’t specify a time in the YAML, it will use the date from the post’s filename, which only includes year, month, day. The time will default to zero.

You can specify an exact timestamp by setting the `date` field in the YAML.

**Comment by parkr** [comment]
Thanks, @pathawks!

**Comment by BradKnowles** [comment]
Thanks @pathawks for the clarification!
