### ISSUE TITLE
Raw CSS imports support

### ISSUE THREAD

**Issue by eberkund** [jekyll/jekyll#4527]
SASS now supports [merging CSS files when you omit the file extension](https://github.com/sass/libsass/pull/754) however it doesn't appear to work in Jekyll (3.1.1). This is a very handy feature for those of using a dependency manager like bower. I've also tried the [sass-css-importer gem](https://rubygems.org/gems/sass-css-importer/versions/1.0.0.beta.0) but that doesn't seem to work either.

**Comment by parkr** [comment]
@eberkund This will have to be made available to the Ruby Sass library. Unless it's in Sass v4, [we should be all set](https://github.com/jekyll/jekyll-sass-converter/blob/master/jekyll-sass-converter.gemspec#L18).

**Comment by eberkund** [comment]
Or would moving to [sassc-ruby](https://github.com/sass/sassc-ruby) be a possibility? (much faster compile times also)

**Comment by parkr** [comment]
> would moving to sassc-ruby be a possibility

No, unfortunately C extensions are too tenuous for Windows users. We run into enough installation issues as it is, sadly.
