### ISSUE TITLE
Posts of current date can't be displayed by ghpages but when today becomes yesterday, they will be displayed.

### ISSUE THREAD

**Issue by Youmoo** [jekyll/jekyll#4528]
I have a [ new post](https://github.com/Youmoo/youmoo.github.io/blob/master/_posts/2016-02-16-%E4%BD%A0%E6%B0%B8%E8%BF%9C%E6%97%A0%E6%B3%95%E5%8F%AB%E9%86%92%E4%B8%80%E4%B8%AA%E8%A3%85%E7%9D%A1%E7%9A%84%E4%BA%BA.md) written today, ghpages does not show it , can you tell me why? Sorry for my poor English.

**Comment by Youmoo** [comment]
Here is my site: http://xiaoyuan.life which shows only posts older than today

**Comment by envygeeks** [comment]
If it works locally you might need to email support@github.com and ask them to look into it further as we do not control Jekyll on their servers and only they could provide you with (or guide you to) getting more detailed logs so we or you can dig deeper.

**Comment by Melyanna** [comment]
Can you check if you have received any automatic email from the github support titled something like "Page build failure" ?
See here: https://help.github.com/articles/troubleshooting-github-pages-build-failures/
Note: I am not github support.

**Comment by pathawks** [comment]
Did you set a timezone in the post `date` in the YAML front matter?

This sounds like a timezone issue.

**Comment by parkr** [comment]
I think @pathawks is right. See http://jekyllrb.com/docs/upgrading/2-to-3/#all-my-posts-are-gone-whered-they-go and write support@github.com if it continues to fail to show up.

**Comment by Youmoo** [comment]
Adding a timezone works. Thank you all.
