### ISSUE TITLE
Run Jekyll on AWS Lamda

### ISSUE THREAD

**Issue by jfaerman** [jekyll/jekyll#4532]
I'm interested in running (or documenting how to run) jekyll inside AWS Lambda (https://aws.amazon.com/lambda/) and would love to contribute to that, if that would be interesting or not yet done.

My first idea was running Jelyll using JRuby and Lambda for Java... but i've seen other approaches, such as falling back to the container shell.

Thoughts?

**Comment by pathawks** [comment]
This discussion would probably be better suited on [talk.jekyllrb.com](http://talk.jekyllrb.com), since this is not an “issue" with Jekyll.

But yes, I am very interested in this idea :+1:

**Comment by parkr** [comment]
Agreed with @pathawks! Please talk on talk.jekyllrb.com. Once you have a guide, feel free to add a docs page to our site by submitting a PR. :smile:

**Comment by jfaerman** [comment]
Moved there! Thanks for the attention and sorry for the non-issue.
