### ISSUE TITLE
How can I set rouge theme to sublime monokai?

### ISSUE THREAD

**Issue by kasperdevs** [jekyll/jekyll#4536]

**Comment by envygeeks** [comment]
This is out of scope as it's not a bug in Jekyll. Please ask your question at https://talk.jekyllrb.com

**Comment by parkr** [comment]
@kasperdevs Agreed with @envygeeks – the answer to your question is that you have to add the `.css` to your site. You can't set it through Jekyll directly, you have to [install it via `rougify style monokai.sublime > css/monokai-rouge.css`](https://github.com/jneen/rouge#css-theme-options)
