### ISSUE TITLE
Numeric post titles always fail an `if post.title == "123"` comparison

### ISSUE THREAD

**Issue by hlilje** [jekyll/jekyll#4552]
###### What version of Jekyll are you using (`jekyll -v`)?

3.0.2

###### What operating system are you using?

Ubuntu 14.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

The comparison `if post.title == "123"` is always false if the post title `123` is entirely numeric. It works fine if I add a one letter to the post title, like `12b3`, and check for that.

###### What did you expect to see?

I tried to find the post titled `404`, but the comparison failed when checking `if post.title == "404"`.

###### What did you see instead?

No post was found, though if I print all post titles one post is clearly titled `404`.

**Comment by pathawks** [comment]
In your YAML, are you setting title as a string with quotation marks?

```yaml
post: "404"
```

**Comment by hlilje** [comment]
No, I must try that later.

**Comment by hlilje** [comment]
Yes, that fixed it. I assumed that the front matter always consisted of strings.
