### ISSUE TITLE
Default _config.yml contains site variables that aren't explained in the docs (github_username and twitter_username)

### ISSUE THREAD

**Issue by detly** [jekyll/jekyll#4556]
Jekyll version: 3.1.2
OS: Ubuntu 14.04.1 LTS

A default install of a Jekyll site (via `jekyll new whatever`) produces a site with a `_config.yml` containing:

```
twitter_username: jekyllrb
github_username: jekyllrb
```

Naturally I change these to `detly` and then wonder... what other links are available? How do these variables work?

Since I'm editing this in the default `_config.yml`, I go to the [Jekyll documentation for configuration](http://jekyllrb.com/docs/configuration/). There is no mention of these variables, nor is there any mention of general branded 3rd party site links at all.

I think that if Jekyll's out-of-the-box config file is going to contain something, it should probably be mentioned in the basic documentation. I incorrectly guessed that this was some sort of plugin, and spent ages searching for what made them work, before realising that they were a kind of global variable and worked via the `_includes/icon-github.html` template.

I don't see this kind of mechanism mentioned in the config docs. It goes into YAML front matter defaults, but it doesn't say you can just straight-up type random variables in here and have them be available to every template via the `site` namespace. (I <kbd>ctrl</kbd>+<kbd>f</kbd>ed for `site.` on that page and didn't see anything; sorry if it actually is there and I skipped over it.)

> The configuration file also allows you to set site-wide variables (eg. `my_variable`) that can be accessed as `site.my_variable`. The default `_config.yml` already contains a couple of these: `github_username` and `twitter_username`. You'll notice in the default site layout, these produce branded links to the corresponding Twitter and Github account. The template `_include/footer.html` and `_include/icon-github.html` show you how to use these: just reference the `site.github_username` to determine what to include and how to construct the appropriate URLs.

**Comment by envygeeks** [comment]
These variables are for the default template, they are not a part of Jekyll in all technicality.

**Comment by detly** [comment]
I still think there should be *some* explanation, somewhere, of what they are and why they're in there. Even a comment in the config file.

**Comment by parkr** [comment]
@detly I would love to see a PR that explains these! It's a good introduction into site-specific variables.

**Comment by detly** [comment]
Do you think it belongs as a comment in the config file or a full explanation in the docs?

**Comment by detly** [comment]
Oh, oops, I see it's already explained in [site variables](http://jekyllrb.com/docs/variables/). A comment referring to this probably works then.
