### ISSUE TITLE
Atx-style Markdown headings aren't generated unless there's whitespace between "#"s and heading text

### ISSUE THREAD

**Issue by mattgemmell** [jekyll/jekyll#4563]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.2

###### What operating system are you using?

OS X El Capitan 10.11.3

###### What did you do?

Using Markdown atx-style headers (i.e. with hash-symbols at the beginning of a line), but without any whitespace between the last "#" and the actual heading text.

###### What did you expect to see?

Expected normal heading-generation, as in previous versions.

###### What did you see instead?

Heading-generation with atx-style headers is broken unless there's whitespace between the hash-symbol(s) and the actual text of the heading.

**Comment by pathawks** [comment]
This sounds like it is probably an issue with your Markdown converter, rather than with Jekyll itself.

What Markdown converter are you using? You said that this behavior has changed in a recent version of Jekyll; can you be more specific?

**Comment by geraldb** [comment]
@mattgemmell  If I dare to say that's a bug in your markdown. Just add the missing space and you are on the save side. See the [Jekyll FAQ](https://github.com/planetjekyll/quickrefs/blob/master/FAQ.md) entry titled "Why are my page headings (e.g. ##Heading) not rendered any longer?". Cheers.   PS: If I dare to say that's not really a bug but really a usage question, thus, post it to the [Jekyll forum](https://talk.jekyllrb.com).

**Comment by mattgemmell** [comment]
Thanks for the reply. I've already done a bulk update of all headings in my site's Markdown files, and that's fine. Just seemed odd that it would (apparently) change between 3.1.1 and 3.1.2, without independently updating kramdown. And if _I_ dare to say, whilst more legible, whitespace in that context ought to be optional. :)

**Comment by geraldb** [comment]
You can use the [Babelmark 2](http://johnmacfarlane.net/babelmark2/?text=%23%23Heading) service to see how different markdown flavors (processors) handle whitespace in headings. The safe "standard" way is using a space.  Cheers. PS: You might close the ticket. I'm just a random guy (don't have any permission):

**Comment by mattgemmell** [comment]
@geraldb Thanks. The Babelmark service shows that kramdown does recognise atx headings without whitespace, which is contrary to the behaviour I'm recently seeing. I think I'll leave this one open, just in case there's somehow something going on with Jekyll in this context. It really has just been since the latest update, and as you point out, it seems to be contrary to how the Markdown library behaves on its own.

**Comment by geraldb** [comment]
@mattgemmell There's nothing wrong. GitHub Pages (and Jekyll) uses the GitHub-Flavored Markdown (GFM) mode for kramdown (as a new default), thus, no space. See [kramdown GFM Parser](http://kramdown.gettalong.org/parser/gfm.html). Cheers.

**Comment by mattgemmell** [comment]
OK. Closing this, then; thanks.

**Comment by parkr** [comment]
@mattgemmell I have added a note about this in our internal issues – thanks!

**Comment by benbalter** [comment]
From the Kramdown GFM page:

> ATX headers need a whitespace character after the hash signs.

Any idea why that's a condition? Testing on GitHub.com, at least in practice, the space isn't required.

**Comment by parkr** [comment]
@benbalter Where did you test it? See:

##Hello

**Comment by benbalter** [comment]
> Where did you test it?

So this is fun. It doesn't work in comments, but it works in READMEs.
