### ISSUE TITLE
Pagination not work on 3.1.2

### ISSUE THREAD

**Issue by tmtxt** [jekyll/jekyll#4568]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.2

###### What operating system are you using?

Mac OS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I updated to jekyll 3.1.2. I follow the instruction to add `gems: [jekyll-paginate]` to _config.yml. I also install `jekyll-paginate` gem by `gem install jekyll-paginate` but the pagination did not work on index.html file. I changed nothing except the _config.yml file. Here is my repo https://github.com/tmtxt/tmtxt.github.com

**Comment by eastwood** [comment]
I'm also getting this error.
Not sure what's happening, `site.posts` works as normal.

**Comment by bk2dcradle** [comment]
Same here

**Comment by pathawks** [comment]
Sorry to hear you are having trouble.

This is an issue with [**jekyll-paginate**](https://github.com/jekyll/jekyll-paginate) rather than **Jekyll** itself. Unfortunately, **jekyll-paginate** has been retired.

**Comment by parkr** [comment]
@tmtxt Remove `safe: true` from your `_config.yml` and it should work.

<img width="1239" alt="screen shot 2016-03-23 at 1 40 33 pm" src="https://cloud.githubusercontent.com/assets/237985/14000112/eb544e92-f0fc-11e5-9328-e8f47c146daa.png">

Confirmed it's working in HEAD so closing this.

**Comment by tmtxt** [comment]
thanks, it works now!

**Comment by sverrirs** [comment]
Here is a re-written pagination plugin I've recently finished, could be a viable alternative for you. https://github.com/sverrirs/jekyll-paginate-v2
