### ISSUE TITLE
Layout variable inheritance not working properly

### ISSUE THREAD

**Issue by tjkohli** [jekyll/jekyll#4571]
So I found a perplexing issue here. First, I thought it was my fault, but I spent an hour and reduced the case and found a replicable issue in Jekyll.

###### What version of Jekyll are you using (`jekyll -v`)?
3.1.2

###### What operating system are you using?
Mac OS X 10.11.3 (15D21)

###### What did you do?

I have attached a .zip of a reduced example.

This is what you have to do
- Have two pages, one with a default layout and another with an alternate layout
- Default layout has no front-matter but alternate layout has one custom variable specifying a subtitle
- Both layouts share an `include` that contains `if layout.subtitle != null` logic testing the existence of the variable, and if present, writing its value to the page

###### What did you expect to see?

As it worked in Jekyll 2, I expected the logic in the `include` to not write the subtitle for the pages using the layout where it is not specified, and write it on the pages using the layout where it is specified.

###### What did you see instead?

I see Jekyll writing the subtitle for both pages. Please run and see the attached use case for details.

I am aware of the change from page.variable to layout.variable for accessing layout front-matter. I already made this change and the bug still exists.

In some cases, when I re-save the default.html layout, the site builds correctly, but saving another file elsewhere causes the unintended behavior again.

[layout-test.zip](https://github.com/jekyll/jekyll/files/143473/layout-test.zip)

###### Notes

Both test pages are identical other than some static text.
Both test layouts are identical other that one has a variable defined and one doesn't.

**Comment by jeremenichelli** [comment]
_*+1*_ I have the same issue. My site has a `default` layout, and then I have a `post` layout that has a variable (so I don't have to add it for each post) and it worked perfectly in 2.x, since 3.0 it's not.

**Comment by axelfontaine** [comment]
+1 Layouts and yaml seem completely broken in Jekyll 3. I am experiencing lots of random issues including this one.

**Comment by axelfontaine** [comment]
Due to the randomness of the issues I am facing (the page and layout objects contain new elements only contained in other page & layouts), I believe some collections are being cleared properly when iterating over the different pages to generate. This is super frustrating as certain page randomly pick up liquid attributes of others if they aren't explicitly set. **Mega fail !!!**

**Comment by jeremenichelli** [comment]
I don't think is random. Basically this is what has been changed:

- **2.x** every property assinged through YAML matter was inherited by the `page` Liquid variable, so `page` held all layout variables and pages.
- **3.x** the `page` variable only holds properties assigned to the specific page is being rendered.

I don't know if this is expected, because it makes some sense, thing is I didn't see this in the changelog and the implicance is big. For example, I use a `type` property for each page to do some almost-dynamic  stuff, but for my post I put that variable in the post.html layout file so I don't have to write it in every single post I create. This stopped working since **3.0**.

I hope some maintainer can shed some light on this. and at list confirm that is a bug or if it was on porpuse.

**Comment by axelfontaine** [comment]
Well yes, there is that, as well as #4540 and the randomness I explained. It is overall a very broken experience.

**Comment by budparr** [comment]
Not sure if this is helpful, but it might just be the way you were able to reference it in the past.

> Introducing: layout. In Jekyll 2 and below, any metadata in the layout was merged onto the page variable in Liquid. This caused a lot of confusion in the way the data was merged and some unexpected behaviour. In Jekyll 3, all layout data is accessible via layout in Liquid. **For example, if your layout has class: my-layout in its YAML front matter, then the layout can access that via {{ layout.class }}**.

https://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata

**Comment by jeremenichelli** [comment]
@axelfontaine not random, just that `page` is not inheriting from `layout` property. At least that's what I'm seeing in difference with **2.x**.
---
OK, there we go, thanks a lot @budparr, now it makes sense. Thanks for taking the time to search for that reference. I've already changed the approach to check the variable  existence in the `layout` namespace on my site.

**Comment by tjkohli** [comment]
@parkr Any thoughts on this?

**Comment by axelfontaine** [comment]
@jeremenichelli  No, It is much worse than that. It is so broken in random ways, it is not even funny.

Example:

Layout `default` has no class
`Layout1` uses `default` and has `class: my-layout`
`Page1` uses `Layout1` and has `class: other`

In that case both `page.class` and `layout.class` will work as @budparr described

Now add `Page2` which uses `default` and has `class: abc`

This will be correct for `page.class`, but will sometimes return `other` for `layout.class` !!!

And to add insult to injury now add `Page3` which uses `Layout1` and has no class.

There `layout.class`will be correct, but `page.class`sometimes contains `abc` !!!

**Comment by tjkohli** [comment]
I don't think it happens randomly with my specific issue.

Layouts **without** the variable explicitly defined seem to inherit the attributes of the _next_ layout that has it defined. Sometimes, the next one is the only one. Other times, it's next in the alphabetical list (processing order, I assume?) of layouts. 

Needless to say, although I do experience randomness with the issue happening vs. not happening depending on what file I last touched, the layout that inheritance incorrectly comes from is very consistent.

**Comment by axelfontaine** [comment]
@tjkohli I indeed also suspect something like that (see my earlier comment with collections probably not being cleared properly while iterating)

**Comment by daattali** [comment]
Seems related to https://github.com/jekyll/jekyll/issues/4439

**Comment by daattali** [comment]
Had this been fixed?

**Comment by parkr** [comment]
@daattali in Jekyll 3.1.4, yes.
