### ISSUE TITLE
Is github-pages-51 needed for servers?

### ISSUE THREAD

**Issue by Ninetailz** [jekyll/jekyll#4572]
###### What version of Jekyll are you using (`jekyll -v`)?
3.1.2

###### What operating system are you using?
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Tried to uninstall Jekyll 3.0.3 gem, i already have Jekyll 3.1.2

###### What did you expect to see?

Tried to just get rid of Jekyll's old gem version which was 3.0.3

###### What did you see instead?

ninetailz@kawaiidesu:~/forbidden/blog$ gem uninstall jekyll --version 3.0.3     
You have requested to uninstall the gem:
        jekyll-3.0.3

github-pages-51 depends on jekyll (= 3.0.3)
jekyll-feed-0.4.0 depends on jekyll (< 3.1.0, >= 2.4.0, development)
If you remove this gem, these dependencies will not be met.

-- My blog is hosted on my server not on Github pages or Github repo, is it safe to uninstall these two to get rid of the old version of Jekyll

**Comment by parkr** [comment]
> My blog is hosted on my server not on Github pages or Github repo, is it safe to uninstall these two to get rid of the old version of Jekyll

Yes, it should be safe to remove Jekyll v3.0.3 as long as you don't need jekyll-feed 0.4.0. :)

**Comment by Ninetailz** [comment]
Is jekyll-rss needed for my feed.xml file which is the rss? or can i reinstall the gem after i get rid of github-pages-51

**Comment by envygeeks** [comment]
@Ninetailz you can reinstall it on the latest Jekyll.
