### ISSUE TITLE
Allow checking if a tag exists

### ISSUE THREAD

**Issue by jeaye** [jekyll/jekyll#4573]
###### What version of Jekyll are you using (`jekyll -v`)?

Github Pages (jekyll 3.0)

###### What operating system are you using?

Github Pages

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I have a shared header include across multiple jekyll sites. One of them is to use an [Atom Feed](https://help.github.com/articles/atom-rss-feeds-for-github-pages/) and requires `{% feed_meta %}` within `<head>`. I'd like to be able to check for the existence of tags and conditionally use them. When this didn't work with `if`, like so:

```liquid
{% if feed_meta %}
  {% feed_meta %}
{% endif %}
```

I tried wrapping it in a variable for the if expression instead, adding a bool to my `_config.yml`:

```liquid
{% if site.has_feed %}
  {% feed_meta %}
{% endif %}
```

###### What did you expect to see?

I expected that meta-programming on tags would be permitted, allowing more code reuse, in my case.

###### What did you see instead?

In both cases shown above, the jekyll build fails, as `feed_meta` is an unknown tag. I haven't yet found a way to share this header which may or may not use the `feed_meta` tag.

Note that this isn't bound to the effects or origins of `feed_meta` itself; the lack of meta-programming capabilities with tags is the issue I'm bringing up. `feed_meta` is used for illustration and context.

**Comment by envygeeks** [comment]
This belongs upstream at https://github.com/shopify/liquid

**Comment by jeaye** [comment]
Word. I've opened it up over here https://github.com/Shopify/liquid/issues/704
