### ISSUE TITLE
Control Liquid's `error_mode` through config.yml

### ISSUE THREAD

**Issue by catherinedevlin** [jekyll/jekyll#4574]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.0.0

###### What operating system are you using?

Ubuntu 15.10

###### What did you do?

Used a filter inside an {% if %} tag.  Took many grey hairs to realize that Liquid was simply silently discarding the filter.

In `_plugins/always_false.rb`:

    module Jekyll
      module AlwaysFalse
        def always_false(input)
          false
        end
      end
    end

    Liquid::Template.register_filter(Jekyll::AlwaysFalse)

In a post:

    {% assign val = true %}
    {{ val | always_false }} means {% if site | always_false %} true {% else %} false {% endif %}.

###### What did you expect to see?

    false means false .

###### What did you see instead?

    false means true .

This plain Ruby file, run without Jekyll, duplicates the error:

    require 'liquid'

    module FalseFilter
      def return_false(input)
        false
      end
    end

    Liquid::Template.register_filter(FalseFilter)
    Liquid::Template.error_mode = :lax

    template = %q({% assign val = true %}
    {{ val | always_false }} means {% if site | always_false %} true {% else %} false {% endif %}.
    )

    puts Liquid::Template.parse(template).render

... but, if `Liquid::Template.error_mode = :lax` instead, then Liquid throws `Liquid syntax error: Expected end_of_string but found pipe` appropriately.

I suggest that config.yml support a directive like `errors: strict`.

(Related, but closed without resolving: https://github.com/jekyll/jekyll/pull/4393)

**Comment by tjkohli** [comment]
Are you able to update to 3.1.2 and see if it is resolved there?

**Comment by envygeeks** [comment]
I don't think it's resolved there, not the suggestion of the errors configuration option.  I like that idea too because sometimes I just wish errors were a bit more strict, especially on a few of our builders.

**Comment by tjkohli** [comment]
I see. I don't have many problems with the errors in 3.x. If anything, I wished the warnings were more verbose because Jekyll 3 does a lot of falling-back fail-safe type stuff and I usually don't know that things are failing.

**Comment by parkr** [comment]
@catherinedevlin I don't think Liquid supports pipes in `if`. You'd have to do something like:

```liquid
{% assign val = true %}
{% assign new_val = site | always_false %}
{{ val | always_false }} means {% if new_val %} true {% else %} false {% endif %}.
```

If you'd like to see pipes supported in Liquid, please file an issue on [Shopify/liquid](https://github.com/Shopify/liquid/issues/new). :smile:

**Comment by catherinedevlin** [comment]
What I mean is that, *because* Liquid doesn't support pipes, a way to see messages from Liquid when it encounters something it doesn't support while building in Jekyll would be great.
