### ISSUE TITLE
How to make .mp4 downloadable?

### ISSUE THREAD

**Issue by Ninetailz** [jekyll/jekyll#4576]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.2

###### What operating system are you using?

Ubuntu 14.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Tried to make a .mp4 file download

###### What did you expect to see?

The video file to download

###### What did you see instead?

It was playing the video instead

-- My question how to i make the video download, instead of it being just played?
My directory is structured like this
- dl
 - video.mp4

I am using nginx server

**Comment by envygeeks** [comment]
Please ask your question at https://talk.jekyllrb.com
