### ISSUE TITLE
hello，I want to translat jekyll document。because i want to convenient for china developers，i hope join to jekyll github organization 。

### ISSUE THREAD

**Issue by CoderBOBO** [jekyll/jekyll#4577]

**Comment by tjkohli** [comment]
Hi @CoderBOBO, thank you for your willingness to help improve Jekyll!
To get started, please feel free to fork this project and work on improving it on your own!

Here are the [Github Guides (English)](https://guides.github.com) and [Google-translated to Chinese](https://translate.google.com/translate?sl=en&tl=zh-CN&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fguides.github.com&edit-text=&act=url).

**Comment by parkr** [comment]
@CoderBOBO We don't have any official translations, unfortunately. The Japanese-speaking community setup a repo like this: https://github.com/jekyllrb-ja/jekyllrb-ja.github.io

It is working well for them, I think! Thanks for your interest. :smile:
