### ISSUE TITLE
Jekyll install fail

### ISSUE THREAD

**Issue by icarlosmendez** [jekyll/jekyll#4579]
###### What version of Jekyll are you using (`jekyll -v`)?
None

###### What operating system are you using?
Ubuntu 14.04 LTS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
sudo gem install jekyll

###### What did you expect to see?
You tell me?

###### What did you see instead?
carlos@web01:/var/www/blog.icarlosmendez.info/public_html$ sudo gem install jekyllBuilding native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/1.9.1/gems/ffi-1.9.10/ext/ffi_c
/usr/bin/ruby1.9.1 -r ./siteconf20160225-18166-1pid4ok.rb extconf.rb
/usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from extconf.rb:4:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/1.9.1/extensions/x86_64-linux/1.9.1/ffi-1.9.10/gem_make.out

**Comment by envygeeks** [comment]
We do not support Ruby 1.9 install 2.0 which is available in the repos.
