### ISSUE TITLE
Set jekyllrb.com link in GitHub repo to HTTPS

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [jekyll/jekyll#4593]
@parkr @mojombo @benbalter 

----

Please set the *`http://jekyllrb.com`* link to **`https://jekyllrb.com`**:

![fireshot screen capture 037 - jekyll_jekyll_ jekyll is a blog-aware static site generator in ruby - github_com_jekyll_jekyll by Suriyaa Kudo](https://cloud.githubusercontent.com/assets/5073946/13358867/a7efffa2-dcb1-11e5-874b-038c5a25f3b4.png)

Thanks.

*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by envygeeks** [comment]
Fixed.

**Comment by SuriyaaKudoIsc** [comment]
:+1:
