### ISSUE TITLE
jekyll doctor should accept --config flag

### ISSUE THREAD

**Issue by joakimkemeny** [jekyll/jekyll#4598]
###### What version of Jekyll are you using (`jekyll -v`)?
3.1.2

###### What operating system are you using?
OS X 10.11.3

###### What did you do?
I create a new project using `jekyll new .` then I run `jekyll doctor --config _config.yml` (I obviously want to move and rename the config file, but this simple case illustrates the problem)

###### What did you expect to see?
Configuration file: /Users/Joakim/Project/_config.yml
  Your test results are in. Everything looks fine.

###### What did you see instead?
jekyll 3.1.2 | Error:  Whoops, we can't understand your command.
jekyll 3.1.2 | Error:  invalid option: --config
jekyll 3.1.2 | Error:  Run your command again with the --help switch to see available options.

**Comment by parkr** [comment]
@joakimkemeny Great catch! [The `--config` flag appears to be there](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/doctor.rb#L11), so there must be a bug here.

**Comment by joakimkemeny** [comment]
That was really fast. Thank you for your awesome work.

**Comment by daniellmb** [comment]
Same thing happens with the `--verbose` flag

**Comment by DirtyF** [comment]
@daniellmb `--verbose` mode is only an option for the `serve` command

**Comment by mvaneijgen** [comment]
I also run in to this problem and I am running jekyll 3.1.6. How do I fix this?
