### ISSUE TITLE
Jekyll include tag not rendering on Github

### ISSUE THREAD

**Issue by motatoes** [jekyll/jekyll#4600]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.0

###### What operating system are you using?

Ubuntu 14.0.4 on vagrant

###### What did you do?

I have an include tag in one of my files that runs fine on localhost but is not rendering on Github

###### What did you expect to see?

I expected to see the page rendered correctly on Github as I do on localhost:

![](http://i.imgur.com/E1iTmXj.png)

###### What did you see instead?

After uploading on [Github](https://github.com/ImportantCool/gogonzo/blob/gh-pages/stories/1/embed_list.html) I see the following

![](http://i.imgur.com/FRthXbV.png)

**Comment by envygeeks** [comment]
Please provide us with some source if you can please!

**Comment by motatoes** [comment]
Hi @envygeeks 

I've managed to fix it now. [This is the repo that had the issue](https://github.com/importantcool/gogonzo/tree/gh-pages), I managed to fix it by replacing `{{ page.content}}` with `{{ content }}` in my [layout file](https://github.com/ImportantCool/gogonzo/commit/632fedcc610c8b664e74a22f7a284122da4ec064), and after I did cthat the page is rendered correctly on github!

I'm not sure why this change has fixed it after pushing (not sure I know what the difference is)! 

Feel free to close this thread!

**Comment by budparr** [comment]
> I have an include tag in one of my files that runs fine on localhost but is not rendering on Github

FYI @motatoes Github Pages is [not running 3.1](https://pages.github.com/versions/). You can avoid having a different version locally by using bundler with a Gemfile that pulls in ```gem 'github-pages'```, which give you the same version Jekyll as well as the other dependencies

**Comment by motatoes** [comment]
Thanks for the tip @budparr !

**Comment by parkr** [comment]
> replacing `{{ page.content}}` with `{{ content }}` in my layout file,

Yes, this is the problem. Well done! `content` is always used in `layout` files, so you should see that consistently across all the examples you encounter. It's also [documented on the Variables page](https://jekyllrb.com/docs/variables/#global-variables). Cheers!
