### ISSUE TITLE
FAQ website link doesn't exist in Jekyll Talk

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [jekyll/jekyll#4605]
@parkr @envygeeks @mattr- 

----

> ***The [FAQ website link](https://jekyllrb.com/faq) in [Jekyll Talk about site](https://talk.jekyllrb.com/about) doesn't exist!***

Website Screenshot:
![fireshot screen capture 038 - about - jekyll talk - talk_jekyllrb_com_about](https://cloud.githubusercontent.com/assets/5073946/13378946/608d6be2-de17-11e5-8c15-028809b36d8d.png)

Response of FAQ website:
![fireshot screen capture 039 - page not found github pages - jekyllrb_com_faq taken by Suriyaa Kudo](https://cloud.githubusercontent.com/assets/5073946/13378941/31f57a22-de17-11e5-932a-7fbc66f239a1.png)

----

*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by parkr** [comment]
I don't know how to get rid of those links, but I don't want them. @envygeeks, is it possible to remove these? This is the fourth or fifth time we've been asked about these links and they 404 either on GitHub or on Jekyll Talk. :/

**Comment by envygeeks** [comment]
There is no way to rid of them as far as I'm aware, the theme will have to be manually adjusted.

**Comment by SuriyaaKudoIsc** [comment]
:+1:

**Comment by SuriyaaKudoIsc** [comment]
@envygeeks Which software do you use for Jekyll Talk?

**Comment by parkr** [comment]
@SuriyaaKudoIsc We use [Discourse](http://discourse.org).

**Comment by SuriyaaKudoIsc** [comment]
@parkr @envygeeks Do you host it or run it yourself?

**Comment by parkr** [comment]
@envygeeks hosts it at the moment using his infrastructure and Docker. :smile:

**Comment by SuriyaaKudoIsc** [comment]
@parkr @envygeeks Did you solved the problem?

**Comment by envygeeks** [comment]
I'll be honest that I do not plan to. Altering the theme would complicate our updates and make the life cycle harder to manage.

**Comment by envygeeks** [comment]
I'll work with @parkr and come up with a better solution

**Comment by SuriyaaKudoIsc** [comment]
:+1:

**Comment by parkr** [comment]
I updated it to point to jekyllrb.com/help/ . We don't have an FAQ as all of jekyllrb.com is kind of an FAQ :smile:

**Comment by envygeeks** [comment]
Works for me!

**Comment by SuriyaaKudoIsc** [comment]
:+1:
