### ISSUE TITLE
Why CSS file cannot load?

### ISSUE THREAD

**Issue by OneNewLife** [jekyll/jekyll#4608]
###### What version of Jekyll are you using (`jekyll -v`)?

3.03

###### What operating system are you using?
win10 professional 64bit 10586

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I just make a CNAME file written in my domain,change the baseUrl into "\" and parse the DNS,but when I open my domain,the documents can load,but the css file cannot load,and I found the url of the css file is not true.

###### What did you expect to see?

I wanna see a blog with style

###### What did you see instead?

It's just an alphabet without color.

**Comment by parkr** [comment]
@OneNewLife You have complete control over your `link` tags. Search `<link` in your project and you will find where you can change it. If your project has a custom domain, then it should build to the root of that domain, and no `baseurl` should be needed. Make sure it's a forward slash, though (i.e. `baseurl: "/"`).

Hope this helps!
