### ISSUE TITLE
Missing theme directory when generate HTML on Github Pages

### ISSUE THREAD

**Issue by hugo53** [jekyll/jekyll#4609]
###### What version of Jekyll are you using (`jekyll -v`)?
3.1.2

###### What operating system are you using?
Mac OSX 10.11

###### What did you do?
Now when I create a new post and publish to Github Pages, HTML file will be generated with a wrong link to theme files. For example, in the below images, those links should be ```/assets/themes/twitter/css/style.css?body=1``` and ```/assets/themes/twitter/bootstrap/css/bootstrap.2.2.2.min.css```

![screen shot 2016-03-01 at 12 07 23 am](https://cloud.githubusercontent.com/assets/1033299/13402683/ff165800-df43-11e5-8d77-a6212bf22901.png)

Anyone has this problem before, and how to fix it? Thank you in advance!

**Comment by geraldb** [comment]
If I dare to say that's not really a bug with Jekyll - more a usage question about your setup for the [Jekyll talk forum](https://talk.jekyllrb.com). 

Also are you using Jekyll Bootrap (JB) - if yes - as far as I can tell it is no longer maintained and is broken with the latest Jekyll 3.x update. You might report the bug to the Jekyll Bootstrap project. Cheers:

**Comment by DirtyF** [comment]
@hugo53 seems to be in order now : http://blog.hoangnm.com/

**Comment by parkr** [comment]
Thanks for your help, @DirtyF!

**Comment by hugo53** [comment]
@DirtyF Yes, I just did a trick when set ASSET_PATH : /assets/themes/twitter, but not sure that's a strong solution.
