### ISSUE TITLE
Triple backticks not working in v3.1.1. kramdown

### ISSUE THREAD

**Issue by herrniemand** [jekyll/jekyll#4613]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.1

###### What operating system are you using?
Kubuntu 15.10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I tried to highlight code with kramdows with triple backticks(```) and it does not work.
P.S. Google could not solve my problem 

###### What did you expect to see?
Highlighted code. 

###### What did you see instead?
String of code and sadness in the mirror.

**Comment by geraldb** [comment]
See the [Jekyll F.A.Q.](https://github.com/planetjekyll/quickrefs/blob/master/FAQ.md) entries on code blocks and syntax highlighting. Cheers.

**Comment by herrniemand** [comment]
@geraldb tried. Not working for me. The only thing kramdown does is wraps `<code class="highlighter-rouge"><code>` around the code.

**Comment by herrniemand** [comment]
@geraldb 
![kramdown_p_1](https://cloud.githubusercontent.com/assets/1636116/13416578/cc7024fa-dfc8-11e5-9567-01a431298d94.png)
![kramdown_p_2](https://cloud.githubusercontent.com/assets/1636116/13416579/ccb6353a-dfc8-11e5-8f78-522ad82ad8a5.png)
![kramdown_p_3](https://cloud.githubusercontent.com/assets/1636116/13416580/ccde32b0-dfc8-11e5-9449-9dc639bcc795.png)
:disappointed: :cry: :cactus:

**Comment by geraldb** [comment]
You need to post your markdown otherwise it's hard to tell. Make sure you have rouge install e.g. $ gem install rouge.

**Comment by herrniemand** [comment]
@geraldb rouge installed.

**Comment by herrniemand** [comment]
@geraldb 


```
---
layout: post
tags: basics
title: What is JSON?
---

\`\`\`json
{
    "company"   : "Tesla Motors",
    "brand"     : "Tesla",
    "model"     : "S",
    "type"      : "electric"
}
\`\`\`

Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt velit illo unde possimus placeat veniam ipsa enim, id excepturi, reiciendis, libero incidunt perferendis voluptas officia quia expedita, quas itaque eius.
```

**Comment by geraldb** [comment]
Here is a [working example](https://github.com/planetjekyll/sandbox-syntax-highlighter/blob/gh-pages/code.md) with your json example. Good luck. Cheers.

**Comment by parkr** [comment]
I got it working, too: https://jekyll-sandbox.herokuapp.com/parkr/a1679892e4ee2ac4d765

**Comment by parkr** [comment]
Oh! I just re-read your title. Try upgrading to v3.1.2. :smile:

**Comment by herrniemand** [comment]
@parkr wow. That's worked. Had no idea that new version came out. XD

**Comment by herrniemand** [comment]
@geraldb @parkr Thanks guys! :beers:
