### ISSUE TITLE
Can't include files from _data folder

### ISSUE THREAD

**Issue by plumbe0** [jekyll/jekyll#4614]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.1.0

###### What operating system are you using?

debian testing

###### What did you do?

added this line to my ~~`_include.yml`~~ `_config.yml`:
`include: ["_data/myfile.json", "_data/myfile2.json", ".dummy"]`

###### What did you expect to see?

i expected those three files to be included in the build

###### What did you see instead?

jekyll includes only `.dummy` but ignores the files in the `_data` directory.
i also tried including only one file at a time but it doesn't work. i tried inlcuding `_data/` and that doesn't work either. including `_data` works, but i don't want the entire folder to be included.

**Comment by parkr** [comment]
Add those lines to `_config.yml`, not `_include.yml`. When you add them to your `_config.yml`, you don't see `_data/myfile.json` and `_data/myfile2.json` in your resulting site under `_site/_data/myfile.json` and `_site/_data/myfile2.json`?

**Comment by plumbe0** [comment]
I completely mistyped that: i actually added the include line in `_config.yml`. The `_data` folder is not created at all when the build happens (of course under `_site` directory).

**Comment by pathawks** [comment]
What is the use case for including the `_data` directory? Isn't this a little like asking for the `_layouts` directory to be copied to the generated site? What files should appear here? Should Jekyll run them through generators first?

**Comment by plumbe0** [comment]
I have a JSON file with data i use to generate a webpage, but now i need to also load this file with AJAX so i need it to be included in the build. It should not be processed, but maybe it should be copied in a different folder like "assets" or something else instead of "_data".

**Comment by parkr** [comment]
I believe this is acceptable as-is. You can't include anything in any directory which starts with a special character `.`, `_`, or `#`. That's mostly by design. In terms of `_data`, we offer a `data_source` configuration option which allows you to publish this data _and_ have it available for use in `site.data`. Use something like `data_source: data` (no underscore) and you'll see your data output properly in your site. Thanks!
