### ISSUE TITLE
Incorrect highlight on single fenced code

### ISSUE THREAD

**Issue by alexconst** [jekyll/jekyll#4627]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.0.3

github-pages versions
+---------------------------+---------+
| Gem                       | Version |
+---------------------------+---------+
| jekyll                    | 3.0.3   |
| jekyll-sass-converter     | 1.3.0   |
| jekyll-textile-converter  | 0.1.0   |
| kramdown                  | 1.9.0   |
| rdiscount                 | 2.1.8   |
| redcarpet                 | 3.3.3   |
| RedCloth                  | 4.2.9   |
| liquid                    | 3.0.6   |
| rouge                     | 1.10.1  |
| jemoji                    | 0.5.1   |
| jekyll-mentions           | 1.0.1   |
| jekyll-redirect-from      | 0.9.1   |
| jekyll-sitemap            | 0.10.0  |
| jekyll-feed               | 0.4.0   |
| jekyll-gist               | 1.4.0   |
| jekyll-paginate           | 1.1.0   |
| github-pages-health-check | 1.0.1   |
| jekyll-coffeescript       | 1.0.1   |
| jekyll-seo-tag            | 1.3.1   |
+---------------------------+---------+

###### What operating system are you using?

Ubuntu 15.10

###### What did you do?

Content:
~~~markdown
User variables can only be declared in the variables section and its syntax is as shown in the first two lines. The first case is obvious. And in the second one the `ssh_user` variable value is set according to the shell environment variable `PACKER_SSH_USER`.
The third line shows how to use a previously declared variable.
And the last line shows the use of configuration template variables, which are in the form `{{ Varname }}` or `{{ .Varname }}`, and are special variables filled by Packer automatically. In this case the `{{ .HTTPIP }}` and `{{ .HTTPPort }}` will be set by Packer with the information about its own local web server and then supplied to the guest OS during the installation process.
~~~

Settings:
```
markdown: kramdown
kramdown:
    input: GFM 
    hard_wrap: false
    toc_levels: 1..6
    syntax_highlighter: rouge
```

###### What did you expect to see?

![alt text](https://i.imgur.com/VwAztfi.png)

###### What did you see instead?

![alt text](https://i.imgur.com/ur8JeLs.png "")

**Comment by parkr** [comment]
@alexconst What's the HTML there?

**Comment by briennakh** [comment]
I'm seeing the same thing. 

Version: Jekyll 3.0.3 (github-pages gem)
OS: OS X Yosemite

Configs: 
```ruby
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
```

**I expect to see inline code like this:**
Hello, my name is `{{ name }}`
`{'carbs': 669.5875, 'protein': 85.5, 'fat': 38.6375}`
`{{{{{{{{{{{}}}}}}}}}}}}}}}}`

**But it looks like this:**
![screen shot 2016-03-19 at 10 49 17 pm](https://cloud.githubusercontent.com/assets/9706870/13902599/e0ea621e-ee24-11e5-8aa3-7f0d75ef0c6a.png)

There shouldn't be any red highlighting; the text should be all white. 

The inline code is contained within raw Liquid tags. 

The following HTML output indicates that once a curly bracket is encountered, following text gets highlighted with a `<span class="err">` element:
![screen shot 2016-03-19 at 10 54 49 pm](https://cloud.githubusercontent.com/assets/9706870/13902620/b53bb1a8-ee25-11e5-96f6-cdb7df58b2cf.png)

**Comment by alexconst** [comment]
@parkr 

This happens when using `inline_theme: monokai`
But even when not specifying any `inline_theme` there is this "highlight weirdness", as mentioned by @briennakh,  that didn't happen before.

The html for one of the `{{ Varname }}` text:
(if you're wondering I have changed the colors, so the hex codes won't match the previously posted image)
```html
<code class="highlighter-rouge">
    <span style="color: #f8f8f2;background-color: #49483e">{</span>
    <span style="color: #960050;background-color: #1e0010">{</span>
    <span style="color: #f8f8f2"> </span>
    <span style="color: #960050;background-color: #1e0010">Varname</span>
    <span style="color: #f8f8f2"> </span>
    <span style="color: #f8f8f2;background-color: #49483e">}</span>
    <span style="color: #960050;background-color: #1e0010">}</span>
</code>
```

**Comment by parkr** [comment]
@alexconst How do you output them? I would surround them in single backticks and `{% raw %}`

> `{% raw %}{{ Varname }}{% endraw %}`

**Comment by alexconst** [comment]
@parkr 
Yes that is what I'm doing as well.

I also just tried moving the backticks from outer (surround the "raw" tags) to inner (only {{Varname}}) but that makes no difference.
Note that this issue (only?) happens with the monokai theme, which I'm not using. I'm using the default theme now.

**Comment by parkr** [comment]
@alexconst This must be a problem then with how kramdown works with its syntax highlighter. Would you mind filing this [on that repo](https://github.com/gettalong/kramdown/)? Thanks!

To disable, do:

```yaml
kramdown:
  syntax_highlighter_opts:
    disable: true
```
