### ISSUE TITLE
Page filename affecting liquid parsing in page.content loop

### ISSUE THREAD

**Issue by jsnmrs** [jekyll/jekyll#4638]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.2 (also tested with github-pages 53)

###### What operating system are you using?
OS X 10.11.3

###### What did you do?

In an attempt to create an aggregate view of several pages, I'm looping through pages and displaying their content:

```
{% assign allpages = site.pages %}
{% for page in allpages %}
    {{ page.content }}
{% endfor %}
```

###### What did you expect to see?

I expected the liquid tags on each page to be parsed when calling {{ page.content }} in a loop

###### What did you see instead?

Pages whose filename begins with digits (ex: 01-test.html) **will parse** liquid tags within this loop.

Pages whose filename does not begin with digits (including index.html) **will not parse** liquid tags inside that loop.

Example page: [http://jasonmorris.com/jekyll-demo/loop/](http://jasonmorris.com/jekyll-demo/loop/)
Example repo: [https://github.com/jsnmrs/jekyll-demo](https://github.com/jsnmrs/jekyll-demo)

In previous versions of Jekyll, index.html pages seemed to process liquid tags within this loop, but that no longer seems to be the case in Jekyll 3.1.2 (and GitHub Pages 53).

**Comment by Crunch09** [comment]
I think this is not restricted to whether your filename starts with a digit or not. It seems that the parsing works fine until it reaches the file where the loop is defined itself ( in your case `index.html` ).
You can check this behavior if you rename your `index.html` page to something like `zindex.html` or by renaming the filenames of the two pages which are not parsed to something which comes before `index.html` like `indew.html` or `foo.html`.

My guess is that this is a desired behavior by jekyll / liquid to prevent endless loops ( although you check this in an if-condition yourself ).

**Comment by parkr** [comment]
Unfortunately this is by design based on our rendering process. If this changes, it will be due to a completed incremental regenerator which can build a dependency tree and resolve in order. If you want to include content, please put your contents in a collection. Thanks!
