### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by arron-jeffery** [jekyll/jekyll#4642]
###### What version of Jekyll are you using (`jekyll -v`)?
`jekyll 3.0.1`

###### What operating system are you using?
`OS X El Capitan`

###### What did you do?
Having the following snippet in an markdown file:—
`[email me here](mailto:foo@bar.com?subject=I’d like to contribute to x…)`
…does not work, whereas…
`[email me here](mailto:foo@bar.com?subject=I'd like to contribute to x...)`
…works correctly. Note the ellipsis and smart-quotes.

###### What did you expect to see?
The _config.yml specifies UTF-8, therefore I expected Jekyll to generate successfully.
```
markdown: kramdown
encoding: utf-8
```

###### What did you see instead?
`Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_collection/collection-item.md': invalid byte sequence in UTF-8`

**Comment by parkr** [comment]
Did you try `encoding: utf8` (no hyphen)?

**Comment by arron-jeffery** [comment]
Removing the hyphen (from `utf-8` to `utf8`) results in `jekyll-3.0.1/lib/jekyll/document.rb:292: warning: Unsupported encoding utf8 ignored`. Note that `utf-8` is also the default encoding for newer versions of Jekyll, therefore I don't think it is an issue with this specific setting in _config.yml.

Thanks! 🙂

**Comment by envygeeks** [comment]
It is that we don't enforce an encoding on strings before passing them around.

**Comment by lyy1994** [comment]
I have encounter the same problem in Windows 7, 32 bit, jekyll 3.1.2, while I'm trying to present a new Chinese post. I have convert my post's encoding to UTF-8 without BOM, and yet it still have the same problem.

**Comment by parkr** [comment]
@lyy1994 Create a new file with the UTF-8 (no BOM) encoding and copy over the content. I have had issues where the non-UTF-8 characters are hidden in my editor(s) so I can't correct it.

**Comment by lyy1994** [comment]
@parkr Sorry for the delay! I used to try your method, but it didn't work. Now I think this issue may come from the incorrect encoding of file names, because there are some Chinese characters within my file name before. Since I converted my file name into English, this problem disappeared.

**Comment by parkr** [comment]
@lyy1994 It sounds like a problem with Ruby in general. I am sorry it didn't work for you but glad it is now functioning properly!
