### ISSUE TITLE
Proposal: Jekyll Affinity Groups

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#4643]
I'd like to propose that we create a handful of small Jekyll [affinity groups](https://en.wikipedia.org/wiki/Affinity_group) to help encourage light-weight discussions and contributions around specific parts of the project.

The idea would be to create say, 4-5 informal groups around core Jekyll concepts, say:

* @jekyll/command-line (anything black background, white text)
* @jekyll/configuration (names, defaults, deprecation, etc.)
* @jekyll/build (reading + writing)
* @jekyll/ecosystem (plugins + themes)

Each team would be a GitHub team within the Jekyll org that wouldn't confer any special privileges. Any community member could freely join or leave any team as they'd like, and you could be a member of more than one team.

As issues come in and get triaged, a maintainer would cc the relevant team(s), brining additional voices into the discussion. Think of it kind of like following a hashtag for a subset of the project.

For the foreseeable future, these would likely remain informal interest groups, but over time, those teams could become experts in different parts of the project, can make decisions and drive development, etc., like many other larger open source projects.

Thoughts? Since they're just GitHub teams, we could theoretically give it a try for a few weeks, and if we don't like it, it's simple enough to delete the team. Just trying to think of ways we can encourage more involvement, short of "submit a pull request".

**Comment by benbalter** [comment]
Also to note, as a thought experiment, I made a tiny Sinatra app [Squad goals](https://github.com/benbalter/squad_goals), that could facilitate allowing community members to freely join/leave teams without maintainer intervention.

**Comment by envygeeks** [comment]
I think a few of those are too high-level and can be merged, take for example configuration I would simply put that as compat that way discussions surface around whether that change is worth it... I also think there need be another group that deals with performance (one of the things I do), websites, and readability (because lets admit it, in some places our code is confusing.)

Groups should focus on an area they can improve.  If a person has questions about whether or not their code is slower or faster they CC performance, if they have questions about whether or not their code could be confusing they CC readability.

**Comment by envygeeks** [comment]
I like the idea though, this is exactly what happens with Ubuntu on launchpad in some areas.

**Comment by benbalter** [comment]
> Groups should focus on an area they can improve. If a person has questions about whether or not their code is slower or faster they CC performance, if they have questions about whether or not their code could be confusing they CC readability.

I like that idea. Kind of an "ask an expert" approach to it as well.

**Comment by parkr** [comment]
@benbalter We talked in :meat_on_bone: :space_invader:, but a revised list of teams:

- @jekyll/command-line (anything black background, white text, particularly UX issues)
- @jekyll/configuration (names, defaults, deprecation, etc.)
- @jekyll/build (reading, rendering, writing; incremental regen; old core)
- @jekyll/ecosystem (plugins + themes)
- @jekyll/performance (speed :dash:)
- @jekyll/documentation (writing, reviewing documentation)

What do you think? @envygeeks and @jekyll/core, too!

**Comment by envygeeks** [comment]
I like it!

**Comment by mattr-** [comment]
:+1:

**Comment by parkr** [comment]
@jekyll/core – Should we collapse any of them? command-line seems kinda amorphous, and configuration seems like it could maybe be a part of build? What do you think?

**Comment by envygeeks** [comment]
@parkr I think configuration should be under compat and handle generic concerns involving old versions, new versions and the merit of changes, as for CLI, I have no opinion on that.

**Comment by mattr-** [comment]
if i was going to change anything, i'd fold performance into build. i see build being the main place for performance improvements/bottlenecks and feel like it would be that groups focus to help push that along.

**Comment by parkr** [comment]
> i'd fold performance into build

Maybe we should rename build. Yes a lot of perf work will happen here, but i'm thinking build will be mostly for bugs/features/enhancements to the build process. I also anticipate perf-related folks not being interested in, e.g., bugs in a filter. So perf is a good way to targeting folks who only care about performance. Given the specialty and the kind of people i imagine would want to be in that team, I'd leave 'em split up. 

> I think configuration should be under compat and handle generic concerns involving old versions, new versions and the merit of changes

@envygeeks maybe @jekyll/stability?

**Comment by envygeeks** [comment]
I like @jekyll/stability, it makes much more sense and is on aim for what it's mean to do.

**Comment by parkr** [comment]
Great! Just created:

- @jekyll/stability – Concerned with all things stability, including configuration, defaults, deprecation, etc.
- @jekyll/build – Concerned with the Jekyll build pipeline, from reading files, rendering them, and writing them. Includes incremental regeneration.
- @jekyll/ecosystem – Concerned with the fostering of a vibrant ecosystem. Plugins, themes, etc.
- @jekyll/performance – Concerned with Jekyll's team.
- @jekyll/documentation – Concerned with making jekyllrb.com and other Jekyll documentation great (again).

Hooray! Thanks for the idea, @benbalter. Let me know if you have further ideas of how to organize these. :heart:

**Comment by parkr** [comment]
Boom! Folks can sign up on https://teams.jekyllrb.com. @benbalter, want to do a blog post tomorrow on jekyllrb.com for this, since it was your baby?
