### ISSUE TITLE
Liquid Snippets in posts

### ISSUE THREAD

**Issue by robbyklein** [jekyll/jekyll#4650]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.2

###### What operating system are you using?
OSX el capitan

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Trying to include liquid code snippets in a post. For example:

```liquid
{{ page.title }}
```

###### What did you expect to see?
My code bits highlighted

###### What did you see instead?
The liquid evaluated

**Comment by pathawks** [comment]
You need to wrap the Liquid code you would like to display inside `{% raw %}{% endraw %}` tags to prevent Liquid from trying to parse it and output it directly.

**Comment by robbyklein** [comment]
Thanks, will give this a try.

**Comment by parkr** [comment]
What @pathawks suggested should fix things up for ya. :smile: We've seen this before and that's the confirmed fix.
