### ISSUE TITLE
code blocks using ``` syntax not highlighted when in lists

### ISSUE THREAD

**Issue by Treri** [jekyll/jekyll#4651]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.0.3 (github pages used version)

###### What operating system are you using?
OS X 10.11.3

###### What did you do?
use below content
```
1. list1
2. list2

    ```js
    var a = function(){}
    ````
```

###### What did you expect to see?
code blocks are highlighted correctly


###### What did you see instead?
code blocks are not detected and highlighted. just output 

```
<p>```js
var a = function(){}
```</p>
```

If I delete leading 4 space, it is highlighted correctly, but the code block will not be in the list item level anymore

**Comment by envygeeks** [comment]
Unfortunately there is nothing we can do about this, as this is a problem with your markdown processor and might not be supported at all by it because it might adhere to the spec (of which I do not think allows this anyways.)

**Comment by Treri** [comment]
OK, I reported at upstream jneen/rouge#425

**Comment by envygeeks** [comment]
@Treri it probably belongs on RedCarpet, or Kramdown.

**Comment by Treri** [comment]
Oh, I missed that. Thank you!

**Comment by geraldb** [comment]
@Treri   FYI:  It's not a bug. If you use kramdown you have to "fix" your source e.g. ident the code block the same as the first non-list marker. See the [Jekyll F.A.Q ](https://github.com/planetjekyll/quickrefs/blob/master/FAQ.md) entry titled "How can I get backtick fenced code blocks working inside lists (with kramdown)?".Cheers.

**Comment by Treri** [comment]
Some weird, but works. Thanks
