### ISSUE TITLE
Multiple Sorting

### ISSUE THREAD

**Issue by nil** [jekyll/jekyll#4656]
I was trying to sort a collection by two variables. I mean, I have these code:
```
// john-doe.md
---
name: "John Doe"
gender: "Male"
age: "24"
order: 3
---

// index.html
{% assign people = site.people | sort: "gender", "order" %}
{% for person in people %}
  <li>
    <h2 class="name">{{ person.name }}</h2>
    <ul>
      <li class="gender">{{ person.gender }}</li>
      <li class="age">{{ person.age }}</li>
    </ul>
  </li>
{% endfor %}
```
I wanted to group all the people first by gender, and then by order. Could you please find a solution for me?

**Comment by budparr** [comment]
You'll get better responses at https://talk.jekyllrb.com because this repo is for reporting bugs. 

Seems at first glance this should work for you. The group_by filter may be an option.

**Comment by nil** [comment]
@budparr Thanks for the advise.

**Comment by parkr** [comment]
Please use Jekyll Talk as @budparr mentioned. Thanks!
