### ISSUE TITLE
doesnt work like cereal box sez

### ISSUE THREAD

**Issue by JazzMaster** [jekyll/jekyll#4661]
###### What version of Jekyll are you using (`jekyll -v`)?
latest(wont report info)

###### What operating system are you using?
debian jessie(8)

tried to follow directions on "simple" instructions for jekyll, mr.hyde...and I get this instead:

/var/lib/gems/2.1.0/gems/jekyll-3.1.2/bin/jekyll:9:in `<top (required)>': undefined method `require_from_bundler' for Jekyll::PluginManager:Class (NoMethodError)
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

--cannot create NEW site.

**Comment by envygeeks** [comment]
Please provide full reproduction information including where you got Ruby from, how you installed Ruby, how you installed Jekyll (where you got it from) and what you were doing.

**Comment by parkr** [comment]
Once you have provided the data, we will open again. This looks at first glance like rubygems activated the wrong Jekyll when using `/usr/local/bin/jekyll`. Cannot reproduce on `master`.
