### ISSUE TITLE
my old pages are all 404

### ISSUE THREAD

**Issue by hongbing** [jekyll/jekyll#4664]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.1.2

###### What operating system are you using?

Mac OS X 10.11

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I just push some changes to github, changes are just modify my css file, and then I  received a email that told me 'pygments' highlighter is not support, I should use "rouge". So I set "rouge" as a highlighter, then I push it into my github.

###### What did you expect to see?

I can see the blog normally show up.

###### What did you see instead?

When I click the blog link,it show me 404.

I use "jekyll serve" command on my mac book, it's ok and I can see the blog link like this:

> localost:40000/posts/blog/15/11/14/monitor-principle.html

but I visit my web site, it shows the blog link like this:
>http://hongbing.github.io/posts/blog/2015-11-14-monitor-principle.html

and the page is 404,and all my pages in web site are 404

what did I do wrong?

**Comment by parkr** [comment]
@hongbing Try setting your permalink differently:

```diff
diff --git a/_config.yml b/_config.yml
index 6eae627..2b38e99 100644
--- a/_config.yml
+++ b/_config.yml
@@ -4,7 +4,10 @@ destination: ./_site
 plugins_dir:     ./_plugins
 layouts_dir:     ./_layouts
 data_dir: ./_data
-collections: null
+collections:
+  posts:
+    output: true
+    permalink: /posts/blog/:short_year/:month/:day/:title:output_ext
 
 # Handling Reading
 safe:         false
@@ -45,8 +48,6 @@ relative_permalinks: false
 
 # Outputting
 paginate: 5
-#permalink: /:year-:month-:day-:title
-permalink: date
 paginate_path: /page:num
 timezone:      null
 ```

This worked for me. :smile:

**Comment by envygeeks** [comment]
Hi, Hulk here.

I think a mistake was made.  It seems you set a ticket as a "bug" but there was no valid resolution in the repository.  Is this a mistake @parkr?

**Comment by hongbing** [comment]
hi, @parkr 
I change my _config.xml  like yours, 
now it's content  as below:

 ```
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data

collections:
  posts:
  output: true
  permalink: /posts/blog/:short_year/:month/:day/:title:output_ext

safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".gitignore"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

show_drafts: null
limit_posts: 0
future:      true
unpublished: false

whitelist: []
gems: [jekyll-paginate]

markdown: kramdown
highlighter: rouge 
lsi:         false
excerpt_separator: "<!-- more -->"

detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

github: hongbing

paginate: 5
paginate_path: /page:num
timezone:      null

disqus:
  shortname: 'hongbing.disqus.com'

quiet:    false
defaults: []

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
```

but when I push it, I got an email says 

> The page build failed with the following error:
Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.
GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:
 https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
If you have any questions you can contact us by replying to this email.


Then I remove the follows, it build success:
```
collections:
  posts:
  output: true
  permalink: /posts/blog/:short_year/:month/:day/:title:output_ext
```

but the 404 problem still there?

still on my mac book link is : 
> http://localhost:4000/posts/blog/2015/11/14/monitor-principle.html

web site : 
> http://hongbing.github.io/posts/blog/2015-11-14-monitor-principle.html

ps: this is my index.html
``` html
---
layout: home
---

<div class="index-content blog">
  <div class="section">
    <ul class="artical-list">
      {% for post in paginator.posts %}
      <li>
        <h2><a href="{{ post.url }}">{{ post.title }}</a></h2>
        <div class="title-desc">{{ post.excerpt | strip_html }}&hellip; <a href="{{ post.url }}" style="font-weight:bold;">Read More</a></div>
      </li>
      {% endfor %}

      <ul class="pager">
        {% if paginator.total_pages > 1 %}
            {% if paginator.previous_page %}
              <li class="lastpage"> <a href="{{ paginator.previous_page_path }}">上一页</a></li>
            {% else %}
              <li class="dislastpage"> 上一页</li>
            {% endif %}
              &nbsp;
            {% for page in (1..paginator.total_pages) %}
              {% if page == paginator.page %}
                <span class="active">{{ page }}</span>
                &nbsp;
              {% elsif page == 1 %}
                <a href="{{ '/index.html' | prepend: site.baseurl | replace: '//', '/' }}">{{ page }}</a>      &nbsp;
              {% else %}
                &nbsp;
                <a href="{{ site.paginate_path | prepend: site.baseurl | replace: '//', '/' | replace: ':num', page }}">{{ page }}</a>
                &nbsp;
              {% endif %}
            {% endfor %}
            &nbsp;
            {% if paginator.next_page %}
              <li class="nextpage"> <a href="{{ paginator.next_page_path }}">下一页</a></li>
            {% else %}
              <li class="disnextpage"> 下一页</li>
            {% endif %}
        {% endif %}
      </ul>
    </ul>
  </div>
</div>
```

**Comment by pathawks** [comment]
Notice the indentation in **@&zwnj;parkr**'s:

```yaml
collections:
  posts:
    output: true
    permalink: /posts/blog/:short_year/:month/:day/:title:output_ext
```

compared to yours:

```yaml
collections:
  posts:
  output: true
  permalink: /posts/blog/:short_year/:month/:day/:title:output_ext
```

**Comment by hongbing** [comment]
my mistake, thanks to point that @pathawks,
now  it works fine, all blog show up @parkr.
thanks.

**Comment by parkr** [comment]
@hongbing Glad it's all working!

Thanks as always @pathawks :smile:
