### ISSUE TITLE
`sample` filter doesn't work

### ISSUE THREAD

**Issue by henryhadlow** [jekyll/jekyll#4665]
###### What version of Jekyll are you using (`jekyll -v`)?

3.0.3

###### What operating system are you using?

OS X 10.11.1

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

`{{ site.pages | sample }}`

###### What did you expect to see?

Output of the content of a single page chosen at random into the template in question

###### What did you see instead?

Output of all the pages

I also tried:

```
{% assign counter = "1|2|3|4|5|6|7|8|9|10" | split: "|" %}

{{ counter | sample }}
{{ counter | sample }}
{{ counter | sample }}
{{ counter | sample }}
{{ counter | sample }}
{{ counter | sample }}
{{ counter | sample }}
{{ counter | sample }}
{{ counter | sample }}
{{ counter | sample }}
```

This outputs `12345678910 12345678910 12345678910 12345678910 12345678910 12345678910 12345678910 12345678910 12345678910 12345678910`

It should output ten individual random numbers.

**Comment by parkr** [comment]
The `sample` filter doesn't exist in Jekyll 3.0.3 so you won't be able to access it. Please upgrade to v3.1.0 or later! https://github.com/jekyll/jekyll/releases/tag/v3.1.0

**Comment by henryhadlow** [comment]
Thanks :) I want to stay vanilla Github Pages if possible... any idea when they're going to update?

**Comment by envygeeks** [comment]
@henryhadlow you'll probably see a pull request at https://github.com/github/pages-gem as soon as they're ready to update.  That's what they did with 3.0.
