### ISSUE TITLE
Sass Converter & (S)CSS Comments

### ISSUE THREAD

**Issue by andi1984** [jekyll/jekyll#4666]
###### What version of Jekyll are you using (`jekyll -v`)?
3.0.2

###### What operating system are you using?
Mac OSX 10.11

###### What did you do?
```Sass
​// *************************************
//
//   First Level
//   -> Description
//
// *************************************
$pickled_bluewood: #334D5C;
$keppel: #45B29D;
$ronchi: #EFC94C;
$red_damask: #E27A3F;
$valencia: #DF4949;
```

###### What did you expect to see?
A converted Sass to CSS file.

###### What did you see instead?

```bash
Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    Invalid CSS after "...uewood: #334D5C": expected "{", was ";" on line 7
```

**Comment by envygeeks** [comment]
Can you please refile this bug upstream at jekyll-sass-converter https://github.com/jekyll/jekyll-sass-converter.

**Comment by andi1984** [comment]
Sure, done.

https://github.com/jekyll/jekyll-sass-converter/issues/47
