### ISSUE TITLE
Jekyll should skip regeneration of same-file changes

### ISSUE THREAD

**Issue by cjaoude** [jekyll/jekyll#4679]
This is just a feature request/comment...

When you're editing the same file multiple times, it's frustrating to see Jekyll regenerating every single save. It should be clever enough to detect the same-file change and abort the queued changes and only regenerate the latest change.

**Comment by DirtyF** [comment]
Hi,

Have you tried the `--incremental` option available since version 3.x?  
There is ongoing work in order to further improve Jekyll's performance.

**Comment by cjaoude** [comment]
Hi, yes, -I flag and all. I'm just pointing out an idea.

**Comment by parkr** [comment]
Incremental regeneration should solve this problem. :smile: Keep an eye out for improvements! Thanks!
