### ISSUE TITLE
Liquid syntax error : Unknown tag 'endhighlight'

### ISSUE THREAD

**Issue by yangxikun** [jekyll/jekyll#4683]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.1.2

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I run `jekyll serve -H 0.0.0.0`,  but there was an error:
```
Liquid Exception: Liquid syntax error (line 61): Unknown tag 'endhighlight'
```
And my markdown post is:
```
{% highlight php linenos %}
function foo() {
    ……
    yield [$someValue];
    ……
}
{% endhighlight %}
```

Is pygments highlight syntax conflict with liquid?
How can I fix this error?
Any help is thanks!

**Comment by envygeeks** [comment]
Wrap your source (highlight contents) in `{% raw %}` because you have `{}` and this confuses Liquid.

**Comment by yangxikun** [comment]
Do you mean wrap highlight contents like that:
```
{% highlight php linenos %}
{%
function foo() {
    ……
    yield [$someValue];
    ……
}
%}
{% endhighlight %}
```
There was another error:
```
Liquid Exception: Liquid syntax error (line 9): Unknown tag 'function'
```

**Comment by EmilStenstrom** [comment]
Shouldn't highlight always handle its content as `{% raw %}`? I think this would make a lot of sense, and avoid people running into this problem with all languages that have braces...

**Comment by EmilStenstrom** [comment]
There's a feature request for tracking this here: https://github.com/jekyll/jekyll/issues/3855
