### ISSUE TITLE
Incorrect WEBrick settings for SSL

### ISSUE THREAD

**Issue by awood** [jekyll/jekyll#4689]
###### What version of Jekyll are you using (`jekyll -v`)?
Jekyll 3.1.1

###### What operating system are you using?
Fedora 23

###### What did you do?
jekyll server --ssl-cert test.crt --ssl-key test.key

###### What did you expect to see?
Jekyll serving over https

###### What did you see instead?
Server running... press ctrl-c to stop.
[2016-03-21 11:08:35] ERROR bad URI `�h�b�\x00\x00\x16�+�/�'.

Using openssl's s_client, you can see that the server is not even responding to the ClientHello message, so it's not "speaking" SSL/TLS at all.

The issue is in serve.rb's `enable_ssl` method.  WEBrick is being configured with ":EnableSSL" but the correct option is [:SSLEnable](http://docs.ruby-lang.org/en/2.2.0/WEBrick.html#module-WEBrick-label-HTTPS).

Also, there is an error in `server_address` where the protocol is hard-coded to http where it should instead take into account the presence of the ssl-cert and ssl-key options and use https if they are present.

**Comment by envygeeks** [comment]
Hulk: +flag +backport ++3.0.2 ++if-exists

**Comment by envygeeks** [comment]
There is a fix in the stream to fix this.

**Comment by envygeeks** [comment]
Hulk here,

This needs to be backported, it has been put into your backlog for 3.0.2. I'll merge for a manual commit.

**Comment by CRamsan** [comment]
I am experiencing what looks like the same issue. I am running Jekyll 3.1.2 in Ubuntu 14.04LTS  and I am trying to make Jekyll serve the certs I got from Let's Encrypt. Is there something I can do to mitigate the issue or all I can do is just wait for a new release?

**Comment by envygeeks** [comment]
@CRamsan you can use Nginx because Webrick is not production quality or if you must you can use master with bundler.

**Comment by envygeeks** [comment]
Actually @CRamsan you'll hve to use 3.1-stable branch looks like this was never picked into master so I'll have to do that sometime today or tomorrow when I have a minute.
