### ISSUE TITLE
Site layout is broken with 3.1.0, fine with 3.0.3

### ISSUE THREAD

**Issue by eepp** [jekyll/jekyll#4691]
I did not investigate the exact feature which does not work the same from 3.0.3 to 3.1.0, but my site's layout is broken suddenly. I'm only using the paginate plugin.

Can you think about anything that changed in a non-backward-compatible way from 3.0.3 to 3.1.0? Anything.

**Comment by parkr** [comment]
We are now using `Liquid::Drop`s instead of `Hash`es to serve data. I do know that `layout.datum` is not enforced everywhere in 3.1 and wasn't present in 3.0 for pages only (but it was present for posts & documents).

**Comment by eepp** [comment]
I think I found it.

Build this with Jekyll 3.1.2: <https://github.com/eepp/jekyll-layout-vars-bug>.

Look at the generated `index.html`: see how both layout variables are defined, while the source of this page only depends on the `default` layout which does not define them? It seems like the layout variables are not cleared from one page processing to the next (or something alike).

I hope this is not intended behaviour, because it's really weird.

Now build it with Jekyll 3.0.3 and see how layout variables are not defined this time.

My site has lots of layout variables affecting the output which are sometimes not defined, depending on the layout, so with this behaviour it's messed up baaaaad.

**Comment by parkr** [comment]
> It seems like the layout variables are not cleared from one page processing to the next

I think you're right. @ptoomey3 was seeing this a couple days ago on a site he was working on.

Would you please submit a patch to clear this value for each render?

**Comment by eepp** [comment]
@parkr I'm sorry to inform you that, as of this date, I don't know Ruby at all.

**Comment by parkr** [comment]
> @parkr I'm sorry to inform you that, as of this date, I don't know Ruby at all.

@eepp I didn't know Ruby when I first started contributing to Jekyll. I think a programmer of your stature would easily pick it up!

**Comment by eepp** [comment]
> @eepp I didn't know Ruby when I first started contributing to Jekyll. I think a programmer of your stature would easily pick it up!

I guess! It's on the TODO list somewhere, but since my full-time job does not require any Ruby skill, time is the limiting factor here...

**Comment by nasht00** [comment]
I think I have the same issue. I finally upgraded my Jekyll, and I see that the `layout` variable contains properties that should apply to a different page...

**Comment by eepp** [comment]
@nasht00 Yes. 3.0.3 will work too. Let's just hope somebody finds some time to fix what looks like a very trivial bug when you're familiar with the project's codebase (and language!).

**Comment by nasht00** [comment]
I've been improving my Ruby skills by writing Jekyll plugins internally, but I'm not familiar with the codebase. If someone from the team can point us to the right place, maybe we can try ...

**Comment by parkr** [comment]
I believe the offending issue is here: https://github.com/jekyll/jekyll/blob/94647af1f4a337a31b2174bc354d0a8b6b3eb716/lib/jekyll/renderer.rb#L143

**Comment by agriffis** [comment]
@parkr If I'm not mistaken, #4909 should fix this.

**Comment by parkr** [comment]
@agriffis indeed! Thanks. 😄
