### ISSUE TITLE
how to convert http to https?

### ISSUE THREAD

**Issue by xxlv** [jekyll/jekyll#4695]
hi ,i don't have a web server . and i just use github. and now , i want to convert my domain from http to https,  how to play it?

**Comment by parkr** [comment]
@xxlv GitHub Pages doesn't support HTTPS officially, though you can get a proper HTTPS connection for https://xxlv.github.io. `@konklone` explains it on his blog: https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

I'd recommend CloudFlare. [Here's a guide to help you](https://rck.ms/jekyll-github-pages-custom-domain-gandi-https-ssl-cloudflare/).
