### ISSUE TITLE
Jekyll not supplying page variable to a collection

### ISSUE THREAD

**Issue by drumanagh** [jekyll/jekyll#4696]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.0.3

###### What operating system are you using?

OS X 10.11.3

###### What did you do?

Using the master branch of the repo at https://github.com/pathminder/pathminder.github.io, run `jekyll build`.

###### What did you expect to see?

The `races` collection should supply pages to `/races/blues/`, `/races/dromites/`, etc.

###### What did you see instead?

Instead, it errors out:

`Liquid Exception: Liquid syntax error (line 6): Unknown tag 'page' in _layouts/race.html`
`jekyll 3.0.3 | Error:  Liquid syntax error (line 6): Unknown tag 'page'`

This seems pretty nonsensical... somehow it's not supplying a `page` variable to one or more of the items in the `race` collection, even though all the other other collections, which are identically configured, work fine.

I can't tell if I'm missing something obvious here, or if I've run into some reserved word or weird edge case in the collections handling.

**Comment by pathawks** [comment]
This is an error in your template, rather than an error in Jekyll.

```html
({% page.subtypes | sort | join: ', ' %})
```

`page` is an object, not a tag. It is accessed using `{{ page.subtypes }}` rather than `{% page.subtypes %}`

**Comment by drumanagh** [comment]
Dang! Somehow I completely missed that. Thank you.
