### ISSUE TITLE
Cannot run Jekyll locally with "No repo name found".

### ISSUE THREAD

**Issue by henrydf** [jekyll/jekyll#4705]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.0.3

###### What operating system are you using?
Mac OS X EI Captian

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Only run 'jekyll serve' after 'jekyll new . --force' in the top level of git repository.

**BUT, everything is ok on http://henrydf.github.io

###### What did you expect to see?
Success output, like below:
Configuration file: /Users/henry/henrydf.github.io/test/_config.yml
            Source: /Users/henry/henrydf.github.io/test
       Destination: /Users/henry/henrydf.github.io/test/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.413 seconds.
 Auto-regeneration: enabled for '/Users/henry/henrydf.github.io/test'
Configuration file: /Users/henry/henrydf.github.io/test/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.

###### What did you see instead?
Configuration file: /Users/henry/henrydf.github.io/_config.yml
            Source: /Users/henry/henrydf.github.io
       Destination: /Users/henry/henrydf.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    No repo name found.

**Comment by chrisfinazzo** [comment]
Looks like you might be in the wrong directory. Can you `cd` into `test` and build from there? As someone who ran into this a few times both when learning about Jekyll and also migrating sites, you might need to move your repo from `test` to the root directory in order for things to work.

**Comment by parkr** [comment]
@henrydf Add your repository name with organization to your `_config.yml`, like: `repository: henry/henrydf.github.io`.

We're working on fixing this up in https://github.com/jekyll/github-metadata/pull/45.

**Comment by corysimmons** [comment]
@parkr What if I don't want my jekyll blog to be a github repo? Any way to run this locally? Is git a requisite?

**Comment by parkr** [comment]
@corysimmons Of course, remove any mention of `jekyll-github-metadata` from your project, including `site.github.*` references in your site.

**Comment by corysimmons** [comment]
@parkr I don't have any references to github in my project.

I can start a fresh project `jekyll new foo`, run jekyll serve, and everything seems to work fine for a second, but if I make minor changes to a page (like `./about.html`) it err's.

To replicate:

- `jekyll new foo`
- `cd foo`
- `jekyll serve`
-

**Comment by cbaba20** [comment]
Hi team,
In my case I have found that there were two gemfile (files) in my project folder . so I deleted one of them and it works.

**Comment by cmdcolin** [comment]
What if jekyll-github-metadata is a sub dependency of the theme I'm using? If I remove the jekyll-github-metadata from gemfile.lock it says it is corrupt

**Comment by Supreme-Kai** [comment]
Hey. I'm actually having the same issue, but the file I'm working with is a forked repo and so I don't feel comfortable changing the cofig files. Is there any other way to get the project running locally? jekyll serve --watch was working perfectly fine for me just a week ago.

**Comment by DirtyF** [comment]
Please [use our forum](https://talk.jekyllrb.com) for questions regarding jekyll's usage.
