### ISSUE TITLE
Error: could not read file [filename]: unknown keyword:categories in jekyll > 3.0.1

### ISSUE THREAD

**Issue by rogerjohansson** [jekyll/jekyll#4707]
###### What version of Jekyll are you using (`jekyll -v`)?

3.0.1: works
3.0.3: broken
3.1.2: broken

###### What operating system are you using?

OS X 10.11.4

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Upgraded Jekyll from 3.0.1 (which worked fine) first to 3.1.2, then tried 3.0.3.

###### What did you expect to see?

Working build :-)

###### What did you see instead?

“Error: could not read file [filename]: : unknown keyword: categories” repeated for every file in my _posts directory.

After uninstalling the newer versions and going back to 3.0.1 the build works again.

**Comment by pathawks** [comment]
Sorry that what should have been a simple upgrade is causing you so much trouble.

Is your site’s source public?
What do your posts look like? Where does "categories" appear in your site source?
Are you using any plugins?

Can you please provide some way to reproduce this issue?

**Comment by rogerjohansson** [comment]
Nope, source isn’t public, sorry.

I have tried disabling all plugins, no difference.

Next I disabled all layouts but "blog-post.html" and "default.html" to contain nothing but {{ content }}. No difference.

The front matter of the files in _posts looks has this structure:

```
---
layout: blog-post
title: Post title
date: some date
category: CSS
tags:
- CSS
summary: 'A summary'
description: 'A description'
---
```

"categories" appears in a plugin for generating categories (https://github.com/recurser/jekyll-plugins/blob/master/generate_categories.rb). But disabling that plugin and the page layout that uses the categories didn’t help.

Since reverting to Jekyll 3.0.1 fixes the problem I’m thinking that something changed.

**Comment by rogerjohansson** [comment]
I tried installing jekyll 3.0.2 and the problem exists there as well. So this seems related to something that changed between 3.0.1 and 3.0.2. Maybe that helps narrowing it down?

**Comment by DirtyF** [comment]
@rogerjohansson the only change in the [3.0.2](//jekyllrb.com/news/2016/01/20/jekyll-3-0-2-released/) is a bugfix related to bad date format in YAML frontmatter, are you using the ISO date format ?

**Comment by pathawks** [comment]
Here is [a diff comparing 3.0.1 and 3.0.2](https://github.com/jekyll/jekyll/compare/v3.0.1...v3.0.2)

If you could provide even a minimal site that demonstrates this behavior, it would make tracking down the bug a *lot* easier.

**Comment by rogerjohansson** [comment]
I’ve done some testing and it *may* be related to YAML formatting. Will try to find time for a closer look tomorrow.

**Comment by rogerjohansson** [comment]
I made a super-minimal test site with only a _posts folder with a single file in (see attachment). No plugins, layout, configuration, front matter or anything, and I still get the error with any version above 3.0.1.

I have also tried changing the extension of the post file to .md in case .html could be a problem. No difference.

Also note that the site does build despite the “could not read file” errors, though it produces slightly different results than v 3.0.1 (not in this minimal test case, but on my “full” site) that show up in git after building.

Just in case it matters, the Ruby version I have is ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-darwin12.3.0] and gem is 2.0.3.

@DirtyF I use the ISO date format. Tried changing the date to something invalid and that generated an “Invalid date” error instead of the “could not read file” error.

[jekyll-test.zip](https://github.com/jekyll/jekyll/files/189152/jekyll-test.zip)

**Comment by DirtyF** [comment]
@rogerjohansson FYI your file works fine on a Jekyll 3.03 install on OS X, with ruby 2.1.7 installed with rbenv and brew.

**Comment by rogerjohansson** [comment]
@DirtyF I updated ruby to 2.3.0 and that seems to have fixed the problem. My site now builds fine with Jekyll 3.1.2, and about 4 times faster than before :-). Is the speed increase a result of upgrading Jekyll, Ruby, or both?

Thanks for helping out! Maybe it would be useful to note somewhere exactly which Ruby version Jekyll (or its dependencies) requires in case others run into this? The docs currently say v2 but apparently 2.0.0  doesn’t cut it.

**Comment by envygeeks** [comment]
Hulk: +debug ++2.0.0 ++jekyll.docker.envygeeks.io ++keywords ++lazy

**Comment by envygeeks** [comment]
Hulk Here,

I'll do what you requested when I'm not busy and not too lazy.  Probably some time this weekend.

**Comment by parkr** [comment]
@rogerjohansson Glad you got things working! Going to close this out.

I couldn't repro on my system with 2.0.0p648:

```text
~/Downloads/jekyll-test$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin15.4.0]
~/Downloads/jekyll-test$ rbenv exec jekyll --version
jekyll 3.0.3
~/Downloads/jekyll-test$ rbenv exec jekyll build
Configuration file: none
            Source: /Users/parkr/Downloads/jekyll-test
       Destination: /Users/parkr/Downloads/jekyll-test/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.041 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

I think it's OK to ask folks to upgrade from Ruby 2.0.0p0 to a later patch version. 😄
