### ISSUE TITLE
The highlight style is not being applied

### ISSUE THREAD

**Issue by chrisfinazzo** [jekyll/jekyll#4708]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.2

###### What operating system are you using?

Mac OS X 10.11.4

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

The code blocks which tell people how to run the test suite are not being highlighted properly. I'm not sure when the regression happened, but the fix should be similar to #4046.

###### What did you expect to see?

Inline code blocks w/ a highlight.

###### What did you see instead?

<img width="670" alt="screen shot 2016-03-24 at 9 54 47 pm" src="https://cloud.githubusercontent.com/assets/1534882/14036178/ae38338c-f20c-11e5-849d-0e016ada1782.png">

As this file is now in the `.github` directory and is generated automatically (see the note in `_docs/contributing.md`), is there anything special that I need to do in order to update this file?

**Comment by envygeeks** [comment]
Those use the `{% highlight %}` tag yeah?

**Comment by chrisfinazzo** [comment]
No. In [that][] case, I think it was eventually [suggested][] to use a class called "highlight" on a `figure` element to get things to wrap correctly and still be visually distinct. Now that I think about it, these aren't really inline anyway, I'll update that.

[that]: https://github.com/jekyll/jekyll/pull/4046
[suggested]: https://github.com/jekyll/jekyll/commit/4e017229412d108d3be16cc3cee0980a7bdafade

**Comment by parkr** [comment]
@chrisfinazzo It's not super high priority for us to have this highlighting I think – it doesn't seem to change the usability of the page. You're welcome to play around with the source from `.github/CONTRIBUTING.markdown` and submit a patch that adds this back.
