### ISSUE TITLE
Problem with jekyll 3.1.2 Installation on Rootserver with Centos 7 64 bit and PHP 5.6

### ISSUE THREAD

**Issue by AlexL777** [jekyll/jekyll#4709]
###### What version of Jekyll are you using (`jekyll -v`)?
I use Jekyll 3.1.2

###### What operating system are you using?

Rootserver on CentOS 7 64 bit, PHP 5.6

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Today I tried Jekyll to install and have running this command:

    gem install jekyll

But my blog frontend under http://projekte.alexl.eu/cms/jekyll/blog is not shown. It looks as if CSS is missing or something like that.

Then I in FTP account **owner/group** rights with **apache:apache**.

How can it be that it is so.

I have entered this command in the console.

    jekyll new blog

So the contents of the /blog was generated, but something does not seem to agree. Can you help me maybe. Thanks in advance.

###### What did you expect to see?

I have a blog frontend expected, or at least a demo page.

###### What did you see instead?

Instead, I see the frontend under **/cms/jekyll/blog** only the code and not a real frontend. How can it be so. Thanks in advance.

**Comment by DirtyF** [comment]
Seems like you didn't run `jekyll build`, it's the `_site` folder content that you must upload on your server.

Please ask usage question on https://talk.jekyllrb.com/, GitHub issues are for Jekyll bugs only.
Thanks, happy jekylling !

**Comment by envygeeks** [comment]
Hi @AlexL777,

I agree with @DirtyF this is a systems problem and should be asked at https://talk.jekyllrb.com because we don't manage your system we cannot do much to really help you without knowing more and that kind of scenario belongs on the forums because it's not a bug in Jekyll but more a less a design of the system you are using.
