### ISSUE TITLE
`jekyll build` exit code not reflecting errors

### ISSUE THREAD

**Issue by felicianotech** [jekyll/jekyll#4713]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.2

###### What operating system are you using?

Ubuntu 12.04/Ubuntu 14.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

If you run `jekyll build`, sometimes you can get the error "Error: could not read file" when the file's Front Matter is not correct YAML.

###### What did you expect to see?

When this happens, I expect the 'exit code' returned by Jekyll to be something other than 0.

###### What did you see instead?

Exit code '0'.

###### Why this matters?
When running `jekyll build` as a step on my CI environment, when this error occurs the command just returns 0. This makes my CI assume everything went well and continues. By returning a non-zero exit code, this signifies that something went wrong (aka an error) and stops everything.

**Comment by parkr** [comment]
This will come with #4674. We are picking and choosing which errors to raise a stink about and which errors not to raise a stink about. We will likely move toward more errors rather than fewer errors so that we can utilize system indicators like status codes better.

All in due time. 🔜
