### ISSUE TITLE
Failing spec on JRuby in Utils#safe_glob.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4718]
https://travis-ci.org/jekyll/jekyll/jobs/118904870#L497

**Comment by henrybraun125** [comment]
Hello, Can you write more detail ?

**Comment by parkr** [comment]
@henrybraun125 The test is right above the link in the issue body:

```
Failure:
TestUtils#test_: The `Utils.safe_glob` method should not apply pattern to the dir.  [/home/travis/build/jekyll/jekyll/test/test_utils.rb:235]
Minitest::Assertion: --- expected
+++ actual
@@ -1 +1 @@
-[]
+["test/safe_glob_test[/find_me.txt"]
```

Feel free to try to correct it on JRuby and submit a PR!

**Comment by parkr** [comment]
Apparently https://github.com/jekyll/jekyll/pull/5015/commits/6f3c01ca8772434f8e205bd7c06c0750233cec92#diff-2fdf881a7b3104bb9a0be6421efdd593R323 isn't a thing in jruby-land.
