### ISSUE TITLE
Install error: jekyll requires Ruby version >= 2.0.0 even though Ruby V2.2 installed 

### ISSUE THREAD

**Issue by glynhudson** [jekyll/jekyll#4724]
###### What version of Jekyll are you using (`jekyll -v`)?

Jekyll first time install fails even though Ruby V2.2.1 is installed: 
 
$ sudo gem install jekyll

ERROR:  Error installing jekyll:
        jekyll requires Ruby version >= 2.0.0.

$ ruby -v 
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

###### What operating system are you using?

Ubuntu 14.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

###### What did you see instead?

s

**Comment by envygeeks** [comment]
Run the following commands and give me the output please:

```
dpkg --get-selections | grep -i ruby
ll /usr/{,local/}bin | grep -E 'gem|ruby'
```

**Comment by glynhudson** [comment]
```
dpkg --get-selections | grep -i ruby
libruby1.9.1                                    install
ruby                                            install
ruby-dev                                        install
ruby1.9.1                                       install
ruby1.9.1-dev                                   install
```

I updated to Ruby 2 using `curl -sSL https://get.rvm.io | bash -s stable --ruby`. This seems to have worked since `$ ruby -v ` returns 2.2.1. Sorry, what am I missing.

**Comment by glynhudson** [comment]
Ah got it. Turns out I had two version of ruby installed:
```
sudo ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

I was trying to instal Jekyll with `sudo gem install jekyll` if I just installed to my default users (no root) with `gem instal jekyll` install went fine :-)

Thanks for your help :+1:

**Comment by envygeeks** [comment]
@glynhudson You should be able to pull down Ruby2.0 on Ubuntu 14.04.  It does this weird thing with 1.9.1 because that was back in the days when Ruby Team did it wrong still so you'll have to select the alternative but at that point Ubuntu will have gem2.0 and ruby2.0 available for you.
