### ISSUE TITLE
htmlbars doesn't render properly

### ISSUE THREAD

**Issue by greyhwndz** [jekyll/jekyll#4726]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.0.1

###### What operating system are you using?
OSX 10.9.5

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
``` htmlbars
<div class="{{if hasError 'has-error'}} form-group">
    {{input type=type value=value size=size pattern=pattern name=name placeholder=placeholder disaled=disabled maxlength=maxlength tabindex=tabindex class=input-class}}
</div>
```

###### What did you expect to see?
I expected to see a properly highlighted htmlbars/handlebars code

###### What did you see instead?
 ``` handlebars

```

**Comment by envygeeks** [comment]
Please provide the compiled source so we can determine if this is an upstream issue. Thanks.

**Comment by pathawks** [comment]
Did you wrap the code in the liquid `{% raw %}` tag?

**Comment by greyhwndz** [comment]
http://emberwatch.com/recipes/user_interface_and_interaction/basic_form_validations_buggy.html

I am currently wrapping the codes in `{% html %}{% raw %}` pairs but we wanted the single-fenced one.

**Comment by parkr** [comment]
@greyhwndz Handlebars is not compatible with Liquid, which also uses `{{` and `}}`. You'll need to do something like:

```html
<div class="{% raw %}{{if hasError 'has-error'}}{% endraw %} form-group">
    {% raw %}{{input type=type value=value size=size pattern=pattern name=name placeholder=placeholder disaled=disabled maxlength=maxlength tabindex=tabindex class=input-class}}{% endraw %}
</div>
```

This is a reality of using Liquid. All posts, colleciton documents, and pages will have this problem. If you don't include any YAML front matter at the top of a page, it will be considered a static file and will not be passed through Liquid and therefore preserved.

**Comment by greyhwndz** [comment]
ok thanks
