### ISSUE TITLE
How to use JekyII

### ISSUE THREAD

**Issue by henrybraun125** [jekyll/jekyll#4728]
How to use JekyII

**Comment by nk8** [comment]
My apologies if the answer is obvious because i'm relatively new to the whole idea of contributing to community projects.. was this ticket opened with   the suggestion of writing up a brief section on how to use Jekyll?

If that's the case, I  agree it's a good idea.

**Comment by envygeeks** [comment]
Please see: https://jekyllrb.com/docs/quickstart/

**Comment by envygeeks** [comment]
If you have any further questions or comments that are not Jekyll bugs please ask your questions at https://talk.jekyllrb.com, which is where we hold all non-bug related discussions.

Thanks!
