### ISSUE TITLE
How to disable autogen id's

### ISSUE THREAD

**Issue by BCasal** [jekyll/jekyll#4729]
jekyll 3.1.1 (BunsenLabs Hydrogen)

How to disable autogen id's for h1, h2, h3 etc...

Why now, when i write posts or pages in markdown, jekyll autogen an id same as text, example:

```
# Title h1 for my first post

render as

<h1 id="Title-h1-for-my-first-post">Title h1 for my first post</h1>
```

the `_config.yml` file contain default settings

```
# Build settings
markdown: kramdown
```

how to disable it?

**Comment by BCasal** [comment]
adding "redcarpet" to my `_config.yml` solved

```
# Build settings
markdown: redcarpet
```

but, [Starting May 1st, 2016, GitHub Pages will only support kramdown, Jekyll's default Markdown engine.](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0)

**Comment by envygeeks** [comment]
Please see the documentation here: https://jekyllrb.com/docs/configuration/ it gives an example of how to configure Kramdown.  Thanks
