### ISSUE TITLE
Error while loading jekyll-paginate

### ISSUE THREAD

**Issue by iamshubh22** [jekyll/jekyll#4730]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.0.3

###### What operating system are you using?
Ubuntu 15.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

###### What did you see instead?
**`jekyll build`** gives

Configuration file: /home/shubham/Documents/blog/test/iamshubh22.github.io/_config.yml
/var/lib/gems/2.1.0/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-paginate (LoadError)
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:27:in `each'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:27:in `require_gems'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:97:in `setup'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:49:in `initialize'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:30:in `new'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:30:in `process'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.1.0/gems/jekyll-3.0.3/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

although
**`bundle show jekyll-paginate`** gives

/var/lib/gems/2.1.0/gems/jekyll-paginate-1.1.0

and Gemfile contains
source "https://rubygems.org"
gem 'jekyll-compose', group: [:jekyll_plugins]
gem "jekyll", "~> 3.0.3"
#gem "rdiscount", "~> 2.1.7"
#gem "pygments.rb", "~> 0.6.3"
#gem 'kramdown', '~> 1.8'
#gem 'rouge', '~> 1.10', '>= 1.10.1'
gem "github-pages", "~> 66"
gem "rake", "~> 10.1.1"
gem "jekyll-paginate"

**Comment by DirtyF** [comment]
Hi,

I can't reproduce your issue locally, everything works fine. They are only some deprecation warnings related to the `_plugins` used.

Please note that there is no need to add `jekyll` or `jekyll-paginate` to [your Gemfile](https://github.com/iamshubh22/iamshubh22.github.io/blob/master/Gemfile) if you use the `github-pages` gem. See `github-pages` [dependencies](https://pages.github.com/versions/).
