### ISSUE TITLE
category name, different with category url.

### ISSUE THREAD

**Issue by alihaddadkar** [jekyll/jekyll#4732]
Hello.
I have 2 variables. category and category-fa.
I want dispaly category-fa variable  for category name, and category variable for category url in for loop.
How do I display the names and addresses different from each other?

**Comment by DirtyF** [comment]
Hi,

Please note that this repository's issues are dedicated to Jekyll's bugs. You can ask any question related to Jekyll's usage on [https://talk.jekyllrb.com/](https://talk.jekyllrb.com/). 

Thanks.

**Comment by alihaddadkar** [comment]
Ok.
Thanks
