### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by altsab** [jekyll/jekyll#4737]
###### What version of Jekyll are you using (`jekyll -v`)?
Not using, there is an error while installing

###### What operating system are you using?

Linux Ubuntu 14.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
User@Somme:~/Soft/rubygems$ gem install jekyll
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/jekyll-3.1.2.gemspec.rz)

###### What did you expect to see?

Installation of Jekyll

###### What did you see instead?

ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/jekyll-3.1.2.gemspec.rz)

**Comment by envygeeks** [comment]
This is a problem with RubyGems.org and/or your own internet.  Unfortunately there is nothing we can do about it other than recommend you try again (this typically works.)  Sorry.
