### ISSUE TITLE
An issue when installing jeklly in windows 8.1

### ISSUE THREAD

**Issue by JayfongL** [jekyll/jekyll#4738]
###### What version of Jekyll are you using (`jekyll -v`)?

actually i am trying to install jekyll but failed

###### What operating system are you using?

windows 8.1

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

i tried to install jekyll by using' gem install jekyll'
but failed and then i did 'gem sources --remove https://rubygems.org/'
'gem sources -a https://ruby.taobao.org/' but after typing these command, 
i found 'gem sources' is empty! 

###### What did you see instead?
input 'gem sources -a https://ruby.taobao.org/' or  'gem sources -a https://rubygems.org/'
show me "Error fetching https.................
                           error:: ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect <https://api.rubygems.org/space.4.8.gz>

**Comment by envygeeks** [comment]
Unfortunately this is a RubyGems.org problem, there is nothing we can do about this. The most we can recommend is that you retry in a little bit with the official https://rubygems.org source (as the other one is not supported by us and if you have a problem with that source we will simply ignore it.) Sorry.
