### ISSUE TITLE
`include` tag with file as variable fails with 'Liquid Exception: Invalid syntax for include tag.'

### ISSUE THREAD

**Issue by SpacyRicochet** [jekyll/jekyll#4739]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.2

###### What operating system are you using?

Mac OSX latest update

###### What did you do?

[Example project to reproduce this issue](https://github.com/SpacyRicochet/jekyll_include_bug)

Add an include tag with a variable for the file. 

**Relevant include tag**

```
{% include {{test}} %}
```

**Variable in _config.yml**

```
test: test
```

`jekyll build` fails with the error: 

```
  Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: Valid syntax: {% include file.ext param='value' param2='value' %} in _includes/header.html, included in _layouts/default.html
```

Instead, if I change the include tag to;

```
{% include test %}
```

the site build fine.

###### What did you expect to see?

No errors during build.

###### What did you see instead?

The error mentioned above.

**Comment by budparr** [comment]
Two things: 
1) It's looking for the value of test to have an extension (that is actually be an include file):

`test: test.html`
 
2) You'll want to call it with the site namespace: 

`{% include {{site.test}} %}`

**Comment by SpacyRicochet** [comment]
> 1) It's looking for the value of test to have an extension (that is actually be an include file):

It doesn't seem to care about this. Using `{% include test %}` where 'test' is the complete filename works fine, for example.

> 2) You'll want to call it with the site namespace:

This works! 🎉 

Do you know if this changed explicitly since jekyll 2.x. The construction without the namespace used to work fine.

**Comment by budparr** [comment]
Actually, when I tested `{% include test %}` I got errors. As far as I recall (having used Jekyll for nearly three years, that's always been the case, but can't say for certain.

**Comment by envygeeks** [comment]
@budparr If I recall (and my memory isn't tight on this one) we recently accepted a pull that allows include to default to an assumptive "test" => "test.html" (where I'm not tight is whether it was rejected or not. I do absolutely remember seeing a pull about it though.)

**Comment by budparr** [comment]
I tested on 3.1.2 and it didn't work.

**Comment by envygeeks** [comment]
Yup @budparr I just double checked that source quickly and I don't see anything that does that so it should error. Did it not error for you @SpacyRicochet?

**Comment by SpacyRicochet** [comment]
Nope. Even more, I use it to add ascii portraits to our blog. The portraits are all files without extensions and it works perfectly.

**Comment by envygeeks** [comment]
Well that's why it works.  An extensionless file can be called without an extension.  Thanks for the update.
