### ISSUE TITLE
Exlude pages from being automatically added to the menu

### ISSUE THREAD

**Issue by sondr3** [jekyll/jekyll#4743]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.2

###### What operating system are you using?
OS X 10.11.4

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I created a 404.html file in the bottom directory for 404 errors, however I didn't want it to show in the automatically generated menu. I had to do

```liquid
{% for my_page in site.pages %}
    {% if my_page.title != "404: Page not found" %}
        <a class="page-link" href="{{ my_page.url | prepend: site.baseurl }}">{{ my_page.title }}</a>
    {% endif %}
{% endfor %}
```

but found it to be a bit too hard coded for my tastes. I was wondering if it would be possible to automatically exclude pages from being generated/what other ways I could do this?

**Comment by parkr** [comment]
> I was wondering if it would be possible to automatically exclude pages from being generated

This is not a feature of pages and we don't plan on that being so.

> what other ways I could do this?

I'd recommend adding some YAML front matter that could be used to filter your pages. On my personal website, I have a few pages I want in the navigation list and I added a `show_in_nav_bar: true` property to those pages' YAML front matter directives. In my layout, I simply filtered based on that property:

```liquid
{% assign nav_pages = site.pages | where: "show_in_nav_bar", true %}
{% for my_page in nav_pages %}
  <a class="page-link" href="{{ my_page.url | prepend: site.baseurl }}">{{ my_page.title }}</a>
{% endfor %}
```

Give that a shot and post to [Jekyll Talk](https://talk.jekyllrb.com) if you are having further difficulties.
