### ISSUE TITLE
URL to ID has hash symbol after closing slash

### ISSUE THREAD

**Issue by sackwort** [jekyll/jekyll#4745]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.2

###### What operating system are you using?
Linux Mint 17.3 64-bit

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
permalink: pretty

Creating a link in one page to a an ID in another page.

###### What did you expect to see?

/about#item/ in the url address bar of the browser, as this is the url of the link.

###### What did you see instead?

/about/#item in the url address bar of the browser.

This link seems to function OK, but I've never before seen a url structured like this. Is it a valid url? Is there a way to get the desired url?

If I don't use pretty permalinks, the url appears in the address bar as expected: /about.html#item

**Comment by envygeeks** [comment]
Technically, it is a valid URL, whether or not it's a good representation of a decent URL is what should be called into question here.

**Comment by envygeeks** [comment]
Let me clarify, I think that's an ugly URL even if it's valid. I however do not know if we adhere to the same principle as web servers to give distinction to folders over files (with dynamic routing) by adding a trailing slash to all directories (that we do index.html in and link to) so if we don't this would be an easy fix, if we do then the logic becomes slightly more complicated but should still be decent if @jekyll/stability @jekyll/core agrees.

**Comment by hg** [comment]
yeah, i agree with @envygeeks here. personally, i've never seen that one before as well though, so maybe it should be reformatted in some way.

coming from the stability team, on the one hand it'd be clearer in that specific case, but on the other hand it'll be more confusing internally and in comparison with other common formats (like how web servers do it). so idk, it's probably best to get more opinions on this

**Comment by sackwort** [comment]
Thanks very much, @envygeeks and @hg, for your input.

I don't like the url; I don't feel I can trust it! So, for now, I think I won't use this kind of link with Jekyll.

**Comment by parkr** [comment]
@sackwort How is the link being made?

**Comment by sackwort** [comment]
@parkr I'm making the links like this: <a href="/therapies#{{ therapy.title | slugify }}">Read more...</a>, but I get exactly the same result if I write them like this: <a href="/therapies#reiki">Read more...</a>.

**Comment by parkr** [comment]
This looks like a quirk in the way the web browser redirects your requests for `/about`. When you go to `/about`, are you redirected to `/about/`? If so, then this is normal and you should be good to go. I see this a lot, actually. 👍

**Comment by sackwort** [comment]
Yes, `/about` takes me to `/about/`.

My 'issue' seems to be happening because of the way the page directories each contain an index.html page when using pretty urls. If I don't use pretty urls, the address is as expected `something.html#id`.

Like you said, it must be just the way browsers interpret the url.

**Comment by envygeeks** [comment]
@sackwort @parkr it's the server doing it, not the browser.  In Apache you can disable that behavior, in Nginx you cannot.  In a lot of proxies and cachers you cannot as well.

**Comment by envygeeks** [comment]
At least for directory/index.html it's the server doing it.  If it does it when it's a dynamic URL (say with try_files) at that point it is the browser doing it (though I've not seen a browser do that for non-directories -- because it's the server doing it for directories.)

Let me clarify:

Browsers says "I want `/page`"
Server says: "It's actually `/page/` because this is a directory go here."
Browser gives you `/page/#anchor`

It's been that way since the dawn of web servers and so far the only ones with the ability to easily disable it in the context you wish to use Jekyll is Apache.  Though I think in a way you can trick Nginx into doing it with `try_files` by usurping it's search for a folder through internal tries.

**Comment by sackwort** [comment]
Thanks for the info @envygeeks. In Apache, can this behaviour be changed via a .htaccess file?

**Comment by envygeeks** [comment]
Depending on who runs the server and how strict they are yes: https://httpd.apache.org/docs/current/mod/mod_dir.html#directoryslash

**Comment by sackwort** [comment]
Thanks very much for your help @envygeeks.
