### ISSUE TITLE
Generation fail

### ISSUE THREAD

**Issue by braaannigan** [jekyll/jekyll#4748]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.0.3

###### What operating system are you using?
OSX 10.9.5

###### What did you do?
I'm trying to generate my jekyll site locally for the first time, following the github pages instruction.  Everything goes smoothly until I get to the command:
bundle exec jekyll serve
I get the following output:
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr/local in PATH, mode 040777
Configuration file: /Users/liambrannigan/Documents/Oceanography/website_local_repo/_config.yml
            Source: /Users/liambrannigan/Documents/Oceanography/website_local_repo
       Destination: /Users/liambrannigan/Documents/Oceanography/website_local_repo/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.0.3 | Error:  undefined method `match' for nil:NilClass

I'm not sure if the world writeable files part is an issue, as I'm the only person with access to this machine.  I haven't had much luck understanding the final error though - any suggestions?  

fwiw I've also just installed ruby with this version: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]

Thanks for any advice!
Liam

**Comment by pathawks** [comment]
Is your site’s source public?

**Comment by braaannigan** [comment]
Hi

No, it's just a local build at this point.

Liam

**Comment by DirtyF** [comment]
HI @braaannigan, could you update to the latest patched version of Ruby 2 and tell us if generation still fails?

**Comment by parkr** [comment]
Please also run jekyll with `--trace`, like `bundle exec jekyll build --trace`. It will give us more info. It looks like a plugin issue at first glance.

**Comment by braaannigan** [comment]
Hi
Thanks for all your suggestions.

I've updated to ruby 2.3.0
ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin13]

I've also re-installed homebrew and bundler.
However, I'm still getting errors at the same point.  I've included the trace output below:

bundle exec jekyll build --trace

/Users/username/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr/local in PATH, mode 040777
/Users/username/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /usr/local in PATH, mode 040777
Configuration file: /Users/username/Documents/Folder_Name/website_local_repo/_config.yml
            Source: /Users/username/Documents/Folder_Name/website_local_repo
       Destination: /Users/username/Documents/Folder_Name/website_local_repo/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-github-metadata-1.10.0/lib/jekyll-github-metadata/ghp_metadata_generator.rb:39:in `git_nwo': undefined method `match' for nil:NilClass (NoMethodError)
Did you mean?  catch
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-github-metadata-1.10.0/lib/jekyll-github-metadata/ghp_metadata_generator.rb:46:in `nwo'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-github-metadata-1.10.0/lib/jekyll-github-metadata/ghp_metadata_generator.rb:8:in `generate'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:154:in `block in generate'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:153:in `each'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:153:in `generate'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-3.0.3/lib/jekyll/site.rb:58:in `process'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-3.0.3/lib/jekyll/command.rb:28:in `process_site'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:60:in `build'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:35:in `process'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-3.0.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-3.0.3/bin/jekyll:17:in `<top (required)>'
	from /Users/username/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `load'
	from /Users/username/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `<main>'
	from /Users/username/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/username/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by Crunch09** [comment]
Can you 

> /Users/username/.rvm/gems/ruby-2.3.0/gems/jekyll-github-metadata-1.10.0/lib/jekyll-github-metadata/ghp_metadata_generator.rb:39:in git_nwo': undefined methodmatch' for nil:NilClass (NoMethodError)

Can you try to specify a remote named `origin` for your local site's git repo and see if this fixes the build process for you?

**Comment by parkr** [comment]
/cc @benbalter

This is a problem with jekyll-github-metadata.

**Comment by benbalter** [comment]
@parkr looks like we need to rescue, can you see what the raise is? Should we just rescue everything?

**Comment by envygeeks** [comment]
@benbalter do you mean rescue everything in Jekyll? If you mean that then that's a very bad way to do applications.  One should only rescue what they expect, anything else is a problem that needs to be address through defensive programming.

**Comment by Crunch09** [comment]
@benbalter Wouldn't it be enough if we would just make sure that `git_remote_url` is not `nil` before calling [`match` on it](https://github.com/jekyll/github-metadata/blob/225bd6f384a33b3377be3d3603f48f7cc63d5721/lib/jekyll-github-metadata/ghp_metadata_generator.rb#L39)?

**Comment by braaannigan** [comment]
Hi
Regarding this comment - "Can you try to specify a remote named origin for your local site's git repo and see if this fixes the build process for you?"

Do I have to restart the repo from scratch in this case to change the name?
Liam

**Comment by Crunch09** [comment]
@braaannigan Hi, no you can just go into your site directory and add a new remote with `git remote add origin git@github.com:braaannigan/MYSITE.git` or rename an existing remote via `git remote rename OLDNAME origin`. All this provided your site directory is already a git repository.
Hope this helps until this issue is fixed!

**Comment by benbalter** [comment]
>  if we would just make sure that `git_remote_url` is not `nil` before calling [`match` on it](https://github.com/jekyll/github-metadata/blob/225bd6f384a33b3377be3d3603f48f7cc63d5721/lib/jekyll-github-metadata/ghp_metadata_generator.rb#L39)?

Ahh yes. That seems like a saner approach. My original suggestion was a rescue on the `git_remote_url` method.

**Comment by braaannigan** [comment]
Excellent - doing  git remote add origin git@github.com:braaannigan/MYSITE.git 

worked like a charm.  Thanks people!

Liam

**Comment by DirtyF** [comment]
@braaannigan, just curious, does your `_config.yml` contains `repository: braaannigan/MYSITE` in order to help `github-metadata` getting remote info?

**Comment by hs2600** [comment]
@DirtyF, I was having the same issue as @braaannigan and by adding `repository:` `hs2600/hs2600.github.io` to `_config.yml` fixed the issue.
Thanks!

**Comment by braaannigan** [comment]
Hi @DirtyF, there's nothing in there about a repository.

Liam

**Comment by parkr** [comment]
Closed by jekyll/github-metadata#54 😄 Will release soon!
