### ISSUE TITLE
Error:  No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by dylankarr** [jekyll/jekyll#4749]
###### What version of Jekyll are you using (`jekyll -v`)?

`jekyll 3.1.2`

###### What operating system are you using?

`Mac OS X v10.11.4 (15E65)`

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Ran `jekyll serve`

###### What did you expect to see?

I expected it to work.

###### What did you see instead?

```
% jekyll serve
Configuration file: none
            Source: /Users/dylankarr
       Destination: /Users/dylankarr/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.1.2 | Error:  No such file or directory @ rb_sysopen - /Users/dylankarr/Applications/1Password 6.app/Contents/Frameworks/AgileLibrary-Mac.framework/AgileLibrary
```

Why is jekyll doing anything with my 1Password data? This seems disconcerting.

**Comment by envygeeks** [comment]
>  Why is jekyll doing anything with my 1Password data? This seems disconcerting.

See: "Source: /Users/dylankarr" you told us to load your entire home directory, that includes your 1Password files if they are anywhere in the home directory ***you asked us to load***.  Try using `--source` to tell us where the Jekyll source to compile is or using a sub-directory. and doing `jekyll serve` there.

**Comment by dylankarr** [comment]
Oops, stupid mistake. This was an unrelated problem with my tmux setup. I opened a new window and thought I was in the same directory, but I wasn't.

**Comment by envygeeks** [comment]
@dylankarr I've had that happen too.  No worries.  Hope it works now!
