### ISSUE TITLE
cannot load such file -- kramdown after modify gemfile

### ISSUE THREAD

**Issue by vjandrei** [jekyll/jekyll#4761]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.2

###### What operating system are you using?
Osx 10.11.3 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I run 
~ $ jekyll new myblog
~ $ cd myblog
~ $ jekyll s
open new tab on the chrome browser http://localhost:4000/
~ $ closed down the jekyll s
added gemfile
modify gemfile by adding 
group :jekyll_plugins do
  gem 'jekyll_pages_api_search'
end
~ $ bundle install 
~ $ jekyll s
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jekyll_pages_api_search'. (Bundler::GemRequireError)
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.2/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
        from /Users/andreaskoutsoukos/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.2/bin/jekyll:9:in `<top (required)>'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/bin/jekyll:23:in `load'
        from /Users/andreaskoutsoukos/.rbenv/versions/2.2.1/bin/jekyll:23:in `<main>'
modify gemfile by removing the  
group :jekyll_plugins do
  gem 'jekyll_pages_api_search'
end and now it´s empty
try to run again 
~ $ jekyll s
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/andreaskoutsoukos/Documents/Personal/_www-projektit/_omatprojektit/_GitHub/myblogi/_config.yml
  Dependency Error: Yikes! It looks like you don't have kramdown or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- kramdown' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.1.2 | Error:  kramdown

**Comment by envygeeks** [comment]
Remove your Gemfile.lock, verify that you have Kramdown in the Gemfile, bundle install again, and then `bundle exec jekyll` instead of doing normal `jekyll` (unless you have it aliased over to bundle exec.)

If it continues this problem should be reported to: https://github.com/bundler/bundler

**Comment by pathawks** [comment]
> and now it´s empty

Is your `Gemfile` _empty_, or does it include Jekyll??

**Comment by vjandrei** [comment]
My Gemfile looks like this source 'https://rubygems.org'
group :jekyll_plugins do
	gem 'github-pages'
	gem 'jekyll-lunr-js-search', '~> 3.1'
	gem 'jekyll-sitemap'
	gem 'autoprefixer-rails'
	gem 'jekyll-assets'
end	
	
group :development do
  gem 'capistrano', '~> 3.4.0'
  gem 'capistrano-rails', '~> 1.1.3'
  gem 'capistrano-rbenv', '~> 2.0.3'
  gem 'capistrano-passenger'
end

**Comment by envygeeks** [comment]
@vjandrei what does `bundle list` produce? And again, did you try with `bundle exec`?

**Comment by vjandrei** [comment]
@envygeeks I removed Gemfile.lock

bundle list
Gems included by the bundle:
  * RedCloth (4.2.9)
  * activesupport (4.2.6)
  * addressable (2.3.8)
  * autoprefixer-rails (6.3.6)
  * bundler (1.11.2)
  * coffee-script (2.4.1)
  * coffee-script-source (1.10.0)
  * colorator (0.1)
  * concurrent-ruby (1.0.1)
  * ethon (0.8.1)
  * execjs (2.6.0)
  * faraday (0.9.2)
  * fastimage (1.9.0)
  * ffi (1.9.10)
  * gemoji (2.1.0)
  * github-pages (68)
  * github-pages-health-check (1.1.0)
  * html-pipeline (2.3.0)
  * i18n (0.7.0)
  * jekyll (3.0.3)
  * jekyll-assets (2.1.2)
  * jekyll-coffeescript (1.0.1)
  * jekyll-feed (0.4.0)
  * jekyll-gist (1.4.0)
  * jekyll-github-metadata (1.10.0)
  * jekyll-lunr-js-search (3.1.0)
  * jekyll-mentions (1.1.2)
  * jekyll-paginate (1.1.0)
  * jekyll-redirect-from (0.10.0)
  * jekyll-sass-converter (1.3.0)
  * jekyll-seo-tag (1.3.3)
  * jekyll-sitemap (0.10.0)
  * jekyll-textile-converter (0.1.0)
  * jekyll-watch (1.3.1)
  * jemoji (0.6.2)
  * json (1.8.3)
  * kramdown (1.10.0)
  * libv8 (3.16.14.13)
  * liquid (3.0.6)
  * listen (3.0.6)
  * mercenary (0.3.5)
  * mini_portile2 (2.0.0)
  * minitest (5.8.4)
  * multipart-post (2.0.0)
  * net-dns (0.8.0)
  * nokogiri (1.6.7.2)
  * octokit (4.3.0)
  * public_suffix (1.5.3)
  * rack (1.6.4)
  * rb-fsevent (0.9.7)
  * rb-inotify (0.9.7)
  * rdiscount (2.1.8)
  * redcarpet (3.3.3)
  * ref (2.0.0)
  * rouge (1.10.1)
  * safe_yaml (1.0.4)
  * sass (3.4.22)
  * sawyer (0.7.0)
  * sprockets (3.6.0)
  * sprockets-helpers (1.2.1)
  * terminal-table (1.5.2)
  * therubyracer (0.12.2)
  * thread_safe (0.3.5)
  * tilt (2.0.2)
  * typhoeus (0.8.0)
  * tzinfo (1.2.2)

Did some command 

andreas-MacBook-Air:myblog Andreas-air$ bundle exec jekyll
A subcommand is required. 
jekyll 3.0.3 -- Jekyll is a blog-aware, static site generator in Ruby

Usage:

  jekyll <subcommand> [options]

Options:
        -s, --source [DIR]  Source directory (defaults to ./)
        -d, --destination [DIR]  Destination directory (defaults to ./_site)
            --safe         Safe mode (defaults to false)
        -p, --plugins PLUGINS_DIR1[,PLUGINS_DIR2[,...]]  Plugins directory (defaults to ./_plugins)
            --layouts DIR  Layouts directory (defaults to ./_layouts)
            --profile      Generate a Liquid rendering profile
        -h, --help         Show this message
        -v, --version      Print the name and version
        -t, --trace        Show the full backtrace when an error occurs

Subcommands:
  build, b              Build your site
  clean                 Clean the site (removes site output and metadata file) without building.
  doctor, hyde          Search site and print specific deprecation warnings
  help                  Show the help message, optionally for a given subcommand.
  new                   Creates a new Jekyll site scaffold in PATH
  serve, server, s      Serve your site locally
andreas-MacBook-Air:myblog Andreas-air$ bundle exec jekyll serve
Configuration file: /Users/Andreas-air/Documents/_demot/myblog/_config.yml
            Source: /Users/Andreas-air/Documents/_demot/myblog
       Destination: /Users/Andreas-air/Documents/_demot/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
fatal: Not a git repository (or any of the parent directories): .git
jekyll 3.0.3 | Error:  undefined method `match' for nil:NilClass
andreas-MacBook-Air:myblog Andreas-air$

**Comment by parkr** [comment]
> fatal: Not a git repository (or any of the parent directories): .git
> jekyll 3.0.3 | Error: undefined method `match' for nil:NilClass

This is fixed by [v69 of `github-pages`](https://github.com/github/pages-gem/releases/tag/v69), which was just released. Run `bundle update github-pages` then use `bundle exec jekyll serve` and it should work. :smile:

**Comment by vjandrei** [comment]
@parkr great this fixed the issue, thanks!!!
