### ISSUE TITLE
Cannot use css background-image: url() function on paginated routes due to '/page:num/' being inserted into route that url() evaluates to

### ISSUE THREAD

**Issue by emcenrue** [jekyll/jekyll#4762]
###### What version of Jekyll are you using (`jekyll -v`)?
3.1.2

###### What operating system are you using?
ubuntu 14.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Basically css function url() will not evaluate to {{site.url}}/{{site.baseurl}}/img/img_name.jpg

because it thinks that the url is {{site.url}}/{{site.baseurl}}/page:num/img/img_name.jpg

and so it searches for that image file path with 'page:num' and obviously wont be able to find it.

###### What did you expect to see?
the ability to have background-image on a paginated route

###### What did you see instead?
there are no file paths with the pagination included

**Comment by pathawks** [comment]
Can you provide a bit more information?

I want to try to reproduce this issue, but I will need _a lot_ more detail. Can you provide maybe a minimal Jekyll site that exhibits this behavior?

**Comment by emcenrue** [comment]
sure, see here: 

http://edwardmcenrue.com/blog/page2/

source code: https://github.com/emcenrue/blog

right click on any of the missing images from the top two posts and then inspect their elements. You'll see that I'm using background-image: url() and I'm providing img/img_name.jpg

then go into the developer tools console and you'll see that url() is evaluating the url route to include the '/page:num/' sub path.

This is my site, so I'm probably gonna change it to work with just an image from aws s3 or something like this guy is doing with his background-image: http://bitwiser.in/bitwiser-material/

thanks for the quick reply :+1:

**Comment by emcenrue** [comment]
actually just realized that I must have done this solution wrong: {{site.url}}/{{site.baseurl}}/{{post.header_image}} when I originally tried it. It's working now with that. I must've misspelled something like hader_image and overlooked the mistake and instead dismissed the solution as not working. My bad
