### ISSUE TITLE
Issue sorting with empty values "comparison of Jekyll::Document with Jekyll::Document failed"

### ISSUE THREAD

**Issue by budparr** [jekyll/jekyll#4766]
###### What version of Jekyll are you using (`jekyll -v`)?
3.0.3
###### What operating system are you using?
OSX
###### What did you do?

Sorting collection items by 'event_date' key, where some items have no date value. Using: `| sort: 'event_date', 'first'`

- Only seeing the issue with dates (I tested sorting by title, then removed a title; no error). 
- Wasn't seeing the error on my local install, but was getting build errors on gh-pages. 
- Then, I changed my empty date fields to values with `event_date: ''` instead of just `event_date:` and got the error locally. 
- Also, the error is not impacted if I don't specify the "nils order." i.e. I get it either way.

###### What did you expect to see?

documents sorted by date, with those having no date showing up first.

###### What did you see instead?

"Liquid error (line 67): comparison of Jekyll::Document with Jekyll::Document failed..."

Looks like this was addressed in 3.0.3 (#4446, #4444)

[stack trace](https://gist.github.com/budparr/3250160ec8fd49c8a89f0641a96b27e9)

**Comment by envygeeks** [comment]
Hey @budparr, Does @parkr's #4741 and HEAD fix this for you?

**Comment by budparr** [comment]
No, unfortunately. I get the same error  `Using jekyll 3.1.2 from git@github.com:jekyll/jekyll.git (at HEAD@0daf1f5)`

**Comment by Crunch09** [comment]
I think the problem is in [Jekyll::Filters#sort](https://github.com/jekyll/jekyll/blob/0daf1f5514d90a3da735afc6d38a07622901194e/lib/jekyll/filters.rb#L261) because it's comparing a `String` with a `Date`. I'm not sure if and how to solve it, though.

**Comment by parkr** [comment]
@budparr Are the values different types, e.g. a mixture of `String`s and `Date`s? If so, did you try picking just one? `nil`s should be fine to compare. I wish this error were more informative about which one breaks (it's the standard Ruby error for bad comparisons, sadly). 

When you compare something using `#<=>`, it must return some integer value, never `nil` though. But the nil check in that block should suffice... It's only if neither item is nil.

The real solution is to ensure the elements are all of the same type, because comparing a `Time` and a `String` will break it.

```irb
>> "2016-01-01" <=> Time.now
=> nil
>> Time.now <=> "2016-01-01"
=> nil
```

**Comment by budparr** [comment]
Yes, I think that's why I can force the error locally by adding `event_date: ''` to my template. My problem is that it's breaking on GH-Pages even when I don't do that.

**Comment by budparr** [comment]
Guys, I'm going to close this issue for now. I worked around it for now, and I'll check it again when GH-Pages is up-to-date with Jekyll.

**Comment by parkr** [comment]
@budparr Waiting on review: https://github.com/github/pages-gem/pull/267
