### ISSUE TITLE
Photoblog and limit image in teaser in index

### ISSUE THREAD

**Issue by nleo** [jekyll/jekyll#4767]
jekyll 3.1.2 on Linux

Hello, guys, please help me figure out how to do this.

I'm creating a photo blog thith jekyll.

I'm putting images in folder galleries/2016/04/sample-gallery and create a plugin to show them:

```ruby
module Jekyll
  class Gallery < Liquid::Tag

    def initialize(tag_name, dir, tokens)
      super
      @dir = dir.strip
      @alt = dir.strip.split('/').last
      @dir_path = (File.expand_path File.dirname(__FILE__)+'/../galleries/'+dir).strip
      @files = Dir.entries(@dir_path).delete_if{|filename| ['..', '.', 'thumbs'].include? filename }
    end

    def render(context)
      html = '<div class="gallery wrapper">'
      @files.each do |filename|
        html += %(<a href="/galleries/#{File.join(@dir, filename)}">)
        html += %(<img src="/galleries/#{File.join(@dir, 'thumbs', filename)}" alt="#{@alt}">)
        html += %(</a>)
      end
      html += '</div>'
      html
    end
  end
end

Liquid::Template.register_tag('gallery', Jekyll::Gallery)

```

And I call it like this in post body `{% gallery 2016/04/sample-gallery %}` 

But now in index I want to show only 3 first images as teaser.

I'll try to use it like this

```html
{% for post in site.posts %}
    <li>
      <span class="post-meta">{{ post.date | date: "%b %-d, %Y" }}</span>

      <h2>
        <a class="post-link" href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>
      </h2>
      {% gallery post.gallery %}
    </li>
{% endfor %}
```

But it don't works. Sends `post.gallery` in helper, not it's contents.

How I can rewrite my plugin to use it in post index like this: `{% gallery post.gallery, only: 3 %}`?

**Comment by nleo** [comment]
Or maybe I can find out is it index page or post page from `context`?

**Comment by DirtyF** [comment]
Hi,

Please note that this repository's issues are dedicated to Jekyll's bugs. You can ask any question related to Jekyll's usage on [https://talk.jekyllrb.com/](https://talk.jekyllrb.com/). 

Thanks.

**Comment by envygeeks** [comment]
Yes @DirtyF stated please use the forums (https://talk.jekyllrb.com) for problems that are not bugs in Jekyll.
