### ISSUE TITLE
Embedding HTML in posts doesn't work with Jekyll 3 / kramdown

### ISSUE THREAD

**Issue by tmcw** [jekyll/jekyll#4768]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.1.2

###### What operating system are you using?

OS X 10.11.4 (15E65)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I updated from Jekyll 2.5.3 to Jekyll 3.0 and kramdown because of the GitHub Pages switch.

###### What did you expect to see?

I expected to see my posts with HTML to be produced with that HTML

###### What did you see instead?

The HTML is entity-encoded. For example, the iframes in http://www.macwright.org/2013/07/10/how-callbacks-work.html are shown as HTML.

* The source of that post: https://gist.github.com/7ddf7b81368737629e3f64b348296c13
* _config.yml: https://gist.github.com/d817f1c6d120c34dd99e3df83a55e58e

**Comment by envygeeks** [comment]
Kramdown ignores invalid HTML.  Please fix your HTML and make sure every attribute has quotes.

**Comment by tmcw** [comment]
Indeed, thanks! - this is invalid.
