### ISSUE TITLE
Feature request: where_intersects filter

### ISSUE THREAD

**Issue by drumanagh** [jekyll/jekyll#4772]
For complicated use of collections, it'd be helpful to have some kind of filter to give the results of an array intersected against docs in a collection, as well as one that does the opposite.

This is sort of hard to explain properly, so here's an example:

I have docs `a.md` and `b.md` in collection `jurassic`.

```
---
title: A
tags:
  - ducks
  - fish
  - zebra
---
```

```
---
title: B
tags:
  - fish
  - octopuses
  - lions
---
```

In a template, I'm handling a doc from collection `cretaceous`. This doc has an array `[fish, lions, koalas]`. I want to use this array to pull from the `jurassic` collection, getting anything where the `tags` contain one or more items from that array. I *also* want to get the items from the array that don't match any of those docs.

Here's some rough ideas of what it might look like:

```
{# returns an array of docs #}
{% assign jurassic_docs = site.jurassic | where_intersects: 'tags', my_array %}

{% for doc in jurassic_docs %}
   ...
{% endfor %}
```

```
{# returns a subset of my_array #}
{% assign non_matching_tags = site.jurassic | no_intersections: 'tags', my_array %}

{{ non_matching_tags | join: ', ' }}
```

I'm open to ideas here, especially for the second use. It's a use case that I have to definitely have to deal with right now (having the first but not the second functionality would eliminate any speed increase, since it'd have to loop through everything in the template anyway), but I can't figure out a less awkward syntax for it.

**Comment by budparr** [comment]
Have a look at this: https://github.com/jekyll/jekyll/pull/4478

**Comment by parkr** [comment]
#4478 should definitely aid quite a bit in accomplishing your goal, as @budparr notes.

This tag is very niche, so I don't see it being added to Jekyll core. Feel free to publish it as a plugin and link back to it here. Neat idea, though!
