### ISSUE TITLE
Jekyll regeneration does not reload plugins.

### ISSUE THREAD

**Issue by chrahunt** [jekyll/jekyll#4774]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.2

###### What operating system are you using?

Windows 10

###### What did you do?

Called `jekyll serve`

###### What did you expect to see?

Plugin and site files regenerated/reloaded when plugin or site files changed.

###### What did you see instead?

Site files regenerated when plugin or site files changed. Changes to plugin files did not go into effect until command was terminated and reissued.

This would be really helpful when developing plugins.

**Comment by parkr** [comment]
This has been the behaviour since Jekyll first had plugins. Are you proposing that when something in `_plugins` changes, the file is re`load`ed and a regeneration takes place? That might work. Could you file this with `jekyll-watch`? That's where all the reloading happens.
