### ISSUE TITLE
ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by ihurui** [jekyll/jekyll#4776]
###### What version of Jekyll are you using (`jekyll -v`)?
i am going to install jekyll.

###### What operating system are you using?

mac osx 10.11.1

###### What did you do?
i was going to install jekyll with typing "gem install jekyll" in the terminal,and i got this response:
ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure

what is the problem with this ?
how can i install jekyll correctly?

**Comment by chrahunt** [comment]
This isn't a Jekyll issue, it's a well-known issue and the fix depends on your platform, Ruby version, specific openssl version, etc. You can find information and suggestions [here](http://railsapps.github.io/openssl-certificate-verify-failed.html) and [here](http://stackoverflow.com/questions/15305350/gem-install-fails-with-openssl-failure).

**Comment by ihurui** [comment]
@chrahunt thx,i have solved the problem by changing the gem source,thx for your  inspiration

**Comment by chrahunt** [comment]
Anytime. Make sure to close the issue!
