### ISSUE TITLE
Jekyll 

### ISSUE THREAD

**Issue by vietvudanh** [jekyll/jekyll#4778]
###### What version of Jekyll are you using (`jekyll -v`)?
3.1.2

###### What operating system are you using?
MacOSX 10.11

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I'm in Vietnam, timezone UTC+7. I have set the `timezone: "Asia/Ho_Chi_Minh"` in `_config.yml`. 
I was writing post with current local timestamp, let's say 12hAM. Run `jekyll serve` or `jekyll build`.

###### What did you expect to see?
The post will be generated into HTML.

###### What did you see instead?
It's not. I think there is a mechanism to filter the time? And it's not working? I think Jekyll only generate post prior to current (UTC) time, *future* post won't be generated?
Because if I set the time of the post to like 5AM, the post is generated.

I have tried to search for solution but seems there no help. Thank you.

###### Work-around
I set the time -7h to my current timestamp, and the post is generated.

**Comment by envygeeks** [comment]
This is how it's meant to work, we do not infer the zone of a post, you must include the timezone.

**Comment by vietvudanh** [comment]
Ah, so I need to specify the timezone in each post? ok, but it's not very convenience.
So the timezone in _config.yml is just use to set environment for ruby?

**Comment by parkr** [comment]
> So the timezone in _config.yml is just use to set environment for ruby?

@vietvudanh Yes, the `timezone` in your `_config.yml` just sets the `TZ` environment variable. 😄
