### ISSUE TITLE
Unable to load JSON on Github pages, though it loads on `jekyll serve`

### ISSUE THREAD

**Issue by geezhawk** [jekyll/jekyll#4782]
###### What version of Jekyll are you using (`jekyll -v`)?
3.0.3

###### What operating system are you using?
Linux Mint 17.2

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I moved a JSON file to a directory in my site's root directory, and accessed it via an AJAX call in my script. When I ran `jekyll serve` the script was able to load the JSON file without a problem. But when I pushed the changes to Github Pages, the attempt to load the JSON file throws a 404 error. 

###### What did you expect to see?
I expected my Github Pages site to be able to serve the JSON file in the same way as it did with `jekyll serve`

###### What did you see instead?
Instead, the JSON file wasn't loaded.

**Comment by parkr** [comment]
@geezhawk Please write into support@github.com as this is not a generic Jekyll problem. It sounds like a CORS-related AJAX problem, but I can't know more unless you provide more information about how you're attempting to load the files. GitHub Support can check out the resulting site and see where your file went if it was generated.
