### ISSUE TITLE
unable to generate site, though it once worked

### ISSUE THREAD

**Issue by hkopp** [jekyll/jekyll#4783]
Hi all,
I have my site at http://hkopp.github.io/ with code at https://github.com/hkopp/hkopp.github.io.git and if i try to compile it locally (jekyll build &&jekyll serve --watch) it works, except it does not find the css-stuff for the posts.
The main page is fine but when i click on a post the layout is broken. 

The relevant HTML-code of the posts is:

    
    <link href="/assets/themes//bootstrap/css/bootstrap.min.css" rel="stylesheet">
    
    <link href="/assets/themes//bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
    
    <link href="/assets/themes//bootstrap/css/bs-sticky-footer.css" rel="stylesheet">
    
    
    <link href="/assets/themes//css/style.css?body=1" rel="stylesheet" type="text/css" media="all">

Which is wrong. Between the two slashes is a bootstrap-3 missing. At the main page it works. The curious thing is that it once worked as you can see on my page.

###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.0.1

###### What operating system are you using?
Fedora 23

###### What did you see instead?
see above. I hope my description is clear. Please feel free to ask if there is anything unclear.

**Comment by hkopp** [comment]
I also tried switching to a different layout, but the problem remains.

**Comment by parkr** [comment]
@hkopp This looks like a problem with Jekyll-bootstrap, not with Jekyll. Did you try https://github.com/plusjade/jekyll-bootstrap/issues/302#issuecomment-202066440 ?

**Comment by hkopp** [comment]
Perfect. That fixed my problem. I don't understand why it broke in the first place, but now it works again.
Thank you.
