### ISSUE TITLE
Run Issue

### ISSUE THREAD

**Issue by herohamp** [jekyll/jekyll#4784]
I built Jekyll and got my page to look like http://www.herohamp.xyz/blog/index.html Please help!

**Comment by envygeeks** [comment]
Hi @herohamp, this medium is for Jekyll bugs only.  If you are having problems getting your site to build the way you wish to build and cannot confirm it's a bug, then please use the forums at https://talk.jekyllrb.com.

Additionally you will need to provide much more information than you have currently given, such as where your source is (and if it's not available then nobody can even begin to help you.) How you are building, and what version of Jekyll you are using (if you are not using github-pages gem or jekyll gem at their latest versions first update and try again.)

Thanks.

**Comment by herohamp** [comment]
OK I quit jekyll

**Comment by vietvudanh** [comment]
I had this problem before, check your css file URL. You probably will see it's wrong so the page looks like this.
Make sure the `baseurl` in config is correct.
