### ISSUE TITLE
Dependency error while trying to load local gem plugin via gemfile

### ISSUE THREAD

**Issue by alias1** [jekyll/jekyll#4785]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.1.2

###### What operating system are you using?

OSX Yosemite 10.10.5

###### What did you do?

I am trying to work on a local gem-based plugin. I sourced it from my gemfile, using the path override to point to the local file:

```
gem 'jekyll-myplugin', :path => "/Users/devalias/dev/jekyll-myplugin"
```

Then I ran `bundle install`.

I made sure to reference it in my `_config.yml`

```
gems:
  - jekyll-myplugin
```

Then I ran `jekyll serve`

###### What did you expect to see?

The plugin loaded correctly and running.

###### What did you see instead?

> Dependency Error: Yikes! It looks like you don't have jekyll-webmention_io or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-webmention_io' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!

**Comment by envygeeks** [comment]
Please try it with `bundle exec jekyll serve` instead of just `jekyll serve` normal bundle install will install to the system until the point you use something like Git or a Path and at  that point it will switch to a localized install so you'll need to do `bundle exec` instead of just `jekyll` like you normally be able to do.

**Comment by alias1** [comment]
I believe I have it setup to automatically shim `jekyll serve` to `bundle exec jekyll serve`, but just in case, tried it directly and got the same error.

**Comment by envygeeks** [comment]
Seems weird.  I'll try to replicate it on one of my Jekyll sites since we have a few that use local gems.

**Comment by alias1** [comment]
Cool. Cheers :)

**Comment by alias1** [comment]
Ok, just played around a bit more and I think some of the naming was messed up in the gem, causing the load to fail. It looks like it's working now (different error, unrelated to loading). Thanks!
