### ISSUE TITLE
Using liquid in liquid

### ISSUE THREAD

**Issue by artemgurzhii** [jekyll/jekyll#4794]
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.2

###### What operating system are you using?
Mac OS X El Capitan

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
`<img src="{{ "/assets/img/ready/ {{ post.tags limit:1 }}.svg " | prepend: site.baseurl }}"  alt="{{ post.tags }}" />`

###### What did you expect to see?
`<img src="/assets/img/ready/html.svg" alt="html css jekyll">`

###### What did you see instead?
`<img src=".svg " |="" prepend:="" site.baseurl="" }}"="" alt="html css jekyll">`

Hi, my question is 'Can I use liquid in liquid? And if I can, can you please provide example/solution of my problem?'

**Comment by DirtyF** [comment]
Hi,

Please note that this repository's issues are dedicated to Jekyll's bugs. You can ask any question related to Jekyll's usage on [https://talk.jekyllrb.com/](https://talk.jekyllrb.com/). 

Thanks.

**Comment by parkr** [comment]
@artemgurzhii You could probably do:

```liquid
<img src="{{ "/assets/img/ready/TAG.svg" | replace: "TAG", page.tags[0] | prepend: site.baseurl }}" alt="{{ post.tags | array_to_sentence_string }}" />

**Comment by artemgurzhii** [comment]
@parkr Thanks, that works
