### ISSUE TITLE
Why my new Jekyll Blog provides design technically from so corrupt

### ISSUE THREAD

**Issue by AlexL777** [jekyll/jekyll#4795]
###### What version of Jekyll are you using (`jekyll -v`)?
Version 3.1.2

###### What operating system are you using?

Rootserver Centos 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Hello Developers,

I would like to work with Jekyll and had installed it. But unfortunately under http://liebrecht-projekte.de/cms/jekyll/jekyll-cms-blog/_site/ I see no real blog and the design is broken. What am I doing wrong or how it should look?

This looks at in the blog and otherwise complete from.

I have installed the latest Jekyll version with "gem install jekyll", looking just after the URL, you must enter in the browser to get on the blog home page. Is it under / _site or where.

Looking forward to your help and thanks.

**Comment by artemgurzhii** [comment]
you should use `<link rel="stylesheet" href="css/main.css">` instead of `<link rel="stylesheet" href="/css/main.css">`

**Comment by AlexL777** [comment]
Thanks, it worked.

**Comment by AlexL777** [comment]
By SSh command "jekyll build" but is always generated the wrong style. How can I fix or I need to adjust something?

**Comment by artemgurzhii** [comment]
I'm not sure but probably something wrong with folder structure. Try to use `jekyll seve -w`

**Comment by AlexL777** [comment]
I jekyll reinstalled and now it goes. But without making a new issue here, I have a question. I have placed in the directory **/_posts** my first blog post as .md and it can not see in the frontend.

The demo blog post I put out and he was previously also indicated, but my first post is not displayed.

What am I doing wrong yet?

**Comment by envygeeks** [comment]
@AlexL777 we have no idea what you could be doing wrong unless you show us the filename and the content of the file.  Otherwise we could come up with any number of potential problems of which would be a diagnostic waste of time.

**Comment by parkr** [comment]
@AlexL777 It sounds like you forgot to add a timezone to your post, like:

```yaml
---
date: 2016-04-15 00:00:00 +2000
---
```

By default, Ruby's `Time.parse` reads them in as UTC.

**Comment by AlexL777** [comment]
It really was because and what does not work, it is the Categorys and tags.

These are not yet displayed. I just want to better understand the system and needs to gain more experience.

My meta tags see the first blog post like this:
```
---
layout: post
title: getting started with the ruby cms called jekyll
date: 2016-04-15 15:51:00 +2000
published: true
tags: jekyll, cms, blogger, installation, ruby
category: jekyllcms
---
```
But in the frontend the categories and tags are not displayed. What could be the problem? Thanks in advance.

**Comment by artemgurzhii** [comment]
`<p>{{ post.tags }}</p>`
`<p>{{ post.category }}</p>`

**Comment by AlexL777** [comment]
I'm really sorry that I have outstanding issues. Now I have integrated these two things in the index.html file.

With me in the front end, it still looks like this:

http://liebrecht-projekte.de/cms/jekyll/blog/_site/

The tags appear with commas between them and there is nothing linked.

Do I have perhaps a little config.yml insert in?

My second question would be whether you can get a blog search on Jekyll? Search must in a blog can to find the content. Is it compatible with the internal search at all possible?

Thanks in advance.

P.S. I will now blogging about Jekyll, so I have the most basic knowledge about ;-)

**Comment by artemgurzhii** [comment]
Read [liquid](https://shopify.github.io/liquid/basics/introduction/). Here you will find introduction how to use liquid template. if you want to have commas between each tag you should use for loop:
`{% for tag in post.tags limit:5 %}
  <p>{{ tag }</p>
{% endfor %}`
