### ISSUE TITLE
Errors don't show file or line number

### ISSUE THREAD

**Issue by nasht00** [jekyll/jekyll#4800]
When writing a plugin in Ruby, we sometimes get errors, it happens.

The problem is, the error that Jekyll gives does not specify the file name or line number.

Example: `jekyll 3.1.2 | Error:  No such file or directory @ rb_sysopen`

**Comment by envygeeks** [comment]
You need to enable debugging with `--verbose` to get the full error message with line numbers.  If that doesn't help then you need to tell us what you were doing because that error could pop up in any number of places and it would just suite to slow this ticket down without knowing what you were doing and what actually happened and what you expected (as our template suggests you do.)

**Comment by nasht00** [comment]
Oh I know what I did wrong and I fixed it.  
What I am saying is it makes debugging harder.

Another example, on purpose I wrote an undefined variable somewhere in my plugin file (`niluuu`).

I used `--verbose`. It prints a lof of things, but I still don't see any file name and line number for the error:

```
........
  Pre-Render Hooks: /tutorials/en/foundation/8.0/adding-the-mfpf-sdk/android.md
  Rendering Liquid: /tutorials/en/foundation/8.0/adding-the-mfpf-sdk/android.md
  Rendering Markup: /tutorials/en/foundation/8.0/adding-the-mfpf-sdk/android.md
  Rendering Layout: /tutorials/en/foundation/8.0/adding-the-mfpf-sdk/android.md
         Rendering: /tutorials/en/foundation/8.0/analytics/remote-controlled-client-side-log-collection/android.md
  Pre-Render Hooks: /tutorials/en/foundation/8.0/analytics/remote-controlled-client-side-log-collection/android.md
  Rendering Liquid: /tutorials/en/foundation/8.0/analytics/remote-controlled-client-side-log-collection/android.md
  Rendering Markup: /tutorials/en/foundation/8.0/analytics/remote-controlled-client-side-log-collection/android.md
  Rendering Layout: /tutorials/en/foundation/8.0/analytics/remote-controlled-client-side-log-collection/android.md
         Rendering: /tutorials/en/foundation/8.0/collateral-tutorials/app-center.md
  Pre-Render Hooks: /tutorials/en/foundation/8.0/collateral-tutorials/app-center.md
jekyll 3.1.2 | Error:  undefined local variable or method `niluuu' for main:Object
```

**Comment by envygeeks** [comment]
I didn't ask if you know what you did wrong, I asked you to tell us what you did wrong so that we can track down where the error is being spit out so that we can correct the problem.

**Comment by nasht00** [comment]
Sure.

1. Create a new file **_plugins/Sample.rb**
2. Enter the following in the file:
```
Jekyll::Hooks.register :pages, :pre_render do |page, payload|
  blablabla
end
```
3. Run `bundle exec jekyll serve --verbose`

**Comment by parkr** [comment]
@nasht00 Use `--trace`, too. `--verbose` shows you where it ran into problems in the content, `--trace` shows you where the error occurred in the code by printing the stack trace. It will tell you to use `--trace` as of #4674.

**Comment by Bilge** [comment]
I think the default setting should be more helpful than it is currently. It doesn't even mention the error type; literally just the message and nothing else. That's no good!
