### ISSUE TITLE
Replace toml with toml-rb

### ISSUE THREAD

**Issue by mrueg** [jekyll/jekyll#4801]
Would it be possible replace https://github.com/jm/toml with https://github.com/eMancu/toml-rb?

It seems to be more actively developed and uses citrus instead of blankslate and parslet.

**Comment by envygeeks** [comment]
I see a commit from @parkr not more than 4 days ago on that repo.

**Comment by parkr** [comment]
@mrueg @envygeeks I did merge a PR recently for someone. I have commit access for it but I am not really maintaining it. It's a little behind the TOML spec, thought TOML isn't really moving forward much as it is.

**Comment by parkr** [comment]
@mrueg I'm OK if you migrate us to toml-rb in a PR. I think `jm` isn't maintaining `toml` either.
