### ISSUE TITLE
Suggestion: Support a _pages directory

### ISSUE THREAD

**Issue by henrywright** [jekyll/jekyll#4802]
###### What version of Jekyll are you using (`jekyll -v`)?

3

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

n/a

###### What did you expect to see?

n/a

###### What did you see instead?

n/a

I'm using Jekyll and seem to have a need for a lot of pages. This means my project root is becoming quite cluttered with files like:

 - about.html
 - contact.html
 - team.html
 - ...

It would be great if you supported a _pages directory in the project root which could be used as a home for all of our page files.

**Comment by budparr** [comment]
You have two choices: Add this to your config.yml file:
```
include:
  - _pages
```
and then, if you want the filename to be your permalink (without the _pages in the url), do this: in config.yml, add this to your defaults:
```
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/
```
You can also declare or override the permalink in your front matter.

The other choice is to make "pages" a collection. The only problem with that is that then your pages show up in site.documents with the others, so the first choice is probably the best.

**Comment by henrywright** [comment]
Thanks @budparr 

If I used the first approach would my page URLs have a trailing slash? https://example.com/about/

Currently, my pages don't have a trailing slash and I'd like to keep it like that.

**Comment by budparr** [comment]
Just change ```permalink: /:basename/``` to ```permalink: /:basename:output_ext```
https://jekyllrb.com/docs/permalinks/#pages-and-collections

**Comment by henrywright** [comment]
Would `permalink: /:basename:output_ext` result in page URLs like this?

https://example.com/about.html

I don't really want the file extension in the URL. My aim is this (which is how my URLs currently look):

https://example.com/about

**Comment by parkr** [comment]
Alternatively, you can create a [collection](https://jekyllrb.com/docs/collections/) called `_pages` and configure with:

```yaml
collections:
  pages:
    output: true
    permalink: /:path/
```

We support this.

**Comment by henrywright** [comment]
@parkr I can see there are many workarounds to this problem but considering a page is a first class citizen (just like a post) I think they should have their own directory with no extra effort from the end developer.

Just some feedback. Thanks for making such a great blogging platform available.

**Comment by henrywright** [comment]
Hi @parkr, if I created a _pages collection as you suggested, how would I access a particular item's data set in the file's front matter?

Would I use `site.pages`? But then isn't that already in use for actual pages (just like `site.posts`)?

**Comment by parkr** [comment]
@henrywright `{% assign pages_collection = site.collections | where: "label", "pages" %}`

**Comment by henrywright** [comment]
Thanks, that's perfect @parkr. And if for a particular item in the collection I had this front matter:

```
---
custom_var: Foo
---
```

How would I access that variable using Liquid? I can't seem to find the answer in the [docs](https://jekyllrb.com/docs/collections/).

**Comment by henrywright** [comment]
@parkr I tested this today:

{% assign pages_collection = site.collections | where: "label", "pages" %}
{{ pages_collection }}

and this is what I get:

{"output"=>true, "label"=>"pages", "docs"=>[#, #, #, #, #], "files"=>[], "directory"=>"/home/henrywright/web/6ty8/_pages", "relative_directory"=>"_pages"}

As you can see, `pages_collection` doesn't seem to contain any data I've set in my page's front matter?

**Comment by parkr** [comment]
@henrywright Please look through the docs again for collections. In this case, your page is a member of `pages_collections.docs`. You can do another where clause to find it via the URL or path then assign it to some variable and that will have your page data.

**Comment by henrywright** [comment]
I decide to change my collection's name because I like how simple `site.collectionname` is to iterate over. Thanks @parkr for your help with this.
