### ISSUE TITLE
Duplicate content when setting a permalink

### ISSUE THREAD

**Issue by henrywright** [jekyll/jekyll#4803]
###### What version of Jekyll are you using (`jekyll -v`)?

3

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I created a new file in my project root called test.html. This is the front matter I'm using in that file:

```
---
layout: default
title: Test
description: This is a test page.
permalink: /test
---
```

###### What did you expect to see?

I expect to be able to access my new page only through _example.com/test_.

###### What did you see instead?

I can access the page through both:

 - example.com/test
 - example.com/test.html

This is causing my site to have duplicate content.

**Comment by artemgurzhii** [comment]
Hi, you should set permalink style to pretty in your _config file `permalink: pretty` like here [permalink](https://jekyllrb.com/docs/permalinks/#built-in-permalink-styles).
Here is solution and example how it works [solution](https://jekyllrb.com/docs/permalinks/#permalink-style-examples)

**Comment by pathawks** [comment]
> I can access the page through both

But only one file is generated, correct?

If you are only worried about SEO juice, you can fix this by specifying a canonical URL.

**Comment by parkr** [comment]
This is to be expected, as extensionless URL's map to files *with* extensions. I'd recommend setting up a redirect in your server to redirect your visitors to the non-html URL's if that's what you're after.

**Comment by henrywright** [comment]
@parkr is a redirect possible if using GitHub Pages?

**Comment by henrywright** [comment]
@pathawks both /test and /test.html exist which means 2 documents in the eyes of Google et al

**Comment by henrywright** [comment]
@artemgurzhii would that stop access to /test.html? To avoid the duplicate content I'd need /test to be accessible only.

**Comment by pathawks** [comment]
If your only concern is SEO duplicate content stuffs, just specify a canonical URL :+1:

**Comment by henrywright** [comment]
The proper solution here would be for Jekyll to return a 404 when test.html is requested.

**Comment by envygeeks** [comment]
@henrywright Jekyll does not serve your content, if you are using Github then it's Github pages that does, if you are using your own server then Nginx/Apache (or otherwise) does.  If you are using Webrick through Jekyll, we don't support that because it's not production ready, it's meant for development so that's probably a WONTFIX.

In the end, Jekyll does not serve content, it merely builds it, how you serve it is up to you and the server that you are using to host that content that Jekyll generates.

**Comment by henrywright** [comment]
Thanks for the info @envygeeks, I guess this is a GitHub Pages issue then?

**Comment by envygeeks** [comment]
@henrywright yessum.  You would need to email support@github.com and ask them to fix the problem there.  However, as @pathawks said, Google allows canonical URL's to solve that problem for services like Github, along with also being able to address it directly in webmaster tools.

**Comment by henrywright** [comment]
Thanks, I'll email them and also set the canonical as @pathawks suggested.
