### ISSUE TITLE
Make Template engines configurable.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4809]
Lets encapsulate our template engine so that users can implement their own engines via plugins, making it super easy for people to have ERB, Handlebars or whatever they want.

**Comment by parkr** [comment]
This is a great idea. We are using `to_liquid` in a number of places, and expect our Drops to be accessed via `#[]`. So I guess as long as we document that this is the way to access information or that they'll have to transform the input before using their own engine. Would this be a hook? Or would this be something like a `Converter` where you'd have:

```ruby
module Jekyll
  class ERBRenderer < Renderer

    # Public: Renders the content of the document into document.output
    # 
    # document - a Jekyll::Document, or Jekyll::Page
    # payload - a Jekyll::UnifiedDrop
    # layouts - an Array of Jekyll::Layout instances registered for this document's site
    #
    # Returns nothing. Output (with layout) is rendered into document.output
    def render(document, payload, layouts)
      document.output = ERB.new(document.content).result(payload)
      render_layouts(document, payload, layouts)
    end

    def render_layouts(document, payload, layouts)
      return unless document.data["layout"]
      # recursively apply layouts...
    end
  end
end
```

We could even let them deal with layouts entirely like above by just passing in the layouts.
