### ISSUE TITLE
Empty site.baseurl resulted in `Liquid Exception: bad argument`

### ISSUE THREAD

**Issue by ickc** [jekyll/jekyll#4810]
It wasn't like this until I upgraded to jekyll 3.0.3.

In my config:

```yaml
baseurl: #place folder name if site is served in subfolder
```

In `_includes/head.html`:

```html
...{{ site.baseurl | replace: '//', '/' }}...
```

Then running `bundle exec jekyll serve` would resulted in

```bash
Liquid Exception: bad argument (expected URI object or URI string) in _includes/head.html, included in _layouts/index.html
jekyll 3.0.3 | Error:  bad argument (expected URI object or URI string)
```

If I removed the baseurl in the config. Then everything is fine. Exactly the same config would result in no error before I upgrade. I forgot the previous Jekyll version though, but I'm sure it is at least 3.0.0.

Thanks.

**Comment by parkr** [comment]
This is an upstream bug with [Liquid](https://github.com/Shopify/liquid/). It should be able to handle `nil` via a `#to_s` call but it can't. Workaround at the moment is to do `baseurl: ""`.

```ruby
~$ irb -ryaml
>> YAML.load("baseurl: ")
=> {"baseurl"=>nil}
>> YAML.load("baseurl: ''")
=> {"baseurl"=>""}
```

**Comment by ickc** [comment]
Thanks. The workaround I currently used is to comment out the whole line about baseurl, such that it is not even there. This trick works.
