### ISSUE TITLE
How to create a link in HTML code that follows "permalink: pretty" syntax?

### ISSUE THREAD

**Issue by ibc** [jekyll/jekyll#4811]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.2

###### What operating system are you using?

OSX

###### What did you do?

In `_config.yaml`:

```yaml
permalink: pretty
```

This generates a `_site/PAGE_NAME/index.html` for every `PAGE_NAME.html` in my root dir. Cool.

But then it comes to write internal links within my HTML pages and, AFAIK, I need to create them manually as follows:

```html
<a href="/PAGE_NAME/">go to PAGE_NAME</a>
```

Then problem is that, if later I want to remove `permalink: pretty` then internal links will fail.

###### What do you expect?

I expect a "helper" that outputs formatted links according to Jekyll's config. This is, something as follows:

 ```html
<a href="{{ /PAGE_NAME.html }}">go to PAGE_NAME</a>
```

that would generate (if `permalink: pretty`):

```html
<a href="/PAGE_NAME/">go to PAGE_NAME</a>
```

Does something like that exist? (NOTE: I'm not using Markdown).

**Comment by plttn** [comment]
I'm not sure if it's exactly what you're looking for (and if you can use Liquid tags in however you're doing it), but the `post_url` tag handles posts at least. 

https://jekyllrb.com/docs/templates/#post-url

**Comment by DirtyF** [comment]
@ibc You want to link to a page from another page, is that it? In a navigation menu? In a posts list? In the middle of your content? The answer will vary depending the case.

**Comment by ibc** [comment]
> You want to link to a page from another page, is that it? In a navigation menu? In a posts list? In the middle of your content? The answer will vary depending the case.

Does it matter? Sorry if I miss something. I just want to place a `<a href="xxx">` link somewhere within my HTML files without having to hardcode them depending on the chosen `permalink`.

What I mean is something such as the [link_to](http://www.rubydoc.info/github/nanoc/nanoc/Nanoc%2FHelpers%2FLinkTo%3Alink_to) helper of *nanoc* (another static web generator). Such a method produces a relative link which looks in some way or another depending on how the source pages are "translated" when building the output site.

BTW I'm not using blog/posts stuff yet. But let's say I've a HTML layout that contains a footer with links to different sections of the site. But links to those sections are different depending on the chosen `permalink`, so if I change `permalink` my links will fail.

**Comment by envygeeks** [comment]
```liquid
{{ site.pages["about.html].permalink }}
```

**Comment by envygeeks** [comment]
I assume that should work, I don't remember if we group them by relative path or not.

**Comment by envygeeks** [comment]
> Does it matter?

Yes, it matters a lot, because depending on what you are doing you would have needed a loop, and depending on where you are doing it, you might have needed a differing loop.  No piece of code is truly universal.

**Comment by ibc** [comment]
@envygeeks I don't get `site.pages` working.

To be more specific, my scenario is just this:

```
index.html
about.html
_layouts/
    layout.html
```

In `_config.yaml` I set `permalink: pretty` so it generates this site:

```
_site/
    index.html
    about/
        index.html
```

The `layout.html` contains a footer as follows (in which I try to use `site.pages`):

```html
<footer>
    <a href="{{ site.pages['about.html'].permalink }}">About</a>
</footer>
```

However the resulting `href` is empty. I've also tried with `'/about.html`, without extension, etc, with same empty result. Do I miss something?

Thanks a lot.

**Comment by ibc** [comment]
NOTE: In the metadata of my `about.html` I don't set `permalink` as I expect it to become autogenerated given `permalink: pretty` in `_config.yaml`.

**Comment by parkr** [comment]
@ibc `site.pages` is an array, not a hash.

```liquid
<footer>
    {% assign about_page = site.pages | where: "relative_path", "about.html" | first %}
    <a href="{{ about_page.permalink }}">About</a>
</footer>
```

**Comment by DirtyF** [comment]
@parkr BTW will the upcoming `link`tag work with pages?

**Comment by envygeeks** [comment]
@DirtyF what upcomming link tag?

**Comment by DirtyF** [comment]
@envygeeks I was refering to https://github.com/jekyll/jekyll/pull/4624

**Comment by envygeeks** [comment]
Maybe we should go back to that pr and ask for the tag to be renamed `link_to` or something since everything is a collection it can have a much more targeted and self-explaining name? /cc @parkr

**Comment by ibc** [comment]
@parkr thanks, but it produces nothing:

```html
<footer>
    {% assign about_page = site.pages | where: "relative_path", "about.html" | first %}
    <a href="{{ about_page.permalink }}">"{{ about_page.title }}"</a>
</footer>
```

It produces:

```html
<a href="">""</a>
```

`about.html` is just:

```
---
title: ABOUT
---

<h1>About</h1>
```

Said that, I don't find in the doc which values can be given to the `where` clause below, and even if it was a valid one I consider this extremely difficult/unusable. I just cannot do that for *every* internal link within my non-blog site.

**Comment by ibc** [comment]
OK, it is not "relative_path" (which is undefined) but "path". However:

```html
{% assign about_page = site.pages | where: "path", "about.html" | first %}
<a href="{{ about_page.permalink }}">{{ about_page.title }}</a>
```

produces:

```html
<a href="">ABOUT</a>
```

This is: `about_page.permalink` has no value.

**Comment by parkr** [comment]
@ibc `permalink` would have to be a custom value. If you're looking for the URL, use `url`.

**Comment by ibc** [comment]
@parkr thanks, `page.url` is what I was looking for.

However, it is still unusable given that I must code `{% assign about_page = site.pages | where: "path", "about.html" | first %}` for **every** internal link I want to place in my HTML. I don't understand why Jekyll just focus on "blog stuff" and provides `post_url` while it does not provide a generic `page_url` or similar. I hope something is cooked in #4624 regarding this obvious need (since not all of us are building a "blog").

**Comment by parkr** [comment]
@ibc Once 3.2 comes out, you'll be able to do:

```liquid
<a href="{% link about.html %}">About</a>
```

For now, you have a fine solution. You could put your nav bar in a data file like `_data/nav.yml`:

```yaml
- about.html
- contact.html
```

then use that to produce the links dynamically:

```liquid
{% for item in site.data.nav %}
{% assign nav_page = site.pages | where: "path", item | first %}
<a href="{{ nav_page.url }}">{{ nav_page.title }}</a>
{% endfor %}
```

Easy. 😄

**Comment by ibc** [comment]
Thanks a lot.
