### ISSUE TITLE
root should be specified in _config.yml by default

### ISSUE THREAD

**Issue by aseem2625** [jekyll/jekyll#4815]
Hi,

I can see that this issue is addressed differently in previous threads, however, the path for css isn't right wrt to the root when everything is as default as created using 'jekyll new' command.

###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.3

###### What operating system are you using?
Mac OSX

###### What did you do?
New blog setup using command 'jekyll new' and everything worked fine locally but after publishing it through git, I realized my css wasn't working. I fixed it by specifying the root in _config.yml as 

    root: /

Please FIX this in the subsequent version because defaults of jekyll should work right out of the box. Because specifying root works both in local and after publishing in git

###### What did you expect to see?
CSS should be working

###### What did you see instead?
CSS wasn't working on publishing

**Comment by DirtyF** [comment]
Could you share some code, because CSS works fine by default when creating a new site.

**Comment by aseem2625** [comment]
Hi @DirtyF 

There need not be any code since I just set up jekyll and ran jekyll serve which worked perfectly fine on local but when I hosted this default jekyll project on github, the CSS didn't work at all. I am not first person facing this problem. I checked internet and got that many people have faced the same issue in the past.

And as I wrote, to fix I had to make the root as root: / in _config.yml
:)

**Comment by parkr** [comment]
`root: /` doesn't exist in the default theme. If you're setting up your site as a user site (i.e. `USERNAME/USERNAME.github.io`), you'd have:

```yml
baseurl: /
url: http://USERNAME.github.io
```

and as a project site (i.e. `USERNAME/PROJECT`):

```yml
baseurl: /PROJECT
url: http://USERNAME.github.io
```

😄

**Comment by aseem2625** [comment]
@parkr 
My test blog url is http://aseem2625.github.io/blogtest/

Yes ```root:/``` doesn't exist but adding it makes my things work

but as you told, (removed root: /) and putting 
   
    baseurl: /blogtest and 
    url: http:aseem2625.github.io doesn't work

and neither putting 
 
    baseurl: /and 
    url: http:aseem2625.github.io works

Also, I didn't understand what difference you meant by user site and project site.

**Comment by DirtyF** [comment]
@aseem2625 It's explained here: https://help.github.com/articles/user-organization-and-project-pages/

**Comment by aseem2625** [comment]
@DirtyF 
@parkr 

Strangely, I tried with multiple combinations and it worked with what parkr you told.

baseurl: "/blogtest"
url: "http://aseem2625.github.io"

May be I forgot to remove the cache.

Thanks. Problem resolved and nothing wrong is default setup for jekyll, just have to fill the correct baseurl and url
