### ISSUE TITLE
Auto-regeneration is broken

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#4821]
###### What version of Jekyll are you using (`jekyll -v`)?

3.0.4 (github-pages v73)

###### What operating system are you using?

Mac OS X 10.11

###### What did you do?

Everything was working fine, then I ran `bundle update` and upgraded to latest `github-pages` version. Now there is a deprecation message when I launch `jekyll serve`. Even with the `--watch` option, auto-generation is disabled.

```
bundle exec jekyll serve
Configuration file: /Users/frank/code/aperoweb-toulouse/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
            Source: /Users/frank/code/aperoweb-toulouse
       Destination: /Users/frank/code/aperoweb-toulouse/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 1.353 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Configuration file: /Users/frank/code/aperoweb-toulouse/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

###### What did you expect to see?

auto-regeneration by default.

###### What did you see instead?

No auto-regeneration at all.

**Comment by m4dc4p** [comment]
I'm seeing the same behavior (just install jekyll today, following GitHub's instructions at https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll).

**Comment by parkr** [comment]
If you remove `github-pages` from `:jekyll_plugins` group, does it fix itself? Seems to be caused by https://github.com/github/pages-gem/pull/276

/cc @jekyll/gh-pages

**Comment by parkr** [comment]
Please file this on the github/pages-gem repo. 😄
