### ISSUE TITLE
`--watch` argument is ignored

### ISSUE THREAD

**Issue by huonw** [jekyll/jekyll#4823]
###### What version of Jekyll are you using (`jekyll -v`)?

`jekyll 3.0.4`

###### What operating system are you using?

Ubuntu 15.10

###### What did you do?

```
$ jekyll new mysite
New jekyll site installed in .../mysite. 
$ cd mysite
$ jekyll serve --watch
Configuration file: .../mysite/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
            Source: .../mysite
       Destination: .../mysite/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.202 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Configuration file: .../mysite/_config.yml
       Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

And making modifications to any files (e.g. `index.html`) indeed doesn't auto-regenerate.

###### What did you expect to see?

I expected `Auto-regeneration: enabled` in the output of `serve` and the site to be regenerated when files are changed.

###### What did you see instead?

`disabled` and no auto-regeneration.

**Comment by renshuki** [comment]
Same problem here.

**Comment by DirtyF** [comment]
duplicates #4821, issue open on github-pages https://github.com/github/pages-gem/issues/280

**Comment by huonw** [comment]
Ah, great, thanks for the heads up!
