### ISSUE TITLE
site.pages variable contains data related to main.scss

### ISSUE THREAD

**Issue by henrywright** [jekyll/jekyll#4824]
###### What version of Jekyll are you using (`jekyll -v`)?

3

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I used `{{ site.pages }}` in a test.html file to see what the `site.pages` variable contained.

###### What did you expect to see?

I expected to see data relating to my site's `.html` and `.md` files only.

###### What did you see instead?

I saw data related to my site's `.html` files but I also get data relating to my site's `css/main.scss` file. To me, it doesn't make sense for `site.pages` to hold `.scss` file data.

**Comment by parkr** [comment]
@henrywright `site.pages` is any non-collection document that has the YAML front matter. This is intended behaviour. If you're looking for just HTML pages, look for permalinks that end in `.html` or `/` and you'll be good to go. 👍
