### ISSUE TITLE
Accessing data related to a `pages` collection

### ISSUE THREAD

**Issue by henrywright** [jekyll/jekyll#4825]
###### What version of Jekyll are you using (`jekyll -v`)?

3

###### What operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Created a new collection called `pages` (see [this comment](https://github.com/jekyll/jekyll/issues/4802#issuecomment-211593302)):

```
collections:
  pages:
    output: true
```

Folder name: `_pages`

###### What did you expect to see?

I expected to be able to access my page's data with `site.pages` just as you would do with collections such as `site.albums` or `site.events`.

###### What did you see instead?

`site.pages` doesn't hold data related to my collection. It holds data related to actual "pages" (kind of like `site.posts`).

**Comment by envygeeks** [comment]
`site.pages` is a reserved (as you already found out.)  I don't know what we could do in this situation.

**Comment by henrywright** [comment]
@envygeeks I guess I could use another name for the collection? Maybe mention collection names that aren't recommended in the docs?

**Comment by parkr** [comment]
`site.pages` will be reserved for the foreseeable future (it'd be a weird change to allow it to be overwritten and cause an increase in support tickets). You can access it via the `site.collections` array. 😄 

Feel free to submit a PR to change `site/_docs/collections.md` to describe potential conflicts with "reserved" names.
