### ISSUE TITLE
Auto-regeneration not being turned on by --watch option

### ISSUE THREAD

**Issue by nwshane** [jekyll/jekyll#4828]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.0.4

###### What operating system are you using?

OS X 10.11.1

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I ran the command `bundle exec jekyll serve --watch`

###### What did you expect to see?

I expected the server to start up with auto-regeneration enabled.

###### What did you see instead?

Auto-regeneration is disabled and the site is not regenerated when I make changes.

```
nathan-shanes-macbook-2:nathan_shane_site django09$ bundle exec jekyll serve --watch
Configuration file: /Users/django09/Dropbox/Programming/projects/nathan_shane_site/_config.yml
Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
Source: /Users/django09/Dropbox/Programming/projects/nathan_shane_site
Destination: /Users/django09/Dropbox/Programming/projects/nathan_shane_site/_site
Incremental build: disabled. Enable with --incremental
Generating... 
done in 0.265 seconds.
Auto-regeneration: disabled. Use --watch to enable.
Configuration file: /Users/django09/Dropbox/Programming/projects/nathan_shane_site/_config.yml
Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
Server address: http://127.0.0.1:4000/
Server running... press ctrl-c to stop.
```

**Comment by envygeeks** [comment]
Please update your github-pages gem and see: https://github.com/github/pages-gem/issues/280
