### ISSUE TITLE
date is mis-interpreted

### ISSUE THREAD

**Issue by JazzMaster** [jekyll/jekyll#4829]
###### What version of Jekyll are you using (`jekyll -v`)?
3.0.1
(just updated)
###### What operating system are you using?
ubuntu16-x64

### issue
parse error on date:
(needs to allow for some date flexibility)
'date:' is interpreted in YAML header but 'Date:' is not.
Either allow both or throw error that Date(as proper CamelCase) is unspecified, or try to parse date from filename.

**Comment by envygeeks** [comment]
I find your issue confusing, please provide examples.

**Comment by parkr** [comment]
@JazzMaster If you want your date to be interpreted from the YAML front matter, it must be `date`, not `Date` or `DATE`. See here for documentation: https://jekyllrb.com/docs/frontmatter/#predefined-variables-for-posts
