### ISSUE TITLE
--watch command ignored

### ISSUE THREAD

**Issue by klomontes** [jekyll/jekyll#4830]
###### What version of Jekyll are you using (`jekyll -v`)?
3.0.4

###### What operating system are you using?
OS X El Capitan v10.11.4

###### What did you do?
I have updated Jekyll to version 3.0.4 and when I try to run it with `bundle exec jekyll s` I get this message in the console:
`Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.`

When I try to run it with `bundle exec jekyll s --watch` the watch command is ignored.

Here is my gem list:
```
activesupport (4.2.6, 4.2.5.1, 4.2.5)
addressable (2.4.0, 2.3.8)
autoprefixer-rails (6.3.1)
bigdecimal (1.2.6)
blankslate (2.1.2.4)
bundler (1.11.2)
classifier-reborn (2.0.3)
coffee-script (2.4.1)
coffee-script-source (1.10.0, 1.9.1.1)
colorator (0.1)
colored (1.2)
concurrent-ruby (1.0.0)
configure-s3-website (1.7.1)
deep_merge (1.0.0)
dotenv (1.0.2)
ethon (0.8.1, 0.8.0)
execjs (2.6.0)
faraday (0.9.2)
fast-stemmer (1.0.2)
fastimage (1.8.1)
ffi (1.9.10)
gemoji (2.1.0)
github-pages (75)
github-pages-health-check (1.1.0)
html-pipeline (2.4.0)
html-proofer (2.6.4, 2.6.1, 2.5.1)
i18n (0.7.0)
io-console (0.4.3)
jekyll (3.1.1, 3.1.0, 3.0.4, 3.0.1)
jekyll-assets (2.1.2)
jekyll-coffeescript (1.0.1)
jekyll-feed (0.5.1)
jekyll-gist (1.4.0, 1.3.5)
jekyll-github-metadata (1.11.1)
jekyll-mentions (1.1.2)
jekyll-paginate (1.1.0)
jekyll-redirect-from (0.10.0, 0.9.1, 0.9.0)
jekyll-sass-converter (1.4.0, 1.3.0)
jekyll-seo-tag (1.3.3)
jekyll-sitemap (0.10.0, 0.9.0)
jekyll-textile-converter (0.1.0)
jekyll-watch (1.3.1, 1.3.0)
jemoji (0.6.2)
json (1.8.3, 1.8.1)
kramdown (1.10.0, 1.9.0)
liquid (3.0.6, 2.6.3)
listen (3.0.6, 3.0.5, 3.0.3)
mercenary (0.3.6, 0.3.5)
mini_portile (0.6.2)
mini_portile2 (2.0.0)
minitest (5.8.4, 5.8.3, 5.4.3)
multipart-post (2.0.0)
net-dns (0.8.0)
nokogiri (1.6.7.2, 1.6.7.1, 1.6.6.2)
octokit (4.3.0)
parallel (1.6.1)
parslet (1.5.0)
posix-spawn (0.3.11)
power_assert (0.2.2)
psych (2.0.8)
public_suffix (1.5.3)
pygments.rb (0.6.3)
rack (1.6.4)
rake (10.4.2)
rb-fsevent (0.9.7, 0.9.6)
rb-inotify (0.9.7, 0.9.5)
rdiscount (2.1.8)
rdoc (4.2.0)
redcarpet (3.3.4, 3.3.3)
RedCloth (4.2.9)
rouge (1.10.1)
s3_website (2.12.2)
safe_yaml (1.0.4)
sass (3.4.22, 3.4.21, 3.4.20, 3.4.19)
sawyer (0.7.0)
sprockets (3.5.2)
sprockets-helpers (1.2.1)
terminal-table (1.5.2)
test-unit (3.0.8)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.2)
toml (0.1.2)
typhoeus (0.8.0)
tzinfo (1.2.2)
yajl-ruby (1.2.1)
yell (2.0.5)
```

Am I missing something?

**Comment by alexpls** [comment]
I'm having this issue too. Same OS as you (El Capitan 10.11.4), and same Jekyll version (3.0.4, installed via the `github-pages` gem).

**Comment by anatskiy** [comment]
Me too (El Capitan 10.11.4).

**Comment by alexpls** [comment]
A temporary fix for me was downgrading my `github-pages` gem to `v72` by changing my Gemfile to this:

```
gem 'github-pages', '72'
```

And then running `$ bundle update`.

It looks like v73 of the github-pages gem bumped the Jekyll version to 3.0.4, which in turn seems to break the `--watch` behaviour.

**Comment by DirtyF** [comment]
Qs @alexpls said, for now you go stick to v72,this is a pages-gam issue, still not resolved with version 75: https://github.com/github/pages-gem/issues/280

**Comment by toybreaker** [comment]
@alexpls fix (downgrading my github-pages gem to v72 by changing my Gemfile) worked for me. (same sys setup)

**Comment by klomontes** [comment]
Thanks @alexpls for the workaround and @DirtyF for the info. Closing this.

**Comment by kevinSuttle** [comment]
Is this still a workaround, considering 

1. this bug is still present
2. the `github-pages` gem is now at version `139`?

**Comment by ashmaroli** [comment]
@kevinSuttle Are you using `jekyll-admin` plugin? That plugin disables `--watch` internally. Commenting the plugin out should help if yes..

**Comment by kevinSuttle** [comment]
@ashmaroli GAH! That fixed it. Had no idea. Thanks!

**Comment by ashmaroli** [comment]
Related question on [StackOverflow](https://stackoverflow.com/questions/43559969/jekyll-auto-regeneration-not-working-even-with-watch-used/43560078?noredirect=1#comment74171132_43560078)
