### ISSUE TITLE
Error installing Jekyll: listen requires Ruby version 2.2.

### ISSUE THREAD

**Issue by San7hos** [jekyll/jekyll#4835]
###### What version of Jekyll are you using (`jekyll -v`)?

None. I have not been able to install Jekyll yet.

###### What operating system are you using?

OS X 10.11.4

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I ran `sudo gem install jekyll`. When it did not work, I updated gems and I also tried `sudo gem install jekyll -n /usr/local/bin`. However, the result is still the same.

###### What did you expect to see?

Installed Jekyll.

###### What did you see instead?

> ERROR:  Error installing jekyll:
> 	listen requires Ruby version ~> 2.2.

###### Notes

Ruby version: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
I understand that this might be the issue. I am not used to using Ruby and I am not sure whether this is a problem of Jekyll or whether the correct approach would be to install rbevn/rvm and try to install jekyll with a newer ruby version.

**Comment by envygeeks** [comment]
This ticket belongs at https://github.com/jekyll/jekyll-watch

**Comment by envygeeks** [comment]
See jekyll/jekyll-watch#37

**Comment by San7hos** [comment]
I see, thank you. What do you suggest if I want to use jekyll now on os x? Installing newer ruby version with some of the ruby version managers?

**Comment by envygeeks** [comment]
@San7hos unfortunately that's all you can do for now, I'll be sending a pull request and pinging @parkr to merge it which will resolve it as soon as he releases a new version but if you wish to have it right now instead of tomorrow sometime you'll have to use something like RVM or Rbenv to get 2.2+.

**Comment by San7hos** [comment]
@envygeeks I think I can wait until tomorrow since it is a matter of personal business. Thanks again for a quick help.
