### ISSUE TITLE
"no implicit conversion of nil into String" Error occured  when  I install jekyll

### ISSUE THREAD

**Issue by Bluelich** [jekyll/jekyll#4836]
```
 ~ gem install -n /usr/local/bin jekyll
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
```
###### What operating system are you using?
```
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65
```

```
Homebrew 0.9.9 (git revision 663f5; last commit 2016-04-24)
Homebrew/homebrew-core (git revision 8a15; last commit 2016-04-24) 
```

```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```

```
gem 2.5.1
```

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
only run command
```
gem install -n /usr/local/bin jekyll
```
###### What did you expect to see?
Install  jekyll success

**Comment by Bluelich** [comment]
I found that,this error is caused by ruby.
Sorry!

**Comment by bgold0** [comment]
How did you fix this?

**Comment by jcalifa** [comment]
+1 I'm getting the same error

**Comment by pathawks** [comment]
This is a very old issue. If you are currently having a similar problem, it is likely unrelated. Please open a new issue and provide as much information as you can about how to reproduce the problem.
