### ISSUE TITLE
Deployment doesn't support apex domains?

### ISSUE THREAD

**Issue by ChaosCat** [jekyll/jekyll#4837]
###### What version of Jekyll are you using (`jekyll -v`)?
3.1.2.

###### What operating system are you using?
Ubuntu 15.10.

###### What did you do?
Deployed the Jekyll _site folder content into my domain both after trying to setting site URL value in the `_config` file to my domain with www and then to my apex domain. (currently I am using the apex domain version)

###### What did you expect to see?
A working generated site on my apex domain.

###### What did you see instead?
A messed up site (showing only the header.html file as if you opened it before building) and a fully functional site at the www,[my domain]

**Comment by parkr** [comment]
Hey @ChaosCat, 

If you have your APEX domain setup such that it serves from the directory you uploaded your files to, then the initial page load should look fine when you go to your apex domain.

For links, I'd recommend setting `url` in your `_config.yml` to the APEX domain with the protocol (e.g. `http://example.com`) and the `baseurl` to `""`. Then run `bundle exec jekyll build` like normal and upload the contents of `_site`.

That should fix you up. Cheers!
