### ISSUE TITLE
Jekyll version `3.1.3` does not automatically get `json` dependency

### ISSUE THREAD

**Issue by uvsmtid** [jekyll/jekyll#4838]
###### What version of Jekyll are you using (`jekyll -v`)?

Version `3.1.3` - see output below.

###### What operating system are you using?

Fedora 23 x86_64:
```
uname -a
Linux projector 4.4.7-300.fc23.x86_64 #1 SMP Wed Apr 13 02:52:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

The script and output is included verbatim from this comment to issue:
https://github.com/mmistakes/hpstr-jekyll-theme/pull/147#issuecomment-214310144

I put commands in `try.sh` script to capture the whole output at once:
```
#/bin/sh
set -e
set -v
set -x
test ! -e test-site
jekyll new test-site
cd test-site
bundle init
echo 'gem "jekyll"' >> Gemfile
cat Gemfile
bundle install
bundle update
bundle exec jekyll build
```

Output :
```
set -x # debut output
test ! -e test-site
++ test '!' -e test-site
jekyll new test-site
++ jekyll new test-site
WARN: Unresolved specs during Gem::Specification.reset:
      listen (~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
New jekyll site installed in /mnt/btrfs/home/_/uvsmtid/Works/test-site/test-site. 
cd test-site
++ cd test-site
bundle init
++ bundle init
Writing new Gemfile to /mnt/btrfs/home/_/uvsmtid/Works/test-site/test-site/Gemfile
echo 'gem "jekyll"' >> Gemfile
++ echo 'gem "jekyll"'
cat Gemfile
++ cat Gemfile
# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "jekyll"
bundle install
++ bundle install
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using colorator 0.1
Using ffi 1.9.10
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.10.0
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.10.1
Using safe_yaml 1.0.4
Using bundler 1.11.2
Using rb-inotify 0.9.7
Using jekyll-sass-converter 1.4.0
Using listen 3.1.1
Using jekyll-watch 1.3.1
Using jekyll 3.1.3
Bundle complete! 1 Gemfile dependency, 15 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
bundle update
++ bundle update
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using colorator 0.1
Using ffi 1.9.10
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.10.0
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.10.1
Using safe_yaml 1.0.4
Using bundler 1.11.2
Using rb-inotify 0.9.7
Using jekyll-sass-converter 1.4.0
Using listen 3.1.1
Using jekyll-watch 1.3.1
Using jekyll 3.1.3
Bundle updated!
bundle exec jekyll build
++ bundle exec jekyll build
Configuration file: /mnt/btrfs/home/_/uvsmtid/Works/test-site/test-site/_config.yml
            Source: /mnt/btrfs/home/_/uvsmtid/Works/test-site/test-site
       Destination: /mnt/btrfs/home/_/uvsmtid/Works/test-site/test-site/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/filters.rb:2:in `require': cannot load such file -- json (LoadError)
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/filters.rb:2:in `<top (required)>'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/renderer.rb:53:in `run'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/site.rb:171:in `block (2 levels) in render'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/site.rb:169:in `each'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/site.rb:169:in `block in render'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/site.rb:168:in `each'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/site.rb:168:in `render'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/site.rb:59:in `process'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/command.rb:26:in `process_site'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/commands/build.rb:60:in `build'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/commands/build.rb:33:in `process'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
        from /home/uvsmtid/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `call'
        from /home/uvsmtid/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /home/uvsmtid/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /home/uvsmtid/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /home/uvsmtid/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /home/uvsmtid/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /home/uvsmtid/.gem/ruby/gems/jekyll-3.1.3/bin/jekyll:13:in `<top (required)>'
        from /home/uvsmtid/bin/jekyll:23:in `load'
        from /home/uvsmtid/bin/jekyll:23:in `<main>'
```

###### What did you expect to see?

I expected that `jekyll` could pull `json` dependency automatically and did not fail on `require 'json'` line.

###### What did you see instead?

I saw the stack trace instead - see the output above.

**Comment by parkr** [comment]
@uvsmtid Hey! [`json` is a part of the Ruby stdlib](http://ruby-doc.org/stdlib-2.0.0/libdoc/json/rdoc/JSON.html). What version of Ruby are you using?

**Comment by uvsmtid** [comment]
The `ruby` package itself on my Fedora 23 is `2.2.4`:

```
rpm -qi ruby
Name        : ruby
Version     : 2.2.4
Release     : 47.fc23

ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
```

But I don't think it is simply `ruby` version it is related `ruby` used in [`bundle`][1] command.

If I create simple file with only single line `require 'json'`, I can easily execute it without problem:

```
cat qwer.rb
require 'json'
ruby qwer.rb
```

I guess `bundle` creates pristine Ruby environment without any gems of any versions (and rely on explicit specification of dependency graph). I don't know commands to execute this script under `bundle` to demonstrate that it fails without explicit dependency on `json`. But one of the [`hpstr-jekyll-theme`][2] I tried to use hit this problem. To avoid these issues in any other cases, I guess it's better to explicitly set (somewhere) that `jekyll` requires `json`.

[1]: http://bundler.io/
[2]: https://github.com/mmistakes/hpstr-jekyll-theme/pull/147

**Comment by envygeeks** [comment]
@uvsmtid this is a problem for Fedoras tracker unfortunately because Bundler does include system gems (unless you didn't install ruby-json -- which again makes this an downstream problem because it should have that as a hard dependency in system Ruby.)  Yes, we could fix this for you by adding JSON but the fact of the matter will remain that it's Fedora that broke in some way (unless you broke Fedora in some way.)

**Comment by parkr** [comment]
Closing as it's a system problem. I don't envision us adding the `json` gem as a dependency anytime soon, as this is easily fixed by installing Ruby through any Ruby Version Manager.

**Comment by uvsmtid** [comment]
No problem. At least some awareness was raised.

One note - I hit it on 3 Fedora machines. They all have `rubygem-json` as RPM installed and I also installed `gem install json` successfully as regular user while troubleshooting this problem. If it's broken (for `bundle`), it is likely to be within system itself - either Fedora or `bundle`. Otherwise I must be gifted to screw things up consistently (which is also plausible taking my `ruby` experience into account).

**Comment by envygeeks** [comment]
@uvsmtid based on what you said, it's probably not you, I'd have to search again, but years ago, I remember there being this *exact* problem on Fedora 17 or 18.  For some reason bundler couldn't find the system gems that RPM brought in, I thought they had fixed that, but it might have regressed.  It's this reason why Debian changed the way they did Ruby Gems and Ruby entirely over the last few years, I think (I could be wrong,) Fedora is on that same track to fix their bad system Ruby too.

**Comment by mmaechler** [comment]
We are seeing this same problem on Fedora 22 -- which is pretty well curated (for our Math department of several 100 client machines; desktops and compute servers).

Notably even if I manually do
```
 gem install json
```
which does nicely install a new version of `json` in my  `~/.gem/ruby/gems`
(and later find that `json` is indeed installed in the system-wide standard ruby installation),
```
bundle exec serve
```
still quickly produces the error (below), so I would agree with @uvsmtid  that it is somehow the fault of
jekyll's own  `bundle` script, but not of ruby itself....  but then I basically know nothing about ruby
(I do speak 'R', 'bash', 'C', emacs-lisp and other lisps, perl, fortran..)  but not yet ruby.  I'd be very grateful for help / hand-holding.  Here's  the "log" with the error  ("MM" are my initials; `/u/maechler/` is my $HOME)
```
MM@lynne:MM-s-jekyll-site$ bundle show json
Could not find gem 'json'.
MM@lynne:MM-s-jekyll-site$ which bundle
/u/maechler/bin/bundle
MM@lynne:MM-s-jekyll-site$ bundle exec jekyll serve
bundler: failed to load command: jekyll (/sfs/u/maechler/bin/jekyll)
LoadError: cannot load such file -- json
  /u/maechler/.gem/ruby/gems/jekyll-3.2.1/lib/jekyll/filters.rb:2:in `require'
  /u/maechler/.gem/ruby/gems/jekyll-3.2.1/lib/jekyll/filters.rb:2:in `<top (required)>'
  /u/maechler/.gem/ruby/gems/jekyll-3.2.1/lib/jekyll.rb:82:in `require'
  /u/maechler/.gem/ruby/gems/jekyll-3.2.1/lib/jekyll.rb:82:in `<module:Jekyll>'
  /u/maechler/.gem/ruby/gems/jekyll-3.2.1/lib/jekyll.rb:36:in `<top (required)>'
  /u/maechler/.gem/ruby/gems/jekyll-3.2.1/exe/jekyll:6:in `require'
  /u/maechler/.gem/ruby/gems/jekyll-3.2.1/exe/jekyll:6:in `<top (required)>'
  /sfs/u/maechler/bin/jekyll:23:in `load'
  /sfs/u/maechler/bin/jekyll:23:in `<top (required)>'
MM@lynne:MM-s-jekyll-site$ 
```

**Comment by envygeeks** [comment]
Add JSON to your Gemfile, this is not a Jekyll problem, this is an downstream problem with your Ruby and or possibly RubyGem's and to a lesser extent (though I don't think it is) Bundler which is not Jekyll's it's a major Ruby library/application.

**Comment by mmaechler** [comment]
Thank you @envygeeks . So let me believe you (*)  How can I 

> Add JSON to your Gemfile

i.e., where is "my Gemfile" and how can I add "JSON" (as opposed to "json" ?) there?   
Yes, I did say that I don't speak ruby yet. ;-)

--
(*) that it is not a Jekyll problem;  still funny to me that you seem to "happily accept" that your installation instructions for Jekyll fail on a pretty important platform such as Fedora.. , or do I misunderstand?

**Comment by mmaechler** [comment]
Ok, I found a `Gemfile`  in the newly created directory,
and reading its comments,  I found and guessed  and ended up adding
```
```
at the very end of `Gemfile`  , and indeed then, also  
```
bundle exec jekyll serve
```
did work nicely: I can point my browser to  `http://127.0.0.1:4000/` and see the newly created dummy web page.   Hooray! ;-)

**Comment by jcubic** [comment]
I had error:
```
  Liquid Exception: Did not recognize your adapter specification (cannot load such file -- json/ext). in /home/kuba/projects/jcubic/blog/repo/_posts/2014-08-06-funkcje-w-javascript.markdown                                                    
jekyll 3.5.2 | Error:  Did not recognize your adapter specification (cannot load such file -- json/ext).
```

adding:
```
gem 'json', '~> 2.0'
```
to Gemfile fixed the issue.
