### ISSUE TITLE
Deprecation: Auto-regeneration can no longer be set from your configuration file(s).

### ISSUE THREAD

**Issue by Izhaki** [jekyll/jekyll#4840]
###### What version of Jekyll are you using?

jekyll 3.0.4

###### What operating system are you using?

OS X 10.10.5

###### What did you do?

Followed the instructions on [GitHub](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/).

###### What did you expect to see?

When running:

    bundle exec jekyll serve

I expected to see jekyll running properly, with auto-generation enabled.

###### What did you see instead?

    Configuration file: /Volumes/Data/Development/Web/izhaki.github.io/_config.yml
           Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
                Source: /Volumes/Data/Development/Web/izhaki.github.io
           Destination: /Volumes/Data/Development/Web/izhaki.github.io/_site
     Incremental build: disabled. Enable with --incremental
          Generating... 
                        done in 0.502 seconds.
     Auto-regeneration: disabled. Use --watch to enable.
    Configuration file: /Volumes/Data/Development/Web/izhaki.github.io/_config.yml
           Deprecation: Auto-regeneration can no longer be set from your configuration file(s). Use the --[no-]watch/-w command-line option instead.
        Server address: http://127.0.0.1:4000/
      Server running... press ctrl-c to stop.

_config.yml:

    # Welcome to Jekyll!
    #
    # This config file is meant for settings that affect your whole blog, values
    # which you are expected to set up once and rarely need to edit after that.
    # For technical reasons, this file is *NOT* reloaded automatically when you use
    # 'jekyll serve'. If you change this file, please restart the server process.
    
    # Site settings
    title: Your awesome title
    email: your-email@domain.com
    description: > # this means to ignore newlines until "baseurl:"
      Write an awesome description for your new site here. You can edit this
      line in _config.yml. It will appear in your document head meta (for
      Google search results) and in your feed.xml site description.
    baseurl: "" # the subpath of your site, e.g. /blog
    url: "http://yourdomain.com" # the base hostname & protocol for your site
    twitter_username: jekyllrb
    github_username:  jekyll
    
    # Build settings
    markdown: kramdown

Running:

    bundle exec jekyll serve -w
    bundle exec jekyll serve --watch

Doesn't work (throws the same error).

**Comment by envygeeks** [comment]
This is a known issue, please see #4831 and use search, thanks!

**Comment by Izhaki** [comment]
Thanks @envygeeks.

Shocking, but I have spent the last 2 hours searching, yet the link to the issue you've provided never came up in the top 30 results. Odd.
