### ISSUE TITLE
layouts_dir doesn't accept an array of folder paths

### ISSUE THREAD

**Issue by lisunshiny** [jekyll/jekyll#4842]
###### What version of Jekyll are you using (`jekyll -v`)?

3.1.2

###### What operating system are you using?

OS X El Capitan

###### What did you do?

Not really a bug, more of a feature request -- I see it here: https://github.com/jekyll/jekyll/blob/master/bin/jekyll#L22. We're using symlinks to maintain 2 very similar Jekyll sites with a lot of shared files, and it would be super useful (similar to `plugins_dir`) to be able to pass in an array of folder paths instead of just a single string to `layouts_dir` so that we can put site-specific plugins and shared plugins in different folders, and then put `layouts_dir: ["_layouts", "_layouts/shared"]` in `config.yml`. Right now we can only pass in a string of a single directory.

**Comment by parkr** [comment]
Hey @lisunshiny! 

We have actually been talking about this quite recently. We recently merged support for gem-based themes ( #4595 ), which allows users to share layouts, includes, and sass all in a way that is standard for the ecosystem. We use the same method for plugins. I explained why I didn't like the idea of multiple layouts in a comment (https://github.com/jekyll/jekyll/pull/4610#issuecomment-200419940).

Check out the comment I left and gem-based themes. I think it will solve the problem of shared layouts that you're indicating. 😄 Cheers!
