### ISSUE TITLE
Jekyll doesn't rebuild after one change

### ISSUE THREAD

**Issue by Lamans** [jekyll/jekyll#4845]
###### What version of Jekyll are you using (`jekyll -v`)?
Jekyll 3.1.3.

###### What operating system are you using?
OSX El Capitan

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

$ jekyll build --watch --incremental

When Jekyll is running, I create the first page and so I add some posts, creating the following structure:

/ --> jekyll_path
.... category1/ 
........... index.html
........... _posts/
.................. post1.md 
.................. post2.md
.................. post3.md
.... _sites/

Jekyll with --watch enable initializes to populate the _sites/ directory correctly .

But, if I modify the content of post1.md or delete post1.md, Jekyll's output:

Regenerating: 1 file(s) changed etc etc........

Note: category1/index.html print the content of every *.md in category1/_posts

###### What did you expect to see?

HTML page in _site/category1 modified, that is the html page without the content the post1.md... 

###### What did you see instead?
 the HTML page in _site/category1 directory remained unchanged. Jekyll didn't overwrite the files with the changes.

**Comment by envygeeks** [comment]
Please see #4830, this is a known issue, please use the search, thanks!

**Comment by Lamans** [comment]
The issue #4830 doesn't resolve my question

**Comment by parkr** [comment]
Oh, you're using `--incremental`. This is a limitation of the way incremental regeneration works at the moment. We aren't able to build a full dependency tree so if you change post1.md, only its output file will update, not `index.html` or anything that references it. /cc @alfredxing
