### ISSUE TITLE
more than one blog on one site

### ISSUE THREAD

**Issue by S0nicY0uth** [jekyll/jekyll#4864]
jekyll 3.1.3

OSX 10.11.2

I am trying to run two blogs. One for News, the other for upcoming events.

I run {% for post in site.post %} and that works just fine with one blog serving from the _posts folder but I can't work out how to run an additional blog and separate my posts. 

I created a folder called events and tried to run {% for post in site.events.post %} but this didn't return any of the blogs.

**Comment by budparr** [comment]
This repos is for reporting bugs. You'll have better luck asking this over at https://talk.jekyllrb.com/

**Comment by S0nicY0uth** [comment]
Apologies. As you can see I'm new to this. 

Thanks.

**Comment by opattison** [comment]
Thread is here: https://talk.jekyllrb.com/t/how-do-i-create-a-multi-blog-site/2314

Issue solved?

**Comment by parkr** [comment]
❤️
