### ISSUE TITLE
Build Warning: Layout 'page' requested in about.md does not exist .

### ISSUE THREAD

**Issue by cyoncan** [jekyll/jekyll#4866]
###### What version of Jekyll are you using (`jekyll -v`)?
`Microsoft@DESKTOP-6LQRH85 MINGW64 ~
$ jekyll -v
jekyll 3.1.3
`

###### What operating system are you using?
**win10**

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
_`Microsoft@DESKTOP-6LQRH85_ MINGW64 /d/GitHub/cyoncan/cyoncan.github.io  (master)
$ jekyll serve
`

###### What did you expect to see?
_`Microsoft@DESKTOP-6LQRH85_ MINGW64 /d/GitHub/cyoncan/cyoncan.github.io  (master)
$ jekyll serve
Configuration file: D:/GitHub/cyoncan/cyoncan.github.io/_config.yml
Source: .
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating...
done in 0.637 seconds.
 Auto-regeneration: enabled for '.'
Configuration file: D:/GitHub/cyoncan/cyoncan.github.io/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
`

###### What did you see instead?
**Configuration file: D:/GitHub/cyoncan/cyoncan.github.io/_config.yml
            Source: .
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating...
     Build Warning: Layout 'post' requested in _posts/2016-05-04-welco me-to-jekyll.markdown does not exist.
     Build Warning: Layout 'page' requested in about.md does not exist .
     Build Warning: Layout 'default' requested in archives.html does n ot exist.
     Build Warning: Layout 'blank' requested in atom.xml does not exis t.
     Build Warning: Layout 'default' requested in categories.html does  not exist.
     Build Warning: Layout 'default' requested in contact.html does no t exist.
     Build Warning: Layout 'default' requested in index.html does not  exist.
     Build Warning: Layout 'default' requested in links.html does not  exist.
                    done in 0.613 seconds.
 Auto-regeneration: enabled for '.'
Configuration file: D:/GitHub/cyoncan/cyoncan.github.io/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
**

**Comment by DirtyF** [comment]
@cyoncan your `_config.yml` contains some deprecated values, PR coming.

**Comment by parkr** [comment]
Thanks, @DirtyF!

**Comment by kousherAlam** [comment]
Hey, the link does not work now...  Can you give me another link ??

**Comment by DirtyF** [comment]
@kousherAlam Nope, but I would advise to post a link to your public repo on https://talk.jekyllrb.com to get help if you run into that kind of issue.
