### ISSUE TITLE
Error when including UTF-8 filenamed files

### ISSUE THREAD

**Issue by jeffreyantony** [jekyll/jekyll#4868]
I have a html file in a non-english langauge ( മലയാളം.html ). If I try to include this html file using the below code, I am getting the below shown error.

{% include blog_comments/മലയാളം.html %}

But I believe the error is from Liquid.

Regenerating: 1 file(s) changed at 2016-05-05 09:49:14 Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: blog_comments/മലയാളം.html Valid syntax: {% include file.ext param='value' param2='value' %} in _includes/post_comments.html, included in _layouts/post.html

Does anyone know how to get the file മലയാളം.html included ?

**Comment by envygeeks** [comment]
@jeffreyantony our include tag is unfortunately ASCII limited so you'll have to make it fall into the ASCII character table to use includes.

**Comment by jeffreyantony** [comment]
Is there any way to get the UTF-8 support ?

Is there any reason to limit the characters in the include tag ? Is it due to any security reasons ?
/^[a-zA-Z0-9_\/\.-]+$/
