### ISSUE TITLE
Old command switches are gone

### ISSUE THREAD

**Issue by omnidan** [jekyll/jekyll#4869]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.1.3

###### What operating system are you using?

OS X 10.11.4

###### What did you do?

```
jekyll --config _config.yml,_config_dev.yml --watch
```

###### What did you expect to see?

Site being served.

###### What did you see instead?

```
       Deprecation: Jekyll now uses subcommands instead of just switches. Run `jekyll help` to find out more.
```

I tried running `jekyll help` but there doesn't seem to be a way to use a certain config or a watch mode. Was this removed from jekyll3? If yes, why?

**Comment by omnidan** [comment]
This seems to be mostly a documentation problem. I now ran: `jekyll serve --config _config.yml,_config_dev.yml` which works fine. Although there is no info about the `--config` option in `jekyll help`. The `--watch` mode still doesn't seem to work, though.

**Comment by envygeeks** [comment]
```
jekyll help serve
jekyll serve -- Serve your site locally

Usage:

  jekyll serve [options]

Options:
            --config CONFIG_FILE[,CONFIG_FILE2,...]  Custom configuration file
```

Seems the documentation states so?

**Comment by omnidan** [comment]
@envygeeks Ah, so it's part of the subcommand docs now. Kinda confusing, but I'll keep this in mind :wink: What about `--watch`?

**Comment by envygeeks** [comment]
@omnidan watch has moved to a switch on said sub-commands too, so you can do `{build,serve} --watch` now instead of the other way around which was fairly more confusing in the past (at least to me it was.) Now you are more explicit in what you want:

`jekyll build --watch`
`jekyll serve --watch --skip-initial-build`
