### ISSUE TITLE
built site structure

### ISSUE THREAD

**Issue by glaistergaucher** [jekyll/jekyll#4875]
###### What version of Jekyll are you using (`jekyll -v`)?
Github Pages - then 3.1.3 locally

###### What did you do?
On Github Pages, only my root "index.html" file was generated, and none of the links pointing to the other pages were working. When building the site locally, I found the built site structure to be different.

###### What did you expect to see?
I was expecting, as before, a structure as such:
x _site 
xx index.html
xx en/
xxx page1.html
xxx page2.html

###### What did you see instead?
The structure has changed, and broke all the links. This is what comes out now:

x _site 
xx index.html
xx en/
xxx page1/
xxxx index.html
xxx page2/
xxxx index.html

Any ideas on how to revert that to the previous behaviour ? many thanks

**Comment by parkr** [comment]
@glaistergaucher In Jekyll 3, pages respect the `permalink` setting in `_config.yml`. Try modifying/removing that [per our docs](http://jekyllrb.com/docs/permalinks/).
