### ISSUE TITLE
Pop and shift return remaining items instead of popped or shifted items

### ISSUE THREAD

**Issue by narthur** [jekyll/jekyll#4880]
###### What version of Jekyll are you using (`jekyll -v`)?

jekyll 3.1.2

###### What operating system are you using?

Mac OSX 10.10.5

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Based on [this comment](https://github.com/jekyll/jekyll/issues/2892#issuecomment-58694325) I ran these tests:

```liquid
{% assign my_array = "one|two|three" | split: "|" %}{{ my_array | pop }}

{% assign my_array = "one|two|three" | split: "|" %}{{ my_array | pop: 2 }}

{% assign my_array = "one|two|three" | split: "|" %}{{ my_array | shift }}

{% assign my_array = "one|two|three" | split: "|" %}{{ my_array | shift: 2 }}
```

###### What did you expect to see?

> three
> 
> twothree
> 
> one
> 
> onetwo

###### What did you see instead?

> onetwo
> 
> one
> 
> twothree
> 
> three

**Comment by parkr** [comment]
[`pop`](https://github.com/jekyll/jekyll/blob/92720363e1f8a4b0a5baf1f0f9a3e0e5c6c8ce14/lib/jekyll/filters.rb#L288-L293) appears to be returning the modified array, as expected.

[`shift`](https://github.com/jekyll/jekyll/blob/92720363e1f8a4b0a5baf1f0f9a3e0e5c6c8ce14/lib/jekyll/filters.rb#L302-L307) appears to be returning the modified array as well, as expected.

**Comment by narthur** [comment]
@parkr Yes, that is the behavior. And this is as intended? Most other languages I'm familiar with return the item popped off the stack instead of the modified stack. ([See Python's implementation.](http://www.tutorialspoint.com/python/list_pop.htm))

So in Liquid I guess you would have to do something like this:

```
{% assign list = site.pages %}
{% assign item = list | last %}
{% assign list = list | pop %}
```

Not too bad, but I still feel like the filter names imply a different behavior.

**Comment by parkr** [comment]
> And this is as intended?

@narthur Yes, this is as intended. It isn't the same as `Array#pop` in Ruby.

I'd be up for a PR to add `pop_item` and `shift_item` which would just proxy to `Array#<method>` in that case.

**Comment by narthur** [comment]
@parkr Ok, thanks. I'd have to learn a bit more about how Jekyll works under the hood before I'd be able to do that. =)

It seems like most things in Liquid require reassignment to be changed. Could a filter like `pop_item` modify the array while still returning the popped item for assignment to another variable?

**Comment by envygeeks** [comment]
@narthur for Liquid filters the returned value is the value that you get back in the tag.

**Comment by narthur** [comment]
@envygeeks Not sure I'm following.

Is this possible?:

```
{% assign list = '1,2,3' | split: ',' %}
{% assign item = list | pop_item %}
{{ item }} {% comment %} should output `3` {% endcomment %}
{{ list }} {% comment %} should output `12` {% endcomment %}
```

In other words, can a filter be made to both return a value and modify another separate variable?

**Comment by envygeeks** [comment]
@narthur if I'm honest, I actually don't know if that's possible,  I've never tried it.  But in theory I would think it would be possible since list should be held inside of the registers as an actual array and if you pop on that array and return that popped value it should affect the register too... unless they dup that value to you which means what you want *should* work but I can't say for sure it will be since there can be any number of ways that could prevent that accidentally.

**Comment by parkr** [comment]
> In other words, can a filter be made to both return a value and modify another separate variable?

Yes, I believe that this is possible! Our preexisting filters don't do this by choice.
