### ISSUE TITLE
Contribution: Ruby Styleguide not present

### ISSUE THREAD

**Issue by mertkahyaoglu** [jekyll/jekyll#4893]
@jekyll/documentation I was trying to find a style guide for Ruby to fix rubocop offenses and noticed that [styleguide/ruby](https://github.com/styleguide/ruby) repo does not exist anymore.

I think we should find another style guide that matches our current one. I don't know if there is already one but we should fix the link in [this](https://jekyllrb.com/docs/contributing/#code-contributions-generally) section.

**Comment by chrisfinazzo** [comment]
Google lists [this][] as the first result, so that might be an option. The account seems to be gone as well, so I'm not sure what to make of it.

Interested to know if @bbatsov is cool with this, too.

cc/ @jekyll/core @benbalter

[this]: https://github.com/bbatsov/ruby-style-guide

**Comment by pathawks** [comment]
What happened to GitHub's style guides??

**Comment by envygeeks** [comment]
@chrisfinazzo that styleguide diverges from the one we based our Rubocop rules on.  I can name three off the bat (the rest I'll have to dig for... and note this is based on when I read that years ago.)

1. We still use hash rockets and actively want them, it recommends keyword style.
2. It recommends '' however, we set it to "" because interpolation is more common than not (and because the perf difference isn't all that wide.)
3. We typically indent by 2 or 4, they indent to the start of the old.  I find that limits my flexibility to keep having to constantly "\" very low.  At least that's what's throughout the source (mostly) but admittedly I do believe we use both styles...

**Comment by envygeeks** [comment]
@pathawks seems weird doesn't it? No announcement or anything, it just got deleted, I even tried to search Twitter and nobody knows what happened :cry:

**Comment by chrisfinazzo** [comment]
@envygeeks 1 and 3 seem a bit arbitrary, but whatever. I'd be more concerned if someone tried to mess with the SASS to move alway from our semi-Stroustrup variant. Everything else looks wrong to me 👎🏻

@pathawks The account is gone too, I seem to remember there being multiple repos there 🤔

**Comment by envygeeks** [comment]
> 1 and 3 seem a bit arbitrary, but whatever. 

One could argue the same for a lot of those rules as we've found they decrease readability for our new programmers and clients, and one could argue the same for the flip of their rules so what's the point?

**Comment by parkr** [comment]
... weird. We could use the wayback machine, or replicate what we're interested in? Rubocop rules do the trick for me, but I could see non-enforceable styleguides being useful. @mertkahyaoglu, want to add that to the main docs?

**Comment by bbatsov** [comment]
I have no idea what happened with GitHub's style guide.

**Comment by benbalter** [comment]
> I have no idea what happened with GitHub's style guide.

We temporarily took down the style guide to give it a cover-to-cover update. We're still dotting some I's and crossing some T's, but I checked with the team involved, and the Ruby style guide should be back up in the very near future.

**Comment by bbatsov** [comment]
Good to know. Thanks!

**Comment by benbalter** [comment]
> at least the Ruby style guide should be back up in the very near future.

...[and we're back](https://github.com/styleguide/ruby)

**Comment by envygeeks** [comment]
@benbalter I'm gonna be honest, my life felt a little bit empty when I couldn't point people there.  Tell everyone thank you for bringing it back!
