### ISSUE TITLE
Layout data used on page with different layout

### ISSUE THREAD

**Issue by stomar** [jekyll/jekyll#4897]
I'm in the process of migrating from Jekyll 2 to Jekyll 3.1.3 (on Linux) with a site that uses nested layouts:

- default
  - page
  - special

`special` defines a property in the YAML front matter that is used in `default` if present; the property is not defined by `page`.

I have several pages (page_1, page_2, page_3, ...) where some use `page` and some use `special`.

After the first page that uses `special` and defines the property, the property seems to be defined for *all* pages, even the pages that use the "normal" `page` layout.

With Jekyll 2 this worked fine (with `page.property` instead of `layout.property`).

I believe this is a bug, or are the layout properties meant to be available globally?

(I can provide the source of a minimal example project that demonstrates the behavior if needed.)

**Comment by agriffis** [comment]
This seems to be the same as what @kvz describes at https://github.com/jekyll/jekyll/issues/4433#issuecomment-177990626

**Comment by stomar** [comment]
Seems so, yes. And I just noticed the very same problem is also described in #4884, and in #4442 (from February 2nd!), and possibly other issues.

It really would be nice to have this fixed soon; currently this is a blocker for migrating www.ruby-lang.org to Jekyll 3.

**Comment by parkr** [comment]
@stomar Can you give `master` a try?

**Comment by parkr** [comment]
@stomar I'm working on a 3.1.4. I'll add this to the list.

**Comment by stomar** [comment]
Tested with master (952947c65efd9ca5d4636edd8b26f5d7ac2bfdbf), no difference. With which commit has this supposedly been fixed?

**Comment by parkr** [comment]
@stomar I don't believe it has been fixed, but I wanted to make sure – we don't have this particular behaviour tested, sadly. 😦 Working on it now!

**Comment by stomar** [comment]
3.1.5 works as expected :smile: :clap:
