### ISSUE TITLE
Add an Ubuntu Snap Package?

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#4900]
Yesterday @iwelch suggested in #4899 we add `apt-get install jekyll` to our documentation (needless to say I pushed back because it includes packages we don't need.) It dawned on me today that maybe we could offer a snap package for people who don't want Docker, don't necessarily know Ruby, and just want a one liner to getting started.

/cc @jekyll/ecosystem

**Comment by envygeeks** [comment]
Note: Snap is only available on Ubuntu 16.04+

**Comment by parkr** [comment]
I don't know many folks using 16.04 and above (lots of folks still using trusty/precise) so I'm not sure this would add much value. But if it's easy, :shrug:

**Comment by envygeeks** [comment]
@parkr Personally I don't think it's worth it, but if people speak up and say it would be nice I'd be happy to maintain it the same as the Docker image, but thus far there seems no interest so I set the bot to close it at 2 weeks as wontfix if nobody speaks up.

**Comment by parkr** [comment]
Closing as stale.

**Comment by envygeeks** [comment]
Agreed.

**Comment by nathanhaines** [comment]
I would still very much be interested in a snap package for this project.  The lack of one was a giant point against when comparing with other static site generators which are available as snaps, but I still thought jekyll had the right balance of features and simplicity.

Snaps now run on Ubuntu 14.04, 16.04, Debian, Fedora, Arch, OpenSUSE, and in any case Ubuntu has not-insignificant marketshare, so an up-to-date snap package should be a good draw for new users just looking to try jekyll out, and once the snapcraft.yaml file is created, it should be pretty easy to automatically build the snap package straight out of the git repository.

**Comment by parkr** [comment]
Hey, @nathanhines! We package and deliver Jekyll to users through RubyGems, which is already cross-platform. If you install Ruby 2.1 or higher, you can use Jekyll with a simple `gem install jekyll`. We don't have the bandwidth to manage multiple package managers. If you wish to create a Snap package for Jekyll & maintain it, we are happy to list it as an option in our README and on our website. Thanks!

**Comment by redtux** [comment]
I have just installed Ruby 2.6.1 via Snap (RVM being no option in this particular situation), but `gem install bundler jekyll` runs into troubles while trying to build [Eventmachine](https://github.com/eventmachine/eventmachine/) 1.2.7. Whatever the problem might be (this would be off topic here), it shows that at least for people using Ruby via Snap (published by the Ruby core team btw) a proper Snap package for Jekyll would be of great help. :+1:
