### ISSUE TITLE
More informative error about "permission denied"

### ISSUE THREAD

**Issue by iwelch** [jekyll/jekyll#4913]
dear jekyll authors:

could you please improve this error message:

        Error:  Permission denied @ dir_initialize - .

regards, /iaw

**Comment by parkr** [comment]
@iwelch Did you run with `--trace`?

**Comment by iwelch** [comment]
no.  just with --verbose .  the plain error could be more informative, even when it is possible to track down the fault.  just a suggestion.

**Comment by envygeeks** [comment]
This is more than likely caused by our global capture of Exception without taking into account special errors like EPERM which include some diagnostically relevant information for the user.
