### ISSUE TITLE
Categories in and out of URLS

### ISSUE THREAD

**Issue by locicero** [jekyll/jekyll#4915]
Hi,

I have a quick question regarding jekyll URLs and categories. Right now I have two categories setup, which for the sake of simplicity will name "one" and "two". In category one, I would like for the post URL to be on the root level, such as "example.com/post-in-category-one/". Then, for category two, I would like to make it so that the URL is "example.com/two/post-in-category-two/"

In my _posts folder, I have a subfolder named "two", where I have placed all posts in category two. Then, all posts in category one (without the category in the URL) are simply placed in the _posts folder.

I have done some searching, and have not found any topics/answers regarding this, and felt it would be best to directly contact the jekyll developers here on GitHub.

Michael

**Comment by envygeeks** [comment]
Hi @locicero this medium is not for generic questions about how to use Jekyll, this ticket system is reserved for bugs only.  Please ask your question at https://talk.jekyllrb.com as the ticket system stated in the template.  Thanks!
