### ISSUE TITLE
Github Pages Wrong 301 Redirection

### ISSUE THREAD

**Issue by octref** [jekyll/jekyll#4920]
Say you have these two files:

- `/test.html`
- `/test/hi.html`

These were generated:

- `/_site/test.html`
- `/_site/test/` folder
- `/_site/test/hi.html`

On github pages, (for example, http://octref.github.io), http://octref.github.io/test 301 to http://octref.github.io/test/

```
> curl -I https://octref.github.io/test
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: http://octref.github.io/test/
Access-Control-Allow-Origin: *
Expires: Fri, 20 May 2016 17:42:50 GMT
Cache-Control: max-age=600
X-GitHub-Request-Id: 17EB2C1C:35F3:74BD:573F4A41
Content-Length: 178
Accept-Ranges: bytes
Date: Fri, 20 May 2016 17:32:50 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-dfw1848-DFW
X-Cache: MISS
X-Cache-Hits: 0
Vary: Accept-Encoding
X-Fastly-Request-ID: a9ea0c3247ebcc542810abbe1bfcd917181f6b98
```

Why it doesn't serve `_site/test.html`? I don't have any repo named `test` either.
What is triggering the 301? If it's the existence of `_site/test`, then that's some really weird logic.

Jekyll version is 3.1.6, but that shouldn't matter.

Thanks!

**Comment by parkr** [comment]
```text
Location: http://octref.github.io/test/
```

HTTPS isn't currently officially supported on GitHub Pages; this is why you're seeing the HTTPS –> HTTP redirect.

When you go to `octoref.github.io/test`, the server sees a directory named `test`, which houses the contents of `_site`. The redirect to add the trailing slash is the server handling the file –> directory redirect.

When the server access `octoref.github.io/test/`, it's accessing the `_site` directory **generated by GitHub Pages** (irrespective of what you have in your repository).

Check out [this documentation](https://help.github.com/articles/user-organization-and-project-pages/) for answers to your questions.

Please write support@github.com if you have further questions – this repository is just for Jekyll, not for GitHub Pages questions. Thanks!

**Comment by octref** [comment]
@parkr 
Thanks for your response! I just emailed GH support.

> the server sees a directory named `test`
> handling the file –> directory redirect.

But it also sees a file `test.html`, so the redirect is unreasonable.

**Comment by parkr** [comment]
@octref I believe it checks for a project _first_, so if you have a repo named `test`, it chooses that over a file named `test.html` in your project. You'd have to specify `test.html` explicitly to get the file.

**Comment by octref** [comment]
@parkr But I don't have a repo named `test`. Does that mean I cannot have `octref.github.io/x` as a clean URL, even if I don't have any project named `x`?

If I'm using clean URL I want each endpoint to be clean. Otherwise I'd just go all slash in the end.

Here is an implementation of clean URL by https://surge.sh. If would be awesome if GH pages could have something similar.

Thanks!

**Comment by octref** [comment]
@parkr And sorry to get you involved in this again. I know this repo is for Jekyll but you seem to work at GH, and I still haven't heard back from GH support.
