### ISSUE TITLE
3.2 pre beta 1 - jekyll new delete existing Gemfile

### ISSUE THREAD

**Issue by djacquel** [jekyll/jekyll#4925]
- [x] I Updated to the latest Jekyll 
- [x] This is a feature request.
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

## My Reproduction Steps

As I'm working with my local jekyll version for development, I first create a Gemfile containing

    source "https://rubygems.org"
    gem 'jekyll', :path => '/path/to/jekyll'

I then make a `bundle install`

And when I make a `bundle exec jekyll new . --force`, my Gemfile is replaced by jekyll's one.

## The Output I Wanted

Preserve existing Gemfile

**Comment by parkr** [comment]
I don't agree that when using the force flag you should expect the gemfile to stay as it was. It implies a destructive action. Why not do `jekyll new test-site` then change the gemfile after? It sounds like you're starting from scratch in all situations.

**Comment by envygeeks** [comment]
I agree.

**Comment by djacquel** [comment]
Ok
