### ISSUE TITLE
Posts are not updating in github pages

### ISSUE THREAD

**Issue by prateepgedupudi** [jekyll/jekyll#4926]
My posts are not updating in git hub pages. Attaching github code and page url for reference 
https://github.com/prateepgedupudi/prateepgedupudi.github.io/tree/master/_posts
http://prateep.info

**Comment by envygeeks** [comment]
Please email support@github.com as only they can help with that problem.

**Comment by prateepgedupudi** [comment]
Thanks. After  delete and recreation of branch work fine for me.
