### ISSUE TITLE
Can I use templates inside other templates?

### ISSUE THREAD

**Issue by jwillmer** [jekyll/jekyll#4937]
What I like to do and not sure if it is possible:
I am creating a blog and have created a nice post template for my blog posts. Now I like to create a page that I call `offline.html`. In this page I like to render each post (with the post template) and display it in a long list. 

![image](https://cloud.githubusercontent.com/assets/1503577/15495866/e1297e44-2192-11e6-8c00-697ca9261c26.png)

The reason I like to do this is so that a user can have all the content on one page and only needs to load it once. This way he does not need to have internet to read through the blog and/or he can print the page as a pdf and has all my content.

This is what I tried so far but I am not able to overried page in the context of the for loop:
```
{% for page in site.posts limit:5  %}
      {% include_relative _layouts/post.html %}
{% endfor %}
```

Is it possible to solve?

**Comment by jwillmer** [comment]
That did the trick but how do I get the header and footer removed?
```
{% for post in site.posts %}
{% unless post.draft %}
{{ post }}
{% endunless %}
{% endfor %}
```

**Comment by envygeeks** [comment]
Hi @jwillmer, this tracker is for bugs only.  For generic questions please use our Discussion platform at https://talk.jekyllrb.com.  Thanks!
