### ISSUE TITLE
Auto regeneration broken in 3.1.6

### ISSUE THREAD

**Issue by colinmcparland** [jekyll/jekyll#4939]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***Mac OS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

gem install jekyll
jekyll new myblog
cd myblog
jekyll serve

Terminal Output:

$ jekyll serve
Configuration file: /Applications/MAMP/htdocs/jekyll/myblog/_config.yml
            Source: /Applications/MAMP/htdocs/jekyll/myblog
       Destination: /Applications/MAMP/htdocs/jekyll/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.295 seconds.
 Auto-regeneration: enabled for '/Applications/MAMP/htdocs/jekyll/myblog'
Configuration file: /Applications/MAMP/htdocs/jekyll/myblog/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
[2016-05-24 16:34:24] ERROR `/favicon.ico' not found.

I expected the pages to update automatically once a file was saved.  It refreshed fine when I quit the server and started a new instance.  Also interestingly, this shows up when I save the first page:

Regenerating: 1 file(s) changed at 2016-05-24 16:34:40

But the page doesn't actually regenerate.  For every other save after that, no message appears.

Gem List:

*** LOCAL GEMS ***

activesupport (4.2.5.1)
bigdecimal (1.2.8)
bundler (1.12.4)
bundler-unload (1.0.2)
cheat (1.3.3)
claide (1.0.0.beta.1, 0.9.1)
cocoapods (1.0.0.beta.3, 0.39.0)
cocoapods-core (1.0.0.beta.3, 0.39.0)
cocoapods-deintegrate (1.0.0.beta.1)
cocoapods-downloader (1.0.0.beta.1, 0.9.3)
cocoapods-plugins (1.0.0.beta.1, 0.4.2)
cocoapods-search (1.0.0.beta.1, 0.1.0)
cocoapods-stats (1.0.0.beta.3, 0.6.2)
cocoapods-trunk (1.0.0.beta.2, 0.6.4)
cocoapods-try (1.0.0.beta.2, 0.5.1)
colorator (0.1)
colored (1.2)
did_you_mean (1.0.0)
directory_watcher (1.5.1)
escape (0.0.4)
executable-hooks (1.3.2)
ffi (1.9.10)
fourflusher (0.3.0)
fuzzy_match (2.0.4)
gem-wrappers (1.2.7)
i18n (0.7.0)
io-console (0.4.5)
jekyll (3.1.6, 3.1.2)
jekyll-docs (3.1.2)
jekyll-sass-converter (1.4.0)
jekyll-watch (1.4.0)
json (1.8.3)
kramdown (1.11.1)
liquid (3.0.6)
listen (3.1.5, 3.0.8)
lolcat (42.1.43)
mercenary (0.3.6)
minitest (5.8.3)
molinillo (0.4.2)
nap (1.1.0)
net-telnet (0.1.1)
netrc (0.7.8)
pager (1.0.1)
paint (1.0.1)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
rb-fsevent (0.9.7)
rb-inotify (0.9.7)
rdoc (4.2.1)
rouge (1.10.1)
ruby_dep (1.3.1)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
safe_yaml (1.0.4)
sass (3.4.22)
test-unit (3.1.5)
thread_safe (0.3.5)
trollop (2.1.2)
tzinfo (1.2.2)
xcodeproj (1.0.0.beta.2, 0.28.2)

jekyll 3.1.6

**Comment by envygeeks** [comment]
What's in your exclude list and what is the name of the file?

**Comment by colinmcparland** [comment]
Nothing excluded, name of the file I am editing is the default page.html layout.  

Config.yml:

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Test Site
email: colin@tiny-bird.ca
description: > # this means to ignore newlines until "baseurl:"
  Harley Alexander is touring the USA in 2016.  Tour dates are listed below.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

**Comment by parkr** [comment]
@colinmcparland Are you working with any symlinks, either in the site, or at the path you describe?

**Comment by colinmcparland** [comment]
Actually yes, the full path of the site is:

/Users/Colini/htdocs/jekyll/myblog

htdocs is a symlink to Applictaions/MAMP/htdocs.

**Comment by colinmcparland** [comment]
I should mention I switched the directory to one with no symlinks and the problem persists.

**Comment by parkr** [comment]
Interesting. This might be a bug with Listen. Did you try running Jekyll with the `--force-polling` flag?

**Comment by colinmcparland** [comment]
Yep I did `jekyll serve --force_polling` but no luck.

**Comment by mhaberler** [comment]
I can confirm this bug, after an accidential upgrade to 3.1.6 from 3.1.3 (https://github.com/mhaberler/docker-jekyll-asciidoctor/commit/4ec98958e6a50d5653b91fec0e75bf0c0ccbcaa5), stepping back now

**Comment by envygeeks** [comment]
Provide debug output, we cannot verify your issue is legitamate without it and test it outside of Docker, there are very well known issues on Docker, sometimes they surface randomly, sometimes they don't but there are very well known issues involving Docker and the problem you are having @mhaberler so we'll need both debug output and verification that you are either on Linux and still doesn't work, or it doesn't work with native Ruby outside of Docker.

**Comment by envygeeks** [comment]
To get debug output append `--trace --verbose`

**Comment by colinmcparland** [comment]
Downgraded to 3.1.2 and it is working...have to refresh the browser window but still works better than before

**Comment by colinmcparland** [comment]
Debug output:

`jekyll serve --trace --verbose`
  Logging at level: debug
Configuration file: /Applications/MAMP/htdocs/jekyll_project/_config.yml
         Requiring: kramdown
            Source: /Applications/MAMP/htdocs/jekyll_project
       Destination: /Applications/MAMP/htdocs/jekyll_project/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
           Reading: _posts/2016-05-25-welcome-to-jekyll.markdown
         Rendering: _posts/2016-05-25-welcome-to-jekyll.markdown
  Pre-Render Hooks: _posts/2016-05-25-welcome-to-jekyll.markdown
  Rendering Liquid: _posts/2016-05-25-welcome-to-jekyll.markdown
         Requiring: rouge
  Rendering Markup: _posts/2016-05-25-welcome-to-jekyll.markdown
         Requiring: kramdown
  Rendering Layout: _posts/2016-05-25-welcome-to-jekyll.markdown
         Rendering: _posts/2016-05-25-welcome-to-jekyll.markdown
  Pre-Render Hooks: _posts/2016-05-25-welcome-to-jekyll.markdown
  Rendering Liquid: _posts/2016-05-25-welcome-to-jekyll.markdown
  Rendering Markup: _posts/2016-05-25-welcome-to-jekyll.markdown
         Rendering: about.md
  Pre-Render Hooks: about.md
  Rendering Liquid: about.md
  Rendering Markup: about.md
  Rendering Layout: about.md
         Rendering: feed.xml
  Pre-Render Hooks: feed.xml
  Rendering Liquid: feed.xml
  Rendering Markup: feed.xml
  Rendering Layout: feed.xml
         Rendering: index.html
  Pre-Render Hooks: index.html
  Rendering Liquid: index.html
  Rendering Markup: index.html
  Rendering Layout: index.html
         Rendering: /css/main.scss
  Pre-Render Hooks: /css/main.scss
  Rendering Liquid: /css/main.scss
  Rendering Markup: /css/main.scss
                    done in 0.271 seconds.
         Requiring: jekyll-watch
         Requiring: kramdown
           Watcher: Ignoring (?-mix:_config\.yml)
           Watcher: Ignoring (?-mix:_site)
 Auto-regeneration: enabled for '/Applications/MAMP/htdocs/jekyll_project'
  Logging at level: debug
Configuration file: /Applications/MAMP/htdocs/jekyll_project/_config.yml
[2016-05-28 13:58:22] INFO  WEBrick 1.3.1
[2016-05-28 13:58:22] INFO  ruby 2.3.0 (2015-12-25) [x86_64-darwin14]
[2016-05-28 13:58:22] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
[2016-05-28 13:58:22] DEBUG unmount .
[2016-05-28 13:58:22] DEBUG Jekyll::Commands::Serve::Servlet is mounted on .
    Server address: http://127.0.0.1:4000/
[2016-05-28 13:58:22] INFO  WEBrick::HTTPServer#start: pid=1184 port=4000
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2016-05-28 13:58:30            Reading: _posts/2016-05-25-welcome-to-jekyll.markdown
         Rendering: _posts/2016-05-25-welcome-to-jekyll.markdown
  Pre-Render Hooks: _posts/2016-05-25-welcome-to-jekyll.markdown
  Rendering Liquid: _posts/2016-05-25-welcome-to-jekyll.markdown
         Requiring: rouge
[2016-05-28 13:58:38] DEBUG accept: 127.0.0.1:49769
[2016-05-28 13:58:38] DEBUG Jekyll::Commands::Serve::Servlet is invoked.
[2016-05-28 13:58:38] DEBUG Jekyll::Commands::Serve::Servlet is invoked.
[2016-05-28 13:58:43] DEBUG Jekyll::Commands::Serve::Servlet is invoked.
[2016-05-28 13:58:43] DEBUG Jekyll::Commands::Serve::Servlet is invoked.
[

**Comment by envygeeks** [comment]
@colinmcparland we never supported refreshing the browser so that has nothing to do with us. What version of Jekyll is this "debug" output from? It looks to me like Jekyll is regenerating.

**Comment by mhaberler** [comment]
first run: inside container, 3.1.3
second run: outside container, 3.1.6 - I aborted this since it takes 16mins
shows that it goes on to rebuilding much more

`````
jenkins@next:~/workspace/machinekit-docs-server/source$ cd ..
jenkins@next:~/workspace/machinekit-docs-server$ docker run --user $(id -u):$(id -g) -it -v $(pwd):/work machinekit/jekyll-asciidoctor:jenkins_122_130  bash
jenkins@cb9d002ebe59:/work$ cd source/
jenkins@cb9d002ebe59:/work/source$ JEKYLL_MODE=preview jekyll serve  --watch --incremental --destination ../output --config _config.yml,_preview.yml --verbose --trace
  Logging at level: debug
Configuration file: _config.yml
Configuration file: _preview.yml
         Requiring: jekyll-asciidoc
         Requiring: asciidoctor-diagram
         Requiring: jekyll-sitemap
         Requiring: kramdown
            Source: /work/source
       Destination: ../output
 Incremental build: enabled
      Generating...
       EntryFilter: excluded /README.md
       EntryFilter: excluded /src
       EntryFilter: excluded /scripts
       EntryFilter: excluded /Makefile
         Rendering: sitemap.xml
  Pre-Render Hooks: sitemap.xml
  Rendering Liquid: sitemap.xml
  Rendering Markup: sitemap.xml
 Post-Render Hooks: sitemap.xml
                    done in 3.743 seconds.
         Requiring: jekyll-watch
         Requiring: jekyll-asciidoc
         Requiring: asciidoctor-diagram
         Requiring: jekyll-sitemap
         Requiring: kramdown
           Watcher: Ignoring (?-mix:_config\.yml)
           Watcher: Ignoring (?-mix:Makefile)
           Watcher: Ignoring (?-mix:scripts)
           Watcher: Ignoring (?-mix:src)
           Watcher: Ignoring (?-mix:README\.md)
 Auto-regeneration: enabled for '/work/source'
  Logging at level: debug
Configuration file: _config.yml
Configuration file: _preview.yml
[2016-05-28 17:31:18] INFO  WEBrick 1.3.1
[2016-05-28 17:31:18] INFO  ruby 2.3.0 (2015-12-25) [x86_64-linux]
[2016-05-28 17:31:18] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
[2016-05-28 17:31:18] DEBUG unmount .
[2016-05-28 17:31:18] DEBUG Jekyll::Commands::Serve::Servlet is mounted on /.
    Server address: http://127.0.0.1:4000//
[2016-05-28 17:31:18] INFO  WEBrick::HTTPServer#start: pid=16 port=4000
  Server running... press ctrl-c to stop.
^C[2016-05-28 17:32:38] DEBUG close TCPSocket(127.0.0.1, 4000)
[2016-05-28 17:32:38] INFO  going to shutdown ...
[2016-05-28 17:32:38] INFO  WEBrick::HTTPServer#start done.
jenkins@cb9d002ebe59:/work/source$ exit
jenkins@next:~/workspace/machinekit-docs-server$ cd source/
jenkins@next:~/workspace/machinekit-docs-server/source$ JEKYLL_MODE=preview jekyll serve  --watch --incremental --destination ../output --config _config.yml,_preview.yml --verbose --trace
  Logging at level: debug
Configuration file: _config.yml
Configuration file: _preview.yml
         Requiring: jekyll-asciidoc
         Requiring: asciidoctor-diagram
         Requiring: jekyll-sitemap
         Requiring: kramdown
            Source: /var/lib/jenkins/workspace/machinekit-docs-server/source
       Destination: ../output
 Incremental build: enabled
      Generating...
       EntryFilter: excluded /README.md
       EntryFilter: excluded /src
       EntryFilter: excluded /scripts
       EntryFilter: excluded /Makefile
         Rendering: sitemap.xml
  Pre-Render Hooks: sitemap.xml
  Rendering Liquid: sitemap.xml
  Rendering Markup: sitemap.xml
 Post-Render Hooks: sitemap.xml
         Rendering: /docs/sandbox/000001.asciidoc
  Pre-Render Hooks: /docs/sandbox/000001.asciidoc
  Rendering Liquid: /docs/sandbox/000001.asciidoc
  Rendering Markup: /docs/sandbox/000001.asciidoc
  Rendering Layout: /docs/sandbox/000001.asciidoc
         Rendering: /docs/sandbox/000002.asciidoc
  Pre-Render Hooks: /docs/sandbox/000002.asciidoc
  Rendering Liquid: /docs/sandbox/000002.asciidoc
  Rendering Markup: /docs/sandbox/000002.asciidoc
  Rendering Layout: /docs/sandbox/000002.asciidoc
         Rendering: /docs/sandbox/000003.asciidoc
  Pre-Render Hooks: /docs/sandbox/000003.asciidoc
  Rendering Liquid: /docs/sandbox/000003.asciidoc
  Rendering Markup: /docs/sandbox/000003.asciidoc
  Rendering Layout: /docs/sandbox/000003.asciidoc
         Rendering: /docs/sandbox/000004.asciidoc
  Pre-Render Hooks: /docs/sandbox/000004.asciidoc
  Rendering Liquid: /docs/sandbox/000004.asciidoc
  Rendering Markup: /docs/sandbox/000004.asciidoc
  Rendering Layout: /docs/sandbox/000004.asciidoc
^C  Liquid Exception:  in _layouts/docs.html

`````

**Comment by envygeeks** [comment]
@mhaberler we are specifically looking for events that come after the initial build can you run this command and provide the logs (make sure to edit and save a file after it boots): `jekyll s --skip-initial-build --trace --verbose` we just specifically need the events after you save the file, so you don't have to wait 16 minutes for it to build, I'm intrigued to see if it emits a change to us at all since we log that.

**Comment by mhaberler** [comment]
I found the reason and it was my own stupidity - I recreated a YML fragment with config info on each job, and that triggered the massive rebuilds.

sorry - please disregard, all peachy ;)

**Comment by parkr** [comment]
@colinmcparland Are you still able to repro? It looks like it's regenerating but hangs.

@mhaberler Glad you got it sorted!
