### ISSUE TITLE
Error: Invalid CSS after "@charset "utf-8"": expected "{", was ";"         on line 4

### ISSUE THREAD

**Issue by DanielPollitt** [jekyll/jekyll#4955]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***Mac OS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---
- [x] I was trying to build.
- [x] It was another bug?

I did a fresh install of Jekyll and created a brand new project. I am using Codekit in conjuntion with sublime text to customize the project.

Without changing anything from the default Jekyll files that comes with a new project, I saved the main.scss file which is located in /css.

I was then thrown this error:

> Error: Invalid CSS after "@charset "utf-8"": expected "{", was ";"
>         on line 4 of /Users/Dan/Desktop/D1A/css/main.scss
>   Use --trace for backtrace.

I have not altered any files--this is an error that happens right out of the box.

Any help is appreciated.

Thanks!

**Comment by parkr** [comment]
Hey! This sounds like a problem with the underlying sass lib. What does `bundle show` show? Most interested in anything related to sass.

**Comment by DanielPollitt** [comment]
Here is what my library structure looks lie. Just a basic, fresh Jekyll install:

![screen shot 2016-05-27 at 9 31 51 am](https://cloud.githubusercontent.com/assets/4998745/15609421/f434ac2c-23ed-11e6-8ec2-834d8f929eed.png)

Otherwise, I'm not using a dev version of Jekyll so I don't know how to use bundle.

FYI: I am not pushing to github yet. Only developing the site locally for now.

Thanks!

**Comment by envygeeks** [comment]
What happens if you drop `@charset` from the SCSS?

**Comment by DanielPollitt** [comment]
It applies the error to the next available line: 


`Error: Invalid CSS after "...ial, sans-serif": expected "{", was ";"
        on line 9 of /Users/Dan/Desktop/D1A/css/main.scss
  Use --trace for backtrace.`

**Comment by envygeeks** [comment]
Well, I can honestly say that at this point without access to the source or without something that can replicate it, we cannot figure out what is going on so this ticket is stalled, we really need something that can replicate this issue so that we can shim the source and trace what is going on.

**Comment by DanielPollitt** [comment]
What do you need me to do? Push it to github?

Otherwise, its just a straight out of the box jekyll install.

**Comment by envygeeks** [comment]
@DanielPollitt that would be great because then we could pull down the source causing errors as is and see if it errors on our systems and then shim Jekyll to trace where the error is coming from.

**Comment by DanielPollitt** [comment]
Should have a link for you soon!

**Comment by DanielPollitt** [comment]
Anyone have a chance to check this out?

Thanks,
Dan

**Comment by pathawks** [comment]
If you delete `css/main.css` (leaving `css/main.scss`) the site builds as expected.

I don't know how this file was created to begin with, it [does not exist in the default site template](https://github.com/jekyll/jekyll/tree/v3.1.6/lib/site_template/css). As long as you rely on Jekyll to convert your SCSS to CSS, everything is just fine :+1:

**Comment by DanielPollitt** [comment]
Thanks! That works!

**Comment by edking4967** [comment]
I am having a similar issue, where _site/css/main.css is generated but doesn't load when I open the site in a browser. This happens serving the site on El Capitan and Ubuntu 12.04.

**Comment by ecurtin** [comment]
Just FYI for anybody coming across this issue through Google in the future, my issue turned out to be using IntelliJ File Watchers to compile the SCSS. Those don't play nice with the required Jekyll front matter. 

Turn off File Watchers from Preferences -> Plugins and then delete `main.css` and you should be good to go.
