### ISSUE TITLE
You should also include build-essential as a dependency...

### ISSUE THREAD

**Issue by dkromp** [jekyll/jekyll#4957]
I got the following error when installing Jekyll on Ubuntu 14.0.
```
creating Makefile

make
sh: 1: make: not found
```
Resolved by 
```
sudo apt-get install build-essential
```
http://superuser.com/questions/192683/sh-make-not-found

**Comment by envygeeks** [comment]
We do not create a Makefile, we do not include a Makefile.  This is a systems or a template/plugin issue.  We also cannot provide system dependencies (that's not how Ruby Gems works.) So you'll need to figure out and provide any dependencies for what you choose to use.

Sorry.
