### ISSUE TITLE
requires Ruby version >- 2.0.0 but 2.0.0 installed and in use

### ISSUE THREAD

**Issue by acartine** [jekyll/jekyll#4963]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***Mac OS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

```
me@me-K5Jr ~/node_modules/bootstrap $ rvm list

rvm rubies

=> ruby-2.0.0-p648 [ x86_64 ]
 * ruby-2.3.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

me@me-K52Jr ~/node_modules/bootstrap $ sudo gem install jekyll -v 3.1.6
ERROR:  Error installing jekyll:
	jekyll requires Ruby version >= 2.0.0.

me@me-K52Jr~/node_modules/bootstrap $ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-linux]
```

## The Output I Wanted

Wanted the install to work

**Comment by envygeeks** [comment]
RVM doesn't work with `sudo` because `sudo` does not import your path because of security reasons.  Remove `sudo` and just do `gem install` because RVM is done in the users home, not on the system.

If you continue to have problems please ask your question at https://talk.jekyllrb.com because this is a systems problem and not a bug in Jekyll. Thanks!
