### ISSUE TITLE
folder starting with underscore is **NOT** being excluded, changes to files still triggers build

### ISSUE THREAD

**Issue by raniesantos** [jekyll/jekyll#4965]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***Mac OS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 7

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

(jekyll gem **version 3.1.6**)

## The problem

It is my understanding that Jekyll is supposed to ignore/exclude folders that start with underscores from the build.

However I found in my project that when I save changes to files in a folder I named `_source` it still triggers a build.

(reference image)
![capture](https://cloud.githubusercontent.com/assets/8528269/15654446/e14bc1d2-26c6-11e6-8f22-6a0bbc2e5301.JPG)

These are the exclude settings in my `_config.yml` file

```yaml
exclude:
- node_modules
- bower_components
- package.json
- bower.json
- gulpfile.js
```

Upon adding the `_source` folder to this exclusion list in the config, I achieved the desired result, but since it is supposed to be Jekyll's behavior to ignore folders named this way, I believe that this is a bug.

Said project is located in [this repo](https://github.com/raniesantos/raniesantos.github.io).

**Comment by envygeeks** [comment]
This hasn't been the case since 3.0 when everything became a collection, and since collections start with an underscore, underscored folders are not ignored by default anymore, it's been the case for a year if not more (if my memory serves right.

It is not a bug.

**Comment by raniesantos** [comment]
Oh okay then, thanks for informing me, I was not aware of this change in v3.0
Closing the issue now
