### ISSUE TITLE
Jekyll 3.1.6, the where_exp filter seems to not filter anything

### ISSUE THREAD

**Issue by jeromecoupe** [jekyll/jekyll#4978]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***Mac OS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

With Jekyll 3.1.6, the where_exp filter seems to not filter anything

On a detail template for a document in a team collection

- This works fine: `{% assign postsByAuthor = site.posts | where: 'author', page.teamId %}`
- Whereas using the `where_exp` filter just returns all the posts `{% assign postsByAuthor = site.posts | where_exp: 'item', 'item.author == page.teamId' %}` The size of `postsByAuthor` is always the total number of posts
- Same if I try with a string: `{% assign postsByAuthor = site.posts | where_exp: 'item', 'item.author == "test"' %}`

**Comment by budparr** [comment]
The where_exp is a 3.2ish feature: https://github.com/jekyll/jekyll/blob/0212c838145e153ea2cab71616eddb3c0bb8c687/History.markdown#minor-enhancements

**Comment by jeromecoupe** [comment]
Hey there. Sorry assumed it should work in 3.1.6 since that's the latest stable release (to my knowledge) and `where_exp` is already in the public docs https://jekyllrb.com/docs/templates/

Really enjoyed your Jekyllconf talk by the way

**Comment by budparr** [comment]
Thanks! I think there's some discussion about how to better handle the docs in cases like this. Feel free to close the issue. Though I'm guessing it'd be a while before you can use the filter in gh-pages (because those updates tend to lag), you can test it locally by putting this in your Gemfile:
` gem "jekyll", :git => "git@github.com:jekyll/jekyll.git", :ref => 'HEAD'`

**Comment by jeromecoupe** [comment]
Yeah Github is genrally a bit behind but not that much these days. Currently running 3.1.6 so not too shabby https://pages.github.com/versions/

Closing the issue
