### ISSUE TITLE
Coffee not compiled when specifying source/destination folders

### ISSUE THREAD

**Issue by carc1n0gen** [jekyll/jekyll#4982]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***Mac OS*** 10.11
- [x] I am on (or have tested on) ***FreeBSD*** 10.2
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

I ran the command:

`jekyll build -s ~/path/to/source -d ~/tmp/test`

Then examined the compiled site in the test folder.  The coffee files were copied instead of compiled.

Here is the coffee file:

```
---
#
---

if window.addEventListener
    window.addEventListener 'load', ->
        document.body.className = document.body.className.replace /\bis-loading\b/, ''

```

When I just go in the the source folder and `jekyll build` it compiles the coffee file correctly

**Comment by Crunch09** [comment]
Hey @carc1n0gen ,
have you put your config file also in your source directory? I only could reproduce your issue if the configuration file (where jekyll-coffeescript is added as a dependency ) is not within the source dir. In this case it is not loaded and that's why the converter is not executed.

**Comment by carc1n0gen** [comment]
@Crunch09 Thank you.  Specifying where the _config.yml file was with the --config build option solved this issue.
