### ISSUE TITLE
Website got messed up

### ISSUE THREAD

**Issue by alexandrius** [jekyll/jekyll#4988]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [ ] I am on (or have tested on) ***Mac OS*** 10+
- [ ] I am on (or have tested on) ***Windows*** 10+

## My Reproduction Steps
Hello, everything was great until a week ago. I just pushed some corrections to the repo and everything got messed up. About is under every post. http://alexandrius.com . I'm not very strong at HTML or CSS and have changed nothing at all in theme.
BTW I updated Jekyll locally and got the same thing. The last working of the website was built Jekyll 3.0.3

Here's the source https://github.com/alexandrius/alexandrius.github.io .

Please help

**Comment by envygeeks** [comment]
Hi @alexandrius this medium is for Jekyll bugs only.  Please post your question at https://talk.jekyllrb.com where the wider community and maintainers can help you solve your problem.  If we feel it's a bug once posted there we will re-open this issue with better details.
