### ISSUE TITLE
Error: `require': iconv will be deprecated in the future

### ISSUE THREAD

**Issue by areohbe** [jekyll/jekyll#499]
When I try running my jekyll server locally, I am getting back this error message. Any idea on a fix or can this be ignored? I saw several mentions of this in other issues but all users were have a long string of issues and none of the fixes mentioned seem to eradicate this issue. 

```
Users/Rob/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
Configuration from /Users/Rob/Documents/Sites/jekyll/areohbe.github.com/_config.yml 
Auto-regenerating enabled: /Users/Rob/Documents/Sites/jekyll/areohbe.github.com -> /Users/Rob/Documents/Sites/jekyll/areohbe.github.com/_sit
```

**Comment by YUFENGWANG** [comment]
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
WARNING: Could not read configuration. Using defaults (and options).
	No such file or directory - new/_config.yml
Building site: new -> myblog
/usr/lib/ruby/vendor_ruby/jekyll/site.rb:126:in `chdir': No such file or directory - /home/jude/new/ (Errno::ENOENT)
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:126:in `read_directories'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:98:in `read'
	from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:38:in `process'
	from /usr/bin/jekyll:250:in `<main>'
oh my gosh ,does anybody know what the heck this is?

**Comment by samiullah** [comment]
I am also getting same warning when running JEKYLL serve , any fixes?

**Comment by envygeeks** [comment]
Update your Ruby and Jekyll.

**Comment by samiullah** [comment]
Please let me know the versions I should update to

**Comment by envygeeks** [comment]
We only support Jekyll 3.0.1 and Ruby 2.0+
