### ISSUE TITLE
application/octet-stream content-type return when post permalink doesn't end with .html

### ISSUE THREAD

**Issue by axelfontaine** [jekyll/jekyll#4996]
- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [X] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***MacOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [X] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [X] It was another bug.

## My Reproduction Steps

Create a post with `permalink: /blog/flyway-4.0.2` and jekyll will serve it as application/octet-stream

Adding `.html` (which I don't want) to the permalink with no other changes will make Jekyll serve the correct content-type again

## The Output I Wanted

A page served with text/html as its content type

**Comment by axelfontaine** [comment]
This is a major regression and occurs both locally on a GH pages!

**Comment by parkr** [comment]
@axelfontaine What is the file in `_site`? If it doesn't have `.html`, then we can't assume that it's HTML.

**Comment by axelfontaine** [comment]
@parkr It doesn't have `.html`, but that was never an issue in the past. This worked flawlessly with Jekyll 2.X.

**Comment by parkr** [comment]
@axelfontaine Did you see [the upgrading docs for this](https://jekyllrb.com/docs/upgrading/2-to-3/#permalinks-no-longer-automatically-add-a-trailing-slash)? I believe you are relying on a feature that was removed to allow for extensionless URL's.

This is not a regression but a feature in this case. I'm sorry you aren't able to take advantage of the previous behaviour in Jekyll 3, but if you add a trailing slash to your permalinks (or via the permalink setting in your config), the old behaviour will likely be restored. 👍
