### ISSUE TITLE
Rendering non-post pages as markdown pages

### ISSUE THREAD

**Issue by cullanisthebest** [jekyll/jekyll#4998]
Hello,

I am having trouble **rendering a non-post markdown page**. 
For example, I want to render the following page as markdown: 
http://rnfc.org/ivey/introduction-to-data-science/Lesson%201/Summary/, but I am not sure how to do that and therefore, it currently only displays the plaintext of what I've written in markdown.

I have included the markdown within my _includes folder, as you can see here: https://github.com/rnfc/rnfc.github.io/tree/master/_includes as Chapter1.md

Referring to the markdown Summary page link above, I have written the following within the index.html of that Summary folder, my summary index file can be seen here: https://github.com/rnfc/rnfc.github.io/blob/master/ivey/introduction-to-data-science/Lesson%201/Summary/index.html

What do I need to do in order to be able to correctly render the Chapter1.md markdown content within the summary index.html page?

All help is appreciated, thank you!

**Comment by envygeeks** [comment]
Hi @cullanisthebest, this medium is for Jekyll bugs only, for usage questions or questions on how to do special stuff please ask at https://talk.jekyllrb.com as our reference ticket states.

Thanks!

**Comment by cullanisthebest** [comment]
Oh sorry, thanks for the guidance.
