### ISSUE TITLE
mobile site css broken

### ISSUE THREAD

**Issue by JazzMaster** [jekyll/jekyll#4999]
Mobile CSS support for jekyll, unlike pico and nano CMS is broken fiercely.
@media tags in css files crashes jekyll and it refuses to do anything about it.
Basically this says:
if on mobile browser-- do this instead.

an alternate is:

```css
*+html body.mobile  {
margin-top: 0;
}
body.mobile {
yada yada
}

img {
  max-width: 100%
}

input, textarea {
  max-width:100%
}
```

-anything here also affects non-mobile-

this said: 
there is an alternate(case is important):
HTML:

```html
<link rel="stylesheet" href="https://southernhedgehogs.org/screen.css" type="text/css" media="Screen" />
<link rel="stylesheet" href="https://southernhedgehogs.org/mobile.css" type="text/css" media="handheld" />
```
in the theme files.

also note _layouts folder is mostly useless, it should contain copies of the theme _include html files.
---

- [ X] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ X] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ X] I am on (or have tested on) ***iPhone 5s***

- [X ] There is a broken Plugin API.
- [X ] It was another bug.

## My Reproduction Steps
just edit a theme and install it. when you serve, you'll see the error.

## The Output I Wanted
mobile friendly formatted @media tags in the css.

Do note:
make a basic css inline with the html FIRST in `<head>`, then load the css externals  between and of `<head>` and `<body>`. this is called 'above the fold'.

**Comment by envygeeks** [comment]
Post the logs, Jekyll would give logs, use `--verbose`

**Comment by parkr** [comment]
Hey, sorry you're having trouble, @JazzMaster.

Mobile CSS support for Jekyll is just fine. Jekyll simply builds your site, so if you compiled the HTML to include CSS with valid `@media` queries, it will work. I have them on my site and they work just fine.

I am finding it very difficult to follow your issue above, and cannot derive reproduction steps from what you have written. Further information is necessary to validate:

> `@media` tags in css files crashes jekyll and it refuses to do anything about it.

I have never seen a CSS file with a valid `@media` tag ever cause problems with Jekyll. If your `@media` tag is in an SCSS or Sass file and the tag has an error in it, the compiler will fail and output a descriptive message.

Jekyll does not output `media="Screen"` unless your content has included it. So I do not know how Jekyll could be causing your issue.

I am closing this until further information is supplied which allows one of us to reproduce it. Thanks!
