### ISSUE TITLE
markdown syntax code highlighting doesn't work

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [jekyll/jekyll#5001]
I build a github-pages with jeykll. [zhengshuaipeng.github.io](https://github.com/ZhengshuaiPENG/zhengshuaipeng.github.io).  The problem is that the code highlight doesn't work. I have searched this problem in issues. But the problem haven't been solved.

This is my _config.yml:
```
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: ZhengshuaiPENG
author: "Zhengshuai PENG"
email: zhengshuai.peng@outlook.com
name: "Blog of Zhengshuai PENG"
url: blog.lovian.org
domain: lovian.org
all_categories: [
["java", "Java","/posts/java.html"],
["program", "Programming","/posts/program.html"],
["web", "Web","/posts/web.html"],
["linux", "Linux","/posts/linux.html"],
["read", "Note","/posts/read.html"],
["algorithm", "Algorithm","/posts/algorithm.html"],
["about", "About","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: Europe/Paris

collections:
  docs:
    output: true

gems:
 - jekyll-paginate

```

If I use the markdown syntax like following:
```
    ```cpp
     some code here
    ```

```

The code highlight doesn't work at all.

**Comment by sheriferson** [comment]
Try

```
{% highlight c++ %}

some code here

{% endhighlight %}
```

I recommend you read Jekyll's documentation here: https://jekyllrb.com/docs/home/

[This page](https://jekyllrb.com/docs/posts) explains code highlighting in Jekyll posts.

**Comment by crispgm** [comment]
Read the documentation:
http://jekyllrb.com/docs/posts/#highlighting-code-snippets

**Comment by ZhengshuaiPENG** [comment]
I know this way works, but I want to use the original markdown syntax, so this means it's not possible to do that?

**Comment by parkr** [comment]
@ZhengshuaiPENG kramdown is very particular. In your example above, your code is indented. If it is indented, make sure it is **only 4 spaces**, no tabs, exactly 4 spaces indented. Code blocks should work very similarly to how they work on GitHub.com otherwise, when not indented at all.
