### ISSUE TITLE
Local Development css stylesheet not found 

### ISSUE THREAD

**Issue by alidcastano** [jekyll/jekyll#5007]
My css sheet isn't found anymore in my personal site. I haven't changed anyhting there and I never had  a baseurl before, so not sure what could be the problem now. 

In includes/head.html:
`
  <link rel="stylesheet" href="{{ site.baseurl }}/styles.css">
`
and then I have a `styles.scss` file in the root of the project. I've tried changing it to css file or creating css folder and linking it from there, but neither worked. 

I'm using the newest version of Jekyll; and the same setup works in another project I have, so not sure how to get local development styles to work again.

**Comment by parkr** [comment]
Your `styles.scss` file must have YAML front matter (it may be empty), as [the docs](http://jekyllrb.com/docs/assets/) specify. Is that the case?

```text
---
---

// My SCSS here...
```

**Comment by parkr** [comment]
If you're referring to [this file](https://github.com/alidcastano/alidcastano.github.io/blob/master/styles.scss#L1). remove the fourth `-` at the top of the page so it's three hyphens instead of four.

**Comment by alidcastano** [comment]
Yeah, you were right, had an extra hypen by accident.  Thanks
