### ISSUE TITLE
Specify timezone for blog posts in settings

### ISSUE THREAD

**Issue by Wilfred** [jekyll/jekyll#5008]
Now that `future: false` is the default setting, GitHub will ignore posts if they look like they're in the future *according to GitHub's timezone*.

This means that a user can write a blog post in the morning and GitHub won't publish it if the current time is before midnight in GitHub's timezone. This is surprising and GitHub only exposes errors in its UI, so it's not immediately clear what's wrong.

If a user could specify their timezone in the settings, then they could obtain the desired behaviour without setting `future: true`.

**Comment by budparr** [comment]
Here's the docs page for setting timezone in config: https://jekyllrb.com/docs/configuration/#configuration-settings

**Comment by Wilfred** [comment]
Argh, poor googling on my part. Thanks.
