### ISSUE TITLE
"linenos" highlight option mangles output

### ISSUE THREAD

**Issue by dhutchison** [jekyll/jekyll#5013]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***MacOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Using jekyll 3.1.6 (as part of github-pages 82).

Using rouge highlighter, kramdown markdown, and a simple reproducible example markdown file:

    ---
    title: test
    date: 2016-06-14 22:39
    slug: test
    ---
    
    {% highlight python linenos %}
    import json
    {% endhighlight %}

The (relevant) produced HTML results in:

    <article> 
        <figure class="highlight">
            &gt;
            <code class="language-python" data-lang="python">
                <table style="border-spacing: 0">
                    <tbody>
                        <tr>
                            <td class="gutter gl" style="text-align: right">
                                <pre class="lineno">1</pre>
                            </td>
                            <td class="code">
                           </td>
                        </tr>
                    </tbody>
                </table>
            </code>
        </figure>
     </article>

A fuller example of the problem can be seen at http://www.devwithimagination.com/2015/05/12/fitness-tracking/ , this site is in the repository https://github.com/dhutchison/dhutchison.github.io .

## The Output I Wanted

The code to be rendered.

Thanks for your work.

**Comment by parkr** [comment]
@dhutchison What version of Rouge are you using?

**Comment by dhutchison** [comment]
Locally, "rouge (= 1.10.1)".

The full example is hosted on GitHub Pages and should have rebuilt today, which should rule out a local install issue (I hope).

**Comment by parkr** [comment]
Yikes, that's not good. It looks like a tag isn't closed properly.

**Comment by dhutchison** [comment]
Works fine still using the highlight block without "linenos". 

Curiously on the fuller example [(source)](https://github.com/dhutchison/dhutchison.github.io/blob/master/_posts/2015-05-12-fitness-tracking.markdown), which mixes highlight blocks and regular indented code blocks, all the content gets lost between the start of the highlight block until the next indented code block. 

I don't know if that is a clue or just a coincidence.

**Comment by parkr** [comment]
@dhutchison I took a look and fiddled with some things. When I set `layout: null` in `_layouts/main.html`, it works (slightly shrunk screenshot):

<img width="801" alt="screen shot 2016-06-15 at 10 28 06 am" src="https://cloud.githubusercontent.com/assets/237985/16090402/18eee834-32e4-11e6-802b-219a6a1c182e.png">

So the problem is actually the `compress` layout.

**Comment by dhutchison** [comment]
Thanks for your help. 

Now time for me to go back to that and figure out what's changed between 2 and 3 to make it go wrong.

**Comment by parkr** [comment]
@dhutchison Good luck! The `compress` layout does not support code blocks AFAIK, so it may just be that you cannot use it for any posts with code.

**Comment by dhutchison** [comment]
Yep, looks like the maintainer has accepted it isn't going to get fixed (https://github.com/penibelst/jekyll-compress-html/issues/71). There is a hacky workaround, but requires a modification to each post potentially. I'll have a bash, but doesn't look promising.
