### ISSUE TITLE
Suggestion: figcaption for highlighted code blocks

### ISSUE THREAD

**Issue by czak** [jekyll/jekyll#5020]
I'd like to propose adding a new (optional) `caption` argument to the `highlight` tag.
The argument - when added - inserts a `<figcaption>` to the highlighted `<figure>`.
This allows e.g. adding a filename as the caption.

Example from [my blog](http://czak.pl/2016/05/31/handbuilt-android-project.html): the following code:

```
{% highlight java caption="gen/pl/czak/handbuilt/R.java" %}
   ... omitted for brevity ...
{% endhighlight %}
```

...yields the following

```html
<figure class="highlight">
  <figcaption>gen/pl/czak/handbuilt/R.java</figcaption>
  <pre>
    <code class="language-java" data-lang="java">
      <!-- ... omitted for brevity ... -->
    </code>
  </pre>
</figure>
```

...and looks like this:

![screen shot 2016-06-16 at 16 23 07](https://cloud.githubusercontent.com/assets/14021/16120135/d152e51a-33de-11e6-9620-e68d50de6c61.png)

A **very rough** implementation can be seen in [my fork](https://github.com/jekyll/jekyll/compare/master...czak:feature/code-highlight-figcaption). A few notes about this code:

* It's pretty much just an update to the regexp
* The argument in my fork is actually called `filename`; this can be discussed further; I now think `caption` is better
* If this is found interesting, I can implement this properly with tests and documentation... or someone else can take a stab

Looking forward to your feedback

**Comment by parkr** [comment]
Hey, @czak! Thanks for suggesting this feature. When evaluating a new feature, we ask "Would at least 80% of users find it useful?" In this case, I am dubious about whether more than 10% of users would want this feature. Could you provide further clarification if you feel at least 80% of users would use this feature?

**Comment by czak** [comment]
Thanks for the response, @parkr. I guess the short answer is "I can't". I don't believe 80% of users would use it.

Nevertheless, here are my own reasons for finding this worthwhile:

* For the 10% of cases, I don't think there's currently an easy way to combine the `{% highlight %}` with a `<figcaption>`
  * I might be mistaken... am I?
  * I would not have started the fork if I knew of an easier way to add a `<figcaption>` inside the highlighted `<figure>`
* This would only be an optional argument
  * very much like a `<figcaption>` is optional within a `<figure>`
* Even if people don't use it, they often **should**
  * a filename above a block of code clarifies a lot and does not require additional introduction in the surrounding text
  * this improves understandability of articles significantly ("Wait so where do I put this code? Oh it says right here.")

**Comment by czak** [comment]
And indeed I found a simpler way.
Since I want to stay up to date with `jekyll/jekyll`, I extracted this "highlight with caption" tag into a plugin and I'm using it on my blog now.

If anyone's interested, here's [the gist](https://gist.github.com/czak/94f8b98e3f6789b38a4f7414ca703380). It's basically `Jekyll::Tags::HighlightBlock` with some tiny additions to allow for the `caption` parameter.

I'm closing the issue as I will not be insisting on the addition at this point.
Please reopen if my previous arguments actually struck a chord :)

**Comment by 11bits** [comment]
I think adding a figcaption would be useful for people using screen readers.

I suggest to add it as an accessibility improvement.

**Comment by olaf-otto** [comment]
Figcaptions would be fantastic. Especially if you are writing software docs, captions are an asset.
