### ISSUE TITLE
Files are 404 when on Github

### ISSUE THREAD

**Issue by geate** [jekyll/jekyll#5029]
Is there a correct way to deal with URL's on localhost and on Github? Because every google search has different ways of doing it and they're all excruciating. 

The current stackoverflow answer I tried was making two _config files with different url's. Which fixed CSS 404 by adding https://geate.github.io/website/main.css to the href. But Jekyll creates other links such as to /about with {{ prepend: site.baseurl }} https://geate.github.io/about which gives a 404.

Here's [my _config](https://github.com/geate/website) 

**EDIT:** Adding baseurl: /website fixed it, but is this the best approach to doing this or is there a better way? Because having two _config files is too much.

**EDIT2:** Now my localhost files are giving 404.. can someone check out my config files I posted above?

**EDIT3:** Apparently adding **site.github.url** magically fixes everything. But do I actually have to replace every url manually? Or is there a way to run jekyll new blog with the url's correctly pointing to site.github.url?

Actually I've found the simplest method. In _config.yml I'll add url: geate.github.io/website, baseurl: /website. And whenever I want to run it locally I'll comment them both out.

**Comment by pathawks** [comment]
This doesn’t sound like a bug in Jekyll. If you have questions about using Jekyll, you could try [talk.jekyllrb.com](https://talk.jekyllrb.com), or check out the docs to learn about [using the `--baseurl` flag](https://jekyllrb.com/docs/configuration/).

**Comment by parkr** [comment]
> EDIT: Adding baseurl: /website fixed it, but is this the best approach to doing this or is there a better way? Because having two _config files is too much.

When running locally, simply do `bundle exec jekyll serve --baseurl /website`. That is why that feature was created, to make this situation more tenable.

`site.github.url` is added by GitHub to make things easier. We do not make `jekyll new` point to `site.github.url` because we cannot assume users will use GitHub Pages. Maybe we can look into that again and use `site.url` and `site.baseurl` as fallbacks.

Thanks!
