### ISSUE TITLE
Document what LSI is actually doing

### ISSUE THREAD

**Issue by cfjedimaster** [jekyll/jekyll#5033]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [X] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [X] This is a feature request.

On the Variables page (https://jekyllrb.com/docs/variables/), the related_posts feature has this to say about it:

"If the page being processed is a Post, this contains a list of up to ten related Posts. By default, these are the ten most recent posts. For high quality but slow to compute results, run the  jekyll command with the --lsi (latent semantic indexing) option. Also note GitHub Pages does not support the lsi option when generating sites."

So, my read of this is that --lsi does something fancy ("semantic indexing" sounds cool!), but the docs don't seem to actually say *what* this means. Is it parsing my content and attempting to find other posts that are similar to it? Is there any way to configure this? For example, what if I want it to just find similar content within the same category? 

I guess my request is - it seems like this is a powerfully cool feature, but there seems to be literally no information about it. (If there is, maybe it could be linked to from here?)

**Comment by DirtyF** [comment]
@cfjedimaster FYI the `--lsi` option makes use of https://github.com/jekyll/classifier-reborn to semantically index posts. AFAIK there are no options available at the moment.

**Comment by parkr** [comment]
@cfjedimaster Would it work to link out to docs of latent semantic indexing? Essentially it's finding a similarity between content on a word-by-word basis using a linear algebraic method.

**Comment by cfjedimaster** [comment]
@parkr Sure. Ideally - a simple sentence ("This feature does X") with a link would be great. You can't go too deep on this page as it is a reference for a lot of stuff already.

**Comment by parkr** [comment]
@cfjedimaster Sounds good to me! Would you mind submitting a pull request to add this to the docs? That content lives on the `master` branch at `site/_docs/variables.md`. 😄 

/cc @jekyll/documentation

**Comment by cfjedimaster** [comment]
Would be glad to - at a conference this week - so it may be a few days.

**Comment by cfjedimaster** [comment]
Thank you @DirtyF - I'm sorry I never got a chance to do this!
