### ISSUE TITLE
Reveal.js slide does not work with Jekyll 3

### ISSUE THREAD

**Issue by xxthermidorxx** [jekyll/jekyll#5034]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [x] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## The Problem I have encountered

I'm hosting reveal.js with my site generated by Jekyll on Github Pages at http://xxthermidorxx.github.io,
repository is https://github.com/xxthermidorxx/xxthermidorxx.github.io.
Since Github Pages began to use Jekyll 3, my reveal.js slide hasn't been working,
like [this slide](https://xxthermidorxx.github.io/2016/05/31/git-best-practice.html#) (I'm sorry but the slide is not written in English).

I try to find out why the slide is not correctly rendered at my local environment with Jekyll 3,
and now I think the reason is because the timing to run the markdown parser has changed.
In reveal.js, when I designate the slide separator like `<section data-separator="\n^---$">`,
[markdown.js](https://github.com/xxthermidorxx/xxthermidorxx.github.io/blob/master/lib/reveal.js/plugin/markdown/markdown.js) recognize '\n^---$' in .md as the slide separator.
But in Jekyll 3, when [markdown.js](https://github.com/xxthermidorxx/xxthermidorxx.github.io/blob/master/lib/reveal.js/plugin/markdown/markdown.js) runs,
the markdown is already parsed into HTML, I mean '---' in .md is parsed into '\<hr />'.

## My Reproduction Steps

Clone the repository, run `$ jekyll serve` with Jekyll3, and access http://localhost:4000/2016/05/31/git-best-practice.html#/.
You will find the slide isn't working.
Originally, you can move to the next or previous slide with the arrow keys.

When I insert `console.log(section.innerHTML);` [here](https://github.com/xxthermidorxx/xxthermidorxx.github.io/blob/master/lib/reveal.js/plugin/markdown/markdown.js#L268),
you can see the markdown has already been parsed into HTML.

## The Output I Wanted

When you run this site with Jekyll 2, you will see the slide properly works
and the markdown has not parsed yet at that line of markdown.js.

## The Things I Want To Ask

Is there a way to change the timing of the parser execution or other countermeasures?
The workaround of this problem is to designate the separator like `<section data-separator="\n^<hr />$">`,
but I think this is a bad know-how.

To make sure, I have already asked at Github Pages support,
but they say this may be a bug or something of Jekyll 3.

**Comment by parkr** [comment]
Hi @xxthermidorxx, I believe this is a limitation of using Markdown here. `---` will always be converted into `<hr />`. Have you tried using `--` or `<!-- break -->` which Markdown may not touch?

Closing as this isn't a Jekyll bug but feel free to reply and I'll see it!

**Comment by xxthermidorxx** [comment]
When I use '--' as a separator in .md, '--' will be parsed into '\<p>--\</p>',
and I have to change the data-separator like this, `<section data-separator="\n^<p>--</p>$">`.

It seems this is not a Jekyll bug, so I'll try changing the data-separator in my HTML.
Thank you for the reply, @parkr.

**Comment by xxthermidorxx** [comment]
This issue is already closed, but now I found a workaround.
This problem is, in short, when `$ jekyll build` runs,
the markdown-written slide of reveal.js is still .md file under `_site/` in Jekyll 2,
but in Jekyll 3, the .md file is converted to .html
and reveal.js cannot recognize the separator `---` because `---` is converted to `<hr />`.

To avoid the .md->.html conversion of Jekyll,
I put the slide file with .html, not .md (the contents of the file is markdown, of course).
