### ISSUE TITLE
A problem occured when execute jekyll serve

### ISSUE THREAD

**Issue by AaronWharton** [jekyll/jekyll#5037]
$ jekyll serve
Configuration file: D:/Users/asus1/AaronWharton.github.io/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-feed or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-feed' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!
jekyll 3.1.6 | Error:  jekyll-feed

What's wrong?I'll be appreciated it if you solve the problem.

**Comment by pathawks** [comment]
```text
gem install jekyll-feed
```

**Comment by AaronWharton** [comment]
Thanks,but I found a new warning:


$ jekyll server
Configuration file: D:/Users/asus1/AaronWharton.github.io/_config.yml
            Source: D:/Users/asus1/AaronWharton.github.io
       Destination: D:/Users/asus1/AaronWharton.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-gist-1.4.0/lib/jekyll-gist/gist_tag.rb:86: warning: constant Jekyll::Gist::GistTag::TimeoutError is deprecated
  Liquid Exception: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed in D:/Users/asus1/AaronWharton.github.io/_posts/2015-08-16-markup-syntax-highlighting.md
jekyll 3.1.6 | Error:  SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Then I delete the file,it worked.I wonder why did it happen...

**Comment by parkr** [comment]
@AaronWharton `Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed` is because your system could not verify the SSL certificate of GitHub's API when [the plugin](https://github.com/jekyll/jekyll-gist) goes to fetch the Gist. You can get around that by adding this to your `_config.yml`:

```yaml
gist:
  noscript: false
```

**Comment by AaronWharton** [comment]
OK,thanks for your guidance.

**Comment by ekremkaraca** [comment]
I have similar issue but I think, it's not related with SSL. Here is mine:

tried to install the gem as shown below (let's say, `jekyll-admin`) :

```shell
    group :jekyll_plugins do
      gem "jekyll-admin", github: "jekyll/jekyll-admin"
    end
```

Installing it directly (without `github: "jekyll/jekyll-admin"`) caused error as shown below:

```shell
    ➜  new-site git:(master) bundle install
    Fetching gem metadata from https://rubygems.org/
    Fetching version metadata from https://rubygems.org/
    Fetching dependency metadata from https://rubygems.org/
    Could not find gem 'jekyll-admin' in any of the gem sources listed in your Gemfile or available on this machine.

    ➜  new-site git:(master) ✗ gem install jekyll-admin
    ERROR:  Could not find a valid gem 'jekyll-admin' (>= 0) in any repository
    ERROR:  Possible alternatives: jekyll-api, jekyll-cdn, jekyll-roman, jekyll-amazon, jekyll-auth
```

I've added gem name in `_config.yml` under `gems` and `whitelist` sections. After installation, when I hit commands below, I got errors shown below respectively:

```shell
    ➜  new-site git:(master) ✗ bundle exec jekyll serve --config _config.yml,_config.dev.yml 
    Configuration file: _config.yml
    Configuration file: _config.dev.yml
      Dependency Error: Yikes! It looks like you don't have jekyll-admin or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-admin' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
    jekyll 3.1.6 | Error:  jekyll-admin

    ➜  new-site git:(master) ✗ jekyll serve --config _config.yml,_config.dev.yml 
    WARN: Unresolved specs during Gem::Specification.reset:
          jekyll-watch (~> 1.1)
    WARN: Clearing out unresolved specs.
    Please report a bug if this causes problems.
    Configuration file: _config.yml
    Configuration file: _config.dev.yml
      Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
    jekyll 3.1.6 | Error:  jekyll-paginate
```

I've also tried to install other gems like jekyll-polyglot but nothing changes.

What goes wrong?

**Comment by parkr** [comment]
@ekremkaraca `jekyll-admin` is not ready to be used in Jekyll yet. Remove that from your `_config.yml` and from your `Gemfile` and we will let you know via the blog on jekyllrb.com when it is ready to use. 😄 Also, always use `bundle exec jekyll serve [options]` and use `bundle install` to install gems in the `Gemfile`.
