### ISSUE TITLE
jekyllrb.com: Add custom 404 page with helpful info 

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#5039]
If you visit a page on jekyllrb.com that does not exist, you get the generic GitHub Pages 404 page.

Instead of this, we should put together a custom page with helpful pointers for finding answers.

/cc @jekyll/documentation

**Comment by adampetrie** [comment]
Im happy to take this on and I took an initial stab in the PR mentioned above. Its not much to look at but hey, it's as start.

What information do you think would be most valuable to include? Right now the main nav gets included but that's it.

**Comment by benbalter** [comment]
Maybe a link to `/docs/` and `/help/`?
