### ISSUE TITLE
Having trouble installing jekyll

### ISSUE THREAD

**Issue by iaavo** [jekyll/jekyll#5040]
- [X] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [X] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [X] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

```
sudo gem install jekyll
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:4:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.10/ext/ffi_c/gem_make.out
```

The steps I did:

sudo gem install jekyll

## The Output I Wanted

Jekyll to be installed.

Why cannot jekyll be apt-get like any other application? It would be so much easier.

**Comment by DirtyF** [comment]
@iaavo make sure you have ruby version > 2 before installing Jekyll 3. 
Jekyll is written in Ruby, and Ruby gems are the way to go when you have to handle ruby packages dependencies.

**Comment by parkr** [comment]
Hey @iaavo! It looks like you're having trouble installing because the development headers aren't available and/or you're using a version of Ruby that is too old.

See our [troubleshooting docs for Installation](http://jekyllrb.com/docs/troubleshooting/#installation-problems) 😄
