### ISSUE TITLE
Unable to use proper links to ssl certs

### ISSUE THREAD

**Issue by Haroenv** [jekyll/jekyll#5046]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

```
$ jekyll serve jekyll s --ssl-cert ~/.ssl/ca.crt --ssl-key /.ssl/ca.key
Configuration file: /Users/haroenv/git/ikhaat/_config.yml
            Source: /Users/haroenv/git/ikhaat
       Destination: /Users/haroenv/git/ikhaat/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.815 seconds.
 Auto-regeneration: enabled for '/Users/haroenv/git/ikhaat'
Configuration file: /Users/haroenv/git/ikhaat/_config.yml
jekyll 3.1.6 | Error:  No such file or directory - /Users/haroenv/git/ikhaat/Users/haroenv/.ssl/ca.crt
```

Can also be reproduced with `/Users/you`, `../../` instead of `~`

## The Output I Wanted

```
Configuration file: /Users/haroenv/git/ikhaat/_config.yml
            Source: /Users/haroenv/git/ikhaat
       Destination: /Users/haroenv/git/ikhaat/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.878 seconds.
 Auto-regeneration: enabled for '/Users/haroenv/git/ikhaat'
Configuration file: /Users/haroenv/git/ikhaat/_config.yml
    Server address: https://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

## Possible source

I think the problem might be [here](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/serve.rb#L185-L188) where you're listening for relative paths instead of absolute paths, but I might be wrong.

**Comment by parkr** [comment]
Hey @Haroenv! Due to our use of [`Jekyll.sanitized_path` when finding the certificates](https://github.com/jekyll/jekyll/blob/1a934125d99598e967cb3f7f2c05a9c59ba738be/lib/jekyll/commands/serve.rb#L185-L188), you'll have to ensure that they are available at **a path within the site's source**. A symlink should work. 

Thanks!

**Comment by Haroenv** [comment]
Okay, I guess that makes sense to require it to be inside the folder, but maybe there could be given some information about that in the `-h` option of `--ssl-cert`  etc? 

Anyway, I can't thank you and the others enough for Jekyll, it's one of the best pieces of software I use.

**Comment by parkr** [comment]
@Haroenv Sure, what do you think we should add? [The options and their help text information are in `lib/jekyll/commands/serve.rb`](https://github.com/jekyll/jekyll/blob/f6dc74933253ae72c2f12389a60fe4e686418823/lib/jekyll/commands/serve.rb#L5-L17).
