### ISSUE TITLE
excerpt_separator is not set to "\n\n" by default as documented.

### ISSUE THREAD

**Issue by carc1n0gen** [jekyll/jekyll#5050]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

1. Deleted the `excerpt_separator` setting from my `_config.yml`
2. Built the site
3. Viewed the site

## The Output I Wanted

The excerpts should have displayed correctly because according to documentation, a double new line should work as a excerpt separator by default.

Instead, the entire article was displayed in the paginator loop.

**Comment by envygeeks** [comment]
The default is "\n\n" and it's shown inside of the configuration: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/configuration.rb#L39 can you provide more information? Are you sure it's not being overridden by a plugin or something else?

**Comment by carc1n0gen** [comment]
I'm using the github_pages gem in my gemfile, does that override the
default separator?

**Comment by pathawks** [comment]
Can you provide a sample project that reproduces the issue, or a link to the source of your site that is exhibiting this behavior?

You haven’t really provided enough information to reproduce the issue.

**Comment by carc1n0gen** [comment]
@pathawks A sample project would be the site I experienced this at: https://github.com/carc1n0gen/carc1n0gen.github.io

**Comment by Crunch09** [comment]
Just tried it and wasn't able to reproduce this 😲 Anybody had more luck?

**Comment by carc1n0gen** [comment]
I decided to try again and what do you know?  IT WORKS.  I have no idea why it wasn't before, but I spent a good half hour banging my head until adding it to my config myself...

**Comment by joallard** [comment]
Whoa... I'm also getting this. Using the Github pages gem, trying to use `\n\n` as separator, and it's not detected. I even tried putting the separator directly in front-matter. Hm.
