### ISSUE TITLE
½ and ¼ are swapped in include variables

### ISSUE THREAD

**Issue by jacobmischka** [jekyll/jekyll#5055]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [x] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

For some reason these two entities are being swapped when in an include variable. I haven't encountered anything else that does this. The entities display correctly when being used in html directly, just not when using an include variable.

`menu.html`:
```
	{% include menu/menu-item-group.html title="Salvo Burgers (&frac12; lb.) & Lil' Debbie Burgers (&frac14; lb.)" dataset=site.data.burgers inline_desc=true %}
```

`menu-item-group.html`:
```
<section class="menu-section">
	<h2>{{ include.title }}</h2>
	<ul class="menu-item-group">
{% for item in include.dataset %}
		<li class="menu-item">{% include menu/menu-item.html item=item inline_desc=include.inline_desc %}</li>
{% endfor %}
	</ul>
</section>
```

Result:
![image](https://cloud.githubusercontent.com/assets/3939997/16572835/a72f4b36-4232-11e6-8194-01ffa1ee3e67.png)

## The Output I Wanted

The intended order of fraction entities (½ then ¼).

**Comment by jacobmischka** [comment]
Ah, the font is just incorrect. I should have guessed this first, apologies, I was tired at the time.

![image](https://cloud.githubusercontent.com/assets/3939997/16592603/240a8160-42a7-11e6-9d63-605d4ced5198.png)

**Comment by parkr** [comment]
No problem! Glad you got it sorted. 😄
