### ISSUE TITLE
jekyll is in violation of bad c rules

### ISSUE THREAD

**Issue by JazzMaster** [jekyll/jekyll#5062]
punched to 316 via ubu 16 in attempt to rebuild my site.
This occurs when using libsafe, which implements on-the-fly range checking for c. (should be standard but isnt yet)

looks like were trying to modify a constant array,which is forbidden(and should be). libsafe has a 'hole' workaround but for some reason the docs on this disappeared on me. will test further. please dont break what works.

Configuration file: /home/me/website/_config.yml
/var/lib/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/configuration.rb:255:in `map!': can't modify frozen Array (RuntimeError)
	from /var/lib/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/configuration.rb:255:in `block in backwards_compatibilize'
	from /var/lib/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/configuration.rb:247:in `each'
	from /var/lib/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/configuration.rb:247:in `backwards_compatibilize'
	from /var/lib/gems/2.3.0/gems/jekyll-3.1.6/lib/jekyll/configuration.rb:198:in `read_config_files'
	from /usr/lib/ruby/vendor_ruby/jekyll.rb:102:in `configuration'
	from /usr/lib/ruby/vendor_ruby/jekyll/command.rb:42:in `configuration_from_options'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:29:in `process'
	from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/vendor_ruby/mercenary/program.rb:42:in `go'
	from /usr/lib/ruby/vendor_ruby/mercenary.rb:19:in `program'

**Comment by envygeeks** [comment]
Jekyll does not use any C code, so these problems belong upstream.  Sorry.
