### ISSUE TITLE
Default site description outputs trailing newline

### ISSUE THREAD

**Issue by brodkewitz** [jekyll/jekyll#5066]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

---

- macOS 10.11.6 Beta (15G24b)
- Jekyll 3.1.6
- github pages 86

Jekyll noob here. It looks like there's a small issue in the rendered HTML using the default site description and theme. The trailing newline after the site description in _config.yml is sneaking through to the final HTML.

``` html
  <meta name="description" content="... and in your feed.xml site description.
">
```

I think this can be remedied either by

1. Adding the YAML strip chomp modifier `>-` in _config.yml
2. Using the `strip_newlines` filter in the template, e.g. `{{ site.description | strip_newlines }}`

I was hoping to submit a pull request using the latter fix (liquid filter), but I can't find _includes/ anywhere in the master branch? Has the default theme been moved to an external source?

**Comment by pathawks** [comment]
`strip_newlines` is *not* an option, because it mangles sentences that span multiple lines.

```
A
B
```

Becomes `AB` instead of `A B`

**Comment by parkr** [comment]
@pathawks With #4917, we can maybe upgrade this for v3.2?

**Comment by pathawks** [comment]
@parkr Is that something that should be fixed here, or in [**jekyll/minima**](https://github.com/jekyll/minima)?

**Comment by parkr** [comment]
@pathawks Yep! Looks like it's defined here: https://github.com/jekyll/minima/blob/master/_includes/head.html#L7
