### ISSUE TITLE
_data file keys and values get assigned as integers, should be strings

### ISSUE THREAD

**Issue by pakamore** [jekyll/jekyll#5071]
EDITED: My bug report was wrong. It's a feature request.

**Comment by parkr** [comment]
Pass both `page.category` and `mycategory` through the `inspect` filter – does `mycategory` have a newline at the end?

**Comment by pakamore** [comment]
The issue was how {% assign %} treats integers.
```
{% capture category_id %}2484881380235357006{% endcapture %}
{{ category_id | inspect }} – &quot;2484881380235357006&quot;
{% assign category_idd = 2484881380235357006 %}
{{ category_idd | inspect }} – 2484881380235357006
```
These values return `false` when comparing with `==` operator. In such case it`s probably my mistake. I should use:
```
{% assign category_idd = "2484881380235357006" %}
```
However, my problem was when these IDs are assigned from a `_data` YML file. There I had:
```
2484881380235357006:
    id: 2484881380235357006
    link: long-permalink
    title: Nice title
```
The key and `id` value were not escaped as strings, and other values were. So I was not able to compare them with other strings from Jekyll (site.*, page.*, etc. – they are all inside quotation marks). When I changed my `_data` YML file to such, everything works fine now:
```
"2484881380235357006":
    id: "2484881380235357006"
    link: long-permalink
    title: Nice title
```
I believe it's a bug. In Liquid docs I was not able to find any methods for converting strings to integers and vice versa. So all values should be strings in Jekyll, no matter whether assigned with `"` or without.
This is especially important in `_data` files. For me it's more common to see keys without `"`. Jekyll `_config.yml` does not put keys inside `"` either.

**Comment by parkr** [comment]
> So all values should be strings in Jekyll, no matter whether assigned with " or without.

Of course, this would break countless sites so we can't do this. What we can do is add filters.

@fw42 👋 Have you ever considered adding type-conversion filters to Liquid? We'd like to be able to run `{{ some_val | to_integer }}` or something similar to convert a value to an integer.

**Comment by crispgm** [comment]
@parkr Is there any way to register Liquid filter in Jekyll?
The ```to_integer``` filter can be easy, but I failed to register the filter unless we add the implementing code in Liquid lib.

**Comment by parkr** [comment]
@crispgm Yes. See the bottom of filters.rb

**Comment by pakamore** [comment]
@parkr, assign format is under the user`s control, so I agree there is no need to change it. But I'm more concerned about `_data` files, where the user has no control how values get assigned.

What I see, the same line (`2: 2`) in the page front matter assigns strings, and in `_data` files it assigns integers. I suggest changing `_data` keys to strings as well. This impacts only those users that have integers in `_data` keys (which is rare) and compare them to page variables `assign`ed as integers. Others that want to compare these keys or values to the variables assigned in a different way, must have their `_data` keys and values as strings already, otherwise it does not work.

**Comment by parkr** [comment]
Users have full control of how `_data` files work, it's just pure YAML. Users have a little less control over how YAML front matter is read, as we convert some values like `date` automatically.

Interesting that data files interprets `2: 2` as `{ 2 => 2 }` but YAML front matter in documents doesn't. It should be using the same underlying YAML parser. Maybe we stringify keys before passing to Liquid.

**Comment by pathawks** [comment]
Why not just put quotes around anything in your YAML that should be a string?

```YAML
---
category: "569738073759577308"
---
```

**Comment by crispgm** [comment]
https://github.com/crispgm/jekyll/blob/dev_to_integer_filter/lib/jekyll/filters.rb#L268

I wrote the ```to_integer``` filter in my fork. @pakamore 
It is pretty simple, can I pr that? @parkr

**Comment by parkr** [comment]
@crispgm Sure! We'll need docs (look for other filters) and a few tests to ensure it doesn't randomly break with strange input like an array or hash.

**Comment by parkr** [comment]
This is an unfortunate reality that I think we have to live with. We've merged the `to_integer` filter and it's been released. Closing this out for now.
