### ISSUE TITLE
Ease Liquid evaluation after/from Converter plugins 

### ISSUE THREAD

**Issue by nhoizey** [jekyll/jekyll#5099]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

I made a "Cloudinarify" Converter plugin that generates [jekyll-cloudinary](https://nhoizey.github.io/jekyll-cloudinary/) Liquid tags from standard Markdown:
https://github.com/nhoizey/nicolas-hoizey.com/blob/7c606257d5659ce0c2006fc74c6d94d4252df5ce/_plugins/cloudinaryfy.rb

The aim is to facilitate publication with standard Markdown in any editor, while providing Cloudinary support when the content is published in a Jekyll site. Best of both worlds.

But, it seems [Liquid tags from posts are parsed before Converters are run](http://stackoverflow.com/questions/38126629/how-is-the-priority-flag-in-jekyll-plugins-supposed-to-work/38312089#comment64048117_38312089), so my Converter must also convert the Liquid tag to HTML.

I tried, but I don't know how to do it, because it needs a context that I don't have in the Converter: https://github.com/nhoizey/nicolas-hoizey.com/blob/7c606257d5659ce0c2006fc74c6d94d4252df5ce/_plugins/cloudinaryfy.rb#L58

I'm aware an issue has already been open to ask for the context in Converters, but it had a negative answer: #1509

I've also found a Pull Request that would allow some Converters to run before Liquid, but it's been closed by @parkr without merging: #917

So, is there a way to run a Liquid render after (or from) a Converter?

**Comment by parkr** [comment]
Have you considered writing a `pre_render` hook?

**Comment by nhoizey** [comment]
Not at all, I will look at it to see if it would be the answer, thanks.
