### ISSUE TITLE
Filters#time should NOT exit; it should raise an error

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#5107]
If you have the Liquid `{{ "" | date_to_xml_string }}`, it will explode with the error:

```text
 Invalid Date: '' is not a valid datetime.
  Liquid Exception: exit in sitemap.xml
```

We should not use `exit(1)` or `abort` in any of our liquid processing code. This should be replaced with a custom error.

@ayastreb, @pathawks, either one of you want to fix this? 😄  Should be fairly straight-forward.

**Comment by pathawks** [comment]
It looks like there is already a custom error.

[filters.rb](https://github.com/jekyll/jekyll/blob/0db1ec339d39cd06f2f91746fcd4b45c827bf655/lib/jekyll/filters.rb#L375-L377):

```ruby
else
  Jekyll.logger.error "Invalid Date:", "'#{input}' is not a valid datetime."
  exit(1)
```

Can we just remove the `exit`? That doesn't seem to break any tests.

**Comment by parkr** [comment]
@pathawks It's `date_to_xmlschema`. Apologies, I misremembered it. Any of [our date functions](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/filters.rb#L63-L107) should raise the errors.

> Can we just remove the exit? That doesn't seem to break any tests.

I'd rather raise an error as `""` is invalid and it usually means some front matter is specified incorrectly.

**Comment by pathawks** [comment]
This still doesn't error for me. I agree that it _should_, but it does not.

All of the date functions call `time` which, [when passed a String that is not a valid date](https://github.com/jekyll/jekyll/blob/0db1ec339d39cd06f2f91746fcd4b45c827bf655/lib/jekyll/filters.rb#L371-L372), calls `to_i`.
`"".to_i` returns `0`.
`Time.at(0)` returns `1970-01-01 00:00:00 UTC`, which is then converted to `localtime` (which works fine) and returned to the date function, which does whatever it is supposed to do.

I created a new Jekyll site with one file.

```haml
---
---

{{ "" | date_to_xmlschema }}
```

When I build this site, `_site/index.html` contains:

```text
1969-12-31T18:00:00-06:00
```

**Comment by parkr** [comment]
@pathawks I wish I could link you to our haystack needles but this occurs all the time. Perhaps it's `nil`. Doing `{{ site.doesnt_exist | date_to_xmlschema }}` – does *that* cause the issue?

**Comment by ayastreb** [comment]
@parkr, @pathawks when I add `{{ site.doesnt_exist | date_to_xmlschema }}` in my jekyll page it just renders empty string without any errors. I run jekyll 3.1.6

However, if I add a test on master which calls the filter with `nil` directly, e.g.
```ruby
# spec/test_filters.rb
@filter.date_to_xmlschema(nil)
```
it does exit with code 1 because of this [line](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/filters.rb#L377).
Not sure why it's not exiting in my local jekyll site 😕 

Should we remove the exit and change it to:
```ruby
  else
    raise ArgumentError, "Invalid Date:", "'#{input}' is not a valid datetime."
```
?

**Comment by parkr** [comment]
@ayastreb Yes, we should raise an error, but I would like to raise a custom error! Add a new error in `lib/jekyll/errors.rb` and raise that error with the text you provided (as one string instead of two).

**Comment by pathawks** [comment]
> Add a new error in `lib/jekyll/errors.rb`

How about [`InvalidDateError`](https://github.com/jekyll/jekyll/blob/v3.2.0.pre.beta1/lib/jekyll/errors.rb#L12)?

**Comment by parkr** [comment]
@pathawks Sure, yeah.
