### ISSUE TITLE
A config setting that limits the amount of pages.

### ISSUE THREAD

**Issue by jp26jp** [jekyll/jekyll#5110]
I started inlining my css with this:

```
{% capture include_to_scssify %}
  {% include _main.scss %}
{% endcapture %}
{{ include_to_scssify | scssify }}
```

but it slowed the build time to about 40 seconds on average. I found the [`limit_posts`](https://jekyllrb.com/docs/configuration/) setting but, currently, my site consists of about 7 posts and 90 pages (split between 5 collections) so this doesn't make much of a difference.

So, my feature request is that a setting be added to limit the amount of pages or limit the collections that can be generated.

**Comment by parkr** [comment]
@jp26jp Is this just for development?

**Comment by chrisfinazzo** [comment]
I have the beginnings of it [here][] if you're interested. Still need to deal with the test failures, but critique away.

[here]: https://github.com/chrisfinazzo/jekyll/tree/limit-pages

**Comment by parkr** [comment]
Yeah I'm not sure about this. Pages are ordered by their path names and limiting what is read and regenerated could be really confusing from a user experience perspective. I'd rather understand more about what the underlying problem is. I have a feeling the solution is elsewhere.

**Comment by jp26jp** [comment]
No, it's not for development. It's in production.

When you say the underlying solution is elsewhere, where else could it be?

**Comment by jp26jp** [comment]
I'm happy to send any debug or build info you need

**Comment by parkr** [comment]
@jp26jp The `limit_posts` option means you _only_ generate a certain number of posts (as opposed to _all_ posts). This is helpful when you're writing your latest post – pass `--limit_posts 1` and only the latest post will be regenerated. It is meant to make development faster, but is not meant to be used at all in a production setting (where you need the _entire_ site).

Do you mean to suggest a `limit_pages` option which only generates a certain number of pages? Only a subset of the site would be available on a clean `_site` directory. If you want the full site, you may be an excellent candidate for `--incremental`, our [Incremental Regeneration feature](https://jekyllrb.com/docs/configuration/#incremental-regeneration) (still in beta). With Incremental Regeneration, only what changes is regenerated.

**Comment by chrisfinazzo** [comment]
@jp26jp If it's a config option, this sounds more and more like a batch generation kind of idea for sites that aren't primarily blogs. It's niche, but I can see the appeal in some circumstances.

@parkr Could Jekyll use something like Octopress' [isolate][] command to achieve this kind of behavior?

[isolate]: https://github.com/octopress/octopress/blob/master/lib/octopress/isolate.rb

**Comment by jp26jp** [comment]
Whoops, yes, `limit_pages` would be for development. Sorry, I somehow read that as would I use `limit_pages` for prototyping.

Oh wow. `--incremental` is exactly what I was needing. I'm so sorry for overlooking this feature and taking up your time! Thank you both for your help!

**Comment by jp26jp** [comment]
It might help to add a tip next to `limit_posts` that links to `--incremental` so dummies like me know that they're conceptually similar.
