### ISSUE TITLE
post['name'] and post.name changes

### ISSUE THREAD

**Issue by i2000s** [jekyll/jekyll#5121]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Ubuntu 16.04*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [x] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [x] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

I have upgraded Jekyll from 2.5.3 to 3.1.6, and at least one of my plugin was broken. The problem is on the way a filename of a post is not retrieved consistently with the previous version. 

Assume I have defined my post `permalink: /:year/:month/:day/:title.html`, and I have a post named as `2016-07-19-welcome.md` in the `_posts` directory. 
In the plugin Ruby file, I can use something like 

```
site.posts.each do |post|
        post.data['path'] = post.name
        puts post.data['path'] # For debugging post names.
end
```
to retrieve the file names of each post in Jekyll 2.5.3. The output as ***expected*** is
```
2016-07-19-welcome.md
```

In Jekyll 3.1.6, I adapted my code to 
```
site.posts.docs.each do |post|
        post.data['path'] = post['name']
        puts post.data['path'] # For debugging post names.
end
```
due to `post.name` is not a valid variable now. However, the output is no longer what I expect to get as the earlier version. Instead, it gives me only the last part of the filename, that is 
```
welcome
```

I have also tried to use `post.url` instead, and it yielded `/2016/07/19/welcome.html`. If it can be transferred to `2016-07-19-welcome` in some comprised way, I would be happy as well.

Should Jekyll make retrieving filename of posts consistent with both 2.x and 3.x versions? I didn't find this change was documented anywhere in the "Upgrading from 2.x to 3.x" document. Maybe I have used a wrong way to retrieve the filename of the post in ruby. A related [issue](https://github.com/jekyll/jekyll/issues/633) doesn't help me on retrieving filenames in Jekyll plugin code. Should you regard this as a bug or tell me what I have missed to retrieve the correct filename? 

Thanks!

**Comment by tekknolagi** [comment]
Hi @i2000s,

I believe you could do something like `File.basename(post.path)`, because `post.path` returns the absolute path to the post, like `/Users/tekknolagi/Documents/code/mysite/_posts/2016-03-16-some_post.md`.

Max

**Comment by i2000s** [comment]
@tekknolagi Yeah, what I did to retrieve the path is as you said, `{% capture true_path %}{{ page.path | replace '_posts'}}{% endcapture %}`. Maybe I don't need the replace. But I kind of preferring to have the `name` tag behave the same as previous versions.

**Comment by tekknolagi** [comment]
@i2000s posts became documents within a Posts collection, so the structure changed some. .`path` is now the proper way to get the filename.

**Comment by i2000s** [comment]
Gotcha. With that I guess I will adapt to the change and close this issue for now. Thank you, @tekknolagi .

**Comment by tekknolagi** [comment]
No problem.
