### ISSUE TITLE
remove all unnecessary spaces.

### ISSUE THREAD

**Issue by carlosdelfino** [jekyll/jekyll#5125]
When do programming using directives Liquid, many unnecessary spaces is inserted due to the use of indenting, a practice that I hold and I think important for code readability.

But this in HTML can become a hell, and make the final file very dowdy and a bit larger than necessary, I know that with current technologies it is irrelevant from a certain point of view, but in maintaining the generated code to the browser, ease if there was an option in Jekyll so he cleared the code unnecessary spaces.

It is possible?

- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

**Comment by budparr** [comment]
Not entirely sure I understand what you're after, but maybe this will help: Compress HTML in Jekyll http://jch.penibelst.de/

**Comment by carlosdelfino** [comment]
is the way.

I will try, thank you.

**Comment by envygeeks** [comment]
This is an upstream problem. And the I don't consider it a problem because
collapsing whitespace is expensive.

**Comment by carlosdelfino** [comment]
i works, testing.

Thanks.

**Comment by parkr** [comment]
Dupe of https://github.com/Shopify/liquid/issues/216
