### ISSUE TITLE
install jeckyll

### ISSUE THREAD

**Issue by Chris511990** [jekyll/jekyll#5133]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

**Comment by parkr** [comment]
Hi! Sorry to hear you're having trouble getting Jekyll up and running. 

This doesn't look like a bug in Jekyll. We are trying to keep our issue tracker for only bugs and feature requests. Try taking a look through our [installation instructions](http://jekyllrb.com/docs/installation/) and asking on [our forum](https://talk.jekyllrb.com) if you still can't get it to work.

Thanks!
