### ISSUE TITLE
Can't start local jekyll server

### ISSUE THREAD

**Issue by dlin303** [jekyll/jekyll#5145]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps
Did a fresh gem install of jekyll 3.2.0 and tried to serve it

```
$ gem install jekyll
$ jekyll new testblog
$ cd testblog
$ jekyll serve
```
Got this error:

```
Configuration file: /Users/Daron/Development/testblog/_config.yml
            Source: /Users/Daron/Development/testblog
       Destination: /Users/Daron/Development/testblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
     Build Warning: Layout 'post' requested in _posts/2016-07-28-welcome-to-jekyll.markdown does not exist.
  Liquid Exception: no implicit conversion of nil into String in about.md
jekyll 3.2.0 | Error:  no implicit conversion of nil into String
```

## The Output I Wanted
But if i `gem uninstall jekyll` and reinstall v3.1.6 `gem install jekyll -v 3.1.6`, everything works fine.

```
$ rm -rf testblog
$ gem uninstall jekyll
$ gem install jekyll -v 3.1.6
$ jekyll new testblog
$ cd testblog
$ jekyll serve
```
I get what I expect:

```
Configuration file: /Users/Daron/Development/testblog/_config.yml
            Source: /Users/Daron/Development/testblog
       Destination: /Users/Daron/Development/testblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.646 seconds.
 Auto-regeneration: enabled for '/Users/Daron/Development/testblog'
Configuration file: /Users/Daron/Development/testblog/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

I'm completely new to jekyll, but wanted to give you all the headsup in case there's something wrong with latest 3.2.0 release since it's only 4 hours old.

**Comment by envygeeks** [comment]
Hi @dlin303,

Can you please re-run your command with `--trace` so that we can trace a regression path.  Thanks!

**Comment by ruisaraiva19** [comment]
I have the same problem...
![jekyll error](https://cloud.githubusercontent.com/assets/7356098/17202737/ff028022-5492-11e6-8e79-e43f0ffada16.png)

**Comment by D14RAP** [comment]
+1

**Comment by Crunch09** [comment]
@envygeeks `theme.includes_path` is nil at [this point](https://github.com/jekyll/jekyll/blob/26f1ea24871c545fe53bbcc313dbc5d437d46915/lib/jekyll/site.rb#L433) which results in the error. I think the cause of the problems is that the `_layouts`, `_includes` and `_sass` directory of `minima` is excluded in the [.gemspec](https://github.com/jekyll/minima/blob/bad702267b0e2a1ef7b899d0a898562febced4e4/minima.gemspec#L15). I'll send a PR to add them!

**Comment by sasivarnan** [comment]
I am still facing this issue. Any idea?

**Comment by Crunch09** [comment]
There needs to be a new release of minima before this will be fixed for
everyone.

Am 28.07.2016 7:00 nachm. schrieb "Sasivarnan R" <notifications@github.com>:

**Comment by sasivarnan** [comment]
@Crunch09 Thanks for the reply. 

For now, I downloaded the [jekyll/minima](https://github.com/jekyll/minima) repo and placed the files inside my site directory.

Now I am facing #4677 Issue.

**Comment by benbalter** [comment]
I'm still getting this issue, even with v1.0.1 of minima. 

I've traced the problem to the fact that `Theme#path_for` always returns `nil` for Gem-distributed themes, because `Jekyll.sanitized_path` double-prepends the root resulting in an root + root + path, which is an invalid file.

**Comment by Crunch09** [comment]
Somehow i can't reproduce it, if i put an `puts "PATH: #{path}"` after this [line](https://github.com/jekyll/jekyll/blob/94af8ca75a97449af5f2dcf4b78aab64fb528c8c/lib/jekyll/theme.rb#L40) i get:

<img width="482" alt="screen shot 2016-07-28 at 21 05 35" src="https://cloud.githubusercontent.com/assets/570608/17225896/1774f530-5507-11e6-819a-89e538db80b7.png">

**Comment by benbalter** [comment]
Digging deeper, it looks like it's only going to affect symlinked gems, which in my case, is the default for rbenv/homebrew.
