### ISSUE TITLE
3.2.0 broken on Windows

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll#5146]
So, after the AppVeyor addition in #5115, I saw the errors and hoped someone would fix them. Now, 3.2.0 is out and doesn't work on Windows.

https://ci.appveyor.com/project/jekyll/jekyll/build/70

https://ci.appveyor.com/project/XhmikosR/mpc-hc-org/build/618/job/cs11cftl184q4po4

So, someone should really try and fix tests on Windows now that we have CI and all.

/CC @parkr

**Comment by parkr** [comment]
> So, someone should really try and fix tests on Windows now that we have CI and all.

@XhmikosR I really appreciate that this is important to you, but we can't drop all we're doing to help. You have a Windows machine, right? Could you lend an hour to help fix these?

Slated for v3.2.1. Sorry for the issue.

**Comment by XhmikosR** [comment]
Well, it's not a small part of your users that are on Windows.

And this was pretty obvious due to the CI failures.

If I had the needed Ruby knowledge I would have submitted a fix, you know
that.

**Comment by parkr** [comment]
This will go out in 3.2.1.

**Comment by wespollek** [comment]
I am having this same path issue, would you know when 3.2.1 is coming? and is there anyway to revert to an older working version in the interim? Thank you for the continued effort! @parkr

**Comment by parkr** [comment]
@wespollek Yes, 3.2.1 will come out tomorrow U.S. Pacific time. In the meantime you can do:

```
$ gem uninstall jekyll
$ gem install jekyll -v 3.1.6
```

to downgrade 😄

**Comment by MJWlodarczyk** [comment]
![jekyll_release](https://cloud.githubusercontent.com/assets/20464496/17322068/f9a1a47a-589b-11e6-81b9-02ab332400c2.PNG)

tommorow mean when, talking about commented 3 days from now :D ?

**Comment by DirtyF** [comment]
@MJWlodarczyk Weird, this comment was posted only a few hours ago.

**Comment by parkr** [comment]
@MJWlodarczyk How interesting! That might be a JavaScript bug on GitHub's side.

**Comment by parkr** [comment]
@MJWlodarczyk What browser & browser version are you using? What is your timezone?
