### ISSUE TITLE
Jekyll bot should automatically create a new GitHub release from the history when a new release is cut

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#5148]
See, e.g.,:

![screen shot 2016-07-28 at 9 37 01 am](https://cloud.githubusercontent.com/assets/282759/17214417/d92de5da-54a6-11e6-8147-cfec2ce7d073.png)

It'd be cool if, when 3.2 was cut, @jekyllbot automatically pulled the changelog from the history and created/tagged a new release.

**Comment by parkr** [comment]
Great idea! I thiiiiink there is a webhook event for tags, but I'll double check.

**Comment by pathawks** [comment]
Should the chanelog update and tag happen _before_ or _after_ a Gem is cut? ie: Shouldn’t the v3.2.0 gem map exactly to the v3.2.0 tag?

**Comment by jake-low** [comment]
Chiming in: IMO the v3.2.0 gem should correspond exactly to the v3.2.0 tag. A pretty typical workflow for releasing from a git repo is to create a commit which updates the changelog, then tag that commit as `vX.Y.Z` (and ideally sign the tag), and finally push both. There's even a [gem by tpope](https://github.com/tpope/git-bump) that automates this sort of workflow.

In this model, a CI/CD system is configured to build release bits for any new tag, and publish them. This ensures that tags are always lined up with the logically corresponding binary releases.

**Comment by parkr** [comment]
Done: https://github.com/jekyll/jekyll/releases/tag/v3.2.0

> IMO the v3.2.0 gem should correspond exactly to the v3.2.0 tag. 

We commit an empty "Release :gem: vX.X.X", tag it, push both to the repo, then build the gem and release. It's all the same ref. 😄

**Comment by jake-low** [comment]
Sweet, thanks for the clarification. Love the :gem: emoji in the commit message, BTW, hadn't noticed that before.

**Comment by parkr** [comment]
This is my new favourite thing. It was so tedious to create these releases!

![screen shot 2016-08-02 at 5 08 50 pm](https://cloud.githubusercontent.com/assets/237985/17349573/e24fed9e-58d3-11e6-8781-7b6274cc7334.png)

**Comment by benbalter** [comment]
![screen shot 2016-08-03 at 10 37 32 am](https://cloud.githubusercontent.com/assets/282759/17369430/570a33a0-5966-11e6-946b-837f753e170f.png)

💖
