### ISSUE TITLE
3.2: "Explicit support for Ruby 2.0.x dropped" but OS X ships with 2.0

### ISSUE THREAD

**Issue by kainjow** [jekyll/jekyll#5151]
Does this mean Jekyll now requires installing a new version of Ruby to use on OS X if we want to ensure it works, since 2.0 is no longer being tested? The [installation docs](https://jekyllrb.com/docs/installation/) specifically says "v2 or above for Jekyll 3".

**Comment by DirtyF** [comment]
It depends what OS X version you're running, on OS X 10.11:

```
❯ /usr/bin/ruby -v    
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
```

But yeah, basically you would need to install a proper Ruby version. 
I personnaly use `brew` and `rbenv` to do so.

**Comment by kainjow** [comment]
No, I haven't tested 3.2, but if 2.0 is not being tested, then I would assume it would eventually break. Might be less of an issue once 10.12 is out and (hopefully) Ruby is > 2.0.

**Comment by envygeeks** [comment]
Jekyll silently dropped support for 2.0.0 when Ruby dropped support for it (it's EOL.) see https://github.com/jekyll/jekyll/issues/4381 for more information.  You should be able to still install Jekyll on 2.0.x as we never increased our required version (it might be a dependency that has changed their required versions.)

On either hand, we do not worry about whether or not OS X still has 2.0 as that is a problem for Apple, we follow the official Ruby which dropped support for 2.0.x this year entirely, we do not feel the need to maintain our software on old Rubies that Ruby maintainers themselves do not wish to maintain anymore. 

If you are having a specific problem, can you please post the error as we do look into some problems on a case-by-case but there are no promises we will maintain support for 2.0.x anymore or even consider fixing an error if it will cause a regression, just to support what Apple does.

**Comment by kainjow** [comment]
Fair enough. I'll look into using rbenv, maybe we can put together as simple as possible instructions for upgrading Ruby on OS X.
