### ISSUE TITLE
Default site fails to build on Jekyll 3.2.x

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#5153]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

```
➜  jekyll git:(master) git pull
Already up-to-date.
➜  jekyll git:(master) be jekyll new test-site
New jekyll site installed in /Users/benbalter/projects/jekyll/test-site.
➜  jekyll git:(master) ✗ cd test-site
➜  test-site git:(master) ✗ be jekyll serve --verbose
```

## The Output I Wanted

🎉 your site is built!

## The Output I got

```
Logging at level: debug
Configuration file: /Users/benbalter/projects/jekyll/test-site/_config.yml
         Requiring: kramdown
            Source: /Users/benbalter/projects/jekyll/test-site
       Destination: /Users/benbalter/projects/jekyll/test-site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
           Reading: _posts/2016-07-28-welcome-to-jekyll.markdown
         Rendering: _posts/2016-07-28-welcome-to-jekyll.markdown
  Pre-Render Hooks: _posts/2016-07-28-welcome-to-jekyll.markdown
  Rendering Liquid: _posts/2016-07-28-welcome-to-jekyll.markdown
         Requiring: rouge
  Rendering Markup: _posts/2016-07-28-welcome-to-jekyll.markdown
         Requiring: kramdown
  Rendering Layout: _posts/2016-07-28-welcome-to-jekyll.markdown
     Build Warning: Layout 'post' requested in _posts/2016-07-28-welcome-to-jekyll.markdown does not exist.
         Rendering: about.md
  Pre-Render Hooks: about.md
  Rendering Liquid: about.md
  Liquid Exception: no implicit conversion of nil into String in about.md
jekyll 3.2.0 | Error:  no implicit conversion of nil into String
```

So it seems:

1. Jekyll can't find the `post` layout
2. Something in `about.md` (the includes?) fail the build.

**Comment by Crunch09** [comment]
@benbalter Hi, i think this is the same issue as #5145

**Comment by benbalter** [comment]
Nice catch. Closing in favor of #5145.
