### ISSUE TITLE
[jekyll 3.2.0] Liquid concat not working

### ISSUE THREAD

**Issue by Jetroid** [jekyll/jekyll#5160]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps
Testing Locally: 
Copy example from [here](https://help.shopify.com/themes/liquid/filters/array-filters#concat) to new file,
test.html
```
---
---
{% assign fruits = "apples, oranges, peaches, tomatoes" | split: ", " %}
{% assign vegetables = "broccoli, carrots, lettuce, tomatoes" | split: ", " %}

{% assign plants = fruits | concat: vegetables %}

{{ plants | join: ", " }}
```
run 'jekyll s' in terminal, no problems.
Navigate to 127.0.0.1:4000/test in browser,
find
```
apples, oranges, peaches, tomatoes
```
Note that this is simply the contents of the fruits array.

## The Output I Wanted
```
apples, oranges, peaches, tomatoes, broccoli, carrots, lettuce, tomatoes
```

**Comment by admhlt** [comment]
The `concat` filter was added to Liquid by Shopify, and is not in "core" Liquid. As such, it works in Shopify stores but not on Jekyll sites. If you know Ruby, you could code a Jekyll plugin for the filter yourself.

**Comment by parkr** [comment]
@admhlt Any reason it shouldn't be in Liquid core? Worried about excess memory, maybe?

**Comment by admhlt** [comment]
That's beyond me. Maybe @fw42 has some insight?

**Comment by Jetroid** [comment]
>  If you know Ruby, you could code a Jekyll plugin for the filter yourself.
Easy enough, thanks.

Is there a maintained list of the features of Liquid Core? My searches don't turn up anything, an concat appears in Shopfiy/Liquid/lib/liquid/standardfilters.rb, so doesn't appear to be an 'extension' in any way I can percieve.

**Comment by admhlt** [comment]
You're right, it is in there, @Jetroid — my mistake. I'm going to look into this some more and see if I can't find out what's going on.

**Comment by Crunch09** [comment]
@admhlt I can't find it in [Liquid 3.0](https://github.com/Shopify/liquid/blob/3-0-stable/lib/liquid/standardfilters.rb) which jekyll is currently using. I think this should be the reason?

**Comment by admhlt** [comment]
That was going to be my next guess. :) Sounds like that's it. Thanks @Crunch09. `concat` has been added in a newer version of Liquid, which Jekyll isn't using yet.

**Comment by Jetroid** [comment]
Good detective work! 
Thanks all.

**Comment by envygeeks** [comment]
I think we intentionally held off on using Liquid 4 because it brought some changes that we couldn't accept in a minor version, we should probably revisit it and see exactly what all breaks to prepare for the future.

**Comment by parkr** [comment]
I was planning on taking a look at this for 3.3.0. Does that sound
reasonable, assuming all plugins do not require changes?

**Comment by Crunch09** [comment]
Does anyone know an ETA for Liquid 4 (stable) ? The last Release Candidate was released on [March 31](https://rubygems.org/gems/liquid).

**Comment by DirtyF** [comment]
@Crunch09 I didn't found a proper Roadmap for Liquid v4 maybe @pushrax or @fw42 can enlighten us.
