### ISSUE TITLE
I get Liquid Exception: no implicit conversion of nil into String in about.md when I try to run the Quick-start example 

### ISSUE THREAD

**Issue by adam-arold** [jekyll/jekyll#5170]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

I simply run the following commands from the Quick-start example page:
```
~ $ gem install jekyll
~ $ jekyll new myblog
~ $ cd myblog
~/myblog $ jekyll serve
```

I get the following error:

> $ jekyll serve
> Configuration file: E:/myblog/_config.yml
>             Source: E:/myblog
>        Destination: E://myblog/_site
>  Incremental build: disabled. Enable with --incremental
>       Generating...
>      Build Warning: Layout 'post' requested in _posts/2016-07-30-welcome-to-jekyll.markdown does not exist.
>   Liquid Exception: no implicit conversion of nil into String in about.md
> jekyll 3.2.0 | Error:  no implicit conversion of nil into String

## The Output I Wanted

I wanted it to work.

**Comment by jake-low** [comment]
Hi @adam-arold,

I was unable to reproduce your issue using Jekyll 3.2.0 (the same version you're using) and minima 1.0.1. What versions of minima do you have? You can check using `gem list`.

**Comment by adam-arold** [comment]
I have minima (1.0.1).

**Comment by jake-low** [comment]
I agree; the maintainers have two PRs (#5168 and #5169) open to address this. v3.2.0 just came out a couple days ago and the docs haven't quite caught up yet. Glad you figured it out!

**Comment by adam-arold** [comment]
I think the problem is that running the command which creates a new project is buggy because it did not create the necessary layout file thus:

> Build Warning: Layout 'post' requested in _posts/2016-07-30-welcome-to-jekyll.markdown does not exist.

If I create a direcory named `_layouts` and put `default.md` `page.md` and `post.md` in it the problem is solved. But in this case I get another error:

> jekyll 3.2.0 | Error:  different prefix: "/" and "E:/my-awesome-site"

What could be the problem?

**Comment by adam-arold** [comment]
[Related issue](https://github.com/jekyll/jekyll/issues/4677)
Seems like this thing got broken since `3.1.6`. I reverted from `3.2.0` to `3.1.6` and jekyll serve now works without problem. So this is actually two issues:
- The site generated by the `jekyll new` command is broken in `3.2.0`
- In `3.2.0` windows users can't get this working because of [Related issue](https://github.com/jekyll/jekyll/issues/4677)

**Comment by jake-low** [comment]
3.2.1 will hopefully be out Monday and will solve these issues. (See #5159).

**Comment by parkr** [comment]
@adam-arold 3.2.1 should fix this for you! http://jekyllrb.com/news/2016/08/02/jekyll-3-2-1-released/

**Comment by sunny-chung** [comment]
Reproduced in 3.3.1.

` Incremental build: disabled. Enable with --incremental
      Generating... 
     Build Warning: Layout 'post' requested in _posts/2017-01-26-welcome-to-jekyll.markdown does not exist.
  Liquid Exception: no implicit conversion of nil into String in about.md
jekyll 3.3.1 | Error:  no implicit conversion of nil into String`

**Comment by parkr** [comment]
@sunny-chung fixed by https://github.com/jekyll/jekyll/pull/5750. keep an eye out for 3.4.0.
