### ISSUE TITLE
Unable to resolve Page build failed?

### ISSUE THREAD

**Issue by AidanDai** [jekyll/jekyll#5174]
the email come from `github`

>The page build failed with the following error:

>Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.

>For information on troubleshooting Jekyll see:

>https://help.github.com/articles/troubleshooting-jekyll-builds

>If you have any questions you can contact us by replying to this email.

I infer the error is from [https://help.github.com/articles/generic-jekyll-build-failures/](https://help.github.com/articles/generic-jekyll-build-failures/) based on this email, but don't ideal to result the error. all areadly reason isn't remove.

Working with continuous integration services

Travis CI: [https://travis-ci.org/AidanDai/AidanDai.github.io/builds/148785056](https://travis-ci.org/AidanDai/AidanDai.github.io/builds/148785056)

jekyll talk issue:
[https://talk.jekyllrb.com/t/the-page-build-failed-on-githup-pages-online-when-i-commit-from-local/2653](https://talk.jekyllrb.com/t/the-page-build-failed-on-githup-pages-online-when-i-commit-from-local/2653)

lasted but important the local is fine;

ruby and gem env at local:

```
ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]

gem -v
2.4.5.1

jekyll -v
3.1.6
```
I am search result method, but don't

can you help me?

**Comment by parkr** [comment]
Hey! For GitHub Pages, we can't help you here. You have to reply to that email. 😄

**Comment by AidanDai** [comment]
@parkr, I haved to replay the email, but nobody care this.

**Comment by ViKapitoshka** [comment]
@AidanDai , you solved the problem?
