### ISSUE TITLE
Jekyll will not serve 

### ISSUE THREAD

**Issue by markwright785** [jekyll/jekyll#5184]
``/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.2.0/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.2.0/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'``

i get this error when trying to using jekyll serve.

**Comment by parkr** [comment]
Hey @markwright785! Run `gem install bundler` and you should be set. 👍

**Comment by markwright785** [comment]
@parkr i ran gem install bundler 

and got this Error? 

ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/bundle

**Comment by parkr** [comment]
@markwright785 Using the system Ruby on Mac is problematic for lots of users due to these permissions errors. We recommend using the Homebrew version of Ruby. Do you have it installed?

```text
$ brew install ruby
$ gem install bundler jekyll
$ jekyll new hello
$ cd hello
$ bundle install
$ bundle exec jekyll serve
```

**Comment by markwright785** [comment]
@parkr installed ruby via brew and then $ gem install bundler jekyll give me the same error as before

**Comment by parkr** [comment]
@markwright785 Try closing your Terminal and re-opening. What is the output of `which ruby` and `which gem`?

**Comment by markwright785** [comment]
@parkr 
unsure if this is right
/usr/bin/ruby 
/usr/bin/gem

**Comment by parkr** [comment]
@markwright785 Try `brew doctor`. Is it linked? Maybe try `brew link ruby`
