### ISSUE TITLE
Why Jekyll need NodeJS installed ？

### ISSUE THREAD

**Issue by GuoZhiQiang** [jekyll/jekyll#5191]
I don't know why NodeJS(or other JavaScript runtime) need been installed as the description in [Requirements](https://jekyllrb.com/docs/installation/). Is the NodeJS necessary? What would happened if i did not install NodeJS ? My OS is EI Capitan ,Chrome is my main browser. Thanks.

**Comment by jake-low** [comment]
Hi @GuoZhiQiang,

I think NodeJS is only needed if you want to write CoffeeScript and have Jekyll compile it for you. You don't need to install it if you don't plan to write CoffeeScript.

**Comment by GuoZhiQiang** [comment]
Thank U @jake-low

**Comment by envygeeks** [comment]
Yes, NodeJS or RubyRacer (or hopefully soon MiniRacer) are what's needed only if you wish to use CoffeeScript, otherwise you can skip the dependency and Jekyll won't notice.
