### ISSUE TITLE
Unable to install jekyll in Ubuntu 16.04

### ISSUE THREAD

**Issue by satwikkansal** [jekyll/jekyll#5193]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

![screenshot from 2016-08-03 15-46-11](https://cloud.githubusercontent.com/assets/10217535/17362175/80ec43f4-5991-11e6-81e1-eecac9f1d172.png)
![screenshot from 2016-08-03 15-46-21](https://cloud.githubusercontent.com/assets/10217535/17362177/8424d6d0-5991-11e6-89a5-18292054a572.png)

**Comment by ashmaroli** [comment]
You seem to be missing the required permission /and tools to install jekyll. Additionally you seem to have entered `udo` instead of `sudo` at certain places.

Watch this [video](http://jekyll.tips/jekyll-casts/install-jekyll-on-linux/) for additional help

**Comment by satwikkansal** [comment]
That worked liked a charm.. Thanks!
