### ISSUE TITLE
Jekyll doesn't parse correctly sass

### ISSUE THREAD

**Issue by dcdeiv** [jekyll/jekyll#5200]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

---

I am developing a theme in Jekyll and of course I am using sass.
I am on Ubuntu 16.04 LTS:
```bash
$ ruby -v
ruby 2.3.1p112 (2016-04-26) [i386-linux-gnu]
$ jekyll -v
jekyll 3.2.1
$ sass -v
Sass 3.4.22 (Selective Steve)
```

It seems Jekyll doesn't parse correctly sass. Especially this snippet doesn't output the way it should:

```sass
button, .button,
input[type="button"], input[type="submit"],
input[type="reset"]
  // Code

  &.primary
    &, &:visited
      //   Code
```
which outputs:

```css
button.primary, button.primary:visited,
.button.primary, .button.primary:visited,
input.primary[type="button"], input.primary[type="button"]:visited,
input.primary[type="submit"], input.primary[type="submit"]:visited,
input.primary[type="reset"], input.primary[type="reset"]:visited
```

Notably the main error is that Jekyll parse the code above in this way: `input.primary[type="button"]:visited` instead of in the correct way : `input[type="button"].primary:visited`.

I tested my sass theme using the sass processor

```bash
$ sass main.sass main.css
```
and it outputs correctly:

```css
button.primary, button.primary:visited, .button.primary, .button.primary:visited,
input[type="button"].primary, input[type="button"].primary:visited,
input[type="submit"].primary, input[type="submit"].primary:visited,
input[type="reset"].primary,  input[type="reset"].primary:visited
```

I also tested it on [sassmeister](http://www.sassmeister.com/) and it also process my theme correctly. See [gist](https://gist.github.com/dcdeiv/22ee1410598dc898b0b63caf69a076a7).

This issue occurs while using both jekyll and github-pages gems.

**Comment by DirtyF** [comment]
@dcdeiv I tested your gist with latest Jekyll with Sass default options, and I see [no difference](https://gist.github.com/DirtyF/a9abecb77ed1c1536686f400a629d48e) with Sassmeister output.

![sass-diff](https://cloud.githubusercontent.com/assets/103008/17410095/882d342a-5a72-11e6-9279-dfbbee9657ff.png)

**Comment by pathawks** [comment]
What is the difference between

```css
input.primary[type="button"]:visited
```

and

```css
 input[type="button"].primary:visited
```

Aren’t they both functionally identical??

**Comment by dcdeiv** [comment]
@pathawks ehrm no.

`input[type="button` selects inputs whose attribute is type="button".

`input` select all inputs.

`.primary[type="button"]` doesn't mean anything.

**Comment by dcdeiv** [comment]
@DirtyF  As soon as I have some time I will run some other test again

**Comment by dcdeiv** [comment]
Uhm. I am a little confused!

This is what firefox shows me:
![firefox](https://cloud.githubusercontent.com/assets/6809907/17412142/71936e74-5a7b-11e6-84b1-aadc4ba3e70a.png)

And this is what chromium shows te me:
![chromium](https://cloud.githubusercontent.com/assets/6809907/17412157/87314e72-5a7b-11e6-8a10-03441af5ab0b.png)

So I guess that this is an issue of Firefox and not Jekyll itself.

**Comment by dcdeiv** [comment]
Well Thank you anyway!

**Comment by envygeeks** [comment]
Any SASS bugs belong upstream at SASS, we do nothing to alter it other than strip the front matter.
