### ISSUE TITLE
change in directory structure and instructions in gemfile in 3.2.1 lead to build fail

### ISSUE THREAD

**Issue by Strangehill** [jekyll/jekyll#5201]
- [x] I believe this to be a bug, not a question about using Jekyll.

- [x] I am on (or have tested on) ***macOS*** 10+

- [x] I was trying to build.

## My Reproduction Steps

```
$ jekyll -v
jekyll 3.2.1

$ jekyll new .
New jekyll site installed in /Users/cog/Dropbox/quick-test-4.
```

In Gemfile, following instructions within:
- Commented this line
  - `# gem "jekyll", "3.2.1"`
- and uncommented one line
  - `gem "github-pages", group: :jekyll_plugins`

`$ bundle install` is succesful

Then `$ bundle exec jekyll build` fails:

```
Configuration file: /Users/cog/Dropbox/quick-test-4/_config.yml
            Source: /Users/cog/Dropbox/quick-test-4
       Destination: /Users/cog/Dropbox/quick-test-4/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
     Build Warning: Layout 'post' requested in _posts/2016-08-05-welcome-to-jekyll.markdown does not exist.
  Liquid Exception: The included file '/Users/cog/Dropbox/quick-test-4/_includes/icon-github.html' should exist and should not be a symlink in about.md
jekyll 3.1.6 | Error:  The included file '/Users/cog/Dropbox/quick-test-4/_includes/icon-github.html' should exist and should not be a symlink
```

**Comment by DirtyF** [comment]
@Strangehill It's because GIthub-Pages still uses Jekyll 3.1.6 for now and Jekyll 3.2.1 new default site template use gem-based `theme`. Juste create a new default site with Jekyll 3.1.6 and you will be fine.

**Comment by Strangehill** [comment]
got it, thanks.
So insert an extra step (`bundle exec jekyll new . -f`) in the steps I took right before `bundle exec jekyll build`. This is a tricky getting started procedure till github-pages upgrades to Jekyll 3.2.

in sum, the way to go about it for now is:
```
$ jekyll new .
$ # make changes to Gemfile
$ bundle install
$ bundle exec jekyll new . -f
$ bundle exec jekyll serve
```

**Comment by envygeeks** [comment]
As of tonight Github Pages is not on Jekyll 3.2, this should no longer be an issue.  That said, Github-Pages is not a Jekyll Plugin, rather a replacement to Jekyll.  One should either choose to do "jekyll" or "github-pages" not both at the same time, as Github Pages brings in it's own supported version of Jekyll.

**Comment by Strangehill** [comment]
Not just for github-pages, but anyone listing a gem version of Jekyll older than 3.2.

If this `gem "jekyll", "3.1.6"` was the only change, the same error would happen. 

Would adding 
> However, if you want to use a version older than 3.2, install the site again with `bundle exec jekyll new . -f`

right in between these two sentences:
```
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
```
be addressing too convoluted a use case? Just sharing some ruby/bundler noob thoughts.
Perhaps a similar point still stands, one should either choose to do "jekyll post-3.2" or "jekyll pre-3.2" and not both at the same time, and that makes sense.

**Comment by db0sch** [comment]
hi all, 

Shall we maybe clarify this on the documentation ?
(like warning people that they must use jekyll 3.1.6 through github-pages gem if they want to deploy on github ?)

thx

**Comment by DirtyF** [comment]
@db0sch It shoudln't be necessary as GIthub Pages is supposed to upgrade today to 3.2.1: https://github.com/blog/2220-github-pages-to-upgrade-to-jekyll-3-2  😄

**Comment by db0sch** [comment]
ok, huh... Damn it, i chose the right day to start a blog on github... 
sorry.
thanks for replying anyway.
all the best
