### ISSUE TITLE
Jekyll 3.2.1 windows

### ISSUE THREAD

**Issue by dthor** [jekyll/jekyll#5206]
- [x ] I believe this to be a bug, not a question about using Jekyll.
- [x ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [x ] I had an error on Github Pages and I did test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

https://github.com/dthor/dthor.github.io
https://dthor.github.io/

## The Output I Wanted

 I have tested my content locally on the local server - http://localhost:4000/ and it works fine locally, I staged, committed and push the content up to my github repository and just get the 404 page not found error when I go to my https link: https://dthor.github.io/

**Comment by parkr** [comment]
dthor.github.io brings up `/`. Your [index.md](https://github.com/dthor/dthor.github.io/blob/master/index.md) file has a `permalink: /home/` so if you want to see that file, you have to go to `dthor.github.io/home/`.

I'd recommend removing the `permalink: /home/` in `index.md`.

**Comment by dthor** [comment]
thanks so much -  such the simplest thing made it not work on github
I dropped the permalink: in my index.md file and now my webpage works fine

thanks
Regards
Darren
