### ISSUE TITLE
Release notes should not list "Page" as something you can use with the new Link tag

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll#5213]
The [Release notes page](https://jekyllrb.com/news/) says:

> Added a link liquid tag which can be used to generate URL’s for any post, page, or document based on its path relative to the site source

However, on the [Templates page](https://jekyllrb.com/docs/templates/), the Link section says:

> Support for static files and pages is coming in a later release but is not released as of v3.2.1.

The Release Notes should be updated to remove "page" from the list of files you can link to using the new link tag.

**Comment by DirtyF** [comment]
@tomjohnson1492 Good catch!
