### ISSUE TITLE
[jekyll 3.2.1] {% if page.categories %} triggering on post without categories

### ISSUE THREAD

**Issue by CMessinides** [jekyll/jekyll#5215]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps
Here is a repo with a quick jekyll site showing my issue: [https://github.com/CMessinides/jekyll-categories-example](https://github.com/CMessinides/jekyll-categories-example)

`jekyll serve` or directly examine the three example posts in `_posts`

## The Output I Wanted
I wanted to include a `{% if page.categories %}...{% endif %}` block in my post layout. I expected nothing inside the block to be rendered if a post had no categories. However,  the block rendered on all posts anyway. 

Here is a screenshot from the example site showing the bug in question:
![image](https://cloud.githubusercontent.com/assets/17892372/17499760/78da77de-5d9d-11e6-9e49-32ab0ab08df7.png)

**Comment by mmistakes** [comment]
Don't think this is a bug. `page.category` and `page.categories` are slightly different. One I believe outputs as a string and the other as an array, which happen to have different [truthiness and falsiness in Liquid](https://help.shopify.com/themes/liquid/basics/true-and-false). That could explain why one works for you and the other doesn't.

Try this for checking if a page has categories:

```Liquid
{% unless page.categories == empty %}
      <span>Categories: </span><span>{{ page.categories }}</span>
{% endunless %}
```

If you add the `inspect` filter to your variables it might help shed some light if it's an array or a string so you can write accurate conditionals.

Example front matter:

```
category: category1
categories: a b c
```

would yield something like:

`{{ page.category | inspect }}` ~> `"category1"`
`{{ page.categories | inspect }}` ~> `["a", "b", "c"]`

and if blank:

```
category:
categories:
```

`{{ page.category | inspect }}` ~> `nil"`
`{{ page.categories | inspect }}` ~> `[]`

**Comment by CMessinides** [comment]
That worked perfectly, thank you.
