### ISSUE TITLE
jekyll serve can't work

### ISSUE THREAD

**Issue by liqimore** [jekyll/jekyll#5216]
MacOS 10.11
Jekyll 3.2.1
jekyll site folder : Gemfile		_posts		css		index.html
_config.yml	about.md	feed.xml

jekyll serve
Configuration file: none
            Source: /Users/Qi/Desktop
       Destination: /Users/Qi/Desktop/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
     Build Warning: Layout 'post' requested in blog/_posts/2016-08-09-welcome-to-jekyll.markdown does not exist.
  Liquid Exception: Could not locate the included file 'icon-github.html' in any of ["/Users/Qi/Desktop/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in blog/about.md
jekyll 3.2.1 | Error:  Could not locate the included file 'icon-github.html' in any of ["/Users/Qi/Desktop/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.

i don't know why i miss the _include folder. Please help, thanks.

**Comment by Crunch09** [comment]
Hi @liqimore ,

it seems that you need to update your `minima` gem, which is the default theme. Could you try running `bundle update minima` in your project root dir and then starting the server again?

**Comment by envygeeks** [comment]
Agreed with @Crunch09, please update your theme, there was recently a bug fixed there.

**Comment by liqimore** [comment]
Thanks guys. But update theme is not working. I reinstall ruby 2.3.1 by using rbenv. Then i jekyll new test , and jekyll serve , it works. It might be something wrong with my ruby.

**Comment by kamilklkn** [comment]
[00:20:31] Starting 'jekyll-build'...
[00:20:31] Starting 'watch'...
[00:20:31] Finished 'watch' after 17 ms
Configuration file: /Users/kamilkalkan/Dropbox/Kisisell/kamilklkn.com/Web Development/blog/_config.yml
            Source: /Users/kamilkalkan/Dropbox/Kisisell/kamilklkn.com/Web Development/blog
       Destination: /Users/kamilkalkan/Dropbox/Kisisell/kamilklkn.com/Web Development/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Could not locate the included file 'about.html' in any of ["/Users/kamilkalkan/Dropbox/Kisisell/kamilklkn.com/Web Development/blog/_includes", "/Users/kamilkalkan/.rvm/gems/ruby-2.3.3/gems/minima-2.1.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in index.html
jekyll 3.4.0 | Error:  Could not locate the included file 'about.html' in any of ["/Users/kamilkalkan/Dropbox/Kisisell/kamilklkn.com/Web Development/blog/_includes", "/Users/kamilkalkan/.rvm/gems/ruby-2.3.3/gems/minima-2.1.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
[00:20:38] 'jekyll-build' errored after 6.85 s
[00:20:38] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/kamilkalkan/Dropbox/Kisisell/kamilklkn.com/Web Development/blog/node_modules/orchestrator/index.js:264:8)
    at /Users/kamilkalkan/Dropbox/Kisisell/kamilklkn.com/Web Development/blog/node_modules/orchestrator/index.js:275:23
    at finish (/Users/kamilkalkan/Dropbox/Kisisell/kamilklkn.com/Web Development/blog/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/Users/kamilkalkan/Dropbox/Kisisell/kamilklkn.com/Web Development/blog/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)


I deleted the project and uploaded it again, but it did not. I don't know why i miss the _include folder. Please help, thanks.

**Comment by ashmaroli** [comment]
Minima-2.1.0 doesn't have an [include](https://github.com/jekyll/minima/tree/master/_includes) called **`about.html`** by default.

So, do **either of the following** to proceed:
  * Create an `_includes` directory at the site's `source`, if there isn't one already, and **add `about.html` to it.**
  * Delete all references of the include **`{% include about.html %}`** within your documents.

**Comment by zhangninghao** [comment]
how to uodate?@ Crunch09

**Comment by zhangninghao** [comment]
how to update?@ Crunch09
