### ISSUE TITLE
Bundle install not working

### ISSUE THREAD

**Issue by chrisdemars** [jekyll/jekyll#5218]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

- [x] I am on (or have tested on) ***macOS*** 10+

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

```
jekyll new my-blogv2
cd my-blogv2
bundle install
``` 

## The Output I Wanted

```
$ bundle install
zsh: command not found: bundle
```

```
$ ruby -v                                                              
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
```

I updated RubyGems and updated Ruby, still I can't get bundle install to work. If this isn't a bug than what am I doing wrong?

**Comment by ashmaroli** [comment]
you need to have [Bundler](http://bundler.io/) installed to use `bundle install`
