### ISSUE TITLE
Update Documentation for Bundler Gem

### ISSUE THREAD

**Issue by miklb** [jekyll/jekyll#5219]
This [ticket](https://github.com/jekyll/jekyll/issues/5218) highlights the need for the documentation to include installing the bundler gem.

[Installation](https://jekyllrb.com/docs/installation/) and [Quickstart](https://jekyllrb.com/docs/quickstart/) make the assumption that it is installed. For someone completely new to Ruby and following documentation, this would be a blocker.

I'm just not sure where it should fall in documentation.

**Comment by ashmaroli** [comment]
hi @miklb, thanks. We already have the update process [underway](https://github.com/jekyll/jekyll/pull/5198). 
It will be made live soon.
we're also considering having bundler added as a dependency, so it will install automatically with Jekyll.
