### ISSUE TITLE
`link_to:` does not cause a link

### ISSUE THREAD

**Issue by stevecheckoway** [jekyll/jekyll#5250]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

Create a file, `test.md`, using the `link_to` [example](https://help.shopify.com/themes/liquid/filters/url-filters#link_to).

```liquid
---
---
{{ 'Shopify' | link_to: 'https://www.shopify.com','A link to Shopify' }}
```

Run `bundle exec jekyll build`.

## The Output I Wanted

Per the `link_to` documentation, I expected to see

```html
<a href="https://www.shopify.com" title="A link to Shopify">Shopify</a>
```
(wrapped in a `p` element from the markdown).

Instead, the `link_to` filter appears to do nothing and the entire output is `<p>Shopify</p>`.

I can't tell if this is a Liquid bug or not. Although, now that I look at the [definition](https://github.com/Shopify/liquid/blob/9a7778e52c37965f7b47673da09cfb82856a6791/performance/shopify/shop_filter.rb#L22) of `link_to`, I'm disappointed it doesn't do url encoding. So I'm actually less sure what the use case is and I now care quite a bit less about this issue. But nevertheless, Jekyll [purports](https://jekyllrb.com/docs/templates/) to support standard Liquid filters and this one appears not to work.

**Comment by pathawks** [comment]
This filter is neither listed in the Jekyll nor [the Liquid documentation](https://shopify.github.io/liquid/filters/). Shopify has their own filters, just like Jekyll has some of its own non-standard filters.

This is not a bug in Jekyll.

**Comment by stevecheckoway** [comment]
Thanks! I completely missed that I wasn't looking at the right liquid documentation.
