### ISSUE TITLE
Missing hex conversion filter (proto-PR)

### ISSUE THREAD

**Issue by lynxlynxlynx** [jekyll/jekyll#5251]
On a site documenting binary formats, hex values are common. Neither liquid nor jekyll has a filter to convert from a decimal to hex. I wrote a [trivial plugin](https://github.com/lynxlynxlynx/Jekyll-Dec-to-Hex/blob/master/dec_to_hex.rb) for that, but am **wondering if this is something of wider interest that would be considered for official inclusion** (before I waste time on a PR for filters.rb). I know it's missing the safe tag, should probably be named to_hex to match the new to_i and perhaps be accompanied with a to_dec. Thoughts?

- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [x] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

**Comment by envygeeks** [comment]
I honestly don't know what it would serve being in core, it can be assumed it's not used by our users as nobody has really brought it up before.  I guess it would be acceptable regardless if the complexity is low, but if it's higher, I think it's better suited as a plugin holding filters.

**Comment by lynxlynxlynx** [comment]
The implementation is a oneliner — a sprintf call, but right, if you consider it feature creep, let's just skip it. Maybe a better case could be made for exposing sprintf itself, so it would be like date and its format parameters.

**Comment by envygeeks** [comment]
I don't like the formatting at all.

**Comment by lynxlynxlynx** [comment]
Ok then, closing.

**Comment by envygeeks** [comment]
My apologies @lynxlynxlynx that comment was actually meant for another ticket.

**Comment by lynxlynxlynx** [comment]
Well then, do you like the idea of exposing printf?

**Comment by envygeeks** [comment]
@lynxlynxlynx I can see a need for it, but I don't know if it can be utilized that well. what I mean by that is, I wonder if liquid could even support sending say 10 variables in to make printf worth it.  /cc @fw42, maybe he can answer.

**Comment by lynxlynxlynx** [comment]
Oh, I hadn't thought about it that way: just as a conversion filter for a single parameter.

**Comment by pathawks** [comment]
This really doesn’t strike me as a feature that belongs in core. I can certainly see its usefulness, but I don’t think it is something that the majority of sites would use.

I think this is plugin territory.

**Comment by lynxlynxlynx** [comment]
Closing again then.
