### ISSUE TITLE
Figure element in highlighted blocks

### ISSUE THREAD

**Issue by 11bits** [jekyll/jekyll#5255]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [X] This is a feature request.

I agree with issues  #4905 and #5020. 

`figure` element should be optional for highlighted code snippets and if it exists it needs a `figcaption`.

Thanks for hearing my suggestions.

**Comment by envygeeks** [comment]
Figcaption is optional. It should be allowable but your suggestion to
always have it is unacceptable.

**Comment by 11bits** [comment]
Maybe I have not expressed well.

My suggestion has two parts:

1. `figure` element should be optional for highlighted blocks (now it is added always) #4905

2. The **option** to add a figcaption should exist (now is not possible) #5020

**Comment by envygeeks** [comment]
There was another ticket that expressed the same sentiment on figure, I don't quite remember the outcome.  Perhaps @parkr can fill us in on what it was decided when somebody wanted to switch it back to "div" but reading again I don't assume that's what you want, I'm assuming you want the option to either use figure **or** div yes?

**Comment by 11bits** [comment]
Yes, it could be a solution, the option to either use `figure` (with an optional `figcaption`) or `div`.

Another solution could be not to add any container and maybe include the `highlight` class in the `pre` element. In this way one could choose either to wrap the code block in a `figure` or not. I don't know if it would be possible.

**Comment by 11bits** [comment]
It seems there is no progress in this request.

At the moment I'm using the @czak [solution](https://gist.github.com/czak/94f8b98e3f6789b38a4f7414ca703380), with little modifications, to add a `figcaption` and it works fine.

I hope it will be an option in the future.

I close the issue.

Regards

**Comment by sarahdayan** [comment]
Unfortunately, the @czak solution isn't compatible with [GitHub Pages](https://jekyllrb.com/docs/plugins/) for security purposes.

It would be really great to be able to use whatever tag we want as a wrapper, or remove it altogether. The current `figure` could remain by default to avoid breaking existing websites.
