### ISSUE TITLE
unable to build a jekyll site … invalid date

### ISSUE THREAD

**Issue by cchorn** [jekyll/jekyll#5267]
when trying to build a jekyll site with "jekyll serve" I get this error:

  Generating...
         ERROR: YOUR SITE COULD NOT BE BUILT:
                ------------------------------------
                Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/cache/gems/jekyll-3.2.1/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.

I used several jekyll templates to test, all with the same result, including the simple test template from the jekyll main page, i.e., "my-awesome-site"

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I Updated to the latest Jekyll (or) if on Github Pages to the latest `github-pages`
- [ ] I Read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on Github Pages, and I have not tested locally.
- [ ] I had an error on Github Pages, and Github Support said it was a Jekyll Bug.
- [ ] I had an error on Github Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

**Comment by crispgm** [comment]
It seems that you use the `.erb` template to generate new site.

To create a new site, you may use `jekyll new your-site-name` instead.

**Comment by cchorn** [comment]
The same issue occurs:
using:
jekyll new your-site-name
bundle install
bundle exec jekyll serve

ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/cache/gems/jekyll-3.2.1/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.


The file "0000-00-00-welcome-to-jekyll.markdown.erb" contains the following header:
---
layout: post
title:  "Welcome to Jekyll!"
date:   <%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>
categories: jekyll update
---

**Comment by pathawks** [comment]
```
<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>
```

It looks like you are trying to use ERB in your post's front matter, which is not supported. This is not a bug in Jekyll.

**Comment by ashmaroli** [comment]
Are you trying to serve a clone of the jekyll github repository?
then make sure you `cd` into the _**site**_ folder before `jekyll serve`
If not, follow these exact steps:
```
$ jekyll new Your New Blog
$ cd your new blog
$ bundle install
$ bundle exec jekyll serve
```

**Comment by cchorn** [comment]
Yes, I used "cd" and I was in the folder. I still have the error message.

**Comment by ashmaroli** [comment]
Can you list the exact steps followed once again? Thanks.

**Comment by cchorn** [comment]
Here are steps. I repeated this again with the same result, an error:

`jekyll new testblog`
`cd testblog`
`bundle install`
`bundle exec jekyll serve`

error

`Generating... 
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/cache/gems/jekyll-3.2.1/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.`

**Comment by ashmaroli** [comment]
The steps are correct. So you should've got a nice message:
`New jekyll site installed in /path/to/testblog`

If you check that dir, You should find a Gemfile and a \_config.yml (alongwith few others); all this in that very directory. These are all that jekyll needs to serve.
The issue is _hence within your system_. Perhaps, its not able to pass the system date n time to Jekyll.

**Comment by cchorn** [comment]
Correct, I can see the the gemfile and _config.yml. I expected it would build a "_site" directory but this is not present.

**Comment by ashmaroli** [comment]
Try uninstalling jekyll, delete jekyll gem cache from `vendor/cache` and re-install with
 `gem install jekyll --no-document`

**Comment by cchorn** [comment]
I completed these steps, uninstall, deleted gem cache, and re-install but no luck. Still the same error.

**Comment by ashmaroli** [comment]
This issue would've made a lot more sense if _posts/0000-00-00-welcome-to-jekyll.markdown.erb was actually /path/to/testblog/_posts/0000-00-00-welcome-to-jekyll.markdown.erb. Then, it would've been close to jekyll being at fault. 
Sorry Charles, I wont be able to assist you, any further.

**Comment by DirtyF** [comment]
@cchorn What version of Ruby are you running?

**Comment by cchorn** [comment]
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by cchorn** [comment]
I've solved it!  It seems that you need to place the line `exclude: [vendor]` in _config.yml 
found this on the following issue:
https://github.com/jekyll/jekyll/issues/2938

**Comment by ashmaroli** [comment]
Thank you for referencing the old issue.
I havent read through completely, but Parker has explained the reason why it works in one of the comments.

Think the documentation needs to add a note about this under "Troubleshooting.."

**Comment by cchorn** [comment]
Yes, that is a good idea.
Thanks

**Comment by cchorn** [comment]
I submitted a request to add this to the documentation, using jekyll-help at the bottom of this page: https://jekyllrb.com/docs/troubleshooting/

**Comment by ashmaroli** [comment]
jekyll-help is no longer maintained. You can create a pull-request by clicking on the "Improve this page" at the top-right of the article.

**Comment by cchorn** [comment]
Thanks. I've done this.

**Comment by pathawks** [comment]
So, this issue can be closed?

**Comment by cchorn** [comment]
Yes

**Comment by BrittanyIRL** [comment]
Just saying thank you, I ran into this error and this thread saved me hours

**Comment by HiKWang** [comment]
it works!Thanks!

**Comment by Atlas7** [comment]
Awesome life saver thank you! Just to add: to incorporate [Travis CI to the Jekyll site](https://jekyllrb.com/docs/continuous-integration/travis-ci/) you need to add the `exclude: [vendor]` in both `_config.yml` and `.travis.yml`. (only learnt just now!)
