### ISSUE TITLE
Jekyll not including content into head

### ISSUE THREAD

**Issue by wolfy1339** [jekyll/jekyll#5288]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have not tested locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

1. Run `git clone --depth=1 https://github.com/wolfy1339/m8tro-bootstrap`
2. Run `jekyll serve --host 0.0.0.0` inside the cloned git repository
3. Open the output in your browser, and in developer tools (or just use cURL as we only need the source) you will see that a section of code that was intended for the `<head>` in the `<body>`  

## The Output I Wanted

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The 3 above meta tags *must* be first -->
<title>M8tro Bootstrap Theme</title>
<style type="text/css">html{position:relative;min-height:100%}body{margin-bottom:40px;padding-bottom:40px}.footer{position:fixed;bottom:0;width:100%;height:40px;background-color:#000;border-top:1px solid #fff;padding-top:4px;z-index:2}.bs-component .modal{position:relative;top:auto;right:auto;left:auto;bottom:auto;z-index:1;display:block}.modal-dialog{width:inherit;margin:0}.fa-clipboard{color:#fff!important;}</style>
<link rel="stylesheet" href="dist/css/m8tro.min.css">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
<link rel="shortcut icon" href="http://s.idleberg.com/m8tro-ico/favicon.png">
<link rel="apple-touch-icon" sizes="57x57" href="http://s.idleberg.com/m8tro-ico/iphone.png">
<link rel="apple-touch-icon" sizes="114x114" href="http://s.idleberg.com/m8tro-ico/iphone-retina.png">
<link rel="apple-touch-icon" sizes="72x72" href="http://s.idleberg.com/m8tro-ico/ipad.png">
<link rel="apple-touch-icon" sizes="144x144" href="http://s.idleberg.com/m8tro-ico/ipad-retina.png">

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>﻿
[...]
</body>
</html>
```
/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by ashmaroli** [comment]
How does the source code within browser (right-click; View page source) look like?

**Comment by wolfy1339** [comment]
Seems, like it might be a browser bug then. But if I copy the code from the include and put it in the head section, it works fine. And this is only happening on this Jekyll site
Thanks anyways!

**Comment by ashmaroli** [comment]
No, its not a browser bug.
Its an Encoding issue. 
The fix is to simply save your `head.html` with `UTF-8 without BOM`
Don't use notepad.exe to create HTML files.
Use Notepad++ or Sublime Text 2 instead.

**Comment by wolfy1339** [comment]
I never use notepad.exe, I use Notepad++.
Alright Thanks, I'll make sure for next time to check that

**Comment by envygeeks** [comment]
I've not used notepad++ for like a decade but back when I last used it, it did add BOM.

**Comment by DirtyF** [comment]
@wolfy1339 ProTip™: Use https://atom.io/ who provides some useful plugins to work with Jekyll.

**Comment by wolfy1339** [comment]
I'll have to try that tip.
