### ISSUE TITLE
undefined method `pagination_enabled?' for Jekyll::Paginate::Pager:Class

### ISSUE THREAD

**Issue by eyaqub** [jekyll/jekyll#5289]
Hi, I installed jekyll 3.2.1 but the serve command gives an error at startup time. It seems related to jekyll-multiple-languages gem. Here is the output:

Generating... 
undefined method `pagination_enabled?' for Jekyll::Paginate::Pager:Class
Did you mean?  pagination_candidate?
/var/lib/gems/2.3.0/gems/jekyll-multiple-languages-2.0.3/lib/jekyll-multiple-languages/pagination.rb:11:in `generate'
/var/lib/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/site.rb:174:in `block in generate'
/var/lib/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/site.rb:172:in `each'
/var/lib/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/site.rb:172:in `generate'

Any hints would be appreciated. Thanks.

**Comment by Crunch09** [comment]
Hi @eyaqub ,

you probably ran into the same issue as this one https://github.com/liaohuqiu/jekyll-multiple-languages/issues/13 .
You need to install the [jekyll-paginate](https://github.com/jekyll/jekyll-paginate) gem, but beware that this is no longer actively maintained in Jekyll 3.

**Comment by eyaqub** [comment]
Hi, I tried the solution from the link you mentioned. Installed the jekyll-paginate gem but it did not help me. If jekyll-multiple-languages cannot be used anymore, could there be a newer gem for multi-language websites? Any hinst are well appreciated. Thanks in advance.
