### ISSUE TITLE
[ Proposal ] Alter default Jekyll Scaffolding

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5299]
## Proposal : Alter Jekyll Scaffolding
 
- Non-related document files to be placed into a directory of their own ( ***_pages*** ) by default
- Promote index page to a new status.
  - It will be a _**Markdown Document**_ with a layout of its own (within theme dir).    
    ( _Originally [proposed](https://github.com/jekyll/minima/issues/13) by Ben Balter_ ).    
    This allows altering homepage layout with greater freedom and hinder theme development.
  - **_It will be the lone markdown document to be placed at the root._**
- Markdown documents to sport a shorter **.md** extension. ( A PR is already open regarding this )
- Define navigation as yaml files by default. Markup to be generated by liquid within default layout.

---
- _config.yml
- _drafts
  - begin-with-the-crazy-ideas.***md***
  - on-simplicity-in-technology.***md***
- ***_pages***
  - ***about.md***
  - ***contact-us.md***
  - ***usage.md***
- _posts
  - 2016-08-26-why-every-programmer-should-play-nethack.***md***
  - 2016-08-29-barcamp-boston-4-roundup.***md***
- _data
  - members.yml
  - ***main-nav.yml***
  - ***side-nav.yml***
- _site
- .jekyll-metadata
- Gemfile
- index.***md***

### minima architecture

- _includes
  - (minima includes)
- _layouts
  - default.html
  - ***home.html***
  - page.html
  - post.html
- _sass
  - (minima styles)

---

/cc @jekyll/ecosystem

**Comment by parkr** [comment]
I really don't like `_pages` as I think the input of your site should more closely resemble the output file structure – it's much more intuitive that way.

I think we could update the pages to markdown as long as it doesn't ruin formatting or anything. Surprised they're not already so! Feel free to submit a PR to this effect!

I think the `index.md` file should have an `{% include post_listing.html %}` or something which is an include in minima. This `post_listing.html` in minima would essentially be the `{% for post in site.posts %}` so folks could easily add content around the listing. I don't think it needs its own layout personally – it makes it harder to modify than includes.

**Comment by envygeeks** [comment]
There are a few of our sites where I think `_pages` would benefit us because we've thousands of pages and having a `_pages` folder would be great to keep the clutter low in the main folder, but at the end of the day, that's very rare, I don't know that I would want it by default (we've solved it by plugin.)

**Comment by ashmaroli** [comment]
> I think we could update the pages to markdown as long as it doesn't ruin formatting or anything. Surprised they're not already so!

They are already markdown docs by default ( with a .md extn too.. ). I was referring to posts to also take on the new extension  ( proposed in #5176, currently [paused] ).
And I'm not entirely sure if the `code` block in [this page](https://jekyllrb.com/docs/structure/) must have .md extensions as well (/cc @DirtyF )
