### ISSUE TITLE
Provide support for HAML and SASS

### ISSUE THREAD

**Issue by imanel** [jekyll/jekyll#53]
More and more  people uses HAML and SASS from nex, so I think it will be good thing to implement it in Jekyll. http://github.com/henrik/jekyll/tree/master have it already in his tree, but it's old and unsuported version of Jekyll. So will it be a problem to pull this functions from his repo? If there's some code-blokers I will willingly help with enhance code.

**Comment by yguezeldal** [comment]
html syntax sucks. full haml support for github-pages please
