### ISSUE TITLE
centering text blocks

### ISSUE THREAD

**Issue by JazzMaster** [jekyll/jekyll#5305]
I am using latest jekyll and (kramdown?) I believe on jessie (9) and have a issue here.

I want to center a block of text, not one line in markdown or jekyll and am unsure how to get this to work. Mind you I have images and text in that block.

I can horse edit the now compacted code with 
`<center> center </center>`
tags where I want centered, however, this is not a solution.

Markdown does 
-> one lines <-

you see.. but not blocks. I use geany to test the markdown code before deployment.

**Comment by JazzMaster** [comment]
these parts *should* be centered, i dunno whats going on here..github uses jekyll

**Comment by parkr** [comment]
This has been answered here: https://github.com/gettalong/kramdown/issues/145#issuecomment-50225474

kramdown does not support the `-> one line <-` syntax. Thanks!
