### ISSUE TITLE
Search Functionality at jekyllrb

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5306]
Hi,
Is there any chance you guys can implement a search functionality to jekyllrb?
Its really hard to find something when in doubt.
Thanks

**Comment by budparr** [comment]
If you just add `site:jekyllrb.com` to your search query in google, you'll limit results to the Jekyll site and the forums. like this: https://www.google.com/#newwindow=1&q=example+site:jekyllrb.com

**Comment by ashmaroli** [comment]
Ah.. never thought of that. Thanks! :smiley:

**Comment by DirtyF** [comment]
Sure we can always narrow a search engine search even to the `/docs/` folder by requesting [site:jekyllrb.com/docs/ _posts](https://duckduckgo.com/?q=site%3Ajekyllrb.com%2Fdocs%2F+_posts&ia=web)  but it does not compare to providing a dedicated search on Jekyll's website with proper autocompletion and search as you type like [Algolia demonstrate on Bootstrap's documentation](https://bootstrap.algolia.com/) (via [their jekyll plugin](https://github.com/algolia/algoliasearch-jekyll))
