### ISSUE TITLE
Jekyll 4.0 Wishlist

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#5307]
Hi!

We have no plans for a 4.0 but I wanted to collect a potential "wishlist" of changes we'd like to see happen in a potential 4.0.
- Remove `Jekyll::Convertible` in favor of `Jekyll::Renderer`

Anything that is a breaking change that you can't see Jekyll without?

**Comment by crispgm** [comment]
* [Function] Apply gem-based theme on single page/post. e.g. Site uses `minima` theme for posts without specify `theme: xxx` in front-matter. But the resume page specify `theme: resume` in front-matter, which uses `resume` theme.
* [Docs/Ecology] Can we collect \*all\* Jekyll plugins and themes? The current plugin page is mixed with tutorials.

**Comment by envygeeks** [comment]
> Can we collect *all* Jekyll plugins and themes? The current plugin page is mixed with tutorials.

I think this is out of scope for Jekyll Core.

**Comment by borisschapira** [comment]
* Ability to configure a collection via the URL of a JSON, XML, RSS ou Atom file. During the build Jekyll call the URL, get the content and use it to build the website.
* The ability to organize content by ourselves, i.e. change conventions by configuration. For example, having the possibility to organize collections in folders and sub-folders.
* A Jekyll Code Style command that could parse the liquid templates and precisely identify performance bottleneck.
* Release the Kraken

**Comment by nhoizey** [comment]
It would be nice to have a convention for a single folder where the core and plugins could put their caches subfolder.

Currently:
- jekyll-assets uses `/.asset-cache/`: https://github.com/jekyll/jekyll-assets#cache-folder (can be modified)
- jekyll-twitter-plugin uses `/.tweet-cache/`: https://github.com/rob-murray/jekyll-twitter-plugin#caching
- I plan to add caching to https://github.com/erossignon/jekyll-youtube-lazyloading, and could apply any planned convention

I personally would suggest `/.caches/<plugin-name>/…`

I understand this is not a breaking change for the core, but I think v4 would be the good version to start enforce such a convention.

**Comment by borisschapira** [comment]
Hi!

I've got another idea: a multiple-layout feature : providing multiple layout through Front Matter, Jekyll would be able to generate multiple output (for example, HTML, AMP, JSON…).

I think this can be done through a Generator plugin, but I would like to see this feature integrated in the core (the ability to adresse the HTML/JSON couple would open great possibilities for progressive web apps).

**Comment by borisschapira** [comment]
The ability to organize content by ourselves, i.e. change conventions by configuration. For example, having the possibility to organize collections in folders and sub-folders.

**Comment by borisschapira** [comment]
A Jekyll Code Style command that could parse the liquid templates and precisely identify performance bottleneck.

**Comment by admhlt** [comment]
@borisschapira That last one already kind of exists — use `jekyll serve --profile` to get a breakdown of the speed and load of each of your templates. It's really useful for identifying what's slowing your site build.

**Comment by budparr** [comment]
#4742 Multi-format layouts, if it's not happening earlier.

**Comment by DirtyF** [comment]
- [ ] Fetch data from external URLs ([originally proposed on Jekyll Talk](https://talk.jekyllrb.com/t/core-data-driven-content/2213)) à la `jekyll-get` (or add `jekyll-get` to Github Pages whitelist plugins)

**Comment by envygeeks** [comment]
I kind of weary about external data sources.  I like the concept but I fear the trouble that could happen without very very very very careful auditing of the source code behind such remote things.

**Comment by admhlt** [comment]
I'd love to see pages be aware of the content around them — we have a plugin that does this, but it would be great to see it become a native thing. Make `page.parent` return the `index.html` file in the current page's directory, or if it's an index file, the `index.html` file in the directory above. Make `page.children` return a page's siblings if it's an `index.html` file.

With a few properties like this you can build amazing, full-featured nav menus for even really complex sites.

**Comment by parkr** [comment]
> [Docs/Ecology] Can we collect *all* Jekyll plugins and themes? The current plugin page is mixed with tutorials.

@crispgm Have you seen https://github.com/jekyll/plugins ? I would like to move the plugins listing there; just haven't had the time yet.

> It would be nice to have a convention for a single folder where the core and plugins could put their caches subfolder.

@nhoizey I believe we have talked about this! Did you see #4227?

> Ability to configure a collection via the URL of a JSON, XML, RSS ou Atom file. During the build Jekyll call the URL, get the content and use it to build the website.

@borisschapira Remote resources can be tricky. What if the site goes down? Usually better to run a job and cache and validate the data before committing & pushing. @DirtyF Is this what you meant as well?

> I've got another idea: a multiple-layout feature : providing multiple layout through Front Matter, Jekyll would be able to generate multiple output (for example, HTML, AMP, JSON…).

@borisschapira Have you seen #4742?

> I'd love to see pages be aware of the content around them — we have a plugin that does this, but it would be great to see it become a native thing. Make page.parent return the index.html file in the current page's directory, or if it's an index file, the index.html file in the directory above. Make page.children return a list of the other pages in the page's current directory if it's an index.html file.

@admhlt Interesting! This would be pretty cool. At the moment, we don't give any context to documents except `page.previous` and `page.next` for iterating through collection documents.

**Comment by DirtyF** [comment]
@parkr yes, that's exactly what I meant fetch data locally, generate content, commit and push.

**Comment by nhoizey** [comment]
@parkr I didn't see #4227, it's great. Can it be reopened then?

**Comment by crispgm** [comment]
> Have you seen https://github.com/jekyll/plugins ? I would like to move the plugins listing there; just haven't had the time yet.

@parkr I have seen this before, but the content is not rich by now. Comparing to the plugins, the theme-based gems are more serious. New users can hardly find any themes other than `minima`.

**Comment by spudowiar** [comment]
@DirtyF if you want that, then I suggest writing a simple plugin for that, I can't see GitHub Pages ever allowing this if you're worried about not having plugins in `safe` mode

@crispgm So far, I've only seen two sites [@planetjekyll](1) and [GitHub Pages](2) so :+1: on that point

[1]: https://github.com/planetjekyll/awesome-jekyll-themes
[2]: https://pages.github.com/themes/

**Comment by tgragnato** [comment]
I would appreciate a cleaner configuration syntax to set a different custom permalink for posts, pages & collections.

For what this does, maybe it's a bit too much trickier.
But maybe I am missing something that already exists.

```yaml
defaults:
-
  scope:
    type: pages
  values:
    permalink: /:path/:basename:output_ext
-
  scope:
    type: posts
  values:
    permalink: /:year/:title.html
```

**Comment by tgragnato** [comment]
Even if it's _not related to core_ I am pointing out the [ jekyll-coffeescript import feature](https://github.com/jekyll/jekyll-coffeescript/issues/5): that would be really really great.

**Comment by icai** [comment]
I hope support 

collections:
  docs:
    output: true
    aysnc: true
    permalink: /:path.html
---

if aysnc is equal to true, that collection read  and generate file one by one with pipe.

**Comment by bomberstudios** [comment]
Built-in LiveReload (a-la https://github.com/awood/hawkins) would make development a bit easier.

**Comment by bomberstudios** [comment]
Native support for content blocks (see https://github.com/rustygeldmacher/jekyll-contentblocks), which are _awesome_ for non-trivial sites with many layouts.

**Comment by spudowiar** [comment]
@bomberstudios #5142

**Comment by bomberstudios** [comment]
@spudowiar cool, thanks. By some funny coincidence, I'm using @awood's plugin for live reloading, and just yesterday I sent a pull request to the project : )

**Comment by oncleben31** [comment]
Tools for i18n and l10n in the core. Currently there is no standard and many plugins try to cover the needs.
At least the localization of the dates to avoid having to create `_includes` files with liquid code (almost the same code from one site to another) to translate days and months.

**Comment by DirtyF** [comment]
Allow other templating engines to be plugged to Jekyll (Haml, Slim, ERB, etc.). source: https://github.com/jekyll/jekyll/issues/4746#issuecomment-207793644

**Comment by pathawks** [comment]
* All URL-related tags should use URL filters (to automatically prepend `baseurl`)

**Comment by MPybus** [comment]
I'd appreciate support for the Liquid whitespace control tags: {%- and -%}

**Comment by borisschapira** [comment]
A RAM-computing server mode, in order not to have the files generated and written in destination folder during `jekyll serve`. It should greatly optimize the live-reload during writing.

**Comment by DirtyF** [comment]
@MPybus on his way, it's a Liquid 4.0 feature (see https://github.com/jekyll/jekyll/pull/4362) and currently scheduled for 3.4.0 ;)

**Comment by sackwort** [comment]
I would like to see Sass sourcemaps integrated into Jekyll.

**Comment by git-no** [comment]
I would like to see autoprefixer in Jekyll css processing from sass, especially with Jekeyll themes.

**Comment by nhoizey** [comment]
@git-no you have Autoprefixer support in Jekyll Assets.

**Comment by AdityaAnand1** [comment]
* How about out-of-the-box support for something like [jekyll-admin](https://github.com/jekyll/jekyll-admin)? It'd definitely help jekyll appeal to customers outside the current prime demographic (i.e, developers) if they can see a wordpress-esque UI.
* Not sure if this is possible, but is there something more that can be done (in jekyll) so that github pages can support more plugins?
* Built in asset pipelining support? Compressing assets/minification/concatenation etc. Or an official way to connect the build process through gulp or something? We can make a custom hack ourselves, but it's far from ideal.

**Comment by mertkahyaoglu** [comment]
> How about out-of-the-box support for something like jekyll-admin? 

Great suggestion @AdityaAnand1 😄

**Comment by AdityaAnand1** [comment]
How about a build progress bar? Something like what npm has (preferably without the whole performance [debacle](https://github.com/npm/npm/issues/11283))

I just tried the `--lsi` build option (for using related posts) and it has been building for about 15 minutes. I have no indication as to whether or not it's even close to finishing. I understand it's supposed to take long, but I'd like to know how long. Not just this, as my blog is getting bigger and bigger (more posts, more layouts, more plugins) the builds are getting progressively longer. I imagine it's the same for everyone. Again, this is nothing unexpected, but it'd be nice to see the progress.

Perhaps not for --incremental, but for plain `build`'s and maybe for the inital `serve` build we could have a build progress bar.

**Comment by leonp** [comment]
- Create individual pages from _data file entries just as you can with collections
- Very general, I know, but speed up site generation. On a site with thousands of posts and pages we're finding a standard `bundle exec jekyll s` takes between 180-240 seconds.

**Comment by AdityaAnand1** [comment]
* Bundle common plugins out of the box. What blogs don't want pagination? I don't know much about SEO, but don't all websites want a sitemap.xml? Of course, only the most stable plugins should make the cut.
* How about an optional `draft:true` in the front matter of posts (as an alternative for using `_drafts` directory)? Might be a little neater..
* Something like livereload built in

**Comment by nhoizey** [comment]
@AdityaAnand1

- I don't use a pagination anymore, because it had more than 100 pages, which is useless.
- I don't use any `sitemap.xml`, because Google and others already know my site, and all new content are linked on the homepage, which is crawled daily.
- Some of my drafts live a few months in `_drafts/` before getting published. I would have to change the filename (for the date), if they lived in `_posts/`

These are juste MY uses, though… ;-)

**Comment by budparr** [comment]
FYI, @AdityaAnand1  - Jekyll has `published: true/false', which serves the purpose you're looking for with the drafts. 

There's also a livereload plugin that works very nicely. And, since I'm here, I'd say that not all Jekyll sites are blogs, nor do they want/need a sitemap, and I for one wouldn't want too much stuff added on when it's so easy to specify a bunch of plugins in the Gemfile. Just my two-cents.

**Comment by envygeeks** [comment]
I would like to see Jekyll stop using the default_proc API on Hash so that I can actually make Jekyll competitive with Hugo, as long as Jekyll uses Hash#default_proc that's almost impossible because nothing can be properly marshaled.

**Comment by sasivarnan** [comment]
1. I would like to see out of box support for [jekyll-archives](https://github.com/jekyll/jekyll-archives/) within jekyll.  I feel listing posts posted under a category, with a specific tag are a standard features of a blogging platform. :crossed_fingers: 
2. I would also like to see `pagination` support for all posts and pagination support for posts listed under categories and tags. 💯

**Comment by alinnert** [comment]
I'm thinking about how categories could be implemented. My current idea is to make that feature more universal by allowing the creation of pages dynamically.

Imagine there are the following categories: _personal_, _travel_, and _cooking_.

Now a file `_dynamic/category.html` could look like this:

~~~twig
---
dynamic: site.categories
permalink: /blog/category/:page/
---

<h1>{{ page }}</h1>

<ul>
{% for post in site.posts | where:"category",page %}
  <li><a href="{{ post.url }}">{{ post.title }}</a></li>
{% endfor %}
</ul>
~~~

this would create 3 files:

- `/_site/blog/category/personal/index.html`
- `/_site/blog/category/travel/index.html`
- `/_site/blog/category/cooking/index.html`

One for every item in the array that gets referenced in the `dynamic:` property of the front matter. `{{ page }}` contains the current item in the array. For this to work `:page` must be present in `permalink:`.

That way one could dynamically generate pages based on any collection, not only tags or categories.

What do you think? I'm not sure if `dynamic:` and `:page` are good names though.

**Comment by ashmaroli** [comment]
making a note of this here for future reference.

 - Remove unnecessary class [`Tags::IncludeTagError`](https://github.com/jekyll/jekyll/blob/v3.5.2/lib/jekyll/tags/include.rb#L5-L12)
Its not used anywhere else in the library (as of v3.5.2) and probably wont be in future, owing to `Liquid::Errors` from Liquid 4.0

**Comment by Strangehill** [comment]
Allow variable(s) in link tag. `{% link var %}` or `{% link {{var}} %}`

**Comment by envygeeks** [comment]
I always liked `{% '{{ var }}' %}` a lot better, it's much more explicit, much less confusing, and doesn't create ambiguity when you want a string over a variable with the same name, but that requires Jekyll to start parsing tags properly.

**Comment by kruncher** [comment]
Automatic generation of category / tag listing pages.

**Comment by DirtyF** [comment]
#5682 : Automatically prepend `{{ site.baseurl }}` or allow to use filters on `link` and `post_url` Liquid tags.

**Comment by cameronmcefee** [comment]
I would love to be able to specify schemas for collections and data files so that builds will fail if a document doesn't conform. As an example, I'm building a resources section for a Jekyll site, which is a bunch of collections of types of files (pdfs, videos, podcasts, events, videos of talks) with metadata. Some elements cross-reference others, for instance events contain a list of slugs for talks and the talks contain a slug that references the event they are from.

I'd like to be able to define schemas for each so that when people add new documents they can't do so with incomplete data. I currently validate this with tests but it'd be nice if it was part of the build step, the same way the link tag can be used to validate whether links are valid.

**Comment by pathawks** [comment]
> I would love to be able to specify schemas for collections and data files so that builds will fail if a document doesn't conform.

And front matter! Love this.

Maybe warn instead of fail, but something like this would be quite helpful.

**Comment by tordans** [comment]
**I would love to see better environment support.**

_For example site.url:_ Right now site.url has an implicit env pattern that is hard coded for development ([Source](https://github.com/jekyll/jekyll/pull/6270)). This is very implicid, hard to understand and remember and not extendable. #5142 

I would love to see this extended. Example:
```yml
url:
  production: 'https://www.example.com'
  development: 'http://www.example.test' # this could have the a fallback like today, see "source" above
  staging: 'https://staging.example.com' # this would be possible
```

The pattern could be:
When jekyll calls a variable, it checks for `<var-name>.<env-name>`. The fallback is `<var-name>`. So it does not matter if I configure just `url` order `url.<env-name>`.

**Comment by AdityaAnand1** [comment]
@parkr Any thoughts or perhaps a timeline on all or some of these? 😄

**Comment by pathawks** [comment]
@AdityaAnand1 A lot of it depends on developer interest. If there is a feature you would particularly like to have, offering to open a PR is a great way to get the ball rolling 👍🏼

**Comment by BlkPingu** [comment]
I would love a way to use authors the same way as tags and categories. I struggled to create a pagination where don't have to hardcode a list of authors into a `.yml` file. I've posted about this on github
https://stackoverflow.com/questions/51744240/how-to-paginate-posts-by-author

**Comment by cameronmcefee** [comment]
@BlkPingu Authors are easy with collections, and work with vanilla Jekyll (no plugins). I've answered your question here: https://stackoverflow.com/a/51912653/10244403

**Comment by oe** [comment]
For suggestions, please use the new wishlist issue: #6948
