### ISSUE TITLE
Forking Jekyll

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5313]
Hello Maintainers & TeamCaptains,
I'm thinking of forking Jekyll into a separate gem and progress it forwards parallel to this repo.

My main intention is to incorporate my ideas deemed unfit to be merged into the upstream tree and use the gem as I like. It will be a public repo and be regularly updated (for as long as possible) in sync with upstream _jekyll_. 

I would like to know, if this is allowed, the do's & dont's to follow when doing this, incl. permissions and legal implications of modifying Jekyll's codebase and brand resources separate from upstream.

Thanks.

/cc @parkr, @mattr-, @envygeeks, @benbalter, @jekyll/core

**Comment by parkr** [comment]
Hey @ashmaroli, you're absolutely welcome to fork Jekyll and run with it.

If you are going to start something new, please change the name. This has been done in the past and it's easier for folks to find your project if it's called something totally different, e.g. `jekmaroli`. Our license allows you to use the code as you wish: http://choosealicense.com/licenses/mit/

Our brand resources we have opened under the CC0 license: https://github.com/jekyll/brand
Please do sufficiently differentiate your project if you choose to use any of our resources so that users are not confused.

Fork away!

**Comment by arthurattwell** [comment]
For the record, Jekyll brand resources are CC BY, not CC0.

Incidentally, this is a fantastic and generous choice of licence. Kudos to the project team.

**Comment by ashmaroli** [comment]
Thanks :smiley:

**Comment by ashmaroli** [comment]
> If you are going to start something new, please change the name.

If I rename my existing fork, ashmaroli/jekyll would that break/close existing PRs upstream?

**Comment by crispgm** [comment]
@ashmaroli I think if you use the fork for private use, the name may not be changed, just a forked repo. If it is launched as a new software, definitely a new name is needed. Right?

**Comment by ashmaroli** [comment]
> If it is launched as a new software, definitely a new name is needed. Right?

Definitely. Obviously.
My question is, _If I rename my existing fork, ashmaroli/jekyll would that break/close existing PRs upstream?_
or, simply push a jekyll clone to a new repo altogether?
If the latter, then please point me to docs outlining how I can automatically track the original jekyll repo

**Comment by pathawks** [comment]
> If the latter, then please point me to docs outlining how I can automatically track the original jekyll repo

That’s not really a Jekyll issue, and is probably best discussed in a different channel:+1:

**Comment by ashmaroli** [comment]
> That’s not really a Jekyll issue, and is probably best discussed in a different channel :+1:

This just struck me:

Instead of forking off the entire repo to incorporate a few changes, why not bundle those changes as a jekyll plugin instead?
How does that idea sound? 
If its a plugin, would it sufficiently override / modify how jekyll core works ( starting from `jekyll new` )

I apologize, if all of these querying appear irritating and out of Jekyll's context.
