### ISSUE TITLE
[Proposal] Expose rake tasks wrapping commands through the gem

### ISSUE THREAD

**Issue by nicolasmccurdy** [jekyll/jekyll#5322]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

I have noticed that many projects using Jekyll have a Rakefile with custom tasks that simply wrap calls to Jekyll Commands. Jekyll's source itself also has a few Rake tasks defined to generate documentation and perform other dogfooding tasks, but I think it would be helpful if these were publicly exposed and documented so that users can integrate these tasks into their sites' build scripts. I personally followed the [continuous integration guide](https://jekyllrb.com/docs/continuous-integration/) for testing my site, though I preferred to create wrapper tasks and I find this more helpful in integrating with other Ruby tools (especially since many linters and other QA tools expose rake tasks in their gems). There could even be a simple template Rakefile in the docs with `jekyll build`, HTML Proofer, and other recommended tools.

/cc @jekyll/ecosystem

**Comment by envygeeks** [comment]
Rakefiles are very much personal, as are Makefiles, it's up to you to decide the flow you decide to use, not up to us as we've a basic workflow that is already exposed (read: `jekyll build`.)  I disagree with exposing our Rakefile to the user, but I do not disagree with us creating a document filled full of cool rake tasks people can contribute to in the documentation (or actually, just updating some of our documentation to show how to turn it into a Raketask.)

**Comment by nicolasmccurdy** [comment]
Thanks for the quick reply. While I do agree that Rakefiles are fairly personal, I'm recommending that Jekyll exposes each command as an individual task so that users can customize which ones they want to execute and in what order. For example, Jekyll could expose a build task that simply calls the build command with the given options and sets "build" as the default task name (similar to what RSpec's main public rake task does).

I'm not saying that the current project Rakefile should be exposed programatically (since it seems specific to building Jekyll's own documentation), but some of the simpler tasks could easily be generalized. Even if some functionality needs to differ between projects, users could still call the commands directly in custom tasks or even create custom tasks that depend on the provided tasks. As for recommending workflows, I think it would make sense to have a simple example of these tasks being used in a Rakefile for the documentation, but it doesn't have to be as complex or specific as Jekyll's own Rakefile.

**Comment by nicolasmccurdy** [comment]
Rough example of a simple test Rakefile using tasks like this:

```ruby
require 'jekyll'

Jekyll::RakeTasks::Build.new
Jekyll::RakeTasks::Doctor.new

task default: [:build, :doctor]
```

**Comment by envygeeks** [comment]
Or better: `jekyll build` and `jekyll doctor`, Rake serve a useful purpose, those examples provide no use above what the already existing commands provide, and our Rake tasks do a lot to setup the site for building.  I do not agree with that at all and never will. Sorry.  My vote is :-1: for that.

**Comment by parkr** [comment]
@nicolasmccurdy Nice! I don't think we want to build Rake tasks directly, but all of our commands are simply classes with `process` methods. [See `Build` for example](http://www.rubydoc.info/gems/jekyll/Jekyll/Commands/Build). Just [call `Jekyll::Commands::Build.process(options)`](https://github.com/jekyll/jekyll/blob/f53a3b627239e87d7e85555982eeba1e038f8e68/lib/jekyll/commands/build.rb#L23) from your rake task. 😄
