### ISSUE TITLE
Custom collection structure

### ISSUE THREAD

**Issue by habibullin** [jekyll/jekyll#5324]
How I can get this _site structure with collections:
- _site
    - projects
        - project-1
            - index.html
            - project-custom-style.css
            - project-image.png
            - some-file.pdf
        - project-2
            - index.html
            - project-custom-style.css
            - project-image.png
            - some-file.pdf
        ...

What should be written in _config.yml?

**Comment by DirtyF** [comment]
@habibullin please ask your questions regarding jekyll's usage on https://talk.jekyllrb.com/, these issues  are only for bug reports. Thanks.

**Comment by parkr** [comment]
Thanks @DirtyF!

@habibullin You should be able to create a `_projects` collection and specify this in your config:

```yaml
collections:
  projects:
    output: true
```

Then just add files to `_projects` like normal and they'll be output to `/projects/` in your site.
