### ISSUE TITLE
Jekyll HEAD has a breaking change that breaks some plugins.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#5328]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

See: https://github.com/jekyll/jekyll-sitemap/issues/123

**Comment by ashmaroli** [comment]
I have traced this error to [this PR](https://github.com/jekyll/jekyll/pull/5308)

**Comment by parkr** [comment]
I just noticed that when running `bundle exec rake site:publish`! Fix in #5337.

**Comment by Crunch09** [comment]
I guess this can be closed now?

**Comment by envygeeks** [comment]
Yessum, thanks @parkr! And thanks for pinging @Crunch09.
