### ISSUE TITLE
Include underscore (_) in permalink in Jekyll 3?

### ISSUE THREAD

**Issue by qpwo** [jekyll/jekyll#5330]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---
- [ ] I am on (or have tested on) **_macOS**_ 10+
- [x] I am on (or have tested on) **_Debian/Ubuntu**_ GNU/Linux
- [ ] I am on (or have tested on) **_Fedora**_ GNU/Linux
- [ ] I am on (or have tested on) **_Arch**_ GNU/Linux
- [ ] I am on (or have tested on) **_Other**_ GNU/Linux
- [ ] I am on (or have tested on) **_Windows**_ 10+

---
- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.
## My Reproduction Steps

First, update to Jekyll 3. I don't think you get this in Jekyll 2.

In the config.yml file, add the line
`permalink: /:year-:month-:day_:title`

Then `jekyll build`. You will get `Error:  undefined method 'day_'`
## The Output I Wanted

I want the page to build without errors.

**How can I escape the underscore so it's not part of the day variable name?** I've been using the `/:year-:month-:day_:title` format since 2015 and I'd prefer to keep it, but I can't in Jekyll 3.

@jekyll/stability

Thanks!!

**Comment by fene** [comment]
hmm, this would technically just require modifying the regex in https://github.com/jekyll/jekyll/blob/master/lib/jekyll/url.rb#L88, right?

**Comment by envygeeks** [comment]
@fene in theory... yes.

**Comment by envygeeks** [comment]
@fene let me elaborate that, `_` can be part of the method name, that needs to stay, it's not the gsub that needs to change, it's the replacement, you'll need to split and test the whole and then test the left so that if they do something like what the op did, it doesn't break.

**Comment by fene** [comment]
@envygeeks right, gotcha

**Comment by qpwo** [comment]
Thanks fene, envygeeks. For now what should I do to get my old links working again? Just wait till the next update of jekyll? I could use [redirects](https://help.github.com/articles/redirects-on-github-pages/) but that is less preferable
