### ISSUE TITLE
Highlight rendering is broken

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#5340]
An entire part of [one of my blog post](https://github.com/DirtyF/frank.taillandier.me/blob/gh-pages/_posts/2014-12-14-un-modele-de-branches-git-efficace.md) was missing due to syntax highlight rendering.

Update: closing, as this seems related to Poole Theme, the same file works fine with minima template.

**Comment by crispgm** [comment]
Saw this bug months before. Might be caused by `rouge`?

Use markdown syntax for highlighting should be proposed instead of `{% highlight %}` tags.

**Comment by DirtyF** [comment]
yeah default theme is working fine so I guess it's not a Jekyll bug as per se.
I can't see what's causing parsing to generate such an output.
