### ISSUE TITLE
Antergos Linux “bash: jekyll: command not found”

### ISSUE THREAD

**Issue by thyell** [jekyll/jekyll#5351]
Hello guys!
I'm trying use Jekyll but i can't use, every time when type on terminal this message appear:
`bash: jekyll: command not found`
I don't know more what do.
I've trying get help on [forum](https://talk.jekyllrb.com/t/linux-bash-jekyll-command-not-found/2955) but no one of answers solved my problem.
So, someone can help me?

**Comment by tigefa4u** [comment]
use https://rvm.io/rvm/install/ :+1:
