### ISSUE TITLE
site local and site remote differ

### ISSUE THREAD

**Issue by JazzMaster** [jekyll/jekyll#5353]
Im using the latest jekyll and I found a bug but its a bug because of the way jekyll works.

Local unice boxes use / (root) as a folder, therefore jekyll cannot assume it. The documentation is wrong.

/_site
/assets
should never exist, nor ever be pointed to.

<site_root>/assets
or
/home/<me>/website/<blah blah>/_site

should however exist AND be pointed to. You can link to both of these in one go using RELATIVE links.

You need to use . and .. relative links, assuming all linked items are under a root folder of lets say _site or your master domain. Then everything works.

Otherwise, you cant use a testbed locally, and all your links point to relative webserver root. FINE, this works, but now its hard coded. You want to test and your machine may not be net connected. That is fine, this can be done, as you have a local copy. However, your links are WRONG, and now everything breaks or fails to load.

As documented:

we are told to use /, which points to the root directory of (drive c) under unices. This is WRONG.
/<anything> is generally a system folder. While you can hard link like this, this is probly not what you want. 

Use . and .. (relative to site root) instead.
-Can someone update the documentation?

**Comment by DirtyF** [comment]
@JazzMaster Does the new URL filter `relative_url` in Jekyll 3.3 address your concern?

**Comment by pathawks** [comment]
If you set `baseurl` and use the new URL filters, everything should be ok 👌🏼
