### ISSUE TITLE
Jekyll::Drops::UnifiedPayloadDrop converts valid Liquid drops to a String.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#5354]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I am on (or have tested on) ***Fedora*** GNU/Linux
- [x] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [x] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [x] It was another bug.

---

Jekyll::Drops::UnifiedPayloadDrop#[]= Converts other Liquid drops to a string, this is a not a desired behavior and if it is, then the drop should also convert hashes to a string, as Liquid drops are Liquids safe version of a hash with custom getters.  This is erroneous behavior.

**Comment by parkr** [comment]
Would you please provide a basic example?

**Comment by envygeeks** [comment]
It was the inspection, the inspection does not provide valid introspection into the drop, it converts it to JSON, so when doing a debug inspection it actually gives you invalid information.  That's an entirely different bug, but we are also having trouble getting the payload to stick on that method too, so there are one or more other bugs coming, this bug is invalid.
