### ISSUE TITLE
Invalid date error resolution

### ISSUE THREAD

**Issue by micahtaylor** [jekyll/jekyll#5359]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

```
gem update jekyll
jekyll new foo
cd foo
bundle install
bundle exec jekyll serve
```

## The Output I Wanted

```
     Generating... 
                    done in 0.332 seconds.
 Auto-regeneration: enabled for '/Users/micahtaylor/Sites/foo'
Configuration file: /Users/micahtaylor/Sites/foo/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```
## The Output I Received
```
Generating... 
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/gems/jekyll-3.2.1/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```

## The resolution
I am able to resolve this by excluding vendor dir to the `_config.yml`
```exclude:
- vendor
```

**Comment by DirtyF** [comment]
@micahtaylor thanks for reporting. This behavious is known and already listed in our troubleshooting page: https://jekyllrb.com/docs/troubleshooting/#configuration-problems

**Comment by afeld** [comment]
Thoughts about excluding 'vendor/' by default?

**Comment by bjoernalbers** [comment]
Today I ran into this.
I think `vendor` or `vendor/bundle` should be excluded by default.
Otherwise every new user gets this error too and has to visit the troubleshooting section.

**Comment by DirtyF** [comment]
@bjoernalbers [vendor/bundle is now excluded by default](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/configuration.rb#L21). 

When we excluded `vendor`, it turns out it was a breaking change for those who use Bower and other packages managers who store assets in this folder by default.

**Comment by ashmaroli** [comment]
I was experimenting with **hosting a jekyll site on heroku** and it seems this `exclude: [vendor/bundle]` is still an issue..
I worked around it by explicitly **excluding `vendor/bundle`** instead of relying on default **`vendor/bundle/`**

**Comment by ashmaroli** [comment]
@bjoernalbers  Even though **`vendor/bundle`** is excluded by default, if your `_config.yml` contains an `exclude` key, then the contents of that `key` will override the default setting.
So, adding `vendor/bundle` to it explicitly should solve your issue.

**Comment by bjoernalbers** [comment]
That did solve the problem, thanks.

I suggest that the stock `_config.yml` should exclude `vendor/bundle` so it doesn't mess up your defauls.
Otherwise all fresh installs will run into this too.

What do you think? Shall I send a PR?

**Comment by ashmaroli** [comment]
> Shall I send a PR?

Its been fixed already. :smiley: 
From the next release onward, the stock `_config.yml` will have the `exclude` [commented out](https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml#L33-L43).

**Comment by pathawks** [comment]
#5860 :+1:

**Comment by bjoernalbers** [comment]
nice 👍
