### ISSUE TITLE
jekyllrb development [watch] on windows

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5370]
Its a known fact that `--watch` is a bit buggy on windows platform.
`build.rb` warns windows users about it : 
```ruby
# lib/jekyll/commands/build.rb#L75-L77
if Utils::Platforms.windows?
  Jekyll.logger.warn "", "--watch arg is unsupported on Windows. "
  Jekyll.logger.warn "", "If you are on Windows Bash, please see: " \
    "https://github.com/Microsoft/BashOnWindows/issues/216"
```
This warning also pops up when `jekyllrb site` is locally previewed using `bundle exec rake site:preview` .
But then, there is no problem with auto-regeneration, when a **newly generated blog** is first served and then edited live, on a **windows** machine. 

So I set out to have `site/` mimic the same process used by a newly-generated blog being served.
Instead of modifying `rake/site.rake` I placed a Gemfile at `site/` and `exclude`d it and its `.lock` from processing.
```
~/site> bundle exec jekyll serve
```
then allowed me to `watch` the `site/` dir contents for any changes.

--

Now, the question is, 
```
"Is this technique valid enough to be considered for a merge?"
```
:smile: 

--
/cc @jekyll/documentation

**Comment by DirtyF** [comment]
I couldn't tell, I don't use Windows. 
cc/ @jekyll/windows for a feedback on this.

**Comment by parkr** [comment]
> But then, there is no problem with auto-regeneration, when a newly generated blog is first served and then edited live, on a windows machine.

Can you explain how this is? From what I understand, this is not the case because the underlying library that `listen` uses to track filesystem changes is not particularly robust on Windows.

**Comment by ashmaroli** [comment]
> Can you explain how this is?

I would gladly do so if I could. But unfortunately, no. I've not dug out the answer yet.
But, I can provide more info surrounding this:

--
Since pristine `Jekyll 3.2.1` cant render layouts properly on Windows, my local version has been tweaked to enable that.
I'm on x64 Windows 7 with a 32-bit Ruby 2.3.1 and its allies.

--

This is the console log after serving a newly generated blog:
```
bundle exec jekyll serve


Configuration file: C:/qwertyui/_config.yml
            Source: C:/qwertyui
       Destination: C:/qwertyui/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.796 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'C:/qwertyui'
Configuration file: C:/qwertyui/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.

```
- Now i simply edit `./about.md` by making some random changes and saving. The console log then updates to:
```
Configuration file: C:/qwertyui/_config.yml
            Source: C:/qwertyui
       Destination: C:/qwertyui/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.796 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'C:/qwertyui'
Configuration file: C:/qwertyui/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2016-09-19 08:39:52 ...done in 0.312 seconds.

```

**Comment by ashmaroli** [comment]
Now when I try to preview the `site/` of  this repo:

```
bundle exec rake site:preview

Running Jekyll...
Configuration file: C:/Sites/Github/jekyll/site/_config.yml
            Source: C:/Sites/Github/jekyll/site
       Destination: C:/Sites/Github/jekyll/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Opening in browser...
                    done in 42.052 seconds.
                    --watch arg is unsupported on Windows.
                    If you are on Windows Bash, please see:  
https://github.com/Microsoft/BashOnWindows/issues/216
Configuration file: C:/Sites/Github/jekyll/site/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.

```
This doesnt update when I edit any of the files in `site/_docs/`

--

- Now I add a Gemfile to `./site` and restart the server from `./site/` : 
```sh
# run git status to show the presence of a new file:
$ git status

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        site/Gemfile

nothing added to commit but untracked files present (use "git add" to track)

# cd to /site dir
cd site

# start jekyll server from there:
$ bundle exec jekyll serve

Configuration file: C:/Sites/Github/jekyll/site/_config.yml
            Source: C:/Sites/Github/jekyll/site
       Destination: C:/Sites/Github/jekyll/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 31.696 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'C:/Sites/Github/jekyll/site'
Configuration file: C:/Sites/Github/jekyll/site/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.

``` 
- And finally when I edit a random file inside `_docs/` and hit save: 
```sh

Configuration file: C:/Sites/Github/jekyll/site/_config.yml
            Source: C:/Sites/Github/jekyll/site
       Destination: C:/Sites/Github/jekyll/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 31.696 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'C:/Sites/Github/jekyll/site'
Configuration file: C:/Sites/Github/jekyll/site/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2016-09-19 03:34:57 ...done in 38.807269 seconds.

```

**Comment by parkr** [comment]
The reason we use the rake task is because we auto-generate content into the site.

What is it you are proposing here? I see that watch is working for you based on your output. Are you sure `force_polling` isn't turned on there?

**Comment by ashmaroli** [comment]
> What is it you are proposing here?

outlined in the PR-5393 :point_up_2:

**Comment by ashmaroli** [comment]
> Are you sure force_polling isn't turned on there?

I'm using a tweaked gem. 
But for this case, any windows user can test it with a pristine Jekyll gem

--
/cc @XhmikosR , @envygeeks 
it'd be nice, if either of you can reproduce this..
Thanks

**Comment by envygeeks** [comment]
I'll get on my Windows machine tonight when I'm not working and see what I can produce.

**Comment by ashmaroli** [comment]
Closing this as none of what I described above works with jekyll repo HEAD instead of jekyll 3.2.1
