### ISSUE TITLE
[NEW FEATURE] Execute script before building

### ISSUE THREAD

**Issue by djcaesar9114** [jekyll/jekyll#5378]
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

---

- [x] I was trying to build.
- [x] It was another bug.

## Feature requested

When I build my website, I'd like Jekyll to execute some scripts first.
Why not creating a "_scripts" folder, in which Jekyll could execute the scripts before building the website?

When you run `jekyll build`, Jekyll checks the files in the`_script` folder and execute them before actually building the website.
Let's say you have to run two scripts, `clean.sh` and `initialize.sh` before running `jekyll build`. If you put them in the `_scripts` folder, you don't have to run them manually.

Other option, you can configure in the `_config.yml` the scripts you want to be executed after the build, for example by precising `after: cleanup.sh`.

**Comment by ashmaroli** [comment]
Hi, you have not provided an example case for us to even consider this request.

**Comment by pathawks** [comment]
Like `_plugins/`?

**Comment by djcaesar9114** [comment]
@ashmaroli : now I did
@pathawks : no

**Comment by budparr** [comment]
Don't know if this is what you're looking for, @djcaesar9114 but I think a lot of people use Gulp, or Grunt, or NPM, or a Make file for this sort of thing. I [personally](https://github.com/budparr/jekyll-base/blob/master/package.json) run an NPM script that process scripts (and other things), and build Jekyll for me.

**Comment by djcaesar9114** [comment]
@budparr : yeah I see what you mean. I used to work with a lot of these stuff, but with the benefit of hindsight, I know that the less technologies I use for a project, the better the development. That's why I'd like to have prehooks and posthooks directly in Jekyll.
But your solution sure works! :)

**Comment by budparr** [comment]
Yeah, I agree wth you on keeping things simple, but worth noting that by keeping scripts out of the Jekyll build process you speed up your build times. That's particularly helpful since you're not always going to need to process them, like when just adding content. (I'm particularly sensitive to build time, so this issue may be more important to me than to others)

**Comment by DirtyF** [comment]
@djcaesar9114 : Jekyll has [hooks](https://jekyllrb.com/docs/plugins/#hooks).

cc @jekyll/core

**Comment by djcaesar9114** [comment]
@DirtyF : yeah, but you can only put ruby lines (although I like ruby) and `:site` & `:pre_render` doesn't match the exact moment I'd like to execute my bash scripts.

**Comment by pathawks** [comment]
> but you can only put ruby lines (although I like ruby)

>  I know that the less technologies I use for a project, the better the development.

You can always use a simple Ruby plugin to launch whatever shell script you’d like to run :+1:

If there is not a hook that works for your use case, _that_ is a conversation worth having.

**Comment by parkr** [comment]
@djcaesar9114 Feel free to submit a PR to add the hook you need. Based on what you have above, you should either wrap Jekyll in your own script (run before Jekyll starts) or `:site, :pre_render` will work. If not, please elaborate in your PR. Thanks!

**Comment by djcaesar9114** [comment]
@parkr : actually :pre_render don't work either. I mean it works the first time I run a build, but when I do `jekyll serve`, when I edit any file (let's say a file in the `_layout` folder), my Ruby plugin runs again and again...
I don't know how to elaborate more than I did: I'd like to execute a script before all the `build` process, just once. Whenever I use a hook, my ruby script is executed infinitely when I edit any file. :(

**Comment by parkr** [comment]
@djcaesar9114 The hook is called every time you edit a file *but* you can keep track of how many times your code is executed. All you have to do is, once your code runs, set a variable that will persist its value between runs and before running your code check to see if the variable is set. 


```ruby
module RunMeOnce
  def self.process(site, payload)
    return if @processed
    # ... Your code here.
    @processed = true
  end
end

Jekyll::Hooks.register :site, :pre_render do |site, payload|
  RunMeOnce.process(site, payload)
end
```

**Comment by djcaesar9114** [comment]
@parkr : I understand, but I think I didn't explain myself clear enough: I don't want the script to be executed only once before the first build, I want it to be executed not only once before the first build, but also after the edition of every file.
The solution you gave works perfectly if I'd wanted to run the script once and for all.
