### ISSUE TITLE
Site fails to load with basic clone && push to gh-pages on Enterprise 2.4

### ISSUE THREAD

**Issue by sylvesterjakubowski** [jekyll/jekyll#5382]
- [X] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [X] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [X] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

"Create a new (empty) repo on github enteprise (2.4 in my case)
git clone git@github.com:jekyll/jekyll.git
cd jekyll

git remote rm origin
git remote add origin git@myent:org/blog.git
git checkout -b gh-pages
git push -u origin gh-pages

Recieved:

 Your site is having problems building: The symbolic link /test/source/_includes/tmp targets a file which does not exist within your site's repository. For more information, see https://help.github.com/enterprise/2.4/user/articles/page-build-failed-symlink-does-not-exist-within-your-site-s-repository.

## The Output I Wanted

The page to generate.

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

I came here via:
https://www.smashingmagazine.com/2014/08/build-blog-jekyll-github-pages/

Thanks!

**Comment by Crunch09** [comment]
Hi @sylvesterjakubowski ,

in the article you linked it is recommended to fork https://github.com/barryclark/jekyll-now as a starting point. Based on your reproduction steps you cloned `jekyll/jekyll` instead which is the site generator itself. Hope this helps!

**Comment by sylvesterjakubowski** [comment]
It does, thanks!
