### ISSUE TITLE
[NEW FEATURE] layout.layout shall return a layout not a string

### ISSUE THREAD

**Issue by HuStmpHrrr** [jekyll/jekyll#5387]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

it seems unreasonable for me to have layout.layout to give a string "default".

### test case:
in `_layouts/post.html`

```
---
layout: default
---
{{ layout.layout }}
```

it gives `"default"`, which is very much unexpected. 

## The Output I Wanted

```
{{ layout.layout }}
```

shall return an object that is an layout, or null if not exist. to extend the same idea, there is no reason for `layout.layout.layout` to only return a string either and so for the more nested cases.

hope it should be easy. it 's very much unexpected behavior for me to not being able to access the inner layer of a layout.

**Comment by parkr** [comment]
This would be a breaking change. Users are already using `layout.layout` to write CSS classes and such–if we changed it to an object, we'd break all those sites. We cannot break sites until Jekyll 4.

Thanks for the suggestion, closing this out for now.
