### ISSUE TITLE
Deploying on several websites with one easy script

### ISSUE THREAD

**Issue by djcaesar9114** [jekyll/jekyll#5395]
# This is a hint suggestion

- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.
- [x] This is a hint, as described [here](https://jekyllrb.com/docs/home/)

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.
- [x] I want to deploy my Jekyll built website easily

## My Reproduction Steps

When I've finished building my website with Jekyll, I run a script which deploys automatically my built site wherever I want, easily.
I used this: https://github.com/djcaesar9114/deploy_jekyll

## The Output I Wanted

I wanted to have my website deployed on every server I want.

/cc @jekyll/documentation

**Comment by pathawks** [comment]
What is your question? I'm not sure I understand the issue.

**Comment by djcaesar9114** [comment]
@pathawks : Sorry, I didn't copied all the description of my script. I edited my issue, that is actually a documentation improvement.

**Comment by DirtyF** [comment]
@djcaesar9114 I'm not sure that we can list all existing deploy scripts or Rakefiles on the website. The deploy section seems already rather complete to me, and your deploy script looks very similar to the one already described on http://jekyllrb.com/docs/deployment-methods/#rsync

That's why I expressed a 👎 on your suggestion, but if other Jekyll team members disagree, feel free to submit a PR.

**Comment by djcaesar9114** [comment]
OK! I understand the point of views :)
