### ISSUE TITLE
Error in the hook documentation

### ISSUE THREAD

**Issue by djcaesar9114** [jekyll/jekyll#5396]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

I have a hook in `_plugin` folder. The content of the hook is not relevant, all that matters is that it's written as requested in [the documentation](https://jekyllrb.com/docs/plugins/#hooks), specially the "after_init" part.

```
Jekyll::Hooks.register :site, :after_init do
# my code
```

## The Output I Wanted

I wanted my website to be built correctly.

## What I got

This message in the terminal:

```
jekyll 3.1.6 | Error:  Invalid hook. site supports only the following hooks [:after_reset, :post_read, :pre_render, :post_render, :post_write]
```

/cc @jekyll/documentation

**Comment by ashmaroli** [comment]
`after_init` was added in Jekyll 3.2.0
Updating your Jekyll gem should solve your issue.

**Comment by djcaesar9114** [comment]
OK, my bad, I forgot `bundle update` and my project was still build with the 3.1.6 version of the gem.
Thanks!
