### ISSUE TITLE
Unsuccessful installation

### ISSUE THREAD

**Issue by xipingsg** [jekyll/jekyll#5401]
sudo 

I have searched all the possible ways in the [stackoverflow](http://stackoverflow.com/questions/31972968/cant-install-gems-on-os-x-el-capitan)
include    
`gem install jekyll bundler`  
and   
`sudo gem install jekyll bundler`   

And it will shows the error like    
`ERROR:  While executing gem ... (Errno::EPERM)    `
  `  Operation not permitted - /usr/bin/listen`   
   
When I type `~ $ jekyll new my-awesome-site`
-bash: jekyll: command not found

**Comment by crispgm** [comment]
which OS do you use?

**Comment by xipingsg** [comment]
EI Captain

**Comment by crispgm** [comment]
Try this: <https://jekyllrb.com/docs/troubleshooting/#jekyll-amp-mac-os-x-1011>

**Comment by pathawks** [comment]
@xipingsg I hope you get everything straightened out.

I am closing this issue, as this isn't the place to get help with installation _but_ if you are still having trouble please post a message at https://talk.jekyllrb.com/
