### ISSUE TITLE
Following quick start gives a malformed site

### ISSUE THREAD

**Issue by 3ncrypter** [jekyll/jekyll#5404]
I am very new to jekyll. I tried the quick start guide mentioned on the homepage which is 

> ~ $ gem install jekyll bundler
> ~ $ jekyll new myblog
> ~ $ cd myblog
> ~/myblog $ bundle install
> ~/myblog $ bundle exec jekyll serve
> #=> Now browse to http://localhost:4000

but it is giving me a malformed site 
![screenshot from 2016-09-24 00-15-14](https://cloud.githubusercontent.com/assets/5441349/18797653/8abb6dfa-81ec-11e6-822c-b45bfb66582a.png)
until I am modifying the _config.yml site. 
changing this `url: "http://example.com" # the base hostname & protocol for your site` to this `url: "" # the base hostname & protocol for your site` in _config.yml file makes it work for me. Am I missing something or this is the default behaviour ? And if it is, shouldn't there be a mention of this in the quick start ?

**Comment by jaybe-jekyll** [comment]
Hi; and welcome. You come at a time of transition to gem-based themes which are awesome.

The default `_config.yml` that comes with the default `minima` theme contains a configuration variable, `url: http://example.com`.

This default configuration is about to change to keep things from breaking upfront.

For now, you can comment out the `url:` configuration variable, or change it to your domain.

**Comment by jaybe-jekyll** [comment]
Bonus: Use/view your web browser developer tools to see the CSS resource that is being called (http://example.com/style.css) and not found, explaining why the site styling breaks.

![screen shot 2016-09-23 at 2 15 13 pm](https://cloud.githubusercontent.com/assets/5395940/18798446/396a1b4e-8198-11e6-85fb-85f64b65d923.png)

**Comment by pathawks** [comment]
Thanks @jaybe-jekyll for such a good explanation.

@3ncrypter Sorry that your first experience with Jekyll led you so quickly into a roadblock. We are working to improve this in the next version:+1:

**Comment by 3ncrypter** [comment]
@jaybe-jekyll  @pathawks Thank you very much both of you for your help. @jaybe-jekyll as said earlier, I figured that out, but because it was not mentioned anywhere so I thought I am missing something that is why it is giving me a wrong config/css path. By the way, I am lovin it (coming from wordpress). Thanks again. Cheers. :+1:  :)
