### ISSUE TITLE
Bug installing new plugins via RubyGems

### ISSUE THREAD

**Issue by g4brielvs** [jekyll/jekyll#5406]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

When I tried installing a new plugin ([jekyll-crosspost-to-medium](https://rubygems.org/gems/jekyll-crosspost-to-medium)) simply adding it to `_config.yml` Jekyll gets me an error.

<img width="1279" alt="screenshot 2016-09-24 00 23 37" src="https://cloud.githubusercontent.com/assets/4053416/18805789/3353113e-81ed-11e6-8a83-23763190513f.png">

I tried installing it explicitly in `_plugins/jekyll-crosspost-to-medium.rb` and it worked just fine! If I can be of any assistance, I would really appreciate some insights.

## The Output I Wanted

I wanted to install new plugins via [Rubygems](https://rubygems.org/). Particularly [jekyll-crosspost-to-medium](https://rubygems.org/gems/jekyll-crosspost-to-medium).

/cc @jekyll/build

**Comment by mmistakes** [comment]
@g4brielvs You need to `gem install` the plugin as well. Just adding it to your _config.yml isn't enough.

The plugin has more detailed installation instructions I suggest you give a look over.

https://github.com/aarongustafson/jekyll-crosspost-to-medium

> This plugin can be installed in two ways:
> 
> As a Ruby Gem: gem install jekyll-crosspost-to-medium
> Via `_config.yml` add `jekyll-crosspost-to-medium` to your gems list; or
> Add `require 'jekyll-crosspost-to-medium'` to `ext.rb` in your plugins directory (new or existing one)
> By directly copying jekyll-crosspost-to-medium.rb (found in the lib directory) into your plugins directory.

**Comment by g4brielvs** [comment]
@mmistakes Thank you for replying. I thought I had installed it locally, but I haven't. My bad :(
