### ISSUE TITLE
Delete gh-pages branch and use master /docs instead (?)

### ISSUE THREAD

**Issue by zdroid** [jekyll/jekyll#5409]
You can choose where the source of your GitHub Pages site should come from in repository settings. The best feature it offers is to use `/docs` directory of master branch for deploying Pages. So why not use it for Jekyll, too? (Unless it really destroys the ecosystem of the project managment.)

So, you have to move `/site` directory to `/docs` and the actual docs to somewhere else. It'll require no need to maintain two branches anymore.

Thoughts?

**Comment by parkr** [comment]
Yes, I would like to do this. We could move the current `/docs` to `/docs-for-maintainers`. I believe @benbalter has been meaning to submit a PR for this.

The reasons I had liked doing it manually were:

1. We get to test Jekyll `master` to ensure it can still build a site properly
2. We get to choose when to release new docs. Sometimes we don't version things properly.

**Comment by envygeeks** [comment]
I'm okay with this, would make it easier.

**Comment by benbalter** [comment]
WIP over in https://github.com/jekyll/jekyll/issues/5459.

**Comment by zdroid** [comment]
Great to see this done. :tada: :tada: :tada:
