### ISSUE TITLE
Add group_by_exp filter

### ISSUE THREAD

**Issue by caspervonb** [jekyll/jekyll#5415]
Similar semantics with `where_exp`.

Usage:

```
{% assign groups = data | group_by_exp: "item", "item.version | split '.' | first" %}
```

Why? If you have compound data, in this example I have a bunch of data with semver strings. Grouping this by major version for example turns what could be a one liner into a huge 100 line mess.

**Comment by parkr** [comment]
This seems really great. Would love to see a PR. These filters are currently in `lib/jekyll/filters.rb`.

**Comment by levlaz** [comment]
I want to take a stab at this. 

@caspervonb could you please provide some sample data and what you would expect to see?

**Comment by caspervonb** [comment]
@levlaz 

The need came up when (ab)using Jekyll to create https://github.com/hasharray/jsperf/ where I have a bunch of browser versions.

Which leads to this mess https://github.com/hasharray/jsperf/blob/master/_layouts/benchmark.html#L91-L134.

```liquid
{% assign versions = browser.items | group_by_exp: "item", "item.version | split: '.' | first" %}
```

Would expect it to group by the result of any valid liquid expression, same way where_exp works except grouping by the value rather than truthy/falsy.

As a tangent, a closely related one is `map_exp`, useful to avoid creating throw away loops to to nested mapping (/cc @parkr on that). To much bloat? They're very generic filters at-least.

**Comment by thiagoarrais** [comment]
@levlaz: have you got anything so far? I'm willing to lend a hand here.

**Comment by levlaz** [comment]
@thiagoarrais sorry not yet :( 

Please feel free!

**Comment by pathawks** [comment]
@thiagoarrais I haven't seen a Pull Request yet. It would be awesome if you could get things going :+1:

**Comment by thiagoarrais** [comment]
Excelent!

PR #5513 (literally nothing) is everything I could get done so far. I foresee having sometime this week to take a look at this.

Please feel free to post any suggestions and/or feedback on this issue or on the PR.
