### ISSUE TITLE
I can't create new themes.

### ISSUE THREAD

**Issue by Catalin08** [jekyll/jekyll#5418]
So, I am using a distribution of Debian 8 and I want to build my own blog with jekyll, but I have some problems.First of all, I want to create a new theme, so I use the command jekyll new-theme mytheme and it gives me:

`jekyll new-theme mytheme
             create /home/catalin/Dropbox/local/sites/mytheme/_layouts
             create /home/catalin/Dropbox/local/sites/mytheme/_includes
             create /home/catalin/Dropbox/local/sites/mytheme/_sass
             create /home/catalin/Dropbox/local/sites/mytheme/_layouts/page.html
             create /home/catalin/Dropbox/local/sites/mytheme/_layouts/post.html
             create /home/catalin/Dropbox/local/sites/mytheme/_layouts/default.html
             create /home/catalin/Dropbox/local/sites/mytheme/Gemfile
jekyll 3.2.1 | Error:  No such file or directory - git
`

Looking at documentation, a file is missing from here, look at this line in the documentation example:

`create /path/to/my-awesome-theme/my-awesome-theme.gemspec`

The file that has the .gemspec extension is missing so I am unable to really create this theme.

I have ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu] and I have rubygems installed.
I use bundler 1.1.5 and when I type bundle install in the mytheme directory I recieve the following error:

`bundle install
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubygems/format (LoadError)
       /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler/source.rb:5:in `<top (required)>'
       /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler/dsl.rb:19:in `initialize'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler/dsl.rb:6:in `new'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler/dsl.rb:6:in `evaluate'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler/definition.rb:18:in `build'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler.rb:135:in `definition'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler/cli.rb:220:in `install'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler/vendor/thor/task.rb:22:in `run'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler/vendor/thor.rb:263:in `dispatch'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/lib/bundler/vendor/thor/base.rb:386:in `start'
       /var/lib/gems/2.3.0/gems/bundler-1.1.5/bin/bundle:13:in `<top (required)>'
       /usr/local/bin/bundle:22:in `load'
       /usr/local/bin/bundle:22:in `<main>'
There was an error in your Gemfile, and Bundler cannot continue.
`

The Gemfile created in the my theme directory has the following code:

`
source "https://rubygems.org"
gemspec`

I get this erorr too when I try bundle install

`
[!] There was an error parsing `Gemfile`: There are no gemspecs at /home/catalin/Dropbox/local/sites/mytheme. Bundler cannot continue.

 #  from /home/catalin/Dropbox/local/sites/mytheme/Gemfile:2
 #  -------------------------------------------
 #  source "https://rubygems.org"
 >  gemspec
 #  -------------------------------------------
`

**Comment by ashmaroli** [comment]
Hello @Catalin08,
it looks like you dont have git installed.
Please run the following to check:
```
$ git --version
```
If you dont have git installed, you can start [here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).

You dont need `rubygems` to be installed to have jekyll create the `mytheme.gemspec` file but to check, please run:
```
$ gem --version
```
If not found, get it [here](https://rubygems.org/pages/download).

--

If you have git installed, please provide us with more info by:
- run jekyll `new-theme` once more with a different name
- If you get errors again, post a screenshot of the error block, if you can, otherwise copy-paste like you did before.
- change directory into your theme-folder and run:
```
git ls-files -z
```
and copy-paste the resulting line here.

**Comment by Catalin08** [comment]
Thanks, git was the problem, I didn't had it installed on my machine.
