### ISSUE TITLE
Jekyll incorrectly processes _data subdirs with a period in the name

### ISSUE THREAD

**Issue by djosborne** [jekyll/jekyll#5429]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

---

## Issue
I'm unable to access data in a  `_data/` subdirectory via the `site.data` array if that subdirectory includes a period `.` in the name/path. It seems jekyll strips everything after the period when storing in the `site.data` array.

## My Reproduction Steps
```
mkdir _data/0.1
touch  _data/0.1/this.yml
```

Then I use this code to simply print `site.data`:
```
{{ site.data }}
```
I see this as the output:
```
{"0"=>{"this"=>false}}
```

I expect this:
```
{"0.1"=>{"this"=>false}}
```

**Comment by parkr** [comment]
Thanks for the report! If you have time, [the relevant code is here](https://github.com/jekyll/jekyll/blob/aa901cdaba54efcd430cd09e1aec09a9bedb3b9d/lib/jekyll/readers/data_reader.rb#L40).

**Comment by ashmaroli** [comment]
please remove the `help-wanted` label. This issue is being handled..
