### ISSUE TITLE
Permalink with month name

### ISSUE THREAD

**Issue by singpolyma** [jekyll/jekyll#5439]
Is there a way for me to have a permalink style like   `/blog/2016/jan/06/title-of-post/`  ?

**Comment by mmistakes** [comment]
Unless I'm missing something don't think you can do month's spelled out.

http://jekyllrb.com/docs/permalinks/

**Comment by parkr** [comment]
Doesn't look like that's possible. https://github.com/jekyll/jekyll/blob/master/lib/jekyll/drops/url_drop.rb

**Comment by singpolyma** [comment]
@parkr if I write a plugin and monkeypatch `UrlDrop` -- will that let me add this?

**Comment by singpolyma** [comment]
Actually, this is basically in there already as `short_month` -- though that uses a capital letter and I'd like all-lowercase
