### ISSUE TITLE
"Theme" property broke JKAN :(

### ISSUE THREAD

**Issue by timwis** [jekyll/jekyll#5443]
Hey folks, I'm the author of [JKAN](https://jkan.io), a Jekyll-powered open data portal. One of our contributors [reported](https://github.com/timwis/jkan/issues/127) that builds suddenly started failing on GitHub Pages, and it looks like this was caused by the latest version of Jekyll reserving the `theme` property in `_config.yml` for its new themes feature. JKAN uses that property for its own themes feature (using bootswatch themes).

<img width="1264" alt="screen shot 2016-10-04 at 10 33 44" src="https://cloud.githubusercontent.com/assets/761444/19078422/0e17be36-8a1e-11e6-9e42-aab3819bcb62.png">

Because Jekyll doesn't recognise themes like "Paper", "Cerulean", etc., the build fails.

As a hotfix, we changed the property to `jkan_theme`. But anyone who uses JKAN won't be able to use their site until they upgrade, and I'm not sure how to notify everyone to upgrade.

Is there any way to not make the build fail if Jekyll doesn't recognise the `theme`?

**Comment by jaybe-jekyll** [comment]
I think what has happened is the term, "theme", was employed as a custom front matter variable and used within a framework prior to Jekyll Themes and the introduction of the now-reserved-term, "theme". i.e. name-space collision.

Outside of core, it's probably best to uniquely identify custom variables and functionalities by prefixing as you've described.

**Comment by parkr** [comment]
Hey, @timwis! Sorry about this – you're absolutely right, there's a conflict here. I haven't used JKAN before but I like the project a lot and would like to reduce friction here for your users. How do themes work in JKAN? Is there a directory they pull down? In an ideal world, we'd be able to use gem-based themes here, but I'm happy to work with you here. If you could provide more info about how this works, that'd be wonderful.

**Comment by timwis** [comment]
Thanks @parkr! Here's how themes work in JKAN: There's a [_data/themes.yml](https://github.com/timwis/jkan/blob/gh-pages/_data/themes.yml) file that's just a list of theme hashes (name, logo, source path to CDN). The themes are just [bootswatch](https://bootswatch.com/) themes that work on top of bootstrap. Them in [`_includes/head.html`](https://github.com/timwis/jkan/blob/gh-pages/_includes/head.html#L10-L14), it checks what `site.theme` is set to (it now uses `site.jkan_theme`) and adds a `<link>` tag with the theme's source path if there is one. There's a [UI page](https://demo.jkan.io/admin/) that lets you change the `theme` setting in `_config.yml`, but nothing magical is happening there - it just uses GitHub's API.

Thanks for looking into this

**Comment by parkr** [comment]
@timwis Thank you for the thorough explanation! I think I understand it.

I think moving forward the best thing to do is to use namespaced properties, like `jkan_theme` or `jkan.theme` (a hash of all `jkan` properties, one of the keys being `theme`). In terms of coding defensively, this would be the best possible route for ensuring JKAN's configuration is never touched by Jekyll core. Having a `Gemfile` would further help here, save running on GitHub Pages.

Would you also consider using a gem-based theme? That way, you could depend on a particular version of Jekyll and handle versioning. Not sure if that's even on your radar, but that might provide the best user experience.

**Comment by parkr** [comment]
We'll leave this the way it is for now! GitHub Pages now warns instead of erroring. 🎉

**Comment by timwis** [comment]
Nick just emailed me about the push this morning - thanks so much for the resolution! We'll certainly use namespaced properties going forward (a `jkan` hash is a good idea too). I haven't used the new gem-based Jekyll themes, but I'll certainly check them out. My impression is that they work a bit differently than something as simple as a bootswatch theme, but I may be wrong.
