### ISSUE TITLE
Question: how to manually process Liquid tags in Jekyll

### ISSUE THREAD

**Issue by sonirico** [jekyll/jekyll#5444]
I am creating a Jekyll theme where all user pages that implement the 'indexable' attribute in the front matter are rendered in the main landing page. So I have the 'frontpage layout:

    ---
    layout: root
    ---
    
    {% assign custom_pages = site.pages | where: 'indexable', true | sort: 'priority' | reverse %}
    
    {% include header.html %}
    
    {% for c_page in custom_pages %}
    <div class="container {{ c_page.class | default: '' }}" >
        {{ c_page.content }}
    </div>
    {% endfor %}
    
    
    {% include footer.html %}
    {% include javascripts.html %}

A sample page that will be processed: 

    ---
    layout: page
    title: Us
    permalink: /us/
    indexable: true
    priority: 10
    class: us-page
    ---
    
    <div class="row">
        {% for member in site.data.members %}
        <div class="col-sm-6">
            <div class="card card-block">
                <img src="{{ member.gravatar }}?s=256" alt="Avatar">
                <h4 class="card-title text-xs-center">{{ member.name }}</h4>
                <p class="card-text">{{ member.description | markdownify }}</p>
                <p class="card-text">
                    {% for tag in member.expertise_areas %}
                        <span>{{ tag }}</span>
                    {% endfor %}
                </p>
                <a href="{{ member.blog }}" class="btn btn-primary" role="button" >Mi blog</a>
            </div>
        </div>
        {% endfor %}
    </div>

However the liquid tags are appearing unprocessed, like the same output  `{% raw %}` would produce. Is there a way through I could do `{{ c_page.content | magic_here }}` in order to manually get rendered those tags? 

**EDIT**. Screenshot:
[![enter image description here][1]][1]

**EDIT2**

 - [Theme repository](https://github.com/sonirico/geekyll)
   
 - [Web implementation](https://github.com/katodia/katodia.com)

  [1]: http://i.stack.imgur.com/f4KPW.png

**Comment by DirtyF** [comment]
Hi @sonirico, 

You should find help on our forum: https://talk.jekyllrb.com/, themes are a ♨️  topic at the moment.

Closing this as GitHub issues are only dedicated to Jekyll's 🐛🐛🐛

**Comment by sonirico** [comment]
Ok, it doesn't matter. Just in case anyone else who has run into an issue **like** this, I found a way to go around and posted it as my own solution:
http://stackoverflow.com/questions/39858593/how-to-manually-process-liquid-tags-in-jekyll
