### ISSUE TITLE
Jekyll serve remove a draft after I edit it.

### ISSUE THREAD

**Issue by oncleben31** [jekyll/jekyll#5446]
- [x ] I believe this to be a bug, not a question about using Jekyll.
- [ x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

---

- [x ] I was trying to build.

## My Reproduction Steps

From a Jekyll site with minima:
*   I create a draft named test.markdown in `_drafts`folder
```markdown
---
layout: post
title:  "test"
---
test3
````
*   I launch the local server with the command 'bundle exec jekyll serve --config _config.yml,_config.dev.yml --host 0.0.0.0 --force_polling --drafts -V``
*   I check with chrome the draft is accessible.
*   When I edit the draft and save it, I see the local server detect a change and relaunch the build but the draft is deleted from the _site folder.

## The Output I Wanted

The draft should be accessible after a refresh triggered by Jekyll serve
/cc @jekyll/build

**Comment by pathawks** [comment]
What plugins are you using?
Unfortunately, I believe this is a known issue of a couple of our plugins, not related to Jekyll Core.

**Comment by oncleben31** [comment]
Only the plugins shipped with the standard installation 
my Gemfile:
```yaml
source 'https://rubygems.org'
ruby RUBY_VERSION
require 'json'
require 'open-uri'
versions = JSON.parse(open('https://pages.github.com/versions.json').read)
gem 'github-pages', versions['github-pages']
#gem 'activesupport', versions['activesupport']
gem "html-proofer"
```

**Comment by pathawks** [comment]
Seems related to jekyll/jekyll-feed#135

**Comment by oncleben31** [comment]
This plugin is not activated on my Jekyll site.
You can look at [my repo oncleben31.github.io](https://github.com/oncleben31/oncleben31.github.io)

**Comment by pathawks** [comment]
You have **jekyll-sitemap** enabled, which has the same issue as **jekyll-feed**

I'm real sorry this is happening. Please open a ticket for **jekyll-sitemap** so we can track this over there.
