### ISSUE TITLE
Jekyll 3.3.0.pre.rc1 - Some bugs

### ISSUE THREAD

**Issue by djacquel** [jekyll/jekyll#5453]
Gemfile :

    gem "jekyll", "3.3.0.pre.rc1"

Commands :

    bundle install
    bundle exec jekyll new . --force
    bundle update
    bundle exec jekyll serve

### Build warning

A required layout doesn't exist.

```
[...]
Generating... 
Build Warning: Layout 'home' requested in index.md does not exist.
[...]
Server address: http://127.0.0.1:4000/
Server running... press ctrl-c to stop.
```

### Navigating to http://127.0.0.1:4000/

- Index is blank.
- About is unstyled.
- CSSs are pulled from http://localhost:4000/css/main.css and not http://127.0.0.1:4000/css/main.css .
- **CSS are not generated** and then CSS folder is not present in the _site folder

**Comment by ashmaroli** [comment]
known issue. ref: [comment](https://github.com/jekyll/jekyll/issues/5400#issuecomment-251860656)
fix: [comment](https://github.com/jekyll/jekyll/issues/5400#issuecomment-251878058)

**Comment by DirtyF** [comment]
@djacquel thanks for the feedback, you're right rc1 needs minima 2.0 in order to run properly, it wasn't specified. 😕 

If you want to run firther tests, please modify your `Gemfile` to use Minima Github repo:

`gem 'minima', github: 'jekyll/minima', branch: 'master'`

**Comment by ashmaroli** [comment]
Tip: `branch: 'master'` is not required.  `gem 'minima', github: 'jekyll/minima'` is sufficient
