### ISSUE TITLE
Liquid Exception: Liquid syntax error (line 123): Variable '{{0,1}' was not properly terminated with regexp: /\}\}/ in xxx.md

### ISSUE THREAD

**Issue by livc** [jekyll/jekyll#5458]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps
After`jekyll server`, I get:
```
➜  livc.github.io git:(master) ✗ jekyll server
Configuration file: /Users/zhao/repo/livc.github.io/_config.yml
            Source: /Users/zhao/repo/livc.github.io
       Destination: /Users/zhao/repo/livc.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Liquid syntax error (line 123): Variable '{{0,1}' was not properly terminated with regexp: /\}\}/ in /Users/zhao/repo/livc.github.io/_posts/2016-02-07-neu1682.md
jekyll 3.2.1 | Error:  Liquid syntax error (line 123): Variable '{{0,1}' was not properly terminated with regexp: /\}\}/
```
But nothing in line 123 as <http://pastebin.com/vZszwbvt>

When I change line 134 from
`int dis[4][2]={{0,1},{0,-1},{1,0},{-1,0}};`
to
`int dis[4][2]={ {0,1},{0,-1},{1,0},{-1,0}};`

It fixed !

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by ashmaroli** [comment]
this is probably because liquid looks for tags with double-curlies `{{`, `}}` or curly-percent `{%` `%`} by adding that whitespace in between, its no longer a liquid tag..

**Comment by pathawks** [comment]
Wrap that whole line with `{% raw %}`…`{% endraw %}` to let Liquid know not to try to parse it :+1:
