### ISSUE TITLE
jekyll 3.3.0 | Error:  undefined method `cyan'

### ISSUE THREAD

**Issue by alessiofx** [jekyll/jekyll#5461]
when i create jekyll new my-awesome-site

I am returned:

jekyll 3.3.0 | Error:  undefined method `cyan' for "/Users/user/Desktop/dd/my-awesome-site":String

why ?

**Comment by DirtyF** [comment]
Seems related to https://github.com/jekyll/jekyll/commit/a9f92278d3987f5d1eec7499e6a5a312569f413a /cc @ashmaroli

**Comment by ashmaroli** [comment]
yes, its related to that commit..
This error shouldnt occur when `colorator` has been installed.. and it should be installed along with jekyll.. 
:thinking:

**Comment by alessiofx** [comment]
ok i fix 
but now i have another error:
jekyll 3.3.0 | Error:  uninitialized constant Bundler::Plugin::API::Source

**Comment by ashmaroli** [comment]
do you have Bundler installed?
If not, install by `gem install bundler`
if yes, please post the contents of your `Gemfile.lock` here

**Comment by alessiofx** [comment]
Yes i have installed bundler
but where is gem file.lock ?

**Comment by ashmaroli** [comment]
you should have that in your site root _after_ you run `bundle exec jekyll build`

**Comment by alessiofx** [comment]
ok i fixed with:
sudo gem update --system


now i have another problem:


`AleX-Mainframe:cc Alessio$ jekyll new my-awesome-site
New jekyll site installed in /Users/Alessio/Desktop/cc/my-awesome-site. 
Running bundle install in /Users/Alessio/Desktop/cc/my-awesome-site... 
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using addressable 2.4.0
Using colorator 1.1.0
Installing ffi 1.9.14 with native extensions
Using forwardable-extended 2.6.0
Using sass 3.4.22
Using rb-fsevent 0.9.7
Using kramdown 1.12.0
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using minima 2.0.0
Using bundler 1.13.2
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/private/var/folders/cy/fq_ctmw51kj98qx588qr1k6h0000gn/T/bundler20161007-9246-1fd5mgpffi-1.9.14/gems/ffi-1.9.14/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -r
./siteconf20161007-9246-1uzmon2.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:434:in `try_do':
The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:549:in
`block in try_compile'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:502:in
`with_werror'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:549:in
`try_compile'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:1038:in
`block in have_header'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:889:in
`block in checking_for'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:340:in
`block (2 levels) in postpone'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:310:in
`open'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:340:in
`block in postpone'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:310:in
`open'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:336:in
`postpone'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:888:in
`checking_for'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:1037:in
`have_header'
	from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

/var/folders/cy/fq_ctmw51kj98qx588qr1k6h0000gn/T/bundler20161007-9246-1fd5mgpffi-1.9.14/extensions/universal-darwin-15/2.0.0/ffi-1.9.14/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/var/folders/cy/fq_ctmw51kj98qx588qr1k6h0000gn/T/bundler20161007-9246-1fd5mgpffi-1.9.14/gems/ffi-1.9.14
for inspection.
Results logged to
/var/folders/cy/fq_ctmw51kj98qx588qr1k6h0000gn/T/bundler20161007-9246-1fd5mgpffi-1.9.14/extensions/universal-darwin-15/2.0.0/ffi-1.9.14/gem_make.out

An error occurred while installing ffi (1.9.14), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.14'` succeeds before bundling.`

**Comment by ashmaroli** [comment]
From the moment, bundle install started running, its no longer an issue related to `jekyll new` or `jekyll v3.3.0` entirely.
I dont hv much experience with non-windows environment, so wont be able to help further..

**Comment by pathawks** [comment]
@alessiofx I'm sorry that you're having trouble installing Jekyll.

The issue tracker here is really just for reporting bugs. You will have better luck getting help installing at https://talk.jekyllrb.com
