### ISSUE TITLE
Autoregeration disabled on Windows

### ISSUE THREAD

**Issue by BladeCode** [jekyll/jekyll#5462]
I am on (or have tested on) **_Windows**_ 10+
jekyll  version 3.3,

```
D:\Jekyll>jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: D:/Jekyll/_config.yml
Configuration file: D:/Jekyll/_config.yml
            Source: D:/Jekyll
       Destination: D:/Jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.575 seconds.
                    --watch arg is unsupported on Windows.
                    If you are on Windows Bash, please see: https://github.com/Microsoft/BashOnWindows/issues/216
Configuration file: D:/Jekyll/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

default `Gemfile.lock` file user jekyll-watch 1.5,but jekyll-watch 1.5 listen (~> 3.0, < 3.1)

**Comment by crispgm** [comment]
Did you use `bundler`? `bundle exec jekyll serve`

**Comment by BladeCode** [comment]
use `bundle exec jekyll serve` command can Works, but it does not automatically monitor file changes

**Comment by ashmaroli** [comment]
Hi, this is a known issue and is under consideration.. this change was made for BASH on Windows that also got extended to the default cmd.exe and powershell.
If you're using BashOnWindows, then there's no fix yet. But if you're on cmd.exe, there's an unofficial hack:

### Temporary workaround `jekyll s` for `cmd.exe`
- install jekyll 3.2.1
- copy lib/jekyll/commands/build.rb from jekyll 3.2.1 and replace the same file in jekyll 3.3.0

**Comment by BladeCode** [comment]
thanks

**Comment by Daniel15** [comment]
Also note that you need to add this to your `Gemfile` to get watching working on Windows:

```
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
```

**Comment by ashmaroli** [comment]
Hello @Daniel15, can you tell me more about your system environment?
I'm using Windows 7, with Ruby 2.3.1 and **never** actually required to add that line to my Gemfile, while using Jekyll 3.2.1 in `cmd.exe` ..

**Comment by Daniel15** [comment]
Not 100% sure but I think it works fine without it, it just polls the filesystem. Installing the `wdm` Gem makes it more efficient since Windows will notify Jekyll that the files have changed. I just know that Jekyll kept telling me I should install `wdm` every time I ran it.

**Comment by ashmaroli** [comment]
yes, thats true.. I ignore it because `--watch` works without adding that, on my system..
I never asked to have it removed though, thinking perhaps some other windows setup might actually require it..

**Comment by maurocap** [comment]
I confirm Jekyll 3.3.0 cannot watch files on Windows 10.
I downgraded it to 3.2.1 and it worked again.

**Comment by ffes** [comment]
Same problem here, using Cygwin.

I always have used Cygwin and it has always worked as expected since I started using Jekyll in Feb-2015. I guess #5235 somehow broke this.

**Comment by envygeeks** [comment]
This is a known issue and it has an open pull request for 3.3.1

**Comment by ashmaroli** [comment]
@envygeeks can you add a green `has PR` label to this?
Would be useful for similar cases in future..

**Comment by pathawks** [comment]
Is there a better title for this issue?

**Comment by ashmaroli** [comment]
how about..? 
**`jekyll serve` autoregeneration broken with v3.3.0 on Windows**

**Comment by goyllo** [comment]
Part time solution.
1. gem install jekyll 3.2.1
2. gem uninstall jekyll

Now you will see option to which version you want to remove, select the 3.3 version. Now you have jekyll 3.2.1 version in your system, which does not give you that error.

Till then wait untill jekyll 3.3 or windows fixed that base error.

**Comment by ashmaroli** [comment]
## (Another) Temporary Fix
Since the workaround I mentioned [before](https://github.com/jekyll/jekyll/issues/5462#issuecomment-252237991) recieved a couple of :confused:, I'm posting another workaround, that doesnt require downloading/using an older version..

Update this [line](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/commands/build.rb#L74) in `build.rb` to say `unless...` instead of `if ...` :
```ruby
unless Utils::Platforms.windows?
```

**Comment by jaminscript** [comment]
@ashmaroli This didn't seem to have any effect for me. I made the change, restarted git bash but nothing different.

**Comment by ashmaroli** [comment]
@jaminscript Did you make the change in `~/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb`?
Can you give me some more info regarding your system? As to, what OS, Ruby version.. etc
or simply please paste the contents of your `Gemfile.lock` here..

**Comment by jaminscript** [comment]
@ashmaroli I deleted my old Gemfile.lock and ran `bundle exec jekyll serve` again, and this time it worked! The current Gemfile has 3.3.0 still set, so it seems your temporary fix worked after all.

**Comment by jrtibayan** [comment]
Replacing the build.rb of the jekyll 3.3.0 with the build.rb of jekyll 3.2.1 made auto regeneration work!
I uninstalled jekyll 3.2.1 after getting the file and it still works!
Does that mean I need to use command of jekyll 3.2.1? Like 'jekyll s'?
Thanks a lot.

**Comment by ashmaroli** [comment]
@jrtibayan, you needn't replace the entire `build.rb` just updating a line will do.. (see couple of comments above) 
`jekyll s` is a shorthand for `jekyll serve`.. both are the same and will remain so forever..

**Comment by jrtibayan** [comment]
Thanks @ashmaroli!
I replaced `if Utils::Platforms.windows?` with `unless Utils::Platforms.windows?`
Worked great! Thanks again

**Comment by mharrisondev** [comment]
Thank you @ashmaroli, worked a treat.

**Comment by ffes** [comment]
The issue Microsoft/BashOnWindows#216 that is mentioned in 17bd63fa195083992b4493ee521729e84373ad77 has been closed.
https://blogs.msdn.microsoft.com/commandline/2016/10/07/wsl-adds-inotify-filesystem-change-notification-support/

**Comment by envygeeks** [comment]
Thanks for the headsup @ffes, I'll update the pull.

**Comment by zachwarner** [comment]
I'm new to Jekyll so apologies if I'm missing something obvious here, but I'm still having trouble. I'm on Windows 10, testing in both Firefox and Chrome. I did a clean re-install of Ruby  Ruby 2.3.1p112 (x-64) and Jekyll 3.3.0, edited the `build.rb` file (switching "if" to "unless"), then ran

```
jekyll new myblog
cd myblog
bundle exec jekyll serve
```

I see auto-regeneration enabled, with a message `Please add the following to your Gemfile to avoid polling for changes`. Auto-regeneration doesn't work either before or after I add the relevant line,

```
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
```
to the Gemfile. 

Finally, one more weird behavior: if I ctrl-c to stop the server, I need to hit `y + ent` twice to terminate the job. Not sure what's up.

**Comment by AnilK2016** [comment]
Hi,

I am very new in Jekyll where I can find build.rb file in Windows 10.Plz give its path and I didn't find path lib/jekyll/commands/build.rb i am using jekyll version 3.3.0

**Comment by ashmaroli** [comment]
@AnilK2016, it will be in your `gems` folder. First get the url to the Jekyll installation:
```
bundle show jekyll
```
Then search for `lib/jekyll/commands/build.rb` at that location.

**Comment by AnilK2016** [comment]
I find the file thanks you somuch for the quick replay:::

**Comment by pizzapgh** [comment]
How do I find the build.rb file?
