### ISSUE TITLE
Pull page title from first H1 or H2 in page

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#5476]
If a page does not have a YAML-front-matter-specified title, we should see if the first line of the markdown file contains a H1 or H2, remove that from the page content, and use that as the page title (via `page.title`).

The reasoning being, that for simple pages with no need for additional YAML front matter (and for those just learning Markdown, it's more intuitive to author the document entirely in Markdown, then in a mix of Markdown and Jekyll-specific markup (YAML front matter with a title key).

Also to note, the advantage here is that the title would be both machine and (more) human readable (e.g., when rendered on GitHub.com's file viewer), or when used to iterate through `site.pages`.

Two bits of context:
1. This may be a breaking change, and thus may need to be opt-in, for sites that expect the page title to be hard-coded into the document itself, and not exposed by the theme.
2. Documents get `page.title` set from the filename, but Pages as their own object, do not.

**Comment by zdroid** [comment]
I support the idea. It'd be nice to see a theoretical example from you, just to make the idea completely clear.

**Comment by benbalter** [comment]
```markdown
# Foo

This is a page
```

Would be functionally equivalent to

```markdown
---
title: Foo
---

This is a page
```

**Comment by zdroid** [comment]
If the proposed change is only for MD files that are missing YAML front-matter, I support it.

**Comment by caspervonb** [comment]
:+1+ for this, as this has some nice side effects, like a README can be rendered as-is. Currently having to do a CI deploy hook on master, which copies source "README" into page "README" but prepends YAML frontmatter.

**Comment by benbalter** [comment]
Thinking this may make more sense as a tiny plugin, where it can be opt in.

**Comment by benbalter** [comment]
> Thinking this may make more sense as a tiny plugin, where it can be opt in.

Created https://github.com/benbalter/jekyll-title-from-headings

**Comment by domoritz** [comment]
How can I override the page title to be not set and still use an h1 on my page?

**Comment by cfree3** [comment]
@domoritz I think you can just say `null`:

~~~
---
title: null
---
~~~
