### ISSUE TITLE
site.url not working after upgrade to 3.3

### ISSUE THREAD

**Issue by goyllo** [jekyll/jekyll#5482]
`{{site.url}}` return my localhost address instead of my domain name everywhere (xml sitemap, canonical link, feed url, etc.) that I have provided in my config file.

Actually the problem is only with `url` name, because I have also set my image path name in config file, and it works fine with `{{site.imagepath}}`

Also `{{site.url}}` works fine when I install jekyll 3.2.1

**Comment by DirtyF** [comment]
@goyllo If you're in development environment, it's the intended behavior in Jekyll 3.3 (see: http://jekyllrb.com/news/#siteurl-is-set-by-the-development-server)

If you want to test the production environment run `JEKYLL_ENV=production bundle exec jekyll serve`

**Comment by shemayas** [comment]
This is just great, I spent hours on tring to understand why my url dosn't change ):

Is there a permenent way to use the old method of the url?

By the way- a big thank you, I love Jekyll :)

**Comment by DirtyF** [comment]
> Is there a permenent way to use the production state of the url?

@shemayas you can run `JEKYLL_ENV=production bundle exec jekyll serve`everytome you want to run in production mode

**Comment by shemayas** [comment]
Hi @DirtyF ,
I meant somthing more like `export JEKYLL_ENV=production` and then I don't need to specify anymore that variable.
