### ISSUE TITLE
The docs should demonstrate how to update your version of Jekyll

### ISSUE THREAD

**Issue by cfjedimaster** [jekyll/jekyll#5484]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [X ] This is a feature request.

The docs for installing Jekyll should contain information on how a user can check their current version, what the most current version is, and how they can update it. For folks who don't know Gem (like me), I had to hunt around a bit to figure it out. While you aren't documenting Gem, I do think a quick note would be helpful.

**Comment by DirtyF** [comment]
@cfjedimaster Good point, I guess we assume people know about `bundle update` or `gem update jekyll`.

Would something like [this section on GitHub Pages](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#keeping-your-site-up-to-date-with-the-github-pages-gem) be sufficient?

**Comment by zdroid** [comment]
@DirtyF Something similar to the section you've linked is perfect for the purpose. :+1:

**Comment by cfjedimaster** [comment]
IMO, no, because it references GitHub pages. If I'm trying to find out how to update Jekyll, I'd stop reading when I see that header. I know it sounds petty, but I can see a lot of readers doing that. If you mean just copying the text at #2, then sure, but obviously it has to use jekyll, not github-pages.

**Comment by zdroid** [comment]
@cfjedimaster He doesn't mean copying the whole `github-pages` section. He wants us to write something similar to that.

**Comment by cfjedimaster** [comment]
Fair enough - it would definitely help.

**Comment by kingscott** [comment]
Hey! Came across this and thought maybe I could help. Is someone already active on this?

**Comment by parkr** [comment]
@kingscott You can look through the PR's, but no I don't think anyone is working on this! Have at it!

**Comment by kingscott** [comment]
Cool, I'll try to have something up tonight!

**Comment by kingscott** [comment]
I have something up at https://github.com/jekyll/jekyll/pull/5497. Let me know!

**Comment by kingscott** [comment]
We can close this one I believe - @pathawks?

**Comment by cfjedimaster** [comment]
lgtm
