### ISSUE TITLE
site.config['url'] should be respected regardless of environment

### ISSUE THREAD

**Issue by miklb** [jekyll/jekyll#5488]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

I am using a [plugin](https://github.com/aarongustafson/jekyll-webmention_io) that stores all links in a post in a .cache file under `source`, the url of the post containing them for further processing. Specifically, the plugin uses `site.config['url']` & the permalink. In 3.3, this breaks, writing `http://localhost:4000` instead of the value in config.

## The Output I Wanted
Respect the value of the config file.

**Comment by Crunch09** [comment]
Hi, have you tried to set your `JEKYLL_ENV` to a different value?

**Comment by miklb** [comment]
`bundle exec jekyll serve JEKYLL_ENV=production` dd not work. My point is, there should be a way to read the value of explicitly set value in config regardless of the environment.

**Comment by miklb** [comment]
To be clear, I never had any issue serving my site locally with that value set prior to 3.3 release.

**Comment by pathawks** [comment]
`JEKYLL_ENV=production bundle exec jekyll serve`

Can you explain your issue a bit more? I'm not sure I understand.

**Comment by miklb** [comment]
My issue is that I don't understand why you can't read the explicitly set value of config and it not be hijacked, regardless of environment. While never had a problem with `site.url` being set to my domain in my config and serving locally, I *sorta* understand the change. But I don't understand why there isn't a way to get the raw value. Hijacking user set config values seems like a very slippery slope and I would love to see the discussion on the decision to do so.

**Comment by Crunch09** [comment]
You are still able to set a local url via the `host` and `port` options (and if you want `ssl` stuff). As described [here](https://jekyllrb.com/docs/configuration/#serve-command-options) those values are for *local* server hostname and *local* server port.
A config like this:

```
host: jekyll.local
port: 4444
url: https://example.com
```
Would give you `http://jekyll.local:4444` in your `development` environment and `https://example.com` in any other environment for `site.url`.

**Comment by miklb** [comment]
So to be clear, serving locally, the only way to read the `url` config setting is to set a `JEKYLL_ENV` to something other than `development`? I personally find that a horrible solution.

**Comment by pathawks** [comment]
Ok, I was more trying to understand your workflow to see if there were a better way to go about things.

I guess the bottom line is that Jekyll is working as intended, and this is not a bug.

**Comment by suprafly** [comment]
I agree with @miklb - this is really unintuitive. I spent a good deal of time debugging this behaviour as well. I would expect the variable to return the data that is contained there, not to coerce it into something that it believes is more accurate.

**Comment by DirtyF** [comment]
Jekyll lives by the 80% rule, default behavior is documented here:
https://jekyllrb.com/docs/usage/#override-default-development-settings
