### ISSUE TITLE
Post not shown if title contains : (colon)

### ISSUE THREAD

**Issue by Heliosmaster** [jekyll/jekyll#549]
in the YAML front matter, if I have

`title: "Post title : Part 1"`

the post is not shown by Jekyll.

**Comment by gideonite** [comment]
I'm using jekyll 2.5.3 and I'm still getting an unhelpful error:
```
Error reading file /home/gideon/Dropbox/the-aperiodic-crystal/_posts/2012-11-15-init-the-aperiodic-crystal.md: (<unknown>): mapping values are not allowed in this context at line 3 column 12 
```

**Comment by parkr** [comment]
@gideonite We asked about this here, check it out: https://github.com/dtao/safe_yaml/issues/54

**Comment by CaioProiete** [comment]
Also using jekyll 2.5.3 and the workaround I prefer, is to use the "non-specifig tag" YAML syntax.
```
---
title: ! 'Attention: This post title has "colon" & stuff'
date: 2015-05-24 11:12:13
---
```

This allows me to use colon, double quotes, and pretty much any special char.

**Comment by fernandomantoan** [comment]
The syntax suggested by @caioproiete works for me.

**Comment by akhyarrh** [comment]
I use `'Title: subtitle'` and `"Title: subtitle"` everything work fine

**Comment by pathawks** [comment]
This issue is more than three years old; I would hope everything works fine.

**Comment by gurghet** [comment]
Quotes worked
