### ISSUE TITLE
Jekyll is exporting site.url as http://localhost:4000

### ISSUE THREAD

**Issue by jp26jp** [jekyll/jekyll#5490]
- I believe this to be a bug, not a question about using Jekyll.
- I am on (or have tested on) ***macOS*** 10+
- Running V3.3.0

---

[This might be a similar issue as this one](https://github.com/jekyll/jekyll/issues/5488) but jekyll started exporting my `site.url` as http://localhost:4000. I'm happy to send my files if necessary.

**Comment by Crunch09** [comment]
Yes,
in 3.3 your [site.url](https://jekyllrb.com/news/#siteurl-is-set-by-the-development-server) is determined by various options if you are in the `development` env.
