### ISSUE TITLE
Add Liquid whitespace controll

### ISSUE THREAD

**Issue by ChristianMayer** [jekyll/jekyll#5523]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Using the example
```
{%- assign username = "John G. Chalmers-Smith" -%}
{%- if username and username.size > 10 -%}
  Wow, {{ username }}, you have a long name!
{%- else -%}
  Hello there!
{%- endif -%}
```
from http://shopify.github.io/liquid/basics/whitespace/ I get the error message
```
Error: Liquid syntax error (line 82): Tag '{%- assign username = "John G. Chalmers-Smith" -%}' was not properly terminated with regexp: /\%\}/
```

## The Output I Wanted

```
Wow, John G. Chalmers-Smith, you have a long name!
```

@jekyll/build

**Comment by pathawks** [comment]
This is a feature of Liquid 4.
Jekyll is currently using Liquid 3.

Liquid 4 is coming:+1:
