### ISSUE TITLE
jekyll 3.3.0 error

### ISSUE THREAD

**Issue by adesign412** [jekyll/jekyll#5525]
hello jekyll team

i am running  10.11.4  osx el caption im trying install  jekyll on to my computer but  i am getting  this  error when i type jekyll serve

configuration file: none
Configuration file: none
            Source: /Users/andywoo
       Destination: /Users/andywoo/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.3.0 | Error:  Operation not supported on socket - /Users/andywoo/Library/Application Support/Google/Chrome/App Shim Socket

 please help 

thanks andy

- [ x] I believe this to be a bug, not a question about using Jekyll.
- [ x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ x] I was trying to build.
- [ ] It was another bug.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by ashmaroli** [comment]
dont simply run `jekyll serve` right away.
First install a new jekyll project:
```
jekyll new my_blog
```
then move into that directory: 
```
cd my_blog
```
then run the *jekyll serve* command:
```
</Users/andywoo/my_blog>: bundle exec jekyll serve
```

**Comment by parkr** [comment]
> jekyll 3.3.0 | Error:  Operation not supported on socket - /Users/andywoo/Library/Application Support/Google/Chrome/App Shim Socket

@adesign412 Sounds like you have a custom plugin that is trying to launch chrome. What plugins are you using?

**Comment by adesign412** [comment]
hello all,
i am really new to frontend web development i am really haveing a really hard time  installing jekyll in to my osx
![screen shot 2016-11-03 at 9 55 31 pm](https://cloud.githubusercontent.com/assets/6730670/19995003/8a291aa6-a210-11e6-9444-b65983d32fc2.png)

**Comment by adesign412** [comment]
if anyone has the answer please let me know

thank you

**Comment by parkr** [comment]
Try running `gen install bundler` and trying again :smile:

**Comment by ashmaroli** [comment]
@parkr, what do you say to having Bundler added as a dependency in the gemspec? Bundler would then automatically install with Jekyll, no?

**Comment by DirtyF** [comment]
@adesign412 so with `bundler` installed, you should be fine. In doubt please refer to official documentation on http://jekyllrb.com/docs/, if you have further question on Jekyll's, ask on our forum https://talk.jekyllrb.com.
