### ISSUE TITLE
bug in `plugins_path` with trailing `/` on windows

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5527]
There exists a bug in how Jekyll handles array of plugins if a new jekyll site on **Windows** is configured to use a **non-default path** to `/plugins`

## To reproduce this bug:
- simply run the test-file `test/test_site.rb` on a Windows machine.

You'll get:  `["<Drive-letter:>/tmp/plugins"]`
Instead of:  `["<abs_path_to_local_Jekyll_Repo>/tmp/plugins"]`

## Workaround:
Change https://github.com/jekyll/jekyll/blob/master/test/test_site.rb#L16 by deleting the trailing `/` of the string; and then run the test again.

You'll get: `["<abs_path_to_local_jekyll_repo>/tmp/plugins"]` as expected, even though, the test fails.

--
/cc @jekyll/windows 
/cc @jekyll/ecosystem

**Comment by pathawks** [comment]
This is a Windows issue. Doesn't have anything to do with @jekyll/ecosystem :beers:

**Comment by ashmaroli** [comment]
can you confirm it works as expected, on a Unixoid?

**Comment by envygeeks** [comment]
What is Unixoid?

**Comment by ashmaroli** [comment]
> What is Unixoid?

Pardon me, I was referring to unix-like systems like Linux, macOS..

**Comment by parkr** [comment]
> You'll get: ["<Drive-letter:>/tmp/plugins"]
> Instead of: ["<abs_path_to_local_Jekyll_Repo>/tmp/plugins"]

This is actually a bug in the test suite, not a bug in the code. It needs to do a `Dir.chdir(ENV["HOME"])` before this test. We intentionally `File.expand_path` relative to the CWD instead of the site source. I tried to make it relative to the local jekyll site and I got tons of angry issues about it around Jekyll 1.0 or 2.0.

**Comment by ashmaroli** [comment]
> This is actually a bug in the test suite, not a bug in the code.
@parkr actually, there is a bug in the code (for Windows). ["/tmp/plugins"] may be same when the path contains a trailing slash or not, but on Windows, it gives:
`["C:/tmp/plugins"]` for `"/tmp/plugins"` and
`["<CWD>/tmp/plugins"]` for `"tmp/plugins"`

**Comment by parkr** [comment]
Oh, that sounds like a Ruby issue.

**Comment by parkr** [comment]
If you add `plugins_dir: /tmp/plugins` it should show `<CURRENT_DRIVE>:/tmp/plugins`.

**Comment by ashmaroli** [comment]
The associated PR is being refactored to simply sub the first `/` and proceed as usual..

**Comment by ashmaroli** [comment]
> If you add plugins_dir: /tmp/plugins it should show <CURRENT_DRIVE>:/tmp/plugins

in that case, the PR will have to be modified to `ensure` a trailing slash if not present..
because `plugins_dir => "tmp/plugins"` gives `["C:/../jekyll/tmp/plugins"]` :tired_face:

**Comment by ashmaroli** [comment]
@parkr, one final clarification:
is the following intended?

### on Windows
current directory = **C:/Sites**
set `plugins_dir => ["/apps/plugins", "apps/plugins"]`
```
site.plugins => ["C:/apps/plugins", "C:/Sites/apps/plugins"]
```
### on Linux
current directory = **/home/Sites/**
set `plugins_dir => ["/apps/plugins", "apps/plugins"]`
```
site.plugins => ["/apps/plugins", "/home/Sites/apps/plugins"]
```

**Comment by parkr** [comment]
@ashmaroli That looks right to me!

**Comment by pathawks** [comment]
@ashmaroli I don't use Jekyll on Windows; I don't know. Sorry.

**Comment by ashmaroli** [comment]
> That looks right to me!

@parkr So, there is no bug, like you were sayin, all this while.. :laughing: 

> I don't use Jekyll on Windows; I don't know. Sorry.

@pathawks, I pinged you to verify that array on Linux/macOS.. Doesnt matter, Parker is fine with the way it is currently.. Thanks anyways.
