### ISSUE TITLE
404 on http://jekyllrb.com/docs/maintaining/

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#5531]
Links on the http://jekyllrb.com/docs/maintaining/ page return 404 errors because of the trailing slash.

- http://jekyllrb.com/docs/maintaining/affinity-team-captain/ -> 404
- http://jekyllrb.com/docs/maintaining/affinity-team-captain -> 200

**Comment by ashmaroli** [comment]
@DirtyF , this issue still seems to persist.. pls investigate.

**Comment by ashmaroli** [comment]
could #5535 be the reason, why the changes from merging #5532 not take effect automatically?

**Comment by DirtyF** [comment]
@ashmaroli I don't think so because locally htmlproofer does return errors too. It may be related  to https://github.com/jekyll/jekyll/commit/1669f944d16e71350a1c162f725689849cf7e399

**Comment by ashmaroli** [comment]
the site builds and serves fine, locally, though.., with the pages in question here at status 200.

**Comment by parkr** [comment]
The problem was that we were using a tag that wasn't supported. We added it to GitHub Pages. 😄
