### ISSUE TITLE
don't have bundler

### ISSUE THREAD

**Issue by wdssmq** [jekyll/jekyll#5534]
Dependency Error: Yikes! It looks like you don't have bundler or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- bundler' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!

**Comment by ashmaroli** [comment]
install bundler then..
```
gem install bundler
```

**Comment by pathawks** [comment]
This is not a bug with Jekyll.

If you need help getting started, you can find answers to many questions at https://help.jekyllrb.com

**Comment by ashmaroli** [comment]
@pathawks do you think we should add bundler as a dependency in the gemspec to have it installed automatically with jekyll?

**Comment by ashmaroli** [comment]
> If you need help getting started, you can find answers to many questions at https://help.jekyllrb.com

This link is down. try https://talk.jekyllrb.com/ instead
