### ISSUE TITLE
Get rid of docs/freenode.txt and docs/latest_version.txt

### ISSUE THREAD

**Issue by zdroid** [jekyll/jekyll#5539]
Currently, there are two files that make me wonder why they're in `docs/` directory — `freenode.txt` and `latest_version.txt`. They're one-liners. What is their purpose?

I guess it'd be better to have them in `_config.yml` if they're used for anything site-related.

**Comment by ashmaroli** [comment]
they're auto-generated when the site is built..

**Comment by zdroid** [comment]
@ashmaroli Okay. Still, why are they built at first? I mean, you can put that information in other files.

**Comment by ashmaroli** [comment]
correction `freenode.txt` is not auto-generated. But yes, `latest_version.txt` is..
and I dont know their relevance.

**Comment by DirtyF** [comment]
@zdroid `latest_version.txt` is meant to give an easy access to external programs to jekyll's latest version. See https://github.com/jekyll/jekyll/pull/2740

**Comment by zdroid** [comment]
@DirtyF Was there any significiant usage of that so far? Also, what's the use of `freenode.txt`?

**Comment by jaybe-jekyll** [comment]
Hi. Freenode.txt  was employed a long time ago for the purposes of verification. I do not believe that file continues to be necessary. I would be fine with removing it. @parker cc:

**Comment by parkr** [comment]
@jaybe-jekyll Does Freenode continuously validate the way, say, Keybase.io does? If we remove this validation file, will they revoke the verification? That's a common thing to do so just want to make sure I ask that before removing this.

I'd like to leave `docs/latest_version.txt`. I'm all about not breaking websites so if anyone's relying on it, then I'd rather leave it. 😄

**Comment by jaybe-jekyll** [comment]
@parkr I have met with our Freenode partners and confirmed the freenode.txt file is no longer needed and no longer serves in a useful capacity, so it may be removed. Hooray for cleanliness and tidiness!

+1 re: leaving latest_version.txt. I personally have been known to pull that `curl` from command history! Thanks!
