### ISSUE TITLE
/docs/github-pages/ still talks about `master` vs `gh-pages` as the only way

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#5543]
We should elaborate now that GitHub supports customizable sources of:

- `gh-pages`
- `master`
- `master` branch, `docs/` subfolder

http://jekyllrb.com/docs/github-pages/

**Comment by DirtyF** [comment]
As GitHub Pages has a [detailed documentation on the matter](https://help.github.com/articles/user-organization-and-project-pages/) is it OK if we just point to the official doc?

**Comment by parkr** [comment]
@DirtyF Absolutely!
