### ISSUE TITLE
Problems with ‘bundle exec jekyll serve’

### ISSUE THREAD

**Issue by ahmetcadirci25** [jekyll/jekyll#5547]
`Could not find gem 'jekyll (= 3.3.0) x86-mingw32' in any of the gem sources listed in your Gemfile or available on this machine.

Run `bundle install` to install missing gems.`

![ekran alintisi](https://cloud.githubusercontent.com/assets/9280397/20005544/a22055b2-a29b-11e6-863f-f8f8ad336d4f.PNG)

**Comment by pathawks** [comment]
So run `bundle install` or `bundle update`
