### ISSUE TITLE
Can not load images resource.

### ISSUE THREAD

**Issue by tingxins** [jekyll/jekyll#5548]
I find that i can't load th url of an image. 2016 is a subdirectory of images. but it just can not load sucessed.

`![timer leaks unresolved img](/assets/images/2016/timer-leaks-unresolved.png)`

Just load a placeholder image. 

https://github.com/tingxins/tingxins.github.io

**Comment by ashmaroli** [comment]
your `assets/images/2016/` directory doesn't have a resource named `timer-leaks-unresolved.png`

**Comment by tingxins** [comment]
@ashmaroli But actually, in assets/images/2016 directory did have resource image that named timer-leaks-unresolved.png. And weirdly, in assets/images directory it can load resource images. But in 2016 sub directory it can not load.

**Comment by ashmaroli** [comment]
try again.. FYI, `date-formate-patterns.png` in the same directory is being *loaded* correctly..

**Comment by tingxins** [comment]
@ashmaroli uh....no no no, actually all resources in assets/images/2016 directory can not load. Not exactly timer-leaks-unresolved.png

**Comment by ashmaroli** [comment]
[..I retracted my previous comment..]

**Comment by ashmaroli** [comment]
@tingxins, I cloned your blog on my Windows system and it seems the image files in `assets/images/2016` are not proper. (I cant open them locally. But it looks fine here on GH)
Pls verify by cloning to a different directory on your system.

Build and serve locally first. If all is fine, its not a Jekyll issue or pages-gem issue.
and then try re-uploading the images..

If its an issue with Jekyll, or pages-gem, the images in `_site/assets/images/2016` will be non-existent or improper too..

**Comment by ashmaroli** [comment]
another difference I noticed is that the images in your assets/images/2016 are **`Stored with Git LFS`** Try  the regular way instead..

**Comment by tingxins** [comment]
@ashmaroli yeah,i try it and indeed. it's works. because of the git lfs. thanks

**Comment by pathawks** [comment]
This sounds like a real issue, but it sounds like it has more to do with GitHub Pages than with Jekyll. You should probably either contact GitHub support directly, or open a pages-gem issue.
