### ISSUE TITLE
Unable to escape something that looks like Liquid inside a code block

### ISSUE THREAD

**Issue by mstanleyjones** [jekyll/jekyll#5549]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by pathawks** [comment]
Use the `{% raw %}` tag to have Liquid ignore the body of code blocks.

**Comment by mstanleyjones** [comment]
Sorry, I meant to come back and add more to the bug (I hit enter before filling it out, it was an accident), but I think I can blame AngularJS and not Liquid. I did know about the `{% raw %}` trick, and we are doing that. Sorry for the trouble.

**Comment by pathawks** [comment]
Hope you get everything sorted. If you figure out a solution, it’d be nice if you could post it here for future reference:+1:
