### ISSUE TITLE
`--watch` doesn't work on Cygwin

### ISSUE THREAD

**Issue by egor-tensin** [jekyll/jekyll#5550]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`

I upgraded `github-pages` from version 93 to 104 (i.e., from Jekyll 3.2.1 to Jekyll 3.3.0), and `--watch`ing for file changes suddenly stopped working on Windows + Cygwin.

I created a repository to reproduce this issue at https://github.com/egor-tensin/jekyll-cygwin-issue.

The output of `jekyll serve --watch --force_polling --verbose` on Jekyll 3.2.1:

      Logging at level: debug
    Configuration file: /cygdrive/d/workspace/personal/jekyll-cygwin-issue/_config.yml
             Requiring: kramdown
                Source: /cygdrive/d/workspace/personal/jekyll-cygwin-issue
           Destination: /cygdrive/d/workspace/personal/jekyll-cygwin-issue/_site
     Incremental build: disabled. Enable with --incremental
          Generating...
           EntryFilter: excluded /Gemfile
           EntryFilter: excluded /Gemfile.lock
                        done in 0.054 seconds.
             Requiring: jekyll-watch
               Watcher: Ignoring (?-mix:_config\.yml)
               Watcher: Ignoring (?-mix:_site)
               Watcher: Ignoring (?-mix:Gemfile)
               Watcher: Ignoring (?-mix:Gemfile\.lock)
     Auto-regeneration: enabled for '/cygdrive/d/workspace/personal/jekyll-cygwin-issue'
      Logging at level: debug
    Configuration file: /cygdrive/d/workspace/personal/jekyll-cygwin-issue/_config.yml
    [2016-11-05 15:56:58] INFO  WEBrick 1.3.1
    [2016-11-05 15:56:58] INFO  ruby 2.2.5 (2016-04-26) [x86_64-cygwin]
    [2016-11-05 15:56:58] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
    [2016-11-05 15:56:58] DEBUG unmount .
    [2016-11-05 15:56:58] DEBUG Jekyll::Commands::Serve::Servlet is mounted on .
        Server address: http://127.0.0.1:4000/
    [2016-11-05 15:56:58] INFO  WEBrick::HTTPServer#start: pid=3352 port=4000
      Server running... press ctrl-c to stop.

The output for the same command on Jekyll 3.3.0:

      Logging at level: debug
    Configuration file: /cygdrive/d/workspace/personal/jekyll-cygwin-issue/_config.yml
      Logging at level: debug
      Logging at level: debug
    Configuration file: /cygdrive/d/workspace/personal/jekyll-cygwin-issue/_config.yml
             Requiring: kramdown
                Source: /cygdrive/d/workspace/personal/jekyll-cygwin-issue
           Destination: /cygdrive/d/workspace/personal/jekyll-cygwin-issue/_site
     Incremental build: disabled. Enable with --incremental
          Generating...
           EntryFilter: excluded /Gemfile
           EntryFilter: excluded /Gemfile.lock
                        done in 0.039 seconds.
                        --watch arg is unsupported on Windows.
                        If you are on Windows Bash, please see: https://github.com/Microsoft/BashOnWindows/issues/216
      Logging at level: debug
    Configuration file: /cygdrive/d/workspace/personal/jekyll-cygwin-issue/_config.yml
    [2016-11-05 16:03:49] INFO  WEBrick 1.3.1
    [2016-11-05 16:03:49] INFO  ruby 2.2.5 (2016-04-26) [x86_64-cygwin]
    [2016-11-05 16:03:49] DEBUG WEBrick::HTTPServlet::FileHandler is mounted on /.
    [2016-11-05 16:03:49] DEBUG unmount .
    [2016-11-05 16:03:49] DEBUG Jekyll::Commands::Serve::Servlet is mounted on .
        Server address: http://127.0.0.1:4000/
    [2016-11-05 16:03:49] INFO  WEBrick::HTTPServer#start: pid=6584 port=4000
      Server running... press ctrl-c to stop.

*BTW, isn't this suspicious that the `Configuration file:` line appears 3 times on Jekyll 3.3.0?*

**Comment by ashmaroli** [comment]
@egor-tensin, Thank you, but the issues you've highlighted here are known and are consideration for the next release.
Tune into the following issue tickets (and subscribe to the referenced PRs within them):
 - disabled watch : #5462 
 - multiple configuration msgs: #5467

**Comment by egor-tensin** [comment]
@ashmaroli Oh, right. Thank you for pointing that out. I'm closing this issue, now, will be happy to add any labels (like "duplicate" or anything else) if someone says so.
