### ISSUE TITLE
Why `codehilite` class instead of Rouge-compatible `highlight`?

### ISSUE THREAD

**Issue by corysimmons** [jekyll/jekyll#5551]
https://github.com/jneen/rouge/issues/343#issuecomment-258562115

**Comment by pathawks** [comment]
We do [use `highlight`](https://github.com/jekyll/jekyll/blob/v3.3.0/lib/jekyll/tags/highlight.rb#L130)

**Comment by corysimmons** [comment]
Hmm... Not sure where codehilite was coming from then...
