### ISSUE TITLE
Jekyll 3.3.0, option --watch does not work for the Windows platform

### ISSUE THREAD

**Issue by jueadams** [jekyll/jekyll#5553]
Hi there,
this is a continueance of issue #5370. 

I ran into the same issue after updating Jekyll from version 3.2.1 to 3.3.0 - the **watcher** does not work anymore, 

I did a diff on ~lib/jekyll/commands/build.rb for 3.2.1 and 3.3.0 version and found an additional if statement  **if Utils::Platforms.windows** that **skips** the initialization for **"jekyll-watch** for the Windows platform.

This is not correct as **jekyll-watch** (using version 1.5.0) **works perfectly on Windows**. I changed the code back to version 2.3.1 (no if) to initialize the watcher back again. No wonder, it works as it worked for version 2.3.1.

Please re-check the code of **build.rb** for Jekyll **version 3.3.0** to make the init for the watcher working again. From my practical experience (I'm not a Ruby programmer) there is **no issue** for **jekyll-watch**  on Windows; therefor no need to **exclude** jekyll-watch for the Windows platform.

Thanks a lot,
Juergen Adams

**Comment by DirtyF** [comment]
@jueadams Could you provide more details on your environment?

/cc @jekyll/core jekyll/windows

**Comment by ashmaroli** [comment]
@jueadams, this is a known issue and will be patched with the next next release. Please check and subscribe to the following PR:
  - #5464 : **Only shutdown watch in Bash On Windows.**

**Comment by pathawks** [comment]
Thanks @ashmaroli :+1:

**Comment by jueadams** [comment]
Hi there,

thanks a lot for picking up the ticket that fast. Whatever that known issue is, it is connected to a non-standard shell for Windows - if **Bash On Windows** means the Linux|Unix port of  the bash shell for Windows.  The way this bug is workaround make Jekyll's incremental mode stop working for the whole platform. I can't see no reason why.

I'm working on a template system for Jekyll, Version 2.6.1 of Jekyll is unusable because (of the bug) that the assets folder is not managed correctly. No assets, no web. 

Anyway, the template  functionality is really great and will improve a lot in terms of using Jekyll as a central driver engine to generate modern, featured static Web sites. 

Bugs are part of the real world. To release a template manager that can't handle assets for a web correctly a different story; or making a platform stop working for an important functionality that is not needed that way.

Afain thanks a lot for your exellent work on Jekyll 3, but think about your release testing and planning.

Best regards,
Jueen Adams

**Comment by pathawks** [comment]
@jueadams The more Windows users we have on our team, the better Jekyll can be for everybody. I would encourage you to join our Windows team so that you may weigh in when situations like this arise in the future :+1:
https://teams.jekyllrb.com/
