### ISSUE TITLE
Missing collation with sort

### ISSUE THREAD

**Issue by hydrargyrum** [jekyll/jekyll#5554]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

- [x] It was another bug.

## My Reproduction Steps

```
{% assign x = "a/é/z" | split :"/" | sort %}
{% for i in x %}
{{i}}
{% endfor %}
```

I get

"a z é"

## The Output I Wanted

"a é z"

**Comment by Crunch09** [comment]
Hi @hydrargyrum ,

the sort-filter is defined in liquid as a [standard filter](https://github.com/Shopify/liquid/blob/b146b49f465419b94c5b778e3e82fc7d1e8832be/lib/liquid/standardfilters.rb#L121), so you'd have to open an issue with them. My guess would be that the current behaviour is intended though:

<img width="171" alt="screen shot 2016-12-04 at 21 47 03" src="https://cloud.githubusercontent.com/assets/570608/20869076/3ece083c-ba6b-11e6-8fe4-ce3b1c24c970.png">

**Comment by pathawks** [comment]
Closing because, as @Crunch09 pointed out, this is a Liquid issue rather than a Jekyll issue.
When you open an issue with Liquid, please do provide a link to that issue 👍
