### ISSUE TITLE
Upgrade to Rouge 2.0

### ISSUE THREAD

**Issue by jneen** [jekyll/jekyll#5556]
Hi! I'm the maintainer of the Rouge syntax highlighter. We released 2.0 back in June, and have added a lot of new languages and bugfixes since then. I'd invite you, when you get a chance, to upgrade.

The only breaking API change is the HTML formatter - instead of taking tons of options and wrapping the output in various divs and other tags, it simply outputs the raw spans and lets you put it in whatever context fits. This means no more `.gsub(/<pre.*?>/)` or the like. We still support the old API through `Rouge::Formatters::HTMLLegacy` if you absolutely need, but I've found it's usually much easier to add HTML context after the fact.

I'm happy to field any questions or work out any bugs/weirdnesses that come up. We've been using 2.0 over at GitLab since June, so I'm confident in its stability.

Thanks!
--Jeanine

**Comment by crispgm** [comment]
#5230

**Comment by Crunch09** [comment]
Hi Jeanine,

as you can see in the linked PR we already started on it but i wasn't sure which Formatter we should choose in regards to still being backwards compatible. 
Maybe we should check the `Rogue` version, use `Rogue::Formatters::HTML` for `2.x` and leave `1.7` untouched?

**Comment by johndmulhausen** [comment]
Just chiming in to +1 this request by the awesome @jneen. :) You can watch us figuring out that lexers we need (Dockerfile) weren't in the currently-supported Rouge gem that Jekyll uses, in this PR: https://github.com/docker/docker.github.io/pull/1021

**Comment by mstanleyjones** [comment]
Is there any update on this?

**Comment by mkobit** [comment]
Looking through related issues, it looks like this is slated for `3.6.0`?

**Comment by DirtyF** [comment]
@mstanleyjones @mkobit Support for Rouge 2 has been shipped last month in [Jekyll 3.6.0.pre.beta1](https://github.com/jekyll/jekyll/releases/tag/v3.6.0.pre.beta1)

You can help us test this version before we release 3.6.0 by updgrading:

```
gem install jekyll --pre
```

or specify this version in your Gemfile

```
gem "jekyll", "3.6.0.pre.beta1"
```

**Comment by johndmulhausen** [comment]
Hooray!!

**Comment by DirtyF** [comment]
@johndmulhausen Rouge 3.0 is on his way #6381 😄
