### ISSUE TITLE
Can't get jekyll to work on ubuntu 15

### ISSUE THREAD

**Issue by gilbertmpanga12** [jekyll/jekyll#5568]
Hello I tried installing jekyll, i put even the gem bundler and suprisingly i get this error.
Dependency Error: Yikes! It looks like you don't have bundler or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- bundler' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.3.0 | Error:  bundler...
what should i do?

**Comment by DirtyF** [comment]
Hi @gilbertmpanga12, sorry you run into trouble with bundler install, this repo is for Jekyll bugs only, but you should be able to find some help on our forum on https://talk.jekyllrb.com 🆘
