### ISSUE TITLE
[Docs] Link to updated Jekyll guide for Windows

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#5578]
In order to help Windows users install Jekyll 3 properly
Given I'm on http://jekyllrb.com/docs/windows/
Then I am invited to refer to https://labs.sverrirs.com/jekyll/

I am no Windows user but we see a lot of issues related to Windows here, I was wondering if this updated guide could help Jekyll 3 users.

/cc @jekyll/windows

**Comment by parkr** [comment]
Wasn't this suggested recently? I feel like we saw this come through recently.

**Comment by DirtyF** [comment]
Duplicates #5475

**Comment by parkr** [comment]
We could replace it though!

**Comment by DirtyF** [comment]
@parkr I'm not sure to understand, the link is in the page. We can make it more obvious by renaming the link to something like "a complete step-by-step guide to install Jekyll 3 on Windows" if that's what you are suggesting.

**Comment by parkr** [comment]
@DirtyF Sorry, I wasn't clear. We could remove the old installation guide as Jekyll 2 is no longer supported.

**Comment by DirtyF** [comment]
@parkr of course, PR coming.
