### ISSUE TITLE
Windows Incompatible character encodings: Windows-1252 and UTF-8, even though all files are UTF-8 (No BOM)

### ISSUE THREAD

**Issue by enzanki-ars** [jekyll/jekyll#5584]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***Windows*** 10+ (Windows issue only)

---

- [x] I was trying to build.

## My Reproduction Steps

For the respository schpaper/schpaper.github.io, the build fails on Windows due to incompatable encodings.  I have run many commands, including dos2unix and iconv to convert all files to utf-8.  I have also tried running the build (Using `bundle exec jekyll build`) in Git Bash and CMD, with CMD using 'chcp 65001`, and the build still fails due to the following error:

```
bundle exec jekyll build
Configuration file: D:/shafe/Documents/Dev/schpaper.github.io/_config.yml
            Source: D:/shafe/Documents/Dev/schpaper.github.io
       Destination: D:/shafe/Documents/Dev/schpaper.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: incompatible character encodings: Windows-1252 and UTF-8 in /_layouts/club.html
jekyll 3.3.0 | Error:  incompatible character encodings: Windows-1252 and UTF-8
```

## The Output I Wanted

This build should not fail.  None of the files have BOM headers, and they are all UTF-8.

/cc @jekyll/build and @jekyll/windows

**Comment by ashmaroli** [comment]
seems to be from `jekyll-seo-tag`. Removing  `{% seo %}` from `_includes/htmlheader.html` seems to solve this issue.

**Comment by SportingCRED** [comment]
thats a bug, you need to delete  _site folder evrytime befor  running jekyll, it's borring but it works!

**Comment by epogrebnyak** [comment]
In my case neither removing the seo tag, nor deleting the _site directory worked. I still get:

```
C:\Users\Евгений\Documents\GitHub\kppk>jekyll serve
Configuration file: C:/Users/Евгений/Documents/GitHub/kppk/_config.yml
Invalid theme folder: _includes
            Source: source
       Destination: C:/Users/Евгений/Documents/GitHub/kppk/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.8.5 | Error:  incompatible character encodings: UTF-8 and Windows-1251
```

**Comment by epogrebnyak** [comment]
In my case it makes a difference where the source files are located, if they are in project root folder, there is no error, if I configure to read from another folder (`--source DIR`), I get the incompatible character encodings error.

**Comment by epogrebnyak** [comment]
Shouldn't this issue be maked as open?

**Comment by ashmaroli** [comment]
> if I configure to read from another folder (`--source DIR`), I get the incompatible character encodings error.

@epogrebnyak What exactly is the custom source_dir name? Does it contain accented characters or other diacritics?

**Comment by epogrebnyak** [comment]
This [Stackoverflow thread](https://stackoverflow.com/questions/13146420/my-jekyll-site-cant-build-liquid-exception-incompatible-character-encodings) also suggests changing `chcp 65001`, but again it does not work with custom dir.

**Comment by epogrebnyak** [comment]
> @epogrebnyak What exactly is the custom source_dir name? Does it contain accented characters or other diacritics?

In my situation the project directory is `C:/Users/Евгений/Documents/GitHub/kppk/` and custom source dir is `C:/Users/Евгений/Documents/GitHub/kppk/source`, so in the long directory name there are non-ASCII characters. Maybe I should try to use a simple ASCII path to see if the error perisists.

**Comment by ashmaroli** [comment]
I think the issue is with your username `Евгений`.. Because of it the paths are encoded differently..
I tried creating a new site **with that name and was not able to build** at my end..
Can you try as well?
```
jekyll new Евгений
cd Евгений
bundle exec jekyll build
```

**Comment by epogrebnyak** [comment]
I'm able to build and serve from ```D:\github\here_is_jekyll_demo\Евгений``` as well as adding ```--source source```. The non-ASCII characters do not seem to be a root of a problem. 

The `jekyll new` command starts a `minima` theme. It seems I run into problems when doing `jekyll-theme-minimal`. My failing repo is [here](https://github.com/epogrebnyak/kppk).

**Comment by ashmaroli** [comment]
@epogrebnyak Can you set up [AppVeyor](https://www.appveyor.com) on that failing repo to test building on Windows..?

**Comment by epogrebnyak** [comment]
I moved the repo to a directory  with ASCII-only full path and the original problem is solved. Still strange the build works on non-ASCII full path until `--source DIR` is specified, but perhaps it is too subltle behavior to replicate and investigate. Short answer is: on Windows your entire full path better be ASCII characters.  

I did setup Travis (linux) and AppVeyor (windows) for repo, and they now show divergent errors:

- [Travis on Linux](https://travis-ci.com/epogrebnyak/kppk/builds/103811808) fails on parsing index.html file
- [AppVeyor  on Windows](https://ci.appveyor.com/project/epogrebnyak/kppk/builds/22960621) - fails to find the _layout files. Same error as mentioned as in #3248. Note the build is maked as success, but the resulting pages at `_site` are empty.

**Comment by ashmaroli** [comment]
> and they now show divergent errors:

Actually, errors on Travis and AppVeyor are the same. Your `_layouts` directory should either be inside your `source` or within the theme-gem..

**Comment by epogrebnyak** [comment]
> Your _layouts directory should either be inside your source or within the theme-gem..
Perhaps I should try a theme-gem, but that way I loose control of editing the layouts. 

The required path inside `source` folder is rather crazy:
`/home/travis/build/epogrebnyak/kppk/source/home/travis/build/epogrebnyak/kppk/_layouts/post.html `

I filled a new issue [error finding _layout\*.html files when building with --source DIR flag on Windows](https://github.com/jekyll/jekyll/issues/7563) as an error report. Maybe that should be a documentation request.
