### ISSUE TITLE
absolute_url filter can't represent https url

### ISSUE THREAD

**Issue by QXSoftware** [jekyll/jekyll#5590]
Hi Everybody!

This [pull request](https://github.com/jekyll/jekyll/pull/5405) is good, because it produced the absolute_url filter.

And also the [doc](https://jekyllrb.com/docs/templates/) is updated:

![](https://cloud.githubusercontent.com/assets/237985/18801805/e7323ea4-8199-11e6-9a08-83c56ceb923b.png)

But there is a little problem with https urls. When my github site is explored with a https url eg. ```https://qxsoftware.github.io/My-test-blog.html```, the **{{ page.url | absolute_url }}** returns ```http://qxsoftware.github.io/My-test-blog.html```.

So, is there any method that I can get the **https** full url?

Thanks!

**Comment by ashmaroli** [comment]
GitHub will automatically redirect all calls with an `http://` automatically to `https://` if the site is hosted under the `github.io` domain and is disabled by default on any other custom-domain. 
**Ref**: [Github Documentation](https://help.github.com/articles/securing-your-github-pages-site-with-https/)

While for assets with an absolute_url **it may still be** an `http://` call, we recommend using the `relative_url` for it anyways.

**Comment by QXSoftware** [comment]
@ashmaroli thanks for the reply 😃

I know that the http request will be redirect but I don't think this is the answer.There will be some circumstances in which I really need the correct url, without redirect. I really wish this will be done correctly or I'll just have to try some js hack. 😞

**Comment by ashmaroli** [comment]
> There will be some circumstances in which I really need the correct url, without redirect.

if that's the case, then you just have to update your `_config.yml`:
```diff
- url: "http://www.example.com"
+ url: "https://www.example.com"
```

**Comment by QXSoftware** [comment]
@ashmaroli many thanks! 😄

**Comment by nurandi** [comment]
I get the problem too.. Simple solution from @ashmaroli works perfectly. Thanks :)
