### ISSUE TITLE
SSL cert expired

### ISSUE THREAD

**Issue by mpchadwick** [jekyll/jekyll#5593]
Whoops

![image](https://cloud.githubusercontent.com/assets/4132322/20499034/a7f669da-affd-11e6-92f5-a5079cc11c05.png)

Was going to tweet @jekyllrb but it says it's unmaintained and points me to talk.jekyllrb.com, which is the thing I'm trying to report.

**Comment by mpchadwick** [comment]
Shameless plug - I built a service to help prevent this from happening https://domainclamp.com/

**Comment by DirtyF** [comment]
The SSL certificate has been renewed, thanks.

**Comment by pathawks** [comment]
It looks like https://teams.jekyllrb.com also has an expired certificate.

**Comment by parkr** [comment]
Updated teams.jekyllrb.com:

<img width="489" alt="screen shot 2016-11-23 at 1 49 49 pm" src="https://cloud.githubusercontent.com/assets/237985/20579828/d516025e-b183-11e6-8476-6ede30c193b5.png">

Anxiously awaiting Heroku's auto-certification feature... maybe someday.

**Comment by DirtyF** [comment]
@parkr [Netlify](https://www.netlify.com/) has auto-renewal and is free for open-source projects.

**Comment by parkr** [comment]
@DirtyF It's not a static site!
