### ISSUE TITLE
gemnasium service for jekyll breaks down

### ISSUE THREAD

**Issue by crispgm** [jekyll/jekyll#5595]
[![Dependency Status](https://img.shields.io/gemnasium/jekyll/jekyll.svg)](https://gemnasium.com/jekyll/jekyll) 

As a result, the dependency badge shows `undefined`.

**Comment by ashmaroli** [comment]
Is this even needed in the README? we lock a few gems to a certain minor_version and that's going to output an **`outdated`** status anyway, right?

**Comment by envygeeks** [comment]
It's standard practice so I see no reason to remove it, I'll email Gemnasium support today and figure out what's going on, I never unauthed it from Jekyll and I don't think @parkr did either... I've reauthed it but it won't pull the gems.

**Comment by crispgm** [comment]
@envygeeks looks good now

**Comment by DirtyF** [comment]
💎💎💎
