### ISSUE TITLE
gem install fails

### ISSUE THREAD

**Issue by stevebovy** [jekyll/jekyll#5606]
- [x] I believe this to be a bug, not a question about using Jekyll.

---

- [x] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+ Bash/Ubunto on Windows 10

---

- [x] I was trying to install.

## My Reproduction Steps

bovy@RECROOM:~$ sudo gem install jekyll
ERROR:  Error installing jekyll:
        public_suffix requires Ruby version >= 2.0.
bovy@RECROOM:~$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]

**Comment by pathawks** [comment]
I am sorry you are having trouble installing Jekyll.
Since this is a support question rather than a bug report, I would recommend you seek help at https://talk.jekyllrb.com
