### ISSUE TITLE
Can't calculate a percentage because divided_by rounds

### ISSUE THREAD

**Issue by timwis** [jekyll/jekyll#5616]
Hey folks, I'm trying to calculate a percentage using liquid and, to my surprise, it seems to be a bit impossible :-/

```liquid
{{ 3470 | divided_by: 8441 | times: 100 | round }}
```
expected: `41`
actual: `0`

It seems to be caused by the fact that liquid's `divided_by` filter [rounds the result "for you"](https://help.shopify.com/themes/liquid/filters/math-filters#divided_by). I was surprised that this behaviour is default, especially given there's a `round` filter, but more surprised that I can't seem to find a way around it :O

Is there no way to calculate a percentage?

**Comment by ashmaroli** [comment]
Since this is not related to Jekyll Core, I suggest you open a ticket at Liquid's [repo](https://github.com/Shopify/liquid).

**Comment by timwis** [comment]
That's fair, thanks

**Comment by ashmaroli** [comment]
but for now, there is a workaround:

`{{ 3470 | times: 100 | divided_by: 8441 }}`
