### ISSUE TITLE
using custom categories with pagination

### ISSUE THREAD

**Issue by pro-devel** [jekyll/jekyll#5620]
as far as jekyll pagination doesn't work with permalink i make my index page display the blog posts
my website have a blog / questions / news / media
so before i use the pagination it was pretty nice i was use `for` to display specified posts like
{% for posts in site.categories['blog'] %} 
to display blog posts only
in sub directory like /blog/
now i move the blog to the main index page 
and pagination works fine but display all posts `blog` `media` `news`
so there's any help ? or some tricks i can use to make the blog posts in multi pages with/without pagination ?

**Comment by pathawks** [comment]
Sorry you are having trouble.

You might have better luck finding answers to questions about templates at https://talk.jekyllrb.com

This issue tracker is only for bugs in Jekyll itself, so I am closing this issue.

**Comment by pro-devel** [comment]
I'm sorry ,I will post it in Jekyll talk 
thanks for your fast response
