### ISSUE TITLE
absolute_url not working with empty url

### ISSUE THREAD

**Issue by buckle2000** [jekyll/jekyll#5625]
`{{ page.permalink | absolute_url }}` will not work if `page.permalink` is `` (i.e. index page).

**Comment by buckle2000** [comment]
I might found the problem.
https://github.com/jekyll/jekyll/blob/7118999958dc5a334e523941cfb06762e7622e99/lib/jekyll/filters/url_filters.rb#L14

**Comment by buckle2000** [comment]
> https://github.com/jekyll/jekyll/blob/7118999958dc5a334e523941cfb06762e7622e99/lib/jekyll/filters/url_filters.rb#L14

**Comment by ashmaroli** [comment]
absolute_url is designed to prepend `<site.url>/<site.baseurl>/` to `<non-empty_input>`
If your `site.url`, `site.baseurl` and `input` are empty, then the filter returns an empty string.

**Comment by buckle2000** [comment]
I think `absolute_url` should transform any URL-like string into a complete URL. For example, HTTPS://google.com should remain unchanged.

In the current version, this processor will only append something in front of input. This is not absolute at all.

**Comment by ashmaroli** [comment]
what is the expected complete url string in your case?

**Comment by ashmaroli** [comment]
if your site is configured as
```
url: http://www.example.com
baseurl: /blog
```
then for given path `assets/css/style.css`
```
absolute_url = http://www.example.com/blog/assets/css/style.css
relative_url = /blog/assets/css/style.css
```
and for the index-page its:
```
absolute_url = http://www.example.com/blog
relative_url = /blog
```

**Comment by ashmaroli** [comment]
or you could define index-page url as simply `/`

**Comment by e0i** [comment]
I have tried to reproduce the issue. Calling `page.url` instead of `page.permalink` seems to deliver the expected result:

    {{ page.url | absolute_url }}

Does that work for your use case?

**Comment by buckle2000** [comment]
That is useful!
Thanks.

**Comment by buckle2000** [comment]
That is useful!
Thanks.
