### ISSUE TITLE
Docker run fails

### ISSUE THREAD

**Issue by lupa18** [jekyll/jekyll#5627]
- [x] I believe this to be a bug, not a question about using Jekyll.
---
- [x] I am on (or have tested on) ***Other*** GNU/Linux
---
- [x] I was trying to install.

## My Reproduction Steps

docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll \
  -it -p 127.0.0.1:4000:4000 jekyll/jekyll

## The Output I Wanted

Jekyll up and running

/cc @jekyll/build

## Output that happens

```
Configuration file: none
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.223 seconds.
jekyll 3.2.1 | Error:  �q��
sh: can't kill pid 35: No such process
```

**Comment by Christopotamus** [comment]
Hi @lupa18 ,

Can you try adding a _config.yml and see if that gets it working for you? I started a fresh jekyll project and was able to run the docker container without issue using the same command as you.

**Comment by lupa18** [comment]
Now it works even without config file
