### ISSUE TITLE
Jekyll not auto-regenerating on Windows

### ISSUE THREAD

**Issue by ruanltbg** [jekyll/jekyll#5629]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

-  Install Jekylls
- `bundle update`

Does not matter what I do, I can't have --watch working properly. 

My gem list is like:
```
* addressable (2.5.0)
  * bundler (1.13.6)
  * colorator (1.1.0)
  * faraday (0.10.0)
  * ffi (1.9.14)
  * forwardable-extended (2.6.0)
  * jekyll (3.3.1)
  * jekyll-feed (0.8.0)
  * jekyll-gist (1.4.0)
  * jekyll-paginate (1.1.0)
  * jekyll-sass-converter (1.5.0)
  * jekyll-sitemap (0.12.0)
  * jekyll-watch (1.5.0)
  * json (2.0.2)
  * kramdown (1.13.1)
  * liquid (3.0.6)
  * listen (3.0.8)
  * mercenary (0.3.6)
  * multipart-post (2.0.0)
  * octokit (4.6.2)
  * pathutil (0.14.0)
  * public_suffix (2.0.4)
  * rb-fsevent (0.9.8)
  * rb-inotify (0.9.7)
  * rouge (1.11.1)
  * safe_yaml (1.0.4)
  * sass (3.4.22)
  * sawyer (0.8.1)
```

And when I try to run jekyll server, with or withou `--watch` it returns like:

```
∴ bundle exec jekyll server --watch
Configuration file: /vagrant/vagrant_data/viajandonasferias/_config.yml
Configuration file: /vagrant/vagrant_data/viajandonasferias/_config.yml
            Source: /vagrant/vagrant_data/viajandonasferias
       Destination: /vagrant/vagrant_data/viajandonasferias/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 3.572 seconds.
 Auto-regeneration: enabled for '/vagrant/vagrant_data/viajandonasferias'
Configuration file: /vagrant/vagrant_data/viajandonasferias/_config.yml
    Server address: http://0.0.0.0:3000/
  Server running... press ctrl-c to stop.
```

And none of my modifications in files inside these folders "autoreload". 
- _layout
- _posts
-_includes

I always have to stop the server and init it again to see the changes.
I am on a windows machine running vagrant with ubuntu 14.04.5 LTS - box: 'ubuntu/trusty64'. I run the jekyll from a shared folder.

## The Output I Wanted

Auto-regenerationg working.

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by parkr** [comment]
There is an open ticket already for Windows and Vagrant not working with Listen (how we detect changes to files). VirtualBox (or whatever your VM software is) doesn't send the correct FS events. This is on them.

**Comment by ruanltbg** [comment]
@parkr sorry to open another one, I didn't find this issue. Do you want me to close this one?
To make sure I will try to run the jekyll with one Ubuntu folder, not a shared one.

**Comment by parkr** [comment]
We should link the two before closing. It's all good.

Yeah please try one when the files are not synced to the host machine and are modified in the VM. It's sounds like a matter of fsync not forwarding the change event.

**Comment by ashmaroli** [comment]
@ruanltbg If you're on a proper Windows system, have you tried running Jekyll using the default `cmd.exe`?
Note: Even then, Jekyll wont `watch` `_layouts,` `_includes`, etc inside the theme-gem.. only when these folders exist within the `source_dir` ..

**Comment by ruanltbg** [comment]
Hi @ashmaroli. I am on a Windows 10 machine but I am running Jekyll inside a VM (vagrant) Linux.
@parkr I tried with a Linux folder (not sync) and it worked like a charm, so the problem is with the sync folder in Vagrant.

I tried with ` jekyll server --watch --force_polling` and it worked with a delay of 6 to 10 seconds, it is not as fast as expected but I can work with that. 

```
 jekyll server --watch --force_polling
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /vagrant/vagrant_data/viajandonasferias/_config.yml
Configuration file: /vagrant/vagrant_data/viajandonasferias/_config.yml
            Source: /vagrant/vagrant_data/viajandonasferias
       Destination: /vagrant/vagrant_data/viajandonasferias/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 5.662 seconds.
 Auto-regeneration: enabled for '/vagrant/vagrant_data/viajandonasferias'
Configuration file: /vagrant/vagrant_data/viajandonasferias/_config.yml
    Server address: http://0.0.0.0:3000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2016-12-05 23:15:33 [2016-12-05 23:15:45] ERROR `/favicon.ico' not found.
...done in 18.598921444 seconds.
[2016-12-05 23:16:04] ERROR `/favicon.ico' not found.
      Regenerating: 1 file(s) changed at 2016-12-05 23:16:07 ...done in 6.47106464 seconds.
      Regenerating: 1 file(s) changed at 2016-12-05 23:16:14 ...done in 5.597614828 seconds.
[2016-12-05 23:16:31] ERROR `/favicon.ico' not found.
```

**Comment by parkr** [comment]
Glad you narrowed it down. Feel free to reference this issue if you file one with `guard/listen` or with VirtualBox. 👍 Sorry for the frustration! Wish we could do more, but we're at the mercy of your virtualization software.
