### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by ferhoba** [jekyll/jekyll#5634]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Hi, I am havig problem to update Jekyll from 3.2.1 to the latest (hp envy dv7 intel chipset, Windows 10)
You have everything in folowed images.

Tnx in advance

Ferhat

![image](https://cloud.githubusercontent.com/assets/24375097/20916580/c7123a66-bb8c-11e6-943d-22345ba80d94.png)

![image](https://cloud.githubusercontent.com/assets/24375097/20916599/e40c8e82-bb8c-11e6-98d5-02949dbff145.png)

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by ashmaroli** [comment]
what version is your RubyGems module at? Run `gem -v` to find out..:
if its less than `v2.6.8`, update it by running:
```
gem update --system
```
and then try updating jekyll again.
If it still fails, refer to following:
  [Link 1](https://github.com/rubygems/rubygems/issues/1736)
  [Link 2](https://gist.github.com/luislavena/f064211759ee0f806c88)

**Comment by ferhoba** [comment]
Hello,

Tnx for fast respond.
Instruction on manual set up on this link
http://guides.rubygems.org/ssl-certificate-update/#manual-solution-to-ssl-issue
helped me solve issue.

I hope this can help to someone.

Once more tnx a lot.

Ferhat
