### ISSUE TITLE
Jekyll 3.2.1 puts new project CSS files in wrong path

### ISSUE THREAD

**Issue by Grippentech** [jekyll/jekyll#5635]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

1.  jekyll new testBlog
2. cd testBlog
3. bundle exec jekyll serve

## The Output I Wanted

**Site renders correctly, instead got:**

 Auto-regeneration: enabled for 'C:/Users/andre/Desktop/testJekyll/testBlog'
Configuration file: C:/Users/andre/Desktop/testJekyll/testBlog/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
[2016-12-06 10:46:06] ERROR `/assets/main.css' not found.
[2016-12-06 10:46:09] ERROR `/assets/main.css' not found.
[2016-12-06 10:46:09] ERROR `/favicon.ico' not found.
[2016-12-06 10:46:10] ERROR `/assets/main.css' not found.
[2016-12-06 10:46:10] ERROR `/favicon.ico' not found.
[2016-12-06 10:46:10] ERROR `/assets/main.css' not found.
[2016-12-06 10:46:10] ERROR `/favicon.ico' not found.
[2016-12-06 10:46:10] ERROR `/assets/main.css' not found.
[2016-12-06 10:46:10] ERROR `/assets/main.css' not found.
[2016-12-06 10:46:11] ERROR `/favicon.ico' not found.
[2016-12-06 10:46:11] ERROR `/assets/main.css' not found.
[2016-12-06 10:46:11] ERROR `/favicon.ico' not found.

**This is because Jekyll 3.2.1 puts the CSS files in a CSS directory, whereas by default it looks for it in assets**

**Moving main.css from "css" to a new folder I create called "assets" fixes the issue.**

I hope this is indeed a bug and I am not wasting your time!

Thank you for making this wonderful tool!

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by ashmaroli** [comment]
Yes, this was a known bug.. but its been rectified.. 
Jekyll v3.2.1 should not be using Minima v2.0.. 
You have two options.. 
- either update Jekyll to `v3.3.1` and Minima to `v2.1.0` 
- or continue using Jekyll v3.2.1 and update your Gemfile to use Minima v1.2.0 by changing the line to `gem "minima", "1.2.0"`
