### ISSUE TITLE
How can i achieve the gist code highlightings?

### ISSUE THREAD

**Issue by sarbull** [jekyll/jekyll#5637]
I have tried all possible combinations of:
- rouge
- pygments
- kramdown
- markdown

And did not managed to create a exact replica of gist code highlighting. Any thoughts on this? Did anyone achived this?

**Comment by pathawks** [comment]
Can you explain your issue a bit more?

Are you trying to embed a Gist? Is nothing at all highlighted, or just highlighted incorrectly? What version of Jekyll are you using? How can I reproduce this issue?

**Comment by sarbull** [comment]
I want to highlight my code from markdown code like this:
```js
var a = true;
```
and look exactly like github's gist code highlights, without using an actual gist embeded code.

**Comment by pathawks** [comment]
Ok, so you are embedding code in your Markdown files, and Jekyll is highlighting that code, but you are not satisfied with how the highlighting looks?

Can you be a lot more specific? What are you seeing currently? What do you want to see? How does the current behavior differ from your desired behavior?
