### ISSUE TITLE
cleaner.rb:73:i n `parent_dirs': stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by SummerBuger** [jekyll/jekyll#5638]
I got a big problem

env:
os: windows7 + cygwin 
ruby: ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-cygwin] 
python: Python 2.7.12
jekyll: jekyll 3.3.1

when I just do
`jekyll build`
then I get the err:

```text
`C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/cleaner.rb:73:i
n `parent_dirs': stack level too deep (SystemStackError)
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/cl
eaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/cl
eaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/cl
eaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/cl
eaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/cl
eaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/cl
eaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/cl
eaner.rb:77:in `parent_dirs'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/cl
eaner.rb:77:in `parent_dirs'
         ... 9350 levels...
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercen
ary.rb:19:in `program'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/exe/jekyll:13
:in `<top (required)>'
        from C:/tools/ruby23/bin/jekyll:23:in `load'
        from C:/tools/ruby23/bin/jekyll:23:in `<main>'`
```

Is this a bug? or I am wrong ? who can help me ? thx a lot!!!

**Comment by pathawks** [comment]
Is the source of your site public? How can I reproduce this on my own machine?

**Comment by parkr** [comment]
Do you have any symlinks or hardlinks in your site? It sounds like it might be looping back on itself over and over. https://github.com/jekyll/jekyll/blob/master/lib/jekyll/cleaner.rb#L77

What are your `source` and `destination` settings?

**Comment by markspolakovs** [comment]
@SummerBuger If possible, please share with us the source of your website; we can't do much without it. Please create a GitHub repo and publish it there, then link it to us in this issue. Thanks!

**Comment by carols10cents** [comment]
I ran into this issue when I upgraded from jekyll 1.2.1 from 3.4.3, and I also had [the alias_generator plugin](https://github.com/carols10cents/carol-nichols.com/commit/62531f4d5fe8137fc52b644fe893da3525749895#diff-a51b8eacb6534342cd5fee5ec4ecc32a). When I removed the alias plugin file and switched to [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from), all was well :)
