### ISSUE TITLE
Update Core team list in the README file

### ISSUE THREAD

**Issue by quiltbag** [jekyll/jekyll#5642]
### First Timers Only

This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝 [About First Timers Only](http://www.firsttimersonly.com/)

### What you will need to know

Nothing! You can work on this issue in the web browser, so that and a GitHub account are the only things you need 😄 

### The Motivation

Jekyll is maintained by the [Core team](https://github.com/orgs/jekyll/teams/core). This team has the final word on important issues and manages the project altogether.

However, the [README](https://github.com/jekyll/jekyll#jekyll) section [Code of Conduct](https://github.com/jekyll/jekyll#code-of-conduct) only lists three maintainers, which is not true since the Core team has four members!

Because of this, the missing links should be added to said list! 

<h3>Step by Step</h3>

- [x] __Claim this issue__: Just comment below saying that you would like to claim this issue! __Assignee__: @hugomd
- [x] __Review__ our [Code of Conduct](https://github.com/jekyll/jekyll/blob/master/CONDUCT.markdown)
- [x] __Fork__ the [jekyll/jekyll repository](https://github.com/jekyll/jekyll/fork). Here is [more information about what forks are](https://help.github.com/articles/about-forks/).
- [x] __Update__ [jekyll/jekyll's README.markdown file](https://github.com/jekyll/jekyll/blob/master/README.markdown): Add `[@alfredxing](https://github.com/alfredxing)` to the `please let a maintainer [...] know` list
- [x] __Commit__ your changes with the message `Update Core team list in README`
- [x] __Start a pull request!__ Set the title to `Update Core team list in the README file` and the description to `fixes #5642`. There are two ways you can commit and send a pull request:
1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
2. You can edit and commit [using your browser](https://help.github.com/articles/editing-files-in-your-repository/). Here's how to [send a pull request from your fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).
- [ ] __You're done!__ Just ask in the comments for a review 😄 

<h3>Questions?</h3>

Feel free to ping me, @quiltbag here on GitHub, send me [an e-mail](mailto:penny@nice.lgbt) or send me a Direct Message [on Twitter](http://twitter.com/pennysucks).

**Comment by hugomd** [comment]
I claim this issue!

**Comment by quiltbag** [comment]
@hugomd you're all set! if there's any questions, just ask me!

**Comment by quiltbag** [comment]
update: github _somehow_ doesn't show teams if you're not in the organization, so let's resort to just manually adding the members to the existing list in the README file

**Comment by quiltbag** [comment]
aaand it's done! thanks so much for claiming this issue and making quick work of it @hugomd! ✨

**Comment by hugomd** [comment]
Thanks for having me, @quiltbag - I'll see about diving into Jekyll, picking up Ruby, and maybe trying to fix some more issues!

**Comment by quiltbag** [comment]
@hugomd if you want to keep tabs on jekyll, i recommend joining an [affinity team](https://teams.jekyllrb.com/)

**Comment by hugomd** [comment]
@quiltbag Which team would you recommend joining? The ecosystem team sounds cool!

**Comment by quiltbag** [comment]
@hugomd i'm not personally on the ecosystem team but i'd recommend it, yeah!

**Comment by Crunch09** [comment]
@quiltbag Mind if i ask what happened to @envygeeks ? He is not listed on https://github.com/orgs/jekyll/teams/core as of now? 😲

**Comment by quiltbag** [comment]
@Crunch09 my guess is that he left voluntarily, but it might be the other way around

**Comment by Crunch09** [comment]
@quiltbag Thanks!
