### ISSUE TITLE
Use assert_nil instead of assert_equal nil

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#5648]
Apparently, Minitest 6 will want us to use `assert_nil` instead of `assert_equal nil`. Our tests are already complaining about this:

```text
Use assert_nil if expecting nil from jekyll/test/test_page.rb:99:in `block (4 levels) in <class:TestPage>'. This will fail in MT6.
```

We use [`assert_equal nil` in a few places](https://github.com/jekyll/jekyll/search?utf8=✓&q=%22assert_equal+nil%22&type=Code), but this should not be difficult to cleanup.

**Comment by parkr** [comment]
:+1:
