### ISSUE TITLE
Instructions to update FontAwesome Icons

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#5650]
I was working on an idea when I realized I have no idea how to update the FontAwesome icons used by Jekyll Documentation. (https://jekyllrb.com/). Though I found the answer within this repo, it required some digging..

A quick investigation revealed the following:
  - It sure is more complicated now than when using the vanilla FontAwesome package.
  - dc4e77c added the instructions to `/docs/readme.md` instead of `/README.markdown`
  - The provided instructions dont specify *`how to add more FA Icons`* to the `.json`

--
/cc @XhmikosR

**Comment by XhmikosR** [comment]
Well, it's not for everyone. My PR was approved, which means someone understood what to do.

Either way, you are welcome to improve the instructions. I have no interest in doing so.
