### ISSUE TITLE
Post Excerpt Includes Footnotes

### ISSUE THREAD

**Issue by IanMitchell** [jekyll/jekyll#5659]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Preface:
I found that jekyll-seo-tag was appending the footnotes to their descriptions - apparently they call `.excerpt` and [referred me here](https://github.com/jekyll/jekyll-seo-tag/issues/144). 

If a footnote is present in the `.excerpt`, it appears that it is appended instead of dropped. A sample repository can be found here: https://github.com/IanMitchell/jekyll_test/commit/7bcb128933d1663f7f978544ff535bea51bf91fa

This results in the following output: https://gist.github.com/IanMitchell/67d8cd7a7ca4108ae771f2a3f80ed510

The sample repository shows the bug with `{% seo %}` output, but it does exist in `{{ page.excerpt }}` as well.

## The Output I Wanted

The content without the footnote appended

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)
@jekyll/build

**Comment by ashmaroli** [comment]
I was not able to reproduce this *completely:*
  - :white_check_mark: **[Bug reproduced]** with seo-tag in test post
  - :x: **[Bug not reproduced]** with seo-tag in test page

**Comment by IanMitchell** [comment]
I guess it's intended behavior, but that feels contrary to what I'd expect as a user. https://github.com/jekyll/jekyll/blob/38f9e93a10283b2ff4dab91d1eeab21c5d3efeb6/lib/jekyll/excerpt.rb#L105

**Comment by parkr** [comment]
Hi! This is entirely intended, as `[blah]: link` is Markdown for a reference link. We need those and have had them for about 4 years working this way (https://github.com/jekyll/jekyll/pull/837). I think the main issue here is that these footnotes are not simply thrown away. Unused reference links should be tossed by the markdown converter (in our case kramdown). 

In my case, kramdown is doing the right thing. Can you pipe the first paragraph of your post and the footnotes through the `kramdown` executable via:

```console
~$ echo -e "Hello there\n\n[^footnote]: Hello I am a footnote" | kramdown -i GFM
<p>Hello there</p>
```

Let me know what you see.

**Comment by IanMitchell** [comment]
```
$ echo -e "which launches a web server and auto-regenerates your site when a file is updated.[^footnote]

[^footnote]: Lorem ipsum dolor sit amet, consectetur adipiscing elit." | kramdown -i GFM
```

```html
<p>which launches a web server and auto-regenerates your site when a file is updated.<sup id="fnref:footnote"><a href="#fn:footnote" class="footnote">1</a></sup></p>

<div class="footnotes">
  <ol>
    <li id="fn:footnote">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <a href="#fnref:footnote" class="reversefootnote">&#8617;</a></p>
    </li>
  </ol>
</div>
```

**Comment by ashmaroli** [comment]
The string combo to consider here is `\n\n` which is Jekyll's default `excerpt_separator`
If a paragraph and the footnote is separated by `\n\n`, then there's no issue.. but the footnote is orphaned onto a newline..

**Comment by parkr** [comment]
If you remove the caret `(^)`, does it go away?

**Comment by parkr** [comment]
It kinda looks like the presence of `[^footnote]` on the first line means you'd *want* it to be output.

As an alternative, you can set `excerpt` in the YAML front matter which will override this default value. In case this is blocking your work.

**Comment by IanMitchell** [comment]
Turning it into a link instead of a footnote? The footnote text goes away in the sense it's moved to an href (might not be understanding what you meant, sorry). 

I'm currently overriding the behavior by using a YAML excerpt, but including the footnote text in a snippet of the article felt odd enough to be a bug. I think stylistically lifting the content of a footnote into the content doesn't make much sense; if you're consciously choosing to put additional information at the end of a document, I don't think there would be a case where one would want it to be in the excerpt.

**Comment by DanielTakeshi** [comment]
Hi all, I'm running into a similar issue. How did you manage to include footnotes, but have them *not* appear in the excerpt?

**Comment by IanMitchell** [comment]
Write a custom excerpt yourself using YAML - I still firmly believe this is a bug, but it looks like it won't be changed for legacy compatibility
