### ISSUE TITLE
Liquid syntax error: Unexpected character

### ISSUE THREAD

**Issue by benkeen** [jekyll/jekyll#5663]
Hi! I just updated one of my old 2.x Jekyll repos to use 3.3.1 and I'm getting a puzzling error: 

```Liquid Warning: Liquid syntax error (line 12): Unexpected character $ in "{{$required_resources}}" in modules/form_builder/customization/anatomy/header.html```

The error is from these lines: 

```
{% raw %}
<textarea class="codemirror" data-lang="html">
<html>
<head>
  <title>{{$form_name}}</title>
  {{$required_resources}}
</head>
<body></textarea>
{% endraw %}
```

I'm using Jekyll 3.3.1. Its my understanding that `{% raw %}` ensures all content in that block won't be evaluated, so this is a mite puzzling.

If you're curious to try it yourself, just check out `https://github.com/formtools/docs` and run `grunt start` (with Jekyll 3.3.1). 

Very possibly I'm doing something daft (I never rule THAT out), but I've done my due diligence and everything seems like it should work. Any ideas? 

- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`

**Comment by ashmaroli** [comment]
This is the [offending line](https://github.com/formtools/docs/blob/master/modules/form_builder/customization/anatomy/header.html#L27) actually.

**Comment by benkeen** [comment]
Gah! I do apologize - thanks for catching that. Closing.

**Comment by pinggit** [comment]
I always got here by google..
the error looks same but I don't understand the solution...
in my case it is:
```
Liquid Warning: Liquid syntax error (line 83): Unexpected character { in Liquid Warning: Liquid syntax error (line 83): Unexpected character { in "{{{2}}" in abc.markdown
```
I did use {% raw %} and {% endraw %} but not working..
how to resolve this actually?

**Comment by ashmaroli** [comment]
@pinggit From the error message, it looks like you have an extra opening curly bracket (`{`). Simply replace `{{{2}}` with `{{2}}`.
If that extra bracket is intentional, you'll have to provide more information or context

**Comment by Rushan-Chen** [comment]
```vue
<template>
  <h1>Create Event, {{ $store.state.user.name }}</h1>
</template>
```

I'm using Jekyll 3.7.4.

I write some vue code, and get the warning as below:

> Liquid Warning: Liquid syntax error (line 7): Unexpected character $ in "{{ $store.state.user.name }}"

I've searched google but still not get the solution.

**Comment by ashmaroli** [comment]
@Rushan-Chen Liquid parses all instances of `{{`, `}}`, `{%`, `%}` as Liquid constructs. To tell Liquid not to parse such instances, wrap the code inside Liquid's `raw` blocks:
```html
<template>
  <h1>Create Event, {% raw %}{{ $store.state.user.name }}{% endraw %}</h1>
</template>
```
or if you have a block of such code, wrap the entire markup:
```html
<template>
  {% raw %}
  <h1>Create Event, {{ $store.state.user.name }}</h1>
  <p>
    {{ $store.state.description }}
  </p>
  {% endraw %}
</template>

**Comment by Rushan-Chen** [comment]
@ashmaroli  Really thank you so much! 😃
