### ISSUE TITLE
Page title not retrieving from config, or markdown h1

### ISSUE THREAD

**Issue by MiguelPynto** [jekyll/jekyll#5667]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [x] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

After creating a gh page, the page title is retrieved from the first ## (h2), after the # (h1) in readme.md file. It should be the first # (h1).
Also, editing the _config.yml, adding title, page.title, site.title, it doesn't change the page title, allways revert to the ## (h2).

Project: https://github.com/MiguelPynto/ShiftDisplay
Config: https://github.com/MiguelPynto/ShiftDisplay/blob/master/_config.yml
Page:  http://miguelpynto.github.io/ShiftDisplay

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by DirtyF** [comment]
@MiguelPynto I made a quick test on a new repo https://dirtyf.github.io/pages/ and the h1 in the README is well set with the Cayman theme. Anyway this is not a Jekyll bug, but more related to GitHub Pages, I suggest you contact the support.

**Comment by ashmaroli** [comment]
@MiguelPynto I had opened a related ticket at [jekyll-titles-from-headings repo](https://github.com/benbalter/jekyll-titles-from-headings/issues/4)
you can add to it.. or open a new ticket entirely..
