### ISSUE TITLE
Get query string parameters

### ISSUE THREAD

**Issue by JiaKunUp** [jekyll/jekyll#5672]
Hi 
I find that jekyll can get url with liquid syntax like `{{ page.url }}`, but this doesn't contain query string parameters,if my url is **/profile/?name=jack**, `{{ page.url }}` is **/profile/** not **/profile/?name=jack**.
I find an [issue](https://github.com/jekyll/jekyll/issues/617) about this, the solution is to use javascript, but I have no idea to deal query string parameters with liquid syntax like : `{{ page.url.params.foo }}` or  `{% for post in site.categories[page.url.params.foo] %}`,I think jekyll support this will be better.
Thanks!

**Comment by pathawks** [comment]
This is not possible to do in Jekyll or Liquid.

Jekyll converts your source files to _static_ HTML files at build time, and then serves those files to site visitors.

Query strings are not sent to the server until a page is served, which means the page has already been built. Jekyll has already done its thing, and is likely not even running at the time a page is served.

Because of this, Jekyll _cannot_ support arbitrary URL queries in Liquid. That said, there is probably another way to solve whatever problem you are trying to tackle. What are you ultimately trying to accomplish?

**Comment by JiaKunUp** [comment]
I have some pages with same layout, but with different keywords the page shows different content, now my method is to create each file of them:
* python.html
* ruby.html
...

code in python.html is :

``` html
---
layout: blog
title: Python
permalink: /python/
---
{% include category.html %}
```

and code in category.html is:

``` html
<div class="row">
    <div class="col-lg-12 text-center">
        <div class="navy-line"></div>
            {% assign category = page.url | remove:'/' | capitalize %}
            {% if category == 'Html' %}
            {% assign category = category | upcase %}
            {% endif %}
        <h1>{{ category }}</h1>
    </div>
</div>

<div class="wrapper wrapper-content  animated fadeInRight blog">
    <div class="row">
		<ul id="pag-itemContainer" style="list-style:none;">
    {% assign counter = 0 %}
		{% for post in site.categories[category] %}
		{% assign counter = counter | plus: 1 %}
		<li>
...
```

I use `{% assign category = page.url | remove:'/' | capitalize %}` to get my category and `{% for post in site.categories[category] %}` to filter my posts.

But if I can get query string parameters I only need to create one html file like this:

``` html
---
layout: blog
title: {{ page.url.params.category }}
permalink: /category/
---
This page is {{ page.url.params.category }} for categories.
```

and url **/category/?category=python** page is same as  **/python/** rendered by python.html .

**Comment by pathawks** [comment]
If you are just trying to create archive pages for categories, you might take a look at [**jekyll-archives**](https://github.com/jekyll/jekyll-archives)

**Comment by JiaKunUp** [comment]
Thanks, I will try jekyll-archives.
This is an example, but what if I want to use other place?I have javascript pagination for each category, this can't be accomplished in jekyll pagination.

**Comment by pathawks** [comment]
I guess what I'm getting at is that this specific task cannot be accomplished by Jekyll (or any _static_ site generator), but chances are that there is another way to accommodate whatever the larger problem is.

**Comment by JiaKunUp** [comment]
Anyway, thanks for help me solving this problem. 👍

**Comment by pathawks** [comment]
If you have further questions about what your options are, try https://talk.jekyllrb.com/

There are some good resources online explaining how to do some pretty awesome things with static sites.

**Comment by JiaKunUp** [comment]
OK, good.
