### ISSUE TITLE
Consider removing gem specific check for pagination 

### ISSUE THREAD

**Issue by sverrirs** [jekyll/jekyll#5673]
Currently if the site.config file contains an entry `paginate` but the `jekyll-paginate` gem is not referenced then Jekyll will print out an error like this

```
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
```

This code is found in the [plugin_manager.rb](https://github.com/jekyll/jekyll/blob/57fd5f887da1189a16bdfbb982d75f725c38d725/lib/jekyll/plugin_manager.rb#L90-L95) file.

__This error message is misleading and should be removed.__

The [jekyll-paginate](https://github.com/jekyll/jekyll-paginate) gem has been marked as _no longer under active development_ which must be interpreted as a deprecation. This will prompt other devs (such as myself) to provide alternative pagination logic that may or may not be backwards compatible with this old gem. 

Having Jekyll print this message out even though there is a pagination gem installed that is currently providing support for the old `paginate` configuration element is misleading. Therefore I would like to suggest that this check be removed from the Jekyll main source code.

**Comment by DirtyF** [comment]
@sverrirs I know that `jekyll-paginate` is still included by default in [GitHub Pages](https://pages.github.com/versions/ ), so not so sure this can be removed yet.

I see you developed https://github.com/sverrirs/jekyll-paginate-v2, could it be part of @jekyll/plugin-core ?

/cc @jekyll/core

**Comment by pathawks** [comment]
When was the depreciation message added?
If during 3.x, maybe we could remove it when 4.0 lands. If 2.x, maybe we don't even need to wait that long.

**Comment by quiltbag** [comment]
seems to have been added by @parkr in the first 3.0.0-beta2 (https://github.com/jekyll/jekyll/commit/a87cda4b128187740f6ee70c264cb8c4912e0451)

**Comment by sverrirs** [comment]
@DirtyF Yes I am the author of the jekyll-paginate-v2. You're more than welcome to include it in plugin-core if you think it is good enough, I would welcome more feedback and new contributors.

Re: the message; it obviously was added for a good reason and I'm all for retaining it while it is useful for the majority of the user-base. If it is only intended for github pages though, would it make sense to have a test in there to detect that platform and only print the error then?
