### ISSUE TITLE
Could not find 'listen'

### ISSUE THREAD

**Issue by mattkcole** [jekyll/jekyll#5675]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

`$ jekyll serve` results in the output:

```
/usr/local/lib/site_ruby/2.3.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'listen' (< 3.1, ~> 3.0) - did find: [listen-3.1.5] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/user/~`
```

`$ gem query --local`

shows:
```
*** LOCAL GEMS ***

addressable (2.5.0)
bigdecimal (1.2.8)
colorator (1.1.0)
did_you_mean (1.0.0)
ffi (1.9.14)
forwardable-extended (2.6.0)
io-console (0.4.5)
jekyll (3.3.1)
jekyll-sass-converter (1.5.0)
jekyll-watch (1.5.0)
json (1.8.3)
kramdown (1.13.1)
liquid (3.0.6)
listen (3.1.5, 3.1.1, 3.1.0, 3.0.8)
mercenary (0.3.6)
minitest (5.8.5)
net-telnet (0.1.1)
pathutil (0.14.0)
power_assert (0.2.6)
psych (2.1.0)
public_suffix (2.0.4)
rake (10.4.2)
rb-fsevent (0.9.8)
rb-inotify (0.9.7)
rdoc (4.2.1)
rouge (1.11.1)
ruby_dep (1.5.0)
safe_yaml (1.0.4)
sass (3.4.23)
test-unit (3.1.5)
```

I also tried:

`gem install listen --version 3.1.0`
which appeared to reinstall listen, but to no avail.

## The Output I Wanted

I wanted to be able to access Jekyll 

`$ jekyll serve`

**Comment by ashmaroli** [comment]
@mattkcole we recommend installing bundler and use it to run jekyll commands:
```sh
# install bundler
#
$ gem install bundler

# use bundler to execute jekyll commands
# Note: requires a Gemfile within project directory
#
$ bundle exec jekyll serve
```

**Comment by mattkcole** [comment]
Thank you!
