### ISSUE TITLE
Blog posts dated today are excluded from processing

### ISSUE THREAD

**Issue by theunrepentantgeek** [jekyll/jekyll#5678]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll

---

- [x] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to build.

## My Reproduction Steps

* Write a draft blog post under the standard `_drafts` folder
* Build the site locally, using the `--drafts` option
* Preview the blog post successfully
* Rename the file by prepending the current date `2016-12-23`
* Move the file to the `_posts` folder
* Build the site locally (without `--drafts`) and observe the post is missing
* Rename the file by changing the prepended date to yesterday `2016-23-22`
* Build the site locally (again, without `--drafts`) and successfully preview the post

Other information: I'm building my site and previewing it with Edge, using IIS as the web server, entirely on my local machine.

## The Output I Wanted

The blog post was not future dated (the date was *today*), so it should have appeared in the output folder.

**Conjecture**: Is this a time zone issue? I'm building the site midmorning on Friday 23 December, my local timezone is NZDT (+13); If the "current date" used by Jekyll is based on UTC (or earlier), then it would think the current date was only Thursday 22 December.

/cc @jekyll/build

**Comment by Crunch09** [comment]
Hi @theunrepentantgeek ,
both (the post date and your site's time of build) should take the timezone into consideration by default. Have you set the `time` or `timezone` value in your config?

**Comment by ashmaroli** [comment]
The `timezone` used by Jekyll is either the system's TZ setting or the `timezone` value in `_config.yml`  
Upto Jekyll `v3.3.1`, there existed a bug for Windows platform that on having the `timezone` value set in the config file, the `TZ` variable would be *reset* to UTC 0

The **workaround** is to set the timezone using [POSIX standard](http://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html)   
(in short, any three-letter-word followed by **UTC Offset in reverse**.: e.g. **NZT-13:00** in your case)   
or remove the `timezone` key entirely.

**Comment by theunrepentantgeek** [comment]
@Crunch09 - My `_config.yml` file does have the timezone set to match my location:

```
timezone: Pacific/Auckland
```

@ashmaroli I'm already running `v3.3.1`, so I shouldn't be running into the bug you describe. I'll run a test tomorrow morning to confirm or refute.

**Comment by ashmaroli** [comment]
@theunrepentantgeek the bug was addressed after the release of `v3.3.1` So, you can test locally by using the master branch of this repo: (Note: wont work on GitHub Pages)
```ruby
gem 'jekyll', :github => 'jekyll'
```

**Comment by theunrepentantgeek** [comment]
I've tried two of the suggested workarounds (using the IANA timezone and relying on the timezone of the PC) and the odd behaviour I'm seeing persists.

Another thing I've noticed is that todays draft post (with a creation & modification date of 30/12/2016) shows up on the generated site with date 29/12/2016.

@ashmaroli I don't understand how/where to apply your suggested **gem** command; I'm not building any gems, nor am I using **bundler**. (For that matter, I'm not really a ruby dev at all, so I'm struggling with the ecosystem a little.)

**Comment by theunrepentantgeek** [comment]
I tried an experiment with todays blog post, rebuilding the site locally (without modification) each hour to see when the new post would be included in the generated output. 

Builds prior to 1pm local time did *not* include my latest blog post.
My first build after 1pm local time *did* include by latest blog post.

**Comment by pathawks** [comment]
> My first build after 1pm local time did include by latest blog post.

So, when it was finally "today" in London? Makes sense.

**Comment by ashmaroli** [comment]
@theunrepentantgeek Sorry I wasn't clear.. the **gem** hack was to be used in your Gemfile. If you're still facing an issue, I'll set up a temporary test repo for you to clone to simply `serve` right away.

**Comment by theunrepentantgeek** [comment]
@pathawks Yes, exactly.

@ashmaroli Thanks very much for the offer, really appreciate that. However, given that I've discovered a simple workaround ("wait until after lunch"), and given that the bug has been addressed in `master`, I can easily wait for the next release.

I propose to close this issue - if I can still repro this issue in the next release, I'll refile/reopen as appropriate.

**Comment by pathawks** [comment]
> if I can still repro this issue in the next release, I'll refile/reopen as appropriate.

Please do, and @-mention me directly :+1:

**Comment by yalov** [comment]
Timezone-related weirdness.  
Windows 10. Locale UTC+3. 
There is no `timezone:` in `_config.yml`.

This is
```
{% assign somedate = "2010-10-10 10:10:10 UTC" %}
{{ somedate  | date_to_xmlschema  | date: "%Y-%m-%d %H:%M:%S" }}
{{ somedate  | date_to_string     | date: "%Y-%m-%d %H:%M:%S" }}
{{ somedate  | timezone: UTC3     | date: "%Y-%m-%d %H:%M:%S" }}
{{ somedate  | timezone: 0300     | date: "%Y-%m-%d %H:%M:%S" }}
{{ somedate                       | date: "%Y-%m-%d %H:%M:%S" }}
```
outputs
```
2010-10-10 13:10:10
2010-10-10 00:00:00
2010-10-10 10:10:10
2010-10-10 10:10:10
2010-10-10 10:10:10
```

Why does only first shows locale time?

**Comment by theunrepentantgeek** [comment]
`date_to_string` does what it says on the label - it converts `somedate` into a series of characters that represent the date only, discarding any time part. When that's reformatted, the "no time" comes out as midnight.

For the rest, I don't know enough Ruby/Liquid to answer.

**Comment by ashmaroli** [comment]
`date_to_xmlschema` will return a formatted String for use in XML
`date_to_rfc822` will return a formatted String according to `RFC-822`

The above two will use the `TZ` environment variable and format the `time` part accordingly.
`ENV["TZ"]` equals the system timezone and from Jekyll 3.4, will equal the IANA Timezone specified in your `_config.yml`

`date_to_string` and `date_to_long_string` will return formatted Strings filtered to only contain `date-month-year` data. So the `hour-min-sec` is essentially set to `0`

I don't know of any existing `timezone` filter so my best guess is that it simply returns the assigned `somedate` string

Note: With Jekyll 3.4, you'll need to bundle the `tzinfo-data` gem to modify the `ENV["TZ"]` on Windows. The Timezone returned in the formatted String will simply say `WTZ` or `WorldTimeZone` even though the `time` string is converted correctly.

**Comment by yalov** [comment]
So 
`{{ somedate  | date: "%Y-%m-%d %H:%M:%S" }}` — always UTC
`{{ somedate  | date_to_xmlschema | date: "%Y-%m-%d %H:%M:%S" }}` — my locale (may be some buggy)

``` javascript
<script type="text/javascript">
    date = Date((2010, 10, 10, 10, 10, 10, 100)) // UTC
    return (date.getHours() + ":" + date.getMinutes())  // locale of user who opens a blog
</script>
```
?

**Comment by pathawks** [comment]
Can we move discussions that are unrelated to bug reports to https://talk.jekyllrb.com
