### ISSUE TITLE
Date filters should never raise an exception

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#5680]
Liquid's own `date` filter will never raise an exception. If passed something that it cannot convert to a date, ~~it will just output `nil`~~ it will passthrough the input unchanged.

It seems like [our own date filters](https://github.com/jekyll/jekyll/blob/v3.3.1/lib/jekyll/filters.rb#L66-L110) should just be convenience methods where the format has already been provided. However, they will all [`raise` an exception](https://github.com/jekyll/jekyll/blob/v3.3.1/lib/jekyll/filters.rb#L379-L380) if the input cannot be converted to a date.

In order to more closely match Liquid core behavior, I wonder if we could also just output `nil` when the input cannot be converted to a date? Perhaps we could warn, but build the site anyway?

This would probably need to wait until Jekyll 4.0…

/cc @jekyll/ecosystem

**Comment by parkr** [comment]
If this behavior was present in Liquid 3, then we have simply been inconsistent. I would be fine making it consistent with Liquid if it worked this way in Liquid 3.

**Comment by pathawks** [comment]
[Liquid 3](https://github.com/Shopify/liquid/blob/3-0-stable/lib/liquid/standardfilters.rb#L221-L227) will simply let the input passthrough if it cannot be converted to a date.

The behavior is the same in Liquid 3 & Liquid 4.

**Comment by parkr** [comment]
Then I'd say 👍 on matching the Liquid 3/4 behaviour. We should have done that all along 🥇

**Comment by DirtyF** [comment]
fixed in #5722
