### ISSUE TITLE
this is the error message i got trying to install jekyll on the command prompt: 'gem' is not recognised as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Prescriptio** [jekyll/jekyll#5681]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by quiltbag** [comment]
this error is related to your ruby installation, not jekyll

**Comment by DirtyF** [comment]
@Prescriptio You should be able to install Jekyll easily with this script:
https://gist.github.com/DirtyF/5d2bde5c682101b7b5d90708ad333bf3

**Comment by ashmaroli** [comment]
@DirtyF IMO, the script above should install the latest stable Ruby v2.3.3 ..

**Comment by Prescriptio** [comment]
Thanks guys @quiltbag are u saying i should re-install ruby? @DirtyF i tried the script in my command prompt windows 8 it's saying 'curl is not recognized as internal or external command. MAybe i'm getting things wrong.

**Comment by DirtyF** [comment]
@Prescriptio Sorry it's intended for OSX. You should take a look at https://labs.sverrirs.com/jekyll/
