### ISSUE TITLE
Stub Liquid Tags

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#5686]
- [x] This is a feature request.

---

Several Jekyll plugins add Liquid tags that allow sites to easily add something to a layout (i.e.: `{% seo %}`, `{% feed_meta %}`).

If a site is using a theme, the site would need to override theme files locally in order to add these tags. It would be nice if themes could just Do The Right Thing out of the box.

If a theme includes a Liquid tag that doesn't exist, Liquid (rightly) chokes.

Perhaps, Jekyll core could include a few of these tags, but just set them up to output the empty string. Then, if a user has the proper plugin installed, that plugin would take over the logic and do its thing when the tag is called.

This way, themes could put things like {% seo %}` and `{% feed_meta %}` in the appropriate places without worrying whether users have those plugins installed or not, and the tags will only do anything if the plugins _are_ installed.

A possible downside would be a user adding `{% seo %}` to a template without installing the plugin and not realizing that nothing is happening.

/cc @jekyll/ecosystem

**Comment by pathawks** [comment]
thanks @jekyllbot

**Comment by parkr** [comment]
I like that we fail loudly in this case. I would love to see the ability for themes to specify plugins they need.
