### ISSUE TITLE
Clarify tags property with collections

### ISSUE THREAD

**Issue by tomjohnson1492** [jekyll/jekyll#5697]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

Basically collections claim to have a tags property even when no doc in the collection does. 

## My Reproduction Steps

1. Create a new collection called _dummycontent. 

2. Create a doc in the dummycontent collection. Do not include any "tags" frontmatter in the doc.

3. On the doc you created, add this code:

```
{% for doc in site.dummycontent %}
{% if doc.tags %}
yes there is some tags content
{% else %}
no there isn't any tags content
{% endif %}
{% endfor %}
```

The response is "yes there is some tags content." But why? The doc doesn't have any tags property in the front matter, nor are there tags defaults set for the collection in the config file. 

I tried to access the tags like this:

```
{% for tag in site.dummycontent.tags %}
{{tag}}
{% endfor %}
```

But I get nothing.

I also tried this: 

```
{% for doc in site.dummycontent %}
{{doc.tags}}
{% endfor %}
```

Nothing.

I also tried this:

```
{{page.tags}}
{{dummycontent.tags}}
```

Nothing.

## The Output I Wanted

Ideally, I'd love for tags to be a built-in variable that I could look in directly, such as by running a for loop with site.dummycontent.tags. However, at the very least, if a doc doesn't have any tags properties set, then when I run a condition such as this:

```
{% if doc.tags %}
```

It shouldn't return true when there isn't a tags property set.

**Comment by pathawks** [comment]
This seems like a Liquid issue.

My _guess_ is that `doc.tags` is an empty array, and Liquid is evaluating that as _Truthy_.

**Comment by ashmaroli** [comment]
Its not a bug actually. If you were to use the `inspect` filter `{{ page.tags | inspect }}`, you'd see that `tags` is a valid object even if not explicitly defined.

**Comment by tomjohnson1492** [comment]
thanks for getting back to me on this. i'm having a hard time understanding why this isn't a bug. if I run `{{ page.tags | inspect }}`, it shows `[]`. but suppose I were to run `{{ page.weather | inspect }}`, I get `nil`. 

What purpose does `tags` returning `[]` as the default serve in collections?

Here's where this functionality is bothersome. I have a tagging scheme set up with my pages. If some pages don't have tags, I wanted to do something different with them. I now need to use separate logic when looking at "tags" properties in page frontmatter:

```
{% if page.tags == empty %}
the page doesn't have any tags
{% else %}
the page does have tags
{% endif %}
```

But for other tags, this same logic doesn't work. I'd have to use something like this:

```
{% if page.weather == null %}
the page doesn't have any weather
{% else %}
the page does have weather
{% endif %}
```

I think this inconsistency is a bug. There's no reason why tags should default to an empty array. What am I missing?

**Comment by ashmaroli** [comment]
The reason could be that Jekyll being a blog-aware software initializes `tags` as an empty array.  Variables like `tags`, `excerpt`, `excerpt_separator` etc are reserved for internal use.
The variables introduced by the consumer / theme-developer will be initialized if required.

**Comment by pathawks** [comment]
> There's no reason why tags should default to an empty array.

I think the reason is so developers can reliably loop over `each` item in the array without worrying about if the array exists or not.

I agree that it can lead to some unintuitive behavior.
