### ISSUE TITLE
Issue with file paths

### ISSUE THREAD

**Issue by christiantype** [jekyll/jekyll#5702]
Hello,

I've placed the images that I wish to use in a images folder located here: https://github.com/christiantype/christian-thoughts/tree/master/_assets/images

In my `index.html`, I'm calling images associated with each post by having the following code:
`<img src="{{ '/' | relative_url }}{{ post.image }}"/>
`
The  {{ post.image }} is referring to the path that I included in the FrontMatter of my posts. For example, this post here: https://raw.githubusercontent.com/christiantype/christian-thoughts/master/_posts/2016-11-16-cdm.md

Has `image: "projects/cdm/cdm_thumb.jpg"` which should be linking to the `{{ post.image }}` mentioned in my `index.html`

I've tried multiple ways to write out the path in the post's FrontMatter but nothing seems to work. 

I still receive an error message in terminal saying: 
`[2016-12-28 11:46:48] ERROR `/journal/assets/projects/cdm/cdm_thumb.jpg' not found.
`

Here is my updated repository.
https://github.com/christiantype/christian-thoughts
Thank you

**Comment by DirtyF** [comment]
@christiantype Since you're using [jekyll-assets plugin](https://github.com/jekyll/jekyll-assets), I suggest you open an issue there or look and ask for help on [https://talk.jekyllrb.com](https://talk.jekyllrb.com/search?q=jekyll-assets)
