### ISSUE TITLE
Jekyll 3.2.1 https mixed content problem

### ISSUE THREAD

**Issue by benjaminhon** [jekyll/jekyll#5709]
I am hosting my page from Github Pages, and using a CNAME to redirect to my github project page.

under my _config.yaml file i have
```
baseurl: "/circuit-monk"
url: "https://benjaminhon.github.io"
```

my site works without CNAME, however when i add the CNAME (my domain has SSL certification set up)

i get all these errors

```
Mixed Content: The page at 'https://www.circuitmonk.com/math/2016/10/14/jupyter-notebook.html'
 was loaded over HTTPS, but requested an insecure stylesheet 
'http://www.circuitmonk.com/assets/main.css'. This request has been blocked; the content must be 
served over HTTPS.
```

First, i always use the ```absolute_url``` for all my assets, i am using the ```minima 2.0.0``` theme and override the parts (_layouts and _includes) where i place my links
For example,
```
<link rel="stylesheet" href="{{ "/assets/main.css" | absolute_url }}">
<link rel="stylesheet" href="{{ '/assets/css/fluidmedia.css' | absolute_url }}">
```

but it seems like the error says it it trying to access main.css from
```
http://www.circuitmonk.com/assets/main.css 
// [http!! not https, i cant change this, as there is no setting???]
```
rather than from
```
https://benjaminhon.github.io/circuit-monk/assets/main.css
```

i checked my index.html files generated and all the links are using the absolute url ```https://benjaminhon.github.io/circuit-monk/assets/...```, thus its a mystery where ```http://www.circuitmonk.com/assets/main.css``` is coming from, im guessing its the redictects? but how can i change it to use https instead of http?

thanks

**Comment by DirtyF** [comment]
What happens of you remove `url` and `baseurl` from your config file?

Locally Jekyll will set default url to localhost:4000 and so you'll be able to preview your website:
![circuitmonk](https://cloud.githubusercontent.com/assets/103008/21576904/0ca3653a-cf44-11e6-85b4-796731ac4fe7.png)

I'm not sure GitHub needs these values either.

**Comment by benjaminhon** [comment]
@DirtyF Thanks for reply,

I suspect that it is because of the following that is happening:

my CNAME file is
```
www.circuitmonk.com
```
Everytime there is a link from the absolute URL
```
https://benjaminhon.github.io/circuit-monk/assets/main.css
```
The CNAME aliases it as:
```
http://www.circuitmonk.com/assets/main.css # no way to change this to https?
```

However i managed to get it working by changing:

*_config.yaml* from
```
baseurl: "/circuit-monk"
url: "https://benjaminhon.github.io"
# to
baseurl: ""
url: "www.circuitmonk.com"
```

In my DNS server:
```
APEX: 
circuitmonk.com -> 192.30.252.153
circuitmonk.com -> 192.30.252.154

CNAME:
www -> benjaminhon.github.io
```

In my project CNAME
```
www.circuitmonk.com
```

the actual site is at ```https://benjaminhon.github.io/circuit-monk```, so i thought of setting the baseurl and url to match it, and then use the CNAME to redirect ```www.circuitmonk.com``` to the project page. But this seems to be screwing up with the links.

is this the right way to do this?

**Comment by parkr** [comment]
Set `url: "https://www.circuitmonk.com"` if you're trying to use HTTPS. All `absolute_url` does is: `url + baseurl + input`, therefore `https://www.circuitmonk.com + "" + input` would be best.
