### ISSUE TITLE
Copyright date in LICENSE

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#5710]
Before somebody submits the annual PR to update the copyright date in `LICENSE`, I just wanted to ask how that all works, legally.

Why do we say that TPW owns the copyright to Jekyll code from 2016 when his last commit was 2013?
When I contribute to Jekyll, do I transfer the copyrights to my contributions to TPW? Neither the license nor CONTRIBUTING says anything to that effect.

Would it be better to say that Jekyll’s copyright is owned by its contributors, or maybe all future contributions will be owned by GitHub?

Obviously I am not a lawyer, I just wanted to see if somebody smarter than I knew the answer, before we just blindly `date++`

(I also apologize for posting this as an issue. This is almost certainly not the place for this discussion, but I’m unsure where it _would_ belong)

**Comment by bkeepers** [comment]
@benbalter has a good [overview of copyright notices](http://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/).

For this instance, the original jekyll code is copyright TPW, but all contributors retrain the copyright for the code they contributed. The pattern we've been using for most new projects at GitHub is `Copyright (c) GitHub and contributors`.

The license file could probably be updated to be: `Copyright (c) Tom Preston-Werner and Jekyll contributors`

cc @mlinksva

**Comment by DirtyF** [comment]
Si if we were to follow @benbalter pattern, we should write:

`Copyright 2008 - 2017, Tom-Preston Werner and Jekyll contributors`

Would you care to submit a PR @pathawks?

**Comment by benbalter** [comment]
👍 to be perfectly transparent, we could just say `(c) 2008 - 2017 Jekyll contributors`, but personally, I like the idea of honoring the project founder with a more prominent position (or in the case of @bkeepers's example, the corporate project maintainer) as a nod of acknowledgement.

**Comment by DirtyF** [comment]
@benbalter Should we also add Parker Moore then? I'm all for acknowledgement.

**Comment by pathawks** [comment]
If we added the current maintainer in addition to the founder, it seems only fair that we add past maintainers as well. That seems like it could be a bit much.

Not to diminish their efforts in any way, of course. Jekyll would not be where it is if not for the efforts of these individuals. My only concern is that the `LICENSE` should be as easily scannable as possible.
