### ISSUE TITLE
Custom variables, dynamic dereferences

### ISSUE THREAD

**Issue by DaveJarvis** [jekyll/jekyll#5714]
- [x] This is a feature request.

---

## My Reproduction Steps
Consider the following Markdown (e.g., `README.md`):

```
![Logo]($application.directory.images$/logo.png)
$application.title$
===
$application.description$
![Screenshot]($application.directory.images$/screenshot.png)
```

Along with the following YAML file:

```
application:
  title: Application
  directory:
    images: images
  description: $application.title$ is almost as amazing as Jekyll.
```

Prior to the markdown (e.g., `README.md`) being displayed, some [recursive pre-parsing](http://www.yaml.org/YAML_for_ruby.html) and [substitution](https://github.com/timcowlishaw/aho_corasick) would help eliminate some duplication within the document.

## The Output I Wanted

```
![Logo](images/logo.png)
Application
===
Application is almost as amazing as Jekyll.
![Screenshot](images/screenshot.png)
```

## The Output I Get

No substitution is preformed, so the `README.md` file is displayed as:

```
![Logo]($application.directory.images$/logo.png)
$application.title$
===
$application.description$
![Screenshot]($application.directory.images$/screenshot.png)
```

---

## See Also
Related information:

* https://hydepress.github.io/jekyll
* http://stackoverflow.com/a/32514256/59087
* https://jekyllrb.com/docs/variables/
* https://jekyllrb.com/docs/configuration/
* Issue #1312

## Additional Details
Using YAML as a bridge between documentation and applications is a slick way to avoid duplication. Since the YAML file is machine-readable, it would be trivial for an application to read its name from the same YAML source as the documentation. Changing the app name would be a simple matter of updating a single YAML file, which simultaneously updates all references in the documentation.

This could be an option passed into Jekyll to maintain backwards compatibility.

Using `_config.yaml` is insufficient here because of namespace clashes. There are a couple of options:

* Jekyll can read all the Markdown files alongside `_config.yaml` and pass them through a pre-processor; or
* `_config.yaml` can specify the pre-processor file(s) to use against all, or specific, Markdown files.

The first is easier, the second is more flexible.

**Comment by pathawks** [comment]
You can use Liquid for just this purpose :+1:

**Comment by quiltbag** [comment]
you might also wanna check out [jekyll collections](http://jekyllrb.com/docs/collections/), although what you want may be entirely possible just using the `config.yml`

**Comment by DaveJarvis** [comment]
@quiltbag - nice idea, but it requires a different namespace:

```
collections:
  my_collection:
    foo: bar
```

This would mean changing $application.title$ to $collections.my_collection.application.title$, and such a prefix wouldn't make sense in other contexts (external to Jekyll).

**Comment by pathawks** [comment]
It sounds the issue is more regarding the fundamentals of how Liquid works: what you are asking for is to define your own template language.

**Comment by DaveJarvis** [comment]
> what you are asking for is to define your own template language.

Nothing so complex, simply two related ideas. First, variable substitution for arbitrary definitions using a dot-separated notation and recursive interpolation. Second, the ability to set a prefix and suffix delimiter.

I've developed both of these in Java. The first is about [19 lines of code](https://bitbucket.org/djarvis/yamlp/src/master/src/main/java/com/whitemagicsoftware/yamlp/Main.java?fileviewer=file-view-default#Main.java-231). The second requires a kind of [variable decorator pattern](https://github.com/DaveJarvis/scrivenvar/tree/master/src/main/java/com/scrivenvar/decorators), which is also fairly trivial in terms of LoC (fewer than 50 lines).

Code that deals with variable substitution often hard-codes the variable delimiters in multiple places, which is a violation of DRY. Using a constant value for those variable delimiters is a better practice, but still violates DRY when those constants are referenced in multiple places, rather than being constructed dynamically using a factory pattern based on some arbitrary criteria (such as a file name extension).

**Comment by quiltbag** [comment]
@DaveJarvis this would still be more related to liquid than it would be related to jekyll

**Comment by DaveJarvis** [comment]
Question for Liquid team.

**Comment by DaveJarvis** [comment]
Here is the [response](https://github.com/Shopify/liquid/issues/844) from the Liquid team:

> I am not familiar with how Jekyll works but can you not already interpolate into markdown files? And does it not already provide a way to define variables from file?

> Liquid knows nothing about configuration files or anything of the like - it's a library that provides an API for interpolating the parameters to the render method into the template provided to the parse method. This repo contains the language implementation and not much more.

Thoughts?

**Comment by pathawks** [comment]
What you are really asking for is to be able to basically replace Liquid with your own template language.

Your **Reproduction Steps** have no connection to the way Liquid + Jekyll currently works.
