### ISSUE TITLE
Rouge seems not to be highlighting correctly

### ISSUE THREAD

**Issue by jedruniu** [jekyll/jekyll#5715]
- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [X] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

![image](https://cloud.githubusercontent.com/assets/14827572/21601742/b2dc21ee-d18d-11e6-9a49-ef52b3e147dc.png)
I am getting such highlight for 
such code 
`{% highlight ruby %} def foo puts 'foo' end {% endhighlight %}`
generated styles are:
`<figure class="highlight"><pre><code class="language-ruby" data-lang="ruby"><span class="k">def</span> <span class="nf">foo</span>
  <span class="nb">puts</span> <span class="s1">'foo'</span>
<span class="k">end</span></code></pre></figure>`
Which works on this page, which is strange 
<figure class="highlight"><pre><code class="language-ruby" data-lang="ruby"><span class="k">def</span> <span class="nf">foo</span>
  <span class="nb">puts</span> <span class="s1">'foo'</span>
<span class="k">end</span></code></pre></figure>

**Comment by pathawks** [comment]
I'm not sure I understand the problem, is it giving you incorrect HTML, or is your CSS not being applied correctly?

**Comment by jedruniu** [comment]
Actually I am not sure, looks like CSS is not applies correctly, but don't know why due to using only official themes. It can be seen on my github page

**Comment by pathawks** [comment]
The problem is that you don't have an appropriate stylesheet. Jekyll is applying the syntax highlighting correctly.

It looks like you are using [Jekyll-Bootstrap](https://github.com/plusjade/jekyll-bootstrap). Perhaps you could check plusjade/jekyll-bootstrap#313
