### ISSUE TITLE
Variables inside variables not possible?

### ISSUE THREAD

**Issue by IdanAdar** [jekyll/jekyll#5716]
Jekyll 3.3.1
We have a plug-in that generates an excerpt of Pages:

```
Jekyll::Hooks.register :pages, :post_init do |page|
  # Set excerpt for pages if not specified in front matter
  page.data['excerpt'] ||= Jekyll::Excerpt.new(page).content
end
```

This excerpt is used later on in HTML:

```
<meta name="description" content="{{ page.excerpt | markdownify | strip_html | strip_newlines | strip | truncatewords: 20}}">
```

It all works fine, except when the excerpt contains a variable, in which case the variable is not rendered:

```
<meta name="description" content="Overview{{ site.data.keys.product_full }} provides several ways to administer {{ site.data.keys.product_adj }} applications in development or in production. {{ site.data.keys.mf_console }}...">
```

Any ideas on how to get those variables to render? Could this be a bug?

**Comment by pathawks** [comment]
Is your excerpt provided in the pages YAML header, or is it coming from somewhere else?

**Comment by nasht00** [comment]
@pathawks as you can see from the Plugin snippet, it is generated by the plugin, taking from the content of the page:

`page.data['excerpt'] ||= Jekyll::Excerpt.new(page).content`

We're using the pre-existing `Jekyll::Excerpt` class to do the work.

**Comment by parkr** [comment]
Calling `.content` won't convert that Liquid, it just gives it to you as plain text which Liquid then chokes on. Simply don't call `.content` and try again.

Note that [internal use of this simply does Jekyll::Excerpt.new(self) and does not call `.content`](https://github.com/jekyll/jekyll/blob/98e19c3cf5122582a8d2b5ecaad805a7902f2e53/lib/jekyll/document.rb#L486).

**Comment by nasht00** [comment]
`'highlight' tag was never closed`

Just a hunch: Maybe excerpt is cutting part of the page (as it should), but it cuts it in the middle of a `highlight` tag?

Is the excerpt cut before processing liquid tags such as `highlight`? That could be a problem ...
