### ISSUE TITLE
hash[list[index]] syntax not supported

### ISSUE THREAD

**Issue by wfjm** [jekyll/jekyll#5717]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
---

I have a hash, and I have a list of keys. Expressions like

    hash[list[index]]

are accepted by the parser (so no error when pages are generated), but the result is always an empty string. Of course one can work around with

    {% assign key = list[index] %]
   hash[key]

imho the parser should either reject such expressions when they are not supported, or handle them properly.

A reproducer is on gh-pages, [see results](https://wfjm.github.io/tests/jekyll_nested_index.html) and [see source](https://github.com/wfjm/wfjm.github.io/blob/master/tests/jekyll_nested_index.html).

## Proviso
Whether this is considered as a bug or a feature request only the jekyll maintainers can decide

**Comment by quiltbag** [comment]
doesn't look like a similar issue has been reported on the liquid issue tracker

**Comment by pathawks** [comment]
@quiltbag What I mean is that it seems this should be handled by Liquid rather than Jekyll.

**Comment by quiltbag** [comment]
@pathawks i absolutely agree, i just thought there was a possibility that this issue might have occurred before

**Comment by parkr** [comment]
Yeah, Liquid's `Expression.parse` should either document that it doesn't do this and why it chose not to, or support for this should be added.
