### ISSUE TITLE
absolute_url should complain if URL is not absolute

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#5718]
If `site.url` == `example.org`, then `{{ "/" | absolute_url }}` will return `example.org/`.

If the current page (`https://example.org/about/`) includes a link to the above URL, visiting that link will direct the browser to `https://example.org/about/example.org/`.

This is obviously not the intended behavior.

Now that **jekyll-sitemap** and **jekyll-feed** are relying on these filters, a `site.url` that does not contain a protocol can bork a site's entire sitemap or feed.

I don't know if this is best fixed with `jekyll doctor` or by complaining at build time.

**Comment by parkr** [comment]
Duplicate of #5788?

**Comment by pathawks** [comment]
> Duplicate of #5788?

No. Kind of the opposite.

In _this_ case, if `site.url` is not absolute, then the `absolute_url` filter will never work: it will never generate an absolute URL.

**Comment by ashmaroli** [comment]
@pathawks the PR linked to this ticket has been merged. Is this still an issue?

**Comment by pathawks** [comment]
@ashmaroli Good catch :+1:
