### ISSUE TITLE
Could not find a valid gem 'jekyll'

### ISSUE THREAD

**Issue by yufang93** [jekyll/jekyll#5727]
when i run "gem install jekyll",i get :
ERROR:  Could not find a valid gem 'jekyll' (>= 0), here is why:
 Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)

**Comment by quiltbag** [comment]
try running `gem install jekyll -v 3.3.1`?

**Comment by yufang93** [comment]
thanks anyway .i have resolve it.
because i am in china,so i have to use https://ruby.taobao.org/  instead ,but not  https://rubygems.org/
