### ISSUE TITLE
Allow parent directory as safe-include path for symlinks in safe mode

### ISSUE THREAD

**Issue by gsnedders** [jekyll/jekyll#5728]
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I had an error on GitHub Pages, and I have reproduced it locally.

## My Reproduction Steps

Now that GitHub Pages allows sites to be served from the /docs/ directory of the master branch, it would be nice to be able to safely include files from *anywhere* in the master branch into Jekyll: i.e., a symlink from /docs/foo to /bar should be allowed as it is within the repository. (It also shows up that the Github Pages error isn't quite accurate now, as such a symlink causes a claim that it "targets a file which does not exist within your site's repository".)

As such, my guess at the best solution to this would be to have a build command option to give a "safe include directory"—we wouldn't want this in the config file because then the user has control over it—with the requirement that it must be a parent directory of the site source directory (or the site source directory itself).

I have two reasons to want to be able to do this: one is to be able to include the /README.md into the documentation, and the other is to include documentation from submodules into our docs without having to have the same repository checked out as a submodule in two locations (and trying to guarantee they stick to having the same revision checked out in both places).

## The Output I Wanted

It to successfully build with the symlink allowed.

/cc @jekyll/core

**Comment by gsnedders** [comment]
FWIW: I'm happy to spend some time implementing this if there's any chance of such a feature being accepted.

**Comment by parkr** [comment]
> my guess at the best solution to this would be to have a build command option to give a "safe include directory"—we wouldn't want this in the config file because then the user has control over it—with the requirement that it must be a parent directory of the site source directory (or the site source directory itself).

We would want this option, yes (like "what is the top-most directory I can look at?"). It can be in the config file because GitHub Pages just overrides this.

I'd be 👍 on adding this feature. Please issue a PR!

**Comment by virtuald** [comment]
So... did anyone implement this? I use symlinks for development purposes also, and jekyll previously used to allow pointing outside of the tree when safe mode was turned off.

**Comment by gsnedders** [comment]
@virtuald I didn't, in the end.

**Comment by guidobouman** [comment]
@parkr Did this ever land? I'd love to use this in a project that uses the `docs/` folder to publish the documentation on an open source javascript library. The final build in the `build/` folder is a file I would love to symlink so I don't require it to be in my repo twice.
