### ISSUE TITLE
GCC and Make are needed for Ubuntu installation.

### ISSUE THREAD

**Issue by seltzy** [jekyll/jekyll#5730]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I was trying to install.

## My Reproduction Steps

I followed the basic installation instructions to the letter, but as administrator, on the latest version of Ubuntu (16.04).

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install ruby
sudo gem update
sudo gem install jekyll
```

Here's where things went wrong during `sudo gem install jekyll`:

```
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.14/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20170107-2494-1m1noxn.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ffi-1.9.14 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.14/gem_make.out
```

It was because `gcc` was not installed. I've also found that some people needed `make`. Please add that to the installation requirements. I also installed `ruby-dev` to be sure. Thanks. :)

**Comment by DirtyF** [comment]
@jekyll/documentation Does someone under GNU/Linux care to submit a PR?

**Comment by zdroid** [comment]
I have both GCC and Make already installed and required for packages on my system, so I don't want to experiment with them removed. However, it seems legit that you need them to finish the installation. I've sent the PR.

**Comment by michaelwsherman** [comment]
Hi all. I know this is closed but I think you also need `build-essential` as a dependency along with `make` and `gcc`. 

I just ran into this problem myself and still got an error after `apt-get install make` and `apt-get install gcc`. Running `apt-get install build-essential` fixed the error and I only then able to successfully run `gem install jekyll` without the "Failed to build gem native extension" error. 

Thanks.
