### ISSUE TITLE
Remove requirements for Jekyll 2

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#5741]
http://jekyllrb.com/docs/installation/ still mentions Jekyll 2 dependencies — an old Ruby version, NodeJS and Python. I don't know how many people would like to install Jekyll 2 today, version 3 was published on October 27th 2015, maybe it's time to remove those instructions?

/cc @jekyll/core @jekyll/documentation

**Comment by parkr** [comment]
Let's keep them for now – I don't think they really cause a lot of confusion. Correct me if someone tells you otherwise! We can do a better job of isolating the Jekyll 2 docs, but I think we should keep them.
