### ISSUE TITLE
Liquid 4.0.0

### ISSUE THREAD

**Issue by JamesDrummond** [jekyll/jekyll#5749]
I upgraded liquid to 4.0.0 and liquid-c to 4.0.0.rc1 using jekyll docker image version 3.3.1 to get feature https://github.com/Shopify/liquid/issues/162 . However the markdown code blocks do not seem to be formatting correctly. Inspecting the html code produce the code blocks seem to be missing `<pre class="highlight"><code>` child element to highlighter-rouge parent class.

**Comment by DirtyF** [comment]
We're currently testing Liquid 4, see #4362
