### ISSUE TITLE
Trying to install jekyll and it says Configuration File: none

### ISSUE THREAD

**Issue by EACallahan** [jekyll/jekyll#5757]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

 I am trying to download jekyll and begin to use it to create a blog. I have been following this guide (http://www.hongkiat.com/blog/blog-with-jekyll/). When I typed $ jekyll serve into the terminal, I got
   
Elizabeths-MacBook-Air:~ Liz$ jekyll serve
    Configuration file: none
    Configuration file: none
            Source: /Users/Liz
       Destination: /Users/Liz/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.3.1 | Error:  Operation not supported on socket @ rb_sysopen - /Users/Liz/Library/Application Support/Google/Chrome/App Shim Socket

I am not sure what this error means or how to fix it. Can anyone walk me through how to fix this error? Thank you

**Comment by quiltbag** [comment]
can you try running `sudo jekyll serve`?

**Comment by pathawks** [comment]
Not sure if it is the source of the problem, but you seem to be running `jekyll serve` from within your home directory. Is this intentional?
Jekyll is meant to be run inside the directory of your Jekyll site; the directory created by `jekyll new`

/cc: @jekyll/mac

**Comment by ashmaroli** [comment]
@EACallahan the first step to create a Jekyll Blog is by running `jekyll new`
e.g. `$ jekyll new liz_writes`

the next step is to navigate to the new blog within command-line:
`$ cd liz_writes`

**then** start a jekyll server.
`$ jekyll serve`

--
Its better to run jekyll commands after `jekyll new` using bundler.
so install bundler if you dont have it already:
`$ gem install bundler` or `$ sudo gem install bundler`

then start a jekyll server with bundler:
`$ bundle exec jekyll serve`

**Comment by EACallahan** [comment]
Thank you so much! The steps I followed were
$ sudo gem install bundler
$ jekyll new liz_writes
$cd liz_writes
$bundle exec jekyll serve
