### ISSUE TITLE
Drop jekyll-watch dependency

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#5762]
Installing Jekyll can be a very frustrating experience for new users who are not Ruby developers.

One of the most common issues when trying to install Jekyll is that **ffi** fails to install, which halts the whole process. **ffi** builds native extensions, which requires the user to have Ruby development headers installed, and these often do not come with a default Ruby installation.

**ffi** is required by (a dependency of) **jekyll-watch** and nothing else. If we could remove [**jekyll-watch** from the `gemspec`](https://github.com/jekyll/jekyll/blob/v3.3.1/jekyll.gemspec#L39), users could _at least_ get Jekyll installed successfully.

Internally, we could `require_with_graceful_fail` **jekyll-watch**, so that the first time a user tries to run `jekyll serve`, we could give them a message letting them know "Hey, you probably need to jump through these hoops to get this feature to work. Here is a link to our troubleshooting page"

I am sure there would be some confusion when users run `jekyll serve` and do not see the error message and cannot figure out why their site isn't reloading. I am (fairly) sure that this change would need to wait until Jekyll 4.0, as it would require users to edit their `Gemfile`s and whatnot.
I really do think that it would be worth it, however, so that at least a new user can run `jekyll new mysite` without several lines of cryptic error messages.

/cc: @BlueberryFoxtrot

**Comment by parkr** [comment]
> Hey, you probably need to jump through these hoops to get this feature to work. Here is a link to our troubleshooting page

This is the reason I haven't been keen on removing this dependency. You shouldn't have to jump through hoops to get `jekyll serve` to work. I think `jekyll serve` with auto-regeneration is core enough to the expected jekyll functionality that it should work on the first installation. Most users are installing Jekyll to develop their websites.

I'd be down to look for an alternative to Listen, which is what triggers that dependency I think.

**Comment by pathawks** [comment]
> I'd be down to look for an alternative to Listen, which is what triggers that dependency I think.

Yup.

> You shouldn't have to jump through hoops to get jekyll serve to work.

The thing is that the hoops are already there. Only difference is that if Jekyll were actually installed, we could maybe give a human readable explanation for what is happening, instead of the current error message which is intended for developers rather than users.

**Comment by envygeeks** [comment]
Just chiming in to say that I've never found a valid replacement, unless one propped up in the last year.

**Comment by pathawks** [comment]
ffi/ffi#552

**Comment by parkr** [comment]
I would be very weary of removing `jekyll-watch` because auto-watching has been automatically bundled with the project since like v0.5 in 2009. I don't think we should remove it. I would also like better error messages – perhaps we can submit a patch to give the current error message a touch-up?

Closing this as `wont-fix` on our end.
