### ISSUE TITLE
main.css reverts back when I do jekyll serve

### ISSUE THREAD

**Issue by Beasted** [jekyll/jekyll#5763]
So I am trying to add the monokai theme for syntax highlighting but when I do jekyll after adding all the highlight code for monokai theme it just reverts back to normal. I spent so much time looking at different people websites but they have folders like _layout and such while I only have two folder _posts and _site. Also the main.css is different compared to other people. This is so weird I followed every step! :(

**Comment by ashmaroli** [comment]
couple of questions: 
- how did you add the `monokai` theme highlighting? 
- where did you add the new CSS?

**Comment by Beasted** [comment]
@ashmaroli I downloaded monokai.css then I went to _site folder then assets and pasted it there. That didn't work so I copied all the code from monokai.css and replaced the highlight code from main.css but when I did jekyll serve it would just revert back. Other people had it replaced as well!

**Comment by ashmaroli** [comment]
okay..
for starters, we have a dedicated forum at http://talk.jekyllrb.com for support.
Please reopen this ticket there and I'll get back to you.
Thanks.

**Comment by Beasted** [comment]
@ashmaroli yea I already have one there as well : 

https://talk.jekyllrb.com/t/how-do-i-apply-the-monokai-theme-to-syntax-highlight-jekyll-3-3-1/3569

**Comment by pathawks** [comment]
Thanks for picking this up @ashmaroli :+1:
