### ISSUE TITLE
HTML table rendering in Github pages but not rendering on output

### ISSUE THREAD

**Issue by xameeramir** [jekyll/jekyll#5770]
In my [page's preview](https://github.com/xameeramir/xameeramir.github.io/blob/master/_posts/2017-1-16-ienumerable-vs-iqueryable.md), the table is perfectly rendering.

However, in the [resulting page](http://xameeramir.github.io/ienumerable-vs-iqueryable/), it doesn't.

What is the problem here?

**Comment by quiltbag** [comment]
@xameeramir hi, it would be nice if you could ask this question on https://talk.jekyllrb.com/ since it does not directly relate to jekyll's source code and the forum allows for more structured discussion. thank you!
