### ISSUE TITLE
github page build faild if has {%%} inside code block

### ISSUE THREAD

**Issue by xing393939** [jekyll/jekyll#5785]
- [ ] I had an error on GitHub Pages and I did not test it locally.

## My Reproduction Steps

 1, my `_config.yml` is like this
```
markdown: kramdown
highlighter: rouge
```
2, and my markdown page has code block like this
```
~~~~~~~~
public function boot()
{
    \Blade::setContentTags('{%', '%}');
    \Blade::setEscapedContentTags('{%%', '%%}');
}
~~~~~~~~
```
3, then github page build faild, I remove this code block, then it build success

**Comment by pathawks** [comment]
Unfortunately, this is because `{%  %}` looks like a Liquid tag. You can explicitly tell Liquid to ignore these by surrounding your code block with the `{% raw %}…{% endraw %}` tags :+1:
