### ISSUE TITLE
Need feedback

### ISSUE THREAD

**Issue by bopoh13** [jekyll/jekyll#5786]
Hi!
Do you plan to do in the local engine _feedback form_ as minimalist sites of the last century?

I'd like to see the feedback function of the box. For GitHub it's not a big load, yep?

**Comment by DirtyF** [comment]
Hi, this repo is intended for Jekyll bugs only and your message does not fit in this category. You can always contact GitHub at https://github.com/contact. Cheers.

**Comment by bopoh13** [comment]
Thank you. I was given [a link](https://github.com/eduardoboucas/staticman).
