### ISSUE TITLE
default github pages gem include throws dependency error

### ISSUE THREAD

**Issue by pnn** [jekyll/jekyll#5787]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I was trying to install.

when uncommenting the default line in the `Gemfile` where github-pages is included, bundler resolved the missing explicit version statement as version `1`, which requires jekyll 1.x.x and therefore errors

this should be fixed by adding a version statement to the default gemfile include

**Comment by pathawks** [comment]
github/pages-gem#351

**Comment by pnn** [comment]
this still happens on `bundler 1.13.7` though :o

**Comment by DirtyF** [comment]
@pnn It will be fixed with 1.14 but we don't know when it will be released.

For now pages-gem README has [specific instructions on gem install](https://github.com/github/pages-gem#usage).

**Comment by DirtyF** [comment]
bundler 1.14 is out and fixes this issue 🎉

**Comment by pnn** [comment]
wooo
