### ISSUE TITLE
absolute_url mangles URL if called twice

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#5788]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

```text
{{ '/' | absolute_url | absolute_url }}
```

Yields `http://example.com/http://example.com/`

## The Output I Wanted

`http://example.com/`

The filter should check to see if the URL is already absolute, and leave it alone if it is.

/cc @jekyll/core

**Comment by jwillmer** [comment]
Maybe also related to this: https://github.com/github/pages-gem/issues/419

**Comment by pathawks** [comment]
@jeillmer I don't think you were using the `absolute_url` filter.

**Comment by jwillmer** [comment]
No, I did not but I also get the url twice in a row. Additionally I have not changed anything in my blog and now it is broken. That is why I think it must be a jekyll bug (new feature?)
