### ISSUE TITLE
Should relative_url replace `/index.html` with `/`?

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#5790]
Many templates that use URL filters (either `relative_url` or `absolute_url`) end up modifying the output to replace `/index.html` with `/`

Could we absorb this complexity directly into the filters themselves?

To do so would only require trivial changes to the code. My only concern would be if there is _any_ circumstance where this substitution would be undesirable.

**Comment by parkr** [comment]
> My only concern would be if there is any  circumstance where this substitution would be undesirable.

We'd get someone who says their server from 1992 doesn't support index.html as the root and that we broke their site's urls!

But really, we'd probably be fine. I would just leave it at `index.html` and explicitly *never* remove `index.htm`, `index.xhtml`, etc. `.html` is the only extension we can do this for reliably.

**Comment by parkr** [comment]
Let's let the user decide about this.
