### ISSUE TITLE
[docs] Separate `plugins` and `available plugins` into two pages

### ISSUE THREAD

**Issue by crispgm** [jekyll/jekyll#5794]
The current documentation for plugins is so long that we cannot easily get to `available plugins` directly. And the page is also over-length and becomes longer, due to user contributions to available plugins.

How about separate `plugins` and `available plugins` into two pages? The first one is to describe the installation and development guide of plugins. The second one is a curated list of available plugins, which is arranged by classification.

If @jekyll/documentation agreed, I would PR for it later.

**Comment by pathawks** [comment]
> The second one is a curated list of available plugins, which is arranged by classification.

Hopefully we can break that into a separate site entirely.

#5771

**Comment by parkr** [comment]
Yep! Keep an 👁 on https://github.com/jekyll/plugins

**Comment by Strangehill** [comment]
While moving themes and plugins to their own directory is the way to go, I think it's very valuable to also have a hand-picked listing that meets a few criteria:
- no more than a dozen plugin/theme gems (to make sure they're maintained and not 404)
- broad appeal
- simplicity. Either it's simple to explain, or simple to demonstrate on the page.
- they're the kind of projects we want to see more of (I have trouble finding gem based themes that 'just work' --- whether as described by the jekyll docs or their own docs)

I'd say jekyll-gist could find a place here. 

> separate... two pages?
> first one... installation and development guide of plugins... 

That's the easier page, it's kinda already there.

> ...second one is a curated list of available plugins, which is arranged by classification.

A curated second page, and a separate site, where classification can help with search and sorting results, maybe?
