### ISSUE TITLE
Problem with GitHub repo for site when `serve -w` regenerates a page.

### ISSUE THREAD

**Issue by hartzell** [jekyll/jekyll#5800]
I am having trouble using `serve -w` to serve a site based on [Tom Johnson's Jekyll Documentation Theme](https://github.com/tomjohnson1492/documentation-theme-jekyll).

`jekyll build` works.  `jekyll serve -w` generates the site correctly the first time.  **But** if I update some content (e.g. `touch index.md`) then regenerating the site fails over some issue with the GitHub repo.  The exact failure varies with whether I'm using his site on GitHub.com or a copy on our internal GitHub Enterprise deployment.

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [x] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build. (NB: **serve**)
- [ ] It was another bug.

## My Reproduction Steps

Here's the sequence of operations I perform.

There is one missing bit in the steps below.  I wait until the server prints the message:

```
  Server running... press ctrl-c to stop.
```

and then, in another window, I `touch index.md`.  That is what triggers the regeneration and the error.

```
hartzelg-UXG8WL:bug hartzelg$ git clone https://github.com/tomjohnson1492/documentation-theme-jekyll
Cloning into 'documentation-theme-jekyll'...
remote: Counting objects: 3547, done.
remote: Total 3547 (delta 0), reused 0 (delta 0), pack-reused 3546
Receiving objects: 100% (3547/3547), 14.28 MiB | 232.00 KiB/s, done.
Resolving deltas: 100% (2299/2299), done.
hartzelg-UXG8WL:bug hartzelg$ cd documentation-theme-jekyll/
hartzelg-UXG8WL:documentation-theme-jekyll hartzelg$ bundle exec jekyll --version
jekyll 3.3.1
hartzelg-UXG8WL:documentation-theme-jekyll hartzelg$ bundle exec jekyll serve -w
Configuration file: /Users/hartzelg/tmp/bug/documentation-theme-jekyll/_config.yml
Configuration file: /Users/hartzelg/tmp/bug/documentation-theme-jekyll/_config.yml
            Source: /Users/hartzelg/tmp/bug/documentation-theme-jekyll
       Destination: /Users/hartzelg/tmp/bug/documentation-theme-jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 3.672 seconds.
 Auto-regeneration: enabled for '/Users/hartzelg/tmp/bug/documentation-theme-jekyll'
Configuration file: /Users/hartzelg/tmp/bug/documentation-theme-jekyll/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2017-01-20 13:34:30    GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: GET https://api.github.com/repos/tomjohnson1492/documentation-theme-jekyll/pages: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/tomjohnson1492/documentation-theme-jekyll/pages: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/tomjohnson1492/documentation-theme-jekyll/contributors?per_page=100: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/tomjohnson1492/documentation-theme-jekyll/contributors?per_page=100: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/tomjohnson1492/documentation-theme-jekyll: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/tomjohnson1492/documentation-theme-jekyll: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/orgs/tomjohnson1492: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/orgs/tomjohnson1492: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/users/tomjohnson1492/repos?per_page=100&type=public: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/users/tomjohnson1492/repos?per_page=100&type=public: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/tomjohnson1492/documentation-theme-jekyll/releases?per_page=100: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/tomjohnson1492/documentation-theme-jekyll/releases?per_page=100: 403 - API rate limit exceeded for 72.34.128.250. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
...done in 9.053986 seconds.
```

I have the same/similar problem using a copy of Tom's repository on my local GitHub Enterprise deployment.

```
hartzelg-UXG8WL:tmp hartzelg$ git clone http://rpbuvgithub.ple.roche.com/hartzelg/demo
Cloning into 'demo'...
remote: Counting objects: 3555, done.
remote: Compressing objects: 100% (1226/1226), done.
remote: Total 3555 (delta 2308), reused 3540 (delta 2299), pack-reused 0
Receiving objects: 100% (3555/3555), 14.28 MiB | 2.14 MiB/s, done.
Resolving deltas: 100% (2308/2308), done.
hartzelg-UXG8WL:tmp hartzelg$ cd demo
hartzelg-UXG8WL:demo hartzelg$ bundle exec jekyll --version
jekyll 3.3.1
hartzelg-UXG8WL:demo hartzelg$ bundle exec jekyll serve -w
Configuration file: /Users/hartzelg/tmp/demo/_config.yml
Configuration file: /Users/hartzelg/tmp/demo/_config.yml
            Source: /Users/hartzelg/tmp/demo
       Destination: /Users/hartzelg/tmp/demo/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 3.839 seconds.
 Auto-regeneration: enabled for '/Users/hartzelg/tmp/demo'
Configuration file: /Users/hartzelg/tmp/demo/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2017-01-20 13:39:48 ...error:
             Error: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.
             Error: Run jekyll build --trace for more information.
^Chartzelg-UXG8WL:demo hartzelg$ git remote -v
origin	http://rpbuvgithub.ple.roche.com/hartzelg/demo (fetch)
origin	http://rpbuvgithub.ple.roche.com/hartzelg/demo (push)
hartzelg-UXG8WL:demo hartzelg$
```

I also have the problem using a Docker container built today using Tom's `Dockerfile`.

Thanks for any help!

## The Output I Wanted

I expect the regeneration to succeed (as the build did).

/cc @jekyll/build

**Comment by parkr** [comment]
[This is how we determine the name with owner (`nwo`) for your repository](https://github.com/jekyll/github-metadata/blob/5226ce60830a7ec0fec10513e1e0759e67d46563/lib/jekyll-github-metadata/metadata_drop.rb#L127-L129). It's in the jekyll-github-metadata plugin.

I'm not sure where this theme you're using utilizes the `site.github` namespace, but the fix here is to add your repository name to your `_config.yml`:

```yaml
repository: hartzell/my-great-site
```

This is the name with owner (`nwo`) for your repository on GitHub.com or your GitHub Enterprise installation.

**Comment by hartzell** [comment]
I see the same problem when I add a `repository` entry to the config file.

```
diff --git a/_config.yml b/_config.yml
index 2ca2843..f9df132 100644
--- a/_config.yml
+++ b/_config.yml
@@ -2,6 +2,8 @@
 output: web
 # this property is useful for conditional filtering of content that is separate from the PDF.

+repository: hartzelg/demo
+
 topnav_title: RSS Computing
 # this appears on the top navigation bar next to the home button
```

I also see the problem when I try to set it via an environment variable, e.g

    env PAGES_REPO_NWO=hartzelg/demo bundle exec jekyll serve -w

**Comment by hartzell** [comment]
And on a related note, given that there **is** a valid git remote named `origin`, it seems as if it should not be failing.

**Comment by hartzell** [comment]
See also [#45 here](https://github.com/jekyll/github-metadata/pull/45).

**Comment by hartzell** [comment]
@parkr -- The thing that led me to file a bug here is that this works correctly when I `build` or when I `serve` or the first time `serve -w` generates the file, but  fails the second (and beyond) times that `serve -w` regenerates the file.

**Comment by hartzell** [comment]
Digging into this more, I think that are [at least] two things going on.

1. As I mentioned above, it seems like the github-metadata stuff only fires when the page is *regenerated*.  That's surprising and might be a jekyll thing.

2. There seem to be a variety of sticky bits using the github-metadata gem with GitHub Enterprise.  I can use the Mac App Little Snitch to watch network traffic as Regeneration happens and it *always* hits `api.github.com`, even when the `origin` is a local GitHub Enterprise deployment.  It's not obvious [how to configure the calls into the Octokit library][foo] to use an Enterprise endpoint and there's [a stale bug over in the github-metadata repo][stale] that talks about it a bit.  I'll follow up more in that repo.

[foo]: https://github.com/jekyll/github-metadata/blob/eacd93bd9e499bc00115563406b7a9e772c2bbd4/lib/jekyll-github-metadata/client.rb#L32-L38
[stale]: https://github.com/jekyll/github-metadata/issues/48

**Comment by tomjohnson1492** [comment]
The error is generated from the github-pages gem in the Gemfile. I followed the instructions in this [Knight Codes](http://knightcodes.com/miscellaneous/2016/09/13/fix-github-metadata-error.html) post to fix it. 

I also added some Mac OS X specific instructions to the Jekyll theme on how to fix this error. See [Resolve "No Github API authentication" errors"](http://idratherbewriting.com/documentation-theme-jekyll/mydoc_install_jekyll_on_mac.html#githuberror). 

@hartzell Can you follow these instructions and confirm that the resolution steps fix the error?

I'm not sure if the error occurs because of my own Mac's setup and authentication configuration, or something else.
