### ISSUE TITLE
Jekyll fails to build sites with `permalink`s that contain only digits

### ISSUE THREAD

**Issue by AJMansfield** [jekyll/jekyll#5804]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [x] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Created this repository and made this commit: https://github.com/AJMansfield/jekyll-test/commit/7cbbc83a73ff5d0e424123548a0eea4b9b8370e2

The site builds fine before the commit, and fails to build afterwards.

This may be related to #5603.

## The Output I Wanted

The actual repository I discovered this issue in is https://github.com/AJMansfield/scp-rec.

I want to be able to navigate to `ajmansfield.github.io/scp-rec/728` and be able to view the content described by `728.md`. It is unfortunately not possible for me to just put that content at some other URL because of how this site has to inter-operate with another site.

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by parkr** [comment]
This is indeed a bug. 

```text
      Generating...
bundler: failed to load command: /Users/parkr/jekyll/jekyll/exe/jekyll (/Users/parkr/jekyll/jekyll/exe/jekyll)
NoMethodError: undefined method `empty?' for 123:Fixnum
  /Users/parkr/jekyll/jekyll/lib/jekyll/convertible.rb:72:in `validate_permalink!'
  /Users/parkr/jekyll/jekyll/lib/jekyll/convertible.rb:58:in `read_yaml'
  /Users/parkr/jekyll/jekyll/lib/jekyll/page.rb:50:in `initialize'
  /Users/parkr/jekyll/jekyll/lib/jekyll/readers/page_reader.rb:18:in `new'
  /Users/parkr/jekyll/jekyll/lib/jekyll/readers/page_reader.rb:18:in `block in read'
  /Users/parkr/jekyll/jekyll/lib/jekyll/readers/page_reader.rb:17:in `map'
  /Users/parkr/jekyll/jekyll/lib/jekyll/readers/page_reader.rb:17:in `read'
  /Users/parkr/jekyll/jekyll/lib/jekyll/reader.rb:91:in `retrieve_pages'
  /Users/parkr/jekyll/jekyll/lib/jekyll/reader.rb:51:in `read_directories'
  /Users/parkr/jekyll/jekyll/lib/jekyll/reader.rb:17:in `read'
  /Users/parkr/jekyll/jekyll/lib/jekyll/site.rb:163:in `read'
  /Users/parkr/jekyll/jekyll/lib/jekyll/site.rb:67:in `process'
```

/cc @jekyll/build
