### ISSUE TITLE
REQ: Expand http://jekyll.tips/jekyll-casts/output-json/

### ISSUE THREAD

**Issue by swizca** [jekyll/jekyll#5807]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] This is a feature request.
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

Could [Output JSON in Jekyll](http://jekyll.tips/jekyll-casts/output-json/) be expanded please?

Although it is clear how variables can have or get JSON, it is not at all clear as to how to get that data out in liquid.

There is a mention of *javacript*, but ... wait ... what!?! ... *javascript*? This is jekyll, kramdown, liquid ... for one's static website ... no *javascript* here!

Which is only to say, (almost?) never do these excellent documentation pages mention javascript.

So, could pointers (links) towards javascript use in jekyll be added?

And, in particular, on this page, could an example of how to include / refer to the JSONified variables, be added?

Thanks for listening.

**Comment by pathawks** [comment]
I don't think we have anything to do with http://jekyll.tips

This is probably not the right place for that request.

**Comment by DirtyF** [comment]
@swizca the example for working with data files is also valid with JSON files : https://jekyllrb.com/docs/datafiles/

We use YAML because it's a bit more readable, but the logic is the same.

**Comment by swizca** [comment]
@pathawks , I take your point (I think I got here because the http://jekyll.tips/jekyll-casts/data-files/ links to https://jekyllrb.com/docs/datafiles/ which links to here), but do please take my point about documentation.

@DirtyF thank you for the link - it demonstrates the same issue. (You have made the assumption that the data is coming from a file.)

However one got to the data, say {% assign colors = "{ one: red, two: green, three: blue }" | jsonify %}, even https://jekyllrb.com/docs/datafiles/ doesn't make clear how to then access the elements of colors.

Granted, I've mixed things up as I work through grokking the ecosystem, but please take my intent.

**Comment by DirtyF** [comment]
@swizca Documentation only covers core features, but you might be interested in things like https://github.com/18F/jekyll-get/ to work with APIs.

**Comment by pathawks** [comment]
> Which is only to say, (almost?) never do these excellent documentation pages mention javascript.
> 
> So, could pointers (links) towards javascript use in jekyll be added?

Jekyll just outputs static files. If you want Jekyll to output JS files for you, that is totally fine, but it doesn't require any special knowledge. The pieces of Jekyll should be orthogonal enough that once you know how to use templates to output HTML, outputting JavaScript or anything else is just done the same way.

> However one got to the data, say {% assign colors = "{ one: red, two: green, three: blue }" | jsonify %}, even https://jekyllrb.com/docs/datafiles/ doesn't make clear how to then access the elements of colors.

You are misunderstanding the `jsonify` filter. It will output data _as_ JSON, not convert JSON _into_ data. Your example will simply output the string `"{ one: red, two: green, three: blue }"`

> Granted, I've mixed things up as I work through grokking the ecosystem, but please take my intent.

I am trying to understand your intent, but it would help me if you were a bit more explicit. What action needs to be taken? You have requested changes be made to a website that we don't control. That is not possible.

It seems like https://talk.jekyllrb.com is the best place for this discussion, but I am not closing this issue yet because it does seem like I may be missing something regarding your intent.

**Comment by swizca** [comment]
> Jekyll just outputs static files.

I don't dispute that.

I have an assumption, I guess: The reader of these web pages is someone who has heard of Jekyll, and is trying to build something. The pages are aimed at audiences that are unfamiliar with just about everything. This is a good / wonderful thing. (Thank goodness for them, even, although I am technically savvy, I am not technically savvy, or wasn't, on Jekyll ... and, it appears, many other things. Such as Ruby.)

[I do not want to get into the non-techsavvy debate here. The only assumption the pages seem to make is that the reader is not computer averse. Full stop.]

So, as far as javacript goes, here, for the purposes of this message thread ... javascript is mentioned almost nowhere else on the pages. Here, a bit of javascript is shown wrt accessing the json data. (But, per below, missing is the bits of javascript by which one accesses the data.)

> You are misunderstanding the jsonify filter. It will output data as JSON, not convert JSON into data. Your example will simply output the string "{ one: red, two: green, three: blue }"

No, I am not misunderstanding the filter, I am mis-writing the explanation herein.

Just take it as a given: "{ one: red, two: green, three: blue }" is in *some* liquid variable.

How to access the individual pieces of the variable (as data elements)?

> Could Output JSON in Jekyll be expanded please?

> Although it is clear how variables can have or get JSON, it is not at all clear as to how to get that data out in liquid.

**Comment by pathawks** [comment]
> Just take it as a given: "{ one: red, two: green, three: blue }" is in some liquid variable.
> 
> How to access the individual pieces of the variable (as data elements)?

This cannot be done. As far as Liquid is concerned, it is a string. You could access it on the client side in JavaScript, but I don't think that's what you are asking.

**Comment by swizca** [comment]
> This cannot be done

Perfect, thank you. Can't do it. (Saying so on the page would be useful.)

Now, just to be complete ... the page noting the java script bits one needs to write into their layout.html page, or rather, link to a page where such is discussed, would be useful.

Thanks again.

**Comment by pathawks** [comment]
I see where you are coming from now :+1:

Yes, being able to slurp up JSON with Liquid and process it into a real data structure has been discussed before (as a feature addition for Liquid) but there isn't really a usecase for it in a _static_ site generator.

As far as using JSON on the client is concerned, do you have a specific question? JSON is common enough that a user probably either already understands how to use it, or can easily Google to find what they need.

**Comment by swizca** [comment]
> JSON is common enough that a user probably either already understands how to use it, or can easily Google to find what they need.

Not so.

One gets here (to Jekyll) because of a need to create some web content. And with only a modicum of digging, it's easy to drown in the slurping - and I'm a tech guy! (Just not a web tech guy.)

So I'm reading along chewing through things ... and suddenly hit ... javascript.

As said ...
> There is a mention of javacript, but ... wait ... what!?! ... javascript? This is jekyll, kramdown, liquid ... for one's static website ... no javascript here!

It's one thing to be able to scan JSON and have a reasonable sense of the data. It's another thing entirely to manipulate it. Never mind it's another thing to grok javascript within .html to access DOM (?) vars.

I don't dispute the ease of googling ... if one knows the terms to search on. (Or I wouldn't have started the issue.)

So, a pointer to a link that makes use of the JSON on the client side, in the doc, would be useful.

And ... given your messaging ... it occurs to me that the search stuff, a la http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/ must be using it ... so there's the example. I suppose.

'course ... that link leads me to http://jekyll.tips/jekyll-casts/output-json/ which is what brought me to this issue ... <sigh>

Read ... read ... read ... javascript in a .md with YAML Front Matter ...

> ... wait ... what!?! ... javascript? This is jekyll, kramdown, liquid ... for one's static website ... no javascript here!

So the use case is ... reading along ... read:
> <script>
>  var colors = {{ page.colors | jsonify }};
></script>
>Which generates a JSON array of colors.
>
> ...
> var colors = ["red","blue","green"];
> ...

and one intuitively wonders how to make use of the structures presented, in liquid / kramdown / jekyll, as that is why one would be reading the page in the first place. ( ... javascript ... wait ... what! )

So notes of:
- can't get there from here.
- nobody has thought of why you'd want to
- if you want to make use of the data (JSON) during client runtime, see <link>

would be useful.

Hmmm.

So here's the use case ... dump the jekyll data environment to JSON (for client runtime inspection?), for debugging when trying to figure out that slippery var name one can't remember where they put.

That's not even jscript, even. Export to .xml, open .xml in a browser (worst case).

(But given the current doc, and reference to jscript, completing the reference by including a link to making use of the examples presented, client side, would be useful.)
