### ISSUE TITLE
Slugify multi word category URL

### ISSUE THREAD

**Issue by yguezeldal** [jekyll/jekyll#5813]
- [x] I believe this to be a bug, not a question about using Jekyll. (nut sure)
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+

## The problem

Currently if I have a post with this category in front matter:

```
category: "Multi word category"
```

and the permalinks configured like this:

```
permalink: /:categories/:title/
```

the output looks like this in the `_site` folder:

```
multi word category/post-title/index.html
```

which is producing an ugly url for the post like this:

```
/multi%20word%20category/post-title/
```

It would be much better path when we could slugify multi word categories. Btw, it would be also more consistent with the multi word tags as they are slugifyed already.

**Comment by parkr** [comment]
> It would be much better path when we could slugify multi word categories.

We won't be able to do this, as it would break tons of pre-existing sites. I would recommend using slugified categories and using a data file or something to provide the "English" version conversion, e.g. `multi-word-category: "Multi Word Category"`.
