### ISSUE TITLE
Unable to perform case-insensitive sort on categories or tags

### ISSUE THREAD

**Issue by kimbaudi** [jekyll/jekyll#5816]
- [x] This is a feature request.

Currently, jekyll only sorts categories or tags in a case-sensitive way so that uppercase precedes lowercase.

```html
{% assign sorted_categories = site.categories | sort %}
{% for cat in sorted_categories %}
<h2>{{ cat[0] }}</h2>
{% endfor %}
```

<br>
<br>

So if I have the categories: `algorithm` `MathJax` and `Ruby`, it would be sorted as
1. `MathJax`
2. `Ruby`
3. `algorithm`

It would be nice to be able to sort without case sensitivity so that `algorithm` comes before `MathJax`.

<br>
<br>

Also, if I have the categories: `problem 1` `problem 2` and `problem 10`, it would be sorted as
1. `problem 1`
2. `problem 10`
3. `problem 2`

It would also be nice to be able to sort numbers naturally so that `problem 2` comes before `problem 10`.

**Comment by xHN35RQ** [comment]
until jekyll supports this natively, you can use this filter https://gist.github.com/264d28f2be337391312d6ffcdc39f824

**Comment by xHN35RQ** [comment]
Liquid provides `sort_natural` which should be what you're looking for: https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L142

Or you can use this filter https://gist.github.com/264d28f2be337391312d6ffcdc39f824

**Comment by kimbaudi** [comment]
I already tried `sort_natural` before I raised this issue and it doesn't work. As for the `sort_insensitive.rb`, how would I be able to use it? Where do I put `sort_insensitive.rb`? How do I call it?

I don't think there is support at this time for case-insensitive sort built into Jekyll. The only work-around is to either uppercase or lowercase the tags/categories in order to make string comparisons insensitive.

**Comment by pathawks** [comment]
> I already tried sort_natural before I raised this issue and it doesn't work.

Can you give a bit more detail? What version of Jekyll are you using?

It appears this feature already exists in Liquid, and it definitely belongs in Liquid rather than Jekyll.

**Comment by kimbaudi** [comment]
@pathawks - this is what I tried, but it didn't work

```
{% assign sorted_categories = site.categories | sort_natural %}
{% for cat in sorted_categories %}
<h2>{{ cat[0] }}</h2>
{% endfor %}
```
I am using Jekyll version 3.3.1

**Comment by pathawks** [comment]
I guess we haven't actually released a version of Jekyll that supports Liquid 4 yet.

Coming soon :+1:

**Comment by xHN35RQ** [comment]
@kimbaudi until liquid 4 ships in jekyll to support `sort_natural` get [`sort_insensitive.rb`](https://gist.github.com/xHN35RQ/264d28f2be337391312d6ffcdc39f824) follow this [guide to install the plugin](https://jekyllrb.com/docs/plugins/#installing-a-plugin) and then use [`sort_insensitive`](https://gist.github.com/xHN35RQ/264d28f2be337391312d6ffcdc39f824#file-sort_insensitive-rb-L8) in place of `sort` or `sort_natural` in your template.

**Comment by kimbaudi** [comment]
@xHN35RQ - Thanks for your suggestion to use `sort_insensitive.rb`. However, that .rb file doesn't handle the case where you have categories/tags like problem20, problem 200, problem 30. It still places problem200 before problem30. I'll just wait until Jekyll supports `sort_natural`.
