### ISSUE TITLE
in `require': cannot load such file -- bundler (LoadError)

### ISSUE THREAD

**Issue by itxuye** [jekyll/jekyll#5818]
`/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.3.1/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.3.1/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'`
When use jekyll ,I got this probelm.

**Comment by MissCuriosity** [comment]
I have met this problem too.
Have you already solved this problem

**Comment by MissCuriosity** [comment]
I have found a solution

gem install bundler

Then,you will find it's ok

**Comment by crispgm** [comment]
@MissCuriosity Install bundler and use `bundle exec jekyll`
