### ISSUE TITLE
How can I show what's the programming language of a given code snippet?

### ISSUE THREAD

**Issue by mfidemraizer** [jekyll/jekyll#5821]
For example, let's say I've this

<pre>
```javascript
// code here
```
</pre>

It would be great that this code snippet could include a header showing what's the programming language being used.

Is it possible?

Thank you in advance!

**Comment by ashmaroli** [comment]
While its not currently possible to do this automatically, it would be a nice addition. :+1:

**Comment by parkr** [comment]
This is possible! We output this value into an HTML attribute. A little custom JS to add a header with this value would be easy.

For the sake of simplicity, I can't see us going [as far as Octopress did](http://octopress.org/docs/blogging/code/). I helped maintain that code and it was a real pain. There were tons of edge cases and it was all custom. 

It's much better if we just rely on the markdown converter and ensure that the data – in some form – is accessible. In this case, the HTML contains the data you need so we're not really blocking you here. 👍 

I don't think this is worth exploring further within Jekyll Core. Thanks!
