### ISSUE TITLE
Specify collection type using front matter

### ISSUE THREAD

**Issue by Neaox** [jekyll/jekyll#5824]
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---
- [x] I am on (or have tested on) ***Windows*** 10+

@jekyll/build

Currently all collection items must exist within a folder with the name of the collection prepended with an underscore (ie if the collection is named `cars` then all items for that collection would need to be within the `_cars` folder).

What would be cool would to be able to specify that an item belongs to a collection using the frontmatter.

By specifying the `type` within the front matter a file would then be included within the collection.

**Comment by Neaox** [comment]
@

**Comment by parkr** [comment]
This is a neat idea! Unfortunately, this adds a lot of complexity. The idea of a collection is to keep everything related in one place. It makes it easy for newcomers to your content to understand its logical structure and to grok how the content flows. It is a very valuable asset to have, this organization.

You may be looking for `categories`: https://jekyllrb.com/docs/variables/

Thanks for the issue!
