### ISSUE TITLE
Question on:Liquid Exception:Invalid date

### ISSUE THREAD

**Issue by kboygit** [jekyll/jekyll#5826]
I have this error when I run jekyll serve:

 Liquid Exception: Invalid Date: 'nil' is not a valid datetime. in atom.xml
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid Date: 'nil' is not a valid datetime.

When I run bundle exec jekyll serve:

          Error: could not read file /home/bruh/Workspace/KBOY/Personal/kirbyjames-blog/_posts/2017-01-11-post.md: (<unknown>): found unexpected end of stream while scanning a quoted scalar at line 7 column 12
       Deprecation: You are using 'kramdown.coderay' in your configuration, please use 'syntax_highlighter_opts' instead.
       Deprecation: You are using 'coderay_wrap'. Normalizing to wrap.
       Deprecation: You are using 'coderay_line_numbers'. Normalizing to line_numbers.
       Deprecation: You are using 'coderay_line_number_start'. Normalizing to line_number_start.
       Deprecation: You are using 'coderay_tab_width'. Normalizing to tab_width.
       Deprecation: You are using 'coderay_bold_every'. Normalizing to bold_every.
       Deprecation: You are using 'coderay_css'. Normalizing to css.
  Liquid Exception: Invalid Date: 'nil' is not a valid datetime. in atom.xml
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid Date: 'nil' is not a valid datetime.

Didn't quite understand on this part as well on the post:

Error: could not read file /home/bruh/Workspace/KBOY/Personal/kirbyjames-blog/_posts/2017-01-11-post.md: (<unknown>): found unexpected end of stream while scanning a quoted scalar at line 7 column 12
       Deprecation: You are using 'kramdown.coderay' in your configuration, please use 'syntax_highlighter_opts' instead.
       Deprecation: You are using 'coderay_wrap'. Normalizing to wrap.
       Deprecation: You are using 'coderay_line_numbers'. Normalizing to line_numbers.
       Deprecation: You are using 'coderay_line_number_start'. Normalizing to line_number_start.
       Deprecation: You are using 'coderay_tab_width'. Normalizing to tab_width.
       Deprecation: You are using 'coderay_bold_every'. Normalizing to bold_every.
       Deprecation: You are using 'coderay_css'. Normalizing to css.

Then I modify confgure.yml for Heroku production and I added below:
gems:      [kramdown]
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
under gems: [jekyll-paginate]

now paginate won't be recognized:

 Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.

Thanks sorry for the long question , I am just trying to understand indepth on jekyll

**Comment by ashmaroli** [comment]
adding `jekyll-paginate` to your `Gemfile` under the group `:jekyll_plugins` should sort the issue about that gem..

**Comment by kboygit** [comment]
uhm @ashmaroli what is the snippet looks like?I am so sorry I had to ask you directly on the snippet

**Comment by ashmaroli** [comment]
When you create a new site with `jekyll new`, a `Gemfile` is already created for you.
```ruby
# Gemfile

group :jekyll_plugins do
  gem "jekyll-paginate"
end
```

**Comment by kboygit** [comment]
@ashmaroli thank you I got it now , so its inside the gem file not inside _config.yml

**Comment by ashmaroli** [comment]
You can either add a plugin to `:jekyll_plugins` group in the `Gemfile` or to the `gems:` array in your `_config.yml`. The thing with the YAML config file is if your *`keys`* are not properly indented, they won't be recognized as such.

**Comment by kboygit** [comment]
@ashmaroli I gotchu thank you for this, now this errors what do they mean?

> WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /home/bruh/Workspace/KBOY/Personal/kirbyjames/_config.yml
Configuration file: /home/bruh/Workspace/KBOY/Personal/kirbyjames/_config.yml
            Source: .
       Destination: ./_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Deprecation: You are using 'kramdown.coderay' in your configuration, please use 'syntax_highlighter_opts' instead.
       Deprecation: You are using 'coderay_wrap'. Normalizing to wrap.
       Deprecation: You are using 'coderay_line_numbers'. Normalizing to line_numbers.
       Deprecation: You are using 'coderay_line_number_start'. Normalizing to line_number_start.
       Deprecation: You are using 'coderay_tab_width'. Normalizing to tab_width.
       Deprecation: You are using 'coderay_bold_every'. Normalizing to bold_every.
       Deprecation: You are using 'coderay_css'. Normalizing to css.

**Comment by ashmaroli** [comment]
you may have the following object in your `_config.yml`:
```yaml
kramdown:
    'coderay' :
       'coderay_wrap' : 'div',
       'coderay_line_numbers' : 'inline',
       'coderay_line_number_start' : 1,
       'coderay_tab_width' : 4,
       'coderay_bold_every' : 10,
       'coderay_css'  : 'style'
```
 or simply `enable_coderay: true` in that block.. Delete all instances of such.

**Comment by kboygit** [comment]
@ashmaroli thank you , you guys can cosider this as close
