### ISSUE TITLE
.jekyll-metadata not being created

### ISSUE THREAD

**Issue by matthewmcvickar** [jekyll/jekyll#5829]
## Summary

I cannot get incremental generation to work after a lot of trying, and re-reading the documentation I noticed it depends on a `.jekyll-metadata file`, which doesn't exist in my project. Is there a reason it might not exist, and can I fix it?

Here is my test repository, which mirrors the setup of the private repository I'm having trouble with (except for its posts and personally identifying information):

https://github.com/matthewmcvickar/matthewmcvickar-jekyll-test

## Details

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I was trying to build.

## My Reproduction Steps

1. Download or clone [matthewmcvickar-jekyll-test](https://github.com/matthewmcvickar/matthewmcvickar-jekyll-test)
1. Install dependencies: `npm install && bundle install`
1. Build assets: `grunt buildAssets`
1. Build Jekyll site: `jekyll build --incremental`
1. Change the text of a single a post and save it.
1. Re-build Jekyll site: `jekyll build --incremental --verbose`
1. Notice that every single page is regenerated.
1. Notice that no `.jekyll-metadata` file is created: `l .jekyll-metadata`

## The Output I Wanted

Incremental generation. This doesn't happen—every page is regenerated on every save. And there is no `.jekyll-metadata` file created.

## What I've Tried

- Disabling [jekyll-archives](https://github.com/jekyll/jekyll-archives). This doesn't fix it.
- Disabling the HTML-minifying layout `compress.html`. This doesn't work either.

**Comment by ashmaroli** [comment]
`--incremental` works in conjunction with `--watch`
please try again with : 
```
$ bundle exec jekyll build --watch --incremental
```
or serve your site. `--watch` is set to `true `by default while serving:
```
$ bundle exec jekyll serve --incremental
```
you should see a message **`Incremental build: enabled`**

**Comment by DirtyF** [comment]
@ashmaroli FYI `.jekyll-metadata` is being created without `--watch`option.

@matthewmcvickar This seems to be related to the `jekyll-archives` plugin: if you comment the gem in the Gemfile, then the metadata file is being created. 

/cc @jekyll/archives

**Comment by ashmaroli** [comment]
Thanks for correcting me @DirtyF 
My bad.. i must've gotten confused with the use of `--watch` with `--livereload` feature under development..
Apologies!

**Comment by DirtyF** [comment]
@ashmaroli I wasn't sure either, I just checked twice before answering 😅

**Comment by alfredxing** [comment]
The current version of Archives is not compatible with incremental regen, but we have merged a fix for that! It should be out soon, but if you want it now, you can use the version directly from the GitHub repo:

```yaml
gem 'jekyll-archives', :git => 'https://github.com/jekyll/jekyll-archives'
```

**Comment by matthewmcvickar** [comment]
Indeed, that worked. Thank you!

I had disabled `jekyll-archives` in the `config.yml` file but not the Gemfile.

Unfortunately, this has only cut the generation time from 45s to 22s, and running `jekyll build` always regenerates the entire site.
