### ISSUE TITLE
Header scrolls down with page

### ISSUE THREAD

**Issue by forteddyt** [jekyll/jekyll#5830]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [X] This is a feature request.

Hello! I'm both new to website building and Jekyll, so I may have overlooked a solution to this, and I apologize if I did. I searched through this repositories issues for a post similar to this but did not find one.

Is there a way to make it so that the web page's header will scroll down along with the user? So to not disappear? Like, for example, on the [twitter](https://twitter.com/) site?

Thanks in advance.

**Comment by DirtyF** [comment]
Hi @forteddyt, your question is more related to HTML/CSS than Jekyll itself. Jekyll does not do presentation, it only converts files.

You should take a look at Jekyll [feeling-responsive theme](http://phlow.github.io/feeling-responsive/) who does have a fixed header. 

Happy Jekyllin'!
