### ISSUE TITLE
jekyll doesn't copy local file permissions

### ISSUE THREAD

**Issue by leaf-node** [jekyll/jekyll#584]
When invoking jekyll, it copies over files to the destination. However, if a file already exists, its contents are updated, but its permissions are not.

For instance, if the permissions of 'static/x.css' is 664, but the 'dest/static/x.css' perms are 600, then when jeyll is invoked, 'dest/static/x.css' will remain in mode 600.

This is not ideal since file permissions affect whether a file is displayable by the web server.

It is only a problem if jekyll was previously invoked when local permissions were bad. In order to work around this problem, one has to 'rm -rf dest/*' then run jekyll, after permissions have been fixed locally.

**Comment by antonk52** [comment]
Just had the same problem. All the files inside _site folder had permissions 600. Fixed it by deleting the inside of _site folder and run jekyll serve again.

**Comment by envygeeks** [comment]
In the meantime with Linux you can `setfacl` on OS X I don't think they even support per-dir ACL's.

**Comment by kainjow** [comment]
Just ran into this problem myself. Fixed it as part of the deployment process, but I'd expect it to retain the file permissions.
