### ISSUE TITLE
Error: code converter not found ...

### ISSUE THREAD

**Issue by De4ce** [jekyll/jekyll#5840]
Configuration file: /pnc/_config.yml
Configuration file: /pnc/_config.yml
            Source: /pnc
       Destination: /pnc/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: code converter not found (xml_attr_content,xml_attr_quote) in feed.xml
jekyll 3.4.0 | Error:  code converter not found (xml_attr_content,xml_attr_quote)

**Comment by parkr** [comment]
Hi, sorry you're having this issue. Without further information, we can't help you out, though.

If you'd like to run `jekyll build --trace` and output the error, that would be helpful for us.

I'm going to close this but I will still see your responses. Cheers!
