### ISSUE TITLE
Trouble with Kramdown TOC

### ISSUE THREAD

**Issue by mstanleyjones** [jekyll/jekyll#5843]
NB: I was unable to get to https://talk.jekyllrb.com/ or I would have asked my question there first, as directed. I have scoured Google and also filed a
[Kramdown issue](https://github.com/gettalong/kramdown/issues/406) in case it's not Jekyll's fault.

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

First, let me describe what I wanted to do. We use the `github-pages` bundle and we use Kramdown. I wanted to take advantage of Kramdown's `{:toc}` macro to automatically insert a TOC on every page, unless a specific frontmatter variable was set. Here's what I did:

1.  Added the following contents to `_layouts/docs.html`, which is the layout file we use:

    ```

    {% unless page.notoc %}
    <div id="inline_toc" markdown="1">

    * TOC
    {:toc}

    </div>
    {% endunless %}

    ```

    The Kramdown docs led me to believe that if I used `markdown=1` on the div, then any enclosed Markdown would be interpreted. I also tried adding `parse_block_html: true` to the `kramdown:` section of the `_config.yml` with no difference in behavior.
    (the extra whitespace is because of some reports in my Google searches that whitespace matters.)

2.  Cleaned and rebuilt the site locally. I have cleaned before each build during this test because of reports that sometimes the TOC does not automatically get built during an incremental build.

## The Output I Wanted

I wanted the TOC to be automatically generated on each page, as though I had used the `{:toc}` macro directly in each individual Markdown file.

## The Output I Got

The Kramdown portion of the included file is emitted verbatim as plain text, as shown in this screenshot.

<img width="820" alt="screen shot 2017-01-30 at 5 06 36 pm" src="https://cloud.githubusercontent.com/assets/7674613/22477569/7c1387f0-e79b-11e6-88ac-a8fd4cd24526.png">

(updated the description after I stopped trying to include it from a separate file)

**Comment by mstanleyjones** [comment]
I got some advice that I couldn't use an include to do this, so I moved the whole div into the `_layouts/docs.html` file, and amended the commit. This didn't fix the problem or change the symptoms in any way that I can tell. :(

**Comment by mstanleyjones** [comment]
The Kramdown team has [responded](https://github.com/gettalong/kramdown/issues/406#issuecomment-276458374) that what I'm trying to do works when you use Kramdown directly, so I think the problem might in the way Jekyll is calling Kramdown. :(

**Comment by pathawks** [comment]
Your layout has an `.html` file extension, so Kramdown never sees it.

Change the extension to `.md` if you want Markdown rendered.

**Comment by mstanleyjones** [comment]
I have now put the contents straight into the layout file, so I'm not sure what I should change the file extension on? [Kramdown docs say](https://kramdown.gettalong.org/syntax.html#html-blocks) that if I set `markdown="1"` on the div, it will get parsed as Markdown.

However I tried moving the following to `_includes/inline_toc.md`:

```
* TOC
{:toc}
```

and including it in the layout like so:

```
<div id="inline_toc" markdown="1">

{% include inline_toc.md %}

</div>
```

I get the same outcome.

**Comment by mstanleyjones** [comment]
It also doesn't work if I change `docs.html` to `docs.md` in the `_layouts/` directory.

**Comment by mstanleyjones** [comment]
This was solved by @allejo on the #jekyll IRC channel. The solution was to use `markdownify`:

```
{% capture foo %}
{% unless page.notoc %}
<div id="inline_toc" markdown="1">

* TOC
{:toc}

</div>
{% endunless %}

{{ content }}
{% endcapture %}

{{ foo | markdownify }}
```

I don't know if this was the "right" way to accomplish this or if it points to the fact that it really is a Jekyll bug and this is the workaround, but I'll leave this here in case anyone else wants to do the same thing.

**Comment by pathawks** [comment]
Are layouts never processed as Markdown? That's contrary to what I would have expected.
