### ISSUE TITLE
Contribute a Dockerfile

### ISSUE THREAD

**Issue by chb0github** [jekyll/jekyll#5844]
Hi there,

I have a Dockerfile that I would like to contribute. I noticed there was some talk but I didn't find any action. 

- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.
- [x] I am on (or have tested on) ***macOS*** 10+

Incidentally [This bit me](https://github.com/jekyll/jekyll/pull/3542):

**Comment by parkr** [comment]
We have Dockerfiles all set up in https://github.com/jekyll/docker! You should be able to see them on Docker Hub and download them the normal way. Cheers!
