### ISSUE TITLE
running script/bootstrap script gave error unknown switches '-j8'

### ISSUE THREAD

**Issue by halfrobo** [jekyll/jekyll#5847]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I was trying to install.

**Comment by halfrobo** [comment]
Hi. Can anyone help me out in this? I am trying to install jekyll through git mode but failed to do so because if this bundle error.

Thank you.

**Comment by DirtyF** [comment]
I don't know about the -j8 option in script/bootstrap but if you want to install jekyll directly from this repository, you can specify it in your `Gemfile`:

```yaml
gem 'jekyll', github: 'jekyll'
```

**Comment by parkr** [comment]
`-j8` is an argument to Bundler. When you run `bundle install`, you can optionally pass it a `--jobs` argument (`-j` for short) to give it parallel processing so the dependencies install more quickly. 

>  I am trying to install jekyll through git mode but failed to do so because if this bundle error.

You can either remove `-j8` from your local copy of `script/bootstrap`, or you can simply run `bundle install` and continue on.

Note that this is not the recommended way to install Jekyll: http://jekyllrb.com/docs/installation/

Hope this helps!
