### ISSUE TITLE
Front matter var doesn't work anymore

### ISSUE THREAD

**Issue by guillaumegautier** [jekyll/jekyll#5851]
Hello. 

I have a problem with custom front matter vars that were working fine until now.

I have this in my page :
```
---
has-cart: true;
---
```

and this in an included snippet :
`{% if page.has-cart == true %}
lorem ispum
{% endif %}`

And it doesn't work anymore. Any idea why ? Thanks

**Comment by pathawks** [comment]
Is the page being rendered but the conditional is not evaluating properly?

Can you try outputting the value of `{{ page.has-cart }}`?

I don't think YAML uses `;` as a terminator. My guess is that `has-cart` has value string `"true;"` and so is not `== true`

**Comment by guillaumegautier** [comment]
The page is being render, yes, but the conditional returns nothing

`{{ page.has-cart }}` returns `true;`

You were right, the problem was the `;`

Thanks !
