### ISSUE TITLE
.csv data to collections

### ISSUE THREAD

**Issue by geloangelia** [jekyll/jekyll#5852]
I have a table of data files from _data(.csv) and want to have another page when selecting the name of a firm.

https://geloangelia.github.io/crowdbotics2/vclist/

I tried to use this process https://github.com/theyworkforyou/jekyll-csv
unfortunately the data is not showing under about tab

Can you help me on how can I turn my csv file to collection and have a separate page of each firm for additional contents.

heres my repo: https://github.com/geloangelia/crowdbotics2

**Comment by pathawks** [comment]
> Can you help me on how can I turn my csv file to collection and have a separate page of each firm for additional contents.

I don't believe this is currently possible.

**Comment by geloangelia** [comment]
Do you have recommendation?

**Comment by parkr** [comment]
I would recommend writing a small script to process your `.csv` file and output files in a collection. They'll need YAML front matter, which can house your data, and I'd recommend setting up a layout they can all use to present the data. Then, add the collection to your `_config.yml` and make sure it has `output: true`.
