### ISSUE TITLE
How to change the root url when buidling the site?

### ISSUE THREAD

**Issue by etiennedesign** [jekyll/jekyll#5853]
Hi,
I made a jekyll website which i host on my own host provider, however i use github pages with custom domain for testing.

For now my production workflow is:
1. Make some modifications on jekyll and test it locally and on github pages
2. When i am ready to publish i copy the _site folder
3. I do a find&replace for all http://localhost:4000 to https://mysite.com
4. I upload the content of the _site folder to my server

I would like to know if there is the way to generate the _site folder locally directly with mysite url as root instead of localhost. 

Any help appreciated :)
Thanks!

**Comment by DirtyF** [comment]
In your `_config.yml`:

`url: https://example.com`

To override development URL you ought to run:
`JEKYLL_ENV=production bundle exec jekyll build`
