### ISSUE TITLE
Jekyll fails to serve the site with a 'Liquid Exception' error

### ISSUE THREAD

**Issue by midhruvjaink** [jekyll/jekyll#5861]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

I had my site running well locally with
```
jekyll serve
```
But now on building and serving it locally I get 
```
Liquid Exception: undefined method `includes_load_paths' for #<Jekyll::Site:0x00558ff67f7e08> in _layouts/main.html
jekyll 3.1.6 | Error:  undefined method `includes_load_paths' for #<Jekyll::Site:0x00558ff67f7e08>
```
error
I have Jekyll 3.1.6 installed

- [x] tried uninstalling and reinstalling jekyll

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by ashmaroli** [comment]
Please upgrade to the latest version (`v3.4.0`) and try again..
```
$ gem update jekyll
```

**Comment by midhruvjaink** [comment]
Hey @ashmaroli 
tried it but it says
> Nothing to update

and the same error persists again

**Comment by parkr** [comment]
You may have a `Gemfile` – if so, run `bundle update` and see if that installs jekyll 3.4.0.

**Comment by cfstras** [comment]
This also happens if you don't have python installed.

    apk add python2   # or the likes...
