### ISSUE TITLE
Feature idea: python integration with liquid

### ISSUE THREAD

**Issue by artcg** [jekyll/jekyll#5866]
I really love the features liquid provides, but find my self quite limited by the control flow. 

Fortunately we don't need to re-invent the wheel, there is stuff like python which is designed to provide easy control flow:

The idea is to allow for liquid to pass on parameters to a python script, which would run independently of liquid and then return the result:

Example usage:

```
{% assign liquid_variable = 10 %}
{% python %}
    def fibonacci(n):
        if n == 0:
            return 0
        elif n == 1:
            return 1
        else:
            return fibonacci(n-1) + fibonacci(n-2)
{% run python_input=liquid_variable %}
    fibonacci(python_input)
{% endpython %}
```

Output:

```
55
```

**Comment by pathawks** [comment]
You might be able to do this already as a Liquid plugin.

With a feature like this, I think developing a feature plugin is definitely the way to start. I can't see this functionality becoming a part of Jekyll core, but if it were available as a plugin I’m sure it could find an audience:+1:

**Comment by parkr** [comment]
Agreed with @pathawks here. This is a neat idea but we won't be able to bring this into Jekyll core as it violates the safety features of Liquid itself, which explicitly doesn't allow users to run arbitrary code in "normal" programming languages. But it'd be a really cool plugin!
