### ISSUE TITLE
Feature: Frontmatter Support in Includes

### ISSUE THREAD

**Issue by fraank** [jekyll/jekyll#5867]
I'm working with jekyll themes at the moment - btw. thanks for this long waited feature - and coming around with an feature request to **support frontmatter header in include files**.

**Why?**
When composing themes, includes are typically used for functional blocks (for example a contact form or image gallery) which could be used on every page. These blocks have some preconfigured settings (in this example text, form fields, or images to include) for this include. For a better readability of the template those settings (or parameters) should be included and preconfigured in the header. When somebody wants to overwrite the include file he should copy the file and change the header.

I know that site- and page- params exists, but sometimes they are not enough for writing functional parts of a template.

Example implementation:

_includes/header.yml

```
---
headline: Hello World!
---
<h1>{{ include.headline }}</h1>
```

index.html (use default setting)

    {% include header.html %}

would Result:
<h1>Hello world.</h1>

index2.html (overwrite by param)

    {% include header.html headline="Hello USA!" %}

would Result:
<h1>Hello USA!</h1>

What do you think of this request? I'm the only one who thinks this is useful? Please give me some feedback if it makes sense to invest time in it to build this functionality (maybe for jekyll-master?)!

**Comment by xHN35RQ** [comment]
Doesn't this already exist? http://jekyllrb.com/docs/includes/#passing-parameters-to-includes

**Comment by fraank** [comment]
Yes, passing variables exists. But frontmatter in includes does not.

Am 07.02.2017 1:55 nachm. schrieb "Nick" <notifications@github.com>:

**Comment by xHN35RQ** [comment]
If you want includes to have default parameters use a YAML data file: http://jekyllrb.com/docs/includes/#passing-references-to-yaml-files-as-parameter-values

**Comment by fraank** [comment]
Yes, this is working and I could use page parameters as well. But this
doesn't solve the problem that a basic configuration for an include is
inside the file with frontmatter.
And yes, I could use variable assignments for this. But frontmatter would
be more easy to read and sexy.

Am 07.02.2017 2:01 nachm. schrieb "Nick" <notifications@github.com>:

If you want includes to have default parameters use a YAML data file:
http://jekyllrb.com/docs/includes/#passing-references-
to-yaml-files-as-parameter-values

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jekyll/jekyll/issues/5867#issuecomment-277992502>, or mute
the thread

**Comment by xHN35RQ** [comment]
> But frontmatter would be more easy to read and sexy.

I disagree. Usually it makes sense for any defaults to be centralized into config.yml or data files instead of spread throughout theme files. http://jekyllrb.com/docs/configuration/#front-matter-defaults But maybe I'm wrong. I'm interested to hear Jekyll core devs opinion on this.

**Comment by pathawks** [comment]
I'm not sure I see the value.

If it were pulled from a data file, I could override it without messing with theme files.

If it were just baked in with the Liquid `default` filter (`{{ include.headline | default: "Hello World!"" }}`, it would at least be very obvious what I need to modify when I want to make a change.

If YAML front matter were used in an include, I would need to override the whole include file (and potentially miss out on future theme updates) _and_ would incur the cognitive overhead of an extra level of indirection.

Just my opinion and I am not a heavy user of themes or includes

**Comment by parkr** [comment]
Hey! I have to agree with @pathawks here: the examples you've given can all be solved through other means. We try to keep things simple here in Jekyll core.

For your example above:

```liquid
{% assign headline = include.headline | default: "Hello World!" %}

...

<h1>{{ headline }}</h1>
```

That would be the solution I would point you to. Using front matter to provide default values is not what front matter is about. It's about metadata for a logical set of content like a page/post/collection document.

Thanks, though!
