### ISSUE TITLE
Dynamically Load Documents Within A Collection

### ISSUE THREAD

**Issue by felicianotech** [jekyll/jekyll#5869]
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I was trying to build.

I've tried searching for this, but I'm not even sure what the best search terms are. So far, I came up with nothing. Here's the scenario:

I have multiple collections, let's say `_docsv1`, `_docsv2`, and `_docsv3`. I know that I can access all of the docs from a particular collection, as an array, like this:

```
{% for doc in site.docsv1 %}
...
{% endfor %}
```

However, how I would I do this, from any doc within any collection, dynamically? I want something like this:

```
{% for doc in site.{{page.collection}} %}
...
{% endfor %}
```

I know that collections can be "searched" by using `{% assign mycollection = site.collections | where:"label","docsv1" | first %}` but that only gives the collection's metadata and not the docs within the collection.

Any ideas?

**Comment by pathawks** [comment]
What are you ultimately trying to accomplish, at a higher level?

**Comment by felicianotech** [comment]
I want to be able to iterate through a collection's docs without having to know the collection's name, and typing it in code, ahead of time.

**Comment by xHN35RQ** [comment]
You mean something like this?

```
{% assign documents = site.documents | where:"collection",{{page.collection}} %}
{% for doc in documents %}
...
{% endfor %}
```

**Comment by felicianotech** [comment]
I think this will do it as well:

```
{% assign myCollection = site.collections | where:"label",{{page.collection}} | first %}
{% for doc in myCollection.docs %}
...
{% endfor %}
```

Pending any performance differences, I guess there's two ways to solve this. Thank you.

**Comment by xHN35RQ** [comment]
If you're creating index pages for each collection https://github.com/jekyll/jekyll/issues/5023 may be useful.

**Comment by felicianotech** [comment]
@xHN35RQ I did see that too. Thanks so much, I think I have what I need for now. I appreciate the quick responses.

**Comment by xHN35RQ** [comment]
No problem. Thought you might have. Just linking for future users.
