### ISSUE TITLE
Errors upon jekyll build & jekyll serve (potential installation issue?)

### ISSUE THREAD

**Issue by fjoyce** [jekyll/jekyll#5873]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on mac OS X 10.9.5

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

1. Checkout productive branch: `git checkout productive`
2. Bring changes from master into productive: `git merge --no-ff master`
3. Optimize source code with require: `r.js -o ./app/app.build.js` (using local installation of r.js)
4. Copy optimized files from require build folder to application folder:
copy minified main.js: `cp ../build/app/main.js ./app/main.js`
copy minified main.css: `cp ../build/assets/css/main.css ./assets/css/main.css`

5. Build site locally: run `jekyll build` 
6. Test site locally: run `jekyll serve`, 
7. Wait and in your browser go to localhost:4000 or http://127.0.0.1:4000/

(5-7 fail)

## The Output
```

/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.3/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.3/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.3/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1391:in `contains_requirable_file?'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:823:in `block in each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:822:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.3/lib/bundler.rb:12:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Users/joyce/.gem/ruby/2.0.0/gems/jekyll-3.4.0/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
	from /Users/joyce/.gem/ruby/2.0.0/gems/jekyll-3.4.0/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

```

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by pathawks** [comment]
I'm sorry you are having trouble.

Can you provide any information about the problem you are having?

**Comment by fjoyce** [comment]
Sorry about that. I had accidentally put the reproduction steps and output into annotations.

**Comment by parkr** [comment]
Run `gem install bundler` and try again – that may be it! You may also need to run `gem update --system`.

For further help, check out our great forums at https://talk.jekyllrb.com!

**Comment by fjoyce** [comment]
Thanks, @parkr.

When I run `gem install bundler`I get the following output:

`You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.`

I think it's an issue with Mac OS X System Ruby.

I'll try following the leads the answers to this: https://github.com/jekyll/jekyll/issues/2425

**Comment by DirtyF** [comment]
@fjoyce if you have [homebrew](https://brew.sh/) installed, you can try [this gist](https://gist.github.com/DirtyF/5d2bde5c682101b7b5d90708ad333bf3) to install jekyll with ruby 2.3.3
