### ISSUE TITLE
(SUPPORT)POST not redirecting after adding a custom domain(CNAME) & .SCSS not working

### ISSUE THREAD

**Issue by kboygit** [jekyll/jekyll#5875]
1st ISSUE: After adding a custom domain on my repo, posts wont redirect as normal unlike using github's hosting 

```
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.
```

2nd ISSUE: sass file not being recognized
```
2http://kirbyjames.me/kirbyjames/css/style.scss Failed to load resource: the server responded with a status of 404 (Not Found)
```

Link to my repository : https://github.com/kboygit/kirbyjames

3rd ISSUE: Trying to integrate travis-ci on my repo but that didn't work out following the documentation on your website 

http://jekyllrb.com/docs/continuous-integration/travis-ci/

eventually I rebased to the previous commit 

Would love some help here getting familiar with jekyll thank you

**Comment by ashmaroli** [comment]
Observations:
  - Your `_config.yml` is very noisy.
      - contains numerous duplicate keys (like multiple `exclude` and `include` keys)
      - you have `jekyll` included under `:jekyll_plugins` and the `gems:` array. **??**
      - many of the `keys` are already [handled by default](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/configuration.rb#L7-L80). There's no point repeating them unless you're overriding those settings.
  - Your URLs don't work because for some reason, `baseurl` is getting reset to `""`
      - your post is accessible when you erase the `baseurl` part from its URL
      - your source-code shows numerous instances of `//` where the `baseurl` got reset.

Inference: Try cleaning up the config file and repeat. If still an issue, repeat trials disabling 3rd party plugins one-by-one.

**Comment by kboygit** [comment]
@ashmaroli thank you that you mentioned all those keys inside _config.yml are already set by default.Removing those duplicate keys wont affect anything general unless overriding the config settings.

Thank you as always!

**Comment by ashmaroli** [comment]
You're welcome Kirby. :smiley:
