### ISSUE TITLE
Hi. Installing jekyll has taken me hours, and it still doesn't work.

### ISSUE THREAD

**Issue by DarylMcCullough** [jekyll/jekyll#5877]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by DarylMcCullough** [comment]
I wish I had recorded every error, but it would have been a list of a few hundred lines long. There are dozens of tutorials explaining how to do it, and no two of them give the same instructions, and none of them work.

I'm trying to install under Cygwin on windows. One attempt got close. It seemed to install jekyll, but then when I ran it with

jekyll new my-site

I got the error message "Bundler: Gem::Ext::BuildError: ERROR: Failed to build gem native extension."

I googled for this error, and somebody said that there were problems with later versions of gem, and suggested I go back to version 2.3 of gem. That screwed things up even worse.

**Comment by DirtyF** [comment]
Hi, sorry you ran intro install problems. Windows is not officially supported but it should work.

Our official documentation links to this guide for installing Jekyll on Windows: https://labs.sverrirs.com/jekyll/ 
Have you tried it?

Please rather ask your questions on our brand new forum: https://talk.jekyllrb.com, it's intended for Jekyll users to find some support there.

**Comment by parkr** [comment]
Agreed – sorry you are having problem! Please reach out on `talk.jekyllrb.com` for more help.

> `Bundler: Gem::Ext::BuildError: ERROR: Failed to build gem native extension`

This error message is a generic one – there is a more specific error message in the output. Look for a compile error or something like that.

**Comment by DarylMcCullough** [comment]
Hi, I got jekyll to work in a DOS shell. Which is okay, but I would have preferred to get it to work within Cygwin. It's not a big deal, though.

**Comment by 77QingLiu** [comment]
takes hours too. This is really frustrating. Both ruby and Dev kit installed, but still got error
