### ISSUE TITLE
Bug: Jekyll post loop not returning anything on GitLab Pages, but returning posts on GitHub pages

### ISSUE THREAD

**Issue by andrewbanchich** [jekyll/jekyll#5879]
I've run into something I can't seem to figure out. I push my Jekyll theme to GitLab, which I have set up to mirror the repository to GitHub. Because of this, the two repos (should be) exactly the same. However, GitLab Pages, which uses Jekyll, is producing an issue, while GitHub Pages is not.

I wanted to remove the `url` variable from the `_config.yml` file so that I can have the demo from GitLab run on GitLab Pages and the demo from GitHub run on GitHub Pages. I used the new-ish `relative_url` filter on some paths and everything seems to be working, except for [a posts loop](https://gitlab.com/andrewbanchich/forty-jekyll-theme/blob/master/_includes/tiles.html). You can see the output of this code on the homepage in [the GitHub Pages demo](https://andrewbanchich.github.io/forty-jekyll-theme/) but, as you can see in [the GitLab Pages demo](https://andrewbanchich.gitlab.io/forty-jekyll-theme/), the tiles are not displaying.

I'm not sure what is causing this, but if the two code bases are the same and producing different results on different sites, wouldn't that imply there is an issue with them being processed?

- [Link to GitLab repo](https://gitlab.com/andrewbanchich/forty-jekyll-theme)
- [Link to GitHub repo](https://github.com/andrewbanchich/forty-jekyll-theme)

**Comment by parkr** [comment]
It looks like there's an issue with the [`for` loop here](https://github.com/andrewbanchich/forty-jekyll-theme/blob/25fe79db257bf6c65646ba1ec8204e05d1571e0a/_includes/tiles.html#L2). GitHub Pages is currently running Jekyll 3.3.x – what version is GitLab running? It could be a bug in Jekyll v3.4.

**Comment by andrewbanchich** [comment]
@parkr GitLab uses a yaml file you include in your repo to run a CI script where you can specify which version of Jekyll you want. I tried changing `gem install jekyll` to `gem install jekyll -v 3.3.1` to specify that version, and after it deployed it built the site correctly!

I take it that means it in a bug in Jekyll 3.4?

**Comment by parkr** [comment]
Please try with the newly release v3.4.1!

**Comment by andrewbanchich** [comment]
@parkr It works! Thank you.
