### ISSUE TITLE
syntax highlight within list entry breaks the list

### ISSUE THREAD

**Issue by cyjake** [jekyll/jekyll#588]
sample:

``` markdown
- item 1
- item 2
  {% highlight ruby %}
  def foo
     p 1
  end
  {% highlight %}
- item 3
```

the code block within second entry breaks the list in two. generates html like this:

``` html
<ul>...</ul>
<div class="highlight"></div>
<ul>...</ul>
```

**Comment by asgarli** [comment]
+1

**Comment by linbug** [comment]
+1 Did anyone find a workaround for this?

**Comment by akhyarrh** [comment]
Use redcarpet with `disable_indented_code_blocks` ?

Ref: https://github.com/vmg/redcarpet#and-its-like-really-simple-to-use

**Comment by olleharstedt** [comment]
I too am looking for a solution for this.

**Comment by parkr** [comment]
@olleharstedt If you're using `kramdown` and `rouge`, use **exactly 4 spaces** in your lists:

```markdown
1. List item 1
2. List item 2
    ```ruby
    def i_am_highlighted
      puts "Hello, I am highlighted!"
    end
    ```
3. List item 3
```

**Comment by zhanghaowx** [comment]
@parkr It fixed the problem but all code are in one line. Anyway to have code blocks instead?

**Comment by parkr** [comment]
@zhanghaowx Can you paste a screenshot and the HTML it produces?

**Comment by zhanghaowx** [comment]
@parkr You can check https://gist.github.com/zhanghaowx/5f397906fa387af65293fc1e066483bb, I get same result on my personal site.

**Comment by parkr** [comment]
@zhanghaowx Interesting! I see that you get the same thing with GitHub-Flavored Markdown, so maybe it's the newlines in between the code block and the numbers:

```markdown
1. List item 1
2. List item 2

    ```ruby
    def i_am_highlighted
      puts "Hello, I am highlighted!"
    end
    ```

3. List item 3
```

**Comment by jmssmth** [comment]
@parkr This worked for me.

**Comment by lvsti** [comment]
run into the same issue, worked it around as follows:
````markdown
&nbsp;1. List item 1
&nbsp;2. List item 2

```swift
let str: String
```

&nbsp;3. List item 3
````

which produces:

&nbsp;1. List item 1
&nbsp;2. List item 2

```swift
let str: String
```

&nbsp;3. List item 3


The `&nbsp;` basically blocks auto-numbering for numbered items. Of course the indentation is wrong but at least this gives you syntax highlighted code blocks without making all items "1.".

**Comment by cjboorman** [comment]
This is an important problem for my project. I'm documenting a dozen different flavors of an SDK, and at the moment - all of my procedures have broken numbered steps (my readers aren't getting the proper user experience). What would it take to properly address this issue?

**Comment by ashmaroli** [comment]
@cjboorman Have you tried using this suggestion from Parker? https://github.com/jekyll/jekyll/issues/588#issuecomment-218852826

**Comment by cjboorman** [comment]
I thought jekyll was specifically designed to use liquid tags (e.g., {% highlight java %}).

**Comment by ashmaroli** [comment]
> I thought jekyll was specifically designed to use liquid tags

Jekyll supports GFM variant of Markdown too.. so you can use the triple-backticks for code-blocks in lieu of the `highlight` tag

**Comment by parkr** [comment]
@cjboorman Yes, it was. However, Liquid tags are agnostic to the markup language you use (the creator of Jekyll used Textile for his personal blog), so it has some unfortunate side effects of breaking the Markdown generator’s understanding of things. kramdown, our current Markdown implementation, is a bit fickle. Indenting here may help, but it’s not clear to me that Liquid tags will work nicely with kramdown in cases like this. This is why I recommended using backtick code blocks, as kramdown can do all the processing and therefore be smarter about context (e.g. knowing the block is part of the `<li>`).

**Comment by streetturtle** [comment]
Below is a workaround I found.
Kramdown has a nice [feature](https://kramdown.gettalong.org/quickref.html#block-attributes) - you can add attributes to the block level elements. In case of `highlight` you simply want to move it to the right (add style `margin-left: 30px;`). You can do it following way:

```markdown
 - get username:

{% highlight bash %}
whoami
{% endhighlight %}{: style='margin-left:30px;'}

 - get date:

{% highlight markdown %}
date
{% endhighlight %}{: style='margin-left:30px;'}
```

But of course you'll need to find the proper value for margin as well as change it for the second or third level list element.
