### ISSUE TITLE
Document deprecation create an inconsistent and hard API

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#5884]
Pages currently support `Page#ext` because it's an accessor, whereas `Document#ext` is deprecated.

**Comment by parkr** [comment]
I'd be OK with adding `Document#ext` back to unify the API's.

One thing I'd be interested in doing is coming up with an interface that we require for all "content classes" and ensuring that both `Document` and `Page` (and maybe `Layout`) respond to all the necessary methods we'll need.

**Comment by parkr** [comment]
@envygeeks would you please submit a PR to add `Document#ext`? Thanks! We can continue conversation there.
