### ISSUE TITLE
Unable to access talk.jekyllrb.com - Secure Connection Failed error

### ISSUE THREAD

**Issue by nancycarroll** [jekyll/jekyll#5888]
I'm not sure where to report this.  At first I thought someone was working on the site, but when I came back today (a week later) it's still there.  I can't imagine that talk.jekyllrb.com is unavailable everywhere so if it helps, I'm in Germany.

Here is a screenshot.  Let me know if I can help further.

![jekyll-talk-secure-connection](https://cloud.githubusercontent.com/assets/1303725/23057590/25627c50-f4f1-11e6-9cdb-e380a1aaa4ed.jpg)

**Comment by ashmaroli** [comment]
Hi, can try accessing the forum via Google Chrome if possible?

**Comment by lsrdg** [comment]
@nancycarroll, in the end of [this issue](https://github.com/jekyll/jekyll/issues/5872) this error is mentioned...

As of today, I am still getting exactly the same error as @nancycarroll with firefox. Opening Chromium just to read the forum. ( :

**Comment by parkr** [comment]
Hey @nancycarroll! It looks like there is a (kind of unpleasant) way to delete the old pinning information: https://linux-audit.com/deleting-outdated-hpkp-key-pins-in-firefox/

I hope this helps!

**Comment by nancycarroll** [comment]
Yes, I am able to access it via Chromium.

**Comment by nancycarroll** [comment]
And removing the hpkp key pin as detailed at the link from @parkr above worked like a charm.  Now I can get to the site also via Firefox.  Thank you for your help, Parker.
