### ISSUE TITLE
Generate list of name from csv/yaml file

### ISSUE THREAD

**Issue by geloangelia** [jekyll/jekyll#5899]
I have a file from google sheet,
https://docs.google.com/spreadsheets/d/14CTs6Y2hMahNV0UeT2XY3dsJixATY6y7dqHD_T6OP6w/edit#gid=737290520

I can list the names,
I just want to have a separate page that contains the detail in the rows.

Do you have recommendation and tips for me to use?

Thank you

**Comment by parkr** [comment]
We offer [data files](http://jekyllrb.com/docs/datafiles/) for this purpose. You can then create a page which iterates over the data and displays it as you wish.
