### ISSUE TITLE
`:path` permalink variable not consistent with documentation – which needs fixing?

### ISSUE THREAD

**Issue by rlue** [jekyll/jekyll#5901]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***macOS*** 10+

---

- [x] I was trying to build.

---

When specifying a permalink configuration, the `:path` variable behaves differently from what is presented in the documentation.

Specifically, the [documentation](https://jekyllrb.com/docs/collections/#permalinks) presents the `:path` variable as consisting of the entire path relative to the originating `_collection` directory, **excluding** the filename itself. Thus, wherever `:path` appears in an example configuration, it is followed by `/:title`.

In practice, it **includes** the filename, making the inclusion of`/:title` redundant. Thus, Example Configuration 2 (which is supposed to be identical to the default configuration),

```yaml
permalink: /:collection/:path/:title:output_ext
```

produces this:

```
├── apidocs
│   └── mydocs
│       └── doc1             <-- `doc1.html` should be here.
│           └── doc1.html
```

To manually reproduce the default configuration, `/:title:output_ext` must be removed:

```yaml
permalink: /:collection/:path
```

I have confirmed this bug occurs in the latest version of Jekyll (3.4.0), without the Github Pages gem. If the error is the documentation, I'm happy to submit a PR – but if the documentation is describing the correct behavior and the error is in parsing the permalink configuration, I'm afraid this one may be over my head.

/cc @jekyll/build @jekyll/documentation

**Comment by parkr** [comment]
The standard permalink is `/:collection/:path/`, which creates `/apidocs/mydocs/doc1/index.html`. `:path` is everything after the collection name, which defaults to a directory as specified.

It sounds like what we want here is a `:dir` template variable which would be just `/mydocs`.

Would you be willing to create a PR? This will modify the `URLDrop` class to add a `dir` method. It may require a `dir` method to be added to `Document`.

**Comment by rlue** [comment]
Thanks for helping get to the bottom of this. To be clear, I don't personally have much need for a `:dir` template variable. My issue was merely that `:path`'s behavior was different from what is described in the docs, and I wasn't sure which was “correct”. 

I will be submitting a PR for the docs instead, if that's peachy by you.

**Comment by rlue** [comment]
I've noticed another inconsistency between documentation and actual permalink configuration behavior, this time with the `:title` template variable. 

Documentation says that `:title` represents a modified version of a document's title as defined in the YAML frontmatter (as distinct from `:name`; i.e., the originating filename). Some cursory experimentation on my end shows it to behave completely identically to `:name`.

I don't use `:title` myself but imagine it has its uses; in this case, I believe the library needs fixing, and not the documentation. @parkr, can you confirm that I'm not just off my rocker? If so, I'm happy to get to work on a PR here.

(Also, I'm under the impression that the `:output_ext` template variable is unnecessary, since Jekyll appears to append file extensions to permalinks by default. Would y'all merge a PR that removed it from the documentation? How about one that removed it from the library as a publicly-accessible template variable altogether?)
