### ISSUE TITLE
Stop CSS generating

### ISSUE THREAD

**Issue by balazsorban44** [jekyll/jekyll#5909]
Hi! I cannot find an option to stop jekyll processing my CSS. I mean, I deleted all of it from jekyll's folder, cause I handle it another place. But still, when I run jekyll, it generates a main.css file from nothing, which I do not need! How can I stop it?

**Comment by pathawks** [comment]
What do you mean “processing your CSS?” If you have not added YAML front matter to your CSS files, Jekyll should not be modifying them.

Are you using a theme? That could be the source of `main.css`

What does your `_config.yml` and directory structure look like? How can I reproduce this on my machine?

**Comment by balazsorban44** [comment]
It is a good question, since my jekyll folder does not even have any kind of CSS (or SASS,SCSS etc.) files. I have something like this:

src
├── img
├── jekyll
│   ├── code
│   ├── _includes
│   ├── _layouts
└── sass
    ├── 1-ESSENTIALS
    ├── 2-MODULES
    ├── 3-PAGES
    └── 4-OTHER

and the output is:

assets
├── css
│   └── main.css  -> Generated by Gulp.js, the one I need
└── main.css -> Generated by jekyll serve command, I do not need it, nothing in this file was

**Comment by balazsorban44** [comment]
## UPDATE:
_config.yml has a line theme: minima which caused the problem, thanks!

**Comment by tmutton** [comment]
@balazsorban44 I am also facing the same issue where the theme (in this case it is minima) is generating a main.css in the assets folder. I am overriding the css and I want to control what happens to it.

How did you overcome this problem?

**Comment by bazzle** [comment]
I'm having this same problem. I'm not using a theme. I have told Jekyll to ignore the assets/css folder as my grunt handles that, but a mysterious 130kb style.css file keeps appearing every time I run serve. I realise I can set my grunt process to overwrite it by using the same filename but it's annoying nonetheless.

**Comment by ashmaroli** [comment]
@bazzle Perhaps you're using `github-pages` gem or some other plugin. Jekyll doesn't inject CSS at any point during the build session.

**Comment by bazzle** [comment]
@ashmaroli that's exactly it, was using github-pages gem. thanks for your quick response!
