### ISSUE TITLE
Install of Jekyll 3.4.1 gem does not install tzinfo

### ISSUE THREAD

**Issue by theunrepentantgeek** [jekyll/jekyll#5935]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
---
- [x] I am on (or have tested on) ***Windows*** 10+
---
- [x] It was another bug.

## My Reproduction Steps

Install Jekyll 3.4.1
```
gem install Jekyll
```
Installation worked.

Attempting to build my site (via a PowerShell script) gave this error
```
Configuration file: C:\dev\www.nichesoftware.co.nz\src/_config.yml
  Dependency Error: Yikes! It looks like you don't have tzinfo or one of its dependencies installed. In order
  to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is:
  'cannot load such file -- tzinfo' If you run into trouble, you can find helpful resources at
  https://jekyllrb.com/help/!
```

## Manual Fix

To work around the issue, I installed `tzinfo` manually
```
gem install tzinfo
```

I then got a different error:
```
Configuration file: C:\dev\www.nichesoftware.co.nz\src/_config.yml
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:182:in `rescue in create_default_data_source': No source of timezone data could be found. (TZInfo::DataSourceNotFound)
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving this error.
```

Fixing this required manual installation of `tzinfo-data`
```
gem install tzinfo-data
```

From what I found online, I only needed this last step because I'm running 64 bit Ruby on Windows

## Expectation

The Jekyll gem should reference `tzinfo` as a dependency, and possibly `tzinfo-data` as well.

As much as anything else, I'm logging this issue so that someone searching this repo for `tzinfo` can find a workaround for the issue.

/cc @jekyll/build @jekyll/windows

**Comment by ashmaroli** [comment]
`tzinfo-data` is only required for Windows, but is automatically included in the Gemfile when you create a new site with `jekyll new` using `v3.4.x` and will be installed by bundler as part of `jekyll new`.
Our documentation had also been updated to inform users about this change.

**Comment by pathawks** [comment]
@jekyll/windows

**Comment by ashmaroli** [comment]
[Discussion in feature pull](https://github.com/jekyll/jekyll/pull/5612#discussion_r90283148)

**Comment by pathawks** [comment]
Is there a reason for this _not_ to be in our `gemspec`?

**Comment by ashmaroli** [comment]
`tzinfo` and `tzinfo-data` are required only by Windows users. So it didn't make sense to me to have that added to the `.gemspec` and have *everyone* install a gemset they may not require.

Since the gems are built based on the packaging environment, adding a Platform-check in the gemspec is also futile, as it will be ignored when Parker *et al* builds a `jekyll` gem for release on their non-Windows machine.

The best solutions are:
  - releasing a platform-specific version like nokogiri
  - document the special requirement (for older users n new), and partially absorb the overhead by having *newly generated* `Gemfile`s include the gems out-of-the-box. (Current approach)

**Comment by pathawks** [comment]
> Since rubygems are built based on the packaging environment, adding a Platform-check in the gemspec is also futile, as it will be ignored when Parker et al builds a jekyll gem for release on their non-Windows machine.

That's right. I remember now :man_shrugging:

**Comment by theunrepentantgeek** [comment]
Versioning of gems is more complicated than I thought. 😮 

If there's no good current solution, I'm happy for this issue to be closed.

**Comment by erikyuzwa** [comment]
Just appending on this issue. Not with the intent on "reopening", but I've tried both the 64 and 32-bit builds of ruby2.4.1-2 on the latest Windows10 and need to rollback Jekyll `v3.5.2` to a previous release. And yes, I have installed both the `tzinfo` and `tzinfo-data` gems (in each 32/64 session).
```
 Dependency Error: Yikes! It looks like you don't have tzinfo or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- tzinfo' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
jekyll 3.5.2 | Error:  tzinfo
```
FWIW

**Comment by erikyuzwa** [comment]
removing comment. I got it working on the latest Jekyll `v.3.5.2` - ummm user error?

**Comment by ashmaroli** [comment]
@erikyuzwa It should be working on previous releases as well.. Can you please report back after checking again with `v3.5.1` and if possible with `v3.4.x` too? Thanks

**Comment by erikyuzwa** [comment]
the REAL issue is my ruby-n00bness @ashmaroli. I was just doing `gem install tzinfo`, but it was only installing the gem on my system ("globally"?) which Jekyll just couldn't find. 
I needed to add `gem 'tzinfo', '1.2.3'` and `gem 'tzinfo-data', '1.2017.2'` to the `Gemfile` in order for everything to work. As I said -- my ruby n00bness. 🍼
