### ISSUE TITLE
Jekyll Image Variable

### ISSUE THREAD

**Issue by lffg** [jekyll/jekyll#5939]
Hi everyone,

Now, I just tried to do this:

**In the post:**
```
---
title: THE_TITLE
img: http://i.imgur.com/kX22nWu.png
---
```

**In the main layout:**
`<img src="{{ post.img }}" class="post-card-img" alt="{{ post.title }}" />`

However, it is not working. =(

---

Can someone help me?
Thanks a lot.

**Comment by pnn** [comment]
there's not really enough information to justify a good answer here. are
you correctly looping through the posts? what does your mail layout look
like? what versions are you running?




On Tue, Mar 7, 2017, at 11:23 PM, Luiz Felipe wrote:

> Hi everyone,



> Now, I just tried to do this:



> *In the post:*

> --- title: THE_TITLE img: http://i.imgur.com/kX22nWu.png ---



> *In the main layout:*

> <img src="{{ post.img }}" class="post-card-img" alt="{{
> post.title }}" />
> However, it is not working. =(



> 

> Can someone help me?

>  Thanks a lot.



> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 




Links:

  1. https://github.com/jekyll/jekyll/issues/5939

**Comment by lffg** [comment]
> you correctly looping through the posts?
Yes, I just quoted a part of the code.

I'm running in version **_3.4.1_**.

Thanks for answering. =)

**Comment by pnn** [comment]
i'd like to kindly redirect you to https://talk.jekyllrb.com/, where these kinds of questions are answered. the jekyll bug tracker is used for... well, bugs, not questions related to usage. judging as how this doesn't really seem like a bug, i believe it'd fit on the talk forum 😄
