### ISSUE TITLE
feat(404): customized 404 page

### ISSUE THREAD

**Issue by MiniJerome** [jekyll/jekyll#5944]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I am on (or have tested on) ***Docker*** image

---

## The Awesome Feature I dream of

Hey, 

I would like to customize a 404 page. I have insert the following code at the line 332 of the file `/usr/lib/ruby/2.3.0/webrick/httpresponse.rb `: 

```
    def create_error_page                                                                                        
      @body = ''                                                  
      @body << <<-_end_of_html_                                   
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">                                                                                       
<HTML>                                                                    
  <HEAD><TITLE>#{HTMLUtils::escape(@reason_phrase)}</TITLE></HEAD>
  <BODY>                                                  
    <H1>#{HTMLUtils::escape(@reason_phrase)}</H1>         
    <HR>                                                  
    <P>Custom error page!</P>                                    
  </BODY>                                                                   
</HTML>                                                        
      _end_of_html_                                            
    end    
```

Then I have adding this example page (404.md) in the root dir of my website: 

```
---
layout: post
title: Lost in Internet
permalink: /404.html
comments: false
---

Welcome nowhere!
``` 

Then every requests to anything that doesn't exists are redirected to this page instead of : 

```
Not Found

`/pouet' not found.
WEBrick/1.3.1 (Ruby/2.3.3/2016-11-21) at your-domain-name:port
```

Anyway, let's me know if this is possible to add this feature. 

Thanks!

**Comment by pathawks** [comment]
I don't think we intend for users to use Webrick in production. Can you provide any detail regarding _why_ you need this?

**Comment by ashmaroli** [comment]
I don't see the need of patching WEBrick. The best solution would be to install the `404.md` via `jekyll new`. You're welcome to create a pull implementing that.

**Comment by MiniJerome** [comment]
Well, I'm confusing this issue seems to be useless.
