### ISSUE TITLE
Jekyll breaks when using uri_escape on a string containing a colon after a space

### ISSUE THREAD

**Issue by cameronmcefee** [jekyll/jekyll#5954]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

1. Insert this snippet anywhere in a Jekyll page (works in index.html)
  `{{ 'Foo : Bat' | uri_escape }}`
2. Receive error: *Liquid Exception: Invalid scheme format: Foo in index.html*

I've noticed that this is dependent on the colon following a space somewhere before it in the string. It doesn't have to be immediately before. For example:

`{{ 'Foo : Bat' | uri_escape }}` - Fail
`{{ 'Foo bar: Bat' | uri_escape }}` - Fail
`{{ 'Foo: Bat' | uri_escape }}` - Pass

## The Output I Wanted

The page should build successfully, and the string should be escaped.

**Comment by FriesFlorian** [comment]
Hi @cameronmcefee, I'm glad you brought this issue up, I spent a couple hours trying to figure out what went wrong with my project. As you will see below, the problem is more complex that wether or not there's a space in front of the colon.

**These strings will pass uri_escape**
"test # : whatever"
"test: whatever"

**These won't**
"test : whatever" 
"test foo: whatever"

I have no idea why this is happening.

**Comment by pathawks** [comment]
@FriesFlorian You are right.

Addressable thinks we are trying to escape a full URI, instead of just a URI component.

**Comment by cameronmcefee** [comment]
<3

**Comment by parkr** [comment]
@cameronmcefee If you're using GitHub Pages :octocat:, you can watch progress here: https://github.com/github/pages-gem/pull/425 – I'll try to ship this 🔜 !

**Comment by kainjow** [comment]
We literally just patched our code to use `cgi_escape` to workaround this issue with 3.4.2. Glad it's been fixed :)
