### ISSUE TITLE
Problems converting minima seeded jekyll page to cayman

### ISSUE THREAD

**Issue by turingsmachine** [jekyll/jekyll#5956]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [x] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

I was trying to edit a jekyll page created locally which is seeded with the minima theme to carry the cayman theme as my hope is to upload to github pages. I followed the following steps after jekyll installation

user$ jekyll new personal #this creates a new personal site with the minima theme
I then try and change the theme on this page to the cayman theme. To do so I go to the gemfile, uncomment gem "github-pages", group: :jekyll_plugins and comment out gem "jekyll", "3.4.2"
I also add gem "jekyll-theme-cayman" to add the cayman theme in the gemfile, and run bundle update and bundle install.

after I do this I get
This seems to work, until I try to load the site locally using

user$ bundle exec jekyll serve
Configuration file: /Users/user/Desktop/personal/_config.yml
Configuration file: /Users/user/Desktop/personal/_config.yml
Source: /Users/user/Desktop/personal
Destination: /Users/user/Desktop/personal/_site
Incremental build: disabled. Enable with --incremental
Generating...
Build Warning: Layout 'post' requested in _posts/2017-03-15-welcome-to-jekyll.markdown does not exist.
Liquid Exception: Could not locate the included file 'icon-github.html' in any of ["/Users/user/Desktop/personal/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in about.md
jekyll 3.4.1 | Error: Could not locate the included file 'icon-github.html' in any of ["/Users/user/Desktop/personal/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.

I emailed github pages and they said it I should contact the Jekyll team. Please help! I am a novice to jekyll.

**Comment by ashmaroli** [comment]
Hi @turingsmachine this has been partially resolved on the `master` branch and will be available with the next release.  
The crux of the resolution is to simply remove all the `{% include -- %}` from your `about.md` and you should be able to `serve` successfully.  
**Note:** you'll need to comment out `layout: --` from the` .md` and `.markdown` files to remove the warning messages. `github-pages` gem will automatically use the required layout for those pages.

**Comment by DirtyF** [comment]
Closing this as this is fixed in #5903
