### ISSUE TITLE
[Feature Request] MD5/SHA256 Liquid Hashing

### ISSUE THREAD

**Issue by 10by10pixel** [jekyll/jekyll#5967]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

---

I mentioned this on [Jekyll Talk](http://talk.jekyllrb.com/t/md5-sha256-hashing-using-liquid/329) and didn't get much response so I'm hoping to see something here. I have found no method of automatically generating a hash from a string or a file which is unfortunate. I ran into a need for this on a project when I wanted to bust cache on a CSS file and had to use commit date instead of hash. This means each time I commit, whether it affects that file or not cache is busted. It'd also be useful for those who are using Github pages to host a javascript library and want to do an integrity check. I'm open to thoughts and questions about my proposal but I think it'd be a mistake not to implement this.

**Comment by pathawks** [comment]
I have [a trivial Liquid plugin](https://github.com/pathawks/liquid-md5/blob/master/lib/liquid-md5.rb) that creates a hash from a string. Would be trivial to extend it to work with files or other algos.

**Comment by 10by10pixel** [comment]
Would it be possible to build it in to Jekyll or even the `github-pages` gem? This seems important for those who use Jekyll for documentation of their software projects.

**Comment by pathawks** [comment]
> Would it be possible to build it in to Jekyll

Possible yes, but I don't think it is currently on the roadmap.

> or even the `github-pages` gem?

Yes, though you'll want to ask them about that. You may also be interested in github/pages-gem#189
