### ISSUE TITLE
[Feature request] Support tab-separated .tsv files in _data

### ISSUE THREAD

**Issue by Crissov** [jekyll/jekyll#5979]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [X] This is a feature request.

- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [X] I had an error on GitHub Pages and I did not test it locally.
- [X] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

- Put a tab-separated file with the TSV (not CSV) extension into the data folder: `_data/{filename}.tsv`.
- Check whether Github.com renders it as a table.
- Try to use it with `site.data.{filename}` in Liquid tags in a Jekyll-parsed file.

## The Output I Wanted

Same as if I had used `.csv`.

**Comment by pathawks** [comment]
This sounds like it would make a great plugin!

I'm not sure enough people would use it to necessitate its inclusion in Jekyll core.

**Comment by Crissov** [comment]
Seriously? I mean, if it was active by default on Github, I wouldn't care that it's actually a plugin, but comma, semicolon and tab separated files are treated so much alike that I really don't see why one should be in the core, but the other should not.

**Comment by DirtyF** [comment]
TSV format is less common than CSV or JSON and we aim to only include features that at least 80% of our users would use. So most of the times, the plugin rule applied.

That said, you're right, so maybe @jekyll/core could be willing to accept a proper PR with tests.

**Comment by danielsaidi** [comment]
+1 for this issue. I now have to post process a data file I receive quite often, which I shouldn't have to if Jekyll would support tab separated data files or of the box.

**Comment by parkr** [comment]
Some light googling indicates that this would be a very small change.

**Comment by parkr** [comment]
I'd be happy to add support in core. Just need a PR which adds support and has appropriate tests.
