### ISSUE TITLE
ruby error when run jekyll serve

### ISSUE THREAD

**Issue by jcesarstef** [jekyll/jekyll#5986]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [X] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [X] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

Hello, i trying to set an lab in my ubuntu server and when i run `# jekyll server` its return this error:

```
jekyll serve
/var/lib/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/drops/document_drop.rb:8: warning: already initialized constant Jekyll::Drops::DocumentDrop::NESTED_OBJECT_FIELD_BLACKLIST
/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb:8: warning: previous definition of NESTED_OBJECT_FIELD_BLACKLIST was here
/var/lib/gems/2.3.0/gems/jekyll-3.4.3/lib/jekyll/drops/drop.rb:8: warning: already initialized constant Jekyll::Drops::Drop::NON_CONTENT_METHODS
/usr/lib/ruby/vendor_ruby/jekyll/drops/drop.rb:8: warning: previous definition of NON_CONTENT_METHODS was here
Configuration file: /home/user/particle-master/_config.yml
Configuration file: /home/user/particle-master/_config.yml
            Source: /home/user/particle-master
       Destination: /home/user/particle-master/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: undefined method `includes_load_paths' for #<Jekyll::Site:0x00558876e24218> in _layouts/treinamento.html
jekyll 3.1.6 | Error:  undefined method `includes_load_paths' for #<Jekyll::Site:0x00558876e24218>


```

**Comment by pathawks** [comment]
It looks like you have multiple versions of Jekyll installed and they are not playing nicely with one another.

Are you [using Bundler?](https://jekyllrb.com/docs/quickstart/#about-bundler) Try `bundle exec jekyll serve`

**Comment by jcesarstef** [comment]
Return me this:

```
sudo gem install bundle
Fetching: bundle-0.0.1.gem (100%)
Successfully installed bundle-0.0.1
Parsing documentation for bundle-0.0.1
Installing ri documentation for bundle-0.0.1
Done installing documentation for bundle after 0 seconds
1 gem installed
user@ubuntu:~/particle-master$ sudo bundle exec jekyll serve
Could not locate Gemfile or .bundle/ directory
usser@ubuntu:~/particle-master$ bundle exec jekyll serve
Could not locate Gemfile or .bundle/ directory


```

**Comment by ashmaroli** [comment]
the gem name is not `bundle` but `bundler`.
But you seem to have `bundler` installed already from the last couple of messages.

From your previous post, it looks like you created a Jekyll site with an older version of Jekyll.  Initialize a `Gemfile` by running command `$ bundle init` from within your `particle-master/` and edit the created `Gemfile` as following:

```ruby
source "https://rubygems.org"

gem "jekyll", "~> 3.4"

group :jekyll_plugins do
  # place any gem-based plugins here
end

**Comment by pathawks** [comment]
And don't use `sudo`
