### ISSUE TITLE
Installing a plugin with _config.yml is broken

### ISSUE THREAD

**Issue by yudina-m** [jekyll/jekyll#5990]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

- [x] I am on (or have tested on) ***macOS*** 10+
- [x] It was another bug.

## My Reproduction Steps

Option 2 in this documentation doesn't work https://jekyllrb.com/docs/plugins/

As stated 

> In your `_config.yml` file, add a new array with the key gems and the values of the gem names of the plugins you’d like to use.

My current example:
```
gems: [jekyll-feed, jekyll-paginate, jekyll-docs]
```
After `gem install jekyll-paginate` and `gem install jekyll-docs` the result of `gem list --local`:

```
*** LOCAL GEMS ***

addressable (2.5.0)
bigdecimal (default: 1.3.0)
bundler (1.14.6)
colorator (1.1.0)
did_you_mean (1.1.0)
ffi (1.9.18)
forwardable-extended (2.6.0)
io-console (default: 0.4.6)
jekyll (3.4.3)
jekyll-docs (3.4.3)
jekyll-feed (0.9.2, 0.9.1)
jekyll-paginate (1.1.0)
jekyll-sass-converter (1.5.0)
jekyll-watch (1.5.0)
json (default: 2.0.2)
kramdown (1.13.2)
liquid (3.0.6)
listen (3.0.8)
mercenary (0.3.6)
minima (2.1.0)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.3)
pathutil (0.14.0)
power_assert (0.4.1)
psych (default: 2.2.2)
public_suffix (2.0.5)
rake (12.0.0)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rdoc (default: 5.0.0)
rouge (1.11.1)
safe_yaml (1.0.4)
sass (3.4.23)
test-unit (3.2.3)
xmlrpc (0.2.1)
```

There are still errors
```
  Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
jekyll 3.4.3 | Error:  jekyll-paginate
```
And
```
You must install the 'jekyll-docs' gem to use the 'jekyll docs' command. 
```

I had to do option 3 as well from https://jekyllrb.com/docs/plugins/

> Add the relevant plugins to a Bundler group in your `Gemfile`. Now you need to install all plugins from your Bundler group by running single command `bundle install`

So I edited my `Gemfile`
```
# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
   gem "jekyll-paginate"
   gem "jekyll-docs"
end
```
and run `bundle install`. Now it works, but documentation says

> `_plugins`,` _config.yml` and `Gemfile` can be used simultaneously. You may use any of the aforementioned plugin options simultaneously in the same site if you so choose. Use of one does not restrict the use of the others.

But the second option is broken. This looks like a bug.

## The Output I Wanted

I thought that the second option from the documentation would be working https://jekyllrb.com/docs/plugins/

**Comment by ashmaroli** [comment]
@yudina-m its actually not a bug in the code but rather a lapse in the documentation. Option 2 will work as  noted if you don't have multiple versions of any of the installed gems on your system and simply run Jekyll without Bundler i.e. `$ jekyll build` or `$ jekyll serve` etc. This is how `github-pages` gem works FYI.

When you run a Jekyll command through Bundler, only those gems included in the `Gemfile` are available for execution. Ergo, **option 2** will work with `Bundler` if you simply add those plugins *outside* the `:jekyll_plugins` group

**Comment by yudina-m** [comment]
But I don't have multiple versions of any of the installed gems. And tried `$ jekyll build` and `$ jekyll serve` etc. 
But maybe there should be a fix in the documentation, it's ok too :)

**Comment by pathawks** [comment]
> But I don't have multiple versions of any of the installed gems.
  
> ```
> jekyll-feed (0.9.2, 0.9.1)
> ```

**Comment by yudina-m** [comment]
```
*** LOCAL GEMS ***

addressable (2.5.0)
bigdecimal (default: 1.3.0)
bundler (1.14.6)
colorator (1.1.0)
did_you_mean (1.1.0)
ffi (1.9.18)
forwardable-extended (2.6.0)
io-console (default: 0.4.6)
jekyll (3.4.3)
jekyll-docs (3.4.3)
jekyll-feed (0.9.2)
jekyll-paginate (1.1.0)
jekyll-sass-converter (1.5.0)
jekyll-watch (1.5.0)
json (default: 2.0.2)
kramdown (1.13.2)
liquid (3.0.6)
listen (3.0.8)
mercenary (0.3.6)
minima (2.1.0)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.3)
pathutil (0.14.0)
power_assert (0.4.1)
psych (default: 2.2.2)
public_suffix (2.0.5)
rake (12.0.0)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rdoc (default: 5.0.0)
rouge (1.11.1)
safe_yaml (1.0.4)
sass (3.4.23)
test-unit (3.2.3)
xmlrpc (0.2.1)
```
Still
```
Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
```

**Comment by blairmacintyre** [comment]
So, moving the `gem: .....` to the Gemfile solved one problem.

But, now `bundle exec jekyll b` is not loading the `*.rb` files I have in `_plugins`, so liquid is not finding any of the tags I've installed there.

**Comment by MathiasSM** [comment]
I have a similar problem to @blairmacintyre. I have plugins loaded with bundler in my Gemfile and noted in `_config.yml`, and they work great, but not a single plugin in the `_plugins` directory works. In my case, I use `bundle exec jekyll b --source "_source"`, and it doesn't seem to matter if the `_plugins` directory is inside the `_source` or outside. Should I open a new issue on thie?

**Comment by ashmaroli** [comment]
@MathiasSM A new dedicated issue ticket would be great.

**Comment by blairmacintyre** [comment]
BTW, I no longer have this problem, and I wish I'd come back and made a note of how I fixed it.  Is there any chance you have github-pages in your Gemfile?  My last "trying to get this working commit" removed that from my Gemfile (and added the plugins I actually needed) and then added `plugins_dir:     ./_plugins` to my _config

**Comment by pathawks** [comment]
> My last "trying to get this working commit" removed that from my Gemfile

That would do it. No custom plugins will load when using `github-pages` because of their whitelist.

**Comment by MathiasSM** [comment]
@ashmaroli Oh my. After hours looking for an answer, finally I checked and realized that I was setting site.safe to true, thus disabling custom plugins. I feel a bit dumb.

**Comment by flashjames** [comment]
I also had this problem, and more specifically when using Liquid templates and bundler. 

I documented the problem here, maybe it can be of help for anybody else stumbling upon the same problem. https://stackoverflow.com/questions/47263333/loading-local-libaries-in-jekyll-liquid-template-library-ruby-bundler/47264025#47264025
