### ISSUE TITLE
favicon.ico not found error

### ISSUE THREAD

**Issue by roopeshm45** [jekyll/jekyll#5991]
![1](https://cloud.githubusercontent.com/assets/24458050/24421252/700591c0-13aa-11e7-84f4-a4c630cc9a0a.png)
![2](https://cloud.githubusercontent.com/assets/24458050/24421254/7507c6ac-13aa-11e7-9d0c-57542afe4696.png)

jekyll server is running.but when i tried to run localhost:4000, it displays an index of page and not the jekyll page as i expected.the command prompt shows favicon not found.﻿

**Comment by pathawks** [comment]
It looks like Jekyll couldn't find a configuration file; are you sure you are running Jekyll from inside your project directory?

**Comment by pathawks** [comment]
I'm not sure this is a bug in Jekyll.

If you have found a bug, please provide steps for somebody to reproduce the issue you are having.

If you are looking for help with getting Jekyll up and running, please do make use of https://talk.jekyllrb.com

**Comment by DirtyF** [comment]
As far as the default favicon is concerned, [Minima, the default them](https://github.com/jekyll/minima/)e doesn't have one by default because it's something you typically have to customize, and the error is a good reminder that you should add one. 😃

**Comment by pathawks** [comment]
@DirtyF It looks like there isn't _anything_ in the generated site, judging by the empty index page.

**Comment by ashmaroli** [comment]
I'm guessing, @roopeshm45 simply created a new directory and ran `jekyll serve` on it instead of scaffolding from `jekyll new --` first..

**Comment by DirtyF** [comment]
@pathawks maybe but the issue raised is easily reproductible:

```sh
~/code/jekyll/themes/minima master*
❯ bundle exec jekyll serve --source example
Configuration file: example/_config.yml
Configuration file: example/_config.yml
            Source: example
       Destination: /Users/frank/code/jekyll/themes/minima/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.654 seconds.
 Auto-regeneration: enabled for 'example'
Configuration file: example/_config.yml
    Server address: http://127.0.0.1:4000/minima/
  Server running... press ctrl-c to stop.
[2017-03-28 21:02:17] ERROR `/favicon.ico' not found.
```

**Comment by ashmaroli** [comment]
> but when i tried to run localhost:4000, it displays an index of page and not the jekyll page as i expected

his real concern could be in this quote and not in the title of this ticket.

**Comment by roopeshm45** [comment]
thank you.. thank you all.. very much for your valuable time. the problem was in connection with installing bundle inthe project directory. now everything works fine :)
