### ISSUE TITLE
Jekyll processes liquid tags differently in php files

### ISSUE THREAD

**Issue by neorganic** [jekyll/jekyll#5998]
Hello, so it looks like Jekyll processes liquid tags differently in php files.

For e.g. :

` <meta name="description" content="{% if page.meta %}{{page.meta}}{% elsif page.content %}{{ page.content | strip_html | strip_newlines | truncate: 160 }}{% else %}{{ site.description }}{% endif %}">`

In php files this resolves to:

`      <meta property="og:description" content="                Sorry, there where problems with your form:                $error                Please go back and fix the problems.                ";    } ..." />`

in html files everything works as it should be.

How to avoid/fix this issue ?

**Comment by pathawks** [comment]
I'm not sure I understand the problem.

Can you give an example of “everything works as it should be,” with the specific differences you are seeing?

I'm suspecting the problem is not with Liquid

**Comment by neorganic** [comment]
So it was just truncating parts of the php code - that's were the error was coming. Somehow missed this logic at first.... my bad. Issue closed.
