### ISSUE TITLE
{% if post.categories == 'projects' %} return false when I have post that categories is `projects`

### ISSUE THREAD

**Issue by Neutree** [jekyll/jekyll#6004]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

---

what I want to is like this:[Retrieving items based on front matter propertiesPermalink](https://jekyllrb.com/tutorials/navigation/#scenario-7-retrieving-items-based-on-front-matter-properties),but when I retrieving items based on `categories`, error hapen!

I use
```
{% if post.categories == 'projects' %}
```
like [this way](https://github.com/Neutree/Neutree.github.io/blame/master/projects.md)
![image](https://cloud.githubusercontent.com/assets/8625829/24622914/44107182-18d9-11e7-8465-d1d706c5e1da.png)
to classify category `projects` and want to make a list of it. But the `if` condition not work(if condition return false)!!!!!
I have created two post that category is `projects` and `test`,but this condition can't pass,it's very strange... ...
the [output](https://neucrack.com/projects.html) is:
![image](https://cloud.githubusercontent.com/assets/8625829/24623022/ad7529d8-18d9-11e7-9fe2-41e7ffe5b76d.png)

when I change 
```
{% if post.categories == 'projects' %}
```
to
```
{% if post.c == 'projects' %}
```
It passed(if confition return true).

Is that I did wrong somewhere or it's a bug?

**Comment by Neutree** [comment]
finally I change 
```
---
layout: default
title: jekyll web
description: build a web by jekll
categories: projects
---
```
to
```
---
layout: default
title: jekyll web
description: build a web by jekll
category: projects
---
```
and change
```
{% if post.categories == 'projects' %}
```
to
```
{% if post.category == 'projects' %}
```

finally,I get the right output.
But I remain can not understand why this error happen only when I use keyword `categories`!!!!

**Comment by pnn** [comment]
@Neutree it's because `post.categories` is formatted as an array, since it's spelled in plural. `post.category` only includes one category!

**Comment by Neutree** [comment]
**thanks!**
**got it!**

now I change to
```
<ul>
  {% for post in site.posts %}
  	{% for category in post.categories %}
		{% if category == 'projects' %}
		    <li class="post_list_item">
		      <h1><a href="{{ post.url }}">{{ post.title }}</a></h1>
		      <h4>{{ post.date | date: '%B %d, %Y' }}</h4>
		      <i>{{ post.excerpt }}</i>
		    </li>
		{% endif %}
	{% endfor %}
  {% endfor %}
</ul>
```

It work now!
