### ISSUE TITLE
jekyll replaces characters

### ISSUE THREAD

**Issue by fliiiix** [jekyll/jekyll#6016]
- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [X] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [X] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [X] It was another bug.

## My Reproduction Steps

1. `$ jekyll new blog`
2. write a blog post with these characters (**'**, **"**, **...**)
3. `$ jekyll build`

The characters getting replaced:
**'** by **’** 
**'** by **‘** 
**"** by **“** 
**"** by **”** 
**...** by **…** 
**--** by **–** 

(and probably more)

## The Output I Wanted

The original character I used in in my .md file.

**Comment by Crunch09** [comment]
Can confirm this behavior.

**Comment by Crunch09** [comment]
@fliiiix Hey, these are the default settings of the `kramdown` parser which parses your markdown and generates the HTML output. You can override them in your `_config.yml`. You can see an example in this [answer on StackOverflow](http://stackoverflow.com/a/25597026) or see the [kramdown documentation](https://kramdown.gettalong.org/rdoc/Kramdown/Options.html).

**Comment by pathawks** [comment]
Thanks @Crunch09 :+1:
