### ISSUE TITLE
Running jekyll on Bash on Ubuntu on Windows with --watch does nothing!

### ISSUE THREAD

**Issue by PedroLamas** [jekyll/jekyll#6023]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10 Creators Update (10.0.15063)

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

In Bash on Ubuntu on Windows, I created a brand new Jekyll site and run `jekyll serve --watch` to serve it.

Unfortunately it seems to be ignoring the `--watch` argument:

![image](https://cloud.githubusercontent.com/assets/85504/24948045/e9269f10-1f60-11e7-8805-80da5ff8de9d.png)

## The Output I Wanted

According to [this article](https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/), Windows 10 Creators Update now has "File change notification support (INOTIFY)", so I'd expect Jekyll to respect the `--watch` argument and watch for file changes, but that doesn't seem to be the case!

**Comment by PedroLamas** [comment]
@jekyll/windows might be interested in this!

**Comment by markspolakovs** [comment]
Cannot reproduce with Jekyll 3.3.1 on Ruby 2.3.3, Windows 10.0.15063.
![image](https://cloud.githubusercontent.com/assets/2904440/24962007/ddad37ea-1f9a-11e7-9357-a5397a2f93a1.png)

**Comment by PedroLamas** [comment]
I'm using the latest 3.4.3 (from github-pages gem), might be related to that!

**Comment by markspolakovs** [comment]
Hmm, nope, still no repro.
![image](https://cloud.githubusercontent.com/assets/2904440/24962470/51c8823c-1f9c-11e7-8fea-f8fe18a516d8.png)

**Comment by PedroLamas** [comment]
Did you update bash? I also did a clean install of bash after the Creators Update!

This is what I get when I run `lsb_release -a`:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

What do you get?

**Comment by markspolakovs** [comment]
Whoops, yeah, that's probably it. Let me try a clean install and I'll get back to you.

**Comment by markspolakovs** [comment]
Still can't reproduce.

![image](https://cloud.githubusercontent.com/assets/2904440/24964564/ee535870-1fa1-11e7-8b18-a2b89b07605d.png)

**Comment by PedroLamas** [comment]
Oh, might be my system then... 😞 I'll run some tests and see if I can find out what's going on!

**Comment by PedroLamas** [comment]
So I just did a clean install of bash, by running:

```
C:\> lxrun /uninstall /full /y
...
C:\> lxrun /install
```

Open bash for the first time and ran

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git nodejs inotify-tools
```

Next, Ruby though RVM with

```
\curl -sSL https://get.rvm.io | bash -s stable --ruby=2.4.1
```

Next, went  to the folder where I have all my jekyll stuff and ran:

```
gem install bundler
bundle install
bundle update
bundle exec jekyll serve -w
```

Same result... 😞 am I missing something here?

**Comment by PedroLamas** [comment]
Ok, found the issue and it's because I added `jekyll-admin` to my Gemfile... seems it's disabling `--watch`, nothing to do directly with Jekyll. Closing issue now!
