### ISSUE TITLE
When using GitHub's theme selector page will not render.

### ISSUE THREAD

**Issue by wsender** [jekyll/jekyll#6025]
- [X ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [X ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [X ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

I build my jekyll site locally and serve the site without issue. Everything works as expected. This is using the minima theme.

I push my changes to GitHub and check the site and everything works.

I navigate to my repository settings, scroll down to GitHub Page, and select the theme I want (in this case Architect). Doing this changes my _config.yml file. If I review the commit that was created by using the theme chooser I can see that the site isn't building and the error message is as follows:

"Failure: A file was included in 'about.md' that is a symlink or does not exists in your '_includes' directory."

## The Output I Wanted

My GitHub Pages page to switch from the minima theme to the Architect (or other) theme.

**Comment by DirtyF** [comment]
This is rather a question for @jekyll/gh-pages,  `minima` could avoid using includes in `about.md` in order to avoid this type of failure. Please open an issue on https://github.com/jekyll/minima asking for compatibility as this issue  is not related to Jekyll's core. Thanks!
