### ISSUE TITLE
What is the difference between {% highlight %} & ``` & ~~~~~~

### ISSUE THREAD

**Issue by atefhares** [jekyll/jekyll#6029]
Hi,

I am confused between:
 this way:  {% highlight %}
 &
  this way:  ``` 
&
 this way:   ~~~~~~

for syntax Highlighting, I have setup rogue but each one of the above gives me different code block style, and I can't even edit this style, for example allow line_numbers to be inside the code block. not separated on left of it.

See my STO question: http://stackoverflow.com/questions/43417188/customizing-code-blocks-style-in-jekyll

Can you help?

**Comment by DirtyF** [comment]
Please rather ask on https://talk.jekyllrb.com, this repo is for issues with Jekyll's core source code only.
Thanks!
