### ISSUE TITLE
linking between page

### ISSUE THREAD

**Issue by danielyang1009** [jekyll/jekyll#6036]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I am on (or have tested on) ***Windows*** 10+
- [x] I was trying to build.

## My Reproduction Steps

I was trying to link between my posts. 

```liquid
[Jekyll Archive By Tag]({% post_url 2017-04-16-jekyll-archive-by-tag %})
```
And I double check my file name is "2017-04-16-jekyll-archive-by-tag.md"

However I received error message, 

```sh
Regenerating: 1 file(s) changed at 2017-04-19 14:59:10        Deprecation: A call to '{{ post_url 2017-04-
16-jekyll-archive-by-tag }}' did not match a post using the new matching method of checking name 
(path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.
```
And I find that it still generate the link for me. and it works. And my call is to `{% post_url %}` not `{{ post_url }}`

**Comment by DirtyF** [comment]
I see your directory structure is `_posts/2017`, how about if you change it to `2017/_posts` ?

**Comment by DirtyF** [comment]
As your posts are in a` 2017` folder your path/date-slug is `{% post_url 2017/2017-04-16-jekyll-archive-by-tag %}`

**Comment by danielyang1009** [comment]
@DirtyF Thanks! It works. However, I've tried to move the post out of `2017/` folder, and it still produces this error. It seems jekyll will look into the folder first as long as the folder is not empty.

Second. the error message is still confusing. I'm calling `{% post_url%}` not `{{ post_url }}`

**Comment by danielyang1009** [comment]
@DirtyF already create a pull request https://github.com/jekyll/jekyll/pull/6040
