### ISSUE TITLE
site.date feature

### ISSUE THREAD

**Issue by danielyang1009** [jekyll/jekyll#6037]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

When I create my blog, I want to create two archive page, by-tag page, by-year page.
For by-tag archive page, it's easily achieved, using `site.stags.TAG`  

To create a tag archive page, I first,
```
---
layout: default
tag: jekyll
---
```
and create a `tag-page.html` in `_layout/`
```
<p>Total of {{ site.tags[page.tag] | size }} post(s)</p>
{% for post in site.tags[page.tag] %}
{{post.title}}
{% endfor %}
```

However I want to create a by-year page. There's no simple way to do it. I need to create a counter function to count post in specific year. I wonder maybe to create a `site.date` variable to include date of all posts (year, month, day, time). Then I can create a by-year page by
```
---
layout: default
year: "2017"
 ---
```
and create a `year-page.html` in `_layout/`
```
<p>Total of {{ site.date.years[page.year] | size }} post(s)</p>
{% for post in site.date.years[page.year] %}
{{post.title}}
{% endfor %}
```

**Comment by hd719** [comment]
Hello @DirtyF and @danielyang1009 can I work on this? 

-Thank you.

**Comment by DirtyF** [comment]
@hd719 Feel free to submit a PR with proper tests if you want to give it a shot

/cc @jekyll/core

**Comment by hd719** [comment]
Hello @DirtyF and @danielyang1009 I am kind of confused on what I am suppose to do here, I don't understand the feature request. If you guys can explain that I would really appreciate it. 

- Thank you.

**Comment by danielyang1009** [comment]
@hd719 @DirtyF I'm not expert in ruby, so I'm just using jekyll. And thinking it would be nice to add a feature to show archives by year. It's achievable by other way. But it would be simple to use like when you create a tag page just use 
```
{% for post in site.tags[page.tag] %}
{{post.title}}
{% endfor %}
```
**So can we add year or time or other custom labels to front matter**, and later we can load those labels using
```
site.some_custom_label
```
For example:
In my creating of archive by year page, I can use load this custom label `year`
```
---
layout: default
year: "2017"
 ---
```
and create a year-page.html in _layout/
```
<p>Total of {{ site.date.years[page.year] | size }} post(s)</p>
{% for post in site.date.years[page.year] %}
{{post.title}}
{% endfor %}
```

Hope this explanation will make thing clear.

**Comment by rukbotto** [comment]
@danielyang1009 I created this plugin: https://github.com/rukbotto/jekyll-index-pages, which can help you achieve what you want. Maybe you can give it a try.

**Comment by danielyang1009** [comment]
@rukbotto great. I will give it a try!

**Comment by parkr** [comment]
The [jekyll-archives](https://github.com/jekyll/jekyll-archives) plugin is built for this! Otherwise a bit more manual work will get you there very easily. I don't see us adding this feature into Jekyll core.
