### ISSUE TITLE
Use Thin instead of WEBrick

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#604]
Thoughts on switching to thin instead of WEBrick?

**Comment by nateberkopec** [comment]
For anyone that comes to this issue via google/other means, here's what I did:

Production/dev parity is important to me, so I wanted a webserver that would gzip content and serve it over HTTP/2, like my production setup. `h2o` does these things.

All I did was create a Procfile for use by Foreman, like so:

```
jekyll: bundle exec jekyll build -w
server: h2o -c h2o/h2o.conf
```

You can obviously replace `server` with whatever you want.
