### ISSUE TITLE
the variable can not be reached by father layout template?

### ISSUE THREAD

**Issue by rowthan** [jekyll/jekyll#6051]
there are two template in '_layout' named 'post.html' and 'default.html'

post.html
```
---
layout: default
class: post
---
```
i have define a variable named 'class' in post.html  
while default.html can not reach it

default.html
```
{% include header.html %}
i want get the variable from child template ：{{page.class}}
{% include footer.html %}
```
however, page.class is empty. is there any mistake i have made ?

but there is something puzzled me that if I rename 'post.html' to 'post.md', it work!

I just want make sure if it is possible that default.html can get the variable from post.html

**Comment by mmistakes** [comment]
Try accessing "child" layout variables in a parent "parent" layout with `layout.whatever`

In your case `layout.class`

**Comment by rowthan** [comment]
yes is works! thanks.
