### ISSUE TITLE
Handle '//' (double slash) caused by baseurl: '/'

### ISSUE THREAD

**Issue by alias1** [jekyll/jekyll#6057]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+

## My Reproduction Steps

To start off with, I realise that setting baseurl to `/` is the wrong way to do it, but in reality, it seems it is often done, and sometimes seems to be the only way to workaround other bugs/things:
* https://github.com/jekyll/jekyll-seo-tag/issues/200
* https://github.com/github/pages-gem/issues/359#issuecomment-263375327
* https://github.com/jekyll/github-metadata/issues/87
* etc

I figured that with the [relative/absolute filters added in 3.3](https://jekyllrb.com/news/#2-relative_url-and-absolute_url-filters) there was now a standard/universal place to fix this in a way that would make the end user experience easier, while possibly also hinting them towards not using the 'bad method'

```
# _config.yml
baseurl: "/"

# default.html
<h1>{{ "/docs/assets/" | relative_url }}</h1>
<h1>{{ "/docs/assets/" | absolute_url }}</h1>
```

Outputs
```
<h1>//docs/assets/</h1>
<h1>http://localhost:4000//docs/assets/</h1>
```

## The Output I Wanted

```
<h1>/docs/assets/</h1>
<h1>http://localhost:4000/docs/assets/</h1>
```

This could be achieved by using a regex/similar to strip off any trailing/leading slashes before concatenation.

For what it's worth, the hacky filter I used in my theme to work around this was:

```
module Jekyll
  module ChompSlashFilter
    def chomp_slash(input)
      input.chomp('/')
    end
  end
end

Liquid::Template.register_filter(Jekyll::ChompSlashFilter)
```

But this obviously doesn't let me work around it when it comes up in other plugins.

It would also be reasonable to expect a warning from Jekyll about how using `/` in baseurl is a bad idea/why, and how to do it better/properly (maybe a link to a blog post about it or similar).

**Comment by ashmaroli** [comment]
> but in reality, it seems it is often done

I assumed this to be an edge-case circa [this comment](https://github.com/jekyll/jekyll/pull/5542#issuecomment-258353886). Sent a PR to handle this.
Do stay tuned.

**Comment by alias1** [comment]
Thanks :) I added some inline comments to your PR
