### ISSUE TITLE
layout variable not available to index.html

### ISSUE THREAD

**Issue by stevenmunro** [jekyll/jekyll#6071]
- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I am on (or have tested on) ***macOS*** 10+

jekyll 3.4.3

I have index.html in my working directory. The frontmatter for this file is:

`---`
`layout: default`
`title: homepage`
`---`

in the _layouts directory, I have a file named default.html - the frontmatter for this file is:

`---`
`nav:`
` - text: Home`
`   url: /`
` - text: Second Page`
`   url: /second-page/`
` - text: Third Page`
`   url: /third-page/`
`---`

Inside index.html, I am including a file from the _includes directory.

`{% include nav.html %}`

The contents of nav.html contains my navigation aid which incorporates a for loop. Lets just say that if we put the following in here, it should output onto the page.

`{{ layout.nav }}`

For second page, and third page (they contain the same frontmatter as index) it works. The issue is that for index.html **it doesn't.**

Furthermore, index.html doesn't appear to inherit **anything** at all from the layout variable.

In my _config.yml - I have **include: ['_pages']**
The second and third pages are located in the _pages directory.

To further test, I disabled this line and reloaded the site. index.html still doesn't show anything from the layout variable.

I re-enabled **include: ['_pages']** and duplicated index.html into the _pages directory. Surprisely it now works. But the same file index.html has to be in both locations.

This seems strange and very much looks like a bug.

**Comment by stevenmunro** [comment]
The workaround is to put index.html into the _pages directory. You can safely delete the index.html in the working directory, however Jekyll will complain if it can't find any html files there, so create a temp.html and just give it some dummy frontmatter.

**Comment by stevenmunro** [comment]
Ok. I've come to the conclusion that Jekyll is **not** production ready. I'm having this issue with other pages too. For eg:

/_pages/acceptable-use-policy.html does not display layout variable

/_pages/**swear word beginning with F here**acceptable-use-policy.html - works.

There is seriously something wrong here with regex.

**Comment by pathawks** [comment]
I've been able to boil this down to the following illustration. In spite of the files being identical, `index2.html` has access to the `layout` data while `index.html` does not.

This is definitely a bug, and a strange one at that.

## index.html
```html
---
layout: default
title: homepage
---

{{ layout.nav }}
```

## index2.html
```html
---
layout: default
title: homepage
---

{{ layout.nav }}
```

## _layouts/default.html
```html
---
nav:
- text: Home
  url: /
- text: Second Page
  url: /second-page/
- text: Third Page
  url: /third-page/
---

{{ content }}
```

/cc: @jekyll/build

**Comment by stevenmunro** [comment]
Sorry if I'm a pain in the arse - but I do like to try and help where I can. I've noticed that in /_pages/ the **first file listed alphabetically** will have issues.

I created a faq.html and that could not read layout data. As soon as I created **a.html**, faq.html was working.

Hope this helps.
