### ISSUE TITLE
Jekyll site rendering HTML but not CSS on GitHub Pages

### ISSUE THREAD

**Issue by cocodevienne** [jekyll/jekyll#6076]
This is a question, not a bug. Please help me. I have a website at http://cocodevienne.github.io) and the link to the repo is here (http://github.com/cocodevienne/cocodevienne.github.io). Now when I open up my website, I do not see the layout I configured using the So Simple Theme. What can I do in order for it to work? Please help me, I at my wits end. Also, when I build the sitre locally using  bundle exec jekyll serve the site builds and I can see the layout. I also followed the instructions on GitHub fr making a website with Jekyll as outlined in the GitHub help.

**Comment by ashmaroli** [comment]
the site loads fine at my end..

**Comment by cocodevienne** [comment]
Yeah I fixed it. I had to change the "http" to "https" for whatever reason.

**Comment by cocodevienne** [comment]
Thanks though!!!
