### ISSUE TITLE
Site Template for data files

### ISSUE THREAD

**Issue by RoiEXLab** [jekyll/jekyll#6080]
I'm using jekyll for quite a while now, and I think I know how jekyll works in theory without having ever looked at the code.
I like how data files can be used to easily generate lists of content, but what if the user doesn't want a list, but an individual page for each entry instead? I believe this is currently only possible by using some workarounds, e.g. generating the list and modifying the DOM using javascript based on the query URL.
Collections seem pretty similar, but they are not quite what I would like to see in jekyll.
I know that jekyll isn't able to handle GET parameters based on the way how jekyll works.
Jekyll generates HTML files whenever the local files are changed and not when a client is requesting them.
But my idea doesn't need dynamic GET parameter handling although it seems to do at first.

I'd like to be able to create a document, a md or html file which acts as template for let's say all the data in a yaml file located in `_data`.
It could look like this:
`employeelist.yaml`
```
- id: 0
  name: John
  sirname: Doe
  rank: Software Developer
  bio: somethingsomething
- id: 1
  name: Alice
  sirname: Johnson
  rank: CEO
  bio: lucky person
- id: 2
  name: Bob
  sirname: The Builder
  rank: Project Manager
  bio: somethingsomething
- id: 3
  name: Eve
  sirname: Devil
  rank: Security Manager
  bio: somethingsomething
```
We want to have a general layout for each individual employee, but we don't want to create a site for each manually.
It would be simpler to just have a single file like we are used to and do something like this:
employee.md
```
---
datasource: site.data.employeelist
uniqueIdentifier: id
layout: page
title: {{ name }} {{ sirname }}
permalink: /employee/
---
### {{ name }} {{ sirname }}
They work at $company as {{ rank }}.
Bio: {{ bio }}
```
Jekyll would then generate a html site for each entry in our data file based on this template at `<dest_folder>/employee/<id>.html`.
John's site would then be accessible via `companyname.org/employee/0`.

A permalink might not even be needed. Another possible option would be `companyname.org/employee.html?id=0` if no permalink was specified, but I'm not sure if jekyll is able to handle such GET requests. (Using `companyname.org/employee.html/0` is simply not looking good)
The same would also work using a html file instead of markdown.
Note how we don't need to append `{{ site.data.employeelist[<id>].name }}` to each entry, because we specified this file as our data source. If this isn't working well with liquid this might need to be changed, but I hope you get the idea!

But I'm interested in your thoughts about this topic and please feel free to ask any questions if I wasn't clear enough or if I left out something!

**Comment by pathawks** [comment]
What you're looking for is collections. You need an `employee` collection with one item for each employee.

This question would be a bettr fit at https://talk.jekyllrb.com

**Comment by RoiEXLab** [comment]
But as far as I know this requires a file per entry instead of just having a single file containing all the data

**Comment by pathawks** [comment]
> But as far as I know this requires a file per entry instead of just having a single file containing all the data

@RoiEXLab That is correct. Currently, there is no way for Jekyll to generate multiple output files for a single input file.

**Comment by RoiEXLab** [comment]
Hmm what if when defining a collection and no `_collectionname` folder is present jekyll searches the `_data` folder for a file named like that collection and checks if it contains an array?
