### ISSUE TITLE
failing escape brace in post content

### ISSUE THREAD

**Issue by sillyousu** [jekyll/jekyll#6083]
- [*] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [*] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [*] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

~~~
---
title: foooo
---

```
{{ }}
```
~~~

## The Output I Wanted
no error , no warning.

```
➜  techblog git:(master) ✗ jekyll build
Configuration file: /xxx/_config.yml
            Source: /xxx
       Destination: /xxx/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
    Liquid Warning: Liquid syntax error (line 2): [:end_of_string] is not a valid expression in "{{ }}" in /xxx/_posts/2017-2-11-bug.md
    Liquid Warning: Liquid syntax error (line 2): [:end_of_string] is not a valid expression in "{{ }}" in /xxx/2017-2-11-bug.md/#excerpt
                    done in 0.356 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```
/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by pathawks** [comment]
What do you want to happen?

**Comment by sillyousu** [comment]
@pathawks  
I except jekyll/liquid can handle  `{{}}` correctly, no error, no warning.


here is case breaking build command:
~~~
---
title: bug
---

```
(gdb) print *(ucontext_t *)$rsi
$3 = {uc_flags = 0, uc_link = 0x0, uc_stack = {ss_sp = 0xdbf080, ss_flags = 0,
    ss_size = 8192}, uc_mcontext = {gregs = {0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
      14422128, 0, 0, 0, 14422120, 4198397, 0, 0, 0, 0, 0, 0}, fpregs = 0x0,
    __reserved1 = {0, 0, 0, 0, 0, 0, 0, 0}}, uc_sigmask = {__val = {
      0 <repeats 16 times>}}, __fpregs_mem = {cwd = 0, swd = 0, ftw = 0, fop = 0,
    rip = 0, rdp = 0, mxcsr = 0, mxcr_mask = 0, _st = {{significand = {0, 0, 0,
          0}, exponent = 0, padding = {0, 0, 0}}, {significand = {0, 0, 0, 0},
        exponent = 0, padding = {0, 0, 0}}, {significand = {0, 0, 0, 0},
        exponent = 0, padding = {0, 0, 0}}, {significand = {0, 0, 0, 0},
        exponent = 0, padding = {0, 0, 0}}, {significand = {0, 0, 0, 0},
        exponent = 0, padding = {0, 0, 0}}, {significand = {0, 0, 0, 0},
        exponent = 0, padding = {0, 0, 0}}, {significand = {0, 0, 0, 0},
        exponent = 0, padding = {0, 0, 0}}, {significand = {0, 0, 0, 0},
        exponent = 0, padding = {0, 0, 0}}}, _xmm = {{element = {0, 0, 0,
          0}} <repeats 16 times>}, padding = {0 <repeats 24 times>}}}
```
~~~


```
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Liquid syntax error (line 8): Variable '{{significand = {0, 0, 0, 0}' was not properly terminated with regexp: /\}\}/ in /Users/supei/Dropbox/blog/techblog/_posts/2017-05-05-bug.md
jekyll 3.4.3 | Error:  Liquid syntax error (line 8): Variable '{{significand = {0, 0, 0,
          0}' was not properly terminated with regexp: /\}\}/
```

**Comment by pathawks** [comment]
This is because you need to put the braces inside a `{% raw %}` block, so it is not processed as Liquid.

**Comment by sillyousu** [comment]
ok.
I though jekyll has full markdown text support.
Indeed, people need fix a few incompatible areas when migrating in/out jekyll.

**Comment by ashmaroli** [comment]
Jekyll uses a flavor of Markdown called [`Kramdown`](https://kramdown.gettalong.org/) which is slightly different from pure Markdown. The error here occurs due to processing of our templating language [`Liquid`](https://shopify.github.io/liquid/) which has nothing to do with Markdown..
