### ISSUE TITLE
.htaccess (dot files in general) ignored in collections

### ISSUE THREAD

**Issue by ekleinod** [jekyll/jekyll#6091]
I cannot get a .htaccess included in the output if the file is in a collection.

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

---

- [x] It was another bug.

## My Reproduction Steps

My file resides in `_pages/subdir/.htaccess.` In my config file, I use

`  collections:`
`  pages:`
`  output: true`
`  permalink: /:path.html`

to use all pages in `_pages`  without the path `_pages`

This works fine but not for the `.htaccess` file. It is ignored in the output. This is true for other dot files as well, e.g. `.htpasswd`

I tried in my config

`  include:`
`  - '.htaccess'`
`  - '_pages/.htaccess'`
`  - '_pages/subdir/.htaccess'`
`  - '*/.htaccess'`

nothing works so far.

## The Output I Wanted

I wanted the `.htaccess` file copied to the output directory as is.

/cc @pathawks

**Comment by pathawks** [comment]
Yes, this seems like a bug.

It seems like if you have `include: ['.htacess']` in your config, than `_pages/subdir/.htaccess` should be treated like any other static file in a collection.

/cc: @jekyll/build
