### ISSUE TITLE
Default _site/index.html has several large gaps

### ISSUE THREAD

**Issue by sarupbanskota** [jekyll/jekyll#6095]
Hola folks, first of all, very grateful for the kickass project you've developed :-)

------

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

------

- [x] I am on (or have tested on) ***macOS*** 10+

--------

## My Reproduction Steps

Pretty straightforward - New to jekyll, so I just ran `gem install jekyll`, created a new project with `jekyll new blog` and then `cd blog`.

I was exploring the various files made available, and couldn't help but notice that without me doing _anything_, `_site/index.html` had a lot of _large gaps_.
https://gist.github.com/sarupbanskota/08d8cc098ddc895acf58ba171c349156. Not a deal breaker, but it felt a bit annoying and _unclean_ to me.

I'm not quite sure if this was expected or if I ran something unexpectedly to cause that .. but if not, is this something I can fix on a separate PR?

Thanks!

**Comment by pathawks** [comment]
Please define “gaps”

Whitespace in the generated HTML?

**Comment by stevenmunro** [comment]
Just in case you were wondering, Jekyll doesn't do any minification by itself. The link breaks you are seeing are likely to also exist in your original index.md or index.html

I use `octopress-minify-html` for minification

**Comment by ashmaroli** [comment]
@sarupbanskota, those gaps you see are a result of Liquid tags that are present in our template includes and layouts. To fix it, you'll have to use a new tag introduced in Liquid 4.0 and submit a PR at jekyll/minima repo.

**Comment by DirtyF** [comment]
closing this as this is related to default theme jekyll/minima .

**Comment by sarupbanskota** [comment]
thanks @DirtyF - i'll PR jekyll/minima
