### ISSUE TITLE
Publish but don't include in blog front page or archive

### ISSUE THREAD

**Issue by mike-ward** [jekyll/jekyll#6096]
- [x] This is a feature request.

---

I would like an option that generates the blog article but does not include it in the blog front page or archive. One possible implementation extends the front matter key `published`

    published: hidden

**Comment by KeJunMao** [comment]
Hope useful:
```liquid
{% for p in site.posts %}
{% if p.published !="hidden" %}
{{p.title}}
{% endif %}
{% endfor %}
```

**Comment by DirtyF** [comment]
As @KeJunMao kindly shows in the example above, you can filter posts on a particular value of a front-matter variable. Could be `hidden: true` or whatever you want.
