### ISSUE TITLE
jekyll is not compiling sass files

### ISSUE THREAD

**Issue by mittalyashu** [jekyll/jekyll#6098]
Here is the preview of the image
![image](https://cloud.githubusercontent.com/assets/29014463/26550277/8b3c13ee-449a-11e7-8beb-6e8db6a0ee05.png)

As you can see in the image the main.sass file in the _site directory is the same file as in the _assets/_css/main.sass
But the file (_site/assets/css/main.sass) is not compiling into main.css

**Comment by DirtyF** [comment]
Did you add YAML Front Matter delimiters to your Sass file in order for Jekyll to process it?

```yaml
---
# Empty but necessary
---
```

Please provide a link to a public repository, it's much easier to help.

**Comment by mittalyashu** [comment]
Yes. I have added the YAML Front Matter delimiters to your Sass file. If made any mistake, plz suggest.

Here is the link to the repository: https://github.com/mittalyashu/blog

**Comment by kevinSuttle** [comment]
I'm having the same issue. https://github.com/kevinSuttle/kevinsuttle.github.io/blob/master/css/main.scss

**Comment by DirtyF** [comment]
@mittalyashu try with`assets/css`instead of `_assets/_css` 
Also beware you have two index files, you better keep one.

**Comment by DirtyF** [comment]
@kevinSuttle simply use `@import "variables"` instead of writing the relative path in your `main.scss` file

**Comment by kevinSuttle** [comment]
@DirtyF Ok, that's a separate issue though, right?     

Does Jekyll not look at changes in ./css/main.scss? That's the example given in the docs, so I figured it was the default convention.

**Comment by kevinSuttle** [comment]
Aha. `jekyll-admin` gem disables `--watch` internally. https://github.com/jekyll/jekyll/issues/4830#issuecomment-305374638

**Comment by ashmaroli** [comment]
Related question on [StackOverflow](https://stackoverflow.com/questions/43559969/jekyll-auto-regeneration-not-working-even-with-watch-used/43560078?noredirect=1#comment74171132_43560078)

**Comment by mittalyashu** [comment]
@kevinSuttle Didn't get, what just you said. 

> Aha. jekyll-admin gem disables --watch internally.

**Comment by DirtyF** [comment]
@mittalyashu https://github.com/jekyll/jekyll-admin is a plugin that provide a local UI to edit your content. Apparently when using this plugin the `--watch` option is disabled. 😕

**Comment by priyeshwalunj** [comment]
I have also faced same issue it was about specifying output style option in `config.yml`.
Kindly check Jekyll documentation : https://jekyllrb.com/docs/assets/
Hope this might solve your problem.
