### ISSUE TITLE
description field in _config.yml not reloaded

### ISSUE THREAD

**Issue by z0ph** [jekyll/jekyll#6099]
Hi, 

I'm trying to change the `description` of my blog on `_config.yml` file but, there is no way to get it done. 

I'm using `bundle exec jekyll build` to regenerate my all site, but it's still the old `description`

I understand that `bundle exec jekyll serve --watch` not reloading the `_config.yml` file from the documentation.

Any tips to help me? Thanks!

---
- [X] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

**Comment by DirtyF** [comment]
Have you tried the following sequence:

```sh
bundle exec jekyll clean
bundle exec jekyll serve
```

Is there a public repo we can access to check your files?

**Comment by z0ph** [comment]
Hello @DirtyF,

No, it's not working. Still the old description.

https://cl.ly/2d2T450l2K1t/[cc00f23323c15d985d0f3c7011ecd61f]_Image%202017-05-30%20at%2010.39.58%20AM.png

Sorry, I'm not using Git/Github to manage my versioning

**Comment by ashmaroli** [comment]
@z0ph it can hard to debug without seeing the files. Anyways, from the screenshot you posted a link to, it looks like you're using a different jekyll theme (not the default theme Minima hence not a Jekyll bug per se). It would be better if you could tell us what theme you're using, or posting a screenshot of the template that generates the `description` markup, or opening a ticket at the theme repo itself..

**Comment by z0ph** [comment]
Hi @ashmaroli 

Sorry, I'm using minimal-mistake, and my blog available here: https://blog.zoph.me/

**Comment by z0ph** [comment]
PS: There is no issue related to "Description" on the theme repo :(

**Comment by mmistakes** [comment]
@z0ph MM doesn't use `description` found in _config.yml for the [splash header](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#splash-page-layout). It pulls from whatever you've set as `excerpt` in the page's YAML Front Matter. Take a look at your `index` page and update the text there.

**Comment by z0ph** [comment]
Ho, ... Thanks @mmistakes ! Its working.
