### ISSUE TITLE
Not able to override the default CSS of Jekyll

### ISSUE THREAD

**Issue by mittalyashu** [jekyll/jekyll#6102]
I tried to write some sass code and I thought Jekyll will compile it into CSS and apply the styles.

But nor Jekyll is compiling the sass file nor applying the style.

Even when I change the link of CSS file from the index.html. Jekyll automatically set the default style sheet again and not able to override the default CSS of Jekyll

**Comment by pathawks** [comment]
This seems like more of a support question than a bug report. You would probably be better served asking at https://talk.jekyllrb.com

**Comment by mittalyashu** [comment]
Do we need to start the `jekyll serve` from command prompt every time we make any modification?

If no, then I face the same problem.

**Comment by DirtyF** [comment]
@mittalyashu Jekyll compiles changes to Sass files when running `bundle exec jekyll serve` (the `--watch` is true by default). 

Please rather ask for help on https://talk.jekyllrb.com and give more context. 
This repo is for bugs only, not usage.

**Comment by mittalyashu** [comment]
Sure. Thanks
