### ISSUE TITLE
Date in filename requirement

### ISSUE THREAD

**Issue by noraj1337** [jekyll/jekyll#6104]
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [X] This is a feature request.
- [X] I am on (or have tested on) ***Arch*** GNU/Linux, (Manjaro in fact)

---

The `posts` collection require files to be named `YEAR-MONTH-DAY-title.MARKUP`.
But:
+ I don't like it
+ This is a waste of time
+ This is painful
+ This make filename longer
+ This make filename less pretty
+ This *may* create redundancy with `date` front matter
+ This make post files less exportable and less usable for other uses (renaming filename needed)
+ This is dirty (expet to keep post in order)

So not putting teh date is the inverse of that plus:
- More easy for beginners that don't understand why they can't see their page or compile fails because they didn't put date in the filename or wrongly format it.

I understand that *posts* are *posts* like blog posts so that they requrie a date **BUT** they don't need the date to be provided in the filename.

In fact I prefer to have a filnename like `title.MARKUP` and use the `date` Front Matter like in [Hexo](https://hexo.io/). (I'm no talking about permalinks that are already customizable)

I also understand that you don't want to migrate from title date requirement to front matter date requirement as it will need ~work~ migration to not brake already existing blogs.

But at least you ~MUST~ should create an option in `_config.yml` to switch the date requirement from title to front matter.

I'm not asking to:
- delete date requirement in posts filename
- switch from filename requirement to front matter requirement

I'm just asking to:
- add on option to allow to from filename requirement to front matter requirement

(~Right now I prefer using Hexo but I hate doing JavaScript and I love using Ruby, but for now Jekyll is pain so I'll continue using Hexo for a moment~)

**Comment by noraj1337** [comment]
A good reason why this feature is needed:

> Jekyll allows you to concoct your sites in any way you can dream up, and it’s thanks to the powerful and flexible configuration options that this is possible.

[Quote source](https://jekyllrb.com/docs/configuration/)

**Comment by ashmaroli** [comment]
> - I don't like it
> - This is a waste of time
> - This is painful

@noraj1337  Except for the first one, the reasons above are empathizable.. While Jekyll Core may not be forthcoming to a change regarding this, we can have a plugin inject a new `jekyll command` to **ease** things out for you..
e.g.
```sh
$ jekyll new-post "A beautiful day"
# => Created '_posts/2017-05-31-a-beautiful-day.md'
```
Whatsay?

**Comment by noraj1337** [comment]
@ashmaroli 

> Whatsay?

I'll continue using Hexo.

More seriously. This may be dirty to include the date in the filename.
I'm using my markdown files for other purpose and don't want the date in the filename. using `jekyll new-post "my-title"` is not faster than `vim 2017-05-31-my-title.mkd` and you are not choosing the extension when doing that. Plus you need to *touch* evry post with `jekyll new-post` when creating them, you can't create them using your favourite text editor. This is not a solution, not even a workaround.

I also want to be able to use my markdown file for others static site generator without having to rename filename or using export tools.

This also make filename longer and less pretty.

**Comment by noraj1337** [comment]
Something like https://hexo.io/docs/writing.html#Filename is preferable.

**Comment by DirtyF** [comment]
Hi @noraj1337,

Don't expect this kind of breaking change until a future major version, also the added value here is very unclear here (except for your own taste).

So I guess you should stick with Hexo if your choice for a static site generator is only based on a post filename.

/cc @jekyll/stability

**Comment by noraj1337** [comment]
@DirtyF I'll try to use jekyll for project that don't need posts and keep Hexo my blog that need posts.
