### ISSUE TITLE
Use a source folder by default

### ISSUE THREAD

**Issue by noraj1337** [jekyll/jekyll#6105]
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [X] This is a feature request.
- [X] I am on (or have tested on) ***Arch*** GNU/Linux (Manjaro in fact)

---

It will be cleaner to a default source folder by using something like `source: _sources` in `_config.yml` **by default**.

This will allow to keep a clean repository tree view. For a website with a lot of page, not using a source folder make the root directory full of file and that mix config files, gem fiels and source files so this is dirty.

Also if user create some other directories that he don't want to include in the source but forget to add in the `exclude` of `_config.yml` these folders will be added/copied to the build. Using a source folder by default will prevent that (unwanted behaviour) to happen.

So what is ask is already possible but this will be nice if it is default. That's really not a lot of works, only the documentation need to be updated.

**Comment by noraj1337** [comment]
I created a PR https://github.com/jekyll/jekyll/pull/6106

Note: maybe documentation need more changes

**Comment by parkr** [comment]
Please see https://github.com/jekyll/jekyll/pull/6106#issuecomment-308547870 for explanation why this isn't necessary. To prevent a breaking change, we will not change this default.
