### ISSUE TITLE
Page build failure: unrecognized tag "avatar"

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#6116]
The tag `avatar` on line 16 in `/_layouts/news_item.html` is not a recognized Liquid tag.

**Comment by parkr** [comment]
On mobile and can't edit.

**Comment by parkr** [comment]
The tag `avatar` on line 16 in `/_layouts/news_item.html` is not a recognized Liquid tag.

**Comment by DirtyF** [comment]
👋  Hey @parkr, this should be fixed by now in #6110
