### ISSUE TITLE
Mistake in the Jekyll documentation

### ISSUE THREAD

**Issue by mittalyashu** [jekyll/jekyll#6118]
I think there is a mistake in the document of Jekyll in the [Deployment method](http://jekyllrb.com/docs/deployment-methods/).

In the documentation, it was showing that you need to upload the _site name folder to the FTP server. But when I tried this. It didn't work. To open the website I type the name of the folder to open the website.

For example: 
`localhost:4000/_site`

When I uploaded the files inside the folder, then it work.
(Sorry, if I am wrong).

**Comment by Balancingrock** [comment]
The documentation is correct (but could be worded better).
If you copy folders, copy the "_site" folder to the destination and make the _site folder the root folder of your website.

However it is more common to copy only the files, in which case you should copy the contents of the _site folder to the folder at the hosting provider that must contain the index file.

**Comment by mittalyashu** [comment]
Oh! Got it. You are right 

> If you copy folders, copy the "_site" folder to the destination and make the _site folder the root folder of your website.
> However it is more common to copy only the files, in which case you should copy the contents of the _site folder to the folder at the hosting provider that must contain the index file.

This should be added in the documentation.

**Comment by pathawks** [comment]
> Just about any traditional web hosting provider will let you upload files to their servers over FTP. To upload a Jekyll site to a web host using FTP, simply run the jekyll build command and copy the generated _site folder to the root folder of your hosting account. This is most likely to be the httpdocs or public_html folder on most hosting providers.

I agree. This could maybe say "copy the _contents_ of the generated `_site` folder..."

/cc: @jekyll/documentation
