### ISSUE TITLE
help me with avoiding duplication on output

### ISSUE THREAD

**Issue by vinayak5192** [jekyll/jekyll#6120]
Im working on jekyll theme design and I have .yml file stored the data (File name : games.yml) and has data as follows

---
- name: NFS
  year: 2015
  id: NFS15
  link: http://www.example.com/
  date: August 3-4, 2017
  categories: Racing

etc
Im trying to output the categories in sidebar with number of count in each category. e.g: 
Racing (3)
Shooter (6)
Sports (5)
 etc How can I achieve this?

My Html output code:

      <a href="javascript:;" class="categories-list-item" cate="All">
        All<span class="my-badge"> {{site.data.games | size}}</span>
      </a>
      {% for cat in site.data.games %}
        <a href="javascript:;" class="categories-list-item" cate="{{ cat.categories}}">
          {{ cat.categories }} <span class="my-badge">{{ cat.categories | size }}</span>
        </a>
      {% endfor %}

Now I get the result with entire category list e.g: 
Racing 
Racing 
Racing 
Shooter 
Shooter 
Shooter
... and so on each count

**Comment by DirtyF** [comment]
Hi @vinayak5192, sorry this repo is for bugs only, but you should be able to get help on Jekyll'usage on https://talk.jekyllrb.com/.

**Comment by vinayak5192** [comment]
Hi @DirtyF  Thankyou. 
Will check for that
