### ISSUE TITLE
Can't build new site.

### ISSUE THREAD

**Issue by Kaligule** [jekyll/jekyll#6127]
Hi, this is my first try using jekyll.

I installed jekyll and generated a new project in an empty directory. Then, since there already was an example blogpost in ```_posts``` I tried to build it (This is supposed to work right? Thats why the ```new``` command exists in the first place, isn't it?).

I got the following error:

```
Configuration file: ~/myblog/_config.yml
            Source: ~/myblog
       Destination: ~/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/gems/jekyll-3.4.3/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```

I found Issue #2938, which seems to be the same problem. I tried the suggested solution with ```echo "exclude: [vendor]" >> _config.yml``` and the problem was gone. #2938 is closed at this moment.

I guess this problem still exists for some reason, even though it is an old one and seems easy to fix. At least as a beginner I shouldn't have this problem, since it makes it harder to start using jekyll.

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [x] I am on (or have tested on) ***Other*** GNU/Linux : CentOS
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

```
gem install jekyll
mkdir myblog
cd myblog
jekyll new .
jekyll build
```

## The Output I Wanted

Something like "Horray, the site was built."

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by Kaligule** [comment]
Forgot: The used version is jekyll 3.4.3

**Comment by DirtyF** [comment]
related to #5564 #5361

**Comment by DirtyF** [comment]
@Kaligule When we excluded `vendor`by default, it broke some sites, and people complained, as this is often used by other tools like `bower` for instance. 

As a result we choose to me more specific and to only exclude some known folders like `node_modules`, `vendor/bundle/ `, `vendor/cache/`,  `vendor/gems/` and `vendor/ruby/`.

You're right to mention that it should work by default, but we're kind of stucked here I guess. 😕

**Comment by Kaligule** [comment]
Hmm, ok. Perhaps this should be doumented in a better way. I only could make it work when I found the issue on Github,

**Comment by DirtyF** [comment]
It's [documented in our troubleshooting section](https://jekyllrb.com/docs/troubleshooting/#configuration-problems) but If you have a better way of warning users, I'll be happy to review a PR :)

**Comment by Kaligule** [comment]
Submitted a pull request, happily waiting for a review :D
