### ISSUE TITLE
main.css is not included properly to pages

### ISSUE THREAD

**Issue by enesterenko** [jekyll/jekyll#6131]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`

---

- [x] I am on (or have tested on) ***macOS*** 10+

---

- [x] I was trying to build.

## My Reproduction Steps
Install ruby 2.4.1
Install latest version of jekyll 3.4.3
Generate a new blog jekyll new .
Open in browser blog/_site/index.html
The site will be rendered without main.css included and will look completed not styled.

This seems to be because main.css is added on the page with absolute path:
link rel="stylesheet" href="/assets/main.css"

Manually editing _site/index.html and changing path to relalative fixes the look and feel of the page.

## The Output I Wanted

I expect if I open in a browser autogenerated blog/_site/index.html, it will be styled with main.css but it's not.

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by pathawks** [comment]
> Open in browser blog/_site/index.html

None of the URLs will work properly if this is how you are viewing the site. You should instead use `jekyll serve`, then all your lonks will work as they should:+1:

**Comment by enesterenko** [comment]
Hey,
What about jekyll build?
I am running jekyll build in my blog folder, than I am using generated artifacts in blog/_site/* to host my static site. In this case URL to main.css is also malfunctioning. This used to work in previous releases.
Thanks.

**Comment by ashmaroli** [comment]
@enesterenko When you run `jekyll build` the links will be created properly but the stylesheet will be "served" to the browser only if you run `jekyll serve`
GitHub Pages will automatically run `jekyll serve` when you instruct it to publish the site and regenerates with each successful push to the repo

### Notes:
- With recent versions of Jekyll, if you're generating a site locally and hosting the output, you need to build explicitly for `production`:

CLI | command
--- | ---
Windows cmd.exe: | `$ set JEKYLL_ENV="production" && bundle exec jekyll build`
BASH and Unices: | `$ JEKYLL_ENV="production" bundle exec jekyll build`

- When generating or previewing a site locally, if there is a Gemfile in your project directory, we recommend that you prepend `bundle exec` to the jekyll commands. i.e. `bundle exec jekyll build` or `bundle exec jekyll serve` respectively.
