### ISSUE TITLE
header info filed date problem

### ISSUE THREAD

**Issue by vandykai** [jekyll/jekyll#6135]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

1. Time now is 2017-06-14 16:06:00
2. I set the header info with date:   2017-06-14 15:06:00, then the post can't be generate
3. But when I change header info with date:   2017-06-13 15:06:00, then the post can be generate.
4. it seems that if the date is close to real time, then the post can't be generate.
## The log is normal

Destination: ./_site/mark
Incremental build: disabled. Enable with --incremental
Generating... 
done in 0.628 seconds.

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by parkr** [comment]
This has to do with the timezone your computer is running in. When we read the date `2017-06-14 15:06:00`, Ruby reads it in as UTC and then converts it to your local timezone. If the converted date is in the future, then it will not generate.

Fix is to add your UTC offset like `2017-06-14 16:06:00 +1100`.
