### ISSUE TITLE
Unknown tag 'gist '

### ISSUE THREAD

**Issue by vellareadings** [jekyll/jekyll#6142]
```text
            Source: C:/Users/Krishna/AppData/Local/GitHubDesktop/vellareadings
       Destination: C:/Users/Krishna/AppData/Local/GitHubDesktop/vellareadings/_
site
 Incremental build: disabled. Enable with --incremental
      Generating...
     Build Warning: Layout 'post' requested in hyde-master/hyde-master/_posts/20
12-02-06-whats-jekyll.md does not exist.

>   Liquid Exception: Liquid syntax error (line 49): Unknown tag 'gist' in C:/User
> s/Krishna/AppData/Local/GitHubDesktop/vellareadings/hyde-master/hyde-master/_pos
> ts/2012-02-07-example-content.md
> jekyll 3.4.3 | Error:  Liquid syntax error (line 49): Unknown tag 'gist'
```
Hi, 
The gist gem is present when checked, I also tried commenting out that particular line it did not help.
Any suggestions please ? Using Windows 8.1 
_Thanks ! 

```text
C:\Users\Krishna\AppData\Local\GitHubDesktop\vellareadings\hyde-master\hyde-mast
er\_posts>gem list

*** LOCAL GEMS ***

actionmailer (5.0.3)
actionpack (5.0.3)
actionview (5.0.3)
activejob (5.0.3)
activemodel (5.0.3)
activerecord (5.0.3)
activesupport (5.0.3)
addressable (2.5.1)
arel (7.1.4)
bigdecimal (default: 1.3.0)
builder (3.2.3)
bundler (1.15.1)
colorator (1.1.0)
concurrent-ruby (1.0.5)
did_you_mean (1.1.0)
erubis (2.7.0)
faraday (0.12.1)
ffi (1.9.18 x64-mingw32)
forwardable-extended (2.6.0)
globalid (0.4.0)
i18n (0.8.4)
io-console (default: 0.4.6)
jekyll (3.4.3)
jekyll-feed (0.9.2)
jekyll-gist (1.4.0)
jekyll-paginate (1.1.0)
jekyll-sass-converter (1.5.0)
jekyll-watch (1.5.0)
json (default: 2.0.2)
kramdown (1.13.2)
liquid (3.0.6)
listen (3.0.8)
loofah (2.0.3)
mail (2.6.6)
mercenary (0.3.6)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.2.0)
minima (2.1.1)
minitest (5.10.1)
multipart-post (2.0.0)
net-telnet (0.1.1)
nokogiri (1.8.0 x64-mingw32)
octokit (4.7.0)
openssl (default: 2.0.3)
pathutil (0.14.0)
power_assert (0.4.1)
psych (default: 2.2.2)
public_suffix (2.0.5)
rack (2.0.3)
rack-test (0.6.3)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.0.3)
rake (12.0.0)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rdoc (default: 5.0.0)
rouge (1.11.1)
safe_yaml (1.0.4)
sass (3.4.24)
sawyer (0.8.1)
test-unit (3.2.3)
thread_safe (0.3.6)
tzinfo (1.2.3)
tzinfo-data (1.2017.2)
xmlrpc (0.2.1)
```

- [ x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ x] I was trying to build.
- [ ] It was another bug.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by parkr** [comment]
Please ensure you have the gem specified in your configuration like this:

```yaml
gems:
- jekyll-gist
```

**Comment by vellareadings** [comment]
Thank you parkr, 

I opened the _config.yml  and found it to be specified as below 
`# Dependencies
gems:                   [jekyll-gist]
markdown:               redcarpet
highlighter:            rouge

# Permalinks
permalink:              pretty
`
Even edited the syntax it to resemble your example 

`gems:
- jekyll-gist`

The error still remains, any idea what could be wrong ?

**Comment by crispgm** [comment]
@vellareadings I tried write `_config.yml` as you shown, and it works on my Bash on Windows. Can you post your repo for more details?

**Comment by vellareadings** [comment]
@crispgm 
I've attached my copy of the repo, Ty :) 
[hyde-master.zip](https://github.com/jekyll/jekyll/files/1083173/hyde-master.zip)

**Comment by ashmaroli** [comment]
@vellareadings Please don't attach zip files here. Security issues.
You can create a repo on GitHub and have it deleted later if you want.. Plus its easier for us to debug..

**Comment by crispgm** [comment]
@vellareadings It works well on my macOS.

**Comment by vellareadings** [comment]
I will switch over to another theme perhaps,(Really liked the double column layout though) as it is still not working on mine (Windows 8.1) 
Thank you very much for helping out
