### ISSUE TITLE
[Help Needed] - Invalid syntax for include tag | Variable inside include {% %}

### ISSUE THREAD

**Issue by 7php** [jekyll/jekyll#6159]
- [x] I have a question about using Jekyll.
- [x] I updated to the latest Jekyll v3.5.0
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I was trying to build.

---

## My Errror Message

> Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: image_caption.html imageurl="http://blog.local/images/home/image.jpg" Valid syntax: {% include file.ext param='value' param2='value' %} in index.html

---

## My Reproduction Steps

- Use a variable inside an include tag, my example is:
`{% include image_caption.html imageurl="{{ site.url }}/images/home/image.jpg" title="some title text" caption="some caption text" %}`

/cc @jekyll/stability @jekyll/build

---

So I guess there's some escaping to be done in this: `{% imageurl="{{ site.url }} %}`  or is that not something achievable?
I'm not into Ruby, so getting stuck here. Any advice appreciated.

**Comment by MPybus** [comment]
I don't think it's achievable, but if you're willing to mess around with image_caption.html, you could use two separate variables:

`{% include image_caption.html image_path="/images/home/image.jpg" base=site.url title="some title text" caption="some caption text" %}`

Or alternatively, in two parts:
`{% assign temp_url = site.url | append: '/images/home/image.jpg' %}
{% include image_caption.html imageurl=temp_url title="some title text" caption="some caption text" %}`

That said, do you definitely need to include site.url here? Unless you're also using external images, why not reference it from within image_caption.html?

**Comment by 7php** [comment]
hi @MPybus 
thanks for the response. Your solution will work for if I'm using the site url itself. But what is when I'm using an external image url like a flickr url?

**Comment by MPybus** [comment]
For the first solution, use `base="flickr.com"` for example.

For the second, you would use `imageurl="flickr.com/image/home/image.jpg"` and neglect the assign bit.

**Comment by 7php** [comment]
Hi @MPybus 
thanks for the suggestion, but I got a perfect match of what I wanted achieve by the solution given here: http://talk.jekyllrb.com/t/invalid-syntax-for-include-tag-variable-inside-include/681

This ticket can be closed now. thanks
