### ISSUE TITLE
How To Structure different Posts types - think gallery posts vs article post

### ISSUE THREAD

**Issue by 7php** [jekyll/jekyll#6160]
- [x ] This is a question about using Jekyll.
- [x ] I updated to the latest Jekyll v3.5.0

---

- [x ] I am on (or have tested on) ***macOS*** 10+

---
## My Question

I would like to gain a bit more control on how I work with posts & even pages.
My posts consist of:
- normal blog posts
- pages
- image posts - An image with a title & a very short description

My concern is, all those "posts" scatter too much around in the same folder. Is there a way I can instruct Jekyllrb so that l "internally" categorise posts into the following hierarchy:
> _entries
> ├── images
> ├── pages
> └── posts
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── 2016
>     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── 01
>     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── 02
>     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;│   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── 03
>     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── 2017
>         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── 03
>         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── 04

But I would also want Jekyllrb to still render all pages or even posts, under //domain.com/about-me-page.html

Is there any way I could achieve this kind of structuring within my jekyll workflow?

PS: The response rate [in the talk forum](http://talk.jekyllrb.com/t/howto-question-structure-different-posts-types-think-gallery-posts-vs-article-post/680) is too slow, hence posting here.

**Comment by DirtyF** [comment]
> The response rate in the talk forum is too slow, hence posting here.

Be patient, I trust the good will of our community to help you with this.

Not a support forum but a bug issue tracker, hence closing this issue.
