### ISSUE TITLE
page.querystring

### ISSUE THREAD

**Issue by marcelduran** [jekyll/jekyll#617]
Is it possible to have URL querystring available? e..g: http://foo.com/bar/?baz=123&qux=456
It'd be nice to have them available as:

``` html
<p>{{ page.querystring.baz }}</p>
<p>{{ page.querystring[1] }}</p>
```

If `querystring` is too long, `params` or `param` might be shorter.
I know this is available in JS via `window.location.search` but my goal is to use it on the server to dynamically build pages bots can read.

**Comment by JiaKunUp** [comment]
Disappointed.
If I want to create some pages with same layout but some keywords are different, I can only create each of them.

**Comment by crispgm** [comment]
@JiaKunUp You may put the keywords into front matters. Is this enough for you?

**Comment by JiaKunUp** [comment]
@crispgm I didn't get your point, could you give me an example? Thanks a lot!

**Comment by pathawks** [comment]
This issue was closed 4 years ago.

If you are experiencing a bug, or would like to propose a feature request, posting as a new issue (possibly referencing _this_ issue) is the way to go. That will ensure it has proper visibility and doesn't confuse an _old_ discussion  :+1:

**Comment by JiaKunUp** [comment]
@pathawks Thanks for response,I have created an issue about this.
