### ISSUE TITLE
Can Jekyll only build new article

### ISSUE THREAD

**Issue by ashidamana** [jekyll/jekyll#6173]
Can Jekyll only build new article,I mean that can it only build the new post I add or update.
Now when I use the command jekyll build,it actually delete all the files in  _site and then regenerate.
My Jekyll version is 2.5.3

**Comment by KeJunMao** [comment]
Try update your jekyll version.

```
 gem update jekyll
```

**Comment by pathawks** [comment]
The latest version of Jekyll supports incremental generation.
Please update to a more recent version of Jekyll.
