### ISSUE TITLE
Update jekyll from 2.x to 3.x

### ISSUE THREAD

**Issue by ashidamana** [jekyll/jekyll#6175]
When I update jekyll from 2.x to 3.x and then run jekyll build,I get so many errors,I searched on the Internet,but can not find certain solutions.What should I do?
Here is the error below.
`      Generating...
C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/url.rb:1:in `require'
: cannot load such file -- addressable/uri (LoadError)
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/url.rb:1
:in `<top (required)>'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/page.rb:
98:in `require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/page.rb:
98:in `url'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-paginate-1.1.0/lib/jekyll
-paginate/pagination.rb:65:in `first_page_url'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-paginate-1.1.0/lib/jekyll
-paginate/pager.rb:65:in `paginate_path'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-paginate-1.1.0/lib/jekyll
-paginate/pager.rb:113:in `initialize'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-paginate-1.1.0/lib/jekyll
-paginate/pagination.rb:45:in `new'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-paginate-1.1.0/lib/jekyll
-paginate/pagination.rb:45:in `block in paginate'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-paginate-1.1.0/lib/jekyll
-paginate/pagination.rb:44:in `each'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-paginate-1.1.0/lib/jekyll
-paginate/pagination.rb:44:in `paginate'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-paginate-1.1.0/lib/jekyll
-paginate/pagination.rb:18:in `generate'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/site.rb:
178:in `block in generate'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/site.rb:
176:in `each'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/site.rb:
176:in `generate'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/site.rb:
72:in `process'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/command.
rb:26:in `process_site'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/commands
/build.rb:63:in `build'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/commands
/build.rb:34:in `process'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/lib/jekyll/commands
/build.rb:16:in `block (2 levels) in init_with_program'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/co
mmand.rb:220:in `block in execute'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/co
mmand.rb:220:in `each'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/co
mmand.rb:220:in `execute'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary/pr
ogram.rb:42:in `go'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb
:19:in `program'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/jekyll-3.5.0/exe/jekyll:13:in `<
top (required)>'
        from c:/Ruby24/bin/jekyll:22:in `load'
        from c:/Ruby24/bin/jekyll:22:in `<main>'
`

**Comment by KeJunMao** [comment]
If it is [ashidamana.github.io](https://github.com/ashidamana/ashidamana.github.io),Only need to follow [this](https://jekyllrb.com/docs/upgrading/2-to-3/) guide operation can be.

**Comment by ashidamana** [comment]
@KeJunMao 我已经搞定啦，现在jekyll版本是3.5.0，谢谢你啦，有QQ的

**Comment by KeJunMao** [comment]
@ashidamana 来来来，你站多少，加个友链啊~

**Comment by ashidamana** [comment]
@KeJunMao 噗，这地方也可以加友链啊，我把站从github pages迁移到虚拟主机了，github pages访问有点慢啊，SSL（https）还没生效，http可以访问，不嫌弃的可以加友链，http://blog.mana.love/ ，之后应该会变成https://blog.mana.love/ 吧
