### ISSUE TITLE
Filter sensitive files from `site.pages`

### ISSUE THREAD

**Issue by jhabdas** [jekyll/jekyll#6178]
Issue template too involved. Sorry, but this is what you get as a result.

Please consider creating a blacklist of known static filenames from `site.pages` or adding a note to the documentation. When looping in liquid to generate a custom XML feed I noticed certain files are output which probably should not be allowed. I'd name one in particular I feel should be blacklisted but for security reasons someone's going to have to [contact me](https://habd.as/contact) for it.

Also, I noticed XSLT is processed by liquid when looping over `site.pages`. Is there an issue for that?

**Comment by jhabdas** [comment]
`letsencrypt.html` cough

**Comment by pathawks** [comment]
I'm not sure what the desired action is here. I’m assuming nothing, since issue is closed?

**Comment by DirtyF** [comment]
@pathawks 😊  Sorry if you already read the issue, I just felt you might want to as it involves custom feed, Liquid and XSLT.

**Comment by jhabdas** [comment]
Pat and Dirty. I closed it after seeing html_files and friends in the variables docs, deciding this was a buyer beware behavior. Thanks for the follow-ups.
