### ISSUE TITLE
jekyll 3.5.0 | Error:  undefined method `registers' for nil:NilClass

### ISSUE THREAD

**Issue by jclwilson** [jekyll/jekyll#6181]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I was trying to build.

## My Reproduction Steps

1. I upgraded from 3.4.3 to 3.5.0.
2. I changed `gems` in the config file to `plugins`. I have installed:
    - jekyll-seo-tag
    - jekyll-redirect-from
    - jekyll-feed
    - jekyll-sitemap
3. When I ran `jekyll build` the build failed and gave the error:
    - ``jekyll 3.5.0 | Error:  undefined method `registers' for nil:NilClass``
4. When I ran `jekyll build -t` the first line gave:
    - ``/var/lib/gems/2.3.0/gems/jekyll-3.5.0/lib/jekyll/filters/url_filters.rb:44:in `site': undefined method `registers' for nil:NilClass (NoMethodError)``
    - There are more lines, but I've omitted them here.

**Comment by ashmaroli** [comment]
@jclwilson Thanks for reporting this.
We _may_ have resolved this already via #6163 

Can you use the `master` branch of this repo and get back?
To use the master branch, make the following change to your `Gemfile`, then run `bundle install`
```diff
- gem "jekyll", "3.5.0"
+ gem "jekyll", :git => "https://github.com/jekyll/jekyll.git"
```

**Comment by DirtyF** [comment]
@jclwilson Thanks for reporting, sorry for the inconvenience. 😕 

Like @ashmaroli said, using jekyll's current `master` branch will allow you to build without erros. 
Or you can downgrade to 3.4.3 for now, until we release a patched version.

`gem "jekyll", "3.4.3"``

**Comment by jclwilson** [comment]
Hi, thanks very much, at least it's been identified. I've installed Jekyll via Ruby Gems, so I just downgraded to 3.4.4.
