### ISSUE TITLE
Jekyll error on jekyll serve -- fsevent: running worker failed

### ISSUE THREAD

**Issue by chadcodes** [jekyll/jekyll#6189]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration

---

- [x] I am on (or have tested on) ***macOS*** 10+

---

- [x] I was trying to build.

## My Reproduction Steps

I created a new Jekyll site in my current directory with: 
`jekyll new .`

Then tried to serve the site with:
`jekyll serve`

## The Output I Wanted

I get 2 errors: 
> Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.

Easily fixed by changing the _config.yml file.

Second error I'm stuck on:
> ERROR -- : fsevent: running worker failed: wrong number of arguments (given 2, expected 1)

**Comment by crispgm** [comment]
I encountered the same error today, which never happened before. I guess it might be wrong with `rb-fsevent`. Would you mind posting `Gemfile.lock`?

**Comment by DirtyF** [comment]
@chadcodes The first message is not an error, it's simply a notice asking you to rename the `gems`list to `plugins` in the `_config.yml`. This change happened in 3.5.0.

Didn't reproduce your issue on MacOS. Could you post `bundle env`output?

**Comment by ashmaroli** [comment]
> The first message is not an error

Technically, it is not an error.. but `Deprecator` does log this message at level `:error` :grimacing:

**Comment by kentaroi** [comment]
On the second error, this is just a temporary workaround,
add the following line to your Gemfile, and `bundle`
```ruby
 gem "rb-fsevent", "0.9.8"
```

**Comment by chadcodes** [comment]
@kentaroi your solution worked, thank you very much!

**Comment by pathawks** [comment]
What version of `rb-fsevent` _were_ you running? Is this something that others are likely to encounter?

**Comment by kentaroi** [comment]
Actually, I also encountered this issue, when the version of `rb-fsevent` was 0.10.1.
There already is a PR https://github.com/guard/listen/pull/432 to `listen` gem, which `jekyll-watch` depends on.

**Comment by huphtur** [comment]
Had the same errors today. For those that never worked with a gem file (like me 😕) make sure to also add `gem jekyll` to the gem file followed by `bundle install` command as that resolved missing kramdown gem.

**Comment by menehune23** [comment]
I encountered this rb-fsevent issue yesterday and discovered it only happens if jekyll serve is running while you save a file (a post for instance). HIt also happens if you have your repo open is VS Code while serve is running, even when not saving (which is what took me so long to figure out what triggers it). Hopefully that might explain why some people are not seeing it reproduced.

**Comment by kentaroi** [comment]
This issue was fixed in `rb-fsevent 0.10.2`
https://github.com/thibaudgg/rb-fsevent/commit/d48b3bb43199e8f3db35a88cf1215d05f4a2ffde
