### ISSUE TITLE
Incorrect path in filter errors for included files

### ISSUE THREAD

**Issue by chromatical** [jekyll/jekyll#6203]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Create an include file `_includes/test.html` containing a tag with incorrect syntax in a filter, e.g. `{{ site.title | prepend 'Prepended Text' }}` (missing colon after `prepend`).

Include it in `index.md` with `{% include test.html %}`.

Build the site and Jekyll with throw an error `Liquid Exception: Liquid error (line 1): wrong number of arguments (given 1, expected 2) in index.md`.

## The Output I Wanted

Jekyll should throw an error with the included file path instead of `index.html`.

The error will display the included file path with other errors.  For example, an unclosed if tag in the included file will throw `Liquid Exception: Liquid syntax error (line 2): 'if' tag was never closed in /tmp/test_website/_includes/test.html, included in index.md`.

/cc @jekyll/build

**Comment by Crunch09** [comment]
Thanks for the report! Seems like i missed adding a check for `Liquid Exception` in #5767. 
@chromatical Do you want to take a stab at a PR to fix this?

**Comment by chromatical** [comment]
@Crunch09 I actually have no Ruby experience at all, so I wouldn't have any idea what I was doing.  :slightly_frowning_face:

**Comment by Crunch09** [comment]
@chromatical No worries! Thank you anyway for reporting 🙇
