### ISSUE TITLE
`page.date` is not working occasionally 

### ISSUE THREAD

**Issue by shivabhusal** [jekyll/jekyll#6204]
I dont understand why `page.date` returns `nil` sometimes. Guys please help me.

### In development
![image](https://user-images.githubusercontent.com/8004593/27849843-d94d2432-616f-11e7-913e-c49a7f026372.png)

```html
<meta property="article:published_time" content="{{ page.date }}" />
<meta property="article:modified_time"  content="{{ page.last_modified_at | date: "%Y-%m-%dT%H:%M:%S%z" }}" />
```

### In production

![image](https://user-images.githubusercontent.com/8004593/27849859-033f3aa0-6170-11e7-8c58-3bd4b9c889e2.png)

---

I am using https://github.com/gjtorikian/jekyll-last-modified-at gem to get updated date

**Comment by DirtyF** [comment]
Hey @shivabhusal, hard to help you without any context, please head over to https://talk.jekyllrb.com to get some help from Jekyll's community.
