### ISSUE TITLE
Two problems when installing Jekyll on macOS 

### ISSUE THREAD

**Issue by doekman** [jekyll/jekyll#6216]
I tried to install Jekyll on a brand new Sierra machine. I found two issues, which prevented me to be "Get up and running in seconds"... This can be a bit discouraging when trying to install Jekyll, and the [web-page](http://jekyllrb.com) doesn't provide any other hints how to install on macOS. 

1. Permission problems

`gem install jekyll bundler` results in `ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.`.

I solved this by running sudo: `sudo gem install jekyll bundler`

2. Wrong ruby version

When running the above install command, I got the error `ERROR:  Error installing jekyll:
	liquid requires Ruby version >= 2.1.0.` (default ruby install on Sierra: `ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]`)

I fixed this by install the latest Ruby with brew: `brew install ruby`.

**Comment by jmknoll** [comment]
Not sure if this is exactly the issue that you're dealing with, but its important to use something like [rbenv](https://github.com/rbenv/rbenv) or [rvm](https://rvm.io/) on MacOS, as the operating system uses ruby for a lot of things under the hood. By default, you can't access the system ruby. You can force it with sudo, but this isn't recommended, as you can end up with a mess of dependencies (more dealing with Rails, but additional info [here](http://railsapps.github.io/installrubyonrails-mac.html). That should also solve your second problem.

I think this isn't an issue particular to Jekyll, but more to the workings of MacOS.

**Comment by pup** [comment]
i believe that it's listed on the installation page that ruby 2.1+ is required for jekyll to run, which in itself forces users to not use system ruby (aside from the fact that it's usually inaccessible). the method using homebrew is [described here](http://jekyllrb.com/docs/troubleshooting/#jekyll--mac-os-x-1011).

so yeah, as @jmknoll said, this is more of a MacOS thing, rather than jekyll thing

**Comment by doekman** [comment]
Perhaps not a Jekyll (as in Ruby code) issue, but I think it sure is a problem... The [installation page](https://jekyllrb.com/docs/installation/) has some issues installing jekyll on macOS. However, I don't know enough about ruby/gem to address this.

(just a Ruby-Noob wanting to help)

**Comment by Crunch09** [comment]
Maybe we can make it more clear that the system installed ruby *is not good enough* ? (Even if Apple would update the pre-installed version we probably wouldn't encourage to use that.)

**Comment by jmknoll** [comment]
Agreed, with @Crunch09 - even if Apple updated the system Ruby, it wouldn't be good practice to use it - ([see here](https://robots.thoughtbot.com/psa-do-not-use-system-ruby) ).  

What's the fix? Update the installation docs to include setting up a ruby environment manager? That may be overkill, but could be valuable to users who are coming at Jekyll from a non-ruby/rails environment.

**Comment by pup** [comment]
@jmknoll i believe it might be helpful to only say that system ruby doesn't support jekyll, and then link to homebrew or even rvm etc. for further information

**Comment by doekman** [comment]
I installed ruby with homebrew. Those two versions work side by side.

**Comment by DirtyF** [comment]
@doekman I like the idea, hugo does this, [the formula is not that complicated](https://github.com/Homebrew/homebrew-core/blob/master/Formula/hugo.rb).

**Comment by pathawks** [comment]
> installation of Jekyll with homebrew would be very nice

Yes. Please.

**Comment by deanilvincent** [comment]
Same issue with me. I'm trying to install jekyll with ruby installed.

![screen shot 2017-09-05 at 11 06 38 pm](https://user-images.githubusercontent.com/10904957/30067955-e89054dc-928e-11e7-8223-7332cbddaadf.png)

**Comment by DirtyF** [comment]
@deanilvincent Jekyll requires at least Ruby 2.1. You can install a proper version of Ruby via `homebrew` and [ `rbenv`](https://github.com/rbenv/rbenv#homebrew-on-macos).

```shell
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update
brew install rbenv ruby-build
rbenv init
rbenv install 2.4.1
rbenv global 2.4.1
rbenv shell 2.4.1
gem install jekyll bundler
rbenv rehash
```

**Comment by deanilvincent** [comment]
Thank you @DirtyF for responding. 

I got this error:

![screen shot 2017-09-12 at 12 37 35 am](https://user-images.githubusercontent.com/10904957/30286013-acbffc28-9752-11e7-9cb6-bf76d7565f0e.png)

**Comment by DirtyF** [comment]
@deanilvincent `ruby -v`shoul be at least 2.1 (in my example above I encourage to use latest Ruby 2.4)

**Comment by deanilvincent** [comment]
![screen shot 2017-09-12 at 8 09 31 pm](https://user-images.githubusercontent.com/10904957/30325196-6a2e8f4c-97f6-11e7-8de1-db9393049991.png)

@DirtyF it's weird. Even I'm trying to install the 2.4, I still ended up with the version 2.0.

**Comment by doekman** [comment]
I did this to install Jekyll with brew:

    brew install ruby
    sudo gem install jekyll bundler

**Comment by pathawks** [comment]
Don't use sudo

**Comment by doekman** [comment]
If you omit `sudo`, gem fails:

    > gem install jekyll bundler
    Fetching: jekyll-3.5.2.gem (100%)
    Successfully installed jekyll-3.5.2
    ERROR:  While executing gem ... (Errno::EACCES)
        Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.4.0/doc/jekyll-3.5.2

**Comment by DirtyF** [comment]
> it's weird. Even I'm trying to install the 2.4, I still ended up with the version 2.0.

@deanilvincent What If you specify `rbenv local 2.4.1` in your Jekyll folder, and then type  `ruby -v` in this same folder?

**Comment by zikadubois** [comment]
me too, I have the same problem with my ruby while installing jekyll...

ERROR:  Error installing jekyll:
	public_suffix requires Ruby version >= 2.1.

**Comment by Crunch09** [comment]
@zikadubois As @DirtyF said this is not a `jekyll` bug. Have you tried the commands that he posted to install an up-to-date ruby version?

**Comment by symmetriccurve** [comment]
This helped me: https://stackoverflow.com/questions/26183787/upgrading-to-ruby-2-1-3-on-mac-osx-10-9-5

**Comment by pneumatics** [comment]
I got this error in my LMDE whilr trying to install jekyll.

`Fetching: ruby_dep-1.5.0.gem (100%)
ERROR:  Error installing jekyll:
	ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.`
I installed ruby by `sudo apt-get install ruby-dev`

**Comment by erikrtn** [comment]
I set up Ruby via `rbenv` (installed 2.5.1) and had the same issues as most of you trying to set up jekyll:

```
$ gem install bundler jekyll
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/CHANGELOG.md
```
and spent hours reinstalling everything and checking paths.

Finally fixed the issue by changing my global Ruby version to 2.5.1 instead of local:

```
$ rbenv versions
* system (set by /Users/erik/.rbenv/version)
  2.5.1

$ rbenv global
system

$ rbenv global 2.5.1

$ rbenv global
2.5.1

$ gem install bundler jekyll
Fetching: bundler-1.16.1.gem (100%)
...
```

**Comment by DirtyF** [comment]
https://jekyllrb.com/docs/installation/#macOS now details install on High Sierra, using latest ruby version with brew, and using rbenv.
