### ISSUE TITLE
Curly braces in javascript code blocks are treated as templates

### ISSUE THREAD

**Issue by aneilbaboo** [jekyll/jekyll#6217]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I had an error on GitHub Pages and I did not test it locally.

## My Reproduction Steps

I have the following in my Github Markdown:

<img width="374" alt="screen shot 2017-07-10 at 10 13 41 pm" src="https://user-images.githubusercontent.com/2592723/28052011-138cc066-65bd-11e7-9e2e-7da35d8cd992.png">

## The Output I Wanted

Appears correctly on Github's markdown view:
<img width="477" alt="screen shot 2017-07-10 at 10 10 22 pm" src="https://user-images.githubusercontent.com/2592723/28052027-20cb68ae-65bd-11e7-9fb8-8d64986b04d4.png">

## The Output I Got

On Github pages:
<img width="642" alt="screen shot 2017-07-10 at 10 10 08 pm" src="https://user-images.githubusercontent.com/2592723/28052040-3af8e1d4-65bd-11e7-9f38-1dbc40a6f81d.png">

**Comment by crispgm** [comment]
Wrap it with:

```
{% raw %}
// your codes here
{% endraw %}

**Comment by aneilbaboo** [comment]
That fixes the problem in Github Pages, but now I get this in Github:

<img width="549" alt="screen shot 2017-07-10 at 10 37 43 pm" src="https://user-images.githubusercontent.com/2592723/28052524-838d9694-65c0-11e7-9157-8469f936dd0e.png">

**Comment by pup** [comment]
@aneilbaboo i'm assuming you still have the triple backticks? you can either put those or the `raw` tag

**Comment by aneilbaboo** [comment]
The problem is that Github doesn't recognize liquid tags.  For example - here is some text without any backticks.  It appears just as I wrote it:

{% raw %}
here is my js code
{% endraw %}

It will look the same inside docs viewed in Github.  

For the record, I've tried:

1. 3-backticks js-code-with-curly-braces 3-backticks  
    Produces the problem in Jekyll reported at the top of this issue
2. raw_tags js-code-with-curly-braces end_rawtags 
    Shows rawtags in Github, doesn't format js-code
3. raw_tags 3-backticks js-code-with-curly-braces 3-backticks end-rawtags
    Shows rawtags in Github, but properly formats js-code
4. 3-backticks raw_tags js-code-with-curly-braces end_rawtags 3-backticks
    Shows rawtags in Github, but properly formats js-code

As you can see, they all produce unacceptable behavior where Github docs are inconsistent with Jekyll docs, which is caused by the fact that Jekyll markdown has different semantics than Github markdown.

**Comment by ashmaroli** [comment]
Liquid is not processed as part of Markdown.
When you view a `document.md` on GitHub, only the Markdown is rendered. It is only when Jekyll "processes" the Markdown document to `document.html` does the Liquid get parsed..

**Comment by pathawks** [comment]
Thanks @ashmaroli.

@aneilbaboo `{% raw %}` is the solution. I agree it isn't elegant, but that's what Liquid requires.

**Comment by aneilbaboo** [comment]
Would it be possible to add a _config.yml option that toggles raw mode on or perhaps just for specific files?

The {% raw %} tag in my Github docs isn't the end of the world, but it is a factor in considering which documentation service to use.

**Comment by LuudJanssen** [comment]
I fixed @aneilbaboo's issue by using:

````markdown
<!-- {% raw %} -->
```html
<div no-ui-slider
     slider-options="{{ optionsWithoutStart }}"
     ng-model="sliderPositions"></div>
```
<!-- {% endraw %}) -->
````

The `<!-- -->` is seen by GitHub as a comment and the `{% raw %} {% endraw %}` prevents Jekyll from parsing the curly braces.

On both GitHub and Jekyll (GitHub Pages), the output is:
```html
<div no-ui-slider
     slider-options="{{ optionsWithoutStart }}"
     ng-model="sliderPositions"></div>
```
