### ISSUE TITLE
Cannot install Jekyll since v3.5 release of sass

### ISSUE THREAD

**Issue by bogosj** [jekyll/jekyll#6221]
- [x] I believe this to be a bug, not a question about using Jekyll.

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

---

- [x] I was trying to install.

## My Reproduction Steps

I use Jekyll + TravisCI to deploy a website. ~12 hours ago this was working, however now my automated build process hangs with what appears to be a conflict with "listen". If I run "gem install sass:3.4.25 jekyll" instead of "gem install jekyll", it works fine.

Here's what happens with an untouched base Google Compute Engine image as well:

$ cat /proc/version
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.43-2+deb8u1 (2017-06-18)

$ \curl -sSL https://get.rvm.io | bash -s stable --ruby
[truncated]

$ rvm use 2.4.1 --install --fuzzy
[truncated]

$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

$ gem install jekyll
Fetching: public_suffix-2.0.5.gem (100%)
Successfully installed public_suffix-2.0.5
Fetching: addressable-2.5.1.gem (100%)
Successfully installed addressable-2.5.1
Fetching: colorator-1.1.0.gem (100%)
Successfully installed colorator-1.1.0
Fetching: rb-fsevent-0.10.2.gem (100%)
Successfully installed rb-fsevent-0.10.2
Fetching: ffi-1.9.18.gem (100%)
Building native extensions. This could take a while...
Successfully installed ffi-1.9.18
Fetching: rb-inotify-0.9.10.gem (100%)
Successfully installed rb-inotify-0.9.10
Fetching: sass-listen-3.0.7.gem (100%)
Successfully installed sass-listen-3.0.7
Fetching: sass-3.5.0.gem (100%)
Successfully installed sass-3.5.0
Fetching: jekyll-sass-converter-1.5.0.gem (100%)
Successfully installed jekyll-sass-converter-1.5.0
Fetching: listen-3.0.8.gem (100%)
listen's executable "listen" conflicts with sass-listen
Overwrite the executable? [yN]

I also filed this here:
https://github.com/sass/sass/issues/2345

**Comment by envygeeks** [comment]
```
Step 15/29 : RUN yes | gem install --no-ri --no-rdoc jekyll -v3.2.1
 ---> Running in 5c6f9b8a5b02
Successfully installed liquid-3.0.6
Successfully installed kramdown-1.14.0
Successfully installed mercenary-0.3.6
Successfully installed safe_yaml-1.0.4
Successfully installed colorator-1.1.0
Successfully installed rouge-1.11.1
Successfully installed rb-fsevent-0.10.2
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	"listen" from listen conflicts with installed executable from sass-listen

Successfully installed ffi-1.9.18
Successfully installed rb-inotify-0.9.10
Successfully installed sass-listen-3.0.7
Successfully installed sass-3.5.0
Successfully installed jekyll-sass-converter-1.5.0
The command '/bin/sh -c yes | gem install --no-ri --no-rdoc jekyll -v3.2.1' returned a non-zero code: 1
```

/cc @parkr @jekyll/owners

This affects everything from the 3.x branch which has broken every single build of Jekyll Docker.

**Comment by aboettger-tuhh** [comment]
```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    build-essential \
    nodejs \
    ruby-dev \
    zlib1g-dev

RUN apt-get -y upgrade

RUN gem install \
    bundler \
    jekyll

…
```

```
Step 4/13 : RUN gem install     bundler     jekyll
 ---> Running in e23591ac6257
Successfully installed bundler-1.15.1
Parsing documentation for bundler-1.15.1
Installing ri documentation for bundler-1.15.1
Done installing documentation for bundler after 6 seconds
Successfully installed public_suffix-2.0.5
Successfully installed addressable-2.5.1
Successfully installed colorator-1.1.0
Successfully installed rb-fsevent-0.10.2
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
	"listen" from listen conflicts with installed executable from sass-listen
Successfully installed ffi-1.9.18
Successfully installed rb-inotify-0.9.10
Successfully installed sass-listen-3.0.7
Successfully installed sass-3.5.0
Successfully installed jekyll-sass-converter-1.5.0
1 gem installed
The command '/bin/sh -c gem install     bundler     jekyll' returned a non-zero code: 1
ERROR: Job failed: Process exited with: 1. Reason was:  ()
```

**Comment by parkr** [comment]
Sounds like we need to restrict Sass to v3.4 or below.

**Comment by nex3** [comment]
I've released sass-listen 4.0.0, which should avoid stepping on the toes of the official listen gem. I've also released sass 3.5.1 which uses sass-listen 4.0.0.

**Comment by envygeeks** [comment]
Thanks so uch @nex3!  It felt awkward to have to `yes | gem --force` this morning to bring our builds up.

**Comment by jmhooper** [comment]
Our site builds are back up and running. Shout out to @nex3 for the quick turnaround 😄

**Comment by parkr** [comment]
Thank you so much @nex3!! 💗
