### ISSUE TITLE
WEBrick directory listings take priority over permalinks

### ISSUE THREAD

**Issue by MattSturgeon** [jekyll/jekyll#6222]
Prefixing the default post permalink and setting page permalink to the same value doesn't work.

Seems to only affect the local `jekyll serve` WEBrick server. GitHub Pages, for example, isn't affected.

---------

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [x] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

- in `_config.yml`, set permalink to `/blog/:title`
- create a page and set its permalink to `/blog`
- run `jekyll serve`
- visit [`localhost:4000/blog`](http://localhost:4000/blog)
  - Note that you are seeing the WEBrick server's directory index, not your page
- visit [`localhost:4000/blog.html`](http://localhost:4000/blog.html)
  - Note that the page _does_ exist
- in `_config.yml`, set permalink to `/notblog/:title`
- rerun `jekyll serve`
- visit [`localhost:4000/blog`](http://localhost:4000/blog)
  - Note that it works correctly now

## The Output I Wanted

I expected that visiting the permalink defined in the page's front matter would display that page.

Related to #3452

**Comment by pathawks** [comment]
So, Webrick doesn't redirect `/blog` to `/blog.html`?

**Comment by MattSturgeon** [comment]
That's right. If you remove the `/blog/` prefix from the post permalink, it works fine. I'm guessing WEBrick only redirects `blog` to `blog.html` if a `blog` directory doesn't actually exist.

**Comment by MattSturgeon** [comment]
Disabling directory indexing by setting [`:FancyIndexing`](http://ruby-doc.org/stdlib-2.0.0/libdoc/webrick/rdoc/WEBrick/Config.html) to `false` for `WEBrick::HTTPServlet::FileHandler` (somewhere in [here](/jekyll/jekyll/blob/master/lib/jekyll/commands/serve/servlet.rb)?) may help fix this.

While I know gh-pages probably uses a different http server (maybe nginx or apache), I couldn't reproduce this bug when I tested on github.io.

Using python's http.server module, which shows directory indexes too, I reproduced this.

**Comment by pathawks** [comment]
I wonder if there is some way we could configure one to take priority over the other

**Comment by MattSturgeon** [comment]
Ok, looking into `WEBrick::HTTPServlet::FileHandler` a little more, and learning some ruby as I go. The directory indexing stuff only happens after the normal GET request handling has failed, so disabling `:FancyIndexing` won't fix this bug anyway.

It may be possible to extend `search_index_files(req, res)` to fallback to `filename + '.html'` after its default check of `filename + '/'`, but this may mess with the `path_info` magic that `set_filename(req, res)` is doing, so we may end up having to override that too.

Thinking of something along these lines:

```ruby
def search_index_file(req, res)

  # First try the default check for index files in the directory
  if file = super
      return file
  end
  
  # Otherwise, try a custom check for directory.html in the parent directory
  
  # Extract basename from the end of res.filename
  path_arr = res.filename.scan(%r{/[^/]*})

  # Get the last non-empty section of the filename
  while basename = path_arr.pop
      break unless basename == '/'
  end

  if file = search_file(req, res, basename + '.html')
      res.filename = path_arr.join
      return file
  end
  
  return nil

end
```

**Comment by janpio** [comment]
Awesome that this was fixed in 3.6.x, but I think there still might something broken maybe:

(I hope it is ok just to reply to this issue, parts of the PR was so salty that I am a bit scared...)

I have a Jekyll project with `permalink: /:path` that has a `page.md` and a `page/second-page.md`. This should be served as `/page` and `/page/second-page`.

In 3.5.2 going to `/page` showed the directory listing. Now in 3.6.0 this is fixed thanks to this PR (if I understood correctly). Problem is while the page works, `/page` is still redirected to `/page/` (which is different to expected behaviour and also different to how it works on Github pages).

Here is a screenshot of Firefox devtools of the redirection:
![image](https://user-images.githubusercontent.com/183673/31851224-af725924-b661-11e7-9497-e96ebeb9865a.png)

Did I find the correct issue connected to this?
What would be an appropriate next step?

**Comment by pathawks** [comment]
@janpio So `/page` should not show a directory listing, and should not redirect to `/page/`, but should display `/page.html`, is that correct?

That seems like a regression, if this changed from 3.5.x to 3.6.0.

Could you open a new issue explaining all of this? This deserves it's own conversation.

**Comment by janpio** [comment]
Almost.

`/page` should show the content.
In 3.5.x it showed the directly listing after redirecting to `/page/`.
Since 3.6.0 it shows the correct content but still redirects to `/page/`. Content good, redirect still bad.

But just now I noticed that `/page/second-page` does actually render the content that should be at `/page`, which is of course really bad.

I will create a new issue with repro etc.

**Comment by pathawks** [comment]
What is on the disk, in the `_site` directory?

If the content is at `/page/index.html` then it seems like a redirect from `/page` to `/page/` is acceptable. But yes, do open an issue so we can give this the attention it needs.

**Comment by janpio** [comment]
No, content is in `page.html`. (Only `page/index.md` should be rendered to `/page/index.html`, right?)

See this new issue for complete description and reproduction repo:
https://github.com/jekyll/jekyll/issues/6459

**Comment by MattSturgeon** [comment]
Is the issue being reported that Jekyll appends a trailing slash (/) to the
URI? Correct content shown but incorrect URI formatting?

**Comment by janpio** [comment]
That is one part, yes.

Unfortunately there is another, pages inside the folder show the same content as the page clashing with the folder name. This only started with 3.6.x. See #6459 for a proper bug report with repro etc.

**Comment by janpio** [comment]
To make it less confusing I extracted the both problem (unnecessary redirect, wrong content rendered) into to seperate issues: https://github.com/jekyll/jekyll/issues/6459 + new https://github.com/jekyll/jekyll/issues/6475
