### ISSUE TITLE
Using different plugins in different Jekyll environments

### ISSUE THREAD

**Issue by queued37** [jekyll/jekyll#6223]
As far as I know, I can specify JEKYLL_ENV variable to make different results for different environments, and this variable is available as Liquid variable. However, I couldn't find a way to use different plugins for different environments.
This is helpful when, for example, I have to use some time-consuming build time plugins (e.g. image resizing) for production but I want a faster development environment.
Is there any other ways to achieve this or is it just not implemented?

**Comment by ashmaroli** [comment]
- If your ENV distinction is simply `production` and `development`, the easiest way is to *comment out* plugins you *don't need for `development`* while you're developing locally, and re-enable them before pushing to production.

- Another way is maintain multiple Gemfiles, one for each environment and then use Bundler's `BUNDLE_GEMFILE` env variable to select the required Gemfile. This could be delegated to a BASH script to avoid repeatedly switching both Bundler's and Jekyll's env variables.

**Comment by queued37** [comment]
The second way sounds nice. Then how about plugins in the _plugins folder? Can I easily disable/re-enable some of them?

**Comment by ashmaroli** [comment]
> Then how about plugins in the _plugins folder? Can I easily disable/re-enable some of them?

No. There is no sane way to delegate items in the `_plugins` folder. But if you're going to use BASH scripts, then I think there may be a way to handle the `_plugins` directory by having it regenerate between ENV vars.

Roughly, (and probably dirty):
  1. Maintain a special directory **outside** the site folder, say `_stash`, `_stash/dev_plugins` and `_stash/prod_plugins`
  2. Have your ENV scripts delete and re-create `_plugins` directory (with contents from the `_stash`) based on your ENV

**Comment by queued37** [comment]
Then maybe it would be good to have an option to disable some plugins in the `_plugins` folder.

**Comment by parkr** [comment]
We always select everything in `_plugins/`, but you can create a separate config file if you're using plugins and pass it in via `jekyll build --config _config.yml,_config.prod.yml`.


> Then maybe it would be good to have an option (in `_config.yml`) to disable some plugins in the `_plugins` folder.

I don't think this would be a good idea. To disable a plugin file, simply rename the file so it's not a `.rb` file, or remove the file. Adding a configuration option makes this much more complicated than it needs to be.

**Comment by parkr** [comment]
To be clear, the `plugins_dir` key in `_config.yml` specifies where the plugins directory is, so you can specify that in your env-specific config.
