### ISSUE TITLE
Suggestion: Add titles to links and a D3 icon

### ISSUE THREAD

**Issue by denjn5** [jekyll/jekyll#6230]
I'd like have simple titles added to the "contact me" links at the bottom. They'd just say the name of the site they link to (e.g., GitHub). (Adding title attributes to the svg-icons.html file)

I'd also like to see a d3 (bl.ocks.org) link added to the "contact me" section of jekyll (see bottom of https://denjn5.github.io/). I've done it locally. The question is, would there be enough use for it?  Not sure. But it looks neat. And it'd save me from re-adding it when jekyll updates.  If this idea is accepted, I'm happy to do the pull request (though I may need a bit of guidance).  --David 

- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [X] This is a feature request.

---

- [X] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

Love Jekyll, BTW!
-David

**Comment by ashmaroli** [comment]
Hello @denjn5, this request is more suited to be addressed at [jekyll/minima](https://github.com/jekyll/minima) &mdash; the default theme for a new Jekyll installation.

This repo is for the Ruby *backend* that generates your site.

**Comment by DirtyF** [comment]
Hi @denjn5, 👍 yeah we could add title on social icons. Feel free to submit a pull request on https://github.com/jekyll/minima/pulls

As for d3, this is something most users won't need and that can be easily added by overwriting the theme as you nicely did.
