### ISSUE TITLE
CSS not loading with quick-start instructions

### ISSUE THREAD

**Issue by rth** [jekyll/jekyll#6233]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] ~~I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`~~ Apparently this was the issue.
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
---
- [x] I am on (or have tested on)  Gentoo GNU/Linux 
(please let me know if you require additional information about my setup)

I run the quickstart instructions from https://jekyllrb.com/ , went to http://localhost:4000 and I get a website with no style (CSS) loaded. In the logs there is an `ERROR /assets/main.css' not found.` The expected output would be a quick start website with rendered CSS. 

Here are the contents of the created folder,
```
my-awesome-site % ls                                           
Gemfile  Gemfile.lock  _config.yml  _posts  _site  about.md  css  feed.xml  index.html
```

This might be related to the use of the minima theme by default and there are some related issues there (e.g. https://github.com/jekyll/minima/issues/16), however, IMO fundamentally this is an issue with the Jekyll quick start instructions not working as expected.

/cc @jekyll/ecosystem

**Comment by rth** [comment]
**Note:** one way of fixing this issue, is by copying and editing the `_includes/head.html` from the minima theme as described in https://github.com/jekyll/minima/issues/16#issuecomment-260677386 . However, the quick start instructions do not mention anything about it..

**Comment by ashmaroli** [comment]
You probably started off with an older version of Jekyll.
Newer versions of Jekyll do not generate `css/` directory when the `jekyll new --` command is run.

**Comment by DirtyF** [comment]
@rh thanks for the feedback, didn't reproduce your issue on macOS. 

Could you provide more info about your environment? (`gem env`) and paste the ouput of `bundle exec jekyll build --trace`?

**Comment by rth** [comment]
@ashmaroli @DirtyF Thanks for your response! Indeed, 
```
% bundle exec jekyll --version
jekyll 3.2.1
% which bundle exec jekyll
/home/rth/.gem/ruby/2.3.0/bin/bundle
```
I did previously run, `bundle install` and `bundle udpate`, which outputs,
```
$ bundle update
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 1.15.2
Using colorator 1.1.0
Using ffi 1.9.18
Using forwardable-extended 2.6.0
Using rb-fsevent 0.10.2
Using kramdown 1.14.0
Using liquid 3.0.6
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using rb-inotify 0.9.10
Using pathutil 0.14.0
Using sass-listen 4.0.0
Using listen 3.0.8
Using sass 3.5.1
Using jekyll-watch 1.5.0
Using jekyll-sass-converter 1.5.0
Using jekyll 3.2.1
Bundle updated!
```
I did also remove `$HOME/.gem/` prior to running the install.

 Sorry, my knowledge of ruby packaging is quite limited, my assumption was that I'd get the latest jekyll version for a new install with bundle; should have checked that it was indeed the case... 

Here is the output of `gem env`,
```
gem env                                                                                                                      [master] 
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.12
  - RUBY VERSION: 2.3.4 (2017-03-30 patchlevel 301) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/rth/.gem/ruby/2.3.0
  - USER INSTALLATION DIRECTORY: /home/rth/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby23
  - EXECUTABLE DIRECTORY: /home/rth/.gem/ruby/2.3.0/bin
  - SPEC CACHE DIRECTORY: /home/rth/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/rth/.gem/ruby/2.3.0
     - /usr/local/lib64/ruby/gems/2.3.0
     - /usr/lib64/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/rth/.gem/ruby/2.3.0/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /opt/bin
     - /usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0
     - /home/rth/.miniconda3/bin
     - /home/rth/admin/scripts
     - /home/rth/.local/bin/
```
and of
```
bundle exec jekyll build --trace 
Configuration file: /home/rth/symerio/website/my-awesome-site/_config.yml
            Source: /home/rth/symerio/website/my-awesome-site
       Destination: /home/rth/symerio/website/my-awesome-site/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.245 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

Please let me know if I should provide any additional information,

**Comment by pathawks** [comment]
You are using `jekyll 3.2.1`, which is _not_ the latest version of Jekyll.

**Comment by rth** [comment]
> You are using jekyll 3.2.1, which is not the latest version of Jekyll.

@pathawks Thanks, I get that. The question is why installing jekyll  from scratch using the quick start instructions on the homepage would not install the latest version?

**Comment by pathawks** [comment]
That's an interesting question, but should be covered in a separate issue. :+1:

**Comment by rth** [comment]
@pathawks I reinstalled everything and can't reproduce this either.

I suspect what must have happened is that previously I had an outdated system install of `jekyll` and when after running `gem install jekyll bundler`, I run `jekyll new my-awesome-site` that outdated install got used, instead of the one in ` ~/.gem/ruby/2.3.0/bin/` since that location is not in `$PATH` by default. This then set the jekyll version for the Gemfile which updated the version of jekyll in `~/.gem/` when I run `bundle install/update`.  Maybe I  should have run `bundle exec jekyll new my-awesome-site` instead.  (In my limited understanding of ruby packaging).

Thanks for your help, and sorry for the noise..
