### ISSUE TITLE
Cannot push Jekyll project to Github

### ISSUE THREAD

**Issue by pvlcor** [jekyll/jekyll#6235]
Hello,

When I'm pushing latest changes to my Jekyll project repo on Github, I get next error.
I've increased http.Buffer in git config, decreased size of every file in my commit to be less than 1MB, but error 36 is still there ((

Counting objects: 70, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (70/70), done.
Writing objects: 100% (70/70), 7.23 MiB | 0 bytes/s, done.
Total 70 (delta 30), reused 0 (delta 0)
**error: RPC failed; curl 56 SSLRead() return error -36**
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by pathawks** [comment]
Sorry you are having problem with your Git client.

This issue really has nothing to do with Jekyll. Maybe you could try contacting GitHub support?
