### ISSUE TITLE
Jekyll build --watch suddenly started to silently crash on windows

### ISSUE THREAD

**Issue by looeee** [jekyll/jekyll#6237]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

--

- [x] I am on (or have tested on) ***Windows*** 10+

- [x] I was trying to build.

## My Reproduction Steps

Run jekyll serve, or jekyll build --watch. 
These worked up until yesterday, and I am sure I did not edit the config or install anything new since then.

This may be related to #5462, and I have tried all the suggestions there, including the following:

* updated from jekyll 3.3.1 to 3.5.1
* ensured wdm gem is installed
* ran gem clean and then bundle install
* ran jekyll clean
* moved project to a new folder and completely rebuilt
* run commands as 'bundle exec jekyll build --watch'
* ran the commands with --safe, --trace and --verbose options

```bs
D:\Web\my_site> bundle exec jekyll build --watch
Configuration file: D:/Web/my_site/_config.yml
            Source: D:/Web/my_site
       Destination: D:/Web/my_site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 5.729 seconds.
 Auto-regeneration: enabled for 'D:/Web/my_site'

// then after around 5 seconds crashes to
D:\Web\my_site>
```

However, I did make a completely clean blog and `build --watch` works there. 
I'll continue to work on this and report back if I find a solution. 

## The Output I Wanted

I'm finding it very hard to track down the issue here, as there are no errors logged. It may be that I've included something stupid in my site somewhere - but the real bug / issue is the lack of error reporting.

/cc @jekyll/build

**Comment by looeee** [comment]
OK, I have figured out how to reproduce the issue on my black site. Adding the following line to my gemfile

`gem 'wdm'`

then `bundle install`, `jekyll build --watch` and boom! Silent crash as soon as I change a file.

**Comment by Rubemlrm** [comment]
that warning message is the default behaviour for jekyll at windows. in the other hand , that started happend after any kind of update ?

**Comment by looeee** [comment]
What is the purpose of the message then? Why would I want avoid polling for changes? 

Yes, Windows updates a couple of days ago, so maybe it's related to that.

I'm on Windows 10 Home Insider Preview
Build 16232.rs_prerelease 170624-1334

**Comment by pathawks** [comment]
If the only change is an update to the OS, it sounds like that's pretty clearly the smoking gun.

Have you reported the issue to the *wdm* folks? They may not have many people testing beta OS updates.

**Comment by ashmaroli** [comment]
@looeee From my own experience in using Jekyll on Windows (Win 7), I can advocate the fact that `gem 'wdm'` is **not** required on Windows for the `--watch` option to work. So you can safely remove it from your Gemfile and uninstall entirely..

The warning message comes from `gem 'listen'` which Jekyll has no control over.. so ignore it..

**Comment by looeee** [comment]
@pathawks I'll do so - however the last commit to that project was two years ago, so I'm not sure how useful that will be. 

@ashmaroli thanks, I guess I'll report this to the listen people as well.

**Comment by ashmaroli** [comment]
> I guess I'll report this to the listen people as well

Already did.. [guard/listen](https://github.com/guard/listen/issues/421)

**Comment by looeee** [comment]
Awesome, thank you! 

Ok, I'll go ahead and  close this. Thanks for the quick help guys! 😄

**Comment by looeee** [comment]
Actually one thing I have noticed - there could be so many causes at this stage that I won't reopen this - but running `jekyll serve --incremental` my build times have gone from ~5 seconds to ~30 seconds.

**Comment by ashmaroli** [comment]
> my build times have gone from ~5 seconds to ~30 seconds

Is this with or without the inclusion of the `wdm` gem?

**Comment by looeee** [comment]
Without - with the gem I just get the silent crash. 
Is it likely to affect build times? If not I'll search for other causes. As I mentioned earlier I upgraded from jekyll 3.3.1 -> 3.5.1 while debugging this, so it may be related to that or one of the other changes I made instead.

**Comment by ashmaroli** [comment]
`--incremental` switch is supposed to reduce the build time as it re-builds only those files that have changed from previous build.

At this point, it'd be better to know if these issues are reproducible on an entirely fresh `jekyll new --` directory installation.

**Comment by looeee** [comment]
Right. At the moment I don't have any more time to spend on this. I've already lost most of a day to it, so I'm going to have to consider it "fixed" for now. If I manage to work out what's causing the increase in build time though I'll report back here. 

Thanks again 👍

**Comment by ashmaroli** [comment]
one last thing then.. any special reports from running `jekyll doctor` on the site?

**Comment by looeee** [comment]
`bundle exec jekyll doctor`

> Your test results are in. Everything looks fine.

Also, I can see from running 
`bundle exec jekyll serve -t -V --incremental`

That incremental build is only partially working. Sass regeneration is skipped if I don't change stylesheets (in any case this is handled by jekyll-assets), but otherwise all pages are completely rebuilt on any change.

**Comment by looeee** [comment]
After working on this for a couple of hours, without changing any other settings, the build time has dropped back down to a couple of seconds. I'm a bit confused, but it all worked out in the end so 👍
