### ISSUE TITLE
Question: include parameter syntax with array

### ISSUE THREAD

**Issue by steveoh** [jekyll/jekyll#6242]
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+

## My Reproduction Steps

I am starting to remove some duplicate content in my pages and to do so I have taken advantage of the includes template with parameters. I am getting hung up on trying to pass an array of values as an include parameter.

I have failed trying the following:

```
{% include page.html param=[1,2,3]
{% include page.html param=1 param=2 param=3
```
The first option fails and the second option returns the last param value of 3.

For the time being I have used a long string with a separator `| split: ';'` but that makes for some really long strings that are not super friendly to edit. _Should_ or _could_ the two above param passing syntaxes work for includes?

/cc @jekyll/documentation

**Comment by ashmaroli** [comment]
You could `assign` a variable beforehand and pass that variable as `param` instead..
Say, you're passing the array of `plugins` in your config file to the include.. then,
```
{% assign my_plugins = site.plugins %}
{% include page.html param=my_plugins %}
```
I could directly pass `site.plugins` as param as well.. but taking the longer route to illustrate other possibilities

**Comment by steveoh** [comment]
@ashmaroli - If I can pass a pre-existing collection that is great! My problem is how would I create a new collection? I don't know the correct syntax and can't find any examples.

**Comment by ashmaroli** [comment]
Yes there is no straightforward way to create an array with liquid. But there are various ways to obtain an array depending on the context.
e.g. `split`, `push`, `unshift` etc..

But this is not the place for that type of discussion. Sorry
We have a community forum at https://talk.jekyllrb.com.

**Comment by steveoh** [comment]
I ended up using frontmatter to create the arrays. Thanks!
