### ISSUE TITLE
[Discussion] Integrate gem `htmlbeautifier` into Core

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#6243]
While I was working on converting template files from Minima to Liquid 4.0, I realized that perfect implementation of `whitespace control` feature from Liquid 4.0 is not going to happen smoothly because the theme-developer would've to constantly monitor the generated HTML to ensure proper indentation and formatting (if he's concerned about the aesthetics of the generated markup)

Looking elsewhere, I found two gems:
  - [`htmlbeautifier`](https://github.com/threedaymonk/htmlbeautifier) &mdash; A lightweight library for beautifying HTML string.
  - [`jekyll-tidy`](https://github.com/apsislabs/jekyll-tidy) &mdash; A Jekyll Plugin that uses above library and another for minifying HTML

Is @jekyll/core interested in supporting HTML beautification natively, using `HtmlBeautifier`?

/cc @jekyll/affinity-team-captains

**Comment by parkr** [comment]
I personally feel that tidying HTML should be a plugin feature. If a plugin is used so ubiquitously that we want to bring it into core then that's fine, but we have had issues when modifying HTML. The jekyll-mentions and jemoji plugins, for example, use HTML Pipeline & nokogiri which attempt to "beautify" the HTML automatically: it enforces HTML 4 and *any fragment of text* must be wrapped in `<html><body></body></html>` unless we manually strip it out. Beautifying plugins usually cause more pain than they're worth in my experience so making it a part of Core will only bring pain and misery to users based on the evidence and experience I have.

**Comment by pathawks** [comment]
Agree with @parkr. While I can understand the motivations for wanting to tidy sourced, it does not belong in core.

**Comment by parkr** [comment]
Thanks for putting it up for discussion, @ashmaroli! I really appreciate your energy and ideas :heart:

**Comment by pathawks** [comment]
Is there anything like source maps that exists for HTML? _That_ could be an interesting plugin.

**Comment by ashmaroli** [comment]
That's a very interesting idea.. :heart:
