### ISSUE TITLE
nil values in Liquid {% cycle %} are ignored after 3.5.0

### ISSUE THREAD

**Issue by AlHoriun** [jekyll/jekyll#6251]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

- update Jekyll from 3.4.3 to 3.5.1
- run Jekyll build

One of my pages contains a liquid cycle to add tags every 4 'for' iterations i.e.

```
{% for post in site.posts %}
    {% cycle 'add row' : '<div class="row">', nil, nil, nil %}

        <div class="col-sm-3">
          //Column content
        </div>

    {% cycle 'end row' : nil, nil, nil, '</div>' %}
{% endfor %}
```
Before updating to 3.5.1 from 3.4.3 it was adding a  `<div class="row">` every 1/4 iteration and  `</div>` after 4/4 iteration. 

After updating it adds  `<div class="row">` and  `</div>` on every iteration, completely ignoring  `nil, nil, nil`  blocks.

This can be fixed by replacing `nil` with empty string. i.e. 
`{% cycle 'add row' : '<div class="row">', '', '', '' %}`

Bug is present on both 3.5.0 and 3.5.1 and can't be reproduced on 3.4.3 or 3.4.5. May be related to Liquid v4 update in this version.

## The Output I Wanted

Shouldn't wrap every `<div class="col-sm-3"></div>` with a `<div class="row"></div>`

**Comment by ashmaroli** [comment]
um.. Jekyll is currently on `v3.x.x`.. Please edit your post to avoid confusion..

**Comment by AlHoriun** [comment]
Fixed, hope that didn't confuse too many people

**Comment by ashmaroli** [comment]
> hope that didn't confuse too many people

Nope. You fixed it soon enough.. :wink:

> May be related to Liquid v4 update in this version.

Yes, This change is not related to Jekyll. You'll have to take this up to the `shopify/liquid` repo.

**Comment by Crunch09** [comment]
@DirtyF I think this can be closed as @ashmaroli mentioned this seems like it needs to be fixed upstream in Liquid.
