### ISSUE TITLE
Links to repository on history page are broken

### ISSUE THREAD

**Issue by nickmccurdy** [jekyll/jekyll#6254]
[History](https://jekyllrb.com/docs/history/) links are in this mangled format:

https://jekyllrb.com/docs/history/%7B%7B%20site.repository%20%7D%7D/issues/...

/cc @jekyll/documentation

**Comment by ashmaroli** [comment]
`not-reproduced` on Google Chrome and Mozilla Firefox, on Windows

**Comment by ashmaroli** [comment]
Thank you for reporting this @nickmccurdy :smiley:

**Comment by nickmccurdy** [comment]
@ashmaroli Wow, that broke the whole page? Tricky...

**Comment by ashmaroli** [comment]
> that broke the whole page?

yep.. that `{% raw %}` tag caused the break.. but I was wrong in suggesting backticks to rectify it.. Will require wrapping the tag within a `raw` tag itself..

```
{% raw %}{% raw %}{% endraw %}
```

**Comment by nickmccurdy** [comment]
I ad a feeling, since otherwise it would just template the tag in backticks.

**Comment by pathawks** [comment]
Could we just escape the braces?

`&#123;% raw %&#125;`

**Comment by ashmaroli** [comment]
> Could we just escape the braces?

Then we *can't* have it processed into a `code` element by enclosing ith within backticks
```
`&#123;% raw %&#125;`   # => <code>&#123;% raw %&#125;</code>
&#123;% raw %&#125;     # => {% raw %}

`{% raw %}{% raw %}{% endraw %}`     # => <code>{% raw %}</code>
```
