### ISSUE TITLE
StaticFile should alias to_json to to_liquid

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#6259]
If you call `site | jsonify` static files are represented as:

<img width="377" alt="screen shot 2017-08-01 at 6 13 53 pm" src="https://user-images.githubusercontent.com/282759/28849485-34c03dd8-76e5-11e7-8885-e5886b31a891.png">

We have a `to_liquid` method, which returns the static file drop. We should alias that method to `to_json` to allow for prettier output for `static_file | to_json`.

**Comment by nicolaguidi** [comment]
I would like to tackle this one, but first-timer here and I'd like some clarifications to know if I'm on the right track.

I was thinking about adding `alias_method :to_json, :to_liquid` to `lib/jekyll/static_file.rb` and maybe testing using something along this line: `Test.method(:to_json) == Test.method(:to_liquid)`.

Could it be a viable solution?

**Comment by xrav3nz** [comment]
Sorry @nicolaguidi I should have left a comment when I started to look at this last night. Made the change but haven't had time to PR until now. 

I took the approach of delegating `to_json` to `to_liquid`, since jsonifying `StaticFileDrop` yield more information. Open to suggestions!
