### ISSUE TITLE
Themes: support for a _themes directory

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#6272]
In #5434 @shawnbot detailed a support for a `_themes` directory, as a fallback for gem-based themes.

> Attempt to require the gem name. If that succeeds, add its "scaffold directories" to the appropriate resolution paths, and perform any other Gem-based theme initialization necessary.
Otherwise, check for the existence of _themes/{name} in the source dir. If that exists, add all of its scaffold directories to the resolution paths instead.
If the directory doesn't exist, throw an error.

/cc @jekyll/themes

**Comment by pathawks** [comment]
I don't understand the value this would add for the majority of Jekyll users. It seems like it would only make everything related to themes a _little more_ complicated.

**Comment by qaisjp** [comment]
If this is not implemented by December, I can give this a go.

**Comment by ashmaroli** [comment]
--- Mode: UTOPIA ---

I see this as a **`v4.0`** feature where `_themes` represent a special directory which houses all files and folders related to a theme (`_layouts`, `_includes`, `_sass`, `assets` and *also `_data`*)

 - This move would cleanup a project's root directory to a certain extent.
 - To facilitate maintainability and reduce confusion, this move **ditches backward-compatibility entirely** and **Jekyll would no longer look for above folders at the root**. Instead looks at either `./_themes` or the `theme-gem`.

**Comment by DirtyF** [comment]
Seems like a duplicates of #6199. Closing then.

**Comment by parkr** [comment]
I'd love to ship something like this in v3.7. We have all the mechanics in the Theme class, just need to update detection!

**Comment by ashmaroli** [comment]
> ship something like this in v3.7

That would mean Jekyll looking for the presentational files in 3 places: `at_root`, `./_themes/`, `theme-gem`..

**Comment by DirtyF** [comment]
@parkr That would be awesome. I'll update #6199 consequently, if you want to provide some guidance.

@ashmaroli yep, kind of what Hugo does. (default, layouts, themes).

**Comment by ashmaroli** [comment]
hmm.., in that case I suggest we establish the override order first and have it prominently displayed in #6199  as reference.

So is it going to be: ?
```
at_root  >>  _themes/**/*  >>  theme-gem
```
