### ISSUE TITLE
unclear install

### ISSUE THREAD

**Issue by aninspiredlifeforme** [jekyll/jekyll#6276]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## The Output I Wanted

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by qaisjp** [comment]
what's unclear?

**Comment by aninspiredlifeforme** [comment]
It's unclear how to create a new site using the Jekyll documentation. Now
that I know how to do it, it could've been explained in like 4 lines on the
site and saved me a couple hours. Somewhere it needs to say, 1. in your
repository in command line, type jekyll new new-site-name. 2. This cannot
be accessed at username.github.io. It must be accessed at
username.github.io/new-site-name.

It was also unclear how to install a theme which took me forever to figure
out. Steps like this could be helpful on the site. 1. Find a theme you like
and go to repository containing it. 2. Click Fork in top right corner. 3.
Add a branch called gh-pages. 4. Go to Branches tab and set gh-pages as
default. 5. Look under settings to see new url to access theme. It will not
be where your main files are but in a folder. Example url would be
username.github.io/theme-name

Adding instructions to the site will make it ten times easier for new
people to figure out how to get started with Jekyll.

**Comment by ashmaroli** [comment]
The thing is, Jekyll has nothing to do with hosting on GitHub Pages.
On the contrary, GitHub Pages utilizes Jekyll to *build* sites on its server. So the specifics of hosting on GHP need not be covered in Jekyll's docs.

Regarding the themes, again, its not a Jekyll thing. The "themes" are simply static site templates that "utilize" Jekyll for processing. Its upto the themes to document their installation and usage.

**Comment by aninspiredlifeforme** [comment]
Ohhhh that makes more sense. I apologize for my severe lack of
understanding. Thank you!
