### ISSUE TITLE
Local serve with post and relative_url fails

### ISSUE THREAD

**Issue by mryellow** [jekyll/jekyll#6308]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

```
{% for post in site.posts %}
  {{ post.url | relative_url }}
{% endfor %}
```

Returns:

`/http://localhost:4000/baseurl/permalink.html`

## The Output I Wanted

`http://localhost:4000/baseurl/permalink.html`

or perhaps, "relative":

`/baseurl/permalink.html`

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

**Comment by pathawks** [comment]
What does your `_config.yml` look like?
Specifically, what are the values of `url` and `baseurl`? What gems/plugins are you using?

How can somebody recreate this problem?

**Comment by mryellow** [comment]
`baseurl: "/news"`
`url: "https://example.com"`

The `baseurl` is being inserted where it should, the `url` is being ignored and replaced with `http://localhost:4000` as it should. Then a `/` is being inserted before everything.

Noticed some discussion around githubpages which involved changing `baseurl: "/"` to `baseurl: ""`. Perhaps some changes in there ended up breaking `relative_url`.

Seems `relative_url` behaviour has changed from "Convert this to a relative URL" to "Take a post path and throw a slash in front of it"

**Comment by mryellow** [comment]
> What gems/plugins are you using?

Actually... It does!

https://github.com/mryellow/jekyll-feed-json/blob/master/lib/jekyll-feed-json/generator.rb#L55

Figured that was by value not reference and only used for the JSON feed but guess it's modifying the site data.

My bad, sorry for the noise.

**Comment by mryellow** [comment]
Confirmed, works as intended without that.

**Comment by mryellow** [comment]
hmm or maybe not, I had `prepend: site.baseurl` in there for that last test.

`http://127.0.0.1:4000/http://localhost:4000/baseurl/permalink.html`

I'm just going to use `prepend: site.baseurl`, easier to know it will do what it says on the tin.
