### ISSUE TITLE
revisit templating page's info on tags 

### ISSUE THREAD

**Issue by Strangehill** [jekyll/jekyll#6312]
The templates page talks about  "a few handy filters and tags" specific of Jekyll. This suggests that there are more than are listed on the page, but does not point in the direction of an authoritative reference.
In #6311, I've tried phrasing things a little differently, but I might have stopped short, not knowing with certainty whether the page is already the comprehensive listing I think it should be.
I also moved the explanation for the jekyll-gist plugin from this page to the plugins where it makes more sense to have it, even though at the moment, it is the only specific plugin that gets more than a line of explanation. So although it's not the perfect fit on that page, it seems closer to home.

/cc @jekyll/documentation

**Comment by Strangehill** [comment]
In addition to clarifying the role the templates page looks to play, I've moved some text between pages to make it easier for the readers to orient themselves with regards to the information that can be found in the templates page, the plugins page, and the resources page.

Afer some reviews, I've reduced information on the jekyll-gist plugin to a one-liner in the available plugin list of the plugins page.

**Comment by Strangehill** [comment]
With the removal of jekyll-gist information in the PR, I'm wondering if documentation has been stripped too clean of plugin examples. The current plugins page mostly shows development instructions for the ruby developer, rather than an intro to what jekyll plugins can be. 
/cc #5794

**Comment by parkr** [comment]
@Strangehill it's definitely meant to be a place for the developer of the plugins & the plugin types. The directory should be more of a place for discovering what is possible with Jekyll plugins.

**Comment by Strangehill** [comment]
Got it! Can't wait for the directory.
