### ISSUE TITLE
Jekyll storing messages in Logger, it's not using, slowing down builds, +mem

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#6313]
https://github.com/jekyll/jekyll/blob/6b8de2a75794be30d9816cf44e914088fca9a31e/lib/jekyll/log_adapter.rb#L102-L106

When we patch out `messages << msg`
```
mem%s: 145576
mem%e: 167840
real	0m32.676s
user	0m6.324s
sys	0m0.400s
```

Without the patch
```
mem%s: 151000
mem%e: 175708
real	0m44.494s
user	0m7.072s
sys	0m0.548s
```

This test is very low quality, considering we disabled 11/12 of our logging.  This problem was discovered when our builds were consuming upwards of 500mb capping out our memory limits for Jekyll builds, that's a lot of memory for something doing such a simple task.

**Comment by parkr** [comment]
Wow, that's a long time in saving the messages. We need to log them for Pages but we can certainly make this configurable based on log level: If the log wont be output, then don't save it to the array. Maybe using a TeeLogger or something that would allow us to keep a record of the logs (could just be a StringIO) would be an acceptable solution.
