### ISSUE TITLE
add SUPPORT file

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#6323]
It should at least help us point to https://talk.jekyllrb.com for usage support.
Also mention https://jekyllrb.com/help/ for getting help.

Anything else we should mention in this file @jekyll/affinity-team-captains ?

see: https://help.github.com/articles/adding-support-resources-to-your-project/

👋  @benbalter Could you point to an existing good SUPPORT file example for inspiration?

**Comment by benbalter** [comment]
Here's [the Pages Gem SUPPORT file](https://github.com/github/pages-gem/blob/master/.github/SUPPORT.md), and [Atom's](https://github.com/atom/atom/blob/master/SUPPORT.md).
