### ISSUE TITLE
cannot seem to get started on a brand new fedora 26 install

### ISSUE THREAD

**Issue by gideondsouza** [jekyll/jekyll#6328]
So I have a site running jekyll for years. I know the drill. 

I believe it might just been some kind of dependency issue or some version mismatch with ruby/gems/jekyll. It seems to just complain like this:

```
New jekyll site installed in /home/gideon/my-awesome-site. 
[gideon@gideon ~]$ cd my-awesome-site/
[gideon@gideon my-awesome-site]$ bundle exec jekyll serve
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
LoadError: cannot load such file -- json

```
And yes, I've done gem install bundle, gem update --system, I've done gem install json and so on. I've looked at many threads, github issues and stackoverflow posts. But I can't seem to get to point of what is wrong and I think that is just worsening my system. 

If I check for jekyll version I get this:

```
[gideon@gideon my-awesome-site]$ jekyll -v
WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
jekyll 3.5.2

Thus, I am following instructions as this **does cause a problem** running existing sites and brand new ones.
```

- [ x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ x] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ x] It was another bug.

## My Reproduction Steps

I have a working ruby dev env I did not use rvm. I'm not a ruby programmer but I am a developer.
I tried to follow : 

```
 gem install jekyll bundler
~ $ jekyll new my-awesome-site
~ $ cd my-awesome-site
~/my-awesome-site $ bundle exec jekyll serve #borks here
#with the aforementioned cannot load json error.

```
I also tried running and existing very old jekyll site and that didn't work too

## The Output I Wanted

Simply that the site should run.

**Comment by ashmaroli** [comment]
Hi, can you please post the output from running the command with the `--trace` option

**Comment by gideondsouza** [comment]
Ok, so somewhere I found instructions that I needed a `Gemfile` (I don't know why this stuff isn't in the jekyll getting started)

Inside the Gemfile I just added `gem json` and it worked. For the newly created my-awesome-site and my existing one.

**Comment by ashmaroli** [comment]
When one runs `jekyll new --` using Jekyll 3.2 and above, a `Gemfile` is automatically created for you.
Also, Bundler does complain when it does not find a Gemfile in your project directory.

**Comment by parkr** [comment]
Looks to me like an old Ruby version we don't support anymore. Can you paste the output of `ruby--version`?

**Comment by parkr** [comment]
Whoops, that's `ruby --version` with a space.

**Comment by gideondsouza** [comment]
Here you go:

```
[gideon@gideon theme-files]$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

Somehow now everything seems to work. I bought a new Jekyll theme from somewhere and that theme side seems to work just fine. 

Also, originally I didn't create my site with bundler so I didn't have a Gemfile. and also somewhere in the flurry I did get bundler complaining that I didn't have a Gemfile so I created one.

**Comment by parkr** [comment]
Glad to hear it's all working!
