### ISSUE TITLE
in `sub!': invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by liushaofeng89** [jekyll/jekyll#6341]
/usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll.rb:173:in `sub!': invalid byte sequence in UTF-8 (ArgumentError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll.rb:173:in `sanitized_path'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll/site.rb:369:in `block in in_source_dir'

**Comment by DirtyF** [comment]
Please provide more details:  what did you do before you get this error ?

**Comment by pathawks** [comment]
It would have been helpful for the issue template to be filled out. 😕

**Comment by parkr** [comment]
Looks like some path has non-UTF-8 characters? :/

**Comment by liushaofeng89** [comment]
@DirtyF what detail message do you want?

**Comment by liushaofeng89** [comment]
@parkr What's mean?  Can you give me some advise to fix the encoding problem? I'm Chinese, so UTF-8 is the best encoding for me,thanks

**Comment by DirtyF** [comment]
@liushaofeng89 Have you try to run your command with `--verbose` or `--trace`?

**Comment by parkr** [comment]
We actually did some work recently to fix encodings! This should be resolved on master.
