### ISSUE TITLE
Insert default generator meta-tag

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#6347]
I recently stumbled upon https://w3techs.com/technologies/details/cm-jekyll/all/all who claims to detect the version used by Jekyll's websites. I don't know how they handle all cases (maybe they index the `Gemfile.lock` when publicly available?), it does not seem very reliable to me.

I know that [Hugo inserts a default meta tag](https://github.com/gohugoio/hugo/blob/master/transform/hugogeneratorinject.go) if none is present, is this a mechanism @jekyll/build would consider adding?

It could give @jekyll/core more visibility on how often people upgrade, what version we should continue to support, the number of jekyll-powered sites, etc. 

It's fine if we don't care about vanity metrics.

**Comment by mattr-** [comment]
Would we use something like the site you pointed out to get the details provided by the meta tag? I'm ok with the idea of adding one by default for new sites. We most likely won't get that for older sites though.

**Comment by pathawks** [comment]
There are also cases where somebody could publish a website once, and never intend to update it. Should we view this as a signal that we need to continue supporting that version of Jekyll?
Due to the static nature of Jekyll, I don't think this is as useful as it is for platforms like WordPress.
That said, I do include a generator tag on my own Jekyll sites.

**Comment by DirtyF** [comment]
@mattr- I hope this can help this kind of service to display more accurate data. It would certainly help Wappalyzer for instance that hopes for that kind of tag.

https://github.com/AliasIO/Wappalyzer/blob/e96fb5ba30aecca00b4aa2db8429f2d0eb8b26de/src/apps.json#L4018 

@pathawks The idea here is not to tell users to upgrade , but when I see that Wappalyzer only detect 3700 Jekyll sites, when there's 1 million GitHub Pages sites, I thought this could help.

**Comment by parkr** [comment]
I would love to be able to detect which version a site was built with. we have historically had issues reading & munging user data so adding a meta tag might be problematic. But we could easily add it to something like Jekyll-seo-tag.
