### ISSUE TITLE
Support index.json in DirectoryIndex

### ISSUE THREAD

**Issue by adborden** [jekyll/jekyll#6348]
Hey there, I'm using Jekyll collections to generate JSON APIs. In order to have more flexible, prettier URLs, it would be nice if Jekyll supported `index.json` in the Webrick DirectoryIndex. This would allow you to have API URLs like `/api/agency/gsa/` instead of `/api/agency/gsa.json`. Currently, `jekyll serve` just shows the directory listing because it doesn't know to look for `index.json` in directories. I've got my production config setup this way, so I'm just looking for the development server to also have this behavior. I'm happy to submit a pull request if you're OK with this addition.

- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

**Comment by parkr** [comment]
We like to keep `jekyll serve` matching GitHub Pages, but I'd be open to making index page extensions configurable.

**Comment by parkr** [comment]
Alternatively, you could use a separate server locally.

**Comment by adborden** [comment]
I'd prefer if there was Jekyll solution. It's easier for collaborators to run when it's just `bundle install; bundle exec jekyll serve`.

If we added this as a config option, are you thinking something like a list of files in `_config.yml`?
```yml
directory_index:
- index.html
- index.htm
- index.xml
- index.json
```

Or like a boolean just for json?

**Comment by parkr** [comment]
Yeah, a listing like that, or something we have for markdown extensions:

```yaml
directory_index_exts: "html,htm,xml,json"
```

More explicit is probably nicer here. I'd shy away from the boolean option. Which would you prefer here? Feel free to submit a PR.

**Comment by parkr** [comment]
[Here's where we keep the list currently.](https://github.com/jekyll/jekyll/blob/ac3e6b384f80c4726f0eac19a6f1a73ee7376d62/lib/jekyll/commands/serve.rb#L88-L94)

**Comment by adborden** [comment]
I went with your suggestion of following the markdown_ext pattern. I think it's good to be consistent. It also allows you to _reduce_ the list if you'd like.
