### ISSUE TITLE
cannot switch to cayman or any other gem based themes 

### ISSUE THREAD

**Issue by beyond2013** [jekyll/jekyll#6351]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [] It was another bug.

## My Reproduction Steps
I followed getting started and had the basic blog working fine with builtin minima theme. But I cannot switch to any other theme. 

### Following are the steps I took on my laptop
---
1. included `gem jekyll-theme-cayman` in my `Gemfile`
2. ran bundle install
3. included `theme: jekyll-theme-cayman` in  `_config.yml`
4. ran  `bundle exec jekyll serve` which results in the following:

>  Generating... 
     Build Warning: Layout 'post' requested in _posts/2017-09-03-how-i-setup-myblog.markdown does not exist.
     Build Warning: Layout 'page' requested in about.md does not exist.
     Build Warning: Layout 'home' requested in index.md does not exist.

5. I have compared the directory structures of gems `minima` and `jekyll-theme-cayman` and found that `_includes` folder was missing in `jekyll-theme-cayman` so i copied it over from `minima` but I see the same build warning.

### Following are the steps I took on my [github-repo](https://github.com/beyond2013/myblog)
---
1. In `GitHub Pages` section of my repo's `Settings`
2. Clicked `Change theme` selected a different theme (tried cayman, and various others)
3. The message `Your site is currently using the ----- theme.`correctly reflects the change
But the site does not render anything

## The Output I Wanted
Wanted the change of theme to work.

**Comment by ashmaroli** [comment]
Hello @beyond2013,
The build warning says you're missing **layouts** instead of **includes**..

The theme Cayman has only one layout: `_layouts/default.html`
So things should render fine once you edit the files in the warning to use the `default` layout

**Comment by beyond2013** [comment]
Thanks for the help @ashmaroli your comment proved very helpful.
