### ISSUE TITLE
Posts generated but not served

### ISSUE THREAD

**Issue by chengdi123000** [jekyll/jekyll#6352]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] I am on (or have tested on) ***Windows*** 10+
- [x] It was another bug.

---

I am trying to use MSYS2 to install and maintain my github-pages which was created using jekyll: [https://github.com/chengdi123000/chengdi123000.github.io](https://github.com/chengdi123000/chengdi123000.github.io). I used the `pacman` to install mingw-64 version of ruby and gem on my MSYS2 shell (which is also mingw64 version rather than msys version), And I am using `ruby.taobao.org` as the source. 

I am using the latest packages available and use `bundle update` to make it updated.

I also run `jekyll doctor` and it said it is OK.

My problem is the posts are generated but cannot be served locally. When I click the link of my posts on the homepage, it shows 404 page rather than the post page. I checked the directory `_site`. The post pages are generated. However, the `jekyll serve` process tell me `[2017-09-10 16:48:57] ERROR: xx..html' not found.`

The last time I used the official guide to install ruby and jekyll on windows (which includes standalone ruby installer and MSYS2 to bundle). It works and I created and uploaded the `https//github.com/chengdi123000/chengdi123000.github.io` repository. Everything works. However, when I switched to pure MSYS2 platform. Everything works except that the posts are generated but not served.

**Comment by pathawks** [comment]
It seems like this is an environment issue, rather than a bug in Jekyll itself?
Have you tried serving your site on another platform? Can you provide a link to your source?

**Comment by ashmaroli** [comment]
@chengdi123000 whats the status on this? To confirm that you're on the latest version of Jekyll, run **`bundle exec jekyll --version``**.
