### ISSUE TITLE
Could not find gem 'minima (~> 2.0)'

### ISSUE THREAD

**Issue by BourAbdelhadi** [jekyll/jekyll#6353]
Hello ,

I have an issue with jekyll 

I followed these steps : 

`gem install jekyll bundler`
`jekyll new blog`
`cd blog`
`bundle exec jekyll serve`

am getting this error : 

`Could not find gem 'minima (~> 2.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.`

After running `bundle install`  , i got this error 

The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your
bundle as root will break this application for all non-root users on this machine.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 3.0.0
Using bundler 1.15.4
Using colorator 1.1.0
Fetching ffi 1.9.18
Installing ffi 1.9.18 with native extensions
Using forwardable-extended 2.6.0
Using rb-fsevent 0.10.2
Using kramdown 1.15.0
Using liquid 4.0.0
Using mercenary 0.3.6
Using rouge 1.11.1
Using safe_yaml 1.0.4
Using addressable 2.5.2
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby2.3 -r ./siteconf20170910-12894-sa8gvn.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/ffi-1.9.18 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.18/gem_make.out

An error occurred while installing ffi (1.9.18), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.18'` succeeds before bundling.

In Gemfile:
  jekyll-feed was resolved to 0.9.2, which depends on
    jekyll was resolved to 3.5.2, which depends on
      jekyll-sass-converter was resolved to 1.5.0, which depends on
        sass was resolved to 3.5.1, which depends on
          sass-listen was resolved to 4.0.0, which depends on
            rb-inotify was resolved to 0.9.10, which depends on
              ffi

**Comment by BourAbdelhadi** [comment]
Well , I found the solution , if you have an issue like this : try to install : 

`gem install minima`

& 

`gem install jekyll-feed`

**Comment by parkr** [comment]
Glad you got it figured out! Looks like a conflict and a problem installing ffi.
