### ISSUE TITLE
`{{page.url}}` does not include `.html`, while the actual page URL really does

### ISSUE THREAD

**Issue by kvz** [jekyll/jekyll#6354]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

In `_config.yml`:

```yaml
permalink: "/blog/:year/:month/:day/:title.html"
```

In my terminal, checking if my page has `.html` in its URL:

```bash
$ curl -I http://localhost:3000/implementations/
HTTP/1.1 404 Not Found

$ curl -I http://localhost:3000/implementations.html
HTTP/1.1 200 OK
```

In `implementations.md`:

```html
{{page.url}}
```

## The Output I Wanted

`/implementations.html`

## The Output I Got

`/implementations`

**Comment by DirtyF** [comment]
Didn't reproduce this behavior, make sure you don't have a `permalink` setting in your markdown page.

**Comment by kvz** [comment]
Full markdown frontmatter:

```
---
layout: default
title: Implementations
comments: true
---
```

full _config.yml:

```
permalink: "/blog/:year/:month/:day/:title.html"
tusd_endpoint: "http://master.tus.io"
commenting_baseurl: https://tus.io

kramdown:
  input: GFM
  hard_wrap: false
  enable_coderay: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6

excerpt_separator: "<!--more-->"

# We'll refer new atom feed though, as adviced by GitHub
# https://github.com/blog/2053-easier-feeds-for-github-pages
feed:
  path: blog.atom

rss_feed: /atom.xml

url: https://tus.io

gems:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

emoji:
  src: "/assets/img"

browsers:
  - "last 1 version"
  - "> 1%"
  - "Explorer 10"

exclude: [vendor]
```

**Comment by DirtyF** [comment]
Works fine with default Jekyll.
Given your config your should rather check for (adapated with default jekyll install):

```shell
❯ http -h http://127.0.0.1:4000/blog/2017/07/01/welcome-to-jekyll.html
HTTP/1.1 200 OK
…
❯ http -h http://127.0.0.1:4000/blog/2017/07/01/welcome-to-jekyll/
HTTP/1.1 200 OK
```

**Comment by kvz** [comment]
What about pages though, this is just a page at the root: `./implementations.md` (source of this site is available online btw: https://github.com/tus/tus.io/blob/master/implementations.md)

**Comment by DirtyF** [comment]
I did reproduce your use case, you're right it does not follow [what's is mentioned in the docs](https://jekyllrb.com/docs/permalinks/#pages-and-collections)

> A permalink style of `/:categories/:year/:month/:day/:title.html` for posts becomes `/:title.html` for pages and collections.)

More than that the generated URL is not the same with pages and collections;

| File                      | URL                                           | Permalink           |
|---------------------------|-----------------------------------------------|---------------------|
| /about.md                 | http://127.0.0.1:4000/about                   | /about              |
| /_products/_a-product.md  | http://127.0.0.1:4000/products/a-product.html | /products/a-product |

Thanks for bringing that up @kvz.

FWIW you can still override the page permalink to get the URL you want.
