### ISSUE TITLE
Remove /assets/javascript/anchor-js

### ISSUE THREAD

**Issue by laukstein** [jekyll/jekyll#6358]
Even when no JavaScript, no plugin or template is used on Jekyll project, `jekyll serve` creates **_site/assets/javascript/anchor-js** with bunch of irrelevant staff.

![grabilla g13256](https://user-images.githubusercontent.com/183966/30325522-bfeeb4a8-97cd-11e7-8146-ef7c24095a57.png)

few of the files
https://jekyllrb.com/assets/javascript/anchor-js/anchor.js
https://jekyllrb.com/assets/javascript/anchor-js/banner.js
https://services.github.com/assets/javascript/anchor-js/banner.js

How to avoid/remove this **anchor-js**? It seems all Jekyll projects are affected by this issue. I hope it doesn't contain harmful JavaScript files.

**Comment by DirtyF** [comment]
[anchorjs](https://github.com/bryanbraun/anchorjs) is an open source project used on many website to create anchor links. It's not embedded in Jekyll by default, nor in minima the default theme.

It is used on Jekyll's website and on many other sites powered by Jekyll, but it's up to you to add it or not.

**Comment by laukstein** [comment]
@DirtyF, you are wrong. Please re-open this task. This is Jekyll bug - every Jekyll installation has this package without any option to remove it. It is not in **gem**, even not **_config.yml** and every `jekyll serve` it injects it again and again under **_site/assets**. When Jekyll root has no **assets** directory, it is not expected to even generate **_site/assets/***. @DirtyF, do you understand what I mean? I suggest you to run clean `jekyll new` >  `jekyll serve` and you will see the bug.

**Comment by ashmaroli** [comment]
@laukstein This is not a Jekyll bug, like DirtyF said. Its not included by the Jekyll gem or its default theme Minima.

If it gets injected into **_site/assets** it's only because of **your theme**

**Comment by laukstein** [comment]
After testing empty Jekyll folder with only **_config.yml** and **Gemfile**, I find out that this issue is caused by Gemfile:

    gem "github-pages", group: :jekyll_plugins

No **_site/assets** when removed Gemfile or used in it `gem "github-pages"`.

But `gem "github-pages", group: :jekyll_plugins` is the recommended setup for GitHub Pages, see https://github.com/github/pages-gem#usage

@ashmaroli, is it GitHub bug?

**Comment by nickmccurdy** [comment]
Wow I didn't even know `:jekyll_plugins` behaved differently despite the recommendation. Either way can we please get some documentation for this bundler group?

**Comment by ashmaroli** [comment]
Yes, `:jekyll_plugins` is treated with extra love by Jekyll. Any gem included in that group is given a higher-priority and "loaded" way before your site has even started began being processed..

I do think we need to properly document this fact about `:jekyll_plugins:

**Comment by nickmccurdy** [comment]
It turns out I didn't read closely enough and the `jekyll_plugins` group is [explained in the docs](https://jekyllrb.com/docs/plugins/#the-jekyll_plugins-group), but is it enough or should we add to it?

**Comment by ashmaroli** [comment]
@nickmccurdy Actually, we added the section on `:jekyll_plugins` after you expressed your doubts. Feel free to submit a PR if you feel the section is inadequate

**Comment by nickmccurdy** [comment]
Looks fine to me, thanks 😄
