### ISSUE TITLE
Generating relative URL (and I mean *actually* relative)

### ISSUE THREAD

**Issue by aioobe** [jekyll/jekyll#6360]
I just discovered `relative_url` but it doesn't do what I expect it to.

In my `default.html` template, I have `<link rel="stylesheet" href="css/style.css" type="text/css">` This works fine as long as I create pages in the root, but not if I have a page (based on the `default.html` template) in a subdirectory.

I can obviously add a leading `/` i.e. change from `href="css/style.css"` to `href="/css/style.css"` and it will work locally and when I've uploaded to my server, but only if I'm serving the site from the root of my domain.

I thought `{{ "/css/style.css" | relative_url }}` would turn into `css/style.css` for pages in the root, and `../css/style.css` for pages in a subdirectory, but no, unless I mess around with the `baseurl` settings, it turns into `/css/style.css` for all pages. This is what I call an **absolute url**. It starts with a `/`!

I would like a way to turn `"/css/style.css"` into `"css/style.css"` for pages in the root, and `"../css/style.css"` in subdirectories. (And `relative_url` is a very misleading name, but maybe that's too late to do something about?)

**Comment by ashmaroli** [comment]
Hello @aioobe you seem to be confused with the two terminologies here.
`relative_url` does not mean relative to the current file or directory but rather *relative* to the site's location.
And `absolute_url` means a fully resolved path to a resource.

If your site is at `http://www.somewhere.com/my-site` then the absolute URL for a `styles.css` in the `css` subdir in an `assets` dir would be `http://www.somewhere.com/my-site/assets/css/styles.css` whereas the relative url for the same file is only `/assets/css/styles.css`

**Comment by ashmaroli** [comment]
Another point to note: the relative path is only resolved by an active server. Simply opening a generated `*.html` in the browser won't load the css. You need to run `jekyll serve` or `bundle exec jekyll serve` first..

**Comment by aioobe** [comment]
Ok, I see the train of thought that led up to the name `relative_url`. It's still confusing imo. The first few hits that come up when googling `relative url` shows examples such as `"sibling-page.html"` and `"../other-page.html"`. Not `"/some/other/page.html"`.

My question remains though: How do I produce links such as `"../css/style.css"`?

I would like to view the HTML on disk (`file://`) and upload the content of `_site` to a static web-server without bothering about how it's served or from which root directory. After all, that's one of the big benefits with working with static HTML-pages, no?

**Comment by ashmaroli** [comment]
> After all, that's one of the big benefits with working with static HTML-pages, no?

Yes. I agree.

**Comment by ashmaroli** [comment]
Besides the need to resolve `../css/style.css` can be easily overcome by proper use of layouts

**Comment by aioobe** [comment]
I don't understand your last two comments.

Why do I need to take `url`, `baseurl` and `JEKYLL_ENV` into consideration?

How can proper use of layouts solve the CSS example situation?

**Comment by ashmaroli** [comment]
> Why do I need to take `url`, `baseurl` and `JEKYLL_ENV` into consideration?

Both `relative_url` and `absolute_url` filters look for the `baseurl` setting while generating the url and the `absolute_url` filter additionally looks for the `url` setting while generating the url. Consider the following examples..

**Comment by ashmaroli** [comment]
```sh
# JEKYLL_ENV is set to `development` by default. At this setting, the `url` is automatically
set to `http://localhost:4000`

# baseurl: "" # or "/"
{{ 'css/styles.css' | relative_url }} # => "/css/styles.css"
{{ 'css/styles.css' | absolute_url }} # => "http://localhost:4000/css/styles.css"

# baseurl: "/blog"
{{ 'css/styles.css' | relative_url }} # => "/blog/css/styles.css"
{{ 'css/styles.css' | absolute_url }} # => "http://localhost:4000/blog/css/styles.css"
```
```sh
# now *build-ing* with non-default JEKYLL_ENV
# $ JEKYLL_ENV="production" bundle exec jekyll build
#
# baseurl: "" # or "/"
# url: "http://www.domain.com"

{{ 'css/styles.css' | relative_url }} # => "/css/styles.css"
{{ 'css/styles.css' | absolute_url }} # => "http://www.domain.com/css/styles.css"

# baseurl: "/blog"
# url: "http://www.domain.com"
{{ 'css/styles.css' | relative_url }} # => "/blog/css/styles.css"
{{ 'css/styles.css' | absolute_url }} # => "http://www.domain.com/blog/css/styles.css"
```

**Comment by aioobe** [comment]
I still don't get it. As stated in my original post, `relative_url` does not do what I want. I don't intend to use it, thus I don't see how your examples with `relative_url` and `absolute_url` is relevant.

What I'm after is something like `"/css/style.css" | some_filter` which renders this as `css/style.css` for pages in the root, and as `../css/style.css` for pages in immediate subdirectories.

There are ugly hacks such as [this](https://stackoverflow.com/q/7985081/276052). I don't find them very appealing.

**Comment by ashmaroli** [comment]
Unfortunately, you need to have a server running to have the assets served to your html page. `jekyll serve` runs it for you locally. in production, your domain's server will take care of it for you..

**Comment by ashmaroli** [comment]
Jekyll is designed to generate pages that work on a server. `file://` won't do..

**Comment by aioobe** [comment]
I'm fully aware of this. I would however like the content of `_site` to be oblivious of which directory it is served from. (Applies both if I serve it from nginx, apache, lighttpd or view it with my browser directly on disk.)

I don't see any inherent reason for why this should be problematic.

**Comment by aioobe** [comment]
Turned out to trivial to implement. Just drop the code below in your `_plugins` directory, and you'll be able to do precisely what I'm after: `{{ "/css/style.css" | relativize_url }}` will generate `css/style.css` for pages in the root, and `../css/style.css` for pages in immediate subdirectories.

```ruby
require 'pathname'

module Jekyll
  module UrlRelativizer
    def relativize_url(url)
      pageUrl = @context.registers[:page]["url"]
      pageDir = Pathname(pageUrl).parent
      Pathname(url).relative_path_from(pageDir).to_s
    end
  end
end

Liquid::Template.register_filter(Jekyll::UrlRelativizer)
```

**Comment by aioobe** [comment]
Pull request filed: https://github.com/jekyll/jekyll/pull/6362

**Comment by dk487** [comment]
> Unfortunately, you need to have a server running to have the assets served to your html page.

Bloody hell, no!

**Comment by ksykes** [comment]
Hey @aioobe - I'm trying to implement this on my site but am having trouble getting it working. I'm new to Jekyll so I'm hoping there's just an obvious step I missed. 

I dropped the code above in `_plugins/urlRelativizer.rb` and have a `_config.yml` at the root of my project that just has my name in it. Is there anything I'm missing that would be prohibiting this plugin from working?

**Comment by pathawks** [comment]
Sorry @ksykes, GitHub Pages runs in Safe Mode which disables all plugins that aren't on GitHub's whitelist, including any code in `_plugins/`

**Comment by Ketrel** [comment]
I came up with this option which doesn't rely on a plugin: https://gist.github.com/Ketrel/1f36fca6b4148f7263b3ee8fdb0923e7

I save that as "_includes/relBase.html" and then just do a `{% include relBase.html %}` at the top of wherever I need it.

From there the html would be like  
`<link rel="stylesheet" type="text/css" href="{{ relBase }}css/file.css">`

It works for my site when I've tested it, though I don't use github pages, so can anyone using that give it a try?

**Comment by lukepighetti** [comment]
calling `relative_url`, well, `relative_url` is ludicrous. It should be called `relative_to_the_servers_html_root_url` because thats the only thing that it can possibly be called in this context.
