### ISSUE TITLE
Could the bot do batch updates of "Update history"?

### ISSUE THREAD

**Issue by bep** [jekyll/jekyll#6363]
I pop in from time to time and look at the commit history, and see these 

```
Update history to reflect merge of #6342 [ci skip]
```

Interleaved between each commit.

Which makes the commit log unreadable to me. This is just a constructive suggestion, but it would be great if you could do some batching of these history updates. I guess they are used at release time, so why not wait until then?

**Comment by benbalter** [comment]
If it were up to me (and for projects I maintain) I just use GitHub Releases (which could be tooled), but recognize this practice predates my involvement with the project (and may have its benefits).

**Comment by bep** [comment]
I will close this. It was just a heads up.
