### ISSUE TITLE
jekyll 3.5.2 | Error:  no implicit conversion of nil into String

### ISSUE THREAD

**Issue by deanilvincent** [jekyll/jekyll#6365]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [x] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

**Comment by ashmaroli** [comment]
More context will help us resolve your situation. Please **edit** the post above and enter relevant details.
Plus run `bundle exec jekyll build --trace` and post the terminal output as well.

Thanks

**Comment by deanilvincent** [comment]
Hello @ashmaroli This is what I got

![screen shot 2017-09-15 at 12 11 38 am](https://user-images.githubusercontent.com/10904957/30441024-c5ca4b1a-99aa-11e7-8b1d-cd8ccc2b1109.png)

**Comment by ashmaroli** [comment]
okay.. run without `bundle exec`:
```
$ jekyll build --trace
```

**Comment by deanilvincent** [comment]
![screen shot 2017-09-15 at 12 18 27 am](https://user-images.githubusercontent.com/10904957/30441250-728b40b6-99ab-11e7-9810-f704fe9a362b.png)

@ashmaroli Oh here's what I get now. What does that mean?

**Comment by DirtyF** [comment]
@deanilvincent You problem is not related to Jekyll itself but to GitHub Pages (who does not support Ruby plugins, hence your error messages).

Please refer to https://help.github.com/categories/customizing-github-pages/ or contact GitHub Support.
