### ISSUE TITLE
Disgusting

### ISSUE THREAD

**Issue by sndn** [jekyll/jekyll#6369]
After trying Jekyll for more than a week I still don't know how to make it work. Includes dont work... CSS dont work... Layouts dont work... I dont know what works and what not works.

Why is Jekyll sooooooooooo Complicated?

Why not make it easier like PHP includes?

**Comment by DirtyF** [comment]
Sorry you're experiencing difficulties, if you have more details you can ask for help on https://talk.jekyllrb.com.

**Comment by meglance1978** [comment]
Ur

**Comment by meglance1978** [comment]
:broken_heart:
