### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by sndn** [jekyll/jekyll#6370]
Not working.

Layout or includes not working

https://sndn.github.io/jekyll/
https://github.com/sndn/sndn.github.io/tree/gh-pages/jekyll

**Comment by DirtyF** [comment]
This issue tracker is dedicated to Jekyll bugs, for any help with Jekyll's usage on GitHub, please contact GitHub Support or ask your question on https://talk.jekyllrb.com or https://stackoverflow.com/questions/tagged/jekyll
