### ISSUE TITLE
Add default gitignore at new step

### ISSUE THREAD

**Issue by lolgear** [jekyll/jekyll#6386]
It would be nice to add default gitignore after new site created.

Example [gitignore](https://github.com/benbalter/benbalter.github.com/blob/master/.gitignore).

**Comment by pathawks** [comment]
We have a `.gitignore` in the site template; is it not being generated correctly? If that is the case, this is a bug.

Could you provide more information about the version of Jekyll you’re using, etc.? (Basically the information from the issue template, so that somebody can try to debug this)

**Comment by lolgear** [comment]
sorry, missed it while copypasting, thanks, solved.
