### ISSUE TITLE
code of conduct enforcement contacts are not publicly visible

### ISSUE THREAD

**Issue by pup** [jekyll/jekyll#6428]
in the readme:

>  If you encounter someone violating these terms, please let a [team captain](https://github.com/orgs/jekyll/teams/affinity-team-captains/members) know and we will address it as soon as possible.

that link redirects to the github team page that lists the affinity team captains. however team pages, even when marked as visible, are not visible to anyone _outside_ of the github organization. true, it's fairly easy to join it due to our teams program, but it's still a hurdle i'd rather not see.

also, why does it state the affinity team captains? members of that team itself don't have any special github rights, so all they'd be able to do in terms of enforcement would be to pass it on to core team members. shouldn't there be a link or listing of the core team members instead?

**Comment by DirtyF** [comment]
@pup 👍 to link to https://github.com/orgs/jekyll/teams/core/members for now.

What's the good practice here, what should we do instead?

**Comment by pup** [comment]
@DirtyF the only thing i can think of right now is to list each member out separately? unless there's an alternative that isn't github's team listing

**Comment by DirtyF** [comment]
OK let's do this.

**Comment by DirtyF** [comment]
@pup https://github.com/jekyll/jekyll/blob/master/CODE_OF_CONDUCT.markdown  only mention a maintainer with no link.

**Comment by DirtyF** [comment]
Thinkin' a bit about his, you seem to be the right person to talk to @pup 
If someone help is willing to help on this, just raise your hand 🤚

**Comment by pathawks** [comment]
✋🏼

**Comment by mattr-** [comment]
✋

**Comment by parkr** [comment]
If y’all want, I can setup @jekyllrb.com email aliases that forward to your accounts.

:hand:

**Comment by pup** [comment]
@parkr that would be perfect!
