### ISSUE TITLE
parsing error while highlighting java code snippets

### ISSUE THREAD

**Issue by Mellivora123** [jekyll/jekyll#6430]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

## My Reproduction Steps
create a new post, then add the following code snippet as the post content:  

<pre>
```java
import java.lang.reflect.Field;
import java.util.List;

public class FieldSpy<T> {
    public boolean[][] b = {{ false, false }, { true, true } };
    public String name  = "Alice";
    public List<Integer> list;
    public T val;

    public static void main(String... args) {
        try {
            Class<?> c = Class.forName(args[0]);
            Field f = c.getField(args[1]);
            System.out.format("Type: %s%n", f.getType());
            System.out.format("GenericType: %s%n", f.getGenericType());

        // production code should handle these exceptions more gracefully
        } catch (ClassNotFoundException x) {
            x.printStackTrace();
        } catch (NoSuchFieldException x) {
            x.printStackTrace();
        }
    }
}
```
</pre>

The error message:
> jekyll 3.5.1 | Error:  Liquid syntax error (line 6): Variable '{{ false, false }' was not properly terminated with regexp: /\}\}/

## The Output I Wanted

The normal java syntax highlighting code snipped.

**Comment by pathawks** [comment]
You will need to surround the code with a `{% raw %}` tag to prevent it from being rendered as Liquid.

I believe this is documented. If not, please do open a PR.

**Comment by Mellivora123** [comment]
I am using the [fenced code blocks way](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) to highlight the code snippet. The problem is the parser(the *liquid* parser or the plugin or whatever) can not process `{{` in the code snippet correctly.

**Comment by pathawks** [comment]
Right. The Liquid parser thinks the code looks like Liquid.

The way you can tell Liquid that it should _not_ parse your code block is by wrapping it in `{% raw %} {% endraw %}` tags. This is a pain, but it is a Liquid issue and there seems to be no way for us to work around it.

Also, it appears that this isn't documented very well. That should change.

**Comment by pathawks** [comment]
#6439
