### ISSUE TITLE
Security: HSTS preload

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#6432]
https://hstspreload.org/?domain=jekyllrb.com

Some security headers are missing, as we are hosted on GitHub Pages I don't know if we can do something about it.

Global security grade: https://observatory.mozilla.org/analyze.html?host=jekyllrb.com

/cc @jekyll/core

**Comment by pathawks** [comment]
It looks like the SSL certificate is for GitHub.com and does not list Jekyllrb.com as a domain name that the certificate can be used with.

When I try to visit https://jekyllrb.com with Safari, I get a big scary error message about how my connection is not private.

**Comment by parkr** [comment]
> It looks like the SSL certificate is for GitHub.com and does not list Jekyllrb.com as a domain name that the certificate can be used with.

Does hstspreload.org support SNI?

> When I try to visit https://jekyllrb.com with Safari, I get a big scary error message about how my connection is not private.

Hm, works fine for me.

**Comment by pathawks** [comment]
![Safari screenshot](https://user-images.githubusercontent.com/251545/31688043-adcc170e-b350-11e7-8250-0dfebe3407d7.png)

**Comment by DirtyF** [comment]
@pathawks works fine for me too.

**Comment by DirtyF** [comment]
> Does hstspreload.org support SNI?

I have no idea, but @lgarron should be able to answer your question.

**Comment by DirtyF** [comment]
@parkr I realize that this issue should rather be submitted to GitHub Pages team. Feel free to close if you think it's inappropriate. While it's a good practice it's not an obligtation to use HSTS preload.

**Comment by pathawks** [comment]
It's working for me now. 🤷‍♂️

**Comment by lgarron** [comment]
> Does hstspreload.org support SNI?
> 
> I have no idea, but @lgarron should be able to answer your question.

Yes, hstspreload.org should be able to handle SNI-only sites without problem.

**Comment by parkr** [comment]
Looking into it. We'll get this sorted, thanks folks!

**Comment by mattr-** [comment]
Going to go ahead and close this since it'll be handled on the GitHub side.
