### ISSUE TITLE
Feature Request: Control of HTML Tags wrapping Code Blocks

### ISSUE THREAD

**Issue by jambonrose** [jekyll/jekyll#6446]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

I'm running jekyll 3.6.0 on macOS 10.11.

I'm brand new, but like how easy it was to get started. Thanks for maintaining Jekyll!

I would like to request more granular control of the tags output with highlighted code snippets.

Below I explain the current state (AFAICT) for syntax highlighting in Jekyll. I've tried to keep it as short as possible, but there are some fiddly details. Thank you for taking the time to read this issue.

## State of Highlighting Code in Jekyll

I appear to be able to highlight syntax in Markdown files in two different ways using Jekyll.

    ```shell
    $ pip install jupyter
    ```

The code above yields:

```html
<div class="language-shell highlighter-rouge">
  <div class="highlight">
    <pre class="highlight">
      <code>
        <span class="nv">$ </span>pip install jupyter
      </code>
    </pre>
  </div>
</div>
```

However, if I use Liquid syntax in my markdown file, the output changes.

```
{% highlight shell %}
$ pip install jupyter
{% endhighlight %}
```

The code above renders to the result below.

```html
<figure class="highlight">
  <pre>
    <code class="language-shell" data-lang="shell">
      <span class="nv">$ </span>pip install jupyter
    </code>
  </pre>
</figure>
```

Please note that this difference does not appear to be documented, and is quite surprising to a Jekyll beginner. I note that in some other issues Jekyll-users appear surprised to discover that highlighting with fenced blocks is an option, because the documentation refers only to the second method.

Note that some behavior changes if I edit my `_config.yml` and set `highlighter` to none

```yaml
markdown: kramdown
highlighter: none # new addition
```

The first code snippet (using Markdown delimiters) now yields the following (note missing `div` tags and syntax highlighting).

```html
<pre>
  <code class="language-shell">
    $ pip install jupyter
  </code>
</pre>
```

The second snippet now yields the code below (syntax highlighting removed, but `figure` tags remains).

```html
<figure class="highlight">
  <pre>
    <code class="language-shell" data-lang="shell">
      $ pip install jupyter
    </code>
  </pre>
</figure>
```

After a dive through the code, I gather that the output of fenced code blocks is entirely handled by kramdown, and that the extra `div` tags are generated there. The second example, however is split between Jekyll and Rouge. Jekyll appears to be introducing the `figure` tags, while Rouge does the rest.

## The Output I Want

I'm currently trying to build a site with small pages, and wish to eschew any unnecessary HTML code. Given my CSS, I do not need the `div` or `figure` tags in the examples above.

I'd like a way to generate code that is not wrapped in extra divs, but that does specify meta data and is syntax highlighted. The code below is an example for this instance.

```html
<pre>
  <code class="language-shell" data-lang="shell">
    <span class="nv">$ </span>pip install jupyter
  </code>
</pre>
```

## Potential Solutions

First and foremost, I think extra documentation about the different highlighting methods would be quite welcome. I note the existence of #6439, but think syntax highlighting could use its own page in the docs under "Your Content", as opposed to being the last item in [Writing posts](https://jekyllrb.com/docs/posts/). It is, for many, one of the central draws to Jekyll.

While I would love for Jekyll to make output between fenced blocks and the highlight tag consistent, I recognize that that is an unreasonable task, given that the output of fenced blocks is entirely outside the control of Jekyll.

I think Jekyll could benefit from an option that disables the output of the `figure` tag that wraps the code blocks. The feature would enable wrapping by default, allowing for backwards compatibility. Ideally, the highlight tag itself would also have a flag, so that the code can be controlled on a case-by case basis.

Thanks again for reading all of this.

**Comment by pathawks** [comment]
> While I would love for Jekyll to make output between fenced blocks and the highlight tag consistent, I recognize that that is an unreasonable task, given that the output of fenced blocks is entirely outside the control of Jekyll.

I could swear that at one point we hooked into **kramdown** to do just this.

> I think Jekyll could benefit from an option that disables the output of the figure tag that wraps the code blocks. The feature would enable wrapping by default, allowing for backwards compatibility. Ideally, the highlight tag itself would also have a flag, so that the code can be controlled on a case-by case basis.

I understand your motivation, but I don't think that such an option belongs in Jekyll core. We want our output to be as concise as possible while letting users style things the way they want. While outputting as little HTML as possible tickles the perfectionist in me, the extra complexity of a toggle switch seems to outweigh the practical benefit of removing the `<figure>` tag.

That being said, for some of my sites I override Jekyll's output for the `{% highlight %}` tag with [my own plugin](https://github.com/pathawks/pathawks.com/blob/master/_plugins/highlight.rb) that allows me 100% control over the output. Maybe something like that could work for you?

**Comment by jambonrose** [comment]
Hi @pathawks - thanks for the quick reply!

I understand the need to keep things focused and lightweight in a project. I think overriding the `{% highlight %}` tag is a great solution to my problem. I'm going to give that whirl on my end.

I'm leaving this issue open as I think the improved documentation focusing on syntax highlighting is still worthwhile, but consider the feature request closed. Feel free to close this as you deem appropriate.

Thanks!

**Comment by pathawks** [comment]
@jambonrose Thanks. I'm glad that works for you.

I agree that we should call out any differences between the two different methods of syntax highlighting. I'm going to open a new issue for that, to keep it focused :+1:
