### ISSUE TITLE
Release 3.6.2

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#6454]
I _think_ I now have the `3.6-stable` branch ready to release `3.6.2` with the new Rubocop stuff (#6444), as well as always treating document `layout` as a string (#6442) and the fix for files that contain a BOM (#6322).

I don't think there's anything else we need to include in a patch release.

Could somebody [take a look at the changelog](https://github.com/jekyll/jekyll/compare/v3.6.1...3.6-stable) and give me the 👌ok? I want to make sure to get it right this time.

**Comment by DirtyF** [comment]
It _looks_ OK to me.

**Comment by pathawks** [comment]
Cool. I’ll cut a :gem:gem tomorrow :+1:

**Comment by Crunch09** [comment]
Changelog looks good 👍

**Comment by pathawks** [comment]
3.6.2 is now available.
