### ISSUE TITLE
No matching jekyll-docs for version 3.6.1

### ISSUE THREAD

**Issue by erozic** [jekyll/jekyll#6456]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

I am a new user and was following the documentation (https://jekyllrb.com/docs/home/) to setup when I came to the part saying: "If you’re interested in browsing these docs on-the-go, install the `jekyll-docs` gem and run `jekyll docs` in your terminal."

This action resulted in the following output in my terminal:
`WARN: Unresolved specs during Gem::Specification.reset: rouge (< 3, >= 1.7)`
`WARN: Clearing out unresolved specs.`
`Please report a bug if this causes problems.`
`You must install the 'jekyll-docs' gem version = 3.6.1 to use the 'jekyll docs' command.`

I installed the `jekyll-docs` gem with `gem install jekyll-docs` and the installed version is `3.5.2`, which is the latest one according to `gem search jekyll-docs` and `gem outdated`.

So it seems that jekyll wants a `jekyll-docs` gem version that does not exist (yet?), and until then docs are not available locally...

**Comment by DirtyF** [comment]
Thanks for the reminder, we forgot indeed to publish a new gem for the docs.

**Comment by pathawks** [comment]
@parkr Could you add @DirtyF and myself to the [**jekyll-docs**](https://rubygems.org/gems/jekyll-docs) gem on RubyGems? We lack the permissions to release the docs :gem:.

**Comment by parkr** [comment]
@pathawks @DirtyF done via https://github.com/jekyll/maintainers/pull/13

**Comment by parkr** [comment]
To release, run

```
$ export JEKYLL_VERSION=3.6.1
$ bundle install
$ bundle exec rake release
```

**Comment by DirtyF** [comment]
@parkr we're 3.6.2 now should we release both versions?

**Comment by parkr** [comment]
> @parkr we're 3.6.2 now should we release both versions?

Yeah, always good to have a jekyll-docs for every version released as a rule of thumb. 👍

**Comment by DirtyF** [comment]
`jekyll-docs` 3.6.1 and 3.6.2 have just been published 🎉

**Comment by erozic** [comment]
Hi! A problem persists, don't know if I should open a new issue for it...?

Anyway, I install the new docs but now when I run `jekyll docs` is says:
`You must install the 'jekyll-docs' gem version = 3.6.2 to use the 'jekyll docs' command.`
And I have both _jekyll_ and _jekyll-docs_ versions 3.6.2 installed (I checked with `gem search jekyll --local`) and the jekyll I run is version 3.6.2 (check with `--version`).

**Comment by DirtyF** [comment]
@erozic my mistake opened an issue over at https://github.com/jekyll/jekyll-docs/issues/20, we'll try to fix that and republish new gems. 😕

**Comment by DirtyF** [comment]
@erozic Can you confirm uninstalling previous gem and installing latest work?

```sh
gem uninstall jekyll-docs

gem install jekyll-docs
Fetching: jekyll-docs-3.6.2.0.gem (100%)
Successfully installed jekyll-docs-3.6.2.0
1 gem installed

jekyll docs
Configuration file: none
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
```

**Comment by erozic** [comment]
@DirtyF I'm sorry but I'm afraid not :/ I still get:

`You must install the 'jekyll-docs' gem version = 3.6.2 to use the 'jekyll docs' command. `

**Comment by DirtyF** [comment]
@erozic we'll get there 😓 

```sh
$ jekyll -v 
$ jekyll _3.6.2_ docs
```

Do you have a `Gemfile`?
What if you run `jekyll docs` in a directory without a `Gemfile`?

**Comment by erozic** [comment]
`simpsonim@maschinko:~$ jekyll -v
jekyll 3.6.2
simpsonim@maschinko:~$ jekyll _3.6.2_ docs
You must install the 'jekyll-docs' gem version = 3.6.2 to use the 'jekyll docs' command. 
simpsonim@maschinko:~$ jekyll docs
You must install the 'jekyll-docs' gem version = 3.6.2 to use the 'jekyll docs' command. `

Yes I do. But I installed everything globally (with `sudo`) so everything should work the same wherever, right? Anyway, I get the same result in a directory with or without a Gemfile. Also the same result using bundle, so `bundle exec jekyll docs` in the folder with the Gemfile.
