### ISSUE TITLE
Improved issue template for first-timers? [Discussion]

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#6458]
I think it'd be great to have a line in the `Issue for First-timers` that informs them to have the following in their Pull request's body..
```
Fixes #ISSUE_NUMBER
```
Our own bot will then replace the `help-wanted` label with a `has-pull-request` label automatically

Currently the first-timer-bot doesn't support doing this automatically, so i think the maintainer or whoever creates the issue will have to edit the issue-ticket-number in manually.. 

Whatsay? Worth adding to the current template?

/cc @pup @pathawks @DirtyF

**Comment by pathawks** [comment]
Let’s wait until first-timers bot adds this functionality. I want the process to be as automated as possible.

hoodiehq/first-timers-bot#153
