### ISSUE TITLE
History escaping characters improperly

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#6461]
From https://jekyllrb.com/docs/history/#documentation:

> Remove duplicate &amp;&#35;34;available&amp;&#35;34; (#6380)

It looks like this is being escaped twice somewhere. That should be fixed.

**Comment by ashmaroli** [comment]
I think Jekyllbot writes those characters as escaped..

![jbot](https://user-images.githubusercontent.com/12479464/31857949-1e3faf44-b709-11e7-94b2-46b10651048a.png)
