### ISSUE TITLE
Weird method name

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#6473]
Just came across a weird method name in our `Rakefile` and was wondering if it was intentional..
https://github.com/jekyll/jekyll/blob/c0e4ce13b5e8439eb7037e8bc16fd2fe907afcd6/Rakefile#L79-L81

The [commit](https://github.com/jekyll/jekyll/commit/e511550c91e24f79ba56bff2bad44aea342c08be) that introduced it deals with `slugs` so I guess its a corruption of `slugify`.. 

/cc @parkr At minimum, I'd like to know why you opted for that name.. and while we're on the same page, can it be changed to a more logical `slugify`, after all these years..? (`Rakefile` is only used internally, I assume..)

**Comment by DirtyF** [comment]
@ashmaroli Maybe it was just for fun, or to avoid confusion with the Jekyll's method?

Let's focus our efforts on more users related issues, and avoid nit picking. 
Opened a PR if this really bugs you.

**Comment by ashmaroli** [comment]
> Opened a PR

Thanks for that :grin: 

> Let's focus our efforts on more users related issues

Roger that.. :+1:
