### ISSUE TITLE
If `bar.html` exists, then `jekyll s` will show `bar.html` for `bar/.*` unless something else explicitly (but not implicitly) overrides it

### ISSUE THREAD

**Issue by janpio** [jekyll/jekyll#6475]
If a file and a folder have the same "permalink" name, `jekyll s` shows wrong content at files in the folder.

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

Windows Linux Subsystem, `bash` via Windows 10 Powershell

- [x] It was another bug.

## My Reproduction Steps

`jekyll s` does strange things when a file has the same name as a folder:

- Site is configured as `permalink: /:path`
- `bar.md`, should render at `/bar`
- `bar/baz.md`, should render at `/bar/baz`

Unfortunately:

On accessing `/bar/baz`:
- In 3.5.2 everything was okay.
- Since 3.6.0 it shows the content of `bar.md`

I think this is a serious bug. It probably is a regression of #6231, which tried to fix some related problems.

In `_site` everything is generated as it should:
- `/bar.html` with content from `bar.md`
- `/bar/baz.html` with content from `bar/baz.md`

So the problem is in the way `jekyll s` decides which file to serve.

### Example repo

Here is a repo that shows this exact scenario:
https://github.com/janpio/jekyll-path-test
Use the site navigation for the three example pages. 

If you use `jekyll s`, note how you see the wrong content for "Baz" (only 3.6.x).

(The project also includes 3 collections that test further iterations of this problem:, _test1 and _test2 with `.html` ending are fine, but _test3 has the exact same problem.)

## The Output I Wanted

You can see how everything should work at Github Pages:
https://janpio.github.io/jekyll-path-test/

**Comment by janpio** [comment]
Did I do everything correct with this issue or is anything missing to this getting looked at or confirmed?

**Comment by ashmaroli** [comment]
@janpio I can no longer see what you described above, in the test repo above..

**Comment by janpio** [comment]
Thanks, I will confirm the repro asap and get back to you.

**Comment by pathawks** [comment]
I can confirm that `/bar/baz.html` and `/bar/baz` do not show the same content: `/bar/baz` shows `/bar.html`

In fact, `/bar/literally/anything` shows `/bar.html`

This is bad.

**Comment by pathawks** [comment]
If `bar.html` exists, then `jekyll s` will show `bar.html` for `bar/.*`

**Comment by pathawks** [comment]
This behavior exists in `master` as well as `3.0.0`, so it is not something that has recently broken.

**Comment by Crunch09** [comment]
Looking into this now.

**Comment by janpio** [comment]
Awesome!

https://github.com/jekyll/jekyll/issues/6459 is probably related and (at least) partially fixed by your PR already.
