### ISSUE TITLE
How to remove p tags from Jekyll Posts

### ISSUE THREAD

**Issue by digitalmatter** [jekyll/jekyll#6477]
I got this but where to add this?
`{{ post.excerpt | remove: '<p>' | remove: '</p>' }}`

Any other solutions?

Thank you.

**Comment by DirtyF** [comment]
👋  @digitalmatter 

Sorry but this repository issues are dedicated to documented bugs only. 
Good news is you can head over to [our forum ](https://talk.jekyllrb.com) to ask that type of questions.
Please search before asking, I'm pretty sure this has been answered many times.

Happy Jekyllin'!
