### ISSUE TITLE
Custom pages getting cleaned up. How do you build custom design website with jekyll?

### ISSUE THREAD

**Issue by skhromchenko** [jekyll/jekyll#6479]
Hi, i pulled your repo and decided to redo design to fit my needs. I added a folder named "pages"(where i kept my custom pages) inside of _site folder. All looked good until i added a new pages-post.md file to _posts folder. Then, all of my custom created pages got deleted with all of the work that i did. 
Question: How do you create custom design website with jekyll if it's deleting all custom stuff?
If it is a clean up class, can i just get rid of it?

Best regards,
Sergii K

**Comment by DirtyF** [comment]
👋 

Sorry but this repository issues are dedicated to documented bugs only. 
Good news is you can head over to [our forum ](https://talk.jekyllrb.com) to ask that kind of question.

Happy Jekyllin'!
