### ISSUE TITLE
Liquid syntax error: Expected end_of_string but found id in

### ISSUE THREAD

**Issue by mayankpant11** [jekyll/jekyll#6481]
Hi
Getting an error
`Liquid syntax error: Expected end_of_string but found id in "{{Data.RatePlanCharge[0].ChargedThroughDate Date| date: "%s" | plus : 86400 | date: "%Y-%m-%d" |to_json}}"`

Please help

**Comment by mayankpant11** [comment]
I think I got it. Date below after ChargedThroughDate was not required

{{Data.RatePlanCharge[0].ChargedThroughDate **_Date_**| date: "%s" | plus : 86400 | date: "%Y-%m-%d" |to_json}}"

**Comment by DirtyF** [comment]
closing then 😄
