### ISSUE TITLE
Post with future date in 'date:' field fails to generate without error

### ISSUE THREAD

**Issue by annard** [jekyll/jekyll#6484]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

Create a new post in _post directory, with the current date. In this post set the 'date' field in the preamble to a day in the future. Now run 'jekyll s'.
This does not generate the page, but it also doesn't generate an error. the 'doctor' command says all is fine.

Once I change the date to the same date as the one in the filename, the article is generated in the _site folder.

## The Output I Wanted

It would be good if an error is shown that says the dates are inconsistent.

**Comment by pathawks** [comment]
This is not an error. By default, future posts are not generated. This allows sites to schedule posts to be published at a future date.

If you would like these posts to be published anyway, you can add the option `future: true` to your `_config.yml`.

https://jekyllrb.com/docs/configuration/
