### ISSUE TITLE
Bundler versions

### ISSUE THREAD

**Issue by chrisfinazzo** [jekyll/jekyll#6492]
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***macOS*** 10+
---
- [x] I was trying to install.
- [x] I was trying to build.
---

As mentioned in #6491, I am rebuilding my environment and while following the steps, found my environment would not pass tests. I ran `bootstrap` to get dependencies and everything seemed to complete without issue. But when I build the docs or run CI, Nokogiri chokes.

    Installing nokogiri 1.8.1 with native extensions
    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

I assume a more recent version of Bundler is compatible w/ 1.8.1?

**Comment by ashmaroli** [comment]
What made you think that Bundler is at fault here?
Its possible that there's some incompatibility between the Nokogiri version and your Ruby DevKit.. no?

**Comment by DirtyF** [comment]
@chrisfinazzo Did you install xcode?  `xcode-select --install`

**Comment by chrisfinazzo** [comment]
@ashmaroli With `script/cibuild`, there's a warning being suppressed about it using an older version - wasn't sure if the requirements had changed under 10.12 as far as what's compatible. In any event, Bundler is the special case as one of the only gems where you can just `gem install`

@DirtyF I did - although this is outdated and should be updated, per Homebrew's notice when I `brew doctor`. On the whole, I tend to be conservative with upgrades, waiting until the tools have absorbed the impact of a new release into their processes. Sometimes, this is the result.

Will investigate further with regard to Nokogiri.

**Comment by ashmaroli** [comment]
@chrisfinazzo Did you get the time to investigate further?

**Comment by ashmaroli** [comment]
closing as this doesn't look like a Jekyll-related bug, to me..
