### ISSUE TITLE
Please I am on my iPhone it hard to type 1 hour please 

### ISSUE THREAD

**Issue by Jchasser** [jekyll/jekyll#6493]
>
I don't have any of the other apple item only a iPhone and dell laptop my other things were stolen by identity theft!

**Comment by ashmaroli** [comment]
Jekyll works fine with a Dell Laptop with any OS installed. All you need is a Ruby Installation in it as well.
Checkout official documentation at https://jekyllrb.com for more details

**Comment by Jchasser** [comment]
I'm am not back at my dorm yet, I am sorry I will come through.  In the meantime I want to thank everyone who put in any amount of work, I think your amazing and I am truly grateful!
