### ISSUE TITLE
Jekyll should be using Gem bins, not system.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll#6498]
The system can wrap in on itself.  Jekyll should be using Ruby to find Ruby stuff.

**Comment by ashmaroli** [comment]
Please elaborate..

**Comment by DirtyF** [comment]
What problem are we trying to resolve here?

**Comment by ashmaroli** [comment]
I think Jordon's referring to the utility function in
https://github.com/jekyll/jekyll/blob/f535218a056a4e04769dc84d4682b20316ae466f/lib/jekyll/commands/new.rb#L143-L152

**Comment by envygeeks** [comment]
I've already shipped a pull-request through my bot.
