### ISSUE TITLE
Exploratory: Autocomplete Jekyll Data in VS Code

### ISSUE THREAD

**Issue by cameronmcefee** [jekyll/jekyll#6504]
I just started using VS Code and it's Intellisense stuff looks cool, especially if Jekyll was supported. I'm thinking specifically of the ability to autocomplete the Jekyll data structure, since it's pretty opaque, requiring printing stuff in templates to see what's available. Imagine typing `site.collections.` and then seeing an autocomplete list of all the collections.

Let's say you were foolish enough to try to make this. How would you do it? Is it possible to query the current state of a running Jekyll server, or run it in some sort of "only give me the data" mode that doesn't take into account the performance burden of rendering?

Feel free to insta-close this. I’m just looking for next steps for my research (or to nerd-snipe someone who is interested in building it before I do).

**Comment by envygeeks** [comment]
It's quite easy to extract the data structure of Jekyll without the data, the problem is that even when you do that Jekyll is too slow to even do that at a pace that an editor would expect (and especially a programmer using said data.) I assume you could do some caching and make it faster, though.

**Comment by cameronmcefee** [comment]
> I assume you could do some caching and make it faster, though.

I would think this is how it'd be done. Realistically the data in Jekyll doesn't update without being acted upon, so one can reasonably assume that, whilst the programmer is in the editor, the Jekyll state remains the same (accounting for file save actions as necessary, etc).

> It's quite easy to extract the data structure of Jekyll without the data

Are there any examples of this in the wild that you know of that I could reverse engineer?

**Comment by envygeeks** [comment]
There are none that I can share as the examples I have are for a company I used to work for, that was in Go though, we would extract the structure of Jekyll and it's site and then put it into the database as metadata.  I'd be willing to build a plugin that can extract that data if you are willing to build the plugin that works with Atom and VSCode (I'm not a big fan of VSCode because atom-ide is way better, and lets face it, the UX on Atom is way better.)

**Comment by cameronmcefee** [comment]
While I'd love to capitalize on your interest, this project is on the farthest edges of my dev abilities so I'm not yet confident I'd be able to pull it off in any sort of near-term fashion that would make you feel like your effort was worth it. I'll keep exploring it and will pop back in here if I get more confident that I could deliver on it.
