### ISSUE TITLE
The 'plugins' configuration option has been renamed to 'plugins_dir'.

### ISSUE THREAD

**Issue by alvarotrigo** [jekyll/jekyll#6505]
As far as I know [the docs ](https://jekyllrb.com/docs/plugins/) says we have to use `plugins` in the config file. Not `plugins_dir`. Why am I getting the error ?

- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+
---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

1 - I updated doing `bundle update`
2- Then, because I was getting the same error as in https://github.com/fastlane/fastlane/issues/6203, I did `gem update --system`
3- Now `jekyll -v` shows the following:

> WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
      rb-inotify (>= 0.9.7, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
jekyll 3.4.0

And `jekyll doctor`:

> WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
      rb-inotify (>= 0.9.7, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Library/WebServer/Documents/blog/_config.yml
       Deprecation: The 'plugins' configuration option has been renamed to 'plugins_dir'. Please update your config file accordingly.
        Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.
  Your test results are in. Everything looks fine.

4 - `gem -v` was showing:
> YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).
2.6.14

So I did `sudo gem update psych`.  Now I get `2.6.14`

**Comment by DirtyF** [comment]
Documentation refers to the latest version (we should mention that somewhere). 
`plugins` key was introduced in Jekyll v3.5.0.

If you still use a previous version of Jekyl, you can stick with `gems` or upgrade to latest Jekyll with `bundle update jekyll`.

Sorry for the inconvenience.

**Comment by alvarotrigo** [comment]
> If you still use a previous version of Jekyl, you can stick with gems or upgrade to latest Jekyll with bundle update jekyll.

I already did `bundle update jekyll` but still getting `jekyll 3.4.0` when using `jekyll -v`.

is it because I have `gem "jekyll", "3.5.0"` in Gemfile?

**Comment by DirtyF** [comment]
You can just use `gem "jekyll"`instead.

**Comment by alvarotrigo** [comment]
I changed the `Gemfile` with `gem "jekyll", "~> 3.5"`.
Tried to do `bundle update jekyll` and I got the message:

> This Bundle hasn't been installed yet. Run `bundle install` to update and install the
bundled gems.

So then I tried `bundle install`. 

Now `jekyll -v` seems to be messed up:

> WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
      rb-inotify (>= 0.9.7, ~> 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/resolver.rb:379:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll (~> 3.5)' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/resolver.rb:349:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/resolver.rb:349:in `verify_gemfile_dependencies_are_found!'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/resolver.rb:203:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/resolver.rb:182:in `resolve'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/definition.rb:252:in `resolve'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/definition.rb:176:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/definition.rb:235:in `specs_for'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/definition.rb:224:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:19:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.14.4/lib/bundler.rb:100:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.4.0/exe/jekyll:9:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

**Comment by Crunch09** [comment]
Hi @alvarotrigo ,
as `bundler` print in it's info message you should never run `bundle install` as root. Your problem with installing a new jekyll version is probably related to that.

**Comment by DirtyF** [comment]
For anyone reading this, a friendly reminder: 

1. Always use `bundler` to launch jekyll commands as shown below. Alias it or put it in a script if you don't want to avoid typing the whole command everytime. Or use a fuzzy finder for the command line like [fzf](https://github.com/junegunn/fzf)  
2. Avoid using `sudo` unless you really have to (on some GNU/Linux systems)
3. Don't lock your Jekyll version in the `Gemfile` for no reason, use the _spermy_ operator instead "~> 3.5"
4. Check [Jekyll's documentation](https://jekyllrb.com/docs/installation/) if you have trouble at install, and help us improve it if you find it incomplete or unclear.
5. Ask for help on [https://talk.jekyllrb.com](https://talk.jekyllrb.com) if none of the above get you out of trouble

```
bundle install
bundle exec jekyll -v
bundle exec jekyll doctor
bundle exec jekyll build
bundle exec jekyll clean
bundle exec jekyll serve
...
bundle update
```

**Comment by alvarotrigo** [comment]
I managed to update after playing the game "follow the rabbit" by googling every single error I was getting on the way. 

Now I have:
`gem -v` 2.6.14
`ruby -v` ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin15]
`jekyll -v` jekyll 3.6.2
`bundle -v`Bundler version 1.16.0.pre.3

When calling `sudo bundle exec jekyll serve` (I need to use `sudo`because for some reason the folder permission requieres it) , I get the following:

> /Users/myusername/.rvm/rubies/ruby-2.3.5/lib/ruby/site_ruby/2.3.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
	from /Users/myusername/.rvm/rubies/ruby-2.3.5/lib/ruby/site_ruby/2.3.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/myusername/.rvm/gems/ruby-2.3.5/bin/bundle:23:in `<main>'
	from /Users/myusername/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/myusername/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `<MacBooMacBook-MacBook-MacBook-Pro-MacBook-PrMacBook-MacBooMacBMaMacBMaMaMaMaMaMaMaMaMacBMaMaMaMacBMa

What am I missing now? 

`bundle exec jekyll doctor` shows:

> 
Configuration file: /Library/WebServer/Documents/blog/_config.yml
    Config Warning: The `paginate` key must be a positive integer or nil. It's currently set to '"nil"'.
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
    Config Warning: The `paginate` key must be a positive integer or nil. It's currently set to 'nil'.
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Is enabled, but I couldn't find any pagination page. Skipping pagination. Pages must have 'pagination: enabled: true' in their front-matter for pagination to work.
        Pagination: Complete, processed pagination page(s)
           Warning: You didn't set an URL in the config file, you may encounter problems with some plugins.
           Warning: Your site URL does not seem to be absolute, check the value of `url` in your config file.

**Comment by alvarotrigo** [comment]
Also, when accessing the folder in which I have my blog `cd my_path` I get the following message:

> VM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /Library/WebServer/Documents/blog/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.
Unknown ruby interpreter version (do not know how to handle): RUBY_VERSION.

Everything seemed to be working smooth with Jekyll, but trying to update it in an attempt to use the pagination plugin is bringing me into the dark side of it... 
I've no idea what I'm doing and what's going on here.

**Comment by pathawks** [comment]
This issue tracker is for bugs relating to Jekyll. This is unfortunately not the place to diagnose problems with Ruby or Bundler.

**Comment by alvarotrigo** [comment]
> as bundler print in it's info message you should never run bundle install as root. Your problem with installing a new jekyll version is probably related to that.

@Crunch09 and now that I used it, how do I undo my action and do it the proper way ?

**Comment by alvarotrigo** [comment]
@pathawks I understand it. I guess my problem is I am not quite sure where's the problem, as I happened when trying to run Jekyll. I guess I should ask then in the Ruby project ?
