### ISSUE TITLE
Jekyll bad uri bad request line

### ISSUE THREAD

**Issue by bgold0** [jekyll/jekyll#6507]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
" Your test results are in. Everything looks fine."
---
- [x] I am on (or have tested on) ***macOS*** 10+
---

- [X] I was trying to build.
- [X] It was another bug.

## My Reproduction Steps

For some reason I started getting this error and I'm not sure why. I haven't been doing anything differently, it just started doing this. Does anyone know why this would be happening?

	Bryans-MacBook-Pro:website bryan$ bundle exec jekyll serve
	Configuration file: /Users/bryan/Dropbox/Websites/Clients/website/_config.yml
	Configuration file: /Users/bryan/Dropbox/Websites/Clients/website/_config.yml
	            Source: /Users/bryan/Dropbox/Websites/Clients/website
	       Destination: /Users/bryan/Dropbox/Websites/Clients/website/_site
	 Incremental build: disabled. Enable with --incremental
	      Generating... 
	                    done in 0.114 seconds.
	 Auto-regeneration: enabled for '/Users/bryan/Dropbox/Websites/Clients/website'
	Configuration file: /Users/bryan/Dropbox/Websites/Clients/website/_config.yml
	    Server address: http://127.0.0.1:4000/
	  Server running... press ctrl-c to stop.
	[2017-10-31 11:06:45] ERROR bad URI `d??\x1EG?7?\x16??\x06???\x16????\\,?\x01\b?oq?K\x00\x00(?,?+?$?#?'.
	[2017-10-31 11:06:50] ERROR bad Request-Line `\x16\x03\x01\x00?\x01\x00\x00?\x03\x03\x14?????.?z?m??\x02®?,??("p?M%?'\x17?N\x00\x00.?,?+?$?#?'.
	[2017-10-31 11:06:50] ERROR bad Request-Line `\x16\x03\x01\x00?\x01\x00\x00?\x03\x01????ۙ\x10o?/?\\????k?<r\x18ofGL>`\x02?Ć\v\x00\x00\x12\x00/\x003\x005\x009?\t?'.

## The Output I Wanted

I was hoping I'd be able to view the website and work on my Jekyll.

**Comment by bgold0** [comment]
@pathawks I was hoping someone has had this issue before or knows where the issue is coming from. It happens on everyone of my Jekyll websites.

**Comment by ashmaroli** [comment]
@bgold0 Are you using any plugins? I suggested that you post the contents of your `Gemfile.lock` here to give us a better idea of your environment..

**Comment by bgold0** [comment]
@ashmaroli I don't believe I am using any plugins

    GEM
      remote: https://rubygems.org/
      specs:
        addressable (2.5.2)
          public_suffix (>= 2.0.2, < 4.0)
        colorator (1.1.0)
        ffi (1.9.18)
        forwardable-extended (2.6.0)
        jekyll (3.4.3)
          addressable (~> 2.4)
          colorator (~> 1.0)
          jekyll-sass-converter (~> 1.0)
          jekyll-watch (~> 1.1)
          kramdown (~> 1.3)
          liquid (~> 3.0)
          mercenary (~> 0.3.3)
          pathutil (~> 0.9)
          rouge (~> 1.7)
          safe_yaml (~> 1.0)
        jekyll-sass-converter (1.5.0)
          sass (~> 3.4)
        jekyll-watch (1.5.0)
          listen (~> 3.0, < 3.1)
        kramdown (1.15.0)
        liquid (3.0.6)
        listen (3.0.8)
          rb-fsevent (~> 0.9, >= 0.9.4)
          rb-inotify (~> 0.9, >= 0.9.7)
        mercenary (0.3.6)
        minima (2.1.1)
          jekyll (~> 3.3)
        pathutil (0.16.0)
          forwardable-extended (~> 2.6)
        public_suffix (3.0.0)
        rb-fsevent (0.10.2)
        rb-inotify (0.9.10)
          ffi (>= 0.5.0, < 2)
        rouge (1.11.1)
        safe_yaml (1.0.4)
        sass (3.5.3)
          sass-listen (~> 4.0.0)
        sass-listen (4.0.0)
          rb-fsevent (~> 0.9, >= 0.9.4)
          rb-inotify (~> 0.9, >= 0.9.7)

    PLATFORMS
      ruby

    DEPENDENCIES
      jekyll (= 3.4.3)
      minima (~> 2.0)
      tzinfo-data

    RUBY VERSION
       ruby 2.4.0p0

    BUNDLED WITH
       1.14.6

**Comment by crispgm** [comment]
```
/Users/bryan/Dropbox/Websites/Clients/website/_config.yml
```
Does Dropbox contain such files?

**Comment by ashmaroli** [comment]
> I don't believe I am using any plugins

I believe you. :smiley: 
You're using Jekyll `v3.4.3`, so technically, not on the latest version (`3.6.2`).. not that you need to update right away..

Coming back to this issue, what is your `url:` setting in your `_config.yml`?

**Comment by bgold0** [comment]
@ashmaroli that's very weird because I ran `bundle update`.

Here is my config file:

    # Welcome to Jekyll!
    #
    # This config file is meant for settings that affect your whole blog, values
    # which you are expected to set up once and rarely edit after that. If you find
    # yourself editing this file very often, consider using Jekyll's data files
    # feature for the data you need to update frequently.
    #
    # For technical reasons, this file is *NOT* reloaded automatically when you use
    # 'bundle exec jekyll serve'. If you change this file, please restart the server process.

    # Site settings
    # These are used to personalize your new site. If you look in the HTML files,
    # you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
    # You can create any custom variable you would like, and they will be accessible
    # in the templates via {{ site.myvariable }}.
    title: Website
    tagline: Interesting Tagline
    email: your-email@domain.com
    description: > # this means to ignore newlines until "baseurl:"
      Write an awesome description for your new site here. You can edit this
      line in _config.yml. It will appear in your document head meta (for
      Google search results) and in your feed.xml site description.
    baseurl: "" # the subpath of your site, e.g. /blog
    url: "" # the base hostname & protocol for your site, e.g. http://example.com

    #gems: ["jekyll-paginate", "algoliasearch-jekyll"]
    #paginate: 6
    #paginate_path:  /stories/page:num/
    #future: true

    #permalink: /stories/:categories/:year/:month/:day/:title

    exclude:
      - Gemfile
      - Gemfile.lock

    # Sass
    sass:
      sass_dir:         _sass
      style:            :compressed

**Comment by ashmaroli** [comment]
> that's very weird because I ran `bundle update`.

Its because your Gemfile has `"jekyll", "3.4.3"` changing it to `"jekyll", "~> 3.4"` will help you update..

A google search on related issues point towards a use of `SSL` or `force_ssl`.. Does those ring a bell to you? Perhaps changed something on your system..?

**Comment by ashmaroli** [comment]
@bgold0 what's the status on this?

**Comment by bgold0** [comment]
@ashmaroli http**s** was indeed the reason why it was messing up. Thank you! And thank you for information about the gemfile, I'll change that so I'm updated :)

Thanks everyone for their help.

**Comment by victoriastuart** [comment]
@ashmaroli , @bgold0 : I was getting the

```
  ...
  [2019-05-30 09:41:07] ERROR bad Request-Line `\x16\x03\x01\x02\x00\x01\x00\x01�\x03\x03YS�l\rv���w\b�^��H�A���U�\x17����q;�8 �\x06�$1�2�A��@�*�E\fM�b�>USݒ"�ΐ�\x00$\x13\x01\x13\x03\x13\x02�+�/̨̩�,�0�'.
  ...
  [2019-05-30 09:41:48] ERROR bad Request-Line `\x16\x03\x01\x02\x00\x01\x00\x01�\x03\x03\x7F0&Bƶ|��L���\e�/a�\x1A�\x03'��I��\t\x17Q\x1F �\t/q7�iaO�Y7\x11,\x17��'��}��;8�\a���'.
  [2019-05-30 09:41:51] ERROR bad URI `Z\x1Dq�ͩ.�ߊ�\x11���\a���\bK\x1E�{�;��\x0E�˲\x00$\x13\x01\x13\x03\x13\x02�+�/̨̩�,�0�'.
  ...
```

output from Jekyll.  In my case, it was caused by the recent addition of the "HTTP to HTTPS" addon (Firefox); when I disabled that addon, those Jekyll errors stopped.  So, it was indeed the http/http<b>S</b> issue ... :-)
