### ISSUE TITLE
Jekyll serve error: can't find gem jekyll (>= 0.a) (Gem::GemNotFoundException

### ISSUE THREAD

**Issue by alvarotrigo** [jekyll/jekyll#6510]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

When doing `sudo jekyll serve` I get the following error:

```
    Users/myusername/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems.rb:271:in 'find_spec_for_exe': can't find gem jekyll (>= 0.a) (Gem::GemNotFoundException)
    from /Users/myusername/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems.rb:299:in 'activate_bin_path'
    from /Users/myusername/.rvm/gems/ruby-2.4.2/bin/jekyll:23:in '<main>'
    from /Users/myusername/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in 'eval'
    from /Users/myusername/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in '<main>'
```

In case it helps:

- `jekyll -v` returns `jekyll 3.6.2`
- `ruby -v` returns `ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin15]`
- `gem -v` returns `2.6.14`
- `bundle -v` returns `Bundler version 1.16.0`

On my Gem file I have:

> ruby '2.4.2'

`rmv list` output:

    ruby-2.3.5 [ x86_64 ]
    =* ruby-2.4.2 [ x86_64 ]
    
    # => - current
    # =* - current && default
    #  * - default

I did `rvm install 2.4.2`. I then did `rvm --default use 2.4.2` but doing `ruby -v` still showing the same as before `ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin15]`. I also did `gem install jekyll` but still having exactly the same issue when running `sudo jekyll serve`.

`jekyll doctor` shows:

>Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
Warning: You didn't set an URL in the config file, you may encounter problems with some plugins.
Warning: Your site URL does not seem to be absolute, check the value of `url` in your config file.

**Comment by pathawks** [comment]
Don’t use `sudo`

**Comment by alvarotrigo** [comment]
To serve jekyll? `sudo jekyll serve`?
What if I need to due to the folder permissions?

**Comment by alvarotrigo** [comment]
> Don’t use sudo

I get this otherwise:
> jekyll 3.6.2 | Error:  Permission denied @ rb_sysopen - /Library/WebServer/Documents/blog/_site/test/just-whatever/index.html

**Comment by pathawks** [comment]
```
sudo rm -rf _site
bundle update
bundle exec jekyll serve
```

**Comment by alvarotrigo** [comment]
@pathawks you are my hero! Got it working again after 3 days getting mad after trying to use the paginator plugin!

**Comment by alvarotrigo** [comment]
Should I always use `bundle exec jekyll serve` instead of `sudo jekyll serve` then?

**Comment by pathawks** [comment]
As a general rule, yes.

`bundle exec` makes sure that Bundler is handling all dependencies properly.

Jekyll does not need Root permissions and should never be run with `sudo`.

I’m glad you’ve got it working now. I’m sorry that this is all so much more complicated than it should be.

**Comment by alvarotrigo** [comment]
Thanks for the info! ;)

> I’m sorry that this is all so much more complicated than it should be.

Not your fault! But I'm sure it can only keep improving with time!
