### ISSUE TITLE
Pagination Support

### ISSUE THREAD

**Issue by fitri** [jekyll/jekyll#6518]
Currently, Jekyll didn't support pagination natively, for many blogs pagination is one of the most important function. If Jekyll started to support pagination natively then it will a good update for Jekyll.

**Comment by DirtyF** [comment]
Pagination was taken out of core in v3.0.
Jekyll is all about being modular. If you want other common features like a feed, a sitemap, you also will have to use plugins. 
As `jekyll-paginate` is not officially maintained anymore, I'd recommend to use the excellent fork of @sverrirs `jekyll-paginate-v2`.

**Comment by pathawks** [comment]
Closing, as we've decided it's easier to maintain this feature outside of core.
**jekyll-paginate-v2** is excellent for pagination.
