### ISSUE TITLE
How do I replace newlines with spaces?

### ISSUE THREAD

**Issue by jameshfisher** [jekyll/jekyll#6523]
## Steps to reproduce

```
<meta property="og:description" content="{{ page.excerpt | strip_html | replace: '\n', ' ' }}"/>
```

## Expected behavior

```
<meta property="og:description" content="My blog posts are auto-posted to Facebook, but they look very plain when posted there. Facebook uses Open Graph tags to determine how to display URLs, and my blog was missing these. My hope is that, starting with this post, my auto-posts will look a little more enticing. "/>
```

## Actual behavior

```
<meta property="og:description" content="My blog posts are auto-posted to Facebook,
but they look very plain when posted there.
Facebook uses Open Graph tags
to determine how to display URLs,
and my blog was missing these.
My hope is that, starting with this post,
my auto-posts will look a little more enticing.
"/>
```

## Notes

`replace` seems to understand other characters, e.g. `replace: 'e', ' '` works as expected. Is the issue that Liquid does not understand the `\n` notation to denote a newline character? If so, what is the Jekyll notation for this character?

I also tried the `strip_newlines` filter for this, but it did not replace newlines with spaces; it removed the newlines entirely.

**Comment by pathawks** [comment]
Liquid does not understand `\n`.
When I have done this, I have had to `capture` a newline as a variable, and use that with the `replace` filter.

**Comment by jameshfisher** [comment]
@pathawks oh wow, that's a disgrace! At least that works though - thanks!

**Comment by pathawks** [comment]
https://github.com/Shopify/liquid/issues/923
