### ISSUE TITLE
`page.categories` to upper case

### ISSUE THREAD

**Issue by danielyang1009** [jekyll/jekyll#6524]
I'm trying to get `page.categories` to show in all upper case
```
  <div class="post-category">{{ page.categories | capitalize }}</div>
```
it shows up in all lower case `{"my-category"}` and in quotation and brackets
```
  <div class="post-category">{{ page.categories | upcase }}</div>
```
shows up the same but all upper case `{"MY-CATEGORY"}`

Can't find the way to get rid of `{""}`

my front matter is like
```
---
title: some-title
categories: my-category
---
```

**Comment by ashmaroli** [comment]
@danielyang1009 We have an Issue Template to easily grasp your basic Jekyll environment. Please utilize those fields the next time you raise an issue in future, for this current topic, please provide answers to the following:
  - Are you using **jekyll** gem or **github-pages**?
  - What version of the above gem are you using?
  - Have you tried updating to the latest version of the above gems?
  - On what OS did you face this issue? (Name and Version)
  - Are you using any plugins? If yes, specify.

**Comment by DirtyF** [comment]
👋 

This repository issues are dedicated to documented bugs only. 
You can head over to [our forum ](https://talk.jekyllrb.com) to ask any question regarding Jekyll's usage. Please search before asking, there are good chances your question has been answered. ❓

**Comment by DirtyF** [comment]
@danielyang1009 You can use CSS for that.

```css
.post-category {
    text-transform: uppercase;
}
```

**Comment by pathawks** [comment]
The issue is that Jekyll treats `categories` as a list rather than a String. You’ll have to iterate over each item in the list to do what you are trying to do.

**Comment by DirtyF** [comment]
> You’ll have to iterate over each item in the list to do what you are trying to do.

```liquid
{% if page.categories %} |
  {% for category in page.categories %}
    <div class="post-category">{{ category | upcase }}</div>
  {% endfor %}
 {% endif %}
```
