### ISSUE TITLE
Error: could not read file... invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by frodoBLR** [jekyll/jekyll#6527]
Hello everyone. Trying to type some text on russian in md file, and have UTF-8 error. What should i do?
I am using jekyll.

**Comment by pathawks** [comment]
Please use the issue template.

**Comment by frodoBLR** [comment]
Didnt get it..

**Comment by pathawks** [comment]
Probably related to https://github.com/jekyll/jekyll/pull/6433 but impossible to know without more information.

**Comment by DirtyF** [comment]
@frodoBLR Please post a link to the markdown file in russian, so that we can try to reproduce your issue and eventually add it to our test suite.
