### ISSUE TITLE
Future dated posts are not *automatically rendered* at or after the prescribed time

### ISSUE THREAD

**Issue by KarinaFernandez** [jekyll/jekyll#6536]
- [x] I believe this to be a bug, not a question about using Jekyll.

- [x] I am on (or have tested on) ***macOS*** 10+

- [x] I had an error on GitHub Pages, and I had reproduced it locally.

## My Reproduction Steps
- In the `_config.yml` file, configure to allow a future post:    **`future: false`**
- Create a post with a future time (ex: 2017-11-09 10:30:00) (and when it should appeared, it doesn't).
- Once it is the time that the post should be published, update the post and enter the same time mentioned before (ex: 2017-11-09 10:30:00) and save it, and it appears.
                                       
No changes have been done in the `_config.yml` file and future post have been working before.

## The Output I Wanted
At the publishing time, the post should be published.

**Comment by ashmaroli** [comment]
You need to set `future: true` in your `_config.yml` to allow future posts

**Comment by KarinaFernandez** [comment]
Thank you so much @ashmaroli for your answer!

I tried changing to `future: true` in the `_config.yml` and run `jekyll server --future` but it still not working.

**Comment by ashmaroli** [comment]
`jekyll server` has been deprecated since long.. what version of Jekyll are you using?

**Comment by KarinaFernandez** [comment]
I use jekyll 3.4.3

**Comment by ashmaroli** [comment]
> I use jekyll 3.4.3

Fairly recent.. It'll do.

**Comment by ashmaroli** [comment]
Okay, so to summarize, you want Jekyll to **automatically publish a future dated post** when the post is supposed to be published, is that correct?

**Comment by envygeeks** [comment]
3.4.3 is not *fairly* recent. It's quite outdated, and pre breaking Liquid 4.x.

**Comment by ashmaroli** [comment]
> 3.4.3 is not *fairly* recent.

True. But I said that because I was partly relieved that the user was not on a much older version because she'd mentioned using the deprecated `jekyll server` command

**Comment by envygeeks** [comment]
Fair enough. :smile: I didn't even know that command still existed, but I always used `s`/`b` anyways.

**Comment by KarinaFernandez** [comment]
Hi guys! I updated jekyll to the version 3.6.2 and ran `jekyll serve` but the post doesn't appear.
Thanks anyway!

**Comment by pathawks** [comment]
I bet this is a problem with incremental generation. My high level suspicion is that Jekyll reads the file initially, decides that it is a future post and should be ignored, and then is ignored even after the publish time has passed.

/cc: @jekyll/build

**Comment by envygeeks** [comment]
Can future posts even get in the way if they aren't enabled by default? Seems suspiciously like mixed concerns and logic if they can in any way.

**Comment by pathawks** [comment]
I guess maybe I don’t understand the problem.

It seems like if the desired outcome is for a post to be hidden before publication date and visible afterwards, config should include **`future: false`**

**Comment by ashmaroli** [comment]
@KarinaFernandez if your issue here is that future dated posts **do not automatically render** when the prescribed time has come, then **I think** this is more of a `feature` request.. if not, I request you to explain your issue a bit more..

**Comment by pathawks** [comment]
Good point. There has to be something else to trigger a new build after the publish time has passed. Is that the issue, @karinafernandez?

**Comment by KarinaFernandez** [comment]
The problem is the one you mentioned @ashmaroli.
Just to keep in mind, this is not a feature request, this was working before.

**Comment by ashmaroli** [comment]
> this is not a feature request, this was working before.

Do you remember what version approximately?

**Comment by pathawks** [comment]
As far as I know, this has never been a supported feature.

/cc: @jekyll/build

**Comment by KarinaFernandez** [comment]
We had been searching for an old post and we couldn't find an old post that had a future post date. Maybe this feature had never been supported.

I'm really sorry. Thank you so much for your time

**Comment by pathawks** [comment]
@KarinaFernandez No need for apologies. I wonder if it would be helpful to emit an info message with the number of future dated posts?

**Comment by KarinaFernandez** [comment]
Yes, that could be of help.
Anyway, is there any possibility to add the mentioned feature?

**Comment by manshreck** [comment]
Don't understand why this is being treated as a "feature request." The post doesn't appear once the date occurs. Regardless of whether it were future:false or future:true (which should only affect future-dated posts, not currently dated ones), the post should appear once the date is passed.

In fact, that seems to be the whole point in allowing future posting: to queue up blog posts.

+1 that this is a bug. making any other "touch" change on the website causes this to appear. That certainly is not intended behavior.

**Comment by ashmaroli** [comment]
@manshreck The processed site from Jekyll is a *static site*. The contents are purely HTML/CSS/JS and has no notion of a datetime parameter.

Its not a bug because `--future` was never designed to automatically trigger a *re-build*

**Comment by bryant1410** [comment]
what if Jekyll only "hides" future posts until their date have passed? This approach is still static.

**Comment by ashmaroli** [comment]
Once a Site has been generated, Jekyll does not act on it in any way till a new build is triggered..

**Comment by bryant1410** [comment]
But it can build every post, even future ones and just "hide" them.

**Comment by cdelfierro** [comment]
+1 to this. I don't understand the existence of the ```--future``` if is not intended to schedule new posts.

**Comment by pathawks** [comment]
I wonder if some of the confusion here comes from sites running on GitHub Pages?

Obviously, if I am running Jekyll locally, it’s easy to understand that nothing on the site will change without running `jekyll build`. However, most online blogging platforms will allow scheduled posts, which could be how users are expecting future dated posts to behave.

I wonder if we could do a better job explaining this in the docs. There isn’t an obvious way to change the behavior; it’s pretty fundamental to how a Static Site Generator works.

**Comment by laukstein** [comment]
@pathawks why not jekyll make able auto trigger to build scheduled posts? I know it is not designed so, but why not to make it work (a feature request)?

**Comment by pathawks** [comment]
@laukstein Jekyll is not cron. Use cron if you'd like to automatically build your site at some point in the future; this feature is beyond the scope of the project.

**Comment by jekyllontime** [comment]
I am working on a service to solve this problem - https://jekyllontime.top.
It is in a very early stage now, so I would appreciate your feedback a lot!
So far it allows to push a commit to GitHub at a given time, but I am open to any suggestions.

**Comment by CraigChamberlain** [comment]
> 
> 
> But it can build every post, even future ones and just "hide" them.

The hiding would have to be done with javascript and this would not really be a Jekyll thing.  A better approach would be a service as @jekyllontime suggests.  People have made their own with scheduling apps to trigger a github commit or some other action.

**Comment by mgrider** [comment]
Has anyone confirmed adding `future: true` to the config actually works? I can't get the posts to render locally unless I run the server with the `--future` flag set.

**Comment by PaulSolt** [comment]
It looks like you could use [Github actions to make it rebuild with Netlify](https://community.netlify.com/t/scheduling-builds-and-deploys-with-netlify/2563/10)
