### ISSUE TITLE
Build: Kramdown warnings do not display document relative path

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#6539]
Related: #6522 

```gherkin
Given I am on the `master` branch of this repo
When I run `bundle exec jekyll rake:preview`
Then the following warnings are displayed:
```

```sh
  Kramdown warning: No link definition for link ID '#1339' found on line 2
  Kramdown warning: No link definition for link ID '' found on line 2
  Kramdown warning: No link definition for link ID '#1338' found on line 3
  Kramdown warning: No link definition for link ID '' found on line 3
  Kramdown warning: No link definition for link ID 'docs' found on line 150
  Kramdown warning: No link definition for link ID 'rubocop' found on line 260
  Kramdown warning: No link definition for link ID '"permalink"' found on line 299
  Kramdown warning: No link definition for link ID 'site' found on line 375
  Kramdown warning: No link definition for link ID 'docs' found on line 437
  Kramdown warning: No link definition for link ID 'docs' found on line 580
  Kramdown warning: No link definition for link ID 'docs' found on line 583
  Kramdown warning: No link definition for link ID 'docs' found on line 592
  Kramdown warning: No link definition for link ID 'add note' found on line 926
  Kramdown warning: No link definition for link ID '' found on line 1002
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
```
## Expected output 

```
Kramdown: No link definition for link ID '' found on line 1002 in /_docs/configuration.md
```

/cc @jekyll/build

**Comment by ashmaroli** [comment]
> `Kramdown: No link definition for link ID '' found on line 1002 in /docs/_docs/configuration.md`

@DirtyF, there's a small error in your "Expectation" above. `/docs/` is where the Jekyll site is based at. (i.e. the source dir). Therefore, you should ideally expect to see just `_docs/configuration.md` irrespective of your current location.. :smiley:

Jokes apart, its a nice find.. Always better to fix a bug in an unreleased enhancement.

**Comment by DirtyF** [comment]
The first two warning are related to [this post](https://raw.githubusercontent.com/jekyll/jekyll/8ae2673ebae7c9d2a7c75e3e3e95729cde04cdfc/docs/_posts/2013-07-24-jekyll-1-1-1-released.markdown) where references are defined in a Liquid for loop.

**Comment by ashmaroli** [comment]
> where references are defined in a Liquid for loop.

Why isn't `[strange excerpt bug in v1.1.0][#1321]` warned about then?

**Comment by parkr** [comment]
I just ran into this and was really confused! Good to fix before the next release. 👍

**Comment by ashmaroli** [comment]
The second set of warnings come from the `SmartyPants` Parser
https://github.com/jekyll/jekyll/blob/master/lib/jekyll/converters/smartypants.rb#L3-L9

```
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
  Kramdown warning: Warning: this should not occur - no block parser handled the line
```

@pathawks I was able to "remove" the warning locally by *deleting* the `@block_parsers = [:block_html]` in the Smartypants Parser. Is our definition really necessary?

**Comment by pathawks** [comment]
> Is our definition really necessary?

Yes

**Comment by ashmaroli** [comment]
> Yes

I was hoping for a slightly more verbose answer. Please explain why.. (for knowledge purposes..)

**Comment by pathawks** [comment]
@ashmaroli Look at the failing tests to see why.

If you just remove that line, the `smartify` filter will wrap all output in a `<p>` tag, which is [Bad and Wrong](http://www.catb.org/jargon/html/B/Bad-and-Wrong.html).

If you replace the line with `@block_parsers = []`, the filter will try to escape HTML tags: `"<div>" => "&lt;div&gt;"`, which is wrong.

We are subclassing `Kramdown::Parser::Kramdown` as is the correct way to build a custom processor.

https://github.com/gettalong/kramdown/blob/a8375683c2873d09a24be53594056199725e068e/lib/kramdown/parser/kramdown.rb#L23-L28

I am guessing that either there is an option somewhere that we need to flip, or this is a bug in kramdown.

https://github.com/gettalong/kramdown/blob/78120ea7cd41ec7e056fa30d563c961add0c3b1a/lib/kramdown/parser/kramdown.rb#L153

**Comment by pathawks** [comment]
Since a converter has no idea what file it is converting, perhaps we need to create a Jekyll warning that can be raised by converters. The kramdown converter could then wrap its own warnings with the Jekyll warning.

**Comment by ashmaroli** [comment]
> I am guessing that either there is an option somewhere that we need to flip, or this is a bug in kramdown.

We may need to bring `@gettalong` into the loop to fix this sooner..

**Comment by pathawks** [comment]
@ashmaroli Where are we even using the `smartify` filter on our docs site? I can't find where this could be coming from.

**Comment by ashmaroli** [comment]
```
        Rendering: feed.xml
 Pre-Render Hooks: feed.xml
 Rendering Liquid: feed.xml
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Kramdown warning: Warning: this should not occur - no block parser handled the line
 Rendering Markup: feed.xml
 Rendering Layout: feed.xml
```

**Comment by pathawks** [comment]
@ashmaroli Right. Forgot about **jekyll-feed**. Thanks for doing that digging.

**Comment by DirtyF** [comment]
@fw42 Do Kramdown knows about the file he is converting? Can we display this information to the user?

**Comment by pathawks** [comment]
Jekyll converters are given a block of content and return a block of converted content. There is never any notion of files in _our_ converters.

**Comment by DirtyF** [comment]
@pathawks Thanks for clearing that up, wasn't sure.

**Comment by Crunch09** [comment]
Thank you for checking this with the website @DirtyF , i should have already done that in #6522 😞 
I assume without file names these warnings are not much helpful to the users.
> Since a converter has no idea what file it is converting, perhaps we need to create a Jekyll warning that can be raised by converters. The kramdown converter could then wrap its own warnings with the Jekyll warning.

I like this idea 👍  We can check this somewhere [here](https://github.com/jekyll/jekyll/blob/525efbc2f89c4972e5defda74b268222c08fa1f4/lib/jekyll/renderer.rb#L117-L129) and apply the filename as with any other warnings.

**Comment by DirtyF** [comment]
@Crunch09  We should have reviewed your PR more carefully 😅 
👍 on raising Kramdown warnings during the rendering.

**Comment by pathawks** [comment]
https://github.com/gettalong/kramdown/issues/473

**Comment by pathawks** [comment]
Yeah, it looks like there is no way to avoid the SmartyPants warnings without subclassing large parts of kramdown.
Since the warnings will never actually be relevant to the user, let's just not log kramdown warnings for the SmartyPants filter.

**Comment by DirtyF** [comment]
Fixed by #6564 and https://github.com/jekyll/jekyll/commit/169ecf91c9a71ace1dde467babd780b14ab8b4e3

**Comment by pathawks** [comment]
Wait, have we actually fixed it so it outputs the file path?

**Comment by DirtyF** [comment]
See https://github.com/jekyll/jekyll/pull/6553
