### ISSUE TITLE
Using --force gives a different directory structure.

### ISSUE THREAD

**Issue by Prathik-Jain** [jekyll/jekyll#6562]
#### I tried using `--force` option and ended up getting an unusual Jekyll directory structure.

![screenshot_20171116_024225](https://user-images.githubusercontent.com/25041441/32860625-1b0bd5c4-ca4a-11e7-82d7-6659e7c111f6.png)

**Comment by pathawks** [comment]
Can you explain what specifically was different from what you expected? Nothing in your listing seems out of place.

**Comment by DirtyF** [comment]
If by unusual you mean where are the layouts, includes and assets? It's because `jekyll new` uses a [gem-based theme](https://jekyllrb.com/docs/themes/#understanding-gem-based-themes).

**Comment by Prathik-Jain** [comment]
This is how the directory looks.  -no modifications at all.

![screenshot_20171116_025653](https://user-images.githubusercontent.com/25041441/32861332-47b6e418-ca4c-11e7-9a15-a82e69fcd07e.png)

**Comment by DirtyF** [comment]
That's perfectly normal, please read our documentation before opening issues on this bug tracker.
If you need any help, please ask on[ our forum](https://talk.jekyllrb.com)

**Comment by Prathik-Jain** [comment]
No its not - the documentation doesn't say that we'll have two  `404.html` files in a new build . 
moreover ` jekyll new . ` that is without `--force` gives the following structure.
![screenshot_20171116_031052](https://user-images.githubusercontent.com/25041441/32861846-f8b660e4-ca4d-11e7-9f56-7525e581322d.png)
