### ISSUE TITLE
missing requirements to "bigdecimal" in tutorial

### ISSUE THREAD

**Issue by dirteat** [jekyll/jekyll#6563]
- [x] I believe this to be a bug, not a question about using Jekyll.

---

- [x ] I am on (or have tested on) ***Other*** GNU/Linux

- [ x] I was trying to install.

## My Reproduction Steps

Starting from scratch, I have followed the tutorial for noobs to install jekyll, which is:

# Install Jekyll and Bundler gems through RubyGems
gem install jekyll bundler

First issue, usually jekyll lands into a directory which is not in the path, a little sentence added here would help, just to say "help yourself to find the binary path, for instance with gem env". Took me 10mn to find the existence of "gem env"

# Create a new Jekyll site at ./myblog
jekyll new myblog

This crashes because a missing requirement is "bigdecimal", this should be added in the list if requirements I guess.

Thanks,
Cheers.

**Comment by ashmaroli** [comment]
> This crashes because a missing requirement is "bigdecimal"

`bigdecimal` is not a requirement to be listed. It is part of Ruby's built-in Standard library. What version of Ruby are you on and what exactly is the error message displayed on crashing..?

**Comment by dirteat** [comment]
``
jekyll new blabla
``

/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bigdecimal (LoadError)


I have fixed it by installing a package named "ruby-bigdecimal" on my distro (Mageia).
This is ruby 2.2.8p477 (2017-09-14 revision 59906).

**Comment by DirtyF** [comment]
@dirteat Thanks for the feedback, we didn't test default install for [all Linux distro out there](http://futurist.se/gldt/wp-content/uploads/12.10/gldt1210.svg) 😅 

Glad you fixed it 👍

**Comment by dirteat** [comment]
Thanks for the help.

I am adding one comment on this, just in case it may help others with the same issues.
After installing the system-wide ruby-bigdecimal package, running:
``
jekyll serve
``
works fine. But running:
``
bundle exec jekyll serve
``
crashed again with:
bundler: failed to load command: jekyll (/home/chris/.gem/bin/jekyll)
LoadError: cannot load such file -- bigdecimal

Doing
``
gem install bigdecimal
``
does not help, as bundle seems to only consider the system-wide version. I suspect the problem comes from some conflicts between the system-wide install of bigdecimal and the one installed locally.  The only working solution I have found is to explicitly add:
``
gem "bigdecimal"
``
in the Gemfile to force bundle to use the local installed version. I've bounced on the same problem with "json".

Cheers,
Chris.

PS: I am even not sure what I am talking about, ruby was only a stone for me till yesterday :)

**Comment by pathawks** [comment]
We could add checks for these system libraries to `jekyll doctor`?

**Comment by ashmaroli** [comment]
> We could add checks for these system libraries

IMO, that'd be an over-engineering with respect to >80% of our users, especially in light of never having received a similar issue centered around Ruby 2.2.x..

**Comment by pathawks** [comment]
Previously there have been issues due to JSON not being installed. It would be fairly easy to try to `require` these things and see what happens.

**Comment by ashmaroli** [comment]
If `bundle exec jekyll doctor` itself is going to fail, I believe its beyond Jekyll's scope to notify users what needs to be done to proceed.. (just my 2cents..)

**Comment by DirtyF** [comment]
@pathawks What could `jekyll doctor`do about dependencies problems? Test they're all installed? Isn't that already what `bundler` is supposed to do?
