### ISSUE TITLE
Uninstall Jekyll(need more info)

### ISSUE THREAD

**Issue by doongsilee** [jekyll/jekyll#6572]
How to completely remove Jekyll that was installed using your own guide (sudo gem install Jekyll)?
 I would like to run Jekyll using Docker. so I want to uninstall Jekyll on my machine clearly.

I saw the issue number #3168 and I tried it
but [gem uninstall Jekyll] command doesn't delete it all. 
there something still remains like Jekyll-feeds and other dependencies.
Could you please give some more guide?
Thanks.

**Comment by pathawks** [comment]
It's probably because you used `sudo` (which is **not** recommended)

Learn about uninstalling Gems with `gem uninstall -h`. You can decide which options are right for you.
