### ISSUE TITLE
Rendering CSS on Pages: URL Problem?

### ISSUE THREAD

**Issue by JuanDiegoDC** [jekyll/jekyll#6576]
Pardon if this is the wrong place to post this.  This is an inquiry, not a bug. 

I have just started to use Jekyll with the Hyde theme in the attempt to create my own portfolio/blog. 

I have a website at http://juandiegodc.com and the link to the repo is here (http://github.com/JuanDiegoDC/hyde). The problem is that whenever I try to access a new page within the site (for example 'About') I lose the CSS style and can only view a plain-text. How do I fix this formatting issue, I am sure it has something to do with the url linking. However, I have tried everything to no avail. 

As you can see I am a beginner at this and would truly appreciate any input.

**Comment by ashmaroli** [comment]
@JuanDiegoDC You can post all "inquiries" about using Jekyll on our forum at http://talk.jekyllrb.com or on a third-party forum at `https://stackoverflow.com`

Regarding your current issue, use `relative_url` filters in your `<link>` definitions. For example,
```diff
- <link rel="stylesheet" href="{{ site.baseurl }}public/css/poole.css">
+ <link rel="stylesheet" href="{{ 'public/css/poole.css' | relative_url }}">
```

**Comment by JuanDiegoDC** [comment]
@ashmaroli Thank you very much!  I foresee a lot of time being spent on that forum.

**Comment by ashmaroli** [comment]
You're welcome. Checkout https://jekyllrb.com/docs/home/ for official documentation on running a Jekyll Project.
Good luck & Happy Jekylling!! :smiley:
