### ISSUE TITLE
All Jekyll commands fail after High Sierra upgrade

### ISSUE THREAD

**Issue by rensa** [jekyll/jekyll#6579]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***macOS*** 10+

---

- [x] I was trying to build.

## My Reproduction Steps

My `bundle exec jekyll serve`, `jekyll doctor` and other Jekyll commands have all started failing since I **upgraded to *macOS High Sierra (10.13.1)***:

```
rensa@rensa-mbp:rensa.github.io$ bundle exec jekyll serve
bash: /usr/local/bin/bundle: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby:
bad interpreter: No such file or directory
```
```
rensa@rensa-mbp:rensa.github.io$ jekyll serve
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Library/Ruby/Gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/plugin_manager.rb:48:in `require_from_bundler'
        from /Library/Ruby/Gems/2.3.0/gems/jekyll-3.6.2/exe/jekyll:11:in `<top (required)>'
        from /usr/local/bin/jekyll:22:in `load'
        from /usr/local/bin/jekyll:22:in `<main>'
```
```
rensa@rensa-mbp:rensa.github.io$ jekyll doctor
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Library/Ruby/Gems/2.3.0/gems/jekyll-3.6.2/lib/jekyll/plugin_manager.rb:48:in `require_from_bundler'
        from /Library/Ruby/Gems/2.3.0/gems/jekyll-3.6.2/exe/jekyll:11:in `<top (required)>'
        from /usr/local/bin/jekyll:22:in `load'
        from /usr/local/bin/jekyll:22:in `<main>'
```

I've tried reinstalling Jekyll with `sudo gem uninstall jekyll` and `sudo gem install jekyll`. I've also tried running `xcode-select --install` and then reinstalling Jekyll.

**Comment by ashmaroli** [comment]
@rensa `require': cannot load such file -- bundler (LoadError) is telling you that Ruby couldn't find Bundler gem installed on your system.

Do try installing it first with `gem install bundler` and then with `sudo gem install bundler` if the first command fails.

**Comment by rensa** [comment]
@ashmaroli Yeah, that got me there! I was also instructed to `bundle install`, but I'm up and running now 🙂 

I think failing to `brew update` and `brew upgrade` after my macOS update might've caused some broader ruby issues, because I'm having problems with a lot of other brew-installed apps, like vim. But thanks for helping me get Jekyll going again 🙂

**Comment by ashmaroli** [comment]
> thanks for helping me get Jekyll going again :slightly_smiling_face: 

You're welcome :slightly_smiling_face: . Closing this then..

**Comment by rensa** [comment]
(For future reference, I learned a valuable lesson today about not using `conda` to set up Python 3.x and then forgetting about it)

![screenshot 2017-11-27 14 16 23](https://user-images.githubusercontent.com/6520659/33249481-f1a4b834-d37e-11e7-8e3f-c5d167e6bcb1.png)
