### ISSUE TITLE
Theme doesn't update when using existing jekyll build

### ISSUE THREAD

**Issue by diisoriiented** [jekyll/jekyll#6580]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

---

- [x] I was trying to build.

## My Reproduction Steps

```sh
$ jekyll new
$ nano Gemfile     # change theme e.g. 'gem jekyll-theme-minimal, "~> 0.1.0"'
$ bundle update
$ nano _config.yml # edit theme to 'jekyll-theme-minimal'
$ bundle exec jekyll serve -w
```
also ran

```sh
$ bundle exec jekyll clean
$ bundle exec jekyll serve
```

## The Output I Wanted

All commands ran fine, but the site is now blank and did not run with the updated theme. Not sure how to update the theme as I followed exact directions from here: https://jekyllrb.com/docs/themes/.

**Comment by ashmaroli** [comment]
Not every theme is designed to render content similar to `Minima`. Your `index.md` doesn't have any content to render.

Add the following to your `index.md` after the front matter dashes, and build again:
```
## Heading 2

This is a paragraph that will contain a blockquote on the next line.
> "Ask and you shall receive!"

Still confused? Try the [docs](https://github.com/pages-themes/minimal) for this theme
```

**Comment by ashmaroli** [comment]
This issue is best tackled at the [dedicated repository](https://github.com/pages-themes/minimal) for the theme..
Closing..
