### ISSUE TITLE
Casting to date/time to check against `post.date` in `where_exp`

### ISSUE THREAD

**Issue by oncletom** [jekyll/jekyll#6581]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I was trying to build.

## My Reproduction Steps

Hello there,

thank you for making Jekyll, it is a super handy tool I use both personally and professionaly (if there is a difference) 🙂 

I was trying to create an advent calendar and I **struggled to fetch blog posts published at a given date**.

Here is how I designed it:

- a list of dates set in random order in _config.yml (`[2017-12-08', '2017-12-03', ...]`)
- I iterate over the dates
- for each date, I try to find a matching published blog post with `where_exp`
- build is date independant (content can be viewed if it's been published `--future` is cool about that)

Which translates into this intent:

```
{% for day in site.calendar.days_order %}
        {% assign post = site.posts | where_exp: "post", "post.date == day" | first %}
        {% include day.html day=day post=post %}
{% endfor %}
```

BUT:

- `post.date` is casted as a `Time` object so I can't compare it equally with a string like `2017-12-01`
- I cannot cast `2017-12-01` as a `Time` object (`Liquid::Utils.to_date` could do but it's not exposed)
- I cannot _pipe_ in `where_exp` so I can't do `where_exp: "post", "(post.date| date:'%Y-%m-%d') == day"`

## The Output I Wanted

So I wonder if we could get an arbitrary time object, which is not `now` nor `today` by stating that **`date` without argument returns `Date.parse`** so as we can deal with dates (`divide`, `minus` then format back to something else).

```
{% for day in site.calendar.days_order %}
        {% assign date = day | date %}
        {% assign post = site.posts | where_exp: "post", "post.date == date" | first %}
        {% include day.html day=day post=post %}
{% endfor %}
```

Ultimately we could do:

```
{% assign year = '2015-01-01' | date | minus: 3600 | date: '%Y' %}
```

What do you think?

**Comment by pathawks** [comment]
In your particular use case, just define `site.calendar.days_order` to be an array of `Date` instead of an array of `String`.

`[2017-12-01, 2017-12-08, …]`

**Comment by oncletom** [comment]
@pathawks thanks for the recommendation :-)

I checked and it is already how it's done. They are not casted as Dates when used in templates :-(

https://github.com/etalab/calendrier-lavent/blob/bbaaea15caa997f34a9bd76858e95d294c888230/_config.yml#L29-L53

**Comment by pathawks** [comment]
I have had luck comparing a `DateTime` set in YAML (`2016-08-01t01:00:00.00-08:00`) with `post.date`. Perhaps you need to include a time stamp to make it work?

I agree that Liquid should include a way to specify a date literal. I would argue that this would be better handled by Liquid than by Jekyll.

**Comment by oncletom** [comment]
Wow! The `[2017-12-08T00:00:00, 2017-12-03T00:00:00, …]` does the trick indeed!

Thanks, it makes the code cleaner :-)
