### ISSUE TITLE
It looks like you don't have jekyll-remote-theme or one of its dependencies installed

### ISSUE THREAD

**Issue by andevele** [jekyll/jekyll#6583]
When input：bundle exec jekyll serve
The error message is as follows：
$ bundle exec jekyll serve
Configuration file: H:/gitblog/andevele.github.io/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
  Dependency Error: Yikes! It looks like you don't have jekyll-remote-theme or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'Could not open library 'libcurl': ▒Ҳ▒▒▒ָ▒▒▒▒ģ▒顣 . Could not open library 'libcurl.dll': ▒Ҳ▒▒▒ָ▒▒▒▒ģ▒顣 . Could not open library 'libcurl.so.4': ▒Ҳ▒▒▒ָ▒▒▒▒ģ▒顣 . Could not open library 'libcurl.so.4.dll': ▒Ҳ▒▒▒ָ▒▒▒▒ģ▒顣 ' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
jekyll 3.6.2 | Error:  jekyll-remote-theme

Then I installed as follows：
$ gem install jekyll-remote-theme
Successfully installed jekyll-remote-theme-0.2.3
Parsing documentation for jekyll-remote-theme-0.2.3
Done installing documentation for jekyll-remote-theme after 0 seconds
1 gem installed

And Finally, I enter this comman 
bundle exec jekyll serve
Errors still occur

How to solve this problem ？

**Comment by ashmaroli** [comment]
@andevele This Issue Tracker is meant to document bugs in the code.
For questions regarding `How to..`, please use our forum at http://talk.jekyllrb.com/

You can find further information on using Jekyll by referring the official docs at https://jekyllrb.com/docs/home/

**Comment by DirtyF** [comment]
@andevele This seems related to the use of `libcurl` on Windows, you should ask on https://github.com/benbalter/jekyll-remote-theme repo instead.

**Comment by yanxyz** [comment]
I also meets this issue. The reason is that one gem that  jekyll-remote-theme used can not find `libcurl.dll`.

My solution: download curl [here](https://curl.haxx.se/download.html#Win32). I've tried the binary provided by Marc Hörsken, unpack the downloaded package, and then copy the `lib/.libs/libcurl-4.dll` to `libcurl.dll` and put it under some directory in PATH, e.g. `/path/to/ruby/bin`.
