### ISSUE TITLE
The dependency of jekyll is not complete

### ISSUE THREAD

**Issue by jsycdut** [jekyll/jekyll#6592]
- [x] This is a feature request.
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I was trying to install.

This is no big deal.  I successfully install jekyll with `gem`, but when I run `jekyll s` to start the server, I met a dependency issue, `minima` is missing, and `jekyll-feed` is missing too.
  You guys declamin that `gem` will automatically manage the dependency, so I suggest that you 
  should take the dependency above into your consideration, Thanks.
  And `bundler` seems to be stepped over when install `jekyll`.

**Comment by ashmaroli** [comment]
This is the reason why we recommend having both `Bundler` and `Jekyll` gem installed in [our docs](https://jekyllrb.com/docs/quickstart/#about-bundler)

**Comment by DirtyF** [comment]
AFAIK we don't intend to define `bundler` as a dependency. Please note that if you use Ruby 2.5, it's already installed by default. Using a Gemfile is the best way to manage a project dependency like you would use a package.json in nodeJS.

**Comment by ashmaroli** [comment]
@DirtyF Ruby 2.5 doesn't include `bundler` by default.. They reverted that just before shipping..
