### ISSUE TITLE
Sass Variables do not Compile Without Interpolation Syntax

### ISSUE THREAD

**Issue by bryantwells** [jekyll/jekyll#6601]
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I was trying to build.

---

## My Reproduction Steps

Running `jekyll serve --watch` `jekyll serve` `jekyll build` etc...

### Input

main.scss
~~~
@function max-size($vw) {
    @return ($vw / 100) * $max-width
}

$base-font-size: 3.5vw;
$sm-font-size: 2vw;
$lg-font-size: 12.9vw;

@import 'base.scss';
~~~

base.css
~~~
:root {
    $max-width: 1200px;

    --base-font-size: $base-font-size;
    --sm-font-size: $sm-font-size;
    --lg-font-size: $lg-font-size;

    @media (min-width: $max-width) {
        --base-font-size: max-size(3.5);
        --sm-font-size: max-size(2);
        --lg-font-size: max-size(12.9);
    }
}
~~~

### Output 

main.css
~~~
:root {
    --base-font-size: $base-font-size;
    --sm-font-size: $sm-font-size;
    --lg-font-size: $lg-font-size;

    @media (min-width: 1200px) {
        --base-font-size: max-size(3.5);
        --sm-font-size: max-size(2);
        --lg-font-size: max-size(12.9);
    }
}
~~~

---

After trying to figure out what the hell was going on here for a couple hours — I found out that these stylesheet _do_ compile correctly, if every variable instance and function reference is wrapped in a interpolation tag (  **#{}**  ).  

For comparison: when compiling with node-sass using node-js, the resulting stylesheet is as expected (without interpolation tags).

**Comment by ashmaroli** [comment]
This should ideally be forwarded to https://github.com/jekyll/jekyll-sass-converter which is in-turn a wrapper for the https://github.com/sass/sass gem.

Have you tried compiling directly with the `sass` gem..?

**Comment by bryantwells** [comment]
just tried using the sass gem — works as expected. Thanks @ashmaroli for the prompt response, will fwd to the sass converter repo
