### ISSUE TITLE
Mixing Liquid with Markdown produces only Liquid and raw Markdown.

### ISSUE THREAD

**Issue by ConduciveMammal** [jekyll/jekyll#6619]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps
I was trying to have liquid rendering inside of a markdown post but it seems the markdown is ignored when using Liquid.

For example, in a header, I tried `#{{page.title}}` and instead of the expected `<h1>GitHub</h1>`, I got `<h1>#GitHub</h1>`.

**Comment by pathawks** [comment]
Is this in a layout? Layouts are not processed by Converters, so Markdown does not get converted.

**Comment by ConduciveMammal** [comment]
Sorry, no it’s in a HTML post.

**Comment by pathawks** [comment]
Change the extension of the post file to `.md`?

**Comment by ConduciveMammal** [comment]
Already have done. Everything else in the post file is rendering fine, it’s just that one line.

**Comment by pathawks** [comment]
Is the repository public? It should work.

**Comment by ashmaroli** [comment]
@ConduciveMammal Your Markdown syntax is incorrect (in the given sample). There's no whitespace between the `#` and title-text..

Processing the following will give you:
```
#{{page.title}}

# {{page.title}}

# {{ page.title }}
```
```
<p>#GitHub</p>
<h1>GitHub</h1>
<h1>GitHub</h1>
```

**Comment by ashmaroli** [comment]
Closed this because:
  - it doesn't look like a `bug` to me..
  - there has been no further communication from the ticket-author
