### ISSUE TITLE
Error makes when I trying to local host

### ISSUE THREAD

**Issue by STEdirisuriya** [jekyll/jekyll#6622]
When I try to make a local host from my windows pc. I typed "Jekyll Serve" on the cmd. But There ahow a file missing like following.
```
PS D:\My documents\GCI\gci17.fossasia.org> gem install github-pages
Fetching: kramdown-1.14.0.gem (100%)
Successfully installed kramdown-1.14.0
Fetching: listen-3.0.6.gem (100%)
Successfully installed listen-3.0.6
Fetching: jekyll-sass-converter-1.5.0.gem (100%)
Successfully installed jekyll-sass-converter-1.5.0
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing github-pages:
        ERROR: Failed to build gem native extension.

    current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1/ext/commonmarker
C:/tools/ruby24/bin/ruby.exe -r ./siteconf20171211-9464-34e8f8.rb extconf.rb
creating Makefile

current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1/ext/commonmarker
make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1/ext/commonmarker
make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1 for inspection.
Results logged to C:/tools/ruby24/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/commonmarker-0.17.7.1/gem_make.out
```
I installed bundle, Ruby, Chocaletry, Jekyll,... But why makes error?

**Comment by ashmaroli** [comment]
This repo is not for debugging `github-pages`.. Please ask at https://github.com/github/pages-gem

**Comment by DirtyF** [comment]
@STEdirisuriya Did you install development kit as mentioned in our docs? https://jekyllrb.com/docs/windows/#install-ruby-and-ruby-development-kit

You need tools to compile native extensions like common-marker (C extension)

**Comment by STEdirisuriya** [comment]
I installed all but same as first window

**Comment by DirtyF** [comment]
Sorry I don't use Windows, but feel free to let us know how to improve our documentation once https://github.com/github/pages-gem/issues/508 is resolved.

**Comment by ashmaroli** [comment]
By default, Jekyll (on Windows) does not require `make` / `cmake` / other building-tools other than the recommended DevKit package for the installed Ruby Version.

Jekyll hasn't added a dependency on `commonmarker` yet, so it doesn't have to document the requirement of `make` / `cmake` etc..
