### ISSUE TITLE
Problem when generating Jekyll, there is a strange symbol.

### ISSUE THREAD

**Issue by DjonyBastone** [jekyll/jekyll#6633]
## Good day!
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
---
- [x] I am on (or have tested on) ***Windows*** 7
---
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Problem when generating Jekyll:
When you generate a page, text, headings, meta tags, there is a strange symbol.

![bug](https://user-images.githubusercontent.com/17172262/34036940-ad0e8276-e1a8-11e7-9885-e24da6139c6b.jpg)
The page uses Russian language.
When a new generation of symbols may not appear, or appear elsewhere.
As a result, one letter is replaced by the two symbols.

Maybe someone faced with similar?

## The Output I Wanted

Please help to solve the problem.

**Comment by DirtyF** [comment]
Hi @DjonyBastone any public repo where the behavior can be reproduced?

**Comment by DjonyBastone** [comment]
[remont-full-bug](https://github.com/DjonyBastone/remont-full-bug)
When bundle Jekyll this can happen in the body of the page text, headers, meta tags. 
Sometimes the symbol does not appear. Therefore, bundle Jekyll, need to make several times.

**Comment by DirtyF** [comment]
@DjonyBastone Could you test without applying the `compress` layout?

**Comment by DjonyBastone** [comment]
Yes, of course
Will test a few days to be sure to exclude this option.

**Comment by DjonyBastone** [comment]
disable `compress`

![image](https://user-images.githubusercontent.com/17172262/34053951-93617cba-e1ea-11e7-9a10-67c95f90ae5c.png)

the problem is not solved

![image](https://user-images.githubusercontent.com/17172262/34054042-fc1cbe90-e1ea-11e7-8ace-4bf3109a70b5.png)

**Comment by DjonyBastone** [comment]
Removed the plugin, Jekyll-paginate, breadcrumbs.
Installed Jekyll-paginate-v2
Error remained.

The Assembly was launched with the help of tusk Gulp. Error therefore?

**Comment by DjonyBastone** [comment]
@DirtyF, good day!

On a different project with a different set of plugins.
![image](https://user-images.githubusercontent.com/17172262/34926846-03178698-f9d4-11e7-991d-6cf28a0e7dc4.png)
The project is based - [mmistakes](https://github.com/mmistakes/made-mistakes-jekyll).
Use the plugins just like in mmistakes.

I assume that the problem is in the encoding

**Comment by DjonyBastone** [comment]
Sorry. Jekyll to do with it. This is the local server [Browsersync](http://disq.us/p/1pebxbg)
