### ISSUE TITLE
jekyll trace command doesn't give desired result

### ISSUE THREAD

**Issue by zorbathegreek** [jekyll/jekyll#6647]
I opened an issue here:
https://github.com/mmistakes/minimal-mistakes/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed
where there filing template is different from the one below. 

The proposed command there to retrieve info about an issue is
bundle exec jekyll --trace --verbose
but I was getting error messages:

[user@localhost gorillablog]$ bundle exec jekyll --trace --verbose
jekyll 3.6.2 | Error:  Whoops, we can't understand your command.
jekyll 3.6.2 | Error:  invalid option: --verbose
jekyll 3.6.2 | Error:  Run your command again with the --help switch to see available options.
[user@localhost gorillablog]$ 
[user@localhost gorillablog]$ bundle exec jekyll --trace --verbose --help
jekyll 3.6.2 | Error:  Whoops, we can't understand your command.
jekyll 3.6.2 | Error:  invalid option: --verbose
jekyll 3.6.2 | Error:  Run your command again with the --help switch to see available options.

The command I found out to be giving the desired result (?) is
bundle exec jekyll serve --trace

Not sure if this is a bug or just a typo in that template. 
I'm on Fedora 27, updated almost daily. 
I did run bundle update

Regards,

Anthony

- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

**Comment by pathawks** [comment]
Where is the mistake in our documentation?

**Comment by ashmaroli** [comment]
@zorbathegreek There is no command called `jekyll --trace` or `jekyll trace`
Run **`jekyll help`** or **`bundle exec jekyll help`** to see the available jekyll commands for your installation.

The `--trace` option or switch is supposed to be used as an adjunct to a vaild jekyll command you find listed in that help menu.. e.g.:
```
jekyll build --trace
```
```
jekyll serve --trace
```
```
jekyll new myblog --trace
```

**Comment by zorbathegreek** [comment]
Sorry if I wasn't clear enough. 
When I open an issue here:
https://github.com/mmistakes/minimal-mistakes/issues/new ,
I am asked to use the guidelines (below) which include the following paragraph:
"  Then provide a complete log by running `bundle exec jekyll --trace --verbose` 
  and include this output in the filed issue."
But running that command gives an error message (included above), not a log.

Regards,
Anthony
 
Below is that complete "New issue" template: 


- [ ] This is a question about using the theme.
- [ ] This is a feature request.
- [ ] I believe this to be a bug with the theme.
  - [ ] I have updated all gems with `bundle update`.
  - [ ] I have tested locally with `bundle exec jekyll build`.

---

## Environment informations



- **Minimal Mistakes version:** 
- **Jekyll version:**
- **GitHub Pages hosted:** yes/no
- **Operating system:** 

---

## Expected behavior



## Steps to reproduce the behavior

**Comment by pathawks** [comment]
I understand. The issue is with the Minimal Mistakes issue template. It will have to be fixed over there.

Sorry for the ping pong.

**Comment by ashmaroli** [comment]
it has been fixed with https://github.com/mmistakes/minimal-mistakes/commit/e68f2c1601e327380cdede893c715494eb372053
