### ISSUE TITLE
documentation error for novices

### ISSUE THREAD

**Issue by githubgnulinux** [jekyll/jekyll#6653]
Web page https://jekyllrb.com/docs/drafts/ states: "... simply run jekyll serve or jekyll
   build with the --drafts switch...."
   
jekyll serve --drafts
Configuration file: none
            Source: /home/user/weblog
       Destination: /home/user/weblog/_site
      Generating... 
     Build Warning: Layout 'post' requested in directory/_drafts/testdraft.html does not exist.
     Build Warning: Layout 'post' requested in directory/_posts/2017-12-27-welcome-to-jekyll.markdown does not exist.
     Build Warning: Layout 'page' requested in directory/about.md does not exist.
     Build Warning: Layout 'default' requested in directory/index.html does not exist.
                    done.
Configuration file: none
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
jekyll build --drafts
Configuration file: none
            Source: /home/user/weblog
       Destination: /home/user/weblog/_site
      Generating... 
     Build Warning: Layout 'post' requested in directory/_drafts/testdraft.html does not exist.
     Build Warning: Layout 'post' requested in directory/_posts/2017-12-27-welcome-to-jekyll.markdown does not exist.
     Build Warning: Layout 'page' requested in directory/about.md does not exist.
     Build Warning: Layout 'default' requested in directory/index.html does not exist.
                    done.

Please advise to solve this error and advise the documentation team to improve clarity of instructions.

**Comment by DirtyF** [comment]
👋  Sorry but this repository issues are dedicated to documented bugs only. 
Good news is you can head over to [our forum ](https://talk.jekyllrb.com) to ask for help
Please search before asking, there are good chances your question has already been answered.

Happy Jekyllin'!

**Comment by pathawks** [comment]
It looks like you probably want to `cd directory` before running `jekyll build`
