### ISSUE TITLE
site.related_post is returning nil when there are related posts

### ISSUE THREAD

**Issue by Ch4s3** [jekyll/jekyll#6663]
I'm posting this in relation to https://github.com/jekyll/classifier-reborn/issues/170. The user was able to feed their articles into the LSI manually and get the expected output, but the Jekyll integration doesn't seem to work.

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] It was another bug.

@mthmulders can you attach reproduction steps?

**Comment by mthmulders** [comment]
Sure! I think I have a pretty normal Jekyll setup. My Gemfile looks like this:

    # frozen_string_literal: true
    source "https://rubygems.org"
    
    gem 'jekyll',            '3.6.2'
    gem 'jekyll-archives',   '2.1.1'
    gem 'jekyll-feed',       '0.9.2'
    gem 'jekyll-minifier',   '0.1.4'
    gem 'jekyll-sitemap',    '1.1.1'
    gem 'classifier-reborn', '2.2.0'

I'm trying to have Jekyll determine some related posts, using [`site.related_posts`](https://jekyllrb.com/docs/variables/#site-variables), but it is always `nil`. I have GSL installed, but it doesn't seem to matter whether I have it or not (apart from the time it takes to build the index).

I've tried to determine whether Classifier Reborn itself is the issue, using this piece of Ruby code:

    #!/usr/bin/env ruby
    require 'classifier-reborn'

    lsi = ClassifierReborn::LSI.new

    paths = [
      "_posts/2013-03-11-ipv6-on-raspbian.md",
      "_posts/2017-02-25-blah-blah-microservices-blah-blah.md",
      "_posts/2017-06-22-jbcnconf-and-voxxedlu.md",
      "_posts/2017-12-30-getting-started-with-zuul.md"
    ]

    paths.each do |path|
      puts "Reading file " << path
      File.open(path) do |file|
        post = ""
        file.each do |line|
          post << line
        end
        lsi.add_item(post)
      end
    end

    puts "Finding related stuff"

    related = lsi.find_related("In these days of microservices", 1)

    puts "Related text:"
    puts related

And the `related` variable indeed is filled with one related post. Except when I *only* classify the first file (`_posts/2013-03-11-ipv6-on-raspbian.md`) which isn't about microservices or anything related; in that case I get `Zero vectors can not be normalized (Vector::ZeroVectorError)`.

If you need to know anything else, please let me know!

**Comment by parkr** [comment]
Did you set `lsi: true` or use `—lsi`when invoking Jekyll?

**Comment by DirtyF** [comment]
closing this as it looks like it was just a typo on `site.related_posts`😄

**Comment by Ch4s3** [comment]
@mthmulders hope this helped.

@parkr I'll make note of this, and if it comes up again I'll handle it on my end.

**Comment by parkr** [comment]
No problem. Thanks, @Ch4s3! It’s be cool if Jekyll could warn you of cases like that.
