### ISSUE TITLE
[Front Matter] If No Title Given Use First H1

### ISSUE THREAD

**Issue by ketozhang** [jekyll/jekyll#6667]
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

Due to the versatility of Markdown sometimes I'd like to use my markdown documents for both web output to Jekyll and PDF output. Is it possible to consider the first H1 `#` as front matter `title` of the page or post?

## Redundant Title
```markdown
---
title: My Title
---

# My Title
## Section 1
```

## Not Redundant Requires Layout
```html
<h1 class="page-title">{{ page.title }}</h1>
```
```markdown
---
title: My Title
---

# Section 1
```

## Request
The following will output to Jekyll and any other format perfectly preserving original Markdown.
```html
<h1 class="page-title">{{ page.h1[0] }}</h1>
```
```markdown
# My Title
# Section 1
```

**Overall this is is a request for the `page.h1`, `page.h2`,... variable(s)**. Front matter is great but I hope Jekyll will go towards making front matter optional.

**Comment by crispgm** [comment]
There was a discussion #5476.

And Benbalter made this a plugin: https://github.com/benbalter/jekyll-titles-from-headings

**Comment by ketozhang** [comment]
Thank you @crispgm
