### ISSUE TITLE
Incompatibility between Jekyll 3.7 and I18n filter plugin

### ISSUE THREAD

**Issue by borisschapira** [jekyll/jekyll#6669]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] I am on (or have tested on) ***macOS*** 10.13.2
- [x] I was trying to build.

---

## My Reproduction Steps

It is very common in the Jekyll community to use the [I18nFilter plugin](https://github.com/borisschapira/jekyll-bugs/blob/master/_plugins/i18n_filter.rb) to translate dates from data provided in YAML.

Until Jekyll 3.6.2, the usage of this plugin was ok. Since Jekyll 3.7, there is a problem.
I have prepared a release that reproduces the problem: https://github.com/borisschapira/jekyll-bugs/releases/tag/jekyll-3.7-i18n-filter

```
"----"
"Loading the locale…"
["/path/to/jekyll/folder/_plugins/../_data/_locales/fr_FR.yml", "/path/to/jekyll/folder/_plugins/../_data/_locales/en_US.yml"]
"Available locales:"
[:en]
"----"
```

## The Output I Wanted

```
"----"
"Loading the locale…"
["/path/to/jekyll/folder/_plugins/../_data/_locales/fr_FR.yml", "/path/to/jekyll/folder/_plugins/../_data/_locales/en_US.yml"]
"Available locales:"
["fr_FR", "en_EN"]
"----"
```

**Comment by ashmaroli** [comment]
Related to changes in this commit: https://github.com/jekyll/jekyll/pull/6509/commits/25dd4cdb15dc4714924a51b29b22293441d7d369

@borisschapira With your experience from working with the `I18n` gem, will you be able to submit a patch for this issue..?

**Comment by borisschapira** [comment]
@ashmaroli Unfortunately no. I am not a Ruby developer and have already spent a few hours just to be able to isolate the bug and provide a reproductive case. To go further, I need help.

**Comment by ledermann** [comment]
@borisschapira To fix, add this to your i18n_filter.rb:

`I18n.config.available_locales = :fr_FR`

**Comment by borisschapira** [comment]
Thanks @ledermann, I'll do that.

Nevertheless, this separation of concerns feels wrong.
I know it works but it implies that I'll have to explicit every available locales where, before, the I18n module would guess them from the files. What if I add a new locale? I'll need to modify my plugin? 😭

**Comment by ashmaroli** [comment]
Hi @borisschapira :wave:
I've opened a PR to try and resolve this issue. Will you be able to test if that PR helps you..?
You can test by editing your Gemfile as below:
```diff
- gem "jekyll", "~> 3.7.2"
+ gem "jekyll", :git => "https://github.com/ashmaroli/jekyll.git", :branch => "drop-hardcoded-locale"
```
Thanks!

**Comment by borisschapira** [comment]
@ashmaroli Hi! I don't know what you did but it works! 👏

**Comment by ashmaroli** [comment]
> I don't know what you did but it works!

Awesome!
If you want to know what I did, [click here](https://github.com/jekyll/jekyll/pull/6791/files) :smiley:

**Comment by borisschapira** [comment]
Wonderful! Is there anything that I need to do now?

**Comment by ashmaroli** [comment]
> Is there anything that I need to do now?

Nope.
But, you can hope that the proposed fix gets approved by the maintainers here at Jekyll.. :smiley:
And update your Gemfile accordingly. (the branch on my fork will be deleted when the PR gets merged)
