### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 1977744311** [jekyll/jekyll#6673]
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I was trying to install.

## My Reproduction Steps

while installing appear：
```sh
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.
```

**Comment by DirtyF** [comment]
Here are some links to help you install Jekyll on macOS:

https://github.com/jekyll/jekyll/issues/6637#issuecomment-352253601
https://jekyllrb.com/docs/troubleshooting/#installation-problems

If you're still experiencing difficulties, please post a message in the related topic on our forum:
https://talk.jekyllrb.com/t/getting-started-osx-permission-issues/647

**Comment by 1977744311** [comment]
Thank you!I made it.
