### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by aprilmintacpineda** [jekyll/jekyll#6674]
`jekyll 3.0.1` gives me the following: `Deprecation: The 'plugins' configurationoption has been renamed to 'plugins_dir'. Please update your config file accordingly.` but https://jekyllrb.com/docs/plugins/ advices the use of method number 2.

**Comment by DirtyF** [comment]
Sorry for the confusion, with a Jekyll version older that `3.5` , you need to use `gems` instead of `plugins`.  I'll fix the docs. Remember to upgrade Jekyll from time to time 😄

**Comment by aprilmintacpineda** [comment]
@DirtyF sorry I was mistaken, I was using `jekyll 3.7.0`. Thanks.
