### ISSUE TITLE
Header on jekyllrb.com doesn't link to new release 3.7.0

### ISSUE THREAD

**Issue by Crunch09** [jekyll/jekyll#6675]
Hey,
just noticed that the header still shows and links to the previous release `3.6.2`. Locally everything works fine, i assume the docs site just has to be regenerated? Is there a way to start a rebuild without a commit?

<img width="1504" alt="screen shot 2018-01-06 at 11 23 28" src="https://user-images.githubusercontent.com/570608/34639234-1034d166-f2d4-11e7-8319-b7f526d053fe.png">

cc: @jekyll/documentation

**Comment by ashmaroli** [comment]
This is probably because Jekyll on GitHub Pages is still at `3.6.2`.. (IMO)

**Comment by DirtyF** [comment]
Site header currently displays `{{ jekyll.version }}` who might differ from github pages.

Latest version is stored in `latest_version.txt`, should we add it to config and use `site.version` instead?

**Comment by ashmaroli** [comment]
> should we add it to config and use `site.version` instead?

I :heart: that idea! :+1:

**Comment by DirtyF** [comment]
Fixed in #6676
