### ISSUE TITLE
Access to original document content post-render

### ISSUE THREAD

**Issue by FabianHenneke** [jekyll/jekyll#6682]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

While working on a plugin that sometimes need to trigger a second render pass for a document, I noticed that the content of `document.content` changes over the course of the rendering process. While it is first populated with the raw file content (without the front matter) in [convertible.rb](https://github.com/jekyll/jekyll/blob/cebcff14120f8365feaf4bbabfa5ebd50b5704c6/lib/jekyll/convertible.rb#L46), it is later overwritten with the output of the Markup renderer in [renderer.rb](https://github.com/jekyll/jekyll/blob/7895168cff9719f20ea9932c934ef4f199d130dd/lib/jekyll/renderer.rb#L81).

I would find it very useful to keep the original, almost raw file content around, for example in a member variable such as `document.orig_content` or `document.file_content`. If this sounds like a reasonable addition to people with more experience with the Jekyll rendering process, I would happily draft a PR.

**Comment by Crunch09** [comment]
Hey,
if i understand you correctly this should be possible with Hooks:
```ruby
require 'ostruct'

Jekyll::Hooks.register [:documents], :pre_render do |doc|
  @unparsed_docs ||= []
  @unparsed_docs.push OpenStruct.new(relative_path: doc.relative_path, unparsed_content: doc.content)
end

Jekyll::Hooks.register [:documents], :post_render do |doc|
  # find doc in the @unparsed_docs array and do stuff :)
end
```

Does this help you?

**Comment by ashmaroli** [comment]
@Crunch09 why are the hook-owners within an array..?
```ruby
Jekyll::Hooks.register [:documents], :pre_render do |doc|
```
instead of
```ruby
Jekyll::Hooks.register :documents, :pre_render do |doc|
```

**Comment by Crunch09** [comment]
No reason, i think i had `:pages` in there as well at first and then forgot to remove the brackets 😆 Either way should work.

**Comment by FabianHenneke** [comment]
Don't know why I didn't see that workaround. Yes, that should work well for my usecase, thanks!
