### ISSUE TITLE
New Jekyll Site loads Previous Jekyll Project

### ISSUE THREAD

**Issue by michaelcabus** [jekyll/jekyll#6683]
- [X ] I believe this to be a bug, not a question about using Jekyll.
- [ X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ X] I ran `jekyll doctor` to check my configuration
- [ X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [X ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [X ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

I created a new jekyll site locally

1.)  jekyll new [site name]

I served the site in the folder

2.) bundle exec jekyll serve

When I do this, it automatically populates the folder with the files from a previous jekyll project I was working on, basically the directory files with files from that project get put there.  I don't need this project so removed it from my computer, and still this happens.  I attempted to serve the site over a different port as well, same result.  I basically want to start a new jekyll site and discard the former site I created.  I checked the config file before serving and nothing references the old site, as far as I can tell.

## The Output I Wanted

I wanted a default new site so I can work on a new project

**Comment by DirtyF** [comment]
Without any other information, we might not be able to help here.

**Comment by pathawks** [comment]
Jekyll doesn’t have any secret cache where it keeps old versions of your site, if that’s what you’re asking about.

What folder does it populate? Were you trying to edit files inside the `_site/` directory?

**Comment by michaelcabus** [comment]
Hi
  Here are some screenshots that show what is happening
<img width="435" alt="screen shot 2018-01-07 at 7 45 16 pm" src="https://user-images.githubusercontent.com/6473266/34656166-d6dbb554-f3e3-11e7-908c-e99a5fc7f778.png">

Site folders before running bundle exec jekyll serve

Site folders after

<img width="552" alt="screen shot 2018-01-07 at 7 42 22 pm" src="https://user-images.githubusercontent.com/6473266/34656178-f4993e22-f3e3-11e7-9811-a7b1f9a73ddf.png">

That _site folder contains a site I was working on for another project.  I can't update those files, because every time I run the command the changes are erased and this returns!

**Comment by michaelcabus** [comment]
Okay, I resolved it! Somehow, when I created a new default index file in the root, the old site stopped coming back!  Weird, but I'm up and running.  Maybe more an FYI in case someone else has this happen!

**Comment by pathawks** [comment]
I don't understand at all: It looks like the before and after pictures are different folders.

At any rate, I'm glad you've got it working now.
