### ISSUE TITLE
Posts not generated when _posts folder is located within custom collections_dir

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll#6702]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Given the following folder setup:

```
├─ _collections
│  ├─ _books
│  ├─ _posts
│  └─ _recipes
└─ _config.yml
```
…and the following configuration:

```yams
collections_dir: _collections
collections:
  books:
    output: true
  posts:
    output: true
  recipes:
    output: true
```

No posts are generated. However, moving the `_posts` folder back into the source directory:

```
├─ _collections
│  ├─ _books
│  └─ _recipes
├─ _posts
└─ _config.yml
```

Generates posts as expected. I am showing representative folder structure and config here, different from my own. But I did the same (moving `_posts` into a custom collections folder and updating the config) after creating a new site (`jekyll new`), and the same behaviour is exhibited.

## The Output I Wanted

The following messages appears on the website:

> **Be sure to move posts into custom collections directory**
> If you specify a directory to store all your collections in the same place with `collections_dir: my_collections`, then you will need to move your `_posts` directory to `my_collections/_posts`.

This was the expected behaviour, however it would appear that the opposite is true.

**Comment by ashmaroli** [comment]
Your `collections_dir` value **should not start with an underscore (`_`)**

**Comment by paulrobertlloyd** [comment]
@ashmaroli Ah, changing this works! And yet, other collections in that folder are rendered as expected. Why the inconsistency? Should I not be able to use an underscore if I choose… much as I can for the other custom folder locations I have?

**Comment by ashmaroli** [comment]
The inconsistency is because Jekyll has separate "handlers" (Ruby Classes) to read "posts" and "other collections".
Its because of this separate "handling" that under default configurations, one can place `_posts` in any directory and its documents will be rendered without fail while "other collections" *should* be placed at the root of the source directory..

I'm afraid the behavior can't be changed all of a sudden since its been so from the very beginning..

**Comment by ashmaroli** [comment]
You're welcome to submit a PR to improve our documentation regarding this, if you want to..

**Comment by paulrobertlloyd** [comment]
Oh, of course! I have, at one time or another, moved `_posts` into sub-directories (not sure if I am right in thinking you can have multiple `_posts` folders in different directories… might be imagining that). Thanks for clarifying. Will mark this issue as closed.

However, if I may take this opportunity to grumble a little, the whole “posts are collections but not really” situation trips me up on numerous occasions. If I was to have one feature wish for Jekyll 4.0, it would for this to be properly, finally, resolved — the trials and tribulations of legacy software with a large user base not withstanding…! 🤞🏻

Thanks again! Will think about how/if the docs can be better worded in this regard.

**Comment by ashmaroli** [comment]
> not sure if I am right in thinking you can have multiple `_posts` folders in different directories… might be imagining that

Nope. You're not imagining it.. Its a valid and supported feature. `./movies/_posts/` along with `./music/_posts/` will process both directories and render them at urls `/movies/YYYY/MM/DD/title.html` and `/music/YYYY/MM/DD/title.html` consecutively.


> If I was to have one feature wish for Jekyll 4.0, it would for this to be properly, finally, resolved

I've got the ball rolling towards this in #6687

**Comment by derekgreer** [comment]
Does this work with github-pages?  I had my jekyll version working perfectly, but when I went to push up to github the collections didn't work.  I switched my local build over from the jekyll gem to the github-pages gem and saw the same behavior.  Anything that can be done besides moving the collections to the root?

**Comment by DirtyF** [comment]
[GitHub Pages](https://pages.github.com/versions/) hasn't updated to latest Jekyll version yet. Watch the [pages-gem](https://github.com/github/pages-gem) repository to be notified when they do.
