### ISSUE TITLE
GEM FilePermissionError

### ISSUE THREAD

**Issue by smileklvens** [jekyll/jekyll#6706]
:~ smileklvens$ sudo gem install jekyll
Password:
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.

macOS  10.13.2

**Comment by DirtyF** [comment]
Have you tried https://jekyllrb.com/docs/troubleshooting/#jekyll--mac-os-x-1011
