### ISSUE TITLE
Error while installing 

### ISSUE THREAD

**Issue by gemini1988** [jekyll/jekyll#6707]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I am on (or have tested on) ***macOS*** 10+ (10.13.2)
- [x] I was trying to install.

## My Reproduction Steps

gem install jekyll bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.

**Comment by pup** [comment]
Have you had a look at this document: https://jekyllrb.com/docs/troubleshooting/#jekyll--mac-os-x-1011?

**Comment by gemini1988** [comment]
Thanks, It worked.
