### ISSUE TITLE
 jekyll 3.7.0 | Error: undefined method `gsub' for #<Hash:0x00000005670110> 

### ISSUE THREAD

**Issue by KochuraniT** [jekyll/jekyll#6714]
I got an issue jekyll 3.7.0 | Error: undefined method `gsub' for #<Hash:0x00000005670110> on rake build please help me out?

**Comment by pathawks** [comment]
This is a duplicate of #6713. Please don’t open duplicate issues.

I am sorry you are having trouble. Please explain (preferably in that original issue) what you are trying to do, and how somebody else can recreate this error message.
