### ISSUE TITLE
Generator output being deleted by regenerate on --incremental

### ISSUE THREAD

**Issue by ibrado** [jekyll/jekyll#6722]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

---

- [x] There is (?) a broken Plugin API.
- [x] It was another bug.

I've been trying to avoid unnecessary reprocessing of files in one of my generator plugins, as it could take a while for large sites. However, Jekyll seems to remove `site.dest` files created by generators during a regenerate, even if it is running on `--incremental`,

## My Reproduction Steps

Using a `jekyll new .` site on 3.7.2 (also on 3.6.2), I added this to `_plugins`:

```ruby
module Jekyll
  module PoofPage
    class Generator < Jekyll::Generator
      def generate(site)
        file = File.join(site.dest, 'poof', 'index.html');
        if File.exist?(file)
          puts "#{file} exists, skipping..."
        else
          # Using PageWithoutAFile to avoid mtime error, but get the same results with Page
          poof = Jekyll::PageWithoutAFile.new(site, site.dest, 'poof', 'index.html')
          poof.data["layout"] = "page"
          poof.data["title"] = "Disappearing page"
          poof.data["permalink"] = "/poof/"
          poof.content = "This is a generated page\n"
          site.pages << poof
        end
      end
    end
  end
end
```

    $ bundle exec jekyll serve --incremental

The page is created and accessible at http://localhost:4000/poof/ . Then in another shell session,

    $ touch about.md

```
      Regenerating: 1 file(s) changed at 2018-01-26 23:33:15
                    about.md
/home/alex/poof/_site/poof/index.html exists, skipping...
                    ...done in 0.292139668 seconds.
```
Afterwards, the folder/file disappears (404; `_site/poof` is gone)

This behavior is not limited to Pages, but also Documents.

## The Output I Wanted

`_site/poof` and all its contents to remain, since this was an `--incremental` run.

**Comment by ashmaroli** [comment]
@ibrado To me, this looks like a bug in your "plugin" instead of Jekyll itself..

As the plugin is currently implemented, irrespective of whether `incremental: true` or not, the results are going to be the same because, the `site.pages` array will not have the "poof" `Page` object on the first regeneration because the generator is simply returning a `puts` call..
On the next regeneration, (`touch about.md` once more), you'll see that `poof/index.html` has returned.. This will continue in the same pattern for subsequent `touch` calls..

**Comment by ibrado** [comment]
Hmm... the point was to avoid have to reprocess/reparse source files in the actual plugin. I would have thought that the regeneration system would have caught (or could be told) that there was some new files to cache(?).

As it stands, all generator plugins cannot take advantage of `--incremental` but will have to regenerate everything, then..?

**Comment by ashmaroli** [comment]
Yes, that's a known issue: Plugins do not have access to the incremental metadata..
Ref: #6418

**Comment by ibrado** [comment]
Still seems a bit strange that existing generated files would disappear. I probably have the wrong idea about what `--incremental` is/does. Thanks for the info...

**Comment by ashmaroli** [comment]
> I probably have the wrong idea about what `--incremental` is/does.

How `--incremental` works can be summarized as following..
  - Check if a file path exists in metadata file
  - If path exists, then check the source-file's `mtime`..
  - If source-file cannot be physically accessed, or if the source file has been modified, then regenerate that file.

In your case, the `Page` object doesn't exist in the `site.pages` array (it gets reset on every regen) so Jekyll thinks, you deleted it in this pass-by.. so the `Cleaner` thinks its an `obsolete` file and is removed from the dest directory..
