### ISSUE TITLE
Access to Liquid "strict_variables" and "strict_filters" config options

### ISSUE THREAD

**Issue by begincalendar** [jekyll/jekyll#6725]
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to build.

## Feature Request

As people have commented [here](https://github.com/jekyll/jekyll/issues/3008#issuecomment-280391429), access to the Liquid **strict_variables** and **strict_filters** configuration options would be quite useful.

**I.e. It would be useful to be able to detect when a non-existent variable/filter has been specified in a template.**

For reference the Liquid options are outlined [here](https://github.com/Shopify/liquid#undefined-variables-and-filters).

**Comment by pathawks** [comment]
I would love to review a PR that introduced this! 👍🏼
