### ISSUE TITLE
Does Jekyll support Multimarkdown format for posts?

### ISSUE THREAD

**Issue by lolgear** [jekyll/jekyll#6734]
Does Jekyll supports Multimarkdown format for posts?
It would be nice if Jekyll has support for this format.

**Comment by pathawks** [comment]
Jekyll supports MarkDown out of the box, and many other formats are [supported via plugins](https://jekyllrb.com/docs/plugins/)

**Comment by DirtyF** [comment]
@lolgear I don't know of a Jekyll plugin for MultiMarkdown, but there has been [prior effort for this](https://github.com/jekyll/jekyll/pull/379), if someone want to develop a plugin.
