### ISSUE TITLE
Problem with the SSL CA cert while testing the website locally using github-pages.

### ISSUE THREAD

**Issue by sahilarora535** [jekyll/jekyll#6758]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

My `Gemfile` looks like this:
```
source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
```
1. `bundle update`
2. `bundle exec jekyll serve`

Apart from that, I also tried `bundle exec jekyll build`. All of them give the same error.

## The Output I Wanted

I wanted my site to build or server locally, none of which is happening correctly as mentioned above.

Here is what I get instead when I run `bundle exec jekyll server`:

```
Configuration file: /home/sahil/ws/kamandprompt.github.io/_config.yml
            Source: /home/sahil/ws/kamandprompt.github.io
       Destination: /home/sahil/ws/kamandprompt.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
      Remote Theme: Using theme mmistakes/minimal-mistakes
jekyll 3.6.2 | Error:  Problem with the SSL CA cert (path? access rights?)
```
When I run `bundle exec jekyll doctor`, I get the same error:

```
Configuration file: /home/sahil/ws/kamandprompt.github.io/_config.yml
      Remote Theme: Using theme mmistakes/minimal-mistakes
jekyll 3.6.2 | Error:  Problem with the SSL CA cert (path? access rights?)
```

Here is the link to the issue I filed on the [`pages-gem`](https://github.com/github/pages-gem) repository: <https://github.com/github/pages-gem/issues/529>

**Comment by pathawks** [comment]
Possibly related: #3985 #4413

**Comment by mmistakes** [comment]
@DirtyF That's correct. As far as I can tell the problem isn't Jekyll or the remote theme gem, but getting libcurl to install properly.

**Comment by sahilarora535** [comment]
@DirtyF @mmistakes I tried some debugging here. I created a new repository using `jekyll new`, and converted it to `github-pages` by deleting other gems and installing the `github-pages` gem:
```
gem "github-pages", group: :jekyll_plugins
```

In this new repository, the `jekyll serve` command worked, but not in my original repository as I have reported in the issue.

**Comment by mmistakes** [comment]
@sahilarora535 It works with `jekyll new` because that is using `theme: minima`. In your first test you were using a `remote_theme`, which pulls down the theme files as a `.zip` and extracts them.

libcurl is used to download those files, and there's some sort of certificate issue with that and how the remote theme gem grabs those files. Seems like you have libcurl install properly but are getting bit by an invalid SSL certificate.

I've had the same problem but couldn't fix it. Maybe this [info here will help you](https://curl.haxx.se/docs/sslcerts.html).

**Comment by sahilarora535** [comment]
Aah I would have never been able to figure out the error was related to `curl`. I have apparently solved it by installing `libcurl4-openssl-dev` using `apt`:
```
sudo apt install libcurl4-openssl-dev
```
Now the site builds locally. Though I am getting this Github API error:
```
GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
```
I think this can be fixed easily.

Thanks a lot, closing the issue! 😃

**Comment by sahilarora535** [comment]
@mmistakes You can probably try this fix I mentioned above if this may work on the error mentioned by you here: https://github.com/benbalter/jekyll-remote-theme/issues/9

**Comment by mmistakes** [comment]
Thanks @sahilarora535, I've tried everything I can think of. Unfortunately the version of Windows I'm using doesn't have `apt` to easily install `curl` and `libcurl` with.
