### ISSUE TITLE
Release 3.8.0

### ISSUE THREAD

**Issue by oe** [jekyll/jekyll#6783]
👋 It's time for a new minor release! We have some pretty important performance improvements, so let's get this one out there.

- [x] #6610 
- [x] #6726
- [x] #5195
- [x] #6597
- [x] #6681
- [x] #6724
- [x] #6736
- [x] #6767 
- [x] #6773 
- [x] #6777
- [x] #6819
- [x] Write a release post
- [ ] Release the gem

If anyone has any more suggestions as for what to land in this release, please suggest them here! ❤️ 

Fix #6845 #6842

**Comment by ashmaroli** [comment]
### Would love these.. (High interest):

- [ ] #5195 
- [ ] #6736
- [ ] #6747 
- [ ] #6763 
- [ ] #6767 
- [ ] #6777 

### Somewhat inclined to.. (Medium interest) :

- #6735 
- #6740 
- #6741 
- #6742 
- #6755

**Comment by oe** [comment]
released!
