### ISSUE TITLE
Clarify Plugin Syntax / Missing docs?

### ISSUE THREAD

**Issue by HeinrichHartmann** [jekyll/jekyll#6793]
Hi all,

I am having trouble writing my first Jekyll plugin, and I wonder if this is a gap in the documentation that should be addressed. The [plugin documentation](https://github.com/jekyll/jekyll/blob/master/docs/_docs/plugins.md) mentions this syntax for adding new tags, but does not explain any of the arguments:
```
    def initialize(tag_name, text, tokens)
      super
      @text = text
    end
```
- What is tag_name?
- What is text?
- What is tokens?

I would expect at least a word or two about the type and the intended contents.
Is this written down somewhere else?

PS: Thanks for making this! You guys rock.

**Comment by DirtyF** [comment]
Should we link to https://github.com/Shopify/liquid/wiki/Liquid-for-Programmers#create-your-own-tags?

**Comment by ashmaroli** [comment]
> Should we link to ..?

Yep.. IMO, we should. That one line will take us off the hook considerably..

**Comment by HeinrichHartmann** [comment]
Ahh this is what I was looking for. Probably a link at the top of the section like this?

https://github.com/jekyll/jekyll/pull/6794
