### ISSUE TITLE
Include_relative liquid tag inside collection doc doesnt work

### ISSUE THREAD

**Issue by hosnas** [jekyll/jekyll#6816]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration

---
- [X] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

---

- [x] I was trying to build.

## My Reproduction Steps

I'm trying to use include_relative liquid tag inside one of my collections document but it is giving me an error:
`Liquid Exception: Could not locate the included file` 
I found that it happens only when I put all my collections inside a `collection_dir` folder  .  when `collection_dir` is not defined, the problem doesn't occur.

I have also created this repository for reference:
https://github.com/hosnas/jekyll-test-1
the document is in `collections/col1` folder named `index.md` and the included file is `fa.md` beside it.
## The Output I Wanted

It should normally give me no error and `include_relative` liquid tag should work as expected.

**Comment by ashmaroli** [comment]
This seems like a legit bug to me.
I hadn't considered this at all when I refactored the `collections_dir` feature in #6685 

Thank you @hosnas for reporting this and including a test-repo.
