### ISSUE TITLE
Rendering MediaWiki Files?

### ISSUE THREAD

**Issue by mathmare** [jekyll/jekyll#6817]
Hey guys, I was wondering if it was possible for Jekyll to render MediaWiki files like the same way it renders markdown files? Both with 'jekyll serve' and GitHub pages...

Thanks!

- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

---

## My Reproduction Steps

N/A

## The Output I Wanted

N/A

**Comment by pathawks** [comment]
In order to support MediaWiki files, we would need a `Converter` for Creole, preferably written in Ruby.

I do not know of any Jekyll plugins that currently support this, but I can see the utility :+1:

**Comment by mathmare** [comment]
@pathawks you know what, I'll just use pandoc to convert mediawiki files to markdown, thanks for the #protip though :-)

**Comment by pathawks** [comment]
That’s probably the best solution 👍🏼
