### ISSUE TITLE
Excluding certain files from "site.pages" without needing front matter/conditionals?

### ISSUE THREAD

**Issue by JarrettBillingsley** [jekyll/jekyll#6825]
This is not really a bug, and I don't know if it's a feature request, because I don't know if this can already be done. Sorry.

Trying to set up some sub-pages in Jekyll and auto-generate navigation from the `site.pages` variable. But for some reason, the generated `assets/main.css` file is in this list. I don't really know why, and I don't know where I would start looking to prevent this from happening.

I've found numerous blog posts where they say to put a custom front matter variable (like `exclude_from_nav: true`) and then check for that with a conditional, but that feels a little awkward to exclude a single file, when I will be using this list in multiple places.

**Comment by DirtyF** [comment]
have you look at other [site variables](https://jekyllrb.com/docs/variables/#site-variables) like `site.html_pages`?

**Comment by JarrettBillingsley** [comment]
...no I did not see those, thanks. 😄

**Comment by JarrettBillingsley** [comment]
Also, I'm trying to authenticate on that forum with my GitHub account but it doesn't seem to work. It says "Authentication is complete. Click here to continue." but clicking there doesn't lead me to a logged-in page.

**Comment by DirtyF** [comment]
Don't know what to say to you, I just log out and log in and I'm not experiencing this issue.
