### ISSUE TITLE
Partially output a collection

### ISSUE THREAD

**Issue by cameronmcefee** [jekyll/jekyll#6831]
Hello! In a collection we can specify:

```
collections:
  my_collection:
    output: true
```

This will cause all of the documents in the collection to generate pages, however, I'd like to be able to selectively enable generation. Anyone have a suggestion for how to do that, that isn't a post-build script that deletes the ones I don't want? I'm open to a plugin option, if that is a solution (I don't know enough about the lifecycle to know if this is viable). `published: false` is not an option, because I still need the data to be accessible.

In context, I have an "events" collection which represents the events our company sponsors/sends speakers too/hosts/etc. For all the 3rd party events, I just want the collection to be data objects, but for the events we host, I'd like those to output their own pages.

**Comment by pathawks** [comment]
It seems like splitting the collection into two collections would be a natural way to organize things. One would be output and the other not.

I don’t know if Liquid has a simple way to union two collections to iterate through both together.

**Comment by cameronmcefee** [comment]
Cool, I figured that'd probably be the case. Liquid can concat arrays now so it's possible that way.

**Comment by pathawks** [comment]
If there were some common use cases here, I could see hierarchical collections to fill this role.
