### ISSUE TITLE
jekyll serve  err

### ISSUE THREAD

**Issue by feixia5712** [jekyll/jekyll#6835]
lxg@bw:~/myblog$ jekyll serve
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/jekyll-3.7.3/lib/jekyll/plugin_manager.rb:48:in `require_from_bundler'
	from /var/lib/gems/2.3.0/gems/jekyll-3.7.3/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:22:in `load'
	from /usr/local/bin/jekyll:22:in `<main>'

**Comment by ashmaroli** [comment]
You need to install the `bundler` gem.
```
gem install bundler
```

**Comment by feixia5712** [comment]
thanks
