### ISSUE TITLE
Jekyll hosted on gitlab doesn't link to relative URL in assets

### ISSUE THREAD

**Issue by Keesromkes** [jekyll/jekyll#6836]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***macOS*** 10+

---

- [x] I was trying to build.

## My Reproduction Steps

1. Ran CI script to build in Gitlab pages (https://wtdib.gitlab.io/curated-child-theme/ as the result)
2. Everything looks to work, except the SVG in the footer, they won't load

        title: WTDIB - Wordpress theme documentation
        email: kees@wattedoeninberlijn.nl
        description: >- # this means to ignore newlines until "baseurl:"
          Gotta love the description of this page, but it's not that hard to be honest.
        baseurl: "/curated-child-theme" # the subpath of your site, e.g. /blog
        url: "http://wtdib.gitlab.io" # the base hostname & protocol for your site, e.g. http://example.com
        twitter_username: keesromkes
        
        # Build settings
        markdown: kramdown
        theme: minima
        plugins:
          - jekyll-feed

3. Here's the .gitlab-ci.yml I'm using:

        image: ruby:2.3
        
        variables:
          JEKYLL_ENV: production
        
        before_script:
           - BUNDLE_GEMFILE="docsite/Gemfile" bundle install
        
        pages:
          stage: deploy
          script:
          - BUNDLE_GEMFILE="docsite/Gemfile" bundle exec jekyll build -s ./docsite/ -d public
          artifacts:
            paths:
            - public
          only:
          - master

## The Output I Wanted

SVG should be shown, as does the CSS that loads fine.

**Comment by pathawks** [comment]
I viewed the page at the link you provided. Everything looks fine. The SVG icons in the footer appear as expected.

Please reopen if you can provide specific details explaining how this is a bug in Jekyll.

**Comment by ashmaroli** [comment]
> The SVG icons in the footer appear as expected.

I concur

![wtdib gitlab io_curated-child-theme_](https://user-images.githubusercontent.com/12479464/37214359-c75668c8-23da-11e8-81bb-2190963ed0fe.png)
