### ISSUE TITLE
unable to install it on windows behind proxy authentication

### ISSUE THREAD

**Issue by prateekrajgautam** [jekyll/jekyll#6847]
this is the outpit of CMD window
`
D:\RAJX>gem update --system -p http://edcguest:edcguest@172.31.102.29:3128
Latest version already installed. Done.

D:\RAJX>gem install jekyll -p http://edcguest:edcguest@172.31.102.29:3128
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20180314-5660-8g241h.rb extconf.rb
creating Makefile

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
generating ruby_http_parser-x64-mingw32.def
make: *** No rule to make target '/C/Ruby25-x64/include/ruby-2.5.0/ruby.h', needed by 'ruby_http_parser.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/http_parser.rb-0.6.0/gem_make.out

D:\RAJX>`

**Comment by ashmaroli** [comment]
@prateekrajgautam This is an issue with your Ruby installation..
You may not have installed the devtools necessary to install gems with native extensions..
Refer to https://github.com/oneclick/rubyinstaller2#using-the-installer-on-a-target-system for more info.., particularly, the bullet-point about `ridk install`

**Comment by ashmaroli** [comment]
closing as this is not related to Jekyll
