### ISSUE TITLE
tags and categories

### ISSUE THREAD

**Issue by steelman** [jekyll/jekyll#6853]
As far as I read the documentation I hadn't found an answer to a very simple question: what is the difference between tags and categories? A post can have multiple categories as it can have multiple tags. Please add a paragraph or two of comparison. Personally, I'd expect to find the information here https://jekyllrb.com/docs/posts/#displaying-post-categories-or-tags

**Comment by BerkhanBerkdemir** [comment]
I just Google it and I found this useful information. I hope, it will explain the situation.

> **Categories** are meant for broad grouping of your posts. Think of these as general topics or the table of contents for your site. Categories are there to help identify what your blog is really about. It is to assist readers finding the right type of content on your site. Categories are hierarchical, so you can sub-categories.

> **Tags** are meant to describe specific details of your posts. Think of these as your site’s index words. They are the micro-data that you can use to micro-categorize your content. Tags are not hierarchical.

[Source link](http://www.wpbeginner.com/beginners-guide/categories-vs-tags-seo-best-practices-which-one-is-better/)

**Comment by BerkhanBerkdemir** [comment]
@DirtyF 
I think, newbie users know the difference between tags and categories. Could we add a chart for this difference? Like,

| Tag | Category  |
| --- | --- |
| Not hierarchical | Has sub-categories |
| Shows details your content | Keeps contents regular |

**Comment by DirtyF** [comment]
Of course but as these are not specifics to Jekyll, I don't really think it's necessarily our job to do so. 
We don't explain what is a blog or a URL either, and it should be noted Jekyll is not particularly designed for newbies (even if it's a good tool for learning purpose).

**Comment by BerkhanBerkdemir** [comment]
Yes, @DirtyF is right about that, but I think, it can be scary

>  ... and it should be noted Jekyll is not particularly designed for newbies ...

**Comment by steelman** [comment]
I already have some knowledge and expectations regarding blogs, tags and categories (I definitely wouldn't call myself a [newbie](https://github.com/steelman/org-mode/commit/f59353cde5791ca88e4bc508d83483c39dbd8fe7)). However, I am also aware of slight differences between software packages which implement them. It'd be nice to know, what exactly Jekyll does.

**Comment by DirtyF** [comment]
Jekyll does not do a lot by default.[ No magic](https://jekyllrb.com/philosophy.html). Depending on your permalink template it will just add the categories to the permalink.

Jekyll does not handle pagination for categories out-of-the-box, you have to use a plugin like [jekyll-paginaate-v2](https://github.com/sverrirs/jekyll-paginate-v2)

To display tags or categories, you'll have to write layouts: [https://jekyllrb.com/docs/posts/#displaying-post-categories-or-tags](https://jekyllrb.com/docs/posts/#displaying-post-categories-or-tags)

Does it answer your question @steelman ?

**Comment by steelman** [comment]
I feel it almost does. One more question (the answer might find its way into the documentation). Are categories and tags technically the same and the distinction in Jekyll is only to enable implementation of both hierarchical (categories) and flat (tags) structures?

TIA

**Comment by DirtyF** [comment]
The only difference is that Jekyll will affect categories automatically if you sort your posts in different folders, whether as for tags you have to specify the tags in your frontmatter.

see https://jekyllrb.com/docs/frontmatter/#predefined-variables-for-posts

**Comment by steelman** [comment]
Thanks a lot. I am sure, that writing down these few pieces of information in this [paragraph](https://jekyllrb.com/docs/posts/#displaying-post-categories-or-tags) will help newcomers a lot.

Thank you very much again.

**Comment by DirtyF** [comment]
@steelman I'll be happy to review a documentation addition regarding what we discussed here. It's always better if users that lacks for information fix the docs themselves.
