### ISSUE TITLE
Passing parameters to include-by-variable across multiple lines

### ISSUE THREAD

**Issue by sbliven** [jekyll/jekyll#6857]
- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
    - github-pages (179), jekyll (3.6.2)
- [X] I ran `jekyll doctor` to check my configuration
- [X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [X] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

When including a file based on a variable name (`{% include {{file}} ... %}`), only variables from the first line are passed to the partial. Anything after the first newline is ignored. This is weird, because newlines are allowed if the filename is included explicitly.

### Minimal example

**test_lvl1.html:**
```
---
---
{% capture nextlevel %}test_lvl2.html{% endcapture %}
<style>div {border: solid 1px black; margin:1em;}</style>
<div id="lvl1">
    <h4>Level 1</h4>
    {% include {{nextlevel}} a="level 1"
       b="level 1" %}
</div>
```

**_includes/test_lvl2.html:**
```
<div id="lvl2">
    <h4>Level 2</h4>
    <blockquote>{{include|inspect}}</blockquote>
</div>
```

One would expect that both `include.a` and `include.b` would be available in the partial, but only the first one is.

**output**:
```
<style>div {border: solid 1px black; margin:1em;}</style>
<div id="lvl1">
    <h4>Level 1</h4>
    <div id="lvl3">
    <h4>Level 2</h4>
    <blockquote>{&quot;a&quot;=&gt;&quot;level 1&quot;}</blockquote>
</div>
</div>
```
<img width="365" alt="screen shot 2018-03-17 at 15 55 35" src="https://user-images.githubusercontent.com/595872/37556830-b16d0c34-29fb-11e8-93e4-6950bdfe332f.png">

## The Output I Wanted
The environment should have also included `b`.

```
<style>div {border: solid 1px black; margin:1em;}</style>
<div id="lvl1">
    <h4>Level 1</h4>
    <div id="lvl3">
    <h4>Level 2</h4>
    <blockquote>{&quot;a&quot;=&gt;&quot;level 1&quot;, &quot;b&quot;=&gt;&quot;level 1&quot;}</blockquote>
</div>
</div>
```

_Note: Issue first filed against liquid as https://github.com/Shopify/liquid/issues/994_

**Comment by ashmaroli** [comment]
Thank you for reporting this @sbliven.
Its definitely a bug in our code since the *`include.b`* in your example renders fine if you were to use the file path directly..
```diff
- {% include {{nextlevel}} a="level 1"
+ {% include test_lvl2.html a="level 1"
       b="level 1" %}
```
