### ISSUE TITLE
I am unable to install Ruby 2.2.5 or above. Each time i try to install ruby with "sudo yum install ruby", Ruby 2.0 is getting installed and when i give "sudo gem install jekyll", it is saying "public_suffix requires Ruby version >= 2.1."

### ISSUE THREAD

**Issue by sasi-infy** [jekyll/jekyll#6862]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

**Comment by oe** [comment]
As evident by your report, your package repositories contain Ruby 2.0, and Jekyll requires 2.2.5 or above. Install Ruby using [RVM](http://rvm.io/) or other similar version managers.
