### ISSUE TITLE
Feed-Generator doesn't generate etags

### ISSUE THREAD

**Issue by buhtz** [jekyll/jekyll#6866]
I tried the feed http://blog.jabref.org/feed.xml . The data comming back tells me that __jekyll__ (3.6.2) was the generator of that feed. But the feed doesn't contain an etag.

There is only an `updated` attribute which is a fallback but not a solution. A modern feed should offer an `etag`.

**Comment by oe** [comment]
This is an issue for https://github.com/jekyll/jekyll-feed. Closing as it's not related to Jekyll Core. Please open an issue in the linked repository instead!

**Comment by buhtz** [comment]
I am not sure where the etag comes from. I used python library `feedparser` which comes back with a complex data structure holding this informations. I don't think that `etag` is part of the HTTP-protocol. This is definitly RSS/Atom-specific. Please see what `feedparser` itself write about `etag`: https://pythonhosted.org/feedparser/http-etag.html
