### ISSUE TITLE
The passage is still exist when I delete the passage on my localhost！

### ISSUE THREAD

**Issue by HNU-Microsoft-Douzi** [jekyll/jekyll#6872]
When I delete one blog in _posts, I push this change to github.
But When I login my website , the delete one is still exist there ,I don't know where the question is.
And I  noticed that jekyll's blog-directory has only ten?

**Comment by Crunch09** [comment]
Hey,
it's difficult to understand what your issue is. Is your jekyll website public? If so could you please provide a link to the code and mention what the file is that you deleted?

**Comment by pathawks** [comment]
Is GitHub pages building your site? It is possible that there is an error preventing GHP from building the page, and it is still serving an old version.
