### ISSUE TITLE
Jekyll ignores posts which are dated in the future

### ISSUE THREAD

**Issue by mr-infty** [jekyll/jekyll#6873]
Not sure whether this is a bug or a feature, but the following is certainly a confusing behaviour of jekyll: if the `date` field of a post is dated in the future, it is ignored by `jekyll build`.

**Comment by DirtyF** [comment]
It's a feature.

Use `--future` or `future: true` if you want to display future posts. See https://jekyllrb.com/docs/configuration/#build-command-options
