### ISSUE TITLE
missing jekyll-docs v3.7.3

### ISSUE THREAD

**Issue by superyyrrzz** [jekyll/jekyll#6876]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps
jekyll-docs v3.7.3 is missing
```
C:\git\jekyll-test\myblog>jekyll docs
You must install the 'jekyll-docs' gem version = 3.7.3 to use the 'jekyll docs' command.

C:\git\jekyll-test\myblog>gem install jekyll-docs -v 3.7.3
ERROR:  Could not find a valid gem 'jekyll-docs' (= 3.7.3) in any repository
ERROR:  Possible alternatives: jekyll-docs
```

## The Output I Wanted
jekyll-docs v3.7.3 install succeeds.

**Comment by DirtyF** [comment]
@superyyrrzz Thanks for the reminder, jekyll-docs 3.7.3 is now available through rubygems: https://rubygems.org/gems/jekyll-docs/versions/3.7.3
