### ISSUE TITLE
Jekyll color_to_rgb filter does not work

### ISSUE THREAD

**Issue by andrewleyva** [jekyll/jekyll#6877]
Using Jekyll 3.7.2

color_to_rgb filter does not work.

{{ '#7ab55c' | color_to_rgb }}
https://help.shopify.com/themes/liquid/filters/color-filters#color_to_rgb

**Comment by ashmaroli** [comment]
This filter is available only for stores at Shopify. Jekyll knows nothing about this filter out-of-the-box
