### ISSUE TITLE
Can't preview local file when name is Chinese charset with 404 warning.

### ISSUE THREAD

**Issue by sanchi3** [jekyll/jekyll#6883]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [x] It was another bug.

## My Reproduction Steps

I'd try to preview a markdown file with command `jekyll s`, and there is a problem with Chinese character coding. 

When run that command it generated a html file in `_site` folder with Chinese name, it auto generated jump url in `<script type="application/ld+json">
{"url":"http://localhost:23333/jekyll/update/2018/03/27/2-%E6%A6%82%E5%BF%B5-%E5%B8%A7%E7%8E%87%E6%AF%94%E7%89%B9%E7%8E%87%E6%96%87%E4%BB%B6%E5%A4%A7%E5%B0%8F.html","headline":"[2][概念] FFmpeg比特率帧率文件大小","dateModified":"2018-03-27T12:01:18+08:00","datePublished":"2018-03-27T12:01:18+08:00","mainEntityOfPage":{"@type":"WebPage","@id":"http://localhost:23333/jekyll/update/2018/03/27/2-%E6%A6%82%E5%BF%B5-%E5%B8%A7%E7%8E%87%E6%AF%94%E7%89%B9%E7%8E%87%E6%96%87%E4%BB%B6%E5%A4%A7%E5%B0%8F.html"},"description":"帧率（Frame rate/frequency）","@type":"BlogPosting","@context":"http://schema.org"}</script>` tag with Urlencode. 

I don't know what it contains but cannot preview with localhost with `404 Page not found` but runs well on github-pages. 

When I changed file name to English, it previewed well. So I am sure it's a charset issue.

But it's confused that only this Chinese name couldn't preview and other was well. So I submit this issues, if this isn't a bug please close it and I'm sorry to bothering you.

[This is the github-pages which cannot preview local.](https://sanchi3.github.io/jekyll/update/2018/03/27/2-%E6%A6%82%E5%BF%B5-%E5%B8%A7%E7%8E%87%E6%AF%94%E7%89%B9%E7%8E%87%E6%96%87%E4%BB%B6%E5%A4%A7%E5%B0%8F.html)

**Comment by ashmaroli** [comment]
@sanchi3 Sorry, I could not reproduce this bug on my local Windows system (yes, with your site's repo.). It could be a local cache issue at your end. Please clear your browser cache and try again or simply do a hard refresh with <kbd>Ctrl</kbd> + <kbd>F5</kbd>

**Comment by crispgm** [comment]
I think it's a known issue and saw it one year before maybe. And it fails on WEBrick.

@sanchi3 之前看到过这个bug Windows下Jekyll的底层库对中文支持有问题

**Comment by ashmaroli** [comment]
@crispgm I was able to preview the rendered post fine on my system (Windows 7, Ruby 2.3) using sanchi's  `Gemfile.lock`

**Comment by sanchi3** [comment]
@ashmaroli Yes I tried to clear browser cache or hard refresh, neither chrome nor IE cannot preview it. I cloned my github repo and tried agin, all of it cannot solve it. So maybe my local environment has problems. Do you need some information else I can provide?

**Comment by ashmaroli** [comment]
> Do you need some information else I can provide?

Since I can't reproduce this at my end, I won't be able to help you any further. Sorry!
I don't know if changes between our Windows versions (I'm on Windows 7) has anything to do with this.., but here's the full screenshot of your post on Google Chrome:

![localhost_23333_jekyll_update_2018_03_27_2- e6 a6 82 e5 bf b5- e5 b8 a7 e7 8e 87 e6 af 94 e7 89 b9 e7 8e 87 e6 96 87 e4 bb b6 e5 a4 a7 e5 b0 8f html](https://user-images.githubusercontent.com/12479464/38073342-38c4a836-3348-11e8-8534-85d7a96de22a.png)

**Comment by sanchi3** [comment]
😂😂😂
My environment: `Windows 10 home` and `ruby 2.5.0p0 (2017-12-25 revision 61468) [x64-mingw32]`
It's confused that github-pages is preview well but only one file can't preview local.
I'll close this issue and check my local configs. Thank you.
