### ISSUE TITLE
Auto redirect to "http://example.com/en/" when input "http://example.com". How to do this ?

### ISSUE THREAD

**Issue by linhnh123** [jekyll/jekyll#6890]
Hello guys,
As title, when I type "http://example.com", I want to auto redirect to "http://example.com/en/". Thanks very much.

**Comment by DirtyF** [comment]
You can either use the [`jekyll-redirect-from` plugin](https://github.com/jekyll/jekyll-redirect-from)

1. Install the plugin
2. Modify the default index to use a `layout:null` if you don't need to display anything
3. In your `en/index.md` file add the following Front Matter:

```
redirect_from:
  - /
```

Now when you build your site, `_site/redirects.json` should contain an entry with the redirection.

Alternately your could set this redirection on your server or [through a header on Netlify](https://www.netlify.com/docs/redirects/)

**Comment by linhnh123** [comment]
Thank you @DirtyF , but this plugin will create a meta tag refresh, I think it's not good for SEO. Any other way to redirect without `.htaccess` ?
