### ISSUE TITLE
Jekyll install error: No Gem permission

### ISSUE THREAD

**Issue by PJOssenbruggen** [jekyll/jekyll#6892]
I hope that my request format for help is okay. **I cannot install jekyll.**

PJO:~ PJO$ brew install ruby
Warning: ruby 2.5.1 is already installed
PJO:~ PJO$ gem install jekyll bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.

PJO:~ PJO$ jekyll doctor
-bash: jekyll: command not found
PJO:~ PJO$ 

 I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- I ran `jekyll doctor` to check my configuration
-I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---
I am on (or have tested on) ***macOS*** 10+
---

I was trying to install. Jekyll and then use GitHub pages with a "Tactile" theme.

## My Reproduction Steps

I cannot install Jekyll on my MacOS version 10.13.4.

## The Output I Wanted

Use GitHub pages with a "Tactile" theme.

Thanks,
Paul

**Comment by DirtyF** [comment]
See https://jekyllrb.com/docs/troubleshooting/#no-sudo

**Comment by PJOssenbruggen** [comment]
Thanks DirtyF,

I am sorry that I did not see your response 10 hours ago. Anyway, I have learned much from searching the web. #6800 was very instructive. 

I am new at ruby, etc. and seeking help. Please look at #6893. I am close to establishing a site but need some direction.

Thanks
Paul
