### ISSUE TITLE
Multiple-pagination works on local server but not on GitHub pages.

### ISSUE THREAD

**Issue by techcentaur** [jekyll/jekyll#6895]
I have been developing a minimalistic theme for bloggers on Jekyll as a static-site generator so that anyone can build multiple blog system making use of the multiple-pagination gem in Jekyll.

It works on my local server and runs smoothly which is the way it should but it doesn't work when I upload it to Github pages.

After talking to many people and going through the official documentation I realized that there is no way to do this and I think Github pages should have this feature. What do you think about it? Is there any way to solve this problem? 

Here is my repository if in need - [link](https://github.com/techcentaur/space)

**Comment by ashmaroli** [comment]
Custom themes and custom plugin `jekyll-paginate-multiple` are [not whitelisted](https://pages.github.com/versions/) for use on GitHub Pages
