### ISSUE TITLE
Occasional errors when using livereload flag

### ISSUE THREAD

**Issue by bdielman** [jekyll/jekyll#6899]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I was trying to build.

## My Reproduction Steps

- Upgrade to Jekyll 3.7.3
- Make necessary changes to `_config.yml`
- Run `bundle exec jekyll serve --livereload`

**Note:**  Using rbenv to manage Ruby versions, this repo is on 2.4.1

## The Output I Wanted

Expecting to see this when I make changes to the source files:

`Regenerating: 1 file(s) changed at 2018-04-03 21:56:36`

## The Output I'm Seeing

I do see the above, but regularly get the following errors upon saving files:

`ERROR Errno::EPROTOTYPE: Protocol wrong type for socket`
`ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:18`

**Comment by ashmaroli** [comment]
@bdielman Hi can you run the server with the `--trace` switch and post the resulting output so that we can get some insight into where the exception could be originating from..?
Thanks.

**Comment by bdielman** [comment]
Only seeing this in the output:

```sh
ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:17 
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
```

**Comment by bdielman** [comment]
For the other error:

```sh
ERROR Errno::EPROTOTYPE: Protocol wrong type for socket
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpresponse.rb:465:in `write'
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpresponse.rb:465:in `<<'
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpresponse.rb:465:in `_write_data'
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpresponse.rb:458:in `_send_file'
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpresponse.rb:413:in `send_body_io'
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpresponse.rb:305:in `send_body'
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpresponse.rb:209:in `send_response'
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:112:in `run'
	/.rbenv/versions/2.4.1/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
```

**Comment by ashmaroli** [comment]
I've not encountered these exceptions at my end (yet) and your backtrace doesn't seem to lead to any of the classes / files in Jekyll.., so not sure what and how to fix..

/cc @awood Would be great if you could throw some light on this.. Thanks.

**Comment by awood** [comment]
Whoa.  I don't know what's going on here.
@bdielman: 
* does everything work normally without `--livereload`?  I'm guessing yes, but I just want to verify.
* does Jekyll actually work at all with `--livereload`?  From your description it sounds like it does work  but prints out those error messages over and over.

I think the issue might be a WEBrick bug since it looks like [rails hit the same issue](https://github.com/rails/rails/issues/18822).  That being said, a little bit of searching hasn't yielded many other mentions of either the "connection reset" or the "wrong type for socket" issues, so maybe it's an error in how WEBrick is being used.

**Comment by bdielman** [comment]
@ashmaroli @awood - Thanks for looking into this!

**Comment by bdielman** [comment]
Upgrading Ruby to 2.5.1 seems to have fixed this issue I'm closing the issue.
