### ISSUE TITLE
Unable to import .css files using sass

### ISSUE THREAD

**Issue by marceloverdijk** [jekyll/jekyll#6903]
I'm trying to import highlight css from my main `site.scss` file like:

@import "highlight-9.12.0/default"; -- there is a `/_sass/highlight-9.12.0/default.css` file

but `jekyll serve` fails with:

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/site.scss':
                    File to import not found or unreadable: highlight-9.12.0/default. Load path: /Users/marceloverdijk/my-site/_sass on line 20
```

I noticed https://github.com/jekyll/jekyll/issues/4527 but don't understand if it is solved or not.
Should importing without extension be supported?

I'm using Jekyll 3.7.3 and Sass 3.5.6 (deploying on GitHub pages).

**Comment by ashmaroli** [comment]
Does it work if you simply rename the file with a `.scss` extension?
`_sass/highlight-9.12.0/default.css` `=>` `_sass/highlight-9.12.0/default.scss`

**Comment by marceloverdijk** [comment]
Yes that works 👍 but off course not the most ideal solution...

**Comment by pathawks** [comment]
> Yes that works 👍 but off course not the most ideal solution...

That's the way Sass works, and is not a Jekyll issue.
