### ISSUE TITLE
Filter absolute_url adding slash in front of the URL

### ISSUE THREAD

**Issue by fefas** [jekyll/jekyll#6908]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
   ```
   Output
   Warning: You didn't set an URL in the config file, you may encounter problems with some plugins.
   ```
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***macOS*** 10+

---

- [x] There is a broken Plugin API.
- [x] I was trying to build.
- [x] It was another bug: all the links that was filtered by `absolute_url` have a slash `/` in front of if.

## My Reproduction Steps

- Link to repository: https://github.com/fefas/blog (PR: https://github.com/fefas/blog/pull/52)
- Command used to build:
   ```shell
   jekyll build --config '_config.yml,_config_dev.yml' --baseurl $URL --future
   ```
- Link to the build: https://5ac682b1a6188f5a859d7b0b--serene-heisenberg-e6ad4a.netlify.com/
- All the links that was filtered by `absolute_url` are broken.

> This problem also occurs when I run the command locally in my machine

**Comment by DirtyF** [comment]
You don't need to specify `--baseurl `if your URL is https://serene-heisenberg-e6ad4a.netlify.com/

`jekyll build --config '_config.yml,_config_dev.yml'--future` should do

see https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/ for more info.

**Comment by fefas** [comment]
@DirtyF .. thanks! I see the point and you are right.. `site.baseurl` and `site.url` are two different things.

But there is still a problem when I want to have the canonical URL dynamically. To give a real use case, I have the following meta tag:

```html
<meta property="og:url" content="<canonical-url>">
```

The production URL is fixed (`https://blog.fefas.net`), but for deployment previews it isn't. As I want to test also this feature before deploying, I would need to define the `site.url` on the build command. Is that somehow possible?

**Comment by DirtyF** [comment]
Haven't tested it but https://github.com/jayvdb/jekyll-netlify might help you

**Comment by ashmaroli** [comment]
@fefas Can this be closed..? Seems like the issue has been resolved at your end..

**Comment by fefas** [comment]
Sure! Thanks a lot for the support! :)
