### ISSUE TITLE
Should `vendor` not be added to the default .gitignore?

### ISSUE THREAD

**Issue by 030** [jekyll/jekyll#6920]
A default .gitignore is created by this project, but the vendor folder does not seem to be added. Result: 3000 files in a branch that have to be added. Should the vendor folder not be ignored?

**Default .gitignore**

```
_site
.sass-cache
.jekyll-metadata
```

**Suggested**

```
_site
.sass-cache
.jekyll-metadata
vendor
```

**Comment by DirtyF** [comment]
We do exclude some folders from build, https://github.com/jekyll/jekyll/blob/master/lib/jekyll/configuration.rb#L21-L24

**Comment by pathawks** [comment]
@030 Please do open a PR to add this :+1:

**Comment by 030** [comment]
@pathawks done
