### ISSUE TITLE
{{site.url}} is not replaced by the URL in some files

### ISSUE THREAD

**Issue by lenis2000** [jekyll/jekyll#6940]
[log.txt](https://github.com/jekyll/jekyll/files/1929869/log.txt)

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [X] I am on (or have tested on) ***macOS*** 10+
- [X] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [X] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

The build of my website failed due to sudden inability of Jekyll to replace {{site.url}} by my URL. The full website is at https://github.com/uva-math/uva-math-code and the failed Travis build is at https://travis-ci.org/uva-math/uva-math-code/builds/368843527 
I attach the build log

## The Output I Wanted

I wanted the website to build correctly. 

## Quickfix

I produced a quickfix by adding a sed script
```
find _site/ -type f -print0 | xargs -0 sed -i 's/{{site.url}}/http\:\/\/math\.virginia\.edu/g'
```
after the build but this is not how it should be done

**Comment by pathawks** [comment]
Can you please link directly to the file on your site that contains `{{ site.url }}` but is not being correctly parsed? Alternatively, maybe provide a link to an example repo that contains a minimal number of files needed to reproduce this issue.

More information is needed to diagnose this issue.

**Comment by lenis2000** [comment]
Ok, I tried this now (after `bundle update`), and the issue vanished. I tested both on my machine and on Travis CI. Guess it got fixed by some update. Closing.
