### ISSUE TITLE
Templates in post excerpts are not parsed correctly

### ISSUE THREAD

**Issue by Chaosed0** [jekyll/jekyll#6944]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Upgraded packages on Ubuntu today, and ran `gem update`. Now, when I build, templates in post excerpts are not parsed correctly.

I could easily reproduce by doing the following:

1. Clone [`jekyll-paginate-v2`](https://github.com/sverrirs/jekyll-paginate-v2/)
2. Edit the 11/27 post in the first example (01-typicalblog), and add `[Link!]({{ "/assets/image.png" | absolute_url }})`
3. EDIT (forgot a step): Add ` <p>{{ post.excerpt }}</p>` in `_layouts/home.html` after the post title
4. Run `jekyll build`.

In `_site/index.html`, I see this mangled output:

```
  <tbody>
    <tr>
      <td>[Link!]({{ “/assets/image.png”</td>
      <td>absolute_url }})</td>
    </tr>
  </tbody>
```

## The Output I Wanted

The markdown/liquid in the excerpt should be parsed appropriately, resulting in a link.

## More Info

 - Ubuntu 16.04.4 LTS
 - Ruby 2.3.7p456
 - Jekyll 3.8.0
 - Jekyll-paginate-v2 1.9.4 (but reproduced on jekyll-paginate 1.1.0 as well)

**Comment by DirtyF** [comment]
reproduced on `master` when liquid code is present in a post excerpt, it's not interpreted.
