### ISSUE TITLE
discussion – jekyll ethos method of serving json

### ISSUE THREAD

**Issue by lukepighetti** [jekyll/jekyll#6950]
Hey guys,

I need to provide JSON to my jekyll site every two minutes to keep some graphs up to date.

I am currently doing this with a simple API server and vanilla JS in a `<script>` tag

Is there a more "jekyll" way of doing this?

One thought was making a custom folder in Nginx at /data/ and putting an index.html in it containing JSON that was written to every two minutes, and serving it as a static file.

Or perhaps making a `data.js` file that contained a single object with the data within and linking to it in the body of the page.

I could just be making it too complicated. Just wondering if there is a simple, lightweight, jekyll-ish way to make some JSON available every two minutes.

**Comment by pathawks** [comment]
Jekyll is a static site generator. A site is generated and then served; there is no concept of “every two minutes.”

I think I might be missing your bigger point. Could you explain in a bit more detail what you are asking _of Jekyll?_

**Comment by DirtyF** [comment]
@lukepighetti Please use [our dedicated forum](https://talk.jekyllrb.com) to ask questions about Jekyll's usage.

If you need to trigger builds every two minutes or listen to events you might want to add a cron to your CI or take a look at AWS Lambda or Cloud functions.

An easy way to do this is through [Netlify functions](https://www.netlify.com/blog/2018/03/20/netlifys-aws-lambda-functions-bring-the-backend-to-your-frontend-workflow/).

**Comment by lukepighetti** [comment]
Thank you for kindly directing me to the forum. I will check out your suggestions. :)

**Comment by lukepighetti** [comment]
@pathawks I use Jekyll because I love how lightweight, fast, and easy it is to use. I also love the YAML frontmatter and using liquid to generate pages. That's all great.

However, I do have a need to show a ticker on my page. For that I do need to pull in some data every couple of minutes. I am using vanilla JS right now to get this data from an API server, and that does work nicely. 

However, I did wonder if I could generate a static file on my server with the information needed and then serve that with nginx as a file that was merely included when the Jekyll site was loaded.

I do not need it to pull every 2 minutes. A refresh by the user is fine. But I will want the data to be updated on the server side every 2 minutes.

**Comment by DirtyF** [comment]
If you wanna to make it _static_, it means you have to pull your data from the API and store it in JSON format in Jekyll's `_data` folder, then trigger a build every time the `_data` folder is updated.

**Comment by lukepighetti** [comment]
Are there any risks to running a build every five minutes or so?
