### ISSUE TITLE
Trouble building page

### ISSUE THREAD

**Issue by HeckCas** [jekyll/jekyll#6953]
- [x] I am on (or have tested on) ***macOS*** 10+
- [x] I was trying to build.

## My Reproduction Steps

  Hi!, i do not if i got a trouble or i do not know how to run it the right way
  
  I configured my config.yml with all my stuff & run jekyll serve
  then i've been working on the index.html (not .md) the .html, renaming some classes adding others, 
  and giving some style with css you know, save & refresh the http://127.0.0.1:4000/ and it goes 
  awesome, everything as i wanted to be 
  BUT if i change something in the config.yml OR i created another post, the page forgives the whole 
  new changes i made, also delete the new images i saved on images folder

  Am i wrong or smth?

  Can i modify the index.html? or is that the problem

**Comment by DirtyF** [comment]
@HeckCas Please use [our forum to ask for help](https://talk.jekyllrb.com) on Jekyll.

It looks like you modified the generated files, you should only edit the source files and build the site for changes to take effects.

**Comment by HeckCas** [comment]
Hi!, i do not if i got a trouble or i do not know how to run it the right way
  
  I configured my config.yml with all my stuff & run jekyll serve
  then i've been working on the index.html (not .md) the .html, renaming some classes adding others, 
  and giving some style with css you know, save & refresh the http://127.0.0.1:4000/ and it goes 
  awesome, everything as i wanted to be 
  BUT if i change something in the config.yml OR i created another post, the page forgives the whole 
  new changes i made, also delete the new images i saved on images folder

  Am i wrong or smth?

  Can i modify the index.html? or is that the problem
