### ISSUE TITLE
exclude 'hidden' posts from 'page.next/previous'

### ISSUE THREAD

**Issue by ScriptWorld-git** [jekyll/jekyll#6954]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] This is a feature request.

---

- [x] It was another bug.

## My Reproduction Steps

I tagged a post with the following front matter:
hidden: true

when i go to an article posted before or after a hidden post, I can scroll to the "next and previous" section and it will show me the hidden post to be the next one.

## The Output I Wanted

hide the hidden posts from page.next and page.previous template command

**Comment by DirtyF** [comment]
Couldn't reproduce your issue. Please [head over our forum](https://talk.jekyllrb.com) to ask for help about using Jekyll.
