### ISSUE TITLE
Published: false no longer working

### ISSUE THREAD

**Issue by domLocalHeroes** [jekyll/jekyll#6958]
Since updating to 3.8 we have noticed pages/items in collections are being outputted even if they have `published: false` in the front matter.

E.g. we have a collection "partners" and there are 9 items in the collection, 3 of which were set to published false due to us still finalising things.

This was fine until we updated but now all 9 items are shown in the collection instead of the 6 that were set to published: true.

Is this a bug or has published been deprecated? If so, what to?

Thanks

**Comment by domLocalHeroes** [comment]
Did you try it with a new collection? It seemed to work OK in our _posts files but not in any other

**Comment by domLocalHeroes** [comment]
And thanks for your reply @DirtyF

**Comment by DirtyF** [comment]
@domLocalHeroes I tested it with a custom collections yes and it's working as intended, documents with `published: false` in their front matter are not generated.

Please provide a link to a public repo where we can reproduce your issue.

**Comment by domLocalHeroes** [comment]
I can't link to our rep as it's private but I've just re-updated to v3.8 and tried this, didn't work, I downgraded back to v3.7.2 and tried it and it works.

In the config:

`collections:
  test_collection1:
    output: true
    sitemap: true
  test_collection2:
    output: false
    sitemap: false`

Then build etc.

Then in _test_collection1, create a file called item.md:
`---
title: Test Item
key: key
published: true
---
`

Then in _test_collection2, create a file called collection.md:

`---
key: key
title: Collection
---
`

Then on a test page:

`{% for testCollection in site.test_collection2 %}
  {% for testItem in site.test_collection1 %}
    {% if testCollection.key == testItem.key %}
      <h1>{{ testItem.title }}</h1>
    {% endif %}
  {% endfor %}
{% endfor %}`

This works fine and on v3.7.2 if you change `published: true` to `published: false` then the test page is blank. On v3.8 however, it will always return the <h1>.

Please let me know if this example doesn't make sense.

**Comment by ashmaroli** [comment]
@domLocalHeroes I have successfully reproduced your issue..
I'll see if I can come up with a patch a.s.a.p..

**Comment by DirtyF** [comment]
@domLocalHeroes This should be fixed in v3.8.1 who is to be released very soon. Thanks for reporting.
