### ISSUE TITLE
Small grammar mistake in latest release notes - v3.8.0

### ISSUE THREAD

**Issue by VincentVToscano** [jekyll/jekyll#6960]
While minor, I thought you might like to know there is a small grammar mistake in the latest release notes. There might be more, but this caught my eye. I'm excited to use the new release.

## Reproduction Steps /Refer to

Visit the latest release notes to view the spelling mistake:
There’s a small spelling mistake on the latest release notes:
https://github.com/jekyll/jekyll/releases/tag/v3.8.0
Refer to this bullet point:
* add Arch Linux instalation troubleshoot (#6782)

## Correct

Change 'instalation' to 'installation'

**Comment by DirtyF** [comment]
Fixed. Thanks.

**Comment by VincentVToscano** [comment]
Anytime. Take care.

**Comment by ashmaroli** [comment]
@DirtyF Please apply the correction to our `History.markdown` and to the published doc `_docs/history.md` as well.. Thanks..
