### ISSUE TITLE
Release 💎 3.8.1

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll#6971]
- [x] Backport #6945 (#6970)
- [x] Backport #6959 (#6972)
- [x] Write release post
- [x] Merge [`History.markdown`](https://github.com/jekyll/jekyll/blob/3.8-stable/History.markdown) changes into `master`
- [x] Cut :gem:

**Comment by ashmaroli** [comment]
Jekyll 3.8.1 has been released.
