### ISSUE TITLE
[Install Windows] ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by coding-rk** [jekyll/jekyll#7000]
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6
.0/ext/ruby_http_parser
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20180509-12256-1rwp6f6.rb extconf.rb
creating Makefile

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/e
xt/ruby_http_parser
make "DESTDIR=" clean

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/e
xt/ruby_http_parser
make "DESTDIR="
generating ruby_http_parser-x64-mingw32.def
make: *** No rule to make target `/C/Ruby25-x64/include/ruby-2.5.0/ruby.h', need
ed by `ruby_http_parser.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_p
arser.rb-0.6.0 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0
/http_parser.rb-0.6.0/gem_make.out
Successfully installed bundler-1.16.1
Parsing documentation for bundler-1.16.1
Done installing documentation for bundler after 3 seconds
1 gem installed

**Comment by DirtyF** [comment]
Did you follow https://jekyllrb.com/docs/windows/ ?

**Comment by ashmaroli** [comment]
Similar issues have been filed in the past. Please search our [`issues`](https://github.com/jekyll/jekyll/issues?utf8=%E2%9C%93&q=%22build+gem+native+extension%22) for related discussions and solutions

**Comment by Jesuslittlebug** [comment]
Hi, I have similar issue when i install jekyll using 2.6.14.1 version of gem and  ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32] version of ruby. How did you solve this problem?

**Comment by manojap** [comment]
I have same issue on windows

I have installed the ruby 6 version which  is the root cause of the problem 

I downloaded then rubyinstaller-devkit-2.5.5-1-x64 version install with MSYS2 
and issued the flowing 

```
gem install bundler

gem install jekyll
```

**Comment by arunkumarzz** [comment]
> I have same issue on windows
> 
> I have installed the ruby rubyinstaller-devkit-2.6.3-1-x64 version which is the root cause of the problem
> 
> I downloaded then rubyinstaller-devkit-2.5.5-1-x64 version install with MSYS2
> and issued the flowing
> 
> ```
> gem install bundler
> 
> gem install jekyll
> ```

Didn't work for me.

**Comment by plamber** [comment]
I had this issue when installing Ruby in a folder with spaces "C:\Program Files". 
Uninstalled the current version and installed the rubyinstaller-devkit-2.5.5-1-x64 by specifying a folder without spaces. 

Afterwards, I was able to execute these commands to successfully install Jekyll:
gem install bundler
gem install Jekyll

**Comment by alexzaharia24** [comment]
> I have same issue on windows
> 
> I have installed the ruby rubyinstaller-devkit-2.6.3-1-x64 version which is the root cause of the problem
> 
> I downloaded then rubyinstaller-devkit-2.5.5-1-x64 version install with MSYS2
> and issued the flowing
> 
> ```
> gem install bundler
> 
> gem install jekyll
> ```

This fixed it for me. 

I downgraded from **Ruby+Devkit 2.6.5-1 (x64)** to **Ruby+Devkit 2.5.7-1 (x64)** and then installing Jekyll worked using `gem install jekyll bundler`

**Comment by ashmaroli** [comment]
Jekyll's CI builds (AppVeyor) currently use the following:
```
ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
```

**Comment by d-prieto** [comment]
I had the same problem in Windows 10

I uninstalled the ruby 2.6.5 and installed the ruby 2.5.7 and after that I rebooted and it worked (the powershell asked me for some admin credentials that it haven't asked me before). Now I haved it installed.

**Comment by bawantha** [comment]
> 
> 
> > I have same issue on windows
> > I have installed the ruby rubyinstaller-devkit-2.6.3-1-x64 version which is the root cause of the problem
> > I downloaded then rubyinstaller-devkit-2.5.5-1-x64 version install with MSYS2
> > and issued the flowing
> > ```
> > gem install bundler
> > 
> > gem install jekyll
> > ```
> 
> This fixed it for me.
> 
> I downgraded from **Ruby+Devkit 2.6.5-1 (x64)** to **Ruby+Devkit 2.5.7-1 (x64)** and then installing Jekyll worked using `gem install jekyll bundler`

how to downgrade

**Comment by jpack2015** [comment]
Ruby 2.7.x worked for me after I moved the install location to a folder without spaces (D:\Program Files\Ruby -> D:\Ruby) and updated the relevant PATH

Strange how finicky spaces in folder names can be considering Window's default Program Files directory has a space :/

**Comment by DivyanshNatani** [comment]
<B>The following error is coming while installing Jekyll. Did all things as prescribed in this thread.
Please help</B>



PS C:\WINDOWS\system32> gem install bundler
Fetching: bundler-2.1.4.gem (100%)
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Installing ri documentation for bundler-2.1.4
Done installing documentation for bundler after 73 seconds
1 gem installed
PS C:\WINDOWS\system32> gem install jekyll
Fetching: public_suffix-4.0.5.gem (100%)
Successfully installed public_suffix-4.0.5
Fetching: addressable-2.7.0.gem (100%)
Successfully installed addressable-2.7.0
Fetching: colorator-1.1.0.gem (100%)
Successfully installed colorator-1.1.0
Fetching: http_parser.rb-0.6.0.gem (100%)
      0 [main] locale (14972) shared_info::initialize: size of shared memory region changed from 51128 to 40888
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
      1 [main] make (11480) shared_info::initialize: size of shared memory region changed from 51128 to 40888
      0 [main] make (3144) shared_info::initialize: size of shared memory region changed from 51128 to 40888
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20200521-4364-lslma1.rb extconf.rb
creating Makefile

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean
      1 [main] make (11480) shared_info::initialize: size of shared memory region changed from 51128 to 40888

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
      0 [main] make (3144) shared_info::initialize: size of shared memory region changed from 51128 to 40888

make failed, uncaught signal 11

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/http_parser.rb-0.6.0/gem_make.out

**Comment by Elizabethcase** [comment]
Just wanted to say, I had the same issues here using Ruby + Devkit v2.7.2-1. I had to install *all* options during the RIDK install (default options install only 1 & 3). Only then I could install Jekyll.
