### ISSUE TITLE
variable defined in include overrides a variable defined in page 

### ISSUE THREAD

**Issue by musikele** [jekyll/jekyll#7012]
- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [X] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [X] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ X ] It was another bug.

## My Reproduction Steps

0. new project: `jekyll new test_jekyll`, `cd test_jekyll` 

1. create file `_includes/test.html` and write: 

```
{% assign test = "I'm in test" %}
```

2. in page `about.md` write: 

```
{% assign test = "I'm in about" %} 

{% include test.html %} 

{{ test }} <!-- outputs: I'm in test -->
```

## The Output I Wanted

I wanted `I'm in about`. Why the variable declaration inside `include` is overriding the one in about.md ? Is this written somewhere? I can't find it in the docs.

**Comment by mmistakes** [comment]
I think this is working as intended due to the order of your assigns.

1. Assign `test` = to `I'm in about`
2. Include reassigns `test` to `I'm in test`
3. `{{ test }}` is called and outputs last known value of `test`... `I'm in test`.

What you might need to do is rewrite your include logic to so it can accept a variable and use that instead of overriding what you assign before it.

Something like:

in `_includes/test.html`

```
{% assign test = include.foo | default: "I'm in test" %}
```

in page `about.md`:

```
{% assign test = "I'm in about" %}
{% include test.html foo=test %}
{{ test }}
```

Which should output `I'm in about`

**Comment by musikele** [comment]
TBH I simply thought there was some kind of "variable scoping" like there's
in every other programming language; I'm starting to believe that in Jekyll
what happens is that the variable `test` lives in the page scope and gets
rewritten (unfortunately I'm not fluent in ruby to check this).
---
Michele Nasti
https://michelenasti.com


Il giorno mer 16 mag 2018 alle ore 17:03 Michael Rose <
notifications@github.com> ha scritto:

**Comment by mmistakes** [comment]
@musikele I don't Ruby either, but yes I think that's the case with the scoping.

Also what you're doing with the `assign` tags isn't Ruby... its [Liquid](https://shopify.github.io/liquid/)... the templating language Jekyll uses.

**Comment by musikele** [comment]
Well I think we can close this issue then.
