### ISSUE TITLE
Adding `file_size` to static_files in Jekyll

### ISSUE THREAD

**Issue by prestonlimlianjie** [jekyll/jekyll#7017]
- [x] This is a feature request.

---

Hi,

I'm new to Jekyll/Ruby, but I would like to add a new 'file_size' variable to static files to let users know the size of the file that they are going to download. 

I figured that I needed to start by adding the following method into */lib/jekyll/static_file.rb*:

```
    # Returns the file size in bytes
    def file_size
      File.size(path)
    end
```

However, I don't know how to go about making sure that this new feature works in the updated Jekyll before I add tests/submit a pull request. Are there any good resources for me to refer to?

Thanks!

**Comment by ashmaroli** [comment]
@prestonlimlianjie If this method is only going to be used in Liquid Templates, then its better that this method is defined directly in the `lib/jekyll/drops/static_file_drop.rb` file.

We do not have tutorials on how to write tests for a new feature. You will just have to refer existing unit tests in the `test` directory and behavior-driven tests in the `features` directory..

**Comment by pathawks** [comment]
This is a feature that should be added by a plugin rather than Jekyll core.

**Comment by ericoporto** [comment]
Just to point a common use case is when making a RSS template and is needed by the [enclosure tag](https://www.w3schools.com/xml/rss_tag_enclosure.asp) - where it would be included a podcast or header image.
