### ISSUE TITLE
Support for Org lightweight markup language

### ISSUE THREAD

**Issue by AvtechScientific** [jekyll/jekyll#7032]
- [x] This is a feature request.

It would be very nice if Jekyll would have support for [Org](http://orgmode.org/) lightweight markup language. It has very broad users community. GitHub, GitLab, emacs, vim, etc. support it.

**Comment by DirtyF** [comment]
This would be a nice plugin feature.

**Comment by pathawks** [comment]
I agree. I think Jekyll core is moving towards including _fewer_ Converters by default and letting users pick and choose which extras they need for their particular sites.

A number of Converters [are already available as plugins](https://jekyllrb.com/docs/plugins/#converters-1), including a Pandoc plugin that could perhaps be used to convert Org. :beers:
