### ISSUE TITLE
gem install jekyll error

### ISSUE THREAD

**Issue by xeriok18600** [jekyll/jekyll#7033]
env :  
window7
ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
gem : 2.6.14.1

**$ gem install jekyll
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
D:/Ruby24-x64/bin/ruby.exe -r ./siteconf20180522-6708-6pgr3v.rb extconf.rb
D:/Ruby24-x64/bin/ruby.exe: No such file or directory -- extconf.rb (LoadError)

extconf failed, exit code 1

Gem files will remain installed in D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to D:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/http_parser.rb-0.6.0/gem_make.out**

**Comment by ashmaroli** [comment]
Please install the DevKit from RubyInstaller to install gems with native extensions.

**Comment by xeriok18600** [comment]
@ashmaroli 
Thank for you help

I install ruby 2.4，include MSYS2-DEVKIT
