### ISSUE TITLE
 No such file or directory -- extconf.rb (LoadError)

### ISSUE THREAD

**Issue by xeriok18600** [jekyll/jekyll#7034]
env:
       window7
       ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
       gem 2.7.7

**$ gem install jekyll
Fetching: public_suffix-3.0.2.gem (100%)
Successfully installed public_suffix-3.0.2
Fetching: addressable-2.5.2.gem (100%)
Successfully installed addressable-2.5.2
Fetching: colorator-1.1.0.gem (100%)
Successfully installed colorator-1.1.0
Fetching: http_parser.rb-0.6.0.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20180522-6916-eztp1n.rb extconf.rb
**C:/Ruby25-x64/bin/ruby.exe: No such file or directory -- extconf.rb (LoadError)**

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to C:/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2.5.0/http_parser.rb-0.6.0/gem_make.out**

---
Can't install jekyll

**Comment by ashmaroli** [comment]
Install DevKit for RubyInstaller to install gems with native extensions.

**Comment by ashmaroli** [comment]
@xeriok18600 Please do not open another issue ticket for this problem. You may continue posting here itself.

The issue you're facing is outside Jekyll's codebase.
You're bound to find solutions for this on StackOverflow.com or RubyInstaller's repository.
