### ISSUE TITLE
site.pages doubles the text

### ISSUE THREAD

**Issue by louisabraham** [jekyll/jekyll#7036]
- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [X] I ran `jekyll doctor` to check my configuration
---

- [X] I am on (or have tested on) ***macOS*** 10+

---

- [X] It was another bug.

## My Reproduction Steps

Just put

```
---
---

before

{{ site.pages }}

after

```

in `index.html`. `jekyll build` outputs:

```
before

before

{{ site.pages }}

after



after

```

**Comment by pathawks** [comment]
`index.html` is a page.

Recursion is recursive.

**Comment by louisabraham** [comment]
I'm not sure I really understand your answer. Isn't `site.pages` supposed to be some kind of mapping?

**Comment by pathawks** [comment]
What output did you expect?

**Comment by louisabraham** [comment]
Something like a list? Or a dict?

**Comment by ashmaroli** [comment]
@louisabraham By default, `site.pages` is an array of `Page`s where each item is reduced into their *rendered output*

To see the true nature of the array, call it with the `inspect` filter:
```
{{ site.pages | inspect }}
```

You can also iterate through the array:
```
{% for page in site.pages %}
<pre>{{ page | inspect }}</pre>
{% endfor %}
```
