### ISSUE TITLE
Invalid PermalInk in test/fixtures/empty_permalink.erb

### ISSUE THREAD

**Issue by DiscoverMore** [jekyll/jekyll#7038]
I am attempting to create a new site but am a bit stuck. After installing the necessary materials I tried to run my site locally by typing in myusername.github.io in the address bar of my browser (where myuserename is the name of my cite) but all the comes up is that the github page does not exist. 

Then through the terminal I attempted to see what the problem was via Doctor and it says:
"Invalid permalink in /Users/name/Documents/myusername.github.io/test/fixtures/empty_permalink.erb".
Not sure how to fix this. Any help will be great. Thank you

- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [X] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [X] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

**Comment by ashmaroli** [comment]
Hi :wave:
Is the `test` folder a part of your site or simply a test suite for your site?

Either ways, please refrain from posting usage queries here. This platform is just for tracking development and bugs in the Jekyll codebase.

You may post this question (preferably, with a link to your repository (if public) in the post body) at our own forum https://talk.jekyllrb.com or at stackoverflow.com
