### ISSUE TITLE
Issue with variables in includes.

### ISSUE THREAD

**Issue by aioobe** [jekyll/jekyll#7080]
This is most likely an upstream bug in Liquid, but I'm not sure which Liquid version I'm on and I'm not sure how to test Liquid in isolation.

I'm on Jekyll version 3.8.3.

- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [X] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [X] It was another bug.

## My Reproduction Steps

I put this in `_includes/rec.html`. It's a simple include file that includes itself (common pattern when generating tree menus etc). This simplified include counts down from `include.n` to `0` and prints the numbers in reverse order.

```
{%- assign nn = include.n -%}
{%- if nn > 0 -%}
    {%- assign m = nn | minus: 1 -%}
    {%- include rec.html n=m -%}
{%- endif -%}
{{ nn }}<br />
```

For `{% include rec.html n=3 %}` the output is

```
0
0
0
0
```

Note that if I _don't_ use an auxiliary  variable `nn`, but instead inline `include.n` as follows:

```
{%- if include.n > 0 -%}
    {%- assign m = include.n | minus: 1 -%}
    {%- include rec.html n=m -%}
{%- endif -%}
{{ include.n }}<br />
```

I get the expected output (shown below).

## The Output I Wanted

```
0
1
2
3
```

<sup><sup><sup><sup>Why did Jekyll choose Liquid as template language? It's absolutely horrible :-(</sup></sup></sup></sup>

**Comment by aioobe** [comment]
> What would be a good template language fit for you?

Anything that allows `x + y` would be preferable. Or logical `not`. Or parenthesized expressions. Liquid is the _only_ language I know of that does _not_ support such trivial constructs.

**Comment by ashmaroli** [comment]
The issue here is once `nn` gets assigned a value of `0`, it no longer has a recollection of what its *previous* value was..
I modified your include to get something like below:

![recursive-include](https://user-images.githubusercontent.com/12479464/41714437-035bae20-756e-11e8-9673-320bc504637f.png)

**Comment by aioobe** [comment]
Right. I just realized the other day that maybe variables aren't scoped to the include. All variables are global it seems. To me this is so mind blowingly stupid that it didn't even occur to me at first. It makes it practically impossible to safely create reusable include files. What if my `comments.md` internally uses a temporary variable with the same name as a variable my template file for instance? How would you deal with variables in recursive includes? Anyway, as stupid as it may seem, this is presumably by design.

Sorry for the noise. Closing.

**Comment by liquidvisual** [comment]
This is absolutely insane, I just ran into this issue too with a recursive component. Liquid is the worst.

**Comment by dawaltconley** [comment]
also just ran into this and I agree, it's totally unintuitive. variables aren't shared between different pages & layouts, so I figured they were all scoped to their particular files—not with includes, it seems.

as a workaround, you can store the variables used by an include in obscure variable names at the top of the include, and then reassign them at the end:
```
{% assign global_scope_x = x %}
    <!-- do stuff in the include using x -->
{% assign x = global_scope_x %}
```

Which makes the include reusable, and should work with recursive includes too. But this is tedious.

**Comment by aioobe** [comment]
> ```
> {% assign global_scope_x = x %}
>     
> {% assign x = global_scope_x %}
> ```

No, this does not work. There will only be one `global_scope_x` variable even when included recursively. To see why it won't work, consider how the end result looks:

```
{% assign global_scope_x = x %}
    {% assign global_scope_x = x %}
        {% assign global_scope_x = x %}
            <!-- do stuff in the include using x -->
        {% assign x = global_scope_x %}
    {% assign x = global_scope_x %}
{% assign x = global_scope_x %}
```

**Comment by dawaltconley** [comment]
You're right. :( I think something like this would work for recursive includes.

```
{% if include.scoped %}
    {% assign x = global_scope_x %}
{% else %}
    {% assign global_scope_x = x %}
{% endif %}

   <!-- do stuff in the include using x -->
   {% include this.html scoped=true %}

{% assign x = global_scope_x %}
```

That said, I hate this.

**Comment by DirtyF** [comment]
Please head over Liquid repository for questions about Liquid: https://github.com/Shopify/liquid/issues/911
