### ISSUE TITLE
`validate_options` non-functional in `serve.rb`

### ISSUE THREAD

**Issue by jamesluberda** [jekyll/jekyll#7082]
Scope is all versions of Jekyll starting with 3.7.0.

As I was working on the code for the `livereload-sleep` option (#7064), I noted that the `validate_options` function in `lib/jekyll/commands/serve.rb` does not appear to be called anywhere, and the checks it is supposed to perform do not appear to be performed. I can see the function was added when `livereload` was added, PR #5142 (which makes sense, as it only validates `livereload` options), but there never appears to have been a call for it in the entire git history, as far as I can tell.

I wasn't sure if this was a bug, or was intentional, with code kept in place for some later implementation, or if I missed/misunderstood something. In any case, I threw in a call in `serve.rb` to test it, and the function does work as expected (and, again,  I confirmed that the conditions it flags are not flagged with the code as it currently is).

To re-create a couple of examples, try

`jekyll serve --livereload-min-delay 3`
or
`jekyll serve --livereload --detach`

In both cases, server will start normally.

Expected output, based on the code, generated by adding a call in `serve.rb`:
```
jekyll serve --livereload-min-delay 3
--livereload-min-delay, --livereload-max-delay, --livereload-ignore, --livereload-port, and --livereload-sleep require the --livereload option.
```
and
```
jekyll serve --livereload --detach
           Warning: --detach and --livereload are mutually exclusive. Choosing --livereload
```

Apologies if this is a non-issue, or I have misunderstood something.

**Comment by ashmaroli** [comment]
@awood What say, perhaps the call to this method got deleted during a rebase?

**Comment by awood** [comment]
@ashmaroli Yeah, I'm looking at my branch and I don't see the call to it.  I must have done something dumb during a rebase.  It should be called in `process` immediately prior to the call to `setup`.

**Comment by ashmaroli** [comment]
Will you be able to open a PR correcting this?
