### ISSUE TITLE
Issue install 

### ISSUE THREAD

**Issue by longtth** [jekyll/jekyll#7085]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

---

- [x] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps
```dos
C:\Users\longnx>gem install jekyll
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20180620-8092-3w02oi.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/http_parser.rb-0.6.0/gem_make.out

C:\Users\longnx>gem install ridk
ERROR:  Could not find a valid gem 'ridk' (>= 0) in any repository
ERROR:  Possible alternatives: idk, radk, rcdk, rick, rid
```

## The Output I Wanted
Sucessfully install to go with `jekyll new my-awesome-site`

**Comment by pathawks** [comment]
I am sorry you are having trouble installing Jekyll.

Since this is not a bug in Jekyll itself, I would recommend you try [talk.jekyllrb.com](https://talk.jekyllrb.com/) for help related to installation. You could also consult the [installation page in our documentation](https://jekyllrb.com/docs/installation/).

**Comment by pathawks** [comment]
> ```text
> 'make' is not recognized as an internal or external command,
> operable program or batch file.
> ```

You need to install `make`

> ```text
> gem install ridk
> ```

I don't know what this is, but it is not related to Jekyll.

**Comment by ashmaroli** [comment]
@longtth `ridk` is not a Rubygem. Its a program associated with the RubyInstaller. I believe the command you should be running is **`ridk install`**

**Comment by longtth** [comment]
Thanks for replies! 
I've tried re-install RubyInstaller and the problem gone, somekind this is an install error caused of my system fault.
