### ISSUE TITLE
{% include %} is unnecessarily restrictive of file path characters

### ISSUE THREAD

**Issue by Convincible** [jekyll/jekyll#7087]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

`{% include_relative file~path.html %}`

## The Output I Wanted

Currently `include` restricts file name/paths to `A-Za-z0-9` + `_-.` only. This is unnecessarily restrictive. Instead, perhaps filter out known illegal characters, as opposed to whitelisting safe characters? e.g. error only if path contains: `<>:"/\|?*` (taking a broad cross-OS view of what counts as illegal).

**Comment by Convincible** [comment]
Why? Sometimes I want partials to have filenames including `#`, `~`, etc. (Usually when they are part of a part.) Why not?

**Comment by ashmaroli** [comment]
Resolved by #8618
