### ISSUE TITLE
Error:  undefined method `config=' for #<Jekyll::Site:0x00005651a9674160>

### ISSUE THREAD

**Issue by shashank98giri** [jekyll/jekyll#7088]
I was getting the following error while executing `bundle exec jekyll serve` to host jekyll blog locally.

`/var/lib/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/drops/document_drop.rb:8: warning: already initialized constant Jekyll::Drops::DocumentDrop::NESTED_OBJECT_FIELD_BLACKLIST
/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb:8: warning: previous definition of NESTED_OBJECT_FIELD_BLACKLIST was here
/var/lib/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/drops/drop.rb:8: warning: already initialized constant Jekyll::Drops::Drop::NON_CONTENT_METHODS
/usr/lib/ruby/vendor_ruby/jekyll/drops/drop.rb:8: warning: previous definition of NON_CONTENT_METHODS was here
/usr/lib/ruby/vendor_ruby/jekyll/hooks.rb:56: warning: constant ::Fixnum is deprecated
Configuration file: /home/<username>/Desktop/blog/_config.yml
jekyll 3.1.6 | Error:  undefined method `config=' for #<Jekyll::Site:0x00005651a9674160>

I am not able to figure out why this Error is occuring , though everything seems right to me.

-I am currently on Ubuntu 17.10 machine

I am new to jekyll thus any kind of help is appreciated.

This is my Gemfile 

> -source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-sitemap'
gem 'jekyll-paginate'

**Comment by pathawks** [comment]
> ```text
> Configuration file: /home/<username>/Desktop/blog/_config.yml jekyll 3.1.6
> ```

Does that say `jekyll 3.1.6`? 😱

Is your site public? How can somebody recreate this issue?

**Comment by shashank98giri** [comment]
Sorry if I recreated this issue.
But unfortunately I cannot find a solution to this problem anywhere and neither have any idea why it is happening in the first place.

**Comment by pathawks** [comment]
It looks like there are two versions of Jekyll competing with one another:

 * `/var/lib/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/drops/document_drop.rb`
 * `/usr/lib/ruby/vendor_ruby/jekyll/drops/document_drop.rb`

I don't know how you installed Jekyll, but it seems to be causing problems. Without the issue template filled out, I do not know what OS you are on. Are you able to build other Jekyll sites on your machine? Are you able to build this Jekyll site on a different machine?

**Comment by shashank98giri** [comment]
I installed it by the command
`sudo gem install jekyll` through terminal.

Anyways thank you the problem is now solved and the site is running perfectly.

**Comment by PatrickHuang888** [comment]
I had same problem.
I'm using Ubuntu18, there was jekyll already install, remove using "sudo apt remove jekyll" first before "bundle install", then everything OK.
