### ISSUE TITLE
depreciation creates plugin loading conflicts

### ISSUE THREAD

**Issue by JazzMaster** [jekyll/jekyll#7098]
Bug since recent depreciation.
All OSes. Discovered on fedora 27.

- There is a broken Plugin API.
the change from gems:  to plugins: to plugins_dir: in config.yaml confuses the engine or mercenary somewhere along the line.

plugins are ruby snippets. 
GEMS are installed subROUTINES. 
Apparently someone doesnt know the difference.

What happens is jekyll thinks there are no _PLUGINS present when they are most certainly there.
This causes spurious issues like:

ERROR: Unknown tag 'prism'

The plugin is installed just fine. Jekyll just doesnt KNOW its a plugin because of syntax changes somewhere above 3.3.0. Using the old syntax resolves the issue but newer versions of jekyll forbid that.

proper syntax is GEMS: in the config.yaml.

**Comment by pathawks** [comment]
If you are trying to specify the location of the plugins directory to use local (non-Gem) plugins, use the `plugin_dir` configuration setting.
