### ISSUE TITLE
blog sorting issue since 3.4.x unresolved

### ISSUE THREAD

**Issue by JazzMaster** [jekyll/jekyll#7099]
Discovered on ubuntu 14. Issue remains on fedora 27.

Blog sorting features for DATE, etc. as posted HERE remain unresolved since 3.4.3.
I dont know why its so difficult to understand the syntax.

Jekyll internal date sorting mechanism doesnt seem to work- or Id use it.
No alternative documentation has been provided for the updated API, thereby breaking existing blogs if a newer version of jekyll is ever installed.

THIS IS WRONG.

the following code:

    {% assign sorted_stuff = (site.categories.blog | sort: 'Date') %}
	{% for post in sorted_stuff limit: 15  %}
        {% endfor %}

should provide a sorted blog by catergory or other taxonomy. It DOES with 3.3.0. It DOES NOT above 3.4.3.

theres nothing FANCY here. 

SORTED blog by date from catergory X.
X so happens to equal "blog".
I have multiple blog variants. This shouldnt pose a problem.

Collections dont work with the setup I need- this code should more than suffice, but only works on 3.3.0. Otherwise you get an empty (null) catergory and an error claiming the "pipe sort" is not understood.

error: .. expected where PIPE found

**Comment by kenman345** [comment]
has this been tried without the parenthesis in the assign?
