### ISSUE TITLE
Files with Front Matter are not included in "includes"

### ISSUE THREAD

**Issue by samuelgoto** [jekyll/jekyll#7103]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [x] It was another bug.

## My Reproduction Steps

1) create a jekyll site
2) add `include: ["_posts" ]` to your `_config.yaml`
3) create two `.md` posts (one with [front matter](https://jekyllrb.com/docs/frontmatter/) and one without) under `_post`
4) `bundle exec jekyll build`
5) Observe that `_site/_posts` contains the original .md file as well as the generated .html file for the file without frontmatter but will contain only the generated .html file for the file with frontmatter (missing the original .md file).

## The Output I Wanted

On step (5), find the original .md post with the frontmatter in the `_site/_posts` directory (due to the `_config.yaml` change).

[The following from the docs..](https://jekyllrb.com/docs/frontmatter/):

> The front matter is where Jekyll starts to get really cool. Any file that contains a YAML front matter block will be processed by Jekyll as a special file. 

..makes me believe that Jekyll treats these files somehow specially, which makes them behave differently than files without them when it comes to the "includes" processing in `_config.yaml`.

## Context

I'm trying to serve the original un-modified markdown files in a manner that works with github pages (e.g. [writing a plugin won't do](https://stackoverflow.com/questions/13159286/how-can-i-access-un-rendered-markdown-content-in-jekyll-with-liquid-tags/13184659#13184659)).

**Comment by kenman345** [comment]
I think this might be fairly easy, we would simply check for the files/folders defined in the `include` section. 

I am curious as to whether it should still process the frontmatter pages and make the HTML or not. 

Can a member of the Jekyll team weigh in? I’d be happy to take a stab if I can get some direction on the functionalities end state

**Comment by ashmaroli** [comment]
@kenman345 The underlying logic at play here is that all files with front matter will be converted and placed into the destination directory as appropriate.., and those that do not, have front matter are *copied verbatim*.
The next logic at play would be that all directories starting with an underscore (except for `_layouts`, `_includes`, `_sass` and `_posts`) are exempt from processing unless they are whitelisted via the `collections` configuration or via the `include` configuration.

**Comment by kenman345** [comment]
Yea, that’s my understanding as well. I was thinking perhaps that if they made this a collection that we could add the ability to use a new tag such as `verbatim` to be used in conjunction with `output` that would just do a straight copy...thoughts?

**Comment by ashmaroli** [comment]
> ability to use a new tag such as `verbatim`

Probably as proposed in #6871
