### ISSUE TITLE
Error:  undefined method `to_i' for #<Date: 2015-03-15 ...>

### ISSUE THREAD

**Issue by chalin** [jekyll/jekyll#7110]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I am on (or have tested on) ***macOS*** 10+

After attempting to [upgrade to Jekyll 3.8.3 in PR 988](https://github.com/dart-lang/site-www/pull/988) for use with https://github.com/dart-lang/site-www, I get the following error:

```console
> jekyll build
...
jekyll 3.8.3 | Error:  undefined method `to_i' for #<Date: 2015-03-15 ((2457097j,0s,0n),+0s,2299161j)>
Did you mean?  to_s
```

This seems to be because of the `updated: 2015-03-15` entry in frontmatter in the file https://github.com/dart-lang/site-www/blob/master/src/_articles/dart-vm/io.md

```
---
title: "An Introduction to the dart:io Library"
description: "An introduction to the Dart I/O library, which is aimed at server-side code that runs on the standalone Dart VM."
written: 2012-03-01
updated: 2015-03-15
category: dart-vm
obsolete: true
---
```

Currently we're using [jekyll 3.7.3](https://github.com/dart-lang/site-www/blob/64acac42ef01028d0f464fdc0f068bbf7ed926d0/Gemfile.lock#L45).

## My Reproduction Steps

- Checkout https://github.com/dart-lang/site-www/pull/988 of https://github.com/dart-lang/site-www
- Follow the setup instructions in the REAME
- Run `jekyll build`

cc @kwalrath

**Comment by ashmaroli** [comment]
@chalin It would be easier for us to track the bug if this issue is reproducible on a minimal site. (I don't want to install `dart` or other dependencies just to catch a certain bug.)

Additionally, you could also post the trace output from the error by running **`jekyll build --trace`**

**Comment by chalin** [comment]
Thanks for recommending the use of `--trace`, I'd forgotten about that option. Here is the output:

```console
> jekyll build --trace
Configuration file: /Users/chalin/git/dart/site-www/_config.yml
            Source: src
       Destination: publish
 Incremental build: disabled. Enable with --incremental
      Generating... 
/Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/publisher.rb:14:in `hidden_in_the_future?': undefined method `to_i' for #<Date: 2015-03-15 ((2457097j,0s,0n),+0s,2299161j)> (NoMethodError)
Did you mean?  to_s
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/publisher.rb:10:in `publish?'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/document.rb:318:in `write?'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/renderer.rb:205:in `add_regenerator_dependencies'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/renderer.rb:159:in `place_in_layouts'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/renderer.rb:88:in `render_document'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/renderer.rb:62:in `run'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/site.rb:479:in `render_regenerated'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/site.rb:463:in `each'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/site.rb:463:in `block in render_docs'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/site.rb:462:in `each_value'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/site.rb:462:in `render_docs'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/site.rb:191:in `render'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/site.rb:71:in `process'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/command.rb:28:in `process_site'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/commands/build.rb:65:in `build'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/commands/build.rb:36:in `process'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/gems/jekyll-3.8.3/exe/jekyll:15:in `<top (required)>'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/bin/jekyll:23:in `load'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/bin/jekyll:23:in `<main>'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/chalin/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:15:in `<main>'
```

> I don't want to install dart ...

Fair enough. I'm working on creating a smaller repro site.

**Comment by ashmaroli** [comment]
Thanks for posting the trace output.
From the output, the error seems to be because the concerned `document`'s `date` attribute is a `Date` object instead of the *expected* `Time` object..
https://github.com/jekyll/jekyll/blob/48e2de862d8396e6ff2f30e2231ac67c5f233b61/lib/jekyll/document.rb#L63-L65

So either the document's `date` attribute has been modified by a plugin *or* something's wrong with `site.time` which is computed automatically during the build.

Since you're building the site locally and pushing it, there's a workaround. Simply convert the date to a time first.:
```ruby
# lib/jekyll/publisher.rb
    def hidden_in_the_future?(thing)
      thing.respond_to?(:date) && !@site.future && thing.date.to_time.to_i > @site.time.to_i
    end
```

**Comment by chalin** [comment]
The offending line seems to be:

```ruby
def hidden_in_the_future?(thing)
  thing.respond_to?(:date) && !@site.future && thing.date.to_i > @site.time.to_i
end
```

It seems reasonable to think that `thing.date` would be a [Date](https://ruby-doc.org/stdlib-2.4.3/libdoc/date/rdoc/Date.html), but `Date` doesn't support `to_i`.  The assumption might be that `thing.date` is a [Time](https://ruby-doc.org/core-2.4.3/Time.html), so maybe the method could be:

```ruby
def hidden_in_the_future?(thing)
  return false unless thing.respond_to?(:date) && !@site.future
  date = thing.date
  t = date.is_a? 'Date' ? date.to_time : date
  t.to_i > @site.time.to_i
end
```

As I mentioned in the opening comment, our site built without issues under Jekyll 3.7.3. Maybe an assumption changed about the type of `thing.date` between 3.7.3 and 3.8.3? (Either that or something processing dates in front matter used to return a Time but now returns a Date?)

**Comment by chalin** [comment]
(Thanks for the quick response. Our posts crossed :)

**Comment by chalin** [comment]
Using this statement:

```ruby
puts ">> #{thing.date.class} #{thing.date.inspect}" if thing.respond_to?(:date)
```

I get:

```console
> jekyll build
Configuration file: /Users/chalin/git/dart/site-www/_config.yml
            Source: src
       Destination: publish
 Incremental build: disabled. Enable with --incremental
      Generating... 
>> Time 2018-07-05 09:01:15 -0400
... (repeated)
```

**Comment by chalin** [comment]
Under jekyll 3.8.3 I get:

```console
> jekyll build
Configuration file: /Users/chalin/git/dart/site-www/_config.yml
            Source: src
       Destination: publish
 Incremental build: disabled. Enable with --incremental
      Generating... 
>> Time 2018-07-05 09:04:22 -0400
>> Time 2018-07-05 09:04:22 -0400
>> Date #<Date: 2015-03-15 ((2457097j,0s,0n),+0s,2299161j)>
jekyll 3.8.3 | Error:  undefined method `to_i' for #<Date: 2015-03-15 ((2457097j,0s,0n),+0s,2299161j)>
Did you mean?  to_s
```

**Comment by chalin** [comment]
Ah, I think that I might have found the cause in one of our own plugins. (Still investigating)

**Comment by chalin** [comment]
Yep, it was on our side 😞. Apologies for the false alarm, and thanks for the help in tracking down the cause!

**Comment by ashmaroli** [comment]
No problem. Glad you were able to resolve the issue. Was it an in-house plugin or a 3rd-party plugin? Perhaps other users of the plugin could benefit from your investigation..

**Comment by chalin** [comment]
In-house.

**Comment by chalin** [comment]
Is it that `date` shouldn't be modified, or is it ok to modifying (provided it is set to a time)?

**Comment by ashmaroli** [comment]
You can modify the `date` as necessary, as long as the result responds to `to_s` :wink:
I'd recommend it be a `Time` object in sync with Jekyll's codebase, though.
