### ISSUE TITLE
Reboot.css

### ISSUE THREAD

**Issue by chrisfinazzo** [jekyll/jekyll#7120]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+

---

- [x] I was trying to build.

As Normalize doesn't bring many changes with it from v7 to v8, it seems appropriate to revisit our reset stylesheet. In #6491, @envygeeks [mentioned][] that Bootstrap's Reboot might be worth a look. Furthermore, Bootstrap itself has migrated away from Normalize to use Reboot in their 4.0 release. If desired, I can open a PR to swap it in - thinking this could go in 4.0, but it's up to @oe and @DirtyF to make that call.

[mentioned]: https://github.com/jekyll/jekyll/pull/6491#issuecomment-340347240

That said, there is one issue I've come across that needs to be resolved: TWBS has numerous mixins and other SASS directives which currently trigger a build failure. Importing all of them feels like overkill and hand-tweaking values is no one's idea of a good time.

Thoughts?

cc\ @jekyll/documentation

---

## My Reproduction Steps

After editing the appropriate files, rebuild the site as normal `bundle exec jekyll build`.

<img width="585" alt="screen shot 2018-07-09 at 11 05 47 am" src="https://user-images.githubusercontent.com/1534882/42458763-62979220-8368-11e8-95c9-e8a7f23cb5e4.png">

## The Output I Wanted

A successful build to appear in `_site`.

**Comment by mattr-** [comment]
Does reboot depend on bootstrap or is it a standalone thing? I'm thinking we may need to extract a pure CSS version of Reboot rather than pulling the SASS version in to avoid a bootstrap dependency or upgrade. If any of this is just flat out wrong, I apologize. I haven't taken the time to get up to speed with bootstrap 4.

**Comment by chrisfinazzo** [comment]
Ah, yes, that's correct. It was developed in parallel with Bootstrap, so we'd need to have a compiled version. I've updated the link and the build now succeeds. I'll post a link to the PR so you can take a look.

@DirtyF This was @envygeeks' suggestion, so he's probably better equipped to answer that than I am. I just wanted to see if it was possible so that there would be an alternative if Normalize ceased active development.

**Comment by DirtyF** [comment]
Given we don't use Bootstrap, I don't see any reason to make this change at the moment, but thanks for the suggestion @chrisfinazzo, we'll keep this in mind if we change our CSS framework (I'd go with Tailwinds if you ask me).

**Comment by mattr-** [comment]
Let's keep in mind that Reboot isn't technically tied to Bootstrap and is a replacement for normalize.css. If normalize ever stops development, then we'll need to find a replacement regardless of CSS framework.
