### ISSUE TITLE
Sponsoring preparation masterplan

### ISSUE THREAD

**Issue by oe** [jekyll/jekyll#7131]
_If you're here and don't know what's going on: This is sort of an internal process. Stay tuned for more information very soon!_

1. Triage existing issues and pull requests and see if they're significant enough to warrant being expended for. This should __not__ only apply to code changes, but if there's a significant documentation change, please label those as well.

The following labels should be used:

1. [priority 1 (must)](https://github.com/jekyll/jekyll/labels/priority%201%20%28must%29) <-- expended
2. [priority 2 (should) ](https://github.com/jekyll/jekyll/labels/priority%202%20%28should%29) <-- expended
3. [priority 3 (could)](https://github.com/jekyll/jekyll/labels/priority%203%20%28could%29) <-- expended on an individual basis
4. [priority 4 (maybe)](https://github.com/jekyll/jekyll/labels/priority%204%20%28maybe%29) <-- not expended

Core team, please add any issues or PRs that you have triaged to the following table by editing this comment:

| Issue Link | Priority | Comments |
|    ---     |   ---    |    ---   |
| #4269  | 1 (must)| Performance: Smarter Regeneration |
| #6874 |  2 (should) | Performance: Marshall Documents |
| #7108 |  2 (should) | Performance: Cache static includes |
| #5211 |  2 (should) |  Consistency: Pages as Documents |
| #5208 | 2 (should) | Consistency: Data as Collection |
| #5857 | 2 (should) | Consistency: Tags and Categories for all Documents |
| #6727 | 2 (should) | UX: add URL filter on link tag |
| #6821 | 2 (should) | UX: Highlight Tag |
| #7118| 2 (should) | Drop Pygments dependency | 
| #4742 | 3 (could) | Feature: Multiple output formats (JSON, AMP, Epub) |
| #6824 | 3 (could) | UX: Disable Liquid Rendering |

2. Write up a policy on using OpenCollective funds. Feel free to borrow from other project's policies, and open a PR so other core team members can help you out. This PR shouldn't be assigned a priority label.

3. Formulate an expense policy for use on OpenCollective. Preferably a short blurb to tell interested contributors where to get started. Should link to the policy described above.

4. Contact sponsors. This is likely going to be my job, so I'll take care of it when the previous points have been done.

5. Revise the blog post on the `sponsor` branch.

6. ???

7. Launch!

**Comment by ashmaroli** [comment]
> please add any issues or PRs that you have triaged to the following list

Instead of a list, a table would be better.

Priority 1 | Priority 2 | Priority 3 | Priority 4
--- | --- | --- | ---
`#xxxx` |

**Comment by oe** [comment]
@ashmaroli good idea, updated
