### ISSUE TITLE
Modify post creation instruction?

### ISSUE THREAD

**Issue by 104fps** [jekyll/jekyll#7137]
As new user of jekyll got little confused about this statement: 

> To add new posts, simply add a file in the `_posts` directory that follows the convention `YYYY-MM-DD-name-of-post.ext` 

because I created file "2018-07-15-hello-world.ext" and just can't open that post, because we should use md/html (?) as file extension. Can we add some info about that or capitalize that (`YYYY-MM-DD-name-of-post.EXT`) or I just badly read docs?

Thanks.

**Comment by pathawks** [comment]
@104fps Sorry for this misunderstanding.

Yes, you are correct that `.ext` is meant to be replaced with `.html` or `.md`.

On our website, I think we do a better job of [explaining the intention](https://jekyllrb.com/docs/posts/#creating-post-files):

> Jekyll requires blog post files to be named according to the following format:
> ```text
> YEAR-MONTH-DAY-title.MARKUP
> ```
>
> Where `YEAR` is a four-digit number, `MONTH` and `DAY` are both two-digit numbers, and `MARKUP` is the file extension representing the format used in the file.

Perhaps we should update the wording of the example post to match the website?

https://github.com/jekyll/jekyll/blob/16e9820dac7c29b5ad835ec7ca1023301f7963d0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb#L9

**Comment by 104fps** [comment]
#7138
