### ISSUE TITLE
Permission denied @rb_sysopen

### ISSUE THREAD

**Issue by robinmetral** [jekyll/jekyll#7170]
I have two Jekyll directories.

When I run `jekyll serve` in on of them, everything works as expected.

However when I try it in the other directory, I get:
`jekyll 3.8.3 | Error:  Permission denied @ rb_sysopen - /home/robin/Documents/web/clarale.com/www/_site/404.html`
(it looks kind of similar to [this issue](https://github.com/envygeeks/jekyll-docker/issues/32), but I'm not using the Jekyll Docker plugin. In fact I'm not using any third-party plugin.)

I can work around this issue if I run the command as sudo.

What's weird is that it only happens on the one Jekyll directory... Any idea what could be wrong? Is my setup somehow messed up? I tried to chmod the permissions on the directory, but it didn't change anything.

**Comment by DirtyF** [comment]
You might want to install your gems in your home directory to avoid permissions issue:

https://jekyllrb.com/docs/troubleshooting/#no-sudo

Please use your forum https://talk.jekyllrb.com to ask about Jekyll's usage.

**Comment by robinmetral** [comment]
Thank you for your quick reply and sorry for not posting in the right place!

... however this *does not explain why I only have trouble in one of two Jekyll directories*. This is the issue I was actually asking about (see my initial post).

But if you think this is not a bug, then no problem. As I mentioned earlier, I can work around it.

**Comment by DirtyF** [comment]
> One shall always use bundler — Doctor Jekyll

https://jekyllrb.com/tutorials/using-jekyll-with-bundler

**Comment by yegorski** [comment]
I used the `jekyll/jekyll` image from Docker hub and hit the same issue:

```
Configuration file: _config.yml
            Source: /srv/jekyll
       Destination: ./dist/staging
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.8.4 | Error:  Permission denied @ rb_sysopen - /srv/jekyll/dist/staging/404.html
The command '/bin/sh -c jekyll build --config _config.yml --destination ./dist/staging' returned a non-zero code: 1
```

The problematic Dockerfile looks like this:

```
FROM jekyll/builder as builder

RUN mkdir -p /srv/jekyll

WORKDIR /srv/jekyll

COPY . .

RUN jekyll build --config _config.yml --destination ./dist/staging
```

I worked around this by using the `ruby` image and installing jekyll tools:
```
FROM ruby as builder

# https://github.com/inadarei/alpine-jekyll/blob/master/Dockerfile
RUN gem install --no-document \
        redcarpet \
        kramdown \
        maruku \
        rdiscount \
        RedCloth \
        liquid \
        pygments.rb \
        sass \
        safe_yaml \
        jekyll \
        jekyll-paginate \
        jekyll-sass-converter \
        jekyll-sitemap \
        jekyll-feed \
        jekyll-redirect-from

RUN mkdir /srv/jekyll

WORKDIR /srv/jekyll

COPY . .

RUN jekyll build --config _config.yml --destination ./dist/staging

```
