### ISSUE TITLE
Jekyll only builds posts and nothing else

### ISSUE THREAD

**Issue by grysvn** [jekyll/jekyll#7172]
Sorry if this isn't a great issue, I have ran into this bug a couple times over the past few years and I'm never sure exactly how to reproduce it - I know it's probably because of broken front-matter somewhere, but I can't figure out where or why. The odd thing is a serve auto-generate will work fine, and then if I build it just doesn't work - nothing goes wrong in verbose output or anywhere else and doctor reports no problems. If anyone has seen this I'd greatly appreciate some tips. Thanks.

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

I'll build after adding a new post and the only content that appears in _site is the posts for the categories on my site - nothing else. I don't know exactly how to reproduce this, I have had my blog going for a while - it uses a pretty simple custom theme - and I stupidly didn't put the blog folder in version control when I first started - only the output which is my GitHub pages site.

I'm just trying to build my site, and it will work if I make random changes and let `jekyll serve` auto generate, but then if I run jekyll build it will delete all of the site files/structure only leaving the posts folders. Here's my verbose output of build. Clean and doctor say nothing is wrong:

https://pastebin.com/fB4NQnQd

## The Output I Wanted

This happens once every year ish. I'll go to write a new post and most of the time it works, but sometimes I get this bug and I've never found anyone else having it and I've never been able to consistently reproduce it.

My config looks like this:

```
# Site settings
title: matt gray
email: email removed
description: > # this means to ignore newlines until "baseurl:"
  bio removed
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattgray.net" # the base hostname & protocol for your site
twitter_username: grysvn
github_username:  grysvn

# Build settings
markdown: kramdown
```

**Comment by DirtyF** [comment]
> it's probably because of broken front-matter somewhere, but I can't figure out where 

You could try to pass `--strict_front_matter` option to your build or add `strict_front_matter: true` in your config, and see if there's any error.

**Comment by grysvn** [comment]
That didn't work, but thanks @DirtyF for the response. I had tried that before in build settings but now I added it to my config - still no warnings. I also went through every file with front matter and none appeared to be off.

Are there any files that should or should not have front matter? 

Also is there anything that is done differently by the build engine when regenerating server-side vs doing a full build. Because regenerating server-side is the only thing that will sometimes work and do a full-build. Example:

1. `jekyll b` - only generates posts - _site contains only folders for each category
2. `jekyll s` - same as above
3. *make miscellaneous change to a file* - whole site correctly generates
4. *make no changes*, `jekyll b` - same as initial build - site doesn't generate

**Comment by DirtyF** [comment]
Hard to tell without a public repo and a specific scenario to reproduce your issue.

About front matter:

- All documents (in posts or other collections) are supposed to have front matter — you can use front matter defaults to keep things DRY.
- If a file don't have any front matter, Jekyll will not process it and simply copy it as is to the output directory.

Possible manuel debugging:

- Try to build in safe mode
- Deactivate plugins one by one and see if there's any difference
- Move possibly _problematic_ content in `_drafts` or outside jekyll's root directory and see if there's any difference

**Comment by grysvn** [comment]
Okay so disregard everything below, I moved the site to a different dir to upload it to git (https://github.com/grysvn/blog-source) and now `jekyll b` appears to be consistently working even when I make changes. I have no idea why a new folder would help with that, but it did. So I think this is resolved. Thank you!
______________________________________

First of all, I really appreciate the help!

I tried all of the debugging you suggested:

1. I built in safe mode, nothing appeared to change.
2. I don't have any plugins so this wasn't an issue,
3. I tried moving all content out to the drafts folder and it didn't change, just built nothing. 

So I'm guessing the problem is in something related to the site itself outside of the posts. I started from a very minimal theme and built the site myself so maybe I mucked something up then. But I can't figure out what might have changed recently. I pushed my site to a public repo, here's the link:

https://github.com/grysvn/blog-source

Calling Jekyll b on what is in that repo currently only builds the posts folder. That's how I would try and reproduce.

**Comment by pathawks** [comment]
@grysvn Glad you got your site to build consistently :+1:

**Comment by DirtyF** [comment]
Any reason to still use rdiscount? What if you rely on Jekyll's default MArkdown engine?

You should try to remove [this line in your config](https://github.com/grysvn/blog-source/blob/master/_config.yml#L14), [rdiscount support will be removed in next major version](https://github.com/jekyll/jekyll/pull/6988)

**Comment by grysvn** [comment]
Thanks for pointing that out! I removed that and rebuilt. I had put it in there because at some point I of desperation I thought "might as well try changing the markdown engine" and that didn't work. Forgot to remove it. Thanks again for all of the help :)
