### ISSUE TITLE
Indent level treated as code block in files included from markdown

### ISSUE THREAD

**Issue by cbsiddharth** [jekyll/jekyll#7177]
I'm using jekyll 3.8.3 with ruby 2.5.1p57 on 64 bit Centos 7.5.  I have a `_include/image.html` file ([see on github][3]) with the following contents,

```html
{% if include.post %}
    {% capture image-path %}{{ site.baseurl }}/assets/posts/{{ include.post | replace:'.md','' }}/{{ include.src }}{% endcapture %}
{% else %}
    {% capture image-path %}{{ site.baseurl }}/assets/{{ page.path | replace:'_posts/', 'posts/' | replace:'.md','' }}/{{ include.src }}{% endcapture %}
{% endif %}

<div class="text-center">
    <a class="b-captionImg" href="#" data-featherlight="{{ image-path }}">
        <img
            data-src="{{ image-path }}" class="img-responsive lazyload"
            {% if include.width %}
                width="{{ include.width }}"
                {% endif %}
            {% if include.alt %}
                alt="{{ include.alt }}"
            {% else %}
                alt="{{ include.src | replace: '-', ' ' | replace: '.png', '' | replace: '.jpg', '' | replace: '.gif', '' }}"
            {% endif %}
        />
        {% if include.caption %}
            <p>{{ include.caption }}</p>
        {% endif %}
    </a>
</div>
```
 I include this file from markdown files to import image assets like this,

```liquid
{% include image.html src="circular-buffer-animation.gif" %}
```

The problem (I believe) is that the since the contents of the file `image.html` is indented by 4 spaces, everything after the first indent level is treated as code block instead of just importing as-is. This problem can be seen [here][1]. The source file for this post can be found [here][4].

On the other hand, other posts that use the same include syntax do not suffer this problem such as this one [here][2] and [here][5]. I also had no issue getting the image rendered in older version of jekyll as this is the first time I am facing this issue in this page.

## Questions:
- Is this a bug? If so is there a known workaround other than loosing the indent levels? I would really like to keep my code clean.
- Is there a way to disable the offset-based code rending feature of GFM? I never really use this feature (I use fenced code blocks) as it doesn't clearly distinguish code blocks from content.

-------

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I was trying to build.

[1]: https://embedjournal.com/implementing-circular-buffer-embedded-c/
[2]: https://embedjournal.com/how-to-make-pcbs-at-home-with-toner-transfer-method/
[3]: https://github.com/EmbedJournal/jekyll-depot/blob/master/jekyll/_includes/image.html
[4]: https://github.com/EmbedJournal/web-content/blob/main/posts/programming/2014-05-16-implementing-circular-buffer-embedded-c.md
[5]: https://embedjournal.com/make-a-cheap-wireless-robot/

**Comment by cbsiddharth** [comment]
Can anyone help out please?

**Comment by ashmaroli** [comment]
@cbsiddharth Can you try the following..?
*"Add `markdown="0"` attribute to a top-level tag to disable Markdown parsing."*
```html
<div class="text-center" markdown="0">
    <a class="b-captionImg" href="#" data-featherlight="{{ image-path }}">
        [...]
    </a>
</div>
```

**Comment by DirtyF** [comment]
👋 @cbsiddharth 
🆘 Head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll.
⚠️ This repository issues are dedicated to **documented bugs only**.

**Comment by cbsiddharth** [comment]
@ashmaroli, that worked. Thanks.
