### ISSUE TITLE
[GH-Pages]  Jekyll cannot build a TeX code sample

### ISSUE THREAD

**Issue by ousia** [jekyll/jekyll#7180]
Sorry, but I’m afraid this is a bug.

I tried to add in a _Markdown_ file for _Jekyll_ the following code and _GitHub Pages_ complained (again and again) about the build failure.

In its shortest form, the sample reads:

``` tex
\def\hashtwofile#1{%
    \ctxlua{context(utilities.sha2.hash256(io.loaddata("#1")))}}

\def\hashfivefile#1{%
    \ctxlua{context(utilities.sha2.hash512(io.loaddata("#1")))}}
```

It seems that the TeX comment introduction in the command definition (such as in `\def\hashtwofile#1{%` or in `\def\hashfivefile#1{%`).

BTW, I wonder why _Ruby_ is enabled inside pure code. And not even from _Ruby_, but from TeX.

Is there any way to get the sample built in Jekyll?

Many thanks for your help and your excellent work.

**Comment by mmistakes** [comment]
You'll probably need to wrap your code block with the `raw` tag. For whatever reason Liquid tags in code blocks are interpreted so it's seeing `{%` and breaking.

Workaround would be this:

```tex
{% raw %}\def\hashtwofile#1{%
    \ctxlua{context(utilities.sha2.hash256(io.loaddata("#1")))}}

\def\hashfivefile#1{%
    \ctxlua{context(utilities.sha2.hash512(io.loaddata("#1")))}}{% endraw %}
```

**Comment by ousia** [comment]
@mmistakes, many thanks for the workaround.

**Comment by ousia** [comment]
@pathawks, does it mean that any `{{` in code blocks or spans will be interpreted as Liquid tags?

**Comment by pathawks** [comment]
Correct. Unfortunately, the `{% raw %}` wrapper is necessary when using anything that Liquid might try to parse.

It’s not great. We’re trying to come up with some better solutions for the next major version of Jekyll.
