### ISSUE TITLE
Liquid Warning: Liquid syntax error (line 258): Unexpected character ñ

### ISSUE THREAD

**Issue by javier-marroquin** [jekyll/jekyll#7207]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      Windows 10      |
| `jekyll`         | 3.8.3     |

## Code Sample

```
{% for post in site.categories.montañas limit:1 %}
...
{% endfor%}
```

## Output

`Liquid Warning: Liquid syntax error (line 258): Unexpected character ñ in "post in site.categories.montañas limit:1" in index.html`

What should I do to make the Latin or Spanish letter "ñ" work?

**Comment by chrisfinazzo** [comment]
Can you try using any of the Entity values instead? E.g, `&#241;` or `&ntilde;`?

**Comment by GregPK** [comment]
@javier-marroquin Is this still an issue? Ruby should handle unicode characters by default, but since this also touches the file system, there's all sorts of mischief that can be going on (especially since the `ñ` character doesn't have to be unicode, it's present in simpler encodings). 

My suggestions is to make sure you're using unicode encoding in all files.

**Comment by DirtyF** [comment]
Reproduced on my end with proper UTF-8 files.

| Software  | Version(s) |
| ---------  | ---------- |
| Operating System | macOS 10.13.6 |
| ruby |  2.5.1   |
| `jekyll`  | master   |

I'm not sure we should support this 

/cc @jekyll/core 

### Workaround

```
  {% assign selection = site.posts | where:"categories","montañas" | limit:1 %}
  {% for post in selection %}

  {% endfor %}
```

**Comment by fullviajeros** [comment]
> ¿Puedes intentar usar cualquiera de los valores de la Entidad en su lugar? Por ejemplo, `&#241;`o `&ntilde;`?

This was the solution, I'm sorry for not taking a look, I've been pretty busy. Thanks, I will close the problem.

**Comment by javier-marroquin** [comment]
> ¿Puedes intentar usar cualquiera de los valores de la Entidad en su lugar? Por ejemplo, `&#241;`o `&ntilde;`?

This was the solution, I'm sorry for not taking a look, I've been pretty busy. Thanks, I will close the problem.
