### ISSUE TITLE
Rouge syntax hilighting is not responsive

### ISSUE THREAD

**Issue by karthikchintala1** [jekyll/jekyll#7209]
This bug is related to responsiveness of code blocks in rouge syntax hilighter.

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I am on (or have tested on) ***Windows*** 10+
- [x] It was another bug.

## My theme details
1. I have installed [jasper2](https://github.com/jekyller/jasper2) theme

## My Reproduction Steps

1. Goto [coderethinked.com post](http://coderethinked.com/streaming-in-asp-net-core-signalr)
2. Press <kbd>F12</kbd> or open developer tools
3. Select the `device toolbar` or press <kbd>Ctrl + Shift + M</kbd>
3. Scroll down a little bit and identify a code block
4. Try to scroll horizontally on the code block

## Actual output
![image](https://user-images.githubusercontent.com/16499209/44941490-0be7d600-adbc-11e8-864f-135eb3921cf4.png)

## The Output I Wanted

A good responsive code blocks for mobile devices, which can be scrollable on any device.

**Comment by DirtyF** [comment]
Please submit an issue on the theme repo, this is not related to Jekyll's core.
