### ISSUE TITLE
nested `include_relative` apparently does not work.

### ISSUE THREAD

**Issue by AlistairB** [jekyll/jekyll#7212]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+
---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

/categories.md

```liquid
---
layout: 'default'
---

{% include_relative fragments/sports.md %}
```

/fragments/sports.md

```liquid
We gots lots of sports

{% include_relative fragments/sports/baseball.md %}
```

Produces `IOError: Could not locate the included file 'fragments/sports/baseball.md' in any of ["/work/fragments/sports"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode.` (run from inside docker, my code root is `/work`)

I have confirmed `fragments/sports/baseball.md` does exist and I have tried many variations trying to get this to work.

## The Output I Wanted

I wanted the nested `include_relative` to just work.

May be related to https://github.com/jekyll/jekyll/issues/6863

**Comment by ashmaroli** [comment]
@AlistairB I could not reproduce this bug using Jekyll 3.8.3 (and current `master`) on my Windows system. I'll prepare a pull request with Cucumber features shortly, to check if this bug can reproduced on any other platforms we're testing..

**Comment by AlistairB** [comment]
Sorry, it seems this is only an issue with `3.7.3` (eg. github pages version). I bumped to `3.8.3` and it works fine. Closing.
