### ISSUE TITLE
No output has been received. The build has been terminated. when posts become more and more,such as 9000 posts.

### ISSUE THREAD

**Issue by mycad** [jekyll/jekyll#7218]
- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+
---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

If the posts more than 9000 thousand,No result return in the CMD window, even half an hour pass.
Less than 3000 posts, github page still could generate the sites pages, thought github process a long time. but as the posts become more and more, github page can't generate our sites. It is also when I run jekyll on my personal computer, jekyll can't generate our sites.

**Comment by mycad** [comment]
Travis CI result:

1.07s$ git clone --depth=50 --branch=master https://github.com/mycad/mycad.github.io.git mycad/mycad.github.io
Cloning into 'mycad/mycad.github.io'...
remote: Counting objects: 9376, done.
remote: Compressing objects: 100% (8459/8459), done.
remote: Total 9376 (delta 776), reused 9221 (delta 770), pack-reused 146
Receiving objects: 100% (9376/9376), 3.59 MiB | 16.05 MiB/s, done.
Resolving deltas: 100% (794/794), done.
$ cd mycad/mycad.github.io
$ git checkout -qf bd6647fc2c84f8808d9cb38c0dd7e43c87eb5afb
Disabling Gradle daemon
$ mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
rvm
35.50s$ rvm use 2.1 --install --binary --fuzzy
curl: (22) The requested URL returned error: 404 Not Found
Required ruby-2.1.10 is not installed - installing.
curl: (22) The requested URL returned error: 404 Not Found
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.1.10.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
ruby-2.1.10 - #configure
ruby-2.1.10 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 23.0M  100 23.0M    0     0  24.3M      0 --:--:-- --:--:-- --:--:-- 24.3M
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.1.10 - #validate archive
ruby-2.1.10 - #extract
ruby-2.1.10 - #validate binary
ruby-2.1.10 - #setup
ruby-2.1.10 - #gemset created /home/travis/.rvm/gems/ruby-2.1.10@global
** Updating RubyGems to the latest version for security reasons. **
** If you need an older version, you can downgrade with 'gem update --system OLD_VERSION'. **
ruby-2.1.10 - #importing gemset /home/travis/.rvm/gemsets/global.gems................................................
ruby-2.1.10 - #generating global wrappers........
ruby-2.1.10 - #uninstalling gem rubygems-bundler-1.4.5.
ruby-2.1.10 - #gemset created /home/travis/.rvm/gems/ruby-2.1.10
ruby-2.1.10 - #importing gemset /home/travis/.rvm/gemsets/default.gems...............
ruby-2.1.10 - #generating default wrappers........
Using /home/travis/.rvm/gems/ruby-2.1.10
$ export BUNDLE_GEMFILE=$PWD/Gemfile
ruby.versions
$ ruby --version
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]
$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 1.16.2
$ gem --version
2.7.7
install.bundler
84.86s$ bundle install --jobs=3 --retry=3
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.....
Fetching concurrent-ruby 1.0.5
Fetching minitest 5.11.3
Installing minitest 5.11.3
Installing concurrent-ruby 1.0.5
Fetching thread_safe 0.3.6
Fetching public_suffix 2.0.5
Installing thread_safe 0.3.6
Installing public_suffix 2.0.5
Using bundler 1.16.2
Fetching coffee-script-source 1.11.1
Fetching execjs 2.7.0
Installing coffee-script-source 1.11.1
Fetching colorator 1.1.0
Installing execjs 2.7.0
Installing colorator 1.1.0
Fetching ffi 1.9.25
Fetching multipart-post 2.0.0
Installing multipart-post 2.0.0
Fetching forwardable-extended 2.6.0
Installing forwardable-extended 2.6.0
Installing ffi 1.9.25 with native extensions
Fetching gemoji 3.0.0
Installing gemoji 3.0.0
Fetching net-dns 0.8.0
Installing net-dns 0.8.0
Fetching rb-fsevent 0.10.3
Installing rb-fsevent 0.10.3
Fetching kramdown 1.16.2
Installing kramdown 1.16.2
Fetching liquid 4.0.0
Installing liquid 4.0.0
Fetching mercenary 0.3.6
Installing mercenary 0.3.6
Fetching rouge 2.2.1
Installing rouge 2.2.1
Fetching safe_yaml 1.0.4
Installing safe_yaml 1.0.4
Fetching mini_portile2 2.3.0
Installing mini_portile2 2.3.0
Fetching jekyll-paginate 1.1.0
Installing jekyll-paginate 1.1.0
Fetching rubyzip 1.2.2
Installing rubyzip 1.2.2
Fetching jekyll-swiss 0.4.0
Installing jekyll-swiss 0.4.0
Fetching unicode-display_width 1.4.0
Installing unicode-display_width 1.4.0
Fetching i18n 0.9.5
Installing i18n 0.9.5
Fetching addressable 2.5.2
Installing addressable 2.5.2
Fetching tzinfo 1.2.5
Installing tzinfo 1.2.5
Fetching coffee-script 2.4.1
Installing coffee-script 2.4.1
Fetching faraday 0.15.2
Installing faraday 0.15.2
Fetching pathutil 0.16.1
Installing pathutil 0.16.1
Fetching nokogiri 1.8.4
Installing nokogiri 1.8.4 with native extensions
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching ruby-enum 0.7.2
Installing ruby-enum 0.7.2
Fetching activesupport 4.2.9
Installing activesupport 4.2.9
Fetching jekyll-coffeescript 1.0.2
Installing jekyll-coffeescript 1.0.2
Fetching sawyer 0.8.1
Installing sawyer 0.8.1
Fetching ethon 0.11.0
Installing ethon 0.11.0
Fetching rb-inotify 0.9.10
Installing rb-inotify 0.9.10
Fetching commonmarker 0.17.12
Installing commonmarker 0.17.12 with native extensions
Fetching octokit 4.11.0
Installing octokit 4.11.0
Fetching typhoeus 0.8.0
Installing typhoeus 0.8.0
Fetching sass-listen 4.0.0
Installing sass-listen 4.0.0
Fetching listen 3.0.6
Installing listen 3.0.6
Fetching html-pipeline 2.8.4
Installing html-pipeline 2.8.4
Fetching jekyll-gist 1.4.1
Installing jekyll-gist 1.4.1
Fetching github-pages-health-check 1.3.5
Installing github-pages-health-check 1.3.5
Fetching sass 3.5.7
Installing sass 3.5.7
Fetching jekyll-watch 1.5.1
Installing jekyll-watch 1.5.1
Fetching jekyll-sass-converter 1.5.0
Installing jekyll-sass-converter 1.5.0
Fetching jekyll 3.6.2
Installing jekyll 3.6.2
Fetching jekyll-avatar 0.5.0
Installing jekyll-avatar 0.5.0
Fetching jekyll-default-layout 0.1.4
Installing jekyll-default-layout 0.1.4
Fetching jekyll-feed 0.9.2
Installing jekyll-feed 0.9.2
Fetching jekyll-github-metadata 2.9.3
Installing jekyll-github-metadata 2.9.3
Fetching jekyll-mentions 1.2.0
Installing jekyll-mentions 1.2.0
Fetching jekyll-optional-front-matter 0.3.0
Installing jekyll-optional-front-matter 0.3.0
Fetching jekyll-readme-index 0.2.0
Installing jekyll-readme-index 0.2.0
Fetching jekyll-redirect-from 0.12.1
Installing jekyll-redirect-from 0.12.1
Fetching jekyll-relative-links 0.5.2
Installing jekyll-relative-links 0.5.2
Fetching jekyll-remote-theme 0.2.3
Installing jekyll-remote-theme 0.2.3
Fetching jekyll-seo-tag 2.3.0
Installing jekyll-seo-tag 2.3.0
Fetching jekyll-sitemap 1.1.1
Installing jekyll-sitemap 1.1.1
Fetching jekyll-titles-from-headings 0.5.0
Installing jekyll-titles-from-headings 0.5.0
Fetching jemoji 0.8.1
Installing jemoji 0.8.1
Fetching minima 2.1.1
Installing minima 2.1.1
Fetching jekyll-theme-architect 0.1.0
Installing jekyll-theme-architect 0.1.0
Fetching jekyll-theme-cayman 0.1.0
Installing jekyll-theme-cayman 0.1.0
Fetching jekyll-theme-dinky 0.1.0
Installing jekyll-theme-dinky 0.1.0
Fetching jekyll-theme-hacker 0.1.0
Installing jekyll-theme-hacker 0.1.0
Fetching jekyll-theme-leap-day 0.1.0
Installing jekyll-theme-leap-day 0.1.0
Fetching jekyll-theme-merlot 0.1.0
Installing jekyll-theme-merlot 0.1.0
Fetching jekyll-theme-midnight 0.1.0
Installing jekyll-theme-midnight 0.1.0
Fetching jekyll-theme-minimal 0.1.0
Installing jekyll-theme-minimal 0.1.0
Fetching jekyll-theme-modernist 0.1.0
Installing jekyll-theme-modernist 0.1.0
Fetching jekyll-theme-primer 0.5.2
Installing jekyll-theme-primer 0.5.2
Fetching jekyll-theme-slate 0.1.0
Installing jekyll-theme-slate 0.1.0
Fetching jekyll-theme-tactile 0.1.0
Installing jekyll-theme-tactile 0.1.0
Fetching jekyll-theme-time-machine 0.1.0
Installing jekyll-theme-time-machine 0.1.0
Fetching jekyll-commonmark 1.2.0
Installing jekyll-commonmark 1.2.0
Fetching jekyll-commonmark-ghpages 0.1.5
Installing jekyll-commonmark-ghpages 0.1.5
Fetching github-pages 177
Installing github-pages 177
Bundle complete! 1 Gemfile dependency, 81 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from sass:
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.
* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install
* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme
* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811
Post-install message from html-pipeline:
-------------------------------------------------
Thank you for installing html-pipeline!
You must bundle Filter gem dependencies.
See html-pipeline README.md for more details.
https://github.com/jch/html-pipeline#dependencies
-------------------------------------------------
$ bundle exec jekyll build
Configuration file: /home/travis/build/mycad/mycad.github.io/_config.yml
       Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
            Source: /home/travis/build/mycad/mycad.github.io
       Destination: /home/travis/build/mycad/mycad.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

**Comment by ashmaroli** [comment]
You can do two things to **try and resolve this issue** to a certain extent..
  - run `bundle update` to update the versions of gems used in your build
  - build using `--verbose` flag to send Travis continuous messages: `bundle exec jekyll build --verbose`

### Notes
- Jekyll has *some performance improvements* in `jekyll-3.8.3` (especially for sites containing huge number of `posts`), but you wont be able to use it since `github-pages` gem is locked to `jekyll-3.7.4`..
- A side-effect of running verbose build on Travis is that *Travis could get choked with huge amounts of log data*..

**Comment by mycad** [comment]
Thanks.

**Comment by DirtyF** [comment]
Did you try to run `bundle exec jekyll build --profile` and see if you could optimize your liquid templates?

**Comment by mycad** [comment]
with --verbose , it could get the result, but the generation time is still too long, it takes more then 30 minitus when built it using Travis-CI.

**Comment by DirtyF** [comment]
Based on the actual build time and our benchmark tests, it _could_ be go down to maybe 20 minutes with latest Ruby 2.5 and Jekyll, maybe less if you can optimize your liquid templates. Even with improved performance, build time would still be several minutes. If you're looking for build in less than a minute for 9000 posts, you better pick up a SSG like [Hugo](https://gohugo.io).

We're already working on performance improvement for the next major version of Jekyll. 
As this issue isn't specific and depends on other services like GitHub Pages and Travis CI, I'll close it for now. Feel free to post any updates if you manage to get better results.

**Comment by ashmaroli** [comment]
@mycad I made an attempt to build your site via Travis CI using `Ruby 2.5`, `jekyll-3.8.3` and `jekyll-commonmark` a plugin that is *known* to speed up builds.
Unfortunately, the build still took [`1896.578 seconds` to complete](https://api.travis-ci.org/v3/job/429629064/log.txt).

I'm afraid that is more or less as fast as it can get currently. You may be able to shave off a few seconds by optimizing your Liquid Templates..

**Comment by mycad** [comment]
@DirtyF @ashmaroli  I am trying to change my site from jekyll to hugo.  hugo generate speed is obviously faster than jekyll, But jekyll's document is hardly to read, and can't find some functions.
Change site form jekyll to hugo is not  easy based on my site.
