### ISSUE TITLE
Docs minor edits

### ISSUE THREAD

**Issue by chrisfinazzo** [jekyll/jekyll#7219]
As a addendum to @mneumegen's reorganization of the docs, I've gone through and corrected a few errors that still exist. Nothing major, mostly punctuation and things of that sort. The proposed changes can be seen below.

However, in its current state, this does not pass `script/proof` - complains about 404 errors regarding linked pages that have different URLs. Other than within `_data` is there another place where this should be changed?

<img width="858" alt="screen shot 2018-09-03 at 4 36 50 pm" src="https://user-images.githubusercontent.com/1534882/45001134-9ab14a00-af98-11e8-9068-88d4821444d2.png">

**Comment by DirtyF** [comment]
Internal links have been checked on current `master`,  there are no 404 reported:
```sh
bundle exec htmlproofer ./docs/_site --allow-hash-href --disable-external
Running ["LinkCheck", "ImageCheck", "ScriptCheck"] on ["./docs/_site"] on *.html...

Ran on 187 files!

HTML-Proofer finished successfully.
```

If you have found significant errors that prevent a proper comprehension of the current docs on master, feel free to open a PR and we'll review your fixes.

**Comment by chrisfinazzo** [comment]
OK, I'll pull out the fixes and resubmit those. Still, the URL issue remains...

The proof doesn't pass `--disable-external` from what I can see - I think that's where I went wrong. I'm a few versions behind, so I'll probably rebuild too before 4.0 lands. With the reorg, Do we have an updated "dev" install guide? In the past I'd do the following.

1. Clone in GH
2. `git clone` to my local directory
3. Add upstream, merge, then `push -u`
4. `script/bootstrap`

The only catch I can think of here is that `bootstrap` isn't loading Proofer from the Gemfile, even though I know I have it installed.

#7042 _really_ needs to land because now the `ENV` variables make my 🧠 not work right.

![huh](https://media.giphy.com/media/mPytjcsG3XS4o/giphy.gif)

**Comment by chrisfinazzo** [comment]
#7238.
