### ISSUE TITLE
How do I add a example.com as text in the body of markdown post without turning it into a link?

### ISSUE THREAD

**Issue by marvindanig** [jekyll/jekyll#7222]
So I'm writing a blog using jekyll and in that post I'm using `example.com/` at a number of places in the body of text. Jekyll is automatically turning them into links. 

I don't want them to turn into links. How do I escape?

Basically,

example.com = correct
[example.com](example.com) != correct

In a post.

**Comment by chrisfinazzo** [comment]
Do you have a sample repo we can look at? Easier to figure out what's going on if the source is available.

**Comment by marvindanig** [comment]
The repo is currently private but the draft blogpost is here: 

https://bubblin.io/blog/set-up-jekyll-blog-quickly-alongside-your-rails-app 

Search for `domain.com`, which is like example.com, supposed to be written for reference only, but jekyll is converting into an actual link.

**Comment by chrisfinazzo** [comment]
I searched the HTML source of the post and didn't find any links for `domain.com` that have this behavior. Has this been fixed. Otherwise, I would suggest making sure you aren't using backticks (``) or other code blocks surrounding that URL.

**Comment by ashmaroli** [comment]
> `domain.com` despite being encapsulated in backticks (``) are clickable.

Which line exactly..?
Can you add some context too, please? (couple of words before `domain.com` and after `domain.com` in page at https://bubblin.io/blog/set-up-jekyll-blog-quickly-alongside-your-rails-app)

**Comment by marvindanig** [comment]
Sure! 

This line on the paragraph immediately after …¯\(ツ)/¯, for example:  

"come along with a subdirectory like this: /domain.com/blog? IMO,"

**Comment by ashmaroli** [comment]
I tried that very line and its just plain text.. no hyperlinks, no change in mouse-pointer, nada.. zilch..

**Comment by marvindanig** [comment]
Interesting. There are more instances of domain.com across the post. Are all of them unclickable on your browser?

**Comment by ashmaroli** [comment]
> Are all of them unclickable on your browser?

Every one of them.. Perhaps its time to update your browser or change it altogether...

**Comment by marvindanig** [comment]
ha! I'm on the following specs:

```
Google Chrome is up to date
Version 69.0.3497.81 (Official Build) (64-bit)
MacOS High Sierra, 10.13.6.
```
On this machine it shows me blue colored links all over `domain.com`. I wonder if that is the case for others with the same browser/OS config or it is just me.

**Comment by marvindanig** [comment]
![jekyll](https://user-images.githubusercontent.com/5659924/45063954-e9d1aa80-b07e-11e8-9cf9-48daeebfc59d.jpg)

**Comment by ashmaroli** [comment]
Screenshot of a blockquote on Google Chrome 69 on Windows:

![bubblin io_blog_set-up-jekyll-blog-quickly-alongside-your-rails-app](https://user-images.githubusercontent.com/12479464/45063966-a737be80-b0ce-11e8-987e-9700cde3c36a.png)

**Comment by marvindanig** [comment]
Yeah, I'll take your word on this. Thanks for digging!
