### ISSUE TITLE
Some search engine results point to broken URLs on jekyllrb.com

### ISSUE THREAD

**Issue by jake-low** [jekyll/jekyll#7230]
It looks like the documentation was overhauled recently (#7205), and as a result some search engine results point to pages that no longer exist. For example, if I search on Google for "jekyll drafts", the first result points to https://jekyllrb.com/docs/drafts/ which 404s. It would be great if this URL instead redirected to https://jekyllrb.com/docs/posts/#drafts.

Some other URLs that are now broken (non-exhaustive, found by browsing through web.archive.org)
- https://jekyllrb.com/docs/quickstart/
- https://jekyllrb.com/docs/extras/
- https://jekyllrb.com/docs/windows/
- https://jekyllrb.com/docs/sites/

Thanks! 🙂

**Comment by chrisfinazzo** [comment]
Hi @jake-low,

Some of this may be Google's index being a bit out of date, eventually they should crawl the new pages. I have a PR in-progress with redirects for the pages you mentioned, the only exception being `/docs/extras` which doesn't really have a mapping in the new structure.

@mneumegen, if you have thoughts on where this should go, I'm all ears.

**Comment by mneumegen** [comment]
Just send it to `/docs/`. Can't imagine it was getting much traffic.
