### ISSUE TITLE
Excerpt throws error when `highlight` and `raw` tags are combined at the begining of a document.

### ISSUE THREAD

**Issue by djacquel** [jekyll/jekyll#7248]
After investigating [this SO question](https://stackoverflow.com/questions/52324134/getting-an-liquid-exception-liquid-syntax-error-while-using-jekyll), I can reproduce an error by combining highlight and raw tags.

## Reproduction Steps
bundle exec jekyll new mysite

Replace "Welcome to Jekyll" post content by :

```
---
front matter
---
{% highlight python %}
{% raw %}
  # line 1
  # line 2
{% endraw %}
{% endhighlight %}
```
This works well.

Add a line between two lines of code :

```
---
front matter
---
{% highlight python %}
{% raw %}
  # line 1

  # line 2
{% endraw %}
{% endhighlight %}
```

Jekyll throws :
>  Liquid Exception: Liquid syntax error (line 2): 'raw' tag was never closed in _posts/2018-09-14-welcome-to-jekyll.markdown/#excerpt
  Liquid Exception: Liquid syntax error (minima-2.5.0/_includes/head.html line 2): 'raw' tag was never closed included in /_layouts/default.html
             Error: Liquid syntax error (minima-2.5.0/_includes/head.html line 2): 'raw' tag was never closed included 
             Error: Run jekyll build --trace for more information.

While :

```
---
front matter
---
{% highlight python %}

{% raw %}
  # line 1
  # line 2
{% endraw %}
{% endhighlight %}
```
Is warning :

>  Warning: Excerpt modified in _posts/2018-09-14-welcome-to-jekyll.markdown!
    Found a Liquid block containing separator ' ' and has been modified with the appropriate closing tag.
    Feel free to define a custom excerpt or excerpt_separator in the document's Front Matter if the generated excerpt is unsatisfactory.

**Comment by ashmaroli** [comment]
@djacquel This was fixed in `v3.8.x` .. Are you using the latest version of Jekyll?
*Note: `github-pages` gem bundles an older version (`v3.7.4`) which does not contain the fixes for this..*

**Comment by djacquel** [comment]
I confirm this throws an error in v3.8.3.

```
---
front matter
---
{% highlight python %}
{% raw %}
  # line 1

  # line 2
{% endraw %}
{% endhighlight %}
```

**Comment by ashmaroli** [comment]
@djacquel Thank you for reporting this. I'll submit a patch for review over the weekend.
