### ISSUE TITLE
Unreleased Cache API documentation visible

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#7249]
The tutorial for the unreleased Cache API (`v4.0` feature) is visible at:
https://jekyllrb.com/tutorials/cache-api/

I request the maintainers to unpublish that page until `v4.0` ships..

/cc @DirtyF

**Comment by DirtyF** [comment]
Fixed in https://github.com/jekyll/jekyll/commit/a22cd6d603761e526a7e3dfc45ad3d71aae5bbf1

**Comment by ashmaroli** [comment]
Thank you @DirtyF
