### ISSUE TITLE
Optimize Scope Globbing in Front Matter Defaults

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#7258]
Stubbing this out to a dedicated ticket in order to give this issue some *priority* for Jekyll 4.0

*Globbing a scope path is currently unusable on moderate-large collections due to the steep increase in build times.*

PR(s) that will have a positive impact on resolving this issue:
  - #6888 - *Merged*
  - #7263 - *Merged*
  - #7345 - *Merged*

/cc @cameronmcefee

**Comment by ashmaroli** [comment]
@cameronmcefee Please check if your site builds *satisfactorily* with the latest `master` branch.
If it doesn't, we'll try and optimize a bit more.. :smiley:

**Comment by cameronmcefee** [comment]
Thanks @ashmaroli! I'll try to figure this out on my own, but I'm not familiar with how to build a jekyll site from the jekyll source. If there is documentation for that please send it my way.

**Comment by ashmaroli** [comment]
Its pretty simple actually..
1. Create a `Gemfile` if there isn't one in your site already..
2. Point to the jekyll repository via the `Gemfile`.
```ruby
# Gemfile
source "https://rubygems.org"

gem "jekyll", :git =>"https://github.com/jekyll/jekyll.git"

# any other gems your site may need during the build process
[...]
```
3. Activate Jekyll via Bundler
```
$ bundle exec jekyll build --trace
```

**Comment by cameronmcefee** [comment]
Nice, that's a pretty solid improvement. On master I don't see much of a difference in glob vs non-glob.

A simple test with a glob that only matches one file:

3.8.2 (whole site/incremental)
Globbing: 38.655/3.94
No Glob: 27.382/1.18

Master (whole site/incremental)
Globbing: 27.36/1.17
No Glob:  27.07/1.2

A complex test with a glob that matches multiple depths of files/folders:

3.8.2 Globbing: 57.7
Master Globbing: 21.515

I'd call this quite satisfactory.

**Comment by ashmaroli** [comment]
Thank you for getting back @cameronmcefee 
I wasn't aiming for much of a difference between "globbing" and "non-globbing", but I see that's open for optimization as well..

But I'm happy with the results from globbing with `v3.8.2` vs globbing with `master`..

**Comment by cameronmcefee** [comment]
Ah, sorry, I was mostly including that for myself, as the difference was significant enough that I was weighing whether to make a separate collection that I'd join to the other rather than keep it all together.

**Comment by ashmaroli** [comment]
No worries, @cameronmcefee 
There *should be a perceivable difference* when you glob vs when you don't glob at all.. So that means, the gain is being swallowed somewhere..

*[rubs hands]*

**Comment by cameronmcefee** [comment]
If you'd like to test with our repo, I can have a branch with the complex test mentioned above later this morning.

**Comment by cameronmcefee** [comment]
Actually, for the glob/non-glob test, you can [work from master here](https://github.com/getsentry/sentry-docs) (currently non-globbing) and revert [this commit](https://github.com/getsentry/sentry-docs/commit/053f376375e167efbf51bf6b0c456e244b34eed4) to enable the globbing test I did above

**Comment by ashmaroli** [comment]
Thank you very much Cameron. I'll use it to do some tests. :+1:

**Comment by ashmaroli** [comment]
Optimized satisfactorily..
