### ISSUE TITLE
Ignoring redcarpet-3.4.0 because its extensions are not built.

### ISSUE THREAD

**Issue by yuis-ice** [jekyll/jekyll#7265]
- [x] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [ ] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

I use jekyll with redcarpet and I added few plugins to jekyll but there are not work.

`jekyll serve  --host 0.0.0.0`'s output says `Ignoring redcarpet-3.4.0 because its extensions are not built.`.

The full error message is:

```
Ignoring commonmarker-0.17.13 because its extensions are not built.  Try: gem pristine commonmarker --version 0.17.13
Ignoring redcarpet-3.4.0 because its extensions are not built.  Try: gem pristine redcarpet --version 3.4.0
/var/lib/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/spec_set.rb:91:in `block in materialize': Could not find public_suffix-3.0.3 in any of the sources (Bundler::GemNotFound)
        from /var/lib/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/spec_set.rb:85:in `map!'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/spec_set.rb:85:in `materialize'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/definition.rb:171:in `specs'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/definition.rb:238:in `specs_for'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/definition.rb:227:in `requested_specs'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:108:in `block in definition_method'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:20:in `setup'
        from /var/lib/gems/2.3.0/gems/bundler-1.16.2/lib/bundler.rb:107:in `setup'
        from /usr/lib/ruby/vendor_ruby/jekyll/plugin_manager.rb:38:in `require_from_bundler'
        from /usr/bin/jekyll:11:in `<main>'

```

This error occur only when specify `plugins`.

**This occur the error**
```
markdown: redcarpet

plugins:
  - jekyll-seo-tag

```

**This occur the error**
```
markdown: redcarpet

plugins:
  # - jekyll-seo-tag

```

**This build normaly**
```
markdown: redcarpet

# plugins:
  # - jekyll-seo-tag

```

**Comment by DirtyF** [comment]
Make sure you have ruby development headers installed in order to compile extensions: 
`sudo apt-get install ruby-full build-essential`

**Comment by yuis-ice** [comment]
I solve this problem. 
Before `bundle install` install gem locally with `gem install redcarpet` make solve this problem.
I test with some plugins and it works well.
Thanks.
