### ISSUE TITLE
error gem 

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [jekyll/jekyll#7275]
Hello guys
I can not install jekyll
with the following command
gem install jekyll
i'm used  fedora 27 
follow error: 
[root@lauriano ~]# gem install jekyll
ERROR:  Could not find a valid gem 'jekyll' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)

**Comment by ashmaroli** [comment]
Obviously, we can't help you download a gem if your internet connection timed out unexpectedly..

**Comment by DirtyF** [comment]
🔌  It looks like a temporary network problem, not related with jekyll itsellf.

👉 Please use [our forum](https://talk.jekyllrb.com) if you need further help with install.
