### ISSUE TITLE
--livereload does not work in a barebones project

### ISSUE THREAD

**Issue by behrangs-sportsbet** [jekyll/jekyll#7279]
* Create a new folder
* Create a sample `index.html` file (e.g. the one from the Jekyll [tutorial](https://jekyllrb.com/docs/step-by-step/01-setup/))
* Run `jekyll serve --livereload`
* Open `localhost:4000`

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Ubuntu 18.04            |
| `jekyll`         | Latest     |

---

## Expected Behaviour

Changes to `index.html` should automatically be reflected in the browser.

## Current Behavior

Changes to `index.html` are not automatically reflected in the browser.

## Code Sample

* Create a new folder
* Create a sample `index.html` file (e.g. the one from the Jekyll [tutorial](https://jekyllrb.com/docs/step-by-step/01-setup/))
* Run `jekyll serve --livereload`
* Open `localhost:4000`

### index.html

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <h1>Hello World!</h1>
  </body>
</html>
```

**Comment by ashmaroli** [comment]
@behrangs-sportsbet There are **two things required** for `--livereload` to work:
  - `<head></head>` markup tag in the main *layout* or `index.html`
  - Front matter dashes in the source file.

In your case, the `index.html` is missing front matter dashes. So, Jekyll sees `index.html` as a `static_file` instead of a `page`..

**Comment by behrangs-sportsbet** [comment]
Thanks! Adding the front matter made livereload kick in.

**Comment by ashmaroli** [comment]
Closing this ticket now..
