### ISSUE TITLE
Liquid Empty Check

### ISSUE THREAD

**Issue by nixpulvis** [jekyll/jekyll#7295]
## Summary

In liquid's most current online documentation, [found here](https://help.shopify.com/en/themes/liquid/basics/types#checking-for-emptiness) there is a section on checking for emptiness. The previous issue #2538 was closed and frozen due to age or I'd just comment there.

## Motivation

Checking for emptiness of an array is critical for preventing extraneous markup, and is generally a thing programmers will expect.

**Comment by ashmaroli** [comment]
@nixpulvis The documentation you linked to is for Liquid used in Shopify themes and stores..
Jekyll uses a different flavor: http://liquidmarkup.org/

Let me know if you find "checking for emptiness" in that documentation.. :wink:

**Comment by nixpulvis** [comment]
Ohhhh, well darn. I thought I was on to something. Boy this would be nice tho, even if it was a hack on top of liquidmarkup :/

Thanks for your quick reply, feel free to close this since it's basically a dup of a closed issue at this point.

**Comment by ashmaroli** [comment]
I'll leave it open in case the Core Team has any plans of introducing the feature in Jekyll..

**Comment by nixpulvis** [comment]
Found something on their wiki, if that counts. https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#if--else, search for empty.

**Comment by ashmaroli** [comment]
I'm not sure if their wiki is up-to-date.
The surest way to know would be to "test" this at your end itself..
The array you have control over is a set of documents in a collection. 

In your Jekyll site, initialize a new empty collection:
```yaml
collections:
  random:
    output: true
```
Now test via Liquid in a new empty page (`./test-page.md`):
```
---
layout: none
title: Test Page
---

{% if site.random == empty %} EMPTY {% else %} NOT EMPTY {% endif %}
```
Build your site and inspect `test-page.html`

Then, add a `./_random/foo.md` with valid contents..
Build your site and inspect `test-page.html`

**Comment by DirtyF** [comment]
T.I.L: It works even if you don't output the collection's documents 😄 

`{% unless site.puppies == empty %} Too many puppies {%endunless}`
