### ISSUE TITLE
Feat: merge theme configuration with default config

### ISSUE THREAD

**Issue by winterbang** [jekyll/jekyll#7303]
I make a theme, and want to use the `_config.yml` in my theme as my blog config.But jekyll can not load the `_config.yml` file which is in my theme. I do not know why.

**Comment by ashmaroli** [comment]
@winterbang Jekyll does not load `_config.yml` inside theme-gems by default.
You can use a third-party plugin called [`jekyll-data`](https://github.com/ashmaroli/jekyll-data) to get that functionality though..

**Comment by ashmaroli** [comment]
> Could it be a feature

It could be a Core Feature if the Core Team wants it to be.. :wink:

**Comment by DirtyF** [comment]
```
Given that I use a gem-based theme and set `theme: my-theme` in `_config.yml`
When I run `bundle exec jekyll build`
Then the theme `_config.yml` is merged with default `_config.yml`
```
### Expected behaviour

Additional theme configuration is taken into account by default. It's the equivalent of running with `--config _config.yml, theme/_config.yml` option.

**Comment by ashmaroli** [comment]
> It's the equivalent of running with `--config _config.yml, theme/_config.yml` option.

@DirtyF That **shouldn't be** the expected behavior.
How the plugin implements the behavior is:
```bash
# config.yml at the right overrides the preceding ones
--config theme/_config.yml, source/_config.yml, _config_dev.yml
```

**Comment by winterbang** [comment]
Geate! Thanks all!
