### ISSUE TITLE
Working with Collections

### ISSUE THREAD

**Issue by abhi2434** [jekyll/jekyll#7309]
While working with Collections in Jekyll, I have found that the collection part of the code is not working for me. I am unable to make it work somehow on my installation. Is it a bug common to everyone or I am the one missing something here. 

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |            |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour
Expected behavior is the list will be populated with the collections mentioned in the folder. 

## Current Behavior
Currently the loop does not produce a value.

## Code Sample
In [config.yml](https://github.com/appseconnect/docs/blob/master/_config.yml), it is written like this :
```
collections:
  category:
    output: true
  listcourses:
    permalink: /:collection/:name
    output: true
```
Here the listcourses is the collection I am trying to load on a [particular page](https://github.com/appseconnect/docs/blob/master/_includes/learning-trails-bottom-block.html). You can see on this page, I have to put all the links separately in elements as the site.collection.listcourses loop is not working. 

Is there something I am missing out here or is it something missing on Jekyll side ...

**Comment by ashmaroli** [comment]
You should iterate collections directly:
```
{% for course in site.listcourses %}
 your code
{% endfor %}
```

**Comment by DirtyF** [comment]
@abhi2434 for help about usage, please rather head over [our forum](https://talk.jekyllrb.com), looks like you're using `minimal-mistakes theme`, @mmistakes may help you there.

**Comment by abhi2434** [comment]
> You should iterate collections directly:
> 
> ```
> {% for course in site.listcourses %}
>  your code
> {% endfor %}
> ```

Yes, I tried it too, but result is the same. 



> @abhi2434 for help about usage, please rather head over [our forum](https://talk.jekyllrb.com), looks like you're using `minimal-mistakes` theme, @mmistakes may help you there.

Thanks, will be checking the forum too, but I have tried all possible ways which people suggested in forums and other areas, but still unable to find the issue. I am hoping someone could help me.

**Comment by mmistakes** [comment]
@abhi2434 Looks to me you're [iterating over `site.collections.listcourses`](https://github.com/appseconnect/docs/blob/master/_includes/learning-trails-bottom-block.html#L6), which won't work.

You need to iterate over `site.listcourses` as @DirtyF suggest.

**Comment by abhi2434** [comment]
> @abhi2434 Looks to me you're [iterating over `site.collections.listcourses`](https://github.com/appseconnect/docs/blob/master/_includes/learning-trails-bottom-block.html#L6), which won't work.
> 
> You need to iterate over `site.listcourses` as @DirtyF suggested.

When I iterate over site.listcourses, it is still not producing any output. The code is now like 

`  {% for course in site.listcourses %}
            <li>
                <div class="learningWhiteBox">
                    <img src="{{ course.icon }}" />
                    <h4>{{ course.name }}</h4>
                    <p>{{ course.content | markdownify }}</p>
                    <a href="http://learning.appseconnect.com/{{ course.path }}" title="Get Started">Get Started</a>
                </div>
            </li>`

I still think there is something missing here @mmistakes, can you just check once for me, as I have wasted to much time on this. 
The [config.yml](https://github.com/appseconnect/docs/blob/master/_config.yml) and [listfiles ](https://github.com/appseconnect/docs/blob/master/_includes/learning-trails-bottom-block.html)are the two areas I have changed.

**Comment by DirtyF** [comment]
Please take this discussion over to our forum, this isn't the place to learn about Jekyll.
