### ISSUE TITLE
Ignoring commonmarker-0.17.13 because its extensions are not built. Try: gem pristine commonmarker --version 0.17.13

### ISSUE THREAD

**Issue by zhouxiang19910319** [jekyll/jekyll#7318]
```
Ignoring commonmarker-0.17.13 because its extensions are not built. 
Try: gem pristine commonmarker --version 0.17.13
```
This is the error I get whenever I try `jekyll doctor` as well as `bundle show minima` and some other jekyll commands.
I am using macOS Mojave, what should I do to get rid of this warning message?

**Comment by zhouxiang19910319** [comment]
Solved this issue using these steps: 

* Add this line to your application’s Gemfile:
`gem 'commonmarker'`
* Execute:
`$ bundle`

**Comment by DirtyF** [comment]
Glad you fixed your problem.

**Comment by zhouxiang19910319** [comment]
@DirtyF Thanks!

**Comment by felix-voicehub** [comment]
I just want to add that I had to update bundler using `gem install bundler` before this worked.

**Comment by egarciamartin** [comment]
> I just want to add that I had to update bundler using `gem install bundler` before this worked. I repeatedly got this error with an older version.

This solved many issues, thanks for that!

**Comment by iamkulbhushansingh** [comment]
thanks matt! Its working
