### ISSUE TITLE
Caching in Jekyll::Renderer has broken automatic Sass reloading

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#7320]
- I'm on latest `master` branch
- I ran `jekyll doctor` to check my configuration
- I'm on Windows

## Expected Behaviour

Changing a sass file should allow me to preview the change in my browser when I'm running
`jekyll serve`

## Current Behavior

The changes are not reflected in the browser.

## Steps to reproduce bug:

1. Create a test-site with `jekyll new test-site`
2. Edit `test-site/Gemfile` to point to the latest `master` of this repository.
3. Follow the necessary steps to allow overriding Minima's styles from `test-site/`
4. `bundle exec jekyll serve --livereload --trace` and preview `http://localhost:4000` in the browser.
5. Follow the steps one would normally follow to change the `background-color` value to `"ffcc00"`
6. **Observe that** the background color **hasn't changed** *automatically* or on *hitting `Refresh`*
7. Stop and restart server
8. Refresh browser.
9. **Observe that** the background color **has changed** as expected

/cc @jekyll/core

**Comment by DirtyF** [comment]
Related: https://github.com/jekyll/jekyll/pull/7183

**Comment by DirtyF** [comment]
I also experienced refreshing problems, even when just editing a file.

**Comment by ashmaroli** [comment]
@pathawks Can I revert the merge of #7183 ..?

**Comment by pathawks** [comment]
@ashmaroli Unfortunately, I do not have time at the moment to track down what the underlying issue might be. Reverting until more debugging can be done seems reasonable :+1:
