### ISSUE TITLE
Excluding my spec directory has unexpected side effects

### ISSUE THREAD

**Issue by zarahzachz** [jekyll/jekyll#7321]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  macOS High Sierra, v 10.13.6  |
| `jekyll`         | 3.7.4  |
| `github-pages`   | No  |

---

## Expected Behaviour

I expect that updating any HTML file would result in `jekyll serve` regenerating that updated file.

## Current Behavior

What I've discovered is files with the word "spec" in the name (i.e., `perspective.html`, `special.html`, etc.) do no kick off the regenerate process. I believe I've pinpointed the cause of this, but I don't understand why or how to fix it. 

It looks like excluding our `spec` directory in the config file is impacting individual files as well. I was able to recreate this by building a clean Jekyll project and writing the same exclude rules, so this does appear to be a Jekyll thing.

## Code Sample
Repo: https://github.com/crdschurch/crds-media

Our current exclude rules in `_config.yml`:
```
exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - package.json
  - README.md
  - spec/
  - tmp/
  - vendor/
```

Note that we've tried excluding directories with and without the `/` and even attempted `spec/*` with no success. I've suggested changing our `spec/` directory to `_spec/`, but the team lead has said this will break our rspec configuration. And renaming the HTML files isn't possible as they have branding tied to the word "perspective".

**Comment by DirtyF** [comment]
Could you provide a public repository where we can reproduce this?

**Comment by zarahzachz** [comment]
@DirtyF Sorry, repo here: https://github.com/crdschurch/crds-media

I've also updated my ticket to include this.

**Comment by DirtyF** [comment]
Testes with Jekyll 3.8.4:

```gherkin
Given I add a folder `spec` at the root and add `spec` to the `exclude` in `_config.yml`
When I run `bundle exec jekyll build`
Then the folder `_site/spec/` does not exists.

Given I add a page `perspective.html` at the root
When I run `bundle exec jekyll build`
Then the page `_site/perspective.html` exists.
```

**Comment by ashmaroli** [comment]
This is not a Jekyll issue, rather a known bug in `jekyll-watch`
Its related to https://github.com/jekyll/jekyll-watch/issues/22

**Comment by zarahzachz** [comment]
@ashmaroli Thank you! I knew this couldn't be the first time someone's run into this! Closing my issue and thanks for the help!
