### ISSUE TITLE
CoffeeScript fails CI

### ISSUE THREAD

**Issue by oe** [jekyll/jekyll#7323]
Does anyone have an idea why CoffeeScript tests are failing sometimes (for me, less often locally and more often on CI)? I've come to the conclusion that it can basically only be dependent on run order, so maybe we can rerun the tests until they pass?

**Comment by pathawks** [comment]
Or track down the source of the non-determinism

**Comment by ashmaroli** [comment]
Based on my observation, this started with the merging of #7183 
But no matter what, I have been unsuccessful at reproducing this failure locally (not even once, let alone *less often*...)

**Comment by ashmaroli** [comment]
Closing as this seems to have been resolved on `master`.
