### ISSUE TITLE
Liquid-4.0.0 en.yml is not a recognized liquid

### ISSUE THREAD

**Issue by blacknbunny** [jekyll/jekyll#7324]
Your site is having problems building: The tag when on line 8 in vendor/bundle/gems/liquid-4.0.0/lib/liquid/locales/en.yml is not a recognized Liquid tag.

Can't resolve this.

**Comment by DirtyF** [comment]
What's your context?

Looks like you need to exclude `vendor/bundle` from your build.

**Comment by blacknbunny** [comment]
https://github.com/blacknbunny/blacknbunny.github.io

**Comment by DirtyF** [comment]
Add the following in your `_config.yml`:

```yaml
exclude:
 - vendor/bundle/
```

**Comment by ashmaroli** [comment]
@DirtyF Strange.. Shouldn't `vendor/bundle` have been *excluded by default*..?
