### ISSUE TITLE
Jekyll error in Jekyll 3.8.4 : Liquid Exception: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by vladimireduardo** [jekyll/jekyll#7328]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  Mac OS X  10.14       |
| `jekyll`       | 3.8.4   |
| `github-pages`    | No   |
| `ruby`          | 2.4      |
| `gem`          | 2.7.7   |
| `bundler`    | 1.16.6  |

---

## Current Behavior

```
jekyll new myblog
cd myblog
bundle exec jekyll serve

Configuration file: /Users/vladimirestrada/code/myblog/_config.yml
            Source: /Users/vladimirestrada/code/myblog
       Destination: /Users/vladimirestrada/code/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
  Liquid Exception: no implicit conversion of nil into String in /_layouts/default.html
jekyll 3.8.4 | Error:  no implicit conversion of nil into String
```

**Comment by vladimireduardo** [comment]
> Please provide a public repo when we can reproduce this issue
> `bundle exec jekyll build --trace`should give more info.

https://github.com/vladimireduardo/jekyllblog

**Comment by DirtyF** [comment]
>   Liquid Exception: no implicit conversion of nil into String in /_layouts/default.html

We can't help you without having access to a public repo or at least the incriminated file.

**Comment by ashmaroli** [comment]
@vladimireduardo The repo seems to contain just a boilerplate site generated with `jekyll new`
Could you run the following command and post the *entire* output here..?
Thanks.
```
bundle exec jekyll build --verbose --trace
```

**Comment by vladimireduardo** [comment]
> @vladimireduardo The repo seems to contain just a boilerplate site generated with `jekyll new`
> Could you run the following command and post the _entire_ output here..?
> Thanks.
> 
> ```
> bundle exec jekyll build --verbose --trace
> ```

Logging at level: debug
Configuration file: /Users/vladimirestrada/code/myblog/_config.yml
           Theme: minima
    Theme source: /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/minima-2.5.0
       Requiring: jekyll-feed
       Requiring: jekyll-seo-tag
       Requiring: jekyll-feed
          Source: /Users/vladimirestrada/code/myblog
     Destination: /Users/vladimirestrada/code/myblog/_site
Incremental build: disabled. Enable with --incremental
    Generating... 
     EntryFilter: excluded /Gemfile
     EntryFilter: excluded /Gemfile.lock
         Reading: _posts/2018-10-21-welcome-to-jekyll.markdown
     Jekyll Feed: Generating feed for posts
      Generating: JekyllFeed::Generator finished in 0.001962 seconds.
       Rendering: _posts/2018-10-21-welcome-to-jekyll.markdown
Pre-Render Hooks: _posts/2018-10-21-welcome-to-jekyll.markdown
Rendering Liquid: _posts/2018-10-21-welcome-to-jekyll.markdown
       Requiring: rouge
Rendering Markup: _posts/2018-10-21-welcome-to-jekyll.markdown
Rendering Layout: _posts/2018-10-21-welcome-to-jekyll.markdown
   Layout source: theme
Liquid Exception: no implicit conversion of nil into String in /_layouts/default.html
/Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer.rb:27:in `join': no implicit conversion of nil into String (TypeError)
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer.rb:27:in `file'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/tags/include.rb:167:in `load_cached_partial'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/tags/include.rb:135:in `render'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/liquid-4.0.1/lib/liquid/block_body.rb:102:in `render_node_to_output'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/liquid-4.0.1/lib/liquid/block_body.rb:91:in `render'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/liquid-4.0.1/lib/liquid/template.rb:208:in `block in render'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/liquid-4.0.1/lib/liquid/template.rb:242:in `with_profiling'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/liquid-4.0.1/lib/liquid/template.rb:207:in `render'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/liquid-4.0.1/lib/liquid/template.rb:220:in `render!'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:126:in `render_liquid'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:195:in `render_layout'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:158:in `place_in_layouts'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:88:in `render_document'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/renderer.rb:62:in `run'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:479:in `render_regenerated'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:463:in `each'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:463:in `block in render_docs'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:462:in `each_value'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:462:in `render_docs'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:191:in `render'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/site.rb:71:in `process'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/command.rb:28:in `process_site'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:65:in `build'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:36:in `process'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/gems/jekyll-3.8.4/exe/jekyll:15:in `<top (required)>'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/bin/jekyll:23:in `load'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/bin/jekyll:23:in `<main>'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
from /Users/vladimirestrada/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by ashmaroli** [comment]
@vladimireduardo We're sorry that you're facing issues with a boilerplate site.
I've pushed a branch to help debugging this issue.

I request you to *edit your `Gemfile` to point to that branch* and post the trace output here:
1. Edit your Gemfile:
    ```ruby
    gem "jekyll", git: "https://github.com/jekyll/jekyll.git", branch: "debug-7328"
    ```
2. Install custom version:
    ```
    bundle install
    ```
3. Build your site
    ```
    bundle exec jekyll build --trace
    ```

**Comment by vladimireduardo** [comment]
i updated to jekyll 3.8.5 and bundler 1.17.1 and works fine!
