### ISSUE TITLE
favicon.ico not found

### ISSUE THREAD

**Issue by rfschafer** [jekyll/jekyll#7329]
During step five on the page [https://jekyllrb.com/docs/](url), I ran `bundle exec jekyll serve`, which successfully ran. I made it to "Jekyll Feed: generating feed for posts", which also successfully ran. However, I then received the error "ERROR `/favicon.ico' not found."

**Comment by DirtyF** [comment]
Like some browsers, Webrick server is looking for a `favicon.ico` flle by default, feel free to add your own custom favicon or type `touch favicon.ico` to create an empty file and get rid of this error.

**Comment by DirtyF** [comment]
> Do I run `touch favicon.ico` in the root folder?

Yes, as error message is looking for a  `/favicon.ico' in your website.

> Is it necessary for this process to finish to start blogging?

You can start blogging by adding content in drafts or posts folder. the `serve`command is only here to give you a local preview of your site. It won't quit until you hit CTRL-C to stop the server.

Before you push your content to a git repository, make sure bundle exec jekyll build exit without error.

I encourage you to [join our forum to ask questions about Jekyll's usage,](http://talk.jekyllrb.com) this repo is dedicated to documented bugs only.

**Comment by chrisfinazzo** [comment]
If I understand your comment correctly, then yes, this is the default behavior.
