### ISSUE TITLE
Syntax highligt with double brackets

### ISSUE THREAD

**Issue by pjc0247** [jekyll/jekyll#7330]
Texts are missing when I trying to use double brackets ({{ }}).

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |    Ubuntu on Windows     |
| `jekyll`         |  3.8.4 |

---

## Current Behavior

![image](https://user-images.githubusercontent.com/1961216/47346774-cfb06200-d6e8-11e8-81e3-953722fee424.png)

## Code Sample

![image](https://user-images.githubusercontent.com/1961216/47346976-3e8dbb00-d6e9-11e8-9a3d-93d64020981e.png)

**Comment by DirtyF** [comment]
[As mentioned in the docs](https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting);

> If you are using a language that contains curly braces, you will likely need to place` {% raw %}` and `{% endraw %}` tags around your code.

**Comment by ashmaroli** [comment]
@pjc0247 `{% %}` and `{{ }}` are detected as Liquid constructs
You'll have to enclose them in `{% raw %} {% endraw %}` to bypass the Liquid Parser:
```
    ```ruby
    name = "jinwoo";
    puts (`Hello, my name is {% raw %}{{name}}{% endraw %}.`);
    ```
```

**Comment by pjc0247** [comment]
Okay, got it.
but it would be nicer if you have some exceptional handlings since this is a code area.

**Comment by ashmaroli** [comment]
Hopefully, Jekyll 4.0 might "enhance" Jekyll's `{% highlight %}` to behave like Liquid's Raw tag. Though, the triple-backticks fencing will remain as is currently..
