### ISSUE TITLE
Liquid filter to reverse sorted list/array?

### ISSUE THREAD

**Issue by jelizaga** [jekyll/jekyll#7331]
Version 3.8.4. on Ubuntu 18.04. Say I have made an array that I want to print in reverse order:

```
{% assign words = 'swag, yolo, hi' | split: ", " | sort: 'last' %}

{% for word in words %}

    <p>{{word}}</p>

{% endfor %}
```

Even with `sort: 'last'`, this will print as:

```
swag
yolo
hi
```

Maybe it's `'first'`. I try that. The output is still

```
swag
yolo
hi
```

with `'first'`.

I've been trying to sort a collection in Jekyll by some page front-matter, and `sort` works--it lists everything in order, by the numbers I gave them (not by title or date), first to last, but what if I want it last to first? If I sort: `'last'`, it's still sorted first to last. The `last` option must be broken, right?

Here's a screenshot: https://i.imgur.com/7Fxep9A.png

**Comment by DirtyF** [comment]
https://shopify.github.io/liquid/filters/reverse/

**Comment by pathawks** [comment]
I don’t think this is listed in our docs (that’s where I was looking for it). Perhaps we need to add it?

**Comment by oe** [comment]
@pathawks I don't think we need to restate what's already in the liquid docs, but a link there could help, for sure.

**Comment by DirtyF** [comment]
https://jekyllrb.com/docs/liquid/ has a link to Liquid docs then to `our` filters and tags
https://jekyllrb.com/docs/liquid/filters/ has a link to Liquid filers

@pathawks you want us to copy all filters with link to Liquid docs?  Like this?

### Standard Liquid filters

- [abs](https://shopify.github.io/liquid/filters/abs/)
- [append](https://shopify.github.io/liquid/filters/append/)
- [at_least](https://shopify.github.io/liquid/filters/append/)
- [at_most](https://shopify.github.io/liquid/filters/at_most/)
- [capitalize](https://shopify.github.io/liquid/filters/capitalize/)
- [ceil](https://shopify.github.io/liquid/filters/ceil/)
- [compact](https://shopify.github.io/liquid/filters/compact/)
- [concat](https://shopify.github.io/liquid/filters/concat/)
- [date](https://shopify.github.io/liquid/filters/date/)
- [default](https://shopify.github.io/liquid/filters/default/)
- [divided_by](https://shopify.github.io/liquid/filters/divided_by/)
- [downcase](https://shopify.github.io/liquid/filters/downcase/)
- [escape](https://shopify.github.io/liquid/filters/escape/)
- [escape_once](https://shopify.github.io/liquid/filters/escape_once/)
- [first](https://shopify.github.io/liquid/filters/first/)
- [floor](https://shopify.github.io/liquid/filters/floor/)
- [join](https://shopify.github.io/liquid/filters/join/)
- [last](https://shopify.github.io/liquid/filters/last/)
- [lstrip](https://shopify.github.io/liquid/filters/lstrip/)
- [map](https://shopify.github.io/liquid/filters/map/)
- [minus](https://shopify.github.io/liquid/filters/minus/)
- [modulo](https://shopify.github.io/liquid/filters/modulo/)
- [newline_to_br](https://shopify.github.io/liquid/filters/newline_to_br/)
- [plus](https://shopify.github.io/liquid/filters/plus/)
- [prepend](https://shopify.github.io/liquid/filters/prepend/)
- [remove](https://shopify.github.io/liquid/filters/remove/)
- [remove_first](https://shopify.github.io/liquid/filters/remove_first/)
- [replace](https://shopify.github.io/liquid/filters/replace/)
- [replace_first](https://shopify.github.io/liquid/filters/replace_first/)
- [reverse](https://shopify.github.io/liquid/filters/reverse/)
- [round](https://shopify.github.io/liquid/filters/round/)
- [rstrip](https://shopify.github.io/liquid/filters/rstrip/)
- [size](https://shopify.github.io/liquid/filters/size/)
- [slice](https://shopify.github.io/liquid/filters/slice/)
- [sort](https://shopify.github.io/liquid/filters/sort/)
- [sort_natural](https://shopify.github.io/liquid/filters/sort_natural/)
- [split](https://shopify.github.io/liquid/filters/split/)
- [strip](https://shopify.github.io/liquid/filters/strip/)
- [strip_html](https://shopify.github.io/liquid/filters/strip_html/)
- [strip_newlines](https://shopify.github.io/liquid/filters/strip_newlines/)
- [times](https://shopify.github.io/liquid/filters/times/)
- [truncate](https://shopify.github.io/liquid/filters/truncate/)
- [truncatewords](https://shopify.github.io/liquid/filters/truncatewords/)
- [uniq](https://shopify.github.io/liquid/filters/uniq/)
- [upcase](https://shopify.github.io/liquid/filters/upcase/)
- [url_decode](https://shopify.github.io/liquid/filters/url_decode/)
- [url_encode ](https://shopify.github.io/liquid/filters/url_encode/)

**Comment by pathawks** [comment]
If you don’t think it’s necessary, I defer to your judgment 👍🏼

**Comment by DirtyF** [comment]
@pathawks well, approve the PR and it's a done deal 🤝
