### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by carolinamgmarques** [jekyll/jekyll#7332]
Hi!

I'm trying to install Jekyll and get always the same error:
ERROR:  Could not find a valid gem 'jekyll' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/specs.4.8.gz)

Can anyone help?
Thanks!

**Comment by DirtyF** [comment]
👋 

I do not reproduce your issue.

```
