### ISSUE TITLE
Jekyll failing to build GitHub Pages site

### ISSUE THREAD

**Issue by DragonOsman** [jekyll/jekyll#7349]
My code is here: https://github.com/DragonOsman/DragonOsman.github.io.  A bit ago, I got an email from Jekyll saying that the build had failed.  And my stylesheet doesn't seem to work completely; locally the space between the div with class "container-fluid" and the element with the class "jumbotron" is gone, but when I upload the code to GitHub and try to visit the site there, the space is still there.  Also, I put a 10 pixel left margin on the image, but that also isn't showing up on the GitHub Pages version of the site.  

And I also changed the favicon icon and logo of the site, but the one in the browser tab is still the same as before.  I made sure to delete the old files and I'm sure that I have the newer ones locally.  I also uploaded them all to GitHub.  I don't know what's wrong.  

I'm using Windows 10 Home edition, by the way.

**Comment by DirtyF** [comment]
Please contact GitHub support, this repository is intended for bugs only.
