### ISSUE TITLE
Jekyll site created using bundle showing post inside gem package

### ISSUE THREAD

**Issue by raja-ashok** [jekyll/jekyll#7356]
Created a new site using bundle as per [doc](https://jekyllrb.com/tutorials/using-jekyll-with-bundler/), then added jekyll-paginated as dependency in [gemfile](https://jekyllrb.com/docs/pagination/). Finally the site is showing some of the post present inside `vendor/bundle/ruby/2.3.0/gems/jekyll-paginate-1.1.0/spec/source/_posts/`. More over `--skip-bundle` option is not available in `jekyll new` command. I am using jekyll `3.0,1` on Ubuntu 16.04.

Is there any way to skip `vendor` folder while building ?

**Comment by DirtyF** [comment]
1. gem update --system; gem install jekyll should help you upgrade to latest jekyll on your system 
2. You can exclude files from build with the [exclude configuration option ](https://jekyllrb.com/docs/configuration/options/#global-configuration) 

/cc @mkasberg if we need to complete this tuturial on bundler

**Comment by raja-ashok** [comment]
I am new to `ruby`. I Installed `jekyll` from `apt` package using `sudo apt install jekyll`. Is this not the right way of installing `jekyll` ?

**Comment by DirtyF** [comment]
See our docs: https://jekyllrb.com/docs/installation/ubuntu/

**Comment by mkasberg** [comment]
@DirtyF Thanks for mentioning me, I think `exclude: ["vendor/bundler"]` is the correct solution and I'll work on a PR in the next few days to update the tutorial with that info.

@raja-ashok The reference DirtyF mentioned from the docs is the best way to install and is "officially" supported by the Jekyll team. That way, you'll always be able to update to the most recent version with the latest changes and bug fixes.

Just to answer your question more completely: If you install with apt, you'll be using the version packaged by the Ubuntu team. It's not "wrong" to install it that way, but there are a few downsides & caveats:
* It might not be the most recent version.
* Other documentation that mentions using `gem` to manage Jekyll won't work.
* In particular, mixing version control systems (installing with apt, and then running `sudo gem update jekyll` or similar) might lead to a plethora of other problems.

@DirtyF I couldn't find anywhere this ^ is discussed in the documentation. I wonder if you think it would be appropriate to add somewhere? Or maybe it's better suited for a different platform, like StackOverflow (or SuperUser)?

**Comment by mkasberg** [comment]
After spending a little bit of time with this, I believe the tutorial is probably OK as-is (no PR necessary). The [default configuration](https://jekyllrb.com/docs/configuration/default/) sets `exclude` to a setting that includes `vendor/bundle`, and I've verified that this default is still in effect when completing the tutorial.

To reproduce the error raja-ashok describes, I had to add a custom `exclude` line to my `_config.yml` file. But I consider modifying the excludes in `_config.yml` beyond the scope of that specific tutorial. Let me know if you disagree or have any other thoughts.

**Comment by raja-ashok** [comment]
Yes. Latest `jekyll 3.8.5` excludes `vendor/bundle` by default. It was not excluded in my older version `3.0.1`.

**Comment by DirtyF** [comment]
@mkasberg Thanks for looking into this. We could encourage Linux users to compare the default version installed by their package manager with the current version. `3.0.1` was released three years ago, and our online documentation is updated for the latest stable version. To install a corresponding version of the docs, you have to [install `jekyll-docs`](https://github.com/jekyll/jekyll-docs#installing).  You might as well install the latest version following our current docs. Happy to review a PR, I'm no Linux user so it's best it this comes from a Linux user from the community.
