### ISSUE TITLE
Jekyll auto regeneration loop never stops

### ISSUE THREAD

**Issue by matthodan** [jekyll/jekyll#736]
When using the master branch, I noticed that Jekyll's auto regeneration never stops regenerating.  It looks like Directory Watcher is watching the `_site` output directory for changes and regenerates the site whenever there is a change to this location.  As you might expect, this becomes self perpetuating and never ends.

**Comment by pavanpodila** [comment]
I am still seeing this issue in jekyll 2.5.3. The regeneration loop is never ending.

**Comment by parkr** [comment]
Ensure that you have the latest `jekyll-watch` and have `exclude`'d generated files.

**Comment by pavanpodila** [comment]
Yup that was the problem. Thanks @parkr

**Comment by ramsey** [comment]
I'm running into the same issue. It seems to be restricted to the content in a specific Markdown file. I can remove all the content from the file, run `jekyll serve`, and then save the file over and over, and it only regenerates a couple of files each time. When I add the content back to the file and save, Jekyll appears to get stuck in a regeneration loop. I have to `Ctrl+C` out of `jekyll serve` to get it to stop.

I haven't been able to determine whether it's specific Markdown elements in the file that's causing the loop or not.

I have Jekyll 2.5.3 and `jekyll-watch` 1.2.1.

I added the following to my `_config.yml` file, but it doesn't appear to help with this problem:

```
exclude: ["_site/"]
```

**Comment by fred-o** [comment]
I also have this problem. I think I've narrowed it down to posts using the octopress codefence and/or codeblock plugins. The regular jekyll highlight plugin seems fine though.

**Comment by fred-o** [comment]
Solved this by adding '.code-highlighter-cache' to `exclude`:

exclude: [ 'Gemfile*', '_site/', '.code-highlighter-cache' ]

**Comment by ramsey** [comment]
That did the trick! Thanks for the tip.

I am, in fact, using the `octopress-codefence` plugin, which created the `.code-highlighter-cache/` directory. That's what was causing this.

**Comment by theaspect** [comment]
same for lunr constantly regeneration index

**Comment by envygeeks** [comment]
This ticket is being locked. If you have an issue please file a new ticket instead of practicing the art of necromancy.  It has hard to maintain actual issues against comments if this happens.
