### ISSUE TITLE
Website is out of date from the repo: has bug in tutorial code

### ISSUE THREAD

**Issue by mrcoles** [jekyll/jekyll#7363]
## Motivation

The step-by-step tutorial on the website does not reflect some of the code in the github repo.

## Suggestion

Update the jekyll docs https://jekyllrb.com/docs/step-by-step/09-collections/ to have the latest code.

The step-by-step [09-collections markdown file](https://github.com/jekyll/jekyll/blame/master/docs/_docs/step-by-step/09-collections.md#L236) does not match what is currently on the site.

The site is missing the "| first" at the end of the `assign where` tag, which creates a broken result.

**Comment by DirtyF** [comment]
@mrcoles I do not see any problem.

https://jekyllrb.com/docs/step-by-step/09-collections/#link-to-authors-page has the `first` filter …if you scroll horizontally.

Site is automatically built from the repo.

**Comment by mrcoles** [comment]
Hrm, I’m seeing it there now too. I remember checking and doing a full scroll to the right, but maybe I somehow compared it to the other section when I did… lol, well, I’m closing this. Cheers 😄
