### ISSUE TITLE
Jekyll LiveReload not working

### ISSUE THREAD

**Issue by datadeveb** [jekyll/jekyll#7364]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | win10 |
| `jekyll`         | Latest 3.8.5  |
| `github-pages`   | Latest     |

---

## Expected Behaviour
It needs to be updated at the time I saved my files.

## Current Behavior
...
LiveReload address: http://127.0.0.1:35729
  JekyllAdmin mode: production
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
        LiveReload: Browser connected

But not working liverelaod on pages.

**Comment by ashmaroli** [comment]
@datadeveb Have you tried without the `jekyll-admin` plugin..?

**Comment by DirtyF** [comment]
@datadeveb not helping, but FYI workin' fine on your website on macOS with a basic `Gemfile`, even with `jekyll-admin`.

**Comment by datadeveb** [comment]
I tried. Not work.

Note: Is there a problem with the security program?

**Comment by DirtyF** [comment]
Most probably, a config problem, not a Jekyll bug. 
Please move this discussion to http://talk.jekyllrb.com to engage with the community.

**Comment by ashmaroli** [comment]
@datadeveb I had issues **regenerating your site** with `jekyll-admin` on Windows 7.. Though `--livereload` works fine at my end **without `jekyll-admin`**..

**Comment by datadeveb** [comment]
I tried... Nothing... 
I opened topic: http://talk.jekyllrb.com/t/jekyll-livereload-not-working-on-windows-10/2336
