### ISSUE TITLE
error with inline octicons

### ISSUE THREAD

**Issue by cup** [jekyll/jekyll#7371]
If you use this Markdown:

~~~
{% octicon file %}world
~~~

you get this:

~~~
<svg class="octicon octicon-file" viewBox="0 0 12 16" version="1.1" width="12"
height="16" aria-hidden="true"><path fill-rule="evenodd" d="M6 5H2V4h4v1zM2
8h7V7H2v1zm0 2h7V9H2v1zm0 2h7v-1H2v1zm10-7.5V14c0 .55-.45 1-1 1H1c-.55
0-1-.45-1-1V2c0-.55.45-1 1-1h7.5L12 4.5zM11 5L8 2H1v12h10V5z"></path></svg>
<p>world</p>
~~~

notice that the icon is no longer inline - its on a line before the text -
workaround is to use HTML:

~~~
<p>{% octicon file %}world</p>
~~~

these produce inline as expected:

~~~
hello{% octicon file %}
hello{% octicon file %}world
~~~

also note that normal image markdown produces inline as well:

~~~
![](something)world
hello![](something) 
hello![](something)world
~~~

**Comment by ashmaroli** [comment]
@cup This tag is not a Jekyll built-in.
Please ask for support at the following repository:
https://github.com/primer/octicons/tree/master/lib/octicons_jekyll

**Comment by cup** [comment]
https://github.com/primer/octicons/issues/259

**Comment by cup** [comment]
@ashmaroli can you make another suggestions - primer issue was closed

**Comment by cup** [comment]
https://github.com/gettalong/kramdown/issues/553
https://github.com/jekyll/jekyll/issues/7371
https://github.com/primer/octicons/issues/259
