### ISSUE TITLE
falsy site.title

### ISSUE THREAD

**Issue by cup** [jekyll/jekyll#7387]
With http://github.com/pages-themes/primer, a header shows on every page because
of this code:

~~~html
{% if site.title and site.title != page.title %} 
 <h1><a href="{{ "/" | absolute_url }}">{{ site.title }}</a></h1> 
{% endif %} 
~~~

you should be able to remove under one of these conditions:

1. site.title == page.title
2. site.title == falsy

we dont want to use number 1, as every page would have the same title. for 2, we
should be able to use `nil` or `false`:

http://shopify.github.io/liquid/basics/truthy-and-falsy

however setting `title: nil` or `title: false` in `_config.yml` has no effect.

**Comment by cup** [comment]
https://github.com/pages-themes/primer/issues/21

**Comment by ashmaroli** [comment]
@cup this report has nothing to do with Jekyll.
Jekyll **does not set {{ site.title }} automatically** under the hood

For support regarding usage of themes and plugins, please approach our community forum at:
http://talk.jekyllrb.com

**Comment by cup** [comment]
https://github.com/jekyll/github-metadata/issues/146
https://github.com/jekyll/jekyll/issues/7387
https://github.com/pages-themes/primer/issues/21

**Comment by cup** [comment]
i found a better hack for this. according to here:

http://github.com/jekyll/github-metadata/blob/6aea65a/lib/jekyll-github-metadata/site_github_munger.rb#L52

if `site.name` is set in `_config.yml`, then `site.title` is not automatically
set, so it will remain "falsy"

so you just need to add `name: hello world` or similar to `_config.yml`
