### ISSUE TITLE
Bundler LoadError on jekyll serve

### ISSUE THREAD

**Issue by osiyuk** [jekyll/jekyll#7391]
- I ran `jekyll doctor` to check my configuration
  - I read the contributing document at https://jekyllrb.com/docs/contributing/

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     Debian/Linux       |
|`ruby`|2.3.3|
| `jekyll`         | 3.8.5     |
| `github-pages`   | No     |

---

## Expected Behaviour

Serve newly created site with `jekyll new ..` and `jekyll serve`

## Current Behavior

I run steps in https://jekyllrb.com/docs/
I installed gems locally as written in https://jekyllrb.com/docs/installation/ubuntu/
I installed `jekyll` gem without `bundler`. I want to run website without bundler.
I created new website, `cd` into it and run several commands:
- `jekyll serve`
- `jekyll doctor`
- `jekyll`
All returns this:
```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/saradomin/gems/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:48:in `require_from_bundler'
	from /home/saradomin/gems/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
	from /home/saradomin/gems/bin/jekyll:22:in `load'
	from /home/saradomin/gems/bin/jekyll:22:in `<main>'
```

**Comment by osiyuk** [comment]
I still see this as a bug. I do not expect to install gem and gracefully find that it needs another gem. And another...

I have overcome this behavior bu using ```jekyll new --blank```

**Comment by DirtyF** [comment]
Jekyll works with gems and bundler is the way to handle gems. Once you installed bundler you should be fine.
