### ISSUE TITLE
Jekyll docs 3.8.5

### ISSUE THREAD

**Issue by space-otter** [jekyll/jekyll#7399]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |   macOS Mojave Version 10.14.1 |
| `jekyll`         | Latest     |
| `github-pages`   | No     |

---

## Expected Behaviour

I just wanted to run `jekyll docs` for the local documentation.

## Current Behavior

I use `rbenv` for my ruby-version-managment and `bundle` for my gems dependencies.
When I try to use `jekyll docs` the following message appears:

`You must install the 'jekyll-docs' gem version = 3.8.5 to use the 'jekyll docs' command.`

If I use `jekyll 3.8.4` the error disappears as expected.

I am a bit confused because [Jekyll Docs](https://jekyllrb.com/docs/) is up to date with `3.8.5`.

**Comment by DirtyF** [comment]
Thanks for the reminder. `jekyll-docs` gem just got updated to v3.8.5, you can install latest version and run `jekyll _3.8.5_ doc`
