### ISSUE TITLE
For Loop not showing anything

### ISSUE THREAD

**Issue by OwenHunter** [jekyll/jekyll#7402]
When I run the code #`---
layout: home
---

<head>
    
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/cirrus-ui@0.5.4/dist/cirrus.min.css">
</head>
<body>
    <div class="home">
        {% for post in site.posts %}
            <div class="card">
                <div class="card-container">
                    <div class="card-image" style="background-image: url(https://images.unsplash.com/photo-1467952497026-86722ef1916f?dpr=1.25&amp;auto=compress,format&amp;fit=crop&amp;w=1199&amp;h=799&amp;q=80&amp;cs=tinysrgb&amp;crop=)"></div>

                    <div class="title-container">
                        <p class="title">{{ post.title }}</p>
                        <span class="subtitle">{{ post.subtitle }}</span>
                    </div>
                </div>
                <div class="content">
                    <p>{{ post.short }}</p>
                </div>
                <div class="action-bar center">
                    <a href="{{ post.url | prepend: site.baseurl }}"><button class="btn">VISIT POST</button></a>
                    <a href="{{ post.project | prepend: site.baseurl }}"><button class="btn">VISIT PROJECT</button></a>
                </div>
            </div>
        {% endfor %}
    </div>
</body>`
The for loop doesnt end up showing anything, only a blank page. The for loop does run without any errors, but nothing actually shows. I have a post in my _posts directory already

**Comment by ashmaroli** [comment]
@OwenHunter We have an "Issue Template" for a reason..
It helps us get to the problem quicker.

Now, please answer the following questions:
- What OS / Platform are you working from..?
- What version of Jekyll are you using?
- What theme are you using?
- Are you using any plugins?
- Are you using the `github-pages` gem..?

**Comment by OwenHunter** [comment]
@ashmaroli apologies, I have solved this as well now.
