### ISSUE TITLE
feat: page.collection property

### ISSUE THREAD

**Issue by derpmarine168** [jekyll/jekyll#7415]
## Summary

add a property to `page` that is the name of the collection 

## Motivation

This is so i can easily diferentiate between colections in my SEO include. for example, 
```html
<meta property="og:type" content="{% if page.collection == posts %}article{% elsif page.collection == authors %}profile{% else %}website{% endif %}">
```
I'd also use it to include diferent CSS and JS files in my posts, main pages, etc. via my tags include. (all of my layouts are inside my default layout)
## Guide-level explanation

would go into <https://jekyllrb.com/docs/variables/#page-variables>.
something like:
| `page.collection`  | the collection the page is in. |

## Reference-level explanation

If it isn't in a collection, it should be null or a empty string.

## Drawbacks

Extra few lines of code to maintain.

**Comment by ashmaroli** [comment]
@derpmarine168 `{{ page.collection }}` property is already available in Jekyll. Feel free to submit a pull request to add the description in our documentation.

*P.S. There is a small error in the Liquid iteration you posted above. Strings should be enclosed in quotes:*
```html
<meta property="og:type" content="{% if page.collection == 'posts' %}article{% elsif page.collection == 'authors' %}profile{% else %}website{% endif %}">
```
