### ISSUE TITLE
Update whitelist

### ISSUE THREAD

**Issue by cup** [jekyll/jekyll#7416]
If you visit here:

http://jekyllrb.com/docs/github-pages

it shows this link:

http://help.github.com/articles/configuring-jekyll-plugins

However comparing it against:

http://github.com/github/pages-gem/blob/fb5c3f2/lib/github-pages/plugins.rb#L22-L41

reveals that these are missing:

- jekyll-commonmark-ghpages
- jekyll-octicons
- jekyll-remote-theme

**Comment by cup** [comment]
https://github.com/github/pages-gem/issues/604

**Comment by cup** [comment]
@ashmaroli:

1. i never mentioned http://pages.github.com/versions - i mentioned
http://help.github.com/articles/configuring-jekyll-plugins

2. http://pages.github.com/versions is a website - not a repository - so im not
sure how i would submit a PR to a website

**Comment by cup** [comment]
@ashmaroli http://pages.github.com/versions is not valid either

https://github.com/github/pages-gem/issues/604

**Comment by pathawks** [comment]
There is nothing on our end to update.
