### ISSUE TITLE
Jekyll won't generate "dot" files

### ISSUE THREAD

**Issue by jacobthurman** [jekyll/jekyll#742]
Jekyll won't generate filenames that start with a dot (e.g. .htaccess). It fails in two scenarios:

---

First:

_config.yml contains the option:
    include:
      - .htaccess

A file called .htaccess will not be generated in this case.

---

Second:
A file called htaccess (no dot) has the following front matter:
    ---
    permalink: .htaccess
    ---

A file called .htaccess is not generated in this case.

---

Oddly, if I have the _config option above, and then put the following front matter in a file called .htaccess (with the dot), the file is generated as expected (with no dot):
    ---
    permalink: htaccess
    ---

**Comment by htmelvis** [comment]
I have noticed that in v. 2.5.3 that the dotfiles (.htaccess) is generated as a normal file and included in the compilation. Once added to the exclude the .htaccess is still compiled and placed in the destination dir. Has anyone else experienced this? 

The docs: http://jekyllrb.com/docs/configuration/ state that dotfiles are excluded by default. I have found this not to be the case with my .htaccess file.

**Comment by jaybe-jekyll** [comment]
.htaccess is a default `include` value.

**Comment by htmelvis** [comment]
That seems a bit odd to do and the docs state: 
<img width="667" alt="screen shot 2015-09-02 at 12 57 04 pm" src="https://cloud.githubusercontent.com/assets/1952926/9638047/427fce4c-5172-11e5-91d4-26eaf100a99e.png">

It also seems that no matter included or excluded the file is still compiled and placed in the ```destination:```

**Comment by jaybe-jekyll** [comment]
I agree; I do not think `.htaccess` (or anything) should be included by default.

I could see at some point why it may have been added in order to alleviate inquiries.

Are you using jekyll v3.* with regeneration? Try building with a full rebuild to ensure you're not seeing ghosts.

**Comment by parkr** [comment]
> I agree; I do not think .htaccess (or anything) should be included by default.

Someone want to submit a PR and research the reasoning for adding it in the first place? Probably somewhere in our Git history.

**Comment by htmelvis** [comment]
I'm on (2.5.3) I have simply removed .htaccess from the project and placed in a deployment config file because I cannot have my htaccesses swapping at staging/live. 

I have no problem looking for it.

**Comment by htmelvis** [comment]
I think this may be it...
<img width="973" alt="screen shot 2015-09-02 at 2 18 10 pm" src="https://cloud.githubusercontent.com/assets/1952926/9640059/86ac7bbe-517d-11e5-8b8b-8247610a793d.png">

**Comment by envygeeks** [comment]
If excluding it does not work please file a bug for this particular issue instead of necromancing, thanks!

**Comment by envygeeks** [comment]
Edit: Didn't see that @parkr took up the issue.  Sorry.
