### ISSUE TITLE
Doesn't watch for changes in files whose name contain an excluded directory as substring

### ISSUE THREAD

**Issue by egmontkob** [jekyll/jekyll#7421]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Ubuntu 18.10   |
| `jekyll`         | 3.8.5     |
| `github-pages`   | No     |

---

I'm building a site using the [just-the-docs](https://github.com/pmarsceill/just-the-docs) theme. As per that theme, `_config.yml` contains

    exclude: [..., "lib/", "bin/", ...]

## Expected Behaviour

A locally running `jekyll serve` should catch up with any change in the data files I'm editing and regenerate the pages.

## Current Behavior

If one of my files happens to contain the substring "lib" or "bin" in its name, changes to that file aren't automatically noticed by Jekyll. For example I'm modifying a file called `docs/combine.md` ("bin" is a substring of "combine") then upon saving this file no action is taken by `jekyll serve`, it still serves the old version.

Upon restarting `jekyll serve`, the pages are regenerated properly. That is, the source file is read and processed as expected, just not being watched for changes.

The bug occurs if the filename contains as a substring one of the filenames specified in `excludes`, _and_ that excluded thing (e.g. the `bin/` directory from the project's root) does indeed exist. E.g. add into `excludes` an entry of `"foo/"`, restart `jekyll serve`, changes to the file `docs/foobar.md` are noticed by `jekyll` as expected. Create a directory called `foo` in the project root, restart `jekyll serve`, changes to `docs/foobar.md` are no longer noticed.

Note: I haven't checked the behavior related to `exclude` entries that contain no trailing slash, or contain a wildcard.

**Comment by ashmaroli** [comment]
@egmontkob This was a bug in our `jekyll-watch` plugin and has been fixed in its `master` branch.
Pointing your Gemfile to the repository should resolve your issue:

```ruby
# Gemfile

gem "jekyll", "~> 3.8"
gem "jekyll-watch", :git => "https://github.com/jekyll/jekyll-watch.git", :branch => "master"
```

**Comment by egmontkob** [comment]
Amazing, thanks a lot!
