### ISSUE TITLE
Disable evaluation of ununused themes

### ISSUE THREAD

**Issue by Krinkle** [jekyll/jekyll#7426]
## My environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     macOS      |
| `jekyll`         | 3.7.3     |
| `github-pages`   | 187     |

---

## Expected behaviour

Able to build a site successfully even if an unused dependency contains a scss file that won't parse for some reason.

## Current behaviour

See https://github.com/jekyll/jekyll-sass-converter/issues/84 for details of the underlying bug. In short, github-pages comes with various themes, including jekyll-theme-primer, which is failing to parse for reasons I don't understand.

The thing is, the static site I was working on ([qunitjs/qunit](https://github.com/qunitjs/qunit/tree/b5208397d1bf27c67c5878a92af509762f5ed718/docs)) doesn't any of these bundled themes. So I'm wondering whether it is intentional behaviour that these get evaluated and are able to break the build process.

**Comment by Krinkle** [comment]
@DirtyF Thanks for looking into this. I appreciate the input on a downstream pull request, that's really cool (at https://github.com/qunitjs/qunit/pull/1337). However, please note that this does not resolve the issue.

I encountered this issue exactly _because_ I am trying to switch from custom Gemfile to using github-pages. With plain Jekyll (out of sync with github-pages) is actually what is working fine.

See https://github.com/jekyll/jekyll-sass-converter/issues/84#issue-391405198 for the Gemfile under which I encounter this problem.

**Comment by DirtyF** [comment]
I wasn't able to reproduce your issue, it's working fine with GitHub Pages gem on my machine.

**Comment by Krinkle** [comment]
@DirtyF Thanks for trying. Might be something specific to my machine, or site config. I've pushed the branch to GitHub and below are the steps I use to reproduce the issue.

```
# system: macOS 10.13.6 (High Sierra)
$ brew uninstall --force ruby && brew install ruby && ruby --version
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

$ gem install bundler && bundle --version
Successfully installed bundler-1.17.2
Bundler version 1.17.2

# Jekyll site
$ cd qunitjs/qunit
$ git checkout origin/docs-gh-gem
... git head at 0982245

$ git clean -dffx
$ cd docs/
$ bundle install
$ bundle exec jekyll serve

Configuration file: /Users/krinkle/Development/qunit/docs/_config.yml
            Source: /Users/krinkle/Development/qunit/docs
       Destination: /Users/krinkle/Development/qunit/docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Invalid US-ASCII character "\xE2" on line 5
jekyll 3.7.4 | Error:  Invalid US-ASCII character "\xE2" on line 5
```

Note that since I started this issue, I'm now on github-pages 193 (jekll 3.7.4). Previously github-pages 187 (jekyll 3.7.3).

**Comment by ashmaroli** [comment]
@Krinkle You can provide us with more information by using the verbose and trace switches:
```
bundle exec jekyll build --verbose --trace
```

**Comment by Krinkle** [comment]
@ashmaroli 

<details><summary><code>$ bundle exec jekyll build --verbose --trace</code></summary>
<pre>
  Logging at level: debug
Configuration file: /Users/krinkle/Development/qunit/docs/_config.yml
      GitHub Pages: github-pages v193
      GitHub Pages: jekyll v3.7.4
         Requiring: jekyll-github-metadata
Dotenv not found. Skipping 
         Requiring: jekyll-seo-tag
         Requiring: jekyll-redirect-from
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
   GitHub Metadata: Initializing...
            Source: /Users/krinkle/Development/qunit/docs
       Destination: /Users/krinkle/Development/qunit/docs/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       EntryFilter: excluded /CNAME
       EntryFilter: excluded /README.md
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
        Generating: JekyllRedirectFrom::Generator finished in 0.018496 seconds.
        Generating: JekyllOptionalFrontMatter::Generator finished in 3.0e-05 seconds.
        Generating: JekyllReadmeIndex::Generator finished in 4.8e-05 seconds.
        Generating: Jekyll::Paginate::Pagination finished in 5.0e-06 seconds.
        Generating: JekyllRelativeLinks::Generator finished in 0.011438 seconds.
        Generating: JekyllDefaultLayout::Generator finished in 0.001312 seconds.
        Generating: JekyllTitlesFromHeadings::Generator finished in 7.9e-05 seconds.
         Rendering: config/QUnit.assert.md
  Pre-Render Hooks: config/QUnit.assert.md
  Rendering Liquid: config/QUnit.assert.md
  Rendering Markup: config/QUnit.assert.md
  Rendering Layout: config/QUnit.assert.md
         Rendering: callbacks/QUnit.begin.md
  Pre-Render Hooks: callbacks/QUnit.begin.md
  Rendering Liquid: callbacks/QUnit.begin.md
  Rendering Markup: callbacks/QUnit.begin.md
  Rendering Layout: callbacks/QUnit.begin.md
         Rendering: config/QUnit.config.md
  Pre-Render Hooks: config/QUnit.config.md
  Rendering Liquid: config/QUnit.config.md
  Rendering Markup: config/QUnit.config.md
  Rendering Layout: config/QUnit.config.md
         Rendering: callbacks/QUnit.done.md
  Pre-Render Hooks: callbacks/QUnit.done.md
  Rendering Liquid: callbacks/QUnit.done.md
  Rendering Markup: callbacks/QUnit.done.md
  Rendering Layout: callbacks/QUnit.done.md
         Rendering: config/QUnit.dump.parse.md
  Pre-Render Hooks: config/QUnit.dump.parse.md
  Rendering Liquid: config/QUnit.dump.parse.md
  Rendering Markup: config/QUnit.dump.parse.md
  Rendering Layout: config/QUnit.dump.parse.md
         Rendering: config/QUnit.extend.md
  Pre-Render Hooks: config/QUnit.extend.md
  Rendering Liquid: config/QUnit.extend.md
  Rendering Markup: config/QUnit.extend.md
  Rendering Layout: config/QUnit.extend.md
         Rendering: callbacks/QUnit.log.md
  Pre-Render Hooks: callbacks/QUnit.log.md
  Rendering Liquid: callbacks/QUnit.log.md
  Rendering Markup: callbacks/QUnit.log.md
  Rendering Layout: callbacks/QUnit.log.md
         Rendering: callbacks/QUnit.moduleDone.md
  Pre-Render Hooks: callbacks/QUnit.moduleDone.md
  Rendering Liquid: callbacks/QUnit.moduleDone.md
  Rendering Markup: callbacks/QUnit.moduleDone.md
  Rendering Layout: callbacks/QUnit.moduleDone.md
         Rendering: callbacks/QUnit.moduleStart.md
  Pre-Render Hooks: callbacks/QUnit.moduleStart.md
  Rendering Liquid: callbacks/QUnit.moduleStart.md
  Rendering Markup: callbacks/QUnit.moduleStart.md
  Rendering Layout: callbacks/QUnit.moduleStart.md
         Rendering: callbacks/QUnit.on.md
  Pre-Render Hooks: callbacks/QUnit.on.md
  Rendering Liquid: callbacks/QUnit.on.md
  Rendering Markup: callbacks/QUnit.on.md
  Rendering Layout: callbacks/QUnit.on.md
         Rendering: config/QUnit.push.md
  Pre-Render Hooks: config/QUnit.push.md
  Rendering Liquid: config/QUnit.push.md
  Rendering Markup: config/QUnit.push.md
  Rendering Layout: config/QUnit.push.md
         Rendering: config/QUnit.stack.md
  Pre-Render Hooks: config/QUnit.stack.md
  Rendering Liquid: config/QUnit.stack.md
  Rendering Markup: config/QUnit.stack.md
  Rendering Layout: config/QUnit.stack.md
         Rendering: callbacks/QUnit.testDone.md
  Pre-Render Hooks: callbacks/QUnit.testDone.md
  Rendering Liquid: callbacks/QUnit.testDone.md
  Rendering Markup: callbacks/QUnit.testDone.md
  Rendering Layout: callbacks/QUnit.testDone.md
         Rendering: callbacks/QUnit.testStart.md
  Pre-Render Hooks: callbacks/QUnit.testStart.md
  Rendering Liquid: callbacks/QUnit.testStart.md
  Rendering Markup: callbacks/QUnit.testStart.md
  Rendering Layout: callbacks/QUnit.testStart.md
         Rendering: assert/async.md
  Pre-Render Hooks: assert/async.md
  Rendering Liquid: assert/async.md
  Rendering Markup: assert/async.md
  Rendering Layout: assert/async.md
         Rendering: async.md
  Pre-Render Hooks: async.md
  Rendering Liquid: async.md
  Rendering Markup: async.md
  Rendering Layout: async.md
         Rendering: assert/deepEqual.md
  Pre-Render Hooks: assert/deepEqual.md
  Rendering Liquid: assert/deepEqual.md
  Rendering Markup: assert/deepEqual.md
  Rendering Layout: assert/deepEqual.md
         Rendering: assert/equal.md
  Pre-Render Hooks: assert/equal.md
  Rendering Liquid: assert/equal.md
  Rendering Markup: assert/equal.md
  Rendering Layout: assert/equal.md
         Rendering: assert/expect.md
  Pre-Render Hooks: assert/expect.md
  Rendering Liquid: assert/expect.md
  Rendering Markup: assert/expect.md
  Rendering Layout: assert/expect.md
         Rendering: index.md
  Pre-Render Hooks: index.md
  Rendering Liquid: index.md
  Rendering Markup: index.md
  Rendering Layout: index.md
         Rendering: config/index.md
  Pre-Render Hooks: config/index.md
  Rendering Liquid: config/index.md
  Rendering Markup: config/index.md
  Rendering Layout: config/index.md
         Rendering: callbacks/index.md
  Pre-Render Hooks: callbacks/index.md
  Rendering Liquid: callbacks/index.md
  Rendering Markup: callbacks/index.md
  Rendering Layout: callbacks/index.md
         Rendering: assert/index.md
  Pre-Render Hooks: assert/index.md
  Rendering Liquid: assert/index.md
  Rendering Markup: assert/index.md
  Rendering Layout: assert/index.md
         Rendering: QUnit/index.md
  Pre-Render Hooks: QUnit/index.md
  Rendering Liquid: QUnit/index.md
  Rendering Markup: QUnit/index.md
  Rendering Layout: QUnit/index.md
         Rendering: QUnit/module.md
  Pre-Render Hooks: QUnit/module.md
  Rendering Liquid: QUnit/module.md
  Rendering Markup: QUnit/module.md
  Rendering Layout: QUnit/module.md
         Rendering: assert/notDeepEqual.md
  Pre-Render Hooks: assert/notDeepEqual.md
  Rendering Liquid: assert/notDeepEqual.md
  Rendering Markup: assert/notDeepEqual.md
  Rendering Layout: assert/notDeepEqual.md
         Rendering: assert/notEqual.md
  Pre-Render Hooks: assert/notEqual.md
  Rendering Liquid: assert/notEqual.md
  Rendering Markup: assert/notEqual.md
  Rendering Layout: assert/notEqual.md
         Rendering: assert/notOk.md
  Pre-Render Hooks: assert/notOk.md
  Rendering Liquid: assert/notOk.md
  Rendering Markup: assert/notOk.md
  Rendering Layout: assert/notOk.md
         Rendering: assert/notPropEqual.md
  Pre-Render Hooks: assert/notPropEqual.md
  Rendering Liquid: assert/notPropEqual.md
  Rendering Markup: assert/notPropEqual.md
  Rendering Layout: assert/notPropEqual.md
         Rendering: assert/notStrictEqual.md
  Pre-Render Hooks: assert/notStrictEqual.md
  Rendering Liquid: assert/notStrictEqual.md
  Rendering Markup: assert/notStrictEqual.md
  Rendering Layout: assert/notStrictEqual.md
         Rendering: assert/ok.md
  Pre-Render Hooks: assert/ok.md
  Rendering Liquid: assert/ok.md
  Rendering Markup: assert/ok.md
  Rendering Layout: assert/ok.md
         Rendering: QUnit/only.md
  Pre-Render Hooks: QUnit/only.md
  Rendering Liquid: QUnit/only.md
  Rendering Markup: QUnit/only.md
  Rendering Layout: QUnit/only.md
         Rendering: assert/propEqual.md
  Pre-Render Hooks: assert/propEqual.md
  Rendering Liquid: assert/propEqual.md
  Rendering Markup: assert/propEqual.md
  Rendering Layout: assert/propEqual.md
         Rendering: assert/pushResult.md
  Pre-Render Hooks: assert/pushResult.md
  Rendering Liquid: assert/pushResult.md
  Rendering Markup: assert/pushResult.md
  Rendering Layout: assert/pushResult.md
         Rendering: assert/rejects.md
  Pre-Render Hooks: assert/rejects.md
  Rendering Liquid: assert/rejects.md
  Rendering Markup: assert/rejects.md
  Rendering Layout: assert/rejects.md
         Rendering: QUnit/skip.md
  Pre-Render Hooks: QUnit/skip.md
  Rendering Liquid: QUnit/skip.md
  Rendering Markup: QUnit/skip.md
  Rendering Layout: QUnit/skip.md
         Rendering: QUnit/start.md
  Pre-Render Hooks: QUnit/start.md
  Rendering Liquid: QUnit/start.md
  Rendering Markup: QUnit/start.md
  Rendering Layout: QUnit/start.md
         Rendering: assert/step.md
  Pre-Render Hooks: assert/step.md
  Rendering Liquid: assert/step.md
  Rendering Markup: assert/step.md
  Rendering Layout: assert/step.md
         Rendering: assert/strictEqual.md
  Pre-Render Hooks: assert/strictEqual.md
  Rendering Liquid: assert/strictEqual.md
  Rendering Markup: assert/strictEqual.md
  Rendering Layout: assert/strictEqual.md
         Rendering: QUnit/test.md
  Pre-Render Hooks: QUnit/test.md
  Rendering Liquid: QUnit/test.md
  Rendering Markup: QUnit/test.md
  Rendering Layout: QUnit/test.md
         Rendering: assert/throws.md
  Pre-Render Hooks: assert/throws.md
  Rendering Liquid: assert/throws.md
  Rendering Markup: assert/throws.md
  Rendering Layout: assert/throws.md
         Rendering: assert/timeout.md
  Pre-Render Hooks: assert/timeout.md
  Rendering Liquid: assert/timeout.md
  Rendering Markup: assert/timeout.md
  Rendering Layout: assert/timeout.md
         Rendering: QUnit/todo.md
  Pre-Render Hooks: QUnit/todo.md
  Rendering Liquid: QUnit/todo.md
  Rendering Markup: QUnit/todo.md
  Rendering Layout: QUnit/todo.md
         Rendering: assert/verifySteps.md
  Pre-Render Hooks: assert/verifySteps.md
  Rendering Liquid: assert/verifySteps.md
  Rendering Markup: assert/verifySteps.md
  Rendering Layout: assert/verifySteps.md
         Rendering: assets/css/style.scss
  Pre-Render Hooks: assets/css/style.scss
  Rendering Liquid: assets/css/style.scss
  Rendering Markup: assets/css/style.scss
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Invalid US-ASCII character "\xE2" on line 5
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/2.5.0/bin/jekyll)
Jekyll::Converters::Scss::SyntaxError: Invalid US-ASCII character "\xE2" on line 5
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:118:in `convert'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/renderer.rb:98:in `block in convert'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/renderer.rb:96:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/renderer.rb:96:in `reduce'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/renderer.rb:96:in `convert'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/renderer.rb:80:in `render_document'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/renderer.rb:62:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/site.rb:473:in `block in render_pages'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/site.rb:471:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/site.rb:471:in `render_pages'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/site.rb:191:in `render'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/site.rb:73:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/command.rb:28:in `process_site'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/commands/build.rb:65:in `build'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/commands/build.rb:36:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/exe/jekyll:15:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.5.0/bin/jekyll:23:in `load'
  /usr/local/lib/ruby/gems/2.5.0/bin/jekyll:23:in `<top (required)>'
</pre>

See also https://github.com/jekyll/jekyll-sass-converter/issues/84#issue-391405198
</details>

**Comment by ashmaroli** [comment]
@Krinkle Though I was not able to reproduced this at my end (the build was successful; OS: Windows), the root cause behind the issue is not Jekyll's doing.
GitHub Pages gem pulls in the primer-theme if no other theme has been set.

Since there's nothing to be done at our end, this is being closed.

**Comment by Krinkle** [comment]
> GitHub Pages gem pulls in the primer-theme [..]

Are you saying that only the sass of Primer is evaluated, not the dozen other gems it downloaded? If so, then I agree this is a non-issue. I assumed that because I am not using this theme, that it was just one of many unused themes installed through Gem that was being evaluated for unknown reasons.

> [..]  if no other theme has been set.

I thought of this and looked for a Jekyll setting that decides the theme, but was unable to find it. Did I miss it?

**Comment by ashmaroli** [comment]
> Are you saying that only the sass of Primer is evaluated, not the dozen other gems it downloaded?

Yes. Primer is the ["fall back theme"](https://github.com/github/pages-gem/blob/840709cf51d3c1276b61d09824e4451b2855b58f/lib/github-pages/configuration.rb#L19) for GHP.

> looked for a Jekyll setting that decides the theme

The setting is simply `theme`. It is `nil` by default.
But the boilerplate config file that is generated by `jekyll new` has `theme: minima` set for you.
The value of the `theme` key should be a valid theme-gem-name or else a `LoadError` exception will be raised.
