### ISSUE TITLE
docs: Wrong command for Windows to open theme dir

### ISSUE THREAD

**Issue by realtebo** [jekyll/jekyll#7431]
## Motivation

At the page https://jekyllrb.com/docs/themes/, there is this 

    2 Open the theme’s directory in Finder or Explorer: 
     ....
    # On Windows
    explorer /usr/local/lib/ruby/gems/2.3.0/gems/minima-2.1.0

Obviously this is NOT a windows' user path.

## Suggestion

Replace with right command, that must take into account the folder of installation of ruby. 

Just as example, I installed into `C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\minima-2.5.0`. So instruction could tell 

    explorer  <ruby installation folder>\gems\<ruby version>\gems\minima-<theme version>`

**Comment by indrakaw** [comment]
You can exec these command to determinate gem directory by:
```
bundle show minima
```
In my case, I installed Ruby via scoop.sh, it shows:
```
C:/Users/Nyanz/scoop/apps/ruby/current/gems/gems/minima-2.5.0
```
https://bundler.io/v1.1/bundle_show.html

`gem environment` shows gem related infos.

**Comment by realtebo** [comment]
Thanks for reply, I know how to find the right path and this is why I opened the issue: the doc is wrong about this.

**Comment by ashmaroli** [comment]
Feel free to submit a pull request, friends.
Thanks.
