### ISSUE TITLE
docs: Add a theme step to Step by Step Tutorial

### ISSUE THREAD

**Issue by realtebo** [jekyll/jekyll#7432]
Plase, add a step on the Step by Step Tutorial to demonstrate how to theme the just finished demo app.

## Motivation

1. Theming is not an obvious task for a newbie like me. Also, doc speaks about gem based and 'regular' file themes. It's confusin  a bit.
2. At the end of demo app it's more beautiful to leave in the han of the user a well looking demo

## Idea

Please include istructions on 
- how to enable default gem base theme
- how to customized if possible a gem theme
- how to switch to a regular file based theme
- idem, how to customize it

... or ...

Create a guide on how to start theming AND then include previous steps into the new tutorial.

Thanks for this excellent piece of software !!!!

**Comment by DirtyF** [comment]
On how to start theming for Jekyll, I'd recommend @daviddarnes articles:

1. https://www.siteleaf.com/blog/making-your-first-jekyll-theme-part-1/
2. https://www.siteleaf.com/blog/making-your-first-jekyll-theme-part-2/

**Comment by realtebo** [comment]
Thanks, but it's better have an official doc, and not links to external resources. IMHO

**Comment by daviddarnes** [comment]
If it's validation you're looking for then I can 100% endorse these tutorials ✨. However if you want this set in stone then maybe we could link to these tutorials in the official docs? Maybe in https://jekyllrb.com/tutorials/home/ or https://jekyllrb.com/resources/. What do you day @DirtyF?

**Comment by desiredpersona** [comment]
What about allowing Jekyll sponsors to post tutorials directly on the site.

Each post has a content sponsored by

**Comment by jpasholk** [comment]
Oooh, I like @desiredpersona’s idea.

**Comment by ashmaroli** [comment]
IMHO, Documentation is one thing and a (sponsored) community blog is an entirely different league altogether. They should not be intermingled.
Documentation is translating "the code base" into layman lingo. (*Point-of-View: Maintainers -> Users*)
Community blog is about sharing experience with the code base. (*Point-of-View: One User -> Other Users*)
Bringing the sponsors into the mix, is just complicating things, unnecessarily.........

**Comment by desiredpersona** [comment]
Hi @ashmaroli 

> IMHO, Documentation is one thing and a (sponsored) community blog is an entirely different league altogether. They should not be intermingled.
> Documentation is translating "the code base" into layman lingo. (_Point-of-View: Maintainers -> Users_)

I agree with you here. 

> Community blog is about sharing experience with the code base. (_Point-of-View: One User -> Other Users_)

I'm thinking the [Tutorials section](https://jekyllrb.com/tutorials/home/) could highlight the community in this way.

**Comment by realtebo** [comment]
Sorry but ... To rest in topic... A simple step added to main step by step intro is so wrong?

**Comment by daviddarnes** [comment]
I don’t see what is wrong with referring to a tutorial on another site? Yes the tutorial was paid for, but tutorials of that size take time to create. Maybe we could add some more detail on the points people are getting stuck on in the docs?

**Comment by realtebo** [comment]
If I see a tutorial on an external website it soon or later will become obsolete.

If I see a tutorial on main site I think that must be ok, tested, and updated. 

Simply. Close this issue

A company that does not understand the need of a full doc do not will offer a serious support in the long time

Bye bye.

**Comment by DirtyF** [comment]
> A company that does not understand the need of a full doc do not will offer a serious support in the long time

Jekyll is an open-source project **freely maintained by volunteers**, it has been around for 10 years now and powers hundred of thousands of websites around the world. 

Jekyll has a great [community](https://talk.jekyllrb.com/) and docs are continuously improved with the help of the contributors.

Jekyll themes _are_ [documented](https://jekyllrb.com/docs/themes/#understanding-gem-based-themes). I'll see if I can add some links to point to theming at the end of the step-by-step guide.
