### ISSUE TITLE
Unable to update Jekyll from 3.6.2 on Mac

### ISSUE THREAD

**Issue by mesibo** [jekyll/jekyll#7445]
We are unable to update Jekyll from 3.6.2 to latest 3.8.5 on Mac (works fine on Linux). 

```
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

```
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
```

```
$ bundle update jekyll 
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using concurrent-ruby 1.1.4

Bundler attempted to update jekyll but its version stayed the same
Bundle updated!
```
```
$ jekyll -v
jekyll 3.6.2

```

Any idea?

**Comment by mesibo** [comment]
Seems like github pages is holding the update. Any idea why github-pages not using the latest jekyll.

**Comment by ashmaroli** [comment]
We have no control over the [`github-pages`](https://github.com/github/pages-gem) gem.
There are active PRs from the community to bump the bundled Jekyll version, though..

Updating to the latest release of GitHub Pages gem will allow you to [use versions listed here](https://pages.github.com/versions/)

Another alternative is to ditch GitHub Pages entirely and opt for services like Netlify.com, etc.
