### ISSUE TITLE
Document anchor links

### ISSUE THREAD

**Issue by cup** [jekyll/jekyll#7455]
it seems jekyll has built in ability to do anchor links via

https://github.com/jekyll/jekyll/blob/831fba6/docs/_includes/anchor_links.html

however i do not see any documentation for this here:

https://jekyllrb.com/docs/includes

or anywhere on https://jekyllrb.com for that matter

**Comment by DirtyF** [comment]
Jekyll (or default theme) don't ship with such includes, it's something that was specifically developed  for Jekyll's website. Feel free to reuse it on your site or rely on lib like https://www.bryanbraun.com/anchorjs/
