### ISSUE TITLE
Ability to chose which one of reversed and limit apply first in collection loops?

### ISSUE THREAD

**Issue by nhoizey** [jekyll/jekyll#7462]
## Summary

I tried to use both `reversed` and `limit: 20` in a loop over my links collection, to list the 20 latest links in my Atom feed:

```
{% for link in site.links reversed limit:20 %}
```

But I get the 20 earliest instead. It looks like `limit` is applied before `reversed`.

Would it be possible to get `reversed` applied first if it comes before `limit` in the loop?

**Comment by ashmaroli** [comment]
@nhoizey `{% for .. %}` is a native Liquid Tag. Jekyll has no control over it.
Jekyll would have to implement an in-house version to change its behavior.

**Comment by DirtyF** [comment]
It's often that you'll have to assign values in Liquid, it's one of those cases:

```liquid
{% assign links = site.links reversed %}
{% for link in links limit:20 %}
```

**Comment by nhoizey** [comment]
@ashmaroli it makes sense. Maybe I can create an issue on Liquid project, then.
