### ISSUE TITLE
Linenos not generated on Jekyll 0.12.0

### ISSUE THREAD

**Issue by sergiolopes** [jekyll/jekyll#747]
I recently updated to Jekyll 0.12.0 and it stopped to generate line numbers on code highlights.
I had to downgrade back to Jekyll 0.11.2 (the version I had before, which works fine).

(I have no idea what the problem is, but I couldn't find nothing related to this in the issue tracker, so I'm submitting the bug report...)

**Comment by simar7** [comment]
Hmm.. just ran into this as well. I was trying <code> {% highlight c lineos %} </code> and it didn't seem to work. I'm on jekyll 2.3.0     
Possible regression?

**Comment by parkr** [comment]
`s/lineos/linenos/`?

**Comment by simar7** [comment]
Yikes. @parkr totally missed that haha. It works now! Thanks for catching that!
