### ISSUE TITLE
Jekyll-mention load error on "jekyll serve" or "bundle jekyll server"

### ISSUE THREAD

**Issue by Kimwangqing** [jekyll/jekyll#7475]
Hello, 

I met this issue when running "jekyll serve" or "bundle jekyll server" on bash,  but got blocked in an error:

$ bundle exec jekyll serve  
Configuration file: D:/Kim.github.io/_config.yml                                   Dependency Error: Yikes! It looks like you don't have jekyll-mentions or one o f its dependencies installed. In order to use Jekyll as currently configured, yo u'll need to install this gem. The full error message from Ruby is: 'cannot load  such file -- jekyll-mentions' If you run into trouble, you can find helpful res ources at https://jekyllrb.com/help/!                                            jekyll 3.8.5 \| Error:  jekyll-mentions
--

Actually, Jekyll-mentions gem existed in gem list jekyll, that means I have installed the gem. You can find the gem is included in gem list:

$ gem list jekyll                                                                
jekyll (3.8.5)                                                                   jekyll-feed (0.11.0)                                                             jekyll-gist (1.5.0)                                                              jekyll-mentions (1.4.1)                                                          jekyll-sass-converter (1.5.2)                                                    jekyll-seo-tag (2.5.0)                                                           jekyll-sitemap (1.2.0)                                                           jekyll-watch (2.1.2)
--

The running background is on Windows 8.1 and:
$ ruby -v                                                                        
ruby 2.4.5p335 (2018-10-18 revision 65137) [x64-mingw32]
$ gem -v                                                                         
2.6.14.3
$ bundle exec jekyll -v                                                          
jekyll 3.8.5
--

I installed jekyll-mentions version is the latest version, that is 1.4.1, and the runtime dependency is compatible with jekyll ~>3.0, and I installed jekyll is 3,8.5 version that is ranged the scope. 

Could you please guide me to go ahead? 

Cheers！

**Comment by ashmaroli** [comment]
You should include `jekyll-mentions` in your Gemfile as well when you're running jekyll with `bundle exec`
```ruby
# Gemfile

gem "jekyll-mentions"
```

**Comment by Kimwangqing** [comment]
I added "jekyll-mentions" in gemfile, and then ran "bundle exec jekyll server", but here is another error (I installed jekyll version 3.8.5):

$ bundle exec jekyll serve                                                       
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/resolver.rb:287 :in `block in verify_gemfile_dependencies_are_found!': You have requested: (Bund ler::GemNotFound)                                                                  jekyll ~> 3.2.1                                                                                                                                                 The bundle currently has jekyll locked at 3.8.5.                                 Try running `bundle update jekyll`                                                                                                                                If you are updating multiple gems in your Gemfile at once,                       try passing them all to `bundle update`                                                  from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/re solver.rb:255:in `each'                                                                  from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/re solver.rb:255:in `verify_gemfile_dependencies_are_found!'                                from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/re solver.rb:49:in `start'                                                                  from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/re solver.rb:22:in `resolve'                                                                from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/de finition.rb:258:in `resolve'                                                             from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/de finition.rb:170:in `specs'                                                               from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/de finition.rb:237:in `specs_for'                                                           from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/de finition.rb:226:in `requested_specs'                                                     from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/ru ntime.rb:108:in `block in definition_method'                                             from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/ru ntime.rb:20:in `setup'                                                                   from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler.rb :107:in `setup'                                                                          from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/se tup.rb:20:in `'                                                          from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55 :in `require'                                                                            from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55 :in `require'
--

**Comment by Kimwangqing** [comment]
finally, I solved it after several attempts up to the error tips.
