### ISSUE TITLE
jekyll install broken after ruby update to 2.5.0

### ISSUE THREAD

**Issue by tigexplorer** [jekyll/jekyll#7477]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | ubuntu 18.04           |
| `jekyll`         | 3.8.5     |

---

## Expected Behaviour

I've updatet ubuntu 16.04 to 18.05. 
In that process ruby was updated from 2.3 to 2.5.
It seems that's breaking the jekyll install.

## Current Behavior
```
jekyll doctor
bash: /usr/local/bin/jekyll: /usr/bin/ruby2.3: Defekter Interpreter: Datei oder Verzeichnis nicht gefunden
```

The jekyll install is found in
```
sudo ls -la /usr/local/bin
insgesamt 56
drwxr-xr-x  2 root root 4096 Jan 13 21:53 .
drwxr-xr-x 10 root root 4096 Apr 17  2014 ..
-rwxr-xr-x  1 root root  497 Nov 30 21:51 bundle
-rwxr-xr-x  1 root root  498 Nov 30 21:51 bundler
-rwxr-xr-x  1 root root  494 Nov 30 21:50 jekyll
-rwxr-xr-x  1 root root  502 Nov 30 21:50 kramdown
-rwxr-xr-x  1 root root  494 Nov 30 21:50 listen
-rwxr-xr-x  1 root root  492 Nov 30 21:50 rougify
-rwxr-xr-x  1 root root  506 Nov 30 21:50 safe_yaml
-rwxr-xr-x  1 root root  486 Nov 30 21:50 sass
-rwxr-xr-x  1 root root  494 Nov 30 21:50 sass-convert
-rwxr-xr-x  1 root root  486 Nov 30 21:50 scss
```
As I understand from the error message, there is a hardlink to ruby 2.3 instead to `/usr/bin/ruby`

How can I cleanup and fix the installation? 
While the paths are broken, uninstall is not possible 
```
gem uninstall jekyll
Gem 'jekyll' is not installed
```

**Comment by ashmaroli** [comment]
> `Defekter Interpreter: Datei oder Verzeichnis nicht gefunden`

Please translate above to English

**Comment by ashmaroli** [comment]
Either ways, this issue is not because of Jekyll.

**Comment by tigexplorer** [comment]
> > `Defekter Interpreter: Datei oder Verzeichnis nicht gefunden`
> 
> Please translate above to English

Defective interpreter: File or directory not found

**Comment by tigexplorer** [comment]
> Either ways, this issue is not because of Jekyll.

I don't think so. 
The hardlink to ruby 2.3 seems to be createt by jekyll install

**Comment by tigexplorer** [comment]
Maybe it's a general issue of installing gems. But how can I fix this in the situation described here?

**Comment by DirtyF** [comment]
Have you tried https://jekyllrb.com/docs/installation/ubuntu/?

**Comment by tigexplorer** [comment]
> Have you tried https://jekyllrb.com/docs/installation/ubuntu/?

Hi, yes in this way, I've installed jekyll under ruby 2.3. But now, after the update to ruby 2.5, this install is furthermore "connected" with ruby 2.3. I think, that's the reason why I cannot uninstall jekyll, bundler and the other gems, installed like in the instruction.
All this gems in the bin folder contains: 
```
#!/usr/bin/ruby2.3
#
# This file was generated by RubyGems.
#
# The application 'jekyll' is installed as part of a gem, and
# this file is here to facilitate running it.
#
``` 

How can I clean up this broken gem installation?
