### ISSUE TITLE
Styles are mysteriously included in the CSS build

### ISSUE THREAD

**Issue by bryanbraun** [jekyll/jekyll#7478]
**Backgroud:** I'm using Jekyll with Github Pages and `pages-gem` (fully updated) to generate a personal site ([repo here](https://github.com/bryanbraun/bryanbraun.github.io)).

## The issue

When I run a build, it generates a file in `/assets/css/style.css` that is unrelated to any of my site's styles. You can [see the compressed stylesheet here](https://www.bryanbraun.com/assets/css/style.css).

I did some digging and they look similar to the styles that are included in `jekyll-theme-primer`. My site doesn't reference this theme and I don't believe my site ever did (the [initial commit](https://github.com/bryanbraun/bryanbraun.github.io/commit/e64945b011e0d9613a209d78fc3d4799c0db280b) says I used `jekyll new`, but there's no reference to a theme in `_config.yml` or `Gemfile`).

Assuming the site somehow became based on `jekyll-theme-primer`, I looked through [the docs on converting-gem-based themes](https://jekyllrb.com/docs/themes/#converting-gem-based-themes-to-regular-themes), but because there's no reference to this theme, I can't find a way to "remove" it.

Could the styles be coming from `jekyll-theme-primer`? Is there a way to prevent them from being generated?

### Steps to reproduce:
1. Clone my repo: `git clone git@github.com:bryanbraun/bryanbraun.github.io.git` and install dependencies.
2. Delete every file ending in `.scss` (for good measure)
3. Run `jekyll build`.
4. See the generated file in `_site/assets/style.css`

***

*FYI: I've seen this issue reported in a few other places like https://github.com/apel/apel.github.io/issues/17 and https://github.com/necolas/normalize.css/issues/656, but not as an issue here.*

**Comment by ashmaroli** [comment]
@bryanbraun Sorry to inform you that this issue is not because of Jekyll but because of the `github-pages` gem customizing Jekyll internally.
GitHub Pages will fall back to using `jekyll-theme-primer` if the `theme; ` key has not been defined (or if set to `null`)

I would suggest taking this issue up with `github-pages` gem repo or try the unofficial (and untested) hack by setting `theme: ''`

**Comment by bryanbraun** [comment]
No worries, this is helpful.

For the record, setting `theme: ''` isn't working for me... I get this error:

```
$ jekyll build
Configuration file: /Users/bryanbraun/Code/bryanbraun/bryanbraun.com/_config.yml
jekyll 3.7.4 | Error:  The  theme could not be found.
```

But `theme: null` seems to be working. ¯\\_(ツ)_/¯

Either way, I'll take it up with that project.
