### ISSUE TITLE
Broken excluded symlink throws error

### ISSUE THREAD

**Issue by MTCoster** [jekyll/jekyll#7481]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | macOS Mojave 10.14.2 (18C54) |
| `jekyll`         | 3.7.4 |
| `github-pages`   | 193 |

---

## Expected Behaviour

`jekyll serve` works correctly.

## Current Behavior

```
➜ jekyll serve
...
jekyll 3.7.4 | Error:  No such file or directory @ realpath_rec - /invalid
```

<details>
<summary>Full stack trace from <code>jekyll serve --trace</code></summary>
<pre><code>Errno::ENOENT: No such file or directory @ realpath_rec - /invalid
  /path/to/ruby/gems/pathutil-0.16.2/lib/pathutil.rb:292:in `in_path?'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/entry_filter.rb:83:in `symlink_outside_site_source?'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/entry_filter.rb:74:in `symlink?'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/entry_filter.rb:35:in `block in filter'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/entry_filter.rb:33:in `reject'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/entry_filter.rb:33:in `filter'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/reader.rb:119:in `filter_entries'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/reader.rb:44:in `block in read_directories'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/reader.rb:44:in `chdir'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/reader.rb:44:in `read_directories'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/reader.rb:82:in `block in retrieve_dirs'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/reader.rb:78:in `each'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/reader.rb:78:in `retrieve_dirs'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/reader.rb:53:in `read_directories'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/reader.rb:18:in `read'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/site.rb:163:in `read'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/site.rb:71:in `process'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/command.rb:28:in `process_site'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/commands/build.rb:65:in `build'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/commands/build.rb:36:in `process'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/commands/serve.rb:93:in `block in start'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/commands/serve.rb:93:in `each'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/commands/serve.rb:93:in `start'
  /path/to/ruby/gems/jekyll-3.7.4/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
  /path/to/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /path/to/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /path/to/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /path/to/ruby/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /path/to/ruby/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /path/to/ruby/gems/jekyll-3.7.4/exe/jekyll:15:in `&lt;top (required)&gt;'
  /path/to/ruby/bin/jekyll:23:in `load'
  /path/to/ruby/bin/jekyll:23:in `&lt;top (required)&gt;'</code></pre>
</details>

## Code Sample

1. Create a new jekyll project
2. Create an invalid symlink within it:

``` 
➜ touch /invalid
➜ ln -s /path/to/jekyll/project/invalid-symlink /invalid
➜ rm -f /invalid
```

3. Add the symlink to `exclude` in `_config.yml`:

```
exclude:
  - invalid-symlink
```

4. Attempt to run `jekyll serve`

While this is obviously the correct behaviour for a symlink Jekyll *should* be parsing, why should the build fail when a file I explicitly told it to ignore is invalid?

**Comment by MTCoster** [comment]
I’m not particularly familiar with Ruby’s `next ... if` syntax, but it looks to me as if the problem comes from the order of evaluation in both this loop:

https://github.com/jekyll/jekyll/blob/79b7b9ac026766a96f55815b5f5e37bb5e41933a/lib/jekyll/entry_filter.rb#L32-L42

And this conditional:

https://github.com/jekyll/jekyll/blob/79b7b9ac026766a96f55815b5f5e37bb5e41933a/lib/jekyll/entry_filter.rb#L69-L76

With the check `symlink_outside_site_source?(entry)` throwing the error.

**Comment by ashmaroli** [comment]
I understand what you're implying with this ticket and I agree with your expectation.
If a path is listed in the `exclude` array, then that path should be excluded right away instead of checking if the path meets other criteria first.

I'll submit a PR for this soon.. Let us see if the other maintainers get on the same page.

**Comment by MTCoster** [comment]
@ashmaroli That does the job, thanks!

**Comment by mk-pmb** [comment]
Is there a way to ignore based on the symlink target?
My current use case is to ignore dead symlinks if their resolved path (readlink -m) points to `$MY_REPO_DIR/.git/annex/objects/**`, so Github won't send me email "The symbolic link `…` targets a file which does not exist within your site's repository." each time I push.
I'd like to get warnings about other kinds of broken symlinks though.
