### ISSUE TITLE
how can i write markdowns work both correct in github pages and github

### ISSUE THREAD

**Issue by hugetiny** [jekyll/jekyll#7485]
## links issue
if I write 
```
  [link]({{ site.baseurl }}{% link another.md %}) 
```
this will show the raw content:  [link]({{ site.baseurl }}{% link another.md %})   in github.com

if i write 
```
[link](https://github.com/....../another.md)
```
this will link pages to github(I need to stay in github pages website)

## how to not show github pages' html in github
and how can i hide the _layouts html when users are browsing github without showing:
![image](https://user-images.githubusercontent.com/19659202/51435575-6aebb000-1cb5-11e9-9afb-2421adb9277c.png)

**Comment by ashmaroli** [comment]
There is no way you can do any of that because GitHub, GitHub Pages and Jekyll are different programs.
Jekyll does not control how pages are rendered on GitHub.
