### ISSUE TITLE
downgraded to ruby 1.9.3p286 as there seems to be a bug for Jekyll on ruby 1.9.3p327

### ISSUE THREAD

**Issue by grayghostvisuals** [jekyll/jekyll#749]
In order to run `jekyll --server`
I've had to downgrade to `ruby 1.9.3p286` as there seems to be a bug for Jekyll on `ruby 1.9.3p327`

running `jekyll --server` on `ruby 1.9.3p327` throws this error

``` shell
You may have encountered a bug in the Ruby interpreter or extension libraries.
```

**Comment by ygweric** [comment]
'sudo jekyll server' works for me

**Comment by ygweric** [comment]
`sudo jekyll server` works for me
