### ISSUE TITLE
Cannot build if the date is in the future

### ISSUE THREAD

**Issue by tristanbes** [jekyll/jekyll#7493]
Hi,

## My Environment

  - I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-
  - I ran `jekyll doctor` to check my configuration

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  OSX 10.14 |
| `github-pages`   | Latest     |

---

## Expected Behaviour

The website should be able to build if we reference a post with `post_url` with a date that is in the future, yet we get an error "Could not find post"

## Current Behavior

```
  Liquid Exception: Could not find post "2019-01-24-clevercloud-vs-scalingo" in tag 'post_url'. Make sure the post exists and the name is correct. in /Users/johndoe/workspace/blog/_posts/2019-01-19-comparatif-paas-wordpress-francais.md
             Error: Could not find post "2019-01-24-clevercloud-vs-scalingo" in tag 'post_url'. Make sure the post exists and the name is correct.
             Error: Run jekyll build --trace for more information.
```

To fix the behaviour, I had to rename the article containing a date that is not in the future.
The problem is that **nothing** tells you it's because of the date that is on the future. It just keep saying "Could not find post..." so you spend 10 minutes trying to get invisible characters, or typo, that doesn't exist.

## Code Sample

Not revelant, you can try it youself just by referencing an article with `{% post_url 2019-04-01-example %}` in the future, and create the article with the same date (in the future).

**Comment by ashmaroli** [comment]
> The problem is that **nothing** tells you it's because of the date that is on the future.

I understand the essence of this ticket.
That said, did you go through the output from building with the `--verbose` flag? IIRC, the output should have a line similar to `Skipped Publish: [path-to-skipped-post]`

**Comment by tristanbes** [comment]
Nope, I tried `--trace` like suggested in the error, but even with `--trace` still no useful information. It was really out of despair that I tried to change the date.

**Comment by ashmaroli** [comment]
Okay. We shall add an additional warning to remind users to check their post's date if the site is not future-enabled.
Are you willing to submit a patch?

**Comment by tristanbes** [comment]
Not that I don't want to, but it's basically the 3rd time I use jekyll as a "user". So if another wants to pick this, feel free to.

**Comment by jakehell** [comment]
@tristanbes a workaround for this would be to use the `--future` flag when running `jekyll build`.

**Comment by jakehell** [comment]
Also, @mojombo you are correct, `-V` will show that jekyll is skipping posts at a future date.

I was able to confirm by having a post with a date in the future and running `jekyll build -V`: 

`Skipping: _posts/2019-12-31-foo.md has a future date`

However, running with the `--trace` option does not show this message.

Knowing this, do you think this is still considered an issue?

**Comment by v3nd3774** [comment]
Hi! I opened up a pull request [here](https://github.com/jekyll/jekyll/pull/7527) to resolve this!
