### ISSUE TITLE
Jekyll 3.8.5 on Mac 10.14.2 (Mojave latest): Liquid Exception: no implicit conversion of nil into String in /_layouts/default.html

### ISSUE THREAD

**Issue by shoaibsufi** [jekyll/jekyll#7500]
When I run:

bundle exec jekyll serve 

It gives me an error - Liquid Exception: no implicit conversion of nil into String in /_layouts/default.html

bundle update

The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 3.0.3
Using addressable 2.6.0
Using bundler 2.0.1
Using colorator 1.1.0
Using concurrent-ruby 1.1.4
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using ffi 1.10.0
Using forwardable-extended 2.6.0
Using i18n 0.9.5
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using sass-listen 4.0.0
Using sass 3.7.3
Using jekyll-sass-converter 1.5.2
Using ruby_dep 1.5.0
Using listen 3.1.5
Using jekyll-watch 2.1.2
Using kramdown 1.17.0
Using liquid 4.0.1
Using mercenary 0.3.6
Using pathutil 0.16.2
Using rouge 3.3.0
Using safe_yaml 1.0.4
Using jekyll 3.8.5
Using jekyll-feed 0.11.0
Using jekyll-seo-tag 2.5.0
Using minima 2.5.0
Bundle updated!

jekyll doctor

Traceback (most recent call last):
	15: from /Users/shoalb/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	14: from /Users/shoalb/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	13: from /Users/shoalb/.rvm/gems/ruby-2.6.0/bin/jekyll:23:in `<main>'
	12: from /Users/shoalb/.rvm/gems/ruby-2.6.0/bin/jekyll:23:in `load'
	11: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/exe/jekyll:11:in `<top (required)>'
	10: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
	 9: from /Users/shoalb/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler.rb:101:in `setup'
	 8: from /Users/shoalb/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler.rb:135:in `definition'
	 7: from /Users/shoalb/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:34:in `build'
	 6: from /Users/shoalb/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:13:in `evaluate'
	 5: from /Users/shoalb/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:234:in `to_definition'
	 4: from /Users/shoalb/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/dsl.rb:234:in `new'
	 3: from /Users/shoalb/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `initialize'
	 2: from /Users/shoalb/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/definition.rb:83:in `new'
	 1: from /Users/shoalb/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:95:in `initialize'
/Users/shoalb/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)

(__but I am using Bundler 2.0.1_ so not sure why it's giving a warning)

bundle exec jekyll build --verbose --trace

  Logging at level: debug
Configuration file: /Users/shoalb/Dropbox (The University of Manchester)/software/event-organisation-guide/_config.yml
             Theme: minima
      Theme source: /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/minima-2.5.0
         Requiring: jekyll-feed
         Requiring: jekyll-seo-tag
         Requiring: jekyll-feed
            Source: /Users/shoalb/Dropbox (The University of Manchester)/software/event-organisation-guide
       Destination: /Users/shoalb/Dropbox (The University of Manchester)/software/event-organisation-guide/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       EntryFilter: excluded /Gemfile
       EntryFilter: excluded /Gemfile.lock
       Jekyll Feed: Generating feed for posts
        Generating: JekyllFeed::Generator finished in 0.001792 seconds.
         Rendering: 404.html
  Pre-Render Hooks: 404.html
  Rendering Markup: 404.html
  Rendering Layout: 404.html
     Layout source: theme
  Liquid Exception: no implicit conversion of nil into String in /_layouts/default.html
Traceback (most recent call last):
	39: from /Users/shoalb/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	38: from /Users/shoalb/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	37: from /Users/shoalb/.rvm/gems/ruby-2.6.0/bin/jekyll:23:in `<main>'
	36: from /Users/shoalb/.rvm/gems/ruby-2.6.0/bin/jekyll:23:in `load'
	35: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
	34: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	33: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	32: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	31: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	30: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	29: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	28: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
	27: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
	26: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
	25: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:71:in `process'
	24: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:192:in `render'
	23: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:471:in `render_pages'
	22: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:471:in `each'
	21: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:472:in `block in render_pages'
	20: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/site.rb:479:in `render_regenerated'
	19: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:62:in `run'
	18: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:88:in `render_document'
	17: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	16: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:195:in `render_layout'
	15: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:126:in `render_liquid'
	14: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	13: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	12: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	11: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	10: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	 9: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/liquid-4.0.1/lib/liquid/template.rb:220:in `render!'
	 8: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/liquid-4.0.1/lib/liquid/template.rb:207:in `render'
	 7: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/liquid-4.0.1/lib/liquid/template.rb:242:in `with_profiling'
	 6: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/liquid-4.0.1/lib/liquid/template.rb:208:in `block in render'
	 5: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/liquid-4.0.1/lib/liquid/block_body.rb:91:in `render'
	 4: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/liquid-4.0.1/lib/liquid/block_body.rb:102:in `render_node_to_output'
	 3: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:135:in `render'
	 2: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:167:in `load_cached_partial'
	 1: from /Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer.rb:27:in `file'
/Users/shoalb/.rvm/gems/ruby-2.6.0/gems/jekyll-3.8.5/lib/jekyll/liquid_renderer.rb:27:in `join': no implicit conversion of nil into String (TypeError)

The weird thing is - this works on GitHub pages and works on Linux - but not on my Mac 

Any help appreciated.

**Comment by DirtyF** [comment]
see https://github.com/jekyll/jekyll/issues/7463#issuecomment-451686361
