### ISSUE TITLE
docs: 

### ISSUE THREAD

**Issue by IpsumLorem16** [jekyll/jekyll#7515]
## Motivation

the link  in the [examples pages ](https://github.com/jekyll/jekyll/wiki/sites)for this person: 

> Ivan A. Hoinacki (source) - A frontend developer, expert in AngularJS who lives in Brazil.

Redirects to different spam and scam sites whenever you click it, including fake mirror.co.uk articles pushing a scam, also sites trying to trick the user into installing a malicious chrome extension.

## Suggestion

remove this link.

**Comment by DirtyF** [comment]
👍 Done. Thanks for reporting.
