### ISSUE TITLE
docs: Incorrect constructor argument documented for Generators

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#7517]
## Motivation

In https://jekyllrb.com/docs/plugins/generators/, we document the constructor for a generator as follows:

```ruby
class CategoryPageGenerator < Generator
  def initialize(site)
    ...
  end
end
```

But a generator is [a subclass of plugin](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/generator.rb), for which the first and only constructor arg [is `config`](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/plugin.rb#L85-L88), not `site`.

Bassed on https://github.com/jekyll/jekyll/commit/31c65c56f4989435301eee622ee375cee4bf2de2 and https://github.com/jekyll/jekyll/commit/fc86c9dd85ae99bc60dd7ec8c6190a58e6df2ec4, it looks like it's been that way for about 9 years.

## Suggestion

If the above is correct we should document that generators get passed the `config` in the constructor and `site` in the `generator` method.

/cc https://github.com/benbalter/jekyll-relative-links/pull/50

**Comment by ashmaroli** [comment]
This is not a mistake, @benbalter. The docs in question are not documenting the "constructor" but the "interface" of all generators.
Generators are "constructed" via `#initialize` method like every Ruby class, only difference being that all generators are initialized at the same time via:
https://github.com/jekyll/jekyll/blob/bbd635539dcd7b4df8be1ccb538b7a0b127dbe67/lib/jekyll/site.rb#L121
https://github.com/jekyll/jekyll/blob/bbd635539dcd7b4df8be1ccb538b7a0b127dbe67/lib/jekyll/site.rb#L299-L303

The method documented `#generate` is the "interface" method which **every generator instance *should* implement.** The `#generate` method rightly takes in `site` as the argument.

Two ways to initialize `@config` would be to:
- redefine `#initialize`:
```ruby
class MyGenerator < Generator
  def initialize(config = {})
    @config = config
  end

  def generate(site)
    ...
  end
end
```
- initialize within `#generate`:
```ruby
class MyGenerator < Generator
  def generate(site)
    @config = site.config
    ...
  end
end
```

**Comment by benbalter** [comment]
Ahh, @ashmaroli you are correct. Sorry for the noise (I misunderstood the docs), but really appreciate you taking the time to explain. :smile:

**Comment by ashmaroli** [comment]
I'm glad that I was able to clear the confusion :smiley:

**Comment by DirtyF** [comment]
Ideally confusion should be cleared in the documentation 😉

**Comment by ashmaroli** [comment]
@DirtyF There was no confusion in the documentation to begin with.
It was just a human error. Ben had misread the docs.
That said, if you feel you can add clarity to existing documentation, I'm happy to review a pull-request towards that.

**Comment by benbalter** [comment]
> It was just a human error. Ben had misread the docs.

Yeah. Specifically, I think I saw the first code block was

```ruby
module Reading
  class Generator < Jekyll::Generator
    def generate(site)
    end
  end
end
```

And then

> This is a more complex generator that generates new pages:

With the following code block:

```ruby
module Jekyll
  class CategoryPage < Page
    def initialize(site, base, dir, category)
    end
  end
end
``` 

With the Generator _below_ that snippet. Skimming, I didn't see the class/namespace change.

If we wanted to, we _could_ switch the order of the second code block so that the generator is first in the Jekyll namespace, but it's a minor optimization, and likely fine as is.

Thanks again for talking through it! :smile:

**Comment by ashmaroli** [comment]
@benbalter Code switched in https://github.com/jekyll/jekyll/commit/9a4b74c44b9679803d907fd97abbd6a84e671c31
