### ISSUE TITLE
_includes not working

### ISSUE THREAD

**Issue by treverandersen** [jekyll/jekyll#7523]
So running 'jekyll new site-name' 
then 'jekyll serve' everything works great. 
Then I created _layouts directory, 
removed _posts (because it's just a static site without a blog), 
created _includes directory and added in the html files I want as includes.. 
Then I tried adding {% include head.html %} to my default.html file inside of _layouts directory
Then ran' jekyll serve' 
and I get this error:
"Liquid Exception: Liquid syntax error (line 9): Unknown tag 'inlcude' in /_layouts/default.html
jekyll 3.8.5 | Error:  Liquid syntax error (line 9): Unknown tag 'inlcude' "

**Comment by DirtyF** [comment]
👋 @treverandersen 
Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage. 🆘

**Comment by crispgm** [comment]
```
"Liquid Exception: Liquid syntax error (line 9): Unknown tag 'inlcude' in /_layouts/default.html
```

Looks like misspelled `inlcude`

**Comment by treverandersen** [comment]
> ```
> "Liquid Exception: Liquid syntax error (line 9): Unknown tag 'inlcude' in /_layouts/default.html
> ```
> 
> Looks like misspelled `inlcude`

*facepalm yep. thanks!
