### ISSUE TITLE
Subscribe to Jekyll News?

### ISSUE THREAD

**Issue by weilinzung** [jekyll/jekyll#7531]
## Summary

We want to post the latest news from https://jekyllrb.com/news/ to Slack Channel, but the Jekyll News doesn't have the `RSS.xml` and also that is an easy way to automatic post to Slack Channel. Please add that.

**Comment by DirtyF** [comment]
You can subscribe through https://jekyllrb.com/feed.xml

**Comment by DirtyF** [comment]
We just added a cateogiry feed for the releases only: https://jekyllrb.com/feed/release.xml

**Comment by weilinzung** [comment]
awesome!
