### ISSUE TITLE
Jekyll MacOS Mojave installation failed

### ISSUE THREAD

**Issue by javasunCN** [jekyll/jekyll#7535]
MacOS Mojave 10.14.3
gcc version 8.2.0 (Homebrew GCC 8.2.0) 

Question:
Building native extensions. This could take a while...
/usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/rubygems/ext/builder.rb:76: warning: Insecure world writable dir /Users/zhangzhihong/tool/zk/zookeeper-3.4.9/bin in PATH, mode 040777
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    current directory: /Users/zhangzhihong/gems/gems/ffi-1.10.0/ext/ffi_c
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0 -r ./siteconf20190218-97402-1vo553h.rb extconf.rb
/usr/local/Cellar/ruby/2.6.1/lib/ruby/2.6.0/mkmf.rb:1565: warning: Insecure world writable dir /Users/zhangzhihong/tool/zk/zookeeper-3.4.9/bin in PATH, mode 040777
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

current directory: /Users/zhangzhihong/gems/gems/ffi-1.10.0/ext/ffi_c
make "DESTDIR=" clean

current directory: /Users/zhangzhihong/gems/gems/ffi-1.10.0/ext/ffi_c
make "DESTDIR="
Configuring libffi
configure: error: in `/Users/zhangzhihong/gems/gems/ffi-1.10.0/ext/ffi_c/libffi-x86_64-darwin18':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
make: *** ["/Users/zhangzhihong/gems/gems/ffi-1.10.0/ext/ffi_c/libffi-x86_64-darwin18"/.libs/libffi_convenience.a] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/zhangzhihong/gems/gems/ffi-1.10.0 for inspection.
Results logged to /Users/zhangzhihong/gems/extensions/x86_64-darwin-18/2.6.0/ffi-1.10.0/gem_make.out

**Comment by DirtyF** [comment]
Did you install the command line tools? 

```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by javasunCN** [comment]
Already installed command line tools

> gcc -v
>Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
>Apple LLVM version 10.0.0 (clang-1000.11.45.5)
>Target: x86_64-apple-darwin18.2.0
>Thread model: posix
>InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

> clang -v
>Apple LLVM version 10.0.0 (clang-1000.11.45.5)
>Target: x86_64-apple-darwin18.2.0
>Thread model: posix
>InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by javasunCN** [comment]
> Apple LLVM version 10.0.0 (clang-1000.11.45.5)
> Target: x86_64-apple-darwin18.2.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> configure:3835: $? = 0
> configure:3824: xcrun clang -v >&5
> Apple LLVM version 10.0.0 (clang-1000.11.45.5)
> Target: x86_64-apple-darwin18.2.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> configure:3835: $? = 0
> configure:3824: xcrun clang -V >&5
> clang: error: argument to '-V' is missing (expected 1 value)
> clang: error: no input files
> configure:3835: $? = 1
> configure:3824: xcrun clang -qversion >&5
> clang: error: unknown argument: '-qversion'
> clang: error: no input files
>

**Comment by DirtyF** [comment]
I have:

```sh
clang -v
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm@4/bin
```

❓ Is it better if you run:

```sh
brew install cmake llvm@4 libffi
```

**Comment by gdmcdonald** [comment]
I have the same issue, and running 
```brew install cmake llvm@4 libffi```
doesn't solve it

**Comment by DirtyF** [comment]
https://desiredpersona.com/install-jekyll-on-macos/

**Comment by javasunCN** [comment]
https://desiredpersona.com/install-jekyll-on-macos/ @DirtyF  Thank you！！！

**Comment by jklymak** [comment]
I followed the steps above, but still could not get jekyll to build.  

This was due to migrating to a new machine, and having cruft in `/usr/local/include` that was being read before the proper header files.  I was able to move `/usr/local/include` to `/usr/local/include_old` and get things to build fine.  

https://github.com/rbenv/ruby-build/issues/1169#issuecomment-367137554
