### ISSUE TITLE
Windows Error ChildProcesses.onexit

### ISSUE THREAD

**Issue by anetk** [jekyll/jekyll#7539]
I'm getting an error only on Windows machine when trying to build Jekyll. 

Here is my gulp task:

`const buildJekyll = () => {
  browserSync.notify("Running: $ jekyll build");
  return spawn(jekyll, ["build"]);
};`

Here is the error:
<img width="784" alt="screen shot 2019-02-18 at 2 18 37 pm" src="https://user-images.githubusercontent.com/11873129/52979309-d6df3800-3389-11e9-8133-9115337f67e3.png">

In my Gemfile I'm using Jekyll version 3.5.0 (also tried 3.8.5)

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      Windows 10    |
| `jekyll`  |  3.5.0 or 3.8.5   
| `github-pages`   | Latest   |

---

## Expected Behaviour

On my Mac machine, when I run jekyll build it opens up localhost in the browser.

## Current Behavior

Exactly the same versions used on Windows are failing with the error above.

## Code Sample

https://github.com/taylorbryant/sass-jekyll

**Comment by ashmaroli** [comment]
@anetk This does not look like a Jekyll issue.
The issue is mostly due to the difference in how `child_process.spawn()` is to be used on Windows and on Unix-based platforms.
Please refer documentation for the `child_process` npm module or ask the author of `sass-jekyll` for assistance.
