### ISSUE TITLE
Liquid Exception: 'if' tag was never closed included in /_layouts/home.html

### ISSUE THREAD

**Issue by mitulsavani** [jekyll/jekyll#7545]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |    MacOS        |
| `jekyll`         |3.7.4     |
| `github-pages`   |196     |
| `Gem`   |2.5.2.3     |
| `Ruby`   | 2.3.7   |

---

## Expected Behaviour

I am trying to push some changes that I made locally to my [website](mitulsavani.github.io)
But it doesn't reflect on the site.

## Current Behavior

[Repo:    https://github.com/mitulsavani/mitulsavani.github.io](https://github.com/mitulsavani/mitulsavani.github.io)

When I run my website locally, using `jekyll serve` it runs the server, regenerates and make changes to my [HTML](https://github.com/mitulsavani/mitulsavani.github.io/blob/master/_site/index.htm) file automatically.

## Code Sample

ERROR that I came across somewhere, but couldn't find a fix for it. 
```
Liquid Exception: Liquid syntax error (/page-build/repo/_includes/masthead.html line 61): 'if' tag was never closed included in /_layouts/home.html
```
^^
 layouts
        |___[home.html](https://github.com/mitulsavani/mitulsavani.github.io/blob/master/_layouts/home.html)

Build Profile -> after typing `jekyll build --profile`
```
Configuration file: /Users/mitulsavani/Documents/Developer/mitulsavani.github.io/_config.yml
            Source: /Users/mitulsavani/Documents/Developer/mitulsavani.github.io
       Destination: /Users/mitulsavani/Documents/Developer/mitulsavani.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.

Filename                  | Count |  Bytes |  Time
--------------------------+-------+--------+------
_layouts/home.html        |     1 | 27.14K | 1.738
_includes/header.html     |     1 |  0.29K | 1.264
_includes/projects.html   |     1 | 20.20K | 0.459
_includes/masthead.html   |     1 |  3.65K | 0.003
_includes/interests.html  |     1 |  2.55K | 0.002
_includes/repo-card.html  |     1 | 19.33K | 0.001
_includes/topic-card.html |     1 |  2.09K | 0.001
index.html                |     1 |  0.00K | 0.000
assets/styles.scss        |     1 |  0.33K | 0.000
_includes/footer.html     |     1 |  0.02K | 0.000
assets/css/style.scss     |     1 |  0.03K | 0.000


                    done in 3.925 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

Send help please...
PS: if this is duplicate

**Comment by DirtyF** [comment]
Hi, please head over Jekyll's forum for help on Jekyll's usage: https://talk.jekyllrb.com or on https://github.community/t5/GitHub-Pages/bd-p/pages

**Comment by mitulsavani** [comment]
@DirtyF I have already posted the issue there, no one have help yet! Thought someone will answer my fix here 🤷‍♂️

**Comment by DirtyF** [comment]
Check your liquid include, it seems like a mismatched ìf`.

**Comment by mitulsavani** [comment]
Thank you so much . I appreciate your response.
