### ISSUE TITLE
[Windows 10] "Liquid Exception: no implicit conversion of nil into String in /_layouts/default.html" when using (really) long pathnames

### ISSUE THREAD

**Issue by vzro** [jekyll/jekyll#7547]
## My Environment

| Software          | Version(s) |
| ---------------- | ----------- |
| Operating System | Windows 10  1703 15063.1418 |
| `ruby`         | 2.5.3p105 revision 65156 [x64-mingw32] |
| `gem`         | 3.0.2 |
| `jekyll`        | 3.8.5 |
| `bundler`    | 3.0.2 |
| `liquid`       | 4.0.1 |
| `github-pages`       | no |

---

## Expected Behaviour

Jekyll should serve the site

## Current Behavior

Jekyll is outputting the error in the title when running the command 'jekyll serve' or 'bundle exec jekyll serve' in a newly created site with the command 'jekyll new site' when 'site' is within a folder which pathname is really long/contains lots of spaces.

## Code Sample

The pathname is:
C:\Users\CPD\Desktop\Learning Static Site Building with Jekyll (Lynda)\site
If 'site' is moved to, say, C:\Users\CPD\Documents\, everything works just fine.

Ruby, Gem, Bundle, Liquid, Jekyll, System... It's all updated.

**Comment by ashmaroli** [comment]
@vzro Hi :wave: 
Can you please post the output from running `bundle exec jekyll serve --trace` &nbsp;?

**Comment by ashmaroli** [comment]
The issue is not with the length of the file path but the fact that a our file-path extractor balks at the presence of a parenthesized entity `(Lynda)` in the path.

You should have no issues with a path such as
`C:\Users\CPD\Desktop\Learning Static Site Building with Jekyll--Lynda`

**Comment by vzro** [comment]
> 
> 
> @vzro Hi 👋
> This issue seems to have been fixed in `master`.
> You may try reproducing the issue with our `master` branch:
> 
> ```ruby
> # Gemfile
> gem "jekyll", git: "https://github.com/jekyll/jekyll.git", branch: "master"
> ```

When will this fix be incorporated in an upcoming stable release?

**Comment by vzro** [comment]
> 
> 
> The issue is not with the length of the file path but the fact that a our file-path extractor balks at the presence of a parenthesized entity `(Lynda)` in the path.
> 
> You should have no issues with a path such as
> `C:\Users\CPD\Desktop\Learning Static Site Building with Jekyll--Lynda`

I see, this is a rather odd bug. I stick with a naming convention for all my folders, I hope we'll be able to use parentheses in the pathname soon.

**Comment by ashmaroli** [comment]
@vzro Sorry for the inconvenience. A patch may or may not be made available for Jekyll 3.x series, but will most likely be included in the upcoming Jekyll 4.0
