### ISSUE TITLE
docs: Help update Jekyll

### ISSUE THREAD

**Issue by muromtsev** [jekyll/jekyll#7553]
Hi. There is a repository with a blog. So, recently I started to swear at what needs to be updated Jekyll.
How to do it?
http://prntscr.com/ms9ret

**Comment by ashmaroli** [comment]
Run `bundle update` in your terminal to update all outdated gems in your project.
Run `bundle update jekyll` in your terminal to just update Jekyll.

**Comment by DirtyF** [comment]
@muromtsev Most of the times, you just need to run `bundle update`.

See https://bundler.io/v2.0/man/bundle-update.1.html if you want to know more.

Be aware that the corresponding update will depend on the versions declared in your Gemfile:

```
gem "jekyll", "3.8.5" # stick to a specific version
gem "jekyll" #versionless, will update to latest version
gem "jekyll", ">= 3.7" # optimistic
gem "jekyll", "~>3" # pessimistic, don't upgrade to next major version, that might break compatibility
```

See https://guides.rubygems.org/patterns/#pessimistic-version-constraint to learn about semantic versioning and version constraint.

@jekyll/documentation Should we add a section on updating gems? (even if there's nothing specific to Jekyll)

**Comment by muromtsev** [comment]
Thank you for your reply.
There was a console error
in find_spec_for_exe cant find with exutable bundle
Corrected. Updated. Thank!
