### ISSUE TITLE
error finding _layout\*.html files when building with --source DIR flag on Windows

### ISSUE THREAD

**Issue by epogrebnyak** [jekyll/jekyll#7563]
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
  - [x] I ran `jekyll doctor` to check my configuration

```
D:\github\here_is_jekyll_demo\kppk>jekyll doctor
Configuration file: D:/github/here_is_jekyll_demo/kppk/_config.yml
Error reading file D:/github/here_is_jekyll_demo/kppk/_layouts/default.html: No such file or directory @ rb_sysopen - D:/github/here_is_jekyll_demo/kppk/source/github/here_is_jekyll_demo/kppk/_layouts/default.html
Error reading file D:/github/here_is_jekyll_demo/kppk/_layouts/post.html: No such file or directory @ rb_sysopen - D:/github/here_is_jekyll_demo/kppk/source/github/here_is_jekyll_demo/kppk/_layouts/post.html
           Warning: You didn't set an URL in the config file, you may encounter problems with some plugins.
           Warning: Your site URL does not seem to be absolute, check the value of `url` in your config file.
```

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  Windows 10 - 10.0.17763 build 17763           |
| `jekyll`         | jekyll 3.8.5 |

---

## Expected Behaviour

I'm expecting the site to build with `bundle exec jekyll build` on a Windows machine. 

[My configuration includes](https://github.com/epogrebnyak/kppk/blob/9614daf389cc5a140a75cb153a05947dbd655368/_config.yml#L2) `--source DIR` flag:

```
source: source
```
I have four files in `source` folder:

another-page.md
index.md
thumbnail.png
_posts\2019-03-09-welcome-to-jekyll.markdown

## Current Behavior

My build passes but the resulting files in `_site` directory are empty. 

Instead of looking at 

`D:/github/here_is_jekyll_demo/kppk/_layouts/default.html`

jekyll attempts to read a non-existent file 

`D:/github/here_is_jekyll_demo/kppk/source/github/here_is_jekyll_demo/kppk/_layouts/default.html`

As a user I want to separate the source file form layouts also when using `--source DIR` option. In an undocumented way jekyll expects the layouts to be insude `source` folder.

On a local machine I get this error:

```
Error reading file D:/github/here_is_jekyll_demo/kppk/_layouts/default.html: No such file or directory @ rb_sysopen - D:/github/here_is_jekyll_demo/kppk/source/github/here_is_jekyll_demo/kppk/_layouts/default.html
Error reading file D:/github/here_is_jekyll_demo/kppk/_layouts/post.html: No such file or directory @ rb_sysopen - D:/github/here_is_jekyll_demo/kppk/source/github/here_is_jekyll_demo/kppk/_layouts/post.html
```
A similar message is given by `jekyll doctor`

On Appveyor there is a [similar error](https://ci.appveyor.com/project/epogrebnyak/kppk/builds/22960621), just the folder structure is different. 

```
bundle exec jekyll build
Configuration file: C:/projects/kppk/_config.yml
            Source: source
       Destination: C:/projects/kppk/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Error reading file C:/projects/kppk/_layouts/default.html: No such file or directory @ rb_sysopen - C:/projects/kppk/source/projects/kppk/_layouts/default.html 

Error reading file C:/projects/kppk/_layouts/post.html: No such file or directory @ rb_sysopen - C:/projects/kppk/source/projects/kppk/_layouts/post.html 
                    done in 0.297 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Build success
```
Similar problem reported earlier in #3248.

If that matters, there is a different error on [Travis CI on Linux](https://travis-ci.com/epogrebnyak/kppk/builds/103811808)

The project repository is [here](https://github.com/epogrebnyak/kppk) - it is a fork from Github Pages minimal theme.

**Comment by ashmaroli** [comment]
Jekyll looks for `_layouts` either inside your configured `source` or inside a theme-gem.

**Comment by pathawks** [comment]
>  In an undocumented way jekyll expects the layouts to be insude source folder.

Can you explain in a bit more detail where you _expected_ Jekyll to find the layouts? Are you using a theme?

I’m not sure if this issue is trying to address a hole in our documentation, or a Windows specific issue.

**Comment by epogrebnyak** [comment]
@ashmaroli , @pathawks many thanks for helping! Initially, I was not sure if it is a bug on Windows or a documentation whole, but now it looks like a documentation or maybe feature request. 

I realise I might be coming from different angle to separating the content from representation. In documentation engine like `sphinx` the `source` usually refers to plain-text RestructuredText or Markdown files with content-only, not a layout [[link](http://www.sphinx-doc.org/en/master/usage/quickstart.html)]:

> The root directory of a Sphinx collection of reStructuredText document sources is called the source directory. 

It quite intuitive for the user to do two jobs separately - do (1) presentation/view setup, (2) add more content as markdown files. Jekyll seems to achieve that through theme gem, but by default in Github Pages themes the content source files are in root of repo and that is a bit messy.

My usercase was the following (skipping detours on other issues):
- I forked <https://github.com/pages-themes/minimal>
- wanted more separation of content from presentation (in my subjective view mixing the site content files with all configuration files in repo root is not clean and makes me loose focus on what should I edit)
- read about `--source DIR`  flag and configuration option in documentation
- tried it, created `source` folder with markdown files
- run into error
- searched for similar issues, bumped at #3248 
- filled this issue

As for documentatation, I would have been glad to learn what @ashmaroli wrote either in documentation or a more friendly error message about layout not found.

> Jekyll looks for _layouts either inside your configured source or inside a theme-gem.

Current error message is just low-level file access error (and it makes think of is it Windows issue):

`No such file or directory @ rb_sysopen - D:/github/here_is_jekyll_demo/kppk/source/github/here_is_jekyll_demo/kppk/_layouts/default.html`

There is hardly a chance a user could have guessed she has to put all the paths to repo folder inside a source folder - I think this is a least intuitive part of jekyll behaviour. A more understandable path could have been `source/_layout` + a couple hints about it in documentation.  Older issue #3248 also discusses a more firendly error message and possible addition to documentation.

Maybe there are other ways to keep the markdown files in a separate folder, that I have not tried. It looks like theme-gem is rather standard way, but I loose option to edit the layout in that case I think.

**Comment by ashmaroli** [comment]
> Current error message is just low-level file access error

@epogrebnyak That particular issue had already been fixed on our `master` branch.
Nevertheless, I've opened a pull request (:point_up:) to provide additional hints to users in such situations and have also included a note in the documentation

**Comment by epogrebnyak** [comment]
@ashmaroli - thanks for following up on the request, I think a PR fully addresses issue I raised.
