### ISSUE TITLE
Excerpt: Footnote definition <...> is unreferenced - ignoring

### ISSUE THREAD

**Issue by TWiStErRob** [jekyll/jekyll#7576]
## For Reproducing
1. Clone https://github.com/TWiStErRob/repros
2. `cd repros/jekyll/excerpt-footnotes`
2. `bundle install`
3. `bundle exec jekyll build`

## Expected:
```
Configuration file: P:/projects/bugs/jekyll-footnotes/_config.yml
            Source: P:/projects/bugs/jekyll-footnotes
       Destination: P:/projects/bugs/jekyll-footnotes/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 0.04 seconds.
```
## Actual:
```
Configuration file: P:/projects/bugs/jekyll-footnotes/_config.yml
            Source: P:/projects/bugs/jekyll-footnotes
       Destination: P:/projects/bugs/jekyll-footnotes/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Kramdown warning: Footnote definition for '1' on line 4 is unreferenced - ignoring
                    done in 0.04 seconds.
```

## Details
The problem seems to be that the abstract doesn't contain a reference to the footnote, which is a reasonable occurrence. The `excerpt_separator` makes no difference, I'm just using an explicit one on my site and it shows where it is better for this repro.

What makes the warning go away:
 * removing `jekyll-feed` from `Gemfile`
 * changing to `abstract [^1]`
 * downgrading to Jekyll 3.6.3, here's the diff between 3.6.3 and 3.7.4:
    ```
    Using jekyll-watch 2.1.2 (was 1.5.1)
    Using rouge 3.3.0 (was 2.2.1)
    Using jekyll 3.7.4 (was 3.6.3)
    ```

This only started showing up when I updated the version, very likely https://github.com/jekyll/jekyll/pull/6522 brought the problem to the surface. That PR is a really good change since it helps fixing issues in my md files, but having an issue I can't fix makes the build noisy and opens up the possibility of not seeing other warnings.

**Comment by ashmaroli** [comment]
When attempting to reproduce the issue with latest `master` locally, the warning appears *once*. Subsequent builds do not register a warning because of disk-caching.

Deleting the `.jekyll-cache` or building with `--safe` resurfaces the issue.

**Comment by TWiStErRob** [comment]
Here's a full repro project with new findings (on latest stable):
[excerpt-footnotes.zip](https://github.com/jekyll/jekyll/files/2974135/excerpt-footnotes.zip)

**Comment by ashmaroli** [comment]
For security reasons, maintainers prefer cloning public repos over attachments.

**Comment by TWiStErRob** [comment]
Oh, didn't know, see linked commit above your comment.

**Comment by TWiStErRob** [comment]
Awesome, thanks @mattr- for the fix. And thanks @ashmaroli for your patience and help in figuring out where this belongs.
