### ISSUE TITLE
feat: Allow link tag to use liquid arguments as a tag value

### ISSUE THREAD

**Issue by aoberoi** [jekyll/jekyll#7582]
## Summary

The `link` tag is great. It let's me turn a path into a link, and make sure that link is valid at compile time. However, if I have the value of the path in a template variable, I can't do anything with the link tag to get the same awesomeness. I'd like to be able to do: `{$ link '{{ variable }}' $}`.

## Motivation

It's a pretty common operation to iterate over a collection to build navigation. Recently, I tried to do this, but I ended up need to do an ugly `| prepend site.baseurl` to get it to work. The `link` tag already takes care of that for me, so why am I having to reinvent this for myself? Well, its because I can't give the `link` tag a variable.

For example, this is what I want to do:

```
{% for widget in site.widgets %}
  <li>
    <a href="{% link '{{ widget.path }}' %}">{{ widget.title }}</a>
  </li>
{% endfor %}
```

And this is what I have to do:

```
{% for widget in site.widgets %}
  <li>
    <a href="{{ widget.url | prepend: site.baseurl }}">{{ widget.title }}</a>
  </li>
{% endfor %}
```

And I won't get the benefit of knowing if my links broke.

## Guide-level explanation

> The `link` tag has an argument which is the path to a document (post, page, or other item in a collection): `{% link path/to/file.md %}`. Sometimes, the path is already in another variable, like when iterating over a collection. In these cases you can format the path using a liquid argument: {% link '{{ page.path }}' %}`

## Reference-level explanation

There's a pretty good explanation of this capability, which has already been implemented on the `asset` tag, here: https://github.com/envygeeks/jekyll-assets#liquid

## Drawbacks

Complexity of implementation I suppose. The implementation in `asset` is probably easy enough to take, but is it easy to maintain?

## Unresolved Questions

None.

**Comment by ashmaroli** [comment]
@aoberoi This has already been implemented on `master` and will be available as part of `jekyll-4.0`.
Though note that the syntax is `{% link {{ page.my_variable }} %}` (*no enclosing quotes*)

*If you'd like to test it, we've shipped a pre-release version.* [Feel free to take it for a test-drive](https://jekyllrb.com/news/2019/03/18/jekyll-4-0-0-pre-alpha1-released/).

**Comment by aoberoi** [comment]
Thanks @ashmaroli, that's great news. The syntax is even better than I suggested, which I was shamelessly taking from the `asset` implementation 🙌.

Unfortunately, I'm building for GitHub Pages, so I won't be able to take advantage of the pre-apha1 release. But I'm so grateful that this project is continuing to evolve! Keep up the good work, and I'll look around here for a bit to see if there's anything I can help with.

**Comment by ashmaroli** [comment]
Thank you @aoberoi.
Pull requests from the community are always most welcome and appreciated :smiley:
