### ISSUE TITLE
Makefile:267: *** multiple target patterns.

### ISSUE THREAD

**Issue by symant233** [jekyll/jekyll#7587]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | windows10 1809|
| `jekyll`         | Latest     |
| ruby | 2.5.3p105|
| gem | `2.7.6` |

My `make` version:
```
PS C:\WINDOWS\system32> make -v
GNU Make 3.82.90
Built for i686-pc-mingw32
```

When I just install jekyll using 'gem install jekyll'
```
PS C:\WINDOWS\system32> gem install jekyll
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Program Files/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb
-0.6.0/ext/ruby_http_parser
"C:/Program Files/Ruby25-x64/bin/ruby.exe" -r ./siteconf20190326-20016-1h80js6.rb extconf.
rb
creating Makefile

current directory: C:/Program Files/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6
.0/ext/ruby_http_parser
make "DESTDIR=" clean
Makefile:267: *** multiple target patterns.  Stop.

current directory: C:/Program Files/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6
.0/ext/ruby_http_parser
make "DESTDIR="
Makefile:267: *** multiple target patterns.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Program Files/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ht
tp_parser.rb-0.6.0 for inspection.
Results logged to C:/Program Files/Ruby25-x64/lib/ruby/gems/2.5.0/extensions/x64-mingw32/2
.5.0/http_parser.rb-0.6.0/gem_make.out
```

**Comment by ashmaroli** [comment]
@symant233 Did you install Ruby via the RubyInstaller program? If yes:
  - Did you install the DevTools in the last stage of the installation and
  - What is the output from running `ridk version`?

**Comment by symant233** [comment]
I have ruby reinstalled using rubyinstaller-devkit-2.5.3-1-x64.exe, but I'm wondering if I really install the devkit or not. Because I using 'gem install jekyll' then the MAKE error occurs again...

```>ridk version
---
ruby:
  path: C:/Program Files/Ruby25-x64
  version: 2.5.3
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.3-1
  git_commit: 16e7aa4
msys2:
  path: C:\Program Files\Ruby25-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev3, Built by MSYS2 project) 8.2.0
os: Microsoft Windows [version 10.0.17763.379]
```

**Comment by ladislav37** [comment]
Hello. I had the same problem. It is beacuse of the space in path to your Ruby instalation. Reinstall it to path without spaces and will work..  
Check this article:
https://stackoverflow.com/questions/2100448/multiple-target-patterns-makefile-error

**Comment by symant233** [comment]
I had read this before but I did't find such line in the jekyll makefile.
Now I'm stop trying to install jekyll in windows...

**Comment by GloomyGhost-MosquitoSeal** [comment]
Try tp use WSL

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
@ladislav37 thank you for sharing your solution. Removing the spaces in the file path solved it for me 👍

**Comment by vimmak** [comment]
@ladislav37 thanks too, I met the same problems of the "make failed, exit code 2", finally follow your solution, reinstall Ruby and succeed in install jekyll. Thank you very much.
