### ISSUE TITLE
real embedded section of text

### ISSUE THREAD

**Issue by Franck78** [jekyll/jekyll#7602]
Hello,

## Code Sample

```

---
layout: page
title: xxxx
permalink: /test/
---
# titre 1
## titre 2
blah blah
<div>
        <p>xxxxxxxxxxxxxxx</p>
        <p>yyyyyyyyyyyyyyyy,</p>
        <p>zzzzzzzzzzzzzzzz</p>
</div>
# titre 3
## titre 4
blah blah

```

The goal was to quickly move to Jekyll by doing a simple copy/past of the body section of a static page.
This does not work because there is no way to just say "raw text here".

Consequently, some analysis of the html inside the div is done and the result is not good.
(and there is no error according to w3c validator)

According to html specs, &lt;/p> is an optional closing tag.

But if you remove one of them in this example, the closing </div> is rendered as & lt;/div& gt;
And the final real served html page is screwed.

## Expected :

Real section of text copied without any interpretation of any kind. 

There is a &lt;div markdown='1'> that almost does it.
Perhaps a &lt;div markdown='x'> can NOT add the &lt;code> highlight stuff...

Just to allow conversion chunk by chunk of imported static pages.

**Comment by DirtyF** [comment]
Didi you consider using includes for the HTML parts?

**Comment by Franck78** [comment]
@DirtyF, No !
This does not really make sense. I use includes for things that are reused anywhere, many times.
May work as a workaround , but it is 'how complicates things that are easily done'. Perl, bash (python?) have such basic functionality for example.

**Comment by ashmaroli** [comment]
@Franck78 All of the Markdown/HTML in a markdown page is handled by the `kramdown` gem.
Moreover, it renders and text indented by more than 4 spaces as part of a code-block.

Regarding the closing `</p>` tag, you may want to approach https://github.com/gettalong/kramdown for any open or previous issue-tickets or pull requests

**Comment by Franck78** [comment]
I understand it is a kramdown bug. But somewhere, it is Jekyll who decides to call markdown on a certain portion a certain file no ? If somewhere something says "no rendering", then Jekyll passes the text as it is to the <<content>>. 
~~~
---
layout: x
rendering: NO  (or kramdown or xyz)
---
this portion is not translated in any way.
~~~

**Comment by DirtyF** [comment]
Feel free to develop a plugin in you want to modify parsing, but for most of people the current behavior works fine.

**Comment by Franck78** [comment]
Let me guess....

It needs 1 line to read the YAML and decide if the thing is published or not
(in publisher.rb)

```
    def can_be_published?(thing)
      thing.data.fetch("published", true) || @site.unpublished
    end

```

and a plug-in is necessary to ask a similar question
that would just skip three lines ???
(in renderer.rb)
```
      Jekyll.logger.debug "Rendering Markup:", document.relative_path
      output = convert(output.to_s)
      document.content = output

```

The worrying thing is the inadmissible action from DirtyF (won't fix). Without any valid argumentation.


>  for a majority of people the current behavior works fine:
of course it does. For every new project

And what for the guy migrating an existing site ?
Not enough. The guy spent hours building the skeleton, avoiding redundancy, etc etc and when comes the moment to copy the core content of the migrated site (the body sections), all valid  html, wait no, not possible.
Jekyll will possibly screw the html because of a renderer not needed.
The guy cannot put online the new jekill site and keep working on converting to markdown.

**Comment by DirtyF** [comment]
> And what for the guy migrating an existing site ?

As you may know there's an import plugin:
https://github.com/jekyll/jekyll-import

You also may use tools like Pandoc to convert your HTML to Jekyll.
Anyway I stand by _my_ decision to not change default rendering in Jekyll core.
