### ISSUE TITLE
GitHub Pages + Jekyll + Bootstrap + CDN question

### ISSUE THREAD

**Issue by SergeySypalo** [jekyll/jekyll#7606]
I'm new to GitHub Pages and Jekyll, and moving my blog https://sypalo.com to it.

I decided to use CDN for Twitter Bootstrap, so just copied example links from official website to the default.html template which is in the https://github.com/SergeySypalo/sergeysypalo/blob/master/_site/_layouts/default.html

But when my site is generated, Jekyll creates a local copy of css on the fly, so instead of pointing to the CDN, it creates a link to /assets/styles.css file, but styles are not applied.

Also, at the default.html page bottom, instead of 3 JavaScript files on CDN I got only one unknown to me pointing to CloudFlare.

Or is it a bug or what I have to do to bypass Jekyll processing links to the files located on CDN?

P.S. You can compare default.html contents (css at the top and links to js at the bottom) and what is generated by GitHub builtin Jekyll engine by opening http://sypalo.com and looking at the page source.

**Comment by DirtyF** [comment]
Hey, thanks for your interest in Jekyll, this repository is dedicated to bug reports in the core only.

Please head over to our community forum to ask for help on usage: https://talk.jekyllrb.com
