### ISSUE TITLE
docs: Small change in Jekyll on macOS - avoid root installs

### ISSUE THREAD

**Issue by haakoo** [jekyll/jekyll#7608]
## Motivation

Avoid the event where the user install `jekyll` and `bundler` as `root` on macOS, before telling them it's best not to do this. The way the documentation is written on [Jekyll on macOS](https://jekyllrb.com/docs/installation/macos/) this might happen. If the user is following along and using the commands they'll end up installing this as root.

## Suggestion

Change the recommendation of installing `jekyll` and `bundler` to default with `--user-install`, since this i recommended. Then (maybe) give the alternative method of installing them globally. Wouldn't someone who needs to install them globally know how to do this anyway?

**Comment by liamrosenfeld** [comment]
That is the main thing I am trying to implement in #7561 (along with fixing some directories that changed).
