### ISSUE TITLE
Installation fails with "unhandled special"

### ISSUE THREAD

**Issue by panicsteve** [jekyll/jekyll#762]
Mac OS X 10.8.2:

$ sudo gem update --system
Updating RubyGems
Updating rubygems-update
Successfully installed rubygems-update-1.8.24
Updating RubyGems to 1.8.24
Installing RubyGems 1.8.24
RubyGems 1.8.24 installed

== 1.8.24 / 2012-04-27
- 1 bug fix:
  - Install the .pem files properly. Fixes #320
  - Remove OpenSSL dependency from the http code path

---

RubyGems installed the following executables:
    /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/gem

$ sudo gem install jekyll
Fetching: fast-stemmer-1.0.1.gem (100%)
Building native extensions.  This could take a while...
Fetching: classifier-1.3.3.gem (100%)
Fetching: directory_watcher-1.4.1.gem (100%)
Fetching: syntax-1.0.0.gem (100%)
Fetching: maruku-0.6.1.gem (100%)
Fetching: kramdown-0.13.8.gem (100%)
Fetching: yajl-ruby-1.1.0.gem (100%)
Building native extensions.  This could take a while...
Fetching: posix-spawn-0.3.6.gem (100%)
Building native extensions.  This could take a while...
Fetching: pygments.rb-0.3.7.gem (100%)
Fetching: jekyll-0.12.0.gem (100%)
Successfully installed liquid-2.4.1
Successfully installed fast-stemmer-1.0.1
Successfully installed classifier-1.3.3
Successfully installed directory_watcher-1.4.1
Successfully installed syntax-1.0.0
Successfully installed maruku-0.6.1
Successfully installed kramdown-0.13.8
Successfully installed yajl-ruby-1.1.0
Successfully installed posix-spawn-0.3.6
Successfully installed pygments.rb-0.3.7
Successfully installed jekyll-0.12.0
11 gems installed
Installing ri documentation for liquid-2.4.1...
Installing ri documentation for fast-stemmer-1.0.1...
Installing ri documentation for classifier-1.3.3...
Installing ri documentation for directory_watcher-1.4.1...
Installing ri documentation for syntax-1.0.0...
Installing ri documentation for maruku-0.6.1...
Couldn't find file to include: 'MaRuKu.txt'
Installing ri documentation for kramdown-0.13.8...
Installing ri documentation for yajl-ruby-1.1.0...
Installing ri documentation for posix-spawn-0.3.6...
Installing ri documentation for pygments.rb-0.3.7...
Installing ri documentation for jekyll-0.12.0...
ERROR:  While generating documentation for jekyll-0.12.0
... MESSAGE:   Unhandled special: Special: type=17, text=""
... RDOC args: --ri --op /Library/Ruby/Gems/1.8/doc/jekyll-0.12.0/ri --charset=UTF-8 lib README.textile LICENSE --title jekyll-0.12.0 Documentation --quiet

**Comment by dagolinuxoid** [comment]
linux@linux-desktop:~$ sudo gem install rdoc
Building native extensions.  This could take a while...
ERROR:  Error installing rdoc:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.2 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/json-1.8.2/ext/json/ext/generator/gem_make.out
PS. linux@linux-desktop:~$ ruby -v
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
linux@linux-desktop:~$ gem -v
1.8.11
 It's drive me craZy (distro ElementaryOS)

**Comment by envygeeks** [comment]
This is not rdoc support, this is for Jekyll. Install your Ruby headers `apt-get install ruby1.9.1-dev`
