### ISSUE TITLE
Front matter error in scss file.

### ISSUE THREAD

**Issue by llgjermeni** [jekyll/jekyll#7628]
Hi, I just started working with Jekyll in local and I'm facing a problem. I followed the steep by steep tutorial from the official site and everything was fine until I added sass.  I have created a _sass/main.scss file where I have normal scss code and css/styles.scss where I added the front matter empty block. The tutorial say 'The empty front matter at the top tells Jekyll it needs to process the file. ' but in this line have the error and scss is not compiling. I googled and didn't find any solution. I work in VS Code already have installed sass and scss-lint but no results. 
I appreciate any help, thanks.

![Capture](https://user-images.githubusercontent.com/8567108/56607917-eee16b00-6609-11e9-8abf-cd101e99e07b.PNG)

**Comment by sodevious** [comment]
What's the error in the CLI?

**Comment by llgjermeni** [comment]
Doesn't compile the scss and the error is can't find the .css file from the layout.

**Comment by ashmaroli** [comment]
@llgjermeni Can you copy-paste the exact error message here? Its possible that your interpretation of the error be incorrect.
Additionally, ensure that any partials imported within `_sass/main.scss` actually exist.

**Comment by llgjermeni** [comment]
I followed the tutorial steep by steep from the Jekyll site. I think this is a syntax error sass doesn't recognize the front matter. I opened another Jekyll project https://github.com/llgjermeni/llazar-resume in local and shows the same error. The error is shown in the image above. The `_sass/main.scss` exist see the image for reference.

**Comment by ashmaroli** [comment]
@llgjermeni Its not a syntax error for Jekyll's sass converter. The image you posted is only showing error in the code editor not the terminal output from Jekyll.
Moreover, I wasn't able to reproduce any error by cloning the repo `https://github.com/llgjermeni/llazar-resume` and building it locally at my end.

Recommended steps:
1. Update bundle by running **`bundle update`**
2. Run with the current bundle in context: **`bundle exec jekyll build`**

**Comment by llgjermeni** [comment]
This commands aren't resolving my error. You can see the error.
>Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles.scss':
                    Invalid CSS after "@import 'main'": expected "{", was ";" on line 4
jekyll 3.8.5 | Error:  Invalid CSS after "@import 'main'": expected "{", was ";" on line 4

**Comment by ashmaroli** [comment]
See..? The actual error is `Invalid CSS after "@import 'main'"`, not the front matter block which is before the `@import` call.
Please post the contents of your `_sass/main.scss` or a link to the repository.

**Comment by llgjermeni** [comment]
The content of the `asstes/css/styles.scss`

```
---
---

@import 'main';

```

The content of `_sass/main.scss`

```
.current {
    color: green;
}
```

**Comment by ashmaroli** [comment]
I don't see any Invalid CSS there..

**Comment by jakecatron** [comment]
@llgjermeni did you ever figure out how to resolve this issue? I'm running into the same problem

**Comment by llgjermeni** [comment]
@jakecatron I think the problem is that VS Code take the front matter as syntax error and the red line of error will be all the time. You just need to compile the sass so I deleted everything in the sass file with front matter and started from beginning and worked for me.

**Comment by jakecatron** [comment]
@llgjermeni Thanks for the response - I actually just figured out the issue. For my use case, I need to be running `jekyll-asset-pipeline` and didn't have that setup. Once that is in place, I won't need the front matter at all.
