### ISSUE TITLE
include_relative fails if it is the first paragraph (used for the #excerpt)

### ISSUE THREAD

**Issue by willymcallister** [jekyll/jekyll#7629]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     MacOS 10.14.4       |
| `jekyll`         | 3.8.5     |
| `github-pages`   | 198     |

---

## Expected Behaviour

Build without error.

## Current Behavior

A markdown file has an include_relative as the first line of the file. 
`{% include_relative eulers-cosine-d3.html %}` 

The referenced file is in the same directory as the markdown file. In prior versions of Jekyll this worked fine. In my current version, 3.8.5 (the same one used by github-pages) the build fails with this email from GitHub:

The page build failed for the `master` branch with the following error:
A file was included in `_articles/eulers-cosine.md/#excerpt` that is a symlink or does not exist in your `_includes` directory.

## Code Sample

Repository: https://github.com/willymcallister/willymcallister.github.io/blob/master/_articles/eulers-cosine.md

Raw markdown file, with a blank space as the first paragraph as a work around for the bug,
https://raw.githubusercontent.com/willymcallister/willymcallister.github.io/master/_articles/eulers-cosine.md

If you remove the first line, `<p>&nbsp;</p>`, then the next line with the include_relative becomes the first paragraph, 
`{% include_relative eulers-cosine-d3.html %} `
This line is extracted as the #excerpt for the article, and the build fails.

**Comment by ashmaroli** [comment]
@willymcallister Could you try our `3.8-stable` branch without your workaround and get back to us?
```ruby
# your Gemfile

gem "github-pages"
gem "jekyll", path: "https://github.com/jekyll/jekyll.git", branch: "3.8-stable"

# any other gems you may need locally..
```
Ensure that you run `bundle install` to fetch the branch snapshot.

*Note: The above applies only to the local environment and not on GitHub Pages*

**Comment by willymcallister** [comment]
I added the suggested line to my Gemfile, but I get an error when I bundle install. The path to the branch gets appended to my website’s URL.?  Suggestions?

The path `/Users/willymcallister/KA/spinningnumbers/https:/github.com/jekyll/jekyll.git` does not
exist.

source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
#gem "jekyll", "3.4.0"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
   gem 'github-pages'
   gem "jekyll", path: "https://github.com/jekyll/jekyll.git", branch: "3.8-stable"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


— Willy McAllister


On Apr 24, 2019, at 12:22 AM, Ashwin Maroli <notifications@github.com> wrote:

@willymcallister <https://github.com/willymcallister> Could you try our 3.8-stable branch without your workaround and get back to us?

# your Gemfile

gem "github-pages"
gem "jekyll", path: "https://github.com/jekyll/jekyll.git", branch: "3.8-stable"

# any other gems you may need locally..
Ensure that you run bundle install to fetch the branch snapshot.

Note: The above applies only to the local environment and not on GitHub Pages

**Comment by ashmaroli** [comment]
@willymcallister My apologies! It should've been `git:` instead of `path:`...
(What was I thinking..??)

```ruby
# your Gemfile

gem "github-pages"
gem "jekyll", git: "https://github.com/jekyll/jekyll.git", branch: "3.8-stable"

# any other gems you may need locally..
```

**Comment by willymcallister** [comment]
Still fails the same way using jekyll version 3.8-stable.
	If the first paragraph is an include_relative the site build fails.
	If I add a paragraph with just a non-blocking space,  `<p>&nbsp;</p>`, at the beginning the build works.

Below: Gemfile, followed by terminal output for bundle install, followed by error message

Gemfile
source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
#gem "jekyll", "3.4.0"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
   gem 'github-pages'
   gem "jekyll", git: "https://github.com/jekyll/jekyll.git", branch: "3.8-stable"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

Terminal window for bundle install

Willy2-MPB:~/KA/spinningnumbers $ bundle install
Fetching https://github.com/jekyll/jekyll.git
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using concurrent-ruby 1.1.5
Using minitest 5.11.3
Using thread_safe 0.3.6
Using public_suffix 3.0.3
Using coffee-script-source 1.11.1
Using execjs 2.7.0
Using colorator 1.1.0
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using ffi 1.10.0
Using multipart-post 2.0.0
Using forwardable-extended 2.6.0
Using gemoji 3.0.0
Using rb-fsevent 0.10.3
Using ruby_dep 1.5.0
Using kramdown 1.17.0
Using liquid 4.0.0
Using mercenary 0.3.6
Using rouge 2.2.1
Using safe_yaml 1.0.5
Using mini_portile2 2.4.0
Using jekyll-paginate 1.1.0
Using rubyzip 1.2.2
Using jekyll-swiss 0.4.0
Using unicode-display_width 1.5.0
Using bundler 1.14.6
Using i18n 0.9.5
Using tzinfo 1.2.5
Using addressable 2.5.2
Using coffee-script 2.4.1
Using em-websocket 0.5.1
Using ethon 0.12.0
Using rb-inotify 0.10.0
Using faraday 0.15.4
Using pathutil 0.16.2
Using nokogiri 1.10.3
Using terminal-table 1.8.0
Using ruby-enum 0.7.2
Using activesupport 4.2.11.1
Using dnsruby 1.61.2
Using jekyll-coffeescript 1.1.1
Using typhoeus 1.3.1
Using sass-listen 4.0.0
Using listen 3.1.5
Using sawyer 0.8.1
Using commonmarker 0.17.13
Using html-pipeline 2.11.0
Using sass 3.7.4
Using jekyll-watch 2.2.1
Using octokit 4.14.0
Using jekyll-sass-converter 1.5.2
Using github-pages-health-check 1.16.1
Using jekyll-gist 1.5.0
Using jekyll 3.8.5 from https://github.com/jekyll/jekyll.git (at 3.8-stable@3c06609)


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password: 
Using jekyll-avatar 0.6.0
Using jekyll-commonmark 1.3.1
Using jekyll-default-layout 0.1.4
Using jekyll-feed 0.11.0
Using jekyll-github-metadata 2.12.1
Using jekyll-mentions 1.4.1
Using jekyll-optional-front-matter 0.3.0
Using jekyll-readme-index 0.2.0
Using jekyll-redirect-from 0.14.0
Using jekyll-relative-links 0.6.0
Using jekyll-remote-theme 0.3.1
Using jekyll-seo-tag 2.5.0
Using jekyll-sitemap 1.2.0
Using jekyll-titles-from-headings 0.5.1
Using jemoji 0.10.2
Using jekyll-commonmark-ghpages 0.1.5
Using jekyll-theme-architect 0.1.1
Using jekyll-theme-cayman 0.1.1
Using jekyll-theme-dinky 0.1.1
Using jekyll-theme-hacker 0.1.1
Using jekyll-theme-leap-day 0.1.1
Using jekyll-theme-merlot 0.1.1
Using jekyll-theme-midnight 0.1.1
Using jekyll-theme-minimal 0.1.1
Using jekyll-theme-modernist 0.1.1
Using jekyll-theme-primer 0.5.3
Using jekyll-theme-slate 0.1.1
Using jekyll-theme-tactile 0.1.1
Using jekyll-theme-time-machine 0.1.1
Using minima 2.5.0
Using github-pages 198
Bundle complete! 5 Gemfile dependencies, 85 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Willy2-MPB:~/KA/spinningnumbers $ 

Error message:

  Liquid Exception: Could not locate the included file 'eulers-cosine-d3.html' in any of ["/Users/willymcallister/KA/spinningnumbers/_articles/eulers-cosine.md"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in /Users/willymcallister/KA/spinningnumbers/_articles/eulers-cosine.md/#excerpt
  Liquid Exception: Could not locate the included file 'eulers-cosine-d3.html' in any of ["/Users/willymcallister/KA/spinningnumbers/_articles/eulers-cosine.md"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in /_layouts/default.html
             Error: Could not locate the included file 'eulers-cosine-d3.html' in any of ["/Users/willymcallister/KA/spinningnumbers/_articles/eulers-cosine.md"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode.
             Error: Run jekyll build --trace for more information.


- Willy


On Apr 25, 2019, at 6:57 PM, Ashwin Maroli <notifications@github.com> wrote:

@willymcallister <https://github.com/willymcallister> My apologies! It should've been git: instead of path:...
(What was I thinking..??)

# your Gemfile

gem "github-pages"
gem "jekyll", git: "https://github.com/jekyll/jekyll.git", branch: "3.8-stable"

# any other gems you may need locally..
