### ISSUE TITLE
Algorithm pseudocode in kramdown

### ISSUE THREAD

**Issue by fjp** [jekyll/jekyll#7631]
Hi,
I am using kramdown and I am able to get latex formulas displayed correctly. Now I would like to add an algorithm using the latex package algorithm2e. This [answer](https://tex.stackexchange.com/a/452565/39188) on the tex.stackexchange shows that it works with markdown and pandoc.

I added the package in a [post](https://fjp.at/posts/localization/mcl/#monte-carlo-localization-algorithm) in the preamble and copied the example from stackexchange but the algorithm does not get rendered as expected.

Here is the [link](https://github.com/fjp/fjp.github.io) to the repo of my github page.

How can I add extra latex packages using kramdown?

The [answer of an issue](https://github.com/gettalong/kramdown/issues/511#issuecomment-391333554) in kramdown states to use a custom latex template. However, I have no idea how to use a new template.

**Comment by DirtyF** [comment]
👋 @fjp, I never used LateX with Jekyll. Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage, this repo is to report bugs within Jekyll core only. Thanks.

**Comment by madebymaze** [comment]
I have managed to make LaTeX work.

* I have created a file "mathjax_support" and added to _includes. The file includes this:
`<script type="text/x-mathjax-config"> MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "all" } } }); </script>
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {
        inlineMath: [ ['$','$'], ["\\(","\\)"] ],
        displayMath: [ ['$$','$$'] ],
        processEscapes: true
      }
    });
  </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>`
* I have included the following lines to my post.html, where I have my post templates.
`{% if page.use_math %}
        {% include mathjax_support %}
    {% endif %}`
* Add my LaTeX code like such:
`$$
\begin{align}
v(t_1) &= v(t_0) + \int_{t_0}^{t_1} a(t) dt \\  
x(t_1) &= x(t_0) + \int_{t_0}^{t_1} v(t) dt \\
\end{align}
$$`

**Comment by fjp** [comment]
@madebymaze thanks for the positive feedback! Glad the source code helped :grin: 

Let me know if you get other latex packages working. I am still missing a way to use for example [algorithm2e](https://ctan.org/pkg/algorithm2e?lang=de)

**Comment by fjp** [comment]
> Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage

@DirtyF I already posted in the forum before I opened an issue here. https://talk.jekyllrb.com/t/kramdown-latex-usepackage-algorithm-pseudocode/2861/3

> this repo is to report bugs within Jekyll core only.

Is there also a place where I can "request" plugins?

**Comment by madebymaze** [comment]
@fjp I have managed to add pseudocode to my markdown :smile: 
* Download [pseudocode.js](https://github.com/tatetian/pseudocode.js/releases) and [KaTeX](https://github.com/KaTeX/KaTeX/releases)
* Add pseudocode.js and KaTeX to your public folder
* Include them to your header
```
<script src="[path]/katex/katex.min.js"></script>
 <script src="[path]/pseudocode.js-1.1/pseudocode.js" type="text/javascript"></script>
<link rel="stylesheet" href="[path]/katex/katex.min.css">
<link rel="stylesheet" href="[path]/pseudocode.js-1.1/pseudocode.css" type="text/css">
```
* Add this to your _includes folder, I called it pseudocode.html
```
<pre id="read-{{ include.id }}" style="display:none;">
    {{ include.code }}
</pre>
<div id="goal-{{ include.id }}"></div>
<script type="text/javascript">
    var code = document.getElementById("read-{{ include.id }}").textContent;
    var parentEl = document.getElementById("goal-{{ include.id }}");
    var options = {
        lineNumber: true
    };
    pseudocode.render(code, parentEl, options);
</script>
```
* Add the follow line when you want to use it in your kmarkdown file:
```
{% include pseudocode.html id="[any unique value]" code="[pseudocode]" %}
Here is an example of how you can use it:
```
{% include pseudocode.html id="1" code="
\begin{algorithm}
\caption{Quicksort}
\begin{algorithmic}
\PROCEDURE{Quicksort}{$A, p, r$}
    \IF{$p < r$} 
        \STATE $q = $ \CALL{Partition}{$A, p, r$}
        \STATE \CALL{Quicksort}{$A, p, q - 1$}
        \STATE \CALL{Quicksort}{$A, q + 1, r$}
    \ENDIF
\ENDPROCEDURE
\PROCEDURE{Partition}{$A, p, r$}
    \STATE $x = A[r]$
    \STATE $i = p - 1$
    \FOR{$j = p$ \TO $r - 1$}
        \IF{$A[j] < x$}
            \STATE $i = i + 1$
            \STATE exchange
            $A[i]$ with     $A[j]$
        \ENDIF
        \STATE exchange $A[i]$ with $A[r]$
    \ENDFOR
\ENDPROCEDURE
\end{algorithmic}
\end{algorithm}
" %}
```

Thanks to @zietzm for his answer in [this thread](https://github.com/manubot/rootstock/issues/177#issuecomment-462160421), and [pseudocode.js](https://github.com/tatetian/pseudocode.js/) and [KaTeX](https://github.com/KaTeX/KaTeX/) for making the libraries!

**Comment by fjp** [comment]
@madebymaze sounds great, thanks for the instructions. I will definitely give this a try :thumbsup:

**Comment by madebymaze** [comment]
@fjp here is a random example of it https://madebymaze.xyz/posts/yolo

**Comment by fjp** [comment]
@madebymaze thank you for the example, looks great. Very nice blog too btw. I also like the code copy feature.
