### ISSUE TITLE
Various broken links in Jekyll Theme wiki

### ISSUE THREAD

**Issue by CookieComputing** [jekyll/jekyll#7632]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |            |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Current Behavior

There are quite a few links in the Themes wiki section that are either broken, or redirects me to some sort of phishing/spam site, e.g. the Exemplar demo page, the Greentea demo page, and many more. These links should be removed or changed to the correct links

**Comment by DirtyF** [comment]
Now that we have topics on GitHub I feel we can unpublish this WIKI page.
https://github.com/topics/jekyll-themes

Also there are more and more dedicated services for Jekyll themes
https://jekyllthemes.io

**Comment by DirtyF** [comment]
No more broken links on https://github.com/jekyll/jekyll/wiki/Themes 😄
