### ISSUE TITLE
data file not being expanded

### ISSUE THREAD

**Issue by Franck78** [jekyll/jekyll#7635]
Jekyll v4.0.0.pre.alpha1

the string "site.data.something" is not always recognized as a data source.

NOT:  {%- for compo in data -%}  _(data="site.data.composants-micro")_
YES:  {%- for compo in site.data.composants-micro -%}

~~~
---
#
# CSV : Nom,Qte,Fonction,Remarque
#
layout: home
data_sources:
-  id:   "MCU"
   desc: "Microprocesseurs"
   data: "site.data.composants-micro"
-  id:   "74LS"
   desc: "Série TTL 74LS"
   data: "site.data.composants-74LS"
---

<!-- not working, f.data not correctly expanded with CSV data -->
{% for f in page.data_sources %}
  <h1>{{ f.desc }}</h1>
  <div class = "posts" id = "{{ f.id }}">
    {%- for compo in f.data -%}
    {% include composant.html %}
    {%- endfor -%}
  </div>
{% endfor %}

<!-- WORKING but duplicated (bad) -->
<h1>Microprocessors</h1>
<div class = "posts" id = "MCU">
    {%- for compo in site.data.composants-micro -%}
    {% include composant.html %}
    {%- endfor -%}
</div>

<!-- and obviously, this is a repeat loop.... -->
<h1>Série TTL 74LSxx</h1>
<div class = "posts" id = "74LS">
    {%- for compo in site.data.composants-74LS -%}
    {% include composant.html %}
    {%- endfor -%}
</div>

~~~

**Comment by DirtyF** [comment]
You can not store Liquid variables in front matter by default, you can add a custom Liquid filter though: e.g. https://github.com/vividh/liquify/blob/master/liquify.rb

**Comment by ashmaroli** [comment]
@Franck78 While you can't store an entire Liquid Variable in the front matter, you can instead store a reference to the data file indirectly:
```yaml
---
layout: home
data_sources:
-  id:   "MCU"
   desc: "Microprocesseurs"
   src: "composants-micro"
-  id:   "74LS"
   desc: "Série TTL 74LS"
   src: "composants-74LS"
---
# rest of the document
```
Then reference the concerned data file using `site.data[key]`
```html
{% for entry in page.data_sources %}
  <h1>{{ entry.desc }}</h1>
  <div class = "posts" id = "{{ entry.id }}">
    {% for compo in site.data[entry.src] %}
      {% include composant.html %}
    {% endfor %}
  </div>
{% endfor %}
```

**Comment by Franck78** [comment]
Thank you ashmaroli, it is working as described.

The bug (if I may) is more a lack of knowledge. It is impossible for a 'newbee' to tell who do what.
The basic documentation about CSV/json/... data-sources should emphasize that

`for X in site.data.file ` is only a form of side.data"something here"

You see, I don't know how to say it. I feel a lot a variation can go after the _in_ . But is it Ruby or Liquid or Jekyll....

Thank you

**Comment by ashmaroli** [comment]
> I feel a lot a variation can go after the _in_ . But is it Ruby or Liquid or Jekyll....

It is a feature of Liquid. Liquid contains a specialized object called `Liquid::Drop` that allows accessing attributes of an `object` via the *dot-notation* (`object.key`) and via `object[key]`.

This can be categorized as "Advanced Usage" and may have been left out of our documentation to avoid confusing new users.
