### ISSUE TITLE
docs: 

### ISSUE THREAD

**Issue by jmporter** [jekyll/jekyll#7651]
## Motivation

Following the Quickstart guide step by step leads to the following error:

$ bundle exec jekyll serve
Could not locate Gemfile or .bundle/directory

## Suggestion

The quickstart doesn't install jekyll in the new site directory using the bundler. So either install jekyll with bundler or change the instructions to the command:

$ jekyll serve

**Comment by DirtyF** [comment]
@jmporter Thanks for reporting, added the option to use bundler: https://github.com/jekyll/jekyll/blob/master/docs/_docs/step-by-step/01-setup.md#installation
