### ISSUE TITLE
jekyll build failed when _posts have pictures in it

### ISSUE THREAD

**Issue by thinkycx** [jekyll/jekyll#7652]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     ubuntu 16.04       |
| `jekyll`         | 3.8.5     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

I want to use relative links to use my images.
```
a.md
img/1.png
```
And I want to use `![](./img/1.png)` in a.md to get the pictures.

## Current Behavior

when use jekyll build, it fails.
output log:
```
             Error: could not read file /root/blog/website/_posts/img/stack_esp.png: invalid byte sequence in UTF-8
             Error: could not read file /root/blog/website/_posts/img/start_dissemble.png: invalid byte sequence in UTF-8
             Error: could not read file /root/blog/website/_posts/img/start/start: invalid byte sequence in UTF-8
             Error: could not read file /root/blog/website/_posts/img/start/start.idb: invalid byte sequence in UTF-8
```

**Comment by DirtyF** [comment]
Looks like Jekyll does not support binary files in _posts out of the box, you should be able to do so with @nhoizey plugin: https://nhoizey.github.io/jekyll-postfiles/

**Comment by thinkycx** [comment]
Thank you. I have used the plugin however the plugin have many bugs. 

Please consider this scene:
```
_posts/1.md
_drafts/2.md
/asserts/1/1.png
/asserts/2/2.png
```
When you run `jekyll serve`, the picture 2.png will also be moved into the `_site` folder , which is obviously not acceptable.
**I think many people will come into the problem, how do you solve the problem? **

At last, I think if the pictures( or some other binary files) in _posts/ or _drafts/ folder will be copied into the `_site`, it will be more convenient.

**Comment by thinkycx** [comment]
For example, bugs:
1. when I use the postfiles plugin and build, the error log still exists. Do you know how to fix it ?
```
             Error: could not read file /root/blog/website/_posts/img/stack_esp.png: invalid byte sequence in UTF-8
```
