### ISSUE TITLE
How to get jekyll running command  in plugins？

### ISSUE THREAD

**Issue by thinkycx** [jekyll/jekyll#7666]
How to get the jekyll running command( such as whether it is running with --drafts) in _plugin/test.rb?
I have to check whether it is running with --drafts and have somethings to do in _plugin/test.rb.

```
jekyll serve 
jekyll serve --drafts
```

For example, _plugin/test.rb:
```ruby
# if jekyll serve   
print "jekyll serve "
FileUtils.cp_r '/Users/user/jekyll-blog/_posts/asserts/', '/Users/user/jekyll-blog/_site/'

# else if jekyll serve --drafts
print "jekyll serve --drafts"
FileUtils.cp_r '/Users/user/jekyll-blog/_drafts/asserts/', '/Users/user/jekyll-blog/_site/'
```

Is there anyone knows? Thank you.

**Comment by DirtyF** [comment]
🆘 Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage.
⚠️ This repository issues are dedicated to **documented bugs only**.
