### ISSUE TITLE
`unknown_tag': Liquid syntax error

### ISSUE THREAD

**Issue by ukkm** [jekyll/jekyll#7669]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  macOS 10.14.4  |
| Docker  | 18.09.2 |
| `jekyll`         | 3.8.5     |

---

## Expected Behaviour

Within of a Liquid section a loop is opened which is based on a YAML file. The loop variable has the name "ev" and is used to prepare text which will be shown on the web page (index.html)

## Code Sample

```

      {%- assign today = site.time | date: "%Y%m%d" -%}

      {%- assign next_themen_nm = nil -%}
      {%- assign next_busfahrt = nil -%}

      {%- assign dfn_arr = dfn_arr_str | split: "," -%}
      {%- for ev in site.data[dfn]-%}

        {%- assign ev_termin = ev.termin | date: "%Y%m%d" -%}
        {%- if ev_termin > today -%}

          {%- unless next_themen_nm -%}
            {%- if ev.ereignis == "Themennachmittag" -%}
              {%- assign ev_text = "leider keine Angaben" -%}
              {%- if ev.anmerkung -%}
                
  124 -->  {%- assign ev_text = ev.anmerkung -%}

              {%- elsif ev.anmerkungen -%}
                {%- assign ev_text = ev.anmerkungen[0] -%}
              {%- endif -%}
              {%- capture dl_date -%}{%- include function/compute-deadline.html date = ev.termin -%}{%- endcapture -%}
              {%- capture next_themen_nm -%}Der nächste {{ ev.ereignis }} {{ ev_text }} findet am {%- ev.termin | date: "%d.%m.%Y" -%} statt - Gastanmeldungen bis {{ dl_date }}{%- endcapture -%}
            {%- endif -%}
          {%- endunless -%}

          {%- unless next_busfahrt -%}
            {%- if ev.ereignis == "Busfahrt" -%}
              {%- assign ev_text = "leider keine Angaben" -%}
              {%- if ev.anmerkung -%}
                {%- assign ev_text = ev.anmerkung -%}
              {%- elsif ev.anmerkungen -%}
                {%- assign ev_text = ev.anmerkungen[0] -%}
              {%- endif -%}
              {%- capture dl_date -%}{%- include function/compute-deadline.html date = ev.termin -%}{%- endcapture -%}
              {%- capture next_busfahrt -%}Die nächste {{ ev.ereignis }} {{ ev_text }} findet am {%- ev.termin | date: "%d.%m.%Y" -%} statt - Gastanmeldungen bis {{ dl_date }}{%- endcapture -%}
            {%- endif -%}
          {%- endunless -%}

          {%- if next_themen_nm and nex_busfahrt -%}
            {%- break -%} {% comment %}break inner loop{% endcomment %}
          {%- endif-%}
  
        {%- endif -%}

      {%- endfor-%}

```
Liquid throws following error:
```
/usr/local/bundle/gems/liquid-4.0.3/lib/liquid/block.rb:38:in `unknown_tag': Liquid syntax error (line 124): Unknown tag 'ev' (Liquid::SyntaxError)
```

The line being the cause here I marked with "-->".  I can't see any error because the variable "ev" has been used before four times without problems. Wat does go wrong with this simple assign statement.

[trace.txt](https://github.com/jekyll/jekyll/files/3187841/trace.txt)

[YAML-files.zip](https://github.com/jekyll/jekyll/files/3187774/YAML-files.zip)

**Comment by ashmaroli** [comment]
The following is incorrect usage:
```
{%- ev.termin | date: "%d.%m.%Y" -%}
```

**Comment by ukkm** [comment]
Hi ashmaroli,

in case you are saying that the date pattern is incorrect, I don't agree. I need the date which is provided by the field "ev.termin" to compare it with a today date (see the first line). So both have to be comparable and that's true by using the pattern "%Y%m%d". Besides that Liquid has the problem wit the line marked with "124 -->"

**Comment by ashmaroli** [comment]
@ukkm When Liquid says `Liquid syntax error (line 124)`, the reality is that Liquid encountered error at Line 124 of the content provided to it. The content provided to it is your file's content **minus** the front matter block.
Therefore, in the following example, **Liquid will throw a syntax error at Line 2**:
```
---
title: Hello World
layout: page
---

{%- hello 'world' -%}
```

---
`{%- ev.termin | date: "%d.%m.%Y" -%}` is incorrect usage. You should use double-braces here:
```
{{ ev.termin | date: "%d.%m.%Y" }}
```

**Comment by ukkm** [comment]
@ashmaroli The Liquid section is a section of index.html without any front matter. The website I'm working on is alive since over a year. Now it gets an update where the said section belongs to.

**Comment by ukkm** [comment]
The line you say is incorrect usage ist that
        {%- assign ev_termin = ev.termin | date: "%Y%m%d" -%}
It's a normal assign statement.

**Comment by ashmaroli** [comment]
@ukkm Is the source open to public? If yes, please provide a link to the repository.
Please read my comment again. I'm pointing you to incorrect usage in
`{%- ev.termin | date: "%d.%m.%Y" -%}`

Search for **`{%- ev.termin | date: "%d.%m.%Y" -%}`** in your content. Replace with double-braces.

**Comment by ukkm** [comment]
@ashmaroli You are right - Thanks a lot!! I found the line which causes the issue. Indeed the double -braces were the reason. But the number of the line is 129 instead of 124 and the error messages of  Liquid are good for nothing! It's not the first time that I had to struggle with such Liquid issues.

**Comment by Ryuno-Ki** [comment]
> @ukkm When Liquid says `Liquid syntax error (line 124)`, the reality is that Liquid encountered error at Line 124 of the content provided to it. The content provided to it is your file's content **minus** the front matter block.

It's line 129, because you have five lines of frontmatter. (two lines with `---` each + three defined by you).

**Comment by ashmaroli** [comment]
@ukkm Glad you sorted this out. Cheers!
