### ISSUE TITLE
Why my post is getting HTTP 404?!

### ISSUE THREAD

**Issue by imvieira** [jekyll/jekyll#7675]
1 - Created: `https://github.com/imvieira/wiki/docs/_posts/2019-05-17-fundamentos-praticos-a-computacao-quantica-bloch-sphere`
2 - Accessed: `https://imvieira.github.io/wiki/`
3 - Clicked on "Blog", then clicked on the Post name.
4 - HTTP 404.
![Screen Shot 2019-05-19 at 9 07 15 PM](https://user-images.githubusercontent.com/13357603/57990152-1812e100-7a7a-11e9-9a87-328407df9bce.png)

![Screen Shot 2019-05-19 at 8 47 58 PM](https://user-images.githubusercontent.com/13357603/57989868-683c7400-7a77-11e9-9b79-c8e368e19959.png)

**Comment by imvieira** [comment]
[docs.zip](https://github.com/jekyll/jekyll/files/3195803/docs.zip)
following attach my website

**Comment by DirtyF** [comment]
👋 @imvieira,

This repository issues are dedicated to **documented bugs only**.
Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage.🆘 
Also contact GitHub support if your problem is related to Github Pages. Thanks.
