### ISSUE TITLE
feat: ability to stick images next to blog posts.

### ISSUE THREAD

**Issue by burtonator** [jekyll/jekyll#7681]
Jekyll allows you to upload images but I'd like a structure where I kept the images next to the blog post instead of polluting one main directory.

Right now I tried this structure:

![image](https://user-images.githubusercontent.com/45447/58373824-3ef16d00-7ee9-11e9-8a5a-09324c943496.png)

but get the following error:

![image](https://user-images.githubusercontent.com/45447/58373828-4749a800-7ee9-11e9-89d0-10b151e5be24.png)

this would make it much easier to just drag the images into my IDE, update the post, and then publish.

Now I have to update the path and hope the URL is right which is a big pain.

**Comment by DirtyF** [comment]
There's a plugin for that https://nhoizey.github.io/jekyll-postfiles/
