### ISSUE TITLE
Ignore Directories

### ISSUE THREAD

**Issue by lenary** [jekyll/jekyll#77]
Please may we have a facility in _config.yml to ignore directories?

**Comment by mine-cetinkaya-rundel** [comment]
I think this is a relevant place to ask my question as well. I need to host (`.Rmd` - R Markdown files, to be specific), which means I need these files to be copied over to `_site` as part of the build. These files have a YAML on top, and the YAML gets stripped when copied over to `_site`. Is there any way to avoid the YAML from being stripped in files with a certain extension? `exclude` won't do it since I actually want the files to be copied over, and specifying a `markdown_ext` for files other than `.Rmd` also doesn't seem to work.

**Comment by parkr** [comment]
@mine-cetinkaya-rundel Add a fourth `-` to the top of the YAML, or remove the third. Only `---\n` gets processed as you describe.

**Comment by mine-cetinkaya-rundel** [comment]
@parkr Thanks. Unfortunately while that solution works for the YAML not being stripped out, it doesn't actually solve the issue as the file that is copied over has  4`-`s in the YAML and won't compile properly in R Markdown (which also requires a valid YAML).

**Comment by parkr** [comment]
You could also put them in an ignored folder and write a custom plugin to copy them over. Other than that, I'm afraid there's no way Jekyll can be told to ignore things that look like Pages.

**Comment by mine-cetinkaya-rundel** [comment]
@parkr gotcha, thanks.

**Comment by parkr** [comment]
@mine-cetinkaya-rundel Sorry about that? If you do go the ignored folder route, the plugin would look something like:

```ruby
class RmdCopyer < Jekyll::Generator
  RMD_FOLDER = '_rmd'
  RMD_OUTPUT_DIR = 'rmd'
  def generate(site)
    FileUtils.cp_r(site.source_dir(RMD_FOLDER), site.dest_dir(RMD_OUTPUT_DIR))
    site.keep_files << RMD_OUTPUT_DIR unless site.keep_files.include?(RMD_OUTPUT_DIR)
  end
end
```

**Comment by mine-cetinkaya-rundel** [comment]
Thanks for the help, much appreciated. 

This gives me the following error.

~~~
Error:  undefined method `source_dir' for #<Jekyll::Site:0x007f9d41e18300>
~~~

I'm not finding many uses of `site.source_dir` (at least on GitHub), so couldn't track down what the issue might be. I tried searching for how `FileUtils.cp_r` works, and tried the following (getting rid of `site.source_dir` and `site.dest_dir`):

```ruby
class RmdCopyer < Jekyll::Generator
  RMD_FOLDER = '_rmd'
  RMD_OUTPUT_DIR = 'rmd'
  def generate(site)
    FileUtils.cp_r(RMD_FOLDER, RMD_OUTPUT_DIR)
    site.keep_files << RMD_OUTPUT_DIR unless site.keep_files.include?(RMD_OUTPUT_DIR)
  end
end
```

but while this runs without any errors, and copies the `_rmd` directory to `_site/rmd`, it still strips the YAML in the .Rmd files inside that directory.

PS: I'm using Jekyll 2.5.3.

**Comment by parkr** [comment]
Instead of site.source_dir(path), you can use Jekyll.sanitized_path(site.source, path). Pass :verbose => true to cp_r to get more info on that process!

**Comment by mine-cetinkaya-rundel** [comment]
@parkr it worked! thanks so much.

**Comment by garyrozanc** [comment]
@mine-cetinkaya-rundel could you post your working plugin? I need to do the same thing and I can't get the above solution to work.

**Comment by mine-cetinkaya-rundel** [comment]
@garyrozanc here it is:

- putr `ignore_rmd.rb` in the `_plugins` folder:

```ruby
# so that .rmd files are ignored in build and their yaml doesn't get stripped

class RmdCopyer < Jekyll::Generator
    RMD_FOLDER = 'post/rmd'
    RMD_OUTPUT_DIR = ''
    def generate(site)
        FileUtils.cp_r(Jekyll.sanitized_path(site.source, RMD_FOLDER), Jekyll.sanitized_path(site.dest, RMD_OUTPUT_DIR))
        site.keep_files << RMD_OUTPUT_DIR unless site.keep_files.include?(RMD_OUTPUT_DIR)
    end
end
```

- then put any `rmd` files that have yamls that you don't want stripped in a folder called `post/rmd`

**Comment by KobaKhit** [comment]
@mine-cetinkaya-rundel @garyrozanc  Since github pages does not allow user's plugins there is another very easy way to not let Jekyll render rmd files. Just add a newline before the Yaml matter in the Rmd file and jekyll wont render it, but the Rmd file will knit in Rstudio as expected. Example

```
\\ skipped line
---
title: "Impact of Weather Events on Population Health and Economy in the US"
author: "[Koba Khitalishvili](http://www.kobakhit.com/about)"
date: "May 17, 2015"
output:
  html_document:
    keep_md: TRUE
---
```

**Comment by equivalent** [comment]
for googling people, Jekyll has a `_config.yaml` option : `exclude: ['_posts/article/unpublished/']`
