### ISSUE TITLE
404 error on Cyrillic links

### ISSUE THREAD

**Issue by simptomy-i-lechenie** [jekyll/jekyll#7700]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |    WIN10 LTSB        |
| `jekyll`         | 3.8.5     |
| `github-pages`   | Latest     |
| `Ruby`   | 2.5.5-1-x64 with MSYS2     |

---

## Expected Behaviour

I expected Cyrillic links to work

## Current Behavior

I am faced with the problem of Cyrillic links on all types of pages.
**For example:**
when i run `jekyll server`, it creates tags in `_site` folder. (e.g http://localhost:4000/ **категория**) but http://localhost:4000/ **category** works.

[screenshot if Cyrillic url](https://imgur.com/5TAk8Kq)
[screenshot if Latin url](https://imgur.com/GJj255y)

The folders **категория** and **categories**  are created in the _site folder.
inside there is an index.html file

but http://localhost:4000/категория - 404 error
http://localhost:4000/categories - it's ok...

[screenshot _site folder](https://imgur.com/v7lYxlP)

## Plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

I do not see any errors and warnings at run `jekyll server`

I would really appreciate it if you'd help me :)

**Comment by ashmaroli** [comment]
@simptomy-i-lechenie This could be a `Ruby on Windows` bug. Not something Jekyll can fix, IMO..

**Comment by ashmaroli** [comment]
To confirm that it is a Ruby bug:
  1. Create a folder named `категория` in your *current directory*
  2. In your terminal move into that directory:
      ```sh
      # e.g. current directory is "C:\my_blog"
      # move into "категория" by using command `cd`:
      cd категория

      # Terminal should now show the new path:
      C:\my_blog\категория>
      ```
  3. Then fire up `irb` and test current directory as seen by Ruby by running `Dir.pwd`
      ```sh
      irb
      001> Dir.pwd
      ```

**Comment by simptomy-i-lechenie** [comment]
> To confirm that it is a Ruby bug:
> 
> 1. Create a folder named `категория` in your _current directory_
> 2. In your terminal move into that directory:
>    ```shell
>    # e.g. current directory is "C:\my_blog"
>    # move into "категория" by using command `cd`:
>    cd категория
>    
>    # Terminal should now show the new path:
>    C:\my_blog\категория>
>    ```
> 3. Then fire up `irb` and test current directory as seen by Ruby by running `Dir.pwd`
>    ```shell
>    irb
>    001> Dir.pwd
>    ```

I did everything you said. I am new to ruby and I don’t understand if it works as it should. I enclose a code listing.

>    ```shell
>    Microsoft Windows [Version 10.0.14393]
>    (c) Корпорация Майкрософт (Microsoft Corporation), 2016. Все права защищены.
>    C:\my_blog\категория>irb
>    irb(main):001:0> Dir.pwd
>    => "C:/my_blog/\xEA\xE0\xF2\xE5\xE3\xEE\xF0\xE8\xFF"
>    irb(main):002:0>
>    ```

[screenshot _cmd](https://imgur.com/h0u8U7H)

**Comment by ashmaroli** [comment]
@simptomy-i-lechenie  You did everything correctly..

**Comment by simptomy-i-lechenie** [comment]
> @simptomy-i-lechenie You did everything correctly..

so ruby working?

**Comment by simptomy-i-lechenie** [comment]
I just installed ruby, bundler and jekyll on a **clean** Windows system. 
### Step by step:
1. downloaded Ruby+Devkit 2.5.5-1 (x64) from rubyinstaller 
2. installed: 
[use utf8 as default externalencoding](https://imgur.com/djAuaC6)
[msys2 development toolchain](https://imgur.com/P9hK5Ss)
[run ridk install to install msys2](https://imgur.com/R6QYxB1)
[msys2 base installation](https://imgur.com/FQz9R0Z)
3. `gem install bundler`
4. `gem install jekyll`
5. `bundle update`
6. in the _posts folder, created the **test.md** and **тест.md** files
7. run` jekyll server`

if I open the **test.md** page, it will open
if I open the **тест.md** page, it will not open - 404 error

**Comment by ashmaroli** [comment]
@simptomy-i-lechenie This is not your fault or an error in your Ruby installation. **Its *probably* a bug in the Ruby language itself.** I'm sorry that you did a fresh Windows 10 install. That was unnecessary.

**Comment by ashmaroli** [comment]
@simptomy-i-lechenie The following Ruby script is a test.
1. Delete existing directory at path `C:\my_blog\категория`
2. Save the code below into a file at path `C:\my_blog\run.rb`.
    ```ruby
    require 'fileutils'

    # inspect current default encoding
    p Encoding.default_external
    puts

    # make a new directory
    FileUtils.mkdir_p("категория")

    # Get the directory's path in current encoding
    Dir.chdir("категория") do
      p Dir.pwd
    end

    puts

    # Force UTF-8 encoding
    Encoding.default_external = "utf-8"

    # Inspect current encoding
    p Encoding.default_external
    puts

    # Get the directory's path in current encoding
    Dir.chdir("категория") do
      p Dir.pwd
    end
    ```
3. In your terminal `cd` into `C:\my_blog` and run `ruby test.rb`

**Comment by simptomy-i-lechenie** [comment]
> @simptomy-i-lechenie The following Ruby script is a test.
> 
> 1. Delete existing directory at path `C:\my_blog\категория`
> 2. Save the code below into a file at path `C:\my_blog\run.rb`.
>    ```ruby
>    require 'fileutils'
>    
>    # inspect current default encoding
>    p Encoding.default_external
>    puts
>    
>    # make a new directory
>    FileUtils.mkdir_p("категория")
>    
>    # Get the directory's path in current encoding
>    Dir.chdir("категория") do
>      p Dir.pwd
>    end
>    
>    puts
>    
>    # Force UTF-8 encoding
>    Encoding.default_external = "utf-8"
>    
>    # Inspect current encoding
>    p Encoding.default_external
>    puts
>    
>    # Get the directory's path in current encoding
>    Dir.chdir("категория") do
>      p Dir.pwd
>    end
>    ```
> 3. In your terminal `cd` into `C:\my_blog` and run `ruby test.rb`

I deleted the "категория" folder, launched the script and it created an empty folder with the name "категория"

[run test.rb](https://imgur.com/kRbxr1g)

>    ```cmd
> C:\my_blog>ruby test.rb
> #<Encoding:IBM866>
> 
> "C:/my_blog/\xEA\xE0\xF2\xE5\xE3\xEE\xF0\xE8\xFF"
> 
> #<Encoding:UTF-8>
> 
> "C:/my_blog/\xEA\xE0\xF2\xE5\xE3\xEE\xF0\xE8\xFF"
> 
> C:\my_blog>
>    ```

**Comment by ashmaroli** [comment]
@simptomy-i-lechenie Thank you. You passed the test! :smiley: 
I get the same results at my end.

Notice how `Encoding.default_external` returned `Encoding:IBM866` even though use had set `UTF-8` at the time of installation. `Encoding:IBM866` comes from the filesystem.

In short, you won't be able to access the category page with cyrillic characters on Windows. But since most servers use Unix-based OS, your site's visitors shouldn't face an issue when they visit the page when deployed to a remote host.

Good luck and Happy Jekyllin!

**Comment by simptomy-i-lechenie** [comment]
> @simptomy-i-lechenie Thank you. You passed the test! 😃
> I get the same results at my end.
> 
> Notice how `Encoding.default_external` returned `Encoding:IBM866` even though use had set `UTF-8` at the time of installation. `Encoding:IBM866` comes from the filesystem.
> 
> In short, you won't be able to access the category page with cyrillic characters on Windows. But since most servers use Unix-based OS, your site's visitors shouldn't face an issue when they visit the page when deployed to a remote host.
> 
> Good luck and Happy Jekyllin!

Thanks for helping me figure it out. By the way Cyrillic links really work on github pages...someday I'll switch to Unix 😃
