### ISSUE TITLE
Dependabot Cannot Update Jekyll From v3.6.2 to Latest

### ISSUE THREAD

**Issue by Arszilla** [jekyll/jekyll#7703]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Windows 10  |
| `jekyll`         | 3.6.2 |
| `github-pages`   | Unknown |

## Expected Behaviour
Dependabot should be able to deploy a fix for the CVE/Update Jekyll to the latest version.

## Current Behavior
Dependabot cannot update Jekyll and displays this:

![firefox_VcTs96I6Fr](https://user-images.githubusercontent.com/22989170/59140461-4d8a5a80-89a6-11e9-95b7-80d9cff00686.png)

> Dependabot cannot create a pull request as one or more other dependencies require a version that is incompatible with this update.

## Code Sample
[My repo](https://github.com/arszilla/arszilla.github.io/)

## Notes
The template I am using is [Jekyll Uno](https://github.com/joshgerdes/jekyll-uno). I cloned the repo, edited `_config.yml`, wrote my post and pushed it to my repo as seen in my [commit history](https://github.com/Arszilla/arszilla.github.io/commits/master). Aside that I've ran `gem update` (Because `gem update jekyll` didn't update anything) in my local repo/folder. But Webstorm does not display any changes to the files.

**Comment by ashmaroli** [comment]
Based on your repo, the `Gemfile.lock` is outdated. Instead of running `gem update`, please run `bundle update` to update *all dependencies* in the `Gemfile.lock`.

**Comment by Arszilla** [comment]
Thanks. That did it.
