### ISSUE TITLE
Docs need update on code snippet highlighting

### ISSUE THREAD

**Issue by mariusa** [jekyll/jekyll#7713]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |       Fedora 30     |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

Docs do not say how to enable the stylesheet for Rouge:

https://jekyllrb.com/docs/liquid/tags/#code-snippet-highlighting
Quote:
In order for the highlighting to show up, you’ll need to include a highlighting stylesheet. For Pygments or Rouge you can use a stylesheet for Pygments, you can find an example gallery here.

**Comment by ashmaroli** [comment]
@mariusa Thank you for bringing this to our attention. Would you like to submit a pull request?
