### ISSUE TITLE
rbenv: jekyll: command not found  The `jekyll' command exists in these Ruby versions:   2.5.0

### ISSUE THREAD

**Issue by yifan97** [jekyll/jekyll#7717]
I followed the instruction and managed to create my first jekyll project/directory. 

However, when I want to create another one I had issue with jekyll new command. 

When I run jekyll new I got this:
```
rbenv: jekyll: command not found

The `jekyll' command exists in these Ruby versions:
  2.5.0
```

I installed ruby 2.6(the latest one)

**Comment by mattr-** [comment]
You'll need to run `gem install jekyll` under your ruby 2.6 install as well. `rbenv` is trying to be helpful by telling you that should either install the gem, or tell rbenv to use Ruby 2.5.0 for this project since jekyll is already installed.

**Comment by yifan97** [comment]
Hey Matt,

Thanks for your help. When I ran gem install jekyll I ran into another (permission) problem 

```
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/yifan/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/.rubocop.yml
```
Do you know how to fix it?

Thanks

**Comment by mattr-** [comment]
That would indicate there's a permissions problem in one of the directories. You'll want to check the permissions to make sure there's nothing wrong with them. All the files and directories should be owned by you. 

If you've used `sudo` in the past to install gems for this ruby, that will have an effect similar to this.

**Comment by yifan97** [comment]
I guess I did use ```sudo```  with these two commands
```
sudo gem install bundler
sudo gem install -n /usr/local/bin/ jekyll
```

Is there anyway to reverse this or modify anything so as to solve the permission issue?

Sorry I am new to ruby. Advanced thanks!
