### ISSUE TITLE
jekyll cannot generate ordered list?

### ISSUE THREAD

**Issue by lmy86263** [jekyll/jekyll#7731]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |    MacOS 10.12.6        |
| `jekyll`         | 3.8.5     |
| `github-pages`   | 198     |

---

## Expected Behaviour

I think it can generate ordered list like this:

1. Java
2. python

## Current Behavior

But it failed. it generate like this:
Java
python

without the ordered numbers.

**Comment by DirtyF** [comment]
Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage.
