### ISSUE TITLE
jekyll installation in windows 10.

### ISSUE THREAD

**Issue by arunkumarzz** [jekyll/jekyll#7733]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      Windows 10      |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour
Installing jekyll

gem install jekyll

## Current Behavior
 current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
C:/Ruby25-x64/bin/ruby.exe -r ./siteconf20190701-1608-1761wu.rb extconf.rb
creating Makefile

current directory: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

Why does jekyll use "make" in windows environment. I installed ruby devkit too so i am no sure if make is included in ruby dev kit.

**Comment by mattr-** [comment]
To answer the question

>Why does jekyll use "make" in windows environment. I installed ruby devkit too so i am no sure if make is included in ruby dev kit.

Probably because it's a gem with compiled dependencies.

However, please use the [Jekyll Talk forums](https://talk.jekyllrb.com/) and see if this question has already been answered there and a solution is available to help you out. Thanks!
