### ISSUE TITLE
jekyll 3.8.5 | Error:  can't modify frozen Array

### ISSUE THREAD

**Issue by rhildred** [jekyll/jekyll#7738]
I am trying to generate a site locally from a _config.yml produced by github pages. I want my README.md to be converted to .html and served as is done by github pages. 

This is my _config.yml

```
theme: jekyll-theme-tactile
```

This is my Gemfile

```
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

```

I am on Ubuntu 16.04.

This is my output:

```
ubuntu@rhlab:~/loginDemo$ jekyll serve --port 31638
Configuration file: /home/ubuntu/loginDemo/_config.yml
jekyll 3.8.5 | Error:  can't modify frozen Array
ubuntu@rhlab:~/loginDemo$

```

**Comment by DirtyF** [comment]
Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage.
and post `jekyll build --trace` result.
