### ISSUE TITLE
feat: Ignore post data

### ISSUE THREAD

**Issue by Lejo1** [jekyll/jekyll#7742]
## Summary

Jekyll doesn't allow post request as it's a static website generator.
It returns a 405 Not Allowed error when sending post data but why sending this why not just ignoring the post data?

## Motivation

It just blocks some possibilities especially if you can't change the things your clients send.

In my case I want to set up a media server which has a index file. This file can be dynamic or static. For the dynamic version there will be sent some post data. But if I now have a static one it doesn't works as the post data results in the 405 Error Code.

## Drawbacks

People could thing that they can handle the post data.

**Comment by ashmaroli** [comment]
@Lejo1 The only place a *server* comes in to play is when you run `jekyll serve`. That server is only for local development.
I don't see any scope for `POST` requests in a local development server nor a feature to ignore such requests.

:-1: from me

**Comment by DirtyF** [comment]
You can always bake you data from an API as _data files and build a static version.
Or request via JavaScript remote data on client side. See https://jamstack.org to understand how to interact with remote data.
