### ISSUE TITLE
feat:  add force html extension option in Jekyll serve command

### ISSUE THREAD

**Issue by travis1111** [jekyll/jekyll#7747]
## Summary

Add an option to jekyll serve command so that any urls hits the jekyll server (Webrick) will result a 404 if .html extension is missing.

## Motivation

The generated htmls all have `.html` extension.  During the development of the site, we use jekyll serve to check if the url is correct.  Jekyll server will handle urls correctly with or without html extension.  For example, a MD file has a permlink abc, after the build, abc.html is generated.  If we launch the page via jekyll's internal server, `localhost/abc` and `localhost/abc.html` both work.  But, if we move the site to our host, `localhost/abc` results 404.  We would like jekyll to have an option, so that localhost/abc will result a 404 error, thus when we reference this page `abc` in other docs we can see the error which will force us to use `abc.html`.

**Comment by DirtyF** [comment]
Can't you test your build with HTMLproofer?

**Comment by travis1111** [comment]
I tried, but I have baseurl, so it doesn't work :-(

**Comment by DirtyF** [comment]
You can output your build to a destination similar to your baesurl https://github.com/jekyll/jekyll/issues/4122#issuecomment-159439360

or the the `--url-swap` option of HTMLProofer
 https://github.com/gjtorikian/html-proofer#special-cases-for-the-command-line

Anyway this has nothing to do with Jekyll.

**Comment by travis1111** [comment]
Thanks will take a look.  Another option in my mind is, serve the html files from an apache server so that I can check the links in live env.
