### ISSUE TITLE
Can't install Jekyll (MacOS High Sierra)

### ISSUE THREAD

**Issue by MattNewtonian** [jekyll/jekyll#7759]
I have the latest version of gems and a ruby development environment installed.

`macs-MBP-2:~ mac$ gem install jekyll
Successfully installed jekyll-3.8.6
Parsing documentation for jekyll-3.8.6
Done installing documentation for jekyll after 1 seconds
1 gem installed
macs-MBP-2:~ mac$ jekyll new test
-bash: jekyll: command not found
macs-MBP-2:~ mac$ `

**Comment by MattNewtonian** [comment]
More info: https://stackoverflow.com/questions/57175665/still-cant-install-jekyll-for-some-reason-fixed-permissions

**Comment by DirtyF** [comment]
👉 https://talk.jekyllrb.com

If https://jekyllrb.com/docs/installation/macos/ is not complete, then please help us fix the docs.
