### ISSUE TITLE
feat: Need better build diagnostics

### ISSUE THREAD

**Issue by pcolmer** [jekyll/jekyll#7763]
## Summary

It would be really helpful if a command-line option could be added that would get Jekyll to produce some diagnostic output that shows the source file that results in the corresponding output file.

## Motivation

A contributor to an existing Jekyll site repo reported that the change they had submitted wasn't appearing on the built site. I could see that their change was in the repo but the output produced by Jekyll was from the old source material, despite clearing the built output directory and rebuilding.

In the end, I discovered that another contributor to the repo had added the affected page in two different places - under _pages and under a directory specifically for the page. It was the latter that the first contributor had changed but Jekyll was building from _pages instead.

I had tried using `--verbose` to troubleshoot this but the output from that doesn't provide any "path" information. In order words, if I had seen something like:

```
Building _pages/join/README.md
Output to /join/index.html
```

that would have saved me (and others) a lot of time because the simple act of building the site would have shown that the page under investigation was being built from a completely different source file than the one thought to be the true source.

## Drawbacks

I'm not sure I can think of a drawback. I think that diagnostic tools are always useful - I don't happen to find the output from `--verbose` particularly helpful in its current form. I don't think I've ever solved a problem with that output.

**Comment by ashmaroli** [comment]
@pcolmer When two different source files happen to have the same destination, there's always a chance that the written file has unexpected contents.

However, the `jekyll doctor` command already performs this analysis and reports the two file paths.

Do verify and get back.

**Comment by pcolmer** [comment]
@ashmaroli Thank you for telling me about `jekyll doctor`. I might use that as a precursor to the build step as a sanity check for these sorts of issues.

It would certainly have helped to solve this situation so I'm happy if you want to close this ... or I'm equally happy if you want to leave it open because it might still be useful information to have Jekyll produce?

**Comment by ashmaroli** [comment]
I'm closing this for now.
This will be reopened when you have newer ideas to improve the *build diagnostics*.
