### ISSUE TITLE
Collections doesn't work well locally.

### ISSUE THREAD

**Issue by 2403772980ygy** [jekyll/jekyll#7766]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     Windows 10       |
| `jekyll`         | Latest     |
| `local ruby enviroment`   | Latest     |

---

## Expected Behaviour

for example:

Mainfolder
....├ _config.yml
....└ FolderA
........├ _config.yml  //collections setting is here
........└ _FolderB
............└ 2019-8-2-test.md

so test.md should be found after posted

## Current Behavior

It doesn't produce test.md when I serve locally, but it seems to be fine on servers. Test on linux has not been done yet.

## Code Sample

repo: https://github.com/2403772980ygy/jekyll-bug-reproduction

note: I accidentally fine this by trying to build this: https://github.com/kitian616/jekyll-TeXt-theme, removing some lines in its exclude part of  _config.yml. And later I tried to simplify the issue.

**Comment by ashmaroli** [comment]
Why do you have two config files in different locations?
What is the exact command that you use to build the site locally..?

**Comment by 2403772980ygy** [comment]
Well I was trying to use https://github.com/kitian616/jekyll-TeXt-theme as a template and discovered the bug.

I use ` bundle exec jekyll serve ` to build it locally..
