### ISSUE TITLE
Jeykll install fails with bundler errors

### ISSUE THREAD

**Issue by mjgs** [jekyll/jekyll#7775]
I've installed ruby fresh with homebrew, then jekyll, but when I try to start jekyll on an existing project I get error messages to install bundler, but when I do that there are more error messages:

```
~ $ brew install ruby
Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version.

==> Downloading https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.xz
Already downloaded: /Users/marksmith/Library/Caches/Homebrew/downloads/560f28185f8505e1bfa48f762e0e421aadf30d2cce18858c97b9b1131e906f6a--ruby-2.6.3.tar.xz
==> ./configure --prefix=/usr/local/Cellar/ruby/2.6.3 --enable-shared --disable-silent-rules --
==> make
==> make install
==> Downloading https://rubygems.org/rubygems/rubygems-3.0.3.tgz
Already downloaded: /Users/marksmith/Library/Caches/Homebrew/downloads/590e1818e7eac6270fe33282ed860abd3a5eab0db9adf2097eac564ecb446b5a--rubygems-3.0.3.tgz
==> /usr/local/Cellar/ruby/2.6.3/bin/ruby setup.rb --prefix=/private/tmp/ruby-20190812-7577-11w
==> Caveats
…
==> Summary
🍺  /usr/local/Cellar/ruby/2.6.3: 19,374 files, 32.4MB, built in 3 minutes 19 seconds
~ $ which ruby
/usr/local/opt/ruby/bin/ruby
~ $ which bundler
/usr/local/opt/ruby/bin/bundler
~ $ gem install jekyll
Fetching jekyll-3.8.6.gem
Successfully installed jekyll-3.8.6
Parsing documentation for jekyll-3.8.6
Installing ri documentation for jekyll-3.8.6
Done installing documentation for jekyll after 1 seconds
~ $ cd [PROJECT DIR]
[PROJECT DIR] $ bundle exec jekyll serve -P 4000
Traceback (most recent call last):
	2: from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
	1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (1.16.2) required by your [PROJECT DIR]/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.2`
[PROJECT DIR] $ bundle update --bundler
Traceback (most recent call last):
	2: from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
	1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
[PROJECT DIR] $ gem install bundler:1.16.2
Fetching bundler-1.16.2.gem
bundler's executable "bundle" conflicts with /usr/local/lib/ruby/gems/2.6.0/bin/bundle
Overwrite the executable? [yN]
ERROR:  Error installing bundler:
	"bundle" from bundler conflicts with /usr/local/lib/ruby/gems/2.6.0/bin/bundle
```

I'm running OSX 10.11.6.

I don't want to install a ruby version manager just to run jekyll, I only want to use homebrew ruby so that I can delete it later (if necessary) and not affect the system ruby.

How do I get this jekyll install to be functional?

**Comment by DirtyF** [comment]
https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html

**Comment by DirtyF** [comment]
What if you install your gems in your home folder:

```
echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
```

Works the same for `.zshrc`.

**Comment by mjgs** [comment]
I can try this, and update my PATH as you describe, but how do actually install the gems into the home folder? (I'm not that knowledgeable about ruby dev environments)

**Comment by DirtyF** [comment]
Once the path is defined you should be good, check `gem env` .

You can also use ``--user-install` option:

`gem install --user-install bundler jekyll`

**Comment by mjgs** [comment]
> Once the path is defined you should be good, check gem env .
What should I look for in `gem env` output, there are a lot of paths in the output.

> You can also use --user-install option:
Does this install to $HOME/gems & $HOME/gems/bin?

**Comment by RAXNATION23** [comment]
> I've installed ruby fresh with homebrew, then jekyll, but when I try to start jekyll on an existing project I get error messages to install bundler, but when I do that there are more error messages:
> 
> ```
> ~ $ brew install ruby
> Warning: You are using macOS 10.11.
> We (and Apple) do not provide support for this old version.
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC. You are responsible for resolving any issues you
> experience, as you are running this old version.
> 
> ==> Downloading https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.xz
> Already downloaded: /Users/marksmith/Library/Caches/Homebrew/downloads/560f28185f8505e1bfa48f762e0e421aadf30d2cce18858c97b9b1131e906f6a--ruby-2.6.3.tar.xz
> ==> ./configure --prefix=/usr/local/Cellar/ruby/2.6.3 --enable-shared --disable-silent-rules --
> ==> make
> ==> make install
> ==> Downloading https://rubygems.org/rubygems/rubygems-3.0.3.tgz
> Already downloaded: /Users/marksmith/Library/Caches/Homebrew/downloads/590e1818e7eac6270fe33282ed860abd3a5eab0db9adf2097eac564ecb446b5a--rubygems-3.0.3.tgz
> ==> /usr/local/Cellar/ruby/2.6.3/bin/ruby setup.rb --prefix=/private/tmp/ruby-20190812-7577-11w
> ==> Caveats
> …
> ==> Summary
> 🍺  /usr/local/Cellar/ruby/2.6.3: 19,374 files, 32.4MB, built in 3 minutes 19 seconds
> ~ $ which ruby
> /usr/local/opt/ruby/bin/ruby
> ~ $ which bundler
> /usr/local/opt/ruby/bin/bundler
> ~ $ gem install jekyll
> Fetching jekyll-3.8.6.gem
> Successfully installed jekyll-3.8.6
> Parsing documentation for jekyll-3.8.6
> Installing ri documentation for jekyll-3.8.6
> Done installing documentation for jekyll after 1 seconds
> ~ $ cd [PROJECT DIR]
> [PROJECT DIR] $ bundle exec jekyll serve -P 4000
> Traceback (most recent call last):
> 	2: from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
> 	1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
> /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (1.16.2) required by your [PROJECT DIR]/Gemfile.lock. (Gem::GemNotFoundException)
> To update to the latest version installed on your system, run `bundle update --bundler`.
> To install the missing version, run `gem install bundler:1.16.2`
> [PROJECT DIR] $ bundle update --bundler
> Traceback (most recent call last):
> 	2: from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
> 	1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
> /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
> [PROJECT DIR] $ gem install bundler:1.16.2
> Fetching bundler-1.16.2.gem
> bundler's executable "bundle" conflicts with /usr/local/lib/ruby/gems/2.6.0/bin/bundle
> Overwrite the executable? [yN]
> ERROR:  Error installing bundler:
> 	"bundle" from bundler conflicts with /usr/local/lib/ruby/gems/2.6.0/bin/bundle
> ```
> 
> I'm running OSX 10.11.6.
> 
> I don't want to install a ruby version manager just to run jekyll, I only want to use homebrew ruby so that I can delete it later (if necessary) and not affect the system ruby.
> 
> How do I get this jekyll install to be functional?

Nothing wrong with what im seeing

**Comment by mjgs** [comment]
What are you seeing?

**Comment by mjgs** [comment]
I ended up downloading the ruby source and compiling, it was very straight forward (3 steps). Instructions at bottom of the [install page](https://www.ruby-lang.org/en/documentation/installation/).

The only extra thing I had to do was have openssl installed (it's not installed on osx, so install with homebrew), and set these env variables prior to compiling:

  export LDFLAGS=-L/usr/local/opt/openssl/lib
  export CPPFLAGS=-I/usr/local/opt/openssl/include
  export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
