### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by danielzph** [jekyll/jekyll#7776]
Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
  Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

**Comment by ashmaroli** [comment]
Please refrain from using this forum to ask for help regarding Jekyll's usage.
We have a dedicated platform for that: https://talk.jekyllrb.com

Regarding your query, adding `gem 'jekyll-paginate'` to your Gemfile and running
`bundle exec jekyll build` should help you proceed.
