### ISSUE TITLE
Test on Ruby 2.7 

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#7787]
Given I have Ruby 2.7preview1 installed on my machine
When I run jekyll build
Then the following message is displayed many times:

`/usr/local/lib/ruby/gems/2.7.0/gems/jekyll-4.0.0.pre.beta1/lib/jekyll/filters.rb:375: warning: deprecated Object#=~ is called on Time; it always returns nil`

source: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/filters.rb#L375

Error is not displayed if property is converted to a string:
`return property.to_f if property.to_s =~ number_like`

**Comment by ashmaroli** [comment]
That is a good suggestion @DirtyF. Apart from the possible increase in String allocation, `property.to_s` shouldn't cause issues.

Go ahead and open the PR..
