### ISSUE TITLE
Jekyll serve not working - rb_sysopen not existing

### ISSUE THREAD

**Issue by irenkaaa** [jekyll/jekyll#7800]
after typing "jekyll serve " or "bundle exec jekyll serve" , i am getting a error message that file/directory rb_sysopen is not existing

**Comment by ashmaroli** [comment]
You'll have to provide more context to receive help.
- What version of Jekyll are you using?
- What plugins are you using?
- What is the exact error message? Running `bundle exec jekyll serve --trace` will provide technical insight on the error.

**Comment by irenkaaa** [comment]
* jekyll version - 4.0.0
* I have no idea about the plugins. Although I managed to run/serve somehow on a different directory, but still, it is strange that I cannot run it everywhere.
* the exact message is: "C:/Ruby25..../jekyll/cache.rb:185: in ''initizliza" : No such file or directory @ rb_sysopen - {location of the folder where i am trying to serve} - Cache/b7/9606fb3afea5bd1609ed40b622142f1c98125abcfe89a76a661b0e8e343910

**Comment by ashmaroli** [comment]
Perhaps there was an interruption when the cache was created. The issue may resolve by itself if you delete the `.jekyll-cache` directory in the folder you're trying to build / serve

**Comment by irenkaaa** [comment]
Thank you ! :)
