### ISSUE TITLE
Jekyll-embedded text on GitHub pages scales incorrectly on mobile.

### ISSUE THREAD

**Issue by pedestriantactics** [jekyll/jekyll#7802]
My site uses the same type size for the main menu as the content. The content is embedded using Jekyll. When I load the page on my phone, the menu font size and content font size are the same, but if I turn my phone sideways, the content font scales up while the menu font stays consistent. Theoretically the content text shouldn't scale up at all. 

I noticed this when previewing my blog on my iPhone 7 Plus. I can't get it to reproduce in a browser-based mobile device sim.

<img width="879" alt="Screen Shot 2019-08-26 at 10 07 32 PM" src="https://user-images.githubusercontent.com/29744444/63742510-eb771e00-c84d-11e9-88f1-a699df8d1bba.png">

**Comment by ashmaroli** [comment]
@pedestriantactics This is not due to Jekyll but rather your CSS directives in the stylesheet(s).
Please seek support in our forum https://talk.jekyllrb.com
