### ISSUE TITLE
Date attribute changes for no reason

### ISSUE THREAD

**Issue by EdenKupe** [jekyll/jekyll#7803]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      OS Mojave      |
| `jekyll`         | Latest     |
| `github-pages`   | No     |

---

## Expected Behaviour

When iterating over a collection of posts and sorting them by date, items are sorted correctly by date (whether reversed or not).

The collection name is `release` and I'm using the following code to sort and display a list of all the pages included in it:

```
<ul>
    {% assign sorted = site.release | sort: 'date' %}
    {% for item in sorted reversed %}
    <li>{{ item.pagename }} - {{ item.date }}</li>
    {% endfor %}
</ul>
```

## Current Behavior

The result shows most files with the correct date they were created while some of the files (seemingly with no pattern) always show the current date as their creation date. That is, when I built it yesterday they all showed August 26th 2019 and when I build them today, it shows August 27th 2019. These files **were not** changed or created on August 27th but rather at varying points in the past. See screenshot below.

![Screen Shot 2019-08-27 at 12 09 42 PM](https://user-images.githubusercontent.com/27225905/63757920-970e8580-c8c3-11e9-829f-3866b962bd75.png)

FWIW, my final goal is to only retrieve the first item of this collection so I can link to it. But I can't do that if the collection is not being sorted correctly. I've currently created work around for this by manually adding a `latest` key to the latest file's header but this is obviously not ideal.

## Code Sample

The collection can be found [here](https://github.com/EdenKupe/knowledge-center/tree/master/_release). 

My config file is [here](https://github.com/EdenKupe/knowledge-center/blob/master/_config.yml).

Thanks!

**Comment by EdenKupe** [comment]
Not sure if it's related but if you look below the title of the page, I'm also using the last-modified-at plugin. This is also showing an erroneous date for **all** files on the site, always displayed the latest date.

**Comment by ashmaroli** [comment]
This is not a bug, actually. A *document*'s `date` attribute is either the date specified in its front matter or `site.time` (which is the system time (with conversions if `timezone` is configured in the config file) when the `site` is built).

For posts, a `date` is also generated via its filename but the time is always the system time as for other documents.

If you need *static dates (and time)* for your documents, then you have to specify the date in the front matter.

**Comment by EdenKupe** [comment]
That makes a lot of sense. I just assumed there was some magic going on in the background and there wasn't ;)

I'll close this issue and we'll work out a process for manually setting the date.

Thanks for the prompt reply!
