### ISSUE TITLE
Permalinks with accents give a 404 error

### ISSUE THREAD

**Issue by Skyost** [jekyll/jekyll#7808]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Windows 10 x64 |
| `jekyll`         | Latest available for `github-pages` |
| `github-pages`   | Latest |

## Expected Behaviour

I'm using a custom permalink for a page with accents. Something like :

```html
---
title: "À propos"
permalink: "/à-propos/"
---
<html>
<body>
<strong>Hello !</strong>
</body>
</html>
```

When I put a link to this page the jekyll server should show me **Hello !**.

## Current Behavior

As said, I put a link like this :

```html
<a href="/à-propos/">Link</a>
```

And I get a 404 error. Even when I'm escaping the accent with the `url_escape` tag.

**Comment by JordyValentine** [comment]
Hi @Skyost 
URL's don't support accented characters, only ASCII. You can however encode the accented letter to make it work.
Here's a good reference on how URL encoding works and what characters are accepted
[https://www.w3schools.com/tags/ref_urlencode.asp](https://www.w3schools.com/tags/ref_urlencode.asp)

**Comment by DirtyF** [comment]
> Scheme names consist of a sequence of characters. The lower case letters "a"--"z", digits, and the characters plus ("+"), period  ("."), and hyphen ("-") are allowed. — [RFC 1738 URL](https://www.ietf.org/rfc/rfc1738.txt)

**Comment by DirtyF** [comment]
@Skyost FYI I have no problem displaying accents in Firefox/macOS.

![image](https://user-images.githubusercontent.com/103008/64908689-c7e41c80-d703-11e9-8a71-8c79821a6f6f.png)

**Comment by Skyost** [comment]
@DirtyF Don't know what's happening on my computer then. I'm on Windows 10 using Chrome tho.
