### ISSUE TITLE
permalink generation removing special characters and spaces

### ISSUE THREAD

**Issue by nalmeida** [jekyll/jekyll#782]
I am using the following configuration:
`permalink: /:categories/:title`
to generate my posts folder structure but I would like to remove every special characters and also replace all the spaces for "`-`"

My category name is: "Acentuação"

Now: 
`http://localhost:4000/Acentua%C3%A7%C3%A3o/testando-acentuacao/`

Preferred:
`http://localhost:4000/acentuacao/testando-acentuacao/` 

Is there any way to do it without changing the Jekyll core?
Any plug-in?

Regards
Nicholas

**Comment by eamaral92** [comment]
I try to add this Lib(https://github.com/wagnerandrade/wind/blob/master/lib/extend_string.rb) to my project but i'ts not working...
Can someone give me some reference to use?
