### ISSUE TITLE
"where" filter doesn't appear to accept integer values in 4.0

### ISSUE THREAD

**Issue by whicks1** [jekyll/jekyll#7820]
- I updated to the latest Jekyll
  - I ran `jekyll doctor` to check my configuration
  - I read the contributing document at https://jekyllrb.com/docs/contributing/

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |    MacOS 10.14.5        |
| `jekyll`         | Latest  (4.0)   |
| `github-pages`   | No     |

---

## Expected Behaviour

- when making a template assignment
- and using a where filter,
- and value is an integer,

we should return the corresponding assigned object

## Current Behavior

Since upgrade from 3.x to 4.0, I no longer return an object if the value is a number. ("where_exp" does work, so does a "where" filter with a string value).

## Code Sample

Assume an "orgs" collection, containing hr.md with `deptid: 2765` and in some site template I only want to pull data about the HR department:
`
{%- assign dept = site.orgs | where: "deptid", 2765 | first -%}
`

`{{ dept.other_metadata }}` returns relevant data in 3.x, nothing in 4.0.

these would work however:

`
{%- assign dept = site.orgs | where: "deptid", "hr" | first -%}
`
if hr.md's id == "hr" instead; success.

`
{%- assign dept = site.orgs | where_exp: "dept", "dept.deptid == 2765" | first -%}
`
where_exp with INT; also success.

Maybe this is just a change in the latest liquid, either way might be worth documentation for migrations.

**Comment by jaredcwhite** [comment]
@whicks1 Thanks for reporting this! I ran into the same issue but hadn't gotten a chance to write up what was going on. (And I ended up switching to using where_exp as a workaround…)

**Comment by ashmaroli** [comment]
Sorry for the inconvenience, guys. In case you want to continue using the where filter, you may point your Gemfile to the PR linked above:
```ruby
gem "jekyll". github: "jekyll/jekyll", ref: "refs/pull/7821/head"
```

**Comment by ashmaroli** [comment]
Hello everyone!
Can someone report back if the current `master` resolves this issue..?
You can edit your Gemfile to following to test:
```ruby
gem "jekyll", github: "jekyll/jekyll"
```
Thanks.

**Comment by whicks1** [comment]
> ```ruby
> gem "jekyll", github: "jekyll/jekyll"
> ```

worksforme
