### ISSUE TITLE
Includes with variables no longer working

### ISSUE THREAD

**Issue by mgerzabek** [jekyll/jekyll#7824]
The [docs](https://jekyllrb.com/docs/includes/) state that one could include templates referenced by variable `{% include {{ page.my_variable }} %}`. This seems no longer valid with 4.0.0.

If I do include templates via the variable syntax I get `Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: Valid syntax: {% include file.ext param='value' param2='value' %} in /_layouts/saleselements.html`

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |   macOS Mojave 10.14.5         |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |
---

**Comment by ashmaroli** [comment]
@mgerzabek What version of Jekyll did this *includes with variable* feature last work..?

**Comment by mgerzabek** [comment]
I'm not quite sure, as I do updates occasionally… but when I switch back to 3.8.3 it works.

**Comment by ashmaroli** [comment]
@mgerzabek Do you have the source code on GitHub or similar? I was not able to reproduce this issue with v4.0 and a boilerplate site generated via running `jekyll new` and would therefore like to use your source-code for testing.

**Comment by mgerzabek** [comment]
@ashmaroli I finally double-checked it and have to admit, it's my fault. So sorry for the noise. Everything works as stated. Sorry again!

**Comment by ashmaroli** [comment]
No problem @mgerzabek. Glad that you got everything sorted out successfully.
Happy Jekyllin'! :smiley:
