### ISSUE TITLE
Number-like strings are converted to floats by certain Jekyll Filters

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#7827]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      All Platforms      |
| `jekyll`         |  **`master`** and `v4.0.0`    |

---

## Expected Behaviour

Expected whole number strings to be rendered verbatim.

## Current Behavior

![filter-bug](https://user-images.githubusercontent.com/12479464/65574703-c3352900-df8b-11e9-8052-972792b9ec25.png)

**Comment by zachwright** [comment]
Taking a crack at this one. Is this the Date filter in this example?

**Comment by ashmaroli** [comment]
@zachwright No, it is not the `date` filter but the result of using the `group_by` filter.
The source code for the above screenshot is located at path `docs/pages/jekyllconf.md`

**Comment by summerisgone** [comment]
Looks like it's a feature now: https://github.com/jekyll/jekyll/pull/6608/files#diff-88ebc99d4a7c9f72a3e30a91bebf8ea8R329-R335
