### ISSUE TITLE
Using Liquid Filters in _layout Pages throws Parsing Error 

### ISSUE THREAD

**Issue by fer-rum** [jekyll/jekyll#7828]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |       Linux 5.0.0-29-generic GNU/Linux     |
| `jekyll`         | 4.0.0     |
| `github-pages`   | n/a     |

---

## Expected Behaviour

Embedding the following liquid code into *_layouts/my_own_layout.html* should evaluate without issue.
```
{{ some text | replace " ", "&thinsp;" }}
```

## Current Behavior
The following warning gets printed on the console:
```
Liquid Warning: Liquid syntax error (line 5): Expected end_of_string but found id in "{{ some text | replace " ", "&thinsp;" }}" in /_layouts/my-own-layout.html
```

## Additional Observation
* The issue also triggers with other filters like `reverse`
* The issue **does** triggers for _layouts_
* The issue **does not** trigger for includes

## Code Sample
/_layouts/my-own-layout.html
``` html
<html>
    <body>
        {{ some text | replace " ", "&thinsp;" }}
    </body>
</html>
```

/liquid_bug.md
``` markdown
---
layout: my-own-layout
---
```

**Comment by ashmaroli** [comment]
Use a colon `:` to delineate filter parameters from filter name:
```diff
- {{ some text | replace " ", "&thinsp;" }}
+ {{ some text | replace: " ", "&thinsp;" }}
```
Please reply if the correction above resolves this issue.

**Comment by fer-rum** [comment]
That fixes the _replace_ use case (although I wonder why the liquid parser did not complain when I left them out in the `_include/ … .html` and still rendered the correct result.)

I tried `{{ some text | reverse }}` as well: With colons or without, I get the same parsing errors in both cases.

**Comment by ashmaroli** [comment]
Okay, Investigating this will need a peek at your site's source code.
Have you tried to reproduce this issue with a new boilerplate site generated by `jekyll new`.. or with a bare-bones site via `jekyll new --blank`?

**Comment by ashmaroli** [comment]
Since even `reverse` filter throws this error, the issue is most likely with the actual string value of the `some text` in your examples above. Perhaps the text is some non-UTF8 encoded string that is confusing the parser..?

**Comment by fer-rum** [comment]
Thanks, it was indeed the case that my brain was broken. :man_facepalming:  
Jekyll is fine, keep up the good work.
