### ISSUE TITLE
Two nested for-loops produce double output

### ISSUE THREAD

**Issue by mosesontheweb** [jekyll/jekyll#7837]
Hi,

I already raised an issue at Shopify: https://github.com/Shopify/liquid/issues/1179

I encountered the problem, that when I provide a JSON data file for, lets say, the menu, I always get two items, when using two for-loops.

The code used:
JSON
```json
{
    "home": {
        "name": "Home",
        "path": "/",
        "icon": "fas fa-home"
    },
    "faq": {
        "name": "FAQ",
        "path": "/faq",
        "icon": "fas fa-question"
    },
    "manuals": {
        "name": "Anleitungen",
        "path": "/manuals",
        "icon": "fas fa-book-open"
    }
}
```
Template
```html
        <div class="navbar-menu">
            <div class="navbar-start">
                {% for rubrik in site.data.navigation %}
                {% for part in rubrik %}
                <a class="navbar-item{% if page.url == part.path %} is-active{% endif %}" href="{{ part.path }}">
                    <span class="icon"><i class="{{ part.icon }}"></i></span><span>{{ part.name }}</span>
                </a>
                {% endfor %}
                {% endfor %}
            </div>
        </div>
```
Output
```html
       <div class="navbar-menu">
            <div class="navbar-start">


                <a class="navbar-item" href="">
                    <span class="icon"><i class=""></i></span><span></span>
                </a>

                <a class="navbar-item is-active" href="/">
                    <span class="icon"><i class="fas fa-home"></i></span><span>Home</span>
                </a>



                <a class="navbar-item" href="">
                    <span class="icon"><i class=""></i></span><span></span>
                </a>

                <a class="navbar-item" href="/faq">
                    <span class="icon"><i class="fas fa-question"></i></span><span>FAQ</span>
                </a>



                <a class="navbar-item" href="">
                    <span class="icon"><i class=""></i></span><span></span>
                </a>

                <a class="navbar-item" href="/manuals">
                    <span class="icon"><i class="fas fa-book-open"></i></span><span>Anleitungen</span>
                </a>


            </div>
        </div>
```
For each element parsed from the JSON data file the part of template is parsed two times, first without any value, secondly as expected with the correct values.

The guys from Shopify suspect rather an implementation error (see link to issue at shopify/liquid).

The version used for this is Jekyll v4.0.0 (fresh install, without any updates to components).

Regards, Thomas

**Comment by ashmaroli** [comment]
@mosesontheweb If its not too much trouble, can you check if this issue resolves with downgrading to Jekyll 3.8? To do so, simply edit your Gemfile as follows and run `bundle install` to install:
```diff
- gem "jekyll", "4.0.0"
+ gem "jekyll", "~> 3.8"
```

**Comment by mosesontheweb** [comment]
Hi,

no worries, that's easy to do (btw. it's `bundle update` to perform the downgrade ;) ).

Anyway, the result remains the same:
```html
<body>
        <p><a href=""></a></p>
        <p><a href="/home">Home</a></p>
        
        <p><a href=""></a></p>
        <p><a href="/faq">FAQ</a></p>
</body>
```
Btw. this are the gems installed at the moment:
Gems included by the bundle:
  * addressable (2.7.0)
  * bundler (2.0.2)
  * colorator (1.1.0)
  * concurrent-ruby (1.1.5)
  * em-websocket (0.5.1)
  * eventmachine (1.2.7)
  * ffi (1.11.1)
  * forwardable-extended (2.6.0)
  * http_parser.rb (0.6.0)
  * i18n (0.9.5)
  * jekyll (3.8.6)
  * jekyll-feed (0.12.1)
  * jekyll-sass-converter (1.5.2)
  * jekyll-seo-tag (2.6.1)
  * jekyll-watch (2.2.1)
  * kramdown (1.17.0)
  * liquid (4.0.3)
  * listen (3.1.5)
  * mercenary (0.3.6)
  * minima (2.5.1)
  * pathutil (0.16.2)
  * public_suffix (4.0.1)
  * rb-fsevent (0.10.3)
  * rb-inotify (0.10.0)
  * rouge (3.11.0)
  * ruby_dep (1.5.0)
  * safe_yaml (1.0.5)
  * sass (3.7.4)
  * sass-listen (4.0.0)

Regards, Thomas

**Comment by ashmaroli** [comment]
> it's `bundle update` to perform the downgrade

Ah yes. That's correct. Thank you for correcting me.

Regarding the issue at hand, since this is reproducible with Jekyll 3.8 as well, then you'll have to resort to a workaround:

*Simply enclose the markup in a Liquid `if` block*
```html
<div class="navbar-menu">
  <div class="navbar-start">
    {% for rubrik in site.data.navigation %}
      {% for part in rubrik %}

        {% if part.name %}
          <a class="navbar-item{% if page.url == part.path %} is-active{% endif %}" href="{{ part.path }}">
              <span class="icon"><i class="{{ part.icon }}"></i></span><span>{{ part.name }}</span>
          </a>
        {% endif %}

      {% endfor %}
    {% endfor %}
  </div>
</div>
```

**Comment by mosesontheweb** [comment]
Ah, yes, I see. Well, that's somehow weird, but it works.

Thanks!

**Comment by ashmaroli** [comment]
> Well, that's somehow weird, but it works.

Technically, its not weird. Its the expected result even in Ruby. For example, the following translation..
```ruby
site.data["navigation"].each do |rubrik|
  rubrik.each do |part|
    puts part["name"].inspect
  end
end
```
..will output:
```
nil
"Home"
nil
"FAQ"
nil
"Anleitungen"
```
If you don't want the additional `if` check, you may want to use the `where` or `where_exp` filter to get a populated array before-hand:
```
{% assign parts = site.data.navigation | where: ... %}
{% for part in parts %}
  ...
{% endfor %}
```
