### ISSUE TITLE
format disordered after Regenerating

### ISSUE THREAD

**Issue by memorate** [jekyll/jekyll#7854]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      win10      |
| `jekyll`         |    3.8.5     |
| `github-pages`   |  196  |

---

## Expected Behaviour
my normal site like this:

![image](https://user-images.githubusercontent.com/45744410/66622325-c67e1500-ec19-11e9-95a3-d70680443ef7.png)

## Current Behavior
when i modify my posts, and jekyll will regenerate the site.

But after regenerating site, my site's format is disordered when i browse my http://localhost:4000.

Like below picture:
![image](https://user-images.githubusercontent.com/45744410/66622172-60918d80-ec19-11e9-8cdc-dc7153c2b7ae.png)

**Comment by ashmaroli** [comment]
This is a CSS issue. Prior to regenerating, you probably edited your Sass files which introduced a subtle error. Correcting that will resolve this.

**Comment by memorate** [comment]
> This is a CSS issue. Prior to regenerating, you probably edited your Sass files which introduced a subtle error. Correcting that will resolve this.

My Sass files？I just only edited my "_post" 's markdown paper.

**Comment by crispgm** [comment]
@mechanomi if you use a theme, it might be theme's issue. otherwise, it's a CSS issue of yourself.

**Comment by ashmaroli** [comment]
@memorate This looks like a bug with the `github-pages` gem.
Edit your Gemfile to remove it from the `:jekyll_plugins` group.
```diff
# Gemfile

- gem 'github-pages', group: :jekyll_plugins
+ gem 'github-pages'
```
However, now you should manually enable the plugins you wish to use. In your config file, edit the `gems` key at the end:
```diff
gems:
  - jemoji
+ - jekyll-paginate
```
*I would additionally recommend renaming gems` in the config file to `plugins` since using `gems` is now outdated.*

**Comment by memorate** [comment]
> ```diff
> - jekyll-paginate
> ```
@ashmaroli  TTTTTThanks, it worked!!!

**Comment by memorate** [comment]
> @mechanomi if you use a theme, it might be theme's issue. otherwise, it's a CSS issue of yourself.

@crispgm ashmaroli's way can fix that!
