### ISSUE TITLE
Unable to render inner folder content on Github pages

### ISSUE THREAD

**Issue by xameeramir** [jekyll/jekyll#7889]
We have a GitHub pages repository https://github.com/ansaar-in/.well-known

The top-level files are getting rendered:

- http://api.ansaar.in/.well-known/
- http://api.ansaar.in/.well-known/a.html
- http://api.ansaar.in/.well-known/README.md
- http://api.ansaar.in/.well-known/LP_VnQ5AT36IcFhWCJ-gf6QGYHTYZ-EtwBa7TMqYS6c

There are files inside folder `a`:

- https://github.com/ansaar-in/.well-known/blob/gh-pages/a/b.html

These files are getting rendered:

- http://api.ansaar.in/.well-known/a/b.html

However, the following files are not getting rendered:

- https://github.com/ansaar-in/.well-known/blob/gh-pages/acme-challenge/LP_VnQ5AT36IcFhWCJ-gf6QGYHTYZ-EtwBa7TMqYS6c
- https://github.com/ansaar-in/.well-known/blob/gh-pages/acme-challenge/a.html

From any of these links:

- http://api.ansaar.in/.well-known/acme-challenge/LP_VnQ5AT36IcFhWCJ-gf6QGYHTYZ-EtwBa7TMqYS6c
- http://api.ansaar.in/.well-known/acme-challenge/a.html

How can I access the inner level files which are hosted on a GitHub pages repository?

What is the missing point here?

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |            |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

The links should be rendered like other links.

## Current Behavior
As described above.

## Code Sample
https://github.com/ansaar-in/.well-known

**Comment by zdroid** [comment]
I tried to replicate your issue, but there are 2 problems:
1) your website is down
2) it is unclear whether your GitHub pages are turned on in GitHub services

The visible difference between the files you described is `LP_VnQ5AT36IcFhWCJ-gf6QGYHTYZ-EtwBa7TMqYS6c` being present in the subdirectory `a/`. It seems to be making the difference in visibility. I however have no clue what is the use of that file on your website, and it seems quite site-specific.

The only additional file you should have is `CNAME`, which redirects users from `<name>.github.com` to your custom website URL.

**Comment by DirtyF** [comment]
Hi, we don't provide support for GitHub Pages,  please contact GitHub Support.
