### ISSUE TITLE
Node Package with updated version of Jekyll

### ISSUE THREAD

**Issue by javag97** [jekyll/jekyll#7890]
I am trying to install Jekyll using npm as I am trying to move away from using ruby gems and bower for dependencies and using exclusively npm. However, the Jekyll project on npm is currently on 3.0 and has only been pushed once 5 years ago. Is there a reason for this? I have tried to look for any reference to this elsewhere on the internet but could not find any.

**Comment by ashmaroli** [comment]
**There is no official Node port of Jekyll.**
The package you're referring to is not owned by the Jekyll team.

If you wish to move away from using Ruby and Ruby gems, please consider switching to a static site generator written in a different language.
