### ISSUE TITLE
The Filter `truncatewords()` Truncate in the Middle of HTML Tag

### ISSUE THREAD

**Issue by RoyiAvital** [jekyll/jekyll#7892]
I have simple paginate case:

```
<article class="row news-article">
	<h3 class="news-title"><a href="{{ post.url | prepend: site.baseurl | replace: '//', '/'  }}">{{ post.title }}</a> <span class="news-date">{{ post.date | date_to_long_string}}</span></h3>
	{{ post.content | truncatewords: 50 }}
</article>
```

Liquido indeed truncate 50 words.
The problem is it seems to truncate from the RAW HTML or something as it truncate in the middle of an HTML tag.

Could it be fixed that truncation will happen in the Markdown representation of the post?  
I know the function `truncatewords()` belongs to Liquido, yet it does as it is intended given input string. I just wonder if Jekyll can do something smart to make it count words which are not part of HTML tag.

It happens on the current GitHub Pages service.

**Comment by ashmaroli** [comment]
Hello @RoyiAvital, unfortunately Liquid doesn't differentiate between Markdown and HTML. It just sees a string of characters.

Closing as this isn't readily actionable.
