### ISSUE TITLE
docs: missing information on plugin development

### ISSUE THREAD

**Issue by dtenenba** [jekyll/jekyll#7897]
## Motivation

I'm looking to develop a Jekyll plugin (or generator). The page `/docs/plugins/generators/` gives me some code samples but does not tell me what directory to put them in or what to name the files, nor whether I need to do anything else (add a line to _config.yml?) to let Jekyll know about my plugin. 

## Suggestion

Please include every bit of information needed in order to write a generator.

**Comment by ashmaroli** [comment]
@dtenenba The following are answers to your questions.
Will you be able to submit a pull request to improve our documentation?

------

> What do I name my plugin files?

If your plugin is contained within a single file, it can be named whatever you want. But it should've a `.rb` extension. If your plugin is split across multiple files, the plugin needs to be packaged as a Rubygem to be published at https://rubygems.org/, naming a gem then depends on its availability at that site. No two gems can have the same name.

------

> What directory do I put plugins in so that Jekyll loads them as expected?

The default directory is **`_plugins`**. However, Jekyll allows you to configure that by assigning the desired name to the key **`plugins_dir`** in the config file.

**Comment by dtenenba** [comment]
The reason I filed this issue is that this critical information is missing in the docs. (Thanks for the answers though). Also, the `_plugins` directory is missing from the Directory Structure page (`/docs/structure/`).
