### ISSUE TITLE
Mangling of HTML tags inside a <table><code> block

### ISSUE THREAD

**Issue by jlsucar** [jekyll/jekyll#7898]
The following Markdown is being rendered incorrectly by Jekyll version 3.8.6:

```
---
title: Test
---

<table>
<tr>
<td>
<code>
    Input name of true model trajectory file;
    <cr> for perfect_output.nc
</code>
</td>
</tr>
</table>

This is additional text. *Some markdown stuff*.
```

Note that <cr> is NOT meant to be an HTML tag but is meant to be escaped code (in this case, for a carriage return).

Jekyll renders the table portion of this Markdown to HTML as:

```
<tr>
<td>
<code>
    Input name of true model trajectory file;
    <cr> for perfect_output.nc
&lt;/code&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/table&gt;

This is additional text. *Some markdown stuff*.
</cr></code></td></tr></table>
```

There are two reasonable things to do:

1) Escape the <> characters. Github generates the following HTML, which is desired: 

```
<table>
<tr>
<td>
<pre><code>
Input name of true model trajectory file;
&lt;cr&gt; for perfect_output.nc
</code>
</pre>
</td>
</tr>
</table>

This is additional text. *Some markdown stuff*.
```

2) Don't escape the <cr> which is what raw HTML does. In this case, <cr> would simply not show up as it is an invalid HTML tag. This would be acceptable.

```
<table>
<tr>
<td>
<pre><code>
    Input name of true model trajectory file;
    <cr> for perfect_output.nc
</code>
</pre>
</td>
</tr>
</table>

This is additional text. *Some markdown stuff*.
```

But what Jekyll is doing is certainly a bug that causes the rest of the page to be escaped as code within the table.

**Comment by ashmaroli** [comment]
@jlsucar Jekyll doesn't directly convert Markdown to HTML. It delegates that job to a program called [`kramdown`](https://github.com/gettalong/kramdown). I would suggest filing a ticket there.

Meanwhile, is there an HTML entity alternative that you could swap `<cr>` with?

**Comment by jlsucar** [comment]
Thanks @ashmaroli. I will file this with kramdown.
