### ISSUE TITLE
Static file in collection (with permalink set) causes build to fail

### ISSUE THREAD

**Issue by joeshannon** [jekyll/jekyll#7904]
With the latest Jekyll version (4) a collection containing a static file causes the build to break when a permalink is set on the collection.

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Linux  |
| `jekyll`         | Latest     |
| `github-pages`   | No|

---

## Expected Behaviour

The static file should be copied into _site and build should succeed.

(Alternatively if there really is a problem a meaningful error message should be given.)

## Current Behavior

Jekyll build fails with stack trace. Example repository here:
https://github.com/joeshannon/jekyll-collection-static-issue

* Errors can be found on the travis builds (i.e. https://travis-ci.org/joeshannon/jekyll-collection-static-issue)
* A Jekyll V3.x branch is provided where there is no issue

## Code Sample

https://github.com/joeshannon/jekyll-collection-static-issue

**Comment by ashmaroli** [comment]
Thank you for reporting this bug. Though this issue only occurs if the static file **doesn't have** an extension.

**Comment by ashmaroli** [comment]
## Workaround
Until a proper patch is shipped, you may use the following workaround by pasting the code in a file at the path `<source_dir>/_plugins/monkey_patch.rb`
```ruby
# frozen_string_literal: true

module Jekyll
  class StaticFile
    def placeholders
      {
        :collection => @collection.label,
        :path       => cleaned_relative_path,
        :output_ext => "",
        :name       => basename,
        :title      => "",
      }
    end
  end
end
```

**Comment by joeshannon** [comment]
No problem, thanks for providing a workaround.
