### ISSUE TITLE
docs: Remove Site from Wiki

### ISSUE THREAD

**Issue by Doppp** [jekyll/jekyll#7907]
## Motivation

Hi, I would like to remove my site from the [wiki](https://github.com/jekyll/jekyll/wiki/sites) as I am no longer using Jekyll. However, since we are no longer able to edit the wiki anymore, I cannot do so.

## Suggestion

Delete `Blind Alley Graffiti (source) – Daryl Yeo’s personal blog` from the [wiki](https://github.com/jekyll/jekyll/wiki/sites). Thanks!

**Comment by DirtyF** [comment]
Done.
