### ISSUE TITLE
Publishing "dot" folders

### ISSUE THREAD

**Issue by KevinColemanInc** [jekyll/jekyll#7917]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     OSX       |
| `jekyll`         | 4.0.0     |
| `github-pages`   | No     |

---

## Expected Behavior

The documentation says:

https://jekyllrb.com/docs/structure/
> Every other directory and file **except for those listed above—such as css and images folders, favicon.ico files, and so forth—will be copied verbatim to the generated site**. There are plenty of sites already using Jekyll if you’re curious to see how they’re laid out. 

Specifically for my Apple requires you to host a verification file at the path `/.well-known/apple-developer-domain-association.txt` to verify your domain with "Login with Apple"

If I create a directory to that path with the file, `jekyll serve` does not host the file at the same path.

I see the folder and contents being copied to the `_site` directory. So maybe the problem is with `jekyll serve`?

## Code Sample

To reproduce:

1. Create a new Jekyll project
2. Create a file at path `/.well-known/apple-developer-domain-association.txt`
3. Run `jekyll serve`
4. Visit http://127.0.0.1:4000/.well-known/apple-developer-domain-association.txt and get a 404

**Comment by DirtyF** [comment]
@KevinColemanInc default port is 4000, so you should visit `http://127.0.0.1:4000/.well-known/apple-developer-domain-association.txt`

**Comment by KevinColemanInc** [comment]
@DirtyF You can use whatever port you want to use, but you're still not going to retrieve that file if the folder is prefixed with a "dot".

**Comment by DirtyF** [comment]
@KevinColemanInc try adding `.well-know` to `include` in `_config.yml`: 

```
include:
 - .well-known
```

**Comment by KevinColemanInc** [comment]
Awesome Thanks!
