### ISSUE TITLE
Jekyll does'nt work due to a TypeError

### ISSUE THREAD

**Issue by algunacosa** [jekyll/jekyll#7930]
When I try to do something with Jekyll, it prints some lines like this:

`from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'`

They are exactly 12, and next prints this error:

`/home/yo/.gem/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/drops/document_drop.rb:17:in 'private': nil is not a symbol nor a string (TypeError) `

There is my enviroment

| Software | Name | Version |
| ------ | ------- | ---- |
| System | Manjaro | 18.3 |
| Ruby | Ruby |  2.6.0 |
| Jekyll | Jekyll | 4.0.0 |
| Shell | Zsh | 5.7.1 |

**Comment by ashmaroli** [comment]
@algunacosa This is a known issue with `forwardable-1.3.0`.
Please downgrade that gem by running the following:
```
gem uninstall forwardable --version 1.3.0
gem install forwardable --version 1.2.0
```

**Comment by algunacosa** [comment]
Ok, there's another error.

When executing the first command, I got this error:

```
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::RDoc

```

**Comment by ashmaroli** [comment]
You need not be inside the source directory.
Try moving to elsewhere..
```
cd /home/

gem uninstall forwardable --version 1.3.0
gem install forwardable --version 1.2.0
```

**Comment by algunacosa** [comment]
Ok, I solved it. 

Due to some reason, my ruby installation came without rdoc gem.

I installed it, downgrade and it works.

Thanks.
