### ISSUE TITLE
feat: replace usage of Utils.has_yaml_header? with Utils.is_static_file?

### ISSUE THREAD

**Issue by MoHKale** [jekyll/jekyll#7932]
## Summary
I feel that `Utils.has_yaml_header?` is being used throughout the jekyll code base to identify whether src files that jekyll encounters are static files or not. This makes it hard for third party plugins to create Converters for files that don't have or want YAML headers.

## Motivation

For example, I'm currently working on the [jekyll-org](https://github.com/eggcaker/jekyll-org) gem. The way it's currently implemented is to prepend a mixin to the Document class which converts the org file to a HTML file when their extensions match. However, a Document instance is only instantiated for org files that have a YAML header or org files in the Posts collection (because of special behaviour therein). To add support for conversion in other collections I need to modify the [read](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/collection.rb#L57) method of the Collection class (by which I mean redefine it altogether in my plugin) such that it also considers files ending in `.org` to be Documents (& not static files). Then I need to find wherever regular files are assessed to be static or document files and do the same there.

## Guide-level explanation

This is an error prone and taxing approach to customise behaviour across the entire code base. It'd be much simpler if there was one method `Utils.is_static_file?` to check whether a file should be made into a document or not. That way I could just override it to add support for org Documents and know that anywhere a file is judged to be static or a document, the files my plugin is designed to convert will be converted, regardless of if they're in a collection or some other construct.

## Reference-level explanation

so I think a reasonable approach would be:
* create the `Utils.is_static_file?`
* have it call `Utils.has_yaml_header?` as its body by default.
* rename all uses of `Utils.has_yaml_header?` with `Utils.is_static_file?`.
* done.

## Drawbacks

Can't really think of a reason not to. I mean for one the name of `Utils.has_yaml_header?` doesn't adequately reflect it's usage.

**Comment by ashmaroli** [comment]
From what I understand about your plugin (from the post above and from the plugin's README) is that it aims to convert `./**/*.org` files into html files irrespective whether those files are inside a collection directory or a standalone page..
But then, it's not a matter of just reading files with `.org` extension. It is also about parsing front matter with an entirely different structure and emit all resulting objects as `Jekyll::Document` objects..

IMO, the better route for your plugin would be to have a dedicated datatype (e.g. `Jekyll::OrgPage`), a `Reader` subclass and a `Generator` subclass to inject that datatype into a given `Site` instance.

The above approach will give you greater control in comparison to piggybacking on existing implementation in the Core.
