### ISSUE TITLE
"/*" breaks highlighting in JSON code block

### ISSUE THREAD

**Issue by Mattnmoore** [jekyll/jekyll#7933]
It appears as though /* breaks code highlighting in subsequent lines within a code block. I've tried the following, and they all fail.
````
```json
{
  "test": "/*this is a test*",
  "test1": "test1",
  "test2": "test2"
}
```
````

```
{% highlight json %}
{
  "test": "/*this is a test*",
  "test1": "test1",
  "test2": "test2"
}
{% endhighlight %}
```
```
{% highlight json %}
{% raw %}
{
  "test": "/*this is a test*",
  "test1": "test1",
  "test2": "test2"
}
{% endraw %}
{% endhighlight %}
```

In all cases, the 3rd line onward loses syntax highlighting.

**Comment by ashmaroli** [comment]
Thank you for opening this ticket. However, Jekyll does not handle syntax-highlighting directly.
It delegates that to a program known as Rouge.

I would suggest that you try using various versions listed here (starting from the latest and proceeding backwards) and see if a particular version helps resolve this.
You can point use a particular version by listing it in the Gemfile:
```ruby
# Gemfile

gem "jekyll", "~> 4.0"
gem "rouge", "3.12.0"
```
If all fails, you may want to go through issues and pull requests at https://github.com/rouge-ruby/rouge and submit a ticket there if one similar doesn't exist already.
