### ISSUE TITLE
Problem with linking to page.url with filenames including ØÆÅ characters

### ISSUE THREAD

**Issue by andreasbalevik** [jekyll/jekyll#7934]
| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  Windows 10           |
| `jekyll`         |  Latest|
| `github-pages`   | Latest     |

---

## Expected Behaviour

When clicking the link "Min første blog post (filename in norwegian)" it should send me to the file `/jekyll/update/2019/12/16/min-første-blog-post.html`

## Current Behavior

When clicking the link jekyll returns 404 Page not found. The URL says: `http://localhost:4000/jekyll/update/2019/12/16/min-f%C3%B8rste-blog-post.html `

When checking the generated index.html the a href is pointing to 
`<a class="post-link" href="/jekyll/update/2019/12/16/min-f%C3%B8rste-blog-post.html">`

The url is not decoded.

So i add custom _plugin url_decode, and list the page.url with decoding. The url is now correct: 
`<a class="post-link" href="/jekyll/update/2019/12/16/min-første-blog-post.html">`

But the http GET Header still says: 
`Request URL: http://localhost:4000/jekyll/update/2019/12/16/min-f%C3%B8rste-blog-post.html`

And jekyll is returning 404.

I use jekyll for blog posts, and netlify to generate the markdown files. Since the title is in norwegian the html file will be in norwegian causing jekyll to fail. 

## Code Sample

This is a fresh site, the only thing changed is adding two new posts in _post
https://github.com/andreasbalevik/jekyll-example

The link with norwegian filename is not working. Even if i add url_decode.

**Comment by ashmaroli** [comment]
This is a known issue with **Ruby on Windows**.
Currently, the only solution is to use ascii characters in the filename.
Even though you're only facing issues with URLs.., you'll also have issues with creating folders if the post's category is named `første`.

The other alternative is to use a different OS.

**Comment by andreasbalevik** [comment]
Thank you, i tried building the same application on Ubuntu 18 and it worked. 
I should have tried a different OS before posting the issue. 

I gues as long as the project is built on a different OS than Windows there is no issue.
