### ISSUE TITLE
warning: Using the last argument as keyword parameters is deprecated (Ruby 2.7.0)

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#7947]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     macOS       |
| `jekyll`         | Latest     |
| `ruby`   | Latest     |

---

## Expected Behaviour

No warnings output when generating jekyll website with Ruby 2.7.0

## Current Behavior

```
bundle exec rake site:generate

/code/jekyll/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/code/jekyll/lib/jekyll/document.rb:466: warning: Using the last argument as keyword parameters is deprecated
/code/jekyll/lib/jekyll/document.rb:432: warning: Passing the keyword argument as the last hash parameter is deprecated
/code/jekyll/lib/jekyll/document.rb:75: warning: The called method `merge_data!' is defined here
/code/jekyll/lib/jekyll/document.rb:439: warning: Passing the keyword argument as the last hash parameter is deprecated
/code/jekyll/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecated
```

For more explanation on what is deprecated, see https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by ashmaroli** [comment]
Ruby 2.7 seems to be using lesser memory than Ruby 2.6
```diff
--- Travis build on Ruby 2.6.3
+++ Travis build on Ruby 2.7.0

- Total allocated: 425.21 MB (3818102 objects)
- Total retained:  19.86 MB (105724 objects)
+ Total allocated: 378.97 MB (3783442 objects)
+ Total retained:  19.53 MB (103632 objects)
```

@DirtyF Is there any significant speed improvements?

**Comment by DirtyF** [comment]
@ashmaroli nothing really noticeable without a proper benchmark 🤷‍♂ 

Ruby 2.7 also introduced better memory defragmentation, but I'm not sure it's applicable to Jekyll:
https://bugs.ruby-lang.org/issues/15626

**Comment by eirannejad** [comment]
Is there any way to suppress these warnings?

**Comment by DirtyF** [comment]
> Is there any way to suppress these warnings? Currently using `bundle exec jekyll serve 2>/dev/null`

Use current `master` until the 4.1 release: https://github.com/jekyll/jekyll/pull/7948#issuecomment-584132037

**Comment by leimao** [comment]
This should not be closed until Ruby 2.7.0 is supported.

**Comment by ashmaroli** [comment]
@leimao Deprecation warnings have been removed in versions v3.8.7 and v4.0.1.
Please update your program accordingly.

**Comment by leimao** [comment]
> @leimao Deprecation warnings have been removed in versions v3.8.7 and v4.0.1.
> Please update your program accordingly.

Thank you. I did `sudo bundle update jekyll` and it seems that the warnings are gone.

**Comment by Atcold** [comment]
> > @leimao Deprecation warnings have been removed in versions v3.8.7 and v4.0.1.
> > Please update your program accordingly.
> 
> Thank you. I did `sudo bundle update jekyll` and it seems that the warnings are gone.

That did not work for me. `gem update jekyll` did the job, though.

**Comment by bhagatparwinder** [comment]
For me, neither of the above two commands worked (using Jekyll with GitHub pages).

Updated gemfile with github-pages to 206 and jekyll to 3.8.7. Executed ```bundle update jekyll```.

Everything is hunky-dory now.
