### ISSUE TITLE
Jekyll themes not working on Github Pages

### ISSUE THREAD

**Issue by algunacosa** [jekyll/jekyll#7968]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      Manjaro Linux 18.3      |
| `jekyll`         |  3.8.5  |
| `github-pages`   | Latest  (203)   |

---

## Expected Behaviour

The page works fine on GH Pages

## Current Behavior

The page works fine, but the theme does'nt work, so the page looks without any style. 
The theme works good on my desktop, even if i use the gem-bassed theme or the regular theme. The only theme that works on GH Pages is Minima, in the others the behaviour is as I explained.

**Comment by DirtyF** [comment]
Please use the GitHub Community forum for issues related to GitHub Pages, this repository is intended for Jekyll reproducible bugs only, thanks.
