### ISSUE TITLE
reStructuredText

### ISSUE THREAD

**Issue by cup** [jekyll/jekyll#7969]
I see that Markdown is supported:

https://jekyllrb.com/docs/configuration/markdown

Is reStructuredText supported?

https://docutils.sourceforge.io/docs/user/rst/quickref.html

**Comment by DirtyF** [comment]
Not officially, it would be the job of a converter plugin. A quick google search shows it used to work:
https://randomgeekery.org/2015/09/08/restructuredtext-in-jekyll/

A gem plugin would be nice. Closing as this won't be implemented in the core.
