### ISSUE TITLE
My command plugin fails to load after migrating to jekyll 4

### ISSUE THREAD

**Issue by mnyrop** [jekyll/jekyll#7976]
Hello! I'm a jekyll plugin maintainer. After migrating my command plugin (pagemaster) to Jekyll 4, running `jekyll serve` or `jekyll pagemaster` throws the following error:
```
bundler: failed to load command: jekyll (/Users/me/Development/project/vendor/bundle/ruby/2.6.0/bin/jekyll) LoadError: cannot load such file -- pagemaster/collection.....
```
However, this is only when the gem is loaded from rubygems. Everything works when the gem is loaded locally in the Gemfile from `:path` OR when loaded from the `:git` branch. Any ideas would be greatly appreciated, since I needed to yank my most recent (broken) release, and I cannot reproduce the error in development.

Repo is here: https://github.com/mnyrop/pagemaster/tree/2.1.1

Note: I've already replaced my `require_relative` statements with `require` in case there was a symlink issue. I have also asked my question on Gitter but feel my question is too specific.

**Comment by ashmaroli** [comment]
Why do you feel this is because of Jekyll 4.0.
What is the output when you build with the `--trace` option?

**Comment by mnyrop** [comment]
Running with trace throws the exact same error. I can't know it's related to jekyll 4 for sure with the error thrown, however (1) it was working before using jekyll 4, and (2) there seem to be similar issues with established plugins popping up in Gitter. But again it's hard to tell bc the errors are vague. I would be happy to share more info if I could!

**Comment by ashmaroli** [comment]
I can't provide further support till you post the `--trace` output..

**Comment by mnyrop** [comment]
```
bundler: failed to load command: jekyll (/Users/marii/.rbenv/versions/2.5.7/bin/jekyll)
LoadError: cannot load such file -- pagemaster/collection
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/pagemaster-2.1.1/lib/pagemaster.rb:14:in `require'
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/pagemaster-2.1.1/lib/pagemaster.rb:14:in `<top (required)>'
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
  /Users/marii/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:11:in `<top (required)>'
  /Users/marii/.rbenv/versions/2.5.7/bin/jekyll:23:in `load'
  /Users/marii/.rbenv/versions/2.5.7/bin/jekyll:23:in `<top (required)>'
```

**Comment by ashmaroli** [comment]
This is not related to Jekyll 4 at all.. therefore I'm closing this.
However, I'd recommend that you take a look in your plugin's `gemspec`. The `spec.files` is incomplete:
```ruby
Gem::Specification.new do |spec|
  spec.name          = 'pagemaster'
  spec.files         = ['lib/pagemaster.rb']
  spec.require_path  = 'lib'
```

**Comment by ashmaroli** [comment]
Also, it should be `spec.require_paths`..
Ref: https://guides.rubygems.org/specification-reference/

**Comment by mnyrop** [comment]
Ooof you're 100% right. I must not have updated it when i broke the classes out to other files. Apologies.
