### ISSUE TITLE
Accessing site context in filters documentation issue

### ISSUE THREAD

**Issue by rp-pedraza** [jekyll/jekyll#7986]
In https://jekyllrb.com/docs/plugins/filters/:

> ProTip™: Access the site object using Liquid
> 
> Jekyll lets you access the site object through the context.registers feature of Liquid at context.registers[:site]. For example, you can access the global configuration file _config.yml using context.registers[:site].config.
> 

I believe `context` should `@context`.

**Comment by ashmaroli** [comment]
Yes, you're right @rp-pedraza :tada: 
Feel free to submit a pull request to update the documentation. Clicking on the *`Improve this page`* at the top of the page will help you get started.
If you're comfortable with the language, optionally, you may also reword the entire note content.

**Comment by rp-pedraza** [comment]
Done. https://github.com/jekyll/jekyll/pull/7989
