### ISSUE TITLE
`trace` is listed twice in `jekyll serve -h`

### ISSUE THREAD

**Issue by danr** [jekyll/jekyll#8001]
## Motivation

```
$ docker run -it jekyll/jekyll jekyll serve -h | grep trace
        -t, --trace        Show the full backtrace when an error occurs
        -t, --trace        Show the full backtrace when an error occurs
```

## Suggestion

List it only once :sunglasses:

**Comment by ashmaroli** [comment]
@danr Where in the documentation site is this..?

**Comment by mattr-** [comment]
It's not in the docs site. It's in the command output when ran via docker.

**Comment by ashmaroli** [comment]
This has been fixed in the latest version of Mercenary gem. Updating the docker image should resolve this then.

**Comment by danr** [comment]
Alright!
