### ISSUE TITLE
Wrong encoding when redirected to 404 page

### ISSUE THREAD

**Issue by mateutek** [jekyll/jekyll#8003]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      macOS mojave      |
| `jekyll`         | Latest     |
| `github-pages`   | no     |

---

## Expected Behaviour
Encoding is fixed when redirected to 404 page

## Current Behavior
When entering not recognized url' I'm redirected to 404 page with broken encoding, but when i enter the /404 page everything is fine.

## Code Sample
Unfortunately i cannot provide any repository, but can share some parts of the code if necessary

**Comment by ashmaroli** [comment]
> Unfortunately i cannot provide any repository, but can share some parts of the code if necessary

@mateutek If you can reproduce this issue with **just those parts of the code**, then please do share them, otherwise this may just be left to go stale.
At minimum, we'd like to see the contents of your Gemfile and config file. Along with that any page that could demonstrate this issue.

**Comment by mateutek** [comment]
OK,
I searched a little bit more and found that after deploy everything is working fine.
Even the plain is working fine, on base port.
The problem was using browsersync which didn't (somehow) understand the encoding after the redirection.
