### ISSUE TITLE
Verification of publisher domain fails when hosted on GitHub Pages

### ISSUE THREAD

**Issue by abraunegg** [jekyll/jekyll#8006]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      N/A      |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

When validating the JSON file, Microsoft Azure should accept the JSON file, no additional content type header should be sent

## Current Behavior

Microsoft Azure rejects the JSON file (.well-known/microsoft-identity-association) with a "server returned an unexpected content type header value", thus verification cannot be performed.

See: https://github.com/MicrosoftDocs/azure-docs/issues/46080 for further details

## Code Sample

N/A

1. Register a new application on Microsoft Azure
2. Host identity file on GitHub pages under /.well-known/microsoft-identity-association
3. Configure `_config.yml` to include `.well-known`

**Comment by abraunegg** [comment]
@DirtyF 
Any update as to how to fix this issue? It is holding back publishing the application verification details for the Linux OneDrive client - any information you can provide is greatly appreciated.

**Comment by ashmaroli** [comment]
@abraunegg You may want [contact GitHub](https://github.com/contact) directly since Jekyll doesn't control GitHub Pages

**Comment by abraunegg** [comment]
@ashmaroli 
I already did via the online form on GitHub - zero response from them

Any further suggestions?

**Comment by ashmaroli** [comment]
> zero response from them. Any further suggestions?

Yes, please wait for a day or two further.
If you still don't get a response, open a ticket at the [`github-pages` gem repository](https://github.com/github/pages-gem).

**Comment by Mike-EEE** [comment]
Any luck here @abraunegg, by chance?  I am running into the same issue with my GitHub Pages site. 😞

**Comment by abraunegg** [comment]
@Mike-EEE 

No luck thus far - sorry.

**Comment by Mike-EEE** [comment]
Ah bummer, @abraunegg ... FWIW I am discussing this directly with MSFT on their forums since this is an Azure domain issue here:

https://docs.microsoft.com/answers/questions/13291/publisher-domain-verification-fails-because-verifi.html

Any additional comments/upvotes there to increase visibility/relevance would be greatly appreciated. 👍

**Comment by abraunegg** [comment]
@Mike-EEE 
Added additional comment re issue

**Comment by Mike-EEE** [comment]
Thank you @abraunegg ... looks like a basic parsing issue.  GitHub Pages is serving the content according to specification and Azure simply cannot handle it.

**Comment by abraunegg** [comment]
@Mike-EEE 
Agree totally .. it would be great if the Azure team could fix this as this really appears to be a bug with there platform and how it interprets responses.

**Comment by DirtyF** [comment]
Closing. @parkr might be able to transfer to the pages team.

**Comment by abraunegg** [comment]
@DirtyF 
Why close this without resolution ... that is not good 'product management' process without discussion with relevant parties .... please re-open until a resolution determined as otherwise this bug / issue will get lost and never get resolved.
