### ISSUE TITLE
A site from wiki has been DNS Hijacked

### ISSUE THREAD

**Issue by FoxerLee** [jekyll/jekyll#8018]
## Motivation

One site from the [wiki's sites](https://github.com/jekyll/jekyll/wiki/sites) page is being DNS Hijacked, redirecting to a gambling site.

Issue site: 9leg: http://www.9leg.com/

The original website is still working: https://zjiajun.github.io/

## Suggestion

Maybe you need to remove it.

**Comment by DirtyF** [comment]
Thanks, done.
