### ISSUE TITLE
Collection sorting breaks with number ids ending with the numbers 8 or 9

### ISSUE THREAD

**Issue by MatthewFallon** [jekyll/jekyll#8024]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     Fedora 30       |
| `jekyll`         | Latest     |
| `github-pages`   | No     |
| `netlify` | Yes | 

---

## Expected Behaviour

I expected for jekyll to iterate through a collection of "questions" that I had created in markdown by using the number key in order to sort all of the questions from [001-nnn].

```
collections:
  questions:
    sort_by: number
    output: true
    permalink: "/:title"
```
Example of each question in questions:
```
---
layout: question
title: question-001
number: 001
question: Name a reason you might get rid of an old family heirloom.
answer1: Broken | 29
answer2: Ugly | 22
answer3: Divorce | 18
answer4: Sell / Need money | 12
answer5: Too much stuff | 10
answer6: Family feud | 5
answer7: Moving | 2
answer8:
answer9:
answer10:
---
```

## Current Behavior

Jekyll will create pages for all files with a number key with value between [nn1-nn7], but will fail for any builds where there is a file with any number with the  value 8 or 9 at the end of it (eg. 008, 009, 019, etc.)

Here is my stacktrace  for when the error occurs in build:
```
Configuration file: /home/mfallon/Documents/CLCFeud/_config.yml
            Source: /home/mfallon/Documents/CLCFeud
       Destination: /home/mfallon/Documents/CLCFeud/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
bundler: failed to load command: jekyll (/home/mfallon/bin/jekyll)
NoMethodError: undefined method `zero?' for nil:NilClass
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/collection.rb:242:in `block in sort_docs_by_key!'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/collection.rb:237:in `sort!'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/collection.rb:237:in `sort_docs_by_key!'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/collection.rb:226:in `sort_docs!'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/collection.rb:68:in `read'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/readers/collection_reader.rb:18:in `block in read'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/readers/collection_reader.rb:17:in `each_value'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/readers/collection_reader.rb:17:in `read'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/reader.rb:20:in `read'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/site.rb:174:in `read'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/site.rb:74:in `process'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
  /home/mfallon/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /home/mfallon/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /home/mfallon/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /home/mfallon/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /home/mfallon/.gem/ruby/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /home/mfallon/.gem/ruby/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
  /home/mfallon/bin/jekyll:23:in `load'
  /home/mfallon/bin/jekyll:23:in `<top (required)>'
```
To replicate, clone the repo, move all files from [008-080].md from the _questions folder to a temporary _hidden folder, observe that the site builds. change the value for [number] to 008 or 019 on any of the files left in the _questions folder, and observe that the build fails. 

This seems to be out of my depth to fix the specific issue that is occurring to cause this.I apologize if it's because I'm doing something wrong, slightly new to Jekyll, but it isn't giving me much information for how this is breaking something, it's kind of boggling my mind right now why numbers ending in 8 or 9 would specifically cause the site builder to implode.

## Code Sample

This is the repo where this site is hosted. 

[https://github.com/MatthewFallon/CLCFeud](https://github.com/MatthewFallon/CLCFeud)

Edit: managed to fix my issue by removing all the leading zeroes in my key value pairs. The bug still exists at commit 2357a35 where I had leading zeroes in those files, it is linked here:
[https://github.com/MatthewFallon/CLCFeud/tree/2357a35b56cc102fee28407a8e18f07210c4a509](https://github.com/MatthewFallon/CLCFeud/tree/2357a35b56cc102fee28407a8e18f07210c4a509)

example of what the site does is currently up at [https://clc-feud.netlify.com](https://clc-feud.netlify.com)

**Comment by MatthewFallon** [comment]
Have found that this issue specifically occurs if the numbers you are using have padding 00's in the front of the number. the number 008 seems to be treated as a string while the number 007 or 016 seem to be treated as an integer.

**Comment by ashmaroli** [comment]
@MatthewFallon Thank you for reporting this bug to us. While the core cause is with Ruby's `yaml` library, there exists a *minor* bug within Jekyll as well (the same line evident in the stack trace: `jekyll-4.0.0/lib/jekyll/collection.rb:242`) which is what causes the builds to fail.

The fix at our end would be:
```diff
 # jekyll-4.0.0/lib/jekyll/collection.rb:242

- if order.zero? || order.nil?
+ if order.nil? || order.zero?
    apples[-1] <=> olives[-1]
  else
```
If you're comfortable with Ruby and Git as such, you can emulate the patch above in a branch on a fork of the Jekyll repository and continue using `number: 008` in your document and report back to us if it has any side-effect on the sorting.

Either ways, I will be opening a pull request after doing some additional testing with https://github.com/MatthewFallon/CLCFeud/commit/2357a35b56cc102fee28407a8e18f07210c4a509 (*Thank you for the repository*).

---

Regarding the behavior with just Ruby's YAML library (no Jekyll involvement), here is the `irb` demo on Ruby 2.4:
```
$ irb
irb(main):001:0> require 'yaml'
=> true
irb(main):002:0> YAML.load("---\nnum: 001\n")
=> {"num"=>1}
irb(main):003:0> YAML.load("---\nnum: 007\n")
=> {"num"=>7}
irb(main):004:0> YAML.load("---\nnum: 008\n")
=> {"num"=>"008"}
```
