### ISSUE TITLE
docs: misleading code snippet for liquid page on getting started guide

### ISSUE THREAD

**Issue by jordanmoore753** [jekyll/jekyll#8033]
## Motivation

Hello! I hope you're having a good day. I'm writing regarding the code snippet on the following page: [Liquid: Getting Started](https://jekyllrb.com/docs/step-by-step/02-liquid/). I believe it is misleading, as it shows the `<h1>` tag inside of the **front matter** at the top of the page. Here is the exact snippet in question:

```html
...
<h1>{{ "Hello World!" | downcase }}</h1>
...
``` 
I believe this is misleading because putting the `<h1>` tag inside of the front matter doesn't actually work. I think new users would see this and write their html as follows and not get the correct output:

```html
---
{{<h1>Hello World! | downcase</h1>}}
---
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <h1>Hello World!</h1>
  </body>
</html>
```
I'm not sure if this section of the page is supposed to be showing the reader **how** to include the **liquid**, or, if this section is merely leading into the next section where front matter is actually used. I believe that it will read better if this section is treated as a solution on its own, and then the next section on front matter actually shows **how** to use front matter on a page.

## Suggestion

I suggest that the code snippet be changed to the following:

```html
---
# front matter goes here -- this will be used on the next page of tutorial!
---
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <h1>{{ "Hello World!" | downcase }}</h1>
  </body>
</html>
```
This snippet clearly shows where the front matter should go, as well as where the **liquid templating** should be. 

Thanks for taking the time to read this and have a great day!

**Comment by DirtyF** [comment]
Hey @jordanmoore753 feel free to click improve this page on upper right on https://jekyllrb.com/docs/step-by-step/02-liquid/ and submit a pull request. Thanks. 🙏

**Comment by dmiedev** [comment]
@jordanmoore753 I don't think the first snippet has a front matter: the line is surrounded by **triple dots**, not triple dashes, and they are supposed to mean that the file is continued both upwards and downwards. 
Moreover, if you follow the tutorial from the step 1, it can be inferred that `    <h1>Hello World!</h1>
` in `<body>` is supposed to be replaced with `<h1>{{ "Hello World!" | downcase }}</h1>`.

**Comment by ashmaroli** [comment]
Thank you @dmiedev for the clarification.
