### ISSUE TITLE
Backticks (```) do not generate data-lang on code blocks

### ISSUE THREAD

**Issue by benknoble** [jekyll/jekyll#8040]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | macOS 10.14.5 |
| `jekyll`         | Latest   |
| `github-pages`   | Latest   |

---

## Expected Behaviour

When enclosing code in triple backticks and specifying a language (<code>```lang</code>), I expect `data-lang` attributes to be generated, similar to using <code>{% highlight lang %}</code> but without the tedium.

## Current Behavior

What's actually generated: 

```
<div class="language-bash highlighter-rouge">
<div class="highlight">
<pre class="highlight">
<code>
...
```

I would prefer `data-lang="bash"` on one of these (`pre` or `code` if possible), rather than this approach. Again, using `{% highlight lang %}` "solves" this, but is not ideal.

## Code Sample

I'm using [benknoble/benknoble.github.io](https://github.com/benknoble/benknoble.github.io) for examples; any language-specific code block will do.

**Comment by ashmaroli** [comment]
@benknoble, we delegate the job of converting <code>```lang</code> into HTML to the `kramdown` gem.
Please file a ticket at that [gem's repository](https://github.com/gettalong/kramdown).
Thank you.
