### ISSUE TITLE
Generating URLs without .html extensions

### ISSUE THREAD

**Issue by jribbens** [jekyll/jekyll#8043]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  Ubuntu 16.04.6          |
| `jekyll`         | 4.0.0 |
| `github-pages`   | No     |

---

## Expected Behaviour

I expect that if I have an input file called `foo.html`, and I do `permalink: /foo` in its front-matter, or `permalink: /:title` in the `_config.yml`, that the output file will be `foo`.

## Current Behavior

The file is actually output as `foo.html`.

## Notes

Obviously I don't really care if I achieve the result I want using the exact configuration described above (although Jekyll's documentation does seem to claim it should behave as I expect), if some other configuration setting will achieve the desired result that would also be fine.

I *can* get it to output as `foo/index.html` by using a `permalink` of `/foo/` or `/:title/`, but that isn't the result I want.

Please don't tell me I can hide this problem using hacks in the web server configuration. I know that. I don't want to have to paper over incorrect output structure by hiding it behind URL transformations in the server.

**Comment by ashmaroli** [comment]
@jribbens This behavior was introduced in https://github.com/jekyll/jekyll/commit/669c80391278c3ed9b7431eac4c56fedbc50614d, way back in 2015.
From the commit message, this looks like a conscious decision.

**Comment by jribbens** [comment]
Deliberate or not, it's surely a bug that Jekyll ignores the explicit configuration set and has its own hard-coded policies that cannot be overridden, resulting in a common user requirement being impossible to achieve. Not to mention, this is not documented - I suspect if it was, the process of writing the documentation would prompt the realisation that it's a bug ;-)

**Comment by mattr-** [comment]
At this point I see no reason to change Jekyll's behavior.
