### ISSUE TITLE
Using Jekyll 4 and jekyll-slim breaks

### ISSUE THREAD

**Issue by bmedici** [jekyll/jekyll#8053]
Hi all,

## Environment

Using Jekyll gem v4.0.0 along with jekyll-slim v0.8.2 to be able to use Slim templates.

## Expected Behaviour

I would expect Jekyll to start serving pages and interpret my Slim templates/pages

## Current Behavior

I get this error when issuing ```bundle exec jekyll serve --trace```:

```
bruno @ ted ~/dev/bmc-www ▶ bundle exec jekyll serve --trace
Configuration file: dev/bmc-www/_config.yml
            Source: dev/bmc-www
       Destination: dev/bmc-www/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
bundler: failed to load command: jekyll (/Users/bruno/.rbenv/versions/2.6.5/bin/jekyll)
NoMethodError: undefined method `extname' for #<Jekyll::Layout:0x00007fd50a2c3a58>
  /Users/bruno/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:39:in `block in converters'
  /Users/bruno/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:39:in `select'
```

Using ```jekyll doctor```gives:
```
jekyll doctor
Configuration file: dev/bmc-www/_config.yml
jekyll 4.0.0 | Error:  undefined method `extname' for #<Jekyll::Layout:0x00007ffea0239be0>
```

What is the expected way to use Slim templates with Jekyll 4.x ?

Thanks !

**Comment by ashmaroli** [comment]
Are you able to use it as expected with Jekyll 3.8.6 ?

**Comment by DirtyF** [comment]
The jekyll-slim plugin has been archived: https://github.com/slim-template/jekyll-slim

**Comment by DirtyF** [comment]
Getting also an error with jekyll 3.3: 

```
NoMethodError: undefined method `transform' for #<Jekyll::Renderer:0x00007f7fe9257798>
  /Users/frank/code/slim-template/vendor/bundle/ruby/2.6.0/gems/jekyll-3.3.0/lib/jekyll/convertible.rb:81:in `transform'
```

Looks like this gem has not been tested on Jekyll > 3.0.

**Comment by bmedici** [comment]
> Are you able to use it as expected with Jekyll 3.8.6 ?

Not at all, I try to downgrade to 3.8 with no more luck.

**Comment by bmedici** [comment]
> The jekyll-slim plugin is unmaintained and has been archived: https://github.com/slim-template/jekyll-slim

Yes, you're right, this is why I asked what is the best way to use slim with 4.x ?

**Comment by mattr-** [comment]
There isn't one. The only way to make `slim` and Jekyll work together is to fork the plugin, make it work with Jekyll 4, and then start using it.

**Comment by ashmaroli** [comment]
@bmedici The workaround (*based on the error report you posted*) is to patch Jekyll's `Layout` class. The steps would be:
- Create a Ruby file at the following path in your source directory: `_plugins/layout_patch.rb`
- The contents of this file would be:
  ```ruby
  module Jekyll
    class Layout
      alias_method :extname, :ext
    end
  end
  ```

**Comment by bmedici** [comment]
> Getting also an error with jekyll 3.3:
> 
> ```
> NoMethodError: undefined method `transform' for #<Jekyll::Renderer:0x00007f7fe9257798>
>   /Users/frank/code/slim-template/vendor/bundle/ruby/2.6.0/gems/jekyll-3.3.0/lib/jekyll/convertible.rb:81:in `transform'
> ```
> 
> Looks like this gem has not been tested on Jekyll > 3.0.



> The jekyll-slim plugin is unmaintained and has been archived: https://github.com/slim-template/jekyll-slim

You're not replying to the question: what is then the right way to use Slim with Jekyll now ?

**Comment by ashmaroli** [comment]
@bmedici See my comment [above](https://github.com/jekyll/jekyll/issues/8053#issuecomment-598714162) The best solution however would be to get someone to maintain the plugin if you or some other user cannot.

**Comment by bmedici** [comment]
> ```ruby
> module Jekyll
>   class Layout
>     alias_method :extname, :ext
>   end
> end
> ```

Thank you, it seems it does the job for now. I do keep in mind that the Slim plugin is old and unmaintained, but we should be able to use erb/haml/slim with Jekyll, and it should be available straight from the core Jekyll gem..

**Comment by ashmaroli** [comment]
> but we should be able to use erb/haml/slim with Jekyll, and it should be available straight from the core Jekyll gem

Jekyll has never advertised being able to convert various formats out-of-the box. Jekyll has an architecture that allows it to be easily extended via plugins. That has been the norm for a very long time.
