### ISSUE TITLE
[Feature Request] Allow using Rouge themes for rendered code-blocks

### ISSUE THREAD

**Issue by ChangyuYan** [jekyll/jekyll#8054]
jekyll 3.8.5
gem 3.1.2 
ruby 2.7.0p0

macOS Catalina 

I have also tried adding these in my _config.yml: 

```
# Build settings
markdown: kramdown
highlighter: rouge
```

I have tried this: 

![Screen Shot 2020-03-14 at 10 36 26 PM](https://user-images.githubusercontent.com/27938057/76696041-459dcc00-6644-11ea-8797-c4dce0206eb2.png)

And this: 

![Screen Shot 2020-03-14 at 10 37 33 PM](https://user-images.githubusercontent.com/27938057/76696051-5ea67d00-6644-11ea-855a-d0960cf655ad.png)

I have also added Rouge to my Gemfile: `gem "rouge", "3.13.0"` and run `$bundle install` 

Yet, whether locally or on my GitHub pages, the syntax coloring just won't show: 

![Screen Shot 2020-03-14 at 10 39 22 PM](https://user-images.githubusercontent.com/27938057/76696090-a75e3600-6644-11ea-960f-607b86a03bb8.png)

![Screen Shot 2020-03-14 at 10 39 28 PM](https://user-images.githubusercontent.com/27938057/76696091-aa592680-6644-11ea-83ff-05cca6c22e2d.png)

Help, please?

**Comment by ashmaroli** [comment]
Jekyll (via Rouge) only generates the *markup* to support syntax-highlighting.
The actual coloring is dependent on your stylesheeet or theme.

**Comment by ChangyuYan** [comment]
> Jekyll (via Rouge) only generates the _markup_ to support syntax-highlighting.
> The actual coloring is dependent on your stylesheeet or theme.

So what do I do to avoid the Rouge markup being overwritten by my current stylesheet or theme? Like, is there a specific place I should check? I have checked my css and I don't have a style for <code> or <pre>

**Comment by ashmaroli** [comment]
As of Jekyll 4.0.0, you can't use the "default" Rouge colors (or Rouge themes) out-of-the-box with Jekyll.
To have Jekyll use the colors provided by Rouge, you will have to (either of the following):
- Write a Ruby plugin (won't be allowed on GitHub Pages though) and bring in that functionality.
- Generate a stylesheet via Rouge manually and link them to your site.

I'm marking this as a feature-request. Feel free to submit a PR.

**Comment by ashmaroli** [comment]
> After all, manually modifying the css still doesn't seem to give me the various colorings

There are existing stylesheets that you can use though:
https://github.com/jwarby/jekyll-pygments-themes

**Comment by ChangyuYan** [comment]
> > After all, manually modifying the css still doesn't seem to give me the various colorings
> 
> There are existing stylesheets that you can use though:
> https://github.com/jwarby/jekyll-pygments-themes

Thank you, this link is very helpful!
