### ISSUE TITLE
 Incremental build: disabled. Enable with --incremental

### ISSUE THREAD

**Issue by tugii20** [jekyll/jekyll#8061]
can edit to my file such as _config.yml from jekyll visual studio code but not showing on local host or when i push it to github repos, wont showing there?

**Comment by ashmaroli** [comment]
Incremental build doesn't have a visible artifact that will be visible on localhost on GitHub Pages. The only artifact is a `.jekyll-metadata` written to source directory.
Moreover, plugins do not respect the `--incremental` flag.
