### ISSUE TITLE
Incremental build and Liquid capture issue

### ISSUE THREAD

**Issue by HorlogeSkynet** [jekyll/jekyll#8062]
Hello everyone :wave:

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Debian |    10 (Buster)        |
| `jekyll`         | v4.0.0     |
| `github-pages`   | No     |

---

## Expected Behaviour

I expected incremental build to work as a _regular_ build when using `capture` statements.

## Current Behavior

Some of my posts contain `{% include %}` or even `{% highlighter %}` blocks.
Due to #1303, I've used Liquid `{% capture %}` blocks (see below) to work-around this issue.

When enabling incremental build, the first build works very well : the output HTML is properly rendered, even for those blocks.
On file modification (and thus Jekyll regeneration), `{% capture %}` does not seem to work anymore, and the "rendered" HTML contains `{% include %}` and `{% highlighter %}` yet again :roll_eyes:

## Code Sample

A simple static page :

```yaml
---
layout: null
---
<!-- ... ->
{%- capture post_content -%}{{ post.content }}{%- endcapture -%}
<!-- ... ->
{{ post_content | markdownify | xml_escape }}
<!-- ... ->
```

Incremental build is enabled in `_config.yml` :

```yaml
# ...
incremental: true
```

An example output on first build (for an `{% highlighter %}` block) : :ballot_box_with_check:  

```html
<!-- -->
&lt;figure class=&quot;highlight&quot;&gt;&lt;pre&gt;&lt;code class=&quot;language-bash&quot; data-lang=&quot;bash&quot;&gt;apt &lt;span class=&quot;nb&quot;&gt;install &lt;/span&gt;git-lfs&lt;/code&gt;&lt;/pre&gt;&lt;/figure&gt;
<!-- -->
```

... and after an incremental regeneration : :negative_squared_cross_mark:

```html
<!-- -->
&lt;p&gt;{% highlight bash %}
apt install git-lfs
{% endhighlight %}&lt;/p&gt;
<!-- -->
```

---

I can run further tests as needed, just keep me posted and tell me what you think about that.

Bye, thanks :wave:

**Comment by ashmaroli** [comment]
@HorlogeSkynet The issue here is not with `{% capture %}` but with `{{ post.content }}`.
See #4112
