### ISSUE TITLE
docs: Finding the switches for serve under "BUILD > Command line usage" seems unintuitive

### ISSUE THREAD

**Issue by yb66** [jekyll/jekyll#8065]
## Motivation

The docs on the website for `jekyll serve` are hidden away under [configuration options](https://jekyllrb.com/docs/configuration/options/#serve-command-options) in the BUILD section. I found them by using the search tool.

Serving and building seem separate in my mind, even if one depends on the other. Hence, finding the switches for serving under a section for build's configuration options felt unintuitive.

## Suggestion

Call the section BUILD & SERVE as those are the two most likely options you'll use (`new` is already covered in the quick start), or perhaps COMMAND LINE USAGE and then have sections like `Overview` (which could [stay the same](https://jekyllrb.com/docs/usage/) yet its title would make more sense), `new`, `build` and `serve` with their more extended instructions and something like `More…` for the rest, or split those up too.

What I'm saying is, I'm stupid and need all the help I can get to find things, but that's a good test for documentation :)

Thanks for all the hard work on the project.

Regards,
iain

**Comment by ashmaroli** [comment]
@yb66 Are you willing to learn enough Jekyllin' to submit a pull request? Follow these steps (in order):
- Fork and Clone this repository to your local system.
- Open a terminal and `cd` into the cloned location.
- Run `gem install bundler` (if you don't have Bundler installed already).
- Run `bundle install` to install all necessary dependencies.
- Run `cd docs` to move the terminal focus into the `docs/` directory.
- Create a new branch: `git checkout -b serve-documentation`
- Run `bundle exec jekyll serve` to start the local server.
- Point your browser to `http://localhost:4000/`.
- Make your desired changes to the concerned files in `docs/_docs` directory in the cloned location.
- Once satisfied with your changes, stop the local server (Ctrl + C).
- Commit your changes: `git add . && git commit -m "Document options for serve subcommand"`.
- Push the branch to your GitHub repository: `git push origin serve-documentation`.
- Open a Pull request.

**Comment by yb66** [comment]
@ashmaroli sure, and thanks for the helpful instructions, I'll try and get a PR in today.

Regards,
iain
