### ISSUE TITLE
I have a trouble installing jekyll ， win10 /ruby2.6.5

### ISSUE THREAD

**Issue by xxb0120** [jekyll/jekyll#8068]
C:\WINDOWS\system32>gem install jekyll
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
D:/Ruby26-x64/bin/ruby.exe -I D:/Ruby26-x64/lib/ruby/site_ruby/2.6.0 -r ./siteconf20200322-20380-c8bsu3.rb extconf.rb
creating Makefile

current directory: D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean
current directory: D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
make failedNo such file or directory - make "DESTDIR="

Gem files will remain installed in D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to D:/Ruby26-x64/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/http_parser.rb-0.6.0/gem_make.out

**Comment by ashmaroli** [comment]
Did you run `ridk install` as the last part of installing Ruby?

**Comment by xxb0120** [comment]
Yes,I installed msys2 with ridk install

**Comment by ashmaroli** [comment]
You can try the following:
- Run `ridk enable`
- The run `gem install jekyll`
If it still fails, we can't help you. Sorry!
Please head over to [our forum](https://talk.jekyllrb.com) and search for similar issues.
