### ISSUE TITLE
index.html in _site is different from root

### ISSUE THREAD

**Issue by fqassemi** [jekyll/jekyll#8070]
When I am running "bundle exec jekyll server" my local site pick up the index.html from root directory. As soon as I make small changes in the "_post" folder suddenly all _config.yml changes start to appear. I am not sure why index.html in the root directory does not contain all the recent changes. By the way, as soon as terminate and return to the site I see the same old index.html.

**Comment by ashmaroli** [comment]
@fqassemi Your post is too vague for us to help you. Why didn't you use the issue template we set up for every new issue ticket?

Which version of Jekyll are you using?
Are you deploying via GitHub Pages? If yes, what version?
Are you using any plugins?
Is there a public repository that we can take a look into..?

**Comment by DirtyF** [comment]
Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage.

**Comment by fqassemi** [comment]
Sorry for not using the template. Here is the information:
1) I am using jekyll 3.8.6
2) I am importing fastpages for gitlab  (https://github.com/fqassemi/diary)
3) Here are list of plugins:
  - jekyll-gitlab-metadata
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
4) Unfortunately there is no public repo. In fact, the whole trouble started to having private repo on gitlab. I have downloaded https://github.com/fqassemi/diary into my local computer. Changing - jekyll-github-metadata to - jekyll-gitlab-metadata. 

File is located in a directory called "diary" and I have changed urls in _config.yml :
url: "https://fqassemi.gitlab.io/"
baseurl: "/diary" 
url: "/"

I just simple wanted to have a private repo with the capabilities of fastpages (jupyter notebooks, word, snapshots, etc). I can include the whole _config.yml if necessary. 

Thanks.

**Comment by ashmaroli** [comment]
Well, the repo `https://github.com/fqassemi/diary` has both an `index.md` page and an `index.html` file.
`index.md` gets converted into `_site/index.html`..

So if you want `index.html` to convert into `_site/index.html`, *delete `index.md`*

**Comment by fqassemi** [comment]
I have removed index.md but again all those problem still persists. Simply, the index.html does not reflect what is in the _posts and it does not reflect what is in the _config.yml! It seems it is frozen to the old index.html no matter what I change. However, as soon as I make change in _post while jekyll is running then all those changes appears on the local website.

**Comment by DirtyF** [comment]
Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage.
