### ISSUE TITLE
jekyll: No post contents

### ISSUE THREAD

**Issue by icyshenfighting** [jekyll/jekyll#8071]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |    Windows        |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

Some posts on my home page.
## Current Behavior
Nothing on my home page but I can find my posts by tags. Also, when I push all the files to github, everything goes well. It's strange that I cannot find all of my post contents.

**Comment by DirtyF** [comment]
Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage.
