### ISSUE TITLE
feat: produce warning or error when accessing undefined variables?

### ISSUE THREAD

**Issue by fingolfin** [jekyll/jekyll#8076]
#7352  Summary

When writing `{{undefined_variable}}` in a Jekyll template file, this is silently replaced by nothing; it would be nice if instead a warning could be shown that `undefined_variable` is not defined.

## Motivation

It is very easy to make a mistake when accessing variables in a template. Maybe a typo in the variable name; maybe you just forget to prefix with `site.data.`; maybe somebody refactors things and renames or moves a variable, but forgets to adjust all places that access the variable. The resulting incorrect data can sometimes go unnoticed for extended periods of time.

If Jekyll instead would show a warning or error, it would be trivial to find and fix these problems. There could be an option to turn the warning on or off, or to switch between  ignore/warning/error. And the default for that warning could be on or off, either is fine with me, as long as I have a way to get it.

I think every Jekyll user would benefit from this. And it's nothing that could be done in a plugin. The only thing that's not clear to me is whether Jekyll can do it at all, or wether this is something for the Liquid developers instead?

## Guide-level explanation

I don't think there is much need for explanation. A warning like "Warning, attempt to read variable "XYZ" which was not defined before" should be self-explanatory.

## Reference-level explanation

I have no idea how this could be implemented :-(.

## Drawbacks

It might add complexity to the code base.

I can't really think of other downsides. OK, perhaps some projects would suddenly get a ton of warnings, but (a) this is mitigated by turning of the warning, and (b) most likely those warnings hint at real bugs and so are actually good.

## Unresolved Questions

One could extend the idea to also cover arbitrary undefined values in general -- such as attempting to use an entry of an array or dictionary that doesn't exist. But I am pretty sure there's quite a bit of code out there which relies on that to silently produce nothing, so for that, having a warning might be more of an issue -- but again, as long as one can turn it off, I see no harm.

**Comment by ashmaroli** [comment]
Have you tried the following configuration:
```yaml
liquid:
  strict_variables: true
```

**Comment by fingolfin** [comment]
Awesome! I swear I googled around for this before submitting this issue. Now of course it was trivial to find this on https://jekyllrb.com/docs/configuration/liquid/

My sincere apologies for wasting your time, and thank you very much for the pointer!
