### ISSUE TITLE
deprecated warnings in jekyll 4.0.0 with ruby 2.7.0 

### ISSUE THREAD

**Issue by toktay** [jekyll/jekyll#8077]
Hello,

I am a newbie in jekyll. My development environment is  manjaro (arch based distro). I am using `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]` and  `jekyll 4.0.0`  

I am receiving the same deprecation warnings while building and serving

While serving : 
```
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecate
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:466: warning: Using the last argument as keyword parameters is deprecated
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:432: warning: Passing the keyword argument as the last hash parameter is deprecated
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:75: warning: The called method `merge_data!' is defined here
```
While building 
```
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecate
```
I had to filter these out with `2>&1 | grep -v`  in my work flow otherwise they tend to hide other messages.. 

I would like to point it out even though it is not a bug...

**Comment by ashmaroli** [comment]
@toktay This has been fixed on `master` (unreleased). Please edit your Gemfile to point to this GitHub repository:
```ruby
gem "jekyll", github: "jekyll/jekyll"
```
