### ISSUE TITLE
make failed, exit code 127

### ISSUE THREAD

**Issue by MindSkyHost** [jekyll/jekyll#8078]
`current directory: /var/lib/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
/usr/bin/ruby2.5 -r ./siteconf20200326-5935-nozn0c.rb extconf.rb
creating Makefile

current directory: /var/lib/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean
sh: 1: make: not found

current directory: /var/lib/gems/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127`

Here are the full log.

**Comment by ashmaroli** [comment]
> sh: 1: make: not found

You did not install the development tools for your OS.
Please refer [our documentation](https://jekyllrb.com/docs/installation/).
