### ISSUE TITLE
How to access the header row in imported .csv data

### ISSUE THREAD

**Issue by chmaynard** [jekyll/jekyll#8086]
## Motivation

For any arbitrary imported .csv data file, I'd like to learn how to read and display the column names in the header. I can't find an example in the Jekyll docs that describes how to access the header row.

**Comment by ashmaroli** [comment]
You know what? I don't think there is a straight-forward way to render arbitrary data.. It has always been about rendering known property names.

We have a community forum at https://talk.jekyllrb.com/.
See if you can get some help there..

If not, this could be converted into a feature request for such functionality.

**Comment by MichaelCurrin** [comment]
Hi from the forum! I added an answer there. I provided a recommendation to use an existing plugin as a `keys` filter. It uses the Ruby `.key` method.

This seems like a sensible Jekyll feature request to me. 

Perhaps a higher level of abstraction could be get the first row and keys in one filter e.g. `csv_data | fields` which would internally be `csv_data[0] | keys`.

**Comment by ashmaroli** [comment]
@MichaelCurrin Since there's already a way to achieve this via Liquid, I doubt if a more straight-forward way would find its way into the Core.

That aside, would you be willing to write a tutorial about rendering CSV data into an HTML table for the Jekyll documentation site..?

**Comment by MichaelCurrin** [comment]
@ashmaroli  Sure, I'd love to. 

I think at the bottom of the Data files page would be appropriate - as _Example: Rendering a CSV as an HTML table_. Otherwise under _Guides_ section?

I'll post back here.

**Comment by ashmaroli** [comment]
@MichaelCurrin That's great!
We have an entire page for this at https://jekyllrb.com/tutorials/home/
All you need to do is add a markdown document under the `_tutorials` collection and register its slug in `_data/tutorials.yml`.
Then add a link to the tutorial page in the data files page as you see fit.

**Comment by MichaelCurrin** [comment]
Oh I got it now. Thanks!

**Comment by chmaynard** [comment]
Thank you both. 

Perhaps it would be helpful for me to describe a use case for this feature. I'm working on a blog post about three art songs by Debussy. I decided to publish the lyrics in the original French and in English, side by side. I have a spreadsheet with the lines in each song. The columns are Title, Stanza, French, English. The spreadsheet data gets exported in CSV format to a file in the  _data folder. The code uses Markdown, HTML, CSS, and Liquid to create a table for the lyrics. In the future, I might want to write about songs written in other languages. I decided it would be useful to create a more general solution that create these lyric tables for any two languages. That's why I need the column names.

**Comment by MichaelCurrin** [comment]
@chmaynard Okay thanks, yes that general case makes sense. I'll see if I can use songs/languages in the tutorial.

YAML can be structured however you like. If you structure it like as an array on hashes (like how Jekyll reads a CSV), then you **can** easily grab the first item in the array as the header, whether CSV or YAML.

Example:

`my_csv_file.csv`

```
name,github
Eric Mill,konklone
Parker Moore,parkr
Liu Fengyun,liufengyun
```

`my_yaml_file.yaml`

```yaml
- name: Eric Mill
  github: konklone
- name: Parker Moore
  github: parkr
- name: Liu Fengyun
  github: liufengyun
```

Both produce the same result - if you use `{{ site.data.my_csv_file[0] }}` 
or `{{ site.data.my_yaml_file[0] }}`, you get:

```
{“name”:”Eric Mill”,”github”:”konklone”}
```

**Comment by ashmaroli** [comment]
@MichaelCurrin I'd recommend having the tutorial based on a simple CSV data like below:
```csv
FirstName,LastName,Age,Location
John,Doe,35,United States
Jane,Doe,29,Female,France
Jack,Hill,25,Australia
```
The tutorial is only about using Jekyll to render the above data (or similar) into a HTML table.
(You may optionally proceed to instruct use of CSS and styling if you want..)

Handling specific use-case is up to the end-user.

**Comment by MichaelCurrin** [comment]
I just submitted a PR. #8090 🚀 😄 

@chmaynard I hope you'll find the tutorial super useful.

**Comment by MichaelCurrin** [comment]
@ashmaroli For background

I started using a the `keys` plugin (even forked it as [MichaelCurrin/jekyll-keys-filter](https://github.com/MichaelCurrin/jekyll-keys-filter)) and then realized the solution had the **same** number of lines in the template, yet required extra effort and was only slightly more readable and couldn't be used for values without extra work. 

So I went with the simpler solution - without the plugin.

With plugin:

```
    {% assign fields = row | keys %}
    {% for column_name in fields %}
    <td>{{ column_name }}</td>
    {% endfor %}
```

Without plugin:

```
        {% for pair in row %}
        {% assign column_name = pair[0] %}
        <td>{{ column_name }}</td>
        {% endfor %}
```

In fact if skip the `assign`, you can do it in fewer lines without the plugin. It's less readable though.

```
        {% for pair in row %}
        <td>{{ pair[0] }}</td>
        {% endfor %}
```

**Comment by chmaynard** [comment]
Thanks, I'll implement your solution and let you know how it goes.
