### ISSUE TITLE
index.html stops working when I reindent it

### ISSUE THREAD

**Issue by XilogOfficial** [jekyll/jekyll#8087]
My Jekyll site was working fine and I went to fix the crappy indentation in my index.html. I changed nothing else. After saving and reloading Jekyll only showed my front matter and file contents:
![image](https://user-images.githubusercontent.com/19237297/78073266-9b4ad600-73b1-11ea-8a2f-d9941ddb346b.png)
And it did not use my layout or anything. My other page and 404 worked just fine. An interesting debugging convo with a friend who is more experienced with Jekyll left him lost after we tried:

- Reinstalling Jekyll on this site
- Clearing cache and _site
- Trying different combinations of front matter that work on other pages
- Removing everything except front matter and adding a bit of text
- Changing random bits of the config, front matter and html

Nothing worked apart from downloading the old file from GitHub and using that. When trying to reindent it the page broke again. Even undoing all my changes and resaving broke it. The only fix is to paste the old file again.

Old file:
[index.zip](https://github.com/jekyll/jekyll/files/4411534/index.zip)
Jekyll 4.0.0
Windows 10 Pro

**Comment by ashmaroli** [comment]
Hello @XilogOfficial There could be something wrong with your *re-indented* index.html.
Could you *repeat the exact the same thing* and push the changed file to **a new branch** on your repository..?

**Comment by XilogOfficial** [comment]
Alright, will do in a couple mins.

**Comment by XilogOfficial** [comment]
Ok sorry I can't make another branch right now but I double checked, this was working right now before i fixed it and after adding some tabs it's broken:

[index.zip](https://github.com/jekyll/jekyll/files/4415200/index.zip)

My editor is Visual Studio Code if it matters

**Comment by ashmaroli** [comment]
The reason I asked you to push a new branch is because we can easily see what changed by using GitHub UI to compare the branch with the default branch.

I won't be unpacking a zip archive and go through changes manually, sorry.

**Comment by XilogOfficial** [comment]
Okay will do.

**Comment by XilogOfficial** [comment]
There you go, https://github.com/XilogOfficial/xilog/blob/master/index.html
there's master and master-broken

**Comment by ashmaroli** [comment]
What changes am I supposed to see here? The two branches are identical!

![comparison with master-broken](https://user-images.githubusercontent.com/12479464/78147727-8c1b6500-7451-11ea-92f7-3eba21ae403e.png)

**Comment by XilogOfficial** [comment]
Sorry I forgot to commit!

**Comment by ashmaroli** [comment]
okay.. It looks like your text editor is changing the encoding to `UTF-8 BOM`. Jekyll doesn't like this encoding. I suggest you search the internet to configure VSCode to not change the document's encoding and to set new documents to UTF-8 by default.

**Comment by XilogOfficial** [comment]
Got it thanks

**Comment by ashmaroli** [comment]
You're welcome.
