### ISSUE TITLE
feat: slugify :categories permalink

### ISSUE THREAD

**Issue by Soundium** [jekyll/jekyll#8093]
Hello,

I want to use for my blog following rule in _config.yml to see like https://test.com/brand-management/test.html:

`permalink: /:categories/:title`

If my category in Front Matter is like “Brand Management” then my permalink looks like https://test.com/brand%20management/test.html

Is it a bug or just misconfiguration?

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |            |
| `jekyll`         | master     |
| `github-pages`   | 3.8.5     |

---

## Expected Behaviour

Permalink use "-" between words.

https://test.com/brand-management/test.html

## Current Behavior

Permalink use %20 for "-" if the category has more than one word in the category.

https://test.com/brand%20management/test.html

**Comment by DirtyF** [comment]
Reproduced on current `master`.

**Comment by ashmaroli** [comment]
@Soundium I think the situation where a single category is a composite of multiple words has never been considered as a bug before.
So when we have two posts with the following front matter
```
---
category: "brand management"
---
```

```
---
categories: "brand management"
---
```
The first post would generate an URL with `/brand%20management/...`
The second post would generate an URL with `/brand/management/...`

---

At this point, we won't be able "fix" like you'd expect it to since there could be users out there who already have permalinks with `%20`, and the "fix" would end up changing URLs for them resulting in 404 errors for their readers.

**Comment by ashmaroli** [comment]
What we can do is have a new placeholder say `:slugified_categories`, that users could opt-into..
/cc @jekyll/core

**Comment by DirtyF** [comment]
@ashmaroli I can see this being a good solution for now, and then remove it in the next major version.

**Comment by Soundium** [comment]
> What we can do is have a new placeholder say `:slugified_categories`, that users could opt-into..
> /cc @jekyll/core

This could be a solution. Thank you for quick response. I appreciate it.

**Comment by ashmaroli** [comment]
@Soundium If your site is compatible with Jekyll 4.0, you can use the feature right away by editing your Gemfile:
```ruby
gem 'jekyll', github: 'jekyll/jekyll', ref: 'refs/pull/8094/head'
```

**Comment by Soundium** [comment]
> @Soundium If your site is compatible with Jekyll 4.0, you can use the feature right away by editing your Gemfile:
> 
> ```ruby
> gem 'jekyll', github: 'jekyll/jekyll', ref: 'refs/pull/8094/head'
> ```

Unfortunately I am on Github Pages. It seems to me I have to find another solution in meantime.

**Comment by DirtyF** [comment]
@Soundium you can use GitHub Actions to deploy on GitHub Pages, you can try https://github.com/helaili/jekyll-action (just updated by a GitHubber)

**Comment by Soundium** [comment]
@DirtyF thank you!

**Comment by melat0nin** [comment]
Is it feasible to do the same for multi-word tags? They exhibit the same problematic behaviour at present.

**Comment by ashmaroli** [comment]
> same problematic behaviour at present.

@melat0nin Could you clarify at bit more?
What version of Jekyll are you using?
And have you replaced `:categories` with `:slugified_categories` in your permalink template?
