### ISSUE TITLE
docs: deploy Jekyll with GitHub Actions

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#8095]
## Motivation

Allow Jekyll users to use latest Jekyll or jekyll plugins not supported by GitHub Pages

## Suggestion

Document how to use GitHub Actions to deploy a Jekyll v4 website using jekyll plugins written by the community.

**Comment by DirtyF** [comment]
We might dogfood here, as we would like to use GitHub Actions to deploy Jekyll website using latest Jekyll version.

**Comment by MichaelCurrin** [comment]
I've been thinking about using Actions recently to deploy Jekyll. And V4 or custom plugins sounds like a good motivation. Plus I read how to use Actions to add React to the build, so that applies here too. I could add a tutorial if you indicate what kind of custom plugin would be appropriate and what section of the site to add the doc?

**Comment by DirtyF** [comment]
I would add it here: https://jekyllrb.com/docs/deployment/automated/

1. first to deploy a Jekyll 4 website with https://github.com/helaili/jekyll-action
2. then test with a plugin like https://github.com/sverrirs/jekyll-paginate-v2

**Comment by MichaelCurrin** [comment]
Thanks for the info. Happy to take this one on. Might spread the work out through this week if I can't get it done in one evening.

**Comment by ashmaroli** [comment]
Sure @MichaelCurrin. Go ahead and take a stab at it.

**Comment by MichaelCurrin** [comment]
I managed to get Jekyll 4 setup on a personal repo using the recommended action.

I'll add the plugin next.

**Comment by ashmaroli** [comment]
@MichaelCurrin That's great news!
You don't have to use that plugin in particular. Any third-party plugin (not whiltelisted on GitHub Pages) (an better if it doesn't need much configuration) will do..

**Comment by MichaelCurrin** [comment]
I had issues with paginate plugin. Around config file and conflicting paginate versions.

I found `jekyll-timeago` much lighter and simpler.

I just finished my tempalte/demo site, so I have what I need to write the tutorial now. Do you mind if I link to it from the Jekyll tutorial?

https://michaelcurrin.github.io/jekyll-actions/

**Comment by DirtyF** [comment]
As long as the whole tutorial lives on Jekyll's website, feel free to link to your example.

**Comment by MichaelCurrin** [comment]
Great, thanks.

I am nearly done writing, going to make a PR soon.

I'm adding myself to the metadata as an author, though the frontend doesn't support that like for the blog posts.

**Comment by DirtyF** [comment]
@MichaelCurrin It does now: https://jekyllrb.com/tutorials/csv-to-table/ :)

**Comment by MichaelCurrin** [comment]
What I meant is that it works on blog posts and tutorials, but not in `/docs` files like the one I am doing.

**Comment by DirtyF** [comment]
yeah it's not about who's writing the docs, it's about collective intelligence to provide the best documetation to the community.

**Comment by MichaelCurrin** [comment]
Sure, fair enough. I took out the author data.

**Comment by MichaelCurrin** [comment]
I've added a PR so I can do a preview it and if you want to look so long. I am going to have another look over it tomorrow as well.

#8119
