### ISSUE TITLE
String in markdown incorrectly rendered as a tag by liquid reporting exception

### ISSUE THREAD

**Issue by kayoch1n** [jekyll/jekyll#8099]
I am using jekyll to develop my own github page. My post happens to contain following content:

    ```python
    # ...
    print('nctf{%s}' % ''.join([c for _, c in sorted(enumerate(s2), key=lambda t: indices[t[0]])]))
    ```

I think that the `{%s` of string enclosed in code block caused the problem and jekyll considered it as an openning tag for liquid with `bundle exec jekyll serve` complaining:

```
Configuration file: /home/ubuntu/kayoch1n.github.io/_config.yml
            Source: /home/ubuntu/kayoch1n.github.io
       Destination: /home/ubuntu/kayoch1n.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
  Liquid Exception: Liquid syntax error (line 389): Tag '{%' was not properly terminated with regexp: /\%\}/ in /home/ubuntu/kayoch1n.github.io/_posts/2020-03-26-cgctf-re.markdown
```

Anyone can see the host [here](https://github.com/kayoch1n/kayoch1n.github.io/commit/dfab6e053aff151342605073b08b7462b31a92a8#diff-0b41a1ef0570893180b3294b1ee08d34R394)

**Comment by ashmaroli** [comment]
Liquid parses everything including code-blocks.
If you want Liquid to not choke at instances of `{%`, `%}`, `{{` or `}}` in your code-blocks, enclose the codeblocks in `{% raw %}...{% endraw %}`:
<pre>
{% raw %}
```python
# ...
print('nctf{%s}' % ''.join([c for _, c in sorted(enumerate(s2), key=lambda t: indices[t[0]])]))
```
{% endraw %}
</pre>
