### ISSUE TITLE
`jekyll serve` – New changes should take effect

### ISSUE THREAD

**Issue by 4Luke4** [jekyll/jekyll#8103]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | macOS v10.15.4          |
| `jekyll`         | v3.8.6     |
| `github-pages`   | No     |

---

## Expected Behaviour
Upon refreshing the webpage, new changes should take effect.

## Current Behavior
Every time I make new changes to my local copy, the Terminal window clearly rebuilds the site, but if I refresh the webpage under consideration, new changes do not take effect.

## Code Sample
`jekyll serve --incremental`

**Comment by ashmaroli** [comment]
Incremental regeneration only rebuilds the page that was changed. For example, if you make changes to `about.md` then only `_site/about.html` (or `_site/about/index.html`) changes. Everything else remains unchanged.
Also note that if you have `{{ page.content }}` or `{{ post.content }}` in your layout, that particular object won't get updated.

**Comment by 4Luke4** [comment]
> Incremental regeneration only rebuilds the page that was changed. For example, if you make changes to `about.md` then only `_site/about.html` (or `_site/about/index.html`) changes. Everything else remains unchanged.
> Also note that if you have `{{ page.content }}` or `{{ post.content }}` in your layout, that particular object won't get updated.

OK, so what should I do exactly?

**Comment by ashmaroli** [comment]
@4Luke4 Is your repository public? Otherwise, please list the exact details of the steps that you followed and what theme and plugins are being used..

**Comment by 4Luke4** [comment]
> @4Luke4 Is your repository public?

Here you go => https://github.com/4Luke4/iesdp

**Comment by ashmaroli** [comment]
Okay. Now which page did you edit exactly?

**Comment by 4Luke4** [comment]
> Okay. Now which page did you edit exactly?

Any page located in `_opcodes`.

**Comment by ashmaroli** [comment]
The collection `opcodes` is not set to output. So it won't generate any pages to `_site` directory.
If you'd want the collection to output files, you must configure them:
```yaml
collections:
  opcodes:
    output: true

**Comment by ashmaroli** [comment]
Additionally, you also have a regular folder named `opcodes`. So the files will intermingle unless you set a different permalink for one of them..

**Comment by 4Luke4** [comment]
> The collection `opcodes` is not set to output. So it won't generate any pages to `_site` directory.
> If you'd want the collection to output files, you must configure them:
> 
> ```yaml
> collections:
>   opcodes:
>     output: true
> ```

That seems broken `yaml`...?

**Comment by ashmaroli** [comment]
How is that broken YAML?

**Comment by 4Luke4** [comment]
> How is that broken YAML?

Sorry, I missed indentation...

**Comment by ashmaroli** [comment]
And yes, you need to edit your `_config.yml`. Please refer https://jekyllrb.com/docs/collections/ for further details.

**Comment by 4Luke4** [comment]
It still doesn't work, I didn't understand what's the issue here

> Additionally, you also have a regular folder named opcodes. So the files will intermingle unless you set a different permalink for one of them..

**Comment by ashmaroli** [comment]
By default `_opcodes/hello.md` will output to `_site/opcodes/hello.html` and also `opcodes/hello.html` will output to `_site/opcodes/hello.html`. So, only one of the source files actually write to `_site`.

Coming back to your issue here. I checked and everything works as expected.
- Run `jekyll serve --incremental`
- Point browser to `http://localhost:4000/iesdp/opcodes/op007.html`
- Edit `_opcodes/op007.html`
- Wait for regeneration build to finish.
- Refresh ``http://localhost:4000/iesdp/opcodes/op007.html`` to see changes.

**Comment by 4Luke4** [comment]
> By default _opcodes/hello.md will output to _site/opcodes/hello.html and also opcodes/hello.html will output to _site/opcodes/hello.html. So, only one of the source files actually write to _site.

OK, so this is not actually an issue?

> Coming back to your issue here. I checked and everything works as expected.

- Run jekyll serve --incremental
- Point browser to http://localhost:4000/iesdp/opcodes/op007.html
- Edit _opcodes/op007.html
- Wait for regeneration build to finish.
- Refresh http://localhost:4000/iesdp/opcodes/op007.html to see changes.

I see. The point is that I usually refresh the entire thing, i.e., `http://localhost:4000/iesdp/`. Am I supposed to refresh one file at a time?
