### ISSUE TITLE
Jekyll reloading not stable

### ISSUE THREAD

**Issue by kad-beumer** [jekyll/jekyll#8105]
I have my Jekyll site running in a container in a Kubernetes pod. Allong with the Jekyll container there is another container in the same pod running Git-Sync to get the site content from my repository.

Despite running `--force_polling` refreshing when content changes are very instable. 

A change on my repository is visible on the containers filesystem but 9 out of 10 times a regeneration is not triggert

**Comment by DirtyF** [comment]
What command are you running?

I know that `jekyll serve` works fine in [Forestry's Instant Previews](https://forestry.io/docs/previews/instant-previews/) (Running a Ruby 2.6 Docker image).

**Comment by kad-beumer** [comment]
I'm runing jekyll serve:

`jekyll serve -s /usr/src/app/git-repo/ --config /conf/_config.yml --force_polling`

**Comment by DirtyF** [comment]
Closing as this does not look like a Jekyll core issue but a Kubernetes config problem.
