### ISSUE TITLE
"collections_dir" and post

### ISSUE THREAD

**Issue by bondbipu** [jekyll/jekyll#8110]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |            |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

 I have created a "collections_dir" setting in config file and I have created a 'collection' folder which contains the collections. After that my posts from the site disappeared. I expected that if the "_posts" folder in the root folder, I should be able to see post, even if the collections are in a sub folder.  

Here is my setup: 

├─ collections
│    └─ _poetry
├─ _posts
└─ _config.yml

## Current Behavior

 I can see the posts only when I transfer the "_post" folder in the specefic collection sub folder. Otherwise, I cannot see the posts on my site. 

## Code Sample

collections_dir: collection
collections:
  poetry:
    output: true
    permalink: /:collection/:title/

**Comment by DirtyF** [comment]
> if you set a custom location for your collections, please ensure you move all of your collections into that directory. This includes posts and drafts as well — https://jekyllrb.com/news/2018/01/25/jekyll-3-7-2-released/
