### ISSUE TITLE
bug: variables used in theme configuration are showing up when not overridden

### ISSUE THREAD

**Issue by ticoombs** [jekyll/jekyll#8114]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |    ruby v2.5.0 - Gentoo        |
| `jekyll`         |  4.0.0    |
| `github-pages`   | N/A     |

---

## Expected Behaviour

The information added under _config.yml was the only information jekyll used. 

## Current Behavior

Having default variables filled, under the theme configuration file, results in those items showing up, if the user does not override them with their own.

### Step 1. Update `Gemfile` to include jekyll v4, and minima latest master
```
gem "jekyll", ">= 4.0.0"
gem "minima", git: "https://github.com/jekyll/minima"
```
### Step 2. Update `_config.yml` with new minima settings:
```
 minima:
   social_links:
     mastodon:
       - username: myusernamehere
         instance: mastodon.social
```
### Step 3. 
```
rm Gemfile.lock
bundle install && bundle update 
bundle exec jekyll serve --watch
```
### Result: 
Github, & Twitter show up, even though we only specified Mastodon.

![image](https://user-images.githubusercontent.com/2687896/79094231-37091880-7d9a-11ea-8b61-473fd3894c69.png)

## Regression Testing:
This does not happen when used with `jekyll v3.8.6`

**Comment by ashmaroli** [comment]
This is rather unfortunate..
I wonder if
- we should make this feature opt-in (:man_shrugging:) or 
- just remove the feature entirely (if that's in accordance with Semver principles)..

**Comment by ashmaroli** [comment]
@ticoombs If you are willing, you can point your Gemfile to the `master` branch of this repository and edit your config file to disable importing theme configuration:
```ruby
# Gemfile

gem "jekyll", github: "jekyll/jekyll"
```
```yaml
# _config.yml

ignore_theme_config: true
```
