### ISSUE TITLE
Release Jekyll 4.1

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll#8115]
👋 It's time to release all the hard work we have been doing for Jekyll next minor release, we're getting closer: 

- [x]  [Focus on shipping last items](https://github.com/jekyll/jekyll/milestone/68)
- [x]  Require Ruby 2.5 (implicit)
- [x]  Write Release Post
- [x] Release 💎 🎉

**Comment by ashmaroli** [comment]
Should we backport some of the fixes to the `4.0-stable` branch and prep for a `v4.0.1` as well ..?

**Comment by DirtyF** [comment]
@ashmaroli If you can take a stab on it, it would be great, mainly for cache issues introduced in 4.0.

**Comment by rokon574** [comment]
Hi i want to buy this [theme from themeforest](https://themeforest.net/item/xavat-saas-corporate-and-business-jekyll-template/26147852) any on know that jekyll is updated with Jekyll 4.1 or not ?

**Comment by DirtyF** [comment]
@jekyll/core  We should be good now, @ashmaroli do you want to take a stab at summarizing the major useful enhancements and features for end-users in the release post?

**Comment by ashmaroli** [comment]
Resolved by https://github.com/jekyll/jekyll/commit/627e3bbe53db16d292d15e3d594d429673813fc1
