### ISSUE TITLE
Encoding::UndefinedConversionError: "\xC3" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by lsolesen** [jekyll/jekyll#8120]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |            |
| `jekyll`         | Latest     |

---

## Expected Behaviour

I would expect my site to build correctly using Github Actions also, as it builds correctly locally and on Travis CI.

## Current Behavior

I am trying to use Github Actions to build my site (https://github.com/lsolesen/larsolesen-dk-jekyll) with the latest Jekyll. However, I encounter the following error:

```
2020-04-14T06:13:01.2803271Z bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
2020-04-14T06:13:01.2806628Z Encoding::UndefinedConversionError: "\xC3" from ASCII-8BIT to UTF-8
```

Full log of the deploy action: https://gist.github.com/lsolesen/084c17e847fed182b591e1e96d0d2a83

However, it builds correctly locally and on Travis - https://travis-ci.org/github/lsolesen/larsolesen-dk-jekyll/jobs/674717849

Is there anything I am missing?

**Comment by ashmaroli** [comment]
Thank you for providing a detailed issue ticket.
Unfortunately, all I can see is Jekyll throwing up at some URL..

Did this start breaking recently.. after you switched to Jekyll 4.0.. or after you switched to `jekyll/jekyll:master`?
Have you tried if this issue reproduces with Jekyll 3.8 or Jekyll 3.7..?

Lastly, since it is URL issue, perhaps one of your pages / documents have an accented character that couldn't be transliterated (*just guessing..*). No guarantee, but you may find additional info by building under debug mode:
```
bundle exec jekyll build --verbose --trace
```

**Comment by lsolesen** [comment]
I now ran it with `--verbose`, but it is still not telling me (that I can see) which file it chokes on.

I've updated the log of the deploy action to reflect this:  https://gist.github.com/lsolesen/084c17e847fed182b591e1e96d0d2a83

I have not used Github Actions for building with 3.8 (there I just used github-pages), but I updated from 4.0.0 to 4@master to try to fix the issue. Then again, it builds correctly locally and on Travis. Only place it is not working is on Github Actions (where I need it to work :))

Isn't there a way to have jekyll telling which file creates the problem - as it is a little much to read through all of the blog posts to try to find a single character :)

**Comment by ashmaroli** [comment]
Yeah.. The verbose log doesn't yield anything..

We have a new proposal for deploying a Jekyll site through GitHub Actions: https://github.com/jekyll/jekyll/pull/8119

It is still under review and therefore can't really say it'll work..
Are you willing to give it a try..?

**Comment by lsolesen** [comment]
Trying to do the following:

    grep -P "[\xC3]" lunr-store.js

It doesn't find the character in question anywhere

**Comment by lsolesen** [comment]
@ashmaroli I tried the proposal. And it pretty much ends with the same error message :)

    /usr/local/bundle/bundler/gems/jekyll-561531eca6c6/lib/jekyll/url.rb:158:in `encode': "\\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

**Comment by lsolesen** [comment]
I tried building with jekyll 3.8.5 which also works locally, but fails on Github Actions with this: https://gist.github.com/lsolesen/74f54fd65dbb2b06abccde5d2e317bbc

```
2020-04-14T09:13:21.4775572Z [31m  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':[0m
2020-04-14T09:13:21.4776122Z jekyll 3.8.5 | Error:  Invalid US-ASCII character "\xE2" on line 54
2020-04-14T09:13:21.4777379Z [31m                    Invalid US-ASCII character "\xE2" on line 54[0m
2020-04-14T09:13:21.4778339Z /usr/local/bundle/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:123:in `rescue in convert': Invalid US-ASCII character "\\xE2" on line 54 (Jekyll::Converters::Scss::SyntaxError)
```

However that the failed US-ASCII character should be in the SCSS seems strange: https://github.com/lsolesen/larsolesen-dk-jekyll/blob/master/assets/css/main.scss

I have also looked through all of my posts in line 54 and I could not find any strange characters.

**Comment by ashmaroli** [comment]
When I build your site on a local Windows system, the error points to `sitemap.xml`. The build succeeds when I disable `jekyll-sitemap` in the config file. So, I don't think the issue is in your `assets/css/main.scss`

**Comment by lsolesen** [comment]
Tried it on another site and got the same error, so the culprit must be in the template somehow. https://github.com/lsolesen/cykel-ruter-dk-jekyll/tree/master

**Comment by lsolesen** [comment]
@ashmaroli Strange. I am building without any issues locally.

**Comment by ashmaroli** [comment]
You could try switching to a different remote theme.. say `jekyll/minima`..? :man_shrugging: :

**Comment by lsolesen** [comment]
However, it would still be nice, if jekyll was a little more precise on what the error actually is.

**Comment by lsolesen** [comment]
@ashmaroli It is not an option to switch theme. I am using too many features from mmistakes/minimal-mistakes

**Comment by ashmaroli** [comment]
The theme switching is just to test the minimal-mistakes theme. If it builds fine with another theme, we can loop in mmistakes for patches..

**Comment by ashmaroli** [comment]
The following is a temporary monkey-patch that modifies a Jekyll core class. You can paste the code into a `*.rb` file in a `_plugins` directory at the root of your site and have GitHub Actions build the site with Jekyll 4.0. Hopefully, it should tell (us) which file exactly.

If not, I'm out of ideas for the time being. Sorry.
 
```ruby
module Jekyll
  class URL
    def self.unescape_path(path)
      path = path.encode("utf-8")
      return path unless path.include?("%")

      Addressable::URI.unencode(path)
    rescue Exception => err
      Jekyll.logger.warn "URL Error:", path
      Jekyll.logger.warn "URL Error:", err
      raise err
    end
  end
end
```

**Comment by lsolesen** [comment]
@ashmaroli The name doesn't matter?

**Comment by ashmaroli** [comment]
No, it doesn't.

**Comment by lsolesen** [comment]
Strange - it is a PDF on one site.

```
         URL Error: /assets/pdf/Focus-Hvordan-foregår-motorisk-læring.pdf
         URL Error: "\xC3" from ASCII-8BIT to UTF-8
```

**Comment by ashmaroli** [comment]
The issue could be that the container in which GitHub Actions run doesn't have the correct codepage set in order to handle the accented characters here. You could either approach GitHub Support about a possible solution or if the filename doesn't matter, use latin equivalents of those characters.
For example, 
```
assets/pdf/Focus-Hvordan-foregar-motorisk-laering.pdf
```

**Comment by lsolesen** [comment]
Fixed based on the monkey-patch. Thanks.
