### ISSUE TITLE
confusing (and possibly conflicting) install instructions

### ISSUE THREAD

**Issue by antoinechoffrut** [jekyll/jekyll#8121]
[The quickstart page](https://jekyllrb.com/docs/#instructions) instructs to:

1. Install a full Ruby development environment.
2. Install jekyll and bundler gems with
  ```
  gem install jekyll bundler
  ```

On the other hand, the link in step 1. leads, **for the case of macOS, not the others**, to [instructions for a local install](https://jekyllrb.com/docs/installation/macos/#local-install) with
```
gem install --user-install bundler jekyll
```
Therefore, step 2. above is a repeat, and somewhat in conflict for macOS users.  

**Suggestion**
In the same spirit [as this other issue](https://github.com/jekyll/jekyll/issues/6800), remove step 2 as above, and modify step 1 with:  

"1. Install a full Ruby development environment (including jekyll and bundler gems)."  

with the same link as above.

I am a relatively new user and currently pulling my hair over problems building a website, and I wonder if I ran these two commands at different times (I cannot remember) and if that has caused my problems.  For example, `gem env` returns:  
```
USER INSTALLATION DIRECTORY: /Users/antoine/.gem/ruby/2.7.0
```
but this directory does **not** exist on my system.

**Comment by johnapaz** [comment]
I've used Jekyll before in the past, and I've never had this much trouble with setting up before. Something changed using bundler, and it's broken things for Mac users as it stands.

Despite installing, reinstalling, uninstalling, and downgrading my bundler versions it won't serve a website and insists I it's my ruby installation. Super frustrating.

**Comment by DirtyF** [comment]
Sorry for the confusion, installing Ruby is indeed a pain because using built-in Ruby for macOS comes with some restrictions (because of permissions). 

Storing your gems in your home folder will save you from having to run commands as root (always a bad idea). I'd recommend using `brew` to install Ruby as it will save you from permissions issues.

You're right those instructions are all mixed up and some options won't play well with others. For instance `--user-install` won't play nice with `rbenv`.

If you have trouble installing Jekyll, please reach out to the community's forum on https://talk.jekyllrb.com.

**Comment by ashmaroli** [comment]
> those instructions are all mixed up and some options won't play well with others.

@DirtyF Shouldn't we normalize the instructions in the docs then..?

**Comment by johnapaz** [comment]
I got things working last night be just not using bundler... 

Also, I'm a tech writer... I can help with docs if I know what needs to change.

**Comment by ajbozdar** [comment]
> Storing your gems in your home folder will save you from having to run commands as root (always a bad idea). I'd recommend using `brew` to install Ruby as it will save you from permissions issues.

Is it okay to install gems in ~/.gems or it must be ~/gems?

**Comment by MichaelCurrin** [comment]
@ajbozdar use `~/.gems` with the dot as that is where `gem install --user-install` installs to.

**Comment by MichaelCurrin** [comment]
Regarding OP question - my assumption is that `~/.gem` will be created after the first time one does a user gem install.

**Comment by MichaelCurrin** [comment]
It looks like a small change is needed

```diff
- gem install jekyll bundler
+ gem install jekyll bundler --user-install
```

The quickstart doesn't use `rbenv` which is okay. It doesn't have to be exhaustive so it doesn't have to cover `rbenv` flow, where `--user-install` won't work from the comment above.

**Comment by MichaelCurrin** [comment]
Just to throw something in - the Windows instructions _don't_ use the user flag and I don't know if Windows accepts the flag but hope it does

**Comment by DirtyF** [comment]
There's ongoing work for `--user-install` to become the default way to install Ruby gems. 
See: https://github.com/rubygems/rubygems/pull/2847

**Comment by MichaelCurrin** [comment]
Ah okay thanks.
