### ISSUE TITLE
Github sponsor button malfunctions

### ISSUE THREAD

**Issue by gwillem** [jekyll/jekyll#8127]
![image](https://user-images.githubusercontent.com/1145479/79543542-f2c59300-808d-11ea-9cf7-abf84dbf2634.png)

![image](https://user-images.githubusercontent.com/1145479/79543520-e4777700-808d-11ea-9ba2-c67acbaa6f55.png)

**Comment by DirtyF** [comment]
@gwillem Thanks for the feedback we'll look into it.
