### ISSUE TITLE
Text in {{}} removed in verbatim (```)

### ISSUE THREAD

**Issue by galvusdamor** [jekyll/jekyll#8129]
I've set up a github pages page (https://panda-planner-dev.github.io/pandaPIparser/) which contains a BibTeX entry (at the very bottom) as verbatim (in ```). This entry contains the text "{{AAAI Press}}". It renders fine at the main github page, but jekyll seems to remove it while rendering (it is not present in them generated html). I suspect that this should not be the case. Am I right?

**Comment by galvusdamor** [comment]
This issue may be fixed by adding {% raw %} around the verbatim/code environment (see https://stackoverflow.com/questions/24102498/escaping-double-curly-braces-inside-a-markdown-code-block-in-jekyll), but then the github markdown renderer does not understand those and just puts them into plain text.

**Comment by ashmaroli** [comment]
@galvusdamor That is the only way to tell Liquid not to parse any consequent `{{ }}` or `{% %}` until a `{% endraw %}` is encountered.
To not render as plain-text, add the language at the end of the triple-backticks. (e.g.<code>```ruby</code> to highlight Ruby code). The following are without and with highlighting respectively:
```
class Foo
  def bar
    'lorem ipsum'
  end
end
```
```ruby
class Foo
  def bar
    'lorem ipsum'
  end
end
```
