### ISSUE TITLE
feat: Add some official French government websites to the showcase

### ISSUE THREAD

**Issue by MattiSG** [jekyll/jekyll#8130]
## Summary

I have built the following government websites with Jekyll, and I believe using such “official” demonstrations could be useful to show the power of the software:

- [pariscall.international](https://pariscall.international), the public website for the Paris Call for Trust and Security in Cyberspace, which uses Jekyll to maintain a [list of signatories](https://github.com/ambanum/pariscall.international/tree/master/_supporters) and relies on an additional [backend](https://github.com/ambanum/pariscall.international-backend) to [create files](https://github.com/ambanum/pariscall.international/commits?author=AmbNum-Bot) from survey answers, making it easy for anyone to add files and for non-technical maintainers to update the data over time.
- [beta.gouv.fr](https://beta.gouv.fr), the website of the French government public digital services incubator, which uses Jekyll both as CMS and HR system and has [over 370 contributors](https://github.com/betagouv/beta.gouv.fr/) of all sorts.
- [disinfo.quaidorsay.fr](https://disinfo.quaidorsay.fr), a resource supporting actors countering information manipulation (aka “fake news”), which uses Jekyll for a [multilingual](https://github.com/ambanum/disinfo.quaidorsay.fr/tree/master/_pages), [collaborative encyclopedia](https://github.com/ambanum/disinfo.quaidorsay.fr/tree/master/_pages/en/encyclopedia) of tools and practices.

## Motivation

European government entities are underrepresented in the showcase, making it harder to convince decision-makers of the appropriateness of this technical choice.

## Guide-level explanation

N/A

## Reference-level explanation

Add to `docs/_data/showcase.yml`.

This is not a PR simply because I preferred to get feedback beforehand.

## Drawbacks

The showcase page is already quite full.

## Unresolved Questions

Which example(s) would be most appropriate to feature?

**Comment by DirtyF** [comment]
EN: 👋 @MattiSG Nice to see Jekyll being used by french public administrations. Which one would be the most relevant to _you_? 

FR: J'avais hésité à ajouter beta.gouv.fr à l'époque, c'est le site qui me semble avoir le plus grand potentiel d'influence sur des décideurs non? Comme tu le sens, tu peux considérer la PR comme mergée 😉

**Comment by MattiSG** [comment]
Thanks @DirtyF for the fast and encouraging reply 😃

I believe I ordered the websites by order of relevance for this specific context, taking into account international reach, technical achievement (= how much it is more than just a basic Jekyll instance) and how appealing the topic is to the wider dev community who is the main audience here.

So I'll say that my ordered list is:

1. pariscall.international
2. beta.gouv.fr
3. disinfo.quaidorsay.fr

…and I'll let you tell me where to draw the line before I open that PR :wink:

**Comment by DirtyF** [comment]
@MattiSG 👌 showcase updated with the first two listed.

https://jekyllrb.com/showcase/

<img width="878" alt="french-gov-showcase" src="https://user-images.githubusercontent.com/103008/81472160-645cb100-91f6-11ea-98dd-1d246148489f.png">

**Comment by MattiSG** [comment]
Thanks Frank, I’m thrilled we made it there! 🙂
