### ISSUE TITLE
jekyll -v , zsh: command not found: jekyll

### ISSUE THREAD

**Issue by samwangdd** [jekyll/jekyll#8134]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      macOS Mojave 10.14.5      |
| `jekyll`         | 4.0.0     |
| `github-pages`   | Latest     |

---

## Expected Behaviour
Expect jekyll to run normally

## Current Behavior
I have installed jekyll, but when I used `jekyll -v`:
![屏幕快照 2020-04-24 下午3 14 05](https://user-images.githubusercontent.com/29837369/80185079-5461a080-863e-11ea-90c6-007386469b8b.png)

## Code Sample
This my `~/.zshrc` configuration:
![屏幕快照 2020-04-24 下午3 17 09](https://user-images.githubusercontent.com/29837369/80185325-bf12dc00-863e-11ea-95cd-e38e4b85826a.png)

I don't know why it's does't work!😂

**Comment by pranabdas** [comment]
Maybe you just need to restart your Terminal?  🤔

**Comment by DirtyF** [comment]
Looks like a setup issue on your end.

```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76

gem install jekyll
...
Successfully installed jekyll-4.0.1
1 gem installed

jekyll -v
jekyll 4.0.1
```

Please check our documentation and reach out to the community on [our forum ](https://talk.jekyllrb.com) if you need more help.
