### ISSUE TITLE
The created Gemfile (jekyll new) should use platforms instead if install_if

### ISSUE THREAD

**Issue by dleidert** [jekyll/jekyll#8139]
Hi there,

I'm part of the Debian maintainers for Jekyll running Debian Linux. When I run `jekyll new foo/ --skip-bundle`, move into the created directory and run `jekyll b` I get an error that the gems, which are for Win/MingW/JRuby platforms (tz* and wdm) cannot be found although they are not even necessary on my platform. I had a discussions with bundler's upstream author in <https://lists.debian.org/debian-ruby/2020/04/msg00062.html> about it and it seems better suited to replace the `install_if` by `platforms` in the created `Gemfile`. I propose the patch in <https://salsa.debian.org/ruby-team/jekyll/-/blob/master/debian/patches/0024-use-platforms-in-default-gemfile.patch>.

**Comment by ashmaroli** [comment]
Thank you for attaching a PR and a link to the discussion with one of the maintainers of Bundler.
