### ISSUE TITLE
Jekyll-auth doesn't spin up the server - git docs

### ISSUE THREAD

**Issue by Gabiabi** [jekyll/jekyll#8148]
Hey, I have a problem. I want to host a Jekyll-auth on a local server without usage of Cloud hosting. I'm using git docs, bundler and Jekyll-auth 2.1.1. 
I run Jekyll-instance by running 
**_sudo bundle exec jekyll-auth serve --host=tek-ffu-h0a.tek.sdu.dk_**

and it is stuck on "spinning up the server...". When I'm hosting it without authentication everything works. I have my git credentials defined in .env file (client_id, secret key and team_id). When I'm trying to access the website Git Log In page appears. I log in with my credential and it says accused denied or safari/chrome can't make secure connection. 

I'm thinking perhaps it is the issue of certificates?Has anyone encountered such problem? 

<img width="582" alt="Screenshot 2020-04-29 at 17 06 39" src="https://user-images.githubusercontent.com/56154564/80612517-5d86af00-8a3c-11ea-9253-11ff1cd53358.png">
<img width="530" alt="Screenshot 2020-04-29 at 17 06 54" src="https://user-images.githubusercontent.com/56154564/80612529-60819f80-8a3c-11ea-9238-ec225e779ae9.png">

**Comment by ashmaroli** [comment]
@Gabiabi Sorry, this is the repository for Jekyll core.
You may want to take this issue up with the folks at the dedicated repository for `jekyll-auth` plugin.

**Comment by Gabiabi** [comment]
But there is none....

**Comment by ashmaroli** [comment]
The repository link can be gauged by referring to the gem's page at https://rubygems.org/gems/jekyll-auth

**Comment by Gabiabi** [comment]
Thank you
