### ISSUE TITLE
Unable to install Jekyll in Ubuntu 16.04

### ISSUE THREAD

**Issue by aashish-ak** [jekyll/jekyll#8151]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     Ubuntu 16.04       |
| `Ruby`         | 2.7.1     |
| `Shell`         | Fish     |

---

Unable to install Jekyll Gem in Ubuntu 16.04 using Fish Shell. On running the `gem install jekyll` it throws following error. Ruby was installed using Snap :-

![ruby](https://user-images.githubusercontent.com/21988675/80739320-db79b180-8b33-11ea-888b-5848a52940fb.png)

**Comment by DirtyF** [comment]
Hi, Jekyll should install fine on Ubuntu.

Please follow our documentation if you haven't https://jekyllrb.com/docs/installation/ubuntu/
If you need more help, reach out to the community [on our forum](https://talk.jekyllrb.com)
