### ISSUE TITLE
Space added to data when using {% capture %}

### ISSUE THREAD

**Issue by splotsh** [jekyll/jekyll#8157]
Been wondering why my comparison operators did not seem to be working when passing data from a layout to an included file.

As per Jekyll's documentation, the recommendation is to use {% capture %} to make page level frontmatter available to be passed to included pages. I have the following:

{% capture product_type %}
{{ page.product_type }}
{% endcapture %}

{{ product_type }} returns the data with a whitespace at the end - is this expected behaviour ?  A patch I'm using here is {{ product_type | strip }}.

**Comment by DirtyF** [comment]
Did you check product_type didn't have any space? I'm surprised this would surface only now.

**Comment by splotsh** [comment]
Absolutely. Tried this again just now:

<h1>s{{ page.product_type }}s</h1>
{% capture product_type %}
{{ page.product_type }}
{% endcapture %}
<h1>s{{ product_type }}s</h1>

And the second one has a space before and after the product_type data. Am I missing something here ?

**Comment by ashmaroli** [comment]
Hello @splotsh, what you're missing here is that `{% capture %}` registers all whitespace including line-breaks.
So there is a difference between the following:
```
{% capture product_type %}{{ page.product_type }}{% endcapture %}
```
```
{% capture product_type %}
    {{ page.product_type }}
{% endcapture %}
```
You can *visualize* this difference by using the `inspect` filter in your template:
```html
<pre>{{ product_type | inspect }}</pre>
```

The solution would be to either make use of the `strip` filter or Liquid's whitespace control feature.
