### ISSUE TITLE
Assigned variables in included files are changed the parent's variables

### ISSUE THREAD

**Issue by FarhanMS123** [jekyll/jekyll#8159]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Win10      |
| `jekyll`         | 3.8.5     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

Well, I don't really think this is a bug from Jekyll or Liquid. Or, maybe a feature of it. Otherwise, while I `include` a file that `assign` a variable, I expect that I cannot access the variable in parent file, but it doesn't.

## Current Behavior

It makes the parent file can access the variable that included file assign, where I don't want that.

## Code Sample

index.html
```
---
---
{% include test1.html %}
{{ var_from_test1 }}
```

_includes/test1.html
```
{% assign var_from_test1="data from test1.html" %}
```

I expect `index.html` wouldn't show anything (I mean `{{ var_from_test1 }}` wouldn't return a value from test1.html). But, It shows.

## The Question
How can I assign a local variables without impact the parent variable?

**Comment by ashmaroli** [comment]
Have you tried testing with Jekyll 4.0 and then the `master` branch of this repository?
You can edit your Gemfile to suit the test environments:
```ruby
# in Gemfile
# To test with Jekyll 4.0
gem "jekyll", "~> 4.0"
```
```ruby
# in Gemfile
# To test with the remote repository
gem "jekyll", github: "jekyll/jekyll"
```
While testing, do note that you may have to explicitly list any plugins used by your site, in the Gemfile as well.

**Comment by ashmaroli** [comment]
> How can I assign a local variables without impact the parent variable?

Currently, you can reassign the variable to `nil` or `false` to reset them or stash a previous value and reassign that value at the end.
The following examples are all within the (child) *included file*:
```js
{% assign var_from_test1 = "data from test1.html" %}
// render markup with `var_from_test1`
....

// reset variable
{% assign var_from_test1 = nil %}
```

```js
{% assign var_from_test1 = "data from test1.html" %}
// render markup with `var_from_test1`
....

// reset variable
{% assign var_from_test1 = false %}
```

```js
// store original value in temp variable
{% assign original_var_from_context = var_from_test1 %}

{% assign var_from_test1="data from test1.html" %}
// render markup with `var_from_test1`
....

// reassign original value
{% assign var_from_test1 = original_var_from_context %}

// reset temp variable
{% assign original_var_from_context = nil %}
```

**Comment by FarhanMS123** [comment]
> > How can I assign a local variables without impact the parent variable?
> 
> Currently, you can reassign the variable to `nil` or `false` to reset them or stash a previous value and reassign that value at the end.
> The following examples are all within the (child) _included file_:
> 
> ```js
> {% assign var_from_test1 = "data from test1.html" %}
> // render markup with `var_from_test1`
> ....
> 
> // reset variable
> {% assign var_from_test1 = nil %}
> ```
> 
> ```js
> {% assign var_from_test1 = "data from test1.html" %}
> // render markup with `var_from_test1`
> ....
> 
> // reset variable
> {% assign var_from_test1 = false %}
> ```
> 
> ```js
> // store original value in temp variable
> {% assign original_var_from_context = var_from_test1 %}
> 
> {% assign var_from_test1="data from test1.html" %}
> // render markup with `var_from_test1`
> ....
> 
> // reassign original value
> {% assign var_from_test1 = original_var_from_context %}
> 
> // reset temp variable
> {% assign original_var_from_context = nil %}
> ```

oh well, I fixed it.
But, I am still curious. Is there a way to assign variable as a local variable?

**Comment by ashmaroli** [comment]
> oh well, I fixed it.

Was it using one of the examples I posted above or was there another way I didn't think about?

> Is there a way to assign variable as a local variable?

Actually, I don't think Liquid has the means to assign with limited scope.

**Comment by FarhanMS123** [comment]
> > oh well, I fixed it.
> 
> Was it using one of the examples I posted above or was there another way I didn't think about?

well yes. I just changed a little bit. I just assign new variable as temporary variable. And then at the end of the script, I just assign it back.
But, still. If in the middle I include a file that assign that temporary variable with new value, It would become useless. So... I cannot really fix my issue. :/

**Comment by ashmaroli** [comment]
> If in the middle I include a file that assign the temporary variable...

The solution currently is to employ the *assign-reassign* strategy in all of your includes. So that, the behavior is consistent.

You may also want to seek counsel at [Liquid's repository](https://github.com/Shopify/liquid).
