### ISSUE TITLE
{{ post.exceprt }} not being generated for all posts in a loop (with category)

### ISSUE THREAD

**Issue by jstride** [jekyll/jekyll#8161]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Ubuntu |
| `jekyll`         | 4.0.0 |
| `github-pages`   | No |

---

## Expected Behaviour

When using {{ post.excerpts }} all posts longer than a paragraph generate a single paragraph as the value.

## Current Behavior

Some posts have the first paragraph as an excerpt, whilst others don’t. I don’t have excerpt_generator set in my config file.

This [post ](https://gist.github.com/jstride/53e05812a8ff116325ffac647a957a36) generates an excerpt, [this ](https://gist.github.com/jstride/ae097bb06dd1583c08003aa039f98abb) doesn’t 

## Code Sample

[Code Sample](https://gist.github.com/jstride/13b05de85dd819b6d3a435087d42bc1b)

**Comment by ashmaroli** [comment]
@jstride I wasn't able to reproduce this issue by using the given documents. Perhaps there has been some misunderstanding at your end..?
Could you generate a new barebones site by running `jekyll new <whatever>`, place those two posts in there along with the page that loops through the posts and then try building..?
If you're still able to reproduce the behavior, please push the test repository as it is to GitHub so that I can clone the repo as you see it.

**Comment by candywater** [comment]
@jstride thanks for your issue, I have the same issue.
@ashmaroli  @DirtyF  

Software | Version(s)
-- | --
Operating System | Kali linux 2019.3(WSL)
jekyll | 4.0.1
github-pages | No

here is my example
https://gist.github.com/candywater/e39aca8d5327704070d998602062de80

I do not know what {{post.exceprt}}  should output.
but output from it seems can change when environment changes.

in my example
follwing files had been outputed all lines
 - _posts/2020-4-1-1.md
 - _posts/2020-4-1-2.md
 - _posts/2020-4-1-3.md
 - _posts/2020-4-1-4.md

follwing files had been outputed only first paragraph 
 - _posts/2020-05-27-welcome-to-jekyll.markdown
 
ps: in my blog site. 
**_posts/2020-4-1-3.md** has outputed only first paragraph, 
**_posts/2020-4-1-4.md** has outputed all lines.

**Comment by DirtyF** [comment]
Are those filenames supposed to be a date? YYYY-MM-DD is a requirement

**Comment by candywater** [comment]
> 
> 
> Are those filenames supposed to be a date? YYYY-MM-DD is a requirement

thanks for rapid repling.
I have changed files name from "yyyy-m-d-[0-9].md" to "yyyy-mm-dd-[0-9].md" 
eg "2020-4-1-3.md" to "2020-04-01-3.md"

I got the same result

**Comment by ashmaroli** [comment]
@candywater Please place those files in a repository and push that to GitHub. That'll give us the exact same file tree you're using.

**Comment by candywater** [comment]
> 
> 
> @candywater Please place those files in a repository and push that to GitHub. That'll give us the exact same file tree you're using.

I have upload a git repo.
https://github.com/candywater/jekyll_issue

I hope we can get the same situation.

**Comment by ashmaroli** [comment]
@candywater I'm rendering your repo now. Can you tell me what you mean by *but output from it seems can change when environment changes.*

**Comment by candywater** [comment]
> 
> 
> @candywater I'm rendering your repo now. Can you tell me what you mean by _but output from it seems can change when environment changes._

-  2020-02-09-loadbalance.md
    the output of it can change in different environment (same PC&jekyll, different jekyll setting)
  + my blog
![](https://github.com/candywater/jekyll_issue/raw/master/example/myblog_1.png)
  + testsite
![](https://github.com/candywater/jekyll_issue/raw/master/example/testsite_1.png)

-  2019-3-31-linux-service.md
  the output of it do not change.
  + my blog
![](https://github.com/candywater/jekyll_issue/raw/master/example/myblog_2.png)
  + testsite
![](https://github.com/candywater/jekyll_issue/raw/master/example/testsite_2.png)

same code
```
{{ post.excerpt | normalize_whitespace  | escape }}
```

**Comment by ashmaroli** [comment]
@DirtyF Are you able to reproduce the issue with given test-site?

@candywater Sorry, I'm still not able to reproduce your `testsite` results above with Jekyll 3.8 and 4.0.1
Can you set up GitHub Pages build on the test-site?
Irrespective of that, you can remove all that HTML tags in your excerpt string if you remove the `escape` filter:
```
{{ post.excerpt | normalize_whitespace }}
```

**Comment by candywater** [comment]
@ashmaroli  
I'm surprised that Github Pages cannot reproduce my case.
https://candywater.github.io/jekyll_issue/
maybe this is an issue only occurs in WSL of windows?

**Comment by ashmaroli** [comment]
@candywater GitHub Pages uses Jekyll v3.8.7.
You can edit your Gemfile to use that version to build. If the issue is still reproducible with that version,  its probably WSL/Windows..
But I really don't see how WSL could be the reason.
