### ISSUE TITLE
Recent post is not appearing at the top (Even though its generated)

### ISSUE THREAD

**Issue by madhur** [jekyll/jekyll#8186]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Mac OS  10.14.6          |
| `jekyll`         | 4.0.1     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

When I create a post in my _posts directory. It should appear in the top of the list.

## Current Behavior

The current behaviour is that it does not appear on the home page. Though, it appears on other pages.

## Code Sample

This is my live site: https://madhur.co.in

If you go to homepage, latest post is shown as https://www.madhur.co.in/blog/2020/05/09/unit-testing-http-retry-strategies.html.

However, I created the new post on 16th May, it got generated too https://www.madhur.co.in/blog/2020/05/16/http-timeouts.html

But, why it isn't appearing on the homepage.

My homepage list is generated as :

```
{% for post in site.posts limit:5%}<h4><a href="{{ post.url }}">{{ post.title }}</a></h4><time datetime="{{ post.date }}" pubdate="pubdate" class="date">{{ post.date | date_to_string  }}</time>{% endfor %}
```

The source of my site is available at: https://github.com/madhur/madhur.github.com/tree/source

**Comment by ashmaroli** [comment]
I see a `.jekyll-metadata` file in the `source` branch. So you built your site with `--incremental` flag.
When you build *incrementally*, only parts of your site are regenerated.

If you delete the metadata file and do a complete build, the post may show up.

**Comment by DirtyF** [comment]
Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage.
