### ISSUE TITLE
Permalink for page over Tor not working

### ISSUE THREAD

**Issue by karan** [jekyll/jekyll#8189]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     MacOS 10.15.4       |
| `jekyll`         | Latest     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

Generate a page such as `_page/keys.md` that has a permalink. For eg:

```
---
layout: page
title:  "Keys"
slug:    keys
permalink: keys
---

Main key: Some content
```

This should be then generated as for example `_site/keys.html`.

This works fine over HTTP/HTTPS using Github Pages, or nginx in front. However, if I throw a tor relay in front of the nginx, the permalink doesn't seem to work.

Permalink for posts is fine because posts are `index.html` files in their own directories.

## Current Behavior

Clearnet: `domain.com/keys` and `domain.com/keys.html` both work.

Tor: `domain.onion/keys` does not work. `domain.onion/keys.html` works.

## Code Sample

```
# _config.yml (trimmed)
...
permalink: /:title/

# Build settings
markdown: kramdown
highlighter: rouge

# Include these directories in the site
include: ['_pages']

# Hide draft posts from live blog
show_drafts: false

# Hide future dated posts from live blog
future: false
```

**Comment by karan** [comment]
Should've read https://jekyllrb.com/docs/permalinks/#pages.

**Comment by karan** [comment]
That doesn't fix it. The way I read the aforementioned doc page was that if `_config.yml` has a `permalink` format defined, then the page's individual `permalink` won't be honored. But that does not seem to be the case here.

**Comment by ashmaroli** [comment]
This is a webserver issue if you want `/keys` to equal `/keys.html`. Perhaps Tor documentation has something about it.
On Jekyll side, configure permalink to be `/keys.html` explicitly.

**Comment by karan** [comment]
I don't agree - I would expect the page to be built as `/keys/index.html` just like posts are.

**Comment by ashmaroli** [comment]
@karan Perhaps you have misunderstood the documentation. The following table will shed some additional light on `permalinks`:
Front Matter | Result
--- | ---
`permalink: /keys` | `_site/keys`
`permalink: /keys.html` | `_site/keys.html`
`permalink: /keys/` | `_site/keys/index.html`

As I understand your opening comment, using Clearnet gives you the desired outcome but Tor doesn't. So, it looks like Tor hasn't been configured enough.

Regarding parity with posts, you should understand that *pages* and *posts* (or *documents* in a collection under `_posts`) have different behaviors. In the same light, processing contents of the directory `_pages` will be different in the following two scenarios:
```yaml
include: [_pages]
```
```yaml
collections:
  pages:
    output: true
```
