### ISSUE TITLE
Blockquote Parsing

### ISSUE THREAD

**Issue by thromeaway** [jekyll/jekyll#8197]
It seems like Blockquotes arent parsed correctly in jekyll. I have to put `</blockquote>` in a new line as it turns out as `&lt;/blockquote&gt;` elsewise. The other Tags around it like` <p>` and` </p> `get parsed correctly. Im not using any Plugins except defaults.

**Comment by ashmaroli** [comment]
Jekyll doesn't parse blockquotes or any HTML element for that matter. It delegates that task to the [`kramdown`](https://github.com/gettalong/kramdown) library.
