### ISSUE TITLE
feat: Provide jekyll as an independent binary

### ISSUE THREAD

**Issue by AdityaAnand1** [jekyll/jekyll#8205]
<Slightly rant-y> Installing ruby is kind of a shitty experience every single time and it somehow always ends up leaving random files all over your system that you end up finding years later.

But I love jekyll. Surely, there must be a way to provide the jekyll binary as a single executable file? Perhaps even wrap it in a node package and ship it via npmjs to be installed as a global command line application?

**Comment by ashmaroli** [comment]
Jekyll Core is pure Ruby. Some of its dependencies however have some code written in C too.

If you can come up with an efficient way to convert all that Ruby code into JavaScript or TypeScript with no change in behavior, then you're welcome to ship Jekyll as a Node package or even over-engineer into a native OS application.

We're only concerned about shipping Jekyll as a Ruby gem.
