### ISSUE TITLE
production php, develop html

### ISSUE THREAD

**Issue by fab1an2** [jekyll/jekyll#8206]
I have trouble with permalink

My site generates fine in html, how convert _config.yml to generate all file with extension .php ? I develop site in html but server can use only php file.
I create line in _config-php.yml
`output_ext: "php"`
and generate site 
`jekyll b --config _config-php.yml `
and noting hapened. I still get .html extension. Who can help me?

**Comment by texrg** [comment]
output_ext not working in jekyll

**Comment by sp00ck** [comment]
any idea?
