### ISSUE TITLE
Why Jekyll auto creating `_site/assets/css/style.css` ??

### ISSUE THREAD

**Issue by MilanAryal** [jekyll/jekyll#8215]
When I compiled a site a `style.css` file is auto created inside `_site/assets/css/` path. To confirm this issue I several checked over Jekyll generated sites as follows and its everywhere:

https://jekyllrb.com/assets/css/style.css
https://byparker.com/assets/css/style.css
https://markdotto.com/assets/css/style.css
https://milanaryal.com.np/assets/css/style.css

**Comment by DirtyF** [comment]
Please head over to [our forum ](https://talk.jekyllrb.com) if you have questions on Jekyll.
