### ISSUE TITLE
page.excerpt behaviour changed between 4.0.1 and 4.1.0

### ISSUE THREAD

**Issue by seth-reeser** [jekyll/jekyll#8216]
Hello, version 4.1.0 introduced an unexpected change in behaviour for `page.excerpt` per [pull request 7642](https://github.com/jekyll/jekyll/pull/7642).

I was using page.excerpt as a meta description entry:

`<meta name="description" content="{% if page.excerpt %}{{ page.excerpt | strip_html | strip_newlines | truncate: 160 }}{% else %}{{ site.description }}{% endif %}">`

In an example of an excerpt not being defined for a page, this would have evaluated to the site.description, but now I'm getting markup generated for me that breaks because of HTML being included.

I would recommend the new implementation approach things similarly by stripping html, stripping newlines, and even maybe truncating.

**Comment by ashmaroli** [comment]
Is your site public @seth-reeser ? If yes, please provide us with a link to it.

**Comment by seth-reeser** [comment]
@ashmaroli, unfortunately I cannot share the website publically, but here's another example. The below snippet loops through each Jekyll page and generates a `search.json` file for consumption by a custom search mechanism:

<img width="1061" alt="Screen Shot 2020-05-28 at 2 44 41 PM" src="https://user-images.githubusercontent.com/6510351/83180821-fbc86c00-a0f1-11ea-8c67-dd24437e49c1.png">

Given a page, in this example, a "Terms of Use" page that has no `page.excerpt` defined in it's markup; I would expect `page.excerpt` to be blank, but now it is not, nor a value that I want. I would expect this to be an issue for others as well.

Before (Jekyll 4.0.1):

![Screen Shot 2020-05-28 at 2 48 27 PM](https://user-images.githubusercontent.com/6510351/83181036-4f3aba00-a0f2-11ea-8da6-d8738daa496b.png)

After (Jekyll 4.1.0):

![Screen Shot 2020-05-28 at 2 47 11 PM](https://user-images.githubusercontent.com/6510351/83180921-27e3ed00-a0f2-11ea-8380-b0bbfd8a7ffc.png)

**Comment by ashmaroli** [comment]
The reason I asked for a link to your website is so that I could see how exactly `{{ page.excerpt | strip_html }}` resulting in rendering HTML tags.
From your comments, I'm guessing that you do not have posts or collections in your site.

As a workaround to get to the old behavior, you can disable `excerpts` for *all pages* by setting front matter `excerpt_separator: ""`. If you too many *pages* that you can't manually modify, you could use front-matter-defaults instead:
```yaml
# _config.yml

defaults:
  - scope:
      path: ""
      type: pages
    values:
      excerpt_separator: ""
```

**Comment by seth-reeser** [comment]
Here's before and after for the original meta description example. Keep in mind for this example, that there was no `page.excerpt` set for the page in question. So the fallback was `site.description`.

Before (Jekyll 4.0.1) `site.description` fallback:
![Screen Shot 2020-05-28 at 5 45 32 PM](https://user-images.githubusercontent.com/6510351/83197212-24109480-a10b-11ea-8b0d-9ae1bf8e955c.png)

After (Jekyll 4.1.0) page content chosen for me by the new `page.excerpt` logic:
<img width="518" alt="Screen Shot 2020-05-28 at 5 43 24 PM" src="https://user-images.githubusercontent.com/6510351/83197202-1eb34a00-a10b-11ea-8075-23bdb0f57c2a.png">

Thank you for the `excerpt_separator` trick and agree that I can programmatically solve this issue - but I could forsee this be a breaking change for many others.
