### ISSUE TITLE
layout: is replaced with layout: default with new version 4.1.0 

### ISSUE THREAD

**Issue by lukas-h** [jekyll/jekyll#8217]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | macOs Catalina |
| `jekyll`         | Latest |
| `github-pages`   | No |

---

## Expected Behaviour

I used `layout: ` and it had the same behaviour as `layout: null`/`layout: none`. 

(I use it for my generated sitemap.xml or JSON files) 

## Current Behavior

Now `layout: ` has the same effect as `layout: default`

## Code Sample

```
---
layout:
---
```

**Comment by ashmaroli** [comment]
Is there a public repository that I can clone and look into..?
If not, are you using any plugins? Or better yet, please post the contents of your `Gemfile` (if present) and config file(s).

**Comment by lukas-h** [comment]
I'll try to recreate it.

**Comment by ashmaroli** [comment]
Any update on this ticket, @lukas-h ?

**Comment by lukas-h** [comment]
@ashmaroli @DirtyF 
sorry for the delay.

But I finished testing 4.0.1 against 4.1.0:

-> Since 4.1.0 jekyll overwrites the `layout: ` property of a file in favor of the layout set in _config.yml's defaults.

example: 

*_config.yml*

https://github.com/lukas-h/jekyll_layout_test/blob/d4185b68fb10fe70056c711ed4c2533097689b96/jekyll-4.1.0/_config.yml#L14

*index.html*

https://github.com/lukas-h/jekyll_layout_test/blob/d4185b68fb10fe70056c711ed4c2533097689b96/jekyll-4.1.0/index.html#L2

---

*_site/index.html* with v. 4.0.1

https://github.com/lukas-h/jekyll_layout_test/blob/master/jekyll-4.0.1/_site/index.html#L1

*_site/index.html* with v. 4.1.0

https://github.com/lukas-h/jekyll_layout_test/blob/master/jekyll-4.1.0/_site/index.html#L1

---

My question:
Is this intended?

**Comment by ashmaroli** [comment]
@lukas-h I see the issue now. The change in behavior was unintended.

That said, the current behavior is the reason why Jekyll also accepts front matter `layout: none`. It is more robust than `layout: `  &nbsp; or `layout: null` in conjunction with front matter defaults.

(*`layout: none` is a valid setting for pages since v3.7.0 and for documents in a collection since v3.5.0*. When set, Jekyll will *not look* for a layout named `none.html` and *will render as if not layout was specifiedfor the current page/document.*)

My personal opinion is that the current behavior is the better behavior moving forwards.

**Comment by ashmaroli** [comment]
@lukas-h I rebuilt the site using the latest `master` (it is a couple of commits ahead of v4.1.0) and it looks like the behavior from v4.0.1 has been restored. Could you verify by editing your Gemfile:
```ruby
gem 'jekyll', github: 'jekyll/jekyll', branch: 'master'
```

**Comment by lukas-h** [comment]
> That said, the current behavior is the reason why Jekyll also accepts front matter layout: none. It is more robust than layout:   or layout: null in conjunction with front matter defaults.

It was a (kind of) legacy project that has not been changed for long. I incorporated `layout: none` as a fix already.
Thank you very much for the help

**Comment by lukas-h** [comment]
> @lukas-h I rebuilt the site using the latest `master` (it is a couple of commits ahead of v4.1.0) and it looks like the behavior from v4.0.1 has been restored. Could you verify by editing your Gemfile:

I can verify that

https://github.com/lukas-h/jekyll_layout_test/blob/1a273ef46b4adf5b0dc29a5dbbed8be965b510c5/jekyll-upstream/_site/index.html#L1

**Comment by ashmaroli** [comment]
Perfect! This ticket can be closed, then?
Thank you for the test samples and results, @lukas-h
