### ISSUE TITLE
4.1.0: Liquid Exception: stack level too deep

### ISSUE THREAD

**Issue by fileformat** [jekyll/jekyll#8219]
I have a Jekyll site with a lot of files.  I'm getting the error:
`Liquid Exception: stack level too deep in report/all-ar21.html/#excerpt`

I'm pretty sure the page is valid Liquid: it does work with Jekyll 4.0.1 and earlier.  

I do have some plugins, but I'm not doing anything fancy.  The only standard plugin is the latest `jekyll-redirect-from`.

I'm not using excerpts, so I tried to disable them, but that didn't help.  I also tried removing that page, but it just shifted the error to a different page.

The [repository](https://github.com/VectorLogoZone/vectorlogozone) is public, and I'm using [TravisCI](https://github.com/VectorLogoZone/vectorlogozone), so you can see exactly what I'm doing.

## My Environment

TravisCI
| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  Ubuntu 18.04.4 LTS          |
| `jekyll`         | 4.1.0     |
| `github-pages`   | n/a     |

---

## Expected Behaviour

Jekyll will build the site like it did in 4.0.1

## Current Behavior

`Liquid Exception: stack level too deep in report/all-ar21.html/#excerpt`

## Code Sample

Failing build log w/excerpts disabled:
https://travis-ci.org/github/VectorLogoZone/vectorlogozone/builds/693113143

Failing build log:
https://travis-ci.org/github/VectorLogoZone/vectorlogozone/builds/692628196

Working build log:
https://travis-ci.org/github/VectorLogoZone/vectorlogozone/builds/693026174

Diff between working and failing (all I did was pin the version back to 4.0.1).  This is a "make it work" change:
https://github.com/VectorLogoZone/vectorlogozone/commit/b1fb9ee2bca549ecc78129976d07caa6b57436ad

Diff between 4.0.1 and 4.1.0 w/excerpts disabled (a "make it fail" change):
https://github.com/VectorLogoZone/vectorlogozone/commit/12fc2ff11a9e5b9aa6a1c3f659a1c30ff84635e2

**Comment by ashmaroli** [comment]
Thank you for reporting. Could you trigger a Travis build with the `--trace` switch? That'll show us what exactly is causing the infinite loop.

**Comment by ashmaroli** [comment]
Never mind. I got around to tracing the cause myself.
What's happening is that Jekyll 4.1.0 started using `Liquid::Drop` to render page data of `Jekyll::Page`. Coupled with your use of `sort` filter with property `'sort'` (`{{ site.pages | sort: 'sort' }}`), the system got tricked into running infinitely.

I haven't come up with a solution though..

**Comment by fileformat** [comment]
The suggested plugin worked for me.  Thanks!
https://travis-ci.org/github/VectorLogoZone/vectorlogozone/jobs/693222901
