### ISSUE TITLE
feat: A mode for using `../` instead for relative url. (UX intent: Hosted In Subfolder Or File:// )

### ISSUE THREAD

**Issue by mofosyne** [jekyll/jekyll#8237]
## Summary

The idea is for some way besides absolute_url and relative_url to have a mode where we use `../` instead. 

* Similar Ticket: https://github.com/jekyll/jekyll/issues/6360

## Motivation

This is especially important for CSS url in non html server applications like loose "html files" in filesystems, or for easier setup in subfolders like in github pages.

In addition according to Daniel Vassallo it's good practice to use relative url ( https://stackoverflow.com/questions/2005079/absolute-vs-relative-urls ):

>In general, it is considered best-practice to use relative URLs, so that your website will not be bound to the base URL of where it is currently deployed. For example, it will be able to work on localhost, as well as on your public domain, without modifications.

## Guide-level explanation

Being trying to figure out how this can be done in practice. Based on https://jekyllrb.com/docs/layouts/#usage example...

Maybe `<link rel="stylesheet" href="/css/style.css">` would be modified to have `<link rel="stylesheet" href="../css/style.css">` if say... in a subfolder.

This could perhaps be activated by a setting in `_config.yml` saying `relative_url:true`.

At the moment am currently using this workaround from https://gist.github.com/Ketrel/1f36fca6b4148f7263b3ee8fdb0923e7 to create `relBase`

```
{% assign relBase = '' %}
{% assign tempDepth = page.url | append: 'hackish-solution' | split: '/' | size | minus: 2 %}
{% for i in (1..tempDepth) %}
  {% if forloop.last %}
    {% assign relBase = relBase | append: ".." %}
  {% else %}
    {% assign relBase = relBase | append: "../" %}
  {% endif %}
{% endfor %}
{% if relBase == '' %}
    {% assign relBase = '.' %}
{% endif %}
```

## Drawbacks

Not sure how much changes needs to be done in layout. Hopefully there is a way to keep a layout as it is, so that you can switch between absolute addressing vs relative `../` addressing.

## Unresolved Questions

How to deal with all the layouts already created by others without having to introduce any new syntax for it.

**Comment by ashmaroli** [comment]
Jekyll is inherently webserver-oriented. So, support for navigation via the `file://` protocol won't appear in the Core. The community is welcome to develop a plugin that provides this functionality.

**Comment by mofosyne** [comment]
Ah that makes sense. Just to clarify, my main applications is for easier maintainance of github project pages. Being trying to figure out the most portable way to deal with github project pages without much success. Hence am looking for a solution and relative url appears to be a desirable solution.

So far I'm settling for:

```
{% comment %} relative url fix: https://gist.github.com/Ketrel/1f36fca6b4148f7263b3ee8fdb0923e7 {% endcomment %}
{% assign relBase = '' %}
{% assign tempDepth = page.url | append: 'hackish-solution' | split: '/' | size | minus: 2 %}
{% for i in (1..tempDepth) %}
  {% if forloop.last %}
    {% assign relBase = relBase | append: ".." %}
  {% else %}
    {% assign relBase = relBase | append: "../" %}
  {% endif %}
{% endfor %}
{% if relBase == '' %}
    {% assign relBase = '.' %}
{% endif %}
```

But happy to hear a more official or maintainable solution.

**Comment by ashmaroli** [comment]
You may want to take this conversation to our forum at https://talk.jekyllrb.com/
This GitHub Issue Tracker is for reporting / discussing bugs and stuff related to Jekyll Core.

**Comment by fauno** [comment]
Something like this?

https://rubygems.org/gems/jekyll-relative-urls
