### ISSUE TITLE
null layout regresion

### ISSUE THREAD

**Issue by steveoh** [jekyll/jekyll#8239]
I was not able to test this locally where it was functioning property on 4.0.1 until https://github.com/envygeeks/jekyll-docker/pull/278 is merged and I can pull 4.1.0 locally. But netlify is using 4.1.0 and this is causing problems in production.

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |            |
| `jekyll`         | 4.1.0     |
| `github-pages`   | -     |

---

## Expected Behaviour

`layout: null` should not use default template

## Current Behavior

the default template is being used

## Code Sample

This is the diff that fixed my issue. 
https://github.com/agrc/gis.utah.gov/commit/078d22fc1fcc33ff47f95edbe48d2478391bca43

**Comment by ashmaroli** [comment]
This has been resolved on `master`. You may point your Gemfile to the repository until we ship v4.1.1:
```ruby
gem 'jekyll', github: 'jekyll/jekyll'
```

**Comment by ashmaroli** [comment]
Also, for future compatibility, prefer `layout: none` over `layout: null` as the former is resistant to
changes from merge two hashes.

**Comment by steveoh** [comment]
> prefer layout: none over layout: null

Is this doc'd somewhere because https://github.com/jekyll/jekyll/issues/2730#issuecomment-51872340 and all of the code samples in https://github.com/jekyll/jekyll/issues?q=is%3Aissue+layout%3A+null

**Comment by ashmaroli** [comment]
> Is this doc'd somewhere..

The feature was first mentioned in https://jekyllrb.com/docs/front-matter/#predefined-global-variables but did not get updated when the feature was extended to cover pages as well.

**Comment by steveoh** [comment]
My issue is not present in master. ✅
