### ISSUE TITLE
feat: Docker image for 4.1.0

### ISSUE THREAD

**Issue by kvz** [jekyll/jekyll#8240]
Hi, I noticed 4.1.0 is out, congrats :tada: I would love to try it out but can only use the Docker version in my company. Looking at https://hub.docker.com/r/jekyll/jekyll/tags it's not out yet. Do you know when this will be? Would love ping so I can take it for a spin.

**Comment by kvz** [comment]
On a sidenote, i wonder if it could be automated on tag-push? Here's how `tusd` does it with GitHub Actions in case it's helpful https://github.com/tus/tusd/blob/master/.github/workflows/main.yml#L51

**Comment by kvz** [comment]
Found this which seems related: https://github.com/envygeeks/jekyll-docker/pull/278

**Comment by DirtyF** [comment]
yep, we don't maintain that image. 😊

**Comment by kvz** [comment]
Shouldn’t it be envygeeks/jekyll then so you have the opportunity to have an official docker image?

**Comment by crispgm** [comment]
> Should that container name rather be called `envygeeks/jekyll` (vs `jekyll/jekyll`) then? Then future folks like me will report in the correct repo, which could perhaps save soms time or disappointment on either end.
> 
> And also so you will then have the opportunity to publish an official docker image, should those aspirations materialize.
> 
> Edit: It does look like https://hub.docker.com/r/jekyll/jekyll/ states it's the official image 🤔

He was the former maintainer of Jekyll, and that repo was originally jekyll/docker. I guess this is the reason.,

**Comment by kvz** [comment]
It appears we should not bother the maintainer with Jekyll matters right now. In order to still be able to use 4.1.0 in our environment I forked the repo and pushed Docker images under `kevinvz/jekyll:4.1.0`. <https://github.com/kvz/jekyll-docker><https://hub.docker.com/r/kevinvz/jekyll>. 

That being said, I'm in no position to really understand or maintain this, so it's more of a stopgap for our own purposes, than anything else. As soon as there are official images I will pull the plug on this but perhaps it helps someone in the meantime.
