### ISSUE TITLE
Consider removing accents

### ISSUE THREAD

**Issue by jmau111** [jekyll/jekyll#8251]
Hello there,

Thanks for the tool, love it, I've been using it for years.

I'm using Jekyll 4.1.0, and I've created a custom plugin that grabs id of titles (h2,h3,h4,h5,h6) in post content. It requires some tweaks, but it works, and I get my anchor links without using any javaScript.

But, there are accents in HTML attributes and URLs. I'm using french language so there are "é", "è", "ö", "ï", etc. I guess it's the same for many other languages.

For example  : 

```html
<h2 id="les-solutions-à-éviter">Les solutions à éviter</h2>
``` 
So, I have a couple of questions : 

* Is it something known?
* Are you willing to fix it in the next releases?

Thx. ✌️

**Comment by ashmaroli** [comment]
Have you tried using `{{ page.url | slugify: 'latin' }}` in your templates?

**Comment by jmau111** [comment]
nice use of filters but the HTML attribute (id) is added by Jekyll, it's build by the core.

**Comment by ashmaroli** [comment]
> the HTML attribute (id) is added by Jekyll, it's build by the core.

Jekyll doesn't add / remove HTML. It is all determined by the theme you're using.
You can check your config file and it may have a key named `theme`.
If found, then you may want to report your issue at the theme repository, else do check your layouts / includes.

**Comment by jmau111** [comment]
> Jekyll doesn't add / remove HTML

Hello, thanks for your time but I think you might be wrong or maybe that was not clear enough on my side.

Let me explain, all titles in post content seem formatted, automatic id with a slugify on the title and this is not due to my theme (I don't have one, it's full custom). I've tested it on a fresh install with the minima theme : 

<img width="830" alt="Screenshot 2020-06-15 at 14 00 46" src="https://user-images.githubusercontent.com/6878027/84655117-a45b3600-af10-11ea-8720-0c4b58182a33.png">

**Comment by ashmaroli** [comment]
My apologies @jmau111. I saw URL in your opening post and I settled on `slugify`.
Instead, the issue is with how Kramdown converts Markdown to HTML.

You can disable the auto-generation of `id` attribute for header tags by having the following in your config file:
```yaml
kramdown:
  auto_ids: false
```

**Comment by jmau111** [comment]
thx
