### ISSUE TITLE
docs: Multiple broken links on the wiki page with Jekyll sites

### ISSUE THREAD

**Issue by ptcodes** [jekyll/jekyll#8253]
## Motivation

I was going through the sites in the wiki for inspiration and noticed that many sites no longer work on this page: https://github.com/jekyll/jekyll/wiki/sites

I've used a link checker to get a list of broken links.

## Suggestion

You should remove the broken links. Here is the list:

http://blog.10to1.be
http://mislav.uniqpath.com/
http://boj.github.com/
http://www.senoj.net/
http://alpinegizmo.com/
http://andreicek.eu/
http://ctshryock.com/
http://exolucere.ca/
http://code.hardikr.com/
http://nickknowlson.com/
http://directstupid.net/
http://andreyglauzer.com.br/
http://flatterline.com/
http://codewu.com/
http://hnresources.com/
http://saberma.me/
http://www.johng.co.uk
http://io.kodfabrik.com/
http://brighterplanet.github.com/
http://alip.github.com/
http://ewertonorg.github.io/
http://kramdown.rubyforge.org/ (timeout error)
http://flyoverblues.com/ (timeout error)

Thank you

**Comment by ptcodes** [comment]
I've just noticed there was a notice on the page:

> This page has been replaced by our Jekyll Showcase on Jekyll Talk! Submit your site there.

It now makes sense why many links don't work. You can disregard my submitted issue then.

One thing, though. Link in the notice takes you to the page that doesn't exist:
https://talk.jekyllrb.com/t/jekyll-showcase-share-your-sites-built-with-jekyll/44

**Comment by DirtyF** [comment]
Thanks, I've cleaned it up.
