### ISSUE TITLE
kramdown setting `math_engine: nil` breaks kramdown_parser

### ISSUE THREAD

**Issue by zaprice** [jekyll/jekyll#8256]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |  macOS Catalina          |
| `jekyll`         | 4.1.0     |
| `github-pages`   | No     |

---

## Expected Behaviour

In `_config.yml`, I have the following block of kramdown settings:
```
kramdown:
  math_engine: nil
```

This option should be accepted, as on the [kramdown documentation](https://kramdown.gettalong.org/rdoc/Kramdown/Options.html), to not use a math engine to convert math blocks. I know this worked at least as recent as jekyll version 3.4.3.

## Current Behavior

If `math_engine: nil` is set, running `jekyll build` gives a Dependency Error; in [kramdown_parser](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/converters/markdown/kramdown_parser.rb#L131), it looks for a hypothetical gem `kramdown-math-nil` which of course does not exist. The fix may be a simple as adding `&& math_engine != "nil"` to the previous if statement, which works on my machine.

## Code Sample

To replicate, create a new Jekyll site with `jekyll new .`, then append the following to your `_config.yml`:
```
kramdown:
  math_engine: nil
```
Then, run `jekyll build` and observe the aforementioned error.

**Comment by ashmaroli** [comment]
In YAML, `nil` is expressed as `null` or with shorthand `~`. Therefore, the config would be:
```yaml
kramdown:
  math_engine: null
```

**Comment by zaprice** [comment]
Thanks, I should be using `null` instead. There are [a few](https://github.com/linjer/jekyll-katex/issues/29) [other people](https://github.com/jekyll/jekyll/issues/6061) [confused](https://github.com/KaTeX/KaTeX/issues/712) [about this](https://github.com/search?q=%22math_engine%3A+nil%22&type=Code) online, since it used to accept `nil` and will crash if they update Jekyll. 

Not sure why I used `nil` originally, I assume someone recommended it for switching from MathJax to KaTeX circa 2017. Hopefully this issue can serve as documentation in case anyone else has the same problem.
