### ISSUE TITLE
The tag bibliography on line 3 in _pages/publications.md is not a recognized Liquid tag

### ISSUE THREAD

**Issue by grjd** [jekyll/jekyll#8260]
I can build page locally but when I try to deploy at github I get this error:

Your site is having problems building: The tag bibliography on line 3 in _pages/publications.md is not a recognized Liquid tag. For more information, see https://help.github.com/en/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.

On line 3 _pages/publications.md there is:
permalink: /publications/

**Comment by DirtyF** [comment]
GitHub Pages whitelist plugins: https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins

See how to deploy a Jekyll site with GitHub Actions if you use other plugins; https://jekyllrb.com/docs/continuous-integration/github-actions/
Or use another free service like Vercel.com or Netlify.com
