### ISSUE TITLE
Remove ".hmtl" from github repository

### ISSUE THREAD

**Issue by sarahshultz** [jekyll/jekyll#8262]
In reference to this previous post that has been closed... I'm trying to remove ".html" from my files on my published website. Excuse my beginner-level understanding, but is "Jekyl" a different download within Github repositories that I must first access before trying to remove the ".html" from published pages and on test server?

My website has been published at: smeishultz.com - But all of the subpages end with ".html" 

I've referenced this post below - But I'm not even sure where to access the 'permalink' attribute in my local code? Not sure if I'm going about this correctly - hopefully someone can help :)

OLD POST REFERENCED BELOW:

I'm sorry, I don't quite understand how to change the `permalink` attribute of a page. Where should I put it?

I have tried to set:
- `permalink: /:title` on the `_config.yml`, then it does not affect pages
- `permalink: /:title` on the frontmatter (inside the page, between `---`), then the page is accessible at URL `/:title` (literal)
- `permalink: /page-title` on the frontmatter, then the page is accessible at URL `/page-title`, but when I browse to it it downloads as a binary file instead of HTML

_Originally posted by @cirosantilli in https://github.com/jekyll/jekyll/issues/2021#issuecomment-34467782_

**Comment by cirosantilli** [comment]
I can't begin to describe how much I love old post autolocking.

**Comment by sarahshultz** [comment]
So are you able to help me? 
I'm not sure where to put the "permalink" attributes and implementing them in the frontmatter? 

Also do I just remove ".html" from the links referenced in a webpage within the <a link </a> code?

**Comment by cirosantilli** [comment]
@sarahshultz sorry, I forgot all about this mostly. And as Jekyll versions change things change. What I suggest is that you start with a minimal reproduction repo, and try everything in Google.

**Comment by cirosantilli** [comment]
I think it works automatically now. Not sure. E.g. I start with https://github.com/cirosantilli/jekyll-min and add a notmain.md that copies index.md, and they show without HTML locally and likely also on GH pages.

**Comment by sarahshultz** [comment]
thank you so much for your help!

**Comment by alexanderadam** [comment]
So… in this case this issue can be closed? :thinking:
