### ISSUE TITLE
an gem proplem with jekyll

### ISSUE THREAD

**Issue by aagradwan** [jekyll/jekyll#8268]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |            |
| `manjaro(linux)`         | Latest     |
| `gem `   | 3.1.2     |
|`ruby` | 2.7.1p83 |

---
Im on manjaro linux and i devlope an web site i well put his link if i end developing it :) 
but iv lessened about github pages and some time in the past (some monthes) iv worked with jekyll and know the github pages are supported jekyll and i think its a nice framework :100:  :) 

sooooooo 

iv reinstalled jekyll with  `gem install bundler jekyll` 
and its had give me this output `Successfully installed bundler-2.1.4
Fetching jekyll-4.1.1.gem
Successfully installed jekyll-4.1.1
2 gems installed
Traceback (most recent call last):
	21: from /home/radwan/.gem/ruby/2.7.0/bin/jekyll:23:in `<main>'
	20: from /home/radwan/.gem/ruby/2.7.0/bin/jekyll:23:in `load'
	19: from /home/radwan/.gem/ruby/2.7.0/gems/jekyll-4.1.1/exe/jekyll:8:in `<top (required)>'
	18: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	17: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	16: from /home/radwan/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll.rb:209:in `<top (required)>'
	15: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	14: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	13: from /home/radwan/.gem/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	12: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	11: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	10: from /home/radwan/.gem/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
	 9: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 8: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 7: from /usr/lib/ruby/gems/2.7.0/gems/sassc-2.3.0/lib/sassc.rb:31:in `<top (required)>'
	 6: from /usr/lib/ruby/gems/2.7.0/gems/sassc-2.3.0/lib/sassc.rb:31:in `require_relative'
	 5: from /usr/lib/ruby/gems/2.7.0/gems/sassc-2.3.0/lib/sassc/native.rb:3:in `<top (required)>'
	 4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 2: from /usr/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/lib/ffi.rb:4:in `<top (required)>'
	 1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- 2.7/ffi_c (LoadError)
	22: from /home/radwan/.gem/ruby/2.7.0/bin/jekyll:23:in `<main>'
	21: from /home/radwan/.gem/ruby/2.7.0/bin/jekyll:23:in `load'
	20: from /home/radwan/.gem/ruby/2.7.0/gems/jekyll-4.1.1/exe/jekyll:8:in `<top (required)>'
	19: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	18: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	17: from /home/radwan/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll.rb:209:in `<top (required)>'
	16: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	15: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	14: from /home/radwan/.gem/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	13: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	12: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	11: from /home/radwan/.gem/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
	10: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 9: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 8: from /usr/lib/ruby/gems/2.7.0/gems/sassc-2.3.0/lib/sassc.rb:31:in `<top (required)>'
	 7: from /usr/lib/ruby/gems/2.7.0/gems/sassc-2.3.0/lib/sassc.rb:31:in `require_relative'
	 6: from /usr/lib/ruby/gems/2.7.0/gems/sassc-2.3.0/lib/sassc/native.rb:3:in `<top (required)>'
	 5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /usr/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/lib/ffi.rb:3:in `<top (required)>'
	 2: from /usr/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/lib/ffi.rb:6:in `rescue in <top (required)>'
	 1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': libffi.so.6: cannot open shared object file: No such file or directory - /usr/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ffi-1.12.2/ffi_c.so (LoadError)
bash: cd: my-awesome-site: No such file or directory
` plz help me :(

**Comment by DirtyF** [comment]
Hi, can you update to latest Jekyll 3.x, Jekyll 3.2 has no support for latest Ruby.

**Comment by aagradwan** [comment]
> Hi, can you update to latest Jekyll 3.x, Jekyll 3.2 has no support for latest Ruby.

but how :) ?

**Comment by ashmaroli** [comment]
> but how to solve :) ?

Try running `bundle update` first. That should at minimum update the `ffi` gem.
When you run `bundle info jekyll`, and the version displayed is still older than `v3.8.7`, perhaps your Gemfile is locked to use the older version. Check your Gemfile and if necessary, edit it to show `gem "jekyll", "~> 3.8"`.

**Comment by aagradwan** [comment]
> > but how to solve :) ?
> 
> Try running `bundle update` first. That should at minimum update the `ffi` gem.
> When you run `bundle info jekyll`, and the version displayed is still older than `v3.8.7`, perhaps your Gemfile is locked to use the older version. Check your Gemfile and if necessary, edit it to show `gem "jekyll", "~> 3.8"`.

Could not locate Gemfile

**Comment by ashmaroli** [comment]
@aagradwan You have an older version of the `ffi` gem installed.
First try running `gem update ffi`. 
After that succeeds, try running `gem install jekyll`.
