### ISSUE TITLE
Plugin with specific filename doesn’t get required

### ISSUE THREAD

**Issue by paulozoom** [jekyll/jekyll#8270]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | macOS 10.15.5 |
| `jekyll`         | 4.1.0     |
| `github-pages`   | No     |

---

## Expected Behaviour
I have a plugin file `_plugins/tags/tag_with_params.rb` declaring a class which I want to be available.

## Current Behavior
If the file is called `tag_with_params.rb`, subclassing the class declared in it throws `Error: uninitialized constant`.

However, if the file is called any of these, the problem doesn’t occur.
* `tag_withparams.rb`
* `tagwithparams.rb`
* `tag_with_attrs.rb`
* `tag_with_xarams.rb`

All of these work.

## Code Sample
It doesn’t seem like the code matters much because it works with a different filename, but anyway:

`_plugins/tags/tag_with_params.rb`:
```ruby
module Jekyll
  module Tags
    class TagWithParams < Liquid::Tag
      REQUIRED_PARAMS = [].freeze
      DEFAULT_PARAMS = {}.freeze

      attr_reader :params

      def initialize(tag_name, markup, tokens)
        super
        # Build a parameters hash with symbol keys and values with appropriate type
        params_hash = markup.scan(::Liquid::TagAttributes).map { |k, v| [k.to_sym, ::Liquid::Expression.parse(v)] }.to_h

        missing_params = self.class::REQUIRED_PARAMS - params_hash.keys
        unless missing_params.empty?
          raise ArgumentError, "Missing params for {% #{tag_name} %}: #{missing_params.map { |a| "'#{a}'" }.join(', ')}"
        end

        @params = self.class::DEFAULT_PARAMS.merge(params_hash)
      end
    end
  end
end
```

`_plugins/tags/youtube_tag.rb`:
```ruby
module Jekyll
  module Tags
    class YoutubeTag < TagWithParams

    # rest of the code omitted for brevity

    end
  end
end

Liquid::Template.register_tag('youtube', Jekyll::Tags::YoutubeTag)

**Comment by ashmaroli** [comment]
I tried to reproduce this with a new Jekyll workspace but did not face any exceptions..

**Comment by paulozoom** [comment]
There’s something fishy going on, because after removing the file, and creating a new one, it wouldn’t work at all, regardless of filename, until the file containing TagWithParams were manually `require`d.

**Comment by ashmaroli** [comment]
If possible it'd be best if you could have the entire source code in a public repository. That way, we'd be able to clone it at our end and test it.

**Comment by paulozoom** [comment]
Unfortunately I'm not at liberty to do that. I’m going to close because this isn't reproducible, and seems quite like an edge case to be taking up your time. Thanks for chiming in!
