### ISSUE TITLE
Win10, Ruby 2.7.1 installation

### ISSUE THREAD

**Issue by gwilku** [jekyll/jekyll#8277]
Hi,

I'm on Windows 10,  with Ruby 2.7.1 and I still have no clue how to properlly install Jekyll.
Here's what I do (following https://jekyllrb.com/docs/installation/windows/):
1. I install Ruby from the installer
2. check to install MSYS2 as well
3. Run ridk install at the end of installation, which asks me to choose what to do next:
 (MSYS base / MSYS ubdate or MSYS + MINGW) 
and this is already not documented.

The link to RubyInstaller Documentation doesn't help at all (https://github.com/oneclick/rubyinstaller2#using-the-installer-on-a-target-system), as it doesn't contain anything relevant to what I'm doing at this stage.

I choose the third option, to have everything installed and proceed.

In step 3. I run gem install jekyll bundler, but it fails, jekyll is not installed, and there is absolutely no hint what to do with that. The docs jus assume that everything works nicely. Well, it doesn't.
The bundler installs fine, but jekyll doesn't and I have no clue what to do next.

**Comment by gwilku** [comment]
This is the same as here:
https://github.com/jekyll/jekyll/issues/6911

And apparently has not been resolved for over 2 years now.

**Comment by ashmaroli** [comment]
@gwilku Would you be able to post the entire output when you run `gem install jekyll`?

**Comment by gwilku** [comment]
> @gwilku Would you be able to post the entire output when you run `gem install jekyll`?

actually... no :)
Turns out that what I had to do is to restart the PC and run gem install jekyll again.

But, the issue with the docs remains:

1. Download and Install a Ruby+Devkit version from RubyInstaller Downloads. Use default options for installation.
-- needs more details about the installation options. Should we go with MSYS included, or install MSYS2 separately?

2. Run the ridk install step on the last stage of the installation wizard. This is needed for installing gems with native extensions. You can find additional information regarding this in the RubyInstaller Documentation
-- this is confusing, as actually ridk install is included in step 1 automatically I think. And, the key question is, which install option should I choose (MSYS base, MSYS update or MSYS + MINGW)

3. Open a new command prompt window from the start menu, so that changes to the PATH environment variable becomes effective. Install Jekyll and Bundler via: gem install jekyll bundler
-- Windows 10 is weird. My Ruby installation was already icluded in PATH, but I'm guessing that not everything really worked as intended: this step needs to be preceeded with a system restart (yup, back to the '90s).

4. Check if Jekyll installed properly: jekyll -v
-- and if not? Some basic hints on troubleshooting would be really handy.


I can try and unistall everything and replicate the issue to get the full error stack again, but it's not an uncommon one, and looks roughly like this:

"Building native extensions. This could take a while...
1 [main] make (11480) shared_info::initialize: size of shared memory region changed from 51128 to 40888
0 [main] make (3144) shared_info::initialize: size of shared memory region changed from 51128 to 40888
ERROR: Error installing jekyll:
ERROR: Failed to build gem native extension."

**Comment by larskanis** [comment]
>  1. Download and Install a Ruby+Devkit version from RubyInstaller Downloads. Use default options for installation.
>     -- needs more details about the installation options. Should we go with MSYS included, or install MSYS2 separately?

If you choose the "Ruby+Devkit" version, you'll get MSYS2 and build tools included. Why should you install MSYS2 separately? Is this mentioned somewhere? In fact it doesn't matter how and which MSYS2 you use, but using the "Ruby+Devkit" versions makes it easier and less error-prone.


> 2. Run the ridk install step on the last stage of the installation wizard. This is needed for installing gems with native extensions. You can find additional information regarding this in the RubyInstaller Documentation
>   -- this is confusing, as actually ridk install is included in step 1 automatically I think. And, the key question is, which install option should I choose (MSYS base, MSYS update or MSYS + MINGW)

The `ridk install` step is necessary for `pacman` to work. Most other Devkit tools will work anyways. Again the default action is just pressing Enter key, as recommended at the `ridk install` screen.


> 3. Open a new command prompt window from the start menu, so that changes to the PATH environment variable becomes effective. Install Jekyll and Bundler via: gem install jekyll bundler
>   -- Windows 10 is weird. My Ruby installation was already icluded in PATH, but I'm guessing that not everything really worked as intended: this step needs to be preceeded with a system restart (yup, back to the '90s).

Yes Windows is weird. The message `size of shared memory region changed` appears when two distinct versions of MSYS2 (or maybe Cygwin) are mixed. That's probably the reason why you needed a reboot. It is usually not necessary.


>     4\. Check if Jekyll installed properly: jekyll -v
>         -- and if not? Some basic hints on troubleshooting would be really handy.

That's a good point. Maybe we should add a hint to reboot here. However the errors can be very varying, so that I would just add a link to open a new [RubyInstaller issue](https://github.com/oneclick/rubyinstaller2/issues/new).

**Comment by shannonxtreme** [comment]
My two cents for 4. : doesn't hurt to have quick troubleshooting steps like reboot as well as a link to create a new issue if it doesn't work. Could be  "note info" class right under the step.
