### ISSUE TITLE
Strange problem with SCSS that comes from a theme.

### ISSUE THREAD

**Issue by dabrahams** [jekyll/jekyll#8279]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |   Mac OS 10.15.5         |
| `jekyll`         | 3.8.7     |
| `github-pages`   | 206     |

---

## Expected Behaviour

Adding style.css that replicates the main scss file of the theme I'm using should produce identical CSS

## Current Behavior

Different CSS is produced

## Code Sample

This [PR](https://github.com/dabrahams/JekyllSCSSBugMaybe/pull/1) on a minimal github pages site repository describes the effects and demonstrates.  The effects reproduce with a locally-running docker container set up to serve github pages.

I can see no reason why I should see this

<img width="304" alt="image" src="https://user-images.githubusercontent.com/44065/86502670-8b4ce480-bd5a-11ea-99df-af3e81fb01ec.png">

 at https://dabrahams.github.io/JekyllSCSSBugMaybe/

Instead of this:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/44065/86502686-b0d9ee00-bd5a-11ea-93d0-0edf0c1c0b2b.png">

But perhaps I'm missing something?

**Comment by ashmaroli** [comment]
This is not a Jekyll issue. From what I see is that the `jekyll-theme-minimal` has all `<ul>` elements inside the `<header>` element to render as a formatted inline table instead of a standard unordered list.
If anything you should override the existing CSS directive to your liking.

**Comment by dabrahams** [comment]
One of us is definitely missing something.  Are we looking at the same [CSS](https://github.com/pages-themes/minimal/blob/master/_sass/jekyll-theme-minimal.scss)?

I'm no CSS expert, but from what I see there the formatted inline table stuff is limited to the `downloads` class.
If I copy [jekyll-theme-minimal.scss](https://github.com/pages-themes/minimal/blob/master/_sass/jekyll-theme-minimal.scss) into my site's `_sass/` directory, I observe that the formatting of a `<ul>` in the header is controlled by whether it has the `downloads` class, but when I let it pull the file from wherever GitHub gets its themes, that is no longer the case.  Looking back at [this commit](https://github.com/pages-themes/minimal/commit/69701fe30f430917e9388b38a4965b853d59e0bf#diff-ca897f9b7a99cddd5cd373327e7a210a), perhaps GitHub is serving an outdated version of the theme?

**Comment by ashmaroli** [comment]
> perhaps GitHub is serving an outdated version of the theme?

That's exactly it! The commit you're referring to hasn't been *released* yet. GitHub Pages is [using v0.1.1](https://pages.github.com/versions/)
