### ISSUE TITLE
Text area rendering error

### ISSUE THREAD

**Issue by a0m0rajab** [jekyll/jekyll#8284]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      Ubuntu 18.04.4 LTS      |
| `jekyll`         | Latest     |
| `github-pages`   | no     |

---

## Expected Behaviour

using include tag i am expecting the HTML page to render fully.

## Current Behaviour

 it's rendering but the error happened on textarea for this tags it's just giving a plain HTML instead of rendering it. 

I am using this theme : 
https://github.com/vsoch/mkdocs-jekyll

but i think the problem is in jekyll.

## Code Sample

{% include convertor.html %} 

## Result

Enter Text
<textarea id=before name="" id="" cols="70" rows="20">test </textarea>
Converted Text
<textarea id=after name="" id="" cols="70" rows="20" readonly></textarea>

**Comment by ashmaroli** [comment]
From what you have posted, I am really not able to tell why you think the error is in Jekyll.
I have no idea what the contents of your include file `converter.html` is, so can't tell if there's a mistake there.

But from the result provided, it is clear that the markup is not correct. The first `id` attribute of your `textarea` elements are not quoted.

**Comment by a0m0rajab** [comment]
Okay i have pushed my page to let you see it. 

https://a0m0rajab.github.io/Open-FSMVU/convertor/

this is were i have used it. 

This is the page file:
https://github.com/a0m0rajab/Open-FSMVU/blob/master/_includes/convertor.html

**Comment by ashmaroli** [comment]
@a0m0rajab Like I said earlier, you need to quote your textarea's first `id` attribute:
```diff
- <textarea id=before name="" id="" cols="70" rows="20">test </textarea>
+ <textarea id="before" name="" id="" cols="70" rows="20">test </textarea>

**Comment by a0m0rajab** [comment]
Thank you, this did the job for me :) 

Now I have to check how to let the JS script work in that file...  :3

**Comment by ashmaroli** [comment]
We have a forum that allows you to interact with the Jekyll community and ask all sorts of questions:
https://talk.jekyllrb.com/
