### ISSUE TITLE
Errors on Mac - Catalina & Big Sur

### ISSUE THREAD

**Issue by kdjanz** [jekyll/jekyll#8289]
I did a Homebrew install to my local user on my development laptop under both Catalina and Big Sur. I followed directions fully and it appeared to install fully without errors in both cases. When I set up the "Hello World" index.html and run Build or Serve, I get the following error:
`Supervisors-MacBook-Pro:~ kdjanz$ jekyll serve
Configuration file: none
            Source: /Users/kdjanz
       Destination: /Users/kdjanz/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    ------------------------------------------------
      Jekyll 4.1.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
Traceback (most recent call last):
	27: from /usr/local/bin/jekyll:23:in `<main>'
	26: from /usr/local/bin/jekyll:23:in `load'
	25: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
	24: from /Users/kdjanz/.gem/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	23: from /Users/kdjanz/.gem/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	22: from /Users/kdjanz/.gem/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	21: from /Users/kdjanz/.gem/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	20: from /Users/kdjanz/.gem/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	19: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	18: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	17: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
	16: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	15: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'
	14: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'
	13: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'
	12: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:78:in `process'
	11: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:180:in `read'
	10: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:16:in `read'
	 9: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:60:in `read_directories'
	 8: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:86:in `retrieve_dirs'
	 7: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:86:in `each'
	 6: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:89:in `block in retrieve_dirs'
	 5: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:48:in `read_directories'
	 4: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:48:in `each'
	 3: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/reader.rb:52:in `block in read_directories'
	 2: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/utils.rb:141:in `has_yaml_header?'
	 1: from /Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/utils.rb:141:in `open'
/Users/kdjanz/.gem/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/utils.rb:141:in `initialize': Operation not permitted @ rb_sysopen - /Users/kdjanz/Library/com.apple.internal.ck (Errno::EPERM)
`

When I go into my Library and find the com.apple.internal.ck file, I cannot get info on it and it says "You have unknown access" and I can't delete it or rename it. 

I believe this is a Catalina permissions thing perhaps, but it breaks both build and serve commands so that I do not get the expected ~/.sites folder created by the build process.

Any suggestions for someone who is a newbie to the command line and to Jekyll as well?

Thanks 

Kelly Janz

**Comment by jaybe-jekyll** [comment]
Hi. You used Homebrew to install what exactly?

**Comment by deirdresm** [comment]
com.apple.internal.ck is internal status that contains nothing that a user should touch, which is why it doesn't let people look at it. It's puzzling why it was a showstopper in this case, though.

**Comment by ashmaroli** [comment]
> It's puzzling why it was a showstopper in this case, though.

Probably because they tried serving the user's root:
```
     Source: /Users/kdjanz
Destination: /Users/kdjanz/_site
```
One should not run `jekyll serve` wherever they wish..
