### ISSUE TITLE
For loop creating content in random places throughout a page

### ISSUE THREAD

**Issue by Jackskitt** [jekyll/jekyll#8308]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |       Windows 10     |
| `jekyll`         | Latest     |
| `github-pages`   | no |

---

## Current Behavior

I've got a loop within my page which populates a gallery, e.g

Now the gallery works fine, however, it's inserting the <a> tags in random places throughout the rest of the markup. This isn't just happening to me on this page or site

## Code Sample
`  {% for galleryImage in page.gallerySection.images limit:4 %}
                        <a href="#" class="lightbox-image w-inline-block w-lightbox">
                        <img src="{{galleryImage}}"/>
{% endfor %}`

**Comment by ashmaroli** [comment]
Jekyll doesn't decide *where to insert markup*. All insertions are determined by the user's template.
Ergo, this is not a Jekyll bug.

For usage related assistance, please approach our community at https://talk.jekyllrb.com/
