### ISSUE TITLE
feat: replace #123 with a link to github.com/project/repo/issues/123

### ISSUE THREAD

**Issue by hboetes** [jekyll/jekyll#8309]
Hi there,

Consider the following text in our NEWS.md:

```
Columns Position Not Being Maintained (#8)
```
The #8 points to a (closed) issue. The html renderer could replace that `#8` with a link to the issue, but does not.

I checked the docs but I couldn't find if this feature is already supported and I think it would be very nice. Or am I missing something?

Thanks!

**Comment by ashmaroli** [comment]
This is not a Jekyll *concern* per se. Converting `#3` into a link to a remote page (irrespective of `github.com`, `gitlab.com`, etc) is not part of Jekyll Core's agenda.
There may be plugins available for such functionality.
Please approach https://talk.jekyllrb.com/ for further assistance on this matter.

**Comment by hboetes** [comment]
In the meanwhile we've found another way to get what we want. Cheers.
