### ISSUE TITLE
Kramdown v2 support for Jekyll v3.x

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#8315]
## Summary

I'd like to upgrade to kramdown v2 in GitHub-pages but we're blocked by the hard requirement that Jekyll v3.8.7 has on kramdown v1.

## Motivation

kramdown v2.3.0 has a CVE fix that we'd like to ship.

## Guide-level explanation

- [x] Ship kramdown v2 support to the 3.9-stable branch (prior art: https://github.com/jekyll/jekyll/pull/7492) https://github.com/jekyll/jekyll/pull/8322
- [ ] Release Jekyll v3.9.0 with kramdown v2 support

## Drawbacks

This further makes the move to Jekyll v4 less appealing and diverts efforts to this older version of Jekyll. That said, GitHub Pages is blocked upgrading to Jekyll v4 due to "invisible" breaking changes that would cause confusion and frustration for Pages users.

/cc @jekyll/core

**Comment by ashmaroli** [comment]
kramdown v2 drops core bundling of various converters and parsers in favor of their namesake kramdown extensions.
Is GitHub Pages willing to bundle those gems as well to maintain backwards-compatibility?

**Comment by parkr** [comment]
Yep! Our key approach is to ensure the user experience is as unchanged as possible from today to tomorrow.

**Comment by ashmaroli** [comment]
Apart from the above *minor hiccup*, relaxing the version constraint from `kramdown ~> 1.14` to `kramdown >= 1.14 < 3.0` shouldn't pose an issue for users still on the Jekyll 3.x train.

**Comment by ashmaroli** [comment]
Resolved via #8322
