### ISSUE TITLE
docs: safe option wording is ambiguous

### ISSUE THREAD

**Issue by ryanve** [jekyll/jekyll#8321]
## Motivation

[`safe` option wording is ambiguous](https://jekyllrb.com/docs/configuration/options/)

> Disable custom plugins, caching to disk and ignore symbolic links.

What does Disable apply to?

## Suggestion

Avoid ambiguous commas. Use short clear sentences.

- Disable custom plugins. Disable disk caching. Ignore symbolic links.
- Disable custom plugins, disk caching, symbolic links.

**Comment by DirtyF** [comment]
Feel free to open a PR and scratch your own itch 😉

**Comment by ryanve** [comment]
Sure if someone can clarify what the correct interpretation is first

**Comment by ashmaroli** [comment]
@ryanve There are two ways to run a build in safe mode:
- by appending CLI switch `--safe`
- setting `safe: true` in config file.

Irrespective of the path chosen, when building under *safe* mode, the following holds true:
- Plugins in the `_plugins` directory are **not loaded**.
- Unless additionally listed in the `whitelist` setting in the config file, gem-based plugins are **not loaded** either.
- The disk-caching feature from Jekyll 4 **is disabled**.
- Symlinks are **not expanded** to their referred paths.

**Comment by ryanve** [comment]
thanks @ashmaroli!
