### ISSUE TITLE
Release v3.9.0 with kramdown v2 support

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#8324]
Hello, this is a tracking issue for releasing Jekyll 3.9.0 with kramdown v2 support.

- [x] kramdown v2 support merged into 3.9-stable branch: https://github.com/jekyll/jekyll/pull/8322 (issue: https://github.com/jekyll/jekyll/issues/8315)
- [x] Set default_lang option for kramdown syntax highlighter options to prevent ambiguous language guesses (https://github.com/jekyll/jekyll/pull/8325)
- [x] 3.9.0 release post merged into 3.9-stable branch (https://github.com/jekyll/jekyll/pull/8323)
- [x] Forward-port 3.9.0 release post and History.markdown changes to mainline branch (https://github.com/jekyll/jekyll/pull/8326)
- [x] Release gem from 3.9-stable
- [x] Merge release post and publish

Thanks, all!

/cc @jekyll/core

**Comment by DirtyF** [comment]
@parkr :shipit:

**Comment by parkr** [comment]
Thanks, @DirtyF!

**Comment by parkr** [comment]
https://jekyllrb.com/news/2020/08/05/jekyll-3-9-0-released/

https://rubygems.org/gems/jekyll/versions/3.9.0

Thanks, all!
