### ISSUE TITLE
Build generates without errors, but sass file isn't processing [Windows 10 + WSL2]

### ISSUE THREAD

**Issue by jkulskis** [jekyll/jekyll#8328]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Windows  |   10  |
| WSL  |   2  |
| `jekyll`         | Latest     |
| `github-pages`   | No    |

---

## Expected Behaviour

I haven't used jekyll before so I'm following the getting started tutorial to get a good high level overview before personalizing anything. I am stuck on the [assets section of the tutorial (step 7)](https://jekyllrb.com/docs/step-by-step/07-assets/). After running `jekyll build` and `jekyll serve`, I'm expecting my `styles.scss` file to import my `main.css` file that's in the _sass folder of my root directory. I have tried building and serving with both powershell and Ubuntu 20.04 running on WSL2.

## Current Behavior

The build doesn't output any errors, and I can succesfully serve my site, but instead of `styles.css` being created in my `_site` directory, `styles.scss` is created, and it is unchanged from the original file. Because of this, I suspect that even though I have a front matter comment in my scss file, the scss isn't being processed by jekyll.

## Code Sample

This is my directory structure:
![Directory Structure](https://i.imgur.com/mBW9kKi.png)

**assets/css/styles.scss**
```scss
---
# Front matter comment to ensure Jekyll properly reads the file
---
@import "main";
```

**_sass/main.scss**
```scss
.current {
  color: green;
}
```

**_config.yml** (I didn't originally have this, but added it just in case there was something wrong with my sass_dir config)
```yml
sass:
  style: compressed
  sass_dir: _sass
```

I thought this was a Windows 10 issue, so I tried building and serving with WSL2, but I have the same problem. I think I may have a similar issue to this one (#7628) that was opened in May of 2019, although it seems like this was never actually resolved, since the user only focused on the vscode linting warnings, and ended up removing the front matter entirely. Although this would fix my import problems, I would prefer to use separate scss files and import them individually, since this allows for much better readability and organization.

**Comment by ashmaroli** [comment]
The issue could be because of your text editor and the encoding of your file.
Jekyll only processes a file if its contents start with the string `---↵`

If your text editor is configured to save a file with UTF-8 BOM encoding, the file contents start with the byte sequence `0xEF0xBB0xBF`.
To verify, see if your text editor has the option to show you the encoding of the opened file. The encoding should not contain BOM in it. If the file has not been saved with UTF-8 encoding, update the encoding, make some multiline changes and save the file.

**Comment by jkulskis** [comment]
Awesome, great suggestion. Turns out all of my files are in UTF-8, except for my sass files, which VS-Code/windows automatically configured as UTF-16 LE. After changing my `styles.scss` to UTF-8, running `jekyll build` did process this file correctly, and it ran into an error since `main.scss` was UTF-16 LE as well.
```none
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles.scss':
    Error: only UTF-8 documents are currently supported; your document appears to be UTF-16 (little endian)
```
Switching my `main.scss` file to UTF-8 then fixed the issue.

Suggestion: I think showing a warning during jekyll build if any sass files have an unsupported encoding would be useful. I understand that there is no error in the edge case that your "parent" sass file with the import statements has an unsupported encoding, since no conversion occurs, but it would be easier to debug issues like this with some sort of warning.

Either way, I'm just glad to finally know what the issue was. Thank you @ashmaroli for the help.
