### ISSUE TITLE
excerpt behavior causing additional rendering and overhead

### ISSUE THREAD

**Issue by jaybe-jekyll** [jekyll/jekyll#8334]
OS:  macOS Catalina
jekyll: latest (4.1.1)

Not sure if this is related to the recent change in the `page excerpt` approach.

Getting the following type of muck when rendering-

```
       Rendering: _statics/404/404.md
  Pre-Render Hooks: _statics/404/404.md
  Rendering Markup: _statics/404/404.md
  Rendering Layout: _statics/404/404.md
         Rendering: _statics/404/404.md/#excerpt
  Pre-Render Hooks: _statics/404/404.md/#excerpt
  Rendering Markup: _statics/404/404.md/#excerpt
         Rendering: _statics/home/home.md/#excerpt
  Pre-Render Hooks: _statics/home/home.md/#excerpt
  Rendering Markup: _statics/home/home.md/#excerpt
         Rendering: _statics/home/home.md
  Pre-Render Hooks: _statics/home/home.md
  Rendering Markup: _statics/home/home.md
  Rendering Layout: _statics/home/home.md
```

Note the `#excerpt` entries.

This is redundancy and also seems to slow down rendering a lot. Not even sure what it suggests it's doing.

I am able to make them go away by adding, e.g.  `excerpt: ""` to either front matter or config defaults.

After adding such...

```
       Rendering: _statics/404/404.md
  Pre-Render Hooks: _statics/404/404.md
  Rendering Markup: _statics/404/404.md
  Rendering Layout: _statics/404/404.md
         Rendering: _statics/home/home.md
  Pre-Render Hooks: _statics/home/home.md
  Rendering Markup: _statics/home/home.md
  Rendering Layout: _statics/home/home.md
```

... as expected.

**Comment by ashmaroli** [comment]
v4.1.1 doesn't render **page excerpts** by default.

In the absence of the page-wise `excerpt_separator`, Jekyll checks for `excerpt_separator: ""` in the config file or for fine-grained control, `page_excerpts: false` in the config file.

That said, what you see in the debug output are not references to page excerpts. `_statics/404/404.md` is a document in the collection `_statics`. You'll see the same output even with Jekyll 3.x.

Regarding additional rendering and stuff, there nothing much we can do.
Jekyll extracts the excerpt contents from the parent document before rendering and then renders both separately.

**Comment by jaybe-jekyll** [comment]
I don't understand this. A new jekyll site doesn't produce those `...#excerpt` renderings.

Until I added a `Collection`, the project referenced didn't produce them.

When I added a `Collection`, the `...#excerpt` entries showed up.

When I add `excerpt: ""` to front matter defaults, they "go away".

I don't get it. I expect to see `_statics/404/404.md` because I created the `Collection` and the document. I don't understand why I'm suddenly seeing `_statics/404/404.md#excerpt` until I make it stop by defining `excerpt` as empty.

Here is output of a `jekyll new` with `minima`:

```
       Rendering: _posts/2020-08-11-welcome-to-jekyll.markdown
  Pre-Render Hooks: _posts/2020-08-11-welcome-to-jekyll.markdown
  Rendering Liquid: _posts/2020-08-11-welcome-to-jekyll.markdown
  Rendering Markup: _posts/2020-08-11-welcome-to-jekyll.markdown
  Rendering Layout: _posts/2020-08-11-welcome-to-jekyll.markdown
         Rendering: _posts/2020-08-11-welcome-to-jekyll.markdown/#excerpt
  Pre-Render Hooks: _posts/2020-08-11-welcome-to-jekyll.markdown/#excerpt
  Rendering Markup: _posts/2020-08-11-welcome-to-jekyll.markdown/#excerpt
         Rendering: 404.html
  Pre-Render Hooks: 404.html
  Rendering Markup: 404.html
  Rendering Layout: 404.html
         Rendering: about.markdown
  Pre-Render Hooks: about.markdown
  Rendering Markup: about.markdown
  Rendering Layout: about.markdown
         Rendering: index.markdown
  Pre-Render Hooks: index.markdown
  Rendering Markup: index.markdown
  Rendering Layout: index.markdown
         Rendering: assets/main.scss
  Pre-Render Hooks: assets/main.scss
  Rendering Markup: assets/main.scss
         Rendering: feed.xml
  Pre-Render Hooks: feed.xml
  Rendering Liquid: feed.xml
  Rendering Markup: feed.xml
  Rendering Layout: feed.xml
         Rendering: assets/main.css.map
  Pre-Render Hooks: assets/main.css.map
  Rendering Markup: assets/main.css.map
```

There is one document- the post- that entertains the `...#excerpt` thing.

Why don't the others? Why sometimes it exists and sometimes it doesn't? How/why can I make it 'go away' by defining `excerpts: ""` with front matter?

I am writing and responding because I, and others, honestly don't understand how this works.

**Comment by ashmaroli** [comment]
- Before v4.1.0, Excerpts could be generated only for *documents* in a *collection*. Now, they can be generated for *standalone pages* as well.
- Under the hood, there are differences between *documents* in a *collection* and *standalone pages*. What you can do with *documents* may or may not be possible with *pages*.
- When creating a new site via `jekyll new`, there is only one collection &mdash; posts. Everything else are *standalone pages* which do not generate pages by default.
- In your site, `_statics/home/home.md/#excerpt` is not a new file but a subset of the document `_statics/home/home.md`.
- By default, excerpts are not generated for *documents* either. They are triggered when a layout / include file / plugin references Liquid `{{ page.excerpt }}`.

**Comment by ashmaroli** [comment]
> why can I make it 'go away' by defining `excerpts: ""` with front matter?

It is a feature that you can use to inject custom excerpt for your document.
For example, consider the following **document**:

```
---
excerpt: Lorem ipsum dolor sit amet
---

Hello World! This is a test post.

Enough about intro, lets get to the point.
```
When a layout has `<p class="excerpt">{{ page.excerpt }}</p>`, the rendered markup would be:
```html
<p>Lorem ipsum dolor sit amet</p>
```
instead of the following:
```html
<p>Hello World! This is a test post.</p>
```

The output `/#excerpt` you see with `--verbose` is only for *excerpt sources generated by Jekyll* not for user-provided custom ones.

**Comment by jaybe-jekyll** [comment]
Thanks @ashmaroli. That is helpful.

So, in summary... if an `excerpt: ...` is not provided by configuration, then #excerpts _are_ generated for `Collections` documents.

`Posts` are a [default] `Collection`, therefore- without an explicit `excerpt: ...`, they also will render an `#excerpt`. New `Collections` will honor the same behavior.

I see your update above whereby you struck on the creation by default; thanks for doing that because that had me further confused until you updated it!
