### ISSUE TITLE
jsonify filter changes/breaks with presence of collection configuration

### ISSUE THREAD

**Issue by jaybe-jekyll** [jekyll/jekyll#8336]
Have been working on a lovely way to expose site, page, etc. variables within a jekyll site for design, programming, learning, visibility, etc.

This is really interesting and helpful.

However while working on it, came across a situation whereby the _presence_ of a single collection affects the output of the `jsonify` filter... which results in failure of routines that worked upon pages _without the presence_ of a Collection.

Restating, it seems that everything works great when minimally showing how it works - with pages only.

Once you add a single, simple collection... the output of `jsonify` apparently changes, and to the point of breaking things.

@ashmaroli - here is a demonstration repository-

- https://github.com/jaybe-jekyll/stript

Pull that minimal example down and serve it. For fun and ease, you can use, e.g. `make s o=-o`

Check out both `index.html` and `test.html`.  Awesome! Right?

The debugging variables desired are defined in each page's front matter as-

```yaml
debug:
  variables:
    - page
    - site.collections
```

... etc.

Now...

Go into the `_config.yml` and simply _uncomment_ the collection for `_tests`.

Now serve it again.

You'll note that:

1. The collection gets produced and it reveals variables data as hoped- within `_tests/debug.html`.

2. The *formerly-working* pages at `/index.html` and `test.html` are broken!?

  - `site` and `site.collections` no longer expose themselves because `jsonify` breaks with the presence of the collection configuration. Comment it out again, re-serve, and it works again.

3. The page source exposes a problem with the jsonify:javascript when a collection is configured/active-

  - For example, in `index.html` --
    - `SyntaxError: JSON Parse error: Expected ']'`

One can compare the `jsonify` before and after adding/removing the collection and comprehend a difference.

Please take a look and let me know your thoughts. Perhaps I'm overlooking some comprehension.  Thanks!

**Comment by ashmaroli** [comment]
@jaybe-jekyll Nothing's broken.
I think your frontend script could be the reason behind this.

You don't need to have a custom collection. Just moving the contents of `_tests/debug.md` into a *post* is sufficient.
Either ways, like I said in a previous issue ticket, *stand-alone pages* and *documents from a collection* have different behavior.

---

P.S. Have you checked out the plugin `jekyll-admin`?
It provides a similar info, if you're interested.
Just edit your `Gemfile` to following, serve and point your browser to `/_api/collections`:
```ruby
gem "jekyll-admin", group: :jekyll_plugins
```

**Comment by jaybe-jekyll** [comment]
> @jaybe-jekyll Nothing's broken.
> I think your frontend script could be the reason behind this.

I feel the point may not have been stated clearly enough.

Regardless of what I'm doing with the `jsonify` output... the point is... that *once* a collection is *configured* and enacted, the output of `jsonify` *changes*... for a **page** that previously did *not* have problematic jsonification. That *change* in behavior causes problems for the **page** - not the collection document.

A question then-

- why would "adding a configuration for a `collection`" result in the output of `jsonify` *changing* on a *page* - that is *not* a collection? ... and on a page that **previously worked fine** prior to adding a collection configuration? The json is literally *different* on the page after merely adding a collection configuration.

> 
> You don't need to have a custom collection. 

I know I don't need anything. This isn't the point.

The collection was only created for the purposes of simply *configuring a single collection* for the purposes of showing that **page** jsonification changes and breaks with the collections presence. The content of the collection test document (existing or not) matters not. Aside, interestingly, the collections document doesn't suffer from the breakage... only the page(s) do (and only unless and after a collection is configured/added).

>Just moving the contents of `_tests/debug.md` into a _post_ is sufficient.
> Either ways, like I said in a previous issue ticket, _stand-alone pages_ and _documents from a collection_ have different behavior.

I recall what you said in another ticket whereby the report was initially dismissed as not a bug that ended up actually being a bug once we understood and experienced which has now been fixed. Thank you!

I understand the backend behavior of `pages` and `collection` documents differ.

This is issue, stated again... is-

- The *contents* of `jsonify`- for a **page**... once correct... will **change** from one state (functional) ... to another state (different - resulting in non-functional)- with the simple addition of a configuration presence for a collection.

Adding a collection, at all, results in the json changing and breaking... on the **page** (not the collection).

Why would simply having a collection configured *change* the output of `jsonify` on a **page** that has nothing to do with a **collection**?

Did you pull the repo and serve it with the `collection` commented out (initial repo state) and see `index.html` properly rendering... and then uncomment the `collection` and serve again... and see the output of jsonify **in the `index.html`** *page* change and differ (and break)?

> 
> P.S. Have you checked out the plugin `jekyll-admin`?
> It provides a similar info, if you're interested.
> Just edit your `Gemfile` to following, serve and point your browser to `/_api/collections`:

I have. jekyll-admin is a wonderful addition and a nice piece of work.

> 
> ```ruby
> gem "jekyll-admin", group: :jekyll_plugins
> ```

Thanks for taking another closer look at this.

And thank you for realizing the bug and fixing re: 

> Summary
>
> Livereload should be triggered even if the site doesn't have a single standalone page.
>
>Context
>
>Resolves #8332
>/cc @jaybe-jekyll

**Comment by ashmaroli** [comment]
Lots of noise and confusion here..
Follow these steps to understand my point:
1. Remove your JavaScript or comment it out.
2. manually code in the jsonify templates in the layout itself so that all pages serve the same variables:
```html
<body>
    <h1>{{ page.title }}</h1>
    <section>
        {{ content }}
    </section>
    <section>
        <h2>site</h2>
        <div><pre>{{ site | jsonify }}</pre></div>
        <h2>page</h2>
        <div><pre>{{ page | jsonify }}</pre></div>
        <h2>site.pages</h2>
        <div><pre>{{ site.pages | jsonify }}</pre></div>
        <h2>site.collections</h2>
        <div><pre>{{ site.collections | jsonify }}</pre></div>
    </section>
    <footer>
        <p>&copy; {{ "now" | date: "%Y" }}</p>
    </footer>
</body>
```
3.  Serve and inspect views
4. Update config, re-serve and inspect in a new browser window
5, Compare and comprehend

`jsonify` outputs the JSON representation of the variable as exposed to Liquid templates.
The `docs` array of a collection is represented as the array of rendered HTML string contents of the document.

*You need not update the config and re-serve. Simply create a valid post with the contents of `_test/debug.html`*

---

Perhaps what's throwing you off is the `page` variable. The `page` variable in a Liquid context refers to the current source material. `{{ page }}` refers to `index.md` at URL `/`; refers to `test.md` at `/test.html`; refers to `_test/debug.md` at `/test/debug.html`

**Comment by jaybe-jekyll** [comment]
Noise? That seems and feels inappropriate and disrespectful.

Confusion? Yes, that is why I am writing and collaborating and seeking understanding.

The comparison and additional information was helpful. Thank you for that information.

To clarify then and hopefully help others in the future, what is happening is that the *rendered content* of pages and collections, etc. are being represented within the `jsonify` output of the `site` variable.

This creates a mirroring effect of the content within the content within the content...

A *solution* to *working around* this behavior may be to approach the challenge differently. One could create/generate the JSON themselves and pick and choose what is and is not included (such as the rendered values of `html_pages`, `output`, etc.)... thereby filtering out the content causing the mirroring.

I pursued this approach and it was indeed much easier to manage. Further, the produced JSON then also *continued to function* with the javascript `pretty JSON print` approach I began this inquiry with.

Hope this information may be helpful to others that find themselves along this path.

**Comment by ashmaroli** [comment]
> Noise? That seems and feels inappropriate and disrespectful.

I apologize. That was not the intention.
By *noise*, I was referring to the back-and-forth dialogue without a clear focus and direction &mdash; You're saying one thing, I'm saying something else..
If a third-party were to read the comments here to try and follow the conversation, they'd get confused more than initially were.

Regarding the rest of your conclusions, yes, you're correct.
There won't be a change in the filter's behavior because it works as intended.

Because of Jekyll's flexibility, you can always write a plugin to get the desired output for your site.
