### ISSUE TITLE
When rendering, `{{ site.config }}`, I expected to see the name fo the config.

### ISSUE THREAD

**Issue by AndrewDVXI** [jekyll/jekyll#8341]
When rendering, `{{ site.config }}`, I expected to see the name fo the config.

e.g. `_test_config.yml`

_Originally posted by @jaybe-jekyll in https://github.com/jekyll/jekyll/issues/8339#issuecomment-673592374_

**Comment by jaybe-jekyll** [comment]
The originating issue, #8339, has been *closed*, and *this* newly-and-recently-opened issue has appeared, and it is open and not closed. I don't understand this process or reasoning and it does not seem to make sense.

If this issue (#8339) is open and relevant and deserving of attention (@ashmaroli referencing @jekyll/core), then I request and recommend the originating issue, #8339, be reopened and function as the origin, and this instance of the issue be closed.
