### ISSUE TITLE
feat: Themes default pages

### ISSUE THREAD

**Issue by IJustDev** [jekyll/jekyll#8345]
## Summary

Hey there!
I would like to have a possibility to use the themes index.html as a my sites index.html. Currently - at least as far as i know only directories like `assets`, `_layouts` and `_includes` are used from the theme gem.

I want to create a `index.html` in my theme, bundle it and once used installed, my site should use this index.html if there isn't a file that overrides it, like this

```gemspec
spec.files         = `git ls-files -z`.split("\x0").select { |f| f.match(%r!^(assets|_layouts|_includes|_sass|LICENSE|README|_config\.yml|blog\.html|filter\.html|index\.html|contact\.html)!i) }
```

This does not exclude creating and shipping other pages like a default `blog.html` to the site. I would suggest he can set this up in the gemspec file which files should be shipped.

## Motivation
If you create multiple pages with the same layout for example affiliate sites, that are all the same, you can update the content once and all pages will be affected which helps a lot for this usecase.

## Drawbacks
There shouldn't be any drawbacks since the user himself can decide whether to use the themes index.html or one created for this special site.

Thanks a lot!
IJustDev

**Comment by ashmaroli** [comment]
Sorry @IJustDev I fail to see the value in this additional complexity even with your given example.
Themes are not meant to dictate content.
Therefore, this will not make it into the core.

You'll have to get a plugin written for this functionality.

**Comment by IJustDev** [comment]
Nevertheless, thank you very much.

Is your plugin @ashmaroli jekyll extract https://github.com/ashmaroli/jekyll-extract one that does similar things?

**Comment by ashmaroli** [comment]
`jekyll-extract` simply copies contents of a theme-gem into your source directory.
If you bundle an `index.html` inside a theme-gem, affiliate-site users will have to manually run `jekyll extract` and override `index.html` at their source.
