### ISSUE TITLE
Warning issued for redirect pages

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll#8346]
With the merge of #8342 warnings are issued when a site uses the `jekyll-redirect-from` plugin:
```
Conflict: The URL 'jekyll/docs/_site/conduct/index.html' is the destination for the following pages: redirect.html, redirect.html
```
This should have been caught during the review, though.
Since it slipped through, the way forward would be to **have an explicit check for a redirect-page** and not issue the warning since the use of same permalink is deliberate.

/cc @SeekingMeaning

**Comment by SeekingMeaning** [comment]
`lib/jekyll/commands/doctor.rb`

```patch
 def collect_urls(urls, things, destination)
   things.each do |thing|
+    next if thing.is_a? JekyllRedirectFrom::RedirectPage
     dest = thing.destination(destination)
     if urls[dest]
       urls[dest] << thing.path
     else
       urls[dest] = [thing.path]
     end
   end
   urls
 end
```

What would be a good way to check if `jekyll-redirect-from` is installed?
