### ISSUE TITLE
Pagination page does not work when it included.

### ISSUE THREAD

**Issue by codelabor** [jekyll/jekyll#8378]
Pagination page (/blog/index.html) works find when I call /blog URL.

But when I include relatively like this, pagination does not work.
```
{% include_relative blog/index.html %}
```

How can I include pagination page into another page?

**Comment by ashmaroli** [comment]
Why would you want to include a pagination page somewhere else?
Sorry, trying to understand the use case here..

**Comment by codelabor** [comment]
Can I include blog summary page with pagination like this?

![usecase](https://user-images.githubusercontent.com/815767/92483765-2e6f1e00-f224-11ea-8419-de4fb601eb78.png)

**Comment by ashmaroli** [comment]
Think about this from a static site's perspective. How would you achieve this if you were to write HTML by hand?
Embed HTML via an `<iframe>` tagset?
Toggle visibility via JavaScript?

`[More]` navigates to `/blog/index.html`. But what if a visitor were to click on one of the pagination pager? Where would they end up?

Either ways, this discussion doesn't seem to point towards a bug in Jekyll. Therefore, I'm closing this.
I suggest you post this question on our Community Forum at https://talk.jekyllrb.com/
