### ISSUE TITLE
{{ post.content | jsonify }} causes JSON parse error

### ISSUE THREAD

**Issue by frippz** [jekyll/jekyll#8382]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |      Alpine Linux 3.11 (Docker dev env) / Ubuntu 18.04.5 (Github Actions OS)      |
| `jekyll`         | Latest     |
| `github-pages`   | No     |

Problem is reproducible in two different environments (as listed above), both using Ruby 2.6.

---

## Expected Behaviour

```liquid
"content_html": {{ post.content | jsonify }}
```

should output

```json
"content_html": "<p>jsonified html content</p>"
```

## Current Behavior

A bad string literal is inserted before jsonified content is generated causing a `SyntaxError: JSON.parse: bad control character in string literal` when opening the resulting `feed.json` file in for example Firefox. The feed is not considered valid and is rejected by feed readers like [NetNewsWire](https://ranchero.com/netnewswire/) and [Feedbin](https://feedbin.com/).

```json
"content_html": "
<p>jsonified html content</p>"
```

## Code Sample

**Full project:**
https://github.com/frippz/frippz.se/

**The specific file (and highlighted line) this bug is appearing in:**
https://github.com/frippz/frippz.se/blob/master/feed.json#L40

**Live sample of the generated JSON file:**
https://frippz.se/feed.json

**Comment by josisusan** [comment]
@frippz I did clone your repo and ran `docker-compose`. It showed the same error. I think the error is in the content itself. So, I tried escape the quotes and greater than and less than braces.
```
"content_html":  {{ post.content | escape | jsonify }}
```
and now its working fine. Hope it helps.

**Comment by frippz** [comment]
Hi @josisusan and thanks for taking at look at this. Correct me if I’m wrong, but won’t the `escape` filter also escape the HTML? When I try this locally and then add the local feed in NetNewsWire, the brackets in the markup are rendered as text, which sort of breaks the feed from another end. 😊

**Comment by frippz** [comment]
Looks like [jekyll-tidy](https://github.com/apsislabs/jekyll-tidy) was the culprit.
