### ISSUE TITLE
feat: Localize site title?

### ISSUE THREAD

**Issue by krzysztofmajewski** [jekyll/jekyll#8397]
I will keep this short in case there is already a way to do this. 

I would like to localize the `<title>` in the `<head>` of my landing page, so that it appears in the correct language. 
I am using the `polyglot` plugin for localization.
The title is generated in `_includes/head.html` by the `seo` plugin:
```
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {%- seo -%}
```

I can override this title by specifying a title in the front matter of my site's `index.md`. However, there are no Liquid tags allowed in the front matter, so I can't use the usual localization trick:
```
title: {{ site.data.locales['title'] }}
```

Is there a workaround for this? Note that for pages other than `index.md`, I can localize the title simply by hardcoding it in the front matter of each page (English title on the English pages, French title on the French pages). But `index.md` is a special case: there is only one `index.md`. 

If there is no workaround, then the feature request is simply to provide a way to localize the title for the site's landing page.

**Comment by krzysztofmajewski** [comment]
OK, I found a workaround. It turns out the `seo` plugin can be customized to turn off the `<title>` generation: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md

Leaving the issue open FYI.

**Comment by DirtyF** [comment]
OK, closing as it's not related to the core.
