### ISSUE TITLE
I can't upload any posts and edit index :( 

### ISSUE THREAD

**Issue by midannii** [jekyll/jekyll#8416]
Hi, I'm in jekyll blog since 04-2020
BUT I faced a huge trouble with it.

I can't upload any post even if I fetch to my github as usual.
It's just a disaster for me with this troubleshooting
plz somebody help me :( 

- Mac catalina 10.15.8
- gem version 3.1.4
- jekyll version 4.1.1
- ruby version 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin19]

**Comment by DirtyF** [comment]
Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage.
⚠️ This repository issues are dedicated to **documented bugs only**.
