### ISSUE TITLE
feat: Allow reversing date-title order for Post filename format? 

### ISSUE THREAD

**Issue by drscotthawley** [jekyll/jekyll#8423]
## Summary

(Reposting from [this StackOverflow question](https://stackoverflow.com/questions/64161248/change-jekyll-post-filename-format-to-date-last-title-first).)
I want to move the date from the front to the end of the filename. How can we do that? Is there a setting in `_config.yml` or a plugin available? Haven't found any such thing yet. 

## Motivation

Because it would make using autocomplete easier when looking for posts in the shell (i.e. I remember the title I used but not the date I started writing). Similarly inconvenient, the abbreviating display of filenames in GUIs means that usually only the date shows before the ellipsis ("...") and not the title.

## Guide-level explanation

Instead of having files titled like "2020-10-04-My-Title.md", they could be "My-Title-2020-10-04.md".
This could be introduced via a variable such as `date_last` which defaults to False, but if the user set it to True then it would allow the user to put the date last.   Or perhaps instead of requiring the user to tell it which ordering to use, Jekyll could support *both* ordering methods (i.e., date-title and title-date). 

## Reference-level explanation

It could be an optional variable like "date_last" set in `_config.yml` or perhaps a plugin such as "jekyll-dates-last".  Or allow both orderings to be used for filenames with no parameter needing to be set. 

## Drawbacks

Depending on how you've written the rest of the Jekyll code, this could require only a small change in one location, namely the initial filename-parsing.  
The URLs could still be left as they are, e.g. 2020/10/3/My-Title/
If, however, the filename-to-date conversion happens in many places in the code, then each of those instances would need changing. 

## Unresolved Questions

I'm not sure.

**Comment by DirtyF** [comment]
`YYYY-MM-DD-title.md` is a Jekyll convention for [posts](https://jekyllrb.com/docs/posts/). You can always create a custom [collection](https://jekyllrb.com/docs/collections/) named `_articles` for instance, Jekyll don't enforce the date in the filename.

**Comment by drscotthawley** [comment]
Right. Exactly: I'm suggesting that that convention be _relaxed_.

I do want to retain dates.  Collections won't work for me  -- I was already aware of them before I posted this -- because I'm using `Fastpages` which only supports `_posts/` and `_notebooks/`.
