### ISSUE TITLE
Do not use https://github.com/Shopify/liquid/pull/1300/

### ISSUE THREAD

**Issue by borisschapira** [jekyll/jekyll#8438]
To support Liquid language evolution https://github.com/Shopify/liquid/pull/1300, do not use `Liquid::Expression::MethodLiteral` in Jekyll filters management.

https://github.com/jekyll/jekyll/blob/c9b84e2b354067e61cf9878f27665c5c1c02481c/lib/jekyll/filters.rb#L407

**Comment by ashmaroli** [comment]
Hi Boris :wave:
Thank you opening this ticket.

As I see it, Liquid is on the path to a major version bump.. i.e., Liquid v5..
So there's a chance that when they do release, it is not going to affect existing Jekyll sites by default.

If that is indeed the case, Liquid v5 will be supported only by Jekyll 5..

**Comment by borisschapira** [comment]
Oh thanks, I didn't know. I'll close this to avoid unnecessary noise.

**Comment by ashmaroli** [comment]
That said, I have no official confirmation that the next release is indeed going to be Liquid v5.
Just my deduction from gauging the upstream changes..
