### ISSUE TITLE
docs: Augment the organization example of data files with a sort by random key 

### ISSUE THREAD

**Issue by user414** [jekyll/jekyll#8440]
First let me start by saying thank you for the great project. It's cringe worthy to remember a time before jekyll. I wrote this piece of code to solve the common problem trying to sort data files objects since all the solution on the web use various strategy of capture, array, split, etc... which are lengthy. I forgot the submit the code upstream, and had to figure it out again, and now I can't remember which projects it belongs to. Therefore, I thought it would be a good place to add it in the jekyll documentation itself, on this page

https://jekyllrb.com/docs/datafiles/

either as part of the organization example or stand-alone. The organization example with the sort by username would become

```
<ul>
{% assign files = site.data.orgs | group_by_exp: "item", "item[1].username" | sort: "name" %}
{% for team_hash in files %}
    {% assign org = team_hash.items[0][1] %}
        <li>
            <a href="https://github.com/{{ org.username }}">
                {{ org.name }}
            </a>
            ({{ org.members | size }} members)
        </li>
{% endfor %}
</ul>
```

In case it's unclear what it does, it use the functionality of group_by_exp to in effect swap the key of the hash, which is usually the filename, to the key we want to sort by so that we can bypass the fact that we cannot sort by object attribute in the hash. The value "username" can be replaced by any attribute to act as the sorting criteria.

**Comment by ashmaroli** [comment]
Unfortunately, the above Liquid code is very hard to understand without proper context.
For example, just by reading the above post, I have no idea what structure `site.data.orgs` has and I'm clueless as to what the final structure is..

Therefore, it is unclear what problem this intends to report..

**Comment by user414** [comment]
@ashmaroli Thanks for your reply, I apologize if it was not clear the example is in the context of the jekyll documentation here

https://jekyllrb.com/docs/datafiles/

The orgs structure is part of the example on that page. This is not intend to report any problem but simply add to the example already in the documentation, by supplementing the existing example in the documentation with a sort, which in my opinion is a common use case. Hopefully that helps clarifying the issue. Please do not hesitate if you have any questions.

**Comment by ashmaroli** [comment]
Feel free to submit a pull request, @user414

**Comment by DirtyF** [comment]
There's so much you can't do with Liquid, I don't see why we would add this particular example over another.
