### ISSUE TITLE
Feature request: Allow <q></q> as smart quotes settings

### ISSUE THREAD

**Issue by kslstn** [jekyll/jekyll#8441]
## Summary
Add support for html tags in the `smart_quotes` setting for `kramdown` in `config.yml`—specifically: `<q>` and `</q>`.

## Motivation
Use of quotation marks is different between languages. Americans do “this”, the French do «cette», etc. The settings let one apply one style for the whole site, but when a site has pages in multiple languages, this is doesn't suffice. By inserting `<q></q>` instead of ”“, the browser could apply smart quotes as it sees just and site owners can define them in CSS. After all, the page's `lang` attribute can be used in a CSS selector to create different styles depending on language of a page or section.

## Guide-level explanation
The default setting for `smart_quotes` is `[“lsquo”, “rsquo”, “ldquo”, “rdquo”]`. Currently, when we try `[“lsquo”, “rsquo”, “<q>”, “</q>”]` instead, we get an error:
```
Liquid Exception: Can't handle generic non-integer character reference '</q>'
```
Possibly, just making the validation of the setting less strict would already be enough to add this feature.

## Drawbacks
I don't know the rationale behind the somewhat outdated way of encoding the quotation marks in the settings this way, perhaps allowing more characters could lead to encoding issues?

**Comment by ashmaroli** [comment]
@kslstn Jekyll doesn't manage smart quotes directly. It delegates the task to `kramdown`.
I suggest you reach out to that project at https://github.com/gettalong/kramdown

**Comment by kslstn** [comment]
Thanks! It looks like [it has been proposed](https://github.com/gettalong/kramdown/issues/61) before.
