### ISSUE TITLE
Syntax Highlight in Black background ?

### ISSUE THREAD

**Issue by Mayurji** [jekyll/jekyll#8442]
Hello

I am new to Jekyll and trying to find my way around it.

Recently, I've added python code using Code block and mention it i have black background for webpages.
It seems like the code block appears but it is over shadowed by background color 

```python
import numpy as np
```

Code block over shadowed 

![image](https://user-images.githubusercontent.com/10477789/96553245-82186100-12d2-11eb-9881-6b7bcb1c0d55.png)

![image](https://user-images.githubusercontent.com/10477789/96553372-b12ed280-12d2-11eb-99a2-7b2156d27f32.png)

I am not sure, what i am doing wrong. Help me out.

**Comment by ashmaroli** [comment]
@Mayurji The issue you're facing is actually CSS-related.
Jekyll has very little to do with this.

If you're using a theme, asking the theme's author for support would be the apt route to resolving this.
