### ISSUE TITLE
Jekyll theme does not work in production (github pages)

### ISSUE THREAD

**Issue by yshmarov** [jekyll/jekyll#8468]
I installed jekyll and hosted it on github paged. The default setup:

Gemfile
```
gem "minima"
```

_config.yml
```
theme: minima
```
****
**Problem**: I noticed that github pages has a different (older) source for `minima` theme that is different from edge `jekyll/minima`. To use the edge `minima` I had to:

Gemfile
```
gem "minima", git: "https://github.com/jekyll/minima"
```

It works in development, but not in production with github pages. To make it work in production I had to edit `_config.yml`:

```
remote_theme: jekyll/minima 
```

So in the end I'm in a funny situation:
* `theme: minima` works in development, but not in production.
* `remote_theme: jekyll/minima` works in production, but not in development.

Or am I doing something wrong? Thanks for looking into it 🧐

**Comment by ChrisHammond** [comment]
I'm fairly new to this, but doesn't GitHub pages only supposed Jekyll 3.9?

**Comment by ashmaroli** [comment]
> `remote_theme: jekyll/minima` works in production, but not in development.

Could you clarify this a bit more?
Why do you say `remote_theme` doesn't work in development?

**Comment by yshmarov** [comment]
@ChrisHammond indeed, [you're right](https://github.com/github/pages-gem/issues/651)
****
@ashmaroli if in _config.yml I put `remote_theme: jekyll/minima`, the theme does not get applied not the application on localhost/development. 

But `remote_theme: jekyll/minima` is the only way to get the theme applied on github_pages/producion.

You can [see my setup here](https://github.com/yshmarov/yshmarov.github.io)

**Comment by ashmaroli** [comment]
To use the `remote_theme` feature, you need to include the gem `jekyll-remote-theme` in your Gemfile:
```ruby
group :jekyll_plugins do
  gem 'jekyll-feed', '~> 0.12'
  gem 'jekyll-remote-theme'
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
end
```

**Comment by yshmarov** [comment]
@ashmaroli thanks a lot! it totally fixed everything!

**Comment by patreeceeo** [comment]
Hi, does anyone know if this still works? I installed the remote theme gem and replaced `theme: minima` with `remote_theme: jekyll/minima`. It works fine locally, but I still see the old theme in production.

**Comment by patreeceeo** [comment]
ah nevermind, started working ~30 minutes after deploy.

**Comment by SamHobbsOrg** [comment]
I apologize, I did not know that my commits will be posted here. I do not know if my problem is the same as here but my problem persists.
