### ISSUE TITLE
docs: change LICENSE to LICENSE.md

### ISSUE THREAD

**Issue by jeremygautama** [jekyll/jekyll#8475]
## Motivation
It has a nice coherence for the format of a license :D 👍 

## Suggestion
Change LICENSE to LICENSE.md

**Comment by ashmaroli** [comment]
But the contents of the file are not Markdown just plain text..

**Comment by jeremygautama** [comment]
It could be either .md or .txt

Here's a link to the statement I made above
[https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository](url)

**Comment by jeremygautama** [comment]
[https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository)

**Comment by jeremygautama** [comment]
It could be either .md or .txt

Here's a link to the statement I made above
[https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository)
![license github](https://user-images.githubusercontent.com/66259053/99630198-0560da00-2a6c-11eb-8dd7-0f224a6b4b42.jpg)

**Comment by DirtyF** [comment]
Won't fix, GitHub adds LICENSE without any file extension when you use github.new
