### ISSUE TITLE
feat: Display which plugins were used when running `jekyll build`

### ISSUE THREAD

**Issue by ctjlewis** [jekyll/jekyll#8479]
## Summary
It would be helpful to know which plugins were used when building a site with `jekyll build`. More importantly, it is confusing to not be able to easily discern which plugins were used at build-time.

## Motivation
I added a plugin to `_config.yaml` and ran `bundle exec jekyll build`. A bunch of warning logs appear, but no mention of which plugins were loaded. Assessing which plugins were loaded seems impossible or unintuitive. 

## Suggestion
Log loaded plugins during build. Per @ashmaroli, this is done with `--verbose` flag, but should be done by default.

**Comment by ashmaroli** [comment]
@ctjlewis If a plugin is issuing warnings, then it is upto the plugin to provide as helpful messages as necessary.
When you run `jekyll build` with the `--verbose` switch, you'll see `Requiring: <name of plugin or path of local plugin>` **provided that the plugin gem is loaded via the config file only and not via the `:jekyll_plugins` group in the Gemfile.**

Beyond this, things from the plugin are not in Jekyll's control and therefore not possible to monitor each and every action executed by the one or more plugins used.

**Comment by ctjlewis** [comment]
The request is then, more formally, to move these `Requiring: <name of plugin or path of local plugin>` from `--verbose` mode to default, with no further adjustments really necessary. This should be shown to the user by default IMO.

**Comment by ashmaroli** [comment]
> to move these `Requiring: <name of plugin or path of local plugin>` from `--verbose` mode to default

Sorry. I'm afraid I'll have to decline your request since the default log output shouldn't be noisy.
Agreed that *noisy* is subjective. However, Jekyll will err on the minimal side.
