### ISSUE TITLE
docs: Homebrew installation deprecated warning

### ISSUE THREAD

**Issue by Lominean** [jekyll/jekyll#8490]
## Motivation
The [installation instructions for macOS](https://jekyllrb.com/docs/installation/macos/) generate a deprecated warning on installation of Homebrew:
> Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
Bash. Please migrate to the following command:
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

https://github.com/jekyll/jekyll/blob/85508ccbf3cc6bd721c45a828cb303a450954bd6/docs/_docs/installation/macos.md#L55

## Suggestion
Change the URL as the notice suggests.

**Comment by DirtyF** [comment]
Fixed.

**Comment by Lominean** [comment]
I noticed this also applies to the rbenv section:
https://github.com/jekyll/jekyll/blob/f4a7eee57a11129a70e1894f677687a8b95f20ff/docs/_docs/installation/macos.md#L63
