### ISSUE TITLE
docs: Broken Showcase screenshots

### ISSUE THREAD

**Issue by Lominean** [jekyll/jekyll#8491]
## Motivation
All of the screenshots on the [showcase page](https://jekyllrb.com/showcase/) of the Jekyll website are broken.

## Suggestion
Make the screenshots load.

**Comment by codingedgar** [comment]
Came here to say that, it also happens on my machine.

![image](https://user-images.githubusercontent.com/10213241/100945742-a2962680-34e0-11eb-8161-56267c19ccfd.png)

**Comment by DirtyF** [comment]
Likely a very lazy-loading, I'll take a look when I have a moment, any help welcome.

**Comment by ashmaroli** [comment]
Its also possible that there's something wrong with the CloudFront instance..

**Comment by DirtyF** [comment]
Yup, there seems to be an issue with Cloudfront here:
<img width="300" alt="Capture d’écran 2020-12-03 à 13 33 20" src="https://user-images.githubusercontent.com/103008/101018706-2b0dd900-356c-11eb-8827-308ef52b315b.png">

**Comment by Lominean** [comment]
Is there really a need for a CDN (CloudFront) when utilising client side lazy-loading?

**Comment by martinmorando** [comment]
> Is there really a need for a CDN (CloudFront) when utilising client side lazy-loading?

We would have to analyze [how much would be consumed, in terms of disk space and bandwidth](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages#guidelines-for-using-github-pages), if we abandon the CDN and migrate static files to GitHub, though a CDN would be ideal, as it delivers faster.

Jekyll was initially created by GitHub's co-founder and former CEO, Tom Preston-Werner (@mojombo). Also, Jekyll is "proudly hosted by GitHub", which is now owned by Microsoft... maybe a project maintainer could consider:

1. Asking Microsoft for free CDN integration with Azure for the few static files of this widely used open-source project.
2. Asking GitHub to increment cuota limit on GitHub and see how it goes. If not, use 1.
