### ISSUE TITLE
feat: Allow Excluding Files from being rendered under a specific directory

### ISSUE THREAD

**Issue by xcodz-dot** [jekyll/jekyll#8495]
## Summary

I have a simple github pages website, but I want to exclude a folder from being rendered so that
i can keep my html and other thing there.

## Motivation

I would be good with a plugin

## Guide-level explanation

For example you have a jekyll site with this structure
```
info
 - about_us.md
 - somefile.md
downloads
 - markdown_template.md
index.md
```

And you want to exclude downloads folder from being rendered

## Reference-level explanation

Allow user to add a specific option to configuration
It can be a feild such as `exclude-files`, `exclude-directories`

I am a novice in this area so i might not help much

## Drawbacks

There are no drawbacks

## Unresolved Questions

None

**Comment by ashmaroli** [comment]
@xcodz-dot There's already an existing feature for this. Simply list your directory under the `exclude` key in your config file.
For example,
```yaml

# _config.yml

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - downloads/
```

**Comment by xcodz-dot** [comment]
thanks
