### ISSUE TITLE
feat: consider adding the loading attribute to lazyload images and iframes

### ISSUE THREAD

**Issue by jmau111** [jekyll/jekyll#8502]
## Summary

The lazy loading attribute is now part of WHATWG. It would be nice to implement it as a core feature.

[Source](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#lazy-loading-attributes)

## Motivation

While it's relatively easy to implement it at plugin's level, I think it make sense to add it as a core feature. Browser support is correct and there is no bad effect on browser versions that do not support it yet.

## Guide-level explanation

Some code could check if there's a `loading="lazy"` attribute or not and add it on the fly if image/iframe dimensions are provided.

**Comment by ashmaroli** [comment]
> it's relatively easy to implement it at plugin's level.

I welcome you to submit a pull request to add this feature to Core.
The maintainers here will review the implementation and will either:
- ask for additional changes
- merge into Core
- reject merge and recommend you to publish it as a plugin.

**Comment by jmau111** [comment]
@ashmaroli hi, thanks for your quick response.
I said it's easy, but it's from my perspective as I control the code ^^, doing the same at core level is a different story.

I know Ruby and stuff, but, honestly, I don't know if I can take all cases into account. Otherwise, I would already have done my pull request.

Is it a feature that makes sense for you? Before developing whatever module, I wanted to discuss that.

**Comment by ashmaroli** [comment]
Honestly, I don't see how Jekyll would be able to do this for users.
Jekyll doesn't directly convert Markdown into HTML. It delegates that task to kramdown (or whatever engine the user chooses)..
Jekyll doesn't directly generate raw HTML either. It expects users to provide Liquid templates either via theme-gems or by having them placed at the source in predesignated directories.

So, when you said that *implementing the feature is relatively easy*, I thought it'd be interesting to see how *you'd* pull it off.. :wink:

**Comment by jmau111** [comment]
I made a `Jekyll::Converters::Markdown` with a regex that target IMG tags, I also use it to add automatic nextgen formats.
I use this approach to add automatic anchor links without javascript.

It has very little impact on build time in my case, it's totally palatable.

**Comment by ashmaroli** [comment]
That sounds awesome!
So how does your plugin handle `![Some image](url-to-image)`?
Either ways, you're welcome to submit a pull request.

**Comment by jmau111** [comment]
In fact at this "time" markdown has already been converted into html, that's why I can add my gsub. I'll try to send a PR, I need to read the contributor guide before.

**Comment by jmau111** [comment]
All in all, it does not make sense as there's no way to determine what's above the fold and what isn't which is problematic for a core feature. I'll probably keep my plugin for now. Thanks for your response.
