### ISSUE TITLE
feat: Livereload by default

### ISSUE THREAD

**Issue by caseywatts** [jekyll/jekyll#8515]
## Summary and Motivation
I love that that have baked livereload in to Jekyll directly. It's critical to my workflow when doing design work on pages, and I'm so happy it's in jekyll directly now.

[Documenting it in the initial setup documentation](https://github.com/jekyll/jekyll/pull/8355) has been done already, and that is a step in the right direction! (ty @DespertaWeb and @DirtyF for doing that documentation change!)

It is such a commonly used and desired feature once people know about it, let's make it the default! Everyone I have talked to about livereload is mind-blown that this workflow is possible. They are also surprised that they didn't know about it.

## Guide-level explanation

> Jekyll automatically refreshes the page with each change you make to the source files, via "livereload." To see this work, simply edit and save a source file after making a change, and the `jekyll serve` command will pick that up and reload the page.

## Reference-level explanation

* This is changing the default of a flag that already exists
* We may want a flag to disable livereload once this is the default
* Do we already have warnings when there are any issues invoking the `--livereload` flag? I can't imagine what they would be, just covering bases here.

## Drawbacks
I'm curious if there are any drawbacks! I can't think of any.

## Unresolved Questions
n/a

**Comment by ashmaroli** [comment]
@caseywatts Thank you for requesting, but I have to disappoint you.
Livereload is not entirely error-free / bug-free / trouble-free yet. So we won't enable it by default.

If you find having to type `--livereload` each time you start the server, cumbersome, you can alternatively just set it once in your config file and start the server normally thenceforth.

```yaml
# in _config.yml

livereload: true
```
```sh
# on the terminal

bundle exec jekyll s
```
