### ISSUE TITLE
Jekyll 4.2.0 won't serve -- can't find gem file

### ISSUE THREAD

**Issue by davidhoyle** [jekyll/jekyll#8531]
I can install and build: 
dhoyle-MBP15-10566:myblog dhoyle$ jekyll -v
jekyll 4.2.0
dhoyle-MBP15-10566:myblog dhoyle$ which ruby
/usr/local/opt/ruby/bin/ruby
dhoyle-MBP15-10566:myblog dhoyle$ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin18]
dhoyle-MBP15-10566:myblog dhoyle$ gem -v
3.2.4
dhoyle-MBP15-10566:myblog dhoyle$ 

But I can't serve, I get: 

dhoyle-MBP15-10566:myblog dhoyle$ bundle exec jekyll serve
Configuration file: /Users/dhoyle/myblog/_config.yml
            Source: /Users/dhoyle/myblog
       Destination: /Users/dhoyle/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 0.27 seconds.
 Auto-regeneration: enabled for '/Users/dhoyle/myblog'
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
	
I tried: 
sudo rm -rf _site
bundle update
bundle exec jekyll serve

But I'm still getting the same error. Can you tell me how I can get/load that file so jekyll serve will work?

**Comment by ashmaroli** [comment]
run `bundle add webrick`.

**Comment by davidhoyle** [comment]
That worked, thanks very much @ashmaroli!

**Comment by kmk3** [comment]
Duplicate of #8523.

**Comment by ck-pro** [comment]
> run `bundle add webrick`.

worked like a charm for me. Thanks!
