### ISSUE TITLE
When developing locally, Jekyll's latest version is not using localhost for site.url

### ISSUE THREAD

**Issue by ravgeetdhillon** [jekyll/jekyll#8541]
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the contributing document at https://jekyllrb.com/docs/contributing/

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Ubuntu | 20.04          |
| `jekyll`         | 4.2.0     |
| `github-pages`         | No     |
---

## Expected Behaviour

When developing locally, Jekyll should use `localhost:port` for `site.url` and `absolute_url` filter, rather than the url provided in `_config.yml`.

## Current Behavior

I just upgraded my website to use Jekyll v4.2.0.

This is my _config.yml

```
url: https://example.com
```

Now when I do `bundle exec jekyll serve` or `jekyll serve`, my `site.url` and `absolute_url` use the `https://example.com`.

Before upgradation, everything was running super fine.

**Comment by ashmaroli** [comment]
This was a conscious change. It was even mentioned in the release post:
https://jekyllrb.com/news/2020/12/14/jekyll-4-2-0-released/

The primary motive for the change was the idea that users needn't have to generate a production build separately for the live remote site. What one sees locally (final HTML source code) during development is what would be deployed as the live site.

If you must use the `absolute_url` and still be able to use the resulting canonical URLs to navigate through your site in development, you'll have to use any other port other than `4000`:
```
bundle exec jekyll serve --port 4001
```

**Comment by ravgeetdhillon** [comment]
Thanks @ashmaroli. After taking a clue from your suggestion, I was able to solve my issue by doing
`bundle exec jekyll serve --host localhost --port 4000`
