### ISSUE TITLE
Can't refer to ssl certificates by absolute path

### ISSUE THREAD

**Issue by bouk** [jekyll/jekyll#8552]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |    macOS 11.1        |
| `jekyll`         | 4.2.0     |

---

## Expected Behaviour

I'm able to run `jekyll serve --ssl-cert=$HOME/.lego/certificates/_.bouke.dev.crt --ssl-key=$HOME/.lego/certificates/_.bouke.dev.key` and it picks up the certificates that are in that directory

## Current Behavior
Jekyll serve crashes with:

```
/opt/homebrew/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:360:in `read': No such file or directory @ rb_sysopen - /Users/bouke/src/github.com/bouk/blog/Users/bouke/.lego/certificates/_.bouke.dev.crt (Errno::ENOENT)
```

As you can see it appends the path, even with a leading slash, to the current working directory.

**Comment by ashmaroli** [comment]
Sorry, we don't allow reading files outside your source directory for security reasons, even if the counter-argument will be along the lines of *... the `serve` command is only ever used locally.*

**Comment by bouk** [comment]
OK that makes sense. I'll just create a symlink then :+1:
