### ISSUE TITLE
feat: ability to detect drafts posts in posts loop

### ISSUE THREAD

**Issue by kaushikgopal** [jekyll/jekyll#8554]
## Summary

When you have a lot of `_drafts` and use the `jekyll serve --drafts` command, when previewing locally it can be hard to distinguish draft posts from regular posts.

It would be nice if there was some way to detect in the for loop for posts if the post being iterated through is a "draft". This way themes could tag posts accordingly with a [draft] warning or header of sorts to help distinguish it clearly for the user.

From my limited understanding of jekyll works, this would have to be baked in? vs being supported through a plugin.

```
{% for post in site.posts  %}

    {% if post.draft %}
    <div> Draft post </div>
    {% endif %}
    ...

{% endfor %}
```

It could be as simple as a tag or identifier on `post` (?)

**Comment by ashmaroli** [comment]
@kaushikgopal your use-case already works as expected. `{{ post.draft }}` will return `true` for posts that are actually drafts.

**Comment by kaushikgopal** [comment]
🤦🏽‍♂️ 🤔 i could have sworn i tried this. I tried it just now and works exactly as expected. thank you.
