### ISSUE TITLE
Missing Gem in specfile

### ISSUE THREAD

**Issue by Freed0mBear** [jekyll/jekyll#8556]
Please add:

s.add_runtime_dependency("listen",                "~> 3.4")

to the spec file.

**Comment by ashmaroli** [comment]
`listen` is an indirect dependency, i.e. it is a dependency of `jekyll-watch` which in turn is a dependency of `jekyll`.
If you want to use `listen-3.4` and above, you may run `bundle update listen` or simply `bundle update` to bump all dependencies.

**Comment by Freed0mBear** [comment]
@ashmaroli, thank you for the reply. We (Gentoo) found that jekyll-watch had a bad Gemspec file in our repository. This was fixed in https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=db5fc51bc4b1f79678ad878adb35f31ce215f961

Thanks again!
