### ISSUE TITLE
Could not find gem 'wdm (>= 0.1.0) x64-mingw32' in any of the gem sources listed in your Gemfile

### ISSUE THREAD

**Issue by wongyah** [jekyll/jekyll#8558]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |   Windows_64bit         |
| `jekyll`         |  4.2.0   |
| `github-pages`   |  No   |

---

## Expected Behaviour

I am following the Docs to learn how to use Jekyll.  I just expect the behavior is same to what the Docs says.

## Current Behavior

![image](https://user-images.githubusercontent.com/38174537/105978134-262d5780-60cd-11eb-89f2-f643916e7f08.png)

![image](https://user-images.githubusercontent.com/38174537/105978310-5d036d80-60cd-11eb-8970-fdb36fe5ee64.png)

![image](https://user-images.githubusercontent.com/38174537/105978499-950ab080-60cd-11eb-924d-037f27fc8141.png)

![image](https://user-images.githubusercontent.com/38174537/105978623-b79cc980-60cd-11eb-9cf4-e8a82bef0ecc.png)

![image](https://user-images.githubusercontent.com/38174537/105978710-d13e1100-60cd-11eb-8a09-e636653af976.png)

Nothing changed. I am stilling receiving the same message: ask me to add a line to Gemfile, and pop error message after I did what I was told to do.

## Code Sample

I followed the Docs creating the famous Hellow World file only. Nothing else.

There is a same ask-how question online:
https://stackoverflow.com/questions/38215088/could-not-find-gem-wdm-0-1-0-x64-mingw32-in-any-of-the-gem-sources-listed

**Comment by ashmaroli** [comment]
Perhaps you did not install the `wdm` gem after you added it to your Gemfile.
1. Run `bundle install`
2. Always prepend `jekyll` commands with `bundle exec`:
    ```
    bundle exec jekyll serve
    ```

**Comment by wongyah** [comment]
![image](https://user-images.githubusercontent.com/38174537/106101319-afe62f00-6178-11eb-8234-5e354624357a.png)

I am still receiving an error like this.

**Comment by wongyah** [comment]
I encounted another issue today:

After I complete the procedure introduced in ["Step by Step Tutorial" → “7. Assets”](https://jekyllrb.com/docs/step-by-step/07-assets/), an error pop up!

(Everything fine when I did the procedure in the previous section ["6. Data Files"](https://jekyllrb.com/docs/step-by-step/06-data-files/).

![image](https://user-images.githubusercontent.com/38174537/106102190-fe47fd80-6179-11eb-8a31-4b267e92f73a.png)

![image](https://user-images.githubusercontent.com/38174537/106102336-34857d00-617a-11eb-855d-fd65877a8986.png)

![image](https://user-images.githubusercontent.com/38174537/106102399-5121b500-617a-11eb-8815-ed4d1f9d6ff0.png)

**Comment by wongyah** [comment]
> ![image](https://user-images.githubusercontent.com/38174537/106101319-afe62f00-6178-11eb-8234-5e354624357a.png)
> 
> I am still receiving an error like this.
> 
> I run `bundle install` again, and noticed a message:
> 
> ![image](https://user-images.githubusercontent.com/38174537/106104404-5e8c6e80-617d-11eb-9a80-4c6e130be336.png)
> 
> The website "rubegems.org" seems to be blocked in China.
> Is this why I always got the error?
> What if I ignore the message which requires me to add `gem 'wdm', ...` in the Gemfile? Is there any bad influences?
> What shall I do in this situation?

# My solution
1. Modify the source to "https://gems.ruby-china.com"。

    ![image](https://user-images.githubusercontent.com/38174537/106218554-7530d500-6212-11eb-8d08-3d64bb0916b7.png)

2. Run ```bundle install```.

![image](https://user-images.githubusercontent.com/38174537/106218853-20da2500-6213-11eb-80ec-d46964bb73ae.png)


3. Run ``` bundle exec jekyll serve ```. The error prompt disappears 👏

![image](https://user-images.githubusercontent.com/38174537/106218897-423b1100-6213-11eb-8fdf-3cbdc8c425d9.png)
