### ISSUE TITLE
@import CSS from SCSS

### ISSUE THREAD

**Issue by davejacobs** [jekyll/jekyll#8570]
(Note: #6903 was filed for this issue in 2018, but it was locked & closed due to inactivity.)

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | macOS Big Sur           |
| `jekyll`         | Latest     |
| `github-pages`   | N/A     |

---

## Expected Behaviour

I have a CSS file—`tailwindcss/base.css`—that I'd like to import from SCSS. This is allowed [per the SCSS spec](https://sass-lang.com/documentation/at-rules/import#importing-css) and is a common pattern, particularly when interacting with node modules that provide pre-compiled CSS. This behavior is also supported by `sassc`.

The following command is expected to import the CSS file and compile it into one final file.

```scss
@import "tailwindcss/base";
```

## Current Behavior

Attempting to compile this file using `jekyll serve` fails:

```
Error: File to import not found or unreadable: tailwindcss/base. (SassC::SyntaxError)
```

All other files on the load path can be imported, but CSS from node_modules appears to fail.

This error is not present when I compile the file directly with `sassc`.

**Comment by davejacobs** [comment]
Following up on this, it might be a load path issue rather than a CSS import issue. Is the load path relative to the project root (location of `_config.yml`)? Or to the `sass_dir`?

**Comment by fauno** [comment]
are your load paths something like this?

```yaml
sass:
  load_paths:
  - node_modules
```

**Comment by davejacobs** [comment]
After fiddling with this, my load path ended up looking like this:

```yaml
sass:
  sass_dir: _sass/
  load_paths:
    - ../node_modules/
```

I only tested the `..` on a whim and was surprised that it worked. Would you consider clarifying in the documentation how this gets translated to `sassc`?

**Comment by seshrs** [comment]
According to https://github.com/jekyll/jekyll-sass-converter/issues/58, SASS load paths are relative to the site source. I think it’s worth documenting the behavior. In fact, I’m unable to find documentation on the Jekyll website about the `load_paths` option at all!

I can open a PR to address this over the weekend.
