### ISSUE TITLE
Bug: Jekyll includes path on default causing bundle exec jekyll serve to malfunction

### ISSUE THREAD

**Issue by Cheese-S** [jekyll/jekyll#8580]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Windows 10 Pro  |  19041.746  |
| `jekyll`         | Latest     |
| `github-pages`   | No     |
| `ruby`   | 3.0.0     |

---

## Expected Behaviour

Quoting the Quick-start instructions from the Jekyll website [https://jekyllrb.com/](url)

  `gem install bundler jekyll`

 ` jekyll new my-awesome-site`

  `cd my-awesome-site`

  `bundle exec jekyll serve`

The website should be up and running on the local server. 

## Current Behavior

Following exactly along with the instructions lead to the following error: 

` Error: could not read file E:/ruby/my-site/path/ruby/3.0.0/gems/jekyll-4.2.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') 
%>': Document 'path/ruby/3.0.0/gems/jekyll-4.2.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'path/ruby/3.0.0/gems/jekyll-4.2.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
                    ------------------------------------------------
      Jekyll 4.2.0   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------`

## Code Sample

```
PS E:\ruby> jekyll new my-site
Running bundle install in E:/ruby/my-site... 
  Bundler: Fetching gem metadata from https://rubygems.org/..........
  Bundler: Resolving dependencies...
  Bundler: Fetching public_suffix 4.0.6
  Bundler: Installing public_suffix 4.0.6
  Bundler: Fetching addressable 2.7.0
  Bundler: Installing addressable 2.7.0
  Bundler: Using bundler 2.2.8
  Bundler: Fetching colorator 1.1.0
  Bundler: Installing colorator 1.1.0
  Bundler: Fetching concurrent-ruby 1.1.8
  Bundler: Installing concurrent-ruby 1.1.8
  Bundler: Fetching eventmachine 1.2.7 (x64-mingw32)
  Bundler: Installing eventmachine 1.2.7 (x64-mingw32)
  Bundler: Fetching http_parser.rb 0.6.0
  Bundler: Installing http_parser.rb 0.6.0 with native extensions
  Bundler: Fetching em-websocket 0.5.2
  Bundler: Installing em-websocket 0.5.2
  Bundler: Fetching ffi 1.14.2 (x64-mingw32)
  Bundler: Installing ffi 1.14.2 (x64-mingw32)
  Bundler: Fetching forwardable-extended 2.6.0
  Bundler: Installing forwardable-extended 2.6.0
  Bundler: Fetching i18n 1.8.8
  Bundler: Installing i18n 1.8.8
  Bundler: Fetching sassc 2.4.0 (x64-mingw32)
  Bundler: Installing sassc 2.4.0 (x64-mingw32)
  Bundler: Fetching jekyll-sass-converter 2.1.0
  Bundler: Installing jekyll-sass-converter 2.1.0
  Bundler: Fetching rb-fsevent 0.10.4
  Bundler: Installing rb-fsevent 0.10.4
  Bundler: Fetching rb-inotify 0.10.1
  Bundler: Installing rb-inotify 0.10.1
  Bundler: Fetching listen 3.4.1
  Bundler: Installing listen 3.4.1
  Bundler: Fetching jekyll-watch 2.2.1
  Bundler: Installing jekyll-watch 2.2.1
  Bundler: Fetching rexml 3.2.4
  Bundler: Installing rexml 3.2.4
  Bundler: Fetching kramdown 2.3.0
  Bundler: Installing kramdown 2.3.0
  Bundler: Fetching kramdown-parser-gfm 1.1.0
  Bundler: Installing kramdown-parser-gfm 1.1.0
  Bundler: Fetching liquid 4.0.3
  Bundler: Installing liquid 4.0.3
  Bundler: Fetching mercenary 0.4.0
  Bundler: Installing mercenary 0.4.0
  Bundler: Fetching pathutil 0.16.2
  Bundler: Installing pathutil 0.16.2
  Bundler: Fetching rouge 3.26.0
  Bundler: Installing rouge 3.26.0
  Bundler: Fetching safe_yaml 1.0.5
  Bundler: Installing safe_yaml 1.0.5
  Bundler: Fetching unicode-display_width 1.7.0
  Bundler: Installing unicode-display_width 1.7.0
  Bundler: Fetching terminal-table 2.0.0
  Bundler: Installing terminal-table 2.0.0
  Bundler: Fetching jekyll 4.2.0
  Bundler: Installing jekyll 4.2.0
  Bundler: Fetching jekyll-feed 0.15.1
  Bundler: Installing jekyll-feed 0.15.1
  Bundler: Fetching jekyll-seo-tag 2.7.1
  Bundler: Installing jekyll-seo-tag 2.7.1
  Bundler: Fetching thread_safe 0.3.6
  Bundler: Installing thread_safe 0.3.6
  Bundler: Fetching tzinfo 1.2.9
  Bundler: Installing tzinfo 1.2.9
  Bundler: Fetching tzinfo-data 1.2021.1
  Bundler: Installing tzinfo-data 1.2021.1
  Bundler: Fetching wdm 0.1.1
  Bundler: Installing wdm 0.1.1 with native extensions
  Bundler: Bundle complete! 6 Gemfile dependencies, 35 gems now installed.
  Bundler: Bundled gems are installed into `./path`
New jekyll site installed in E:/ruby/my-site.
PS E:\ruby> cd my-site
PS E:\ruby\my-site> bundle exec jekyll serve
```

After doing some digging, this is similar to [https://github.com/jekyll/jekyll/issues/2938](url). In order to fix this issue, add 
`exclude: [path]` to the _config.yml.

This issue is submitted since this seems to be the default behavior of Jekyll. I was able to recreate this bug by doing the above process again with a different path.

**Comment by ashmaroli** [comment]
Ideally, you should keep your Ruby installation directory separate from your Jekyll site directory.
