### ISSUE TITLE
Creating text boxes with leader arrows in jekyll markdown

### ISSUE THREAD

**Issue by awa5114** [jekyll/jekyll#8589]
I would like to ask whether there exists a way of annotating code using text boxes and leader arrows in `jekyll` for a `github-pages` site. I am referring to something like the following:

[![enter image description here][1]][1]

I am open to javascript libraries though I would prefer sticking to something I can include as a plugin in the `jekyll` framework. I have looked into some options such as `jekyll-spaceship` but couldn't really think of a way to use those tools to achieve the image above. Thanks for your consideration.

  [1]: https://i.stack.imgur.com/MtwNa.jpg

**Comment by seshrs** [comment]
I don’t think a solution that only uses Jekyll or Jekyll plugins exists. Jekyll uses Rouge for syntax highlighting by default, and I’m not sure if plugins exist that could achieve what you want. 

However, it looks like Prism, a JS based syntax highlighter, achieves what you’re looking for. Their documentation site has an example: https://prismjs.com/#basic-usage

Prism also allows you to include plugins and custom styles. It looks like [line-highlight](https://prismjs.com/plugins/line-highlight/) with custom styles might help.

**Comment by DirtyF** [comment]
Not something that feels like a common struggle to justify modifying the core, hope you can find a way to achieve this with plugins or JS libraries.
