### ISSUE TITLE
Static .txt file in subdirectory fails on GHP

### ISSUE THREAD

**Issue by networkimprov** [jekyll/jekyll#8592]
On github pages, I created a file `t/shortfile.txt` with a few lines of text and no front-matter. (The `t/` directory also contains .png images which work fine.) That produced the error "Page build failed" and no further info. I subsequently renamed the file to `t/shortfile.t` as a workaround.

GHP source: https://github.com/mnmnotmail/website/tree/master/t
Rendered site: https://mnmnotmail.org/

I searched the jekyll docs, google, stackoverflow, and this issue tracker about this. Apologies if it's working-as-intended. If so, are there docs for it?

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `github-pages`   | Latest     |

## Expected Behaviour

Produce a static file accessible at https://example.com/t/shortfile.txt

## Current Behavior

"Page build failed."

## Code Sample

File contents:
```
Here is a short text file.

With two lines,

or maybe more.
```

**Comment by networkimprov** [comment]
Renaming the file to `shortfile.t` was not a useful workaround, because the GHP http server doesn't send it as text/plain, so the browser offers to download/save it instead of displaying it.

**Comment by seshrs** [comment]
Hi @networkimprov, I was unable to repro this issue locally on a personal Jekyll website. I tried [building](https://docs.github.com/en/github/working-with-github-pages/creating-a-github-pages-site-with-jekyll) your [source repo](https://github.com/mnmnotmail/website) locally, and the build succeeds even after renaming the file to `shortfile.txt`. I am also able to visit the local URL hosting that txt file and it loads as expected.

I wonder if there's some other reason that the build fails on GitHub Pages, but I have no idea what that might be 😅

**Comment by networkimprov** [comment]
Thanks for trying! I just tried it again at GHP, and it works now. Hopefully because someone noticed this issue; if so it's sad they didn't comment.
