### ISSUE TITLE
Problem with jekyll start

### ISSUE THREAD

**Issue by aligote** [jekyll/jekyll#8619]
Traceback (most recent call last):
        14: from /home/jack/gems/bin/jekyll:23:in `<main>'
        13: from /home/jack/gems/bin/jekyll:23:in `load'
        12: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/exe/jekyll:8:in `<top (required)>'
        11: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        10: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
         9: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:191:in `<top (required)>'
         8: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:12:in `require_all'
         7: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:12:in `each'
         6: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll.rb:13:in `block in require_all'
         5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         3: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/drops/collection_drop.rb:3:in `<top (required)>'
         2: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/drops/collection_drop.rb:4:in `<module:Jekyll>'
         1: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/drops/collection_drop.rb:5:in `<module:Drops>'
/var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/drops/collection_drop.rb:10:in `<class:CollectionDrop>': undefined method `delegate_method_as' for Jekyll::Drops::CollectionDrop:Class (NoMethodError)

**Comment by DirtyF** [comment]
Hi, this repository is for documented Jekyll core issues 🐛 only (not themes, or usage) 

🆘 Please reach out to [GitHub support](https://support.github.com/) or [community](https://github.community), you can also ask question on J[ekyll's community forum](https://talk.jekyllrb.com)

Thanks. 🙏
