### ISSUE TITLE
Footnotes don't respect ARIA

### ISSUE THREAD

**Issue by kinoute** [jekyll/jekyll#8625]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |        macOS 10.14.6    |
| `jekyll`         | 4.2.0    |
| `github-pages`   | No     |

---

## Expected Behaviour

Footnotes generated by Jekyll should respect "ARIA" standard for accessibility : https://web.dev/aria-required-children/?utm_source=lighthouse&utm_medium=devtools 

## Current Behavior

When running Lighthouse to check the performance of my website, I found out that the HTML footnotes generated from my markdown files don't seem to respect the "ARIA" standard for accessibility in terms of "role".

## Code Sample

Here is a post sample with footnotes : https://y.defret.in/2021/03/18/add-dark-theme-on-ruby-on-rails-app.html

The markdown file:

```markdown
[...]
When you think about it, it makes sense that a website about movies, displaying movie snapshots with cinema benches and curtains around them, provides a better experience to the users with dark colors everywhere.

[^1]: Of course if you can respect both levels, this is awesome. But I found out, in my case, that trying to achieve the level AAA for small texts was sometimes very hard.
```

The footnotes appear like this in the generated HTML source code:

```html
<div class="footnotes" role="doc-endnotes"> 
  <ol> 
    <li id="fn:1" role="doc-endnote"> 
      <p>
        Of course if you can respect both levels, this is awesome. But I found out, in my case, 
        that trying to achieve the level AAA for small texts was sometimes very 
        hard.&nbsp;<a href="#fnref:1" class="reversefootnote" role="doc-backlink">↩</a>     
     </p> 
    </li> 
  </ol> 
</div>
```

Here is the lighthouse report:

![Capture d’écran 2021-04-01 à 02 31 41](https://user-images.githubusercontent.com/623763/113227234-72924080-9292-11eb-9127-75a495c44b2f.png)

Link to the report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fy.defret.in%2F2021%2F03%2F18%2Fadd-dark-theme-on-ruby-on-rails-app.html#accessibility

**Comment by DirtyF** [comment]
Thiis is an upstream issue: https://kramdown.gettalong.org/quickref.html#footnotes

There's an ongoing [related issue in Kramdown](https://github.com/gettalong/kramdown/pull/693), Jekyll default Markdown engine that could fix this accessibility issue.
