### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by wikicrafter** [jekyll/jekyll#8636]
Expectation after downloading was running it properly without any issues but when i'm running command:

* bundle exec jekyll serve
> Error is :               ------------------------------------------------
    1.  Jekyll 4.2.0   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------ <br>
2. Ruby30-x64/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/servlet.rb:3:in `require':  cannot load such file -- webrick (LoadError)

**Comment by wikicrafter** [comment]
# bundle add webrick 
command solved this issues

**Comment by kmk3** [comment]
Duplicate of #8523.
