### ISSUE TITLE
please support tags without need plugins to make github pages support tags

### ISSUE THREAD

**Issue by guileen** [jekyll/jekyll#867]
github use jekyll but disable plugins，can't generate tag pages, please support tag officially, so next time github upgrade Jekyll, github pages could support tags

**Comment by wireddown** [comment]
For commenters that are using pure gh-pages without plugins, I have a [changeset](https://github.com/poole/lanyon/pull/85) that adds tags to [poole/lanyon](https://github.com/poole/lanyon) influenced by @minddust's implementation.

If you're using a different Jekyll theme, you can:

 1. use items 1..6 (which add new files)
 1. apply item 7 for your theme
 1. ignore item 8 (which is Lanyon documentation)

**Comment by MrLoh** [comment]
I have a GitHub Pages compatible completley automated date and tag archive solution. It works with creating files locally with a ruby script. Have a look at my blog: http://mrloh.se/2015/06/automatic-archives-for-jekyll-on-github-pages/
