### ISSUE TITLE
Error: Please append '--trace' to the 'serve' command

### ISSUE THREAD

**Issue by RealisticCoder** [jekyll/jekyll#8710]
So far I’ve had a few teething issues with Jekyll but I’ve managed to get to the point where I installed Jekyll (gem install bundler Jekyll) and downloaded the files for my project (Jekyll new my-awesome-site)

However, now I’m trying to get my Jekyll site to run locally by trying “bundle exec Jekyll serve” and now I’m getting an error

                ------------------------------------------------
  Jekyll 4.2.0   Please append `--trace` to the `serve` command 
                 for any additional information or backtrace
![image](https://user-images.githubusercontent.com/73340294/122156807-5c565280-ce87-11eb-9478-aad79c1d859a.png)

**Comment by molitona** [comment]
I'm getting the same error too on Arch, please help!

**Comment by uberfuzzy** [comment]
#8685  #8524  #8536

**Comment by ashmaroli** [comment]
Resolved via https://github.com/jekyll/jekyll/commit/bcaf878b65d6349da9e53ad9243796e72797c0db

**Comment by yohosun** [comment]
Me too,What's this mean?
![image](https://user-images.githubusercontent.com/77920708/163665444-2b82d2c8-9972-45b4-b1f2-1493115f9e15.png)

**Comment by YorkWong30** [comment]
i find the answer at this page.
hope this can help u.
[https://jadyer.cn/2016/10/17/jekyll-build-blog/](url)

**Comment by caglarj** [comment]
This is because:
webrick has not been bound to Ruby since Ruby 3.0. Please refer to the link:   Ruby 3.0.0 Released   Description in.

Webrick needs to be added manually.

The added commands are:

`bundle add webrick`

**Comment by fabioew89** [comment]
thank you so much, i fix the problem with your answer

pt-br
muito obrigado, consegui consertar o problema com sua resposta
