### ISSUE TITLE
Show All category posts (collection) in homepage

### ISSUE THREAD

**Issue by hippomu-media** [jekyll/jekyll#8716]
{% for cat in site.categories %}

This code only show category on collection posts
I create collections games, the category in collection games not show.

I use this code
{% for cat in site.collection.categories %}
Still not work

**Comment by Simran-B** [comment]
Shouldn't it be more like this?

```
{% for coll in site.collection %}
  {% for cat in coll.categories %}
    ...
  {% endfor %}
{% endfor %}
```
