### ISSUE TITLE
A mode for using `./` 

### ISSUE THREAD

**Issue by PanPeople** [jekyll/jekyll#8722]
Sorry, maybe I am too stupid to use this powerful tool but how can i change all **.css** and **images** url to ulrs with `./` at the beginning. I really don't want to do it manually or write a python parser for that.

Example if i wasn't clear:
* what is in code:  `href="/assets/main.css"`
* what I want: `href="./assets/main.css"`

**Comment by fauno** [comment]
you can probably set `url: './'` in `_config.yml` and do something like

```
{{ 'assets/main.css' | absolute_url }}

{{ post.url | absolute_url }}
```

if what you want are relative urls, something like jekyll-relative-urls
can help

**Comment by PanPeople** [comment]
> you can probably set `url: './'` in `_config.yml` and do something like ``` {{ 'assets/main.css' | absolute_url }} {{ post.url | absolute_url }} ``` if what you want are relative urls, something like jekyll-relative-urls can help

The isn't any 'url'  only ' baseurl'  but it is a different thing.

Also i don't want to set manually this files to have ` | absolute_url }}` .

I just want to add `./` next to every url. But I am afraid that Jekyll can't do that so I just write a python parser for that.

But thanks for the help anyway.
