### ISSUE TITLE
feat: Cache file contents that haven't changed during serve

### ISSUE THREAD

**Issue by sdegutis** [jekyll/jekyll#8739]
## Summary

Cache file contents of all non-binary files (i.e. files that are going to be read/transformed/used by Jekyll) during file-watch mode when using `jekyll serve`.

## Motivation

It would probably speed up site-generation when files change.

I've updated to Jekyll 4 and that sped up my website from 15 seconds to 8-10, then upgraded to Ruby 3 which sped it up to 2-3 seconds. But it's still a noticeable delay.

Presumably a lot of this time is spend reading my collection files. I have hundreds of them, and an old slow computer. But they don't total more than 2-3 MB in contents, and that can easily fit in RAM. (At least, I hope Ruby can manage that.)

## Drawbacks

It might not actually speed anything up. I'm completely assuming that I/O is a lot of the bottleneck here. But it's just a guess.

**Comment by ashmaroli** [comment]
@sdegutis Have you tried using the `--incremental` option?
```
bundle exec jekyll serve --incremental
```
*Note: Incremental regeneration will only render the non-binaries that changed since last regeneration / build. The remaining content will be left unrendered.*

**Comment by sdegutis** [comment]
I have not, I always assumed it was either experimental or had serious caveats. If that's the only caveat then it would probably be what I'm looking for in this issue.

Also, I don't use Jekyll anymore, as my site finally became dynamic enough to move to Express.js, so I no longer have any stock in this issue personally.
