### ISSUE TITLE
Jekyll exists with code 0 even when there are errors, preventing GitLab CI from reporting a problem

### ISSUE THREAD

**Issue by TheOddler** [jekyll/jekyll#8751]
When running `jekyll build` it ends with code 0, even when an error occurred.

It's unclear if this is intended behavior. From my understanding this might be because the error is not fatal, and thus Jekyll builds what it can. Though it this also make GitLab pages just continue with it's deploy without reporting any problem.

This can be very frustrating in combination with GitLab pages, as the build succeeds, but the new page does not show up.
Without any indication as to why unless you go check the job output.
This is not that big of a problem for technical people, but non-technical people will first have to contact the admin, rather than the admin just getting an email the build failed and being notified instantly.

```
$ jekyll build -d public
...
Bundle complete! 5 Gemfile dependencies, 29 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
Configuration file: /builds/TheOddler/mjb/_config.yml
            Source: /builds/TheOddler/mjb
       Destination: /builds/TheOddler/mjb/public
 Incremental build: disabled. Enable with --incremental
      Generating... 
             Error: YAML Exception reading /builds/TheOddler/mjb/_work/immaculate.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
       Jekyll Feed: Generating feed for posts
                    done in 1.104 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Uploading artifacts for successful job 00:09
Uploading artifacts...
```

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | jekyll docker latest |
| `jekyll`         | Latest     |
| `github-pages`   | No     |

---

## Expected Behaviour

Jekyll to report a non-0 error code, so that this can be picked up by a a CI system.

## Current Behavior

Jekyll build returns a 0 code, even though there is an error.

**Comment by fauno** [comment]
Hi, from reading the code, you can set `strict_front_matter: true` in
`_config.yml` so Jekyll fails the build on parsing errors

**Comment by TheOddler** [comment]
This was indeed pretty well fixed with the option `strict_front_matter: true`.
