### ISSUE TITLE
docs: Case sensitivity in Jekyll Tags should be documented.

### ISSUE THREAD

**Issue by kcclemo** [jekyll/jekyll#8757]
## Motivation

This may be documented and I'm just unable to find it but, searching the [jekyllrb.com](https://jekyllrb.com/) site didn't return anything along these lines.

When using the `jekyll-tagging` plugin, you can add tags to the front matter of a post. However, there isn't any documentation that warns against using capitalization in the tags. This is important because Jekyll normalizes the tags to lowercase when generating each tag page.

For example, if I apply a tag of `Fruit` the value that is returned by `{{ post.tags }}` is `Fruit`. When inserting this value into the `href` of an anchor tag, the URL would be `/tag/Fruit`. However, the page that is actually generated by Jekyll is `/tag/fruit`. This results in a link being rendered on the page that returns a 404.

## Suggestion

It would be worthwhile to document this so that developers are aware and can use other means for displaying the tags on the page. My solution was to use CSS to capitalize the tag on the page allowing the URL to generate properly.

Per a long conversation in issue #2977 I agree with the school of thought that the plugin should generate the URL exactly as the tag is written in code since URL creation is the responsibility of the individual who is coding the site but, that's a separate issue that I may open later. For now, documenting the behavior so that developers are aware would be helpful.

**Comment by MichaelCurrin** [comment]
That sounds like a good idea.

I've always written tags in frontmatter as lowercase so actually never came up against this issue. This tutorial uses `tags: classic hollywood` for example.

https://jekyllrb.com/docs/posts/#tags-and-categories



So is worth adding to the docs to say that the rendered page's URL will be lowercase regardless of if you tag is uppercase or lowercase and also to recommend users write _lowercase_ tags (with hyphens like `tags: classic-movie hollywood` ) to avoid confusion.

I suppose it also helps that things are lowercased. If you had to handle `site.tags.hollywood` and `site.tags.Hollywood` separately that would be annoying, so rather they are merged for you.

**Comment by kcclemo** [comment]
> ...the rendered page's URL will be lowercase regardless...

This is not quite true, the rendered URL is actually just as the developer has typed it. But, the generated page file for each tag is all lowercase. That is why this combination results in a 404.

**Comment by chrisfinazzo** [comment]
> That sounds like a good idea.
> 
> I've always written tags in frontmatter as lowercase so actually never came up against this issue. This tutorial uses `tags: classic hollywood` for example.
> 
> https://jekyllrb.com/docs/posts/#tags-and-categories
> 
> So is worth adding to the docs to say that the rendered page's URL will be lowercase regardless of if you tag is uppercase or lowercase and also to recommend users write _lowercase_ tags (with hyphens like `tags: classic-movie hollywood` ) to avoid confusion.
> 
> I suppose it also helps that things are lowercased. If you had to handle `site.tags.hollywood` and `site.tags.Hollywood` separately that would be annoying, so rather they are merged for you.

As long as filters such as `upcase` or `capitalize` continue to work, this is good.

**Comment by ashmaroli** [comment]
> > ...the rendered page's URL will be lowercase regardless...
> 
> This is not quite true, the rendered URL is actually just as the developer has typed it.

@kcclemo The generated page's URL will be lowercase by default but the link pointing to that page will have it as is if it is not handled before hand.
For example, if your tags array `[Apple, Banana]` was used in the following template:
```liquid
{% for tag in post.tags %}
  <a href="/tags/{{ tag }}/" title="Posts tagged with {{ tag }}">{{ tag }}</a>
{% endfor %}
```
then you would definitely get the following (because it is just simple substitution):
```html
  <a href="/tags/Apple/" title="Posts tagged with Apple">Apple</a>
  <a href="/tags/Banana/" title="Posts tagged with Banana">Banana</a>
```
But the pages generated by your plugin would by default have their URL as:
```
/tags/apple/
/tags/banana/
```

This discrepancy is easily handed by using the provided `slugify` filter in your template:
```liquid
{% for tag in post.tags %}
  <a href="/tags/{{ tag | slugify }}/" title="Posts tagged with {{ tag }}">{{ tag }}</a>
{% endfor %}
```

Even if we were to document the case-insensitivity, the end result depends on how the plugin is implemented.
The plugin author can choose to generate tag-page with URL `/tags/Apple/` if they wish to..
