### ISSUE TITLE
if ... contains does not find the element

### ISSUE THREAD

**Issue by RobTranquillo** [jekyll/jekyll#8768]
First things first, thank you very much for creating and maintaining Jekyll! I'm working on my first project with it right now and I really like it. 

I'm not 100% sure if it's a bug or if I'm just holding it wrong. So please excuse me if I missed something.

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Win 10 | 10.0.19043 Build 19043 |
| `jekyll`         | 4.2.0 |
| `github-pages` | no|

---

## Expected Behaviour
A variable set in Front Matter should be testable for existence whether it is set by a collection or not.
Example:
```
{% if page contains "headline" %}
    {% if page.headline %}
        <h2>{{ page.headline }}</h2>
    {% endif %}
{% endif %}
```

## Current Behavior
The Example above works fine in a html template for a simple page, but not if this page is "generated" by a collection.
Turns out, even then, if the variable is specified, it cannot be evaluated using `{% if ... contains ... %}`.

### The way it works fine
To check for a parameter in an html template that is in the *.md file I use the following code

/index.md
```
---
title: Home
layout: default
permalink: /
---
```

/_includes/default.html
```
{% include sitebar.html %}
```
/_includes/sitebar.html
```
{% if page contains "title" %}
    {% if page.title %}
        <h2>{{ page.title }}</h2>
    {% endif %}
{% endif %}
```

And this works fine for normal pages, if my index.md contains the line with the title it is displayed, if not the whole header is not displayed. 

### What does not work
I want to use the same construct when rendering *.md files with html templates using a collection.

_config.yml
```
collections:
  posts:
    output          : true 
  cards-home:
```

/_cards-home/card-1.md
```
---
layout: card
card-style: card-image-right
headline: What a nice header
---
```

/_layouts/card.html
```
{% include {{ page.card-style }}.html %}
````

/_includes/card-image-right.html
```
{% if page contains "headline" %}
    {% if page.headline %}
        <h2>{{ page.headline }}</h2>
    {% endif %}
{% endif %}
```
This code should generate the output  `<h2>What a nice header</h2>`

I can also just print out `{{ page.headline }}` and it works. It's displaying the header messge. But evaluation via `{% if ... contains ... %}` does not work.

### Workaround with `for` loop

I found an workaround for me by using the `for` loop. 
```
{% for page-stuff in page %}
    {% if page-stuff == "headline" %}
        <h2>{{ page.headline }}</h2>
    {% endif %}
{% endfor %}
```
But I find it very ugly and would like a more specific solution.

Thank you people

**Comment by ashmaroli** [comment]
@RobTranquillo Instead of passing the `page` object directly to `contains`, try passing `page.keys`.

```
{% if page.keys contains "headline" %}
    {% if page.headline %}
        <h2>{{ page.headline }}</h2>
    {% endif %}
{% endif %}
```
Disclaimer: Even if it works, it may not be a very performant solution. (See if your build times increase..)

Why not avoid the double-check and render directly?

    {% if page.headline %}
        <h2>{{ page.headline }}</h2>
    {% endif %}

**Comment by RobTranquillo** [comment]
Hi @ashmaroli thank you very much for your hint with using the `.keys` array. I've never seen this before, but it works like a charme. Performance is not important in the project.

> Why not avoid the double-check and render directly?

As you can see in my example, if a variable is not specified, or it is empty, I do not want to output the tags surrounding it. This gives the people who maintain the content of the *.md files more possibilities to influence the result.This saves me from having to create and maintain more templates.

**Comment by ashmaroli** [comment]
> I do not want to output the tags surrounding it.

I get that. But why opt for double-checks? Isn't just checking `{% if page.headline %}` sufficient?

**Comment by RobTranquillo** [comment]
>  But why opt for double-checks? Isn't just checking {% if page.headline %} sufficient?

Just checking via **if** throws an error:
_Liquid Exception: Liquid error (D:/Website/_includes/cards/card-image-full.html line 7): undefined variable foobar included in D:/Website/_layouts/card.html_
_Error: Liquid error (D:/Website/_includes/cards/card-image-full.html line 7): undefined variable foobar included_

index.md
```
foobar: true
```

card-image-full.html
```
// throws the error
{% if page.foobar %}
    <h2>Foobar</h2>
{% endif %}

// does not work
{% if page.keys contains "foobar" %}
    <h2>Foobar</h2>
{% endif %}
```

Why was the issue closed, it is obviously a bug? The trick you showed is only a workaround, but does not change the problem. Even though I just noticed that probably the thrown error seems to be more serious when using If.

**Comment by ashmaroli** [comment]
> Why was the issue closed, it is obviously a bug?

There is no bug.
When you have `liquid.strict_variables` set to `true`, in your config file, Liquid is *expected* to throw errors when it encounters an undefined variable. It is a [documented](https://github.com/Shopify/liquid/tree/v4.0.3#undefined-variables-and-filters) feature.
Your options now are limited to either using the workaround or disable the configuration.

**Comment by RobTranquillo** [comment]
This issue is not about the error being thrown. This is a different issue and I understand what the strict option does. The problem I submitted here is about: "if ... contains does not find the element", as it is written in the headline.In this case, no error is raised, it just doesn't work. Sorry if I'm not clear enough or misunderstand a function. But I am still convinced that it is an bug.

**Comment by ashmaroli** [comment]
@RobTranquillo Okay. Since we have not documented anywhere that the Liquid operator `contains` can be used to test if a Liquid object has certain attribute, it is not a bug technically.

Was the feature working as expected in any version of Jekyll 3 and beyond? If yes, it was a regression and a bug.
The fact that it works for *normal pages* is not by design but coincidence.

You may either open a new feature-request ticket asking to port the functionality to documents in collections (including posts) or
you may open a bug-report ticket lamenting about the lack of parity between *normal pages* and *documents from a collection*.
