### ISSUE TITLE
feat: Let --blank flag create Gemfile before running bundler

### ISSUE THREAD

**Issue by emcoding** [jekyll/jekyll#8779]
## Summary

Running `new` with `--blank` wil add the Gemfile and run `bundle install`.

I would be very happy to create a PR for this feature. 

## Motivation

When running regular `new` (without `--blank` flag), jekyll installs a new site in `mydir` and [creates a gemfile](https://github.com/jekyll/jekyll/blob/493b800edbf6f6e97c34d1812698260907255665/lib/jekyll/commands/new.rb#L112). 
I would expect that that adding a `--blank` flag would add the Gemfile as well. Instead I need to run:
```
- `cd mydir`
- `bundle init`
- `bundle add jekyll`
- `bundle install`  
```
I expect that people who are using the `--blank` flag do that mainly because they don't want to use a theme. On deployment they will still need a Gemfile. (Installation guide step 10.) 
In the spirit of 'it just works' I would expect the Gemfile to be present, unaffected from the decision to (not) use a theme.  

## Guide-level explanation

 `jekyll new PATH --blank`  - Creates a new blank Jekyll site scaffold at specified PATH, including a basic Gemfile
OR 
`jekyll new PATH --blank`  - Creates a new blank Jekyll site without a theme at specified PATH

## Reference-level explanation

- The only implication I can see is that people who use the `--blank` flag now will get a Gemfile too. I can't think of use cases where that may be a huge problem.  
- Since there's no theme gem to bundle in a blank template, the only reason to also run `bundle install` is to also create the Gemfile.lock. I think that is a good enough reason to run bundle install after adding the gemfile. 
That means the [`after_install`](https://github.com/jekyll/jekyll/blob/6855200ebda6c0e33f487da69e4e02ec3d8286b7/lib/jekyll/commands/new.rb#L135) command must be updated too, for use with the blank flag. As it is currrenlty been skipped with `--blank`  option. 
- A `--skip-bundle` flag exists for cases where people don't want to run bundle install on creating the site. (If adding a Gemfile can be a problem, we may add a `--skip-gemfile` flag as well.)
- The [current autocreated gemfile](https://github.com/jekyll/jekyll/blob/6855200ebda6c0e33f487da69e4e02ec3d8286b7/lib/jekyll/commands/new.rb#L70) adds the default theme gem, we would either just create the Gemfile with `bundle init`, or create new content with the jekyll specific text included (which would be nice), or rethink the way the gemfile content is added, so we can make the theme gem conditional on (not having) the `--blank` flag.
 

## Drawbacks

If very few users use the `--blank` flag. 
If Jekyll is mostly targeted to Rails and Ruby devs, because they probably will have experience with bundle to fix it themselves.
If there are other reasons for people to use a blank template other than having a template without a predefined theme. (I am not aware of such reasons, so please enlighten me :-) )

## Unresolved Questions

* In the same spirit, I would also like an automated `git init`. 
* Maybe the `--blank` flag should also run `after_install`. But, without the Gemfile created, that makes it more complicated to change the current after_install method. 
* Maybe the `--blank` flag should only skip the theme-related things, and implement all the other features. I don't know if that is useful/doable/overengineering/redundant. 

Again, I would be happy to work on a PR.

**Comment by ashmaroli** [comment]
> On deployment they will still need a Gemfile.

Technically, this is not true.
`jekyll build` is still valid.

If there's a Gemfile, the invocation would mandate the prefix `bundle exec`.

Sorry. We don't intend to support this enhancement.
