### ISSUE TITLE
No docs for customizing server headers

### ISSUE THREAD

**Issue by yaitskov** [jekyll/jekyll#8785]
Through _config.yaml user can set binding IP mask and port, but I haven't found a way to setup HTTP headers sever should send to client.

I cannot setup CORS headers and struggle with google search engine integration because js code is loaded from foreign domain.

**Comment by DirtyF** [comment]
Jekyll server is only meant to be used locally while development, we don't set any server header, I'm not sure what you're trying to achieve here and how it related to Jekyll.
