### ISSUE TITLE
Support subdirectories for posts with additional resources

### ISSUE THREAD

**Issue by rgov** [jekyll/jekyll#881]
It'd be nice to be able to have a _posts structure that supports posts with their own directories of resources, such as photos or CSS.

```
_posts/
    2013-01-01-some-post.markdown
    2013-01-02-post-with-resources/
        post.markdown
        someimage.jpeg
```

I investigated creating a custom Generator plugin, but this does not seem practical because the Post class makes assumptions about the directory structure.

**Comment by nhoizey** [comment]
I wonder if it would be well received if I open a new issue on this topic, but at least I can point to a comment I made on StackOverflow… ;-)

http://stackoverflow.com/questions/10363812/local-post-assets-with-jekyll/35270428#35270428
