### ISSUE TITLE
Support markdown intermixed with inline HTML

### ISSUE THREAD

**Issue by mohitmv** [jekyll/jekyll#8819]
Inline HTML and markdown syntax of kind "```C++ .... ```" could be intermixed in all the markdown viewer. Please fix it here too.
Example of intermix:

<table style='border: solid #ccc 0px; vertical-align: top;' ><tr>
<td>

```C++
#include <stdio.h>
void P( ) {
  ... 
}
...
```

</td>
<td style='vertical-align:top' >

```C++
extern "C" int printf(const char *format, ...);
```
</td>
</tr></table>

Markdown code for above : https://i.imgur.com/637oa5P.png

My use case : I'm using jekyll's inbuilt support in Github to power my blog.

**Comment by ashmaroli** [comment]
> if I use `<iframe style='border:none; width:500px; height: 300px;' src="http://www.youtube.com/embed/e7wm8pw2Yw0"></iframe>` inside my markdown blog, jekyll won't work...

Hello @mohitmv
Simply saying *jekyll won't work* isn't going to help.
Please tell us what you expected to see and what you got to see instead..

How did you conclude that the `iframe` has not rendered properly? Were you able to see raw HTML? Or did GitHub send you an email / notification regarding a build error..?

**Comment by mohitmv** [comment]
Hi, The youtube iframe worked after following some stackoverflow answer. It was not related to jekyll but it was youtube's http/https issue. Earlier I think I read some outdated tutorial which was showing how to embed youtube in jekyll blogs..

So I edited the title of this issue. Now the only issue remaining is intermixed usage of markdown and HTML.

It's repro is very simply - You can try that markdown (in screenshot above). The jekyll is rendering some the code in a single line, with messed up triple tick displayed as is... However when I used the same markdown in Github's comment above, Github rendered it properly. ( See the table above with 2 columns, each of them is a code snippet )

**Comment by mohitmv** [comment]
Another issue related to code highlighting - if I put a code snippet inside `{% highlight c++ %}`, then it works well. However if put inside "```C++" , then it works but renders double border around the code snippet which doesn't look good.

**Comment by ashmaroli** [comment]
> You can try that markdown (in screenshot above).

Ah! I see.. That was the expected result. (Wasn't very clear from reading the post).
Anyways, that is supported but requires manual intervention. (Won't happen automagically on all pages of your blog).

The solution is to add attribute `markdown="1"` to the immediate parent container.
Therefore, your given code now would look like:

~~~
<table style='border: solid #ccc 0px; vertical-align: top;'><tr>
<td markdown="1">

```C++
#include <stdio.h>
void P( ) {
  ... 
}
...
```

</td>
<td markdown="1" style='vertical-align:top' >

```C++
extern "C" int printf(const char *format, ...);
```
</td>
</tr></table>
~~~

Every markdown flavour has their own quirks and intricacies. Jekyll uses the flavour `kramdown` by default.

---

> then it works but renders double border around the code snippet...

This is not a Jekyll issue as well. The HTML generated when using triple backticks is dictated by kramdown. *How it looks* is dictated by the stylesheets of your theme. Jekyll doesn't control any of those variables.

---

Therefore closing..

**Comment by mohitmv** [comment]
This helps. Thanks.
