### ISSUE TITLE
I can't install jekyll

### ISSUE THREAD

**Issue by dylanmeca** [jekyll/jekyll#8832]
## My Environment

Hello, good afternoon when installing jekyll on windows I get this error, I have installed Ruby + Devkit 2.7.X (x64), I also have msys64 and mingw64 installed and I can use cmake but I don't know why I get that error:

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |    Windows 10        |
| `jekyll`         | Latest  4.2.1     |
| `github-pages`   | Latest     |

---

## Expected Behaviour

Jekyll gem must be installed

## Current Behavior

Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Program Files/Ruby30-x64/lib/ruby/gems/3.0.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
C:/Program\ Files/Ruby30-x64/bin/ruby.exe -I C:/Program\ Files/Ruby30-x64/lib/ruby/3.0.0 -r ./siteconf20210930-16232-92wyd8.rb extconf.rb
creating Makefile

current directory: C:/Program Files/Ruby30-x64/lib/ruby/gems/3.0.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make DESTDIR\= clean

current directory: C:/Program Files/Ruby30-x64/lib/ruby/gems/3.0.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make DESTDIR\=
generating ruby_http_parser-x64-mingw32.def
compiling ruby_http_parser.c
gcc.exe: error: Files/Ruby30-x64/lib/ruby/gems/3.0.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser: No such file or directory
make: *** [Makefile:245: ruby_http_parser.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Program Files/Ruby30-x64/lib/ruby/gems/3.0.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to C:/Program Files/Ruby30-x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/http_parser.rb-0.6.0/gem_make.out

## Code Sample

Just download Ruby + Devkit 2.7.X (x64), install mingw64 and msys64, also install cmake but it doesn't allow me to install jekyll

Please help how do I solve this?

**Comment by mattr-** [comment]
Hello! 👋

We'd prefer that issues on the jekyll repo not be used for support requests. Since you're having issues getting Jekyll to work on your machine, please head over to https://talk.jekyllrb.com to get help from the wider community there.

Thanks!

**Comment by dylanmeca** [comment]
Thank you so much 👍
