### ISSUE TITLE
  Liquid Exception: Can't convert Array into String.

### ISSUE THREAD

**Issue by YexuanXiao** [jekyll/jekyll#8859]
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | Ubuntu 20.04 (WSL2)  |
| `jekyll`         | 4.2.1     |
| `github-pages`   | No     |

---

## Expected Behaviour

Build pages

## Current Behavior

```bash

$ bundle exec jekyll serve

Configuration file: /home/bizwen/yexuanxiao.github.io/_config.yml
            Source: /home/bizwen/yexuanxiao.github.io
       Destination: /home/bizwen/yexuanxiao.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Can't convert Array into String. in /home/bizwen/yexuanxiao.github.io/_layouts/default.html
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
```

and

```bash
$ bundle exec jekyll serve

Configuration file: /home/bizwen/yexuanxiao.github.io/_config.yml
            Source: /home/bizwen/yexuanxiao.github.io
       Destination: /home/bizwen/yexuanxiao.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Killed

```

## Code Sample

```html

{% for tag in site.tags limit:15 %}
<a href="{{ site.alternateurl }}/tags#{{ tag | uri_escape }}" class="tag is-info is-light">
    # {{ tag }}
</a>
{% endfor %}

```

commit in my repo:

https://github.com/YexuanXiao/yexuanxiao.github.io/commit/e3ed37a181af06e6de8478b018e142aa2bf6aef5#diff-907a69846a1f6b238f1c43199984197d12c7eab26f3c3adcd45d628b26644950
https://github.com/YexuanXiao/yexuanxiao.github.io/commit/e3ed37a181af06e6de8478b018e142aa2bf6aef5#diff-88e83e5d0edb4286d0e35534fa9f49405a4ef6724137b468772a31183cb43a3f

**Comment by ashmaroli** [comment]
@YexuanXiao `site.tags` is not a simple list of tags in your site.
It is a set of key-value pairs.
To know the actual structure, use the `inspect` or `jsonify` filter
For example:
```
<pre>
{{ site.tags | inspect }}
</pre>
```
or
```
{% for tag in site.tags limit:15 %}
<pre>
{{ tag | jsonify }}
</pre>
<pre>
{{ tag[0] | inspect }}
</pre>
<pre>
{{ tag[1] | inspect }}
</pre>
{% endfor %}
```

**Comment by YexuanXiao** [comment]
> @YexuanXiao `site.tags` is not a simple list of tags in your site. It is a set of key-value pairs. To know the actual structure, use the `inspect` or `jsonify` filter For example:
> 
> ```
> <pre>
> {{ site.tags | inspect }}
> </pre>
> ```
> 
> or
> 
> ```
> {% for tag in site.tags limit:15 %}
> <pre>
> {{ tag | jsonify }}
> </pre>
> <pre>
> {{ tag[0] | inspect }}
> </pre>
> <pre>
> {{ tag[1] | inspect }}
> </pre>
> {% endfor %}
> ```

thanks a lot😄
