### ISSUE TITLE
Github pages server never updating

### ISSUE THREAD

**Issue by Houdanait** [jekyll/jekyll#8873]
Hello!

I am trying to push my changes to my web page : https://houdanait.github.io/. 
When I try to run `bundle exec jekyll serve`  it keeps telling me : 

`Auto-regeneration: enabled for '/Users/houdanaitelbarj/Desktop/Houdanait.github.io'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.`

But nothing happens, after hours, this is still running without the page being updated. Please HELP!

**Comment by ashmaroli** [comment]
Hello @Houdanait 
I think you have misunderstood the purpose of the CLI command `jekyll serve`...

Running `bundle exec jekyll serve` will build your site *locally*, start *a local webserver* and serves the built site using that local server to aid in the development of your site.
The command **doesn't push the built site to GitHub.** You have to do that manually.

To summarize, your development workflow would be the following:
```sh
# start local webserver at address http://localhost:4000
bundle exec jekyll serve

# Preview served site via above address.
# Make changes if necessary.

# Stop server to commit changes to source files.
<Ctrl + C>

# Commit changes and push to <remote> git repo
git add .
git commit -m "My changes"
git push <remote> <branch_name>
```
For more information, please refer the following [documentation](https://jekyllrb.com/docs/github-pages/).

---

Closing this..
