### ISSUE TITLE
feat: Add emphasis within code blocks

### ISSUE THREAD

**Issue by darkstar** [jekyll/jekyll#8878]
## Summary

I'd like to have a feature where I can emphasize certain parts of a (larger) code block.

Please excuse if this feature is already available but I have searched (and asked around) for quite a while and came up with nothing.

## Motivation

When I'm posting larger code blocks, especially of shell commands and their output, I'd like to add highlights to certain parts. For example consider a very long interactive session with some program, where the user has to enter something at two particular points. I'd like to emphasize these commands that the user has to type, to make them easier findable in the long stream of text.

I'm also thinking of adding simple "annotations" to larger code blocks (especially blocks with highlighting), which I can then refer to in the text below. 

Say, have one part of a line outlined by a blue box, and another by a yellow box, and then later reference to them as "...the blue-outlined part..." etc. to make it clear what I'm talking about. This is possible in DocBook, for example, by using callouts.

## Guide-level explanation

There is a special markdown-syntax (let's call it `||`) that you can wrap around some piece of code in your code block, that will put a `span` around it with the (predefined?) CSS class `mark`:

````
...this is the output of our program:

~~~~
some code
more stuff
more stuff
some ||interesting|| stuff
more stuff
and another uninteresting line
~~~

You see that the **interesting** part is ...
````

In this example you could make the CSS class `mark` appear in bold text, which would render the word "interesting" in the second line as bold.

Or for the second case, you'd need some sort of parameter to that markdown, so you wrap it in `|:<id>|` to start, and end with `||`. You'd probably also need a new option to the highlighter itself, `markings`:

````
{% highlight python markings %}
def abs(num):
   if num |:1|>= 0||:
        return num
    else:
        return |:2|-num||
{% endhighlight %}
````

This would wrap the `>=0` part in one CSS class (say, `mark-1`) and the `-num` part in `mark-2`, which could then be defined to have different-colored boxes around them to be referenced later in the text.

## Reference-level explanation

I don't know if the second variant is possible, as it would require support in liquid and the syntax highlighter, and I don't know if such a feature is available (and exposable) there...

## Drawbacks

Too complicated to implement, or too few use cases maybe?

## Unresolved Questions

* Escaping of the markdown sequence if you want it verbatim?
* The actual syntax of these "tags" is debatable

**Comment by ashmaroli** [comment]
Jekyll doesn't parse or convert Markdown to HTML directly. It uses kramdown (default) for parsing and converting Markdown into HTML.
Regarding the Liquid tag, again, Jekyll doesn't parse the contents. Instead, it uses Rouge (default) to parse, lex and generate the markup.

**Comment by ashmaroli** [comment]
Sorry. But closing as this isn't actionable.
