### ISSUE TITLE
[Bug/Security]: Default config allows easy HTML injection into code blocks

### ISSUE THREAD

**Issue by joshgoebel** [jekyll/jekyll#8903]
### Operating System

All I think.

### Ruby Version

All I think.

### Jekyll Version

Not entirely sure, I'm getting this second hard from all the Jekyll users having issues with Highlight.js.

### GitHub Pages Version

Latest

### Expected Behavior

_HTML characters included in code blocks should be escaped properly by default._  Raw HTML injection should not be possible unless a user explicitly enables it.

I'm aware Jekyll uses kramdown, but I'm filing this here because I feel like this is a broken/poor security default on Jekyll's part...

### Current Behavior

HTML injection is allowed by default because the code blocks seem to be inserted into the HTML verbatim.  Please correct me if I'm mistaken.  I'm getting this second hard from all the Jekyll users having issues with Highlight.js.

Therefore Highlight.js will alert that this is a security risk...

![](https://user-images.githubusercontent.com/58632405/145713366-9377e5e1-37d7-4c75-b10f-160012a9295a.png)

Related: https://github.com/highlightjs/highlight.js/issues/2886

### Relevant log output

```shell
None.
```

### Code Sample

**Markdown samples**

````
```js
if (a<5) {
  alert("hello")
}
```
````

If this case the `<` should be encoded as `&lt;`.

````
```html
<h1>Hello World</h1>
```
````

In this case the `<` and `>` should be encoded to avoid the `H1` tag from literally being injected directly into the persons website unintentionally.

**Comment by ashmaroli** [comment]
Hello @joshgoebel 
I've not been able to reproduce this with the following steps:

- Run `jekyll new inject-html-test --skip-bundle`*
- Run `cd inject-html-test`
- Edit Markdown document inside `inject-html-test/_posts` directory to contain your snippets.
- Run `bundle exec jekyll serve`
- Point browser to `http://localhost:4000/` > navigate to the Welcome post > Check HTML source code in browser.

*Note: I used `skip-bundle` CLI flag because my system has the necessary gems to build a Jekyll site by default. If your's doesn't, drop the flag.

If you're still not convinced, please set up a minimal repository, have it hosted and deployed via GitHub Pages and provide us with the public URL so that we may see it as you see it.

**Comment by joshgoebel** [comment]
I can't reproduce either using those steps - the HTML is escaped as I would hope it should be.  Thanks for the step-by-step to create a test environment.  I'll continue to try and chase this down on my end with the original reporters.

**Comment by y377** [comment]
@joshgoebel hi!Thank you for your attention. I am a novice and have not encountered any problems so far. However, for your questions, I will reproduce them in the daytime on UTC+8, December-14, 2021. Please wait. [The current version:](https://github.com/taufik-nurrohman/highlight.ln.js/issues/4#issue-1077787373)

**Comment by y377** [comment]
@joshgoebel hi!
If I comment it out, he will indeed show, whose error is jekyll or highlight.js? what should I do?

>  `hljs.configure({ ignoreUnescapedHTML: true });`
```
<script>hljs.highlightAll();
 //  hljs.configure({ ignoreUnescapedHTML: true });
</script>

```
![image](https://user-images.githubusercontent.com/58632405/146048069-cdfde162-5637-44ab-9312-b7112172ebee.png)

**Comment by joshgoebel** [comment]
That isn't enough to show us anything.  We'd need to see:

- raw HTML BEFORE it's highlighted
- or you could expand those nodes in your console output to see what tags are inside them

But that output doesn't look like Highlight.js.  We do not have tiny short  class names like that, so you're doing stuff on top of us that might be causing this problem.

**Comment by joshgoebel** [comment]
_You should not be using both `rouge` and Highlight.js..._  Before highlighting your RAW HTML `pre` tags should be *only source code*, no other HTML.
