### ISSUE TITLE
[ Bug ] : " Bundle Exec Jekyll " - Not working

### ISSUE THREAD

**Issue by BSOD2528** [jekyll/jekyll#8926]
### Operating System

Windows 10

### Ruby Version

3.1.0p0 (2021-12-25 revision fb4df4416) [x64-mingw-ucrt]

### Jekyll Version

jekyll 4.2.1

### Expected Behavior

I am unable to get my github pages version to fill up in the above tab.

But my major issue is, whenever i try to run `bundle exec jekyll serve`, I am getting this major big traceback. I have tried to do what it said, but it still gave the same traceback. Given below is the traceback given.

### Current Behavior

PS C:\Users\ADMIN\Desktop\AV's Folder\FLP's\Code\BSOD2528.github.io\BSOD> bundle exec jekyll serve
Configuration file: C:/Users/ADMIN/Desktop/AV's Folder/FLP's/Code/BSOD2528.github.io/BSOD/_config.yml
            Source: C:/Users/ADMIN/Desktop/AV's Folder/FLP's/Code/BSOD2528.github.io/BSOD
       Destination: C:/Users/ADMIN/Desktop/AV's Folder/FLP's/Code/BSOD2528.github.io/BSOD/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 0.554 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'C:/Users/ADMIN/Desktop/AV's Folder/FLP's/Code/BSOD2528.github.io/BSOD'
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `require_relative'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `setup'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:100:in `process'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby31-x64/bin/jekyll:2Q5:in `load'
        from C:/Ruby31-x64/bin/jekyll:25:in `<main>'

**Comment by ashmaroli** [comment]
> `require': cannot load such file -- webrick`

Add `gem "webrick"` to your Gemfile and you'll be serving fine.

**Comment by BSOD2528** [comment]
> > `require': cannot load such file -- webrick`
> 
> Add `gem "webrick"` to your Gemfile and you'll be serving fine.

Thank you very much - it works now :D

**Comment by iBobik** [comment]
@ashmaroli This is bug because webrick should be installed automatically if it required.

**Comment by dogweather** [comment]
The "Get up and running in _seconds_" recipe on the home page failed for me because of this.
