### ISSUE TITLE
[Bug]: bundle exec jekyll serve gives bundler: failed to load command: jekyll (/usr/local/bin/jekyll) error

### ISSUE THREAD

**Issue by christineymshen** [jekyll/jekyll#8935]
### Operating System

macOS Monterey 12.0.1

### Ruby Version

ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]

### Jekyll Version

N/A

### GitHub Pages Version

github-pages 223

### Expected Behavior

I was trying to host my personal page locally, so I used:

`bundle exec jekyll serve`

### Current Behavior

But I got error messages as enclosed below. I've googled and tried a few things such as:

`bundle install`

`bundle update`

But none of them worked. The reason that Jekyll version is listed as NA in my query here is because when I tried to get jekyll version, I also got error messages. I'll post the error messages in the comments below. Appreciate it if anyone knows how to solve this!

### Relevant log output

```shell
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/extension.rb:30:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `block in require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler.rb:176:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.0/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:23:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:484:in `exec'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:31:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:25:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/extension.rb:7:in `require_relative': dlopen(/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h')), '/usr/lib/nokogiri.bundle' (no such file) - /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle (LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri/extension.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri.rb:10:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-arm64-darwin/lib/nokogiri.rb:10:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `block in require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler.rb:176:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.0/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:23:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:484:in `exec'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:31:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:25:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
```

**Comment by christineymshen** [comment]
Error msg for `jekyll -v`

`/Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:309:in `check_for_activated_spec!': You have already activated i18n 1.8.11, but your Gemfile requires i18n 0.9.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:25:in `block in setup'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/spec_set.rb:136:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/spec_set.rb:136:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:24:in `map'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:24:in `setup'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler.rb:151:in `setup'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.2.1/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-4.2.1/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
`

**Comment by christineymshen** [comment]
running `bundle exec jekyll -v` gives a similar error msg as `bundle exec jekyll`

**Comment by ashmaroli** [comment]
The source of the error is:
```
nokogiri-1.13.1-arm64-darwin/lib/nokogiri/extension.rb:30:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
```
Looks like *native extensions* for macOS wan't built properly.
Try the following in serial order (proceed to the next only if the current fails):
- Reinstall latest Nokogiri gem by running `gem uninstall nokogiri --force && gem install nokogiri`.
- Downgrade Nokogiri via Gemfile by adding `gem "nokogiri", "1.13.0"` in your Gemfile and consequently running `bundle update`.
- Downgrade Nokogiri once again by changing above entry to `"1.12.5"` and running `bundle update`.

**Comment by christineymshen** [comment]
> The source of the error is:
> 
> ```
> nokogiri-1.13.1-arm64-darwin/lib/nokogiri/extension.rb:30:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
> ```
> 
> Looks like _native extensions_ for macOS wan't built properly. Try the following in serial order (proceed to the next only if the current fails):
> 
> * Reinstall latest Nokogiri gem by running `gem uninstall nokogiri --force && gem install nokogiri`.
> * Downgrade Nokogiri via Gemfile by adding `gem "nokogiri", "1.13.0"` in your Gemfile and consequently running `bundle update`.
> * Downgrade Nokogiri once again by changing above entry to `"1.12.5"` and running `bundle update`.

Hi ashmaroli!

Thanks for your reply! I've tried what you suggested. Still doesn't work. Here are the error messages I got.

After running `gem uninstall nokogiri --force && gem install nokogiri`, I got the following error message.

`Directory not empty @ dir_s_rmdir - /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-x86_64-darwin`.

I (maybe this isn't the right thing to do) manually deleted these two folders:

- /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.13.1-x86_64-darwin
- /Library/Ruby/Gems/2.6.0/doc/nokogiri-1.13.1-x86_64-darwin/

Then I rerun `gem uninstall nokogiri --force && gem install nokogiri`. This time it finished running without error, but only installed nokogiri 1.13.1 x86_64. So at this point if I try to run `bundle exec jekyll serve`, I get the following msg: `Could not find nokogiri-1.13.1-arm64-darwin in any of the sources`. So I run `bundle update`, which installs nokogiri 1.13.1 arm64. But then running `bundle exec jekyll serve` just gives the same error msg as I posted originally. 

I then tried the second and third suggestions to downgrade nokogiri to 1.13.0 then to 1.12.5, in both cases, I got similar error messages as what I originally got. Here I post the one for 1.12.5:

```
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/extension.rb:30:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/extension.rb:30:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri.rb:11:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri.rb:11:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `block in require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler.rb:176:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.0/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:23:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:484:in `exec'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:31:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:25:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/extension.rb:7:in `require_relative': dlopen(/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h')), '/usr/lib/nokogiri.bundle' (no such file) - /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/2.6/nokogiri.bundle (LoadError)
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/extension.rb:7:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri.rb:11:in `require_relative'
	from /Library/Ruby/Gems/2.6.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri.rb:11:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:55:in `block in require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/runtime.rb:44:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler.rb:176:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.0/lib/jekyll/plugin_manager.rb:51:in `require_from_bundler'
	from /Library/Ruby/Gems/2.6.0/gems/jekyll-3.9.0/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli/exec.rb:23:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:484:in `exec'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:31:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/cli.rb:25:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'

```

Any thoughts~~~?

**Comment by ashmaroli** [comment]
> Any thoughts~~~?

Yes. Uninstall this version again and proceed to step 2 in my previous comment.

**Comment by christineymshen** [comment]
> > Any thoughts~~~?
> 
> Yes. Uninstall this version again and proceed to step 2 in my previous comment.

Hi!

As I mentioned in my last reply. These are results after trying all three steps. The error msg I posted is after the third step. The error msg I got for step 2 is very similar, hence I didn't post it.

**Comment by ashmaroli** [comment]
> These are results after trying all three steps.

Ah! Sorry, I overlooked the `1.12.5` in your trace report.
Hmm..
Have you followed the docs at http://jekyllrb.com/docs/installation/macos/?

**Comment by christineymshen** [comment]
> > These are results after trying all three steps.
> 
> Ah! Sorry, I overlooked the `1.12.5` in your trace report. Hmm.. Have you followed the docs at http://jekyllrb.com/docs/installation/macos/?

Um ... I set these up a while ago. I think at that time I followed [this link](https://www.taniarascia.com/make-a-static-website-with-jekyll/). It's been working ok. But it's been a few months since I last tried to update anything on my page. And when I tried yesterday it suddenly gave me these errors.

 I'll go through your link later to see whether can make it work!

**Comment by christineymshen** [comment]
> > > These are results after trying all three steps.
> > 
> > 
> > Ah! Sorry, I overlooked the `1.12.5` in your trace report. Hmm.. Have you followed the docs at http://jekyllrb.com/docs/installation/macos/?
> 
> Um ... I set these up a while ago. I think at that time I followed [this link](https://www.taniarascia.com/make-a-static-website-with-jekyll/). It's been working ok. But it's been a few months since I last tried to update anything on my page. And when I tried yesterday it suddenly gave me these errors.
> 
> I'll go through your link later to see whether can make it work!

Hey! Happy to report that now it's working! Honestly I'm not sure exactly how and why things work or not. But here's what I did (mainly to leave a record for myself, and in case it might be helpful to anyone ...)

1. I noticed that the ruby version I had was 2.6.0, but the latest should be at least 3.0
2. Following your link, I was able to install the latest ruby
3. after that, when I try to run bundle exec jekyll again, it made some progress and showed me a different error message, which is eesntially [this problem](https://github.com/jekyll/jekyll/issues/8523). So I just followed the solutions there to manually install the four gems that are missing, then it worked

As someone who's not familiar with ruby/ gem, or in general the very basics for building static webpage, everytime I want to update anything, it's a thrilling experience. I guess maybe I need to one day try to really know what's going on behind the hood, otherwise eventually the same thing will be recurring from time to time that I'll need to deal with error messages/ bugs which I have no idea what they mean and how to fix and just blindly rely on google ... Having complained all these, I am very grateful for the community's help here!!!

**Comment by ashmaroli** [comment]
Glad that you got things to work @christineymshen. TBH, there is no requirement for Ruby 3.0. Jekyll works fine on Ruby 2.5 as well.
If only managing Ruby environment wasn't this tasking....

Oh well, Happy Jekyllin'!

**Comment by christineymshen** [comment]
> Glad that you got things to work @christineymshen. TBH, there is no requirement for Ruby 3.0. Jekyll works fine on Ruby 2.5 as well. If only managing Ruby environment wasn't this tasking....
> 
> Oh well, Happy Jekyllin'!

Yeah I guess as an amateur user, I don't have a good understanding of how things are linked together. So everytime when there's a bug, it's like a treasure hunt. I'd be trying different stuff and not really sure exactly what worked. Even when it's working now, I feel like I'll just be waiting for it to break down the next time. Um ... I'd like to ask actually, anything you might recommend reading if I want to have a better understanding of jekyll/ruby/gem~~~? 

And want to say I really appreciate your help!!!

**Comment by ashmaroli** [comment]
> anything you might recommend reading if I want to have a better understanding of jekyll/ruby/gem

As a Jekyll user, being thorough with everything under https://jekyllrb.com/docs/ is a good start and in most cases, it'd be all that's needed.
Regarding tracing errors, there isn't a single source of truth. The best route would be to googling the *error message*. In your case, it would be `cannot load such file -- nokogiri/nokogiri (LoadError)`. There's a high probability of someone else having encountered the same or *very similar* situation before you.

**Comment by christineymshen** [comment]
> > anything you might recommend reading if I want to have a better understanding of jekyll/ruby/gem
> 
> As a Jekyll user, being thorough with everything under https://jekyllrb.com/docs/ is a good start and in most cases, it'd be all that's needed. Regarding tracing errors, there isn't a single source of truth. The best route would be to googling the _error message_. In your case, it would be `cannot load such file -- nokogiri/nokogiri (LoadError)`. There's a high probability of someone else having encountered the same or _very similar_ situation before you.

Thanks! Very helpful~~
