### ISSUE TITLE
For the other file, you have `log_success` when you've completed. Should you use log_success here, too?

### ISSUE THREAD

**Issue by mtg06001** [jekyll/jekyll#8969]
For the other file, you have `log_success` when you've completed. Should you use log_success here, too?

<img width="1020" alt="Screen Shot 2022-02-11 at 10 08 05 AM" src="https://user-images.githubusercontent.com/237985/153645717-b1568790-5cf3-4c76-807c-86ea62bb0445.png">

_Originally posted by @parkr in https://github.com/jekyll/jekyll/pull/8965#discussion_r804892030_

**Comment by ashmaroli** [comment]
Parker's question was responded to soon after.
Thank you for making some noise.
