### ISSUE TITLE
Deployment doesn't work

### ISSUE THREAD

**Issue by Wonderer11** [jekyll/jekyll#8978]
### Discussed in https://github.com/jekyll/jekyll/discussions/8977

<div type='discussions-op-text'>

<sup>Originally posted by **Wonderer11** February 27, 2022</sup>
I want to deploy the latest Jekyll version on GitHub pages and I follow the tutorial https://jekyllrb.com/docs/continuous-integration/github-actions/ but the GitHub action doesn't work.
If anyone had successfully deploy Jekyll 4 on GitHub pages, can you tell me how?
Thank you.</div>

**Comment by pranabdas** [comment]
@Wonderer11 Hello there, I faced some issues with GitHub pages automatic deploy, and needed to build and deploy via GitHub actions. I have created a minimal working example here <https://github.com/pranabdas/deploy-jekyll-github-action>, which is working for me. Hope it helps you.

**Comment by Wonderer11** [comment]
thank you!
