### ISSUE TITLE
[Bug]: No compatible version of github-pages exists for minima

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [jekyll/jekyll#9009]
### Operating System

Windows 10

### Ruby Version

ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]

### Jekyll Version

jekyll v4.2.2

### GitHub Pages Version

N/A

### Expected Behavior

- Comment the `jekyll` gem 
- Uncomment the "github-pages" gem
- `bundle install`
- `bundle update`
Jekyll is deployable by running `bundle exec jekyll serve`

### Current Behavior

Following the instructions in the gemfile, after commenting the `jekyll` gem and uncommenting the "github-pages" gem, a conflict happens between the two. Running `bundle update` does not fix the conflict. 

### Relevant log output

```shell
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies.....
Bundler could not find compatible versions for gem "jekyll-feed":
  In snapshot (Gemfile.lock):
    jekyll-feed (>= 0.16.0)

  In Gemfile:
    github-pages was resolved to 36, which depends on
      jekyll-feed (= 0.2.3)

    minima (~> 2.5) was resolved to 2.5.1, which depends on
      jekyll-feed (~> 0.9)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by ashmaroli** [comment]
Why are you using `github-pages-v36`? That is a very old version.
Please post the entire contents of your **`Gemfile.lock`** here for review.
Thanks.

**Comment by ItsIgnacioPortal** [comment]
Nevermind, I've moved my project to [Ghost](github.com/tryghost/ghost).
Although if someone else stumbles upon this, here's another issue I opened on Minima. I think there's a solution there: https://github.com/jekyll/minima/issues/646#issuecomment-1079638045
