### ISSUE TITLE
feat: provide an option to globally disable Liquid template tags parsing

### ISSUE THREAD

**Issue by pensierinmusica** [jekyll/jekyll#9018]
## Summary

Hi, can you please provide an option to globally disable Liquid template tags parsing through `_config.yml`?

## Motivation

Some documentation requires code examples that use double curly braces, but these get interpolated by default in Jekyll.

We have a repo that is used to generate docs both in GitHub pages and in an app where we use [Marked.js](https://marked.js.org/).

We would like the behavior to be consistent between the two by being able to disable Liquid tag parsing.

## Drawbacks

If this is provided as an option I honestly don't see what drawbacks it could have.

**Comment by ashmaroli** [comment]
Jekyll already allows you to disable Liquid *per page* by having `render_with_liquid: false` in the front matter. of the page.
Jekyll also allows assigning bulk front matter by using [Front Matter Defaults](https://jekyllrb.com/docs/configuration/front-matter-defaults/) in your config file.

**Comment by pensierinmusica** [comment]
@ashmaroli thanks! Unfortunately this doesn't work on GitHub since as of today they still use Jekyll 3.9.2 and the `render_with_liquid: false` is only available from Jekyll 4.0.

https://github.com/github/pages-gem/issues/651
