### ISSUE TITLE
Jekyll install error :Failed to build gem native extension; Error junk `:' after experssion

### ISSUE THREAD

**Issue by blackjyn** [jekyll/jekyll#9033]
My Env is on Win x64, Ruby with Devkit
```
C:\>ruby -v
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]
```

I've :
- run `ridk install` and chose all options 1,2,3 
- install libffi
- search for solutions on SFs , Googling etc but no luck
- opened issue in SASSC https://github.com/sass/sassc-ruby/issues/235

but still got this:
```
gem install sassc
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing sassc:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0 -r ./siteco
nf20220413-632-tjxszh.rb extconf.rb
creating Makefile

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
make DESTDIR\= clean

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
make DESTDIR\=
compiling ./libsass/src/ast.cpp
{standard input}: Assembler messages:
{standard input}:7466: Error: junk `:' after expression
make: *** [Makefile:238: ast.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-
2.4.0 for inspection.
Results logged to C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.
1.0/sassc-2.4.0/gem_make.out

```

![jekyllinstallerr](https://user-images.githubusercontent.com/6046191/163667434-6b73f4c1-fab1-41c1-8700-6132a835dbfe.png)

Help really needed

**Comment by ashmaroli** [comment]
Hi,
- First try rebooting your system and then try installing the `sassc` gem.
- If that doesn't work, first run `ridk enable` and then run `gem install sassc`.
- If that doesn't work, the problem might be that sassc isn't compatible with `x64-mingw-ucrt` platform. Unfortunately, that means you have to uninstall Ruby 3.1 completely, reboot, and then install ***Ruby 3.0.x or older*** and then try installing then sassc gem.

**Comment by blackjyn** [comment]
thank you! 
Unfortunately , the only working solution is **by downgrading to Rb 3.0.x .** 
```
$>ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
```


![jekyllinstal_succed_dgd](https://user-images.githubusercontent.com/6046191/163697779-dcb59e53-2817-42c1-8921-0c6d21661c28.png)
