### ISSUE TITLE
[Bug]: Collection order is ignored

### ISSUE THREAD

**Issue by andreamoro** [jekyll/jekyll#9043]
### Operating System

Ubuntu 21.10

### Ruby Version

ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]

### Jekyll Version

4.2.2

### Expected Behavior

I would expect the order of the pages in the collection to be respected as per the documentation at https://jekyllrb.com/docs/collections/#manually-ordering-documents

### Current Behavior

I've created a small test collection as such:

```
collections:
  test:
     order:
      - en/meh1.md
      - en/meh2.md 
      - it/meh3.md
      - meh0.md
```
![image](https://user-images.githubusercontent.com/5256583/164909315-c4b10d18-c78e-4600-8628-9e441ee32568.png)

The content of the file, for simplicity is as follow:
Meh + Number + Lang 

You would therefore expect 1, 2, 3 & 0, but the order is not respected.

![image](https://user-images.githubusercontent.com/5256583/164909343-45b128f4-27ca-4c8f-80fb-0884b5822698.png)

### Code Sample

The relevant code to cycle through the collection is as below.
```
    {% assign items = site.test %}
    {% for item in items %}
        {{ item }}
        <hr>
    {% endfor %}
```

**Comment by ashmaroli** [comment]
Hi @andreamoro 
I was not able to reproduce this on my Windows system.
Could you try shuffling the order in your config file and test if the loop gets updated..?

P.S. Don't forget to restart your server after every save to your config file.

**Comment by TakatoKinoshita** [comment]
I faced a similar problem on
+ macOS 12.6
+ ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
+ jekyll 3.9.2

**Comment by dashcambike** [comment]
What is in `meh*.md`?

I encountered this problem, and it was caused by having the key `order` in my pages. After removing `order`, the manual sorting worked fine.

**Comment by ashmaroli** [comment]
@TakatoKinoshita Custom ordering of documents in a collection is not available on Jekyll 3.x. You will have use Jekyll 4.x for this feature.

**Comment by TakatoKinoshita** [comment]
@ashmaroli Thank you for your support.

Actually, I found out the cause was Jekyll's version after I posted the comment, but I also found out that the actual issue is that [github pages only supports up to Jekyll 3.x](https://pages.github.com/versions/).

I had forgotten I had posted here until you replied .... Anyway, I appreciate your kind response.

**Comment by ashmaroli** [comment]
You can configure **GitHub Actions** to build and deploy your site using Jekyll 4.x if Jekyll 3.9 is not sufficient for your needs.
