### ISSUE TITLE
[Docs]: Access site variable in Jekyll Command

### ISSUE THREAD

**Issue by mslinn** [jekyll/jekyll#9060]
## Motivation
Seems like there must be a way for a custom Jekyll command to access the `site` variable, but I have not found it.

## Suggestion
I expect that the `init_with_program` method will be the place that the `site` variable will need to be accessed from.

Please document how to do so.

**Comment by ashmaroli** [comment]
As documented at https://jekyllrb.com/docs/plugins/commands/, the `:init_with_program` class method simply takes an instance of `Mercenary::Program` from which all `options` provided via the terminal can be accessed.

At the outset, there is no `site` or `Jekyll::Site` instance to hook onto. It is to be initialised by the command itself using the `options` extracted from the `Mercenary::Program` instance earlier.

Please refer to implementation of existing commands such as `build`, `doctor`, `serve`, etc at `lib/jekyll/commands/` for further details.
