### ISSUE TITLE
command not found: jekyll

### ISSUE THREAD

**Issue by xiaoyouPrince** [jekyll/jekyll#9072]
➜  ~ gem install jekyll
Successfully installed jekyll-4.2.2
Parsing documentation for jekyll-4.2.2
Done installing documentation for jekyll after 0 seconds
1 gem installed
➜  ~ jekyll
zsh: command not found: jekyll

**Comment by phieri** [comment]
What operating system and Ruby version?

**Comment by xiaoyouPrince** [comment]
thank you for reply me!

OS: macOS Monterey 12.3.1
RubyVersion: 2.6.8(system default). and i have installed the latest version(3.0.2)

------------------------------

I have solved this problem now。

1. brew install ruby ----> then reopen iTerm

It may be that I haven't shut down the machine for a long time. After I shut down the machine and start it again, the command will work normally。

Then I found that cocoapods could not be used. Then I installed RVM and reinstalled cocoapods using the system version. Then it was OK
