### ISSUE TITLE
[Bug]: Absolute `/README.md` link is translated to relative link

### ISSUE THREAD

**Issue by krystof-k** [jekyll/jekyll#9083]
### Operating System

macOS Big Sur 11.6.7

### Ruby Version

ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-darwin20]

### Jekyll Version

jekyll 3.9.2

### GitHub Pages Version

226

### Expected Behavior

Create `/README.md` and `/sub/README.md` file with the following contents:

```markdown
[link](/README.md)
```

Run `jekyll serve` and visit `localhost:4000/sub`. Expected contents:

```html
<p><a href="/">link</a></p>
```

Now rename the `sub` folder to `subfolder` and visit `localhost:4000/subfolder`. Expected contents:

```html
<p><a href="/">link</a></p>
```

### Current Behavior

Run `jekyll serve` and visit `localhost:4000/sub`. Actual contents:

```html
<p><a href="/sub/">link</a></p>
```

Now rename the `sub` folder to `subfolder` and visit `localhost:4000/subfolder`. Actual contents:

```html
<p><a href="/README.md">link</a></p>
```

`jekyll build` results to the same result as when `jekyll serve` is run for the first time.

**Comment by 966556296635** [comment]
#4567
