### ISSUE TITLE
[Docs]: Gem-Based Themes and Hooks

### ISSUE THREAD

**Issue by N7K4** [jekyll/jekyll#9121]
## Motivation

In ticket #6361 (asked 2017 closed 2019) was a question to exclude files from a theme. The feature was rejected.

I found a workaround with the `hooks`, this may worth to be mentioned in the docu.

## Suggestion

The situation is the following:

My theme has some default pages, where I described the features of the theme (I put some front matter markdown files below assets/pages).
The consumer of my theme was NOT able to hide the pages, they where always redered and present in the _site folder.

On the consumer side, I created an plugin `_plugins/removePagesFromTheme.rb` with the content

```ruby
Jekyll::Hooks.register :site, :pre_render do |site|
  site.pages.reject!{|s| s.relative_path.start_with?('assets/pages/theme-features/')}
end
```
With the hook I was able to ignore the files from the theme :-)

**Comment by ashmaroli** [comment]
Themes should not ideally inject default pages. If it does anyways, the theme should have the plugin to manage such pages bundled as a dependency.
Closing as this is an edge-case.
