### ISSUE TITLE
[Bug]: Default layout not loaded

### ISSUE THREAD

**Issue by remino** [jekyll/jekyll#9143]
### Operating System

macOS 12.6

### Ruby Version

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

### Jekyll Version

jekyll 4.2.2

### GitHub Pages Version

github-pages 227

### Expected Behavior

I expect my site to use the default layout when needed or when specified, and not use any theme when I don’t want any.

### Current Behavior

No matter if a `default.html` layout file is present in `layouts`, and no matter if `layout: default` is specified in the frontmatter of the source Markdown file, the default layout is never used.

When using only the jekyll gem without github-pages, in the case of `index.md`, if there is no layout specified in the frontmatter is specified, a Webrick directory listing is displayed instead. If a theme is specified, only the HTML of the Markdown document is output; no HTML of the default layout.

When using the github-pages gem, the default jekyll-theme-primer always takes over, no matter if I want it or not. The github-pages seems to override my config with jekyll-theme-primer as its default, and there is no way for me to disable the theme.

### Relevant log output

```shell
Nothing of relevance appears in the log. But sometimes there is a mention of the “default” layout not being found.


Configuration file: /Users/[redacted]/_config.yml
            Source: /Users/[redacted]/src
       Destination: /Users/[redacted]/site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 0.014 seconds.
 Auto-regeneration: enabled for 'src'
LiveReload address: http://127.0.0.1:35729
    Server address: http://127.0.0.1:4000/jeksite/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2022-10-03 13:01:08
                    index.md
                    ...done in 0.025011 seconds.

      Regenerating: 1 file(s) changed at 2022-10-03 13:01:38
                    index.md
                    ...done in 0.003799 seconds.
```
```


### Code Sample

### _config.yml

```yml
data_dir: data
destination: site
includes_dir: includes
layouts_dir: layouts
source: src

sass:
  sass_dir: sass
```

### src/index.md

```md
# Layout Not Specified
```

### src/specified.md

```md
---
layout: default
---

# Layout Specified
```

### layouts/default.html

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{{ page.title }}</title>
	</head>
	<body>
		<h1>Custom Layout</h1>
		<hr />
		{{ content }}
	</body>
</html>
```

### Gemfile

```rb
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
# gem "jekyll", "~> 4.2.2"

gem "faraday-retry", "~> 2.0"
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]
gem "prettier"
gem "wdm", "~> 0.1.1", platforms: %i[mingw x64_mingw mswin]
gem "webrick"

platforms :mingw, :x64_mingw, :mswin, :jruby do
	gem "tzinfo", "~> 1.2"
	gem "tzinfo-data"
end
```

**Comment by ashmaroli** [comment]
Hello @remino

First of all, let me inform you that as of v4.2.x, Jekyll out-of-the-box doesn't treat a `default` layout with special status. It is just like any other layout irrespective of the name. (*In that sense, l admit, the name `default` is misleading.*). Therefore, if you want Jekyll to assign a layout to a Markdown file, you will have to explicitly define the `layout` key in the front matter or consider using `Front matter defaults` via your config file or resort to using a third-party plugin (like `jekyll-default-layout`).

Secondly, `github-pages` gem is not under our control. So we cannot address issues arising from using the gem. Therefore, it loading `jekyll-theme-primer` is not because of Jekyll. Technically, that gem is meant to emulate the GitHub Pages service as close as possible. It already includes the plugin I referenced above.

**Comment by remino** [comment]
Hi @ashmaroli,

Thanks for your reply and sorry for the misunderstanding.

It’s been a while since I dealt with GitHub Pages and Jekyll, so I wasn’t sure of the relationship between the two anymore. I’ve reported a separate issue to them, so I’ll focus on the one here that arises when only using the plain `jekyll` gem.

As you suggested, I read about the defaults you mentioned. I ahead the following to my `_config.yml`:

```yaml
defaults:
  values:
    layout: default
```

But even then, it’s making no difference.

I tried with `src/index.md` containing front-matter:

```md
---
layouts: default
---

# Hello
```

And again without:

```md
# Hello
```

With my custom layout in `layouts/default.html`:

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{{ page.title }}</title>
	</head>
	<body>
		<h1>Custom Layout</h1>
		<hr />
		{{ content }}
	</body>
</html>
```

Still then, when visiting the site at `/`, all I get is the following `text/html` response body:

```html
<h1 id="hello">Hello</h1>
```

The output of Jekyll in the terminal is not complaining about any layout file not being found.

**Comment by ashmaroli** [comment]
Okay, as it stands, your directives are incorrect.
Front matter key should be `layout` (singular).
And default front matter in the config files takes a list of mappings, not a mapping directly. Try this instead:

```yaml
# _config.yml

defaults:
  - scope:
      type: pages
    values:
      layout: default
```

**Comment by remino** [comment]
My apologies. I did notice that error and corrected my config, and I updated my comment. But either way, it still does not work.

I went ahead and pushed a sample repo of my broken Jekyll site:
https://github.com/remino/broken-jekyll

**Comment by remino** [comment]
I also pushed a `no-config` branch, with the configuration file removed, added front-matter to `index.md`, and moved all files to their default locations (`_layouts`, etc.)

Yet still, both `index.md` and `specified.md` will render as `index.html` and `specified.html` with no custom layout.

There is a custom `_layouts/default.html`, like the one before, but Jekyll is not using it as it should.

Although, this time, there is no file listing.

**Comment by remino** [comment]
Alright, so in both branches, when I mentioned `layout` in the front-matter of any file, I actually wrote `layouts`.

I fixed the typo in both branches. Now `no-config` works, but `main` remains unaffected.

**Comment by ashmaroli** [comment]
The `main` branch doesn't work because your `layouts` directory is outside `src`. Move the directory into `src` and add an empty front matter to `src/index.md`:
```
---
---
# Hello
```

**Comment by remino** [comment]
You’re right. I had to add an empty front-matter. I also just read the following:

> You must include front matter on the page for Jekyll to process any Liquid tags on it.
— https://jekyllrb.com/docs/step-by-step/03-front-matter/

Although, I was under the impression the `layouts_dir` setting was relative to the location of the `_config.yml` file and not the `source` directory. I can’t find a mention of it in the docs yet.

I’ll close this ticket because it seems I simply had a poor understanding of Jekyll and it was not a bug after all.

Thank you for the help, @ashmaroli.

**Comment by remino** [comment]
Here there was a big fat warning about directories after all. Turns out I’m just blind:

> In general, make directory path values in configuration keys like plugins_dir relative to the current working directory, not the site source. The sass configuration key is an exception, where values must be relative to the site source.
— https://jekyllrb.com/docs/configuration/default/

**Comment by ashmaroli** [comment]
Hmm.. I wouldn't blame you for getting misled because a lot of legacy behavior and documentation is inconsistent with more recent behavior. Anyways, I'm glad that your issue got resolved.
