### ISSUE TITLE
`load': incompatible marshal file format (can't be read) (TypeError)  format version 4.8 required; 60.60 given

### ISSUE THREAD

**Issue by devlopersfield** [jekyll/jekyll#9147]
[jekyll serve problem.txt](https://github.com/jekyll/jekyll/files/9707163/jekyll.serve.problem.txt)
i am facing this error when  trying to serve using 
"bundle exec jekyll serve"
could you please assist me in this

**Comment by ashmaroli** [comment]
@devlopersfield Try deleting the `.jekyll-cache` folder and start  fresh `jekyll serve` session

**Comment by devlopersfield** [comment]
@ashmaroli thanks, it works for me 👍
