### ISSUE TITLE
[Bug]: 4.3 not reading data from `site.<collection>` correctly.

### ISSUE THREAD

**Issue by JKarlavige** [jekyll/jekyll#9165]
### Operating System

macOS Monterey 

### Ruby Version

ruby 3.0.3p157

### Jekyll Version

jekyll 4.3

### Expected Behavior

On version 4.2.2, we have a `_data` collection, reading data from here works as expected, for example: `{{site.data.customers}}`. When logging the data, it shows an object with all properties.
![image](https://user-images.githubusercontent.com/13647110/197221035-3a42a625-fdf9-463f-bced-9efe50837f56.png)

In collections where we use a `name` property, that property is set correctly on the site, for example when using: `{{include.event.name}}`.
![image](https://user-images.githubusercontent.com/13647110/197223492-caf0db6f-0abe-4bd6-ba54-3b287c0d5dfa.png)

### Current Behavior

Seeing odd behavior when reading our _data with `site.data`. When logging the data it shows a Jekyll hash, rather than the actual object: `site.data.customers: #<Jekyll::DataHash:0x000000012cad8db0>`

The `name` property is also being replaced by the filename in all collections. In our `events` collection, we have a `name` property is each file within the collection, for example: `name: Coalesce 2022`. However, the `name` property is replaced with the filename on the site in Jekyll 4.3.0 when using `{{include.event.name}}`. Screenshots below:
<img width="1338" alt="Screen Shot 2022-10-21 at 2 54 07 PM" src="https://user-images.githubusercontent.com/13647110/197221629-fc2e8ac2-e55c-46cf-a364-ce3ccb7208a0.png">

![image](https://user-images.githubusercontent.com/13647110/197222989-ff367ceb-ae70-4472-8017-56a8f60cffaa.png)
![image](https://user-images.githubusercontent.com/13647110/197223045-b5cb6e70-cae0-4c19-9369-519807094db2.png)

The same is occurring for another collection `_resource-categories/case-studies.md`:
```
---
name: Case studies
singular: Case study
slug: case-studies
description: ""
---
```
And when logged, the name property is replaced with the file name:
![image](https://user-images.githubusercontent.com/13647110/197231237-cef173d0-0fae-4a44-82fc-55e5992272d9.png)

### Relevant log output

```shell
Build installed latest Jekyll 4.3.0 version:
9:37:35 AM: Fetching jekyll 4.3.0
9:37:36 AM: Installing jekyll 4.3.0

We noticed these issues after Jekyll 4.3.0 was installed.
Reverting to Jekyll 4.2.2 reverted the issue:

10:10:58 AM: Fetching jekyll 4.2.2
10:10:58 AM: Installing jekyll 4.2.2
```

**Comment by ashmaroli** [comment]
@JKarlavige May I know how exactly you're logging the `site.data` object. Yes, there has been an internal change into `Jekyll::DataHash` object, but I had tried my best to not expose that detail to users to maintain backwards compatibility. Guess, I overlooked something.

Is the repository accessible to public?

**Comment by ashmaroli** [comment]
@JKarlavige I have submitted a patch to fix the `name` attribute issue. Could you please cross-verify if that is acceptable to your use-case?
To check, you may point your Gemfile to the PR as:
```ruby
gem "jekyll", github: "jekyll/jekyll", ref: "refs/pull/9167/head"
```
Thanks.

**Comment by JKarlavige** [comment]
> @JKarlavige May I know how exactly you're logging the `site.data` object. Yes, there has been an internal change into `Jekyll::DataHash` object, but I had tried my best to not expose that detail to users to maintain backwards compatibility. Guess, I overlooked something.
> 
> Is the repository accessible to public?

Hi @ashmaroli, I can confirm your update looks to have fix the issues with the `name` property. However, I am still seeing issues with the items in our `site.data` collection. Unfortunately this is a private repo, but I will share as much as I could.

We have multiple `.yml` files within the `_data/customers` directory. Each `.yml` file includes a `name` and `img` property.
![image](https://user-images.githubusercontent.com/13647110/197852904-51e20c03-f72a-4018-b318-32b4728c5edc.png)

On Jekyll 4.2.2, we were accessing these files using `site.data.customers`,  which returned an array of objects with the data from each `.yml` file.

On the new version of Jekyll, the same call returns: `site.data.customers: #<Jekyll::DataHash:0x0000000129e50478>`.

In our frontmatter, we have an array of customers:
```
customers:
  - Customer name
  - Customer name
  - Customer name
```

We are looping through this array, and pulling the data from the customer file under `_data/customers`:

```
{% for customer in customers %}
  {% assign thisCustomer = site.data.customers | where: "name", customer | first %}
     <div class="customer-img-contain">
       <img src="{{thisCustomer.img}}" alt="{{thisCustomer.name}}" width="120" height="45">
     </div>
{% endfor %}
```

However, when trying to get the customer file with the line: `{% assign thisCustomer = site.data.customers | where: "name", customer | first %}` it is unable to find that file as it appears `site.data.customers` is returning that data hash and not the actual object.

I am using the following command to log the data:
```
<script>
  console.log('site.data.customers:', JSON.parse(decodeURIComponent("{{ site.data.customers | jsonify | uri_escape }}")))
</script>
```

**Comment by suppadeliux** [comment]
Hello, 
Having a similar issue on our documentation site, since the update.
Before => `context.registers[:site].data['chapter_link']` inside one of our plugins, just to return the right value in order to handle it.
But now, the same calling returns simply => `Jekyll::DataEntry:0x00007f088f3a1cd8`
Any idea or hint about this?
I know is the hash which is returned now, but I have no idea where to fix this.
Anyways, thanks for the help!

**Comment by ashmaroli** [comment]
@JKarlavige Thank you for giving me additional context to reproduce the issue. I was able to create a sample using clues from your opening post and reproduce the error using the `jsonify` filter.
While I was able to "solve" the issue, I decided that the better solution would be to revert the commit that introduced the change.

**Comment by ashmaroli** [comment]
@suppadeliux Thank you for reporting the issue.
I have decided to revert the change and release `v4.3.1` either today or tomorrow.

**Comment by suppadeliux** [comment]
Thanks for the quick fix! 🎉 🎉 🎉, everything is working as expected with the new version (`4.3.1`)
