### ISSUE TITLE
The excerpt of page including the style of rich text

### ISSUE THREAD

**Issue by ZhongUncle** [jekyll/jekyll#9189]
Hi, I met a trouble when I generate an excerpt of page. If I have a Markdown title or some rich text at the beginning of the content, the excerpt will show it.

For example, if the Markdown file is:
```
---
layout: article
---
## Introduction
This is the test content.
```
You can see the content of page below.
<img width="776" alt="screenshot" src="https://user-images.githubusercontent.com/78771985/202871437-de779d67-1cd4-4dbc-aed3-23c42937dbde.png">

Is there any method to ignore it? Or using a syntax to select specified content? I have tried the `page_excerpts`, but it just specify the content from the beginning, and can't solve the problem.

**Comment by Xaymar** [comment]
As a workaround, you can use [strip_html](https://shopify.github.io/liquid/filters/strip_html/) to strip out unwanted HTML from an excerpt. For example `var.excerpt | strip_html | truncatewords: 60` will strip out unwanted HTML tags, and truncate the whole excerpt to 60 words.

**Comment by ZhongUncle** [comment]
> As a workaround, you can use [strip_html](https://shopify.github.io/liquid/filters/strip_html/) to strip out unwanted HTML from an excerpt. For example `var.excerpt | strip_html | truncatewords: 60` will strip out unwanted HTML tags, and truncate the whole excerpt to 60 words.

Thanks for your suggestion! I find a nice way to show what I want!

**Comment by ashmaroli** [comment]
@ZhongUncle Jekyll will by default select text from beginning till first encounter of `\n\n` (first blank line). There are two front matter options for customizing this behavior:
- `excerpt`: Define entire excerpt content.
- `excerpt_separator`: Change the default `\n\n` to a substring of your choice. For example: `<! more >`, etc.

**Comment by ZhongUncle** [comment]
> @ZhongUncle Jekyll will by default select text from beginning till first encounter of `\n\n` (first blank line). There are two front matter options for customizing this behavior:
> 
> * `excerpt`: Define entire excerpt content.
> * `excerpt_separator`: Change the default `\n\n` to a substring of your choice. For example: `<! more >`, etc.

Thanks a lot! It helps me more!
