### ISSUE TITLE
[Bug]: HTML-Proofer found 1 failure!

### ISSUE THREAD

**Issue by haircutfish** [jekyll/jekyll#9238]
### Operating System

Windows 10 Pro 19045.2364

### Ruby Version

ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x64-mingw32]

### Jekyll Version

jekyll 4.3.1

### GitHub Pages Version

Latest

### Expected Behavior

I expect the site to build and serve properly

### Current Behavior

Currently I can serve on my local machine
![image](https://user-images.githubusercontent.com/68355453/210007175-2acaf699-545f-471e-b638-fba2005219de.png)

But when I try and push it to Github, it fails with HTML-Proofer found 1 failure!
![image](https://user-images.githubusercontent.com/68355453/210007938-8ed0dd91-93fe-4933-b2c8-66eb719f46ed.png)

![image](https://user-images.githubusercontent.com/68355453/210007927-6bf1b9b9-a838-4db4-b252-e9fdcb9f8fb8.png)

**Comment by ashmaroli** [comment]
This is not Jekyll's fault. Your template / theme is responsible. If you look at the HTMLProofer error, it's pointing to a pop-up link referencing a non-existent image fileurl. Jekyll does not generate URLs of that pattern.

Hence closing.
