### ISSUE TITLE
[Bug]: `_sass` and `_layouts` directories are not generated at all

### ISSUE THREAD

**Issue by EmilySeville7cfg** [jekyll/jekyll#9241]
### Operating System

Ubuntu 22.04.1 LTS

### Ruby Version

ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

### Jekyll Version

jekyll 4.3.1

### GitHub Pages Version

bundler: command not found: github-pages

### Expected Behavior

`_sass` and `_layouts` directories to be generated at `bundle exec jekyll serve`.

### Current Behavior

`_sass` and `_layouts` directories are not generated at all.

### Code Sample

Available [here](https://github.com/emilyseville7cfg-better-emacs/site.github.io).

**Comment by EmilySeville7cfg** [comment]
The original issue is [here](https://github.com/emilyseville7cfg-better-emacs/site.github.io/issues/11).

**Comment by ashmaroli** [comment]
The reason behind this is your `baseurl` setting.
Set it as `baseurl: "/site.github.io"` and your *code sample* should be fine.
Repeat similarly for the other repo. If stylesheets do not resolve correctly even after setting baseurl correctly, ensure your templates are using Jekyll's URLFilters such as `relative_url` / `absolute_url`.
