### ISSUE TITLE
[Docs]: Be sure to move drafts and posts into custom collections directory

### ISSUE THREAD

**Issue by y377** [jekyll/jekyll#9253]
## Motivation
Hi, everyone, although after 2 years of learning and using Jekyll, I can basically use it smoothly now. My theme has exceeded the layout and layout that a blog should have, but I want to improve it better. I I want to build more functions (including but not limited to the layout of posts and pages), but now I have a confusion and hope to get more professional guidance!

```shell
.
├── assets
│   └── css
│       └── main.scss
├── collections-folder  # This is the folder where the three collections are merged
│   ├── JavaScript  #this is collection
│   │   ├── and_more.md   #layout: long_document
│   │   ├── doc1.md           #layout: long_document
│   │   ├── doc2.md           #layout: long_document
│   │   └── doc3.md           #layout: long_document
│   ├── jekyll          #this is collection
│   │   ├── and_more.md   #layout: doc
│   │   ├── doc1.md           #layout: doc
│   │   ├── doc2.md           #layout: doc
│   │   └── doc3.md           #layout: doc
│   └── ruby             #this is collection
│       ├── and_more.md
│       ├── doc1.md
│       ├── doc2.md
│       └── doc3.md
├── _config.yml
├── _data
├── _drafts
├── _includes
├── index.md
├── _layouts
│   └── default.html
├── _posts  #layout: post
└── _sass
    └── main.scss

```

## Suggestion

What is the best way to use `permalink: /:collection/:name` for collections (JavaScript, ruby, jekyll) in `collection-folder` if I want the directory structure shown above?
Because I saw in the official docs that `_drafts` and `_posts` need to be migrated, this got me stuck in the build
> If you specify a directory to store all your collections in the same place with collections_dir: my_collections, then you will need to move your _drafts and _posts directory to my_collections/_drafts and my_collections/_posts. Note that, the name of your collections directory cannot start with an underscore (`_`).

**Comment by ashmaroli** [comment]
@y377 What the documentation means is that you should move `_drafts` to `collection-folder/_drafts`.

Also, please avoid opening "issues" regarding questions about usage. "Issues" are only for reporting bugs and tracking development. For general stuff, head to "Discussions" or our community forum at https://talk.jekyllrb.com.

Thanks.

**Comment by y377** [comment]
> @y377 What the documentation means is that you should move `_drafts` to `collection-folder/_drafts`.
> 
> Also, please avoid opening "issues" regarding questions about usage. "Issues" are only for reporting bugs and tracking development. For general stuff, head to "Discussions" or our community forum at https://talk.jekyllrb.com.
> 
> Thanks.
Ok, **next time I will pay attention to the issue specification**, since I saw your reply, please allow me to consult with you here
I have understood the meaning of the explanation in the official document, but I want the structure of the above code block, how should I set it? if you know!

**Comment by ashmaroli** [comment]
Since "drafts" and "posts" are also "collections", you cannot have them separate from user-defined collections.
