### ISSUE TITLE
[Bug]: All the rests will not be processed and shown if there exists an 'iframe'

### ISSUE THREAD

**Issue by LiuJiewenTT** [jekyll/jekyll#9266]
### Operating System

Latest

### Ruby Version

Latest

### Jekyll Version

Latest

### GitHub Pages Version

Latest

### Expected Behavior

All my content after iframe should be shown.

### Current Behavior

Nothing after iframe will be shown.

### Relevant log output

I don't think the log shows anything useful. Anyway, I paste it below:

```shell
[link](https://pipelines.actions.githubusercontent.com/serviceHosts/35cc43f2-a2b5-4588-a9e6-cb727f4fb0de/_apis/pipelines/1/runs/147/signedlogcontent/2?urlExpires=2023-01-22T10%3A13%3A19.3996281Z&urlSigningMethod=HMACV1&urlSignature=pq2krwthNZ17dsbFPTUJ0zNyeXukt1SEZAboGn1GyQs%3D)
```

### Code Sample

```
# Test markdown file
hello
## Heading one
<iframe style="height:800; width:100%" src="https://github.com/Creators-of-Create/Create/wiki/Useful-Tags" />

nothing will be shown from this line to the end of file.

---

The iframe.

## Heading two

something...
```

**Comment by leabs** [comment]
@LiuJiewenTT The iframe element isn't self closing and is not valid HTML.  I tested it out without self closing and it worked as expected.

Example:
```html
# Test markdown file

hello

## Heading one

<iframe style="height:800; width:100%" src="https://github.com/Creators-of-Create/Create/wiki/Useful-Tags" ></iframe>

nothing will be shown from this line to the end of file.

---

The iframe.

## Heading two

something...
```
![Screenshot 2023-02-21 at 11 55 29 AM](https://user-images.githubusercontent.com/7071812/220409860-101b19b1-4cab-4213-93c5-8c0edfc3f00e.png)

**Comment by LiuJiewenTT** [comment]
Thank you very much. My mistake is corrected now and things go as expected.



---Original---
From: "Steven ***@***.***&gt;
Date: Wed, Feb 22, 2023 00:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jekyll/jekyll] [Bug]: All the rests will not be processed andshown if there exists an 'iframe' (Issue #9266)




 
@LiuJiewenTT The iframe element isn't self closing and is not valid HTML.  I tested it out without self closing and it worked as expected.
 
Example:
 # Test markdown file hello ## Heading one <iframe style="height:800; width:100%" src="https://github.com/Creators-of-Create/Create/wiki/Useful-Tags" &gt;</iframe&gt; nothing will be shown from this line to the end of file. --- The iframe. ## Heading two something...
