### ISSUE TITLE
[Bug]: `<details>` disclosure elements prevent markdown rendering

### ISSUE THREAD

**Issue by todb** [jekyll/jekyll#9297]
### Operating System

doesn't matter

### Ruby Version

all

### Jekyll Version

all

### Expected Behavior

Jekyll should render markdown inside an html `<details>` element.

This element is [described here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) and seems to work well with GFMD in preview.

### Current Behavior

Jekyll does not render markdown inside a `<details>` element.

### Code Sample

```markdown
Our VDP is derived from the [disclose.io](https://policymaker.disclose.io/policymaker/introduction) Policymaker, edited to cover vulnerability reports involving other parties.

<details>

  <summary>VDP (click to expand)</summary>

## Vulnerability Disclosure Policy

more words and stuff
```

Result:
![busted-markdown](https://user-images.githubusercontent.com/24144/217855077-58b0b35c-e98a-4401-b161-2215ededf157.png)

**Comment by leabs** [comment]
You can get markdown working inside of HTML elements by using [jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship): https://github.com/jeffreytse/jekyll-spaceship#6-hybrid-html-with-markdown

Also seems to work with [kramdown](https://kramdown.gettalong.org/index.html): https://kramdown.gettalong.org/syntax.html#html-blocks

There is a built in option in Jekyll, also. Using the markdownify filter in liquid:

```html
<details>
    {{ "## Vulnerability Disclosure Policy" | markdownify }}
    {{ "more words and stuff" | markdownify }}
</details>
```

Hope this was helpful

**Comment by vadimkantorov** [comment]
Jekyll Spaceship is nice, but for this working in default GitHub Pages, I guess this needs to be supported in some hotfix update to Jekyll 3.9.3 / next 3.x version :)

**Comment by horatiu-udrea** [comment]
I also think this behaviour should be provided out of the box

**Comment by Potherca** [comment]
Ran into this today with GitHub pages. Spent time trying to fix my markdown, nothing seemed to work, so went on to Google the problem. Ended up here. Cursed.

Very confusing, as the Markdown with `<details>` renders perfectly in GitHub but as soon as a (default) site is generated form the projects `README.md` things break for unclear reasons.

<details><summary><sup><kbd>Not suitable for work comment</kbd></sup></summary>

![image](https://github.com/jekyll/jekyll/assets/195757/dfaf72a0-204f-4749-a594-d315d5004b6d)


</details>

**Comment by daattali** [comment]
There is a fairly simple workaround for this issue. Simply add the attribute `markdown="1"` to the details tag.  Example:

```
<details markdown="1">
<summary>Click here</summary>
## Title
Hello **world**
</details>
```

**Comment by josephmate** [comment]
> There is a fairly simple workaround for this issue. Simply add the attribute `markdown="1"` to the details tag. Example:
> 
> ```
> <details markdown="1">
> <summary>Click here</summary>
> ## Title
> Hello **world**
> </details>
> ```

This solution worked for me. I applied it to [my blog post](https://josephmate.github.io/2025-02-26-3200p-cpu-util/).
