### ISSUE TITLE
[Bug]: Error: expected "{". (RuntimeError)

### ISSUE THREAD

**Issue by virajChuaudhary** [jekyll/jekyll#9298]
### Ruby Version

ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]

### Jekyll Version

jekyll 4.2.2

### GitHub Pages Version

Latest 

### Expected Behavior

Hello, I am Facing an issue during publishing the website
Siteleaf continuously shows this error
Error: Expected "{". (RuntimeError)
what is this and how can I solve this?

### Current Behavior

It is Working locally perfect but when i am trying to publish this using siteleaf

**Comment by leabs** [comment]
Can you try running the build command and see if you get any output that way?

Assuming you're using bundle:
```
bundle exec jekyll build --trace
```

**Comment by ashmaroli** [comment]
This most likely could be due to `jekyll-sass-converter-3.0` which uses modern Sass engine written in Dart.
This implementation doesn't allow template file and imported partial to have the same filename, e.g., `css/main.scss` importing `_sass/main.scss` is now illegal.

**Comment by virajChuaudhary** [comment]
@leabs @ashmaroli thanks it is fixed now 
@ashmaroli you are right issue is in `jekyll-sass-converter-3.0`

**Comment by tobyshorin** [comment]
@virajChuaudhary how did you figure out that this gem was the issue? I'm having a similar problem (also siteleaf).

I'm on Jekyll version 4.3.2. I have no issue building and serving locally, but when I try to publish through siteleaf (web and CLI) I get the following error:

`Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss': (RuntimeError)`

I tried your solution, but I'm not importing any partials with the same name as my master scss file. Running `bundle exec jekyll build --trace` doesn't give me any more information. Any ideas as to what to try?

**Comment by tobyshorin** [comment]
I figured it out here: https://github.com/siteleaf/community/discussions/52#discussioncomment-7275973
