### ISSUE TITLE
[Bug]: 转化scss使用了@import不兼容老版本.The conversion of scss uses @ import incompatible with the old version.

### ISSUE THREAD

**Issue by LY1806620741** [jekyll/jekyll#9311]
### Operating System

windows11

### Ruby Version

ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]

### Jekyll Version

jekyll 4.3.2

### GitHub Pages Version

Latest

### Expected Behavior

顺利编译并正常启动.Compile successfully and start normally.
```
bundle exec jekyll serve
```

### Current Behavior

```
bundle exec jekyll serve
```
error log in new jekyll version:
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    expected "{".
             Error: expected "{".
             Error: Run jekyll build --trace for more information.

### Relevant log output

```shell
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    expected "{".
             Error: expected "{".
             Error: Run jekyll build --trace for more information.
```

### Code Sample

project tree
```
├─_sass
        └─style.scss
└─assets
    ├─css
         └─style.scss(1)
```

(1):
```css
---
---

@import "style";
```

我检查出是重名引起的，但是它在jekyll老版本是可以这么做的,这个兼容问题是符合预期的么。I checked that it was caused by duplicate names, but it can be done in the old version of jekyll. Is this compatibility problem in line with expectation.

**Comment by LY1806620741** [comment]
我找到了方案,重命名`_sass/style.scss`为`_sass/_style.scss`,然后`assets/css/stype.scss`中`@import "_style";`,如果这个兼容问题无需关注那就可以关闭这个讨论。I found the scheme, rename it`_ Sass/style. scss ` is`_ sass/_ Style. scss `, then ` @ import "_style"; ` in ` assets/css/stype. scss `, If this compatibility issue doesn't need attention, you can close this discussion

**Comment by ashmaroli** [comment]
This is known issue, cannot be addressed and has been [documented here](https://github.com/jekyll/jekyll-sass-converter#dropped-support-of-importing-files-with-the-same-filename-as-their-parent-file).
