### ISSUE TITLE
[Bug]: Incremental build bulids twice on git checkout

### ISSUE THREAD

**Issue by Giszmo** [jekyll/jekyll#9325]
### Operating System

debian 5.10

### Ruby Version

ruby 2.7.4p191

### Jekyll Version

jekyll 4.2.0

### Expected Behavior

When running `bundle exec jekyll serve` and changing many files in one second, jekyll should trigger rendering only once. Maybe delay rendering by 100ms at a time to see if more changes are detected.

### Current Behavior

When running `bundle exec jekyll serve` and then changing many files in one second by doing a git checkout or a script that touches 100 files, jekyll renders after seeing the first few file changes and after it's done it runs again for the other changed files.

**Comment by Giszmo** [comment]
I was verifying my issue with a script that replaces 8k files and now I see:

```
INotify::QueueOverflowError: inotify event queue has overflowed.
```

but I think the issue exists without `QueueOverflowError`, too. Problem is, reviewing pull requests I jump between branches and build locally and it takes 50s per build and routinely it's thousands of files that change, so it should also avoid running twice in those cases.

**Comment by OratileMelamu** [comment]
[Name of file(11).PDF](https://github.com/jekyll/jekyll/files/11099303/Name.of.file.11.PDF)
https://github.com/jekyll/jekyll/issues/9325#issue-1638123059
