### ISSUE TITLE
[Docs]: Update supported macOS versions

### ISSUE THREAD

**Issue by fulldecent** [jekyll/jekyll#9402]
## Motivation

The current supported versions of [Jekyll's macOS install instructions](https://jekyllrb.com/docs/installation/macos/) are [motivated by](https://github.com/jekyll/jekyll/pull/8993#pullrequestreview-908004059) Homebrew's restrictions.

Since then, Homebrew [has changed their supported versions](https://docs.brew.sh/Installation#2). This includes removing a version that Jekyll now supports and adding a new version that we don't support.

## Suggestion

According to the justification for Jekyll's current documentation, we must remove support for Catalina (macOS 10.15) in the documentation.

But also we should consider adding support for macOS 13.

Ping @monfresh

**Comment by mattr-** [comment]
Would you have time to write up a PR for this?

**Comment by mattr-** [comment]
Thank you for the PRs! ❤️  If the instructions generally work, then I see no reason to do anything else other than update the versions.

**Comment by monfresh** [comment]
Thank you, William! I confirm that the instructions work on Big Sur, Monterey and Ventura, assuming you have a clean macOS installation and/or a clean dev setup.
