### ISSUE TITLE
[Docs]: Typo in Japanese Documents

### ISSUE THREAD

**Issue by Naoyuk** [jekyll/jekyll#9407]
I found a type at `_site`'s description in Japanese docs.
[http://jekyllrb-ja.github.io/docs/structure/](http://jekyllrb-ja.github.io/docs/structure/)
It should be like below
```
- 生成されたサイトがJ、ekyllが変換した際に配置される（デフォルトの）場所です。これを .gitignore ファイルに追加することをお勧めします。
+ 生成されたサイトがJekyllが変換した際に配置される（デフォルトの）場所です。これを .gitignore ファイルに追加することをお勧めします。
```

**Comment by mattr-** [comment]
Thanks for reporting this, but AFAIK, we don't maintain the Japanese docs. Would you please report this against their repository? https://github.com/jekyllrb-ja/jekyllrb-ja.github.io

**Comment by Naoyuk** [comment]
Sorry about that. Okay, I will. Thanks!
