### ISSUE TITLE
[Bug]: Links are all being rendered with the page URL first. 

### ISSUE THREAD

**Issue by jdromero88** [jekyll/jekyll#9446]
### Operating System

Linux Mint 21.2 x86_64

### Ruby Version

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

### Jekyll Version

jekyll 4.3.2

### GitHub Pages Version

Latest

### Expected Behavior

When I add a link to the markdown file, I expected to be rendered just to the linked address, so when I click on it can open the expected link/website
Considering the next file 2023-09-20-welcome-to-jekyll.md
```md
---
layout: post
title:  "Welcome to Jekyll!"
date:   2023-09-20 13:57:17 -0400
categories: jekyll update
---
You’ll find this post in your `_posts` directory. Go ahead and edit it and re-build the site to see your changes. You can rebuild the site in many different ways, but the most common way is to run `jekyll serve`, which launches a web server and auto-regenerates your site when a file is updated.

Jekyll requires blog post files to be named according to the following format:

I want this [link](www.jekyllrb.com) to be rendered as www.jekyll.rb and not with the page url before "http://localhost:4000/jekyll/update/2023/09/20/www.jekyllrb.com"
```

### Current Behavior

The link is on the md file, it's appended to the page URL
```md
this [link](www.jekyllrb.com) it's being rendered as "http://localhost:4000/jekyll/update/2023/09/20/www.jekyllrb.com"
```

### Code Sample

follow the quickstart from jekyll 

```bash
gem install jekyll bundler
```
```bash
jekyll new myblog
```
```bash
cd myblog
```
open the file: "2023-09-20-welcome-to-jekyll.markdown"
and update with this:
```md
---
layout: post
title:  "Welcome to Jekyll!"
date:   2023-09-20 13:57:17 -0400
categories: jekyll update
---
You’ll find this post in your `_posts` directory. Go ahead and edit it and re-build the site to see your changes. You can rebuild the site in many different ways, but the most common way is to run `jekyll serve`, which launches a web server and auto-regenerates your site when a file is updated.

Jekyll requires blog post files to be named according to the following format:

I want this [link](www.jekyllrb.com) to be rendered as www.jekyll.rb and not with the page url before "http://localhost:4000/jekyll/update/2023/09/20/www.jekyllrb.com"
```
then run
```bash
bundle exec jekyll serve
```
Browse to http://localhost:4000/ and then http://localhost:4000/jekyll/update/2023/09/20/welcome-to-jekyll.html

**Comment by NotReallyDustin** [comment]
Hello @jdromero88, I'm not sure if you've already solved this, but Instead of `[link](www.jekyllrb.com)`, use `[link](https://jekyllrb.com)`

**Comment by mattr-** [comment]
:wave: This is not a bug because `www.jekyllrb.com` is not a full web address. Browsers do the work of translating that into a full `https://www.jekyllrb.com` address for us as a convenience. @NotReallyDustin's previous comment is the correct way to write links to other websites.
