### ISSUE TITLE
[Bug]: `jekyll serve` produces unwanted 301 redirects from /page to /page/

### ISSUE THREAD

**Issue by iromanovsky** [jekyll/jekyll#9450]
### Operating System

arm-based macOS running container mcr.microsoft.com/devcontainers/jekyll:2-bullseye (Linux fe37958f288f 6.1.29-0-virt #1-Alpine SMP Wed, 17 May 2023 14:22:15 +0000 aarch64 GNU/Linux)

### Ruby Version

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux]

### Jekyll Version

3.9.3 (as github pages)

### GitHub Pages Version

224

### Expected Behavior

I expect `jekyll serve` to behave like GitHub pages, 

So when having a page with front matter like below:
```
permalink: /page
redirect_from: /page/
```

requesting `/page` would serve the page content, and requesting `/page/` would serve the HTML with redirect to address with no trailing slash.

### Current Behavior

Same as #6459 -- described very well there. It was closed as fixed, but I still see this behavior on the current version supported by GitHub pages.

when running `jekyll serve`, and having a page with front matter like below:
```
permalink: /page
redirect_from: /page/
```

produces the below result:
```
curl http://127.0.0.1:4000/page -I 
HTTP/1.1 301 Moved Permanently
Location: http://127.0.0.1:4000/page/
```
Instead of serving the content of `/page`

### Relevant log output

```
<!DOCTYPE html>
<html lang="en-US">
  <meta charset="utf-8">
  <title>Redirecting&hellip;</title>
  <link rel="canonical" href="http://localhost:4000/test">
  <script>location="http://localhost:4000/test"</script>
  <meta http-equiv="refresh" content="0; url=http://localhost:4000/test">
  <meta name="robots" content="noindex">
  <h1>Redirecting&hellip;</h1>
  <a href="http://localhost:4000/test">Click here if you are not redirected.</a>
</html>
```

### Code Sample

```
---
permalink: /page
redirect_from: /page/
---

curl http://127.0.0.1:4000/page -I 
HTTP/1.1 301 Moved Permanently
Location: http://127.0.0.1:4000/page/
```

**Comment by mattr-** [comment]
`jekyll serve` and GitHub Pages are not the same, as GitHub Pages uses nginx to serve the site and `jekyll serve` is built around WEBrick. I won't invest any time in fixing this myself but if an interested party provides a PR, I'm happy to review and merge it.
