### ISSUE TITLE
[Docs]: plugin hook ordering unclear

### ISSUE THREAD

**Issue by agowa** [jekyll/jekyll#9460]
## Motivation

I didn't find a statisfying answer to the following question:

I want to write plugin that post processes stuff another plugin did. How can I make sure that my plugin runs *after* that plugin?

In this case the plugin I want to post process uses the :site, :post_write hook. And from the current documentation it is unclear how to get "behind" this hook, as it is the last one listed and nothing about "ordering" of the hooks is listed.

The base plugin is from the repos. My plugin would be in _plugins as of now.

The motivation behind this endever is that the original plugin adds a file to the page but that file contains invalid references. So I want to search and replace these with the correct ones. Currently it is kinda working, but I still don't know if the ordering is reliable.

## Suggestion

Add a section about how to deal with such dependencies. And explain in which order hooks are executed and how to influence it.

**Comment by ashmaroli** [comment]
Hello @agowa, hooks are called in the order listed in the documentation which is exactly how it has been implemented in the source code.
So, you'd be better of using the `:site, :post_render` hook in your use-case.
