### ISSUE TITLE
feat: A question about how to let user to submit the request and upload to post automatically

### ISSUE THREAD

**Issue by Murasamess** [jekyll/jekyll#9461]

**Comment by Murasamess** [comment]
Hi all,

I want to ask about how to let users to upload the information by filing a template and upload to my website automatically ( by permission would be great). I am doing a paper sharing website for the research group

**Comment by agowa** [comment]
as jekyll is for static webpages, your request for "wordpress like CMS" is probably outside of the scope of Jekyll.
However, what you could do is setup CI/CD on either GitLab or GitHub that automatically deploys your site to your server and grant people access to the git repository of your website. That way they can update content on your website. And depending on how "fancy" you get with your git repository setup it can way exceed the capabilities of wordpress.

**Comment by mattr-** [comment]
Thanks for your question! As @agowa mentioned, this functionality is not provided by Jekyll. I will confirm it is outside the scope of the project. If this is functionality you absolutely need to have, you can follow the suggestions @agowa gave you or you may need to look for another solution other than Jekyll.
