### ISSUE TITLE
feat: Add a content or "do not delete" attribute to static_file

### ISSUE THREAD

**Issue by agowa** [jekyll/jekyll#9463]
## Summary

Allow static_file to not just copy an existing file, but also to create a new file from content. Or alternatively a property to not delete a specific file that is already in the output directory.

## Motivation

I've a need to patch a file in flight, so I wrote a filter plugin that does it, however Jekyll is overwriting (deleting) the file I placed in the output folder. And StaticFile also doesn't have a "content" property so that I could tell it to use a specific content when generating that file.
I also tried to look into the documentation where to generate a temporary copy of my file to use for `site.static_files << file`, but that wasn't documented either. I do not really want to place it somewhere random either.

Is there currently no way to dynamically create a file from within a filter plugin?

**Comment by agowa** [comment]
Found workaround for now:
```
        file_asset = Jekyll::StaticFile.new(site, File.expand_path(base), File.dirname(input), File.basename(input))
        unless site.pages.map(&:path).include?(file_asset.url.delete_prefix('/'))

          Jekyll.logger.info 'KatexModule ' + file_asset.path + ' => ' + file_asset.url
          text = File.read(file_asset.path)

          output_jekyll_file = Jekyll::PageWithoutAFile.new(site, __dir__, File.dirname(file_asset.url), File.basename(file_asset.url))
          output_page = output_jekyll_file.tap do |obj|
            obj.content = text.gsub(/url\(fonts/, 'url(/assets/webfonts')
            obj.data.merge!(
              "layout"     => nil,
              "sitemap"    => false,
              "xsl"        => false,
              "collection" => nil,
              "category"   => nil,
              "tags"       => nil,
              "permalink"  => nil,
              "excerpt"    => nil
            )

            obj.output
          end
          site.pages << output_page
          Jekyll.logger.info 'KatexModule ' + output_page.path
        end
```

**Comment by ashmaroli** [comment]
Sorry @agowa, this feature request has been declined.
