### ISSUE TITLE
[Bug]: Jekyll can support html in markdown ? 

### ISSUE THREAD

**Issue by UNIONDONG** [jekyll/jekyll#9483]
### Operating System

Ubuntu20.04

### Ruby Version

ruby 2.7.3 

### Jekyll Version

jekyll 4.2.1

### Expected Behavior

I want it to display html in markdown, how to do ?

### Current Behavior

I don't know why  that  I post one article which have some html language, but Text can't support it. 

Is there something wrong with my configuration?

![image](https://github.com/kitian616/jekyll-TeXt-theme/assets/35584433/63824fd6-9e40-4c75-a522-eccbd73ee555)

**Comment by UlyssesZh** [comment]
Whether you can use HTML in Markdown is dependent on the Markdown engine and the Markdown configurations. By default, you should be using Kramdown, and it supports HTML tags as far as I know.

Maybe you could share the source codes of your website to make it easier for others to help you troubleshoot.

**Comment by mattr-** [comment]
Closing until we have more information about whether this is an actual bug.
