### ISSUE TITLE
[Bug]: Jekyll Github Pages site doesn't "play nice" with Ruby versions required by vscode

### ISSUE THREAD

**Issue by kortina** [jekyll/jekyll#9489]
### Operating System

MacOS Sonoma 14.0

### Ruby Version

ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [arm64-darwin21]

### Jekyll Version

jekyll 3.9.0

### GitHub Pages Version

github-pages 222

### Expected Behavior

I'm trying to get linting working with the latest version of VS Code, but running into the error below.

### Current Behavior

After a recent update to VS Code, I started getting the following warning in my editor:

```
Failed to activate none environment: 
The Ruby LSP requires Ruby 3.0 or newer to run. This project is using 2.7.4.
```

I have `2.7.4` in my site's `.ruby-version` file to keep it in sync with what's used on GitHub Pages, which according to the following site is `2.7.4`:

https://pages.github.com/versions/

Does anyone have a best practice for getting a jekyll siite to play nice with the Ruby linting features in VS Code, while also keeping things in sync / compatible with GitHub Pages?

*(Also, I realize this is not technically a "bug" with jekyll, but couldn't find a better place to post. If people have suggestions for other places to ask, please lmk.)*

Thanks in advance for any advice / pointers.

**Comment by mattr-** [comment]
You can either switch ruby versions and see if there are consequences, which there shouldn't be unless you've written or are using a bunch of custom ruby plugins, or you can switch to an Actions based build workflow and use a newer version of Jekyll. 3.9 is quite old.
