### ISSUE TITLE
> ¡Hola! 👋

### ISSUE THREAD

**Issue by Leonelhdzm99** [jekyll/jekyll#9491]
> ¡Hola! 👋
> 
> Noté que la restricción que tiene para activesupport no permite utilizar la última versión.
> 
> La restricción que encontré fue `~> 7.0.0`, y la última versión disponible es `7.1.1`.
> 
> ¿Puede considerar actualizar esa restricción para que nuestros usuarios puedan usar la última y mejor versión? ¡Gracias! 💞

_Originally posted by @Leonelhdzm99 in https://github.com/jekyll/jekyll/issues/9484#issuecomment-1807469832_

**Comment by mattr-** [comment]
Español: Esta restricción es necesaria porque las versiones más nuevas rompen las pruebas.

English: This restriction is necessary because newer versions break the tests.
