### ISSUE TITLE
Found CRITICAL Vulnerability in your website!

### ISSUE THREAD

**Issue by imchiragprajapati** [jekyll/jekyll#9494]
### Operating System

Windows 11

### Ruby Version

1

### Jekyll Version

1

### GitHub Pages Version

1

### Expected Behavior

Found CRITICAL Vulnerability in your website!

### Current Behavior

Hello I am Chirag Prajapati a Certified Penetration Tester and Ethical Hacker my License no is: 10188-161-078-1726.

We would like to inform you that, a security vulnerability affecting your website.

Affected Website: http://sp4ce.net

Following the ISO/IEC 29147 (“Information technology — Security techniques — Vulnerability disclosure”) guidelines, we verified the vulnerability's existence prior to notifying you. Please connect with us for technical details of the vulnerability, 
The researcher may also help remediate the vulnerability if you need any assistance.

For more information I request you to kindly revert me back so that I can share with you the report !
Looking forward to hearing from you !

**Comment by mattr-** [comment]
We don't have anything to do with `http://sp4ce.net`, please find the maintainers of that site first.
