### ISSUE TITLE
[Docs]: The Jekyll Docs site is broken and always displays "Deployment" as the page heading.

### ISSUE THREAD

**Issue by michaelnordmeyer** [jekyll/jekyll#9527]
[Quickstart](https://jekyllrb.com/docs/) displays the content of its page, but has "Deployment" as headline.

[Installation](https://jekyllrb.com/docs/installation/) displays the content of its page, but has "Deployment" as headline.

The same goes for all other pages in section docs, except the step-by-step tutorial.

In the [step-by-step tutorial](https://jekyllrb.com/docs/step-by-step/01-setup/) "Deployment" becomes the second headline.

And the last menu item in the right docs sidebar called "Deployment" has broken styling.

**Comment by heironimus** [comment]
PR #9338 introduced this bug. Reverting the PR fixes it.

**Comment by velle** [comment]
I think I found the problem. In docs_contents_mobile.html, `page` should be replaced with `current_page`.

The typo is only in the mobile version of the docs contents html, but the problem affects both mobile and regular output. 

I don't like that its called `current_page` btw. To me it implies that its the page currently shown/active, which is what `page` holds. IMHO `p`, `pg` or `menu_item_page`  would be better.

**Comment by heironimus** [comment]
> I think I found the problem. In docs_contents_mobile.html, `page` should be replaced with `current_page`.

@velle Yep, that works for me.

**Comment by mattr-** [comment]
Fixed by #9548
