### ISSUE TITLE
[Docs]: Search on the Jekyll Docs site is broken

### ISSUE THREAD

**Issue by michaelnordmeyer** [jekyll/jekyll#9528]
Submitting a search does not work. The Chrome developer tools console prints:

> `Error with Permissions-Policy header: Parse of permissions policy failed because of errors reported by structured header parser.`

> `docs/:414 Uncaught ReferenceError: docsearch is not defined`
> `   at docs/:414:10`

Reloading with disabled cache doesn't make a difference.

**Comment by MatheusRich** [comment]
It was working a few days ago. I see that the CDN link still works. 🤔

**Comment by mattr-** [comment]
I'll merge the PR to fix this either later today or early tomorrow.
