### ISSUE TITLE
[Bug]: Starting with Ruby 3.4.0, csv will no longer be part of stdlib

### ISSUE THREAD

**Issue by hkockerbeck** [jekyll/jekyll#9534]
### Operating System

Ubuntu 22.04

### Ruby Version

ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]

### Jekyll Version

jekyll 4.3.3

### Expected Behavior

I expected `bundle exec jekyll serve --livereload` to run without deprecation notice(s).

### Current Behavior

Since I switched from Ruby 3.2.x to 3.3.0, `bundle exec jekyll serve --livereload` shows several deprecation notices, among them

> warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of jekyll-4.3.3 to add csv into its gemspec.

**Comment by mattr-** [comment]
Already handled by #9522
