### ISSUE TITLE
[Docs]: Remove my entry from the Wiki Sites

### ISSUE THREAD

**Issue by juliaaano** [jekyll/jekyll#9541]
Please remove my name and webiste from https://github.com/jekyll/jekyll/wiki/Sites.

It is the one with the entries "Juliano..." "A blog about software engineering."

This is the revision where it was added: https://github.com/jekyll/jekyll/wiki/Sites/082835ed4cbe83004565f8f58b3658974651993e

Thank you.

**Comment by mattr-** [comment]
The wiki is user editable and you should be able to remove it yourself.

**Comment by juliaaano** [comment]
It is not editable anymore. Please assist.

**Comment by juliaaano** [comment]
The wiki page says "This page has been replaced...", what may indicate as to why it's not editable anymore. In any case, I cannot edit the page.

**Comment by mattr-** [comment]
Very strange. I've removed your entry from the Sites page. Sorry for the trouble!
