### ISSUE TITLE
No me funciona disqus en mi página

### ISSUE THREAD

**Issue by stsacademys** [jekyll/jekyll#9547]
He tratado de encontrar y solucionar el problema pero no encuentro el id de mi página (creo que el problema viene de allí). De esta parte de código que he puesto en _layouts/post.html:
 {% if page.comments %}
    <div id="disqus_thread"></div>
    <script>
      /**
      *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
      *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
      
      var disqus_config = function () {
        this.page.url = 'https://stsacademys.github.io';  
        this.page.identifier = '/https://stsacademys.github.io';
      };
      (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://https-stsacademys-github-io.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  {% endif %}

ALGUIEN ME PODRÍA AYUDAR?

**Comment by mattr-** [comment]
GitHub Issues are not an appropriate forum to ask for help with Jekyll. Please ask your question on our Discourse forum at https://talk.jekyllrb.com
