### ISSUE TITLE
[Bug]: Unable to build website

### ISSUE THREAD

**Issue by Shanthika** [jekyll/jekyll#9557]
### Operating System

Linux mint

### Ruby Version

ruby 2.7.0p0 

### Jekyll Version

jekyll 4.3.1

### Expected Behavior

The website is working when launched locally.

### Current Behavior

Getting the following error with git push:
Run yes | bin/deploy --verbose  --src master --deploy gh-pages
+ shift
+ [[ [4](https://github.com/Shanthika/shanthika.github.io/actions/runs/8073741399/job/22057918552#step:7:5) > 0 ]]
Deploying...
+ key=--src
+ case $key in
+ SRC_BRANCH=master
+ shift
+ shift
+ [[ 2 > 0 ]]
+ key=--deploy
+ case $key in
+ DEPLOY_BRANCH=gh-pages
+ shift
+ shift
+ [[ 0 > 0 ]]
+ set -e
+ echo Deploying...
+ echo 'Source branch: master'
+ echo 'Deploy branch: gh-pages'
+ read -r -p 'Do you want to proceed? [y/N] ' response
+ [[ ! y =~ ^([yY][eE][sS]|[yY])+$ ]]
+ git diff-index --quiet HEAD --
Source branch: master
Deploy branch: gh-pages
++ git ls-files --exclude-standard --others
+ test -z ''
++ git branch
++ tail -1
++ tr ' ' '\n'
++ grep master
+ '[' master ']'
+ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
++ git branch
++ grep gh-pages
+ '[' ']'
+ git checkout -b gh-pages
Switched to a new branch 'gh-pages'
+ bundle exec jekyll build
bundler: failed to load command: jekyll (/home/runner/work/shanthika.github.io/shanthika.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll)
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.[5](https://github.com/Shanthika/shanthika.github.io/actions/runs/8073741399/job/22057918552#step:7:6).[6](https://github.com/Shanthika/shanthika.github.io/actions/runs/8073741399/job/22057918552#step:7:7)/lib/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated uri 0.10.1, but your Gemfile requires uri 0.13.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:25:in `block in setup'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/spec_set.rb:191:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/spec_set.rb:191:in `each'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:24:in `map'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:24:in `setup'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler.rb:162:in `setup'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/setup.rb:26:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/ui/shell.rb:159:in `with_level'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/ui/shell.rb:111:in `silence'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/setup.rb:26:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:56:in `require_relative'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:56:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:12[7](https://github.com/Shanthika/shanthika.github.io/actions/runs/8073741399/job/22057918552#step:7:8):in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:5[8](https://github.com/Shanthika/shanthika.github.io/actions/runs/8073741399/job/22057918552#step:7:9)4:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:[11](https://github.com/Shanthika/shanthika.github.io/actions/runs/8073741399/job/22057918552#step:7:12)7:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.5.6/exe/bundle:[20](https://github.com/Shanthika/shanthika.github.io/actions/runs/8073741399/job/22057918552#step:7:21):in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:[23](https://github.com/Shanthika/shanthika.github.io/actions/runs/8073741399/job/22057918552#step:7:24):in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x[64](https://github.com/Shanthika/shanthika.github.io/actions/runs/8073741399/job/22057918552#step:7:65)/bin/bundle:23:in `<main>'
yes: standard output: Broken pipe
Error: Process completed with exit code 1.

**Comment by mattr-** [comment]
It looks like `You have already activated uri 0.10.1, but your Gemfile requires uri 0.13.0. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem.` is the error here. Unfortunately, since this doesn't appear to be an issue in Jekyll itself, there's not much I can do here. You might be able to get more help from the community at [Jekyll Talk](https://talk.jekyllrb.com/)
