### ISSUE TITLE
[Bug]: `permalink_ext': undefined method `end_with?' for {}:Hash

### ISSUE THREAD

**Issue by marek22k** [jekyll/jekyll#9558]
### Operating System

Arch Linux

### Ruby Version

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

### Jekyll Version

jekyll 4.3.3

### Expected Behavior

Builds the website

### Current Behavior

Does not build the website

### Relevant log output

```shell
$ jekyll build --trace
Configuration file: /home/marek/git/dn42-wiki/_config.yml
            Source: /home/marek/git/dn42-wiki
       Destination: /home/marek/git/dn42-wiki/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:239:in `permalink_ext': undefined method `end_with?' for {}:Hash (NoMethodError)

      if document_permalink && !document_permalink.end_with?("/")
                                                  ^^^^^^^^^^
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:46:in `output_ext'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/convertible.rb:89:in `output_ext'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/page.rb:170:in `html?'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/page.rb:80:in `template'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/page.rb:94:in `url'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:65:in `block in file_exists?'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:65:in `any?'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:65:in `file_exists?'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-sitemap-1.4.0/lib/jekyll/jekyll-sitemap.rb:13:in `generate'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/site.rb:193:in `block in generate'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/site.rb:191:in `each'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/site.rb:191:in `generate'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/site.rb:79:in `process'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
	from /home/marek/.rvm/gems/ruby-3.2.2/bin/jekyll:25:in `load'
	from /home/marek/.rvm/gems/ruby-3.2.2/bin/jekyll:25:in `<main>'
	from /home/marek/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `eval'
	from /home/marek/.rvm/gems/ruby-3.2.2/bin/ruby_executable_hooks:22:in `<main>'
```

### Code Sample

_config.yml:
```
plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      permalink: {{ "/:path/:name" }}

title: dn42 wiki

keywords: dn42,wiki,routing,bgp

lang: "en"
```

# Problem

Hello,

I have a number of Markdown files and have given them all a title using `jekyll-titles-from-headings` and `jekyll-optional-front-matter`. These Markdown files are in the `wiki/` directory. With `permalink: "/:path/:name"` will now create a URL like `website/wiki/page`. However, I do not want to have `wiki` in the URL. So I have something like `permalink: {{ "/:path/:name" | replace: "wiki/", "" }}` but got this error.

**Comment by mattr-** [comment]
Is the site you're building public? If so, can you provide a link to the source code?

**Comment by marek22k** [comment]
Hello, I have the ZIP file with the problem [here](https://github.com/jekyll/jekyll/files/15419992/problem.zip).

The website is [public](https://codeberg.org/mark22k/dn42-wiki), but I have used the ["trick"](https://codeberg.org/mark22k/dn42-wiki/src/commit/b6ec07b29ec104f62a9b75c70adbf9545b9b4fce/.woodpecker/generate.yaml#L10) of copying all files from the `wiki/` directory into the root directory. The actual Markdown files are from [https://git.dn42.dev/wiki/wiki](https://git.dn42.dev/wiki/wiki), which is only accessible with a login due to protection against bots. Hence the ZIP file with the problem.

**Comment by ashmaroli** [comment]
The problem is with `permalink: {{ "/:path/:name" | replace: "wiki/", "" }}`.
Jekyll doesn't support Liquid constructs in front matter.

**Comment by marek22k** [comment]
Perhaps the error message could be improved? Perhaps this could be explicitly mentioned in the documentation?

Is there another way to dynamically change the front matter?

**Comment by ashmaroli** [comment]
> Perhaps the error message could be improved?

I agree. But this particular scenario wasn't accounted for so far. Jekyll expected `permalink` to be be a String. But the Liquid construct got parsed by YAML engine into Ruby Hash.

> Perhaps this could be explicitly mentioned in the documentation?

Our docs are open-source as well. Pull request welcome :wink:


> Is there another way to dynamically change the front matter?

I'm sure there are third-party plugins that adds this functionality to Jekyll. It was never added to core to preserve backwards-compatibility for those users that use front matter variable to store Liquid templates.
