### ISSUE TITLE
[Bug]: error running "bundle exec jekyll s"

### ISSUE THREAD

**Issue by mahidsec** [jekyll/jekyll#9559]
### Operating System

kali 2024.1

### Ruby Version

ruby 3.1.2p20

### Jekyll Version

jekyll 4.3.3

### Expected Behavior

I expected to start a server locally with the command ```bundle exec jekyll s```

### Current Behavior

giving an error like 

> Configuration file: /home/mahidsec/Desktop/mahid/mahidsec.github.io/_config.yml
>             Source: /home/mahidsec/Desktop/mahid/mahidsec.github.io
>        Destination: /home/mahidsec/Desktop/mahid/mahidsec.github.io/_site
>  Incremental build: disabled. Enable with --incremental
>       Generating... 
> /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/connection.rb:54: warning: /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/ext/sass/dart-sass/src/dart: error while loading shared libraries: /lib/x86_64-linux-gnu/libc.so: invalid ELF header
>   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':                                                                 
>                     Broken pipe
>                     ------------------------------------------------
>       Jekyll 4.3.3   Please append `--trace` to the `serve` command 
>                      for any additional information or backtrace. 
>                     ------------------------------------------------
> /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/connection.rb:85:in `write': Broken pipe (Errno::EPIPE)
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/connection.rb:85:in `block in write'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/connection.rb:84:in `synchronize'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/connection.rb:84:in `write'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/dispatcher.rb:91:in `send_proto'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/channel.rb:59:in `send_proto'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/host.rb:212:in `send_message'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/host.rb:43:in `block in compile_request'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/host.rb:176:in `block in await'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/host.rb:191:in `listen'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/host.rb:175:in `await'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler/host.rb:36:in `compile_request'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/compiler.rb:156:in `compile_string'
>         from /var/lib/gems/3.1.0/gems/sass-embedded-1.71.1-x86_64-linux/lib/sass/embedded.rb:37:in `compile_string'
>         from /var/lib/gems/3.1.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:160:in `convert'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:105:in `block in convert'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `each'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `reduce'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `convert'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:84:in `render_document'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:63:in `run'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:572:in `render_regenerated'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:564:in `block in render_pages'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `each'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `render_pages'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:211:in `render'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:80:in `process'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
>         from /var/lib/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
>         from /var/lib/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
>         from /var/lib/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
>         from /var/lib/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
>         from /var/lib/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
>         from /var/lib/gems/3.1.0/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
>         from /usr/local/bin/jekyll:25:in `load'
>         from /usr/local/bin/jekyll:25:in `<top (required)>'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
>         from /var/lib/gems/3.1.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
>         from /usr/local/bin/bundle:25:in `load'
>         from /usr/local/bin/bundle:25:in `<main>'

### Code Sample

cloned https://github.com/cotes2020/chirpy-starter.git
tried to execute bundle - worked fine
execute 'bundle exec jekyll s' - got the error message

**Comment by rxsh** [comment]
You find a solution?

**Comment by mahidsec** [comment]
> You find a solution? I have the same error. I need help

I've changed the OS on Windows it is working fine. I think some permission-related things are blocking the execution

**Comment by n00br00t** [comment]
Someone managed to solve? This problem only happens on Linux, it has been working fine on Windows. I downloaded a new repository from the blog and tested, it also doesn't work. I've updated the gems, installed specific versions of Jekyll, followed the official instructions.

**Comment by mahidsec** [comment]
> Someone managed to solve? This problem only happens on Linux, it has been working fine on Windows. I downloaded a new repository from the blog and tested, it also doesn't work. I've updated the gems, installed specific versions of Jekyll, followed the official instructions.

I've been tried many things but it seems nothing is working! Searching for the sollution

**Comment by harmanhobbit** [comment]
I had the same problem in NixOS. In the end I had to modify the serve command to `steam-run bundle exec jekyll serve`. From what I found its to do with where Nix stores the binaries and Ruby not being able to find them but I don't know if it applies to the OS you are running.

**Comment by mahidsec** [comment]
### **If you are here means You also faced this issue**
I was trying to run chirpy theme on github and Here is a solution that worked for me in kali version 2024.3
Upgrade gem manually from "https://rubygems.org/pages/download"

Steps:

1. bundle update ffi
    If shows error then gem install ffi

And yes you're all done

**Comment by troccoli** [comment]
That didn't work for me.

I can build and serve the site just fine locally, on my Mac. But it returns the error if I'm using Docker to build the site

```
export JEKYLL_VERSION=4.2.2
docker run --rm -it \
  --volume="$PWD:/srv/jekyll" \
  -p 4000:4000 \
  --platform linux/amd64 \
  jekyll/jekyll:$JEKYLL_VERSION \
  jekyll serve --trace --watch --force_polling --drafts --future --unpublished --incremental
```

I shouldn't think it mattered that I am on Mac, but maybe it does.

The error message in essentially the same, apart from a difference in the version of the `sass-embedde` gem

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':
                  Broken pipe
/usr/gem/gems/sass-embedded-1.82.0/lib/sass/compiler/connection.rb:82:in `write': Broken pipe (Errno::EPIPE)
        from /usr/gem/gems/sass-embedded-1.82.0/lib/sass/compiler/connection.rb:82:in `block in write'
        from /usr/gem/gems/sass-embedded-1.82.0/lib/sass/compiler/connection.rb:81:in `synchronize'
```

**Comment by ashmaroli** [comment]
@troccoli If the issue occurs only via a Docker container, I suggest checking / asking at our forum https://talk.jekyllrb.com/.

**Comment by troccoli** [comment]
Thanks @ashmaroli 

I searched the forum and althouhg I didn't find my issue, I found another issue with Docker that helped.

All I needed to do was to run `bundle update` before jekyll

```
export JEKYLL_VERSION=4.2.2
docker run --rm -it \
  --volume="$PWD:/srv/jekyll" \
  -p 4000:4000 \
  --platform linux/amd64 \
  jekyll/jekyll:$JEKYLL_VERSION \
  /bin/bash bundle update && jekyll serve --watch --force_polling --drafts --future --unpublished --incremental
```
