### ISSUE TITLE
[Bug]: Can't serve website due to sass-embedded version

### ISSUE THREAD

**Issue by davidskeck** [jekyll/jekyll#9563]
### Operating System

Ubuntu 23.10

### Ruby Version

ruby 3.1.2p20

### Jekyll Version

jekyll 4.3.3

### Expected Behavior

The site would be built and served locally when I ran ```bundle exec jekyll serve``` 

### Current Behavior

I received the error message bellow.

```bash
Could not find compatible versions

Because every version of jekyll depends on jekyll-sass-converter >= 2.0, < 4.0
  and every version of jekyll-sass-converter depends on sass-embedded ~> 1.54,
  every version of jekyll requires sass-embedded ~> 1.54.
So, because sass-embedded ~> 1.54 could not be found in locally installed gems for any resolution platforms (x86_64-linux)
  and Gemfile depends on jekyll ~> 4.3.3,
  version solving has failed.

The source contains the following gems matching 'sass-embedded (~> 1.54)':
  * sass-embedded-1.71.1-x86_64-linux-android
```

### Relevant log output

```shell
Ubuntu 23.10
gem v 3.3.15
ruby 3.1.2p20
```

### Code Sample

Followed the steps to install ruby here:
https://jekyllrb.com/docs/installation/ubuntu/

Install Jekyll by following the guide online for Ubuntu.

1. `gem install bundler jekyll`
2. `jekyll new my-awesome-site`
3. `cd my-awesome-site`
4. `bundle exec jekyll serve`

**Comment by davidskeck** [comment]
This was partially solved by running `gem install sass-embedded -v 1.54.0`, though I'm not sure this is the correct solution.

**Comment by ntkme** [comment]
This is a well-known issue with old version rubygems. You need both rubygems >=3.3.22 and bundler >=2.3.22 to install latest version of sass-embedded.

After you upgrade, also make sure you delete `Gemfile.lock`, and then try again.

**Comment by davidskeck** [comment]
How do I upgrade my bundler install? I am not a ruby developer so I'm not used to how this all works. Thanks!

**Comment by ntkme** [comment]
``` sh
gem update --system
```

Alternatively you can upgrade to ruby 3.2 or higher, which comes with new enough version of both rubygems and bundler.

**Comment by davidskeck** [comment]
Interesting. Thanks!! This fixed it.
