### ISSUE TITLE
[Bug]: pipe character to single row table priority unexpectedly high

### ISSUE THREAD

**Issue by feeshy** [jekyll/jekyll#9575]
### Operating System

github deploy

### Ruby Version

2.7.4

### Jekyll Version

Jekyll 3.9.5

### GitHub Pages Version

Latest

### Expected Behavior

when I wrote this markdown code

```
- [ADOX | Rodinal / Adonal](https://web.archive.org/web/20151213024654/http://www.adox.de/Photo/adox-film-developer/rodinal-adonal)
```

it was expected to be rendered as a bullet list

- [ADOX | Rodinal / Adonal](https://web.archive.org/web/20151213024654/http://www.adox.de/Photo/adox-film-developer/rodinal-adonal)

### Current Behavior

it was rendered as a "single row table on a bullet list"

![image](https://github.com/jekyll/jekyll/assets/10860212/98b1583a-6d30-46f3-b036-991fdf171591)

bullet list will only be rendered correctly with an escape character

```
- [ADOX \| Rodinal / Adonal](https://web.archive.org/web/20151213024654/http://www.adox.de/Photo/adox-film-developer/rodinal-adonal)
```

**Comment by ashmaroli** [comment]
This is the expected behavior.
