### ISSUE TITLE
feat: XMPP: Post to PubSub

### ISSUE THREAD

**Issue by sjehuda** [jekyll/jekyll#9583]
## Summary

Publishing posts to PubSub, either a dedicated PubSub service (e.g. `pubsub.ekyllrb.com`) or to a personal account (e.g. `george@ekyllrb.com`).

## Motivation

> Why do you want to see this feature in Jekyll?

1. More exposure, (1) be it to people communicating on my XMPP server and then check the dedicated PubSub service, or (2) be it by people communicating with other people and then they check their PubSub nodes of each other.

> What makes you sure that it should not be implemented at the plugin level, but in Jekyll core?

Because this would allow people that do ot have a website nor server that are open for incomming connections - for whatever reason - to publish contents using their own XMPP account alone. No server of their own would be needed to publish whatever they want.

> What use cases does it support?

1. Website administrators (obviously)
2. Real users! (New audience: Any one)

> NOTE: Please be mindful of the Jekyll philosophy (https://jekyllrb.com/philosophy/), particularly Section 5. Think about if 90% of the users would benefit from your feature request, and whether your feature would be better off in a plugin.

With clause 2 in mind, over 110% of the users would benefit from this feature request!

## Guide-level explanation

In XMPP, using PubSub(1) (XEP-0060), it is possible to store posts as Atom Syndication(2) entries into XMPP(3).

There are several XMPP extensions that apply it, namely XEP-0227 (4) and XEP-0472 (5) which make node `urn:xmpp:microblog:0` as a common choice to manage news for client accounts (e.g. `blog@jekyllrb.com`), yet a component account (e.g. `pubsub.jekyllrb.com`) may use all of its nodes for this purpose.

A Ruby library that might be utilized would be XMPP4R.

I have made a script that realizes viewing PubSub node items as Atom XML feeds over HTTP.

[XEP-0060: Publish-Subscribe](https://xmpp.org/extensions/xep-0060.html)
[RFC 4287: The Atom Syndication Format](https://www.rfc-editor.org/rfc/rfc4287)
[Atom Over XMPP](https://datatracker.ietf.org/meeting/66/materials/slides-66-atompub-1.pdf)
[XEP-0277: Microblogging over XMPP](https://xmpp.org/extensions/xep-0277.html)
[XEP-0472: Pubsub Social Feed](https://xmpp.org/extensions/xep-0472.html)
[XMPP4R](http://xmpp4r.github.io/)
[PubSub Over HTTP](https://codeberg.org/poezio/slixmpp/issues/3526)

## Reference-level explanation

Publish items to XMPP PubSub nodes as Atom format. See the references to Movim and to PubSub Over HTTP above.

```
pubsub.jekyllrb.com/
|
|-- updates/
    |-- Sombre
     `-- Varied
|-- releases/
 `-- events/
pubsub service/
|
|-- node/
    |-- item
     `-- item
|-- node/
 `-- node/
```

## Drawbacks

None.

## Unresolved Questions

None

**Comment by mattr-** [comment]
I don't believe this fits in to Jekyll's core functionality. It should be done as a plugin. If someone wants to do this with a plugin, I'm happy to help support that effort.

**Comment by sjehuda** [comment]
I would be delighted to work with you in writing an XMPP PubSub plugin.
