### ISSUE TITLE
[Bug]: jekyll changes filenames when copying files to _site on build

### ISSUE THREAD

**Issue by rriemann** [jekyll/jekyll#9585]
### Operating System

Opensuse Tumbleweed

### Ruby Version

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

### Jekyll Version

jekyll 4.3.3

### Expected Behavior

I expect Jekyll to copy my asset files:

~~~
.well-known
├── webfinger
└── webfinger.d
    └── http%3A%2F%2Fopenid.net%2Fspecs%2Fconnect%2F1.0%2Fissuer
        └── acct%3Arobert%riemann.cc.json

~~~

My motivation is here to catch requests to `/.well-known/webfinger?rel=http://openid.net/specs/connect/1.0/issuer&resource=acct:my@mail.com` and use a CDN redirect to `/.well-known/webfinger.d/:rel/:resource.json` to hardcode the response.

### Current Behavior

After a `bundle exec jekyll build`, I get:

~~~
.well-known
├── oidc.webfinger
├── webfinger
└── webfinger.d
    └── http:
        └── openid.net
            └── specs
                └── connect
                    └── 1.0
                        └── issuer
                            └── acct:robert%riemann.cc.json
~~~

### Code Sample

Just create an empty Jekyll project and do:

~~~sh
mkdir -p webfinger.d/http%3A%2F%2Fopenid.net%2Fspecs%2Fconnect%2F1.0%2Fissuer/
touch webfinger.d/http%3A%2F%2Fopenid.net%2Fspecs%2Fconnect%2F1.0%2Fissuer/acct%3Arobert%riemann.cc.json
~~~

Then build to _site.

**Comment by mattr-** [comment]
This isn't something we support or that you should use Jekyll for. You'll need to configure the webserver that you're using to serve your static site to support this somehow, if that's even possible. This is not a bug.
