### ISSUE TITLE
[Bug]: exclude broken for md files

### ISSUE THREAD

**Issue by axelfontaine** [jekyll/jekyll#9592]
### Operating System

Ubuntu 24.04

### Ruby Version

ruby 3.2.3 (2024-01-18) [x86_64-linux-gnu]

### Jekyll Version

jekyll 4.3.3

### Expected Behavior

In `_config.yml`

```
exclude:
  - README.md
```

prevents `README.md` from being included in `_site`

### Current Behavior

`README.md` is copied to `_site`

**Comment by mkasberg** [comment]
I cannot reproduce this.

```
$ jekyll --version
jekyll 4.3.3

$ jekyll new test-exclude-md
Running bundle install in /home/mkasberg/code/test-exclude-md... 
New jekyll site installed in /home/mkasberg/code/test-exclude-md. 

$ cd test-exclude-md 

$ echo "testing" > README.md

$ bundle exec jekyll build
Configuration file: /home/mkasberg/code/test-exclude-md/_config.yml
            Source: /home/mkasberg/code/test-exclude-md
       Destination: /home/mkasberg/code/test-exclude-md/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 0.374 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

$ ls _site # NOTE README.md gets created because it's not yet excluded.
404.html  about  assets  feed.xml  index.html  jekyll  README.md

$ echo "exclude:
dquote>   - README.md" > _config.yml 

$ tail -n4 _config.yml 
exclude:
  - README.md

$ bundle exec jekyll build
Configuration file: /home/mkasberg/code/test-exclude-md/_config.yml
            Source: /home/mkasberg/code/test-exclude-md
       Destination: /home/mkasberg/code/test-exclude-md/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
     Build Warning: Layout 'post' requested in _posts/2024-05-23-welcome-to-jekyll.markdown does not exist.
     Build Warning: Layout 'default' requested in 404.html does not exist.
     Build Warning: Layout 'page' requested in about.markdown does not exist.
     Build Warning: Layout 'home' requested in index.markdown does not exist.
                    done in 0.327 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

$ ls _site # NOTE exclude works correctly and removes README.md.
404.html  about  feed.xml  index.html  jekyll
```

Since I don't believe this is a bug with Jekyll, here are some other things you might check:
 - Run `jekyll clean`, or otherwise delete `README.md` from `_site` and see whether it gets re-created.
 - Ensure your `_config.yml` is valid yaml and your `exclude:` section is formatted correctly.
 - Ensure there are no other errors that prevent your jekyll build from running.

**Comment by jbleuzen** [comment]
Another thing that you can check : 
- You have the keyword `exclude` only once in your `_config.yml`.

I watched the issue because I thought I had the issue but with @mkasberg test I don't reproduce. After checking my conf I had the keyword `exclude` twice...

**Comment by mattr-** [comment]
@axelfontaine Please feel free to reopen after checking the above comments to confirm you don't have a double `exclude` key in your config. If you do reopen this, you **must** provide a reproduction test case since we can't confirm your issue. Thanks!
