### ISSUE TITLE
SCSS class not found when i call to the function

### ISSUE THREAD

**Issue by neerajs0532** [jekyll/jekyll#9596]
### Operating System

MAC 2 MACOS 14.4.1 (23E224)

### Ruby Version

no

### Jekyll Version

no

### GitHub Pages Version

nothing

### Expected Behavior

i expected to scuccesfully work this library and we want able to use my plugin

### Current Behavior

SCSS class not found.
Fatal error: Uncaught Error: Call to undefined function compile_scss_to_css() in /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-content/plugins/custom-scss-compiler/custom-scss-compiler.php:51 Stack trace: #0 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-settings.php(473): include_once() https://github.com/scssphp/scssphp/issues/1 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-config.php(103): require_once('/Users/a1d8sihz...') https://github.com/scssphp/scssphp/issues/2 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-load.php(50): require_once('/Users/a1d8sihz...') https://github.com/scssphp/scssphp/issues/3 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-blog-header.php(13): require_once('/Users/a1d8sihz...') https://github.com/scssphp/scssphp/issues/4 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/index.php(17): require('/Users/a1d8sihz...') https://github.com/scssphp/scssphp/issues/5 {main} thrown in /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-content/plugins/custom-scss-compiler/custom-scss-compiler.php on line 51
There has been a critical error on this website.

[Learn more about troubleshooting WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)

### Relevant log output

```shell
SCSS class not found.
Fatal error: Uncaught Error: Call to undefined function compile_scss_to_css() in /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-content/plugins/custom-scss-compiler/custom-scss-compiler.php:51 Stack trace: #0 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-settings.php(473): include_once() #1 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-config.php(103): require_once('/Users/a1d8sihz...') #2 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-load.php(50): require_once('/Users/a1d8sihz...') #3 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-blog-header.php(13): require_once('/Users/a1d8sihz...') #4 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/index.php(17): require('/Users/a1d8sihz...') #5 {main} thrown in /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-content/plugins/custom-scss-compiler/custom-scss-compiler.php on line 51
There has been a critical error on this website.

Learn more about troubleshooting WordPress.
```

### Code Sample

<?php
/*
Plugin Name: SCSS to CSS Compiler
Description: Compiles SCSS to CSS in WordPress and enqueues the generated CSS file.
Version: 1.0
Author: Neeraj Singh
*/
// Include Composer autoloader
require_once 'scssphp/scss.inc.php';

use ScssPhp\ScssPhp\Compiler;

// Function to compile SCSS to CSS
function compile_scss_to_css()
{
    // Input SCSS file path
    $scss_file_path = get_template_directory() . '/assets/b2b/css/b2b.scss';

    // Output CSS file path
    $css_file_path = get_template_directory() . '/assets/b2b/css/b2b.css';

    // Create SCSS compiler instance
    $scss = new Compiler();
    $scss->setImportPaths(dirname($scss_file_path));

    // Compile SCSS to CSS
    $css = $scss->compile('@import "' . basename($scss_file_path) . '";');

    // Write compiled CSS to file
    file_put_contents($css_file_path, $css);

    // Enqueue the generated CSS file
    wp_enqueue_style('custom-style', get_template_directory_uri() . '/assets/b2b/css/b2b.css', array(), '1.0', 'all');
}

// Call the function when WordPress initializes
function scss_to_css_plugin_init()
{
    compile_scss_to_css();
}
add_action('init', 'scss_to_css_plugin_init');

**Comment by mattr-** [comment]
You don't appear to be using Jekyll. We can't assist you with what looks like a WordPress related issue.
