### ISSUE TITLE
feat: Ability to Remove Trailing Slash from Paginated Pages

### ISSUE THREAD

**Issue by niclake** [jekyll/jekyll#9608]
## Summary

- I am moving my blog from my site index to `/blog/index.html`, using the .html file to be able to utilize pagination.
- This is hosted on GitHub Pages, so I am using the default pagination plugin vs. the v2
- My site by default uses a permalink of `/:title`, i.e. no trailing slashes on any page (ex: `/about` or `/hello`, or `/post-url` for blog posts)
- However, now that I've done this, to get to my blog, you must navigate to `/blog/`. All pagination is `/blog/page2/`. As far as I can tell, there's no way to remove this trailing slash

## Motivation

This is less "omg it's breaking everything" than it is "huh, *that's* inconsistent". People can still navigate to `/blog` and arrive at `/blog/`. It just looks different to anyone peeking at it.

**Comment by ashmaroli** [comment]
Sorry @niclake, this repository doesn't handle pagination related issue tickets.
