### ISSUE TITLE
Release Jekyll 3.10.0 for Ruby 3.4

### ISSUE THREAD

**Issue by parkr** [jekyll/jekyll#9617]
## Summary

Ruby 3 is starting to drop built-in RubyGems, like `csv` and `webrick`. Jekyll relies on these, so let's release a Jekyll 3 minor version  that includes them.

Use `3.10-stable` branch instead of `master` when filing PRs.

## Tasks

- [x] Add csv: https://github.com/jekyll/jekyll/pull/9616 (dropping [as of Ruby 3.4](https://github.com/ruby/ruby/blob/v3_3_0/NEWS.md#stdlib-updates))
- [x] Add webrick: https://github.com/jekyll/jekyll/pull/9620 (dropped in [Ruby 3.0](https://github.com/ruby/ruby/blob/v3_0_0/NEWS.md#stdlib-compatibility-issues))

**Comment by chmaynard** [comment]
@parkr Someone in a leadership position still cares enough about Jekyll to actually open a new issue. Thank you.

**Comment by parkr** [comment]
Work is now done. Now in GitHub's court to upgrade Pages: https://github.com/github/pages-gem/pull/917.
