### ISSUE TITLE
[Bug]: _site folder generates pages incorrectly

### ISSUE THREAD

**Issue by ElijahB09** [jekyll/jekyll#9626]
### Operating System

macOS Sonoma 14.5

### Ruby Version

ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]

### Jekyll Version

jekyll 4.3.3

### GitHub Pages Version

Latest

### Expected Behavior

I would expect each page that I create to be properly copied in the _site folder.

### Current Behavior

Some pages are properly copied into the _site folder however 5 pages are not. Specifically, what seems to be happening is that the following information for a page is copied over correctly.

---
layout: redacted
title: redacted
description: redacted
permalink: /redacted/
page_css: css/redacted.css
group: "navigation"
navigation_order: 5
pagination:
    enabled: true
---

However the html written below this section is not being copied over correctly and is instead being replaced by the html found in the root index.html file. I am able to temporarily solve the problem by deleting and recreating the file, however deployments are still affected by this problem and deleting and recreating deployed files is annoying and also should not be an accepted solution for this problem.

### Relevant log output

```shell
There is none, logs do not catch this as a bug.
```

### Code Sample

In terms of reproduction, this bug happened after an upgrade from jekyll 3.9.5 to jekyll 4.3.3. The official upgrade guide on the Jekyll site was followed, so either the guide is out of date in terms of a breaking change, or there were some instructions that were not written in the guide. This is all that I have for reproduction.

**Comment by ashmaroli** [comment]
A lot of stuff had changed between v3.x and v4.x. We won't be able to pinpoint to the actual cause(s) if we don't have a minimal sample to reproduce the issue.

Perhaps if you could replace the redacted values with dummy values and put those 5 pages (with different dummy texts) in a sample repository, we could clone the repo locally and investigate..

**Comment by ElijahB09** [comment]
I can try, but in the meantime I would like to hear how the copying logic works from the src/ folder to the _site/ folder

**Comment by ElijahB09** [comment]
Alright, here is a really stripped down version of some pages
https://github.com/ElijahB09/Dummy_Jekyll_Site

**Comment by ElijahB09** [comment]
Alright, good news, after. taking a close look I may have found a solution. It seems that in the header section the part with ```
paginator:
    enabled: true
```
is causing the problems. What has this feature been replaced by as I believe I stil need it for my blog to work?

**Comment by ElijahB09** [comment]
Largely fixed this on my own, turned out to be a dependency misconfiguration with jekyll-pagination-v2. Thank you for the help regardless. If anyone else comes upon the same issue that I've had, here is the relevant discussion that helped me https://github.com/sverrirs/jekyll-paginate-v2/issues/222
