### ISSUE TITLE
[Bug]: CI Appveyor 2.7 builds fail

### ISSUE THREAD

**Issue by olleolleolle** [jekyll/jekyll#9636]
### Operating System

Windows

### Ruby Version

Environment: RUBY_FOLDER_VER=27, TZINFO_VERSION=~> 1.2, TEST_SUITE=test

### Jekyll Version

jekyll 4.3.3

### GitHub Pages Version

Latest

### Expected Behavior

I expected a green build, perhaps only using non-EOL'd Ruby versions.

### Current Behavior

https://ci.appveyor.com/project/jekyll/jekyll/builds/50207910 uses a too-new Bundler (2.5.13) for it work.

### Relevant log output

```shell
bundle install --retry 5 --jobs=%NUMBER_OF_PROCESSORS%
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:35: warning: already initialized constant Bundler::CompactIndexClient::SUPPORTED_DIGESTS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:35: warning: previous definition of SUPPORTED_DIGESTS was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:36: warning: already initialized constant Bundler::CompactIndexClient::DEBUG_MUTEX
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:36: warning: previous definition of DEBUG_MUTEX was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:39: warning: already initialized constant Bundler::CompactIndexClient::INFO_NAME
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:39: warning: previous definition of INFO_NAME was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:40: warning: already initialized constant Bundler::CompactIndexClient::INFO_VERSION
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:40: warning: previous definition of INFO_VERSION was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:41: warning: already initialized constant Bundler::CompactIndexClient::INFO_PLATFORM
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:41: warning: previous definition of INFO_PLATFORM was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:42: warning: already initialized constant Bundler::CompactIndexClient::INFO_DEPS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:42: warning: previous definition of INFO_DEPS was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:43: warning: already initialized constant Bundler::CompactIndexClient::INFO_REQS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:43: warning: previous definition of INFO_REQS was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:35: warning: already initialized constant Bundler::CompactIndexClient::SUPPORTED_DIGESTS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:35: warning: previous definition of SUPPORTED_DIGESTS was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:36: warning: already initialized constant Bundler::CompactIndexClient::DEBUG_MUTEX
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:36: warning: previous definition of DEBUG_MUTEX was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:39: warning: already initialized constant Bundler::CompactIndexClient::INFO_NAME
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:39: warning: previous definition of INFO_NAME was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:40: warning: already initialized constant Bundler::CompactIndexClient::INFO_VERSION
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:40: warning: previous definition of INFO_VERSION was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:41: warning: already initialized constant Bundler::CompactIndexClient::INFO_PLATFORM
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:41: warning: previous definition of INFO_PLATFORM was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:42: warning: already initialized constant Bundler::CompactIndexClient::INFO_DEPS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:42: warning: previous definition of INFO_DEPS was here
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:43: warning: already initialized constant Bundler::CompactIndexClient::INFO_REQS
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client.rb:43: warning: previous definition of INFO_REQS was here
--- ERROR REPORT TEMPLATE -------------------------------------------------------

SyntaxError: C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client/cache.rb:46: syntax error, unexpected '=', expecting ';' or '\n'
      def names_path = directory.join("names")
                     ^
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/bundler-2.5.13/lib/bundler/compact_index_client/cache.rb:47: syntax error, unexpected '=', expecting ';' or '\n'
```

### Code Sample

See https://ci.appveyor.com/project/jekyll/jekyll/builds/50207910

**Comment by ashmaroli** [comment]
Hi,
Since there's a successful test run with Ruby 2.7 via GitHub Actions, we could consider doing away with AppVeyor entirely and add a couple of Windows-based jobs to the existing CI workflow.

(*Subject to approval of active maintainers here*)

**Comment by MSP-Greg** [comment]
> Since there's a successful test run with Ruby 2.7 via GitHub Actions

Do you have any links for that?  I'd like to see what test commands it was running.

JFYI, locally I tried running `bundle exec rake test` with Ruby head (some Gemfile changes due to Ruby 'bundled' gems), and there were only three failures, all are 'time' related.

**Comment by ashmaroli** [comment]
Hello @MSP-Greg,

When I posted about a successful test run on GitHub Actions (GA) almost a month ago, I was referring to existing successful test runs (on Ubuntu images with Ruby 2.7) in this repo's workflows and not exactly a successful test run using a Windows image on GA.

I had recommended the move away from AppVeyor so that all CI runs of this repo could be managed from the same YAML file, using the same routines. (The current AppVeyor failures for this repo is due to having the pre-installed Bundler using Ruby 3.0 syntax even though the jobs ran on Ruby 2.7).

Regarding the failures (runs with ruby-head) you have highlighted, all of those are timezone related mismatch between (DST ??) Windows and posix and may need some fudging of test expectations.

**Comment by crispgm** [comment]
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#250-december-15-2023 bundler dropped Ruby 2.7 supports after this version, which breaks the Windows CI. Should we lock bundler version or drop 2.7 support either? @ashmaroli

**Comment by olleolleolle** [comment]
@crispgm https://github.com/ruby/setup-ruby/blob/master/action.yml#L20 setup-ruby offers a `bundler:` parameter, which can given to GHA Workflows, to "select a Bundler version".

**Comment by ashmaroli** [comment]
Ruby 2.7 reached EOL about 18 months ago (2023-03-31). But I would like to test with it for *one more minor version of Jekyll*.
The crossroad here is between either continuing with AppVeyor or move Windows based testing to GitHub Actions as well.

(While the latter seems better to me owing to having the settings, logs and statuses all at same place, I would also like @mattr- and @parkr to weigh in on this)

**Comment by parkr** [comment]
I would vote to use only GitHub Actions where possible. I believe Jekyll 4 can informally drop Ruby 2.7 support by dropping the target in the test matrix, but I would not raise the required Ruby version in the gemspec until Jekyll 5.

**Comment by olleolleolle** [comment]
So, a suggested next action is "make a PR that takes the AppVeyor steps as a "runs-on: windows-latest" + a few `includes` elements that has `os: windows-latest` in them.

**Comment by ashmaroli** [comment]
Awesome! So, its two votes in favor of migrating to GitHub Actions.
@olleolleolle I will assign myself to this task if you haven't started working on this already. This is now high on the priority list.

**Comment by MSP-Greg** [comment]
@ashmaroli

> Regarding the failures (runs with ruby-head) you have highlighted, all of those are timezone related mismatch between (DST ??) Windows and posix and may need some fudging of test expectations.

I just looked at the bash test script, and it contains the following, which explains the test failures:
```bash
# Tests only pass when timezone offset is zero.
TZ=UTC
```

Re some of the 'Bundler' discussion, I've found that updating RubyGems with older Rubies works better than just updating Bundler, and works with Rubies going back to 2.4 (I think).  `setup-ruby` also has an input for it.

Also, I generally don't like to run Windows CI in a bash shell.  There are certainly repos doing it, but it often brings a set of problems that are difficult to address.

**Comment by ashmaroli** [comment]
Thank you for sharing your insights, @MSP-Greg
