### ISSUE TITLE
[Docs]: Jekyll global variable

### ISSUE THREAD

**Issue by sgofferj** [jekyll/jekyll#9652]
## Motivation

I just spent 1.5 hours googling how to display the currently used version of jekyll until I accidentally stumbled over {{ jekyll.version }} in the header.html.

## Suggestion

Document the jekyll and possibly other usefull global variables.

**Comment by ashmaroli** [comment]
Hello @sgofferj
Thank you for bringing this to our attention.

Our docs are open-source as well. If you wish to update the docs site, I invite you to submit a pull request. The relevant files in this case are:

- [docs/_data/jekyll_variables.yml](https://github.com/jekyll/jekyll/blob/a5460320c5a37b8d883f8d8c89fa58349d893af0/docs/_data/jekyll_variables.yml)
- [lib/jekyll/drops/jekyll_drop.rb](https://github.com/jekyll/jekyll/blob/a5460320c5a37b8d883f8d8c89fa58349d893af0/lib/jekyll/drops/jekyll_drop.rb)

**Comment by sgofferj** [comment]
Unfortunately, I don't have the time to read myself into the project's conventions and I don't speak any Ruby, so I don't really understand the source code.
