### ISSUE TITLE
New Jekyll'd site

### ISSUE THREAD

**Issue by sgofferj** [jekyll/jekyll#9670]
Not sure if that's of interest for you or if you have a list or something. I just thought, I put it here.

I'm running the noncommercial website ["Suomen Sääkeskus - The Finnish Weather Center"](https://www.saakeskus.fi) for stormchasers and other people interested in weather since 2008. It started with hand-coded PHP but from 2010 on, it ran on Joomla. I recently moved the website to Jekyll, mostly for performance and security reasons. I wrote a [short blog article](https://www.saakeskus.fi/news/welcome-to-jekyll/) about it on the site. So far, my users seem to be quite happy with the move.

Thank you for your work and making such an awesome piece of software Open Source!

PS: Two months earlier, I also moved my [personal website](https://www.gofferje.net) from Drupal to Jekyll...

PPS: Feel free to close when read.

**Comment by ashmaroli** [comment]
On behalf of all contributors who made Jekyll what it is today, thank you @sgofferj for your appreciation.
