### ISSUE TITLE
[Bug]: cmd "bundle exec jekyll serve" runs over 30mins

### ISSUE THREAD

**Issue by llliijie** [jekyll/jekyll#9676]
### Operating System

macOS

### Ruby Version

ruby 3.3.5 (2024-09-03 revision ef084cc8f4)

### Jekyll Version

3.10.0

### GitHub Pages Version

232

### Expected Behavior

I expected the command `bundle exec jekyll serve` will finish in less in 1 min.

### Current Behavior

The command `bundle exec jekyll serve` is still running after more than 30 mins without producing results.

**Comment by llliijie** [comment]
additional info:

`bundle install` was run.

dependencies were resolved and are compatible with macOS system.

command `bundle exec jekyll build` was run before `bundle exec jekyll serve`, the only warning message is `/usr/local/Cellar/ruby/3.3.5/lib/ruby/3.3.0/json/common.rb:3: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.`

The command used to finish in less than 1 min on other macOS (same system but different machine)

**Comment by ashmaroli** [comment]
Hello @llliijie
Jekyll 3.x (and therefore GitHub Pages) uses the old unoptimized version of Jekyll core. You may want to consider upgrading to Jekyll 4.x and deploy using GitHub Actions.

**Comment by llliijie** [comment]
Hi thank you @ashmaroli. Seems like two different versions of Jekyll there, removed the old one and worked.
