### ISSUE TITLE
[Bug]: Deprecation Warning: `lighten()` / `darken()` is deprecated.

### ISSUE THREAD

**Issue by Tr4cck** [jekyll/jekyll#9686]
### Operating System

Archlinux 6.10.10-arch1-1

### Ruby Version

ruby 3.2.5 (2024-07-26 revision 31d0f1a2e7) [x86_64-linux]

### Jekyll Version

jekyll 4.3.4

### Expected Behavior

I expected my website to be built successfully without any warning or error  when I run `bundle exec jekyll serve`.

### Current Behavior

You can see that color statements, like `lighten()` and `darken()` in .scss files got deprecation warning. And I did `bundle update minima` but that's not work.

### Relevant log output

```shell
https://paste.rs/RQvhv.txt
```

**Comment by ashmaroli** [comment]
Hello @Tr4cck, this deprecation is a very recent development in the sass engine.
You may either downgrade to an older version of the engine in your Gemfile by adding:

```ruby
# Gemfile

gem "sass-embedded", "~> 1.78.0"
```
and then run `bundle update` to rehash your `Gemfile.lock`.

or

Silence deprecation warnings for current version and all future versions by having the following in your config file:
```yaml
# _config.yml

sass:
  quiet_deps: true
```

**Comment by pranabdas** [comment]
You may update the affected `.scss` file(s):
```diff
// on the top
+ @use "sass:color";

// replace lighten
- $grey-color-light: lighten($grey-color, 40%);
+ $grey-color-light: color.adjust($grey-color, $lightness: 40%);

// replace darken
- $grey-color-dark: darken($grey-color, 25%);
+ $grey-color-dark: color.adjust($grey-color, $lightness: -25%);
```
More info - https://sass-lang.com/d/color-functions

**Comment by ashmaroli** [comment]
Also please note that Minima-2.x cannot ship with the patch above because the `@use "sass:color"` may not work for users on older versions of Jekyll (e.g. 3.x on `github-pages`) that do not use the sass-dart library.

Whether this patch can be added to the `master` branch is yet to be decided (will be breaking for `remote_theme` users).

**Comment by Tr4cck** [comment]
Thanks a lot @ashmaroli @pranabdas :) I will close the issue.

**Comment by Venkatakrishnan-M** [comment]
> You may update the affected `.scss` file(s):
> 
> ```diff
> // on the top
> + @use "sass:color";
> 
> // replace lighten
> - $grey-color-light: lighten($grey-color, 40%);
> + $grey-color-light: color.adjust($grey-color, $lightness: 40%);
> 
> // replace darken
> - $grey-color-dark: darken($grey-color, 25%);
> + $grey-color-dark: color.adjust($grey-color, $lightness: -25%);
> ```
> 
> More info - https://sass-lang.com/d/color-functions

Worked For me. Thanks Soo much

**Comment by SourLemonJuice** [comment]
By the way, migration can be done with [sass-migrator](https://sass-lang.com/documentation/cli/migrator/)

**Comment by SourLemonJuice** [comment]
And SASS seems to want to preferably add a `$space: hsl` to `color.adjust()`

https://sass-lang.com/documentation/breaking-changes/color-functions/#single-channel-adjustment-functions

**Comment by humiliatedhuntsville45-sudo** [comment]
> ### Operating System
> Archlinux 6.10.10-arch1-1
> 
> ### Ruby Version
> ruby 3.2.5 (2024-07-26 revision 31d0f1a2e7) [x86_64-linux]
> 
> ### Jekyll Version
> jekyll 4.3.4
> 
> ### GitHub Pages Version
> _No response_
> 
> ### Expected Behavior
> I expected my website to be built successfully without any warning or error when I run `bundle exec jekyll serve`.
> 
> ### Current Behavior
> You can see that color statements, like `lighten()` and `darken()` in .scss files got deprecation warning. And I did `bundle update minima` but that's not work.
> 
> ### Relevant log output
> https://paste.rs/RQvhv.txt
> ### Code Sample
> _No response_

Great job lmaf
