### ISSUE TITLE
[Bug]: Some HTML whitespace breaks file include from .md page

### ISSUE THREAD

**Issue by fulldecent** [jekyll/jekyll#9691]
### Operating System

mac

### Ruby Version

ruby 3.1.3p185

### Jekyll Version

4.3.4

### GitHub Pages Version

Latest

### Expected Behavior

Including a _includes/something.html works regardless of whitespace conventions in that file

### Current Behavior

Certain whitespace which is insignificant to HTML breaks rendering

### Code Sample

# Input

Here the include a and b are equivalent. But there is a extra newline inside the strong tag in one of them.

```
grep -r .
./_includes/b.html:<strong>
./_includes/b.html:    Yo</strong
./_includes/b.html:>
./_includes/a.html:<strong>
./_includes/a.html:    Hi
./_includes/a.html:</strong>
./index.md:---
./index.md:---
./index.md:{% include a.html %}
./index.md:{% include b.html %}
./Gemfile:source 'https://rubygems.org'
./Gemfile:gem 'jekyll', '4.3.4'
```

# Broken output

See how one of them includes verbatim but the other html encodes it?

```sh
grep -r _site
./_site/index.html:<p><strong>
./_site/index.html:    Hi
./_site/index.html:</strong></p>
./_site/index.html:<p><strong>
./_site/index.html:    Yo&lt;/strong</strong></p>
./_site/index.html:<blockquote>
./_site/index.html:</blockquote>
```

# Notes

Please note that if a line of code is long, the Prettier tool will automatically and silently transform code between these two equivalent HTML representations.

**Comment by ashmaroli** [comment]
Hello @fulldecent
Technically, this is a *very edgy* edge-case.
Why would any procedure mutilating `<element>` into `<ele\nment>` be considered anything but a bug or a code-smell??

Secondly, have you tried rendering the same code outside an include_file? Jekyll's Markdown converter, [`kramdown`](https://github.com/gettalong/kramdown) is responsible for all generated HTML output. One known side-effect of using HTML in include_files is that kramdown will render all lines with an indentation of 4 or more spaces as code-blocks. (_Yes. Not applicable to your case_)

Regardless, if you can reproduce the bug using the same string outside include_file, I suggest reporting the distilled issue (reproducible with just plain kramdown, without any Jekyll involvement) at the `kramdown` repository linked above.

Thanks.

**Comment by fulldecent** [comment]
It is not mutilating to `<ele\nment>`, it is multilating to `<\nelement>` which is a valid HTML change.

This is a well-known technique in HTML to control whitespace (keep the `<` at the end of one line). It is the default behavior of Prettier. This is a very popular software, running [in many projects' workflows](https://github.com/search?q=prettier+path%3A.github%2Fworkflows%2F*&type=code).

---

Thank you for the notes, great I reported this upstream to https://github.com/gettalong/kramdown/issues/815

**Comment by fulldecent** [comment]
Here is one workaround specifically for people using Jekyll.

For example if you have an include:

```html
Bob
[ prettier adds a newline here at end ]
```

And you don't want that newline because you are including that in a Markdown file like this:

```md
Hello {% include name.html %}.
```

then you can work around with by using this whitespace killer:

```html
Bob
{%- comment -%}
{%- endcomment -%}
[ prettier adds a newline here at end ]
```
