### ISSUE TITLE
Jekyll not regenerating

### ISSUE THREAD

**Issue by spentacular** [jekyll/jekyll#970]
Hey Parker, here's my output:

``` text
Spencers-MacBook-Air:~ spentacular$ gem install jekyll
Fetching: liquid-2.5.0.gem (100%)
Successfully installed liquid-2.5.0
Fetching: classifier-1.3.3.gem (100%)
Successfully installed classifier-1.3.3
Fetching: directory_watcher-1.5.1.gem (100%)
Successfully installed directory_watcher-1.5.1
Fetching: maruku-0.6.1.gem (100%)
Successfully installed maruku-0.6.1
Fetching: jekyll-0.12.1.gem (100%)
Successfully installed jekyll-0.12.1
Parsing documentation for liquid-2.5.0
Installing ri documentation for liquid-2.5.0
Parsing documentation for classifier-1.3.3
Installing ri documentation for classifier-1.3.3
Parsing documentation for directory_watcher-1.5.1
Installing ri documentation for directory_watcher-1.5.1
Parsing documentation for maruku-0.6.1
Couldn't find file to include 'MaRuKu.txt' from lib/maruku.rb
Installing ri documentation for maruku-0.6.1
Parsing documentation for jekyll-0.12.1
Installing ri documentation for jekyll-0.12.1
5 gems installed
```

And when I start it:

``` text
Spencers-MacBook-Air:test spentacular$ jekyll --server --auto
Configuration from /Users/spentacular/projects/personal/test/_config.yml
Auto-regenerating enabled: /Users/spentacular/projects/personal/test -> /Users/spentacular/projects/personal/test/_site
[2013-04-14 10:22:18] regeneration: 1 files changed
[2013-04-14 10:22:19] INFO  WEBrick 1.3.1
[2013-04-14 10:22:19] INFO  ruby 2.0.0 (2013-02-24) [x86_64-darwin12.3.0]
[2013-04-14 10:22:19] INFO  WEBrick::HTTPServer#start: pid=24773 port=4000
[2013-04-14 10:22:19] regeneration: 1 files changed
[2013-04-14 10:22:19] regeneration: 1 files changed
[2013-04-14 10:22:19] regeneration: 1 files changed
```

I've been trying to change a css that's under stylesheets/app.css, and not luck with that.

**Comment by ricemidesign** [comment]
mingyans-mbp:portfolio mingyanmi$ jekyll serve --watch
Configuration file: /Users/mingyanmi/Desktop/portfolio/_config.yml
            Source: /Users/mingyanmi/Desktop/portfolio
       Destination: /Users/mingyanmi/Desktop/portfolio/_site
      Generating... 
                    done.
 Auto-regeneration: enabled for '/Users/mingyanmi/Desktop/portfolio'
Configuration file: /Users/mingyanmi/Desktop/portfolio/_config.yml
    Server address: http://127.0.0.1:3000/

I have the same issue....is it because my jekyll is not installed 100%?

**Comment by parkr** [comment]
@ricemidesign Check `exclude` in your config yml and make sure it doesn't contain any part of the filename you're having trouble with. if that is ok, run jekyll with the LISTEN_GEM_DEBUGGING=1 environment variable set. That should give you more information.

**Comment by ricemidesign** [comment]
thanks for replying!!

**Comment by SuryaChitrapu** [comment]
Hello, 
Jekyll is getting stuck at this point:

$ jekyll build
WARN: Unresolved specs during Gem::Specification.reset:
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: D:/doc_portal/documentation/_config.yml
            Source: D:/doc_portal/documentation
       Destination: D:/doc_portal/documentation/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 6.921 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

**Comment by SuryaChitrapu** [comment]
$ bundle exec jekyll serve
Configuration file: D:/doc_portal/documentation/_config.yml
            Source: D:/doc_portal/documentation
       Destination: D:/doc_portal/documentation/_site
      Generating...

**Comment by SuryaChitrapu** [comment]
The -site folder is getting built but no further...the portal doesn't get generated. I cleared browser cookies, did bundle install - but the issue persists. Can someone help, please?

**Comment by parkr** [comment]
@SuryaChitrapu Please open up a new issue with the logs from running `bundle exec jekyll serve --verbose`. Thanks!
