### ISSUE TITLE
[Bug]: LiveReload with ignore globs (still) does not work

### ISSUE THREAD

**Issue by Cnly** [jekyll/jekyll#9712]
### Operating System

macOS 15.0.1

### Ruby Version

ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]

### Jekyll Version

jekyll 4.3.4

### Expected Behavior

When using live reload with the `--livereload-ignore` option, no error should be produced

### Current Behavior

This is an attempt to reopen a still existing but closed bug report: https://github.com/jekyll/jekyll/issues/8550 so I'm using the original description. This still happens on v4.3.4.

When supplying the `--livereload-ignore` option, the server complains as follows:

```
Error: wrong number of arguments (given 1, expected 2)
```

According to the original issue:

> The problem is on the following line:
>
> https://github.com/jekyll/jekyll/blob/4.1-stable/lib/jekyll/commands/serve.rb#L163
>
> `Jekyll.sanitized_path` takes two arguments, but only one is given.

**Comment by ashmaroli** [comment]
@Cnly, this has already been fixed on the `master` branch and will ship as part of v4.4.0.

If you desire to use the patch right away, you may point your Gemfile to this repository's `master` branch:

```ruby
# Gemfile

gem 'jekyll', github: 'jekyll/jekyll', branch: 'master'
```

Happy Jekyllin'!
