### ISSUE TITLE
`Jekyll new` command should warn if overwriting existing files

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll#981]
What I did:
1. Make folder called `test-site`
2. Add `index.html` or `_config.yml` file with "important content" to `test-site` folder
3. Execute `jekyll new test-site`

What I expected:
- A big red warning telling me I'm about to :boom: my files

What I saw:
- Files were :skull:

**Comment by andersonweb** [comment]
@parkr thanks you! It was very helpful

**Comment by popmix** [comment]
Pls add something like "--force    Force installation to existing directory. WARNING! existing jekyll files may be overwritten!" to Jekyll Usage Options section (when just typing "jekyll" in command prompt), otherwise there is no information about such flag.

**Comment by envygeeks** [comment]
Please file a new ticket instead of requesting features inside of an already resolved ticket. Thanks!
